### ISSUE TITLE
Can Fresco download multiple images?

### ISSUE THREAD

**Issue by Evequal** [facebook/fresco#1001]
Hi,

I need to download multiple images in background and display one of the images to user, when user taps on the image, I need to load a new image in the same drawee view and I wanted to be image that is already downloaded, so user do not need to wait.

So, is Fresco capable of downloading multiple images?

**Comment by IanChilds** [comment]
Yes, please see the docs: http://frescolib.org/docs/requesting-multiple-images.html#_

**Comment by Evequal** [comment]
I saw that, but that is only for 2 images, thumb and full size, as far as I get it.

I have 10 images and I want to download them to folder. 

Is that possible?

**Comment by IanChilds** [comment]
You can just create image requests for each one, how about that? http://frescolib.org/docs/using-image-pipeline.html#_
