### ISSUE TITLE
How to get preview image from AnimatedDrawable

### ISSUE THREAD

**Issue by ChenSiLiang** [facebook/fresco#1002]
I use the code to get a `AnimatedDrawable`

``` java
if (image instanceof CloseableAnimatedImage) {
            AnimatedImageResult img = ((CloseableAnimatedImage) image).getImageResult();
            AnimatedDrawableFactory animatedDrawableFactory = Fresco.getImagePipelineFactory().getAnimatedDrawableFactory();
            if (animatedDrawableFactory != null) {
                AnimatedDrawableOptions options = new AnimatedDrawableOptionsBuilder().setForceKeepAllFramesInMemory(true).setAllowPrefetching(true).build();
                AnimatedDrawable animatedDrawable = animatedDrawableFactory.create(img, options);
                if (animatedDrawable != null) {
                    return animatedDrawable;
                }
            }
```

and I want to get a preview image for this `AnimatedDrawable`
I try `renderFrame()` but did not work
hope reply soon!

**Comment by aagnes** [comment]
Can you use drawee for hosting the animated image? If you .setAutoPlayAnimations(false), it will only take the first frame as preview image.

**Comment by ChenSiLiang** [comment]
Sorry,I cant use drawee to do that.I use `RecycleView` to load local images containing JPG,GIF,PNG.
When to show a big image,I need a scale function and I can't do this with drawee.
So,I use
```java
DataSource<CloseableReference<CloseableImage>> dataSource =
                    Fresco.getImagePipeline().fetchDecodedImage(request, null);
            dataSource.subscribe(new BaseDataSubscriber<CloseableReference<CloseableImage>>(){
 @Override
                protected void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                    CloseableReference<CloseableImage> result = dataSource.getResult();
}
```
I get a `CloseableImage` object and I can get `CloseableStaticBitmap`,`CloseableAnimatedImage`.
When It comes to a very big gif,`CloseableAnimatedImage.start()` when lead to OOM!

> https://github.com/facebook/fresco/issues/159

**Comment by tbruceyu** [comment]
You can get the preview bitmap with this call CloseableAnimatedImage.getImageResult().getPreviewBitmap(). But we need to enable decode preview option in the ImageRequestBuilder.
`
                ImageRequestBuilder imageRequestBuilder =
                    ImageRequestBuilder.newBuilderWithSource(uri);
                imageRequestBuilder.setImageDecodeOptions(ImageDecodeOptions.newBuilder()
                        .setDecodePreviewFrame(true).build());
`

**Comment by ChenSiLiang** [comment]
@tbruceyu yep!It works.Thanks.I still hope to solve the big gif problem. the issue as  #159

**Comment by tbruceyu** [comment]
@ChenSiLiang Yeah. Fresco not support Gif downsample so far. We could only wait for the official solution.

**Comment by ChenSiLiang** [comment]
@tbruceyu thanks

**Comment by ChenSiLiang** [comment]
It pretty hard to get a preview for a gif with drawee and OOM.
I use `AnimatedImageFrame.renderFrame(AnimatedImage.getWidth(),AnimatedImage.getHeight(),Bitmap)` to draw a bitmap for the preview frame.
But I got this Exception
```java
 java.lang.IllegalStateException: Width or height is too small
at com.facebook.imagepipeline.gif.GifFrame.nativeRenderFrame(Native Method)
at com.facebook.imagepipeline.gif.GifFrame.renderFrame(GifFrame.java:52)
```

**Comment by tbruceyu** [comment]
I think you can try to change the source of Fresco. Make gif images decoded as CloseableStaticBitmap. Disable the animation producing.
