### ISSUE TITLE
how to config fresco proguard?

### ISSUE THREAD

**Issue by Ly-cc** [facebook/fresco#1003]
Error:Execution failed for task ':DDF:transformClassesAndResourcesWithProguardForOem0001Release'.
> java.io.IOException: Please correct the above warnings first.

**Comment by Ly-cc** [comment]
# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

# Keep native methods
-keepclassmembers class * {
    native <methods>;
}

-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn com.android.volley.toolbox.**

**Comment by IanChilds** [comment]
Please see the docs: http://frescolib.org/docs/proguard.html#_
