### ISSUE TITLE
GridView blinks after notifyDataSetChanged get called

### ISSUE THREAD

**Issue by QiuSean** [facebook/fresco#1004]
GridView item blinks after selected item notifyDataSetChanged get called

**Comment by IanChilds** [comment]
Please can you give more details, otherwise there is no way that we are able to help you.

**Comment by QiuSean** [comment]
@IanChilds thanks for you, I found reason, because default memory cache size small, bitmap cache recycle seem has bug

**Comment by JakeWang123** [comment]
I already make memory cache size big but the blink still exist. How to solve this!

**Comment by JakeWang123** [comment]
Thanks for you. I already fix the blink by using view tag!

**Comment by fxhereng** [comment]
I'm having the same problem with blinking images when some changing are made. I'm using viewHolders with tags.

@QiuSean , @jabagawee , How do you make memory cache size bigger?

EDIT: on destroying activity or fragment view, I'm doing:
```java 
 @Override
    public void onDestroyView() {
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        imagePipeline.clearCaches();
        super.onDestroyView();
    }
```

it seems to have solve the problem
