### ISSUE TITLE
How to skip the blank placeholder for GIF

### ISSUE THREAD

**Issue by robinsking** [facebook/fresco#1006]
I loaded a local res image to SimpleDraweeView, and set the placeholder image also as this local res image. And then I try to load a GIF to SimpleDraweeView, it will show blank placeholder before the GIF. Is there any way to skip this blank placeholder image? Thanks a lot.

 `          Uri uri = Uri.parse("res://com.kinstalk.cookielauncher/" + mAnimResId);

            GenericDraweeHierarchy hierarchy = mAnimationView.getHierarchy();

            hierarchy.setPlaceholderImage(mStaticResId);

            DraweeController controller = Fresco.newDraweeControllerBuilder()

                .setUri(uri)

                .setAutoPlayAnimations(true)

                .setOldController(mAnimationView.getController())

                .build();

            mAnimationView.setController(controller);`

**Comment by IanChilds** [comment]
So you're not seeing your placeholder at all? Sounds like it's not resolving to the resource correctly, are you setting something valid? 

For example, if you do `hierarchy.setPlaceholderImage(new ColorDrawable(Color.BLUE)`, does that show up correctly? If it does, then it's definitely a problem with your resource.
