### ISSUE TITLE
Running sample project in As met Error:Execution failed for task ':imagepipeline:ndk_clean_gifimage'.

### ISSUE THREAD

**Issue by honghuiqing326** [facebook/fresco#101]
Error:Execution failed for task ':imagepipeline:ndk_clean_gifimage'.
> A problem occurred starting process 'command 'ndk-build''

**Comment by tyronen** [comment]
Can you try it again from the latest head?

**Comment by michalgr** [comment]
We do know that :imagepipeline:clean fails if there is nothing to clean in imagepipeline subproject. I'll fix that.

**Comment by ljnalex** [comment]
@honghuiqing326 Do you have the same problem when execute 'gradle build'? if you have，try to add ’ndk.path=D\:\\android-ndk-r10d‘ in gradle.properties

**Comment by xingxiang1989** [comment]
ndk.dir=/Users/xiangxing/ndk2/android-ndk-r10d   add this ，and it doesn't work

**Comment by michalgr** [comment]
fix for ndk_clean_* specific failures is now in master
