### ISSUE TITLE
Allow to disable crossfade

### ISSUE THREAD

**Issue by AlexBlokh** [facebook/fresco#1011]
When crossfading `placeholder` and `downloaded image` - both images changes alpha channel from `0..1` and from `1..0` 
TransitionDrawable has an option `.setCrossFadeEnabled(boolean enabled);`
This option will lead to a smoother transition between `placeholder drawable (colour drawable)` and `downloaded drawable`
it should be done in `FadeDrawable.class`

**Comment by aagnes** [comment]
I don't understand what you mean? Is that a question or a feature you want fresco library to have?

**Comment by AlexBlokh** [comment]
![zqfl8](https://cloud.githubusercontent.com/assets/4045375/13280267/348ad4cc-dadd-11e5-9f66-a3e3d761138c.gif)
on the left - transition with crossfade, on the right - without

**Comment by aagnes** [comment]
It would be great if you want to contribute and have a pull request after.

**Comment by AlexBlokh** [comment]
got it

**Comment by AlexBlokh** [comment]
spent half a day and still can't build the project :O

**Comment by plamenko** [comment]
Instead of `placeholderImage`, sat the `backgroundImage` to black.
