### ISSUE TITLE
Image doesn't decode

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#1014]
I am loading image from local path, image is available in particular path but its not shown in SDV if i am getting below log 

```
D/skia: --- decoder->decode returned false
D/skia: --- decoder->decode returned false
```

 I am getting this log multiple times, i am setting image from adapter

**Comment by karun2189** [comment]
Detailed log
D/skia: --- decoder->decode returned false
D/skia: --- decoder->decode returned false
W/unknown:RequestLoggingListener: time 1744951128: onProducerFinishWithFailure: {requestId: 84, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: java.lang.IllegalArgumentException}
W/unknown:RequestLoggingListener: time 1744951128: onRequestFailure: {requestId: 84, elapsedTime: -1 ms, throwable: java.lang.IllegalArgumentException}
D/skia: --- decoder->decode returned false
 D/skia: --- decoder->decode returned false
W/unknown:RequestLoggingListener: time 1744953544: onProducerFinishWithFailure: {requestId: 101, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: java.lang.IllegalArgumentException}
W/unknown:RequestLoggingListener: time 1744953545: onRequestFailure: {requestId: 101, elapsedTime: -1 ms, throwable: java.lang.IllegalArgumentException}

**Comment by aagnes** [comment]
Can you provide more details how you use the SDV. What url of image are you using? It's quite obvious the request of image is not successful so you won't see the image there. But need to understand why.

**Comment by karun2189** [comment]
I am using my SDV in list adapter, I am creating a bitmap and stored in to SDCard then i am accessing that image via 

`simpleDraweeView.setImageURI(Uri.fromFile(new File(mPath)));`

please refer this link
[http://stackoverflow.com/questions/35605269/android-fresco-image-is-not-display-in-simpledraweeview-if-set-to-the-same-uri](url)

**Comment by aagnes** [comment]
I don't see issue you use SDV. Do you have a valid file path? You can debug and see what returns from Uri.fromFile(new File(mPath)).

**Comment by karun2189** [comment]
Ya i am having valid path. I am verifying that image is available in that path, and Uri.fromFile(new File(mPath)) return exact path only. Whats wrong?

**Comment by michalgr** [comment]
What is the format of the image ? Is it one of the formats recognized by BitmapFactory ? http://developer.android.com/guide/appendix/media-formats.html

**Comment by karun2189** [comment]
I am using .PNG image format.

**Comment by michalgr** [comment]
Are you able to decode that particular image with BitmapFactory ?

**Comment by karun2189** [comment]
ya i am able to decode it

**Comment by tyronen** [comment]
Can you upload the image itself here so we can take a look?

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
