### ISSUE TITLE
Can I use the ashmem heap on Android 5.0 or upper?

### ISSUE THREAD

**Issue by zoneoflkf** [facebook/fresco#1016]
Because  OOM   occured on some  Android5.0 ROM with 2GB RAM, so if it does, I would try to use ashmem heap on Android 5.0. Please tell me how to do?

**Comment by aagnes** [comment]
Well, from 5.0, Android don't have ashmem. So we won't be able to use ashmem as well. You can try to see if you have memory leak or do a resize option for your jpeg image to help oom happening.

**Comment by zoneoflkf** [comment]
thanks for your help, I' ll  check my code.
