### ISSUE TITLE
Setting setProgressiveRenderingEnabled false does not work.

### ISSUE THREAD

**Issue by HildaChen** [facebook/fresco#1017]
I want to remove the progressive rendering effect of jpg image. So I set ProgressiveRenderingEnabled false. I find the effect still appears.
public ImageRequest buildImageRequest() {
        ImageRequest request;
        if (mUri != null) {
            request = ImageRequestBuilder.newBuilderWithSource(mUri).setAutoRotateEnabled(mIsAutoRotateEnabled)
                    .setResizeOptions(mResizeOptions).setProgressiveRenderingEnabled(false).build();
        } else {
            request = ImageRequestBuilder.newBuilderWithResourceId(mResourceId)
                    .setAutoRotateEnabled(mIsAutoRotateEnabled).setResizeOptions(mResizeOptions).setProgressiveRenderingEnabled(false).build();
        }
        return request;
    }

**Comment by HildaChen** [comment]
I use version 0.8.1

**Comment by aagnes** [comment]
I feel this is weird because setProgressiveRenderingEnabled is default to false. And I don't see any issues when digging into source code. Can you debug yourself and see the value?

**Comment by HildaChen** [comment]
this is my code, 
`public class FrescoView<DH extends DraweeHierarchy> extends View {
    private GenericDraweeHierarchy mHierarchy;
    private DraweeHolder<DH> mDraweeHolder;
    private boolean mInitialised = false;
    private int mDrawableWidth;
    private int mDrawableHeight;
    private Drawable mDrawable;
    private Matrix mDrawMatrix = null;
    private ImageView.ScaleType mScaleType;
    private Matrix mMatrix;
    private RectF mTempSrc = new RectF();
    private RectF mTempDst = new RectF();
    private boolean mIsDownload = false;
    private IFDrawableCallback mDrawableCallback;
    private Context mContext;

    public static void initQView(Context context, boolean isLowMemoryDevice) {
        FrescoImagePipeline.initialize(context, isLowMemoryDevice);
    }

    public FrescoView(Context context) {
        super(context);
        init(context);
    }


    public FrescoView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    public FrescoView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
    }

    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    public FrescoView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
        init(context);
    }

    private void init(Context context) {
        if (!mInitialised) {
            mHierarchy = new GenericDraweeHierarchyBuilder(getResources()).build();
            mDraweeHolder = (DraweeHolder<DH>) DraweeHolder.create(mHierarchy, context);
            mInitialised = true;
            mContext = context;
        }
        mIsDownload = false;
    }


    public DH getHierarchy() {
        return mDraweeHolder.getHierarchy();
    }

    @Override
    public void onStartTemporaryDetach() {
        super.onStartTemporaryDetach();
        mDraweeHolder.onDetach();
    }

    @Override
    public void onFinishTemporaryDetach() {
        super.onFinishTemporaryDetach();
        mDraweeHolder.onAttach();
    }

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        mDraweeHolder.onAttach();
    }

    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        mDraweeHolder.onDetach();
    }

    @SuppressLint("ClickableViewAccessibility")
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        return mDraweeHolder.onTouchEvent(event) || super.onTouchEvent(event);
    }

    @Override
    protected boolean verifyDrawable(Drawable who) {
        super.verifyDrawable(who);
        if (who == mDraweeHolder.getTopLevelDrawable()) {
            return true;
        }
        return false;
    }

    public void setDrawableCallback(IFDrawableCallback callback) {
        mDrawableCallback = callback;
        mIsDownload = false;
    }

    public void releaseDrawableCallback() {
        mDrawableCallback = null;
        mIsDownload = false;
    }

    public void setImageRequest(FImageRequest fImageRequest) {
        FLog.data("isDownload=" + mIsDownload);
        if (fImageRequest != null) {
            int id = fImageRequest.getPlaceHolderResourceId();
            if (id != 0) {
                mHierarchy.setPlaceholderImage(id);
            }
            RoundingParams rp = fImageRequest.buildRoundingParams();
            ImageRequest request = fImageRequest.buildImageRequest();
            FLog.data("ProgressiveRenderingEnabled="+request.getProgressiveRenderingEnabled()); // this echo false;
            mHierarchy.setRoundingParams(rp);
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setImageRequest(request).setOldController(mDraweeHolder.getController())
                    .setControllerListener(new ControllerListener<ImageInfo>() {
                        @Override
                        public void onSubmit(String id, Object callerContext) {
                            FLog.data("onSubmit id=" + id);
                        }

                        @Override
                        public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                            FLog.data("onFinalImageSet id=" + id);
                            Drawable drawable = mDraweeHolder.getHierarchy().getTopLevelDrawable();

                            final int oldWidth = mDrawableWidth;
                            final int oldHeight = mDrawableHeight;
                            mDrawable = drawable;
                            updateDrawable(mDrawable);

                            if (oldWidth != mDrawableWidth || oldHeight != mDrawableHeight) {
                                requestLayout();
                            }
                            FHttpExecutor.getHttpExecutor().execute(new Runnable() {
                                @Override
                                public void run() {
                                    if (!mIsDownload && mDrawableCallback != null) {
                                        mDrawableCallback.onSuccess(mDrawable);
                                    }
                                }
                            });
                            mIsDownload = true;
                        }

                        @Override
                        public void onIntermediateImageSet(String id, ImageInfo imageInfo) {
                        }

                        @Override
                        public void onIntermediateImageFailed(String id, Throwable throwable) {
                        }

                        @Override
                        public void onFailure(String id, Throwable throwable) {
                            FLog.data("onFailure id=" + id);
                            FHttpExecutor.getHttpExecutor().execute(new Runnable() {
                                @Override
                                public void run() {
                                    if (mDrawableCallback != null) {
                                        mDrawableCallback.onFailed();
                                    }
                                }
                            });
                        }

                        @Override
                        public void onRelease(String id) {
                            FLog.data("onRelease id=" + id);
                            FHttpExecutor.getHttpExecutor().execute(new Runnable() {
                                @Override
                                public void run() {
                                    if (mDrawableCallback != null) {
                                        mDrawableCallback.onRelease();
                                    }
                                }
                            });
                        }
                    })
                    .build();
            mDraweeHolder.setController(controller);
        }
    }

    @SuppressLint("NewApi")
    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        /*
        Drawable drawable = mDraweeHolder.getHierarchy().getTopLevelDrawable();

        final int oldWidth = mDrawableWidth;
        final int oldHeight = mDrawableHeight;
        mDrawable = drawable;
        updateDrawable(mDrawable);

        if (oldWidth != mDrawableWidth || oldHeight != mDrawableHeight) {
            requestLayout();
        }

        if (mDrawable != null && !mIsDownload && mDrawableCallbacks.size() > 0) {
            for (IFDrawableCallback callback : mDrawableCallbacks) {
                callback.onSuccess(mDrawable);
                mIsDownload = true;
            }
        }*/
        //mDrawable.draw(canvas);
    }

    public Drawable getDrawable() {
        return mDrawable;
    }

    private void updateDrawable(Drawable d) {
        if (d != null) {
            d.setCallback(this);
            if (d.isStateful()) {
                d.setState(getDrawableState());
            }
            d.setVisible(getVisibility() == VISIBLE, true);
            mDrawableWidth = d.getIntrinsicWidth();
            mDrawableHeight = d.getIntrinsicHeight();
            configureBounds();
        } else {
            mDrawableWidth = mDrawableHeight = -1;
        }
    }

    private void configureBounds() {
        if (mDrawable == null) {
            return;
        }

        int dwidth = mDrawableWidth;
        int dheight = mDrawableHeight;
        int vwidth = getWidth() - getPaddingLeft() - getPaddingRight();
        int vheight = getHeight() - getPaddingTop() - getPaddingBottom();

        boolean fits = (dwidth < 0 || vwidth == dwidth) &&
                (dheight < 0 || vheight == dheight);

        if (dwidth <= 0 || dheight <= 0 || ImageView.ScaleType.FIT_XY == mScaleType) {
            mDrawable.setBounds(0, 0, vwidth, vheight);
            mDrawMatrix = null;
        } else {
            mDrawable.setBounds(0, 0, dwidth, dheight);
            if (ImageView.ScaleType.MATRIX == mScaleType) {
                if (mMatrix.isIdentity()) {
                    mDrawMatrix = null;
                } else {
                    mDrawMatrix = mMatrix;
                }
            } else if (fits) {
                mDrawMatrix = null;
            } else if (ImageView.ScaleType.CENTER == mScaleType) {
                mDrawMatrix = mMatrix;
                mDrawMatrix.setTranslate((int) ((vwidth - dwidth) * 0.5f + 0.5f),
                        (int) ((vheight - dheight) * 0.5f + 0.5f));
            } else if (ImageView.ScaleType.CENTER_CROP == mScaleType) {
                mDrawMatrix = mMatrix;
                float scale;
                float dx = 0, dy = 0;

                if (dwidth * vheight > vwidth * dheight) {
                    scale = (float) vheight / (float) dheight;
                    dx = (vwidth - dwidth * scale) * 0.5f;
                } else {
                    scale = (float) vwidth / (float) dwidth;
                    dy = (vheight - dheight * scale) * 0.5f;
                }

                mDrawMatrix.setScale(scale, scale);
                mDrawMatrix.postTranslate((int) (dx + 0.5f), (int) (dy + 0.5f));
            } else if (ImageView.ScaleType.CENTER_INSIDE == mScaleType) {
                mDrawMatrix = mMatrix;
                float scale;
                float dx;
                float dy;

                if (dwidth <= vwidth && dheight <= vheight) {
                    scale = 1.0f;
                } else {
                    scale = Math.min((float) vwidth / (float) dwidth,
                            (float) vheight / (float) dheight);
                }

                dx = (int) ((vwidth - dwidth * scale) * 0.5f + 0.5f);
                dy = (int) ((vheight - dheight * scale) * 0.5f + 0.5f);

                mDrawMatrix.setScale(scale, scale);
                mDrawMatrix.postTranslate(dx, dy);
            } else {
                mTempSrc.set(0, 0, dwidth, dheight);
                mTempDst.set(0, 0, vwidth, vheight);
                mDrawMatrix = mMatrix;
                mDrawMatrix.setRectToRect(mTempSrc, mTempDst, scaleTypeToScaleToFit(mScaleType));
            }
        }
    }

    private static final Matrix.ScaleToFit[] sS2FArray = {
            Matrix.ScaleToFit.FILL,
            Matrix.ScaleToFit.START,
            Matrix.ScaleToFit.CENTER,
            Matrix.ScaleToFit.END
    };

    private static Matrix.ScaleToFit scaleTypeToScaleToFit(ImageView.ScaleType st) {
        return sS2FArray[st.ordinal() - 1];
    }
}
`

**Comment by HildaChen** [comment]
I have found the solution of the problem. Because I rebuild the NetworkFetcher and return true in shouldPropagate(FETCH_STATE fetchState);

**Comment by HildaChen** [comment]
Sorry, I found the solution does not work.

**Comment by HildaChen** [comment]
DecodeProducer .class code is below
`@Override
  public void produceResults(
      final Consumer<CloseableReference<CloseableImage>> consumer,
      final ProducerContext producerContext) {
    final ImageRequest imageRequest = producerContext.getImageRequest();
    ProgressiveDecoder progressiveDecoder;
    if (!UriUtil.isNetworkUri(imageRequest.getSourceUri())) {
      progressiveDecoder = new LocalImagesProgressiveDecoder(consumer, producerContext);
    } else {
      ProgressiveJpegParser jpegParser = new ProgressiveJpegParser(mByteArrayPool);
      progressiveDecoder = new NetworkImagesProgressiveDecoder(
          consumer,
          producerContext,
          jpegParser,
          mProgressiveJpegConfig);
    }
    mInputProducer.produceResults(progressiveDecoder, producerContext);
  }`
Are you sure that there judges whether isProgressiveRenderingEnabled from ImageRequest?

**Comment by erikandre** [comment]
Closing issue due to lack of updates (2 years stale)
