### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Couldn't load jpush173

### ISSUE THREAD

**Issue by RocLiuYC** [facebook/fresco#1018]
When i add compile 'com.facebook.fresco:fresco:0.9.0+' in build.gradle, in debug model, app run error :java.lang.UnsatisfiedLinkError: Couldn't load jpush173 from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xx.apk"],nativeLibraryDirectories=[xx, /vendor/lib, /system/lib]]]: findLibrary returned null

**Comment by aagnes** [comment]
What device and os are you using? This should be a device specific issue. You may also want to try using other Fresco version.

**Comment by RocLiuYC** [comment]
I use the smartisan phone, but i dont think it is a device issue.

When i remove the 'com.facebook.fresco:fresco:0.9.0+' in build.gradle, the jpush.so can be used in apk file.

**Comment by Runpop** [comment]
see #410

**Comment by RocLiuYC** [comment]
@Runpop thx

**Comment by michalgr** [comment]
Are you using armv8 (64bit) device by any chance ? Is jpush173 compiled for armv8 or armv7 ? Can you list content of lib directory in your apk ?

**Comment by aagnes** [comment]
merge into #410
