### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1891]:   174 could not load needed library 'libwebp.so' for 'libimagepipeline.so' (load_library[1093]: Library 'libwebp.so' not found)

### ISSUE THREAD

**Issue by yang747046912** [facebook/fresco#1019]
when id use ImageRequest to load a local  and then crash like this 

02-25 18:58:15.813: E/AndroidRuntime(8756): FATAL EXCEPTION: Thread-481
02-25 18:58:15.813: E/AndroidRuntime(8756): java.lang.ExceptionInInitializerError
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at java.lang.Thread.run(Thread.java:856)
02-25 18:58:15.813: E/AndroidRuntime(8756): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1891]:   174 could not load needed library 'libwebp.so' for 'libimagepipeline.so' (load_library[1093]: Library 'libwebp.so' not found)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at java.lang.Runtime.loadLibrary(Runtime.java:370)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at java.lang.System.loadLibrary(System.java:535)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
02-25 18:58:15.813: E/AndroidRuntime(8756): 	... 10 more

**Comment by aagnes** [comment]
please continue the thread in #410
