### ISSUE TITLE
solve the problem of compile failed in windows

### ISSUE THREAD

**Issue by guqun** [facebook/fresco#102]
the main problem is to compile native code. i modify some configuration files and compile success.
1）in \fresco\imagepipeline\build.gradle, Modify four places:
i）def makeNdkTasks(String name) {
    task "ndk_build_$name"(type: Exec) {
        inputs.file("src/main/jni/$name")
        outputs.dir("$buildDir/$name")
        commandLine getNdkBuildCommand(),
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_PROJECT_PATH=Android.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            '--jobs', '8'
    }

    ii）task "ndk_clean_$name"(type: Exec) {
        commandLine getNdkBuildCommand(),
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            'clean',
            'NDK_PROJECT_PATH=Android.mk'
    }
iii）def getNdkBuildCommand() {
    // we allow to provide full path to ndk-build tool
    if (hasProperty('ndk.command')) {
        return property('ndk.command')
    }
    // or just a path to the containing directiry
    if (hasProperty('ndk.path')) {
        def path = property('ndk.path')
        if (!path.endsWith(File.separator)) {
            path += File.separator
        }
        return path + 'ndk-build.cmd'
    }
    // if none of above is provided, we assume ndk-build is already in $PATH
    return 'C:\\android-dev\\android-ndk-r10d\\ndk-build.cmd'
}
iv)    task "ndk_clean_$name"(type: Exec) {
        commandLine getNdkBuildCommand(),
            'NDK_APPLICATION_MK=../Application.mk',
            'NDK_OUT=' + temporaryDir,
            "NDK_LIBS_OUT=$buildDir/$name",
            '-C', file("src/main/jni/$name").absolutePath,
            'clean',
            'NDK_PROJECT_PATH=Android.mk'
    }
2)in fresco\imagepipeline\src\main\jni\Application.mk, modify one place.
NDK_MODULE_PATH := $(APP_MK_DIR)../../../build/nativemerge

the last, i suggest to run gradlew.bat in cmd.

**Comment by tyronen** [comment]
Code doing something similar is now in master.

**Comment by niesen1990** [comment]
still problem
