### ISSUE TITLE
How could I free memory in this situation?

### ISSUE THREAD

**Issue by zoneoflkf** [facebook/fresco#1020]
A activity start B activity, and B activity start C activiy and so on...
(the activity task may be looked like this: A->B->C->D->E ...)
every activity has a recyclerView with some loaded images . I found that after several times jump, the memory cost accumulated and would not be free timely, then an OOM might happen. 
So could I do someThing to solve this problem, or how could I free the memory initiatively ?
I'd try to  use "Fresco.getImagePipeline().clearMemoryCaches()"  but it seems that the memory usage didn't decreased obviously.

**Comment by aagnes** [comment]
you'll need override public void onLowMemory() { Fresco.getImagePipeline().clearCaches(); }. Register MemoryTrimmableRegistry for handling memory for activity. You also need to check if you have a memory leak issue in your app.

**Comment by zoneoflkf** [comment]
Thank you, I‘ll try again.

**Comment by zhuAria** [comment]
@zoneoflkf  How did you deal with, can share

**Comment by zoneoflkf** [comment]
@zhuAria just follow @aagnes 's advance. Call "Fresco.getImagePipeline().clearCaches()" in onLowMemory()  and onTrimMemory(). And do a resize for every image.
it can avoid most of OOM.

**Comment by zhuAria** [comment]
hank you for your reply @aagnes
