### ISSUE TITLE
roundAsCircle does not apply when if a SimpleDraweeView is contained in a extended FrameLayout such as SwipeLayout

### ISSUE THREAD

**Issue by redmouth** [facebook/fresco#1023]
If a com.facebook.drawee.view.SimpleDraweeView is added in a SwipeLayout container, set fresco:roundAsCircle="true" won't work. What's the problem? Is it necessary to add SwipeLayout manually?

https://cloud.githubusercontent.com/assets/1421702/6934310/6529630e-d800-11e4-9f24-ec93e398de88.png

**Comment by aagnes** [comment]
This sounds like a bug somewhere in Android. Can you share the code how you use two views together.

**Comment by redmouth** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.paic.zhifu.wallet.activity.control.widget.swipe.SwipeLayout
        xmlns:swipe="http://schemas.android.com/apk/res-auto"
        android:id="@+id/swipe"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        swipe:leftEdgeSwipeOffset="0dp"
        swipe:rightEdgeSwipeOffset="0dp"
        swipe:clickToClose="true">

        <LinearLayout
            android:id="@+id/delete"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:background="#FF5534"
            android:gravity="center"
            android:tag="Bottom3">

            <ImageView
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:src="@drawable/trash" />
        </LinearLayout>

        <LinearLayout
            android:id="@+id/layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/white"
            android:gravity="center_vertical"
            android:orientation="horizontal" >

            <RelativeLayout
                android:layout_width="44dp"
                android:layout_height="44dp">

                <com.facebook.drawee.view.SimpleDraweeView
                    android:id="@+id/image_head"
                    android:layout_width="44dp"
                    android:layout_height="44dp"
                    android:layout_alignParentBottom="true"
                    android:layout_alignParentLeft="true"
                    app:actualImageScaleType="fitCenter"
                    app:placeholderImageScaleType="fitCenter"
                    app:roundAsCircle="true"
                    app:roundWithOverlayColor="@color/white" />

                <ImageView
                    android:id="@+id/image_status"
                    android:layout_width="10dp"
                    android:layout_height="10dp"
                    android:layout_alignParentRight="true"
                    android:layout_alignParentTop="true"
                    android:visibility="gone" />
            </RelativeLayout>

            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="10dp"
                android:layout_marginRight="20dp"
                android:gravity="center_vertical"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/txt_name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:ellipsize="end"
                    android:singleLine="true"
                    android:textColor="#353535"
                    android:textSize="14sp" />

                <TextView
                    android:id="@+id/txt"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="2dp"
                    android:textColor="#6d6d6d"
                    android:textSize="12sp" />
            </LinearLayout>
        </LinearLayout>
    </com.paic.zhifu.wallet.activity.control.widget.swipe.SwipeLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1px" />
</LinearLayout>

**Comment by redmouth** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <SwipeLayout
        xmlns:swipe="http://schemas.android.com/apk/res-auto"
        android:id="@+id/swipe"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        swipe:leftEdgeSwipeOffset="0dp"
        swipe:rightEdgeSwipeOffset="0dp"
        swipe:clickToClose="true">

        <LinearLayout
            android:id="@+id/delete"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:background="#FF5534"
            android:gravity="center"
            android:tag="Bottom3">

            <ImageView
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:src="@drawable/trash" />
        </LinearLayout>

        <LinearLayout
            android:id="@+id/layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/white"
            android:gravity="center_vertical"
            android:orientation="horizontal" >

            <RelativeLayout
                android:layout_width="44dp"
                android:layout_height="44dp">

                <com.facebook.drawee.view.SimpleDraweeView
                    android:id="@+id/image_head"
                    android:layout_width="44dp"
                    android:layout_height="44dp"
                    android:layout_alignParentBottom="true"
                    android:layout_alignParentLeft="true"
                    app:actualImageScaleType="fitCenter"
                    app:placeholderImageScaleType="fitCenter"
                    app:roundAsCircle="true"
                    app:roundWithOverlayColor="@color/white" />

                <ImageView
                    android:id="@+id/image_status"
                    android:layout_width="10dp"
                    android:layout_height="10dp"
                    android:layout_alignParentRight="true"
                    android:layout_alignParentTop="true"
                    android:visibility="gone" />
            </RelativeLayout>

            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="10dp"
                android:layout_marginRight="20dp"
                android:gravity="center_vertical"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/txt_name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:ellipsize="end"
                    android:singleLine="true"
                    android:textColor="#353535"
                    android:textSize="14sp" />

                <TextView
                    android:id="@+id/txt"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="2dp"
                    android:textColor="#6d6d6d"
                    android:textSize="12sp" />
            </LinearLayout>
        </LinearLayout>
    </SwipeLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1px" />
</LinearLayout>

**Comment by aagnes** [comment]
We'll investigate

**Comment by demjoey** [comment]
I was suffering from a same kind of problem, but in my case it was caused by Android Studio adding the xmlns wrong scheme `xmlns:fresco="http://schemas.android.com/tools"` instead of the correct one which is `xmlns:fresco="http://schemas.android.com/apk/res-auto"`. It just compiled fine though, but the roundAsCircle wasn't applied with the wrong scheme. Also I use the tag `fresco:roundAsCircle="true"` instead of the tag `app:roundAsCircle="true"` as shown in the answer of @redmouth above

**Comment by HannahCarney** [comment]
Thanks @joeywp I couldn't understand why it wasn't working - this was my problem too!!

**Comment by oprisnik** [comment]
Looks like fixing the scheme should resolve the problem, thanks @joeywp
