### ISSUE TITLE
How can i save bitmap to BitmapMemoryCache ?

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#1024]
I am refer the below link
 [https://github.com/facebook/fresco/issues/705](url)

They are telling about this method `Fresco.getImagePipelineFactory().getBitmapMemoryCache().cache( cacheKey, `closeableReference`).`

How can i create the `closeableReference` here ? thanks for advance

**Comment by aagnes** [comment]
you can use CloseableReference.of()
