### ISSUE TITLE
How to use Fresco to fit screen?

### ISSUE THREAD

**Issue by leveychen** [facebook/fresco#1026]
In `Android-Universal-Image-Loader`,I can use the layout to fit screen width and wrap content height in listview. But it doesn‘t work in `fresco`.
What can I do?
````java
<ImageView
        android:id="@+id/image_item"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:scaleType="fitCenter"/>
````

**Comment by HomHomLin** [comment]
Fresco doesn't allow you to use "wrap_content" in your View,  it will make your View couldn't visible ,you should specify your DraweeView a specific  size or use "match_parent".
Also, I have make a Library which can easy use: <https://github.com/HomHomLin/FrescoImageView>

**Comment by michalgr** [comment]
Please have a look here for an explanation why `wrap_content` is not supported: http://frescolib.org/docs/wrap-content.html

**Comment by dnhyde** [comment]
http://frescolib.org/docs/wrap-content.html
link is broken.

Any hints on how to achieve the fit screen non programmatically?
