### ISSUE TITLE
The bug with setting “roundingBorderWidth”

### ISSUE THREAD

**Issue by cyzxyz** [facebook/fresco#1027]
In the xml file , I edit the code like this:

```
    <com.facebook.drawee.view.SimpleDraweeView
        android:layout_width="80dp"
        android:layout_height="80dp"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="6dp"
        android:layout_marginLeft="12dp"
        fresco:placeholderImage="@drawable/drawable_u"
        fresco:placeholderImageScaleType="centerCrop"
        fresco:roundingBorderWidth="3dp"
        fresco:roundingBorderColor="@android:color/white"
        fresco:roundAsCircle="true"
        />
```

but it shows as the follow picture

![screenshot_2016-02-29-17-03-18](https://cloud.githubusercontent.com/assets/6849142/13390040/a6b2fcdc-df06-11e5-8b8e-4c05b7a0f0c6.png)

there is a circle line around this view

as I change the placeholderImage , it show like this

![screenshot_2016-02-29-16-56-06](https://cloud.githubusercontent.com/assets/6849142/13390063/d8c0a698-df06-11e5-9033-ea675379570b.png)

But when I change the roundingBorderWidth to 0dp, the link will disappear.

I think is that the border can't fill with all this view.

My english is not very good ....but,can what i wrote be understood?

**Comment by michalgr** [comment]
Could you please explain what you mean by "link will disappear" ? Is this issue about part of the image being rendered outside of the border ?

**Comment by cyzxyz** [comment]
@michalgr  yes ! It is just like what you say!

**Comment by plamenko** [comment]
I don't really understand the issue. The screenshot looks correct to me. If this tiny gray circle around the border is what bothers you, just add `fresco:roundingBorderPadding="1dp"`.
If you specify border width to be 0dp, border won't be drawn at all, and this is expected too.

**Comment by cyzxyz** [comment]
@plamenko after adding the  fresco:roundingBorderPadding="1dp"  , this tiny gray circle around the border disappear

but I think , this issue about part of the image being rendered outside of the border  . As I change the placeholderImage, the color of circle around the border will  be changed .

**Comment by oprisnik** [comment]
As explained by @plamenko, you should either set no border or add border padding.
If there is a different bug, please post a screenshot that highlights the issue and we can re-open this. Closing for now.

**Comment by twlkyao** [comment]
What bothers us is why borderWidth make the gray circle, it seems like the pic is leak out.
