### ISSUE TITLE
How to download image only?

### ISSUE THREAD

**Issue by leveychen** [facebook/fresco#1029]
I just want to download a image in backgroud without use a SimpleDraweeView, and save this image to disk when it download success.
What should I do?

**Comment by eldk** [comment]
Hello,

You should look here : http://frescolib.org/docs/using-image-pipeline.html

and check : imagePipeline.prefetchToDiskCache(imageRequest, callerContext);

Eric

**Comment by michalgr** [comment]
Thanks @eldk.

**Comment by leveychen** [comment]
Thank you, I go it
