### ISSUE TITLE
webp not work on device not support webp

### ISSUE THREAD

**Issue by caojianfeng** [facebook/fresco#1034]
[DraweeDemo.zip](https://github.com/facebook/fresco/files/156595/DraweeDemo.zip)

This demo work well on an android4.3 device like this one
![work_well_device](https://cloud.githubusercontent.com/assets/11853564/13492398/c2bb0ffa-e172-11e5-9243-794d04c63b7e.png)

but not work on  an android4.1 device like this one 
![not_work_device](https://cloud.githubusercontent.com/assets/11853564/13492414/d1d1ed1a-e172-11e5-8b0e-cf382bcbdd7c.png)

**Comment by eldk** [comment]
Hello,
Should you try to use :
` compile 'com.facebook.fresco:fresco:0.9.0+' 
  compile 'com.facebook.fresco:webpsupport:0.9.0+' `
in your app build.gradle

Then disable `.setWebpSupportEnabled(true)` in your ImagePipeline config.

and set a resize option in your ImageRequest

`ImageRequest request = ImageRequestBuilder
                    .newBuilderWithSource(urlImage)
                    .setResizeOptions(new ResizeOptions(2048, 2048))
                    .build();`

Finally, check that http://zhitu.isux.us/assets/img/imgWebp/IMG20160303/75/20160303175820-ORuxL4cu11.webp is ok. I can't get to preview it in chromium or chrome. I have a 200 answer from Apache2 but nothing shown (image is downloaded as if there was a mismatch on apache2 files extension handlers)

Thanks,

Eric

PS : https://github.com/facebook/fresco/issues/917

**Comment by caojianfeng** [comment]
Thank u very much! It`s work now! 
The "normal webp" shown well.
But the larg webp still not shown.This is an other bug :https://github.com/facebook/fresco/issues/743

**Comment by caojianfeng** [comment]
Its very strange that     setWebpSupportEnabled(true)  make webp not work ,and       setWebpSupportEnabled(false) make it work!
