### ISSUE TITLE
image flashes when GPU rendering is not enforced

### ISSUE THREAD

**Issue by AllenVork** [facebook/fresco#1035]
i turned off the "enforce GPU rendering" and use fresco to load image
the image flashes and got black frame when loading circle image

**Comment by aagnes** [comment]
@AllenVork, any reason why you want to turn off the "enforce GPU rendering"? From 4.0, the "Force GPU rendering" option is vestigial and it's already the default.

**Comment by AllenVork** [comment]
My project uses Fresco to load image instead of picasso. But some users encoutered such problem when showing circle image.Picasso hasn't such problem so i wonder whether you could fix it.

**Comment by wankey** [comment]
i got the problem similarly when I set `android:hardwareAccelerated="false"`  in AndroidManifest

**Comment by oprisnik** [comment]
Using a overlay color for rounding should be a workaround for this, see http://frescolib.org/docs/rounded-corners-and-circles.html

The question still remains why you are disabling GPU rendering in the first place?

**Comment by wsychina** [comment]
I encountered with the same issue, however I set android:hardwareAccelerated="true" in AndroidManifest.

**Comment by erikandre** [comment]
Closing as a workaround was suggested. Forcefully disabling hardware acceleration is usually not a good idea.
