### ISSUE TITLE
Scale type "none" not handled properly

### ISSUE THREAD

**Issue by bejibx** [facebook/fresco#1036]
Hi, I'm trying to use ["none" scale type](http://frescolib.org/docs/scaling.html#none) but actual scale type I've got is "center crop". It seems "none" scale type not being handled properly.

To obtain scale type from xml [getScaleTypeFromXml(TypedArray, int, ScalingUtils.ScaleType)](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/drawee/src/main/java/com/facebook/drawee/view/GenericDraweeView.java#L352) method is used. Third parameter of this method is scale type used "by default", i.e. if int value obtained from xml lower than zero, which is true for "none" scale type, see [actualImageScaleType enum attribute](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/drawee/src/main/res/values/attrs.xml#L79)):
```xml
<!-- Scale type of the actual image. -->
    <attr name="actualImageScaleType">
      <enum name="none" value="-1" />
      <enum name="fitXY" value="0" />
      <enum name="fitStart" value="1" />
      <enum name="fitCenter" value="2" />
      <enum name="fitEnd" value="3" />
      <enum name="center" value="4" />
      <enum name="centerInside" value="5" />
      <enum name="centerCrop" value="6" />
      <enum name="focusCrop" value="7" />
    </attr>
```
This method is used from [inflateHierarchy(Context, AttributeSet)](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/drawee/src/main/java/com/facebook/drawee/view/GenericDraweeView.java#L140) method like this:
```java
actualImageScaleType = getScaleTypeFromXml(
                gdhAttrs,
                R.styleable.GenericDraweeView_actualImageScaleType,
                actualImageScaleType);
```
`actualImageScaleType` variable is being initialized [a little earlier](ScalingUtils.ScaleType actualImageScaleType =
        GenericDraweeHierarchyBuilder.DEFAULT_ACTUAL_IMAGE_SCALE_TYPE;) this way:
```java
ScalingUtils.ScaleType actualImageScaleType =
        GenericDraweeHierarchyBuilder.DEFAULT_ACTUAL_IMAGE_SCALE_TYPE;
```
And finally `GenericDraweeHierarchyBuilder.DEFAULT_ACTUAL_IMAGE_SCALE_TYPE` initialization:
```java
public static final ScaleType DEFAULT_ACTUAL_IMAGE_SCALE_TYPE = ScaleType.CENTER_CROP;
```
So it seems when we using "none" scale type, actual scale type is "center crop".

Am I missing something?

**Comment by plamenko** [comment]
Yes, that used to be a bug, but I believe this has been fixed recently. I am not sure If we released the version with the fix yet. What is the Fresco version you use?

**Comment by plamenko** [comment]
Yeah, this has been fixed internally, but the code has not yet been pushed to GitHub.

**Comment by bejibx** [comment]
Ok, can't wait for fix to be pushed! Thank you for responding.

**Comment by bejibx** [comment]
Any update when to expect new version?

**Comment by oprisnik** [comment]
Very soon, stay tuned!

**Comment by bejibx** [comment]
Good to hear this!
