### ISSUE TITLE
How to override hash method for file name in disk cache?

### ISSUE THREAD

**Issue by dochathuc** [facebook/fresco#1039]
Hi,
I am considering to change my own image loader lib by the fresco lib? But I wonder 2 things which I did not see on the documents:
- I am working in a telco company which release a ott app (chat app). We have a policy for users to free 3g when using this app. We do this by support a extra url for loading image. 
        Example: origin url        https://www.abc.com/photos/image1.jpg
                        free 3g url     https://www.f-abc.com/photos/image1.jpg
        so when I create file name for caching the image to disk, I remove the host url. Final file name is hash("photos/image1.jpg").
    How can I do that with the fresco lib? Does Fresco support override method for this?

- Animated images (gif, webp) can be run one time? It means when I click on, it will run one time and then stop.

Thanks in advance,
Thuc.

**Comment by plamenko** [comment]
Yes, fresco does support both things.

* CacheKey: You need to provide a custom `CacheKeyFactory` while initializing `Fresco`. You can just extend the [DefaultCacheKeyFactory](https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/imagepipeline/src/main/java/com/facebook/imagepipeline/cache/DefaultCacheKeyFactory.java) and override `getEncodedCacheKey`. There you can build a cache key from the normalize uri ("photos/image1.jpg").

* Animations: You can specify a `ControllerListener` that will notify you once the image is loaded. The `onFinalImageSet` callback provides `Animatable` which can be started/stopped at your convenience.

**Comment by dochathuc** [comment]
thanks
