### ISSUE TITLE
simpledraweeview neither call failure nor success when loading image on Samsung galaxy note 5

### ISSUE THREAD

**Issue by chyi13** [facebook/fresco#1041]
Hi, 
 I am using simpledraweeview(Fresco 0.9.0) with viewpager. It works well on many devices except the samsung galaxy note 5(Android version 5.1.1). The situation is, turn off internet connection when the viewpager loads the first two images, then swipe to the third image which has not loaded the image. The simpledraweeview does not show anything(black page, failure image has been set). Neither onFailure() nor onFinalImageSet() is called. Thx.

**Comment by chyi13** [comment]
only the third view does not work. The onRelease() method of that view is called without showing the failure image.

**Comment by plamenko** [comment]
If `onRelease` has been called, it means DraweeView for some reason thinks it's not visible. Can you please provide the logcat logs as explained [here](http://frescolib.org/docs/troubleshooting.html#_)?

**Comment by chyi13** [comment]
**1.start a viewpager and instantiate the first two simpledraweeview**
03-10 10:39:04.541 27355-27355/? V/unknown:AbstractDraweeController: controller 17ed5c75 null -> 0: initialize
03-10 10:39:04.551 27355-27355/? V/unknown:AbstractDraweeController: controller 17ed5c75 0: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@19df647b
03-10 10:39:04.551 27355-27355/? V/unknown:AbstractDraweeController: controller 17ed5c75 0: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@6dd7298
03-10 10:39:04.551 27355-27355/? V/unknown:AbstractDraweeController: controller 17ed5c75 0: onAttach: request needs submit
03-10 10:39:04.551 27355-27355/? V/unknown:RequestLoggingListener: time 264804415: onRequestSubmit: {requestId: 0, callerContext: null, isPrefetch: false}
03-10 10:39:04.551 27355-27355/? V/unknown:RequestLoggingListener: time 264804416: onProducerStart: {requestId: 0, producer: BitmapMemoryCacheGetProducer}
03-10 10:39:04.551 27355-27355/? V/unknown:RequestLoggingListener: time 264804416: onProducerFinishWithSuccess: {requestId: 0, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.551 27355-27355/? V/unknown:RequestLoggingListener: time 264804417: onProducerStart: {requestId: 0, producer: BackgroundThreadHandoffProducer}
03-10 10:39:04.551 27355-27355/? V/unknown:AbstractDraweeController: controller 17ed5c75 0: submitRequest: dataSource: fcf86d6
03-10 10:39:04.551 27355-27373/? V/unknown:RequestLoggingListener: time 264804417: onProducerFinishWithSuccess: {requestId: 0, producer: BackgroundThreadHandoffProducer, elapsedTime: 0 ms, extraMap: null}
03-10 10:39:04.551 27355-27355/? V/unknown:AbstractDraweeController: controller 15f5cd57 null -> 1: initialize
03-10 10:39:04.551 27355-27373/? V/unknown:RequestLoggingListener: time 264804418: onProducerStart: {requestId: 0, producer: BitmapMemoryCacheProducer}
03-10 10:39:04.551 27355-27373/? V/unknown:RequestLoggingListener: time 264804418: onProducerFinishWithSuccess: {requestId: 0, producer: BitmapMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804419: onProducerStart: {requestId: 0, producer: EncodedMemoryCacheProducer}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804420: onProducerFinishWithSuccess: {requestId: 0, producer: EncodedMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804420: onProducerStart: {requestId: 0, producer: DiskCacheProducer}
03-10 10:39:04.561 27355-27374/? V/unknown:BufferedDiskCache: Did not find image for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_1638043c5df9796cf83e87880108887b.jpg in staging area
03-10 10:39:04.561 27355-27374/? V/unknown:BufferedDiskCache: Disk cache read for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_1638043c5df9796cf83e87880108887b.jpg
03-10 10:39:04.561 27355-27355/? V/unknown:AbstractDraweeController: controller 15f5cd57 1: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@e109aae
03-10 10:39:04.561 27355-27355/? V/unknown:AbstractDraweeController: controller 15f5cd57 1: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@1cc7104f
03-10 10:39:04.561 27355-27355/? V/unknown:AbstractDraweeController: controller 15f5cd57 1: onAttach: request needs submit
03-10 10:39:04.561 27355-27355/? V/unknown:RequestLoggingListener: time 264804426: onRequestSubmit: {requestId: 1, callerContext: null, isPrefetch: false}
03-10 10:39:04.561 27355-27355/? V/unknown:RequestLoggingListener: time 264804426: onProducerStart: {requestId: 1, producer: BitmapMemoryCacheGetProducer}
03-10 10:39:04.561 27355-27355/? V/unknown:RequestLoggingListener: time 264804426: onProducerFinishWithSuccess: {requestId: 1, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.561 27355-27355/? V/unknown:RequestLoggingListener: time 264804426: onProducerStart: {requestId: 1, producer: BackgroundThreadHandoffProducer}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804426: onProducerFinishWithSuccess: {requestId: 1, producer: BackgroundThreadHandoffProducer, elapsedTime: 0 ms, extraMap: null}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804426: onProducerStart: {requestId: 1, producer: BitmapMemoryCacheProducer}
03-10 10:39:04.561 27355-27355/? V/unknown:AbstractDraweeController: controller 15f5cd57 1: submitRequest: dataSource: 13d433dc
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804426: onProducerFinishWithSuccess: {requestId: 1, producer: BitmapMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804426: onProducerStart: {requestId: 1, producer: EncodedMemoryCacheProducer}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804426: onProducerFinishWithSuccess: {requestId: 1, producer: EncodedMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.561 27355-27373/? V/unknown:RequestLoggingListener: time 264804426: onProducerStart: {requestId: 1, producer: DiskCacheProducer}
03-10 10:39:04.561 27355-27375/? V/unknown:BufferedDiskCache: Did not find image for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_9b1781b17b50473f827c45d5410dd41e.jpg in staging area
03-10 10:39:04.561 27355-27375/? V/unknown:BufferedDiskCache: Disk cache read for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_9b1781b17b50473f827c45d5410dd41e.jpg
03-10 10:39:04.571 27355-27374/? V/unknown:BufferedDiskCache: Disk cache miss for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_1638043c5df9796cf83e87880108887b.jpg
03-10 10:39:04.571 27355-27375/? V/unknown:BufferedDiskCache: Disk cache miss for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_9b1781b17b50473f827c45d5410dd41e.jpg
03-10 10:39:04.571 27355-27375/? V/unknown:RequestLoggingListener: time 264804430: onProducerFinishWithSuccess: {requestId: 1, producer: DiskCacheProducer, elapsedTime: 4 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.571 27355-27374/? V/unknown:RequestLoggingListener: time 264804430: onProducerFinishWithSuccess: {requestId: 0, producer: DiskCacheProducer, elapsedTime: 10 ms, extraMap: {cached_value_found=false}}
03-10 10:39:04.571 27355-27374/? V/unknown:RequestLoggingListener: time 264804430: onProducerStart: {requestId: 0, producer: NetworkFetchProducer}
03-10 10:39:04.571 27355-27375/? V/unknown:RequestLoggingListener: time 264804431: onProducerStart: {requestId: 1, producer: NetworkFetchProducer}
03-10 10:39:04.631 27355-27377/? V/unknown:RequestLoggingListener: time 264804491: onProducerEvent: {requestId: 0, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 61 ms}
03-10 10:39:04.761 27355-27377/? V/unknown:RequestLoggingListener: time 264804620: onProducerEvent: {requestId: 0, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 190 ms}
03-10 10:39:04.791 27355-27376/? V/unknown:RequestLoggingListener: time 264804658: onProducerEvent: {requestId: 1, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 227 ms}
03-10 10:39:05.361 27355-27376/? V/unknown:RequestLoggingListener: time 264805220: onProducerEvent: {requestId: 1, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 789 ms}
03-10 10:39:05.391 27355-27377/? V/unknown:RequestLoggingListener: time 264805245: onProducerEvent: {requestId: 0, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 815 ms}
03-10 10:39:06.141 27355-27377/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806006: onProducerEvent: {requestId: 0, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 1576 ms}
03-10 10:39:06.161 27355-27377/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806025: onProducerFinishWithSuccess: {requestId: 0, producer: NetworkFetchProducer, elapsedTime: 1595 ms, extraMap: null}
03-10 10:39:06.171 27355-27374/com.android.cy.fresco_test V/unknown:BufferedDiskCache: About to write to disk-cache for key http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_1638043c5df9796cf83e87880108887b.jpg
03-10 10:39:06.181 27355-27456/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806044: onProducerStart: {requestId: 0, producer: DecodeProducer}
03-10 10:39:06.181 27355-27374/com.android.cy.fresco_test V/unknown:BufferedDiskCache: Successful disk-cache write for key http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_1638043c5df9796cf83e87880108887b.jpg
03-10 10:39:06.211 27355-27456/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806068: onProducerFinishWithSuccess: {requestId: 0, producer: DecodeProducer, elapsedTime: 24 ms, extraMap: {queueTime=8, imageType=DEFAULT, hasGoodQuality=true, bitmapSize=410x266, isFinal=true}}
03-10 10:39:06.211 27355-27456/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806072: onRequestSuccess: {requestId: 0, elapsedTime: 1657 ms}
03-10 10:39:06.221 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 17ed5c75 0: set_final_result @ onNewResult: image: CloseableReference 374921c5
03-10 10:39:06.931 27355-27376/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806797: onProducerEvent: {requestId: 1, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 2366 ms}
03-10 10:39:06.951 27355-27376/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806812: onProducerFinishWithSuccess: {requestId: 1, producer: NetworkFetchProducer, elapsedTime: 2381 ms, extraMap: null}
03-10 10:39:06.951 27355-27505/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806813: onProducerStart: {requestId: 1, producer: DecodeProducer}
03-10 10:39:06.951 27355-27375/com.android.cy.fresco_test V/unknown:BufferedDiskCache: About to write to disk-cache for key http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_9b1781b17b50473f827c45d5410dd41e.jpg
03-10 10:39:06.951 27355-27375/com.android.cy.fresco_test V/unknown:BufferedDiskCache: Successful disk-cache write for key http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_9b1781b17b50473f827c45d5410dd41e.jpg
03-10 10:39:06.961 27355-27505/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806828: onProducerFinishWithSuccess: {requestId: 1, producer: DecodeProducer, elapsedTime: 15 ms, extraMap: {queueTime=4, imageType=DEFAULT, hasGoodQuality=true, bitmapSize=410x266, isFinal=false}}
03-10 10:39:06.971 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 15f5cd57 1: set_intermediate_result @ onNewResult: image: CloseableReference 706e827
03-10 10:39:07.051 27355-27507/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806918: onProducerStart: {requestId: 1, producer: DecodeProducer}
03-10 10:39:07.091 27355-27507/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806955: onProducerFinishWithSuccess: {requestId: 1, producer: DecodeProducer, elapsedTime: 37 ms, extraMap: {queueTime=89, imageType=DEFAULT, hasGoodQuality=true, bitmapSize=410x266, isFinal=true}}
03-10 10:39:07.091 27355-27507/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264806956: onRequestSuccess: {requestId: 1, elapsedTime: 2530 ms}
03-10 10:39:07.091 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 15f5cd57 1: set_final_result @ onNewResult: image: CloseableReference 2defdfc3
03-10 10:39:07.101 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 15f5cd57 1: release_previous_result @ onNewResult: image: CloseableReference 706e827

**Comment by chyi13** [comment]
**2. off network and swipe quickly to the third view**
03-10 10:39:16.301 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 17ed5c75 0: onTouchEvent MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=1011.0, y[0]=1497.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=169206813, downTime=169206813, deviceId=3, source=0x1002 }
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 3921e040 null -> 2: initialize
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 3921e040 2: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@17402b79
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 3921e040 2: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@c2790be
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 3921e040 2: onAttach: request needs submit
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onRequestSubmit: {requestId: 2, callerContext: null, isPrefetch: false}
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerStart: {requestId: 2, producer: BitmapMemoryCacheGetProducer}
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerFinishWithSuccess: {requestId: 2, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerStart: {requestId: 2, producer: BackgroundThreadHandoffProducer}
03-10 10:39:16.581 27355-27373/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerFinishWithSuccess: {requestId: 2, producer: BackgroundThreadHandoffProducer, elapsedTime: 0 ms, extraMap: null}
03-10 10:39:16.581 27355-27373/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerStart: {requestId: 2, producer: BitmapMemoryCacheProducer}
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 3921e040 2: submitRequest: dataSource: 2be6b51f
03-10 10:39:16.581 27355-27373/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerFinishWithSuccess: {requestId: 2, producer: BitmapMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:16.581 27355-27373/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerStart: {requestId: 2, producer: EncodedMemoryCacheProducer}
03-10 10:39:16.581 27355-27373/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerFinishWithSuccess: {requestId: 2, producer: EncodedMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
03-10 10:39:16.581 27355-27373/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816446: onProducerStart: {requestId: 2, producer: DiskCacheProducer}
03-10 10:39:16.581 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 15f5cd57 1: onTouchEvent MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=988.0, y[0]=1494.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=169207094, downTime=169207094, deviceId=3, source=0x1002 }
03-10 10:39:16.581 27355-27374/com.android.cy.fresco_test V/unknown:BufferedDiskCache: Did not find image for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_e5a9c13a873efcdcbfe55328e523ce54.jpg in staging area
03-10 10:39:16.581 27355-27374/com.android.cy.fresco_test V/unknown:BufferedDiskCache: Disk cache read for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_e5a9c13a873efcdcbfe55328e523ce54.jpg
03-10 10:39:16.581 27355-27374/com.android.cy.fresco_test V/unknown:BufferedDiskCache: Disk cache miss for http://u.thsi.cn/fileupload/data/Flashcms/2016/119075179_e5a9c13a873efcdcbfe55328e523ce54.jpg
03-10 10:39:16.581 27355-27374/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816448: onProducerFinishWithSuccess: {requestId: 2, producer: DiskCacheProducer, elapsedTime: 2 ms, extraMap: {cached_value_found=false}}
03-10 10:39:16.581 27355-27374/com.android.cy.fresco_test V/unknown:RequestLoggingListener: time 264816448: onProducerStart: {requestId: 2, producer: NetworkFetchProducer}
03-10 10:39:17.051 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 17ed5c75 0: onDetach
03-10 10:39:17.051 27355-27355/com.android.cy.fresco_test V/unknown:AbstractDraweeController: controller 17ed5c75 0: release: image: CloseableReference 374921c5

**Comment by tyronen** [comment]
The sequence of events shows that the controller is detached very soon, before the request to network has even gone out. Fresco is told that the controller is detached, so it cancels the network request. 

The weird thing is why the controller gets detached when it is actually on-screen. This might be an issue with the ViewPager code itself, at least on this device.

`onDetach` is called from either `View.onStartTemporaryDetach` or `View.detachFromWindow`. For whatever reason one of these is being called. If you can set a breakpoint to them in your debugger and find when one of them is called on the SDV, that would give you a clue.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
