### ISSUE TITLE
anr occurred but i`m not sure it is fresco`s bug

### ISSUE THREAD

**Issue by yychai** [facebook/fresco#1042]
#anr occurred many times on my app, and in the traces log said something about fresco, please help me  analyze it .look traces log at [ https://github.com/yychai/outOfProject/blob/master/traces.txt](url)

**Comment by gnehsuy** [comment]
刚想用这个框架，请问图片缓存怎么整？

**Comment by plamenko** [comment]
I cannot open the link with the logs. Can you attach the txt file here on github?

**Comment by yychai** [comment]
I'm sorry,and now I put the traces.txt log on [https://github.com/yychai/outOfProject/blob/master/traces.txt](url),
something said about fresco between line170 and line190. please look at it thank you very much.
