### ISSUE TITLE
Call back when image loads/doesnt load.

### ISSUE THREAD

**Issue by sahana-tib** [facebook/fresco#1044]
How to get callbacks if the image loads and fails to load?

**Comment by plamenko** [comment]
http://frescolib.org/docs/listening-download-events.html#_

**Comment by younas-bangash** [comment]
@plamenko the link is not found I did not know why you did not provide the call back

**Comment by lambdapioneer** [comment]
You can register a `ControllerListener` and react in the `onFailure` method. See http://frescolib.org/docs/listening-to-events.html
