### ISSUE TITLE
Cannot Load image without type as JPG, PNG

### ISSUE THREAD

**Issue by khangpv202** [facebook/fresco#1046]
it seem not load image which don't have type format like : https://placekitten.com/g/201/300
i use this link with universal ImageLoader and Picaso, it work. how could i resolve this?

**Comment by massimocarli** [comment]
I've tested the URL with our demo app and everything works. What's the code you're using to show it?

Thanks

**Comment by khangpv202** [comment]
thanks for reply. 
in xml, i create a layout like this: 
 <com.facebook.drawee.view.SimpleDraweeView
            android:layout_width="150dp"
            android:layout_height="150dp"
            android:scaleType="centerInside"
            android:id="@+id/sdvRegisterEntry" />
and i my Activity: 
onCreate: 
SimpleDraweeView simpleDraweeView = (SimpleDraweeView) findViewById(R.id.sdvRegisterEntry);
Uri uri = Uri.parse("https://placekitten.com/g/201/300");
simpleDraweeView.setImageURI(uri);
can u show me what's my wrong. @massimocarli

**Comment by tyronen** [comment]
Please follow the "Investigating issues with logcat" section of the [troubleshooting page](http://frescolib.org/docs/troubleshooting.html) and paste the log output here.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
