### ISSUE TITLE
Image is stretched When I set fresco:roundAsCircle="true"and fresco:actualImageScaleType="center"

### ISSUE THREAD

**Issue by qiuqiutang** [facebook/fresco#1048]
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/ivImage"
                android:layout_width="@dimen/px120"
                android:layout_height="@dimen/px120"
                fresco:roundAsCircle="true"
                fresco:actualImageScaleType="center"/>
when I set  fresco:roundAsCircle="false" and fresco:actualImageScaleType="center" ,It's OK.
and fresco:roundAsCircle="true" and fresco:actualImageScaleType="none", It's also OK.
only when I set fresco:roundAsCircle="true" and fresco:actualImageScaleType="centerInside" Or "Center",the Image is Stretched.

**Comment by massimocarli** [comment]
Thanks @qiuqiutang,
we'll make some investigation.

**Comment by aagnes** [comment]
@qiuqiutang, can you please provide the url and link of your image so we can get access to it?

**Comment by qiuqiutang** [comment]
@aagnes ,my image url is http://cdn2.55haitao.com/bbs/data/attachment/store/new/20150624084033.jpg

**Comment by plamenko** [comment]
This is a known limitation as explained in the [documentation](http://frescolib.org/docs/rounded-corners-and-circles.html).
