### ISSUE TITLE
Stop downloads based on the Content-Length header

### ISSUE THREAD

**Issue by kit678** [facebook/fresco#1053]
Android/fresco/general programming noob reporting.
I am working with an 'aggregator' application which sources images from various sites. The images are not being stored on our servers, instead we purely rely on the 'urls' coming from xml/csv/json feeds coming from these websites. 
Fresco is awesome thus far. Only that it jitters while scrolling up and down in a grid view. The most probable reason for that I suspect is the large size of some of the images. 

Is there any remote possibility of stopping the downloads based on the content-length header, so that beyond a threshold size of an image, that download/image is just skipped?

I know about the download listeners, but not sure if its going to be of help here. 

I have my control listener as follows :

```
ControllerListener controllerListener = new BaseControllerListener<ImageInfo>() {
			@Override
			public void onFinalImageSet(
					String id,
					@Nullable ImageInfo imageInfo,
					@Nullable Animatable anim) {
				if (imageInfo == null) {
					return;
				}

				holder.feedImage.setAspectRatio((float) imageInfo.getWidth() / imageInfo.getHeight());
			}

			@Override 
			public void onIntermediateImageSet(String id, @Nullable ImageInfo imageInfo) {

				holder.feedImage.setAspectRatio((float) imageInfo.getWidth() / imageInfo.getHeight());
			}

			@Override
			public void onFailure(String id, Throwable throwable) {

			}
		};
```

Can I somehow put a check inside the 'onIntermediateImageSet' ? Am I in the right direction? 
Much thanks.

**Comment by massimocarli** [comment]
The onIntermediateImageSet() is not so accurate and is relative to all the pipeline process. The feature you're requesting is a feature of the Network layer and can be probably done at that level. http://frescolib.org/docs/using-other-network-layers.html#using-your-own-network-fetcher-optional
