### ISSUE TITLE
Animation control

### ISSUE THREAD

**Issue by atkdev** [facebook/fresco#1060]
1. How to get animation current frame? 
2. How to set current animation frame position or time?

**Comment by massimocarli** [comment]
To manage animation you should check this [code](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/animated/base/AnimatedDrawableBackend.java) and in general what's in the java.com.facebook.imagepipeline.animated.base packages. We'll provide more documentation on that.

Thanks
