### ISSUE TITLE
Get image size

### ISSUE THREAD

**Issue by rpopovici** [facebook/fresco#1061]
Hello guys,
Is there any way to get the original image size based on uri, for a cached image?
Thanks!

**Comment by massimocarli** [comment]
When we load an image we also put it into the cache. If the image has some ResizeOptions we put also the resized image into the cache with different key. In your case you should fetch the image without resizeOptions and query its size on the Bitmap object. Obviously if the image is very big (greater that 2048x2048) there might be some problems. Hope this answers.

**Comment by erikandre** [comment]
Closing as the suggested solution seems to cover the use case, and further comment was made.
