### ISSUE TITLE
use SimpleDraweeView in popupwindow can not display

### ISSUE THREAD

**Issue by qindachang** [facebook/fresco#1063]
I use SimpleDraweeView in poppupwindow and use this method 'setImageURI' before 'new PopupWindow' .however, it can not display img in phone.
But , the button can call back onclick method before  'new PopupWindow' .

**Comment by massimocarli** [comment]
Thank you @qindachang,
we'll investigate the use case.

**Comment by oprisnik** [comment]
I don't really understand the issue here. Could you give us a minimal example that shows how to reproduce the issue? (for example by modifying the Showcase sample app in GitHub).

I'll re-open once we have more details
