### ISSUE TITLE
NPE invoking com.facebook.drawee.backends.pipeline.d

### ISSUE THREAD

**Issue by leeon7** [facebook/fresco#1065]
java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.drawee.backends.pipeline.d com.facebook.drawee.backends.pipeline.e.a()' on a null object reference
    at com.facebook.drawee.backends.pipeline.b.b(Fresco.java:54)
    at com.chemao.car.adapter.FindcarListAdapter.getView(FindcarListAdapter.java:196)
    at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
    at android.widget.AbsListView.obtainView(AbsListView.java:2847)
    at android.widget.ListView.makeAndAddView(ListView.java:1903)
    at android.widget.ListView.fillDown(ListView.java:713)
    at android.widget.ListView.fillGap(ListView.java:677)
...

I got many of this, any help?

**Comment by massimocarli** [comment]
The log doesn't say too much. Can you provide please the code you're using into your ListView?
Thanks

**Comment by leeon7** [comment]
here it is, thx
***
@Override public 
View getView(final int position, View convertView, ViewGroup parent) {     
ViewHolder viewHolder;     
if (convertView == null) {
 Fresco.initialize(mContext.getApplicationContext(),ImagePipelineConfigFactory.getOkHttpImagePipelineConfig(mContext.getApplicationContext()));         
convertView = mInflater.inflate(R.layout.item_car, null);         
viewHolder = new ViewHolder();         
viewHolder.sdv_car = (SimpleDraweeView) convertView.findViewById(R.id.sdv_car);        
 ...         
convertView.setTag(viewHolder);    
 } else {         
viewHolder = (ViewHolder) convertView.getTag();     }
    ...     
viewHolder.sdv_car.setImageURI(Uri.parse(url));     
return convertView;
 }

**Comment by massimocarli** [comment]
Hi,
for sure you have to initialize Fresco just ones so this code should not be in the getView() method.
`
Fresco.initialize(mContext.getApplicationContext(),ImagePipelineConfigFactory.getOkHttpImagePipelineConfig(mContext.getApplicationContext())); `
 I suggest you to give a look to our sample application [here](https://github.com/facebook/fresco/tree/master/samples) on how to use Fresco into a ListView o RecyclerView.

Thanks

**Comment by leeon7** [comment]
thanks, i have looked into the sample before and what confused me is that when should i call "Fresco.shutdown()"? I found only by calling this can i release the memory in my app so i invoked it many places. It's also the reason i had to initialize many times....

**Comment by massimocarli** [comment]
Hi @leeon7,
Actually Fresco.shutdown() should stop all services, executors and clean stuff in order to release resources. At the moment it's just clearing memory caches. We're going to improve this but i think this should be invoked, if you want, when the application stops and so on the onDestroy() of the main Activity. Thanks

**Comment by leeon7** [comment]
Alright, I see. But also, i need to confirm one thing, invoking shutdown `is not required` for Fresco to release memory automatically, is it right?  If so, i can conclude i was doing something else wrong result to a memory leaking.

**Comment by erikandre** [comment]
Closing old issues
