### ISSUE TITLE
why can't show image from https?

### ISSUE THREAD

**Issue by ronhunlam** [facebook/fresco#1066]
Uri uri = Uri.parse("https://c2.staticflickr.com/4/3933/18823211329_10ccbb55e3_o.jpg");
SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.draw);
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setProgressiveRenderingEnabled(true)
                .build();
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
                .setTapToRetryEnabled(true)
                .setOldController(draweeView.getController())
                .build();
        draweeView.setController(controller);

**Comment by stevenchans** [comment]
。。。

**Comment by eldk** [comment]
Hello,

As image is huge (>4096), I think you should resize (image request) and eventually down-sample it (image pipeline).

http://frescolib.org/docs/resizing-rotating.html#_

Thanks,

Eric

**Comment by massimocarli** [comment]
Yes, as @eldk said the image is too big. You should use ResizeOptions to resize it.
Thanks

**Comment by DaGeTian** [comment]
Hello, my image is very small.
https://s3.amazonaws.com/xopr/advt1.jpg
I code like ronhunlam. but code is not working. what is wrong?
I initialised as follow this.
Fresco.initialize(this);


SimpleDraweeView view = (SimpleDraweeView) rootView.findViewById(R.id.slide_image);

        Bundle arguments = getArguments();
        if (arguments != null) {
            String url = arguments.getString(IMAGE_URL);

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse("https://i.imgur.com/tGbaZCY.jpg"))
                    .setProgressiveRenderingEnabled(true)
                    .build();
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setImageRequest(request)
                    .setTapToRetryEnabled(true)
                    .setOldController(view.getController())
                    .build();
            view.setController(controller);
        }

**Comment by eldk** [comment]
Hello,

Maybe you should test with this first :

`SimpleDraweeView view = (SimpleDraweeView) findViewById(R.id.slide_image);`

`Uri uri = Uri.parse("https://s3.amazonaws.com/xopr/advt1.jpg");`

`ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
               // .setProgressiveRenderingEnabled(true)
                .build();
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
              //  .setTapToRetryEnabled(true)
                .setOldController(view.getController())
                .build();
        view.setController(controller);
    }`

**Comment by DaGeTian** [comment]
Thank you, very much.
This is working, now.
But, it is not working in other activity. I also initialised Fresco in other activity's onCreate();
What is it wrong?

**Comment by eldk** [comment]
Hello,

>I also initialised Fresco in other activity's onCreate();

You should initialize Fresco once : http://frescolib.org/docs/getting-started.html

Eric
