### ISSUE TITLE
Error removing non-existent files from disk cache

### ISSUE THREAD

**Issue by Mithrandir21** [facebook/fresco#1067]
Situation:
Getting a lot of Warnings in my log about the inability to remove a cache file.
Example:
`W/System.err: remove failed: ENOENT (No such file or directory) : /data/data/[APPNAME]/cache/image_cache/v2.ols100.1/78/8WswI13U1FWU5wZ277Lpoy9XJ8w.cnt
W/System.err: remove failed: ENOENT (No such file or directory) : /data/data/[APPNAME]/cache/image_cache/v2.ols100.1/98/jzeIB0BtOx8DNuaXVQ97hRELr0Q.cnt
`
- Fresco (0.9.0) initialised with following code:

``` java
Fresco.initialize(this);
```
- And the request is done as following:

``` java
// Create the Image Request
ImageRequestBuilder requestBuilder = 
ImageRequestBuilder.newBuilderWithSource(uri).setProgressiveRenderingEnabled(true);

DraweeController controller = Fresco.newDraweeControllerBuilder()
    .setImageRequest(requestBuilder.build())
    .setOldController(view.getController())
    .build();

view.setController(controller);
```

The images load correctly, but I get an error message for every image I load.

**Comment by eldk** [comment]
Hello,

Should you build your app with logs for fresco and follow this (http://frescolib.org/docs/troubleshooting.html#) to trace 

`Set<RequestListener> requestListeners = new HashSet<>();
requestListeners.add(new RequestLoggingListener());
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)
   . // other setters
   .setRequestListeners(requestListeners)
   .build();
Fresco.initialize(context, config);
FLog.setMinimumLoggingLevel(FLog.VERBOSE);`

Thanks,

Eric

**Comment by massimocarli** [comment]
Hi,
can you please check if all the permission are ok and if there's enough space on the device please?
Thanks

**Comment by Mithrandir21** [comment]
@eldk Thank you for the logging suggestion.
Used your code to enable logging. Reproduced the issue with logging on (attempting to narrow log to only issue, but a couple of lines from other things might have also gotten).

The whole log can be found here: [Pastebin Log](http://pastebin.com/BB0JNi8L)
(PS: I've replaced all mentions of package names and image URLs in the log with placeholders.)
Below you can see the entire log between 2 errors:

...
03-21 15:58:55.151 555-645/... W/System.err: remove failed: ENOENT (No such file or directory) : /data/data/.../cache/image_cache/v2.ols100.1/70/oG_l_2p1ngYqmR1k1cLAUIaXI-A.cnt
03-21 15:58:55.151 555-645/... V/unknown:BufferedDiskCache: Successful disk-cache write for key {IMAGE-URL}
03-21 15:58:55.151 555-645/... V/unknown:StagingArea: Count = 0
03-21 15:58:55.181 555-668/... V/unknown:RequestLoggingListener: time 1133555294: onProducerFinishWithSuccess: {requestId: 180, producer: DecodeProducer, elapsedTime: 38 ms, extraMap: {queueTime=1, imageType=DEFAULT, hasGoodQuality=true, bitmapSize=692x692, isFinal=false}}
03-21 15:58:55.181 555-668/... V/unknown:BitmapPool: release (free) (object, size) = (2022df63, 1915456)
03-21 15:58:55.181 555-668/... V/unknown:BitmapPool: Used = (40, 66029120); Free = (0, 0)
03-21 15:58:55.181 555-555/... V/unknown:AbstractDraweeController: controller 21875e2a 180: set_intermediate_result @ onNewResult: image: CloseableReference 1c8c4abf
03-21 15:58:55.241 555-673/... V/unknown:RequestLoggingListener: time 1133555357: onProducerStart: {requestId: 180, producer: DecodeProducer}
03-21 15:58:55.251 555-673/... V/unknown:BitmapPool: Used = (41, 67944576); Free = (0, 0)
03-21 15:58:55.251 555-673/... V/unknown:BitmapPool: get (alloc) (object, size) = (353c358c, 1915456)
03-21 15:58:55.301 555-673/... V/unknown:RequestLoggingListener: time 1133555412: onProducerFinishWithSuccess: {requestId: 180, producer: DecodeProducer, elapsedTime: 55 ms, extraMap: {queueTime=61, imageType=DEFAULT, hasGoodQuality=true, bitmapSize=692x692, isFinal=true}}
03-21 15:58:55.301 555-673/... V/unknown:RequestLoggingListener: time 1133555412: onRequestSuccess: {requestId: 180, elapsedTime: 2154 ms}
03-21 15:58:55.321 555-555/... V/unknown:AbstractDraweeController: controller 21875e2a 180: set_final_result @ onNewResult: image: CloseableReference 393ba4d5
03-21 15:58:55.321 555-555/... V/unknown:AbstractDraweeController: controller 21875e2a 180: release_previous_result @ onNewResult: image: CloseableReference 1c8c4abf
03-21 15:58:55.321 555-555/... V/unknown:BitmapPool: release (free) (object, size) = (1e7578de, 1915456)
03-21 15:58:55.321 555-555/... V/unknown:BitmapPool: Used = (40, 66029120); Free = (0, 0)
03-21 15:58:55.841 555-702/... V/unknown:NativeMemoryChunkPool: Used = (52, 4047872); Free = (4, 27648)
03-21 15:58:55.851 555-702/... V/unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (371dfe84, 1024)
03-21 15:58:55.851 555-702/... V/unknown:GenericByteArrayPool: Used = (1, 16384); Free = (3, 49152)
03-21 15:58:55.851 555-702/... V/unknown:GenericByteArrayPool: get (reuse) (object, size) = (35193385, 16384)
03-21 15:58:55.851 555-702/... V/unknown:NativeMemoryChunkPool: Used = (53, 4064256); Free = (3, 11264)
03-21 15:58:55.851 555-702/... V/unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (26b937c3, 16384)
03-21 15:58:55.851 555-702/... V/unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (371dfe84, 1024)
03-21 15:58:55.861 555-702/... V/unknown:NativeMemoryChunkPool: Used = (52, 4063232); Free = (4, 12288)
03-21 15:58:55.861 555-702/... V/unknown:RequestLoggingListener: time 1133555973: onProducerEvent: {requestId: 182, stage: NetworkFetchProducer, eventName: intermediate_result; elapsedTime: 2699 ms}
03-21 15:58:55.861 555-702/... I/unknown:TiffUtil: Unsupported orientation
03-21 15:58:55.861 555-702/... V/unknown:GenericByteArrayPool: Used = (2, 32768); Free = (2, 32768)
03-21 15:58:55.861 555-702/... V/unknown:GenericByteArrayPool: get (reuse) (object, size) = (1a6adef, 16384)
03-21 15:58:55.871 555-702/... V/unknown:GenericByteArrayPool: release (reuse) (object, size) = (1a6adef, 16384)
03-21 15:58:55.871 555-702/... V/unknown:GenericByteArrayPool: Used = (1, 16384); Free = (3, 49152)
03-21 15:58:55.871 555-674/... V/unknown:RequestLoggingListener: time 1133555981: onProducerStart: {requestId: 182, producer: DecodeProducer}
03-21 15:58:55.871 555-702/... V/unknown:NativeMemoryChunkPool: Used = (53, 4096000); Free = (4, 12288)
03-21 15:58:55.871 555-674/... V/unknown:BitmapPool: Used = (41, 67944576); Free = (0, 0)
03-21 15:58:55.871 555-702/... V/unknown:NativeMemoryChunkPool: get (alloc) (object, size) = (2744d3db, 32768)
03-21 15:58:55.871 555-674/... V/unknown:BitmapPool: get (alloc) (object, size) = (273d1e78, 1915456)
03-21 15:58:55.871 555-702/... V/unknown:NativeMemoryChunkPool: Used = (54, 4161536); Free = (4, 12288)
03-21 15:58:55.871 555-702/... V/unknown:NativeMemoryChunkPool: get (alloc) (object, size) = (1d1eb951, 65536)
03-21 15:58:55.871 555-702/... V/unknown:NativeMemoryChunkPool: release (free) (object, size) = (2744d3db, 32768)
03-21 15:58:55.871 555-702/... V/unknown:NativeMemoryChunkPool: Used = (53, 4128768); Free = (4, 12288)
03-21 15:58:55.871 555-702/... V/unknown:RequestLoggingListener: time 1133555986: onProducerFinishWithSuccess: {requestId: 182, producer: NetworkFetchProducer, elapsedTime: 2712 ms, extraMap: null}
03-21 15:58:55.881 555-702/... I/unknown:TiffUtil: Unsupported orientation
03-21 15:58:55.881 555-702/... V/unknown:StagingArea: Count = 1
03-21 15:58:55.881 555-641/... V/unknown:BufferedDiskCache: About to write to disk-cache for key {IMAGE-URL}
03-21 15:58:55.881 555-641/... V/unknown:GenericByteArrayPool: Used = (2, 32768); Free = (2, 32768)
03-21 15:58:55.881 555-641/... V/unknown:GenericByteArrayPool: get (reuse) (object, size) = (2c960b33, 16384)
03-21 15:58:55.881 555-641/... V/unknown:GenericByteArrayPool: release (reuse) (object, size) = (2c960b33, 16384)
03-21 15:58:55.881 555-641/... V/unknown:GenericByteArrayPool: Used = (1, 16384); Free = (3, 49152)
03-21 15:58:55.881 555-641/... W/System.err: remove failed: ENOENT (No such file or directory) : /data/data/.../cache/image_cache/v2.ols100.1/96/h6oYteTuK2GMQiyk4MEfQC0wIlo.cnt
...

**Comment by Mithrandir21** [comment]
Just observed that the error is only logged on items that have not previously been cached (ie. downloaded).

**Comment by eldk** [comment]
Hello,

Should you look @massimocarli comment and try on another device ?

**Comment by raylee4204** [comment]
This issue occurs to me as well

**Comment by celesteshire** [comment]
This issue occurs to me as w well T_T

**Comment by diousk** [comment]
same issue occurred in my project

**Comment by erikandre** [comment]
Closing as this seems to be harmless.
