### ISSUE TITLE
unable to expand TAR 'imagepipeline\build\downloads\libjpeg-turbo-1.3.1.tar.gz'

### ISSUE THREAD

**Issue by Jacky-Xu** [facebook/fresco#107]
The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file exten
sion.
  If you need to specify the compression explicitly please refer to the DSL refe
rence.
> Unexpected end of ZLIB input stream 

I tried. / gradlew build, but the compilation fails, appear the error message above.

**Comment by ljnalex** [comment]
I have the same problem

**Comment by ljnalex** [comment]
* What went wrong:
Unable to expand TAR 'D:\Git\fresco\imagepipeline\build\downloads\libp
ng-1.6.10.tar.gz'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file e
xtension.
  If you need to specify the compression explicitly please refer to the DSL
reference.
> Could not copy tar entry D:\Git\fresco\imagepipeline\build\downloads
\libpng-1.6.10.tar.gz!libpng-1.6.10/configure to 'D:\Git\fresco\imagep
ipeline\build\tmp\expandedArchives\libpng-1.6.10.tar.gz_3xzelags58nc56gwvsid
o56le\libpng-1.6.10\configure'.

**Comment by michalgr** [comment]
Can you remove imagepipeline/build directory and try again ?

**Comment by michalgr** [comment]
I assume that the advice helped. Please reopen if not.

**Comment by Jacky-Xu** [comment]
The solution is to download http://downloads.sourceforge.net/project/libjpeg-turbo/1.3.1/libjpeg-turbo-1.3.1.tar.gz

**Comment by macroharder** [comment]
Unable to expand TAR '/Users/liukun/code/fresco/imagepipeline/nativedeps/downloads/v0.4.2.tar.gz'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file extension.
  If you need to specify the compression explicitly please refer to the DSL reference.
> Could not copy tar entry /Users/liukun/code/fresco/imagepipeline/nativedeps/downloads/v0.4.2.tar.gz!libwebp-0.4.2/swig/libwebp_python_wrap.c to '/Users/liukun/code/fresco/imagepipeline/build/tmp/expandedArchives/v0.4.2.tar.gz_efurske37c9d98oidjq3g8dsd/libwebp-0.4.2/swig/libwebp_python_wrap.c'.
              
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
BUILD FAILED

**Comment by xckevin** [comment]
Yep, I got same error. Even though remove **imagepipeline/build** directory and try again

**Comment by macroharder** [comment]
@xckevin the error is solved,you can try it by remove all build directory and remove fresco/imagepipeline/nativedeps diectory ,then rebuild!

**Comment by xckevin** [comment]
@macroharder  Awesome

**Comment by mahuafactory** [comment]
@Jacky-Xu The solution is to download http://downloads.sourceforge.net/project/libjpeg-turbo/1.3.1/libjpeg-turbo-1.3.1.tar.gz
This is the solution
