### ISSUE TITLE
Nexus 5X Marshmallow OOM

### ISSUE THREAD

**Issue by Roma-Lis** [facebook/fresco#1071]
I use fresco lib to load images to items in recycler view. It used to work on all test devices with any os version aboard. But i have OOM on LG Nexus 5X (Marshmallow). With memory monitor I found out that memory consumption raise up proportionally to items i scroll through and after the app reach 512M it freezes for a moment and crashes with OOM. I also have tried to inspect scrolling with network monitor, and I am  persuaded the app didn't load so many data from network.

```
Clamp target GC heap from 527MB to 512MB
Alloc concurrent mark sweep GC freed 2422(131KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 1.425ms total 42.172ms
WaitForGcToComplete blocked for 181.671ms for cause Alloc
Starting a blocking GC Alloc
Uncaught exception thrown by finalizer
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and -2640B until OOM
                                                           at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:53)
                                                           at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                           at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                           at java.lang.Thread.run(Thread.java:818)
```

Currently Nexus 5x is the only device I can reproduce the issue.
Usage case: initialize lib in app's onCreate and setImageURI to SimpleDraweeView bound via ButterKnife.

**Comment by massimocarli** [comment]
Thank you @Roma-Lis, we'll investigate the problem. Can you please provide us a snippet of the cose you use into the RecyclerView
Thanks

**Comment by Roma-Lis** [comment]
public class VideoHolder extends RecyclerView.ViewHolder {
    @Bind(R.id.preview)
    protected SimpleDraweeView preview;
    ... title, likes, etc.

    public VideoHolder(View itemView) {
        super(itemView);
        ButterKnife.bind(this, itemView);
    }

    public void bindData(Video video) {
        preview.setImageURI(Uri.parse(video.getThumbnailUrl()));
       ..... title, likest, etc.
    }
}

... and in Adapter
   @Override
    public VideoHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new VideoHolder(inflater.inflate(R.layout.video_item_layout, parent, false));
    }

    @Override
    public void onBindViewHolder(VideoHolder holder, int position) {
        Video video = videos.get(position);
        holder.bindData(context, video, this);
    }

**Comment by kirwan** [comment]
I wonder whether my comment here will help. It relates to reusing the controller in `onBindViewHolder()`.

https://github.com/facebook/fresco/issues/1113#issuecomment-211455186

**Comment by atship** [comment]
@kirwan No, the problem still exists. I wonder that why fresco don't use ashmem after lollipop, it's so good for prevent OOM exceptions.

**Comment by tyronen** [comment]
As a workaround for now add `android:largeHeap="true"` to your `AndroidManifest.xml` file.

**Comment by Roma-Lis** [comment]
I ran out of 512M with largeHeap enabled

**Comment by kraghu** [comment]
is this fixed ?

**Comment by kirwan** [comment]
I'm not aware of anything specifically that might have fixed this, though I would say that we don't have similar problems with the Nexus 5X internally and are obviously loading a lot of images within RecyclerViews too.

First thing to try would be to upgrade to the latest release: 1.0.1.

Beyond that, I can suggest some more diagnostic tools if you're seeing problems with this.

**Comment by erikandre** [comment]
Would also recommend that ResizeOptions are used in case the loaded images are large. Closing issue for now but please comment with any additional useful information that could help us investigate this. Thanks!
