### ISSUE TITLE
Fresco load image without drawee but in subscribe() callback getResult.get()=null

### ISSUE THREAD

**Issue by TmRobust** [facebook/fresco#1074]
Hi,When i load image  and display it successfully in a activity in the following
ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse("http://kelutest-imgservice.huiian.com/image/100005_1458554647805_xhtav3r9idxvmp0mz7sn")).build();
        Fresco.getImagePipeline()
        .fetchEncodedImage(imageRequest, null).subscribe(new BaseDataSubscriber<CloseableReference<PooledByteBuffer>>()
        {

            @Override
            protected void onFailureImpl(DataSource<CloseableReference<PooledByteBuffer>> arg0)
            {
                // TODO Auto-generated method stub
                
            }

            @Override
            protected void onNewResultImpl(DataSource<CloseableReference<PooledByteBuffer>> arg0)
            {
                InputStream is = new PooledByteBufferInputStream(arg0.getResult().get());
                imageView.setImage(is);
            }
        }, limitedTaskExecutor);

but when i load image in viewpager , int the callback arg0.getResult().get() =null, arg.getResult is not null

i don't know how to resolve it , please help me, thx

**Comment by massimocarli** [comment]
What type of ViewPagerAdapter are you using? At what stage are you making the request for the image?
Thanks

**Comment by TmRobust** [comment]
sorry，i have resloved it.
i use handler in the callback，like this
handler.post(new Runnable()
                    {
                        
                        @Override
                        public void run()
                        {
                            InputStream is = new PooledByteBufferInputStream(arg0.getResult().get());
            imageView.setImage(is);
                        }
                    })
