### ISSUE TITLE
FAILURE:gradlew build successful , but compiled failed with an exception

### ISSUE THREAD

**Issue by LonelyRay** [facebook/fresco#108]
environment：
mac os
jdk:1.8

The project cloned from github;
stp1:running gradlew script is successful；
stp2:I have a problem when compiling；
../fresco-master/imagepipeline/build.gradle
Error:(80, 0) Cause: java.nio.file.Paths

i have no idea about this；

**Comment by xingxiang1989** [comment]
me too

**Comment by LonelyRay** [comment]
it's just because of the  wrong JDK path I set for android studio。
