### ISSUE TITLE
获取图片bug

### ISSUE THREAD

**Issue by pinguo-hedongjin** [facebook/fresco#1083]
本地图片是780*900，传入的ResizeOptions是1600*1600,返回的图片大小是195*255的图片,怎么不是原图，并且下次取该图是是直接返回了内存中的该图

demo:
ImagePipeline imagePipeline = Fresco.getImagePipeline();

        ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(uri)
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.DISK_CACHE)
                .setResizeOptions(resizeOptions)
                .build();

        DataSource<CloseableReference<CloseableImage>>
                dataSource = imagePipeline.fetchDecodedImage(imageRequest, mContext);

        DataSubscriber dataSubscriber =
                new BaseDataSubscriber<CloseableReference<CloseableImage>>() {
                    @Override
                    public void onNewResultImpl(
                            DataSource<CloseableReference<CloseableImage>> dataSource) {

                        try {
                            if (!dataSource.isFinished()) {
                                L.v("Not yet finished - this is just another progressive scan.");
                            }

                            CloseableReference<CloseableImage> imageReference = dataSource.getResult();
                            if (imageReference == null) {
                                L.e("imageReference is null");
                                callback.onComplete(null);
                            } else {
                                FrescoImage frescoImage = new FrescoImage(imageReference);
                                Bitmap bitmap = frescoImage.get();
                                L.v("getImageFromDiskCache bitmap (" + bitmap.getWidth() + ", " + bitmap.getHeight() + ")");

                                callback.onComplete(frescoImage);
                            }
                        } finally {
                            dataSource.close();
                        }

                    }

                    @Override
                    public void onFailureImpl(DataSource dataSource) {
                        Throwable throwable = dataSource.getFailureCause();
                        // handle failure
                        callback.onError(throwable.toString());
                    }
                };

        dataSource.subscribe(dataSubscriber, CallerThreadExecutor.getInstance());

**Comment by aagnes** [comment]
本地图片是780900，传入的ResizeOptions是16001600,返回的图片大小是195*255的图片,怎么不是原图
you don't need to load the entire bitmap in the view if your view is a lot smaller in dimension

并且下次取该图是是直接返回了内存中的该图
We cache bitmap and retrieve it for you next time when you need the same image
