### ISSUE TITLE
Import a local version of fresco

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#1085]
Do you have a guide for importing a local(fork/cloned and modified) version of fresco as a library into another project.I went through the pom files on maven central.However wondering if there is an easier way to do so.

**Comment by aagnes** [comment]
unfortunately we don't support it now

**Comment by droidekas** [comment]
I managed to do it albeit in a mutilated manner.Would there be an appropriate place to document the same for future users? And you could maybe verfify if this would work correctly.

**Comment by oprisnik** [comment]
You can always add a comment here with your solution :)

**Comment by erikandre** [comment]
Closing as there has been no updates for the last year. A potential solution to this would be to modify Fresco and then publish the build artifact to your own maven repo (or even a local one if it does not need to be shared)
