### ISSUE TITLE
Allow resize of Drawee in case of local images

### ISSUE THREAD

**Issue by vedant1811** [facebook/fresco#1087]
Great work on the library!
This is a feature request.

I agree with the rationale of not supporting `wrap_content`- better to fetch the dimensions from the server and set the aspect ratio instead.

But in the case of local images, the image is (practically) loaded as soon as it is set with no chances of errors. So if we are to resize the view *after* fetching the image, the user will not notice.

I get a square image view when setting a local URI.

Also, I tried using a plain old `ImageView` but that's not efficient and looks bad.

I will use [this](http://stackoverflow.com/questions/33955510/facebook-fresco-using-wrap-conent/34075281#34075281) to solve my problem, so feel free to close this if you think it doesn't go with your design principles.

**Comment by aagnes** [comment]
For local images, it won't be available immediately as well. There's still chance of glitch when view size get changed. You can use aspect ratio to get a none square view you want.
