### ISSUE TITLE
Load the local image with url which is contain special symbol

### ISSUE THREAD

**Issue by helengray** [facebook/fresco#1088]
the local url is :
`/storage/emulated/0/tencent/QQfile_recv/KB1U3X]UODZSR[`1H1`)G%W.png`
but it load fail,and throw the throwable on BaseControllerListener.onFailure:
`java.io.FileNotFoundException: /storage/emulated/0/tencent/QQfile_recv/KB1U3X]UODZSR[`1H1`)G�png: open failed: ENOENT (No such file or directory)`

I think,it cause the url contain special symbol %

I promise the local image is exist

**Comment by wangjing53406** [comment]
I had the same problem.

**Comment by karun2189** [comment]
How you load your local file ? its like simpleDraweeView.setImageUri(Uri.parseFromFile(new File(path))) right ?

**Comment by a631855639** [comment]
@karun2189 yes

**Comment by huangjunkun** [comment]
You could try to decode your url before call Fresco image request.
尝试先对url做decode操作，比较安全，比如uri.parse ，好像有默认编码处理的。

**Comment by a631855639** [comment]
@huangjunkun I have try to Uri.encode(url, "@#&=*+-_.,:!?()/~\'%"),but it don't work fine

**Comment by a631855639** [comment]
please use Uri.parseFromFile(new File(path)) ,not use Uri.parse("file//:"+path)

**Comment by aagnes** [comment]
As this is solved, I'm closing the task.

**Comment by hzvtc** [comment]
please use Uri.FromFile(new File(path)) ,not use Uri.parse("file://"+path)

**Comment by oprisnik** [comment]
You should use `UriUtil`, see https://github.com/facebook/fresco/blob/master/fbcore/src/main/java/com/facebook/common/util/UriUtil.java#L218

**Comment by Ujjwal-soft** [comment]
Found a solutions to this:

convert imagepath to Uri as :
    Uri picUri= Uri.fromFile(new File("/storage/emulated/0/Pictures/OGQ/Richard Walker_Stairway To Heaven%3F_YkFgR2RZ.jpg"
    
    ImageRequest request=ImageRequestBuilder.newBuilderWithSource(picUri).setResizeOptions(new ResizeOptions(width, height)).build();

This will load image contains special chars or symbols.
