### ISSUE TITLE
fresco can't load local image with url witch is contain special symbol on sdcard. 

### ISSUE THREAD

**Issue by wangjing53406** [facebook/fresco#1089]
I use freco to load a local file, but my file path contains a "#", then fresco can't load the image.

Here is my file path:
file://com.culiu.purchase/storage/sdcard0/Android/data/com.culiu.purchase/culiukeji#99baoyou/im_35d98e2ad3dac38dd8/image/thbb36a010-f57b-11e5-81e5-51fce7a71292

Here is log:
java.io.FileNotFoundException: /storage/sdcard0/Android/data/com.culiu.purchase/culiukeji: open failed: ENOENT (No such file or directory)

**Comment by aagnes** [comment]
Combine into #1088
