### ISSUE TITLE
BUG for mDecodeFileDescriptorEnabledForKitKat

### ISSUE THREAD

**Issue by huangjunkun** [facebook/fresco#1091]
LocalFetchProducer
    if (mDecodeFileDescriptorEnabledForKitKat && inputStream instanceof FileInputStream &&
        javaMax >= 64 * javaFree) {
      return getInputStreamBackedEncodedImage(new File(inputStream.toString()), length);
    }

result in ：
com.facebook.imagepipeline.platform.DalvikPurgeableDecoder#decodeJPEGFromEncodedImage

    final CloseableReference<PooledByteBuffer> bytesRef = encodedImage.getByteBufferRef();
    Preconditions.checkNotNull(bytesRef);

throw new NullPointerException();
==========================
so：
 mDecodeFileDescriptorEnabledForKitKat is faulted commit ！  ：（

**Comment by aagnes** [comment]
THanks for pointing it out. We'll fix the bug asap.

**Comment by huangjunkun** [comment]
OK

**Comment by kirwan** [comment]
This is actually an experimental config option which I wouldn't currently recommend using.

In the next release this has been moved to a separate class to the main `ImagePipelineConfig` called [`ImagePipelineExperiments`](https://github.com/facebook/fresco/blob/abeb080ce8135326a450e65b2e00b95f9dacd876/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipelineExperiments.java) to make it more obvious that this is one of a few options which are riskier to change.

**Comment by huangjunkun** [comment]
A good idea.

**Comment by huangjunkun** [comment]
Hoo ~ nice.
