### ISSUE TITLE
Miss parseMetaData leading to  decode source(big) Bitmap Object

### ISSUE THREAD

**Issue by huangjunkun** [facebook/fresco#1092]
com.facebook.imagepipeline.producers.DecodeProducer.ProgressiveDecoder#ProgressiveDecoder
commit：a617d2e300b9de389e7f6f9d0e8e1f560d5cabe7
From：Moved sample size calculations to DecodeProducer only

            if (mDownsampleEnabled) {
              ImageRequest request = producerContext.getImageRequest();
              if (mDownsampleEnabledForNetwork ||
                  !UriUtil.isNetworkUri(request.getSourceUri())) {
                encodedImage.setSampleSize(DownsampleUtil.determineSampleSize(
                    request, encodedImage));
              }
            }
==================
Correct is follow ：

          if (mDownsampleEnabled) {
              ImageRequest request = mProducerContext.getImageRequest();
              if (mDownsampleEnabledForNetwork ||
                  !UriUtil.isNetworkUri(request.getSourceUri())) {
                  if (!EncodedImage.isMetaDataAvailable(newResult)) {
                      newResult.parseMetaData();
                  }
                  newResult.setSampleSize(DownsampleUtil.determineSampleSize(
                    request, newResult));
              }
            }

**Comment by huangjunkun** [comment]
This is Fresco-ImagePipeline's defect or bug.

**Comment by aagnes** [comment]
Thanks for letting us know. You can actually send us pull request from feature did or bug you found.

**Comment by huangjunkun** [comment]
@aagnes   OK
