### ISSUE TITLE
Setting new Image Uri on SDV flickers

### ISSUE THREAD

**Issue by norman-kapschefsky** [facebook/fresco#1103]
Hi,
in our app we display preview images from cache if the target one is not laoded so far. The problem is that if the final image is loaded and a preview image was set on SDV the transition between this images flickers. What can I do to avoid this? No placeholder or progress drawable is defined.

**Comment by aagnes** [comment]
May I understand why you don't use preview image as placeholderImage?

**Comment by oprisnik** [comment]
See #1328 for a potential workaround
