### ISSUE TITLE
ProgressBarImage not working correctly when roundAsCircle=true

### ISSUE THREAD

**Issue by panteluke** [facebook/fresco#1110]
Hi,

I have a SimpleDraweeView like that:
```xml
<com.facebook.drawee.view.SimpleDraweeView
    android:layout_width="100dp"
    android:layout_height="100dp"
    fresco:progressBarImage="@drawable/my_drawable"
    fresco:progressBarImageScaleType="none"
    fresco:roundAsCircle="true" />
```

Now, the results is really strange. Progress bar image is displayed in the centre of the view. But there are also two diameter lines (one vertical and one horizontal, marking something like a cross) below the progress bar image.

**Comment by oprisnik** [comment]
Hi!

Could you please post a screenshot of the drawee view and of the progress bar drawable itself?

Does it work if you use `OVERLAY_COLOR` instead? (see #153 and [the documentation for rounded corners](http://frescolib.org/docs/rounded-corners-and-circles.html))

**Comment by panteluke** [comment]
The placeholder image is like that (so it's already a circle):

![profile_no_image](https://cloud.githubusercontent.com/assets/1526088/14377265/5e7fc334-fd77-11e5-9f28-d84f42f6bf11.png)

The progress bar image is like that:
![feed_image_loader](https://cloud.githubusercontent.com/assets/1526088/14377292/7f08fbf2-fd77-11e5-807e-3f2361ef36c3.png)

I don't know if that's what you requested. The actual image is taken from camera, uploaded to web and then fetched from there, so there's no point in posting a screenshot.

So, it seems that if I set:
```
            fresco:roundedCornerRadius="50dp"
            fresco:roundWithOverlayColor="@color/my_color"
```
then the problem does not appear (of course I have to match the background color with my_color). 
It's a workaround, I suppose. But shouldn't the roundAsCircle work? I mean, it's a bug, no?

**Comment by aagnes** [comment]
Can you share the screenshot of your view to show what do you mean by "But there are also two diameter lines (one vertical and one horizontal, marking something like a cross) below the progress bar image." And also which fresco lib version do you use?

**Comment by panteluke** [comment]
I suppose I'm using the latest version. In build.gradle there's this line
`compile 'com.facebook.fresco:fresco:0.9.0+`

This is the screenshot (ignore the camera icon, it's a different image view. Even if I remove it, the SimpleDraweeView has the same effect):
![example](https://cloud.githubusercontent.com/assets/1526088/14424284/ec066f00-ffe8-11e5-9560-fd4125b337be.png)

**Comment by aagnes** [comment]
That's a bug we fixed and will come out in the next release. If you wanna fix it right now, you can modify your progress bar image by making the pixel on edge "not green". When the bitmap is upscaled to the dimen of hosting view, the edge gets repeated.

**Comment by NammariMarkavip** [comment]
+1
