### ISSUE TITLE
Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and 3GB until OOM" (recursive case)

### ISSUE THREAD

**Issue by DankeLuo** [facebook/fresco#1111]
![qq 20160407102621](https://cloud.githubusercontent.com/assets/6705440/14338679/7588c3c2-fcab-11e5-9393-08b5cb83d63c.png)
![qq 20160407102748](https://cloud.githubusercontent.com/assets/6705440/14338680/75f2df32-fcab-11e5-877e-b0213e0005c2.png)

device is SAMSUNG J7008, fresco version is 0.8.1. Sometime it case a deadlock.here is some log about the question .

**Comment by oprisnik** [comment]
Hey, thanks for reporting this issue!

Fresco is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

If you don't know how to do something or something is not working as you expect but not sure it's a bug, please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

We welcome clear issues and PRs that are ready for in-depth discussion. Please provide screenshots where appropriate and always mention the version of Fresco you're using. Thank you for your contributions!
