### ISSUE TITLE
When will update the new version?

### ISSUE THREAD

**Issue by sangmingming** [facebook/fresco#1119]
That has some bugs as see in Issues, when will update the new version to fix that?

**Comment by aagnes** [comment]
What bugs do you mean by that? We'll have a new release shortly.

**Comment by sangmingming** [comment]
@aagnes  my app get the bugs of  [#issues1077](https://github.com/facebook/fresco/issues/1077) and other bugs

**Comment by aagnes** [comment]
please try with the solution with #933 . If you experience bugs, please create a new thread or join an existing one so we can track for each.
