### ISSUE TITLE
Drawing different kind of image shapes

### ISSUE THREAD

**Issue by Nimrodda** [facebook/fresco#1120]
Fresco has built-in support for circular images and rounded corner, but what about other shapes such as diamond or parallelogram, etc?
I've searched this topic for the past 2 days and barely found anything about it.
An example of a shape I would like to have:
![example](http://i.stack.imgur.com/59zzh.png)

I've posted a more in-depth question on [stackoverflow](http://stackoverflow.com/questions/36614917/android-fresco-drawing-different-kind-of-image-shapes) and would really appreciate it if you could check it out.

**Comment by aagnes** [comment]
Answered in stackoverflow

**Comment by Nimrodda** [comment]
@aagnes thanks for your reply. I just checked my question, but can't see the answer there.

**Comment by aagnes** [comment]
I can see my comments from there now. Can you please check it again?

**Comment by Nimrodda** [comment]
Yes, thank you very much!
