### ISSUE TITLE
I concurrent display a lot of pictures, an error occurs, the application Crash

### ISSUE THREAD

**Issue by devsoulwolf** [facebook/fresco#1121]
`04-14 04:45:32.491 23256-23256/com.cxwx.girldiary A/libc: Fatal signal 11 (SIGSEGV), code 1, fault     addr 0xddeb300c in tid 23256 (.cxwx.girldiary)
04-14 04:45:32.592 85-85/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-14 04:45:32.592 85-85/? I/DEBUG: Build fingerprint: 'generic/vbox86p/vbox86p:5.0/LRX21M/buildbot11172321:userdebug/test-keys'
04-14 04:45:32.592 85-85/? I/DEBUG: Revision: '0'
04-14 04:45:32.592 85-85/? I/DEBUG: ABI: 'x86'
04-14 04:45:32.592 85-85/? I/DEBUG: pid: 23256, tid: 23256, name: .cxwx.girldiary  >>> com.cxwx.girldiary <<<
04-14 04:45:32.592 85-85/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xddeb300c
04-14 04:45:32.599 85-85/? I/DEBUG:     eax ddeb300c  ebx f5384bac  ecx 00000190  edx da6a1800
04-14 04:45:32.599 85-85/? I/DEBUG:     esi 00000300  edi 00000064
04-14 04:45:32.599 85-85/? I/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000007  xss 0000002b
04-14 04:45:32.599 85-85/? I/DEBUG:     eip f7627b6a  ebp da6a1800  esp fffd7068  flags 00210287
04-14 04:45:32.599 85-85/? I/DEBUG: backtrace:
04-14 04:45:32.599 85-85/? I/DEBUG:     #00 pc 00016b6a  /system/lib/libc.so (memcpy+42)
04-14 04:45:32.600 85-85/? I/DEBUG:     #01 pc 0010bc7c  /system/lib/libskia.so
04-14 04:45:32.600 85-85/? I/DEBUG:     #02 pc 0011aa6a  /system/lib/libskia.so (SkARGB32_Shader_Blitter::blitRect(int, int, int, int)+538)
04-14 04:45:32.600 85-85/? I/DEBUG:     #03 pc 0018f0f4  /system/lib/libskia.so (SkScan::AntiFillRect(SkRect const&, SkRegion const*, SkBlitter*)+1380)
04-14 04:45:32.600 85-85/? I/DEBUG:     #04 pc 001900ce  /system/lib/libskia.so (SkScan::AntiFillRect(SkRect const&, SkRasterClip const&, SkBlitter*)+142)
04-14 04:45:32.600 85-85/? I/DEBUG:     #05 pc 001358e0  /system/lib/libskia.so (SkDraw::drawRect(SkRect const&, SkPaint const&) const+960)
04-14 04:45:32.600 85-85/? I/DEBUG:     #06 pc 00104d27  /system/lib/libskia.so (SkBitmapDevice::drawRect(SkDraw const&, SkRect const&, SkPaint const&)+55)
04-14 04:45:32.600 85-85/? I/DEBUG:     #07 pc 00124bf0  /system/lib/libskia.so (SkCanvas::drawRect(SkRect const&, SkPaint const&)+928)
04-14 04:45:32.600 85-85/? I/DEBUG:     #08 pc 0012a25e  /system/lib/libskia.so (SkCanvas::drawRectCoords(float, float, float, float, SkPaint const&)+78)
04-14 04:45:32.600 85-85/? I/DEBUG:     #09 pc 000f45b5  /system/lib/libandroid_runtime.so (android::SkiaCanvas::drawRect(float, float, float, float, SkPaint const&)+85)
04-14 04:45:32.600 85-85/? I/DEBUG:     #10 pc 000d9469  /system/lib/libandroid_runtime.so
04-14 04:45:32.600 85-85/? I/DEBUG:     #11 pc 00a8d3f5  /data/dalvik-cache/x86/system@framework@boot.oat
04-14 04:45:32.600 85-85/? I/DEBUG:     #12 pc 000ef0ff  [anon:libc_malloc]
04-14 04:45:32.600 85-85/? I/DEBUG:     #13 pc 000f4f5f  /system/lib/libandroid_runtime.so
04-14 04:45:32.600 85-85/? I/DEBUG:     #14 pc 0078c153  [stack]
04-14 04:45:32.711 85-85/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_00
                                    
                                    
                                    --------- beginning of system`

**Comment by aagnes** [comment]
What do you mean by concurrent? Can you show what you want to achieve here and how do you deal with it and also full error log from logcat? The error you pasted above are from skia and android, which basically cannot help us understand anything.

**Comment by devsoulwolf** [comment]
I have found the problem and repair it, nothing to do with Fresco, he was great, to bring you the inconvenience, please understand ~

**Comment by zrg1215** [comment]
@amphiaraus How do you repair it? I have the same problem. fresco version 1.10.0, HUAWEI P9, android 7.0

**Comment by zrg1215** [comment]
@amphiaraus 直接写中文吧！我也遇到相同的问题，我不用fresco加载图片就不会crash，一旦用了就会crash，现在毫无头绪
