### ISSUE TITLE
How to translate the GitHub page?

### ISSUE THREAD

**Issue by ppamorim** [facebook/fresco#1123]
Hi Fresco team.

I want to translate the GitHub page to Spanish and Portuguese, where I can find the files to do it?

Thanks.

**Comment by kirwan** [comment]
Thanks for your interest in translating our page, that would be fantastic.

I'm afraid that right now we don't have a great way of supporting multiple languages with the way our pages are setup.

The existing translations are actually self-hosted by the people who were kind enough to do them. That would be an option but we're also discussing how we may be able to accommodate translations on our main GitHub pages. We'll let you know what comes out of that discussion.

**Comment by tyronen** [comment]
The English files are found here in the repo, in the [gh-pages](https://github.com/facebook/fresco/tree/gh-pages) branch.

We would be very happy for you to set up your own repos for Spanish and Portuguese. You can see the [Chinese](https://github.com/liaohuqiu/fresco-docs-cn) and [Korean](https://github.com/recrack/fresco-docs-kr) repos for examples. I believe these files are automatically published using GitHub's Pages facility.

We don't yet have a way of automatically notifying volunteer translators of changes in the English docs. The best you can do for now is watch the repo and keep an eye on changes to the gh-pages branch.

Thanks for your help! We really appreciate it. We would be happy to place links to your translations from the English site once they are ready.
