### ISSUE TITLE
Implement ZoomableDraweeView - GenericDraweeHierarchyInflater not found

### ISSUE THREAD

**Issue by yahim91** [facebook/fresco#1126]
I am trying to implement ZoomableDraweeView but I do not have access to GenericDraweeHierarchyInflater class. How should I proceed?

I've seen [this](https://github.com/kunny/ZoomableDraweeView-sample) implementation but uses an old version which does not need this class.

**Comment by kirwan** [comment]
You don't need direct access to `GenericDraweeHierarchyInflater`. That class will simply look for any of the properties identified within it in the properties you've identified in your layout XML file.

You can take the approach shown in the implementation you linked to if you want to set those values in code or you can set the values in your XML layout.

If you need further help, please let me know which properties you're trying to set and I can try to be more specific.

**Comment by yahim91** [comment]
Thank you, Kirwan. I'll let you know if I encounter problems. I went with that version from the link.

**Comment by kirwan** [comment]
OK great. For now, I'm going to close the issue but please reopen if you still have problems.
