### ISSUE TITLE
ZoomableDraweeView slide conflict with viewpager

### ISSUE THREAD

**Issue by e-hai** [facebook/fresco#1129]
If I zoom the image then if I scroll that, then image has to move instead of ViewPager。

**Comment by kirwan** [comment]
Can you please clarify? Is the ZoomableDraweeView consuming the touch events or the ViewPager?

I think you mean the zoomed image isn't scrolling around so I'll check that.

**Comment by e-hai** [comment]
When I zoom the image it can not scrolling to the next image.

**Comment by kirwan** [comment]
OK, I may need to create a test for this scenario. I'll look into that.

**Comment by plamenko** [comment]
This is a known issue.

**Comment by oprisnik** [comment]
I'm pretty sure that this is the behavior you'd want most of the time. Zooming in on an image and then not being able to pan around would be quite weird. If you need this behavior, you can just manually set a gesture listener that doesn't pan to the left or right side.
