### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jyh149129** [facebook/fresco#1131]
sorry for my bad english

error info:
java.lang.UnsatisfiedLinkError
Cannot load library: link_image[1962]: 96 could not load needed library 'libwebp.so' for 'libimagepipeline.so' (load_library[1117]: Library 'libwebp.so' not found)

phone list:
GT-I9105P(samsung)
GT-I8552(samsung)
GT-S7568(samsung)
GT-I8552(samsung)
GT-S7562(samsung)
GN135(GiONEE)
GT-I9082i(samsung)
R811(OPPO)
U701T(OPPO)
R813T(OPPO)
MI 1S(Xiaomi)
Lenovo A390(Lenovo)
HTC T528d(htccn_chs_ct)
vivo Y11i T(vivo)
and more.......

All errors occur < Android 4.3 SDK ?
![2222](https://cloud.githubusercontent.com/assets/7726240/14697929/771e2fe0-07bb-11e6-9ba4-8d49290222c8.png)

**Comment by kirwan** [comment]
I suggest trying the [solution here to use the ReLinker library](https://github.com/facebook/fresco/issues/933#issuecomment-186266187). We've found that's helped people in the past with this problem.

Please re-open the issue if you continue to have problems.
