### ISSUE TITLE
Fresco load gallery image has bad performance compare with Glide?Who can tell me why？

### ISSUE THREAD

**Issue by niejunhong** [facebook/fresco#1134]
On Device: One Plus
Android version:5.1.1
Load local image with:

**Resources resources = context.getResources();
GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(resources)
        .setFadeDuration(300)
        .setPlaceholderImage(resources.getDrawable(R.drawable.image_not_exist))
        .setFailureImage(resources.getDrawable(R.drawable.image_not_exist))
        .build();
    photoImageView.setHierarchy(hierarchy);
    ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(uri)
        .setResizeOptions(new ResizeOptions(200, 200)).build();
    DraweeController controller = Fresco.newDraweeControllerBuilder()
        .setOldController(photoImageView.getController())
        .setImageRequest(imageRequest).build();
    photoImageView.setController(controller);**

perfermance:
![fresco](https://cloud.githubusercontent.com/assets/1409727/14709679/8d234020-0804-11e6-9415-314c13c425ec.jpg)

with Glide:
**Glide.with(photoImageView.getContext())
     .load(uri)
     .centerCrop()
     .error(R.drawable.image_not_exist)
     .placeholder(R.drawable.image_not_exist)
     .dontAnimate()
     .into(photoImageView);**

perfermance:
![glide](https://cloud.githubusercontent.com/assets/1409727/14709696/a5d096f4-0804-11e6-97b4-75cecf2a1de7.jpg)

this gallery display local image
Fresco init with:Fresco.initialize(context);

Why in this condition, fresco performance so bad?
I find this condition just on this One plus now
on my MI and Samsung fresco performance well!

**Comment by plamenko** [comment]
You are using fading animation with fresco (`setFadeDuration(300)`), but no animation with Glide (`dontAnimate`). Try disablign fading with Fresco too: `setFadeDuration(0)`

**Comment by chenwulue** [comment]
@plamenko I had setFadeDuration(0),but it also has bad performance compare with Glide.
