### ISSUE TITLE
Fresco can't load local image what the image's file name is urlencoded,file name like "%E6%8E%A8%E8%8D%90%E4%B8%93%E9%A2%98-1000%E5%85%83.jpg"

### ISSUE THREAD

**Issue by qiuqiutang** [facebook/fresco#1142]

**Comment by massimocarli** [comment]
Url Encoding is responsibility of the client. Why is this encoded?

**Comment by qiuqiutang** [comment]
@massimocarli , I need to read all of the local pictures, and user can choose any to upload,this picture is urlencode stored  by other app.
