### ISSUE TITLE
libwebp.so: Error: Duplicate resources on compile imagepipeline 

### ISSUE THREAD

**Issue by XuWeishun** [facebook/fresco#1145]
Error:Execution failed for task ':imagepipeline:mergeReleaseJniLibFolders'.

> [armeabi-v7a/libwebp.so] /Users/xuws/Documents/fresco-master/imagepipeline/build/imagepipeline/armeabi-v7a/libwebp.so [armeabi-v7a/libwebp.so] /Users/xuws/Documents/fresco-master/imagepipeline/build/webpimage/armeabi-v7a/libwebp.so: Error: Duplicate resources

**Comment by tyronen** [comment]
Can you first do 

```bash
./gradlew clean allclean
``` 

and try again?

**Comment by massimocarli** [comment]
@XuWeishun,
what version of Gradle are you using?
Thanks

**Comment by oprisnik** [comment]
I assume the problem has been resolved. Please let us know if you're still experiencing this issue.
