### ISSUE TITLE
Image not display when call notifyDataChanged()

### ISSUE THREAD

**Issue by howedeng** [facebook/fresco#1149]
Normal state：display image in RecyclerView
![1a8da52b0c7363a16ff48b4d5bc29e8d](https://cloud.githubusercontent.com/assets/4645390/14738585/f21c4f0c-08b4-11e6-8027-1a8d7420fec6.jpg)

when I call notifyDataChanged() to refresh the RecycleView , Sometimes can not be displayed
![e760cae10975bf8c145b37230cc3403a](https://cloud.githubusercontent.com/assets/4645390/14738721/cfbf45da-08b5-11e6-9b56-0c29d03aafc2.jpg)

The following is my code in `onBindViewHolder`

`ImageRequest request = ImageRequest.fromUri(Uri.parse(finalUrl));
 DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
                .setOldController(imageView.getController()).build();
 imageView.setController(controller);`

`<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/publicityImg"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        fresco:backgroundImage="@drawable/shape_show_off_img_bg"
        fresco:roundedCornerRadius="2dp"
        fresco:roundingBorderWidth="1dp"
        fresco:placeholderImage="@drawable/default_img_small_5x4"
        fresco:placeholderImageScaleType="fitXY"
        fresco:roundingBorderColor="@color/common_divider_color"/>`

**Comment by massimocarli** [comment]
In our comparison app we're using Drawee into a RecyclerView. Please use that demo app as reference.

**Comment by howedeng** [comment]
Problem is solved when remove  fresco:roundingBorderWidth  and fresco:roundingBorderColor，I do not know why!  Is this a bug?

**Comment by massimocarli** [comment]
@howedeng Thank for this. We'll make some test about this.
