### ISSUE TITLE
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.

### ISSUE THREAD

**Issue by zjl880812** [facebook/fresco#115]
Information:Gradle tasks [:sample:assembleDebug]
:sample:preBuild
:sample:compileDebugNdk UP-TO-DATE
:drawee:compileLint
:drawee:copyReleaseLint UP-TO-DATE
:drawee:preBuild
:drawee:preReleaseBuild
:drawee:checkReleaseManifest
:drawee:preDebugBuild
:drawee:preDebugTestBuild
:fbcore:compileLint
:fbcore:copyReleaseLint UP-TO-DATE
:fbcore:mergeReleaseProguardFiles UP-TO-DATE
:fbcore:preBuild
:fbcore:preReleaseBuild
:fbcore:checkReleaseManifest
:fbcore:prepareReleaseDependencies
:fbcore:compileReleaseAidl UP-TO-DATE
:fbcore:compileReleaseRenderscript UP-TO-DATE
:fbcore:generateReleaseBuildConfig UP-TO-DATE
:fbcore:generateReleaseAssets UP-TO-DATE
:fbcore:mergeReleaseAssets UP-TO-DATE
:fbcore:generateReleaseResValues UP-TO-DATE
:fbcore:generateReleaseResources UP-TO-DATE
:fbcore:packageReleaseResources UP-TO-DATE
:fbcore:processReleaseManifest UP-TO-DATE
:fbcore:processReleaseResources UP-TO-DATE
:fbcore:generateReleaseSources UP-TO-DATE
:fbcore:compileReleaseJava UP-TO-DATE
:fbcore:processReleaseJavaRes UP-TO-DATE
:fbcore:packageReleaseJar UP-TO-DATE
:fbcore:compileReleaseNdk UP-TO-DATE
:fbcore:packageReleaseJniLibs UP-TO-DATE
:fbcore:packageReleaseLocalJar UP-TO-DATE
:fbcore:packageReleaseRenderscript UP-TO-DATE
:fbcore:bundleRelease UP-TO-DATE
:drawee:prepareComAndroidSupportSupportV42103Library UP-TO-DATE
:drawee:prepareComFacebookFrescoFbcore010Library UP-TO-DATE
:drawee:prepareReleaseDependencies
:drawee:compileReleaseAidl UP-TO-DATE
:drawee:compileReleaseRenderscript UP-TO-DATE
:drawee:generateReleaseBuildConfig UP-TO-DATE
:drawee:generateReleaseAssets UP-TO-DATE
:drawee:mergeReleaseAssets UP-TO-DATE
:drawee:generateReleaseResValues UP-TO-DATE
:drawee:generateReleaseResources UP-TO-DATE
:drawee:mergeReleaseResources UP-TO-DATE
:drawee:processReleaseManifest UP-TO-DATE
:drawee:processReleaseResources UP-TO-DATE
:drawee:generateReleaseSources UP-TO-DATE
:drawee:compileReleaseJava UP-TO-DATE
:drawee:extractReleaseAnnotations UP-TO-DATE
:drawee:mergeReleaseProguardFiles UP-TO-DATE
:drawee:processReleaseJavaRes UP-TO-DATE
:drawee:packageReleaseJar UP-TO-DATE
:drawee:compileReleaseNdk UP-TO-DATE
:drawee:packageReleaseJniLibs UP-TO-DATE
:drawee:packageReleaseLocalJar UP-TO-DATE
:drawee:packageReleaseRenderscript UP-TO-DATE
:drawee:packageReleaseResources UP-TO-DATE
:drawee:bundleRelease UP-TO-DATE
:imagepipeline:compileLint
:imagepipeline:copyReleaseLint UP-TO-DATE
:imagepipeline:preBuild
:imagepipeline:preReleaseBuild
:imagepipeline:checkReleaseManifest
:imagepipeline:preDebugBuild
:imagepipeline:preDebugTestBuild
:imagepipeline:prepareComAndroidSupportSupportV42103Library UP-TO-DATE
:imagepipeline:prepareComFacebookFrescoFbcore010Library UP-TO-DATE
:imagepipeline:prepareReleaseDependencies
:imagepipeline:compileReleaseAidl UP-TO-DATE
:imagepipeline:compileReleaseRenderscript UP-TO-DATE
:imagepipeline:generateReleaseBuildConfig UP-TO-DATE
:imagepipeline:generateReleaseAssets UP-TO-DATE
:imagepipeline:mergeReleaseAssets UP-TO-DATE
:imagepipeline:generateReleaseResValues UP-TO-DATE
:imagepipeline:generateReleaseResources UP-TO-DATE
:imagepipeline:mergeReleaseResources UP-TO-DATE
:imagepipeline:processReleaseManifest UP-TO-DATE
:imagepipeline:processReleaseResources UP-TO-DATE
:imagepipeline:generateReleaseSources UP-TO-DATE
:imagepipeline:directories UP-TO-DATE
:imagepipeline:downloadFiles UP-TO-DATE
:imagepipeline:unpackGiflib UP-TO-DATE
:imagepipeline:copyGiflib UP-TO-DATE
:imagepipeline:ndk_build_gifimage FAILED
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'ndk-build''
Information:BUILD FAILED
Information:Total time: 4.338 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

when I run gradlew --info again it toasts me that SUCCESS.while I run the application ,it print the above error messages.how should I do

**Comment by tyronen** [comment]
Are you still experiencing this on latest head? What operating system are you on?

**Comment by arlong** [comment]
@tyronen 
I have the same issue on Mac Os ,but it's ok on Windows Os!

**Comment by tyronen** [comment]
Please sync to latest head, do a ./gradlew clean, and follow the current [build instructions](http://frescolib.org/docs/building-from-source.html#_). Reopen if the problem persists.

**Comment by xiaoluo** [comment]
Thanks too much ，when I sync the newest code，It works on Windows，THX~~
