### ISSUE TITLE
Execution failed for task: 'imagepipeline-test: processReleaseResources'. a library uses the same package as this project :com.facebook.imagepipelinebase.

### ISSUE THREAD

**Issue by wgykontage** [facebook/fresco#1150]

**Comment by massimocarli** [comment]
Thanks @wgykontage,
can you please provide information on the version of Gradle you're using?

**Comment by wgykontage** [comment]
thank you, i have solved the problem. change the imagepipeline-test
project`s package name in AndroidManifes.xml and complier the fresco on
liunx platform.

2016-04-26 18:20 GMT+08:00 Massimo Carli <notifications@github.com>:

**Comment by elephantzhai** [comment]
I have the same problem.gradle version -- 2.1.0

**Comment by massimocarli** [comment]
Perfect.
Thanks

**Comment by wgykontage** [comment]
have you sloved the problem? <?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.facebook.imagepipelinebase.test"
    >

  <uses-sdk
      android:minSdkVersion="9"
      android:targetSdkVersion="21"
      />
</manifest>
above is the content in imagepipeline-test`s xml file. it is successful.
you should complier the project on linux platform.

2016-04-27 17:55 GMT+08:00 elephantzhai <notifications@github.com>:
