### ISSUE TITLE
basic auth in url getting ignored

### ISSUE THREAD

**Issue by npomfret** [facebook/fresco#1152]
Urls that contain basic auth credentials (e.g http://user:pass@localhost:8080/foo.jpeg) are not working for me.  I think the credentials should be parsed from the url and added as a base64 encoded _authorization_ header.

I don't know this codebase at all, but I think parsing the values out and adding the headers in the  [OkHttpNetworkFetcher.java](https://github.com/facebook/fresco/blob/master/imagepipeline-backends/imagepipeline-okhttp/src/main/java/com/facebook/imagepipeline/backends/okhttp/OkHttpNetworkFetcher.java#L88) might work.

Something like:

```
    Request.Builder builder = new Request.Builder()
            .cacheControl(new CacheControl.Builder().noStore().build())
            .url(uri.toString());

    String userInfo = uri.getUserInfo();
    if(userInfo != null) {
        String[] parts = userInfo.split(":");
        String userName = parts[0];
        String password = parts[1];
        builder.addHeader("Authorization", com.squareup.okhttp.Credentials.Credentials.basic(userName, password))
    }

    final Request request = builder.get().build()
```

I'd try and submit a PR but I can't get the project to compile in intellij for some reason.

**Comment by erikandre** [comment]
Closing as this type of authentication for HTTP is more or less obsolete.
