### ISSUE TITLE
failed to update to fresco 0.9.0 with gradle(Android Studio 2.1 Preview 5,gradle-2.11)

### ISSUE THREAD

**Issue by Casper3635** [facebook/fresco#1153]
![fresco1](https://cloud.githubusercontent.com/assets/3745303/14774914/b395555e-0aed-11e6-8acb-6dcf5a63c48b.jpg)
![fresco2](https://cloud.githubusercontent.com/assets/3745303/14774915/b53e2610-0aed-11e6-9fbe-23f4ddf3e195.jpg)

I upgrate Fresco from 0.8.1 to 0.9.0  and there are something wrong in my project(see img above)

It seems gradle failed to download some package form Jcenter

or is there something change of using Supplier and ByteConstants ? 

If I go back to 0.8.1 ,everything work fine again

plz help

**Comment by eastwoodwang** [comment]
same to me, i cannot find it in repository.... for 0.9.0+

**Comment by massimocarli** [comment]
Hi @eastwoodwang and @Casper3635,
do you still have the same problem with 0.10.0?

Thanks

**Comment by eastwoodwang** [comment]
Thank you for send the mail, i fix it in as.

Maybe it’s a bug is as 2.0+, when use the mouse to click the “search” button, it cannot find the fresco in the center repository.
But when i click the “Enter” in the keyboard, it can extract the fresco.

**Comment by eastwoodwang** [comment]
Thank you for send the mail, i fix it in as.

Maybe it’s a bug is as 2.0+, when use the mouse to click the “search” button, it cannot find the fresco in the center repository.
But when i click the “Enter” in the keyboard, it can extract the fresco.

**Comment by Casper3635** [comment]
well, I'm upgrade it to 0.10.0 today and it works fine!  I can extract fresco now, Thanks! @eastwoodwang
