### ISSUE TITLE
What's the difference between version 0.9.0 and 0.10.0

### ISSUE THREAD

**Issue by MycroftWong** [facebook/fresco#1154]
I can search 'com.facebook.fresco:fresco:0.10.0' in Android Studio. But i didn't find any doc about it. And i found that fresco 0.10.0 is much smaller than 0.9.0 by deleting many features. It can't display gif for example. 
I want to know what should I do to display gif by using fresco 0.10.0. 
Can anyone help? Thank you!

**Comment by fabcoding** [comment]
you can find the answer at: http://frescolib.org/docs/index.html

dependencies {
  // If your app supports Android versions before Ice Cream Sandwich (API level 14)
  compile 'com.facebook.fresco:animated-base-support:0.10.0'

  // For animated GIF support
  compile 'com.facebook.fresco:animated-gif:0.10.0'

  // For WebP support, including animated WebP
  compile 'com.facebook.fresco:animated-webp:0.10.0'
  compile 'com.facebook.fresco:webpsupport:0.10.0'

  // For WebP support, without animations
  compile 'com.facebook.fresco:webpsupport:0.10.0'
}

**Comment by MycroftWong** [comment]
@fabcoding Thank you. I can't connect to that website in my country😰

**Comment by massimocarli** [comment]
Thanks,
release notes are also here https://github.com/facebook/fresco/releases/tag/v0.10.0
