### ISSUE TITLE
When should i call "Fresco.shutdown()"?

### ISSUE THREAD

**Issue by leeon7** [facebook/fresco#1159]
I found only by calling this can i release the heap so i invoked it many places. It's also the reason i had to initialize many times...  [Details here: issue1065 NPE invoking com.facebook.drawee.backends.pipeline.d](https://github.com/facebook/fresco/issues/1065)
thx for help!

**Comment by massimocarli** [comment]
Hi @leeon7,
as said at the isses you mentioned you should call Fresco.shutdown() just once when you finish your application. Anyway we need to improve that method in order to do more than clear memory caches. I'll close this issue and keep opened the other one.
Thanks
