### ISSUE TITLE
drawee-0.1.0-javadoc.jar not available

### ISSUE THREAD

**Issue by tqzym** [facebook/fresco#116]
after build success, I import   fresco/drawee/build/libs/drawee-0.1.0-sources.jar into Eclipse Android Project ,but it(jar file)  not available, why ?

same problem /fresco/fbcore/build/libs/fbcore-0.1.0-sources.jar \  image pipeline-0.1.0-sources.jar\......

how i generate available fresco jar file, and import into eclipse android project ??

**Comment by tyronen** [comment]
You do not need the sources.jar or javadoc.jar in order to build.

However, we haven't entirely got the import into Eclipse working. Please track this in issue #96.
