### ISSUE TITLE
Documentation has a small typo

### ISSUE THREAD

**Issue by ndurell** [facebook/fresco#1161]
I think on page: 

http://frescolib.org/docs/troubleshooting.html

under setting up logcat:

> Set<RequestListener> requestListeners = new HashSet<>();
requestListeners.add(new RequestLoggingListener());
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)
   . // other setters
   .setRequestListeners(requestListeners)
   .build();
Fresco.initialize(context, config);
FLog.setMinimumLoggingLevel(FLog.VERBOSE);

should be:

> Set<RequestListener> requestListeners = new HashSet<>();
requestListeners.add(new RequestLoggingListener());
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)
   // other setters
   .setRequestListeners(requestListeners)
   .build();
Fresco.initialize(context, config);
FLog.setMinimumLoggingLevel(FLog.VERBOSE);

I would submit a PR but I don't see the html for this in the repo.

**Comment by massimocarli** [comment]
Hi @ndurell,
if you want make the PR you should change branch

https://github.com/facebook/fresco/blob/gh-pages/_docs/03-troubleshooting.md

Thanks

**Comment by ndurell** [comment]
submitted a pr but the build failed...let me know if there is something I need to do to fix it.

**Comment by oprisnik** [comment]
Thanks for the PR @ndurell. There are just no tests for the github pages and for some reason this gets reported as failing. Everything is OK, I just merged your PR.

**Comment by ndurell** [comment]
Cool! Thanks @oprisnik!
