### ISSUE TITLE
Get  cache size 

### ISSUE THREAD

**Issue by e-hai** [facebook/fresco#1164]
Can I get cache size like that 
`ImagePipelineFactory.getInstance().getMainDiskStorageCache().getSize();`

**Comment by massimocarli** [comment]
The `getMainDiskStorageCache()` method has been deprecated. You can use: 
`getMainFileCache().getSize()`  in `ImagePipelineFactory`

**Comment by eldk** [comment]
https://github.com/facebook/fresco/commit/542cdcc14fc6bbfe13c613f787835c794d42f397

**Comment by ilumer** [comment]
after this method `Fresco.getImagePipeline().clearDiskCaches();` why `getMainFileCache().getSize()` not return 0 , this is my [question](http://stackoverflow.com/questions/42371227/whats-wrong-about-delete-fresco-diskcache-and-calculate-size)
