### ISSUE TITLE
help~~~~  build error 

### ISSUE THREAD

**Issue by mio4kon** [facebook/fresco#117]
:imagepipeline:directories UP-TO-DATE
:imagepipeline:downloadFiles UP-TO-DATE
:imagepipeline:unpackGiflib UP-TO-DATE
:imagepipeline:copyGiflib UP-TO-DATE
:imagepipeline:ndk_build_gifimage UP-TO-DATE
:imagepipeline:unpackLibjpeg UP-TO-DATE
:imagepipeline:copyLibJpeg UP-TO-DATE
:imagepipeline:cloneWebp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:cloneWebp'.
> org.eclipse.jgit.api.errors.TransportException: https://chromium.googlesource.com/webm/libwebp: cannot open git-upload-pack

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 33.624 secs
>use android studio build 

Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
 A problem occurred starting process 'command 'ndk-build''

**Comment by littletanker** [comment]
you can replace "https://chromium.googlesource.com/webm/libwebp" with "https://github.com/webmproject/libwebp.git".

**Comment by PeiyaoChen** [comment]
I got the same problem

**Comment by tyronen** [comment]
Also sync to head - we are no longer hitting the googlesource.com url.
