### ISSUE TITLE
Doc - Adding Fresco webp support to project - Android API < 14

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#1170]
Hello,

Reading the doc :  http://frescolib.org/docs/index.html

I see : 

`dependencies {`
 ` // If your app supports Android versions before Ice Cream Sandwich (API level 14)`
 ` compile 'com.facebook.fresco:animated-base-support:0.10.0'`

 ` // For animated GIF support`
  `compile 'com.facebook.fresco:animated-gif:0.10.0'``

  `// For WebP support, including animated WebP`
  compile 'com.facebook.fresco:animated-webp:0.10.0'
  compile 'com.facebook.fresco:webpsupport:0.10.0'`

 ` // For WebP support, without animations`
 ` compile 'com.facebook.fresco:webpsupport:0.10.0'`
`}`

So for API < 14 with webp support but no animation (gif or webp) I must add only : 
 `compile 'com.facebook.fresco:fresco:0.10.0'`
 ` compile 'com.facebook.fresco:webpsupport:0.10.0'``

Right ?

Thanks,

Eric

**Comment by massimocarli** [comment]
Hi @eldk,
yes, you're right. If you just want to support static Webp for API < 14 you have to add 

`'compile 'com.facebook.fresco:webpsupport:0.10.0'`

Thanks

**Comment by eldk** [comment]
Thanks @massimocarli
