### ISSUE TITLE
Creating a sprite animation using SimpleDraweeView?

### ISSUE THREAD

**Issue by hay12396** [facebook/fresco#1171]
I would like to create a sprite animation using Fresco.
Once i load the image into SimpleDraweeView, and i got the coordinates of the rectangle that i want to show, how can i tell SimpleDraweeView to only display that part(the rectangle) of that image? 

With regards,
Hay.

**Comment by hay12396** [comment]
If anyone will look for this, managed to do it by extending the BaseRepeatedPostProcessor.

**Comment by plamenko** [comment]
Implement a custom (ScalingUtils.ScaleType)[http://frescolib.org/docs/scaling.html] and set it as `simpleDraweeView.gethierarchy().setActualImageScaleType(mySpriteScaleType)`.

**Comment by samnang-chea369** [comment]
Could you give me the implementation in code? I can't not figure out.
