### ISSUE TITLE
Using Fresco on 64 bit devices (Problem)

### ISSUE THREAD

**Issue by assadyouness** [facebook/fresco#1172]
HI
I got a problem after adding Fresco Lib on 64 bit android devices, my app includes BASS Library which uses native code (32 Bit). I got UnsatisfiedLinkError Error and couldn't run BASS Lib in my app after adding fresco ( It works fine on 32 bit devices ). 

I solved it By adding ::
ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }  
in defaultConfig in gradle.
(Just incase it happens with anyone)

**Comment by massimocarli** [comment]
Hi @assadyouness,
Thank you very much for the tip.
