### ISSUE TITLE
How to load bitmap to fresco cache

### ISSUE THREAD

**Issue by AllenVork** [facebook/fresco#1173]
As we know, Fresco's resize option only works for jpeg.And when comes to load a lot of gif and other format of images, Fresco can't perform well.So i resize the images myself  to bitmap and get the first frame of gif.But i don't know how to add the resized bitmap to Fresco's cache so i needn't resize it again, just get it through uri from the cache.Do you have any solution?

**Comment by plamenko** [comment]
If this thing is easy to do it would already be supported :) You should take a look at the [resizing section in the documentation](http://frescolib.org/docs/resizing-rotating.html).

I am not sure how exactly are you performing that resizing, but one way to do it would be via [post-processors](http://frescolib.org/docs/modifying-image.html). Post-processed images can be cached and that might work for you.

Downside of that approach is that both the big original image and the resized image will be stored in the bitmap cache.
