### ISSUE TITLE
After uprading to 0.10.0 ，can not load gif pic from url

### ISSUE THREAD

**Issue by wenmingvs** [facebook/fresco#1175]
can not load gif pic from url after update  to 0.10.0, show blank in SimpleDraweeView 
Change to 0.9.0 , and no find this problem

**Comment by oprisnik** [comment]
Hi! We split the Fresco library up in v0.10.0 and you have to enable GIF support by adding

```
// For animated GIF support
compile 'com.facebook.fresco:animated-gif:0.10.0'
```

to your build.gradle.

More information can be found here: http://frescolib.org/docs/index.html
