### ISSUE TITLE
Animated GIFs don't play with ProGuard

### ISSUE THREAD

**Issue by hellosure** [facebook/fresco#1177]
May I ask what's the proguard of animated-gif?

**Comment by oprisnik** [comment]
You can take a look at the [Fresco ProGuard documentation](http://frescolib.org/docs/proguard.html). If you have ProGuard issues with animated-gif, please give us more details.

**Comment by MycroftWong** [comment]
@oprisnik I copy the ProGuard text to my ProGuard file, but it's not working. It can't display gif in all  devices.

**Comment by oprisnik** [comment]
Did you add the support version for animated GIFs to your projects according to [Adding Fresco to your Project](http://frescolib.org/docs/index.html).
We made the core library smaller by making things like GIF support optional.

**Comment by MycroftWong** [comment]
`compile 'com.facebook.fresco:fresco:0.10.0'
compile 'com.facebook.fresco:animated-gif:0.10.0'
compile 'com.facebook.fresco:imagepipeline-okhttp3:0.10.0'`

`# fresco start------------------------
# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

# Keep native methods
-keepclassmembers class * {
    native <methods>;
}
-keep class com.facebook.animated.gif.** {
    *;
}

-keep class com.facebook.** {
    *;
}
-dontwarn okio.**
-dontwarn javax.annotation.**
# Keep native methods
-dontwarn com.android.volley.toolbox.**
# fresco end ------------------------`

Finally when I add below code, it's working.
`-keep class com.facebook.** {
    *;
}`

**Comment by oprisnik** [comment]
Does it work if you add `compile 'com.facebook.fresco:animated-base-support:0.10.0'`?

A stack trace for the crash could also be helpful, thanks.

**Comment by MycroftWong** [comment]
It doesn't crash and works well. It just didn't play gif when using proguard. My project's min sdk is 15.
My problem is that the proguard in ducumentation doesn't work well

**Comment by ndurell** [comment]
Sounds like #1160 maybe?

**Comment by gajicm93** [comment]
+1

Animated gifs don't work when using ProGuard minification. In non minified debug builds they work properly. There is no crash, I just see a white screen (my background is white). But I know the gif is there, it's just invisible and doesn't play.

I'm on Nexus 4, 6.0.1 Android.

**Comment by skptl** [comment]
+1

gifs not loading with proguard, no error logs.

**Comment by PiotrWpl** [comment]
+1

**Comment by justsosoxd** [comment]
+1

**Comment by yingyixu** [comment]
I've fixed this by adding this line to my proguard-rules:
`-keep class com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl {
   public AnimatedFactoryImpl(com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory, com.facebook.imagepipeline.core.ExecutorSupplier);
}`

After comparing the GIF-related code before and after obfuscation, I found that the constructor method of AnimatedFactoryImpl is removed after obfuscation. This method may be invoked by reflection elsewhere I guess.

**Comment by zhm-nico-nico-ni** [comment]
+1

and add those doesn't work

-keep class com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl { public AnimatedFactoryImpl(com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory, com.facebook.imagepipeline.core.ExecutorSupplier); }

**Comment by TimOfTheYear** [comment]
+1, @yingyixu your solution worked for me, thanks!

**Comment by YongHuiLuo** [comment]
+1 @yingyixu  thanks，it is worked for me.

**Comment by oprisnik** [comment]
We've fixed this issue in 0d0c5757ff40eb9e9f23533c9798dcdde095ce86.
With the next release, you don't need to manually change your ProGuard files any more.
Thanks for reporting!

**Comment by liutian1937** [comment]
+1
