### ISSUE TITLE
Can't set resource id for retry, failure and progressBar images

### ISSUE THREAD

**Issue by Ribesg** [facebook/fresco#1178]
As stated [here](http://stackoverflow.com/questions/36967395/why-cant-i-set-the-failure-retry-nor-progress-images-of-a-fresco-drawee-using), it feels like 3 methods are missing:
* `GenericDraweeHierarchy.setFailureImage(int resourceId)`
* `GenericDraweeHierarchy.setProgressBarImage(int resourceId)`
* `GenericDraweeHierarchy.setRetryImage(int resourceId)`

And their mirrors:
* `GenericDraweeHierarchyBuilder.setFailureImage(int resourceId)`
* `GenericDraweeHierarchyBuilder.setProgressBarImage(int resourceId)`
* `GenericDraweeHierarchyBuilder.setRetryImage(int resourceId)`

Is this by choice? Why would you have `GenericDraweeHierarchy.setPlaceholderImage(int resourceId)` and not those other methods?

**Comment by oprisnik** [comment]
You are right, we could add these methods. I don't think that there is a particular reason why we did not add this.

**Comment by oprisnik** [comment]
If you want, feel free to submit a pull request that adds this :)
