### ISSUE TITLE
Errors while migrating to 0.10.0

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#1179]
I am trying to update from 0.9.0 to 0.10.0, I face the following errors:

Cannot find SimpleDraweeView
Cannot find ScalingUtils.
I extend  the aforementioned classes to provide some common functionality in my app.

My `build.gradle` contents

```
    compile("com.facebook.fresco:fresco:${rootProject.ext.frescoVersion}")
    compile "com.facebook.fresco:animated-base-support:${rootProject.ext.frescoVersion}"
    compile "com.facebook.fresco:webpsupport:${rootProject.ext.frescoVersion}"
    compile "com.facebook.fresco:animated-webp:${rootProject.ext.frescoVersion}"
//where frescoVersion=0.10.0
```

Am I missing something.And perhaps indicating in the release that there are breaking changes would be helpful :)

**Comment by oprisnik** [comment]
Hi!

`compile 'com.facebook.fresco:fresco:0.10.0'` depends on drawee and should automatically download the artifacts required. It works for me for a demo project.

Can you try and refresh the Gradle project (`./gradlew clean build` should run without errors)? And if you're using Android Studio / IntelliJ, sync your project with Gradle again / restart it.

If this doesn't work you can always manually add the drawee dependency by adding

`compile 'com.facebook.fresco:drawee:0.10.0'`

Please let us know if this fixes the problem.

**Comment by droidekas** [comment]
Hi @oprisnik ,
 Adding the dependencies gives me the same errors(cannot find `SimpleDraweeView` and `GenericDraweeHierarchy`) .Will try to invalidate the android studio cache and retry.

**Comment by droidekas** [comment]
This just got solved.It was my fault.Sorry about that:

But still a a migration guide would really help.

I was using` R.styleable.GenericDraweeView` to build xml attributes which has now changed to `.styleable.GenericDraweeHierarchy`.  Making this changed fixed the project.
Thanks for the help :)

**Comment by droidekas** [comment]
@oprisnik I am slightly confused,the `0.10.0` release does not contain #1086 ?

**Comment by oprisnik** [comment]
@droidekas yes your change in #1086 got merged after the release cut. It will be included in the next release.

I have added the styleable change to https://github.com/facebook/fresco/releases/tag/v0.10.0

**Comment by droidekas** [comment]
Thanks!
