### ISSUE TITLE
Retrieving a Bitmap

### ISSUE THREAD

**Issue by jmcdonnell40** [facebook/fresco#118]
How can I get a bitmap, after loading an ImageRequest? I can't use the given Drawable because I need the Bitmap for custom drawing. I'm currently stealing it using a postprocessor which I know is wrong.

**Comment by tyronen** [comment]
Can you give more details on what custom drawing you are doing and why it needs a Bitmap?

**Comment by jmcdonnell40** [comment]
I was required to make an endless parallaxing background, so I needed to sample the image and draw on the canvas twice depending on the position. However, I've now managed to do this with the given Drawable!

**Comment by plamenko** [comment]
Yeah, bitmap obtained by postprocessor should never escape the scope of `process` method.
What do you mean by "sample the image"?

**Comment by jmcdonnell40** [comment]
I need to draw a section of the Bitmap onto a canvas using Rects so that I can achieve my endless parallaxing effect.

**Comment by plamenko** [comment]
You can implement a custom view as explained in http://frescolib.org/docs/writing-custom-views.html#_.
E.g.

    canvas.save();
    canvas.clip(...);
    canvas.translate(...);
    mHolder.getTopLevelDrawable().draw(canvas);
    canvas.restore();
    // repeat above code for each section you need to draw

**Comment by jmcdonnell40** [comment]
Yep, that's what I've done. As the image is huge, it's not ideal because I'm drawing way more than I need to, but it's just perfomant enough to not look laggy. Cheers.

**Comment by derekcsm** [comment]
IMO this should be re-opened there are so many scenarios (like the Palette lib for example) where developers need easy access to a bitmap or drawable directly from the `DraweeView` hooking into the image pipeline http://frescolib.org/docs/using-image-pipeline.html#_ seems far to complex for most situations.
