### ISSUE TITLE
ZoomableDraweeView double tap to zoom

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#1181]
How to implement double tap to zoom with ZoomableDraweeView.
Both Fresco(0.10.0) and ZoomableDraweeView sample code has updated, and [old example code for double tap to zoom](https://github.com/facebook/fresco/issues/86) not working.

**Comment by plamenko** [comment]
I provided code example in a duplicate issue #1183

**Comment by rafaelekol** [comment]
Thanks, it worked.
