### ISSUE TITLE
Can images in ListView contained with ScrollView be recycled correctly?

### ISSUE THREAD

**Issue by HenryBrightChao** [facebook/fresco#1185]
I know it is not recommended to use fresco with ScrollView.Thanks first.

**Comment by tyronen** [comment]
That depends on how your app works. The ListView will recycle images when you scroll the list view. But the ScrollView won't recycle anything in the ListView if you scroll the ListView itself off screen.

**Comment by HenryBrightChao** [comment]
Thanks,how does the Picasso behave with ScrollView?

**Comment by tyronen** [comment]
Picasso does not recycle images at all. They all stay in memory until the containing view is dereferenced, which may not be until the activity exits.
