### ISSUE TITLE
How to load images from Resources(R.drawable.image)?

### ISSUE THREAD

**Issue by raikecody** [facebook/fresco#119]
I'm trying to load a resource image called "R.drawable.rating_golden_crown" in a SimpleDraweeView.
But how to translate this into a  Fresco supported URI?

**Comment by jmcdonnell40** [comment]
`Uri.parse("res:///" + R.drawable.rating_golden_crown)` works for me. I think they need to make the URI syntax for resources/assets clearer.

**Comment by tyronen** [comment]
Pull request #53 should take care of this. Stay tuned.

**Comment by raikecody** [comment]
Thanks, I've used GenericDraweeHierarchy.setBackground to solve the problem temporarily. Will try the "res:///" tomorrow. I thought it's only two "/".

**Comment by lkw103037** [comment]
it's really three "/".  two "/" not work :)

**Comment by ironmanTony** [comment]
Uri uri = new Uri.Builder()
    .scheme(UriUtil.LOCAL_RESOURCE_SCHEME) // "res"
    .path(String.valueOf(resId))
    .build();
// uri looks like res:/123456789
simpleDraweeView.setImageURI(uri);

http://stackoverflow.com/questions/30887615/loading-drawable-image-resource-in-frescos-simpledraweeview
this works for me

**Comment by nbarraille** [comment]
The URI thing kinda works, but because the URI is exactly the same for all configuration, the caching will screw things up if you want different images for different languages or orientations. Can we have actual built in support for this @tyronen?

**Comment by BongJaeChoi** [comment]
"res:///" +R.drawable.xxx  is working

**Comment by chjan** [comment]
Regarding the use of res///, a suggestion would be to enable the normal use of R.drawable, and hide away the ///res. That solution gives me as a programmer nothing but a tint of extra complexity. What do you say?
