### ISSUE TITLE
Image not load properly

### ISSUE THREAD

**Issue by nihar89** [facebook/fresco#1190]
I have used fresco many times but first time i'm getting this issue regarding image not showing.
Is there because of space in the image URL or what i don't know. 

and one of image size is 1000*350 and showing like this 
![device-2016-05-05-151259](https://cloud.githubusercontent.com/assets/4938183/15040660/0121b28e-12d4-11e6-916f-1697bce4674d.png)

i don't know why image quality changes that much. The same image not showing in fixed resoltion of 100*120.

The code is: 
Uri uri = Uri.parse(list.get(position).getImgUrl());
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                        .setProgressiveRenderingEnabled(true) //Progressive loading
                        .build();
                DraweeController controller = Fresco.newDraweeControllerBuilder()
                        .setImageRequest(request)
                        .setOldController(holder.mSimpleDraweeView.getController())
                        .build();
                holder.mSimpleDraweeView.setController(controller);

any suggestion?

**Comment by plamenko** [comment]
What you see is one of the earliest progressive JPEG scans which is naturally of low quality, but gives some idea about what the image displays. You explicitly enabled this with `setProgressiveRenderingEnabled`. The question here is why the final image (of the high quality) doesn't show up. There are couple of possibilities:

* The image is still downloading and you need to wait (most likely).
* The image file is incomplete (less likely).
* An internal bug in the image pipeline (unlikely).

You can get an idea what is going on with that image by looking at the logcat as explained in the [Troubleshooting documentation](http://frescolib.org/docs/troubleshooting.html).

**Comment by oprisnik** [comment]
I assume that this problem has been resolved. Please let us know if you're still experiencing this issue.
