### ISSUE TITLE
Rounded Image use too much memory

### ISSUE THREAD

**Issue by niorgai** [facebook/fresco#1194]
I use SimpleDraweeView in RecyclerView's item,  and the xml layout is like this:

    <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/img_tag_list_avatar"
            android:layout_width="30dp"
            android:layout_height="30dp"
            fresco:roundAsCircle="true"/>

And the RecyclerView has about 200 items. when I fast scroll RecyclerView, I notice the memory increase quickly and got `OutOfMemoryError`. But it will not happen if I set `fresco:roundAsCircle="false"`.

**Comment by oprisnik** [comment]
Can you try and add `fresco:roundWithOverlayColor="@color/your_color"`? It should be more efficient if you use the overlay color rounding mode.

See also http://frescolib.org/docs/rounded-corners-and-circles.html

**Comment by niorgai** [comment]
I had try this, finally I found I should set both `fresco:roundWithOverlayColor="@color/common_white"` and `fresco:roundedCornerRadius="15dp"`.
But It was not work if I set both `fresco:roundWithOverlayColor="@color/common_white"` and `fresco:roundAsCircle="true"`. I guess set exactly radius is more efficiently.

**Comment by IanChilds** [comment]
I don't think that should be the case, but glad that you found a solution.

**Comment by niorgai** [comment]
Maybe you are right, It does not happen in my Nexus 6, but it happen in Samsung Edge. 
Thanks for all your reply.
