### ISSUE TITLE
com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary error

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#1195]
fresco version    compile 'com.facebook.fresco:fresco:0.10.0'
http://crashes.to/s/47cbe863a3c

**Comment by IanChilds** [comment]
Does this help? https://github.com/facebook/fresco/issues/239#issuecomment-102857475

**Comment by erikandre** [comment]
Closing due to lack of response
