### ISSUE TITLE
Fresco prefetch multiple pictures,How to listen progress?

### ISSUE THREAD

**Issue by lzy26fate** [facebook/fresco#1197]
I try user DataSource<Void>.**getProgress**(),but **getProgress**() return 0.0,Log print only once.
so,what am I to do?

**Comment by IanChilds** [comment]
It sounds like you are just calling `getProgress` once before the DataSource returns anything so that's why it returns 0.0. 

You need your `DataSubscriber` to implement `onProgressUpdate`.

**Comment by lzy26fate** [comment]
thx,I'm going to try it.
