### ISSUE TITLE
Android Studio Off-Line:Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable

### ISSUE THREAD

**Issue by shanquanqiang** [facebook/fresco#1199]
I use Android Studio（off-line），so i just import fresco like in eclipse ,i have add drawee， fbcore， fresco， imagepipeline ,imagepipelinebase to my project
but  there are some problems.

Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable
at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.updateBuilder(GenericDraweeHierarchyInflater.java:104)

**Comment by tyronen** [comment]
The Eclipse instructions won't work for Android Studio. You need to instead set up a local Maven repo on your machine, download Fresco into it, and then point Android Studio to use it.

**Comment by shanquanqiang** [comment]
Thanks for reply.
