### ISSUE TITLE
how get download image width and height

### ISSUE THREAD

**Issue by hexianqiao3755** [facebook/fresco#1201]
I would like to ask how to get the width of the Java code to download pictures

**Comment by IanChilds** [comment]
I'm not sure what you mean? Do you want the width of the downloaded image, or are you asking how to get the width of your view into which you want to download an image (in which case, this is not really a Fresco issue)?

**Comment by hexianqiao3755** [comment]
I need to get the width and height of the network image, know the picture width high and then to the Java code set the picture size. [   view.setLayoutParams( download image width, download image height)   ]

**Comment by IanChilds** [comment]
Why do you want to do that? You can use `ImageInfo` to get the width and the height but this approach is not recommended. It will be a very jarring experience when the image loads.

**Comment by hexianqiao3755** [comment]
Do I need a waterfall effect, the waterfall stream picture height is according to the server to set the height with pictures.
