### ISSUE TITLE
Slow to loading image in handle of main thread

### ISSUE THREAD

**Issue by alucard263096** [facebook/fresco#1203]
Hi All,

I have a map app for add the marker to map. When i load the marker from url that i start a handle to add the marker to map. In that time. I initialize the marker for loading an image. Unforturnately, it is too slow to display. It make more that 3 mintute to load <100K jpg.

**Comment by IanChilds** [comment]
This doesn't sound like a fresco issue. Perhaps your network is wrong, or something like that?

**Comment by alucard263096** [comment]
Thanks for you reply. But actually it is not a network issue. Because i use that in main thread, it is very fast. Anyway, i got unversal-image-loader is fine. I love something good the fresco did but i need to use such 2 loader in my one app.
