### ISSUE TITLE
Build fail on Mac, followed instruction but failed on :imagepipeline:ndk_build_imagepipeline

### ISSUE THREAD

**Issue by pungrue26** [facebook/fresco#1205]
I followed [Building from Source](http://frescolib.org/docs/building-from-source.html), but failed to build fresco.

my ndk version is r11c and logs :

make: /Users/MyName/Downloads/android-ndk-r11c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++: No such file or directory
make: **\* [/Users/MyName/MyDirectory/fresco/imagepipeline/build/tmp/ndk_build_imagepipeline/local/armeabi-v7a/objs/imagepipeline/exceptions.o] Error 1
:imagepipeline:ndk_build_imagepipeline FAILED
- What went wrong:
  Execution failed for task ':imagepipeline:ndk_build_imagepipeline'.
  > Process 'command '/Users/MyName/Downloads/android-ndk-r11c/ndk-build'' finished with non-zero exit value 2

**Comment by skyfishjy** [comment]
Same error
<img width="1329" alt="screen shot 2016-05-12 at 3 25 34 pm" src="https://cloud.githubusercontent.com/assets/996019/15207109/702658ce-1856-11e6-90e4-6c257f9bbd5e.png">

**Comment by wangduheng** [comment]
how  fix the error? me too  thanks

**Comment by kirwan** [comment]
Between 9 and 16 May building on the master branch was broken. Sorry about that.

Please git pull to ensure you have fb0f3f4bb056cf48bbdf290bd9e5b6626d27e42c then let us know if the problem persists.

**Comment by balazsbalazs** [comment]
btw: you can follow the status on our CI server: https://circleci.com/gh/facebook/fresco

**Comment by ffelini** [comment]
Just made pull from master.
Got this error while building comparison sample.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':samples:comparison'.
> Cannot evaluate module imagepipeline-okhttp : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Android studio doesn't see the modules. Anyone encountered same problem?

**Comment by kirwan** [comment]
The change which broke usages of okhttp has been reverted.

As for the problem with building the native libraries, try building from the command line by running `./gradlew build`.

I've heard some people say they can build the native code from the command line but not from within Studio. If this is the case for you, you should then be able to build from inside Studio as long as the C/C++ files are unchanged.

Let us know if this helps you and we'll try to resolve that issue too.

**Comment by ffelini** [comment]
@kirwan Unfortunately it didn't helped. Same problem building it from command line

**Comment by kirwan** [comment]
We have pushed a couple of fixes to the build, including one for exactly the error message @ffelini quoted. Please let us know if it still won't build in your setup.

**Comment by chthai64** [comment]
I also got the build error until I use the old version ndk 10c, not sure if that will work for you.

**Comment by snowjade** [comment]
I got the same error , with the lastest ndk and current ract-native repo .

**Comment by jgrife** [comment]
I was getting the same error with [NDK-r15](https://github.com/android-ndk/ndk/wiki). Switched to NDK-r14b and that solved this issue.
