### ISSUE TITLE
Image name with '%' can't show

### ISSUE THREAD

**Issue by AllenVork** [facebook/fresco#1206]
file:///storage/emulated/0/Download/Bluetooth/6W9[V~%DP]5`RHU1FWS[ZJX.png

file:///storage/emulated/0/Download/Bluetooth/6W9[V~%DP]5`RHU1FWS[ZJX(1).png

images of these names can't be load by Fresco

**Comment by AllenVork** [comment]
image name contains '%' will not be shown by fresco

**Comment by StevenTangJian** [comment]
I also find this bug.   my used version is 0.8.1  I want to know the lastest version have this bug? is it fixed already?

**Comment by plamenko** [comment]
Unfortunately the stock Java Uri.parse doesn't do escaping. You need to escape your string beforehand. Check this [StackOverflow](http://stackoverflow.com/questions/573184/java-convert-string-to-valid-uri-object) answer.

**Comment by AllenVork** [comment]
I've solved it by using Uri.fromFile(new File(path))
