### ISSUE TITLE
How to prefetch images in recyclerview ?

### ISSUE THREAD

**Issue by abeemukthees** [facebook/fresco#1207]
I read your docs about prefetch. (_http://frescolib.org/docs/using-image-pipeline.html#prefetching_) 
I'm not able to understand how it works. I tried : _imagePipeline.prefetchToBitmapCache(imageRequest, holder.draweeView.getContext());_
_imagePipeline.prefetchToDiskCache(imageRequest, holder.draweeView.getContext());_

I want to preload images (jpeg/png/gif) mixed types from imgur in a recylerview.  I tried this hack: _https://viksaaskool.wordpress.com/2015/08/30/how-to-do-userless-reddit-oauth-2-on-android-with-retrofit-tutorial/_ . But it is not effective. 

**Please give me an example  on how to prefetch images in a recyclerview (Linear/Grid)**, as simple as possible without fiddling with the image pipeline directly because its written "This page is intended for advanced usage only." 

I just simply want to prefetch the images so that when the user scrolls, the images are already loaded, just like your Instagram/Facebook apps. 

#913 #335

**Comment by IanChilds** [comment]
See #335

**Comment by gracevenkat** [comment]
abeemukthees... Me too struggling in the same problem. Please share your knowledge. Did you fixed this issue?
