### ISSUE TITLE
some prombles when load webp on android 4.2.2

### ISSUE THREAD

**Issue by AndroidZbb** [facebook/fresco#1208]
when i load webp on android 4.2.2,  E/unknown:WebpTranscodeConsumer: unhandled exception,why?

**Comment by eldk** [comment]
Hello,

You should give logs : Setting up logcat : http://frescolib.org/docs/troubleshooting.html

Thanks,

Eric

**Comment by AndroidZbb** [comment]
![qq 20160513100627](https://cloud.githubusercontent.com/assets/11239605/15235933/5ee7bd7c-18f2-11e6-8c74-e62b8e6864b2.png)

**Comment by AndroidZbb** [comment]
i have solved by include com.facebook.fresco:webpsupport:0.9.0+
