### ISSUE TITLE
Is it possible to set max concurrent download operation?

### ISSUE THREAD

**Issue by speedpursuer** [facebook/fresco#1210]
For example - if I want to have max set to 3, then only 3 images can be downloaded through network at the same time. Other requests would wait and will begin when any of the prior requests has been finished.

Please help advise how to implement this requirement. Thanks!

**Comment by IanChilds** [comment]
Not sure I follow. The network will only download one image at a time, right? The other requests will be queued until that one is finished.

**Comment by speedpursuer** [comment]
Thanks for your response. Please see the screenshot below. All the visible images are being downloaded at the same time.
![1 pic](https://cloud.githubusercontent.com/assets/1818577/15246676/58506172-1941-11e6-996b-3f4f24d3de6d.jpg)

When the images are large, limiting the concurrent downloading will be quicker for user to see at least one image. So I'm looking for the option I can customize the max number of images being downloaded at a time. It would be 1 or more than one (like what's shown in the screenshot).

Thank you!
