### ISSUE TITLE
fatal error: Bitmaps.h: No such file or directory

### ISSUE THREAD

**Issue by zhengziwang** [facebook/fresco#1211]
android-ndk-r11c,
detail:
./init.cpp:12:21: fatal error: Bitmaps.h: No such file or directory
 #include "Bitmaps.h"
                     ^
compilation terminated.
make: *** [/Users/wangzhengzi/Documents/Workspace/Github/fresco/imagepipeline/build/tmp/ndk_build_imagepipeline/local/armeabi-v7a/objs/imagepipeline/init.o] Error 1
make: *** Waiting for unfinished jobs....
:imagepipeline:ndk_build_imagepipeline FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_imagepipeline'.
> Process 'command 'ndk-build'' finished with non-zero exit value 2

**Comment by IanChilds** [comment]
Please follow the instructions for building from source: http://frescolib.org/docs/building-from-source.html
