### ISSUE TITLE
use fresco,quick switch and load image,the screen flashes

### ISSUE THREAD

**Issue by lzy26fate** [facebook/fresco#1216]
[https://www.youtube.com/watch?v=lOjGnJpxqw4&feature=youtu.be](url)
[https://www.youtube.com/watch?v=91D3w0jKggc&feature=youtu.be](url)
i upload to youtube,you can see screen always flashing,there is a short white space
so,how not to make these white space appear?

**Comment by lzy26fate** [comment]
https://www.youtube.com/watch?v=lOjGnJpxqw4
https://www.youtube.com/watch?v=91D3w0jKggc

The above address is invalid.

**Comment by IanChilds** [comment]
Most likely, the image is not fitting in the cache. You should make your cache bigger or download something that is the right size.
