### ISSUE TITLE
implement PlatformBitmapFactory

### ISSUE THREAD

**Issue by caoyunxuan07** [facebook/fresco#1218]
i guess if i want to create a blank bitmap (with alpha channel) but a picture for any uri, i should use this class(PlatformBitmapFactory).
Althought the method 'createBitmap(int, int)' is not abstruct, but the method only invoke to the abstruct method 'createBitmap(int ,int, config)' which i dont know how to implement.
```
public abstract class PlatformBitmapFactory {
  public abstract CloseableReference<Bitmap> createBitmap(
      int width,
      int height,
      Bitmap.Config bitmapConfig);

  public CloseableReference<Bitmap> createBitmap(int width, int height) {
    return createBitmap(width, height, Bitmap.Config.ARGB_8888);
  }
```

i only want to simply implement it for create a bitmap and get its Reference.

**Comment by plamenko** [comment]
You should probably not be using `PlatformBitmapFactory` directly. Can you give us more context on what you are trying to achieve?

I don't understand the "blank bitmap (with alpha channel) but a picture for any uri" part. Is it a blank bitmap or is it a bitmap that shows image pointed by a specific uri?

**Comment by caoyunxuan07** [comment]
What I want to achieve is create a reference of Bitmap but do not consume my app's memory(just like DraweeView do).
And I have two demands:
One is : get a reference of some new bitmap, same as `Bitmap.createBitmap()`, I would save their reference in a List, and then take the reference, further get them, additional draw some thing on them.(more than once)
Two is : get a reference of a drawable and it should be a  bitmap,  same as `BitmapFactory.decodeXXX()`. I would save its reference in a global variable, and then take the reference, further get it, use it `Canvas canvas = new Canvas(Bitmap);`(more than once too)

Now I try to do like one of implements of PlatformBitmapFactory `ArtBitmapFactory`
```
int sizeInBytes = BitmapUtil.getSizeInByteForBitmap(width, height, bitmapConfig);
    Bitmap bitmap = mBitmapPool.get(sizeInBytes);
    Bitmaps.reconfigureBitmap(bitmap, width, height, bitmapConfig);
    return CloseableReference.of(bitmap, mBitmapPool);
```
but memory increased.

**Comment by plamenko** [comment]
You should not be implementing `PlatformBitmapFactory`, we already did that. You can just get its instance from Fresco and create a bitmap directly:

```
CloseableReference<Bitmap> bitmapRef = Fresco.getImagePipelineFactory().getPlatformBitmapFactory().createBitmap(width, height);
```

However, keep in mind that you are responsible for managing the lifetime of your bitmap and you need to call `bitmapRef.close()` once you don't need the bitmap anymore.

**Comment by caoyunxuan07** [comment]
yes, it worked, thanks anyway. But my memory increased. 
Can I create the bitmap in Fresco special cache(like DraweeView) and only get references on my app's memory?
