### ISSUE TITLE
when can  make gif achieve round?

### ISSUE THREAD

**Issue by weizongwei5** [facebook/fresco#1219]
when can  make gif achieve round? next version?

**Comment by oprisnik** [comment]
Hi!

Rounded corners with animated GIFs are supported if you use the OVERLAY_COLOR rounding mode.
You just have to add `fresco:roundWithOverlayColor="@color/your_color"` to your DraweeView in XML. You can also set this in code. More information on rounding modes can be found here: http://frescolib.org/docs/rounded-corners-and-circles.html

The BITMAP_ONLY rounding mode currently does not support animated GIFs as you've noticed.

**Comment by weizongwei5** [comment]
yeah, i know.  

OVERLAY_COLOR  not supoort  "@color/transparent“
i  need BITMAP_ONLY  rounding  mode.  

BITMAP_ONLY  rounding  mode, next version can support?

**Comment by kirwan** [comment]
I don't think we currently plan to support that rounding mode for animated gifs and as you've seen the overlay color must be an opaque color, `@color/transparent` won't work.

**Comment by weizongwei5** [comment]
yeah, maybe you are right.
