### ISSUE TITLE
some problem that display circle image in RecyclerView with GridLayoutManager,android6.0 nexus5x

### ISSUE THREAD

**Issue by tanghuai** [facebook/fresco#1221]
always no response when I use circle image in in RecyclerView with GridLayoutManager.
The test terminal is Nexus5x,android6.0
have somebody has the same problem?

**Comment by plamenko** [comment]
By "some problem" and "no response", do you mean the image doesn't load?
For "circle", do you mean `roundAsCircle`? If so, is the rounding part important? If you remove rounding, do images load?

**Comment by tanghuai** [comment]
Yes,I use roundAsCircle attr.
If I remove rounding,it's no problem.

**Comment by erikandre** [comment]
Closing as we've had no further reports of this issue
