### ISSUE TITLE
DataFetchProducer returns StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Rj-ku** [facebook/fresco#1223]
int commaPos = uri.indexOf(44); returns -1 because there is no comma in my file path as it shouldn't be, i don't understand why the DataFetchProducer searches for a comma to begin with!!
I've checked with FileInputStream and indeed the file exists.
and this is how i built the Uri.
`
Uri uri = new Uri.Builder()
                .scheme(UriUtil.DATA_SCHEME)
                .path(image.getPath())
                .build();
`
and this is the `Uri.getString();`
uri = data:/data/data/com.example.ranj.android_project/cache/c451907d-6cc0-4170-96a2-7951c7aec40b

**Comment by plamenko** [comment]
This is not the format of the data uri. The syntax of data URIs was defined in Request for Comments (RFC) 2397, published in August 1998, and follows the URI scheme syntax. A data URI consists of:

```
data:[<media type>][;charset=<character set>][;base64],<data>
```

Observe that the data is separated from the preceding part by a comma (,). This comma is not optional.

**Comment by plamenko** [comment]
Can't you use the file scheme instead? Also, check the [supported uris](http://frescolib.org/docs/supported-uris.html).
