### ISSUE TITLE
Do I use a wrong version of NDK ?

### ISSUE THREAD

**Issue by ffelini** [facebook/fresco#1226]
@tyronen
I'm trying to run locally fresco samples and I get this error. I'm on MAc and looks like I have the latest version of NDK.

[armeabi-v7a] Compile        : bitmaps <= Bitmaps.c
make: /Users/vturcan/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc: No such file or directory
[armeabi] Compile        : bitmaps <= Bitmaps.c
make: Circular /Users/vturcan/Studio <- /Users/vturcan/Studio dependency dropped.
make: Circular /Users/vturcan/Studio <- /Users/vturcan/Studio dependency dropped.
make: /Users/vturcan/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc: No such file or directory
[arm64-v8a] Compile        : bitmaps <= Bitmaps.c
make: *** [Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/armeabi-v7a/objs/bitmaps/Bitmaps.o] Error 1
make: *** Waiting for unfinished jobs....
make: /Users/vturcan/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.8/prebuilt/darwin-x86_64/bin/aarch64-linux-android-gcc: No such file or directory
[x86] Compile        : bitmaps <= Bitmaps.c
make: *** [Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/armeabi/objs/bitmaps/Bitmaps.o] Error 1
make: /Users/vturcan/Library/Android/sdk/ndk-bundle/toolchains/x86-4.8/prebuilt/darwin-x86_64/bin/x86-gcc: No such file or directory
make: *** [Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/arm64-v8a/objs/bitmaps/Bitmaps.o] Error 1
make: *** [Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/x86/objs/bitmaps/Bitmaps.o] Error 1
:imagepipeline:ndk_build_bitmaps FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> Process 'command '/Users/vturcan/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.561 secs
Process 'command '/Users/vturcan/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

**Comment by plamenko** [comment]
Have you checked [StackOverflow](http://stackoverflow.com/questions/14307611/problems-compiling-object-using-arm-linux-androideabi-gcc) ?

**Comment by plamenko** [comment]
Duplicate, let's track this in  #1205
