### ISSUE TITLE
https  Image

### ISSUE THREAD

**Issue by myxfeng** [facebook/fresco#1227]
# https  imgae    
**don't support https  imgae    **

**Comment by kirwan** [comment]
Fresco does support HTTPS images.

We would need more information to be able to help here.

If your image is failing to load, look at LogCat to see what error is shown. It could be a certificate problem.

**Comment by myxfeng** [comment]
expmple :   https://community.apicloud.com/bbs/data/attachment/forum/201602/01/191807lkn96kh86ezfxk8h.jpg


What does Fresco need to configure for HTTPS imgaes  ?

**Comment by kirwan** [comment]
I just put that URL into the Uri sample app included in Fresco and the image appeared. That app doesn't have anything unusual setup for Fresco.

One thing which may help you debug is to add logging and look at the output.

Try this and look at Logcat.

```
Set<RequestListener> listeners = new HashSet<>();
listeners.add(new RequestLoggingListener());
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
    .setRequestListeners(listeners)
    .build();
```

**Comment by myxfeng** [comment]
I find the reasons is because the open Fiddler Web Debugger causes the image did not appeared，

image can be appeared with 4G network 


final  my english is bad ,   thanks  your  help !!!
