### ISSUE TITLE
Bug: AsCircle Fail!!!

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#123]
url="http://ktvme.qiniudn.com/jpg/9fc174b15b7d3aaa0d0933759d63c492.jpg"
I want to show as circle, but it just show as rect.

**Comment by ICECHN** [comment]
The view's size is larger than the picture.

**Comment by ICECHN** [comment]
The view's size is larger than the picture.

**Comment by ICECHN** [comment]
The view's size is larger than the picture.

**Comment by ICECHN** [comment]
The view's size is larger than the picture.

**Comment by ICECHN** [comment]
The view's size is larger than the picture.

**Comment by ICECHN** [comment]
The view's size is larger than the picture.

**Comment by ICECHN** [comment]
The sample code:
 ImageRequest imageRequest =
        ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
            .setResizeOptions(
                new ResizeOptions(100, 100))//view.getLayoutParams().width, view.getLayoutParams().height))
            .build();

The Setting does not work.

**Comment by plamenko** [comment]
I don't understand the issue. If you have a big rounded frame and a small picture inside it, the image won't be rounded, of course. You either need to use a smaller view or scale the image (with scale type, not with the resize options.)
See http://frescolib.org/docs/resizing-rotating.html#_
