### ISSUE TITLE
It’s slow on loading high-resolution gif

### ISSUE THREAD

**Issue by ParkGiTae** [facebook/fresco#1231]
It’s too slow on loading high-resolution gif

**Comment by ParkGiTae** [comment]
https://americanbridgepac.org/app/uploads/unnamed-6.gif

**Comment by YGDroid** [comment]
i faced same problem. i using fresco 0.10 version.
high-resolution animated gif loding delayed about 5s more than other normal-resolution animated gif.
could you help me?

**Comment by eldk** [comment]
Hello,

I download the picture given in url, from France, and more than 6s are needed in desktop browser.

curl request : 

`curl 'https://americanbridgepac.org/app/uploads/unnamed-6.gif' -H 'Host: americanbridgepac.org' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:46.0) Gecko/20100101 Firefox/46.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'`

`"cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 286,
          "send": 0,
          "wait": 287,
          "receive": 5849
        }`

Eric

**Comment by kirwan** [comment]
I just took a look and that GIF is 2.5MB so I'm not surprised that it takes some time to download.

**Comment by ParkGiTae** [comment]
i'm save the image of the link to the local storage
but it seems that still takes a lot of time GIF decode only. 
Do you know the problem of high resolution GIF?

**Comment by tyronen** [comment]
As @kirwan said, this is a 1920x1076 image with 26 frames. The decode has to do this frame by frame. It will take a while.
