### ISSUE TITLE
How can fresco display the full quality image?

### ISSUE THREAD

**Issue by MycroftWong** [facebook/fresco#1232]
Some of my images are blurry.
When using downsample for global, how can I display the full quality images?

**Comment by MycroftWong** [comment]
When using downsample for global, how can I display the full quality images?

**Comment by tyronen** [comment]
This likely means your `ResizeOptions` are too small. Try increasing it to the actual size you need to display.

**Comment by MycroftWong** [comment]
@tyronen I found it in document, thanks anyway.

**Comment by hoanghunguet** [comment]
Hello. I same use fresco library and don't show full screen my image. Can you help me ? Please!
