### ISSUE TITLE
Unable to load DiskCacheConfig class

### ISSUE THREAD

**Issue by OrangeHao** [facebook/fresco#1234]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/cache/disk/DiskCacheConfig;

**Comment by OrangeHao** [comment]
how to solve this problem

**Comment by tyronen** [comment]
How are you building? Did you follow the [instructions](http://frescolib.org/docs/index.html)?

If so, please post your `build.gradle` file here.

**Comment by OrangeHao** [comment]
oh,it's my fault,i was initialized the fresco twice,so the problem occurs
