### ISSUE TITLE
Autorotate not supporting inverted orientations

### ISSUE THREAD

**Issue by kcdbox** [facebook/fresco#1237]
Fresco is missing autoOrientation support for inverted exif orientations.
Orientations 1, 3, 6, 8 get corrected, but 2, 4, 5, 7 not.
Exif Orientations
![Exif Orientations](http://www.daveperrett.com/images/articles/2012-07-28-exif-orientation-handling-is-a-ghetto/EXIF_Orientations.jpg)
Examples
![screenshot_20160524-123512](https://cloud.githubusercontent.com/assets/1330997/15501208/8146f582-21ac-11e6-93a7-03bf6c803700.png)
![screenshot_20160524-123518](https://cloud.githubusercontent.com/assets/1330997/15501207/8145862a-21ac-11e6-8c03-2b1950c0a35e.png)
![screenshot_20160524-123525](https://cloud.githubusercontent.com/assets/1330997/15501206/8142d740-21ac-11e6-96f7-5fdbc02ab9a6.png)
![screenshot_20160524-123532](https://cloud.githubusercontent.com/assets/1330997/15501205/81427444-21ac-11e6-8e85-afb1ee480c33.png)

**Comment by plamenko** [comment]
Yep, this is a known limitation.

**Comment by oprisnik** [comment]
This feature has been added by @franzks in d25944a2ac2f5b7e865140ab0ee77ab2c70e4c90
