### ISSUE TITLE
ProgressBarDrawable.onLevelChange() always 10000

### ISSUE THREAD

**Issue by YoonKyoungTae** [facebook/fresco#1240]
Hi,
I'm using Big size GIF image for fresco, so i want use progressbar.
However, ProgressBarDrawable.onLevelChange() is always input 10000.
why onLevelChange () method without doing input 0-10000 ?

so, When the call GenericDraweeHierarchy.setProgress()

Answers I'll wait

**Comment by plamenko** [comment]
At the moment, progress is only being reflected for downloading. If you already have the image downloaded and in one of our caches, the reported progress will be 10000 (i.e. 100%). In most cases this is good enough as the total time to display an image is being dominated by network fetch. However, decoding can also take a non trivial amount of time if the image is large. This is what most likely you are seeing and unfortunately we currently do not support decoding progress. We might add this feature some time in the future.

**Comment by YoonKyoungTae** [comment]
It has been a lot of Note, thanks your help
