### ISSUE TITLE
Fresco cannot load custom drawable

### ISSUE THREAD

**Issue by qbeenslee** [facebook/fresco#1244]
using fresco load resource like:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true" android:drawable="@drawable/pic_pressed" />
    <item android:drawable="@drawable/pic_normal" />
</selector>
```

And fresco report `failure: java.lang.IllegalArgumentException: unknown image format`

**Comment by oprisnik** [comment]
How do you set the resource? Placeholder? What are you trying to do?

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
