### ISSUE TITLE
Bugs in EXIF auto-rotation for loaded images

### ISSUE THREAD

**Issue by jmbusby** [facebook/fresco#1247]
I see that there is an API available on `ImageRequestBuilder` to enable and disable auto-rotation of images with EXIF data. I am having some issues getting it to work with my code:
1. Auto-rotation seems to be enabled by default, although this does not seem to be mentioned in the docs at all as far as I can see.
2. When I try to disable it with `ImageRequestBuilder.setAutoRotateEnabled(false)`, the image still gets auto-rotated. Is this a bug?
3. When an auto-rotated image finishes loading and the listener invokes `BaseControllerListener.onFinalImageSet()`, the width and height values reported in `ImageInfo` do not reflect the rotation that has been performed. For example, a 1024x512 image with EXIF rotation 6 reports its width x height as 1024x512, not 512x1024 as I would expect.

UPDATE: I found [this](http://stackoverflow.com/questions/34514161/android-how-to-rotate-image-using-fresco) post on StackOverflow. Seems my problem is because I have enabled downsampling? Is there a fix in the works for this? Also, the documentation ought to be updated to mention this caveat with downsampling to save other people from wasting time trying to fix it.

**Comment by jmbusby** [comment]
I see a tag of "bug" has been added. Is this a known issue? Any workaround available?

**Comment by jmbusby** [comment]
I found [this](http://stackoverflow.com/questions/34514161/android-how-to-rotate-image-using-fresco) post on StackOverflow. Seems my problem is because I have enabled downsampling? Is there a fix in the works for this? Also, the documentation ought to be updated to mention this caveat with downsampling to save other people from wasting time trying to fix it.

**Comment by jmbusby** [comment]
Is there any response on this issue? I see it got labelled as a bug back in May, and now it is August. Anyone able to answer my questions?

**Comment by kirwan** [comment]
I've just completed a series of changes to be included in the next Fresco release.

This adds a `RotationOptions` class which can be specified when building an image request. As well as having a new API, several fixes have been made with respect to rotation when downscaling is enabled, when a postprocessor is attached and other cases we were aware of.

The initial commit for these changes is 36dd783.

When the new release is made (or sooner if you'd like to build from source and test with that) I'd be interested to know if this resolves your use case.

**Comment by kirwan** [comment]
I think there may be a little confusion here about what auto-rotate means though and I will update the docs when the new API is released in Fresco 0.14.0.

Where an image has been stored with metadata to define a rotation, auto-rotate needs to be turned on to see the image oriented correctly.

I think your problem was that when downsampling was on, the rotation wasn't being done, not that it couldn't be stopped.

**Comment by daerimin** [comment]
I've run into this same issue today using 0.14.1.  When .setResizeOptions() is specified, the .setRotationOptions(RotationOptions.autoRotate()) does not work.  If I leave out the .setResizeOptions(), the auto-rotation works.

**Comment by sdeira** [comment]
The same is happening to me, any workaround?

**Comment by jmbusby** [comment]
For what it's worth, I recently updated Fresco to v1.5.0 and this issue is now definitely fixed for me. Thanks!
