### ISSUE TITLE
can not show image with the size of 3.9M 

### ISSUE THREAD

**Issue by jasminezz** [facebook/fresco#1250]
The image is 5312x2988 and it's size is 3.9M.
When I user SimpleDraweeView.setImageUrI, callback is onFinalImageSet, but the imge is not show in my phone.
After using ResizeOptions(1280,720), the picture can show.
Why？ Is Fresco has image loading limitation?

**Comment by tyronen** [comment]
No, Android itself does. Most devices cannot display more than 4096x4096, and many can't do more than 2048x2048. The OpenGL subsystem can't render an image like that, which is much bigger than a mobile screen anyway.
