### ISSUE TITLE
How could I stop or cancel  a already ImageRequest by myself when many uris set to only one ImageView

### ISSUE THREAD

**Issue by SimplySu** [facebook/fresco#1254]
Hi friends.

I have got the same problem like Issues: IndexOutOfBoundsException - RecycleView #925
this will be happened random

ErrorLog:
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)at com.facebook.drawee.controller.ForwardingControllerListener.onFailure(ForwardingControllerListener.java:133)
……

from the message :
[ **This may happen if for example you have a controller listener that onFailure attempts to set a new Uri to the DraweeView.**]

For that i will use a ImageView to load many uris, so i want to cancel or stop the before ImagRequest when set to a new uri,but i can't find any method ?how to deal with this situations?

**Comment by michalgr** [comment]
Could you explain what do you want to do ? Drawee already[supports [loading images from multiple sources](http://frescolib.org/docs/requesting-multiple-images.html). Can you use that ?

**Comment by plamenko** [comment]
Once you set a new uri to a DraweeView, the previous request will automatically get cancelled. You should not cancel anything explicitly.

As for the crash you are seeing, please provide the code of your controller listener.

**Comment by SimplySu** [comment]
Sorry for later, I changed my way of imageRequest and DraweeView that i haven't found this problem again.
for the crash was random happened, i focus attention on it once happened.
