### ISSUE TITLE
android:scaleType="fitCenter" can not work well

### ISSUE THREAD

**Issue by jasminezz** [facebook/fresco#1255]
As photo shows below, I use the same image,and the scaleType are "fitCenter". The left is displayed by SimpleDraweeView, right is displayed by ImageView. Apparently, SimpleDraweeView zoom in the image, Why?
When I use the scaleType "centerInside",the resut is the same. It seems the scaleType cannot work?
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/network_image_view"
        android:layout_width="200dp"
        android:layout_height="200dp"
        fresco:actualImageScaleType="centerInside"
         />
    <ImageView
        android:id="@+id/network_image_view1"
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:scaleType="fitCenter"/>

I use
![fresco_vs_imageview](https://cloud.githubusercontent.com/assets/16434016/15650148/226c2350-26a9-11e6-8b1b-a21d0f6a7676.png)

**Comment by jasminezz** [comment]
I solved it

**Comment by nidhiAscra** [comment]
how u solved?

**Comment by RiteshAdulkar** [comment]
@jasminezz how u solved?
