### ISSUE TITLE
The item of my recyclerview always swap

### ISSUE THREAD

**Issue by Rickyballs** [facebook/fresco#1256]
There is a problem about the method resize.
Here is my code:

```
int width = 495, height = 335;
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
    .setResizeOptions(new ResizeOptions(width, height))
    .build();

PipelineDraweeController controller = Fresco.newDraweeControllerBuilder()
    .setOldController(mDraweeView.getController())
    .setImageRequest(request)
    .setControllerListener(new MyBaseController())
    .build();
mSimpleDraweeView.setController(controller);
```

MyBaseController()

```
public void onFinalImageSet(String id,ImageInfo imageInfo,Animatable animatable){
          super.onFinalImageSet(id,imageInfo,animatable);
          Log.e("FrescoSize","width:"+imageInfo.getWidth()+" height:"+imageInfo.getHeight());
}
```

Origin Size:width:1024 height:695
Resize Size:width:495 height:335
ImageInfo Size:width:512 height:348

Only if I excute the API notifyDataSetChange() and then scroll to the top,the item position always move.I don't know how to deal with it.

**Comment by Rickyballs** [comment]
@kangax @daaku @natacado @bricooke @aizatto

**Comment by Rickyballs** [comment]
@kangax @daaku @natacado @bricooke @aizatto @tyronen @plamenko

**Comment by michalgr** [comment]
Could you explain what do you mean by "the item position always move" ?

When it comes to dimensions of resized image - Fresco can't resize images to arbitrary dimensions. Scalling factor is always a fraction with denominator equal to 8, see [here](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/imagepipeline/src/main/java/com/facebook/imagepipeline/nativecode/JpegTranscoder.java#L31-L33).

**Comment by Rickyballs** [comment]
@michalgr a sample moving item:

http://i.imgur.com/FUapm2K.gif?1

if you play (scroll up and down) you can discover more interesting animation

**Comment by Rickyballs** [comment]
The same issuse in stackoverflow [https://stackoverflow.com/questions/37639883/using-fresco-with-staggeredgridlayoutmanager-cause-moving-items](url)

**Comment by embydextrous** [comment]
I think this issue has nothing to do with fresco. While using StaggeredGridLayoutManager, keep in mind that height of the items is set before loading image and does not change. Don't make your item wrap content. Because when image loads size of viewholder changes and staggered grid layout manager arranges items to fit them in best positions.

I am using fresco with resizing in staggeredgridlayoutmanager and my api returns us the size of each image on the basis of which I calculate viewholder size and set it to that size before image is loaded.
Before that I was also facing the same problem and I was using picasso.

We named it 'Dancing Items Problem'.

**Comment by Rickyballs** [comment]
I think I've done it（holder.picture.setLayoutParams(params)） before loading.

@embydextrous 
Can you give me a sample demo or keycode of the progress.I don't know how to do it right.

**Comment by embydextrous** [comment]
private void setProductThumbnail(final ProductHolder holder, final Product product) {
        double aspect = product.getHeight() / (double) product.getWidth();
        holder.ivThumb.getLayoutParams().height = (int) (aspect * (Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6)));
        holder.ivThumb.requestLayout();
        holder.mask.setVisibility(View.GONE);
        boolean isDisapprovedProduct = PrefUtils.getUserId(mContext)==product.getProductUserInfo().getUserid()&&product.isDeleted()==2&&product.isAvailable();
        if(isDisapprovedProduct){
            holder.disapprovedTv.setVisibility(View.VISIBLE);
        } else {
            holder.disapprovedTv.setVisibility(View.GONE);
        }
        if(product.getThumbnail()!=null) {
            ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(Uri.parse(product.getThumbnail()))
                    .setResizeOptions(new ResizeOptions(Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6), (int) (aspect * Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6))))
                    .setPostprocessor(isDisapprovedProduct?new GrayscalePostprocessor():null);
            PipelineDraweeController pipelineDraweeController = (PipelineDraweeController) Fresco.newDraweeControllerBuilder().setImageRequest(imageRequestBuilder.build())
                    .setOldController(holder.ivThumb.getController())
                    .setControllerListener(new ControllerListener<ImageInfo>() {
                        @Override
                        public void onSubmit(String id, Object callerContext) {

                        }

                        @Override
                        public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                            holder.mask.setVisibility(View.VISIBLE);
                        }

                        @Override
                        public void onIntermediateImageSet(String id, ImageInfo imageInfo) {

                        }

                        @Override
                        public void onIntermediateImageFailed(String id, Throwable throwable) {

                        }

                        @Override
                        public void onFailure(String id, Throwable throwable) {
                            holder.mask.setVisibility(View.GONE);
                        }

                        @Override
                        public void onRelease(String id) {

                        }
                    })
                    .build();
            holder.ivThumb.setController(pipelineDraweeController);
        } else {
            holder.mask.setVisibility(View.GONE);
            holder.ivThumb.setController(null);
        }
    }

**Comment by embydextrous** [comment]
private void setProductThumbnail(final ProductHolder holder, final Product product) {
        double aspect = product.getHeight() / (double) product.getWidth();
        holder.ivThumb.getLayoutParams().height = (int) (aspect * (Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6)));
        holder.ivThumb.requestLayout();
        holder.mask.setVisibility(View.GONE);
        boolean isDisapprovedProduct = PrefUtils.getUserId(mContext)==product.getProductUserInfo().getUserid()&&product.isDeleted()==2&&product.isAvailable();
        if(isDisapprovedProduct){
            holder.disapprovedTv.setVisibility(View.VISIBLE);
        } else {
            holder.disapprovedTv.setVisibility(View.GONE);
        }
        if(product.getThumbnail()!=null) {
            ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(Uri.parse(product.getThumbnail()))
                    .setResizeOptions(new ResizeOptions(Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6), (int) (aspect * Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6))))
                    .setPostprocessor(isDisapprovedProduct?new GrayscalePostprocessor():null);
            PipelineDraweeController pipelineDraweeController = (PipelineDraweeController) Fresco.newDraweeControllerBuilder().setImageRequest(imageRequestBuilder.build())
                    .setOldController(holder.ivThumb.getController())
                    .setControllerListener(new ControllerListener<ImageInfo>() {
                        @Override
                        public void onSubmit(String id, Object callerContext) {

                        }

                        @Override
                        public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                            holder.mask.setVisibility(View.VISIBLE);
                        }

                        @Override
                        public void onIntermediateImageSet(String id, ImageInfo imageInfo) {

                        }

                        @Override
                        public void onIntermediateImageFailed(String id, Throwable throwable) {

                        }

                        @Override
                        public void onFailure(String id, Throwable throwable) {
                            holder.mask.setVisibility(View.GONE);
                        }

                        @Override
                        public void onRelease(String id) {

                        }
                    })
                    .build();
            holder.ivThumb.setController(pipelineDraweeController);
        } else {
            holder.mask.setVisibility(View.GONE);
            holder.ivThumb.setController(null);
        }
    }

**Comment by embydextrous** [comment]
`private void setProductThumbnail(final ProductHolder holder, final Product product) {
        double aspect = product.getHeight() / (double) product.getWidth();
        holder.ivThumb.getLayoutParams().height = (int) (aspect * (Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6)));
        holder.ivThumb.requestLayout();
        holder.mask.setVisibility(View.GONE);
        boolean isDisapprovedProduct = PrefUtils.getUserId(mContext)==product.getProductUserInfo().getUserid()&&product.isDeleted()==2&&product.isAvailable();
        if(isDisapprovedProduct){
            holder.disapprovedTv.setVisibility(View.VISIBLE);
        } else {
            holder.disapprovedTv.setVisibility(View.GONE);
        }
        if(product.getThumbnail()!=null) {
            ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(Uri.parse(product.getThumbnail()))
                    .setResizeOptions(new ResizeOptions(Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6), (int) (aspect * Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6))))
                    .setPostprocessor(isDisapprovedProduct?new GrayscalePostprocessor():null);
            PipelineDraweeController pipelineDraweeController = (PipelineDraweeController) Fresco.newDraweeControllerBuilder().setImageRequest(imageRequestBuilder.build())
                    .setOldController(holder.ivThumb.getController())
                    .setControllerListener(new ControllerListener<ImageInfo>() {
                        @Override
                        public void onSubmit(String id, Object callerContext) {

                        }

                        @Override
                        public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                            holder.mask.setVisibility(View.VISIBLE);
                        }

                        @Override
                        public void onIntermediateImageSet(String id, ImageInfo imageInfo) {

                        }

                        @Override
                        public void onIntermediateImageFailed(String id, Throwable throwable) {

                        }

                        @Override
                        public void onFailure(String id, Throwable throwable) {
                            holder.mask.setVisibility(View.GONE);
                        }

                        @Override
                        public void onRelease(String id) {

                        }
                    })
                    .build();
            holder.ivThumb.setController(pipelineDraweeController);
        } else {
            holder.mask.setVisibility(View.GONE);
            holder.ivThumb.setController(null);
        }
    }`

**Comment by embydextrous** [comment]
I am calling method this inside my adapter's onBindViewHolder method:

```
private void setProductThumbnail(final ProductHolder holder, final Product product) {
        double aspect = product.getHeight() / (double) product.getWidth();      //calculate aspect ratio
        holder.ivThumb.getLayoutParams().height = (int) (aspect * (Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6)));   //set height as width is decided automatically by staggered grid layout manager
        holder.ivThumb.requestLayout();    //important to get new params rendered, I think you are missing this part

       //Setting resize options equal to drawee view width and height for faster image loading and smoother scrolling
        ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(Uri.parse(product.getThumbnail()))
                    .setResizeOptions(new ResizeOptions(Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6), (int) (aspect * Utils.getScreenWidth(mContext) / 2 - Utils.dpToPx(6))))
                    .setPostprocessor(isDisapprovedProduct?new GrayscalePostprocessor():null);
            PipelineDraweeController pipelineDraweeController = (PipelineDraweeController) Fresco.newDraweeControllerBuilder().setImageRequest(imageRequestBuilder.build())
                    .setOldController(holder.ivThumb.getController())
                    .build();
            holder.ivThumb.setController(pipelineDraweeController);
    }
```

**Comment by oprisnik** [comment]
We have an example for displaying images in a RecyclerView here:

https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeRecyclerViewFragment.java

Otherwise, I suggest to ask the general question about view recycling on Stackoverflow since it's unrelated to Fresco.
