### ISSUE TITLE
下载的.so文件导致我的项目崩溃

### ISSUE THREAD

**Issue by a63622110** [facebook/fresco#1261]
依赖后，会下载包含各种cpu的.so文件，但是我的项目里只有armeabi,这样就导致了我的.so文件运行不到手机里。怎么下载指定的cpu类型.so文件？

**Comment by longya3xian** [comment]
你可以在build.gradle里面进行如下配置：
    buildTypes {
        release {
            ndk {
                abiFilters "armeabi"
            }
         
        }
        debug {
            ndk {
                abiFilters "armeabi"
            }
｝

**Comment by michalgr** [comment]
Thanks longya3xian. @a63622110: also have a look at our documentation here: http://frescolib.org/docs/multiple-apks.html
