### ISSUE TITLE
below Android 18, about pin Bitmap.when the bitmap unpin.

### ISSUE THREAD

**Issue by rooneyGG** [facebook/fresco#1262]
In Fresco, I find it can pin bitmap below Android 18; but when closeableBitmap is being cloed, it not call unpin bitmap. so I feel the bitmap pinned can not be released. please tell me the reason.

I want to kown the reason crizing, so please help me. thank you.

**Comment by michalgr** [comment]
When `CloseableBitmap` is closed [this](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/BitmapCounter.java#L54) code is executed. Recycle will release the bitmap even if it is pinned.
