### ISSUE TITLE
Support Netscape Application Loop Block (GIFs)

### ISSUE THREAD

**Issue by lvpengwei** [facebook/fresco#1263]
I found that the `loopcount` is not assigned in `animated-gif/src/main/jni/gifimage/gif.cpp` but assigned in `animated-webp/src/main/jni/webpimage/webp.cpp`

**Comment by michalgr** [comment]
It seems that there is no loop count in basic gif, it was added in netscape extension. I'll repurpose this issue as enhancement to add support for that.

**Comment by oprisnik** [comment]
This has been fixed with 95359b9cb7650cf00b362ffbc018e90d503d476b
