### ISSUE TITLE
Debug.getNativeHeapSize() never decreases

### ISSUE THREAD

**Issue by cwkcyd** [facebook/fresco#1264]
test Android 4.1.2 And 4.4.4

project **fresco/samples/comparison**

I changed some values in MainActivity as follows:

public static int calcDesiredSize(Context context, int parentWidth, int parentHeight) {
    int orientation = context.getResources().getConfiguration().orientation;
    int desiredSize = (orientation == Configuration.ORIENTATION_LANDSCAPE) ?
            **parentHeight / 12 : parentHeight / 12;**
    return Math.min(desiredSize, parentWidth);
  }

**Then, I load local images, which most of them are large map， w * h = 4100 * 3100,  sizes were 3.5-7.2MB. After loading a large number of local images, crash.**

if I change **COLS_NUMBER  = 6** again; it would become more easier;
private static final int COLS_NUMBER = 3;

Debug.getNativeHeapSize() : **raise up always , not decline**

When Debug.getNativeHeapAllocatedSize() raise, Debug.getNativeHeapSize() follow the raise, and when Debug.getNativeHeapAllocatedSize() declined, Debug.getNativeHeapSize() did not follow the decline

if I change MemoryCacheParams second param 64, It becomes a bit better, or no cache

final MemoryCacheParams bitmapCacheParams = new MemoryCacheParams(
        ConfigConstants.MAX_MEMORY_CACHE_SIZE, // Max total size of elements in the cache
            **64,                     // Max entries in the cache**
        ConfigConstants.MAX_MEMORY_CACHE_SIZE, // Max total size of elements in eviction queue
            Integer.MAX_VALUE,                     // Max length of eviction queue
            Integer.MAX_VALUE);

I don't know what is Max entries Related to native memory, thanks!

**Comment by cwkcyd** [comment]
This project is Fresco official sample, 
**link https://github.com/facebook/fresco/tree/master/samples/comparison,** 
And I modify some values in MainActivity, as follow:

public static int calcDesiredSize(Context context, int parentWidth, int parentHeight) {
int orientation = context.getResources().getConfiguration().orientation;
int desiredSize = (orientation == Configuration.ORIENTATION_LANDSCAPE) ?
**parentHeight / 12 : parentHeight / 12;** 
return Math.min(desiredSize, parentWidth);
}

if I change COLS_NUMBER = 6 again; it would become crash more easier;
**private static final int COLS_NUMBER = 3;**

**Comment by michalgr** [comment]
`Debug.getNativeHeapSize()` is not supposed to go down. The implementation delegates to mallinfo and returns highwater mark.

https://android.googlesource.com/platform/frameworks/base/+/kitkat-mr2.2-release/core/jni/android_os_Debug.cpp#123
http://man7.org/linux/man-pages/man3/mallinfo.3.html

**Comment by cwkcyd** [comment]
native memory reaches 1gb, then **App crash**. Especially a lot of  image display on Screen.Can you try to it ? Thanks!!
