### ISSUE TITLE
Animated WebP image in ListView - flickering issue

### ISSUE THREAD

**Issue by Wbreadboy** [facebook/fresco#1266]
I'm developing Android chatting App, use animated image WebP in ListView.
But, It was flickering when send and receive the message everytime.
what should i do.......

https://youtu.be/ADLXdwwhiUs

**Comment by michalgr** [comment]
I suppose something in the way you append new messages causes all the DraweeViews to be detached and attached again. Could you check that is the case by checking what is printed in logcat when you send new messages ? First you'll have to tell Fresco to log more info to logcat (see "Setting up logcat" here: http://frescolib.org/docs/troubleshooting.html).

**Comment by Wbreadboy** [comment]
@michalgr 
Hello! Thanks for your help.
Here is fresco log when receive animated messages twice.

https://github.com/Wbreadboy/fresco-log/blob/master/fresco_log.txt

**Comment by Wbreadboy** [comment]
I tried that add View.setTag(), getTag() like this ↓

```
String acticonTag = recvActiconWebPView.getTag(R.id.acticonUrl).toString();
String acticonUrl = acticonData.acticonImgM3WebP;
if(acticonTag == null || !acticonUrl.equals(acticonTag)) {
					recvActiconWebPView.setActiconWebPView(acticonData, Constants.ACTICON_TYPE_REPLYVIEW);
					recvActiconWebPView.setOnActiconClickListener();

					recvActiconWebPView.setTag(R.id.acticonUrl, acticonUrl);
}
```
But, It was not work.(Tag is new created everytimes)

Isn't there anyone able to solve this problem? please....

**Comment by hit1983** [comment]
I counter exactly the same problem, Anyone can help?

**Comment by oprisnik** [comment]
As @michalgr mentioned, I guess you are re-attaching the drawee view - which results in the flicker since animated images are heavier than normal image.
You should only invalidate / re-attach the new views.

**Comment by erikandre** [comment]
Closing as a fix was suggested that should resolve this.
