### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by cwkcyd** [facebook/fresco#1269]
Resubmit 
This project is **Fresco official sample**, 
link https://github.com/facebook/fresco/tree/master/samples/comparison, 
And I modify some values in **MainActivity**, as follow:

public static int calcDesiredSize(Context context, int parentWidth, int parentHeight) {
int orientation = context.getResources().getConfiguration().orientation;
int desiredSize = (orientation == Configuration.ORIENTATION_LANDSCAPE) ?
**parentHeight / 12 : parentHeight / 12;** 
return Math.min(desiredSize, parentWidth);
}

if I change **COLS_NUMBER = 6** again; it would become **crash** more easier;
private static final int COLS_NUMBER = 3;

4.4.4 **native memory reaches 1gb**, then **App crash**. Especially a lot of image display on Screen.Can you try to it ? Thanks!!

**Comment by michalgr** [comment]
After applying your changes I am able to display 78 images at once. At the same time the comparison app is not configured to downsample or resize images, so if each of them was a big 4100px * 3100px (size you reported in previous task) local image then in total there would be almost 3.5GB of pixel data in memory (4 bytes per pixel). At that point the crash is expected.

In general, apps should either download images that have appropriate size for the destination view, or should tell Fresco to downsample or resize (http://frescolib.org/docs/resizing-rotating.html)

**Comment by cwkcyd** [comment]
I just modified the MainActivity, the other is the default.**by default** , is open downsampling. And resizing images on comparison project calculated by  MainActivity calcDesiredSize method, so app is configured to downsample and resize images. You can store 600+ images on sdcard,  display 48+ images at once
