### ISSUE TITLE
I want dataSource.subscribe(new BaseBitmapDataSubscriber() to  receive sequentially when dataSource.subscribe(new BaseBitmapDataSubscriber() converts an image file to a bitmap

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#127]
DataSource<CloseableReference<CloseableImage>> dataSource  =  imagePipeline.fetchDecodedImage(imageRequest,null);
                dataSource.subscribe(new BaseBitmapDataSubscriber() {
                    @Override
                    protected void onNewResultImpl(@Nullable Bitmap bitmap) {
                    
                    }

                    @Override
                    protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                       
                    }
                }, CallerThreadExecutor.getInstance());

**Comment by plamenko** [comment]
Can you clarify the question?

**Comment by chonamdoo** [comment]
T T glide source 
 bitmap = Glide.with(mContext).load(arrayPath.get(j)).asBitmap()

i want fresco decode image return bitmap

**Comment by tyronen** [comment]
http://frescolib.org/docs/using-image-pipeline.html and the next two pages after that show you how to get a CloseableReference out of a DataSource, and how to get a Bitmap safely from a CloseableReference. Be sure this is really what you need, though.
