### ISSUE TITLE
Feature request: inject local files to disk cache

### ISSUE THREAD

**Issue by SteveYurka** [facebook/fresco#1270]
I have been trying to cache a local image, using the remote URL, so that the user does not have to download something which they just uploaded. Previously we were using UIL for image loading, which did this very easily. 

I imagine this is quite a common use case, but I have been unable to figure out a solution even after looking through various things in the documentation such as CacheKeyFactory, I couldn't find anything to fit my specific scenario.

Here is the scenario I am trying to achieve:

1) The user captures data on the device (eg a camera image, or gallery image)
2) The user uploads this to our backend server
3) The backend server responds to the client with the remote URL for this file, which will be used for all future loads by all users
3) When we get the backend response, we wish to be able to cache the local file, under that remote URL instead of the local file URL, so that the user does not have to download this file again when viewing their own file
4) This would mean that when the user next calls for a fresco lookup on this remote URL, it will then be able to find this already in the cache, based on the local/client version of the file which we uploaded and precached against that remote URL

Is there any functionality in fresco that would allow me to do this?

Thanks! loving the library

**Comment by michalgr** [comment]
There is no API to do this yet, but you should still be able to hack something for now by talking directly to the disk cache. The code would look like something like this:

```java
ImageRequest imageRequestForYourImage =  ...;
InputStream yourImageStream = ...;
try {
    CacheKey cacheKey = DefaultCacheKeyFactory.getInstance(). getEncodedCacheKey(imageRequestForYourImage);
    Fresco.getImagePipelineFactory().getMainFileCache().insert(cacheKey, WriteCallbacks.from(yourImageStream));
} finally {
    yourImageStream.close();
}
```

Let us know how it goes.

**Comment by SteveYurka** [comment]
Thanks for the rapid response Michal!

I just tried your suggestion out and its working perfectly. Thank you very much.

It was basically as you suggested:

public void cacheLocalFileAsRemoteURL(Uri remoteUrl, File localFileToCache) {
        ImageRequest imageRequest = buildImageRequest(remoteUrl);

        CacheKey remoteUrlCacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(imageRequest);

        InputStream localFileInputStream = null;

        try {
            localFileInputStream = new FileInputStream(localFileToCache);

            Fresco.getImagePipelineFactory().getMainFileCache().insert(remoteUrlCacheKey, WriterCallbacks.from(localFileInputStream));
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (localFileInputStream != null) {
                    localFileInputStream.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

**Comment by erikandre** [comment]
Closing as a workaround was provided which resolved the issue
