### ISSUE TITLE
gif issue

### ISSUE THREAD

**Issue by Fisherman91** [facebook/fresco#1271]
Why I according to the appearance in the demo, I write a demo, to load a GIF images, network load is not to come out.

**Comment by Fisherman91** [comment]
SimpleDraweeView simpleDraweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
DraweeController animatedGifController = Fresco.newDraweeControllerBuilder()
                .setAutoPlayAnimations(true)
                .setUri(Uri.parse("https://s3.amazonaws.com/giphygifs/media/4aBQ9oNjgEQ2k/giphy.gif"))
                .build();
simpleDraweeView.setController(animatedGifController);

**Comment by michalgr** [comment]
I am not sure I understand. Are you saying that you cannot download the image ?

**Comment by Fisherman91** [comment]
Need to refer to the library to make display GIF：
`compile 'com.facebook.fresco:animated-gif:0.10.0'`
