### ISSUE TITLE
Retrieving file from disk cache for editing

### ISSUE THREAD

**Issue by qsyj** [facebook/fresco#1272]
Excuse me, the cache images suffix is cnt? If it is,How to modify the suffix in the cache!  Because my Because my project need pictures path to image for editing!

(I'm sorry,I am a Chinese, English is not good)

**Comment by michalgr** [comment]
You can fetch encoded bytes and store them outside of disk cache, would that work for you ? Checkout [skipping the decode section in our docs](http://frescolib.org/docs/using-image-pipeline.html)

**Comment by qsyj** [comment]
I think is the default cache file to jpeg or PNG, instead of CNT

**Comment by gajicm93** [comment]
Just replace .cnt with .jpg or whatever, and it will work. Just rename it.

**Comment by liaohuqiu** [comment]
@qsyj  And here is the Chinese docs: http://fresco-cn.org/docs/using-image-pipeline.html

**Comment by erikandre** [comment]
Closing as there seems to be nothing more to do here
