### ISSUE TITLE
Can I pass OkHttpClient of Android Networking to Fresco

### ISSUE THREAD

**Issue by mohitkumar0571** [facebook/fresco#1274]
[Android Networking](https://github.com/amitshekhariitbhu/AndroidNetworking)

In my project after using [Android Networking](https://github.com/amitshekhariitbhu/AndroidNetworking) , I found my networking perfect but I want to use OkHttpClient in fresco also.
So can I pass same OkHttpClient in both Android Networking and Fresco.?
I found it is best combination for complete networking (Fresco+AndroidNetworking)

**Comment by oprisnik** [comment]
Take a look at http://frescolib.org/docs/using-other-network-layers.html
It explains how you can set a custom network layer, like `OkHttpClient`.
