### ISSUE TITLE
fresco display remote gif  5~20 seconds after downloaded.

### ISSUE THREAD

**Issue by JiaoShuai** [facebook/fresco#1275]
I tried display network gifs in a recycleview list.  the gif size is normal. After onLevelChange reaches to 10000, i have to wait 5~20 seconds to see the gif display animation. 

fresco usage : 
`compile` 'com.facebook.fresco:fresco:0.10.0'
compile` 'com.facebook.fresco:animated-gif:0.10.0'``

in fresco 0.90+, the same problem is there. 

the same issue is reported in:
https://github.com/facebook/fresco/issues/475
https://github.com/facebook/fresco/issues/365

the problem is pretty serious in my senario, often you have to wait  more than 30 seconds to see the animation.

**Comment by kirwan** [comment]
Can you provide a link to an image you're having this problem with?

As you say it has been raised before and I'll take a look to see how we can resolve this. It would be good to have another image to test with though, the example in #475 is a really large (file size) image and I'm curious how large yours are.

**Comment by JiaoShuai** [comment]
@kirwan  thank you for your time.  All gifs are small gifs. examples like: 

http://files.wikicivi.com/files/Images/Radar/20160605/710593fb874468e6a00f510a9c8ce0b0.gif
http://files.wikicivi.com/files/Images/Radar/20160605/7139f285ecdfe21930d8bdce0eca2e35.gif
http://files.wikicivi.com/files/Images/Radar/20160605/fad49bca95031df34ba812e8d2acf5fe.gif 
http://files.wikicivi.com/files/Images/Radar/20160605/ad560c12cfd51d8b962b06727863f338.gif
http://files.wikicivi.com/files/Images/Radar/20160605/03a5e6455996b06852122973afae1dec.gif
http://files.wikicivi.com/files/Images/Radar/20160605/ad280a2e53a390deb8909156d4fe549d.gif
http://files.wikicivi.com/files/Images/Radar/20160605/b69467fb06ce8198181fa0f2421eaac7.gif
http://files.wikicivi.com/files/Images/Radar/20160605/e2f268d7bd3d425460c8ef8d3fa950f5.gif

these gifs are arranged in a recycleview, they downloaded very fast (2~5 seconds), the progressbar reachs to 100%, but you have to wait ( > 5) seconds to see the gif shown, this looks stupid. 

my guess is: 
1: fresco has to simutaneously render several gifs in recycle view, which run serially and slow?
2: fresco in nature render a gif slower than comparable gif drawing tool? 

if large gif slow the rendering time, is there anyway to estimate the rendering time, so we can simulate a progressbar by onchangelevel and rendering time, as suggested by @plamenko in #475 ?

thank you!

**Comment by kyangc** [comment]
this issue exists for a really long time... hoping for any update here.

**Comment by JiaoShuai** [comment]
what should i do ? i cannot wait for the next update..... turn to Glide? @kyangc @

**Comment by kirwan** [comment]
I've created a simple fix which will stop the progress bar disappearing until the decoding is complete. Fortunately, I'm also preparing a new release so I'm hoping that will fix your issue, even if we may still want to improve the sophistication of the solution later.

**Comment by JiaoShuai** [comment]
@kirwan thank you ,that's encouraging!

**Comment by kyangc** [comment]
Great

JiaoShuai <notifications@github.com>于2016年6月15日周三 上午9:18写道：

> @kirwan <https://github.com/kirwan> thank you ,that's encouraging!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/fresco/issues/1275#issuecomment-226062948>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG_JkuAvC-HiQF9aKArZv0YYH0CfU8Jqks5qL1LjgaJpZM4IuhlT>
> .
>
-- 
See me here: about.me/chengkangyang

**Comment by kirwan** [comment]
I believe this should be resolved by da9b7f162bb31f538bda2f34e83ac505f0e67a39.

**Comment by SZn007** [comment]
but the decode time is still too long, and the experience is not good.

**Comment by rafaelekol** [comment]
Can you include decode progress to download progress when showing progressbar? I have also same issue with big GIF images. It downloads fast, but then progressbar just stays there for several seconds, until GIF starts to play.
