### ISSUE TITLE
Fresco downSampleSize

### ISSUE THREAD

**Issue by AllenVork** [facebook/fresco#1276]
I'm using fresco to load a lot of images and i have configured it with downSampleSize.But after using it, when i wanna show the original image of a thumb, it's muzzy.How could i use downSampleSize dynamically?

**Comment by aagnes** [comment]
What do you mean by downSampleSize?

**Comment by hss01248** [comment]
do you mean ResizeOptions + Downsampling  ?
if you want the original image and the downsampled bitmap to be different ,give them two different key: append the url with "?xx=yy" or "&xx=yy"

**Comment by erikandre** [comment]
Closing as it's not clear what the problem is, and no further information was provided
