### ISSUE TITLE
I would like to load GIF in SimpleDraweeView.Gone. Then GIF loaded to complete the SimpleDraweeView.VISIBLE, how to do?

### ISSUE THREAD

**Issue by Tijn1314** [facebook/fresco#1279]
I would like to load GIF in SimpleDraweeView.Gone. Then GIF loaded to complete the SimpleDraweeView.VISIBLE, how to do?

**Comment by aagnes** [comment]
You can use ControllerListener. See http://frescolib.org/docs/listening-download-events.html.
