### ISSUE TITLE
java.io.FileNotFoundException by some special uri

### ISSUE THREAD

**Issue by lindow2009** [facebook/fresco#128]
some uri has special character like file:///storage/emulated/0/Tencent/QQfile_recv/PL6YD4~F{T)9)TBLX2%IB%C.png

so display throw exception 
cause by libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
any suggestions？

**Comment by plamenko** [comment]
Are you sure that the filename is correct and that the file exists?
Does `FileInputStream("/storage/emulated/0/Tencent/QQfile_recv/PL6YD4~F{T)9)TBLX2%IB%C.png")` work?

**Comment by plamenko** [comment]
Closing this as we haven't heard back. Please reopen if this is still an issue.

**Comment by wang00850023** [comment]
Yes ,I have encountered this problem,and this picture is exist,because I can see it in system photo album,but when I use Freco to display it ,it throw this exception.open failed: ENOENT (No such file or directory)
