### ISSUE TITLE
Bitmap too large to be uploaded into a texture (414x9571, max=8192x8192)

### ISSUE THREAD

**Issue by Caij** [facebook/fresco#1280]
SimpleDraweeView have layout_width and layout_height, the actualImageScaleType is centerCrop.
why need setResizeOptions for request? Why is it not according to the size of the SimpleDraweeView 。Glide and Picasa is Support。
url:http://ww4.sinaimg.cn/bmiddle/005SiNxygw1f4lpwlbo8uj30bi7dvb29.jpg

**Comment by aagnes** [comment]
OpenGL limit bitmap rendering no more than 2048x2048. Auto resize is what we wanna achieve. It would be really helpful if someone in community can give us a hand in this.

**Comment by zhuAria** [comment]
How did you solve this problem @Caij

**Comment by Caij** [comment]
@zhuAria  you need set resizeOptions for request
```java
SimpleDraweeView imageView = (SimpleDraweeView) findViewById(R.id.imageview);
        ImageRequest imageRequest  = ImageRequestBuilder.
                newBuilderWithSource(Uri.parse(url)).
                setResizeOptions(new ResizeOptions(width, hight));
                build();
        DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequest)
                .build();
        imageView.setController(draweeController);
```

**Comment by oprisnik** [comment]
Yeah, unfortunately there is a system limit. Resizing the image should help.
