### ISSUE TITLE
（windows）fresco build  failed file:///E:/dir_git/fresco/imagepipeline-base/build/reports /tests/debug/index.html

### ISSUE THREAD

**Issue by joimxjtuse** [facebook/fresco#1289]
Labels>:build

while build the newest version fresco in windows, i get an error as follow: 

> There were failing tests. See the report at: file:///E:/dir_git/fresco/imagepipeline-base/build/reports
/tests/debug/index.html
              
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log ou
tput.         
              
BUILD FAILED  
              
Total time: 1 mins 18.917 secs

**Comment by joimxjtuse** [comment]
commit id:  e4d5bfbbf027de67d620d4cfa5b4071b0799d8c5 [e4d5bfb]

**Comment by kirwan** [comment]
As the message says there were failing tests but you haven't provided enough detail to understand why.

Please view the file specified (`file:///E:/dir_git/fresco/imagepipeline-base/build/reports
/tests/debug/index.html` in this case) in your browser and see which tests failed.

If you share that with us we might be able to understand why.

**Comment by kirwan** [comment]
We're still missing details here. Let me know if you still need help but I'm closing the issue for now.
