### ISSUE TITLE
Is Fresco resizing the image before displaying?

### ISSUE THREAD

**Issue by johntiror** [facebook/fresco#1292]
Hi,

lately I was using [Glide ](https://github.com/bumptech/glide/wiki) to load images. One nice feature of Glide is that it resizes the image to the dimension of the ImageView where it'll be displayed, so less pixel to draw means less RAM to use. This means Glide is also able to display huge images with nothing to do by the developer. Is Fresco doing the same? 

Thanks

**Comment by oprisnik** [comment]
Hi!
You can specify `ResizeOptions` for the image request. If you don't set resize options, the image will just be scaled. We currently do not automatically set ResizeOptions for you, so you have to explicitly set them.
More information: http://frescolib.org/docs/resizing-rotating.html

**Comment by AlexBlokh** [comment]
The point is Glide doesn't do decoding to bitmap unless ImageView is measured and then it decodes it with Matrix Scale transformation
So if you have grid of 360x360 images and they're stored on disk as 720x720, Glide will resize them during decoding and then put them in memory as 320x320

**Comment by atimb** [comment]
It's 2021 and Fresco still doesn't automatically resize image to fit the containing view.
