### ISSUE TITLE
可以为GIF、Webp 动画添加播放完成的事件回调吗？

### ISSUE THREAD

**Issue by hbm1985** [facebook/fresco#1293]

**Comment by massimocarli** [comment]
Hi @hbm1985 ,
if I have understood the question you need a callback in order to understand when the Webp/Gif animation has completed. Do you confirm?

Thanks

**Comment by aagnes** [comment]
@massimocarli hbm1985 is asking the exact thing. So you would need BaseControllerListener to listen for the event.

**Comment by renyanxu2000** [comment]
@massimocarli You are right!
