### ISSUE TITLE
Downscaling CMYK JPEGs fails

### ISSUE THREAD

**Issue by jbxberg** [facebook/fresco#1294]
`JpegTranscoder.transcodeJpeg()` fails, if the jpeg uses CMYK colors. 

> java.lang.RuntimeException: Unsupported color conversion request

**Comment by kirwan** [comment]
That error message comes from with the libjpeg_turbo from [jccolor.c](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/3ff13e651bbe6de9c6f15d05235d1d4f26f63ffc/jccolor.c#L678).

It suggests CMYK images should work if valid.

Does this only happen when downscaling is enabled?

**Comment by jbxberg** [comment]
Exactly, it only happens when scaling is applied. displaying CMYK jpegs without scaling works fine.

**Comment by yk3372** [comment]
how to fix it finally? thanks

**Comment by kirwan** [comment]
Can you provide a sample image for us to look at?

**Comment by erikandre** [comment]
Closing as we don't have a jpeg to reproduce this with.
