### ISSUE TITLE
Can we have the duration of animate webp or callback when animation is finish?

### ISSUE THREAD

**Issue by pzhangleo** [facebook/fresco#1296]
Thank you, we need that feature.

**Comment by oprisnik** [comment]
I've added the possibility to get the animation duration, see 5c927efcff52213016497e86af7cde45ab295b12

**Comment by renyanxu2000** [comment]
@oprisnik Yes, this feature is very important, and sometimes we need to play only once.When will release a new version?

**Comment by oprisnik** [comment]
We don't have an exact release schedule, but we're now releasing on a regular basis, so you can expect a new version pretty soon.

**Comment by assafb81** [comment]
@oprisnik,
sorry for writing in a closed issue.
I looked at [5c927ef](https://github.com/facebook/fresco/commit/5c927efcff52213016497e86af7cde45ab295b12)

are this new properties accessible via RN code?
mDurationMs? mLoopCount?

I want to play the GIF once and manually, currently its not available (as far as I can see it - see  #2086) so I may be able to write a workaround using the above props.
