### ISSUE TITLE
How to write proguard roles ? gif will not show

### ISSUE THREAD

**Issue by ijustyce** [facebook/fresco#1297]
Lately I use fresco0.9, it work fine, but when I update to 0.10.0 gif will not show, and if I turn minifyEnabled to false, gif play as nomal .So, I think I should add proguard roles , but I don't know how to do it,  just   `-keep class com.facebook.**{*;}`   ?

**Comment by Wbreadboy** [comment]
Here is same problem and solution.

https://github.com/facebook/fresco/issues/1177

**Comment by kirwan** [comment]
As @Wbreadboy says, the solution can be found in this comment: https://github.com/facebook/fresco/issues/1177#issuecomment-221807002

I'll ensure our Proguard documentation is updated to include this.

**Comment by oprisnik** [comment]
We've fixed this with 0d0c5757ff40eb9e9f23533c9798dcdde095ce86 so this will be fixed in the next release. Thanks for reporting!
