### ISSUE TITLE
xml set overlayImage,it is not in center of the picture

### ISSUE THREAD

**Issue by HeyManImMoy** [facebook/fresco#1299]
most of phones performance normal ,the overlay image (.9.png)can be placed in the center of the draweeview,but,when it open on SUMSUMG,I9500,it diverges from the draweeview,in other words,the overlay image is not in the center.

**Comment by HeyManImMoy** [comment]
picture here
![device-2016-06-16-161904 1](https://cloud.githubusercontent.com/assets/10720800/16110486/88b6a984-33e0-11e6-9f18-dffbf37a08f9.png)

**Comment by oprisnik** [comment]
How are you using Fresco? Can you give a short example where the overlay image is not centered?
Does this only happen for 9-patch files or also for normal images?

**Comment by HeyManImMoy** [comment]
` <DraweeView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:placeholderImagde="@mipmap/image_loading_goods"
            app:placeholderImageScaleType="centerInside"
            app:overlayImage="@mipmap/bg_watermark"
            app:url="@{image}"/>`code

this only happen for 9-patch image,normal images never occur ,but,normal images will be scale like the mode "fixXY" when I set it for overlay,like picture below:
![watermark](https://cloud.githubusercontent.com/assets/10720800/16289281/5436f470-3926-11e6-9184-d99b28f7d4cf.png)

**Comment by HeyManImMoy** [comment]
I‘m so sorry,I found that overlayimage 's scale type is linked with placeholderimagescale today,I hope I didn't bring you inconvenience.
