### ISSUE TITLE
Not able to show GIF with ProGuard enabled in 0.11.0

### ISSUE THREAD

**Issue by joshzngf** [facebook/fresco#1301]
Hello,

I've built my app with proguard enabled and followed the instruction found in the document:
https://raw.githubusercontent.com/facebook/fresco/master/proguard-fresco.pro

However, the GIFs cannot be displayed.
I have found a solution to fixing this problem by adding the following line to the ProGuard config file:
`-keep class com.facebook.imagepipeline.animated.** { *; }`
and everything worked as normal.

Could you update the ProGuard file in documentation if there is no other solution?
Thank you.

**Comment by oprisnik** [comment]
Thanks, we're looking into this!

**Comment by oprisnik** [comment]
We've fixed this with 0d0c5757ff40eb9e9f23533c9798dcdde095ce86 so this will be fixed in the next release. Thanks for reporting!
