### ISSUE TITLE
Placing rounded images under other views produce glitches

### ISSUE THREAD

**Issue by defHLT** [facebook/fresco#1302]
On SGS5/4.4.2 device `SimpleDraweeView` leaves traces when going under the view with the following param:

``` xml
fresco:roundAsCircle="true"
```

![fresco-rounded-z](https://cloud.githubusercontent.com/assets/1539296/16119469/4cb5dd5c-33e4-11e6-9894-00868e4ac3cb.png)

This is mitigated by specifying overlay color, e.g.:

``` xml
fresco:roundWithOverlayColor="@android:color/white"
```

**Comment by kirwan** [comment]
Fresco supports two rounding types, [`BITMAP_ONLY` and `OVERLAY_COLOR`](https://github.com/facebook/fresco/blob/89477f77af3b6954f57dc39b8c572b4b8eb4e84a/drawee/src/main/java/com/facebook/drawee/generic/RoundingParams.java#L22).

`BITMAP_ONLY` is the default but supports limited scale types. Does your image's scale type match one of those? What are the other params on the view?

**Comment by mlatu** [comment]
I have few other options, here is the full code:

```xml
    <com.facebook.drawee.view.SimpleDraweeView
        xmlns:fresco="http://schemas.android.com/apk/res-auto"
        android:id="@+id/drawee_manager_avatar"
        android:layout_width="@dimen/medium_rounded_image_size"
        android:layout_height="@dimen/medium_rounded_image_size"
        android:layout_gravity="center_vertical"
        android:layout_marginEnd="@dimen/margin_medium"
        android:layout_marginRight="@dimen/margin_medium"
        fresco:placeholderImage="@drawable/img_empty_avatar"
        fresco:roundAsCircle="true">
```

**Comment by oprisnik** [comment]
And how are you attaching the image to the view in the screenshot? It should be below the blue bar at the top or above? How does the parent view look like?

**Comment by igalata** [comment]
The same bug on sgs5

![screen](https://cloud.githubusercontent.com/assets/20659278/17132661/67eb3d22-532b-11e6-80d7-684601cce68a.png)

`  <com.believersconnect.ui.views.SelectableDraweeView
        android:id="@+id/avatar"
        style="@style/Avatar"
        android:layout_alignBottom="@+id/text_view_message"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_marginLeft="@dimen/chat_list_item_margin" />`

`<style name="Avatar">
        <item name="android:layout_height">@dimen/chat_avatar_size</item>
        <item name="android:layout_width">@dimen/chat_avatar_size</item>
        <item name="fadeDuration">300</item>
        <item name="roundAsCircle">true</item>
        <item name="placeholderImage">@drawable/ic_placeholder_big</item>
        <item name="placeholderImageScaleType">fitCenter</item>
    </style>`

**Comment by kirwan** [comment]
Is this still causing a problem for anyone? If so, can you provide more detail of your layout (not just the drawee view) and how the view's being used, e.g. RecyclerView or ListView.

**Comment by oprisnik** [comment]
I'm closing this issue since it's more than a year old. Feel free to comment if this is still an issue.
