### ISSUE TITLE
Too much momery used

### ISSUE THREAD

**Issue by ijustyce** [facebook/fresco#1303]
![fresco](https://cloud.githubusercontent.com/assets/6041166/16121983/f114766e-3417-11e6-9a7f-6fd7a8c48089.png)

My app have many picture， and for some reason I only can use listview，but I found memory used more than 200M， the more pictures I load the more memory used , in my test it used 320M memory then reduced to 80 M.

**Comment by kirwan** [comment]
Sorry, I can't really tell anything from this graph.

You could look at my suggestions here https://github.com/facebook/fresco/issues/1306#issuecomment-226775401

I'll close this issue and if you'd like to discuss memory further, let's do it on #1306

**Comment by ijustyce** [comment]
ok, thanks.

**Comment by FabianTerhorst** [comment]
I have to say that with fresco i have lower memory allocated then with glide.
