### ISSUE TITLE
libjpeg turbo version too low,and google playstore reject it;

### ISSUE THREAD

**Issue by iceAnson** [facebook/fresco#1305]
Hello Google Play Developer,

We detected that your app(s) listed at the end of this email are using an unsafe version of libjpeg_turbo library.

What’s happening

Beginning September 17, 2016, Google Play will block publishing of any new apps or updates that use pre 1.4.2 versions of libjpeg_turbo. Apps with vulnerabilities like this can expose users to risk of compromise and may be considered in violation of our Malicious Behavior policy.

Action required: Migrate your app(s) to use libjpeg-turbo v1.4.2 or higher as soon as possible and increment the version number of the upgraded APK.

**Comment by kirwan** [comment]
Thanks for letting us know. We'll upgrade the dependency and include that in our next release.

It looks like you haven't been rejected here, but this is a warning that action is required to avoid being rejected later in the year. Correct me if I'm wrong.

**Comment by iceAnson** [comment]
@kirwan Yes,you're right,it is a warning,that will be fine if we fix it before September 17, 2016,my apps is rejected becauseof other reason;

**Comment by shekarrex** [comment]
Any Update on how to fix this issue?

**Comment by PiotrWpl** [comment]
@shekarrex https://github.com/facebook/fresco/releases/tag/v0.13.0 didn't fix?

**Comment by kirwan** [comment]
As @PiotrWpl mentioned, this should be fixed in 0.13.0 which was released last Friday thanks to bc6016e1f8daa74ce0cb60710414afd3f320f2aa and 5649f0cfee8670c1e262a1626528d0077af5ace3.

Reopen the issue if you still see issues but I think this is now resolved.
