### ISSUE TITLE
please close.

### ISSUE THREAD

**Issue by 1201205** [facebook/fresco#1306]
The native mem leak from my device was not from Fresco, I'm sorroy about my less rigorous attitude.

**Comment by ijustyce** [comment]
Me too,  I finally used the glide. https://github.com/facebook/fresco/issues/1303

**Comment by kirwan** [comment]
There really isn't enough information for me to be able to say what kind of problem might be involved here.

Are you using drawee or requesting image from the pipeline directly?

One thing you could try is to specify alternative `MemoryCacheParams` in your `ImagePipelineConfig`. The default values come from `DefaultBitmapMemoryCacheParamsSupplier`. You could even set it to hold no items at all to make sure the cache isn't holding onto images which you don't need.

**Comment by 1201205** [comment]
I just use SimpleDraweeView and set the uri , I do not use pipeline directly. The native heap is increasing in a low speed whlie the app running monkey, but the ashmem is in the normal level. My problem is the increasing in native and unkown mem.

**Comment by 1201205** [comment]
@kirwan 
![qq 20160624143949](https://cloud.githubusercontent.com/assets/8895235/16330300/d5109728-3a1a-11e6-87a5-7557168bbc9a.png)
![qq 20160624144008](https://cloud.githubusercontent.com/assets/8895235/16330305/db4de26c-3a1a-11e6-85c2-4dc1c5ced1dc.png)
![qq 20160624144036](https://cloud.githubusercontent.com/assets/8895235/16330306/dc9370c4-3a1a-11e6-8010-bd4f7947a088.png)
![qq 20160624144420](https://cloud.githubusercontent.com/assets/8895235/16330308/ddd983d8-3a1a-11e6-9cf3-eccf3ff0134a.png)
Here is some more information from my app. Why there are so many NativeMemoryChunk objects  existed, why they were still alive with a few view . Can you give me some advise?
