### ISSUE TITLE
Gif not load in fresco 0.10.0,0.11.0

### ISSUE THREAD

**Issue by killermyth** [facebook/fresco#1307]
I load gif with code below

mGifImg = (SimpleDraweeView) findViewById(R.id.gifImg);
        Uri uri = new Uri.Builder()
                .scheme(UriUtil.LOCAL_RESOURCE_SCHEME)
                .path(String.valueOf(R.drawable.test))
                .build();
        DraweeController draweeController =
                Fresco.newDraweeControllerBuilder()
                        .setUri(uri)
                        .setAutoPlayAnimations(true)
                        .build();
        mGifImg.setController(draweeController);

fresco 0.8.1,0.9.0 load gif right，0.10.0,0.11.0 could not load

**Comment by kirwan** [comment]
In 0.10.0, we broke GIF support out into a separate dependency to reduce the size of the core library. Does your Gradle file include the following?

```
compile 'com.facebook.fresco:animated-gif:0.11.0'
```

See [the docs](http://frescolib.org/docs/index.html) for the other optional modules too.

**Comment by killermyth** [comment]
thank so much

**Comment by hzy82218052** [comment]
why support out ，Chinese Forum is not updated？
