### ISSUE TITLE
Load gif image error

### ISSUE THREAD

**Issue by Caij** [facebook/fresco#1312]
06-19 12:06:45.764 9601-9626/com.example.caij.viewwidthandheightdemo V/unknown:StagingArea: Count = 1
06-19 12:06:45.792 9601-9626/com.example.caij.viewwidthandheightdemo V/unknown:GenericByteArrayPool: release (reuse) (object, size) = (c128e14, 16384)
06-19 12:06:45.793 9601-9626/com.example.caij.viewwidthandheightdemo V/unknown:GenericByteArrayPool: Used = (0, 0); Free = (1, 16384)
06-19 12:06:45.795 9601-9631/com.example.caij.viewwidthandheightdemo V/unknown:BufferedDiskCache: About to write to disk-cache for key http://ww3.sinaimg.cn/bmiddle/6a6a919egw1f4z8l50em2g20bb0f6k2e.gif
06-19 12:06:45.868 9601-9631/com.example.caij.viewwidthandheightdemo V/unknown:GenericByteArrayPool: Used = (1, 16384); Free = (0, 0)
06-19 12:06:45.868 9601-9631/com.example.caij.viewwidthandheightdemo V/unknown:GenericByteArrayPool: get (reuse) (object, size) = (c128e14, 16384)
06-19 12:06:45.875 9601-9631/com.example.caij.viewwidthandheightdemo V/unknown:GenericByteArrayPool: release (reuse) (object, size) = (c128e14, 16384)
06-19 12:06:45.875 9601-9631/com.example.caij.viewwidthandheightdemo V/unknown:GenericByteArrayPool: Used = (0, 0); Free = (1, 16384)
06-19 12:06:45.876 9601-9631/com.example.caij.viewwidthandheightdemo V/unknown:BufferedDiskCache: Successful disk-cache write for key http://ww3.sinaimg.cn/bmiddle/6a6a919egw1f4z8l50em2g20bb0f6k2e.gif
06-19 12:06:45.877 9601-9631/com.example.caij.viewwidthandheightdemo V/unknown:StagingArea: Count = 0
06-19 12:06:45.956 9601-9601/com.example.caij.viewwidthandheightdemo V/unknown:AbstractDraweeController: controller 34c776d 0: final_failed @ onFailure: failure: java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.imagepipeline.image.CloseableImage com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(com.facebook.imagepipeline.image.EncodedImage, com.facebook.imagepipeline.common.ImageDecodeOptions, android.graphics.Bitmap$Config)' on a null object reference

**Comment by desmond1121** [comment]
add `compile 'com.facebook.fresco:animated-gif:0.10.0` in `build.gradle`, you must using version `0.10.0+` fresco,  see [relase v0.10.0](https://github.com/facebook/fresco/releases/tag/v0.10.0)

**Comment by Caij** [comment]
@desmond1121 thanks
