### ISSUE TITLE
can fresco support video cache

### ISSUE THREAD

**Issue by shuaimango** [facebook/fresco#1314]
this is glide,support video cache
 // load video file
        Glide.with(itemView.getContext())
                .using(VideoListGlideModule.getOkHttpUrlLoader(), InputStream.class)
                .load(new GlideUrl(item.getVideoUrl()))
                .as(File.class)
                .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                .into(progressTarget);

**Comment by oprisnik** [comment]
So you want to display a selected frame of a video / a preview image? Or cache a video from a server? Or play a video?

**Comment by shuaimango** [comment]
I need to cache a video from a server, like Glide, it can cache other files on disk.
If it can display a selected frame of a video, that would be better . 
Thank you for your answer !

**Comment by oprisnik** [comment]
We currently do not support adding videos to our cache. The only thing that could work is rendering a frame (as a bitmap) of a locally stored video.

**Comment by shuaimango** [comment]
you are right.but  when support adding videos to fresco cache?   As network traffic more and more cheap, the client's video shows more and more

**Comment by oprisnik** [comment]
Since Fresco is an image loading library, we currently don't have plans to support adding random files to our caches in the near future.
It should be fairly easy though to write a simple file cache yourself.
