### ISSUE TITLE
[question] determineDownsampleRatio is inappropriate 

### ISSUE THREAD

**Issue by huangjunkun** [facebook/fresco#1317]
> reference：com.facebook.imagepipeline.producers.DownsampleUtil#determineDownsampleRatio

I think that determineDownsampleRatio is inappropriate.

`float ratio = Math.max(widthRatio, heightRatio);`

It's could cause ImagePipeline use more Memory to decode image for bitmap, a wasteful behavior.
I think the logical thing to do would have been to select which come near to 1.0f, eg. 0.6 vs 1.2 and select 0.9.

**Comment by huangjunkun** [comment]
`float ratio = (Math.abs(1.0f-widthRatio) > Math.abs(1.0f-heightRatio)) ? widthRatio : heightRatio;`

If you consider that is reasonable, **I can make a pull request**.

**Comment by oprisnik** [comment]
The DownsampleUtil is used by the ImagePipeline itself, which does not know anything on how the image is used later on.
I suppose that for your case, you're using a `fit...` scaling type for your DraweeView? 
But the pipeline at this point does not know that (and different DraweeViews could have different scale types) and if we're too aggressive with downscaling and you're using cropping, the quality might be worse.

**Comment by huangjunkun** [comment]
Sorry. You maybe not understand my content.

determineDownsampleRatio return ration, which is for adjust sample. Look the following
> com.facebook.imagepipeline.producers.DownsampleUtil#determineSampleSize

`  float ratio = determineDownsampleRatio(imageRequest, encodedImage);
    int sampleSize;
    if (encodedImage.getImageFormat() == ImageFormat.JPEG) {
      sampleSize = ratioToSampleSizeJPEG(ratio);
    } else {
      sampleSize = ratioToSampleSize(ratio);
    }`

and ratio > 0.8333, sampleSize = 1.//decode a original Bitmap.
> com.facebook.imagepipeline.producers.DownsampleUtil#ratioToSampleSize
`  if (ratio > 0.5f + 0.5f * INTERVAL_ROUNDING) {
      return 1; // should have resized
    }`

**Comment by huangjunkun** [comment]
Example

>  ratio 0.6 vs 1.2 and  a bitmap of 1920*1080 (used memory 1920*1080*3  approximately equal to 6Mb)

`float ratio = Math.max(widthRatio, heightRatio);`
select ratio 1.2 and sampleSize=1, used memory 6Mb (approximately)


`float ratio = (Math.abs(1.0f-widthRatio) > Math.abs(1.0f-heightRatio)) ? widthRatio : heightRatio;`
select ratio 1.2 and sampleSize=0.6, used memory 2Mb (approximately)

Because we have consider the one  which come near to 1.0f, the shorter side of ImageView(width or height),  the quality would be not affected.

**Comment by aagnes** [comment]
@huangjunkun sampleSize is always an integer.

**Comment by huangjunkun** [comment]
@aagnes   Yeah, sampleSize is integer, but ratio is float.

**Comment by kirwan** [comment]
As commented on the PR, we're soon introducing a more flexible way of defining resize options. I think that makes this redundant.
