### ISSUE TITLE
Listview /convertView/ SimpleDraweeView shown wrong order

### ISSUE THREAD

**Issue by weimianlong** [facebook/fresco#1318]
In a listview adaper,the getView method always like this:

public View getView(int position, View convertView, ViewGroup parent)
    {
        ViewHolder viewHolder = null;
        if (null == convertView)
        {
            LayoutInflater mInflater = LayoutInflater.from(mContext);
            convertView = mInflater.inflate(R.layout.view_listitem_home, null);
            viewHolder = new ViewHolder(convertView);
            convertView.setTag(viewHolder);
        }
        else
        {
            viewHolder = (ViewHolder) convertView.getTag();
        }
      viewHolder.simpleDraweeView.setImageURI(getImageUri(position)); //to load image asynchronously
}
As above,the item view will reuse,so the simpleDraweeView also will reuse,how to avoid wrong image to be set on the item view when asyn request finish?Like below???

holder.imageView.setTag(imgUrl);//because getView reuse convertView
................
// where the background request finish and return to UI thread,the correct imageview to set image
if (imageView.getTag() != null && imageView.getTag().equals(imageUrl)) {
    imageView.setImageBitmap(result);
}

**Comment by oprisnik** [comment]
We have a sample app for this, called `scrollperf`.
See also the 3 classes `DraweeViewAdapter`, `DraweeViewHolder` and `DraweeViewListAdapter` [here](https://github.com/facebook/fresco/tree/master/samples/scrollperf/src/main/java/com/facebook/samples/scrollperf/fragments/recycler).
