### ISSUE TITLE
High CPU usage when coming back from screen unlock

### ISSUE THREAD

**Issue by speedpursuer** [facebook/fresco#1319]
My activity is similar to the Comparison sample that has a RecyclerView displaying multiple gif images from network. All the images have been downloaded and cached. 

Scrolling down and up the list is quite smooth and images display quite fast in normal. But if pressing power button to lock the screen for serval mins, and getting back, the image loading become very slow when doing the same (scrolling down and up). 

I found the CPU usage is also very high. This symptom will last for few mins and it comes to normal. I attached the CPU charts for comparison between normal and unnormal. Another thing to notes is that If the device is connected to PC via USB, there is NO such problem.

I suspect it's related to device sleep mode where CPU is off. If it is, I'm wondering why it's that slow for CPU to wake to calculate as fast as normal and what I can do the let the CPU wake in short time so user will not see the difference.

Normal:
![before](https://cloud.githubusercontent.com/assets/1818577/16305358/0dc198b8-398c-11e6-91d8-6a27a15b550a.jpg)

Coming back from screen lock
![after](https://cloud.githubusercontent.com/assets/1818577/16305357/0d6d4218-398c-11e6-8d4f-45ad236fc034.jpg)

**Comment by oprisnik** [comment]
I guess the activity has to be recreated and all images have to be read from the (disk) cache, decoded etc. - which just takes some time. GIF images especially take quite some time to decode, see for example #1231.

How big are your GIFs (resolution and size) and how many do you display?

**Comment by speedpursuer** [comment]
Thanks for the reply! The single gif is 400 x 300 in around 5MB. The RecyclerView displays 3-4 gifs at a time. Do you think this is still in a range Fresco can handle on device running SDK ver 19 and above?

The strange part is that the image loading is very slow and CPU is at high usage just in the 1-2 min after the device is wake from screen lock. After that period, it comes to work perfectly, no matter how many times you quite and re-enter the activity.

PS: I'm quite sure the problem occurs when the activity is not recreated.

Look forward to your kind help!

**Comment by oprisnik** [comment]
We've released [Fresco v1.4.0](https://github.com/facebook/fresco/releases/tag/v1.4.0), which includes a new implementation for animated GIFs that is way more performant. Let us know if you're still experiencing problems with 1.4.0.
