### ISSUE TITLE
 Bitmap too large to be uploaded into a texture (440x7253, max=4096x4096)

### ISSUE THREAD

**Issue by leelei** [facebook/fresco#132]
why ? I do resize Image 

```
new ResizeOptions(400, 400)
```

Picasso support

**Comment by leelei** [comment]
it not use option.inSampleSize  to scale Image first ?

**Comment by tyronen** [comment]
Resize options will only work if the source image is a JPEG.

**Comment by plamenko** [comment]
We are working on supporting downscaling for other image formats.

**Comment by ICECHN** [comment]
The source code from Fresco 0.4.0 is : 
com.facebook.imagepipeline.decoder.ImageDecoder.java
public CloseableImage decodeImage(
      final CloseableReference<PooledByteBuffer> pooledByteBufferRef,
      @Nullable ImageFormat imageFormat,
      final int length,
      final QualityInfo qualityInfo,
      final ImageDecodeOptions options) {
    if (imageFormat == null || imageFormat == ImageFormat.UNKNOWN) {
      imageFormat = ImageFormatChecker.getImageFormat_WrapIOException(
          new PooledByteBufferInputStream(pooledByteBufferRef.get()));
    }

    switch (imageFormat) {
      case UNKNOWN:
        throw new IllegalArgumentException("unknown image format");

      case JPEG:
        return decodeJpeg(pooledByteBufferRef, length, qualityInfo);

      case GIF:
        return decodeAnimatedGif(pooledByteBufferRef, options);

      case WEBP_ANIMATED:
        return decodeAnimatedWebp(pooledByteBufferRef, options);

      default:
        return decodeStaticImage(pooledByteBufferRef);
    }
  }

Resize options doesn't work if the source image is a JPEG.

@tyronen
