### ISSUE TITLE
Support fit

### ISSUE THREAD

**Issue by wangbourne** [facebook/fresco#1320]
In Picasso, we don't need to care about memory usage and more importantly don't need manually calculate the best image size to fit since it provides a magic method: **fit**. 

Does fresco provide similar function too? 

```
Picasso
    .with(context)
    .load(UsageExampleListViewAdapter.eatFoodyImages[0])
    .fit()
    // call .centerInside() or .centerCrop() to avoid a stretched image
    .into(imageViewFit);
```

**Comment by oprisnik** [comment]
So if I understand correctly, `fit()` takes the size of the image view and automatically resizes the image once it is downloaded?
We do not support this out-of-the-box, but it would be pretty easy to implement:
You know the size of your view, so you can just set the resize options accordingly.
If you're using match_parent, you can just get the width of the view (delay the request until you have a size) and then set the resize options: http://frescolib.org/docs/resizing-rotating.html

It might also be related that we [don't support `wrap_content`.](http://frescolib.org/docs/wrap-content.html)

The best solution would be if your images would have an appropriate size right away.

**Comment by erikandre** [comment]
Closing as this is enhancement is not prioritized to be implemented.
Still, please feel free to submit a pull request for any missing functionality.
