### ISSUE TITLE
placeholder image and progressbar image are not displayed when using in custom imageview

### ISSUE THREAD

**Issue by caprice** [facebook/fresco#1322]
Hi,
 
> As our UI request, I have to use custom view to use fresco. As your document in your official site. I do the below things. Use the my view, the remote picture was loaded successfully, but it's displaying empty not the place holder image before remote picture loaded. I am not sure it's your library's bug. Can you help look at this? thanks!
 
- init code.

```java
public class ChatImageDraweeView extends ImageView {

        private CloseableReference<CloseableImage> imageReference = null;

        public DraweeHolder<GenericDraweeHierarchy> mDraweeHolder;

        public ChatImageDraweeView(Context context) {
            this(context, null);
        }

        public ChatImageDraweeView(Context context, AttributeSet attrs) {
            this(context, attrs, 0);
        }

        public ChatImageDraweeView(Context context, AttributeSet attrs, int defStyle) {
            super(context, attrs, defStyle);
            GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(getResources())
                    .setFailureImage(R.color.img_placehoder_color)
                    .setProgressBarImage(new ProgressBarDrawable())
                    .setProgressBarImageScaleType(ScalingUtils.ScaleType.CENTER_INSIDE)
                    .setPlaceholderImage(context.getResources().getDrawable(R.color.img_placehoder_color))
                    .setPlaceholderImageScaleType(ScalingUtils.ScaleType.CENTER_INSIDE)
                    .build();
            mDraweeHolder = DraweeHolder.create(hierarchy, context);
        }


-  setImageUrl:

 public void setImageUrl(String url) {
        ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url))
                .build();
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        final DataSource<CloseableReference<CloseableImage>> dataSource =
                imagePipeline.fetchImageFromBitmapCache(imageRequest, this);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(mDraweeHolder.getController())
                .setImageRequest(imageRequest)
                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFinalImageSet(String s, @Nullable ImageInfo imageInfo, @Nullable Animatable animatable) {
                        try {
                            imageReference = dataSource.getResult();
                            if (imageReference != null) {
                                CloseableImage image = imageReference.get();
                                // do something with the image
                                if (image != null && image instanceof CloseableStaticBitmap) {
                                    CloseableStaticBitmap closeableStaticBitmap = (CloseableStaticBitmap) image;
                                    Bitmap bitmap = closeableStaticBitmap.getUnderlyingBitmap();
                                    if (bitmap != null) {
                                        setImageBitmap(bitmap);
                                    }
                                }
                            }
                        } finally {
                            dataSource.close();
                            CloseableReference.closeSafely(imageReference);
                        }
                    }
                })
                .setTapToRetryEnabled(true)
                .build();
        mDraweeHolder.setController(controller);
    }

**Comment by oprisnik** [comment]
Why are you not using a simple DraweeView?

First of all, you're only setting 1 bitmap that is available at the beginning, which is never updated - you have to set the drawable.
Second, you don't handle the Drawee lifecycle correctly (attach / detach events, setting the Drawable callback etc.).

Please use DraweeView instead or if you *really* need a custom view take a look at http://frescolib.org/docs/writing-custom-views.html

**Comment by caprice** [comment]
@oprisnik 

Actually, I am using [BubbleImageView](https://github.com/lguipeng/BubbleView), while simple  DraweeView extends ImageView. So I can't use SimpleDraweeView, or honestly to say, I have no idea how to do the same things as BubbleImageView when using SimpleDraweeView.

>First of all, you're only setting 1 bitmap that is available at the beginning, which is never updated - you have to set the drawable.
I don't understand what's your meaning, could you give me a simple example how should I do it. Thx!

The above the code is just one snippet in the whole class. I handle all the  Drawee lifecycle in it as the site you gave.

**Comment by caprice** [comment]
@oprisnik 
>First of all, you're only setting 1 bitmap that is available at the beginning, which is never updated - you have to set the drawable.

From your point, could you show me more details based on my requirement. Thanks!

**Comment by oprisnik** [comment]
As I have mentioned above, just make sure that your custom view does everything as described in http://frescolib.org/docs/writing-custom-views.html

Since you're extending `BubbleImageView`, which extends `ImageView`, you can take a look at [DraweeView](https://github.com/facebook/fresco/blob/4b94f604e0a98a999dcc1357992f8cb34b1b83b6/drawee/src/main/java/com/facebook/drawee/view/DraweeView.java).
If you want a simpler interface, you can also check out GenericDraweeView and SimpleDraweeView.

You cannot call `setImageBitmap` but have to use something like
`super.setImageDrawable(mDraweeHolder.getTopLevelDrawable());` (which is done in DraweeView as well)).

**Comment by caprice** [comment]
@oprisnik 
Thanks a lot for your detailed explanation. After I added ` mDraweeHolder.setController(controller) `below ` mDraweeHolder.setController(controller); `in my code the place holder image is showing correctly.

**Comment by 447zyg** [comment]
thanks very much! @caprice  @oprisnik
