### ISSUE TITLE
The  border is wrong when use 'roundingBorder' on android 4.x

### ISSUE THREAD

**Issue by kingty** [facebook/fresco#1324]
my xml settings is below:

```
     fresco:roundingBorderWidth="@dimen/border_size"  <1dp>
     fresco:roundingBorderColor="@color/black"
     fresco:roundedCornerRadius="@dimen/messages_item_corner_radius_small"  <4dp>
     fresco:roundTopLeft="true"
     fresco:roundTopRight="true"
     fresco:roundBottomLeft="false"
     fresco:roundBottomRight="false"
```

it works well after 5.0,but there is something wrong on 4.x as below:

![1467098377021](https://cloud.githubusercontent.com/assets/3754040/16407033/1d72f016-3d44-11e6-957f-fd7a986b6228.png)

the border's bottom line seems just below the bottom of the top corner the pic .
It's right after 5.x：
![screenshot_20160628-153139](https://cloud.githubusercontent.com/assets/3754040/16407325/bc41a0ce-3d45-11e6-8b16-5d6139005087.png)

**Comment by oprisnik** [comment]
This works for me on API19.
I just changed the SimpleDraweeView of our `uriapp` sampe and changed the background to white.

![screenshot_20160629-122543](https://cloud.githubusercontent.com/assets/2699634/16450483/16947696-3df5-11e6-98c8-cc03d6e3ea85.png)

```xml
    <com.facebook.drawee.view.SimpleDraweeView
      android:id="@+id/simple_drawee_view"
      android:layout_width="match_parent"
      android:layout_height="0dp"
      android:layout_weight="1"
      fresco:actualImageScaleType="fitCenter"
      fresco:roundingBorderWidth="1dp"
      fresco:roundingBorderColor="@android:color/black"
      fresco:roundedCornerRadius="4dp"
      fresco:roundTopLeft="true"
      fresco:roundTopRight="true"
      fresco:roundBottomLeft="false"
      fresco:roundBottomRight="false"
      fresco:failureImage="@color/red" />
```
(https://github.com/facebook/fresco/blob/89477f77af3b6954f57dc39b8c572b4b8eb4e84a/samples/uriapp/src/main/res/layout/activity_main.xml)

We need more information how you use Drawee.

**Comment by kingty** [comment]
@oprisnik 
thanks for your response .
```
<v.VDraweeView
                    android:id="@+id/profile_image"
                    android:layout_width="match_parent"
                    android:layout_height="216dp"
                    fresco:roundBottomLeft="false"
                    fresco:roundBottomRight="false"
                    fresco:roundTopLeft="true"
                    fresco:roundTopRight="true"
                    fresco:roundedCornerRadius="4dp"
                    fresco:roundingBorderColor="@color/black"
                    fresco:roundingBorderWidth="1dp"/>
```
These are all my xml settings, VDraweeView is a class extends SimpleDraweeView,just add a forgroud for it .
And my test phone is SUMSUNG  Galaxy Mega , Android 4.2.2 .

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
