### ISSUE TITLE
If i set maxsize/8 in DefaultBitmapMemoryCacheParamsSupplier class ?

### ISSUE THREAD

**Issue by duanyunfei** [facebook/fresco#1329]
If i set maxsize in DefaultBitmapMemoryCacheParamsSupplier class, change it form "maxMemory / 4" to "maxMemory / 8",  what will happen?  what it will cause other problems？
I find   if set "maxMemory / 4", much bitmaps occupy memory  ，not release。 if I load a map Module， maybe app OOM。

**Comment by oprisnik** [comment]
See the comment above the return statement for `getMaxCacheSize()`:
```
// We don't want to use more ashmem on Gingerbread for now, since it doesn't respond well to
// native memory pressure (doesn't throw exceptions, crashes app, crashes phone)
```
