### ISSUE TITLE
fresco:roundedCornerRadius  doesnt work with version 0.11.0!

### ISSUE THREAD

**Issue by JiaoShuai** [facebook/fresco#1332]
the following code doesnt work for fresco 0.11.0 while functional in 0.9.0+
in xml
`            
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/editer_icon"
                android:layout_width="32dp"
                android:layout_height="32dp"
                fresco:roundedCornerRadius="15dp"
                fresco:roundWithOverlayColor="@color/blue"
                fresco:roundingBorderWidth="1dp"
                fresco:roundingBorderColor="@color/red"/>`

in java

`editer_icon.setImageURI(imageUrl);`

in version 0.9.0+, the image is rounded as expected.

in version 0.11.0, the image is shown as it is, still rectangle.

**Comment by oprisnik** [comment]
It works for me, there must be another issue with your code.
My code:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/editer_icon"
        android:layout_width="32dp"
        android:layout_height="32dp"
        fresco:roundedCornerRadius="15dp"
        fresco:roundWithOverlayColor="#0000ff"
        fresco:roundingBorderWidth="1dp"
        fresco:roundingBorderColor="#ff0000"/>
</RelativeLayout>
```

```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fresco.initialize(this);
        setContentView(R.layout.activity_main);
        SimpleDraweeView sdv = (SimpleDraweeView)findViewById(R.id.editer_icon);
        sdv.setImageURI("http://lorempixel.com/800/800/");
    }
}
```

Looks like this:

![screenshot_20160630-141145](https://cloud.githubusercontent.com/assets/2699634/16489302/d4bfdaf2-3ecc-11e6-8c7b-1312c8cd21cf.png)

**Comment by oprisnik** [comment]
Side note: you can also use `roundAsCircle="true"` since it seems that you want a circle.

**Comment by lovearthhome** [comment]
@oprisnik thank you for your time, yes, i may have other specific reason in the project damage the effect. i will dig in.

**Comment by oprisnik** [comment]
I'm closing this but if you find this is a Fresco issue, please let us know and we will investigate.
