### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by OrangeHao** [facebook/fresco#1334]
my app run with 20mb memory normally.After I run monkey test on my device for 12 hours,the memory usage came to 80mb.Then I found that fresco take up a lot of memory.
Is there any idea to do with it?

Objects in memory:
![objects](https://cloud.githubusercontent.com/assets/13446529/16510779/aec8446a-3f7b-11e6-8a83-dcbfa36398ae.png)

A Detail of an object:
![details](https://cloud.githubusercontent.com/assets/13446529/16510788/beda72d8-3f7b-11e6-9763-0d1b46c90466.png)

**Comment by OrangeHao** [comment]
I  use fresco in a listview which has 150 items

**Comment by huangjunkun** [comment]
It must be you are use Fresco to load Bitmaps lacking of standardization.
Please check your code first.

**Comment by ijustyce** [comment]
@OrangeHao Try to use recyclerview, I used listview and found fresco used more than 300M, but when I used recyclewview and found fresco only used 100M
