### ISSUE TITLE
请问使用Fresco加载图片有时候会变成背景全部为黑色是怎么回事

### ISSUE THREAD

**Issue by caopeng000** [facebook/fresco#1337]
请问使用Fresco加载图片有时候会变成背景全部为黑色是怎么回事

**Comment by desmond1121** [comment]
@caopeng000 贴一下图

**Comment by massimocarli** [comment]
Hi @caopeng000 
could you provide more information please?
Thanks

**Comment by huangjunkun** [comment]
之前帮忙朋友分析、解决过比较多这种情况。
一般Fresco 初学使用者容易出现这样的错误情况：没有引用住 CloseableReference<CloseableImage> （没有clone 或者 太早调用close）方法引起Bitmap对象被回收了，而使用层还在使用Bitmap，这种情况就很容易导致图片都变黑了。

@caopeng000    可以检查你的代码是否存在这样的问题。

**Comment by caopeng000** [comment]
![3z1vi93ylzer 0j nfa uu](https://cloud.githubusercontent.com/assets/7322422/16573269/74c9ee18-42a4-11e6-84af-75e0dea366c8.jpg)

**Comment by massimocarli** [comment]
Hi @caopeng000 
are you using Drawee or accessing the Bitmap directly?

Thanks

**Comment by caopeng000** [comment]
@huangjunkun 我这种情况是属于几款机型，总是报了一些OpenGl OOM *** 不知道是不是和这个有关系

**Comment by s1rius** [comment]
I think why this happen is you use `Uri` like this:
```
Uri uri = Uri.parse("res://com.example.android" + R.drawable.ic_launcher);
```
Just change it to 
```
draweeView.getHierarchy().setPlaceholderImage(R.drawable.ic_launcher);
```
or
```
ImageRequestBuilder.newBuilderWithResourceId(R.drawable.ic_launcher)
```

ps:
When you ask a question, please provide more information like your code, device info, fresco version, android version, log and so on. This will save time.

**Comment by huangjunkun** [comment]
@caopeng000  你可以贴一下你的调用图片加载的那部分代码。

**Comment by e-hai** [comment]
@massimocarli
I have the same problem 
` Postprocessor redMeshPostprocessor = new BasePostprocessor() {

            public CloseableReference<Bitmap> process(Bitmap sourceBitmap, PlatformBitmapFactory bitmapFactory) {
                CloseableReference<Bitmap> bitmapRef = bitmapFactory.createBitmap(
                        sourceBitmap.getWidth(),
                        sourceBitmap.getHeight());
                try {
                    Bitmap destBitmap = bitmapRef.get();
                    for (int x = 0; x < destBitmap.getWidth(); x++) {
                        for (int y = 0; y < destBitmap.getHeight(); y++) {
                            destBitmap.setPixel(x, y, sourceBitmap.getPixel(x, y));
                        }
                    }
                    FastBlur.doBlur(destBitmap, 2, true);
                    return CloseableReference.cloneOrNull(bitmapRef);
                } finally {
                    CloseableReference.closeSafely(bitmapRef);
                }
            }
        };
        int width = simpleDraweeView.getWidth() / 8;
        int height = simpleDraweeView.getHeight() / 8;
        try {
            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setResizeOptions(new ResizeOptions(width, height))
                    .setPostprocessor(redMeshPostprocessor)
                    .build();
            PipelineDraweeController controller = (PipelineDraweeController)
                    Fresco.newDraweeControllerBuilder()
                            .setImageRequest(request)
                            .setOldController(simpleDraweeView.getController())
                            .build();
            simpleDraweeView.setController(controller);
        }catch (Exception e){
            e.printStackTrace();
        }`

**Comment by e-hai** [comment]
@huangjunkun 我也出现这种情况，你可以帮我看看吗？代码在上面

**Comment by caopeng000** [comment]
e-hai 你现在也是图片背景为黑色吗？

**Comment by caopeng000** [comment]
private void operateRound(int type) {
        ScalingUtils.ScaleType scaleType = getRealScaleTypeByImageView(getScaleType());
        if (onImageChangeListener != null) {
            getBitmap();
        }
        RoundingParams roundingMethod = null;
        switch (type) {
            case OperateType.CIRCLE:
                roundingMethod = RoundingParams.asCircle();// 圆形
                break;
            case OperateType.RADIUS:
                ImageRadius imageRadius = imageOption.getImageRadius();
                if (imageRadius != null) {
                    float topLeft = imageRadius.getTopLeftRadius();
                    float topRight = imageRadius.getTopRightRadius();
                    float bottomRight = imageRadius.getBottomRightRadius();
                    float bottomLeft = imageRadius.getBottomLeftRadius();
                    roundingMethod = RoundingParams.fromCornersRadii(topLeft, topRight, bottomRight, bottomLeft);
                } else {
                    roundingMethod = RoundingParams.fromCornersRadius(imageOption.getDegres());
                }
                break;
            default:
                break;
        }
        Uri url = Uri.parse(uri);
        try {
            GenericDraweeHierarchy genericDraweeHierarchy = getHierarchy();
            genericDraweeHierarchy.setRoundingParams(roundingMethod);
            genericDraweeHierarchy.setPlaceholderImage(getDrawable(imageOption.getImageResOnLoading()), scaleType);
            genericDraweeHierarchy.setFailureImage(getDrawable(imageOption.getImageResOnLoading()), scaleType);
        } catch (Exception exception) {
            KL.e(UniversalView.class, " getHierarchy()获取为空:{}", exception.toString());
        }
        setImageURI(url);
    }

**Comment by caopeng000** [comment]
@huangjunkun 代码贴上了还有一个就是监听回调

**Comment by huangjunkun** [comment]
@caopeng000   
 使用Fresco的DraweeView 就不用 ImageView的setImageURI 方法了啊，你这样混用会有问题的。
建议你先认真看下Fresco的使用文档：

> http://fresco-cn.org/docs/index.html#_

使用 DraweeView 时，请不要使用任何 ImageView 的属性

> http://fresco-cn.org/docs/gotchas.html#draweeview-imageview

**Comment by huangjunkun** [comment]
@e-hai  
Hi 你好，你的问题应该出现在其他地方，从你贴的代码看不出问题。
应该使用的 CloseableReference<Bitmap> 或CloseableReference<CloseableImage> 对象被外部其他逻辑 调用close，没有引用住，导致渲染显示时候Bitmap对象已经被recycle，图片显示就被黑了。

所以，你继续检查一下你的其他代码逻辑吧。

**Comment by caopeng000** [comment]
@ @huangjunkun 我用的是SimpleDraweeView，官方文档不都是直接设置.setImageURI(uri);
开始加载图片

Uri uri = Uri.parse("https://raw.githubusercontent.com/facebook/fresco/gh-pages/static/fresco-logo.png");
SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
draweeView.setImageURI(uri);
只不过又添加了GenericDraweeHierarchy 。这个有问题？

**Comment by huangjunkun** [comment]
@caopeng000 
"https://raw.githubusercontent.com/facebook/fresco/gh-pages/static/fresco-logo.png"， 404: Not Found
SimpleDraweeView对象使用setImageURI没问题，应该跟你自行添加的GenericDraweeHierarchy 。
正常情况下，GenericDraweeHierarchy 对象是内部自动设置的：
> com.facebook.drawee.view.GenericDraweeView#inflateHierarchy

不了解你那边详细关联代码逻辑，没有太多信息，无法帮你进一步分析，Sorry，你对着Fresco-Drawee源码，检查一下你的代码逻辑吧。加油！

**Comment by e-hai** [comment]
@huangjunkun 我在一个布局里面使用SimpleDraweeView引用了图片，布局里的viewpager也有个SimpleDraweeView引用了同一图片，切换后viewpager的图片变黑了

**Comment by huangjunkun** [comment]
@caopeng000  @e-hai 
注意一下Fresco的以下这点规范：

> http://frescolib.org/docs/using-drawees-code.html
**Customizing the hierarchy**
Calling setHierarchy more than once on the same view is usually unnecessary, even if the view is recycled. The hierarchy is expensive to create and in most cases you can just modify the existing hierarchy instead of creating a new one. Keep in mind that each instance of a DraweeView needs its own instance of a DraweeHierarchy. Same instance of a DraweeHierarchy is not to be used by multiple views. To change the actual image displayed by the view, use setController or setImageURI.

慎用：**setHierarchy**

**Comment by huangjunkun** [comment]
> http://frescolib.org/docs/gotchas.html
**Re-use Drawable resource IDs, not Java Drawable objects**
This is for the same reason as the above. Drawables cannot be shared in multiple views.
You can freely use the same @drawable resource ID as a placeholder, error, or retry in multiple SimpleDraweeViews in XML. If you are using GenericDraweeHierarchyBuilder, you must call Resources.getDrawable separate for each hierarchy. Do not call it just once and pass it to multiple hierarchies!

**Comment by bingzhao0719** [comment]
@caopeng000 我也遇到这个问题了，请问你解决了吗？我是用gridview显示图片列表，在adapter里拿到图片url后直接调用setImageURI(uri);然后一部分的图片全黑了，程序也卡住了

**Comment by erikandre** [comment]
Closing old issue since it needs been in "needs details" state since last year.

**Comment by JackSparrow6** [comment]
@bingzhao0719 你好，我也遇到跟你一样的问题，请问你的解决了吗？如果解决了，麻烦回复一下我解决的方案是怎样，谢谢！
