### ISSUE TITLE
setDownsampleEnabled(true)

### ISSUE THREAD

**Issue by AllenVork** [facebook/fresco#1343]
I use Fresco to load images and encounter a lot of bad things which make me really wanna give up.
Here are few:
resizeoption can only resize JPG, if i wanna resize png and such stuffs i should use setDownsampleEnabled(true). This option affects all the images that using fresco to load which means the image which you don't want to resize will also be resized automatically even if i didn't set resizeOption.This is what I am suffering now.I'm using PhotoDraweeView to zoom, which makes some image muzzy especially long images.I don't know how to solve it. I've tried to remove setDownsampleEnabled, but i know it's not a good solution.

**Comment by massimocarli** [comment]
Hi @AllenVork,
resizing can have some performance and memory implications. Can we place face a problem at a time? Could you provide us a specific example?
Thanks

**Comment by AllenVork** [comment]
@massimocarli I wanna load a lot of images in RecyclerView, in the case of memory and performance, i use setDownsampleEnabled(true) and resizeOption to show the thumbs. When the user click the image, I have to show the original image and support zoom.That's the problem.For I have used setDownsampleEnabled(true), the images are downSampled .When I zoom out, they are muzzle.

**Comment by AllenVork** [comment]
The resizeOption only works on JPG.If I don't use setDownsampleEnabled(true), the png and other format of images won't be resized then cause memory and performance problem.

**Comment by kirwan** [comment]
I've tried the zoomable sample app in the Fresco project and the image looks fine for me even with downsampling turned on.

I suggest you do two things:

1. Add a comment with the image request you're using with the PhotoDraweeView.
2. Look at http://frescolib.org/docs/troubleshooting.html and follow the steps in the **Investigating issues with logcat** section. In your case, I suggest particularly looking out for a "onProducerFinishWithSuccess" log for the DecodeProducer, which will include the size of the bitmap that's been decoded.

**Comment by kirwan** [comment]
Hi @AllenVork, is this still causing you a problem?

**Comment by anudeepreddygopu** [comment]
Hey, 
I am facing the same issue and it is troubling me

**Comment by ironmanTony** [comment]
In Application onCreate set setDownsampleEnabled true
```
ImagePipelineConfig imagePipelineConfig = ImagePipelineConfig.newBuilder(getApplicationContext())
                .setDownsampleEnabled(true)
                .build();
Fresco.initialize(getApplicationContext(), imagePipelineConfig);
```

and load a big image( eg:1080*19500) with SimpleDraweeView
**this picture is muzzy**

the load image code:
```
SimpleDraweeView simpleDraweeView = findViewById(R.id.simple_draweeview);
simpleDraweeView.setImageURI(uri);
```
in xml:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/atom_simple_draweeview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</LinearLayout>
```

**Comment by oprisnik** [comment]
What do you mean with "muzzy"? Do you have a sample image and can you post a comparison between original and downsampled image?

**Comment by ironmanTony** [comment]
<img width="277" alt="good" src="https://user-images.githubusercontent.com/5860185/33939082-bd9efb44-e044-11e7-9093-68be82957616.png">
<img width="281" alt="muzzy" src="https://user-images.githubusercontent.com/5860185/33939101-d0580726-e044-11e7-9946-15e82ab58c72.png">

origin image:
![screencapture-frescolib-org-docs-modifying-image-html-1512380318795](https://user-images.githubusercontent.com/5860185/33939160-0842b834-e045-11e7-9ac6-95a233e13db4.png)

**Comment by hjm1fb** [comment]
another simple solution is set the maxBitmapSize property in constructor method of ResizeOptions.
Debug this property, and you will find something interesting. For me, just use ResizeOption(width, height,4000) solves the problem.

**Comment by oprisnik** [comment]
Looks like there are some solutions that should mitigate this issue. Closing for now.
