### ISSUE TITLE
Some images loaded in corrupted way when scrolling fast up and down

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#1344]
In our chat app we use Fresco to show medias. At first we show blurred thumbnail. When image is visible for user it starts downloading original image from server and replace it with thumbnail. Problem is when you scroll fast up and then back some images get corrupted. Check screenshots.
We use this code for loading images into view.

```

private DraweeHolder<GenericDraweeHierarchy> draweeHolder;
private void loadImage(String filePath, String thumbUrl, boolean autoDownload) {
        ControllerListener<ImageInfo> controllerListener = new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                if (component != null) {
                    downloaded = true;
                    loaded = true;
                    createVideoMetaLayout();
                    parent.invalidate();
                }
            }

            @Override
            public void onFailure(String id, Throwable throwable) {
                if (component != null) {
                    downloaded = false;
                    createVideoMetaLayout();
                    if (thumbUrl != null) {
                        loadThumb(thumbUrl, autoDownload);
                    }
                }
            }
        };

        PipelineDraweeControllerBuilder controllerBuilder = Fresco.newDraweeControllerBuilder()
                .setImageRequest(MediaHelper.getImageRequest(filePath))
                .setControllerListener(controllerListener)
                .setOldController(draweeHolder.getController());

        if (thumbUrl != null) {
            controllerBuilder.setLowResImageRequest(getThumbnailRequest(thumbUrl));
        }

        draweeHolder.setController(controllerBuilder.build());
    }

```

![screenshot_20160707-102616 2](https://cloud.githubusercontent.com/assets/1390965/16642659/0595cfbc-442f-11e6-8591-2942a6caa4e7.png)
![screenshot_20160707-102632 2](https://cloud.githubusercontent.com/assets/1390965/16642660/05bb3860-442f-11e6-8a26-12c12f1b6843.png)
![screenshot_20160707-102644 3](https://cloud.githubusercontent.com/assets/1390965/16642661/05e5f208-442f-11e6-92a4-74509ae40366.png)

**Comment by massimocarli** [comment]
Hi @rafaelekol,
in order to understand what is happening could you please load the same images using our scrollperf demo app? There you can insert your URLs into a string-array resource and se what is happening. 
At first look it seems that you're loading local images. Are you applying the ResizeOptions? 

Thanks

**Comment by rafaelekol** [comment]
Yes we are using ResizeOptions, but our images not local, we are loading them from Server by URL.

```
public static ImageRequest getImageRequest(String filePath) {
        int imageSize = LayoutHelper.dp(100);
        return ImageRequestBuilder.newBuilderWithSource(Uri.fromFile(new File(filePath)))
                .setResizeOptions(new ResizeOptions(imageSize, imageSize))
                .setAutoRotateEnabled(true)
                .build();
    }
```

**Comment by massimocarli** [comment]
Hi @rafaelekol,
can you double check if the downloaded files are ok? I mean, just access the file system and check if the image files are corrupted during download. 
Thanks

**Comment by rafaelekol** [comment]
I haven't tried yet your sample app. But in our app, it behaves like this:
The problem occurs only when image is drawn into Drawee view. And images stays corrupted while in memory cache. When we click on corrupted images they open in fullview(even though they are using same image files, in fullview they are not corrupted). If I kill app and open it again, the images this time will load into Drawee from local cache without any corruption. Thus downloaded files are OK.

**Comment by nesterov-n** [comment]
@massimocarli Also faced with this problem. When I start the my app first time local images are loaded with corruptions.

**Comment by rafaelekol** [comment]
@nesterov-n how many images are you loading?

**Comment by nesterov-n** [comment]
@rafaelekol Same case. I'm trying to load up to 10 local photos. Each is about 500KB in size

**Comment by rafaelekol** [comment]
Our Fresco config code
```
DiskCacheConfig diskCacheConfig = DiskCacheConfig.newBuilder(context)
                .setBaseDirectoryPath(getExternalCacheDir())
                .setBaseDirectoryName("images")
                .setMaxCacheSize(50 * ByteConstants.MB)
                .setMaxCacheSizeOnLowDiskSpace(10 * ByteConstants.MB)
                .setMaxCacheSizeOnVeryLowDiskSpace(5 * ByteConstants.MB)
                .build();

        ImagePipelineConfig imagePipelineConfig = ImagePipelineConfig.newBuilder(context)
                .setMainDiskCacheConfig(diskCacheConfig)
                .setDownsampleEnabled(true)
                .build();

        Fresco.initialize(context, imagePipelineConfig);
```

**Comment by massimocarli** [comment]
Hi all,
now in `ImagePipelineExperiments` we have 2 experimental methods which allow us to test the max number of threads during decoding and the cancellation when `ImageRequest` are cancelled. The latter is very useful for local images. In particular I'm writing about:

[max number of decoding thread](https://github.com/facebook/fresco/blob/c07bb70d457f5cd27a4dde55a177d681942563b9/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipelineExperiments.java#L208)
```
public ImagePipelineConfig.Builder setThrottlingMaxSimultaneousRequests(
        int throttlingMaxSimultaneousRequests) 
```

and [enabled cancellation for cancelled requests](https://github.com/facebook/fresco/blob/c07bb70d457f5cd27a4dde55a177d681942563b9/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipelineExperiments.java#L172)
```
public ImagePipelineConfig.Builder setDecodeCancellationEnabled(
        boolean decodeCancellationEnabled)
```

Can you please test if, changing those parameters, you have the same problem?


Thanks

**Comment by rafaelekol** [comment]
@massimocarli  I couldn't figure out how to use this method `setDecodeCancellationEnabled`
Can you provide sample usage code.

**Comment by massimocarli** [comment]
Hi @rafaelekol,
an example is into the [ScrollPerf sample application](https://github.com/facebook/fresco/blob/master/samples/scrollperf/src/main/java/com/facebook/samples/scrollperf/ScrollPerfApplication.java#L47).
Thanks

**Comment by rafaelekol** [comment]
@massimocarli  I use Fresco 0.14.1, but I don't have this `setDecodeCancellationEnabled` method in my ImagePipelineExperiments class.

**Comment by oprisnik** [comment]
Can you try with newer versions of Fresco @rafaelekol? The issue does not reproduce for me in our Showcase sample app, so it's hard to say what's going on. If this is still a problem, let us know!
