### ISSUE TITLE
when use Fresco,have some  problem

### ISSUE THREAD

**Issue by 646448434** [facebook/fresco#1345]
When I listView use Fresco, each item needs to be loaded to load a low-resolution thumbnail, then reload a high-resolution map. Maybe not with fresco pictures downloaded downloaded when the first low-resolution thumbnails displayed in listView, when the second high-resolution image download cover down when the first, listView will flash once! You can achieve this by fresco gradual effect it?

**Comment by massimocarli** [comment]
Hi @646448434 
can you provide us more details please?
Thanks

**Comment by 646448434** [comment]
ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(Uri.parse(uri))
                .setProgressiveRenderingEnabled(true)
                .setResizeOptions(
                        new ResizeOptions(width, height)).setAutoRotateEnabled(true)
                .build();
        DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequest)
                .setOldController(view.getController())
                .setControllerListener(view.getListener())
                .setAutoPlayAnimations(true).build();
        view.setController(draweeController);


After downloading the first low-resolution maps, this method is called, downloading high-resolution maps, local view refresh

**Comment by 646448434** [comment]
In fact, there are two different resolutions, local maps, in listView replace the time how can we not blink? fresco provide that method can be used? thank you for your help

**Comment by moeintav** [comment]
hello i wanted to resize the image in fresco and your solution
 (((((ImageRequest imageRequest = ImageRequestBuilder
.newBuilderWithSource(Uri.parse(uri))
.setProgressiveRenderingEnabled(true)
.setResizeOptions(
new ResizeOptions(width, height)).setAutoRotateEnabled(true)
.build();
DraweeController draweeController = Fresco.newDraweeControllerBuilder()
.setImageRequest(imageRequest)
.setOldController(view.getController())
.setControllerListener(view.getListener())
.setAutoPlayAnimations(true).build();
view.setController(draweeController); )))))
very helpfull for me

**Comment by lambdapioneer** [comment]
@646448434 using `setLowResImageRequest` should solve the issue for you (see http://frescolib.org/docs/requesting-multiple-images.html)

When using this, make sure that you only create one image request and controller in total.

If there's any other issue, feel free to re-open this issue.
