### ISSUE TITLE
Why the two lines are grey？

### ISSUE THREAD

**Issue by xiedong** [facebook/fresco#1346]
![b9_0 1 df tjs y w8dhh](https://cloud.githubusercontent.com/assets/5304861/16650851/e13198f6-4472-11e6-9574-32064b037fda.png)
 Configured compile 'com.facebook.fresco:fresco:0.11.0'
Do you need any other？

**Comment by massimocarli** [comment]
Hi @xiedong,
the question is not related to Fresco. Anyway those lines are gray because the related namespaces are not used in the layout :)
Thanks
