### ISSUE TITLE
Is there any way to load part of a image? 

### ISSUE THREAD

**Issue by JiaoShuai** [facebook/fresco#1347]
Due to very specific needs, i need to load part of a image( since the image is too long that exceeds the 4096x4096 limit). how to do that elegantly using fresco. 

like the bold line following:

GenericDraweeHierarchy hierarchy = builder
    .setFadeDuration(300)
    .setPlaceholderImage(new MyCustomDrawable())
    .setBackgrounds(backgroundList)
    .setOverlays(overlaysList)
    **.setCropRegion(0,0,imageWidth,4096)**
    .build();
mSimpleDraweeView.setHierarchy(hierarchy);

**Comment by lovearthhome** [comment]
up, same needs!

**Comment by massimocarli** [comment]
Hi,
we planned to do that. At the moment you can use the [focusCrop](http://frescolib.org/docs/scaling.html#focusCrop) ScaleType. 
Thanks

**Comment by JiaoShuai** [comment]
@massimocarli  thankyou for your time and thanks to your plan. I should clarify my idea to disper misunderstandings for my thoughts before.  Current now, yes, i can use  focusCrop  to show top part of the iamge, but for image that exceeds 4096x4096, fresco just log errors. to avoid the embarrasement, i have to setResizeOption(resizeWidth,4096) , which makes very long image looking vague(due to downsampling).  the key solution is, of course, not to wrap focusCrop in a more easy-to-use way, but is, provide some interface to really crop the image and still maintain the resolution.

**Comment by massimocarli** [comment]
Hi @JiaoShuai,
sure I understand what you're saying. Loading a "cropped" means loading (and decoding) only the part of interest with a lot of savings in memory. That's what I meant as the plan for a kind of CropParams :) This is not in our immediate plan but if you like challenges you could create a PR for it.
Thanks

**Comment by lovearthhome** [comment]
@massimocarli  thanks a lot, nice talking with you! ^_^
