### ISSUE TITLE
Crash when init Fresco

### ISSUE THREAD

**Issue by MichaelArchangel** [facebook/fresco#1348]
after upgrading to 0.11, APP crashs when init Fresco...

	private void FrescoInit() {
		int maxHeapSize = (int) Runtime.getRuntime().maxMemory();
		final int maxMemoryCacheSize = maxHeapSize / 4;
		//	public static final int maxDiskCacheSize = 40 * ByteConstants.MB;
		final int maxDiskCacheSize = maxMemoryCacheSize * 2 / 1000 / 1000;//in MB
		//ImagePipelineConfig.Builder configBuilder = OkHttpImagePipelineConfigFactory.newBuilder(this, getAngelNetInstance().getClient());
		ImagePipelineConfig config = OkHttpImagePipelineConfigFactory
				.newBuilder(this, getAngelNetInstance().getClient())
				.setDownsampleEnabled(true)
				.setBitmapMemoryCacheParamsSupplier(
						new Supplier<MemoryCacheParams>() {
							public MemoryCacheParams get() {
								return new MemoryCacheParams(
										maxMemoryCacheSize, // Max total size of elements in the cache
										Integer.MAX_VALUE,                     // Max entries in the cache
										maxMemoryCacheSize, // Max total size of elements in eviction queue
										Integer.MAX_VALUE,                     // Max length of eviction queue
										Integer.MAX_VALUE);                    // Max cache entry size
							}
						})
				.setMainDiskCacheConfig(
						DiskCacheConfig.newBuilder(this)
								.setBaseDirectoryPath(getApplicationContext().getCacheDir())
								.setBaseDirectoryName("imagepipeline_cache")
								.setMaxCacheSize(maxDiskCacheSize)
								.build())
		.build();
		//Fresco.initialize(this);
		Fresco.initialize(this, config);
	}

It thows a RuntimeException at com.facebook.imagepipeline.core.ImagePipelineConfig.<init>(ImagePipelineConfig.java:170), seems that 

    mCustomLocalProducerSequenceFactory = builder.mCustomProducerSequenceFactory;
    mImagePipelineExperiments = builder.mExperimentsBuilder.build();
    mCustomLocalProducerSequenceFactory.init(getExecutorSupplier(),
                        getPoolFactory().getPooledByteBufferFactory(),
                     mImagePipelineExperiments.isDecodeFileDescriptorEnabled());

builder.mCustomProducerSequenceFactory is null so mCustomLocalProducerSequenceFactory.init() throws the exception.

The default init method without config parameter is also not working...What's wrong?

**Comment by massimocarli** [comment]
Hi @MichaelArchangel 
could you provide us the stack trace please?
Thanks

**Comment by massimocarli** [comment]
HI,
are you sure you're running 0.11? I cannot find correspondence from the line in the stacktrace and the code.

**Comment by massimocarli** [comment]
Hey @MichaelArchangel 
did you customize the code? Actually that's not our code. We don't provide  custom ProducerSequenceFactory. If you do that you should also provide an implementation. Anyway this is not a think you can customize in Fresco. At least at the moment.

**Comment by MichaelArchangel** [comment]
@massimocarli I just added this and that code  appeared:
dependencies {
    compile 'com.facebook.fresco:fresco:0.11.0'
    compile "com.facebook.fresco:imagepipeline-okhttp3:0.11.0"
}
