### ISSUE TITLE
[Request] How to disable DraweeEventTracker?

### ISSUE THREAD

**Issue by ex3ndr** [facebook/fresco#1349]
In our chat application fast scrolling of list of chats causes many calls to DraweeEventTracker that calls DraweeEventTracker that have ArrayBlockingQueue that locks thread for 15% for nothing on slow devices doing this even when logging is not used at all. It will be nice to have something to disable this calls or change collection to more performant one.

**Comment by aagnes** [comment]
We don't have a way to disable DraweeEventTracker without modifying fresco's source code at the moment. We definitely should provide a way to disable logging in the future.

**Comment by eldk** [comment]
Hello,
This is done here : https://github.com/facebook/fresco/commit/8f4978ea3460e1badc1c94b5cbdf136ea583cb0e

**Comment by oprisnik** [comment]
@eldk is right, the code to disable looks like this:

    DraweeEventTracker.disable();
    Fresco.initialize(...);
