### ISSUE TITLE
What can I remove controllerListener?

### ISSUE THREAD

**Issue by BruceeWang** [facebook/fresco#1352]
ControllerListener listener = new BaseControllerListener()； 
simpledraweeview.setController(controller);

I want to remove this controller in onDestroy method, but I don't know how to remove this controllerListener.
（English is not very well,please excuse me）

**Comment by aagnes** [comment]
Why exactly do you need to put the listener in onDestroy?

**Comment by BruceeWang** [comment]
I want to remove listener,not set the listener in onDestroy.I put listener in onCreat method.
@aagnes 
(English is not very well,please excuse me)

**Comment by aagnes** [comment]
you can removeListener from controller and reset listener to null in onDestroy().

**Comment by BruceeWang** [comment]
Thank you,I will try to do this method.
@aagnes
