### ISSUE TITLE
Memory issues because of usage of Object.finalize() 

### ISSUE THREAD

**Issue by fab1an** [facebook/fresco#1354]
I've reported an issue in react-native, that applies here as well: https://github.com/facebook/react-native/issues/8711

**Comment by narychen** [comment]
Oh I didn't see you opened an issue already. I just opened another same issue here.

**Comment by narychen** [comment]
I noticed a important clue on Fresco site.
```
Memory
A decompressed image - an Android Bitmap - takes up a lot of memory. This leads to more frequent runs of the Java garbage collector. This slows apps down. The problem is especially bad without the improvements to the garbage collector made in Android 5.0.
On Android 4.x and lower, Fresco puts images in a special region of Android memory. It also makes sure that images are automatically released from memory when they’re no longer shown on screen. This lets your application run faster - and suffer fewer crashes.
Apps using Fresco can run even on low-end devices without having to constantly struggle to keep their image memory footprint under control.
```
Which I found on my android 4.3 phone, the memory usage is very low around 20M-30M, no matter how many pictures you browse. So I think the leaks exist on the special region of Android memory, not java. And finalize is not the cause of these problems.

**Comment by fab1an** [comment]
Here  (#8711) you can find a lengthy explanation why `Object.finalize()` is bad, but the two main reasons, why Fresco should stop using it are:

1. The `FinalizerQueue` can fill-up and stop being processed, this can happen for many reasons, and it's possible that `Object.finalize()` is **never** called until the JVM exits. This also means that, *every* object that's referenced from an object whose finalizer isn't called, isn't garbage-colllected.

2. Finalizers slow everything down by a giant amount. Quote from effective java:
    > Oh, and one more thing: there is a severe performance penalty for using finalizers. On my machine, the time to create and destroy a simple object is about 5.6 ns. Adding a finalizer increases the time to 2,400 ns. In other words, it is about 430 times slower to create and destroy objects with finalizers.

**Comment by fab1an** [comment]
Closing in favor of #1363 .
