### ISSUE TITLE
Fresco stops VRPanoview from working

### ISSUE THREAD

**Issue by MikeDocherty1991** [facebook/fresco#1359]
Hello 

This is a very unusual bug that i can't quite explain fully. 

We currently have a group of 5 tabbed lists inside our main activity. In each list we display a list of Imageview's, which direct the user to various places in our app , generally depending on which list the user selects an item from. 

In one list, the top item is a VRPanoramaView from the google cardboard sdk. (This class here: https://developers.google.com/vr/android/). 

However, when i add the current Fresco build as a dependency in the gradle build this causes the   VRPanoramaView to crash. Specifically i don't need to initialize Fresco for it to crash and give the error below. 

I have included the (very long) stack trace. 

> 07-13 14:49:48.098 32081-32081/com.gettyimages.gettyimages W/System.err: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
> 07-13 14:49:48.098 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
> 07-13 14:49:48.099 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 07-13 14:49:48.099 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.gettyimages.gettyimages.adapters.VrRecyclerAdapter.onCreateViewHolder(VrRecyclerAdapter.java:46)
> 07-13 14:49:48.099 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.gettyimages.gettyimages.adapters.VrRecyclerAdapter.onCreateViewHolder(VrRecyclerAdapter.java:27)
> 07-13 14:49:48.100 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
> 07-13 14:49:48.100 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
> 07-13 14:49:48.100 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
> 07-13 14:49:48.101 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
> 07-13 14:49:48.101 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:528)
> 07-13 14:49:48.101 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
> 07-13 14:49:48.101 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
> 07-13 14:49:48.102 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
> 07-13 14:49:48.102 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
> 07-13 14:49:48.102 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
> 07-13 14:49:48.103 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
> 07-13 14:49:48.103 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.103 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.104 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
> 07-13 14:49:48.104 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.104 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.105 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
> 07-13 14:49:48.105 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.105 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.106 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
> 07-13 14:49:48.106 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.106 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.107 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 07-13 14:49:48.107 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 07-13 14:49:48.107 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.108 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.108 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
> 07-13 14:49:48.108 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
> 07-13 14:49:48.109 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
> 07-13 14:49:48.109 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.109 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.110 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 07-13 14:49:48.110 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 07-13 14:49:48.110 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.110 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.111 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
> 07-13 14:49:48.111 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
> 07-13 14:49:48.111 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
> 07-13 14:49:48.112 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.112 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.112 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
> 07-13 14:49:48.113 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
> 07-13 14:49:48.113 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
> 07-13 14:49:48.113 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.View.layout(View.java:16636)
> 07-13 14:49:48.114 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
> 07-13 14:49:48.114 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
> 07-13 14:49:48.114 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
> 07-13 14:49:48.115 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
> 07-13 14:49:48.115 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
> 07-13 14:49:48.115 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
> 07-13 14:49:48.116 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
> 07-13 14:49:48.116 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:606)
> 07-13 14:49:48.116 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
> 07-13 14:49:48.117 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
> 07-13 14:49:48.117 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
> 07-13 14:49:48.117 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.os.Looper.loop(Looper.java:148)
> 07-13 14:49:48.118 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5422)
> 07-13 14:49:48.118 32081-32081/com.gettyimages.gettyimages W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 07-13 14:49:48.118 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 07-13 14:49:48.119 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 07-13 14:49:48.119 32081-32081/com.gettyimages.gettyimages W/System.err: Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView
> 07-13 14:49:48.120 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
> 07-13 14:49:48.120 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
> 07-13 14:49:48.120 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
> 07-13 14:49:48.121 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
> 07-13 14:49:48.121 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
> 07-13 14:49:48.121 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 07-13 14:49:48.122 32081-32081/com.gettyimages.gettyimages W/System.err:    ... 63 more
> 07-13 14:49:48.122 32081-32081/com.gettyimages.gettyimages W/System.err: Caused by: java.lang.reflect.InvocationTargetException
> 07-13 14:49:48.122 32081-32081/com.gettyimages.gettyimages W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
> 07-13 14:49:48.123 32081-32081/com.gettyimages.gettyimages W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
> 07-13 14:49:48.123 32081-32081/com.gettyimages.gettyimages W/System.err:    ... 68 more
> 07-13 14:49:48.124 32081-32081/com.gettyimages.gettyimages W/System.err: Caused by: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-support-annotations-23.4.0_5cd8e6e3877f47f0e817780a8ed2a36eb4b88110-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-retrofit-2.1.0_65fda88ea2872fab022cc9db29f3b03e836159c4-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-picasso-2.5.2_1e05e027dfaf3abf506b0227b59cc61427232314-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-okio-1.8.0_3a1fd32557e466c4f6e67a5b743858ad0c4294ec-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-okhttp-3.3.0_cfea126b83a7c2a6942ede9e30cfb6c5a1987793-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-library-2.4.0_3773720b2c4e1291f95e38a753b3e831fa3c9a59-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-internal_impl-23.4.0_570ddb20e6e80ad7b7a43cb88a24aa59f977951f-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-gson-2.7_ca4f096090797f6330494c5b786cc9ce1ba1931e-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-eventbus-3.0.0_537875a51da47435038f79846dd96de13e176a35-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-cupboard-2.1.4_f768f29d915cd1dfa3b3dee643fe2cbb41aa7321-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-converter-gson-2.1.0_99ab612108d2fa02f0d04849c115921b795748c4-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.squareup.leakcanary-leakcanary-android-no-op-1.4-beta2_fcc0b7d2014e52222011d576cade6d66d5c139cb-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.makeramen-roundedimageview-2.2.1_adddd195cbf00e19397b4b7ca1e7671a14d2d6ab-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.google.firebase-firebase-iid-9.0.2_c6599cd2f2675ed3cdde97dcf5bce80fc7ce0ecc-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.google.firebase-firebase-crash-9.0.2_e0f6767ded6511c5a1e774dc5b7610733124d70d-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.google.firebase-firebase-common-9.0.2_b3dc09ed85985ab360ed4fa865d4ebc67c49e007-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.google.firebase-firebase-analytics-impl-9.0.2_96859d0068c1944e14ed69cd9dcc36f58f3b8d97-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.google.firebase-firebase-analytics-9.0.2_33e908685672f4be3ffa590997e82f72ca7e6e0e-classes.dex", dex file "/data/data/com.gettyimages.gettyimages/files/instant-run/dex/slice-com.
> 07-13 14:49:48.126 32081-32081/com.gettyimages.gettyimages W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:367)
> 07-13 14:49:48.126 32081-32081/com.gettyimages.gettyimages W/System.err:     at java.lang.System.loadLibrary(System.java:1076)
> 07-13 14:49:48.126 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.<init>(VrPanoramaRenderer.java:30)
> 07-13 14:49:48.127 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.google.vr.sdk.widgets.pano.VrPanoramaView.createRenderer(VrPanoramaView.java:99)
> 07-13 14:49:48.127 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.google.vr.sdk.widgets.pano.VrPanoramaView.createRenderer(VrPanoramaView.java:14)
> 07-13 14:49:48.127 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.google.vr.sdk.widgets.common.VrWidgetView.initializeRenderingView(VrWidgetView.java:306)
> 07-13 14:49:48.128 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.google.vr.sdk.widgets.common.VrWidgetView.init(VrWidgetView.java:218)
> 07-13 14:49:48.128 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.google.vr.sdk.widgets.common.VrWidgetView.<init>(VrWidgetView.java:171)
> 07-13 14:49:48.128 32081-32081/com.gettyimages.gettyimages W/System.err:     at com.google.vr.sdk.widgets.pano.VrPanoramaView.<init>(VrPanoramaView.java:0)
> 07-13 14:49:48.129 32081-32081/com.gettyimages.gettyimages W/System.err:    ... 70 more

I don't really understand what is causing this issue. Though i have come across this: https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/native which seems to be somewhat similar to my issue. 
Thanks 
Mike

**Comment by NormW** [comment]
you could add following in your app gradle defaultConfig
```
    defaultConfig {
           ....
        ndk {
            abiFilters 'armeabi-v7a', "x86"
        }
    }
```

[more detail](http://stackoverflow.com/questions/38889814/adding-fresco-library-breaks-android-project)

**Comment by erikandre** [comment]
The log indicates that instant run was enabled for the build. If this bug report is still relevant, try disabling it and see if that helps.
