### ISSUE TITLE
Problem ： "AsCircle "

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#136]
Required: Large View, small picture, show as circle
Setting(in sample code):
 protected InstrumentedDraweeView createView() {
    GenericDraweeHierarchy gdh = new GenericDraweeHierarchyBuilder(getContext().getResources())
        .setPlaceholderImage(Drawables.sPlaceholderDrawable)
        .setFailureImage(Drawables.sErrorDrawable)
        .setRoundingParams(RoundingParams.asCircle())
        .setProgressBarImage(new ProgressBarDrawable())
        .setActualImageScaleType(ScaleType.CENTER_CROP)
        .build();
    return new InstrumentedDraweeView(getContext(), gdh);
  }
protected void bind(final InstrumentedDraweeView view, String uri) {
      view.setAdjustViewBounds(true);
    ImageRequest imageRequest =
        ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
            .build();
    DraweeController draweeController = Fresco.newDraweeControllerBuilder()
        .setImageRequest(imageRequest)
        .setOldController(view.getController())
        .setControllerListener(view.getListener())
        .setAutoPlayAnimations(true)
        .build();
    view.setController(draweeController);
  }
Result:
![9fc174b15b7d3aaa0d0933759d63c492](https://cloud.githubusercontent.com/assets/11832023/7108433/12fe971c-e1b9-11e4-9589-71ebc6696f65.jpg)
url="http://ktvme.qiniudn.com/jpg/9fc174b15b7d3aaa0d0933759d63c492.jpg"

but what i need is : 
![qq 20150413083933](https://cloud.githubusercontent.com/assets/11832023/7108438/36a4a12a-e1b9-11e4-9a51-e5bd263d3a66.jpg)

**Comment by ICECHN** [comment]
The error result is : 
![error](https://cloud.githubusercontent.com/assets/11832023/7108439/54d8b67c-e1b9-11e4-88c0-c2b2996fe2db.jpg)

**Comment by ICECHN** [comment]
Why?

**Comment by tyronen** [comment]
Are you trying to show an animated image in a circle? You must use an overlay color to do that:

```java
  RoundingParams.asCircle().setOverlayColor(R.color.white);
``` 

Also, you probably don't need to use `InstrumentedDraweeView`. Use `SimpleDraweeView` instead.

**Comment by plamenko** [comment]
It is not clear to me what's the issue. Please take a look at http://frescolib.org/docs/rounded-corners-and-circles.html#_
