### ISSUE TITLE
Fresco in listView

### ISSUE THREAD

**Issue by 646448434** [facebook/fresco#1361]
When I listView use Fresco, each item needs to be loaded to load a low-resolution thumbnail, then reload a high-resolution map. Maybe not with fresco pictures downloaded downloaded when the first low-resolution thumbnails displayed in listView, when the second high-resolution image download cover down when the first, listView will flash once! You can achieve this by fresco gradual effect it?

**Comment by lambdapioneer** [comment]
Hi @646448434, have a look at our sample app `scrollperf` on how to use Fresco with a list view. If the issue persists, please provide us with a small example that can reproduce the issue.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
