### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/facebook/common/executors/UiThreadImmediateExecutorService

### ISSUE THREAD

**Issue by Nimrodda** [facebook/fresco#1368]
Recently, I added RxJava and Retrolambda dependencies to my app and reached the 64K method limit, so I had to enable the new [Shrinker](http://tools.android.com/tech-docs/new-build-system/built-in-shrinker) for debug builds in `build.gradle`:
```
    buildTypes {
        debug {
            minifyEnabled true
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
   ...
```

Since then, my app started to randomly crash on start up with the following exception:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/common/executors/UiThreadImmediateExecutorService;
at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:60)
at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:40)
at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:34)
at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:43)
at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:33)
```

As said, It happens randomly during development (Android Studio 2.1.2) when I build and run the app on my test device - Nexus 6 (Android v6). Sometimes the app starts just fine and all images are loaded perfectly fine. Then I make some code modifications and run the app again and it might or might not crash with this exception.

**Please note**, when I disable the Shrinker and remove the newly added dependencies, going back under the 65K limit, everything works fine I do not get this exception anymore. So this is tightly related to **enabling the Shrinker**.

According to the new Shrinker docs, it is using the Proguard rules defined by `proguardFiles`. Here is my Proguard rules for Fresco:

```
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers class * {
    native <methods>;
}

-dontwarn okio.**
-dontwarn com.squareup.okhttp.**
-dontwarn javax.annotation.**
-dontwarn com.android.volley.toolbox.**
```

I additionally tested it on my emulator Nexus 5X x86_64 running Android 6 (API 23) and an old Android device with Android 4.4.2. They all randomly get this crash.

### Extra details about my build set up

* Android Gradle plugin 2.0.0 with Gradle wrapper version 2.14.
* Split by architecture (**worked flawlessly so far**):
```
splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk false
        }
    }
```
* compileSdkVersion 24
* buildToolsVersion "23.0.2"
* minSdkVersion 16
* targetSdkVersion 23
* Fresco version 0.11.0 via its Gradle depedency `compile 'com.facebook.fresco:fresco:0.11.0'`
* I do not use multidexing

**Comment by kirwan** [comment]
It seems that shrinker is currently only experimental, as per this page: http://tools.android.com/tech-docs/new-build-system/built-in-shrinker

So, if you're having a problem it might be worth creating an issue in Google's Issue Tracker. Also, you could try removing the `useProguard false` line to use Proguard instead of the new shrinker.

I've just tried to reproduce your issue with the Fresco demo app but have not been able to.

**Comment by Nimrodda** [comment]
Eventually, I enabled multidex for debug builds instead of using the new shrinker for debug builds. I use proguard for release builds. Thanks for your help.
