### ISSUE TITLE
upgrade webp lib from 0.4.3 to 0.5.1

### ISSUE THREAD

**Issue by alexodus** [facebook/fresco#1369]
In the new versions there are a lot of improvements for mobile device.

**Comment by kirwan** [comment]
We will look into this. If you'd like to send us a pull request it would probably happen a bit sooner though.

**Comment by eldk** [comment]
Hello,

This have been done here :  https://github.com/facebook/fresco/pull/1377

Thanks,

Eric

**Comment by eldk** [comment]
Hello,

I think this should be closed.

Thanks,

Eric

https://github.com/facebook/fresco/commit/c142b3e84774a87594344613be4fad77f90f726f
