### ISSUE TITLE
BaseRepeatedPostProcessor documentation inconsistency

### ISSUE THREAD

**Issue by aneophyte** [facebook/fresco#1372]
[Repeated Postprocessors section](http://frescolib.org/docs/modifying-image.html) seem to not match with how `BaseRepeatedPostProcessor` actually works.

`BaseRepeatedPostProcessor` only invokes some callback and I'm not sure how `update()` will actually call `process()` or any related method. Clarifications please.

**Comment by lambdapioneer** [comment]
The documentation seems correct to me.

You can see how the repeated post processor works internally here: https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/imagepipeline/src/main/java/com/facebook/imagepipeline/request/BaseRepeatedPostProcessor.java#L25-L29

For your code, you just need to make sure that the `update()` method is called in your new sub class when you want to re-apply the post processor (as it is done in the example).  The callbacks will be set by the internals of the ImagePipeline.

**Comment by aneophyte** [comment]
It didn't work. Tried subclassing and called `update()`.

Also, `update()` doesn't seem to do anything according to its implementation. It looks like it only invokes the callback we set. As you can see it first calls `getCallback()` which returns `mCallback` but `mCallback` is set via a `setCallback()` method which is public. And that callback's `update()` method is called if the said callback is not `null`.

Will try running the example code in the docs. Still the implementation doesn't suggest any update being made.
