### ISSUE TITLE
proguard file should be up to date

### ISSUE THREAD

**Issue by AllenVork** [facebook/fresco#1373]
After copying the proguard file to my project.There comes few problems for I used the animated-gifs and okhttp3.
So I add the following rules to my proguard file and it works well.So I hope you to add it to the official website in case of other people got trapped.

//this is for animated-gifs. Without it, you can run your project successfully but the animated-gifs won't animate.
```java
    -keep class com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl { 
              public AnimatedFactoryImpl(com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory,       
              com.facebook.imagepipeline.core.ExecutorSupplier); 
    }
```
//This is for okhttp3
```java
    -dontwarn okhttp3.**
```

**Comment by kirwan** [comment]
Thanks for both of those, I'll update the Proguard file we point people to.

We have fixed the animated GIF example but that's not been released yet, so you're right that bug still exists in the latest release.
