### ISSUE TITLE
PlaceHolder display error

### ISSUE THREAD

**Issue by ArtisanM** [facebook/fresco#1374]
做夜间模式时需要更换占位图，我通过定义attr，在不同的theme下引用了不同的图。然后在代码中通过
`((SimpleDraweeView) image).getHierarchy().setPlaceholderImage(R.mipmap.xxxx)`
来切换占位图。

两张占位图，一张是一只颜色为#E0DFDF的猫，另一张是颜色为#2C2C2C的猫

点击切换按钮，代码中进行了切换后，占位图实际显示出的猫是正常的，但是颜色不对，分别为#9D9E99 （预期#E0DFDF），和#1F1F1F （预期 #2C2C2C）。只有在退出App再重进时，占位图才显示正常

-----------

I am using SimpleDraweeView to show image. When i use custom attr to reference 2 different images as placeholder in different theme, and when i change the theme, i replace the placeholder in code like this:

`
if (day) {
  ((SimpleDraweeView) image).getHierarchy().setPlaceholderImage(R.mipmap.default_day);
} else {
  ((SimpleDraweeView) image).getHierarchy().setPlaceholderImage(R.mipmap.default_night);
}
`

R.mipmap.default_day is a cat with color #E0DFDF, and R.mipmap.default_night is a cat with color #2C2C2C

When i change the theme, the placeholder in day theme shows a cat with color #9D9E99, and #1F1F1F in night theme.

Until i restart the App it shows the right color.

**Comment by lambdapioneer** [comment]
Hi @ArtisanM, can you clarify the issue you are facing? Is it about missing persistency of the attribute or about a wrong display of the color? Ideally, you can provide us with an example that helps us to reproduces the issue.

Additionally: Are the themes you are mentioning on OS level or are they specific to your app?
