### ISSUE TITLE
Downloaded transparent png image via BaseBitmapDataSubscriber gets black background

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#1376]
I am downloading png image with transparancy via BaseBitmapDataSubscriber. The resulted bitmap instead of transparent parts shows black color.

This is my code.

```
ImageRequest imageRequest = ImageRequestBuilder
                            .newBuilderWithSource(Uri.parse(clickedItem.imageUrl))
                            .build();

                    ImagePipeline imagePipeline = Fresco.getImagePipeline();
                    DataSource<CloseableReference<CloseableImage>>
                            dataSource = imagePipeline.fetchDecodedImage(imageRequest, App.getContext());

                    dataSource.subscribe(
                            new BaseBitmapDataSubscriber() {
                                @Override
                                public void onNewResultImpl(@Nullable Bitmap bitmap) {
                                    //here I get bitmap with black background instead of transparancy
                                }


                            },
                            CallerThreadExecutor.getInstance());
```

![screenshot_20160719-183639 2](https://cloud.githubusercontent.com/assets/1390965/16950061/0e0cbd6c-4de0-11e6-9ad8-fd61f5c415db.png)

**Comment by kirwan** [comment]
The image you've shared here looks a lot like a JPEG (in which transparency isn't supported) but that might just be from your screenshot. Can you share the URL of the image in question?

**Comment by rafaelekol** [comment]
You  were right bitmap was saving as JPG format. with this method:
bitmap.compress(Bitmap.CompressFormat.JPEG, quality, new FileOutputStream(filePath));

I changed it to PNG and transparency preserved. Thank you for your help.
