### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by huli1987** [facebook/fresco#1379]
ava.lang.ExceptionInInitializerError: empty message
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.com.facebook.imagepipeline.memory.NativeMemoryChunk alloc(int)(NativeMemoryChunkPool.java:60)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.void free(java.lang.Object)(NativeMemoryChunkPool.java:22)
java.lang.Object alloc(int)
com.facebook.imagepipeline.memory.BasePool.java.lang.Object get(int)(BasePool.java:259)
com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.void <init>(com.facebook.imagepipeline.memory.NativeMemoryChunkPool,int)(NativePooledByteBufferOutputStream.java:53)
com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.NativePooledByteBuffer newByteBuffer(java.io.InputStream,int)(NativePooledByteBufferFactory.java:98)
com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.PooledByteBufferOutputStream newOutputStream()(NativePooledByteBufferFactory.java:26)
com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(java.io.InputStream,int)
com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(byte[])
com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(java.io.InputStream)
com.facebook.imagepipeline.cache.BufferedDiskCache.com.facebook.imagepipeline.memory.PooledByteBuffer readFromDiskCache(com.facebook.cache.common.CacheKey)(BufferedDiskCache.java:316)
com.facebook.imagepipeline.cache.BufferedDiskCache.com.facebook.imagepipeline.cache.StagingArea access$000(com.facebook.imagepipeline.cache.BufferedDiskCache)(BufferedDiskCache.java:38)
com.facebook.imagepipeline.memory.PooledByteBuffer access$400(com.facebook.imagepipeline.cache.BufferedDiskCache,com.facebook.cache.common.CacheKey)
void access$500(com.facebook.imagepipeline.cache.BufferedDiskCache,com.facebook.cache.common.CacheKey,com.facebook.imagepipeline.image.EncodedImage)
com.facebook.imagepipeline.cache.BufferedDiskCache$2.com.facebook.imagepipeline.image.EncodedImage call()(BufferedDiskCache.java:162)
com.facebook.imagepipeline.cache.BufferedDiskCache$2.java.lang.Object call()(BufferedDiskCache.java:146)
bolts.Task$2.void run()(Task.java:195)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
java.lang.Thread.run(Thread.java:856)

**Comment by lambdapioneer** [comment]
Can you tell us if you are using the latest version `0.12.0`?

If the issue persists, please provide some additional information. Ideally a minimal piece of code that can reproduce the issue. Also let us know about the Android version you are using.

**Comment by huli1987** [comment]
i'm using the version 0.10.0。 

i try to update the latest version

thanks

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
