### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot draw recycled bitmaps

### ISSUE THREAD

**Issue by walid1992** [facebook/fresco#1380]
java.lang.IllegalArgumentException: Cannot draw recycled bitmaps  --- > [in listview]

**Comment by lambdapioneer** [comment]
Have a look at the sample app `scrollPerf` on how to use Fresco with a list view.

Please provide more details (full log, minimal repro) if the issue persist.

**Comment by oprisnik** [comment]
I'm closing this issue since it's more than a year old. Feel free to comment if this is still an issue.
