### ISSUE TITLE
Fresco OOM upgrade fresco lib from 0.8.1 to 0.12.0

### ISSUE THREAD

**Issue by donggx** [facebook/fresco#1381]
upgrade fresco lib from 0.8.1 to 0.12.0
appear this：

java.lang.OutOfMemoryError
Failed to allocate a 2743536 byte allocation with 2249744 free bytes and 2MB until OOM
android.view.InflateException:Binary XML file line #375: Error inflating class <unknown>
android.view.LayoutInflater.createView(LayoutInflater.java:633)
......
Caused by:
java.lang.OutOfMemoryError:Failed to allocate a 2743536 byte allocation with 2249744 free bytes and 2MB until OOM
dalvik.system.VMRuntime.newNonMovableArray(Native Method)
android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:973)
android.content.res.Resources.loadDrawableForCookie(Resources.java:2423)
android.content.res.Resources.loadDrawable(Resources.java:2330)
android.content.res.Resources.getDrawable(Resources.java:758)
android.content.res.Resources.getDrawable(Resources.java:724)
com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:252)
com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:77)
com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:60)
java.lang.reflect.Constructor.newInstance(Native Method)
java.lang.reflect.Constructor.newInstance(Constructor.java:288)
android.view.LayoutInflater.createView(LayoutInflater.java:607)
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
android.view.LayoutInflater.inflate(LayoutInflater.java:504)
android.view.LayoutInflater.inflate(LayoutInflater.java:414)
android.view.LayoutInflater.inflate(LayoutInflater.java:365)

XML file line #375 ：

```
        <com.facebook.drawee.view.SimpleDraweeView
            android:layout_width="251dp"
            android:layout_height="120dp"
            android:layout_alignParentTop="true"
            android:layout_centerHorizontal="true"
            fresco:backgroundImage="@drawable/xxx"
            fresco:failureImage="@drawable/xxx"
            android:contentDescription="@string/app"
            fresco:actualImageScaleType="fitCenter"
            fresco:fadeDuration="0" />
```

**Comment by jmheart** [comment]
我也在图库选择，遇到了这个问题， 请问一下，你解决了吗？

**Comment by oprisnik** [comment]
I assume that the problem has been fixed with newer Fresco versions. Please let us know if you're still experiencing this issue.
