### ISSUE TITLE
Is it possible to turn off disk cache?

### ISSUE THREAD

**Issue by contrudar** [facebook/fresco#1389]
I know it's a very specific feature, but we can't save anything on a disk because of security reason. So far, I found only methods for deleting the existing cache such as clearDiskCaches() and evictFromDiskCache(). 

How to prevent to save anything on a disk?

**Comment by lambdapioneer** [comment]
On the `ImageRequestBuilder` for the individual `ImageRequest`s you can call `disableDiskCache()`.

Alternatively, you can create your own `nullFileCache` by extending `FileCache` and implement the methods s.t. they have no effect. You then inject it into the `ImagePipeline` using `ImagePipelineConfig#setFileCacheFactory`.

**Comment by contrudar** [comment]
Can DiskCacheConfig.newBuilder(this).setMaxCacheSize(0) work?

like this

        Fresco.initialize(this, OkHttpImagePipelineConfigFactory.newBuilder(this, okHttpClient)
                .setMainDiskCacheConfig(DiskCacheConfig.newBuilder(this).setMaxCacheSize(0).build()).build());

**Comment by erikandre** [comment]
@contrudar That should work, but using disableDiskCache() should be a better alternative.
