### ISSUE TITLE
 After the native compiler did not find libmemchunk.so, how to compile all of the libraries

### ISSUE THREAD

**Issue by benzly** [facebook/fresco#1392]

**Comment by oprisnik** [comment]
I suppose you get a crash when you start your app that's something like `UnsatisfiedLinkError: couldn't find "libmemchunk.so"`.
In that case, there are already a lot of questions around this topic, so please do [a quick search](https://github.com/facebook/fresco/issues?utf8=%E2%9C%93&q=is%3Aissue%20libmemchunk.so) and look for example at #410, #429 or other search results.
