### ISSUE TITLE
Disk cache management - wrong byte size

### ISSUE THREAD

**Issue by thieu75** [facebook/fresco#1395]
Hi guys,

Working now on the Android version of an iOS App. I'm trying to use Fresco the same way that what I have done on the iOS version of the app. Here is what I do not succeed to recreate on Android.
1- A user upload an image
> I get the size in bytes of the uploaded jpeg (quality 60%) and add it to my object (Firebase).

2- other users can download this image.
-> Consequence : the image is cache

3- I have created an helper function that grab the cached image with a custom key (because like AWS the URI to the image change). Compare the byte size of the cached jpg to the value stored on the object. 2 possibilities:
> same size: I display the cached version
> different size: I get the download URL from Firebase Storage then I download the image and store it with the custom key.

So If I replace an image directly in the server (with the same name) + I update the size to the correct one on the server object, user will update the image to display the new one.

It works like a charm ... on iOS.

On Android, I have installed fresco and try to mimic the same behavior.
For now i do not manage the 1-upload. That's fine, I have plenty of image to grab form the server.

The problematic parts are: 
- storing the file in the cache with the custom Key
- grading the size that I should have and should be same as server.

Here is the codes involved. Please help me to understand why there is a difference in byte sized:

First part : check if the key exist in the cache. If yes, grab the resource else download then store in cache.
Please note that I'm not using a drawee which is sad!

If you have a better solution, or understanding the problem I'd love to know about.
Last here are a sample:
Size on server and iOS cache: 60,23ko
Size on Android from cache: 36,12ko

`
static public void loadImageInView(final ImageView imageView, String bucket, String name) {
        FirebaseStorage storage = FirebaseStorage.getInstance();
        StorageReference storageRef = storage.getReferenceFromUrl(dataService.BUCKET_ROOT);

        final CacheKey key = new SimpleCacheKey(bucket+"_"+name);
        FileCache cache = Fresco.getImagePipelineFactory().getMainFileCache();
        //Cache reading
        if (cache.hasKey(key)) {
            BinaryResource resource = cache.getResource(key);

            try {
                final byte[] byteArray= resource.read();
                Bitmap bitmap = BitmapFactory.decodeByteArray(byteArray, 0, byteArray.length);

                ByteArrayOutputStream stream = new ByteArrayOutputStream();
                bitmap.compress(Bitmap.CompressFormat.JPEG, 60, stream);
                final byte[] byteCompressedArray = stream.toByteArray();
                int sizeJpeg = byteCompressedArray.length;

                imageView.setImageBitmap(bitmap);
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            //I grab the image
            storageRef.child(dataService.BUCKET_SETUP+"/"+name).getDownloadUrl().addOnSuccessListener(new OnSuccessListener<Uri>() {
                @Override
                public void onSuccess(Uri uri) {

                    ImagePipeline imagePipeline = Fresco.getImagePipeline();
                    ImageRequest imageRequest = ImageRequestBuilder
                            .newBuilderWithSource(uri)
                            .setRequestPriority(Priority.HIGH)
                            .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                            .build();
                    DataSource<CloseableReference<CloseableImage>> dataSource =
                            imagePipeline.fetchDecodedImage(imageRequest, context);

                    try {
                        dataSource.subscribe(new BaseBitmapDataSubscriber() {
                            @Override
                            public void onNewResultImpl(@Nullable Bitmap bitmap) {
                                if (bitmap == null) {
                                    Log.d("URI IMAGE LOADER", "Bitmap data source returned success, but bitmap null.");
                                    return;
                                }
                                //Display Image
                                imageView.setImageBitmap(bitmap);

                                //cache recording
                                try {
                                    ByteArrayOutputStream stream = new ByteArrayOutputStream();
                                    bitmap.compress(Bitmap.CompressFormat.JPEG, 60, stream);
                                    final byte[] byteArray = stream.toByteArray();
                                    Fresco.getImagePipelineFactory().getMainFileCache().insert(key, new WriterCallback() {
                                        @Override
                                        public void write(OutputStream os) throws IOException {
                                            os.write(byteArray);
                                        }
                                    });
                                } catch (IOException cacheWriteException) {

                                }
                            }

                            @Override
                            public void onFailureImpl(DataSource dataSource) {
                                // No cleanup required here
                            }
                        }, CallerThreadExecutor.getInstance());
                    } finally {
                        if (dataSource != null) {
                            dataSource.close();
                        }
                    }

                }
            }).addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {
                    Log.d("URI IMAGE LOADER", "Bitmap data source returned success, but bitmap null.");

                }
            });
        }
    }
`

Thanks guys!
Matthieu

**Comment by oprisnik** [comment]
You should use DraweeView though (or if you really need to implement a [custom view](http://frescolib.org/docs/writing-custom-views.html) that does everything that's required) since ImageView doesn't handle the lifecycle correctly and which leads to memory leaks.

You're using BaseBitmapDataSubscriber, and call `imageView.setImageBitmap(bitmap);`, which is **not** going to work. You set the bitmap that you get to your `ImageView` but if you take a look at the [JavaDoc](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/imagepipeline/src/main/java/com/facebook/imagepipeline/datasource/BaseBitmapDataSubscriber.java#L74) for the method, you'll see that Fresco will automatically free the memory afterwards.

For different sizes: You're using `bitmap.compress(Bitmap.CompressFormat.JPEG, 60, stream);` and I suppose that the implementation (or the parameters) are different compared to iOS, which leads to different file sizes.

I also don't see where you actually compare the local cache size with the one on the server.
In general, I think that relying on the file size is not the best idea, but you should do something like this:

* Use `SimpleDraweeView`.
* Have a custom `CacheKeyFactory` that you set for the `ImagePipelineConfig` and that you then use when initializing Fresco (`Fresco.initialize(context, imagePipelineConfig)`). Now, everything should automatically use correct CacheKeys for your Firebase setup.
* You can then use URIs (or ImageRequests) directly to fetch your images (`draweeView.setImageURI(uri)`).
* Before you do that, you have to check if the image needs to be re-fetched and evict the old image from the cache if so (I didn't actually test this but something like this should work):
```java
if (Fresco.getImagePipeline().isInDiskCache(uri)) {
    ImageRequest cachedRequest = ImageRequestBuilder.newBuilderWithSource(uri).setLowestPermittedRequestLevel(ImageRequest.RequestLevel.DISK_CACHE).build();
    DataSource<CloseableReference<PooledByteBuffer>> dataSource = Fresco.getImagePipeline().fetchEncodedImage(cachedRequest, null);
    dataSource.subscribe(new BaseDataSubscriber<CloseableReference<PooledByteBuffer>>() {
        @Override
        protected void onNewResultImpl(DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
            if (dataSource.hasResult()) {
                int localSize = dataSource.getResult().get().size();
                if (localSize != remoteSize) { // or whatever your re-fetch condition is
                    Fresco.getImagePipeline().evictFromCache(uri);
                }
            }
        }

        @Override
        protected void onFailureImpl(DataSource<CloseableReference<PooledByteBuffer>> dataSource) {

        }
    });
}
```

**Comment by thieu75** [comment]
@oprisnik Thanks for your reply and rich feedbacks.

I'm also convinced that relying on the byte size is probably not the best/elegant way to do it but I don't see other viable options. If you have something in mind, feel free to tell me. 

I had also thought that the jpeg implementation differ from a platform to the other. But it shouldn't. Jpeg should be jpeg ;). That's why I was hoping it would be fine. 

My code doesn't show any size comparison for now due to the fact that for my test I did know the awaited size ;)

Last thing, I wanted to bypass the uri because I need to request the uri server side. So if user is offline I wanted a way to grab image from cache: that's the reason of the cache key. 

Your code (and Thanks you for taking the time to write it) use uri. Any idea if I can use a custom key there ?
That's also the reason why I had to switch from Drawee to imageView. 


Thanks
Matthieu

**Comment by oprisnik** [comment]
If you use my code above, the size comparison should work since you don't compress the image on the client again but take the size of the original image that you've downloaded from the server.

How do you request data from the server then if you don't have a URI? E.g. in the beginning nothing is cached locally and you have to set something?

Fresco manages all the caching for you. For example, if you have a URI that is "http://something.com/image.jpg", you just set it. If you're offline, it will not show and your placeholder / error images will be displayed. If you're online and the image is not cached, it will try to download, cache and display it.

If the file is in cache, it will automatically take it from there.

**Comment by thieu75** [comment]
@oprisnik for sure, the first request need to be with the URI. I grab the URI of the image with another request to Cloud (via Firebase). I just didn't want to have the result of this request (the uri) to grab the picture from cache (if it has already been cache).

I'm gonna try your code and tell you. Thanks a lot 👍

**Comment by thieu75** [comment]
@oprisnik Ok man! I have now the exact same size has the image on the server. Cool, I can now evict a pict if needed. Your code rules all!

But I still have a problem with the SimpleDraweeView. I still want to access the cache file and display it in the drawee without going through the network.

Can I create a request with a Uri pointing directly to the file in cache. I'd really want to avoid a go and back to the Firebase server to grab the correct Uri.

Any Idea if it's possible?
Thanks :-)

**Comment by oprisnik** [comment]
As I've said above, Fresco should automatically use the cached file for you.
For example, if you have a URI "http://something.com/image.jpg" it will NOT always use the one from the network. If the image is already in cache, it will detect that and use the cached version.
You can verify this by monitoring the network traffic of your app (e.g. with Stetho).

**Comment by thieu75** [comment]
I know @oprisnik! I think my english let you misunderstood my point. I need to grab the Uri from a server !
`
storageRef.child(dataService.BUCKET_SETUP+"/"+name).getDownloadUrl().addOnSuccessListener(new OnSuccessListener<Uri>() {
            @Override
            public void onSuccess(Uri uri) {
...
`

The Uri in the onSuccess is the one that is use after in the ImageRequest.
This getDownloadUrl is the request I want to avoid if I know that the image is in cache :)
Objective : avoid this client/server request if possible. Because even if I have a local cache of the picture, it's a pity to have to interrogate the network.

**Comment by oprisnik** [comment]
I guess the easiest solution would be to just store the URI somehwere locally on the device (depending on how many of them you actually have).

**Comment by thieu75** [comment]
@oprisnik I've ended by adding the uri to my object the first time it is grabbed. Not storing it, so only live in the memory. That's a pity that it's so complicated to grab the image directly in the cache without the uri! Thanks for your help :)

**Comment by oprisnik** [comment]
Great to hear that it works now!
