### ISSUE TITLE
How can change to another End point?

### ISSUE THREAD

**Issue by leeyc09** [facebook/fresco#1397]
i used 
 'com.facebook.fresco:fresco:0.12.0'
 'com.facebook.fresco:imagepipeline-okhttp3:0.12.0'

i have 4 different Server.
get image from the server must need own http session.
so I initalize Fresco when create Activity. every time.

```
@Override
	protected void onCreate(Bundle savedInstanceState) {
	...
	if (mRequest.getSource().equals(A.BASE_URL)) {
		Fresco.initialize(mFolderDetailView.getContext(), ImagePipelineConfigFactory.getNewOkHttpImagePipelineConfig(mFolderDetailView.getContext(), A_RestfulAdapter.getClient()));
	} else if (mRequest.getSource().equals(B.BASE_URL)) {
		Fresco.initialize(mFolderDetailView.getContext(), ImagePipelineConfigFactory.getNewOkHttpImagePipelineConfig(mFolderDetailView.getContext(), B_RestfulAdapter.getClient()));
	} else if (mRequest.getSource().equals(C.BASE_URL)) {
		Fresco.initialize(mFolderDetailView.getContext(), ImagePipelineConfigFactory.getNewOkHttpImagePipelineConfig(mFolderDetailView.getContext(), C_RestfulAdapter.getClient()));
	} else {
		Fresco.initialize(mFolderDetailView.getContext(), ImagePipelineConfigFactory.getNewOkHttpImagePipelineConfig(mFolderDetailView.getContext(), A_RestfulAdapter.getClient()));
	}
```

work is fine.
but have NativeMemory leak. I afraid of OOM.

Log is right this

> NativeMemoryChunk: finalize: Chunk 267867b0 still active. Underlying address = 2fcca010

is 'Fresco.initalize' only way change to another End point?
or How can change to another End point?

**Comment by oprisnik** [comment]
We currently don't support re-initializing Fresco, which leads to these memory leaks.
However, we might support this some time in the near future.

**Comment by leeyc09** [comment]
@oprisnik thanks for your help.
I hope fix this issue. ASAP.

**Comment by oprisnik** [comment]
Also, you want to switch this for each image request? how would this work in your case when you load multiple images from different servers and the user is on a slow network. This would re-initialize everything mid-loading. Can you not configure OkHttp to correctly handle this internally?
What does `ImagePipelineConfigFactory.getNewOkHttpImagePipelineConfig(...)` do?

**Comment by oprisnik** [comment]
Another alternative would be to write your own simple backend that handles this correctly. It's just 2 classes and you can have all your endpoints and forward to the correct one, see https://github.com/facebook/fresco/tree/master/imagepipeline-backends/imagepipeline-okhttp3/src/main/java/com/facebook/imagepipeline/backends/okhttp3

**Comment by leeyc09** [comment]
getNewOkHttpImagePipelineConfig(...) is creates config using OkHttp as network backend.
```
public static ImagePipelineConfig getNewOkHttpImagePipelineConfig(Context context, okhttp3.OkHttpClient client) {
		ImagePipelineConfig.Builder configBuilder = OkHttpImagePipelineConfigFactory.newBuilder(context, client).setDownsampleEnabled(true);
		configureCaches(configBuilder, context);
		sOkHttpImagePipelineConfig = configBuilder.build();

		return sOkHttpImagePipelineConfig;
	}


/**
 * Configures disk and memory cache not to exceed common limits
 */
private static void configureCaches(ImagePipelineConfig.Builder configBuilder, Context context) {
	final MemoryCacheParams bitmapCacheParams = new MemoryCacheParams(
			ConfigConstants.MAX_MEMORY_CACHE_SIZE, // Max total size of elements in the cache
			Integer.MAX_VALUE,                     // Max entries in the cache
			ConfigConstants.MAX_MEMORY_CACHE_SIZE, // Max total size of elements in eviction queue
			Integer.MAX_VALUE,                     // Max length of eviction queue
			Integer.MAX_VALUE);                    // Max cache entry size
	configBuilder.setBitmapMemoryCacheParamsSupplier(() -> bitmapCacheParams)
			.setMainDiskCacheConfig(DiskCacheConfig.newBuilder(context)
			.setBaseDirectoryPath(context.getApplicationContext().getCacheDir())
			.setBaseDirectoryName(IMAGE_PIPELINE_CACHE_DIR)
			.setMaxCacheSize(ConfigConstants.MAX_DISK_CACHE_SIZE)
			.build());
}

```

**Comment by oprisnik** [comment]
Yeah, writing your own `BaseNetworkFetcher<OkHttpNetworkFetcher.OkHttpNetworkFetchState>` should be the best solution here since re-initializing Fresco all the time would clear all the memory caches etc. - which is not really what you want.

**Comment by leeyc09** [comment]
@oprisnik  got it . Thank you
