### ISSUE TITLE
Set the corner with the border, the outermost layer will have a pixel shadow, how to solve this

### ISSUE THREAD

**Issue by yuyuhan1** [facebook/fresco#1399]
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/sdv_tea_language_head"
                android:layout_width="46dp"
                android:layout_height="46dp"
                android:layout_marginRight="11dp”
                fresco:actualImageScaleType="centerCrop"
                fresco:roundAsCircle="true"
                fresco:roundingBorderColor="@color/list_bg"
                fresco:roundingBorderWidth="2dp" />

**Comment by oprisnik** [comment]
A screenshot would be really helpful to see what you mean with "pixel shadow".

**Comment by yuyuhan1** [comment]
![shadow](https://cloud.githubusercontent.com/assets/14089839/17423340/a5fe176a-5aec-11e6-9d4f-f3abf2dbb9a5.png)

**Comment by oprisnik** [comment]
Yeah, you're right this seems to be a bug. The image has the same size as the white border and you see the image leaking through the edges. We should make the underlying image smaller if we have a border.

**Comment by oprisnik** [comment]
As a workaround, you can add `fresco:roundingBorderPadding="${the border width}"` in xml as suggested by @s1rius in #1525

**Comment by oprisnik** [comment]
Also, there is now the possibility to scale the image within the border, see d4bcaf98e23e6bdd964650350a380667066bfa93
