### ISSUE TITLE
No static method newBuilder()

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#1401]
No static method newBuilder()Lcom/facebook/cache/disk/DiskCacheConfig$Builder; in class Lcom/facebook/cache/disk/DiskCacheConfig; or its super classes (declaration of 'com.facebook.cache.disk.DiskCacheConfig' appears in 。。。.apk:classes2.dex)

Yes. decompile classes2.dex,DiskCacheConfig in classes2.Dex

**Comment by oprisnik** [comment]
Did you set up ProGuard correctly? http://frescolib.org/docs/proguard.html

**Comment by droidwolf** [comment]
I solved the problem. Because I integrate react-native. RN use fresco version and my app is not the same version.
