### ISSUE TITLE
ProGuard - imagepipeline.platform.GingerbreadPurgeableDecoder

### ISSUE THREAD

**Issue by deejaygeekout** [facebook/fresco#1402]
Error
`Not converting this method         
java.lang.IllegalArgumentException: Dex method index overflow [65592]
Unexpected error while converting: 
  Class       = [com/facebook/imagepipeline/platform/GingerbreadPurgeableDecoder]
        at com.guardsquare.dexguard.iY.b(DexGuard7.1.00:173)
  Method      = [copyToMemoryFile(Lcom/facebook/common/references/CloseableReference;I[B)Landroid/os/MemoryFi
le;]
        at com.guardsquare.dexguard.iK.a(DexGuard7.1.00:8434)
  Exception   = [java.lang.IllegalArgumentException] (Dex method index overflow [65593])`

`
-keep class com.facebook.imagepipeline.platform.GingerbreadPurgeableDecoder {
    public GingerbreadPurgeableDecoder(com.facebook.common.references.CloseableReference);
}

-keep class com.facebook.** {
    *;
}

-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

# Keep native methods
-keepclassmembers class * {
    native <methods>;
}

-dontwarn okio.**
-dontwarn com.squareup.okhttp.**
-dontwarn okhttp3.**
-dontwarn javax.annotation.**
-dontwarn com.android.volley.toolbox.**

# Works around a bug in the animated GIF module which will be fixed in 0.12.0
-keep class com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl {
    public AnimatedFactoryImpl(com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory,com.facebook.imagepipeline.core.ExecutorSupplier);
}`

Still does not work?

**Comment by lambdapioneer** [comment]
Hi @deejaygeekout , this seems to be a problem with the `dexguard` tool that you are using instead of the classic `proguard`. It mentions an dex method index overflow (>65k).

You might want to reach out to the Dexguard developers and optionally point them to this documentation: http://frescolib.org/docs/proguard.html
