### ISSUE TITLE
Samsung mobile phones can not display pictures

### ISSUE THREAD

**Issue by hcadoid** [facebook/fresco#1404]
HI：
I'm on the Samsung SM-G3818Android4.2.2: pictures do not show up, this is my picture address: https: //dn-runedu-img.qbox.me/5324277294619549696.   

Adjustment ResizeOptions on other mobile phone and some can not be displayed

public static void showImageEnty(SimpleDraweeView view, String url,
            int width, int height, int imageResouse) {
        if (url == null) {
            view.setImageURI(Uri
                    .parse("res://com.zjcs.student/" + imageResouse));
        } else {
            Uri uri = Uri.parse(url);
            ImageRequest request = ImageRequestBuilder
                    .newBuilderWithSource(uri)
                    .setResizeOptions(new ResizeOptions(width, height)).build();
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setOldController(view.getController())
//                  .setAutoPlayAnimations(true)
                    .setImageRequest(request).build();
            view.setController(controller);
        }
    }

 ImageUtils.showImageEnty(itemHolder.groupLogo, info.getImgUrl(), ScreenUtil.dp2px(activity, 48), ScreenUtil.dp2px(activity, 48)
                    , R.drawable.home_def_type);

<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/group_photo"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_gravity="center_horizontal"
        fresco:actualImageScaleType="focusCrop"
        fresco:roundAsCircle="true"
        fresco:failureImageScaleType="center"
        fresco:placeholderImage="@drawable/home_def_type"
        fresco:placeholderImageScaleType="center"
        fresco:retryImage="@drawable/home_def_type"
        fresco:retryImageScaleType="center"
        android:layout_centerVertical="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true" />

**Comment by lambdapioneer** [comment]
Hi @hcadoid, do you see any errors in `adb logcat`?

As you mentioned that you see this bug on a particular device configuration: Do the sample applications work on that device? Can you check if it works without `setResizeOptions` or `fresco:roundAsCircle`?

**Comment by hcadoid** [comment]
@lambdapioneer 
1.Use another phone, when I ResizeOptions (48dp, 48dp), is not displayed.

08-08 18:39:44.655 22076-22076/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433df5d0 null -> 0: initialize
08-08 18:39:44.655 22076-22076/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433df5d0 0: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@433d3b48
08-08 18:39:44.705 22076-22076/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433df5d0 0: onAttach: request needs submit
08-08 18:39:44.710 22076-22076/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433df5d0 0: submitRequest: dataSource: 433e98d0
08-08 18:39:45.350 22076-22076/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433df5d0 0: final_failed @ onFailure: failure: java.lang.RuntimeException: Unsupported color conversion request


2.When I ResizeOptions (80dp, 80dp), increasing the width and height can be displayed

08-08 18:44:49.340 28179-28179/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433e3420 null -> 0: initialize
08-08 18:44:49.340 28179-28179/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433e3420 0: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@433d7960
08-08 18:44:49.385 28179-28179/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433e3420 0: onAttach: request needs submit
08-08 18:44:49.395 28179-28179/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433e3420 0: submitRequest: dataSource: 433ed720
08-08 18:44:50.245 28179-28179/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 433e3420 0: set_final_result @ onNewResult: image: CloseableReference 43414498

3.on SM-G3818Android4.2.2:  When I ResizeOptions (80dp, 80dp)

08-08 18:47:26.648 31142-31142/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 42758920 null -> 0: initialize
08-08 18:47:26.648 31142-31142/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 42758920 0: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@427802c8
08-08 18:47:26.679 31142-31142/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 42758920 0: onAttach: request needs submit
08-08 18:47:26.687 31142-31142/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 42758920 0: submitRequest: dataSource: 4275acc8
08-08 18:47:27.140 31142-31142/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 42758920 0: final_failed @ onFailure: failure: java.lang.RuntimeException: Unsupported color conversion request

4.on SM-G3818Android4.2.2:  

 SimpleDraweeView simpleDraweeView= (SimpleDraweeView) findViewById(R.id.group_photo);
        Uri uri = Uri.parse("http://dn-runedu-img.qbox.me/5324277294619549696");
        simpleDraweeView.setImageURI(uri);

08-08 18:52:23.906 5018-5018/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 427540d8 0: onDetach
08-08 18:52:25.953 5018-5018/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 4273ec68 null -> 1: initialize
08-08 18:52:25.953 5018-5018/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 4273ec68 1: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@427709e0
08-08 18:52:25.968 5018-5018/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 4273ec68 1: onAttach: request needs submit
08-08 18:52:25.968 5018-5018/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 4273ec68 1: submitRequest: dataSource: 42805bd8
08-08 18:52:25.992 5018-5018/com.zjcs.myapplication V/unknown:AbstractDraweeController: controller 4273ec68 1: final_failed @ onFailure: failure: java.lang.RuntimeException: Failed to pin Bitmap

Image is a problem or an error set ResizeOptions？？

**Comment by lambdapioneer** [comment]
Thanks for the logs, they have been very helpful. Your image uses the CMYK color space which is quite unusual and seems to create the problem:

```
>$ identify image.jpeg
image.jpeg JPEG 220x220 220x220+0+0 8-bit CMYK 9.03KB 0.000u 0:00.000
```

I'd suggest to create a png or a jpeg with a RGB colorspace.

**Comment by oprisnik** [comment]
if somebody wants to add support for CMYK images, please submit a pull request. I'm closing this issue for now.
