### ISSUE TITLE
Avoid resizing large images bitmap

### ISSUE THREAD

**Issue by rsicarelli** [facebook/fresco#1407]
I'm using Fresco to process bitmap. But, when the image is larger, the processed bitmap reduces half the image spec:

> Original image spec:
> Height: 4032
> Width: 3024
> Size: 4,65 MB
> 
> Processed image spec:
> Height: 2016
> Width: 1512
> Size: 595 Kb

There is a way to avoid that? I mean, to keep the image spec and only reduces the image size?

My code:

```
Uri uriPhoto = Uri.parse("file://" + path);
ImageRequest imageRequest = ImageRequestBuilder
        .newBuilderWithSource(uriPhoto)
        .build();

ImagePipeline imagePipeline = Fresco.getImagePipeline();
DataSource<CloseableReference<CloseableImage>> dataSource =
        imagePipeline.fetchDecodedImage(imageRequest, context);

dataSource.subscribe(new BaseBitmapDataSubscriber() {
    @Override
    public void onNewResultImpl(@Nullable Bitmap bitmap) {
        if (bitmap != null) {
            String s = Formatter.formatFileSize(context, bitmap.getAllocationByteCount() / 10);

            String builder = "Processed image spec ----> "+ path + ": \n"
                    + "Height: "
                    + bitmap.getHeight()
                    + "\nWidth: "
                    + bitmap.getWidth()
                    + "\nSize: "
                    + s;

            Logger.info(builder);
        }
    }

    @Override
    public void onFailureImpl(DataSource dataSource) {
        // No cleanup required here.
    }

}, CallerThreadExecutor.getInstance());
```

My `Application`:

```
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(application)
        .setBitmapsConfig(Bitmap.Config.RGB_565)
        .setDownsampleEnabled(true)
        .build();
Fresco.initialize(application, config);
```

I'm using the version `0.8.1`.

Thanks!

**Comment by huangjunkun** [comment]
Hi @rsicarelli   Look  **BitmapUtil.java**,  Fresco has a property **MAX_BITMAP_SIZE**
`com.facebook.imageutils.BitmapUtil#MAX_BITMAP_SIZE`
`public static final float MAX_BITMAP_SIZE = 2048f;`

**Comment by rsicarelli** [comment]
@huangjunkun hmmm, interesting! In my analysis, there is no way do change that field because he is static and final. 

Do you recommend some approach for this case?

**Comment by huangjunkun** [comment]
@rsicarelli    Maybe you should only modify the Fresco's source.

**Comment by oprisnik** [comment]
Pull requests are always welcome :)

**Comment by erikandre** [comment]
Closing due to lack of updates.
