### ISSUE TITLE
how to clear the request queque

### ISSUE THREAD

**Issue by 54binge** [facebook/fresco#1412]
hi,
In a particular case, only single thread is supported.
In the first activity, a lot of requests were sent.
Then I start a second activity(and the first activity is not be finished),there're also some requests need to send in this activity,
but these request wouldn't be excuted until requests from the first activity are finished.my server is not fast enough,then i mush wait a long time.
So, can anybody tell me how to cancel a request in the queque, or how to clear the request queque.
Any thoughts would be appreciated.

**Comment by massimocarli** [comment]
Hi @54binge,
are you using Drawee or accessing the ImagePipeline directly?
Thanks

**Comment by 54binge** [comment]
Hi @massimocarli this is my code
`ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(new ResizeOptions(width, height))
                .setAutoRotateEnabled(true)
                .build();
        AbstractDraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(simpleDraweeView.getController())
                .setImageRequest(request)
                .build();
        simpleDraweeView.setController(controller);`

**Comment by massimocarli** [comment]
Hi @54binge,
have you tired to se the controller to null when you're finished? 
`simpleDraweeView.setController(null);`
