### ISSUE TITLE
Can I replace the default LocalVideoThumbnailProducer for a request?

### ISSUE THREAD

**Issue by aguynamedrich** [facebook/fresco#1414]
`LocalVideoThumbnailProducer` uses `ThumbnailUtils.createVideoThumbnail` which fails to load thumbnails for certain HD videos.  Glide allows me to bypass this kind of default behavior by adding a custom decoder to a request.  Is there a mechanism to use a custom producer in Fresco where I can use my own logic to extract the thumbnail?

**Comment by massimocarli** [comment]
Hi @aguynamedrich ,
At the moment you cannot do this but we're working in that direction. 
Thanks
