### ISSUE TITLE
FadeDrawable call invalidateSelf() so many times when the picture is downloading.

### ISSUE THREAD

**Issue by s1rius** [facebook/fresco#1417]
I had a RecyclerView like this.
![screen_shot](https://cloud.githubusercontent.com/assets/3580391/17665201/fc0a8f7a-632b-11e6-83b1-7afd5d0f1a79.png)

I write a custom view follow this [guide](http://frescolib.org/docs/writing-custom-views.html) to show 0-9 pictures.
To make the view scroll smooth, I set the fade animation's duration is 0 and not set the ProgressBarDrawable. 

I except 
the custom view call onDraw() times = 1(init) + DraweeHolder count * (1(placeholder drawable) + 1(actual drawable))

But I find the invalidateDrawable() method called so many times.

I checked the source code(GenericDraweeHierarchy.java line 278)
```
  public void setProgress(float progress, boolean immediate) {
    mFadeDrawable.beginBatchMode();
    setProgress(progress);
    if (immediate) {
      mFadeDrawable.finishTransitionImmediately();
    }
    mFadeDrawable.endBatchMode();
  }

```
The InvalidateSelf() function called wether the ProgressBarDrawable is set or not.
I think we can check ProgressBarDrawable not null first, then call the ```setProgress ``` function.

**Comment by massimocarli** [comment]
Hi @s1rius ,
thanks for letting us know.
