### ISSUE TITLE
Custom Authentication Header for Image Load

### ISSUE THREAD

**Issue by leofirespotter** [facebook/fresco#142]
I am seeing a similar issue that I had to fix manually in Volley. In order to load images, I need to add an authentication header to the request. Is there any support built in to do this? Or do I need to fork Fresco and do it myself?

**Comment by leofirespotter** [comment]
Figured out that using OkHttp I can add Authentication

**Comment by heyanyanchina123** [comment]
could you please paste some important code for this problem?

**Comment by leofirespotter** [comment]
@heyanyanchina123 sure.

When I initialize Fresco

```
    private void initFresco() {
        okHttpClient = new OkHttpClient();
        okHttpClient.setAuthenticator(this);
        ImagePipelineConfig config = OkHttpImagePipelineConfigFactory
                .newBuilder(this, okHttpClient)
        .build();
        Fresco.initialize(this, config);
    }
```

And then have that class implement Authenticator, which looks something like this:
```
    @Override
    public Request authenticate(Proxy proxy, Response response) throws IOException {
        String accessToken = getAccessToken();
        if (accessToken == null) {
            return null;
        }

        return response.request().newBuilder()
                .addHeader("udid", getDeviceId())
                .addHeader("Authorization", "Bearer " + accessToken)
                .build();
    }
```

**Comment by heyanyanchina123** [comment]
@leofirespotter thanks!

**Comment by KynoYang** [comment]
@leofirespotter Can I ask the version of okhttp that you are using. I tried the code above, but it seems not working. My okhttp version is 2.0.0, BTW.

**Comment by leofirespotter** [comment]
@KynoYang I am on 2.5, which I believe to be the latest

**Comment by KynoYang** [comment]
@leofirespotter  Thank you very much. But it seems not working for me even if I upgrade okhttp to 2.5.0 . Sad.

Finally, I extends OkHttpClient and override newCall method. It works.

**Comment by leofirespotter** [comment]
@KynoYang hm weird, you used the code above exactly?

**Comment by KynoYang** [comment]
@leofirespotter  Yes, weird. I copied your code.

**Comment by Doctoror** [comment]
I suggest reopening this issue. What if one needs to use different authentication params for different request that run simultaneously? It would be better to override this per-request rather than setting the global Authenticator.

**Comment by ssomnoremac** [comment]
@Doctoror, I agree. In my case I'd like to be able to use credentials in the URI but they get stipped on the actual call:
`http://admin:pass@localhost...` becomes `http://localhost...` on the actual request. Is there a security concern for removing the credentials in the url? I'm not sure where it happens either.
