### ISSUE TITLE
Pictures drawing problem

### ISSUE THREAD

**Issue by mxylayout** [facebook/fresco#1422]
Excuse me but i have a problem：
code：
![a123123](https://cloud.githubusercontent.com/assets/10346229/17797865/ed0f6e16-65fe-11e6-9bd2-1b4467222b83.png)

![123123123](https://cloud.githubusercontent.com/assets/10346229/17797953/b1a00a92-65ff-11e6-98ca-bd8efea24cb3.png)

and the effect is：
![456456](https://cloud.githubusercontent.com/assets/10346229/17797996/15f5ff24-6600-11e6-85d4-1ec4f8131a9a.png)

Here is the picture address：
http://miclouds.hebg3.com//userfiles/manufacturer/images/goods/1/0204020208003.jpg

i ‘d also try to use CENTER_INSIDE ,run on different phone,use android:hardwareAccelerated="true" but it doesn't works.

Should I need to add some other code to solve this？
Thanks in advance.

**Comment by oprisnik** [comment]
This is related to the rounding mode and scale type that you're using. Take a look at #153, #208 and #1110 to find out why this is happening.
