### ISSUE TITLE
JAR packages conflicts

### ISSUE THREAD

**Issue by oyty** [facebook/fresco#143]
when I build the app, it got follow error message:
![image](https://cloud.githubusercontent.com/assets/6076991/7129105/627f3924-e28e-11e4-9353-af262cdbddff.png)

when I search the class AnimRes
![image](https://cloud.githubusercontent.com/assets/6076991/7129145/e6cd7e2a-e28e-11e4-8710-ae8add8285c5.png)
you could find the class AnimRes comes from two places, the V4 package and the support-annotations package, the V4 is in my libs, but I can't find the support-annotations package, I think it is a dependance of the fresco library. The possible way to solve this problem is to delete the V4 package, but I need it, the V4 package contains two items, annotations and v4, i need v4, but i can't just delete the annotations item, what should I do?
My dependances:
![image](https://cloud.githubusercontent.com/assets/6076991/7129243/126a3590-e290-11e4-875c-fc2dc4e8b199.png)

**Comment by tyronen** [comment]
We have a pending commit that should fix this.

**Comment by andforce** [comment]
@oyty : Before @tyronen fix, you can try shis:
compile ('com.facebook.fresco:fresco:0.1.0+'){
    exclude group: 'com.android.support', module: 'support-v4'
    exclude group: 'com.android.support', module: 'appcompat-v7' }
if you have used nineoldandroids,also you can try this:

    compile('com.nineoldandroids:library:2.4.0') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }

**Comment by tyronen** [comment]
The most recent head should take care of this issue. Reopen if it doesn't.

**Comment by oyty** [comment]
@andforce ,yeah, I fix it. I just delete the v4 package use the one that fresco is dependent on. And i said i need my v4 package before because of some problem else. i have to point out that when we use the fresco, we have to pay attention to the dependences library, and some classes of them can't be mixed up, you should to keep them in the proguard file.
