### ISSUE TITLE
onFinalImageSet of ControllerListener not called the first time

### ISSUE THREAD

**Issue by aneophyte** [facebook/fresco#1430]
`onFinalImageSet()` of the `ControllerListener` does not get called the first time if a postprocessor has been set (`setPostprocessor` of `ImageRequestBuilder`) for some reason. It does work upon the second request (eg. reloading the same item upon scroll). The postprocessor implementation in my project works but could have problems in this regard.

The postprocessor cache key for each image with the said postprocessor is unique and remains the same, as this information might be relevant.

Any pointers to fix this issue?

**Comment by oprisnik** [comment]
This works for me for a sample app. Do you have a minimal code example that doesn't work for you?

I've used this:
```java
DraweeController controller = Fresco.newDraweeControllerBuilder().setImageRequest(
        ImageRequestBuilder.newBuilderWithSource(Uri.parse("http://lorempixel.com/800/800/?random=" + Math.random()))
                .setPostprocessor(new BasePostprocessor() {
                    @Override
                    public void process(Bitmap bitmap) {
                        Log.d(TAG, "Postprocessor.process");
                    }
                })
                .build())
        .setControllerListener(new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                Log.d(TAG, "BaseControllerListener.onFinalImageSet");
            }
        })
        .build();
simpleDraweeView.setController(controller);
```


Output is as expected:
Postprocessor.process
BaseControllerListener.onFinalImageSet

**Comment by aneophyte** [comment]
Using `BaseRepeatedPostProcessor`, this issue can be reproduced.

```DraweeController controller = Fresco.newDraweeControllerBuilder().setImageRequest(
                        ImageRequestBuilder.newBuilderWithSource(Uri.parse("http://lorempixel.com/800/800/?random=" + Math.random()))
                                .setPostprocessor(new BaseRepeatedPostProcessor() {
                                    @Override
                                    public void process(Bitmap bitmap) {
                                        Log.d(TAG, "Postprocessor.process");
                                    }
                                })
                                .build())
                        .setControllerListener(new BaseControllerListener<ImageInfo>() {
                            @Override
                            public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                                Log.d(TAG, "BaseControllerListener.onFinalImageSet");
                            }
                        })
                        .build();```

I've edited your snippet with the required change to `BaseRepeatedPostProcessor` where the problem can be observed.

It was called the second time and onwards in my project, due to the postprocessor cache key. It fails there the first time even if the key is supplied.

Side note: lorempixel looks interesting to try stuff with!

**Comment by oprisnik** [comment]
I see what you mean.
However, it's working as expected since that's exactly what the `BaseRepeatingPostprocessor` is for. It has an `update()` method that runs postprocess again and updates the image. That's why `onFinalImageSet` is never called since there never is a final image (because you could call `update()` at any time).
That's why you can use `onIntermediateImageSet()` in this case. However, if you do not need to postprocess multiple times, just use a normal `BasePostprocessor` instead.

More information can be found here: http://frescolib.org/docs/modifying-image.html
