### ISSUE TITLE
on 6.0 machines, memory leaks

### ISSUE THREAD

**Issue by lushan1314** [facebook/fresco#1431]
Log saw many oom，most occurred in android 6.0 or more machines。

I use the mat is analyzed。

![22222](https://cloud.githubusercontent.com/assets/3870266/17928867/7b1cf776-6a2f-11e6-906a-5607f4d74c53.png)
![33333](https://cloud.githubusercontent.com/assets/3870266/17928874/82385b40-6a2f-11e6-8b8a-c7f74d705b3f.png)
![111111](https://cloud.githubusercontent.com/assets/3870266/17928877/85925d22-6a2f-11e6-8899-ac5d1cf62c7c.png)

when the activity to exit ， memory cannot be released

same code on android 4.4, everything is ok.

on android 6.0 ，finnally，i get this error:
![44444](https://cloud.githubusercontent.com/assets/3870266/17928975/03a1920a-6a30-11e6-88fa-8f9e83a8f946.png)

the fresco version is 0.13.0.

**Comment by oprisnik** [comment]
How are you using Fresco? How big are your images? Animations?
I see that you're using a RecyclerView, are you unbinding the DraweeViews somewhere (setting the URI to null)?

There are also [similar discussions here](https://github.com/facebook/fresco/issues?utf8=%E2%9C%93&q=is%3Aissue%20oom)

**Comment by lushan1314** [comment]
have no animation，not big.

how to unbinding?

**Comment by lushan1314** [comment]
the point is : 
**1. same code on android 4.4,is ok.
2.when activity is exit , memory cannot be released**
why？I did not find this problem before。

**Comment by lushan1314** [comment]
the point is the SimpleDraweeView  hold the **context**
so  Activity cannot be release all the source

**Comment by lushan1314** [comment]
i test on android  5.0,also is ok.

just on android 6.0. easy to leaks

**Comment by oprisnik** [comment]
How many images are we talking about and what dimensions and file type (width x height). Are you using downsampling or resizing?
Do you re-use the controller (e.g. like here https://github.com/facebook/fresco/blob/master/samples/scrollperf/src/main/java/com/facebook/samples/scrollperf/fragments/recycler/DraweeViewHolder.java#L68 )?

You stated "the point is the SimpleDraweeView hold the context".
[Every view on Android holds on to the context](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/view/View.java#3476), you should not hold on to the view when your Activity is destroyed.

**Comment by lushan1314** [comment]
i know . u mean i should **setUri(null)** whe the activity is destoryed?

**Comment by lushan1314** [comment]
width x height = 480*480,a most is that.

i used setUri(Uri.parse("http://....")),not use controller

**Comment by lushan1314** [comment]
ok,i try setController like method **bind** in the sample ,It looks better.

In the past，i just used **SimpleDraweeView.setUri()**,but under the android 5.0，its works good
