### ISSUE TITLE
Get Image's Memory Footprint

### ISSUE THREAD

**Issue by SidhantDuggal** [facebook/fresco#1433]
We are using the image pipeline directly to prefetch images (imagePipeline.prefetchToBitmapCache(imageRequest, callerContext) is the specific method ). We are using the basedatasubscriber with the returned datasource to log the request's success/failure. We would also like to log the memory footprint of the downloaded image. How can we get the image's memory footprint ?

**Comment by agnesmax** [comment]
I think what you're looking for is CountingMemoryCacheInspector. It's logging what cache contains at the moment you log.

**Comment by SidhantDuggal** [comment]
@agnesmax It would be great if you could point me to some documentation that can help me in using this inspector class. I am not able to figure out the usage of this class.

**Comment by oprisnik** [comment]
Sorry for the late response. You can do something like

```
CountingMemoryCacheInspector.DumpInfo memoryCacheDumpInfo = new CountingMemoryCacheInspector<>(Fresco.getmagePipelineFactory().getBitmapCountingMemoryCache())
                .dumpCacheContent();
// do something with memoryCacheDumpInfo
```
