### ISSUE TITLE
Border not visible in Rounded Image

### ISSUE THREAD

**Issue by varunrramani** [facebook/fresco#1436]
I'm using the following code to round the image and also trying to set the border with it. The result image is rounded but the border is not visible.

`RoundingParams roundingParams = RoundingParams.asCircle();`
`roundingParams.setRoundAsCircle(true);`
`roundingParams.setBorder(android.R.color.white,15.0f);`

and setting this as the rounding params as
`view.getHeirarchy().setRoundingParams(roundingParams)`

but still no border is seen.
I also tried setting in xml but still no luck.
I'm using the latest version of fresco i.e. 
`compile 'com.facebook.fresco:fresco:0.13.0'`

**Comment by varunrramani** [comment]
@aagnes any update on this?

**Comment by oprisnik** [comment]
This still works for me. The issue in your code is that you have to supply a color value instead of a color resource ID for `setBorder(...)`.
Our documentation on this is also wrong, we will update it accordingly. Thanks for flagging!


Setting in Java:

```
int color = getResources().getColor(android.R.color.white); // or whatever your color is
simpleDraweeView.getHierarchy().setRoundingParams(RoundingParams.asCircle().setBorder(color, radius));
```
Setting in XML

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/drawee"
        android:layout_width="46dp"
        android:layout_height="46dp"
        fresco:roundAsCircle="true"
        fresco:roundingBorderWidth="8dp"
        fresco:roundingBorderColor="@android:color/white"
        />

**Comment by varunrramani** [comment]
Thank you for the solution. It works!

**Comment by oprisnik** [comment]
I have also added a support annotation in 4924b892fe1e6b4574b9e55f1fbe0a54ec0a39f7. You should see a warning / error in Android Studio now if you supply a wrong type.
