### ISSUE TITLE
disk cache update size problem.

### ISSUE THREAD

**Issue by jiqimaogou** [facebook/fresco#1437]
```
  private BinaryResource endInsert(
      final DiskStorage.Inserter inserter,
      final CacheKey key,
      String resourceId) throws IOException {
    synchronized (mLock) {
      BinaryResource resource = inserter.commit(key);
      mResourceIndex.add(resourceId);
      mCacheStats.increment(resource.size(), 1);
      return resource;
    }
  }
```

it I update a file, why it call increment the new size, but not minus old resource size.

**Comment by kirwan** [comment]
I think you're right. Are you calling `DiskStorageCache.insert()` directly to replace existing items? In the pipeline, it's only ever called if the item is not already in cache.

**Comment by erikandre** [comment]
Closing as it's not clear if the problem was due to incorrect usage
