### ISSUE TITLE
Crashed because of NoClassDefFoundError

### ISSUE THREAD

**Issue by huli1987** [facebook/fresco#1439]
java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.imagepipeline.memory.NativeMemoryChunk; see exception in other thread
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.com.facebook.imagepipeline.memory.NativeMemoryChunk alloc(int)(NativeMemoryChunkPool.java:60)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.void free(java.lang.Object)(NativeMemoryChunkPool.java:22)
## _child_## java.lang.Object alloc(int)##_child_

com.facebook.imagepipeline.memory.BasePool.java.lang.Object get(int)(BasePool.java:259)
com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.void <init>(com.facebook.imagepipeline.memory.NativeMemoryChunkPool,int)(NativePooledByteBufferOutputStream.java:53)
com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.NativePooledByteBuffer newByteBuffer(java.io.InputStream,int)(NativePooledByteBufferFactory.java:98)
com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.PooledByteBufferOutputStream newOutputStream()(NativePooledByteBufferFactory.java:26)
## _child_## com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(java.io.InputStream)##_child_

com.facebook.imagepipeline.producers.LocalFetchProducer.com.facebook.imagepipeline.image.EncodedImage getByteBufferBackedEncodedImage(java.io.InputStream,int)(LocalFetchProducer.java:99)
## _child_## java.lang.String getProducerName()##_child_

com.facebook.imagepipeline.producers.LocalFetchProducer.com.facebook.imagepipeline.image.EncodedImage getEncodedImage(java.io.InputStream,int)(LocalFetchProducer.java:119)
com.facebook.imagepipeline.producers.LocalResourceFetchProducer.com.facebook.imagepipeline.image.EncodedImage getEncodedImage(com.facebook.imagepipeline.request.ImageRequest)(LocalResourceFetchProducer.java:42)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.com.facebook.imagepipeline.image.EncodedImage getResult()(LocalFetchProducer.java:66)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.java.lang.Object getResult()(LocalFetchProducer.java:62)
com.facebook.common.executors.StatefulRunnable.void run()(StatefulRunnable.java:45)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)

**Comment by aagnes** [comment]
Can you try with the solution in #410 ?

**Comment by peacepassion** [comment]
@aagnes Excuse me, what is the solution there?

**Comment by kirwan** [comment]
@peacepassion When we've seen issues like this before it's because the native library was not successfully loaded.

I think @aagnes had this solution in mind: https://github.com/facebook/fresco/issues/933#issuecomment-186266187

That comment has a solution to use another small library called Relinked and integrate it with `SoLoaderShim` to improve the success of loading those native libraries.

**Comment by erikandre** [comment]
Closing as a workaround was suggested and no updates since last year

**Comment by OrangeFlavoredColdCoffee** [comment]
it appears  when i update ReactNative to 0.48.4.   so  why it works well before ,and suddenly it happened
