### ISSUE TITLE
i want use ControllerListener Listener image download progress..

### ISSUE THREAD

**Issue by terryyhl** [facebook/fresco#144]
how can i use ?

**Comment by tyronen** [comment]
Can you explain more what you want to do?

http://frescolib.org/docs/listening-download-events.html shows how to listen to download events.

**Comment by plamenko** [comment]
If you want to display the download progress, you should set some progress bar drawable to the hierarchy.
See example usage:
https://github.com/facebook/fresco/blob/53e1317d47e0e33d9927740ad4974cc479d8cc2a/sample/src/main/java/com/facebook/fresco/sample/adapters/FrescoAdapter.java

And example implementation of a progress bar drawable (onLevelChange is the important method):
https://github.com/facebook/fresco/blob/53e1317d47e0e33d9927740ad4974cc479d8cc2a/drawee/src/main/java/com/facebook/drawee/drawable/ProgressBarDrawable.java
