### ISSUE TITLE
how to animate from circle to normal draweeview in share element transition?

### ISSUE THREAD

**Issue by anlijiu** [facebook/fresco#1441]
I use https://github.com/facebook/fresco/samples/transition for example.
add 'fresco:roundAsCircle="true"' to SimpleDraweeView of drawee_source.xml
the shape doesn't change smoothly

**Comment by oprisnik** [comment]
You can also manually add a circular reveal animation to your transition, which could give you the effect that you want, see https://github.com/facebook/fresco/issues/992

We're not going to implement a custom transition. However, if you want to add an example to the Showcase sample app, feel free to submit a pull request.
