### ISSUE TITLE
transition animation problem?

### ISSUE THREAD

**Issue by nickming** [facebook/fresco#1442]
when i use SimpleDrawView in RecyclerView ,use this element share in the second Activity ,that SimpleDrawView will not show Picture  identimmediately? the uri is not null.

**Comment by aagnes** [comment]
Can you please show are you're using the SimpleDraweeView in code?

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know. There is also a related discussion going on in #1445
