### ISSUE TITLE
How is fresco "disk cache strategy

### ISSUE THREAD

**Issue by lushan1314** [facebook/fresco#1444]
When the disk cache is full,then request will all request network?

Have the relevant document to introduce it，thanks~

**Comment by aagnes** [comment]
Fresco uses LRU logic of eviction in disk cache. You can find it in DefaultEntryEvictionComparatorSupplier.java.

**Comment by lushan1314** [comment]
thank u

**Comment by lushan1314** [comment]
Looked from the log of CDN and found the android images of network request value is much higher than expected。

Want to consulting, memory leaks may cause this to happen?Do you have any Suggestions to optimize it！

Thank you very much！
