### ISSUE TITLE
image not shown set width to match_parent and height to wrap_content

### ISSUE THREAD

**Issue by ryanouyang** [facebook/fresco#1447]
`<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/banner"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>`

**Comment by ryanouyang** [comment]
i just need to show my picture in the original aspect ratio, please help!

**Comment by eldk** [comment]
Hello,

Should you have a look at : 
http://frescolib.org/docs/wrap-content.html#main_wrap
http://frescolib.org/docs/using-drawees-xml.html#wrapcontent

Thanks,
Eric
