### ISSUE TITLE
Rounding GIFs is not supported. How to get GIF source?

### ISSUE THREAD

**Issue by SandyWangWei** [facebook/fresco#1448]
Hi~~~ I get a problem , I want to get the gif source loaded by fresco , but I have no idea after I finish reading docs~~~can you help me ??

**Comment by aagnes** [comment]
What do you need to do exactly?

To display a gif image using Fresco, you can use

Uri uri;
DraweeController controller = Fresco.newDraweeControllerBuilder()
    .setUri(uri)
    .setAutoPlayAnimations(true)
    . // other setters
    .build();
mSimpleDraweeView.setController(controller);

**Comment by SandyWangWei** [comment]
I would like to achieve a rounded picture of the first frame in a gif. Now I get a condition that I need achieve rounded picture with a url, but the picture in the url could be a gif, the round would be gone when it's gif ,so I would like to achieve a rounded picture of the first frame in a gif and show it.

**Comment by aagnes** [comment]
If you don't .setAutoPlayAnimations(true), Fresco would take the first frame as real image for the view. You can also apply round param to the DraweeHierarchyBuilder.

**Comment by kirwan** [comment]
Please show us the XML or `DraweeController` code that creates the view. I suspect there might be an issue with the `RoundingMethod` you're using.

**Comment by SandyWangWei** [comment]
`public void setImageURIAndCircle(String uri, boolean asCircle) {
        if (uri == null) {
            return;
        }
        setImageURI(Uri.parse(uri));
        if (!asCircle) {
            RoundingParams roundingParams = this.getHierarchy().getRoundingParams();
            if (roundingParams == null) roundingParams = new RoundingParams();
            roundingParams.setRoundAsCircle(false);
            this.getHierarchy().setRoundingParams(roundingParams);
            roundAsCircle = false;
        } else {
            RoundingParams roundingParams = this.getHierarchy().getRoundingParams();
            if (roundingParams == null) roundingParams = new RoundingParams();
            roundingParams.setRoundAsCircle(true);
            this.getHierarchy().setRoundingParams(roundingParams);
            roundAsCircle = true;
        }`
this is a method of the  view extends from SimpleDraweeView~~~

**Comment by SandyWangWei** [comment]
`public void setImageURIAndCircle(String uri, boolean asCircle) {
        if (uri == null) {
            return;
        }
        setImageURI(Uri.parse(uri));
        if (!asCircle) {
            RoundingParams roundingParams = this.getHierarchy().getRoundingParams();
            if (roundingParams == null) roundingParams = new RoundingParams();
            roundingParams.setRoundAsCircle(false);
            this.getHierarchy().setRoundingParams(roundingParams);
            roundAsCircle = false;
        } else {
            RoundingParams roundingParams = this.getHierarchy().getRoundingParams();
            if (roundingParams == null) roundingParams = new RoundingParams();
            roundingParams.setRoundAsCircle(true);
            this.getHierarchy().setRoundingParams(roundingParams);
            roundAsCircle = true;
        }
    }`
this is a method of the view extends from SimpleDraweeView~~~ @kirwan

**Comment by oprisnik** [comment]
GIF rounding is currently not supported.

**Comment by oprisnik** [comment]
More details and workarounds in https://github.com/facebook/fresco/issues/2087
