### ISSUE TITLE
Can fresco load an image without SimpleDraweeView ?

### ISSUE THREAD

**Issue by bjzhou** [facebook/fresco#145]
How can I do this simply?

**Comment by IanChilds** [comment]
See http://frescolib.org/docs/using-image-pipeline.html#_

**Comment by bjzhou** [comment]
@IanChilds Thanks, but I want to find an easier way to do this, seems no yet. What I want is I send a request, then fresco give me a bitmap, and fresco will manage the cache for me

**Comment by plamenko** [comment]
Our image pipeline requires bitmaps to be manually disposed once not needed anymore and this is hard to do. That's why it is highly recomended to use Drawee for displaying images, as it takes care of all that.
