### ISSUE TITLE
is lib set the defalut resizeoptions ?

### ISSUE THREAD

**Issue by 54binge** [facebook/fresco#1451]
hi @natacado 
when i dispaly a image and zoom it, i found it is not the same quallity as system album, i didn't set resizeoptions, here's my code:

```
PipelineDraweeControllerBuilder controller = Fresco.newDraweeControllerBuilder();
        controller.setRetainImageOnFailure(true);
        controller.setLowResImageRequest(ImageRequest.fromUri(thumb));
        controller.setImageRequest(ImageRequest.fromUri(url));
        controller.setOldController(touchImageView.getController());
        controller.setControllerListener(new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                super.onFinalImageSet(id, imageInfo, animatable);
                if (imageInfo == null) {
                    return;
                }
                touchImageView.update(imageInfo.getWidth(), imageInfo.getHeight());
                touchImageView.setEnabled(true);
            }

            @Override
            public void onFailure(String id, Throwable throwable) {
                super.onFailure(id, throwable);
            }
        });
        touchImageView.setController(controller.build());
```

thans!

**Comment by aagnes** [comment]
We don't set a resizeOption as default for now. What format is your image?

**Comment by 54binge** [comment]
@aagnes hi,
than you for reply, images are jpg format

**Comment by kirwan** [comment]
I presume these are local images on the device. In which case you shouldn't need to set `setLowResImageRequest()`. Maybe the main URI is failing so I suggest trying to remove that and `setRetainImageOnFailure()` and see if your image loads as expected.

**Comment by oprisnik** [comment]
I'm closing this issue since it's more than a year old and @kirwan answered your question. Feel free to comment if this is still an issue.

**Comment by 54binge** [comment]
@oprisnik sorry about that,i have not in that team any more,it seems that they use other way instaead. sorry.
