### ISSUE TITLE
Setting android:adjustViewBounds="true" yields wrong height

### ISSUE THREAD

**Issue by DSofter** [facebook/fresco#1452]
With Android `ImageView` I was able to set the `ImageView` as follows and achieve the effect that the ImageView is the same wide as the screen and the height will adjust proportionally. 

![image](https://cloud.githubusercontent.com/assets/1687829/18238426/bac14d62-72f1-11e6-9401-8dc07fc5e3d1.png)

However with `SimpleDraweeView` the height seems a little off:
![image](https://cloud.githubusercontent.com/assets/1687829/18238443/ec6f0a5c-72f1-11e6-8351-80d99a4184a6.png)

Any idea how to fix that?

**Comment by kirwan** [comment]
`adjustViewBounds` is not supported, as documented in the [Gotchas section](http://frescolib.org/docs/gotchas.html#dont-use-imageview-attributes-or-methods-with-draweeview) of the documentation.

Try using `fresco:viewAspectRatio` instead.

**Comment by DSofter** [comment]
@kirwan Thx for your response! I came across this post http://stackoverflow.com/questions/34874463/simpledraweeview-not-resizing-after-scaling-image-in-fresco/34957508#34957508 which mentioned there's disadvantage that comes with using dynamic ratio, wondering what that is?

**Comment by kirwan** [comment]
The primary disadvantage @plamenko was warning of is that if the image size changes when the image loads the screen layout may change after the initial layout. This is a very unpleasant user experience.

However, you can use `android:setAspectRatio` without having to update later as long as you have set either the width or height, which you have in your case with `android:layout_width="match_parent"`

**Comment by DSofter** [comment]
@kirwan That makes a lot of sense! Actually in my case I know the width height ratio is always gonna be a fixed value so i can just ahead and set `fresco:viewAspectRatio` to that fixed value. Thanks so much!
