### ISSUE TITLE
[BUG]closeableObject could be closed unsafely in MultiplexProducer.Multiplexer#onNextResult

### ISSUE THREAD

**Issue by huangjunkun** [facebook/fresco#1453]
**closeableObject** could be closed unsafely in MultiplexProducer.Multiplexer#onNextResult

> com.facebook.imagepipeline.producers.MultiplexProducer.Multiplexer#onNextResult

```
      while (iterator.hasNext()) {
        Pair<Consumer<T>, ProducerContext> pair = iterator.next();
        synchronized (pair) {
          pair.first.onNewResult(closeableObject, isFinal);
        }
      }
```

**The Failed Situation is submitting two image request for the same url image, but their width/height is different.**
In result, one image request is successful, one image request is **failed**. e.g.
![image](https://cloud.githubusercontent.com/assets/815609/18239160/e53e1ee2-7375-11e6-9382-b51271d43426.png)

**Comment by kirwan** [comment]
Hi @huangjunkun. I'm still interested in testing this original issue, after we had to revert the PR. Do you have a simple sample app which results in the screenshot you attached?

If you could send me that it would really help in testing what goes wrong. We think the second line you pointed to should stop this being an issue.

**Comment by huangjunkun** [comment]
@kirwan  sorry, I had deleted  the sameple app.
I just use imagepipeline not use drawee, call 
> com.facebook.imagepipeline.core.ImagePipeline#fetchDecodedImage 

**The Failed Situation is submitting two image request for the same url image, but their width/height is different.**

**Comment by foghina** [comment]
I tried to repro but I couldn't. Both datasources get a valid result with this sample code:

```java
private static class SimpleLoggingDataSubscriber
    extends BaseDataSubscriber<CloseableReference<CloseableImage>> {
  private final String mTag;

  private SimpleLoggingDataSubscriber(String tag) {
    mTag = tag;
  }

  @Override
  protected void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
    Log.d(mTag, String.format(
        "ds#isClosed:%b result#isValid:%b image#isClosed:%b",
        dataSource.isClosed(),
        dataSource.getResult().isValid(),
        dataSource.getResult().get().isClosed()));
  }

  @Override
  protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
    Log.d(mTag, "failed!");
  }
}
// later, in onCreate
final DataSource<CloseableReference<CloseableImage>> ds1 =
    Fresco.getImagePipeline().fetchDecodedImage(
        ImageRequestBuilder.newBuilderWithSource(Uri.parse("http://i.imgur.com/gknajFC.jpg"))
            .setResizeOptions(new ResizeOptions(200, 200))
            .build(),
        null);
final DataSource<CloseableReference<CloseableImage>> ds2 =
    Fresco.getImagePipeline().fetchDecodedImage(
        ImageRequestBuilder.newBuilderWithSource(Uri.parse("http://i.imgur.com/gknajFC.jpg"))
            .setResizeOptions(new ResizeOptions(100, 100))
            .build(),
        null);
ds1.subscribe(new SimpleLoggingDataSubscriber("DS1"), CallerThreadExecutor.getInstance());
ds2.subscribe(new SimpleLoggingDataSubscriber("DS2"), CallerThreadExecutor.getInstance());
```

Closing for now. Feel free to reopen if you have a valid repro (code sample or app).

**Comment by huangjunkun** [comment]
@foghina 
I used the tag v0.10.0  Fresco's ImagePipeline before, which version you use to test ?
Maybe the newest version the problem has been fixed.

**Comment by oprisnik** [comment]
We've released version 1.0.0 now. Could you check if you still have issues with this release? Thanks!

**Comment by huangjunkun** [comment]
@oprisnik 
Using  version 1.0.0   do not have the issues.

**Comment by oprisnik** [comment]
Good to know, thanks @huangjunkun
