### ISSUE TITLE
Where is trim function in MemoryTrimmable called?

### ISSUE THREAD

**Issue by brycegao** [facebook/fresco#1455]
I have download source code of 0.13.0 release.  In the comments,  trim function in MemoryTrimmable can trim memory, But there is no caller to process this method.
As in the picture, there‘s only 8 usage found.
![trim](https://cloud.githubusercontent.com/assets/14868523/18240112/5af5abf4-737c-11e6-84e1-5e991a949389.png)

**Comment by kirwan** [comment]
Look at the [`MemoryTrimmableRegistry`](https://github.com/facebook/fresco/blob/master/fbcore/src/main/java/com/facebook/common/memory/MemoryTrimmableRegistry.java) interface.

The only implementation currently available in the library is a no-op but the docs explain how you can [create your own MemoryTrimmableRegistry](http://frescolib.org/docs/configure-image-pipeline.html#using-a-memorytrimmableregistry).
