### ISSUE TITLE
How to get a collection of MemoryTrimmable objects ?

### ISSUE THREAD

**Issue by brycegao** [facebook/fresco#1457]
As docs said, I can override Activity.onTrimMemory, and excute MemoryTrimmable interface. But how can I get MemoryTrimmable objects?   Can you provide a demo?

If your application listens to system memory events, it can pass them over to Fresco to trim memory caches.

The easiest way for most apps to listen to events is to override Activity.onTrimMemory. You can also use any subclass of ComponentCallbacks2.

You should have an implementation of MemoryTrimmableRegistry. This object should keep a collection of MemoryTrimmable objects - Fresco’s caches will be among them. When getting a system memory event, you call the appropriate MemoryTrimmable method on each of the trimmables.

**Comment by kirwan** [comment]
1) implement `MemoryTrimmableRegistry` (as per the docs you copied here)
2) In your `Application` class customise the config by calling `ImagePipelineConfig.newBuilder()`, provide the builder with an instance of your `MemoryTrimmableRegistry` implementation and build the config to pass to `Fresco.initialize()`.

**Comment by brycegao** [comment]
Hi, kirwan,  I have do it just as you say.  I choose Fresco and Local in Comparison App.  When calling Fresco.initialize(), we can see registerMemoryTrimmable is executed. As docs said, I can override Activity.onTrimMemory and transfer memory event to Fresco. I'm confused how to do it. Can you provide complete Activity.onTrimMemory code? 
     In my opinion, I have to get instance of Fresco memory which implements MemoryTrimmable interface, and calling trim method with memory event.

![trimmable](https://cloud.githubusercontent.com/assets/14868523/18296255/e1e71e0e-74da-11e6-9211-c7b8043ad4b3.png)

**Comment by brycegao** [comment]
Hi kirwan, I've got it.  Can you help check it? 
Here's my solution:
1.   I can define a static instance which hold MemoryTrimmable object. 
  private static ArrayList<MemoryTrimmable> sMemoryTrimmable;
  public static ArrayList<MemoryTrimmable> getMemoryTrimmable() {
      return sMemoryTrimmable;
  }
2.   Save MemoryTrimmable objects to static instance when implement MemoryTrimmableRegistry interface.
  public static ImagePipelineConfig getImagePipelineConfig(Context context) {
    if (sImagePipelineConfig == null) {
      ....
      sMemoryTrimmable = new ArrayList<>();
      configBuilder.setMemoryTrimmableRegistry(new MemoryTrimmableRegistry() {
        @Override
        public void registerMemoryTrimmable(MemoryTrimmable trimmable) {
            sMemoryTrimmable.add(trimmable);
            Log.d("brycegao", "registerMemoryTrimmable size: " + sMemoryTrimmable.size());
        }
        ......
3.  Transfer memory event to Fresco bystatic instance,  Also I can override Application.onLowMemory and process like below.
  @Override
  public void onTrimMemory(int level) {
      super.onTrimMemory(level);
      ArrayList<MemoryTrimmable> array = ImagePipelineConfigFactory.getMemoryTrimmable();
      if (array != null) {
          for (MemoryTrimmable trimmable:array) {
            //just demo, it should be proper params according to level.
            trimmable.trim(MemoryTrimType.OnSystemLowMemoryWhileAppInBackground);
          }
      }
  }

09-07 09:57:15.088 2235-2235/com.facebook.samples.comparison D/brycegao: registerMemoryTrimmable size: 4
   According to the log, there's 4 MemoryTrimmable objects by default. Is't right?

**Comment by kirwan** [comment]
This looks good to me.

I don't believe `sMemoryTrimmable` or `sImagePipelineConfig ` need to be static as your `Application` class will only be instantiated once per session but neither will that break this.

As for the number of trimmables, more than four classes implement `MemoryTrimmable` but some are dependent on the Android version or your config so it seems reasonable that you see four.

**Comment by Logan676** [comment]
@brycegao Does your solution actually work? I have tried this but I didn`t find any memory reduction.
