### ISSUE TITLE
Request Timeout

### ISSUE THREAD

**Issue by githubdoramon** [facebook/fresco#146]
If the source from the image is a network url, and for some reason that image does not exist anymore, how can I tell it to cancell the request? My problem is that in these cases the app becomes really slow, probably because it keeps trying to get the image. Is it possible to make a request timeout or something like this?

**Comment by tyronen** [comment]
If you are using a SimpleDraweeView, you can simply `setImageURI` to null, which will cancel the request unless it has already started loading.

If you are using OkHttp, you can use the OkHttpClient.setReadTimeout method to set a timeout.

**Comment by githubdoramon** [comment]
@tyronen in the SimpleDraweeView, how can I set the Uri to null if I have now idea if the image exists or not?

**Comment by githubdoramon** [comment]
One more.... when is it the fresco:failureImage called?

**Comment by tyronen** [comment]
If the image fails to load - a default timeout, no internet connection, connection reset etc, you will see the failure image. 

Note that a bad URL shouldn't be slowing your app down at all. If the server doesn't have the image you ask for, it should give you a 404 right away - usually faster, in fact, than a found image.

If you had a slow server or slow internet, the download might take a while, but that alone isn't enough to slow your app down. Unless you are requesting a large number of images one by one in a slow network environment.

**Comment by githubdoramon** [comment]
please disregard my questions... I understood how to use the failure stuff now.... Thanks for your patience
