### ISSUE TITLE
DiskStorageCache mLock problem

### ISSUE THREAD

**Issue by jiqimaogou** [facebook/fresco#1460]
as we see, when new DiskStorageCache class, it could use a background thread to calculate the cache size which may take long time, and when I want to get a resource, it must wait the initialization to complete, because they use the same locker. 

can this be optimized?

**Comment by erikandre** [comment]
Closing as part of our cleanup of old issue.
We've not seen that this synchronization (and waiting for the lock) is causing issues but if anyone is experiencing issue with this, please file a new bug report.
