### ISSUE TITLE
how to get  http response header?

### ISSUE THREAD

**Issue by jyh149129** [facebook/fresco#1464]
in my case , some value store in http response header ,how to get it ?

**Comment by kirwan** [comment]
This has been asked before, for example #712.

It's not currently possible. Images aren't always retrieved from HTTP (for example local or cached images) so these wouldn't be available consistently anyway.

You would be able to extract the headers if you implemented your own `NetworkFetcher` however you would still need to find another way of passing back the values you want.

**Comment by jyh149129** [comment]
ok, Fine
