### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by riccyRascal** [facebook/fresco#1465]
it's that a way that I can add params to my request, not in the link but in the header or body?

**Comment by kirwan** [comment]
It's not currently possible but we have recently received PR #1459 which allows the addition of headers to be included in the request. This should be available in the next release of Fresco.

It's dependent on using a `NetworkFetcher` which makes use of the headers added to the `ImageRequest` though.

**Comment by oprisnik** [comment]
You can however implement your own network fetcher or extend one of the existing ones to just add your parameters.
