### ISSUE TITLE
Can I use Fresco download video files?

### ISSUE THREAD

**Issue by 1181631922** [facebook/fresco#1471]
I can use Glide download video files,now I use fresco but I do not know how to use it download video files or Fresco can not download video files?

**Comment by lambdapioneer** [comment]
Hi @1181631922, Fresco does not support downloading videos, as it is focussed on still images.

You can use the underlying network stack (e.g. HttpURLConnection, OkHttp2/3 or Volley) to download files manually. Or use Android's [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager.html) for large files.

**Comment by 1181631922** [comment]
OK,thanks ,Fresco will add this function or not in the future?

**Comment by lambdapioneer** [comment]
Most likely not, as we are focussed on images.
