### ISSUE TITLE
imagePipelineFactory.getMainFileCache().getSize() return -1 after app restart

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#1472]
Hello,

Testing crash reports and then have some app restart, I see imagePipelineFactory.getMainFileCache().getSize() return -1 even if cache is not empty (it's the same for getCount()).

This was not the case some time ago.

My repository is up to https://github.com/facebook/fresco/commit/93d5a4c81c8b4b1bb9e5a1f874851969d06a3a0f.

I will update it this afternoon and test again.

Thanks,

Eric

**Comment by eldk** [comment]
Hello,

I have tested on last Fresco master branch : https://github.com/facebook/fresco/commit/b74da9e78f47db5baaba419f2fea606607d6cb4b .

It's the same, after app restart (device restart, force shutdown, or app crash), cacheStats are not initialized, so getSize() or getCount() return -1.

This PR solve it : https://github.com/facebook/fresco/pull/1473.

Thanks,

Eric

PS : CircleCl is broken

**Comment by lambdapioneer** [comment]
Hi @eldk,

I'm currently fixing the CI. Once that's done I'll have a look at the PR.

Cheers, Daniel

**Comment by eldk** [comment]
Hello,

This was solved using : 

`DiskCacheConfig diskCacheConfig = DiskCacheConfig.newBuilder(context)`
(...)
`.setIndexPopulateAtStartupEnabled(true)`
`.build();`

Doc : http://frescolib.org/javadoc/reference/com/facebook/cache/disk/DiskCacheConfig.html

Sorry,

Eric

**Comment by weibingyi** [comment]
Fresco.getImagePipelineFactory().getMainFileCache().trimToMinimum(); 
long cacheSizeFresco = Fresco.getImagePipelineFactory().getMainFileCache().getSize();
