### ISSUE TITLE
Does it support custom calculateInSampleSize or custom decode (such as BitmapRegionDecoder) ? 

### ISSUE THREAD

**Issue by leelei** [facebook/fresco#148]

**Comment by tyronen** [comment]
Not yet, though this could be added. Note that similar functionality can already be done with [resizing](http://frescolib.org/docs/resizing-rotating.html)

Can you give me an example where that doesn't meet your needs?

**Comment by leelei** [comment]
resizing not afford my need. if a image width and height is  440*8000, to avoid "Bitmap too large to be uploaded into a texture"  it should resize , if inSampleSize = 4 , width is so small to fit screen, so i nedd show a part of image, use BitmapRegionDecoder, decode reegion  such as Rect(0, 0, 440, 400)

**Comment by plamenko** [comment]
I think this is very similar to https://github.com/facebook/fresco/issues/4

**Comment by leelei** [comment]
yes i know SubsamplingScaleImageView , but i think it use just to show a single image. I have a ListView ,each item contain image , not sure the size of the picture, some image is about 400*400 , some is  440*8000, SubsamplingScaleImageView in ListView not work well  and smooth
