### ISSUE TITLE
fix TooManyBitmapsException

### ISSUE THREAD

**Issue by anastr** [facebook/fresco#1481]
i tried to load just 3 photos (Local images) using `SimpleDraweeView`, **But** it is display just the first picture ...
the code : 

``` java
PipelineDraweeControllerBuilder controller = Fresco.newDraweeControllerBuilder();
        controller.setUri(uri);
        controller.setOldController(draweeView.getController());
        controller.setControllerListener(new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                super.onFinalImageSet(id, imageInfo, animatable);
                if (imageInfo == null) {
                    return;
                }
                // ....
            }

            @Override
            public void onFailure(String id, Throwable throwable) {
                super.onFailure(id, throwable);
                throwable.printStackTrace();
            }
        });
        draweeView.setController(controller.build());
```

throwable print **TooManyBitmapsException** .....

i tried to remove memory cashed , it didn't work ...
image's size between (2500 - 3000 px) and _i don't need to resize any one_.
**So** please, we need a solution.

**Comment by kirwan** [comment]
You say you've only attempted to load three images, but that exception should only be thrown once you've [created 384 bitmaps](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/BitmapCounterProvider.java#L24).

Are you absolutely sure you're not loading any other images within your app which aren't being released?

**Comment by anastr** [comment]
no nothing from this.
actually, it is just three, in ViewPager...

it is happen just when image's width or height > 2500 .
image size on disk 2MB.

**Comment by anastr** [comment]
It turned out that I was using a library that called `Fresco.initialize(context);` method.
thanks.
