### ISSUE TITLE
Local gif only play once.

### ISSUE THREAD

**Issue by niorgai** [facebook/fresco#1483]
I put a gif in drawable resource of my project and call `setAutoPlayAnimations(true)`.
But I found it only play once.

Later I change the local resource to a gif url, it works fine.

**Comment by kirwan** [comment]
Are the drawable resource and the one downloaded from the URL _exactly_ the same GIF?

When you're loading it from local resources, how are you doing that?

**Comment by niorgai** [comment]
@kirwan 
Sorry about reply so late, My network had some problem so i didn't get the notification email.

They are not the same GIF, but the drawable resource works fine on iOS device. And finally I found the hack method.

````Java
setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                        super.onFinalImageSet(id, imageInfo, animatable);

                        if (animatable != null) {
                            try {
                                Field field = AbstractAnimatedDrawable.class.getDeclaredField("mLoopCount");
                                field.setAccessible(true);
                                field.set(animatable, 0);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                            animatable.start();
                        }
                    }
                })

But I think it is not a good solution. From the document it should work fine.

**Comment by oprisnik** [comment]
Can you try with v0.14.1? We've changed the loop count parsing in 95359b9cb7650cf00b362ffbc018e90d503d476b

**Comment by niorgai** [comment]
v0.14.1 still not work.

**Comment by oprisnik** [comment]
It looks like your GIF has no NETSCAPE2.0 block, which means that the GIF should only be repeated once. 

I suppose that this GIF plays correctly: https://s3.amazonaws.com/giphygifs/media/4aBQ9oNjgEQ2k/giphy.gif

**Comment by niorgai** [comment]
You are right. i download this gif and it works fine.
Thank you for your answer.
