### ISSUE TITLE
prefetchToBitmapCache not support post process?

### ISSUE THREAD

**Issue by SethFeng** [facebook/fresco#1485]
```java
Fresco.getImagePipeline().prefetchToBitmapCache(
        ImageRequestBuilder.newBuilderWithSource(Uri.parse(url))
                .setPostprocessor(new XXXPostprocessor())
                .build(),
        null);
```
XXXPostprocessor.process() not executed. 
Changing `prefetchToBitmapCache` to `fetchDecodedImage`, XXXPostprocessor.process() will be excuted!

**Comment by kirwan** [comment]
You're right. `prefetchToBitmapCache()` only takes the image as far up the pipeline as the main bitmap cache.

Post-processing and caching the result of that comes later.

Pre-fetching before you need the image will give you the benefit of downloading the image and decoding into bitmap cache. Then calling `fetchDecodedImage()` will take the image from cache and run the post-processor.
