### ISSUE TITLE
Authenticator.setDefault() with Fresco requests

### ISSUE THREAD

**Issue by Doomkyn** [facebook/fresco#1487]
Hi I'm using Fresco to show images from a password-protected webservice.
I'm setting the default authenticator for my http/https requests in my app's onCreate like this:

```
        Authenticator.setDefault(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(
                        userWebService, pwdWebService.toCharArray());
            }
        });
```

But everytime I call

```
                SimpleDraweeView image = (SimpleDraweeView) findViewById(R.id.imageView_product);
                GenericDraweeHierarchy h = image.getHierarchy();
                h.setActualImageScaleType(ScalingUtils.ScaleType.CENTER_INSIDE);
                image.setImageURI(uri);
```

the request is fired twice: the first fails the authentication (response 401) while the second authenticate correctly (response 200).
I'm not 100% sure but I actually feel like it's a Fresco issue since the code is really simple.
Is anyone able to test this?

Thanks, 
Kind Regards.

**Comment by massimocarli** [comment]
Thanks @Doomkyn,
this is interesting. Could you provide us more context please? What HTTP layer are you using?

Thanks

**Comment by Doomkyn** [comment]
Hi @massimocarli,
What do you mean with HTTP layer? I'm simply authenticating to a Windows WebService that provides me images, I actually cannot share the WebService's informations since that's an internal service and can only be accessed from the intranet.
I don't know which detail can I add to make it more clear, but if you have any ideas I'm up to it.
Thanks

**Comment by massimocarli** [comment]
Sorry @Doomkyn,
I meant the network layer. Are you using http3?

Thanks

**Comment by Doomkyn** [comment]
@massimocarli the WebService is an https address.

**Comment by Doomkyn** [comment]
@massimocarli if you mean which library I'm using in my application, I'm using none, I only use the native android Authenticator method exactly like I posted in my first post.
If anyone could do a test on this would be good.
PS: I have no control over the WebService.

**Comment by Doomkyn** [comment]
UPDATE:
Actually seems like a bug of the native android network layer (HttpURLConnection).
Previously I was doing this to initialize Fresco:

```
Authenticator.setDefault(new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(
                        userWebService, pwdWebService.toCharArray());
            }
        });

Fresco.initialize(this);
```

In this case, the agency that provide me the WebService form where I load my images told me they always see 2 requests for every image, the first without authentication header and the second correctly authenticated.

Then, thanks to @massimocarli's post , I tried using OkHttp3 as network layer, implementing it like this:

```
String credentials = userWebService + ":" + pwdWebService;
        final String basic =
                "Basic " + Base64.encodeToString(credentials.getBytes(), Base64.NO_WRAP);
        final OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder()
                .addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        final Request.Builder requestBuilder = chain.request().newBuilder();
                        requestBuilder.addHeader("Authorization", basic);
                        return chain.proceed(requestBuilder.build());
                    }
                });
        final ImagePipelineConfig imagePipelineConfig = OkHttpImagePipelineConfigFactory.newBuilder(
                getApplicationContext(),
                okHttpClientBuilder.build())
                .build();

        Fresco.initialize(this, imagePipelineConfig);
```

And now it seems to work fine: only one authenticated request is fired.

I'm not closing this, I actually wait for a mod to close this so if there is a more technical consideration to do, it can be done.

Kind regards.

**Comment by massimocarli** [comment]
Great @Doomkyn,
that is actually the solution that we usually suggest for this :)

Thanks
