### ISSUE TITLE
can someone please tell me how to use gif in fresco kindly?

### ISSUE THREAD

**Issue by walter-ghost** [facebook/fresco#1489]
i'm a beginner and i cannot understand any explanation given by fresco website.

        String uri = "android.resource://" + getPackageName() + "/"+R.raw.inbody_gif;
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setAutoPlayAnimations(true)
        .build();
        mSimpleDraweeView.setController(controller);

trying to use my own gif file, but keep getting error on the last line on the controller.

Android is keep tellling me null point exception.

**Comment by massimocarli** [comment]
Hi @walter-ghost,
[here](http://frescolib.org/blog/2016/09/02/fresco-101.html) you can find an example.
Thanks
