### ISSUE TITLE
Does Fresco support Multi Touch To Zoom?

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#149]
Does Fresco support Multi Touch To Zoom?
How to do?

**Comment by tyronen** [comment]
We don't support multi-touch to zoom right now.

**Comment by plamenko** [comment]
See a duplicate issue: https://github.com/facebook/fresco/issues/86
And @nbarraille's implementation: https://gist.github.com/nbarraille/eb5d0da20bc813969b08

**Comment by arlindiDev** [comment]
Here is the code for smooth double tap zoom and pinch to zoom for the fresco library
https://github.com/arlindiDev/FrescoDoubleTapZoom

![](https://github.com/arlindiDev/FrescoDoubleTapZoom/blob/master/gif.gif?raw=true)

**Comment by BurakDizlek** [comment]
https://github.com/ongakuer/PhotoDraweeView     I am using this. The best solution.

**Comment by praneetloke** [comment]
@BurakDizlek I just started using PhotoDraweeView after seeing your comment and I agree it is the best so far that works with Fresco. I am hoping for [this](https://github.com/facebook/fresco/issues/4) issue to be implemented though.
