### ISSUE TITLE
Force rotation for image with EXIF orientation tag

### ISSUE THREAD

**Issue by nesterov-n** [facebook/fresco#1492]
Fresco 0.14 added new class `RotationOptions.forceRotation(int angle)` allows users to rotate image to custom angle. `forceRotation` doesn't pay attention to EXIF orientation tag. I think it will be more useful to calculate angle passed to `JpegTranscoder` as difference between EXIF orientation  tag and angle set by user.
In my opinion, most common use-case for for force rotation is "Show image rotated by 90 degrees from it's natural orientation", not "Show image rotated by 90 degrees from how it saved in file "
It can be done by custom `PostProcessor` now. But it is additional time-consuming step and additional memory allocation.
If you approve this proposal I can prepare PR for it.

**Comment by kirwan** [comment]
@nesterov-n Your proposal makes perfect sense and a PR would be gratefully received.

**Comment by erikandre** [comment]
Closing issue as the pull request was merged some time ago
