### ISSUE TITLE
Static code Analysis number

### ISSUE THREAD

**Issue by patientrx** [facebook/fresco#1494]
Hi
If they are using Static Code Analysis, what is the tool. How many low, mid, high issues.
Also suggest the evidence for same.

**Comment by oprisnik** [comment]
Hi! Can you give us more details what exactly what you mean by that? Static Code Analysis is a very wide topic, what are "low, mid, high issues"?

**Comment by patientrx** [comment]
We are looking for the result of static code analysis(SCA) for fresco code. There are SCA tools available which help identify security issue in code/program - stating low , mid and high types  
Tools
Google CodePro Analytix (Free)(one of my favourate tool), 
Findbugs. 
PMD. 
Checkstyle.

**Comment by oprisnik** [comment]
Internally, we use infer for static analysis and also run a range of linters, and run tests for every commit (Circle CI). Unfortunately, I don't have any numbers for you.
