### ISSUE TITLE
Question: is there a way to remove all other caches if not in a special url list.

### ISSUE THREAD

**Issue by shirensong** [facebook/fresco#1495]
I have a requirement to just remove all other image caches if not in a special url list. I do not know if there is a way to do this.

**Comment by oprisnik** [comment]
I don't think that this is currently possible. 
For memory caches, something similar to [clearMemoryCaches()](https://github.com/facebook/fresco/blob/84aeab6895f3177cee473e85656cf898112f263f/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipeline.java#L375) with a custom `Predicate` that only clears the images that you want.

**Comment by erikandre** [comment]
Closing as this is enhancement is not prioritized to be implemented.
Still, please feel free to submit a pull request for any missing functionality.
