### ISSUE TITLE
could I custom producer and set it to ImagePipeline to load image for special cases?

### ISSUE THREAD

**Issue by zjupure** [facebook/fresco#1497]
As I know, fresco supports custom network fetcher. But I want to customize some local file fetcher to load image from disk. Is there any interface for imagepipeline to customize the produer?

The case is I have some videos with private file formats and I want get thumbnail from them. Not like the general video, I can get thumbnail through uri format(file:///) and it will be auto processed by LocalVideoThumbnailProducer. For those private videos, if i want to get thumnail through fresco, i must custome the producer to replace the normal producer. Therefore, I can take advantage of fresco and cache management to simplify my code.

Is is possible for fresco to customize the producer pipeline?

**Comment by oprisnik** [comment]
Hi! You could try doing this with a custom decoder. I have recently added this functionality and a [simple sample app](https://github.com/facebook/fresco/tree/master/samples/decoders).

You could add a custom image format for your use case and add a custom decoder that does whatever you want.

For now, you have to manually clone the GitHub repo though since we did not release a pre-built version that includes custom decoder support yet.

**Comment by zjupure** [comment]
Thanks. The sample looks good and could solve my problem.

It means current release version do not support this function. So when the release version will be available to customize the ImageDecoder? Or which version?

**Comment by oprisnik** [comment]
Good to hear that this works for you!

The next version that we release will support this and we're releasing quite regularly right now, so expect a new version soon (a couple of days I suppose). For now you can just check out Fresco from GitHub and include in your project.

**Comment by shuangmin** [comment]
@oprisnik the url you offer invalided, how can i find the real url

**Comment by oprisnik** [comment]
We've moved the custom decoder samples to https://github.com/facebook/fresco/tree/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat
