### ISSUE TITLE
Add aspectRatio into xml property

### ISSUE THREAD

**Issue by villadora** [facebook/fresco#150]
Hi, I found that in the doc, we can call `setAspectRatio` in java to set aspect ratio, but it's not available for declaring in xml, like:

```
<SimpleDraweeView fresco:aspectRatio="1.3f" />
```
Thanks

**Comment by tyronen** [comment]
I think we will have this ready soon.

**Comment by tyronen** [comment]
This has been added in today's release, 0.4.0. It is called `fresco:viewAspectRatio`.

**Comment by squeeish** [comment]
Does it work? I get the error

Error:(29, 37) String types not allowed (at 'viewAspectRatio' with value '1.33f').
