### ISSUE TITLE
SimpleDraweeView加载从相册里选择的图片之后会变成黑色

### ISSUE THREAD

**Issue by XumingX** [facebook/fresco#1501]
设备：红米1s，Android 4.4.4，MIUI 8.0
问题：选择图片路径是外置内存卡时，可以正常显示；当路径是**内置内存卡**时，会变成黑色。

显示图片正常uri路径：_/storage/sdcard1/DCIM/Camera/IMG_20160525_144332.jpg_
显示图片变黑uri路径：_/storage/emulated/0/DCIM/Camera/IMG_20161013_182559.jpg_

用image pipeline 打出的VERBOSE级别日志，变黑的情况会多出两条log：
```
V/unknown:NativeMemoryChunkPool: release (free) (object, size) = (4242fe48, 1164920)
V/unknown:NativeMemoryChunkPool: Used = (1, 131072); Free = (1, 1048576)
```
代码：
```
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == PhotoSelectDialog.ITEM_CAMERA && resultCode == RESULT_OK) {
            LogUtils.d("获取拍照uri", mCameraUri.getPath());
            headImage.setImageURI(mCameraUri);
        } else if (requestCode == PhotoSelectDialog.ITEM_ALBUM && resultCode == RESULT_OK) {
            LogUtils.d("获取图片uri", data.getData().getPath());
            Uri albumUri = data.getData();
            headImage.setImageURI(albumUri);
        }
    }

```
布局：
```
 <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/imageLeftBarHead"
        android:layout_width="171px"
        android:layout_height="171px"
        android:layout_marginLeft="61px"
        android:layout_marginTop="67px"
        fresco:roundAsCircle="true" />
```
已使用下面的代码查找异常，但没有报错
`FileInputStream fis = new FileInputStream(new File(localUri.getPath()));`

另外使用URI 带上 scheme依旧会出现问题，代码如下
`headImage.setImageURI("file://" + albumUri.getPath());`

**Comment by oprisnik** [comment]
Are you sure that both files exist? Can you access them with ADB?

**Comment by XumingX** [comment]
This is the uri log : _file:///storage/emulated/0/KydwSmartKey/JPEG_20161017_1032411961543464.jpg_
I can access it with ADB at : 
![image](https://cloud.githubusercontent.com/assets/13777420/19423728/e1dd6fe0-9455-11e6-8d86-aa68e0bf110c.png)
@oprisnik 
Still I can't find out where the problem is...
Hope to receive your reply!

**Comment by XumingX** [comment]
My problem is in this picture.
![device-2016-10-17-110207](https://cloud.githubusercontent.com/assets/13777420/19424177/a9fcf4f2-9459-11e6-9d3a-3e9966dcc6fe.png)

**Comment by XumingX** [comment]
This is the uri log : _file:///storage/emulated/0/KydwSmartKey/JPEG_20161017_1032411961543464.jpg_
And I also can access it with ADB at:
![image](https://cloud.githubusercontent.com/assets/13777420/19424591/ec6caeec-945c-11e6-8804-e5a111b82ca9.png)
I think this is a MIUI system error...

**Comment by XumingX** [comment]
But if I use  `File file = new File("/storage/sdcard0" + "/KydwSmartKey");` to create file, it still can't load.
I can access it with ADB at the right path.

**Comment by oprisnik** [comment]
So this seems to be a device specific problem then. Let us know if you think this is a Fresco problem.

In general, you shouldn't hardcode these paths but use Android's system methods to get to the correct directories.

**Comment by xdcosmosli** [comment]
if you problem solved?

**Comment by xdcosmosli** [comment]
你的问题最后怎么解决的？ @XumingX
