### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 6170268 byte allocation with 1845100 free bytes and 1801KB until OOM

### ISSUE THREAD

**Issue by YangCrayon** [facebook/fresco#1503]
scrollview+viewpager+fragment+recyclerview+fresco

**Comment by lambdapioneer** [comment]
Hi @YangCrayon, please have a look at http://frescolib.org/docs/troubleshooting.html

If the problem persists, please provide more details such as logs, android version, sample images and ideally a minimal piece of code that reproduces the issue.
