### ISSUE TITLE
duplicate entry: android/support/v4/print/PrintHelper$PrintHelperStubImpl.class  fresco build error ，is anyone have this problem

### ISSUE THREAD

**Issue by yuxingfafu** [facebook/fresco#1506]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/print/PrintHelper$PrintHelperStubImpl.class

**Comment by yuxingfafu** [comment]
version is 0.14.1
this is my config 



 compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.greenrobot:eventbus:3.0.0'//eventbus 事件总线 发布订阅
    // compile 'com.android.support:support-v4:23.+'//support支持库
    compile 'com.google.code.gson:gson:2.7'//gson解析
    compile 'com.android.support:recyclerview-v7:23.+'//recyclerview
    compile 'com.github.bumptech.glide:glide:3.7.0'//图片加载
    compile 'in.srain.cube:ultra-ptr:1.0.11'//下拉刷新控件
    compile project(':library')
    compile 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.2.2'//RecyclerView 快速适配器
    compile ('com.facebook.fresco:fresco:0.14.1'){
        exclude group:'com.nineoldandroids'
    }

    compile 'com.facebook.fresco:animated-gif:0.14.1'

**Comment by oprisnik** [comment]
You need to update your support library, see #1493
