### ISSUE TITLE
Download large sizes of images

### ISSUE THREAD

**Issue by wangbourne** [facebook/fresco#1507]
I have an image with a size of 8000 *8000, i need to show it on an imageview with size of 200dp *200dp. So generally you know there could be a problem of memory waste or even out of memory.

My simple question is: 
do i need to apply advanced technologies in Fresco like scaling or resizing to achieve this, or Fresco automatically elegantly deal with it and memory  with only couple lines  simple codes like:

`Uri uri = Uri.parse("https://raw.githubusercontent.com/facebook/fresco/gh-pages/static/logo.png");
SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
draweeView.setImageURI(uri);`

**Comment by lambdapioneer** [comment]
Hi @wangbourne, have a look at http://frescolib.org/docs/resizing-rotating.html . You probably want to apply resizing and/or downsampling for that request. An image of that size is likely to have a decoded size of around 250 MiB!

**Comment by wangbourne** [comment]
Got it. Thanks
