### ISSUE TITLE
How to extend ImageRequest

### ISSUE THREAD

**Issue by wstczlt** [facebook/fresco#1508]
I have a bean named Photo, the bean has more than one imageUrl, so i should use 'setFirstAvailableImageRequests'.  I want to use Photo.Id to generate the cacheKey for following reasons:
1. I want to use Photo.Id to generate the cacheKey, because all of it's urls can share the same cache.
2. When i want to fetchBitmapCache, i can just use the Photo.Id to fetch, because the i don't know which url fetched the Image.
For the feature, I need to extend ImageRequest and add a String field named mCacheKey, and override CacheKeyFactory and use ImageRequest.mCacheKey to getCache.

Is there any better way for the feature?

**Comment by wstczlt** [comment]
Code:
/**
 * 这个Request的目的是让一组Url可以共用一个CacheKey.
 * 例如QPhoto中CDNUrl[]数组创建的ImageRequest[], 逻辑上这组ImageRequest应该共用一个CacheKey.
 */
public class CacheKeyImageRequest extends ImageRequest {

  private final String mCacheKey;

  public CacheKeyImageRequest(ImageRequestBuilder builder, String cacheKey) {
    super(builder);
    mCacheKey = cacheKey;
  }

  public String getCacheKey() {
    return mCacheKey;
  }

}




package com.yxcorp.gifshow.image;

import android.support.annotation.Nullable;

import com.facebook.cache.common.CacheKey;
import com.facebook.cache.common.SimpleCacheKey;
import com.facebook.imagepipeline.cache.BitmapMemoryCacheKey;
import com.facebook.imagepipeline.cache.CacheKeyFactory;
import com.facebook.imagepipeline.cache.DefaultCacheKeyFactory;
import com.facebook.imagepipeline.request.ImageRequest;
import com.facebook.imagepipeline.request.Postprocessor;

public class KwaiCacheKeyFactory implements CacheKeyFactory {

  @Override
  public CacheKey getBitmapCacheKey(ImageRequest request, Object callerContext) {
    return new BitmapMemoryCacheKey(
        getCacheKeyForRequest(request),
        request.getResizeOptions(),
        request.getAutoRotateEnabled(),
        request.getImageDecodeOptions(),
        null,
        null,
        callerContext);
  }

  @Override
  public CacheKey getPostprocessedBitmapCacheKey(ImageRequest request, Object callerContext) {
    final Postprocessor postprocessor = request.getPostprocessor();
    final CacheKey postprocessorCacheKey;
    final String postprocessorName;
    if (postprocessor != null) {
      postprocessorCacheKey = postprocessor.getPostprocessorCacheKey();
      postprocessorName = postprocessor.getClass().getName();
    } else {
      postprocessorCacheKey = null;
      postprocessorName = null;
    }
    return new BitmapMemoryCacheKey(
        getCacheKeyForRequest(request),
        request.getResizeOptions(),
        request.getAutoRotateEnabled(),
        request.getImageDecodeOptions(),
        postprocessorCacheKey,
        postprocessorName,
        callerContext);
  }

  @Override
  public CacheKey getEncodedCacheKey(ImageRequest request, @Nullable Object callerContext) {
    return new SimpleCacheKey(getCacheKeyForRequest(request));
  }

  private String getCacheKeyForRequest(ImageRequest request) {
    if (request instanceof CacheKeyImageRequest) {
      return ((CacheKeyImageRequest) request).getCacheKey();
    }
    return request.getSourceUri().toString();
  }
}

**Comment by lambdapioneer** [comment]
Hi @wstczlt, thanks for the question. @kirwan is currently implementing `MediaVariations`. I think these changes provide the feature you are asking for (first commit: https://github.com/facebook/fresco/commit/3f851dbf1369b7d381eec89307b16e3a81857f5e).

Until those changes make it into a release, you could also consider just implementing a custom `getCacheKeyForRequest` in the cache key factory and have an external component map the different URLs to IDs that you then use for the cache keys.

**Comment by kirwan** [comment]
Are you saying the different URLs point to exactly the same image at the same size?

If so, a `CacheKeyFactory` which creates keys based on this ID sounds like it would work perfectly and may require your extended `ImageRequest`.

Another option would be to normalize the Uri into a cache key which removes the parts which may vary between versions of the Uri, if that's possible.

The Media Variations API @lambdapioneer mentioned is intended to help in cases where you have the same image at different sizes and these may be suitable to serve a new request rather than requesting a new version of the image from the network.

**Comment by wstczlt** [comment]
Thank you for your reply!
@kirwan I have already extend the ImageRequest, however, I think is not very elegant because I must supply a ImageRequestBuilder for the constructor, maybe i should also extend ImageRequestBuilder? But ImageRequestBuilder's constructor is private, so sad :(

**Comment by kirwan** [comment]
In that case, if you can wait for our next release you will see the addition of a [`MediaVariations`](https://github.com/facebook/fresco/blob/50a6a39e81a47cc55527ec51ed123adbfbc13832/imagepipeline/src/main/java/com/facebook/imagepipeline/request/MediaVariations.java) object in the image request. This takes an ID for the piece of media and you will be able to use that in your custom `CacheKeyFactory`.

**Comment by wstczlt** [comment]
Thank you very much !

**Comment by lambdapioneer** [comment]
Looks resolved :)
