### ISSUE TITLE
Can't Run Unit Tests for project

### ISSUE THREAD

**Issue by pedant** [facebook/fresco#151]
I can't execute unit-test from android studio by "build variants" tool.I changed plugin versions as follow:
```javascript
ANDROID_GRADLE_PLUGIN_VERSION=1.1.0
ROBOLECTRIC_GRADLE_PLUGIN_VERSION=1.0.1
```
added dependency `org.powermock:powermock-api-mockito:1.6.2`
now everything looks well as below:
![image](https://cloud.githubusercontent.com/assets/5111206/7158679/06db5054-e3af-11e4-85b7-b2f5c2e4ea9c.png)

until i run any method with @test annotation, i found this error:
![af8730a7e0dfdae3d78b4cb15a2e8d7d](https://cloud.githubusercontent.com/assets/5111206/7159021/c921d30c-e3b1-11e4-951c-3956ff512174.jpg)

all in package com.facebook.common.testing couldn't be find, **FakeClock not found**, but they actually exist there.**Why?**

although i removed lines related FackClock, the result is:
```shell
com.facebook.drawee.controller.AbstractDraweeControllerTest > testLoadingS_FFS FAILED
    java.lang.IllegalArgumentException

com.facebook.drawee.controller.AbstractDraweeControllerTest > testLoadingS_FGS FAILED
    java.lang.IllegalArgumentException

com.facebook.drawee.controller.AbstractDraweeControllerTest > testLoadingS_FLS FAILED
    java.lang.IllegalArgumentException

com.facebook.drawee.controller.AbstractDraweeControllerTest > testLoadingS_GFS FAILED
    java.lang.IllegalArgumentException

com.facebook.drawee.controller.AbstractDraweeControllerTest > testLoadingS_GGS FAILED
    java.lang.IllegalArgumentException

com.facebook.drawee.controller.AbstractDraweeControllerTest > testLoadingS_LFS FAILED
    java.lang.IllegalArgumentException
....
....
201 tests completed, 201 failed
:drawee:testDebug FAILED
Error:Execution failed for task ':drawee:testDebug'.
> There were failing tests. See the report at: file:///D:/work/fresco/drawee/build/reports/tests/debug/index.html
```
**Does it success?** please help ,thanks a lot.

**Comment by tyronen** [comment]
Yes, unfortunately our unit tests only work in our internal build environment. We hope to fix this soon.

**Comment by pedant** [comment]
thanks for your answer, looking forward to your fix very much.

Meanwhile is it convenient to show your other dependencies in advance?

**Comment by tyronen** [comment]
This is now fixed in source.
