### ISSUE TITLE
Failed to load URI having non-ascii characters

### ISSUE THREAD

**Issue by stephen-niu** [facebook/fresco#1510]
hey guys , when i load imageurl="http://211.138.24.191:28090/ngvlcs/201609/9d32cd535b084a5881dec2076fa29058_天津王睿泽.jpg?AccessId=6cb8a292a4d2d9d2905c&Expires=4628058286&Signature=7VLhulfnCWCffz2JkLe8%2BkmFunw%3D" ;  SimpleDraweeView didn't work.   isn't  imaeurl   could not appeared Chinese？

**Comment by lambdapioneer** [comment]
Hi @stephen-niu, the given URL does not (even) load in my browser. Have tried another HTTP framework like OkHttp3 described here: http://frescolib.org/docs/using-other-network-layers.html ?

In any case, it would be great if you could provide us the logcat output by following the steps here: http://frescolib.org/docs/troubleshooting.html

**Comment by stephen-niu** [comment]
Thank you for your reply   
This's normal , that's URL was in my country（china）
my point is   look at this picture 
<img width="617" alt="43dc1974-f206-4914-aaa7-53debff8ad81" src="https://cloud.githubusercontent.com/assets/17307584/19598458/82e16336-97cd-11e6-82f3-3a09c5f18248.png">
when that 'url' contains Chinese like this "http://231.128.123.123:8070/你好/d3c50"    
that code  ' simpleDraweeView.setController(controller);  '  don't work
at least for now

**Comment by stephen-niu** [comment]
sorry    this question was  solved, all because my cellphone system . 
fresco was great
thanks everybody

**Comment by SethFeng** [comment]
I met the problem "URL has Chinese", too. My Nexus 6 is OK, but XiaoMi failed.
I fix the problem  using OkHttp3 for the network layer, instead of the default client HttpURLConnection。See the [doc](http://frescolib.org/docs/using-other-network-layers.html).
