### ISSUE TITLE
Really low performance on RecyclerView 

### ISSUE THREAD

**Issue by senhor** [facebook/fresco#1517]
I am using fresco for loading profile pictures of users and it is really laggy when there is more then 3 visible images in a recycler view. 

here is the problematic layout. There is no lag when DraweeView's visibility is set to "gone".

![screenshot_20160831-173440](https://cloud.githubusercontent.com/assets/5410942/19829699/64ed7570-9df1-11e6-83d7-cc93e35f358e.png)

_**EDIT:**_

* I haven't made any changes on ImagePipelineConfig
* 
`holder.profilePicture.setImageURI(Uri.parse(Connection.getImageLink((String) data.get("profileimageid"))));`

"data" is a HashMap<Obejct>

```
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/profilePicture"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_margin="10dp"
        app:roundAsCircle="true"/>
```

* 69,7 KB 1080x1080

* Dataset updates doesn't affect the sliding at all

I think the problem relies behind your third question. Having a 1080x1080 images is a big problem. Doesn't Fresco resize images after loading them? It shouldn't lag like that if so, I think. 

Thanks for your help.

**Comment by kirwan** [comment]
I can't say why that might be based on the information you've given.

- Have you made any changes to the default ImagePipelineConfig?
- Can you show an example image request and/or the drawee view's XML?
- What size are the images received from the server?
- Do you repeatedly update the dataset or do you just update the adapter once?

**Comment by senhor** [comment]
* I haven't made any changes on ImagePipelineConfig
* 
`holder.profilePicture.setImageURI(Uri.parse(Connection.getImageLink((String) data.get("profileimageid"))));`

"data" is a HashMap<Obejct>

```
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/profilePicture"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_margin="10dp"
        app:roundAsCircle="true"/>
```

* 69,7 KB 1080x1080

* Dataset updates doesn't affect the sliding at all


I think the problem relies behind your third question. Having a 1080x1080 images is a big problem. Doesn't Fresco resize images after loading them? It shouldn't lag like that if so, I think. 

Thanks for your help.

**Comment by chenjyr** [comment]
>I think the problem relies behind your third question. Having a 1080x1080 images is a big problem. >Doesn't Fresco resize images after loading them? It shouldn't lag like that if so, I think.

This is definitely the problem from my experience, and no it doesn't – you have to specify it using `ResizeOptions`. See http://frescolib.org/docs/resizing-rotating.html

**Comment by erikandre** [comment]
Closing as a solution has been provided. Automatic resizing might be implemented in the future but for now using ResizeOptions is the way to go
