### ISSUE TITLE
GridView images blink

### ISSUE THREAD

**Issue by fxhereng** [facebook/fresco#1519]
Hi everyone,

This might be a duplicate problem but I didn't find any solution to it, I have a grid view displaying images from the gallery. When I select an image, `notifyDataSetChanged()` gets called and makes the images blink. Sometimes various, sometimes just one or two, it's not happening in any case.

![device-2016-10-31-102902](https://cloud.githubusercontent.com/assets/5686128/19850035/98f7947a-9f56-11e6-893a-43344d6b9d74.gif)

I'm using a view holder with tag and load them like this:
```java
if (mItemSize > 0) {
                Uri uri = Uri.parse("file://" + data.path);
                ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                        .setResizeOptions(new ResizeOptions(mItemSize, mItemSize))
                        .setAutoRotateEnabled(true)
                        .build();

                PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                        .setOldController(frescoImage.getController())
                        .setImageRequest(request)
                        .build();
                frescoImage.setController(controller);
            }
```

I'm using fresco:**0.13.0**

I tried to clear cache when exiting activity, (don't know if it's good practice or not):

```java
 @Override
    public void onDestroyView() {
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        imagePipeline.clearCaches();
        super.onDestroyView();
    }
```
but the problem still occurs.

What am I doing wrong?

Thanks for your help

**Comment by kirwan** [comment]
Each time you call `notifyDataSetChanged()`, all the images will be re-requested. Bitmaps which are held in the memory cache should be reloaded immediately (so won't blink) but any that aren't will be reloaded in a background thread then faded in.

As your screen shows a grid of local photos which I suspect are much larger than they're shown, that could explain why as soon as the old bitmaps are closed, some are likely to be immediately evicted from cache.

I don't know how easy this would be for you, but I'd recommend using the `RecyclerView` if you're not already and report changes to the dataset more specifically than the general `notifyDataSetChanged()` which throws away everything and rebuilds all views, whether or not each of them needs it.

**Comment by fxhereng** [comment]
Thanks for your support, it's not a recyclerView indeed but I can give a try with it, maybe using `notifyItemChanged(int)` instead of `notifyDataSetChanged()` will solve it.

**Comment by kirwan** [comment]
Yes, just updating the individual items could help a lot.

I'm going to close this issue but feel free to comment if you have another question and I can reopen it.

**Comment by fxhereng** [comment]
Eventually I did it like you said, updating individual items, it's working well. Though when cache is full it only reloads the one I clicked.

Thanks!
