### ISSUE TITLE
Inspect SimpleDraweeView

### ISSUE THREAD

**Issue by benoitdion** [facebook/fresco#1521]
In some of our tests we'd like to verify the content of a SimpleDraweeView. For example:
 - Assert image url set on a drawee
 - Check the drawable currently displayed (placeholder, progress, success or failure) 

Any recommendation in that area or best practice around testing image loading with Fresco?

**Comment by eldk** [comment]
Hello,

You should have a look here : http://frescolib.org/docs/troubleshooting.html (Setting up logcat)

And here if you want to set a listener on draweeView : http://frescolib.org/docs/listening-download-events.html

Eric
