### ISSUE TITLE
DiskCache invalid after long time

### ISSUE THREAD

**Issue by shidongdi** [facebook/fresco#1522]
I call prefetchToDiskCache to cache a picture,
and a few hours later 
ImagePipelineFactory.getInstance() .getMainFileCache().hasKey(cacheKey) return false;

How can I indefinitely cache the image to disk?

**Comment by eldk** [comment]
Hello,

Have you check response headers from your picture server : 

>Cache-Control: max-age=31098734
Connection: Keep-Alive
Content-Length: 181095
Content-Type: image/jpeg
Date: Tue, 01 Nov 2016 11:24:17 GMT
Expires: Fri, 27 Oct 2017 09:56:31 GMT 

max-age .... ?

Thanks,

Eric

**Comment by shidongdi** [comment]
Thanks for your reply!
the response headers is:
HTTP/1.1 200 OK
Date: Wed, 02 Nov 2016 04:36:33 GMT
Server: nginx
Content-Type: image/jpeg
Content-Length: 446788
Last-Modified: Fri, 28 Oct 2016 02:14:17 GMT
ETag: "5812b479-6d144"
Expires: Fri, 02 Dec 2016 04:36:32 GMT
Cache-Control: max-age=2592000
Accept-Ranges: bytes
X-Via: 1.1 oudxin56:7 (Cdn Cache Server V2.0)
Connection: keep-alive

**Comment by eldk** [comment]
Hello,

I think there is no concern in headers. 
Should you check if image is in cache like this :

`private boolean isImageDownloaded(Uri pictureUri) {`
`        if (pictureUri == null) {`
`            return false;`
`        }`
`        CacheKey cacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(ImageRequest.fromUri(pictureUri), this);`
       ` return ImagePipelineFactory.getInstance().getMainFileCache().hasKey(cacheKey) || ImagePipelineFactory.getInstance().getSmallImageFileCache().hasKey(cacheKey);`
   
` }`

and give détail as @massimocarli asked : 
- Fresco version
- picture uri
 ....

Thanks,

Eric

**Comment by shidongdi** [comment]
Thanks.
I used to use getSmallImageFileCache and getMainFileCache,it Does not work.

- Fresco version : 0.14.1
- url:http://stc.zjol.com.cn/g1/M000A40CggSDVgNtYWALd_UAAbRRC_bkRE541.jpg_r1080x1812q100.webp?width=720&height=1280

**Comment by eldk** [comment]
Hello,

Could you check if "DiskCache invalid after long time" occures with a simplified url, for example http://domain.tld/name.jpg  with the same picture, + another one?

Thanks,

Eric
