### ISSUE TITLE
hierarchy.setPlaceholderImage(null) not working since 0.14

### ISSUE THREAD

**Issue by ekzee** [facebook/fresco#1523]
Hello!
At first I have only low resolution image and loading it with my placeholder drawable
```
hierarchy.setPlaceholderImage(photoLoadingDrawable);
imageView.setImageURI(lowResUrl);
```
Next, I fetch high resolution image url from API and if low resolution image is already in cache, I show low resolution image as a preview while high resolution image is loading. There placeholder is set to null and low resolution image is acting as a placeholder.
```
hierarchy.setPlaceholderImage(null);
DraweeController controller = Fresco.newDraweeControllerBuilder()
		.setLowResImageRequest(ImageRequest.fromUri(lowResUrl))
		.setImageRequest(ImageRequest.fromUri(highResUrl))
		.setOldController(imageView.getController())
		.build();
imageView.setController(controller);
```

When I upgrade from 0.13 to 0.14 (both 0.14.0 and 0.14.1) this solution breaks. I see low resolution image first, then when I get high resolution image url I see placeholder and then high res image.

**Comment by foghina** [comment]
I can't repro this on master:

https://gfycat.com/PleasedAgileKudu

The code I used:

```java
mSimpleDraweeView.getHierarchy().setPlaceholderImage(R.mipmap.ic_launcher);
mSimpleDraweeView.setImageURI("http://i.imgur.com/0fYW56sb.jpg");

new Handler().postDelayed(
    new Runnable() {
      @Override
      public void run() {
        mSimpleDraweeView.getHierarchy().setPlaceholderImage(null);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
            .setLowResImageRequest(ImageRequest.fromUri("http://i.imgur.com/0fYW56sb.jpg"))
            .setImageRequest(ImageRequest.fromUri("http://i.imgur.com/0fYW56s.jpg"))
            .setOldController(mSimpleDraweeView.getController())
            .build();
        mSimpleDraweeView.setController(controller);
      }
    },
    3000);
```

Closing the issue for now. Feel free to reopen if you have a valid repro (e.g. sample app).
