### ISSUE TITLE
I have a problem about loading GIF.The url is http://image.zzd.sm.cn/1721434009114212362.gif?id=0

### ISSUE THREAD

**Issue by yangbo637829** [facebook/fresco#1524]
I have a problem about loading GIF.The url is http://image.zzd.sm.cn/1721434009114212362.gif?id=0.
Fresco loaded success,but can't play it .This problem is just for the specific url.

**Comment by massimocarli** [comment]
Thanks @yangbo637829,
we'll try this image and see what's happening.
