### ISSUE TITLE
the image has rough edge 

### ISSUE THREAD

**Issue by sungerk** [facebook/fresco#1525]
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/imageview_user_header_image"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_below="@+id/imageview_user_skin"
        android:layout_centerHorizontal="true"
        android:layout_marginLeft="15dp"
        android:layout_marginTop="-50dp"
        fresco:placeholderImage="@mipmap/ico_peron_non"
        fresco:roundWithOverlayColor="@color/white"
        fresco:roundedCornerRadius="5dp"
        fresco:roundingBorderColor="@color/white"
        fresco:roundingBorderWidth="3dp" />

![qq 20161101190205](https://cloud.githubusercontent.com/assets/7720072/19887920/68ef306a-a066-11e6-89d7-6baba5b8ec2a.png)

**Comment by oprisnik** [comment]
Unfortunately this is a known issue. See #1399 for more information.

**Comment by s1rius** [comment]
Set a roundingBorderPadding can fix this.
@sungerk Please try add `fresco:roundingBorderPadding="${the border width}"` in xml.

**Comment by sungerk** [comment]
@s1rius Thank you,this is correct
