### ISSUE TITLE
[Question] Is it necessary to call bitmap.recycle()?

### ISSUE THREAD

**Issue by huyduongtu** [facebook/fresco#1526]
As fresco lib 's instructions, after decoding and pushing the bitmap into Ashmem, we call pinBitmap to prevent it from reclaiming by the system. After the bitmap isn't used anymore, we recycle it by calling bitmap.recycle() to unpin it.

But I tried not calling bitmap recycle in both of my application and fresco sample. Bitmaps are still recycled by Garbage Collector. The bitmaps are not leaked in memory.
So is it necessary to call bitmap.recycle()? Thanks in advance.

**Comment by oprisnik** [comment]
No, you don't have to recycle the bitmaps if you use Fresco correctly. How do you get the Bitmaps?

**Comment by huyduongtu** [comment]
Sorry for my unclear questions. So that you get me wrong. 
I see in the fresco library, It calls bitmap.recycle() to unpin the bitmap from Ashmem when the bitmap is not used anymore. I try not calling bitmap.recycle() in fresco library (remove the code calling bitmap.recycle()). It's still working. The bitmap is still recycled by Garbage Collector. The bitmaps are not leaked in memory.

So that I wonder Is it necessary to call bitmap.recycle()?

**Comment by oprisnik** [comment]
Manually recycling the bitmap is more efficient since we're not sure when the next GC run will be.
 
From the [Android documentation for memory](https://developer.android.com/training/displaying-bitmaps/manage-memory.html):
> On Android 2.3.3 (API level 10) and lower, using recycle() is recommended. If you're displaying large amounts of bitmap data in your app, you're likely to run into OutOfMemoryError errors. The recycle() method allows an app to reclaim memory as soon as possible.


On some Android versions we also use bitmap pools where the bitmaps are not recycled immediately but re-used instead.
