### ISSUE TITLE
Why react-native use fresco_0.11.0?

### ISSUE THREAD

**Issue by benzly** [facebook/fresco#1527]
Can't i replace to fresco_0.14.0？  Looking forward to your reply!!!!

**Comment by massimocarli** [comment]
Hi @benzly ,
at the moment RN support only 0.11 because of the compatibility library version. Do you have any special feature of the 0.14?
Thanks

**Comment by benzly** [comment]
Hi, @massimocarli 
No special feature，only we need build fresco jar with fresco source.
and i find it(fresco_0.14.0) to work with RN.

**Comment by oprisnik** [comment]
React native is using a newer version now.
