### ISSUE TITLE
getEncodedCountingMemoryCache()

### ISSUE THREAD

**Issue by benzly** [facebook/fresco#1530]
why Fresco.getImagePipelineFactory().getEncodedCountingMemoryCache().getSizeInBytes() return 0 
always? 

Looking forward to your reply.

**Comment by massimocarli** [comment]
Hi @benzly 
when are you invoking that method? 

Thanks

**Comment by benzly** [comment]
Hi @massimocarli 
I invking it different moments.  before request, requesting, after requesting, and request the new urls；

`    public static void dumpAllInfo() {
        Fresco.getImagePipelineFactory().getMainFileCache().trimToMinimum();

        StringBuilder sb = new StringBuilder();
        sb.append("Cache info: \n");
        sb.append("#######################################\n");
        sb.append("[memory]-> decode=" + getAllMemoryDecodeSize() + " inUse=" + getAllMemoryDecodeInUseSize());
        sb.append("\n");
        sb.append("[memory]-> unDecode=" + getAllMemoryUnDecodeSize() + " inUse=" + getAllMemoryUnDecodeInUseSize());
        sb.append("\n");
        sb.append("[disk]  -> count=" + getAllDiskCacheCount() + " size=" + getAllDiskCacheSize());
        sb.append("\n#######################################");
        mLogger.d(sb.toString());
    }`

Looking forward to your reply.

**Comment by oprisnik** [comment]
I just verified that the following code will properly output the memory cache size:

`    Log.d(TAG, "size=${Fresco.getImagePipelineFactory().getEncodedCountingMemoryCache().getSizeInBytes()}")
`
