### ISSUE TITLE
why my onBitmapCacheHit is low?

### ISSUE THREAD

**Issue by shixiangyu** [facebook/fresco#1531]
please help ，why my onBitmapCacheHit is low?
 
My code：

private void initFresco(Context context) {
        ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)
                .setImageCacheStatsTracker(new ImageCacheTracker())
                .setDownsampleEnabled(true)
                .setDecodeMemoryFileEnabled(true)
                .build();
        Fresco.initialize(context,config );
    }

**Comment by shixiangyu** [comment]
![0jhpm5nw4u2mz4r o fn](https://cloud.githubusercontent.com/assets/18461582/20003197/35aeaddc-a2c0-11e6-8b79-af173b4f767f.png)

**Comment by massimocarli** [comment]
Hi @shixiangyu 
you question is too generic. Can you provide more context please?
Thanks

**Comment by shixiangyu** [comment]
Hi @massimocarli 
Thanks very much,but i don't know  how to describe the question. BitmapCache is used very low,cause to load the picture is  slow.

**Comment by oprisnik** [comment]
We would need more details please, including information on how to reproduce your issue. Please let us know if this is still an issue.
