### ISSUE TITLE
.setDownsampleEnabled(true) then resize don't work for webp

### ISSUE THREAD

**Issue by shixiangyu** [facebook/fresco#1533]

**Comment by eldk** [comment]
Hello,

I think @massimocarli solve it here : https://github.com/facebook/fresco/commit/474f62af906341026943efeabf64a32516d1b2fe.

Will it be in the next release ?

Eric

**Comment by shixiangyu** [comment]
@eldk,

Thanks,hope it be in the next release!

**Comment by shixiangyu** [comment]
@eldk 
  My problem is that my app are mostly webp format pictures, but also the big picture, cause the memory cache is full, and I should be how to solve?

**Comment by shixiangyu** [comment]
@eldk ,
Hi,
My problem is that my app are mostly webp format pictures, but also the big picture, cause the memory cache is full, and I should be how to solve?

**Comment by eldk** [comment]
Hello,

Are you speaking of diskCache (3. Disk cache http://frescolib.org/docs/caching.html) or (1. Bitmap cache) ?

Eric

**Comment by shixiangyu** [comment]
Hello,
it's bitmap cache,thanks

**Comment by eldk** [comment]
Hello,

If it's bitmap cache, you should : 
- reduce the size of WebP downloaded files (downsample before download them)
- use only jpg files
or
- use the master Fresco repository to build library yourself

If none is convenient, the best is to wait the next release.

Thanks,

Eric

**Comment by erikandre** [comment]
Closing as this is a duplicate of #743
