### ISSUE TITLE
UnsatisfiedLinkError for arm64-v8a (split apk)

### ISSUE THREAD

**Issue by wiradikusuma** [facebook/fresco#1535]
I'm using split apk:

	splits {
		abi {
			...
			include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
		}
		density {
			...
		}
	}

but I encounter this exception only for **arm64-v8a**:

	Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.bla-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libimagepipeline.so"
		   at java.lang.Runtime.loadLibrary(Runtime.java:367)
		   at java.lang.System.loadLibrary(System.java:988)
		   at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SourceFile:32)
		   at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SourceFile:56)
		   at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(SourceFile:43)

even though the resulting apk contains `lib/arm64-v8a/libimagepipeline.so`.

**NOTE:** This error is reported by Crashlytics, I don't have compatible device to test myself. Affected devices are OPPO **R831K** and **A33w**, Samsung **SM-J110G** and SPC **S5**, with Android version **4.4.2** (47%), **4.2.2** (47%) and **4.4.4** (6%).

**Comment by kirwan** [comment]
I suggest trying the [solution here to use the ReLinker library](https://github.com/facebook/fresco/issues/933#issuecomment-186266187). We've found that's helped people in the past with this kind of problem.

You can use the same technique with Facebook's full [SoLoader](https://github.com/facebook/SoLoader) library.

Please let me know if that helps.

**Comment by wiradikusuma** [comment]
Thanks, seems to be working now.
