### ISSUE TITLE
ImageInfo Incorrect for Rotated Images

### ISSUE THREAD

**Issue by sushiisumii** [facebook/fresco#1536]
When auto-rotate is enabled, it seems that the `ImageInfo` returned in the `ControllerListener.onFinalImageSet` is wrong for images that were rotated.

Namely if I have a 50x100 image with rotation 90, Fresco will auto-rotate this as 100x50 and display the image as wide, but the ImageInfo will report the image as having 50x100.

```
        ControllerListener<ImageInfo> listener = new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, @Nullable ImageInfo imageInfo, @Nullable Animatable animatable) {
                int width = imageInfo.getWidth(); // Reports 50
                int height = imageInfo.getHeight(); // Reports 100
            }
        };

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setControllerListener(listener)
                .build();
        draweeView.setController(controller);

```

Is this intended? If it is, is there a way to detect if a rotation occurred? 

I am trying to have images loaded in that are full width but variable height with the image's intended aspect ratio as described in this [SO post](http://stackoverflow.com/questions/33955510/facebook-fresco-using-wrap-conent/34075281#34075281).

**Comment by oprisnik** [comment]
What version of Fresco are you using? Does this still happen with v14.0.1? I think that @kirwan has been working on this in recent releases and it should work.

**Comment by sushiisumii** [comment]
Yea @oprisnik that's still happening with v14.0.1. I updated yesterday to check and seems like that's still the case.

**Comment by sushiisumii** [comment]
Not sure if this is helpful or not, but I found a scenario in which the returned ImageInfo is actually corrected. 

```

        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        DataSource<CloseableReference<CloseableImage>>
                dataSource = imagePipeline.fetchDecodedImage(imageRequest, getContext());

        DataSubscriber<CloseableReference<CloseableImage>> dataSubscriber =
                new BaseDataSubscriber<CloseableReference<CloseableImage>>() {
                    @Override
                    protected void onNewResultImpl(
                            DataSource<CloseableReference<CloseableImage>> dataSource) {
                        if (!dataSource.isFinished()) {
                            return;
                        }
                        CloseableReference<CloseableImage> ref = dataSource.getResult();
                        if (ref != null) {
                            try {
                                CloseableImage imageResult = ref.get();
                                Log.d(TAG, "subscriber image width: " + imageResult.getWidth() + 
                                 " height: " + imageResult.getHeight());
                                // Somehow the CloseableImage and the ImageInfo returned in 
                                // the ControllerListener are now correct width and height values.
                            } finally {
                                CloseableReference.closeSafely(ref);
                            }
                        }
                    }

                    @Override
                    protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                        // Do nothing
                    }
                };

        dataSource.subscribe(dataSubscriber, executor);
```

I have no idea why adding a DataSubscriber affects the ControllerListener results, but the CloseableImage reference and the ImageInfo passed through the ControllerListener are corrected for images auto-rotated. 

This seems to be a reasonable workaround for me for now.

**Comment by kirwan** [comment]
OK, I see the difference here which highlights the cause of the bug.

When you use `Fresco.newDraweeControllerBuilder().setUri(String)` an `ImageRequest` is created internally which requests for the rotation to be deferred until render time as drawee handles this for us.

When you create an `ImageRequest` directly in `ImageRequest.fromUri(String)` the default `RotationOptions` are used which results in the image being rotated within the image pipeline.

So, the bitmap which the `DraweeController` receives is actually different to the one the `DataSubscriber` gets. They are both rendered the same though of course and are both perceived the same so they clearly should receive the same info.

This may involve just a simple fix to `CloseableStaticBitmap` but that might have side-effects so we'll need to check on that.

I'm glad you have a fix for now but we'll aim to fix this before our next open source release.
