### ISSUE TITLE
How can I track the ImageRequest downloadTime,decodeTime,totalTimeCost?  label:question

### ISSUE THREAD

**Issue by MoonRune** [facebook/fresco#1537]
I want to make  statistics of image-request time cost. But only find cacheTrack . I want to know how to get each image-request's download-time-cost 、total-time-cost and so on.

**Comment by kirwan** [comment]
Have you looked at creating a `ProducerListener`? That allows you to get some more specific feedback from particular producers in the pipeline and it might help provide the details you're interested in.
