### ISSUE TITLE
Error:Execution failed for task ':sample:processDebugResources'.

### ISSUE THREAD

**Issue by MartinMu2016** [facebook/fresco#154]
Error:Execution failed for task ':sample:processDebugResources'.

> Error: more than one library with package name 'com.facebook.drawee.backends.pipeline'
> You can temporarily disable this error with android.enforceUniquePackageName=false
> However, this is temporary and will be enforced in 1.0

**Comment by tyronen** [comment]
Does this persist after running a 'gradlew clean' ?

**Comment by tyronen** [comment]
Respond if it does.

**Comment by erikandre** [comment]
Closing as there has been no response for 2 years
