### ISSUE TITLE
gif item in RecyclerView,help

### ISSUE THREAD

**Issue by asker517** [facebook/fresco#1540]
So powerful library , but as gif item in recyclerview ,it performances bad .issue like #954 

when I cost time loading gif image then playing everything is ok ,but when I scroll the gif item out of screen ..then scroll in ..it still cost much time to playing normal . during this period placeholder image will display long time . it seems gif not cache ..just load remote everytime ..when gif image size is small ,it's accepted , however when gif size is bigger, it's really a boring phenomenon. help needed.

**Comment by lambdapioneer** [comment]
Hi @asker517, depending on the circumstances, this might be a real limitation. Decoded GIF images take up a lot of memory and therefore their frames are not cached as done for static images. However, the encoded version (i.e. the GIF file) should still be in the encoded memory cache and disk cache.

We are currently reconsidering our animation implementation and chances are that it might work better in this use-case.

**Comment by asker517** [comment]
@lambdapioneer thanks for you reply & your team hardwoking. Looking forward its better performance in this circumstance. I just found many users trapped here. thanks again.
