### ISSUE TITLE
Use Animated WebP with Proguard, build failed.

### ISSUE THREAD

**Issue by androidbyxj** [facebook/fresco#1546]
compile(name:'animated-base-0.14.1', ext:'aar')
    compile(name:'animated-webp-0.14.1', ext:'aar')
    compile(name:'fbcore-0.14.1', ext:'aar')
    compile(name:'imagepipeline-0.14.1', ext:'aar')
    compile(name:'imagepipeline-base-0.14.1', ext:'aar')
    compile(name:'webpsupport-0.14.1', ext:'aar')

-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip
# Do notstrip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
   @com.facebook.common.internal.DoNotStrip *;
}
# Keepnative methods
-keepclassmembers class * {
    native <methods>;
}
-keep class com.facebook.** {*;
}
-dontwarn javax.annotation.**

This is my own configuration information,but always prompt BUILD FAILED.Hope to get help,Thanks

**Comment by lambdapioneer** [comment]
Hi @androidbyxj, have you followed the instruction on http://frescolib.org/docs/proguard.html ?

**Comment by oprisnik** [comment]
I assume the problem has been resolved. Please let us know if you're still experiencing this issue.
