### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed.

### ISSUE THREAD

**Issue by desmond1121** [facebook/fresco#1547]
Recently, we've encountered several strange problems in `System.loadLibrary()`, it crashed in `dlopen` with several different msg, they are:

1. Bad file number

```
java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app-lib/tv.danmaku.bili-2/libimagepipeline.so" phdr mmap failed: Bad file number
```

2. Has no loadable segemnts

```
java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app-lib/tv.danmaku.bili-1/libimagepipeline.so" has no loadable segments
```

3. Invalid argument

```
java.lang.UnsatisfiedLinkError
Cannot load library: load_library(linker.cpp:785): can't load program header table: /data/app-lib/tv.danmaku.bili-2/libimagepipeline.so: Invalid argument
```

4. Bad ELF magic

```
java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/tv.danmaku.bili-1/lib/arm/libimagepipeline.so" has bad ELF magic
```

We have many other native lib but the problem seems only occur in Fresco's so(It seems only happend in `libimagepipeline.so` and `libmemtrunk.so`). It cannot be reproduced and we know the crash in our crash system.

===
**Fresco version**: 0.11.0
**Android system distribution**:
4.4.4(API 19) => 39.85%
4.3(API 18) => 19.13%
4.4.2(API 19) => 11.99%
5.1.1(API 22) => 11.06%
4.2.2(API 17) => 6.49%
**Manufacturer**:
Most in XIAOMI and VIVO

**Comment by lambdapioneer** [comment]
Hi @desmond1121, thanks for this opening this issue.

Do you by any chance have a local repro and can provide us with the logcat from the app start up to this issue? I'm inclined to say that this related to the specific models. Also, is this a one-off issue for those devices or is it happening on every start?

**Comment by desmond1121** [comment]
@lambdapioneer Sorry for late response, I've use something like `SoLoaderShim` in Fresco. But we cannot reproduce the crash. Yes it's related to specific model and it seems that every device just happen once or twice.

**Comment by droidwolf** [comment]
+1[issues/1747](https://github.com/facebook/fresco/issues/1747)

**Comment by oprisnik** [comment]
SoLoader will be the default with the next release, see aef3790d3429833599d8b5529602e2c12f18c8aa
