### ISSUE TITLE
Slow loading from MediaStore ContentProvider

### ISSUE THREAD

**Issue by xiaohuhu** [facebook/fresco#155]
I have changed th ListView to GridView  and the network image to local,in the demo.

![1](https://cloud.githubusercontent.com/assets/7322048/7179465/ac58a0fc-e46a-11e4-91e9-a8fe0d978c48.png)
![2](https://cloud.githubusercontent.com/assets/7322048/7179464/ac572f9c-e46a-11e4-8f4d-bc97b16f793b.png)
![screenshot_2015-04-16-18-50-06](https://cloud.githubusercontent.com/assets/7322048/7179462/ac560f90-e46a-11e4-8b8d-7fc7295f3873.png)
![screenshot_2015-04-16-18-51-49](https://cloud.githubusercontent.com/assets/7322048/7179463/ac56a1da-e46a-11e4-90f2-5b24b566f1f7.png)

It is not smooth-scrolling while using fresco,and the memory footprint is  larger than others, I think I must have done something wrong.

**Comment by tyronen** [comment]
Can you send us a pull request of the changes you made to the sample app? This will be helpful in debugging.

**Comment by xiaohuhu** [comment]
@tyronen  I change the method (**Line Num 275**)
 ```android
   private void updateAdapter(List<String> urls) {
    if (mCurrentAdapter != null) {
      mCurrentAdapter.clear();
      if (urls != null) {
        for (String url : urls) {
          mCurrentAdapter.add(url);
        }
      }
      mCurrentAdapter.notifyDataSetChanged();
    }
  }
```
to
 ```android
  private void updateAdapter(List<String> urls) {
    //use the local pic
    urls = new ArrayList<>();
    try {
      final String[] columns = { MediaStore.Images.Media.DATA,
              MediaStore.Images.Media._ID };
      final String orderBy = MediaStore.Images.Media._ID + " DESC";

      Cursor imagecursor = getContentResolver().query(
              MediaStore.Images.Media.EXTERNAL_CONTENT_URI, columns,
              null, null, orderBy);

      if (imagecursor != null && imagecursor.getCount() > 0) {

        while (imagecursor.moveToNext()) {

          int dataColumnIndex = imagecursor
                  .getColumnIndex(MediaStore.Images.Media.DATA);
          String a = imagecursor.getString(dataColumnIndex);
          urls.add(a);
        }
        imagecursor.close();
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
    if (mCurrentAdapter != null) {
      mCurrentAdapter.clear();
      if (urls != null) {
        for (String url : urls) {
          mCurrentAdapter.add("file://"+ url);
        }
      }
      mCurrentAdapter.notifyDataSetChanged();
    }
  }
```

and in the xml **activity_main.xml**
 ```android
<ListView
      android:id="@+id/image_list"
      android:layout_width="wrap_content"
      android:layout_height="0dp"
      android:layout_weight="1"
      />
 ```
to
 ```android
 <GridView
      android:numColumns="3"
      android:id="@+id/image_list"
      android:layout_width="wrap_content"
      android:layout_height="0dp"
      android:layout_weight="1"
      />
 ```

**Comment by rockerhieu** [comment]
I think I got the same problem. My app has a gallery picker screen, and when using Fresco 0.4.0 to view the photos, it's very easy to get crash:
```
Fatal Exception: java.lang.IllegalStateException
Process 1011 exceeded cursor quota 100, will kill it
raw
android.os.Parcel.readException (Parcel.java:1473)
android.provider.MediaStore$Images$Media.query (MediaStore.java:789)
com.company.widget.gallery.ImageList.createCursor (ImageList.java:82)
```

The app works fine with Fresco 0.1.0. It looks like Fresco consume too much memory when loading local photos.

**Comment by tyronen** [comment]
We have made improvements in 0.6.0.

**Comment by droidekas** [comment]
I seem to be facing the issue in 0.6.0 with low disk space phones(~500 mb left). Can you tell me what changed?I could not figure it out from the changelogs
