### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by qiiyue** [facebook/fresco#1552]
java.lang.UnsatisfiedLinkError: No implementation found for void com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeFree(long) (tried Java_com_facebook_imagepipeline_memory_NativeMemoryChunk_nativeFree and Java_com_facebook_imagepipeline_memory_NativeMemoryChunk_nativeFree__J)
at com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeFre[  212.360000] ioctl: u8bSigstate = 1
e(Native Method)
at com.facebook.imagepipeline.memory.NativeMemoryChunk.close(NativeMemoryChunk.java:75)
at com.facebook.imagepipeline.memory.NativeMemoryChunk.finalize(NativeMemoryChunk.java:243)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
at java.lang.Thread.run(Thread.java:818)

this issue had discovery in 2 android-tv, all of them is api23. it is still cannot load image when restart app.

**Comment by kirwan** [comment]
I suggest trying the [solution here to use the ReLinker library](https://github.com/facebook/fresco/issues/933#issuecomment-186266187). We've found that's helped people in the past with this kind of problem.

You can use the same technique with Facebook's full [SoLoader](https://github.com/facebook/SoLoader) library.

Please let me know if that helps.

**Comment by lanxin1995** [comment]
What are the advantages of SoLoader library compared to your library?

**Comment by LucianWang** [comment]
The device is currently experiencing this situation is some smart TV (Android6.0), in the simulator Android6.0 did not find this situation. I view library SoLoader just to support the Android 4.3. Is there any other way to solve or prevent it?

**Comment by LucianWang** [comment]
The device is currently experiencing this situation is some smart TV (Android6.0), in the simulator Android6.0 did not find this situation. I view SoLoader library  just to support the Android 4.3. Is there any other way to solve or prevent it?

**Comment by LucianWang** [comment]
The device is currently experiencing this situation is some smart TV (Android6.0), in the simulator Android6.0 did not find this situation. I view SoLoader library just to support the Android 4.3. Is there any other way to solve or prevent it?
this id log : W/NativeMemoryChunk( 6186): finalize: Chunk c1f90e4 still active. Underlying address = 0

**Comment by LucianWang** [comment]
The device is currently experiencing this situation is some smart TV (Android6.0), in the simulator Android6.0 did not find this situation. I view SoLoader library just to support the Android 4.3. Is there any other way to solve or prevent it?
this is log : W/NativeMemoryChunk( 6186): finalize: Chunk c1f90e4 still active. Underlying address = 0

**Comment by kirwan** [comment]
We use SoLoader but it was open-sourced later than Fresco so isn't part of the library.

SoLoader adds greater reliability than the default behaviour which just tries once to call `System.loadLibrary(String)`.

The failures we tend to see occur somewhat randomly and rarely so I'm not surprised you haven't seen them in your own tests.

**Comment by LucianWang** [comment]
Thank you very much!My problem has been solved.
