### ISSUE TITLE
how to refresh a drawee with a same uri but not the same image acturally

### ISSUE THREAD

**Issue by shuifengYu** [facebook/fresco#1553]
for example :at first  i did :draweeAvatar.setImageURI("avatar.jpg");
then i updated the 'avatar.jpg' to another picture but still named 'avatar.jpg',when i call the method ：draweeAvatar.setImageURI("avatar.jpg"); it would not update,how can i update the bitmap in the draweeAvatar

**Comment by kirwan** [comment]
There are obviously parts of the image pipeline that make the assumption that a URL will always point to the same resource.

If this isn't possible for you, there are a couple of alternatives that come quickly to mind.

1. Add a cache-busting query parameter (e.g. `avatar.jpg?c=2` where the previous version was 1)
2. Call `draweeAvatar.setImageURI(null)` then `ImagePipeline.evictFromCache(Uri)` before setting the same Uri back to the avatar.

**Comment by kirwan** [comment]
I'm closing as there have been no follow-up questions.
