### ISSUE TITLE
Add    fresco:0.14.1 Error 

### ISSUE THREAD

**Issue by ZhetengDashen** [facebook/fresco#1555]
Error LOG:

 java.lang.NoSuchMethodError: No static method setOnApplyWindowInsetsListener(Landroid/view/View;Landroid/support/v4/view/OnApplyWindowInsetsListener;)V in class Landroid/support/v4/view/ViewCompatLollipop; or its super classes (declaration of 'android.support.v4.view.ViewCompatLollipop' appears in /data/data/basedemo.wang.com.ztdemo/files/instant-run/dex/slice-internal_impl-24.2.1_bfca4b8d70d59a19478bbd1357f144335c733e34-classes.dex)

**Comment by desmond1121** [comment]
@ZhetengDashen It seems a bug of instant-run, can you reproduce it after disable instant-run?

**Comment by ZhetengDashen** [comment]
I restart the Android Studio、Clean Project. Will appear the same mistake.

**Comment by kirwan** [comment]
Fresco depends on version 24.2.1 of the support library. Do you depend on a different version which might be clashing?

I would expect something like that to result in a build-time error rather than runtime though.

**Comment by ZhetengDashen** [comment]
Thank you very much .  Change to  compile 'com.android.support:appcompat-v7:24.2.1'   successful.

**Comment by kirwan** [comment]
Glad that helped. Our next release should remove any more issues like this.
