### ISSUE TITLE
Is there a way to exclude the native part?

### ISSUE THREAD

**Issue by hqzxzwb** [facebook/fresco#1556]
I am developing app running only on devices whose sdk > 21. The ashmem cache seems not availabe to me. If the .so files are only for ashmem purposes, they are a size waste for me. Can I exclude that part in some way? Or should I just remove the .so files and assume it won't crash?

**Comment by massimocarli** [comment]
Hi @hqzxzwb ,
The [ImagePipelineNativeLoader](https://github.com/facebook/fresco/blob/84aeab6895f3177cee473e85656cf898112f263f/imagepipeline/src/main/java/com/facebook/imagepipeline/nativecode/ImagePipelineNativeLoader.java#L43) class is responsible for loading the memchunk native library which is necessary for Fresco. We're not using native code just for decoding so at the moment what you need is not possible. Anyway we'll consider to allow the usage of Fresco also in newest Android releases without the unnecessary .SOs.
