### ISSUE TITLE
How can I load tall images?

### ISSUE THREAD

**Issue by wangguifa** [facebook/fresco#1557]
I want to load a long graph，There are about three mobile phone screen so long，What should i do？Thank you

**Comment by massimocarli** [comment]
Hi @wangguifa 
can you provide more information please?
Thanks

**Comment by wangguifa** [comment]
For example，The size of the image is 352px*1920px，I can not load this image.because it is too long.if
the size is 352px * 352px, it can load.What should i do？Thank you

**Comment by wangguifa** [comment]
For example，The size of the image is 352px*1920px，I can not load this image.because it is too long.if
the size is 352px * 352px, it can load.What should i do？Thank you

**Comment by wangguifa** [comment]
For example，The size of the image is 352px*1920px，I can not load this image.because it is too long.if
the size is 352px * 352px, it can load.What should i do？Thank you @massimocarli

**Comment by massimocarli** [comment]
Hi @wangguifa 
if you can control the Bitmap I suggest to tile it and basically divide it into smaller part. 
Thanks

**Comment by oprisnik** [comment]
A 352 x 1920px image should still be OK for most devices. Do you get an exception? Does the image not show up?
As suggested by @massimocarli , splitting the image up would work. There's also a discussion for an alternative solution going on in #4

**Comment by erikandre** [comment]
Closing as we cannot proceed without more information
