### ISSUE TITLE
Intercept request to change image URL

### ISSUE THREAD

**Issue by sourabhv** [facebook/fresco#1559]
Is there a way to intercept Fresco's request to change URL and set a thumb size in it. I used OkHttp's default NetworkFetcher and I can change the URL in `fetch` method but I need view's size there for it, which is not available. I was looking for something like `GlideModule`, something like [this](https://github.com/ewintory/udacity-popular-movies/blob/52c95eaddd75632564012af459a9330ee84ddb4a/app/src/main/java/com/ewintory/udacity/popularmovies/data/GlideSetup.java#L59)

**Comment by massimocarli** [comment]
Ho @sourabhv 
Fresco itself doesn't allow to intercept the Uri of the image and change it. This is also because we use the Uri also for the Cachekey. You could use what OkHttp offers but keeping in mind the cache implications.

**Comment by oprisnik** [comment]
Another problem is that we do not necessarily know the size of the view yet. You could prefetch an image or use the image pipeline manually.
We currently don't have a simple way of changing this behavior I'm afraid.

I guess you could manually get the size of the view before calling the image pipeline and supply resize options with these dimensions and then access the resize options?

**Comment by erikandre** [comment]
Closing as this is not practical to implement in Fresco.
