### ISSUE TITLE
Fetch bitmap from DraweeView

### ISSUE THREAD

**Issue by adnan-SM** [facebook/fresco#156]
So I am trying to work with the new Palette API which requires me to pass in a bitmap object to it. Is there any way I can retrieve the bitmap object from the SimpleDraweeView ?  I have tried the following without any success : 

1st Attempt - 
```  
        Uri uri = Uri.parse(imagePath);

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setLowResImageRequest(ImageRequest.fromUri(shot.getImages().getTeaser()))
                .setImageRequest(ImageRequest.fromUri(uri))
                .setAutoPlayAnimations(Constants.shouldAnimateGifs)
                .setOldController(detailImageView.getController())
                .build();
        detailImageView.setController(controller);

        detailImageView.setDrawingCacheEnabled(true);

        detailImageView.buildDrawingCache(true);

        Bitmap bitmap = detailImageView.getDrawingCache();
```

2nd Attempt - 
```
 BitmapDrawable bMapDrawable = (BitmapDrawable) detailImageView.getDrawable();
 Bitmap bitmap = bMapDrawable.getBitmap();
```

The bitmap returned in both the cases  is always null ! The only other option I have is the post processor I suppose, but I would rather not use post processor as I just need the bitmap object and don't really need to modify the bitmap returned !

Any help would be appreciated !

**Comment by tyronen** [comment]
Looking at the [source code] (https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/palette/src/android/support/v7/graphics/Palette.java) class, it doesn't look like it holds onto a reference to the passed-in reference.

So actually I think the postprocessor is the simplest way for your needs, even if you're not actually modifying the Bitmap.

There is no future-proof way of getting a Bitmap from a Drawee. You could alternatively, in addition to your Drawee, send a second [image pipeline request](http://frescolib.org/docs/using-image-pipeline.html#_). But honestly, the postprocessor is simpler.
