### ISSUE TITLE
AnimatedDrawableCache Crash

### ISSUE THREAD

**Issue by Leiluojun** [facebook/fresco#1563]
When the memory occupied by dynamic image< 5M, all the frames will be placed in memory. But when I have many dynamic image in a page(example gridview), it will consume a lot of memory in the low-end mobile phone will be OOM. I hope the minimum image memory size can be configurable. What do you think?

` private static int getDefaultMaxBytes(ActivityManager activityManager) {
    int memory = activityManager.getMemoryClass();
    if (memory > 32) {
      return 5 * 1024 * 1024;
    } else {
      return 3 * 1024 * 1024;
    }
  }`

**Comment by massimocarli** [comment]
Hi @Leiluojun 
we're refactoring all the animations in order to fix this and other animation problems.
Stay tuned!

Thanks

**Comment by Leiluojun** [comment]
thanks , look forwarding...

**Comment by Leiluojun** [comment]
This probably takes how long? We now use the way to reflect the 5M changed to 2M。。

**Comment by oprisnik** [comment]
The new implementation is being worked on. We don't have an ETA yet.

**Comment by oprisnik** [comment]
We've released [Fresco v1.4.0](https://github.com/facebook/fresco/releases/tag/v1.4.0), which includes a new implementation for animated GIFs and animated WebPs that is way more performant, especially in the case where you display multiple images. Let us know if you're still experiencing problems with 1.4.0.
