### ISSUE TITLE
HttpUrlConnectionNetworkFetcher opens a url-connection without setting timeout?

### ISSUE THREAD

**Issue by yrom** [facebook/fresco#1566]
I found the default implementation of interface `NetworkFetcher`, that claiming the simplest, class `HttpUrlConnectionNetworkFetcher` ([line 128](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/HttpUrlConnectionNetworkFetcher.java#L126-L128)) opening URLConnection without any timeout! 

It's OK, but, just like a trap. 
I mean, it should be mentioned in documentation such as http://frescolib.org/docs/using-other-network-layers.html to bring users implement by their own.

**Comment by oprisnik** [comment]
Thanks for the feedback! Yeah, we could improve the documentation or add a timeout.
If you'd like, feel free to send a pull request :)

**Comment by jnawaz** [comment]
I've created a pull request for this issue. Default timeout of 30 seconds, based on some user testing to download a very small image under a "very bad network".

#2068
