### ISSUE TITLE
How can i add my custom producer to ProducerFactory?

### ISSUE THREAD

**Issue by wstczlt** [facebook/fresco#1571]
I want to decode video's thumbnail by my custom rule, so i want to write a producer and add it to ProducerFactory,  but the method 'getProducerFactory' in ImagePipelineFactory can't be override.
Could you help me to solve this problem? Thanks very much!

**Comment by oprisnik** [comment]
I don't think that custom producers can be added right now.
However, I think in your case you want a custom decoder instead. Take a look at the custom decoder example here: https://github.com/facebook/fresco/tree/master/samples/decoders/src/main/java/com/facebook/samples/decoders

**Comment by wstczlt** [comment]
However, my video sometime can't be decode by ThumbnailUtils like HD Movie, I saw the custom decoder, but it can't resolve the problem...

**Comment by wstczlt** [comment]
https://github.com/facebook/fresco/issues/1414

**Comment by oprisnik** [comment]
So what do you want to do exactly that requires a custom `Producer` instead of a `Decoder`?

**Comment by oprisnik** [comment]
I'm closing this since it's almost a year old. Feel free to comment with why you'd need a custom producer instead of a decoder if this is still an issue.
