### ISSUE TITLE
How to set a image TileMode REPEAT?

### ISSUE THREAD

**Issue by rayboot** [facebook/fresco#1575]
How could I set a background image with tile mode REPEAT?
And the image is from network , not local file.

**Comment by oprisnik** [comment]
I'm afraid that's currently not supported out-of-the-box. 
However, it is possilbe to implement a custom `DrawableFactory` that does tiling.

Adding this to the core library would also be quite easy. You would need to pass a parameter down to `PipelineDraweeController` where the `BitmapDrawable` is created and then use that. Or Modify GenericDraweeHierarchy to have support for this.

**Comment by erikandre** [comment]
Closing as this is enhancement is not prioritized to be implemented.
Still, please feel free to submit a pull request for any missing functionality.
