### ISSUE TITLE
When I use SimpleDraweeView with asCircle in the listview,my App has OOM error....

### ISSUE THREAD

**Issue by KaleXia** [facebook/fresco#1581]
In My App,I use SimpleDraweeView with **asCircle** attribute  in the **listview** to show My User's HeadImage ,I has **OOM error**; and than,I remove asCircle attribute , the Monitors show normal value;
  Now,I set the ImageRequest API  setResizeOptions(new ResizeOptions(120,120)) to improve the memory used;
  I guess whether the SimpleDraweeView with asCircle has not recycle?

My gradle:
compile('com.facebook.fresco:fresco:0.14.1')
compile('com.facebook.fresco:animated-gif:0.14.1')
compile('com.facebook.fresco:animated-base-support:0.14.1')

Forgive my poor English

**Comment by oprisnik** [comment]
How are you using Fresco? How big is the original image and what type? What rounding mode do you use (http://frescolib.org/docs/rounded-corners-and-circles.html), how many images are displayed at the same time (i.e. how many list items and how do you bind these)?

**Comment by KaleXia** [comment]
My image usually not bigger than 100kb,300*300 px.
and the one item just one image, (the view just like a Common Comment)
the ListView size > 500,when i scrollTo item over  more than a certain amount (i guess 200), feel lag clearly;than i continue scroll and will be crash;

My code the fresco load image

```
public void displayCircleImage(SimpleDraweeView simpleDraweeView, String url){

        if (checkTag(simpleDraweeView, url)) {
            simpleDraweeView.setTag(R.id.simpleDraweeView, url);

            DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                    .setImageRequest(getImageRequest(url))//设置请求
                    .setAutoPlayAnimations(false)//gif
                    .setControllerListener(null)//监听器
                    .setOldController(simpleDraweeView.getController())
                    .build();

            GenericDraweeHierarchy hierarchy = null;
            boolean b = simpleDraweeView.hasHierarchy();
            if (b) {
                hierarchy = simpleDraweeView.getHierarchy();
//                hierarchy.setRoundingParams(RoundingParams.asCircle());//already set in XML
                if(isNight){
                    hierarchy.setOverlayImage(AppUtils.getInstance().getContext().getResources().getDrawable(R.drawable.common_night_overimage_circle));
                }
            } else {
                GenericDraweeHierarchyBuilder builder = new GenericDraweeHierarchyBuilder(context.getResources());
                builder.setFadeDuration(0);
                builder.setActualImageScaleType(ScalingUtils.ScaleType.FIT_XY);
                builder.setRoundingParams(RoundingParams.asCircle());
                if(isNight){
                    builder.setOverlay(AppUtils.getInstance().getContext().getResources().getDrawable(R.drawable.common_night_overimage_circle));
                }
                hierarchy = builder.build();
            }
            if(hierarchy != null){
                simpleDraweeView.setHierarchy(hierarchy);
            }
            if(draweeController != null){
                simpleDraweeView.setController(draweeController);

            }
        }
    }


 private ImageRequest getImageRequest(String url) {
        if (url == null || url.length() == 0) {
            url = "";
        }
        return ImageRequestBuilder.newBuilderWithSource(Uri.parse(url)).build();
    }
```


ListView bind the data:
```
 public View creatView(int position, View convertView, ViewGroup parent) {
        ViewHolder viewHolder;
        int type = getItemViewType(position);
        if(convertView == null){
                convertView = inflater.inflate(R.layout.item_news_comment, null);
                viewHolder = new ViewHolder(convertView);
                convertView.setTag(viewHolder);
          
        }else {
        
                viewHolder = (ViewHolder) convertView.getTag();
           
        }
       
        setData();// set My data 

        return convertView;
    }
```

**Comment by KaleXia** [comment]
@oprisnik

**Comment by oprisnik** [comment]
You should not use ListView for this but RecyclerView (or something similar that does view recycling). ListView keeps all elements in memory - which means that you will have more and more images in memory - which leads to the OOM eventually.

**Comment by KaleXia** [comment]
@oprisnik  eh....I will try use RecyclerView instead of ListView;
But the same ListView and the same Adapter, Used th asCircle = "true" in XML  must be happend OOM
remove the asCircle = "true" in XML ,the Monitors Memory can see it self-recycle;

**Comment by oprisnik** [comment]
I assume the problem has been resolved. Let us know if you're still experiencing this issue.
