### ISSUE TITLE
Important function and class in fresco

### ISSUE THREAD

**Issue by edconan93** [facebook/fresco#1582]
Hello. Im research about fresco, I found a very clear image describe the what fresco running, but when I trace code, it's very hard to find the function with each pharse, can someone tell me the function with each pharse in the pipiline goes in the image, thank you

**Comment by lambdapioneer** [comment]
Hi @edconan93, you can have a look at http://frescolib.org/docs/intro-image-pipeline.html for introductory information on how the pipeline works.

However, the definite documentation is the code in this repository. The [`ProducerSequenceFactory`](https://github.com/facebook/fresco/blob/fc393f739d08f38dd16ef9c2c05f9c1a9d0087dd/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ProducerSequenceFactory.java) is a good place to start.

**Comment by lambdapioneer** [comment]
I'm closing out this old issue - if this is still relevant, please create a new one
