### ISSUE TITLE
Readme and docs update for version 1.0

### ISSUE THREAD

**Issue by PiotrWpl** [facebook/fresco#1584]
Hi!

Thank You very much for the 1.0.0 version. Amazing job!

But, can You update the Readme.md and documentation on http://frescolib.org/docs/ ?
There are lack of information about 1.0.0 version, and things like displaying for example gif images. Until now there was com.facebook.fresco:animated-gif:0.14.0 but I found there is nothing like com.facebook.fresco:animated-gif:1.0.0

Greetings

**Comment by oprisnik** [comment]
Thanks, we're on it, the docs will be updated soon. The version number is `1.0`instead of `1.0.0`.

**Comment by oprisnik** [comment]
Everything has been updated. We also changed the version number to 1.0.0 in order to be consistent.
