### ISSUE TITLE
A gif does not play if it just has 2 frames.

### ISSUE THREAD

**Issue by zongjingyao** [facebook/fresco#1587]
A gif does not play if it just has 2 frames.
What's the problem? Help me please.

**Comment by zongjingyao** [comment]
sample gif
![1219104035](https://cloud.githubusercontent.com/assets/2386640/21300512/88e7c0f0-c5df-11e6-9cac-5bb9a2629b3f.gif)

**Comment by lambdapioneer** [comment]
Hi @zongjingyao, I cannot reproduce this in our demo app "uri app". Which Fresco version are you using? Also, please provide a minimal code example that reproduces the issue :) Thanks

**Comment by zongjingyao** [comment]
Hi @lambdapioneer 
Thanks for your reply. Here are my configs in build.gradle and my sample code.

```
compile 'com.facebook.fresco:fresco:0.12.0'
compile 'com.facebook.fresco:animated-gif:0.12.0'
```
---
```Java
SimpleDraweeView simpleDraweeView = (SimpleDraweeView) findViewById(R.id.dv_image);
Uri uri = Uri.parse("file:///sdcard/sample.gif");
DraweeController controller = Fresco.newDraweeControllerBuilder()
     .setUri(uri)
    .setAutoPlayAnimations(true)
    .build();
simpleDraweeView.setController(controller);
```

I tried the latest version of Fresco，the problem is gone. It seems that the new version has fixed this bug. I must upgrade my project as soon as possible.
