### ISSUE TITLE
Some problem about  "placeholderImageScaleType"="center"

### ISSUE THREAD

**Issue by palmyer** [facebook/fresco#1588]
Why white lines?
Looks Like being stretched out.
![238b9358-045c-425e-8712-2743f81e992d](https://cloud.githubusercontent.com/assets/8294906/21303948/f0a211ba-c5fc-11e6-85f7-02dd258c7216.png)
![534978ad-2252-4b6b-9168-0d574b6d6fef](https://cloud.githubusercontent.com/assets/8294906/21303956/fe40868a-c5fc-11e6-9ef9-e7af32e692bd.png)

**Comment by palmyer** [comment]
<com.facebook.drawee.view.SimpleDraweeView
                    android:id="@+id/image"
                    style="@style/simpledraweeview_leftround_style"
                    android:layout_width="@dimen/dp_114"
                    android:layout_height="@dimen/dp_114"
                    fresco:placeholderImage="@drawable/search_item" />

<style name="simpledraweeview_style">
        <item name="fadeDuration">300</item>
        <item name="actualImageScaleType">centerCrop</item>
        <item name="placeholderImageScaleType">center</item>
    </style>

<style name="simpledraweeview_leftround_style" parent="simpledraweeview_style">
        <item name="roundAsCircle">false</item>
        <item name="roundedCornerRadius">@dimen/round_corner_big</item>
        <item name="roundTopLeft">true</item>
        <item name="roundBottomLeft">true</item>
        <item name="roundTopRight">false</item>
        <item name="roundBottomRight">false</item>
        <item name="backgroundImage">@drawable/shape_grey_leftround</item>
    </style>

It is normal PNG

**Comment by lambdapioneer** [comment]
Hi @palmyer, this is a known limitation of this combination of scale type and rounded corners. 

Please see http://frescolib.org/docs/rounded-corners-and-circles.html for some background and solutions to this. I think that this should solve your issue.

**Comment by palmyer** [comment]
I think this is the BITMAP_ONLY method and I change the backgroundImage to "color/color_57778f" not NinePatchDrawable or ShapeDrawable, but it is not solved my problem.
Then I try to add 3px(1px or 2px is not enough) translation edge to placeholde image and it works well.
Is this the solution？

**Comment by oprisnik** [comment]
You can either use the color overlay rounding mode or modify your image to have a 1px transparent border (so that transparent pixels will be repeated instead of the white ones. Unfortunately, there's no better solution yet.
