### ISSUE TITLE
OOM wgen loading a lot of image

### ISSUE THREAD

**Issue by edconan93** [facebook/fresco#1590]
I have created a app with a gridview with simple adapter to load about 2400 image 10dp x10dp thumbnail but it crash because OOM. And sometime image not loaded, compare with picasso it always good. Please check it.

**Comment by lambdapioneer** [comment]
Hi @edconan93, can you provide us with a minimal code sample that reproduces the issue?

In general, we recommend using a RecyclerView for those scenarios. You can have a look at our scroll perf app on how to do this (including a grid layout).

**Comment by oprisnik** [comment]
I suppose this issue has been resolved. Please let us know if that is not the case.
