### ISSUE TITLE
Load image fail if uri contain char '#'

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#1595]
Load image fail if uri contains char '#', like this:
/storage/emulated/0/Android/data/com.testfresco/test#demo/image/th90441482388839685.jpg

**Comment by lambdapioneer** [comment]
Hi @ICECHN, I cannot reproduce this using the URI sample app. I've been using the following URI: `file:///sdcard/Download/test#test/sq_h.jpg`.

Can you provide us with sample code where your file path fails?

**Comment by ICECHN** [comment]
Uri.fromFile(new File(picFilePath))) fail,
Uri.parse("file://"+filePath) ok.
