### ISSUE TITLE
bring 5 aar file into my project. it is cant run fresco 

### ISSUE THREAD

**Issue by yangmaogithub** [facebook/fresco#1598]
hi developer,
because some reason, our project should use android-sourc-code to make. so i need use fresco aar file. i put drawee-1.0.0.aar, fbcore-1.0.0.aar,fresco-1.0.0.aar,imagepipeline-1.0.0.aar,imagepipeline-base-1.0.0.aar. into libs.   it can build. but when run apk  it crashed. the log is 
java.lang.NoClassDefFoundError: bolts.Task
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.cache.BufferedDiskCache.getAsync(BufferedDiskCache.java:167)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.cache.BufferedDiskCache.get(BufferedDiskCache.java:138)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.cache.SmallCacheIfRequestedDiskCachePolicy.createAndStartCacheReadTask(SmallCacheIfRequestedDiskCachePolicy.java:48)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.DiskCacheReadProducer.produceResults(DiskCacheReadProducer.java:64)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer.produceResults(EncodedMemoryCacheProducer.java:95)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(MultiplexProducer.java:336)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:125)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:87)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:29)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.produceResults(ResizeAndRotateProducer.java:80)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.java:108)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer.produceResults(BitmapMemoryCacheProducer.java:94)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(MultiplexProducer.java:336)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:125)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:87)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(ThreadHandoffProducer.java:43)
E/AndroidRuntime(13695): 	at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
E/AndroidRuntime(13695): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(13695): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(13695): 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
E/AndroidRuntime(13695): 	at java.lang.Thread.run(Thread.java:841)

**Comment by oprisnik** [comment]
You also need to add Bolts to your project (and potential other libraries that are missing). Just take a look at our `build.gradle` files in the dependency sections.

**Comment by eldk** [comment]
Hello,

I have updated to Fresco 1.0.0 yesterday (it's ok, build run ...).
Before 1.0.0, image-base-test, and imagepipeline-test, were needed. Those module are still in my dev environment, but I haven't check yet if they are really needed.
Maybe should you add them to your 1.0.0 build.

Eric
