### ISSUE TITLE
How can I get images by POST request ?

### ISSUE THREAD

**Issue by durgeshsatyam** [facebook/fresco#1599]
Hi,
The request that FRESCO uses is possibly GET in order to download the images from the server.
I want to know whether there is any possible way to download the images using POST request instead of GET request.

**Comment by Presleyzheng** [comment]
initialize Fresco with ImagePipelineConfig with NetworkFetcher which implement with Http POST method

**Comment by oprisnik** [comment]
Yes, what @Presleyzheng said. A custom NetworkFetcher can be used to do this.
