### ISSUE TITLE
Rounding doesn't work for placeholder-only

### ISSUE THREAD

**Issue by nimengbo** [facebook/fresco#160]
<com.facebook.drawee.view.SimpleDraweeView
         android:id="@+id/head_img"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_alignParentLeft="true"
        android:layout_marginLeft="17dp"
        fresco:actualImageScaleType="focusCrop"
        fresco:failureImage="@mipmap/icon_default_head"
        fresco:placeholderImage="@mipmap/icon_default_head"
        fresco:roundAsCircle="true" />

in java : imgView.setImageURI(null);  .  

result  isn't  circle 
show as original drawing by "@mipmap/icon_default_head"
 String url = "xxxxxx"
if set imgView.setImageURI(Uri.parse(url));
result is circle 

if url is null fresco:roundWithOverlayColor is must be set?

Chinese:
当我设置 setImageURI(null)  在xml里设置的 fresco:roundAsCircle="true" 没起作用，用的还是原来是图是方的而不是圆的。
如果我设置url不是null 那么 得到的效果是圆的。
如何让我的占位图和失败时的图 也能是圆的？ 前提是我的原图是方的

 fresco:roundWithOverlayColor 这个属性是必须的吗？

**Comment by kooze** [comment]
Actually, the rounding is only works for no-9 path in placeholder. I hope I can help you.

**Comment by plamenko** [comment]
Hi, yes, this is a known limitation. Only images that resolve to `BitmapDrawable` or `ColorDrawable` can be rounded. Rounding `NinePatchDrawable`, `ShapeDrawable` and other such drawables is not supported (regardless whether they are specified in XML or programmatically).
Please see Caveats section in http://frescolib.org/docs/rounded-corners-and-circles.html#_

**Comment by nimengbo** [comment]
uh .. @mipmap/icon_default_head just a PNG not .9.png  AsCircle not support ??

**Comment by plamenko** [comment]
Can you please attach a screenshot? Is it possible that your placeholder image is too small?

**Comment by nimengbo** [comment]
![16ca2d01-c191-41a9-bf7c-297598018ac1](https://cloud.githubusercontent.com/assets/6950107/7222624/fa826cfe-e744-11e4-8a45-ebf8bb6dd322.png)
![060f4244-01aa-4240-b7ad-d3991ca428d5](https://cloud.githubusercontent.com/assets/6950107/7222628/fb64d7ce-e744-11e4-9b7c-be6a086b2a51.png)
![9315b83a-956c-42bb-9bdb-6a6a70341af0](https://cloud.githubusercontent.com/assets/6950107/7222625/fa9335c0-e744-11e4-8d2f-b1c4146827f4.png)
![gls 6 x0hz7 a01y6h3 im](https://cloud.githubusercontent.com/assets/6950107/7222626/faa7369c-e744-11e4-972c-814ec59c5c9d.jpg)

icon_default_head is a square ..
But when i set setImageURI(null)  show as result  the AsCircle don't work

**Comment by nimengbo** [comment]
I change the icon_default_head size as 436x436  44.2KB  but  fall flat

**Comment by plamenko** [comment]
Is it possible that the image is actually a GIF (even though the extension says PNG)?
Can you upload this image please?

**Comment by nimengbo** [comment]
![icon_default_head](https://cloud.githubusercontent.com/assets/6950107/7244401/7d5415a6-e80d-11e4-9f3e-f72c687af901.png)

Uh.. actually  the image is a PNG

**Comment by plamenko** [comment]
Can you remove `fresco:failureImage` from XML?

**Comment by nimengbo** [comment]
When I removed  fresco:failureImage from XML , AsCircle was  worked .
But why ?

**Comment by nimengbo** [comment]
fresco:failureImage This is unnecessary？

**Comment by plamenko** [comment]
Rounding is not supported for the failure image at the moment.
See http://frescolib.org/docs/rounded-corners-and-circles.html#_

If failure image is not specified, the placeholder image is shown in case of a failure, so if those two images are the same, it is redundant to specify `failureImage`
See http://frescolib.org/docs/drawee-components.html#_

**Comment by nimengbo** [comment]
ok  thanks for lot
