### ISSUE TITLE
RecyclerView in NestedScrollView

### ISSUE THREAD

**Issue by bblackbelt** [facebook/fresco#1600]
Hi, 
 I have a complex view that forces me to put a RecyclerView (the RecyclerView handles the SimpleDraweeView), among other widgets into a NestedScrollView. Doing so, seems to be causing a lot of 

>  onRequestFailure: {requestId: 69, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 150994944 Used size = 150494072 Free size = 0 Request size = 3578640}

Removing the NestedScrollView makes the whole loading work correctly and no onRequestFailure lines appear on the logcat. I read about not having a SimpleDraweeView as direct child of a ScrollView. Does this limitation applies to my use case ( <NestedScrollView> <RecyclerView>SimpleDraweeView</RecyclerView></NestedScrollView>) ?

My Request type is 

```
    ImageRequestBuilder request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setPostprocessor(mPostprocessorProcessor)
                .setResizeOptions(new ResizeOptions((int) mResizeWidth, (int) mResizeHeight));
        PipelineDraweeController controller = (PipelineDraweeController)
                Fresco.newDraweeControllerBuilder()
                        .setImageRequest(request.build())
                        .setOldController(getController())
                        .setControllerListener(mImageControllerListener)
                        .build();
        setController(controller);
```

Please advice
Best

**Comment by bblackbelt** [comment]
The issue is related to android. RecyclerView does not recycle its items when its height is wrap_content and it is a child of NestedScrollView

**Comment by oprisnik** [comment]
Thanks for the info. Yeah, looks like you're never releasing images, which causes them to fill up the pool until the [hard cap throws exceptions](http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/memory/PoolParams.html) due to too many images. Try to recycle those views.
