### ISSUE TITLE
can not find symbol :fresco

### ISSUE THREAD

**Issue by Aheadboy** [facebook/fresco#1601]
mine project has already  depencies on drawee;but i got this problem
![image](https://cloud.githubusercontent.com/assets/8358046/21491963/58c049a8-cc3b-11e6-8647-a8342952998f.png)
![image](https://cloud.githubusercontent.com/assets/8358046/21491966/6d989d8a-cc3b-11e6-84ad-40ec17da72be.png)
mine ide is itellij idea how should i solve this problem

**Comment by oprisnik** [comment]
Fresco lives in the `drawee-pipeline` module. You have to add that one as well.

**Comment by Aheadboy** [comment]
![image](https://cloud.githubusercontent.com/assets/8358046/21628782/feadade8-d25c-11e6-86a4-d7b52ba0052c.png)
there is
no such drawee-pipeline module i can find from the jar package


now, import is fine 
![image](https://cloud.githubusercontent.com/assets/8358046/21628843/96e80db0-d25d-11e6-8bbf-79c8b687a8b8.png) but,when i run apk it occure
this 
![image](https://cloud.githubusercontent.com/assets/8358046/21628883/0a5f6036-d25e-11e6-9610-1be65a9c9630.png)

**Comment by Aheadboy** [comment]
when i use eclipse ,my project dependencies is the same as when i use intellij idea.but elicpse is fine ,intellij idea cause problem.

**Comment by lambdapioneer** [comment]
Hi @Aheadboy, I assume you are using IntelliJ at the moment?

It would be great if you can share your `build.gradle` file(s) or parts of it. Also have a look at http://frescolib.org/docs/index.html on how it should look like

**Comment by Aheadboy** [comment]
yes ,I'm using IntelliJ where cause this problem.my project was migrated from eclipse to IntelliJ idea.
![image](https://cloud.githubusercontent.com/assets/8358046/21840052/3112e910-d816-11e6-99f3-d3bb4a14d0e4.png)
this is part of my build.gradle
problem still there

**Comment by Aheadboy** [comment]
![image](https://cloud.githubusercontent.com/assets/8358046/21840132/bc099276-d816-11e6-80d7-2c28c65283aa.png)
I'm importe this package ,but error says
![image](https://cloud.githubusercontent.com/assets/8358046/21840144/d1d23bda-d816-11e6-99c2-d2a9608a0761.png)
Am I imported wrong package?

**Comment by oprisnik** [comment]
As I said above: There is a [drawee-pipeline](https://github.com/facebook/fresco/tree/master/drawee-backends/drawee-pipeline) package that you need to include.
