### ISSUE TITLE
how to load pressed image from uri？

### ISSUE THREAD

**Issue by liuchenx** [facebook/fresco#1606]
it like  
```
GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(getResources())
Uri uri = "http://...";        
hierarchy.setOverlayImage(uri);
```

**Comment by kirwan** [comment]
Do you mean a different image for the pressed state? That's not something I'd recommend due to the likelihood of a delay which will seem strange to the user.

You could define an overlay with a `StateListDrawable` for local drawables.

**Comment by oprisnik** [comment]
You would have to manually manage image loading in that case. I would suggest reading through the custom view guide (http://frescolib.org/docs/writing-custom-views.html) and using the pipeline directly (http://frescolib.org/docs/using-image-pipeline.html)
