### ISSUE TITLE
Build fails with clang++: error: unknown argument: '-fno-weak'

### ISSUE THREAD

**Issue by korDen** [facebook/fresco#1608]
From GCC documentation:

-fno-weak
Do not use weak symbol support, even if it is provided by the linker. By default, G++ uses weak symbols if they are available. This option exists only for testing, and should not be used by end-users; it results in inferior code and has no benefits. This option may be removed in a future release of G++.

Let's not use it.

**Comment by korDen** [comment]
To elaborate, I'm not forcing a clang build but rather using default ndk configuration, which uses clang by default. Not sure why "NDK_TOOLCHAIN_VERSION := 4.9" takes no effect.

**Comment by lambdapioneer** [comment]
Hi @korDen, this looks reasonable to me. Thanks a lot for this very helpful issue. Getting rid of deprecated flags is usually a good idea.

Do you want to create a PR for this change? I think it's just appearing in three places :) I'll then import that change and run it against our internal tests to make sure it has no observable negative impact.

**Comment by erikandre** [comment]
@lambdapioneer, closing this since it was handled in the PR as far as I can see
