### ISSUE TITLE
load Net image be failed

### ISSUE THREAD

**Issue by kartyjoin** [facebook/fresco#1609]
Our url like  "https://xxxx.xxxx.com/xxx/goods@2x.png"
Fresco whether to support url include '@'?

**Comment by oprisnik** [comment]
According to the [URL RFC 1738](http://www.ietf.org/rfc/rfc1738.txt), the "@" symbol is a reserved symbol, so you have to encode it. Does it work if you use `goods%402x.png`?

**Comment by kartyjoin** [comment]
Thanks, you're right
