### ISSUE TITLE
gif image play crash on x86 based device

### ISSUE THREAD

**Issue by dwzzhw** [facebook/fresco#1610]
When I load a gif image on my x86 device, the image can be displayed at first, but soon it will crash after a few loops, here is the crash backtrace:

12-30 18:42:25.772 150-150/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-30 18:42:25.772 150-150/? I/DEBUG: Build fingerprint: 'Lenovo/K900/K900:4.3/JSS15Q/VIBEROM_V1.0_1418_DEV_K900:user/releasekey'
12-30 18:42:25.772 150-150/? I/DEBUG: Revision: '0'
12-30 18:42:25.772 150-150/? I/DEBUG: pid: 4773, tid: 4823, name: Thread-5812  >>> com.facebook.samples.demo <<<
12-30 18:42:25.772 150-150/? I/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
12-30 18:42:25.802 150-150/? I/DEBUG:     eax 60bbac80  ebx 6108ef24  ecx 00001002  edx 60f61a14
12-30 18:42:25.802 150-150/? I/DEBUG:     esi 00000000  edi 00000000
12-30 18:42:25.802 150-150/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
12-30 18:42:25.802 150-150/? I/DEBUG:     eip 6106f8df  ebp 613ef154  esp 60f619cc  flags 00210206
12-30 18:42:25.812 150-150/? I/DEBUG: backtrace:
12-30 18:42:25.812 150-150/? I/DEBUG:     #00  pc 000058df  /data/app-lib/com.facebook.samples.demo-2/libgifimage.so
12-30 18:42:25.812 150-150/? I/DEBUG:     #01  pc 00006f31  /data/app-lib/com.facebook.samples.demo-2/libgifimage.so
12-30 18:42:25.812 150-150/? I/DEBUG:     #02  pc 00002c9b  /data/app-lib/com.facebook.samples.demo-2/libgifimage.so
12-30 18:42:25.812 150-150/? I/DEBUG:     #03  pc 000049bd  /data/app-lib/com.facebook.samples.demo-2/libgifimage.so

and this is the related code lines:
LOADING-MC0:bin loading$ ./i686-linux-android-addr2line -e libgifimage.so 000058df 00006f31 00002c9b 000049bd
/Users/loading/work/fresco/fresco-1.0.0/animated-gif/src/main/jni/../../../nativedeps/merge/giflib/dgif_lib.c:819
/Users/loading/work/fresco/fresco-1.0.0/animated-gif/src/main/jni/../../../nativedeps/merge/giflib/dgif_lib.c:457
/Users/loading/work/fresco/fresco-1.0.0/animated-gif/src/main/jni/gifimage/./gif.cpp:346
/Users/loading/work/fresco/fresco-1.0.0/animated-gif/src/main/jni/gifimage/./gif.cpp:1106 (discriminator 2)

besides gif image, an animated webp image may also cause a similar crash, the image is from fresco sample demo, https://www.gstatic.com/webp/animated/1.webp, and the backtrace looks like this：
12-30 18:44:11.012 150-150/? I/DEBUG: pid: 6445, tid: 6520, name: Thread-5908  >>> com.facebook.samples.demo <<<
12-30 18:44:11.012 150-150/? I/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
12-30 18:44:11.042 150-150/? I/DEBUG:     eax 605482f0  ebx 63ef7ee0  ecx 00000000  edx 63ed2a20
12-30 18:44:11.042 150-150/? I/DEBUG:     esi f3ffc000  edi 00000006
12-30 18:44:11.042 150-150/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
12-30 18:44:11.042 150-150/? I/DEBUG:     eip 63ec53f7  ebp 605492c0  esp 61ddd58c  flags 00210246
12-30 18:44:11.052 150-150/? I/DEBUG: backtrace:
12-30 18:44:11.052 150-150/? I/DEBUG:     #00  pc 000763f7  /data/app-lib/com.facebook.samples.demo-1/libstatic-webp.so
12-30 18:44:11.052 150-150/? I/DEBUG:     #01  pc 0004c18e  /data/app-lib/com.facebook.samples.demo-1/libstatic-webp.so
12-30 18:44:11.052 150-150/? I/DEBUG:     #02  pc 0004d17a  /data/app-lib/com.facebook.samples.demo-1/libstatic-webp.so
12-30 18:44:11.052 150-150/? I/DEBUG:     #03  pc 00051a0b  /data/app-lib/com.facebook.samples.demo-1/libstatic-webp.so
12-30 18:44:11.052 150-150/? I/DEBUG:     #04  pc 00043124  /data/app-lib/com.facebook.samples.demo-1/libstatic-webp.so
12-30 18:44:11.052 150-150/? I/DEBUG:     #05  pc 000452d0  /data/app-lib/com.facebook.samples.demo-1/libstatic-webp.so
12-30 18:44:11.052 150-150/? I/DEBUG:     #06  pc 000097e0  /data/app-lib/com.facebook.samples.demo-1/libstatic-webp.so

LOADING-MC0:bin loading$ ./i686-linux-android-addr2line -e libstatic-webp.so 000763f7 0004c18e 0004d17a 00051a0b 00043124 000452d0 000097e0
/Users/loading/Android/NDK/android-ndk-r12b/toolchains/x86-4.9/prebuilt/darwin-x86_64/lib/gcc/i686-linux-android/4.9.x/include/emmintrin.h:979
/Users/loading/work/fresco/fresco-1.0.0/static-webp/src/main/jni/../../../nativedeps/merge/libwebp-0.5.1/src/dec/frame.c:47
/Users/loading/work/fresco/fresco-1.0.0/static-webp/src/main/jni/../../../nativedeps/merge/libwebp-0.5.1/src/dec/frame.c:511
/Users/loading/work/fresco/fresco-1.0.0/static-webp/src/main/jni/../../../nativedeps/merge/libwebp-0.5.1/src/dec/vp8.c:603
/Users/loading/work/fresco/fresco-1.0.0/static-webp/src/main/jni/../../../nativedeps/merge/libwebp-0.5.1/src/dec/webp.c:488
/Users/loading/work/fresco/fresco-1.0.0/static-webp/src/main/jni/../../../nativedeps/merge/libwebp-0.5.1/src/dec/webp.c:780
/Users/loading/work/fresco/fresco-1.0.0/static-webp/src/main/jni/static-webp/./webp.cpp:656

Can anyone help us? Many thanks for your kind help!

**Comment by lambdapioneer** [comment]
Hi @dwzzhw, thanks for the detailed bug report!

Can you tell us on which exact device and Android version you are able to reproduce this?

**Comment by massimocarli** [comment]
Hi @dwzzhw,
can you tell us if the problem persists also with the last update of libwebp to version 0.5.2 we have done in release 1.0.1?
Thanks

**Comment by dwzzhw** [comment]
hi @lambdapioneer, I reproduce this issue on Lenovo K900, with android 4.3 inside

**Comment by dwzzhw** [comment]
hi @massimocarli, yes, this problem still persists with libwebp version 0.5.2

**Comment by oprisnik** [comment]
We've significantly changed animated image rendering with more recent Fresco versions, so I'll close this for now. If this is still an issue, please let us know.
