### ISSUE TITLE
Fresco failed to load all images.

### ISSUE THREAD

**Issue by The-RobinHood** [facebook/fresco#1615]
Hello
I' trying to load number of images using `setLowResImageRequest` & `setImageRequest` but it load only first image and failed to load others images, please look at screen shot and attached code.

> Note:- height width of **thumb** image is 400x400 & Loading **original** without compressing.

> Code snippet

`
                    DraweeController controller = Fresco.newDraweeControllerBuilder()
                            .setLowResImageRequest(ImageRequest.fromUri(Uri.parse(imageData.getThumb())))
                            .setImageRequest(ImageRequest.fromUri(Uri.parse(imageData.getUrl())))
                            .setOldController(pVh.sdvPhoto.getController())
                            .build();
                    pVh.sdvPhoto.setController(controller);`

>URLs
`"Url": "http:\/\/andromak.s3.amazonaws.com\/Post\/aviary-image-1483668519447.jpeg",
          "Thumb": "http:\/\/andromak.s3.amazonaws.com\/Post\/thumb\/aviary-image-1483668519447.jpeg",`

![device-2017-01-06-194725](https://cloud.githubusercontent.com/assets/1669628/21720442/3bb2c5aa-d449-11e6-8d20-9543c18f3cdc.png)
![device-2017-01-06-194823](https://cloud.githubusercontent.com/assets/1669628/21720441/3bac8690-d449-11e6-9063-909adeea4150.png)

**Comment by oprisnik** [comment]
Do you use view recycling? Is it always just 1 image? What if you change the URLs? Do you use Fresco v1.0.0?
