### ISSUE TITLE
com.android.server.job.controllers.JobStatus.getUid()-->NullPointerException

### ISSUE THREAD

**Issue by daiwenbo88** [facebook/fresco#1622]
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1580)
	at android.os.Parcel.readException(Parcel.java:1527)

----->The exception has been bothering me for several days, don't know if you can exit the solution suggestion or opinion  I have noticed that the image loader useful to JobScheduler as follows

        at   com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)

**Comment by foghina** [comment]
What are you doing when you get this exception? Do you have a consistent repro?

**Comment by jeryfer** [comment]
For those, who also get this issue: links: [https://code.google.com/p/android/issues/detail?id=104302](https://code.google.com/p/android/issues/detail?id=104302)

**Comment by jeryfer** [comment]
I asked a question on StackOverFlow.[http://stackoverflow.com/questions/41531529/attempt-to-invoke-virtual-method-on-a-null-object-reference-int-com-android-ser](http://stackoverflow.com/questions/41531529/attempt-to-invoke-virtual-method-on-a-null-object-reference-int-com-android-ser)
