### ISSUE TITLE
Corrupted images

### ISSUE THREAD

**Issue by triple-dot** [facebook/fresco#1623]
While I load the images in ListView, some of the images I get are corrupted and shown with half-grayish background. (link attached).
![currupt_image](https://cloud.githubusercontent.com/assets/23431961/21840871/d3132006-d805-11e6-8a4e-6b84ac68d096.jpg)

While downloading, I am also saving the image to the disk. Below is the way I'm doing it:

`        GenericDraweeHierarchyBuilder builder =
            new GenericDraweeHierarchyBuilder(context.getResources());
        builder
            .setFadeDuration(50)
            .setProgressBarImage(null)
            .setPlaceholderImage(R.color.colorPrimaryLightWithMoreAlpha)
            .setPlaceholderImageScaleType(ScalingUtils.ScaleType.CENTER_CROP);

        GenericDraweeHierarchy hierarchy =builder.build();
        Uri lowResUri= Uri.parse(imageUrl+"_blur");
        Uri highResUri= Uri.parse(imageUrl);
        imageView.setHierarchy(hierarchy);
        ProductImageHelper productImageHelper = new ProductImageHelper();
        Uri uriLocal = productImageHelper.getUriForProductImage(context,productId);
        ImageRequest localImageRequest = ImageRequestBuilder.newBuilderWithSource(uriLocal).setRequestPriority(priority).build();
        ImageRequest hiresImageRequest = ImageRequestBuilder.newBuilderWithSource(highResUri).setResizeOptions(new ResizeOptions((int) context.getResources().getDimension(R.dimen.product_width),(int) context.getResources().getDimension(R.dimen.product_height))).setRequestPriority(priority).build();
        ImageRequest lowResImageRequest = ImageRequestBuilder.newBuilderWithSource(lowResUri).setRequestPriority(priority).build();
        ImageRequest[] requests = { localImageRequest, hiresImageRequest};
        ImagePipeline imagePipeline = Fresco.getImagePipeline();

        DataSource<CloseableReference<CloseableImage>> dataSource =
                imagePipeline.fetchDecodedImage(hiresImageRequest, context.getApplicationContext());
        dataSource.subscribe(new CustomBitmapDataSubscriber(context.getApplicationContext(),productId,highResUri,uriLocal), CallerThreadExecutor.getInstance());

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setLowResImageRequest(lowResImageRequest)
                .setFirstAvailableImageRequests(requests)
                .setOldController(imageView.getController())
                .build();
        imageView.setController(controller);
`

in CustomBitmapDataSubscriber, I am removing hiResUri from memory cache and prefetching localuri in memory cache.

**Comment by foghina** [comment]
Do you have a URL to the image you are trying to load?

**Comment by triple-dot** [comment]
Here is the link
[http://shopperts.in:8080/ShoppertsGalleryEngine/ProductImageServlet?affiliateProductId=1_4746](url)

It is not image specific though, when I scroll down in listview, it happens on 1-2 images every time at random.

**Comment by foghina** [comment]
I can't repro the problem. What device are you seeing this on, or is it not device-specific?

Is there a way you can provide a (preferably stripped down) sample app where this happens?

**Comment by prgomet** [comment]
I have same problem in my application and it happens when i load image from phone storage into SimpleDraweeView **only first time after downloading it** (when i restart application image is loaded correctly), also ti happens on random images.

It is not related to any specific phone, android version or image, i'm testing it on 20+ phones (from android 4.4 to 7.1.1).

**Comment by foghina** [comment]
@prgomet are you downloading the image outside of fresco? If yes, is there any chance the download is incomplete when you load it into SimpleDraweeView? Any reason why you're not using [prefetching](http://frescolib.org/docs/using-image-pipeline.html#prefetching)?

**Comment by prgomet** [comment]
Problem solved!
In my case problem was because `onBindViewHolder` was called before download was completed and i was checking only if file exists and because of that Fresco loads corrupted image (file is created when download starts), for me solution was to check in database if download was completed.

**Comment by foghina** [comment]
@triple-dot any chance you're doing a similar thing to @prgomet?
