### ISSUE TITLE
Requested: Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeCopyBitmap:(Landroid/graphics/Bitmap;ILandroid/graphics/Bitmap;II)V

### ISSUE THREAD

**Issue by 836154942** [facebook/fresco#1627]
4.4 system 。  cannoet load imag white  with log 
E/dalvikvm: ERROR: couldn't find native method

Requested: Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeCopyBitmap:(Landroid/graphics/Bitmap;ILandroid/graphics/Bitmap;II)V

other system  can  use successful

**Comment by foghina** [comment]
Does this error happen all the time? Or just sometimes? What device with Android 4.4 is this happening on?

**Comment by 836154942** [comment]
happen always on devices  smae as virtual devices and   other phone same xiaomi  also 。

**Comment by 836154942** [comment]
solved it。 because of proguard thanks 。
