### ISSUE TITLE
Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'. 

### ISSUE THREAD

**Issue by hzy87email** [facebook/fresco#163]
OS： mac 10.10.3
Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> A problem occurred starting process 'command 'ndk-build''

## help

**Comment by tyronen** [comment]
Do you have the Android NDK installed? Have you followed the [build instructions](http://frescolib.org/docs/building-from-source.html#_)?

If so, please run gradle with the --debug option to get further details.

**Comment by hzy87email** [comment]
@tyronen yes I'm installed Android NDK，but Android studio build Compile is error

**Comment by hzy87email** [comment]
@tyronen  thank you   build success

**Comment by avenwu** [comment]
@hzy87email so how do you fixed this issue?

**Comment by gdky005** [comment]
大家可以在 imagepipeline 子项目里面的 gradle.properties 文件中得最后添加

ndk.path=/Users/XXX/Android_SDK/android-ndk-r10d

(PS：/Users/XXX/Android_SDK/android-ndk-r10d是你系统里面的NDK路径)
就可以了，不需要在 build.gradle 里面写，方便以后的修改。

我发现在Android Studio 的 1.0.1 版本上可以， 在最新的1.2里面不可以，可能和 编译器有关吧。

**Comment by hzy87email** [comment]
@avenwu In the folder imagepipeline with gradle.properties file to add the NDK path in the directory。
For example：ndk.path=/Users/XXX/Android_SDK/android-ndk-r10d

**Comment by hzy87email** [comment]
@gdky005  不知道你遇上的是什么情况，我之前的android studio 也是1.1编译通过，现在studio也是1.2编译一样运行~你会不会是其他问题？

**Comment by gdky005** [comment]
@hzy87email 如果你是升级上来的应该不会出现问题，如果是单独装上1.2后，发现每次编译都会出现 

-**Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> A problem occurred starting process 'command 'ndk-build''**

最后按照其他的issue 修改具体的路径，结果就编译通过了，最后进一部分对 gradle 分析，发现在外面配置 ndk.path 也是Ok的。

**Comment by hzy87email** [comment]
@gdky005 最后按照其他的issue 修改具体的路径 能贴下那个连接吗？我想看看，谢谢~

**Comment by 1379266135** [comment]
check the JDK version . there will be a problem if the version is 1.8 . changed 1.7 .

**Comment by gdky005** [comment]
@hzy87email   #5  
![qq20150507-1 2x](https://cloud.githubusercontent.com/assets/3477872/7509820/21304174-f4c8-11e4-8d2d-8d4fb57285a2.png)

**Comment by hzy87email** [comment]
@1379266135  JDK 1.7

**Comment by hzy87email** [comment]
@gdky005 我之前照这个人的配置了 在studio1.1下编译 也是不通过的  后来换成在 imagepipeline 子项目里面的 gradle.properties 文件中得最后添加 ndk.path=/Users/XXX/Android_SDK/android-ndk-r10d 编译才过的

**Comment by gdky005** [comment]
http://blog.csdn.net/gdky005/article/details/45560423

**Comment by gdky005** [comment]
echo $NDK_HOME

**Comment by dupengyun** [comment]
android studio 1.2.1.1 build passed

**Comment by LightCity** [comment]
为什么都用中文交流？哈哈哈哈。

**Comment by gdky005** [comment]
都是自己人哈，你懂的！

**Comment by yy1300326388** [comment]
@LightCity @gdky005  你们让外国哥们咋办？还可不可以愉快的捡肥皂了。
