### ISSUE TITLE
java.lang.NoSuchMethodError: okio.Source.timeout

### ISSUE THREAD

**Issue by jinguangyue** [facebook/fresco#1631]
在小米三手机里面出现这个错误
当前版本：
compile 'com.facebook.fresco:fresco:0.9.0+'
compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.1+'

我使用 0.14.1也报这个错误

**Comment by oprisnik** [comment]
This seems to be related to OkHttp. Did you set up proguard correctly?

**Comment by jinguangyue** [comment]
Is it   compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.1+'   correctly?.
I found the following tests in the Android 5.0 this problem.

I make a network request in a waterfall stream then this problem occurs during the sliding process

**Comment by jinguangyue** [comment]
Is it   compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.1+'   correctly?.
I found the following tests in the Android 5.0 this problem.

I make a network request in a waterfall stream then this problem occurs during the sliding process

**Comment by oprisnik** [comment]
Can you try with a newer version of Fresco (1.0.0) and maybe also with OkHttp3?

```
  compile "com.facebook.fresco:imagepipeline-okhttp3:1.0.0"
```

**Comment by jinguangyue** [comment]
OK I will Use the latest version. If there are problems I will then feedback, thank you

**Comment by oprisnik** [comment]
It seems that this issue has been resolved. Let us know if this is still an issue for you and we can re-open this issue.
