### ISSUE TITLE
how get ResizeOptions in custom decoder's decode()

### ISSUE THREAD

**Issue by zetbrush** [facebook/fresco#1632]
I have large raw bitmap file (suppose it is 20MB int array of bitmap), and need to load it with different resolutions in different parts of app,
so while building custom decoder, I can't get resized options that I have set while building request.
eventually it caches large bitmap and leads to OOMs and memory leaks.

Question. how get resized options in custom decoder's decode() method, to resize large images?

**Comment by oprisnik** [comment]
I think it's currently not possible to get the `ResizeOptions` in the custom decoder. Resizing is done before the decoding step is reached, hence we don't pass down the size right now.

**Comment by zetbrush** [comment]
Thanks @oprisnik that solved the problem, also will suggest to add file path in ImageFormat.FormatChecker, to be able to differentiate custom formats by examining file path, in case when no header is reserved and format check is impossible. thanks again.

**Comment by oprisnik** [comment]
Great to hear that it worked!
You're right, having the file name (or even better the `Uri` itself) would be useful. However, currently this is based on input streams (`encodedImage.getInputStream()`) and we don't have easy access to the URI there. We would need to shuffle things around a bit.

**Comment by zetbrush** [comment]
copy that 👍
