### ISSUE TITLE
Loading pictures become  black

### ISSUE THREAD

**Issue by bingzhao0719** [facebook/fresco#1635]
when load lots of pictures with gridview , some SimpleDraweeView background become black. 
I use setImageURI in my adpater only.It happens only on xiaomi brand tv box, it is ok on other brand tv box,then OpenGLRenderer: GL error:  Out of memory  happens .At last,forgive me for my poor English!
![img_0310](https://cloud.githubusercontent.com/assets/18749734/22100328/253c5ea0-de6a-11e6-9a78-08b53af2a018.JPG)
![code2](https://cloud.githubusercontent.com/assets/18749734/22100342/328f99be-de6a-11e6-81ec-5005197ec0bb.png)

**Comment by oprisnik** [comment]
How big are your images? Do you do view recycling?
As you've noticed, it seems that OpenGL can't render all of these bitmaps. Can you try and make the images smaller? Do you use resizing or downsampling?
You could also enable the Fresco debug overlay by initializing Fresco with:


    DraweeConfig draweeConfig = DraweeConfig.newBuilder()
        .setDrawDebugOverlay(true)
        .build();
    Fresco.initialize(this, yourImagePipelineConfig, draweeConfig);


Ideally, your images should have a green background and the `I` and `D` dimensions in the overlay should approximately be the same.

**Comment by bingzhao0719** [comment]
thank you for your answers,it did solve my problem using resizing.but I find it strange that in the case of the same code, there will be no problem with the other boxes

**Comment by oprisnik** [comment]
Great to hear that you could solve the problem.

Can you please clarify what exactly you find strange? The first pictures can be loaded and displayed by the GPU. Then, there is no more memory and no more new images can be displayed.

**Comment by CarryHekangkai** [comment]
> thank you for your answers,it did solve my problem using resizing.but I find it strange that in the case of the same code, there will be no problem with the other boxes

你好,我看您应该也是国人我就不用英语了，我也跟您遇到同样的问题了，请问一下您最后怎么解决的？
SimpleDraweeView mActivityBg;
mActivityBg.setImageURI(activityInfo.getActivityBackPath());
mActivityBg.setVisibility(View.VISIBLE);
我是使用了这个方法之后就会报内存溢出、图片变黑，一断时间过后app崩溃退出。
