### ISSUE TITLE
HUAWEI mate8 cannot install application

### ISSUE THREAD

**Issue by litangyu** [facebook/fresco#1639]
Sorry I didn't find a similar Isssus, so I opened it.

My problem is that HUAWEI mate8 phone (CPU model is Kirin 950) can not install the application (App integrated Fresco)

The message on the phone is：
Reason for failure: this application is not compatible with the CPU model of this device

My App gradle file is integrated with on-demand packaging

splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'arm64-v8a', 'armeabi-v7a','armeabi'
            universalApk false
        }
    }

Can you help me？（My English is not very good, please forgive me）

**Comment by kirwan** [comment]
You are splitting the build for different architectures (x86, armeabi etc.) so are you installing the correct build on your phone? I think any of the arm builds should work for you (arm64-v8a being the best) so I'm surprised if this is failing.

Can you try removing the splits and seeing if it installs then?

**Comment by litangyu** [comment]
Okay, I'll try again. Thank you
