### ISSUE TITLE
Still image with extension .gif not blurred with Postprocessor

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#1640]
We use Giphy.com to show GIF animations. In our app firstly we want to show blurred thumbnail, then when original animated GIF is loaded we want to play original animated GIF. The problem is that Postprocessor not blurring still images provided by Giphy because they have .gif extension. Its not animated GIF.
Like this: https://media0.giphy.com/media/oOTTyHRHj0HYY/giphy_s.gif

How I can blur received image?

```
public static ImageRequest getImageRequest(String filePath) {
        return ImageRequestBuilder.newBuilderWithSource(Uri.fromFile(new File(filePath)))
                .setRotationOptions(RotationOptions.autoRotate())
                .build();
    }

    public static ImageRequest getThumbnailRequest(String thumbUrl) {
        return ImageRequestBuilder.newBuilderWithSource(Uri.parse(thumbUrl))
                .setResizeOptions(new ResizeOptions(thumbnailSize, thumbnailSize))
                .setPostprocessor(new BlurPostprocessor())
                .build();
    }

    PipelineDraweeControllerBuilder controllerBuilder = Fresco.newDraweeControllerBuilder()
                .setLowResImageRequest(getThumbnailRequest(component.getThumbUrl()))
                .setImageRequest(ImageRequest.fromUri(component.getMediaUrl()));
                .setControllerListener(controllerListener)
                .setAutoPlayAnimations(true)
                .setOldController(draweeView.getController());


        draweeView.setController(controllerBuilder.build());
```

**Comment by kirwan** [comment]
Post-processors are only applied to images held in a `CloseableStaticBitmap`. Any GIF results in a `CloseableAnimatedImage` even if it doesn't actually include an animation.

However, you can fix this with [`ImageRequestBuilder.setImageDecodeOptions(ImageDecodeOptions)`](https://github.com/facebook/fresco/blob/bf0e2f15038a6cba4b913b66db93f26169c85a24/imagepipeline/src/main/java/com/facebook/imagepipeline/request/ImageRequestBuilder.java#L215) which is set to [force static images](https://github.com/facebook/fresco/blob/0c1fa3b4c310abfe0a9d124c883f3269eed28fb8/imagepipeline-base/src/main/java/com/facebook/imagepipeline/common/ImageDecodeOptionsBuilder.java#L137).

I think that should fix your issue, so I'm going to close this. You can still reply if the problem remains.

**Comment by rafaelekol** [comment]
@kirwan Thanks, that worked.
