### ISSUE TITLE
When downloading big GIF images, progressbar finishes and then just stays there for several seconds

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#1646]
Can you include decode progress to download progress when showing progressbar? I have also same issue with big GIF images. It downloads fast, but then progressbar just stays there for several seconds, until GIF starts to play.
I found this this issue: [fresco display remote gif 5~20 seconds after downloaded](https://github.com/facebook/fresco/issues/1275) That is same issue.
I think it would be better solution to reserve 10-20% of progress bar for encoding time, than keeping progressbar almost finished and visible while image is encoded.

**Comment by kirwan** [comment]
It's a valid suggestion but I don't think these are things we're likely to change right now partly because we tend to use indeterminate progress bars.

If you'd like to contribute a PR for this, I'd be very happy to take a look at it.

**Comment by oprisnik** [comment]
We've released [Fresco v1.4.0](https://github.com/facebook/fresco/releases/tag/v1.4.0), which includes a new implementation for animated GIFs that is way more performant, including decoding. Let us know if you're still experiencing problems with 1.4.0.

**Comment by oprisnik** [comment]
As @kirwan mentioned, pull requests are welcome but I don't think we'll have time to implement this any time soon.
