### ISSUE TITLE
I defined my Hierarchy ,but setprogressImage didn't useful..

### ISSUE THREAD

**Issue by shangcongrong** [facebook/fresco#1650]
the code like this:

	new GenericDraweeHierarchyBuilder(context.getResources()).setFadeDuration(300)
                .setFailureImage(context.getResources().getDrawable(R.drawable.image_default_bg))
                .setRoundingParams(RoundingParams.fromCornersRadius(roundingRadius))
                .setProgressBarImage(context.getResources().getDrawable(R.drawable.loading_circle_gray_round))
                .build();

I want loading_circle_gray_round auto rotate loading ,but it doesn't loading...

**Comment by oprisnik** [comment]
Please take a look at our Showcase sample app. We have an example with a progress bar [here](https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeHierarchyFragment.java).

**Comment by oprisnik** [comment]
Please let us know if you still experience the issue and we can re-open this task.
