### ISSUE TITLE
AutoRotateDrawable in DraweeHolder is squeezing drawable image

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#1651]
I am trying to use indefinite progressbar in custom view via Fresco DraweeHolder. After setting code below, I got squeezed progress bar image rotating. Do I need to set dimensions for DraweeHolder?
I also can set AutoRotateDrawable dimensions, thus image is very big.

```
public void draw(Canvas canvas) {
        Drawable drawable = draweeHolder.getTopLevelDrawable();
        drawable.setBounds(0, 0, width, height);
        drawable.draw(canvas);
    }
public void loadImage(String thumbUrl, String imageUrl) {
    PipelineDraweeControllerBuilder controllerBuilder = Fresco.newDraweeControllerBuilder()
                .setControllerListener(controllerListener)
                .setLowResImageRequest(ImageRequest.fromUri(thumbUrl))
                .setImageRequest(ImageRequest.fromUri(imageUrl))
                .setOldController(draweeHolder.getController())
                .setAutoPlayAnimations(true);

        draweeHolder.setController(controllerBuilder.build());

   Drawable spinner = ContextCompat.getDrawable(context, R.drawable.spinner_24dp);

   draweeHolder.getHierarchy().setProgressBarImage(new AutoRotateDrawable(spinner, 700));
}
```
![420636c3-2a9f-4e63-964e-683a258d77ab](https://cloud.githubusercontent.com/assets/1390965/22643895/9c789992-ec8a-11e6-87a1-2badb789d3db.jpg)
![bdf296e2-d470-4551-b0ee-7d939b81373c](https://cloud.githubusercontent.com/assets/1390965/22643894/9c773890-ec8a-11e6-84a3-fad8e05f1282.jpg)

**Comment by foghina** [comment]
Have you tried passing a second parameter to `setProgressBarImage`? Like this:

```
hierarchy.setProgressBarImage(…, ScaleType.CENTER);
```

**Comment by rafaelekol** [comment]
@foghina Thanks, that did the trick 👍
