### ISSUE TITLE
Question - C4A - may someone say if it'll be open-source ?

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#1652]
Hello,

I've read this : https://code.facebook.com/posts/531104390396423/components-for-android-a-declarative-framework-for-efficient-uis/

But can't found any clue on the way this will be released or not.

I've read about Yoga https://github.com/facebook/yoga

Should someone give some clue ?

Thanks,

Eric

**Comment by kirwan** [comment]
Sorry Eric, we don't comment on future plans.
