### ISSUE TITLE
How can I Listening SimpleDraweeView already show the image？

### ISSUE THREAD

**Issue by gmm932** [facebook/fresco#1655]
How can I Listening SimpleDraweeView already show the image？
I want to get blur after show image. How can I know

**Comment by gmm932** [comment]
How can I Listening SimpleDraweeView already show the image？
I want to get blur after show image. How can I know

**Comment by oprisnik** [comment]
Take a look our [postprocessor](http://frescolib.org/docs/modifying-image.html) documentation.

You have to add the postprocessor to the image request:
```
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
    .setPostprocessor(yourPostprocessor)
    .build();
```

Our Showcase sample app also has some sample postprocessors [here](https://github.com/facebook/fresco/tree/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/postprocessor) that are used [here](https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/ImagePipelinePostProcessorFragment.java).

**Comment by gmm932** [comment]
Thankyou！
