### ISSUE TITLE
How to set URI in failure Hierarchy?

### ISSUE THREAD

**Issue by anandcpadiya** [facebook/fresco#1659]
I have a scenario in which I have to try another URI if one URI fails to get an image.
DH.setFailureImage accepts either Drawable or a resource id.
Please do let me know if there is any way to provide alternate URI or failure URI.
Thanks In Advance.

**Comment by oprisnik** [comment]
You can add a `ControllerListener` and try a different URI in `onFailure`.
See http://frescolib.org/docs/listening-download-events.html
