### ISSUE TITLE
when fresco can support ico format .

### ISSUE THREAD

**Issue by zhangmaoyong34** [facebook/fresco#1670]
Now from h5's favicon.ico
but not support on android phone

when fresco can support ico format.

thanks.

**Comment by foghina** [comment]
We're not going to support this as part of fresco. But, we do support custom decoders, so nothing is stopping you from adding one for this format. Unfortunately though, we don't yet have any docs on that, so I'm assigning this to @oprisnik as he wanted to add them.

**Comment by zhangmaoyong34** [comment]
thanks @oprisnik ,Look forward to your results。
