### ISSUE TITLE
Ignore the "placeholderScaleType" set in xml

### ISSUE THREAD

**Issue by pavel163** [facebook/fresco#1673]
SimpleDraweeView ignores the "placeholderScaleType" set in xml.

**Comment by foghina** [comment]
See eacc313 - setting `placeholderImageScaleType` in XML works correctly. Make sure you don't mix-and-match setting the scaleType in XML and the actual image in Java. If you're setting the image in Java just do e.g.:

```java
draweeView.getHierarchy().setPlaceHolderImage(R.drawable.placeholder, ScaleType.CENTER_INSIDE);
```

**Comment by pavel163** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<com.facebook.drawee.view.SimpleDraweeView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/detail_image"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:actualImageScaleType="fitCenter"
    app:placeholderImageScaleType="fitCenter" />`

This code does not work. But 

`private fun addProgressBar(imageView: SimpleDraweeView) {
        val progressBar = CircleProgressBarDrawable()
        progressBar.backgroundColor = Color.GRAY
        progressBar.color = Color.WHITE
        val builder = GenericDraweeHierarchyBuilder(activity.resources)
        builder.actualImageScaleType = ScalingUtils.ScaleType.FIT_CENTER
        builder.placeholderImageScaleType = ScalingUtils.ScaleType.FIT_CENTER
        imageView.hierarchy = builder.setProgressBarImage(progressBar).build()
    }`

This code works.

**Comment by foghina** [comment]
@pavel163 either set both the image and the scaleType in XML, or set them both in code. This works:

```xml
<com.facebook.drawee.view.SimpleDraweeView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:placeholderImage="@drawable/my_placeholder"
    app:placeholderImageScaleType="fitCenter" />
```

As well as this:

```kotlin
draweeView.hierarchy.setPlaceholderImage(R.drawable.my_placeholder, ScaleType.FIT_CENTER);
```

However this won't work, because setting the placeholder image in code overrides the scaleType set in XML:

```xml
<com.facebook.drawee.view.SimpleDraweeView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:placeholderImageScaleType="fitCenter" />
```

```kotlin
draweeView.hierarchy.placeholderImage = R.drawable.my_placeholder;
```

**Comment by pavel163** [comment]
Thank you very much
