### ISSUE TITLE
Images stretched, can't adjust them

### ISSUE THREAD

**Issue by TestDotCom** [facebook/fresco#1675]
### Description

I would like to display some images downloaded from Giphy, with a RecyclerView, GridLayout and CardView, but I get a huge withe space between each cell.

[here there's a screenshot](http://i.imgur.com/JWXc9Jz.png)

### Reproduction

`
<android.support.v7.widget.CardView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:card_view="http://schemas.android.com/apk/res-auto"
        android:id="@+id/card_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        card_view:cardCornerRadius="6dp"
        card_view:cardUseCompatPadding="true">

        <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/gif"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            fresco:actualImageScaleType="centerCrop"
            fresco:failureImage="@drawable/ic_error_black_24dp"
            fresco:placeholderImage="@drawable/ic_android_black_24dp"
            fresco:viewAspectRatio="1.33"/>
    </android.support.v7.widget.CardView>
`

`
public class GiphyView
        extends RecyclerView
        implements GiphyPresenter.ViewBind {
    ...

    private void initView(Context context) {
        CustomApplication.get(context).getGiphyComponent().inject(this);

        //setLayoutManager(new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL));
        setLayoutManager(new GridLayoutManager(context, 2, VERTICAL, false));
        setAdapter(mAdapter);
    }

    @Override
    protected void onDetachedFromWindow() {
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        imagePipeline.clearCaches();

        mGiphyPresenter.detachVu();

        super.onDetachedFromWindow();
    }

    private class GiphyAdapter extends RecyclerView.Adapter<GiphyViewHolder> {
        @Override
        public GiphyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            return new GiphyViewHolder(
                    LayoutInflater.from(parent.getContext())
                            .inflate(R.layout.giphy_cell, parent, false));
        }

        @Override
        public void onBindViewHolder(GiphyViewHolder holder, int position) {
            holder.setGif(mGiphyPresenter.getItemImage(position));
        }

    class GiphyViewHolder extends ViewHolder {
        ...

        void setGif(String url) {
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setUri(url)
                    .setAutoPlayAnimations(true)
                    .build();
            mGif.setController(controller);
        }
    }
}
`

### Additional Information

* Fresco version: 1.1.0
* Platform version: SDK emulator, android 7.1

[Rest of the code if it can help](https://github.com/TestDotCom/BackstackRoot)

**Comment by TestDotCom** [comment]
Resolved! The culprit was linearLayout at the root.

**Comment by oprisnik** [comment]
Great!
I have added a sample that shows how to use `CardView`, `Fresco` and `RecyclerView` with a grid layout here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeRecyclerViewFragment.java

Stackoverflow discussion for this issue: http://stackoverflow.com/questions/42353478/image-height-stretched-simpledraweeview
