### ISSUE TITLE
NullPointerException  at com.facebook.drawee.backends.pipeline.Fresco.newDraweeControllerBuilder(Fresco.java:54)

### ISSUE THREAD

**Issue by helloyzp** [facebook/fresco#1679]
this is a online bug in my app:
java.lang.NullPointerException: Attempt to invoke virtual method \'com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.get()\' on a null object reference at com.facebook.drawee.backends.pipeline.Fresco.newDraweeControllerBuilder(Fresco.java:54) at 
.....
it means the sDraweeControllerBuilderSupplier member of class Fresco.java is null when execute the code 
'sDraweeControllerBuilderSupplier.get()' in the method newDraweeControllerBuilder() of class Fresco.java,
but I already execute the "Fresco.initialize(this)" in the onCreate() method of Application,
so how to solve this issue?
thank you very much!

**Comment by kirwan** [comment]
That definitely shouldn't happen if you're calling `Fresco.initialize()` before creating the drawee.

Can you tell me where the drawee is being created?

My best guess right now is that you're setting the content view in `Activity.oncreate()` before calling `super.onCreate()`, which could result in the application class being initiated too late.

If I'm wrong about that, I'd need more information to help you understand why this has gone wrong.

I'd also suggest adding a Logcat call just before your call to `Fresco.initialize(this)` to verify whether that's called.

**Comment by Springws** [comment]
hi, I meet the problem too.   I use Fresco play gif in a viewPager.  when I quiet the application I crash and log is the same.  it occur on some phones.    thank you

**Comment by oprisnik** [comment]
How are you initializing Fresco? This shouldn't happen.

**Comment by oprisnik** [comment]
Please make sure that Fresco is initialized correctly. If you're still seeing this crash, let us know with repro steps.
