### ISSUE TITLE
rounding corners cannot support  Gif

### ISSUE THREAD

**Issue by lushan1314** [facebook/fresco#168]
i saw the document , there are have not a good solutions,

but i used another way in the past ,  used PorterDuffXfermode  and Mode.DST_IN, it's just looks good.

how about this way?can support used it?

**Comment by tyronen** [comment]
Rounded corners are supported for GIFs. If the GIF is an animation, you must specify an overlay color for it to work.  Something like:

```xml
fresco:roundWithOverlayColor="@color/blue"
```

Let me know if this works for you.

**Comment by lushan1314** [comment]
yeah, thank you ! 
i  know that ... Sometimes it does work, but I'm afraid this method won't work in my here,
i can't  use "roundWithOverlayColor",beacuse  there cannot use the background color

in my case ,  The background is uncertain, it could be a picture  , or  used other color.

so , In this case, have any good Suggestions?  thank you a lot.

**Comment by lushan1314** [comment]
execuse me, i have another  question.

i saw [This link](http://frescolib.org/docs/datasources-datasubscribers.html#_) has a piece of code:
        dataSource.subscribe(dataSubscriber, executor);
i don't see the __executor__ detailed description.  
my question is : the __executor__ need management by myself?

How to use it correctly?  
thank you.

**Comment by lushan1314** [comment]
execuse me, i have another question.

i saw This link has a piece of code:
    dataSource.subscribe(dataSubscriber, executor);
i don't see the executor detailed description.

my question is : the executor need management by myself?

How to use it correctly?

thank you.

**Comment by lushan1314** [comment]
execuse me, i have another question.

i saw This link has a piece of code:
__dataSource.subscribe(dataSubscriber, executor);__
i don't see the _executor_ detailed description.

my question is : the _executor_ need management by myself?

How to use it correctly?

thank you.

**Comment by lushan1314** [comment]
execuse me, i have another question.

i saw This link has a piece of code:
__dataSource.subscribe(dataSubscriber, executor);__
i don't see the __executor__ detailed description.

my question is : the __executor__ need management by myself?

How to use it correctly?

thank you.

**Comment by lushan1314** [comment]
execuse me, i have another question.

i saw [This link](http://frescolib.org/docs/datasources-datasubscribers.html#_) has a piece of code:
__dataSource.subscribe(dataSubscriber, executor);__
i don't see the __executor__ detailed description.

my question is : the __executor__ need management by myself?

How to use it correctly?

thank you.

**Comment by plamenko** [comment]
There is no way (as far as I know) of PorterDuffXfermode being sufficient to draw rounded corners (unless, of course, a temporary bitmap is being used). I've seen some attempts that might happen to work in some cases, but this is Android bug and/or yet another software/hardware rendering inconsistency.

For Executor, see http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executor.html
We should probably add some documentation on when to use a background thread executor, ui thread executor or same thread executor.

**Comment by lushan1314** [comment]
ok,i got it, i will try another way in my case,thank you for your answer!
