### ISSUE TITLE
Can't set timeout when using imagePipeline.fetchDecodedImage download network image

### ISSUE THREAD

**Issue by JuHonggang** [facebook/fresco#1680]
### Description

I use okhttp set timeout, and use it to config fresco in application's onCrate. but when using ImagePipeline.fetchDecodeImage to download network image, it's timeout invalid. when downloading a big image, It will cost long time. 

init fresco code:

`

	okhttp3.OkHttpClient httpClient = new okhttp3.OkHttpClient.Builder()
	.connectTimeout(5, TimeUnit.SECONDS)
	.readTimeout(10, TimeUnit.SECONDS)
	.build();
	ImagePipelineConfig imageConfig = OkHttpImagePipelineConfigFactory.newBuilder(this, httpClient).build();
	Fresco.initialize(this, imageConfig);
`
        
download image coder:
`

	DataSubscriber dataSubscriber = new BaseDataSubscriber<CloseableReference<CloseableBitmap>>() {
		@Override
		public void onNewResultImpl(DataSource<CloseableReference<CloseableBitmap>> dataSource) {
		    
		}

		@Override
		public void onFailureImpl(DataSource dataSource) {
		    
		}
	};

	ImagePipeline imagePipeline = Fresco.getImagePipeline();
	ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url)).build();
	DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(request, context);
	dataSource.subscribe(dataSubscriber, CallerThreadExecutor.getInstance());
`
### Reproduction

Using ImagePipeline to download network image.

### Additional Information

* Fresco version: [v1.1.0]
* imagepipeline-okhttp3 version: [v0.12.0]

Please check it. Thank you very much!

**Comment by kirwan** [comment]
Sorry, I don't quite understand.

Are you saying that the timeout isn't respected or that there are specific images where you want to allow more time?

**Comment by JuHonggang** [comment]
the timeout isn't respected.

**Comment by kirwan** [comment]
I suspect this would need to be worked out in the OkHttp layer. If you try making a direct request to OkHttp for the same image in those circumstances, do you see the request time out as you expect?

In `OkHttpNetworkFetcher` we provide an implementation of `okhttp3.Callback` which implements both callback methods so if one of those is triggered, the failure should return through the pipeline.

**Comment by JuHonggang** [comment]
@kirwan Thank  you very much.
I found the answer,  okhttp set timeout is not exact.

**Comment by eldk** [comment]
Hello,

Should you give a try to OkHttp 3.6 ? https://github.com/facebook/fresco/pull/1668 

Are you calling HTTP2 urls ?

How are you initializing OkHttp ?

Thanks,

Eric

**Comment by kirwan** [comment]
Sorry, I closed when I saw @JuHonggang had responded but I'm reopening to see whether @eldk's questions help further.

**Comment by JuHonggang** [comment]
@eldk 

I used okhttp v3.0.1

init code:

`

	okhttp3.OkHttpClient httpClient = new okhttp3.OkHttpClient.Builder()
		.connectTimeout(2, TimeUnit.SECONDS)
		.readTimeout(2, TimeUnit.SECONDS)
		.build();
	ImagePipelineConfig imageConfig = OkHttpImagePipelineConfigFactory.newBuilder(this, httpClient).build();
	Fresco.initialize(this, imageConfig);
`

**Comment by eldk** [comment]
Hello,

So, you mean that when you set connectTimeout and readTimeout to OkHttp, picture fetch/download and decode is not canceled when one OkHttp timeout is reached ?

Are you requesting HTTP2 urls ?

What's the Android API used for the tests ?

If you read here : http://frescolib.org/docs/using-image-pipeline.html, I think it's up to you to close the datasource if timeout is reached (as the connection is used and data read, okHttp will not close it) :

"Drawees keep these references alive for as long as they need their image, and then call the .close() method on these references when they are finished with them. If your app is not using Drawees, it must do the same."

May be I misunderstood ?

Thanks

Eric

**Comment by JuHonggang** [comment]
@eldk 

Hello,

You understand correctly.

I download image with http/1.1 url.

I read the document about using-image-pipeline, and encapsulated a download method. my code is here:
`

    public static void downloadImage(Context context, String url, final DownloadListener listener) {
        DataSubscriber dataSubscriber = new BaseDataSubscriber<CloseableReference<CloseableBitmap>>() {
            @Override
            public void onNewResultImpl(DataSource<CloseableReference<CloseableBitmap>> dataSource) {
                if (listener != null) {
                    if (dataSource.isFinished()) {
                        CloseableReference<CloseableBitmap> imageReference = dataSource.getResult();
                        if (imageReference != null) {
                            final CloseableReference<CloseableBitmap> closeableReference = imageReference.clone();
                            try {
                                CloseableBitmap closeableBitmap = closeableReference.get();
                                Bitmap bitmap = closeableBitmap.getUnderlyingBitmap();
                                if (bitmap != null && !bitmap.isRecycled()) {
                                    listener.downloadFinish(bitmap);
                                } else {
                                    listener.downloadFailure();
                                }
                            } catch (Exception e) {
                                listener.downloadFailure();
                            } finally {
                                imageReference.close();
                                closeableReference.close();
                            }
                        } else {
                            listener.downloadFailure();
                        }
                    } else {
                        listener.downloadFailure();
                    }
                }
            }

            @Override
            public void onFailureImpl(DataSource dataSource) {
                if (listener != null) {
                    listener.downloadFailure();
                }
            }
        };

        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url)).build();
        DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(request, context);
        dataSource.subscribe(dataSubscriber, CallerThreadExecutor.getInstance());
    }
`

I try a test, In slow speed network(use Charles and start throttling network), I set read timeout 10 **milliseconds**, the onFailureImpl is called, but when read timeout is set 10 **seconds**,  onFailureImpl is not called, the image will cost about 2 minutes to download. 

You can test the url: http://7xrqzm.com1.z0.glb.clouddn.com/bg.jpg

Thanks

JuHonggang

**Comment by eldk** [comment]
http://stackoverflow.com/questions/32267251/read-and-write-timeouts-behavior

**Comment by JuHonggang** [comment]
I understood, thank you very much.

**Comment by eldk** [comment]
Here one example for a progressListener for OkHttp : https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java .

It is for fetched bytes, but may be should be adapted to set a timeOut deadLine on fetch/download progress then/and close Fresco closeable.

**Comment by kirwan** [comment]
Thanks @eldk for your responses here. It looks like I can close the issue now.

If there are more questions, just reply and we'll re-open.
