### ISSUE TITLE
No fade-in animation for Gifs 

### ISSUE THREAD

**Issue by storix** [facebook/fresco#1681]
Hi,

I tried to display in a `RecyclerView` a bunch of Gifs (from small to medium size). Everything works fine, performance is ok. However, there is no fade in animation when Gifs are loaded. They are just being appeared immediately. Setting in XML `fresco:fadeDuration="300"` has no effect. I'm using Fresco Version 1.1.0.

Is it expected behavior? Are there any way to set a custom animation to present the downloaded Gifs more smoothly?

**Comment by kirwan** [comment]
The view should fade in just like any other image.

Animations go through a different decode path though so it's quite likely there's a timing problem for you here where the first frame is still being decoded when the fade in occurs.

I'm not sure whether this will fix it for you, but you can try setting `ImageDecodeOptions` with the option set to decode the preview frame.

**Comment by storix** [comment]
Thank you! This fixed the issue:

```
val imageDecodeOptions = ImageDecodeOptionsBuilder()
                .setDecodePreviewFrame(true)
                .build()
```
