### ISSUE TITLE
Dynamically link jpegturbo lib for reduce library size.

### ISSUE THREAD

**Issue by desmond1121** [facebook/fresco#1685]
I've noticed native lib **jpegturbo** is both statically linked in bellowing module:

- **imagepipeline** (See  [imagepipeline/Android.mk#L28](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/jni/imagepipeline/Android.mk#L28)) 
- **static-webp** (See [static-webp/Android.mk#L37](https://github.com/facebook/fresco/blob/master/static-webp/src/main/jni/static-webp/Android.mk#L37))

It's size is 165KB kb in armeabi-v7 and 409KB in x86 (so big!), would cause a lot of redundant apk size!

Since every body who use **static-webp** library would and must already have  **imagepipeline** in their app, so I think we can do some trick:

- make fb_jpegturbo as a shared library and dynamically link them in two modules;
- after ndk-build success in **static-webp**, delete fb_jpegturbo.so in this module otherwise it would conflict with **imagepipeline**'s.

If this idea is accepted, I would give a PR in several days.

**Comment by lambdapioneer** [comment]
Hi @desmond1121, thanks for raising this issue! Having both projects statically linking against a larger library sounds bad and we should fix this. Your solution sounds good and hopefully there's an easy way to do this.

Definitely looking forward to read your PR! 👍 Would great to have some numbers on the size win.

**Comment by desmond1121** [comment]
@lambdapioneer PR #1686
