### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by beraybentesen** [facebook/fresco#1687]
### Description

High memory usage when compared to Glide with SimpleDraweeView

### Reproduction

Default settings, same application, same data with same RecyclerView Adapter.

![17092408_10155119514154511_604692076_n](https://cloud.githubusercontent.com/assets/6421164/23522574/26ab49ca-ff8c-11e6-97cf-213ab275d845.png)

Cropping images while downloading worked so it uses between 30-40 but I want to download original size. 

### Additional Information

* Fresco version: Latest
* Platform version: Android 6.0 - Android 7.1.1 - Android 5.0

**Comment by kirwan** [comment]
Can you provide more information and code showing how you use Fresco within your RecyclerView?

What you said about cropping might explain it though (if you mean resizing) as Glide downsamples automatically.

**Comment by beraybentesen** [comment]
// Default Fresco  
 propertiesViewHolder.imageView_property.setImageURI(modelProperty.getPhoto());

// Default Glide 
 Glide.with(context).load(modelProperty.getPhoto()).into(propertiesViewHolder.imageView_property);

 Custom setups to solve memory problem 


        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(modelProperty.getPhoto()))
                .setResizeOptions(new ResizeOptions(130, 130))
                .build();
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(propertiesViewHolder.imageView_property.getController())
                .setImageRequest(request)
                .build();

        propertiesViewHolder.imageView_property.setController(controller);

**Comment by kirwan** [comment]
@beraybentesen The key difference here I think is that Glide automatically downscales images to the size needed for the view. It slightly delays the request if necessary until that's known.

Fresco doesn't currently do this, though I think there's a strong case to add similar functionality. That's why you currently need to explicitly set `ResizeOptions` if you're loading a larger image than you need for the view.

**Comment by erikandre** [comment]
Closing as this is the expected behaviour when not using ResizeOptions to control the final bitmap size.
