### ISSUE TITLE
roundAsCircle won't work correctly

### ISSUE THREAD

**Issue by beraybentesen** [facebook/fresco#1688]
### Description

Round as circle method won't work as expected.

### Reproduction

![screen shot 2017-03-02 at 22 09 05](https://cloud.githubusercontent.com/assets/6421164/23522676/8cea413c-ff8c-11e6-8fdb-5c06f6510729.png)

XML Code : 

` <com.facebook.drawee.view.SimpleDraweeView
        android:layout_centerHorizontal="true"
        android:layout_alignBottom="@id/view_background"
        android:layout_width="72dp"
        android:layout_height="72dp"
        app:roundWithOverlayColor="@color/gray"
        app:fadeDuration="0"
        app:roundAsCircle="true"
        app:roundingBorderWidth="1dp"
        app:roundingBorderColor="@color/gray_light"
        tools:ignore="ContentDescription" />`

### Additional Information

* Fresco version: Latest
* Platform version: Android 5.0+

**Comment by kirwan** [comment]
Can you please make clear what the reproduction is showing? I don't see from the XML anything that's obviously wrong in the image, depending on where the red/white portion is drawn from.

Is the red/white a view behind the drawee view or the image itself?
Has the image loaded at this point?

It might be more useful to see an image showing a photo within the drawee view. And also the Java code you're using to populate the image itself.

**Comment by oprisnik** [comment]
I assume this issue has been resolved. Let us know if that is not the case.
