### ISSUE TITLE
JPEGs in content provider don't display

### ISSUE THREAD

**Issue by aliang5820** [facebook/fresco#169]
when I use Content provider for SimpleDraweeView,some folder's uri can display success,but some failed.
![314c f7p398og v9q e c](https://cloud.githubusercontent.com/assets/8259919/7228762/17e8561a-e78f-11e4-9393-ff4167e1130a.png)
![24e79a4d469e066867a76b4feffb2bf5](https://cloud.githubusercontent.com/assets/8259919/7228767/1f0922b2-e78f-11e4-8bd2-28eb405b4a18.jpg)

the first folder's image uri always fail ,but second folder's image uri all success.

**Comment by tyronen** [comment]
Can you tell us the difference between the first and second folders' URIs?

**Comment by aliang5820** [comment]
success Uri:     content://media/external/images/media/532110
failed Uri:         content://media/external/images/media/528034

**Comment by tyronen** [comment]
Are these two images the same format? ie are they both JPEG images? or is one of them different from the other?

**Comment by aliang5820** [comment]
yeah, one is png format, another is jpg format.
png can display,but jpg can't display.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by erikandre** [comment]
Cleaning up old issues.
