### ISSUE TITLE
Play a local gif file,But  controller.getAnimatable()  animatable is null?

### ISSUE THREAD

**Issue by songmeitao** [facebook/fresco#1697]
AbstractDraweeController build = Fresco.newDraweeControllerBuilder()
                    .setAutoPlayAnimations(true)
                    .setUri(Uri.fromFile(new File(path)))
                    .setTapToRetryEnabled(true)
                    .build();

Animatable animation = build .getAnimatable();
animation  is null.

**Comment by oprisnik** [comment]
The animatable will be null until the final image has been set. You can use a ControllerListener instead, see http://frescolib.org/docs/animations.html
