### ISSUE TITLE
Animatable in Android N while animatable.start() faild

### ISSUE THREAD

**Issue by WTree** [facebook/fresco#1698]
Animatable in Android N while animatable.start() faild,but in screen off->on the Animatable will run

**Comment by erikandre** [comment]
Hi @WTree!

Thank you for submitting the bug report.

I tried (and failed) to reproduce this on both an Android 7.0 device and Genymotion.
Could you please provide some additional information to help us investigate the issue?

Either a more detailed step by step or code sample would be very helpful. Thanks!
Also, to be clear, is it a GIF you are loading or some other form of animated image?

**Comment by WTree** [comment]
Seems to be able to solve this problem by delay

**Comment by erikandre** [comment]
OK, that's good :)

At what point are you calling .start()? Are you using a ControllerListener to get hold of the Animatable after it has been loaded? (like described here: http://frescolib.org/docs/animations.html)

**Comment by oprisnik** [comment]
You shouldn't use a fixed delay. A `ControllerListener` is the way to go :) See also #1697
