### ISSUE TITLE
Supporting other widget?

### ISSUE THREAD

**Issue by MarkMjw** [facebook/fresco#17]
The ImageView can be replaced by  SimpleDraweeView in Fresco, but is Fresco supporting other widgets in Android, such as TextView or Layout,sometimes we need loading an image to the background of view?

**Comment by plamenko** [comment]
One way of achieving that is to subclass the view in question (E.g. TextView). In that subclass you can have a DraweeHolder and you can use its top-level-drawable as a regular drawable. You must be careful to forward attach/detach events properly to the holder.
See: http://frescolib.org/docs/writing-custom-views.html#_
