### ISSUE TITLE
The WebP animation twinkles

### ISSUE THREAD

**Issue by notice501** [facebook/fresco#1700]
Hi, I use Fresco to play webp animations, but sometimes it do not work well, every frame is flashing, may be loaded too slowly?

Here is the code, contains the flashing webp file:
```
        Uri uri = Uri.parse("http://77flrh.com1.z0.glb.clouddn.com/038B98F02B26B70DF0DF8EF62257F9EB.webp");
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setAutoPlayAnimations(true)

                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo, final
                    Animatable animatable) {
                        animatable.start();
                    }
                })
                .build();
        SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
        draweeView.setController(controller);
```

**Comment by erikandre** [comment]
Hi @notice501 !

Thank you for submitting the bug report. I managed to reproduce the issue using the provided URL.

I do notice that there seems to be something a bit odd with that WEBP file. When loaded in Chrome (on desktop and mobile) the transparency does not work correctly until the animation has looped once.

I can not reproduce this issue when trying to play other animated WEBP files, so I'm thinking that it might be an issue with the file itself. It might be a good idea to try different tools or different settings when exporting the animation (like trying to export it without alpha to see if the glitch is still there).

**Comment by notice501** [comment]
Hi, thanks for your reply.
I export animations with the guide from [Google](https://developers.google.com/speed/webp/docs/webpmux). Almost every file has the same issue, like [this one](http://77flrh.com1.z0.glb.clouddn.com/output%287%29.webp). Do you have some suggestions about tools or something else?

**Comment by notice501** [comment]
By the way, I use [YYImage](https://github.com/ibireme/YYImage) to play WebP animation for IOS, everything works well.

**Comment by erikandre** [comment]
There are a couple of interesting options you could try experimenting with. For example the "-bgcolor A,R,G,B" option (try setting a background with no alpha) or the options related to the dispose method for each frame.

**Comment by notice501** [comment]
I almost tried every option……And I can't find out the problem what you mentioned on Chrome. Is that possible a performance issue? Can I preload every frame to memory cache before playing the animation?

**Comment by notice501** [comment]
I find out that the problem is related to the frame rate of the animation. when I use the same resources which I mentioned before, but exported with higher frame rate, the flashing is gone. But I still cannot find out why. Do you have any idea?

**Comment by erikandre** [comment]
@notice501 , I suspect it could be an issue in `libwebp` since that is where the actual animation is handled. We are currently a bit behind the latest version of this library so there is always a chance that upgrading could resolve it. This will require quite a bit of testing though, so it's not something that will happen in the very short term.

**Comment by notice501** [comment]
Thanks, look forward to solving.

**Comment by UFreedom** [comment]
Is there any progress in this problem? 
I have the same problem in use Fresco，The picture will flash several times at the beginning.
But when I use YYImage to play WebP animation for IOS, everything works well with the same WebP file.

Also,I have try to change the frame rate of the animation or set a background with no alpha ,But no improvement has been made，

**Comment by erikandre** [comment]
@UFreedom The next release of Fresco will contain an updated version of libwebp (0.6.0), hopefully this will resolve this problem.

**Comment by UFreedom** [comment]
@erikandre 

Have you found the reason for the specific problem? Or does libwebp know the problem?

**Comment by oprisnik** [comment]
We've released [Fresco v1.4.0](https://github.com/facebook/fresco/releases/tag/v1.4.0), which includes a new implementation for animated GIFs that is way more performant, especially in the case where you display multiple GIFs. Let us know if you're still experiencing problems with 1.4.0.

**Comment by UFreedom** [comment]
@erikandre @oprisnik 
This is exciting news. I've just updated to the latest version(1.4.0), tested all the webp files that have problems and found no problems. all of the problem have been resolved.

You've done a great job. Thank you very much for your support during this time。

**Comment by oprisnik** [comment]
Thanks! Great to hear that it works now!
