### ISSUE TITLE
MediaVariations item never delete from database

### ISSUE THREAD

**Issue by xjy2061** [facebook/fresco#1702]
It seems there is no code for deleting item from `media_variations_index` database, the database file size will bloat continuously, is that expected?

**Comment by FtheGFW** [comment]
BTW, I'm expecting webp image to be correctly used as a variant, when will that be supported ? @kirwan

**Comment by kirwan** [comment]
Thanks for raising these issues, which are both part of media variations still being in development.

I'm looking at them both now and they should be resolved very soon.

**Comment by a-d-collins** [comment]
I'm coming in late here, but just out of curiosity, what is the desired entry-deletion behavior of the MediaVariationsIndexDatabase? Is the deletion of an individual entry supposed to be allowed? Or is the dropping of a db table the only means of deleting entries?

In either case, are specific events supposed to trigger the deletion of an entry or entire db table?

After a preliminary search through the codebase, the only media variations SQL deletion logic that I can find is the `MediaVariationsIndexDatabase.SQL_DELETE_ENTRIES` string. This is supposed to be executed by `MediaVariationsIndexDatabase.onUpgrade()`, which is called by `MediaVariationsIndexDatabase.onDowngrade()` but there is no existing logic that invokes that method.

**Comment by zmroczek** [comment]
Closing as we're removing the Media Variations support.
