### ISSUE TITLE
Media variations not working if candidate not a jpeg image

### ISSUE THREAD

**Issue by kirwan** [facebook/fresco#1707]
Self-creating an issue to track this.

@FtheGFW raised PR #1630 to fix this but it involved changes to the `ProgressiveJpegParser`. We shouldn't get into that class if we're not decoding a jpeg. This comes from the previous assumption that non-final images would always be progressive jpegs.

**Comment by FtheGFW** [comment]
👍  hopes this change would be included in the next release

**Comment by kirwan** [comment]
Yes, it just missed 1.2.0 but another release will follow soon.
