### ISSUE TITLE
SimpleDraweeSpanTextView : some images disappear when it starts a newline sometimes

### ISSUE THREAD

**Issue by nirack** [facebook/fresco#1708]

**Comment by nirack** [comment]
we are using SimpleDraweeSpanTextView (drawee-span) to show text and images,but sometimes some images just disappear and leave empty spaces there when it starts a new line, sometimes it's ok,pretty wired.

**Comment by oprisnik** [comment]
Do you have a more concrete repo for this? We have a `DraweeSpan` sample in our Showcase sample app here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeSpanSimpleTextFragment.java

Can you repro the issue there?

**Comment by nirack** [comment]
@oprisnik 
sorry i don't know how to repro the issue there .it's my first time to use this :(
it's something like a chat room ,we use DraweeSpanTextView to render user's messages,those messages could only contain pure text info or could alse have some images too.
If  one message were long enough,those images in the end would could disppear , for example [拜拜][拜拜][拜拜][拜拜][拜拜][拜拜][拜拜][拜拜]
here 
[拜拜] will be treated as an image ,an ImageSpan , 
if everything goes right ,there shall be eight same images,but it turns out to be empty spaces and then start a new line,  and in the new line there will be one or two images 

here are some of my code 
//styleParam.styleType indicates  if this span is an image or just text or something else,
when (styleParam.styleType) {
                "img" -> {//if it is image 
                    indexes?.forEach {   // this "indexes" is a list of image span's position in the whole text info
                        index ->
                        run {
// if the image is an local resource image 
                            if (("local" == styleParam.source && StringHelper.isNotEmpty(paramValue) && paramValue!!.toInt() >= 0)
                                    || styleParam.preffix == "emoji") {
                                val resId: Int = ImageUtils.getLocalImageResid(paramValue, styleParam)
                                //set this span's width and height 
                                var specifiedWidth = dip(15)
                                var specifiedHeight = specifiedWidth

                                if (styleParam.preffix == "user-level") {
                                    specifiedHeight = dip(15)
                                    specifiedWidth = dip(29)
                                }
//problem goes here and below
                                builder.setImageSpan(context, resId, index, index, specifiedWidth, specifiedHeight)

                            } else if ("remote" == styleParam.source) {
//problem also goes here 
                                builder.setImageSpan(context, StringHelper.getOssImgUrl(paramValue!!), index, dip(15), dip(15))
                            }

                        }
                    }
                }
                "basic" -> {
                    indexes?.forEach { index -> forEachBasicSpan(index, styleParam, builder) }
                }
                else -> {
                    indexes?.forEach { index -> forEachBasicSpan(index, styleParam, builder) }
                }
            }



any other things shoud i provide ,let me know please.
thanks !!!!

**Comment by nirack** [comment]
@oprisnik 
sorry i don't know how to repro the issue there .it's my first time to use this :(
it's something like a chat room ,we use DraweeSpanTextView to render user's messages,those messages could only contain pure text info or could alse have some images too.
If  one message were long enough,those images in the end would could disppear , for example [拜拜][拜拜][拜拜][拜拜][拜拜][拜拜][拜拜][拜拜]
here 
[拜拜] will be treated as an image ,an ImageSpan , 
if everything goes right ,there shall be eight same images,but it turns out to be empty spaces and then start a new line,  and in the new line there will be one or two images 

here are some of my code 
//styleParam.styleType indicates  if this span is an image or just text or something else,
when (styleParam.styleType) {
                "img" -> {//if it is image 
                    indexes?.forEach {   // this "indexes" is a list of image span's position in the whole text info
                        index ->
                        run {
// if the image is an local resource image 
                            if (("local" == styleParam.source && StringHelper.isNotEmpty(paramValue) && paramValue!!.toInt() >= 0)
                                    || styleParam.preffix == "emoji") {
                                val resId: Int = ImageUtils.getLocalImageResid(paramValue, styleParam)
                                //set this span's width and height 
                                var specifiedWidth = dip(15)
                                var specifiedHeight = specifiedWidth

                                if (styleParam.preffix == "user-level") {
                                    specifiedHeight = dip(15)
                                    specifiedWidth = dip(29)
                                }
//problem goes here and below
                                builder.setImageSpan(context, resId, index, index, specifiedWidth, specifiedHeight)

                            } else if ("remote" == styleParam.source) {
//problem also goes here 
                                builder.setImageSpan(context, StringHelper.getOssImgUrl(paramValue!!), index, dip(15), dip(15))
                            }

                        }
                    }
                }
                "basic" -> {
                    indexes?.forEach { index -> forEachBasicSpan(index, styleParam, builder) }
                }
                else -> {
                    indexes?.forEach { index -> forEachBasicSpan(index, styleParam, builder) }
                }
            }



any other things shoud i provide ,let me know please.
thanks !!!!

**Comment by nirack** [comment]
@oprisnik problem solved,it's nothing about DraweeSpan,it is about TextView,  as mentioned before , i used to translate   [拜拜][拜拜][拜拜][拜拜][拜拜][拜拜][拜拜][拜拜]   in to eight empty strings (" ") ,that would cause this issue , but if i changed " " into any string else ,it will work just fine.

thanks anyway.
