### ISSUE TITLE
Request Priority won't work ?

### ISSUE THREAD

**Issue by sdqhzhm** [facebook/fresco#1710]
### Description
Images that are currently visible on screen won't fetch first when pretch a lot images to disk,
and “Priority” has no obvious logical calls in source code.

* Fresco version: 1.1.0
* Platform version: 6.X

**Comment by kirwan** [comment]
You're right, unless you've written your own network fetcher priorities don't have an effect. Internally we use a network layer which does support these but OkHttp doesn't at this time.

See https://github.com/square/okhttp/issues/1361

I'll update our docs to make this point clear.
