### ISSUE TITLE
localfile  path :   /storage/emulated/0/Tencent/QQfile_recv/%Q}DEE1YCE9EJ7%R08X1%ER.png   load fail

### ISSUE THREAD

**Issue by Eminem8080** [facebook/fresco#1721]
`SimpleDraweeView view = getView(viewId);
        Uri uri = Uri.parse("file://" + imgUrl);
        view.setImageURI(uri);`

**Comment by Eminem8080** [comment]
java.io.FileNotFoundException: /Tencent/QQfile_recv/�7DDEE1YCE9EJ7�8X1�.png: open failed: ENOENT (No such file or directory)

**Comment by Lee-Wang-Jing** [comment]
the urlpath need UrlEncode

**Comment by Eminem8080** [comment]
我读取的是本地图片 并且之前也进行过Uri编码的转化  但是fresco中接受的uri还是显示为乱码
` String upper="file://";
        String path="/Tencent/QQfile_recv/%Q}DEE1YCE9EJ7%R08X1%ER.png";
        Uri uri = Uri.parse(encodeURI(upper+path));
        System.out.println("EEERRR=="+uri);
        //本地文件
       // File file = new File(Environment.getExternalStorageDirectory(), path);
        //加载图片
       // Glide.with(this).load(file).into(imageView);
//        userimg.setImageURI(uri);
      

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(encodeURI(upper+path))
                .setControllerListener(listener)
                .build();
        userimg.setController(controller);`

**Comment by s1rius** [comment]
@Eminem8080 Maybe #754 could help you.
