### ISSUE TITLE
Crash when loading so

### ISSUE THREAD

**Issue by sangchengjiang** [facebook/fresco#1723]
### Description

we built a platform to collect user's crash log, here is what we found about fresco:

# pool-2-thread-1(16636)
java.lang.UnsatisfiedLinkError
Couldn't load imagepipeline from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sohu.sohuvideo-2.apk", zip file "/data/data/com.sohu.sohuvideo/code_cache/secondary-dexes/com.sohu.sohuvideo-2.apk.classes2.zip", zip file "/data/data/com.sohu.sohuvideo/code_cache/secondary-dexes/com.sohu.sohuvideo-2.apk.classes3.zip"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /data/datalib]]]: findLibrary returned null

1 java.lang.Runtime.loadLibrary(Runtime.java:358)
2 java.lang.System.loadLibrary(System.java:555)
3 com.facebook.common.soloader.SoLoaderShim$DefaultHandler.void loadLibrary(java.lang.String)(SoLoaderShim.java:32)
4 com.facebook.common.soloader.SoLoaderShim.void loadLibrary(java.lang.String)(SoLoaderShim.java:56)
5 com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.void load()(ImagePipelineNativeLoader.java:43)
6 com.facebook.imagepipeline.memory.NativeMemoryChunk.void <clinit>()(NativeMemoryChunk.java:36)
7 com.facebook.imagepipeline.memory.NativeMemoryChunkPool.com.facebook.imagepipeline.memory.NativeMemoryChunk alloc(int)(NativeMemoryChunkPool.java:60)
8 com.facebook.imagepipeline.memory.NativeMemoryChunkPool.void free(java.lang.Object)(NativeMemoryChunkPool.java:22)
9 ##_parent_##1##_parent_##
10 ##_child_## java.lang.Object alloc(int)##_child_##
11 com.facebook.imagepipeline.memory.BasePool.java.lang.Object get(int)(BasePool.java:259)
12 com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.void <init>(com.facebook.imagepipeline.memory.NativeMemoryChunkPool,int)(NativePooledByteBufferOutputStream.java:53)
13 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.NativePooledByteBuffer newByteBuffer(java.io.InputStream,int)(NativePooledByteBufferFactory.java:98)
14 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.PooledByteBufferOutputStream newOutputStream()(NativePooledByteBufferFactory.java:26)
15 ##_parent_##3##_parent_##
16 ##_child_## com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(java.io.InputStream,int)##_child_##
17 ##_child_## com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(byte[])##_child_##
18 ##_child_## com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(java.io.InputStream)##_child_##
19 com.facebook.imagepipeline.producers.LocalFetchProducer.com.facebook.imagepipeline.image.EncodedImage getByteBufferBackedEncodedImage(java.io.InputStream,int)(LocalFetchProducer.java:89)
20 ##_parent_##2##_parent_##
21 ##_child_## com.facebook.imagepipeline.image.EncodedImage getEncodedImage(com.facebook.imagepipeline.request.ImageRequest)##_child_##
22 ##_child_## java.lang.String getProducerName()##_child_##
23 com.facebook.imagepipeline.producers.LocalFetchProducer.com.facebook.imagepipeline.image.EncodedImage getEncodedImage(java.io.InputStream,int)(LocalFetchProducer.java:101)
24 com.facebook.imagepipeline.producers.LocalFileFetchProducer.com.facebook.imagepipeline.image.EncodedImage getEncodedImage(com.facebook.imagepipeline.request.ImageRequest)(LocalFileFetchProducer.java:35)
25 com.facebook.imagepipeline.producers.LocalFetchProducer$1.com.facebook.imagepipeline.image.EncodedImage getResult()(LocalFetchProducer.java:56)
26 com.facebook.imagepipeline.producers.LocalFetchProducer$1.java.lang.Object getResult()(LocalFetchProducer.java:52)
27 com.facebook.common.executors.StatefulRunnable.void run()(StatefulRunnable.java:45)
28 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
29 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
30 java.lang.Thread.run(Thread.java:841)

### Solution

add try...catch to avoid

### Additional Information

* Fresco version: 1.1.0
* Platform version: Android 4.4.2,level 19 HUAWEI MT7-CL00

**Comment by massimocarli** [comment]
Hi @sangchengjiang
using try/catch doesn't fix the problem because you avoid the crash but the library is not loaded anyway. Have you tried the solution here #933?
Thankx

**Comment by erikandre** [comment]
As suggested, we recommend using https://github.com/facebook/SoLoader to fix these kind of crashes. If that does not work, please comment here and we can reopen the issue.

**Comment by dmueller39** [comment]
I recently had a similar issue which was actually the result of a version mismatch. I was compiling a dependency that was compiling an upgraded version of fresco `compile 'com.facebook.fresco:fresco:1.3.0'` , but in my projects build.gradle I was specifying an older version of the animated gifs library `compile 'com.facebook.fresco:animated-gif:0.14.1'`. Updated my version, and it started working again. Simple issue, but this might steer someone else in the right direction.
