### ISSUE TITLE
Crash when loading class com.facebook.imagepipeline.memory.NativeMemoryChunk

### ISSUE THREAD

**Issue by sangchengjiang** [facebook/fresco#1724]
### Description

java.lang.NoClassDefFoundError
com/facebook/imagepipeline/memory/NativeMemoryChunk

com.facebook.imagepipeline.memory.NativeMemoryChunkPool.com.facebook.imagepipeline.memory.NativeMemoryChunk alloc(int)(NativeMemoryChunkPool.java:60)
2 com.facebook.imagepipeline.memory.NativeMemoryChunkPool.void free(java.lang.Object)(NativeMemoryChunkPool.java:22)
3 ##_parent_##1##_parent_##
4 ##_child_## java.lang.Object alloc(int)##_child_##
5 com.facebook.imagepipeline.memory.BasePool.java.lang.Object get(int)(BasePool.java:259)
6 com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.void <init>(com.facebook.imagepipeline.memory.NativeMemoryChunkPool,int)(NativePooledByteBufferOutputStream.java:53)
7 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.NativePooledByteBuffer newByteBuffer(java.io.InputStream,int)(NativePooledByteBufferFactory.java:98)
8 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.com.facebook.imagepipeline.memory.PooledByteBufferOutputStream newOutputStream()(NativePooledByteBufferFactory.java:26)
9 ##_parent_##3##_parent_##
10 ##_child_## com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(java.io.InputStream,int)##_child_##
11 ##_child_## com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(byte[])##_child_##
12 ##_child_## com.facebook.imagepipeline.memory.PooledByteBuffer newByteBuffer(java.io.InputStream)##_child_##
13 com.facebook.imagepipeline.cache.BufferedDiskCache.com.facebook.imagepipeline.memory.PooledByteBuffer readFromDiskCache(com.facebook.cache.common.CacheKey)(BufferedDiskCache.java:341)
14 com.facebook.imagepipeline.cache.BufferedDiskCache.java.lang.Class access$200()(BufferedDiskCache.java:38)
15 ##_parent_##2##_parent_##
16 ##_child_## com.facebook.imagepipeline.cache.ImageCacheStatsTracker access$300(com.facebook.imagepipeline.cache.BufferedDiskCache)##_child_##
17 ##_child_## com.facebook.imagepipeline.memory.PooledByteBuffer access$400(com.facebook.imagepipeline.cache.BufferedDiskCache,com.facebook.cache.common.CacheKey)##_child_##
18 com.facebook.imagepipeline.cache.BufferedDiskCache$2.com.facebook.imagepipeline.image.EncodedImage call()(BufferedDiskCache.java:185)
19 com.facebook.imagepipeline.cache.BufferedDiskCache$2.java.lang.Object call()(BufferedDiskCache.java:168)
20 bolts.Task$4.void run()(Task.java:357)
21 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
22 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
23 java.lang.Thread.run(Thread.java:841)

### Solution

add try...catch to avoid

### Additional Information

* Fresco version: 1.1.0
* Platform version: Android 4.4.2,level 19 HUAWEI MT7-CL00

**Comment by massimocarli** [comment]
This is related to #1723. So I'm closing this issue keeping open the previous.
