### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2dad25ee

### ISSUE THREAD

**Issue by MinJiLiu** [facebook/fresco#1726]
### Description
The BitmapPool log below:
04-18 10:39:34.797 21848-21984/? V/unknown:BitmapPool: release (free) (object, size) = (37535584, 16384)
04-18 10:39:34.797 21848-21984/? V/unknown:BitmapPool: Used = (256, 10787136); Free = (0, 0)
04-18 10:39:34.797 21848-21977/? V/unknown:BitmapPool: Used = (257, 10803520); Free = (0, 0)
04-18 10:39:34.797 21848-21977/? V/unknown:BitmapPool: get (alloc) (object, size) = (84036b7, 16384)
04-18 10:39:34.797 21848-21977/? V/unknown:BitmapPool: release (free) (object, size) = (39308e33, 16384)
04-18 10:39:34.797 21848-21977/? V/unknown:BitmapPool: Used = (256, 10787136); Free = (0, 0)
04-18 10:39:34.807 21848-21982/? V/unknown:BitmapPool: Used = (257, 10803520); Free = (0, 0)
04-18 10:39:34.807 21848-21982/? V/unknown:BitmapPool: get (alloc) (object, size) = (1bf43b42, 16384)
04-18 10:39:34.807 21848-21982/? V/unknown:BitmapPool: release (free) (object, size) = (2dad25ee, 16384)
04-18 10:39:34.807 21848-21982/? V/unknown:BitmapPool: Used = (256, 10787136); Free = (0, 0)
04-18 10:39:34.807 21848-21975/? V/unknown:BitmapPool: Used = (257, 10803520); Free = (0, 0)
04-18 10:39:34.807 21848-21975/? V/unknown:BitmapPool: get (alloc) (object, size) = (35708589, 16384)
04-18 10:39:34.817 21848-21975/? V/unknown:BitmapPool: release (free) (object, size) = (afcb37f, 16384)
04-18 10:39:34.817 21848-21975/? V/unknown:BitmapPool: Used = (256, 10787136); Free = (0, 0)
04-18 10:39:34.817 21848-21976/? V/unknown:BitmapPool: Used = (257, 10803520); Free = (0, 0)
04-18 10:39:34.817 21848-21976/? V/unknown:BitmapPool: get (alloc) (object, size) = (5882dbc, 16384)
04-18 10:39:34.817 21848-21976/? V/unknown:BitmapPool: release (free) (object, size) = (1f80c125, 16384)
04-18 10:39:34.817 21848-21976/? V/unknown:BitmapPool: Used = (256, 10787136); Free = (0, 0)

Then there was a crash.This happens when I use ImagePipeline directly while repeating the same picture but rewriting the CacheKey in PostProcess for not allow it to use bitmap in memory. Because it can be reproduced this crash.The code is below:

```
imagePipeline.fetchDecodedImage(request, null);

@Override
            protected void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                if (!dataSource.isFinished()) {
                    onFailureImpl(dataSource);
                    return;
                }

                CloseableReference<CloseableImage> result = dataSource.getResult();
                if (result != null) {
                    listener.success(new FrescoBitmapWrapper(result));
                    result.close();
                }
            }
```

Here i clone the result in FrescoBitmapWrapper's constructor.And then put the bitmap in the ImageView.

### Additional Information
* Fresco version: [1.0]
* Platform version: [android 4.0,5.0,6.0]

**Comment by massimocarli** [comment]
Hi @MinJiLiu 
we'll have a look.
Thanks

**Comment by oprisnik** [comment]
How are you cloning the bitmap and using it? I suspect that the underlying bitmap is closed.

**Comment by MinJiLiu** [comment]
```
public FrescoBitmapWrapper(CloseableReference<CloseableImage> ref) {
        mReference = ref.clone();
}

@Override
@Deprecated
public synchronized Bitmap get() {
    if (mReference != null) {
        CloseableImage image = mReference.get();
        if (image != null && image instanceof CloseableBitmap)
        return ((CloseableBitmap) image).getUnderlyingBitmap();
    }
    return null;
}

@Override
public void release() {
    if (release) {
        return;
    }
    CloseableReference.closeSafely(mReference);
    mReference = null;
    release = true;
}
```

**Comment by oprisnik** [comment]
I think the issue here is that you re-attach the imageView, which will result in the bitmap being closed for the detach event and re-attaching causes the recycled bitmap to be drawn, which throws the exception. You have to correctly handle closeable references as described in http://frescolib.org/docs/closeable-references.html
