### ISSUE TITLE
In ImagePipeline.prefetchToDiskCache callback, the cached file is not yet ready.

### ISSUE THREAD

**Issue by yihuaqi** [facebook/fresco#1727]
### Description

What I want to do is to download an image as file. 
I decided to use ImagePipeline.prefetchToDiskCache(), and tried to load the file from Fresco's cache when I got the result. My guess is that the cache file is not ready, because I always got null.
I did a further investigation that I set up a CacheEventListener in DiskCacheConfig, and found that the onNewResult callback always happens before onWriteSuccess, which proved my guess.

### Reproduction

```
ImagePipeline imagePipeline = Fresco.getImagePipeline();
DataSource<Void> dataSource = imagePipeline.prefetchToDiskCache(imageRequest, null);
dataSource.subscribe(new BaseDataSubscriber<Void>() {
    @Override
    protected void onNewResultImpl(DataSource<Void> dataSource) {
        if (dataSource.isFinished()) {
            // file is always null.
            File file = findInDiskCache(imageRequest);
        }
    }

    @Override
    protected void onFailureImpl(DataSource<Void> dataSource) {
    }
}, CallerThreadExecutor.getInstance());

private File findInDiskCache(Context context, ImageRequest imageRequest) {
    CacheKey cacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(imageRequest, null);
    BinaryResource binaryResource = ImagePipelineFactory.getInstance().getMainFileCache().getResource(cacheKey);
    if (binaryResource == null) {
        return null;
    }
    File file = ((FileBinaryResource) binaryResource).getFile();
    return file;
}
```
### Solution

It would be much more convenient to have the cache file ready in onNewResultImpl.

### Additional Information

* Fresco version: 1.2.0
* Platform version: No specific platform.

**Comment by massimocarli** [comment]
Hi @yihuaqi,
this is interesting.  This is because the DataSource has been designed in order to provide the reference to the image without waiting for the image into the file system. A think you can try is to use a `CacheEventListener` which has the `onWriteSuccess()` method. You can set it using the `DiskCacheConfig` object. 
Thankx

**Comment by yihuaqi** [comment]
@massimocarli Thanks for your quick response.
I end up doing what you suggested, listening to onWriteSuccess and then set the result. It works as expected, though not as elegant as the other part of the code. 
I totally agree with the design of DataSource that provide the image reference as soon as it's available. But in this particular case of prefetchToDiskCache, I think it makes more sense to have the cache file ready in the callback, or better yet to use the DataSource<File> as the result, since the cache file is the only reference to the image.

**Comment by letronje** [comment]
We have a case where we render a local Image URI ( file:///.... ) first while the image is uploaded somewhere and then we switch to the remote URI post upload. I guess the smoothest way is to prefetch the image and then once it is known to be in cache, switch to the remote URI. Can this be done ?

**Comment by erikandre** [comment]
Closing as the original issue was addressed. @letronje Yes, that sounds reasonable. If you need further assistance, please create a new issue (since reusing old ones makes things a bit messy). Thanks!

**Comment by pranavrao1** [comment]
@yihuaqi  mind sharing the code as an example. I am facing a similar issue but not sure of how to implement it.
