### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [facebook/fresco#1730]
# Thread-1669(1669)
java.lang.OutOfMemoryError
Failed to allocate a 1638412 byte allocation with 1496952 free bytes and 1461KB until OOM
` dalvik.system.VMRuntime.newNonMovableArray(Native Method)
 android.graphics.Bitmap.nativeCreate(Native Method)
 android.graphics.Bitmap.createBitmap(Bitmap.java:843)
 android.graphics.Bitmap.createBitmap(Bitmap.java:820)
 android.graphics.Bitmap.createBitmap(Bitmap.java:787)
 com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
 com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
 com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
 com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
 com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
 com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:186)
 com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:63)
 com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:126)
 com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:239)
 com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
 com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:144)
 com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
 com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
 com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
 java.lang.Thread.run(Thread.java:818)`

### Additional Information

* Fresco version: [1.2.0]
* Platform version: [
  Android 6.0.1,level 23  
  ROM: XiaoMi/MIUI 
  Equipment type: XiaoMi 3]
Length of use
17 hours, 22 minutes and 35 seconds
Front and rear state
Reception
Equipment type
Millet MI 3
System version
Android 6.0.1, level 23
ROM
XiaoMi/MIUI
CPU architecture
Armeabi-v7a

**Comment by massimocarli** [comment]
Hi @Lee-Wang-Jing 
the OOM could be caused by a leak in some other part of the code and be thrown by the Bitmap allocation because Bitmap objects are usually big. Have you tested you application with some memory specific tools? 
Thankx

**Comment by erikandre** [comment]
If this is a reproducible crash I would recommend to capture a memory dump right before the crash occurs. That should reveal what is holding onto the memory.
