### ISSUE TITLE
App crash caused by regression in 1.3.0

### ISSUE THREAD

**Issue by davidpfahler** [facebook/fresco#1741]
### Description

We are developing a react-native app which uses a lot of third-party native dependencies. Our `build.gradle` file used to specify the following dependency:
`compile "com.facebook.fresco:animated-gif:+"`
When fresco 1.3.0 was released, all builds from that point forward started to crash.

### Reproduction

Render a react-native `Image` component with a gif as a source.

### Solution

Pin dependency to `compile "com.facebook.fresco:animated-gif:1.2.0"`.

### Additional Information

* Platform version: Android 6.0, Nexus 7

**Comment by erikandre** [comment]
Hi @davidpfahler !

Could you please give us the stack trace as well? Thanks!

**Comment by davidpfahler** [comment]
@erikandre This should be the relevant part:

```
04-27 10:58:34.798 14191 14263 E AndroidRuntime: Process: com.app, PID: 14191
04-27 10:58:34.798 14191 14263 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.facebook.imagepipeline.producers.ProducerListener.onUltimateProducerReached(java.lang.String, java.lang.String, boolean)"
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at com.facebook.imagepipeline.listener.ForwardingRequestListener.onUltimateProducerReached(ForwardingRequestListener.java:144)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at com.facebook.imagepipeline.producers.NetworkFetchProducer.handleFinalResult(NetworkFetchProducer.java:155)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:110)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:122)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-27 10:58:34.798 14191 14263 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:761)
04-27 10:58:34.801  5051  9276 W ActivityManager:   Force finishing activity com.app/.MainActivity
```

This also seems related to #1732.

**Comment by kirwan** [comment]
@davidpfahler You've hit a breaking change I'm afraid, rather than a regression.

I presume you have an implementation of `ProducerListener` or `RequestListener`, in which case you need to implement one new method. I assume this is in your code because the only listener within React Native extends `BaseRequestListener` which has a no-op implementation to avoid this problem.

I've updated the [release notes for 1.3.0](https://github.com/facebook/fresco/releases/tag/v1.3.0) to make this clearer.

**Comment by davidpfahler** [comment]
@kirwan Thank you. We are looking into it and will let you know if we can identify the problem so others with the same problem may benefit.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.

**Comment by wwf7758258** [comment]
I also encountered the same problem
below is log:
 Process: com.heniaokeji.geji, PID: 21644
                                                                     java.lang.AbstractMethodError: abstract method "void com.facebook.imagepipeline.producers.ProducerListener.onUltimateProducerReached(java.lang.String, java.lang.String, boolean)"
                                                                         at com.facebook.imagepipeline.listener.ForwardingRequestListener.onUltimateProducerReached(ForwardingRequestListener.java:144)
                                                                         at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:61)
                                                                         at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:51)
                                                                         at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)

1. 



![image](https://user-images.githubusercontent.com/9246653/29010491-39181c34-7b5e-11e7-9b56-21f0ec381204.png)

**Comment by erikandre** [comment]
@wwf7758258 Looks like your problem is that the versions for the different Fresco modules do not match (you are using 1.3.0 for Fresco and 1.2.0 for the animated-gif and other modules).
Please change all of them to use the same version, and I would also recommend that you don't use: 

`compile "com...react-native:+"`

to include react native but instead specify exactly which version you want. Otherwise things can easily break when they release a new version, even without you modifying your app.
