### ISSUE TITLE
Compressed animated GIFs showed with white spots

### ISSUE THREAD

**Issue by venik** [facebook/fresco#1742]
### Description
When I try to render any compressed gif (I suppose they were compressed with gifsicle or something similar), I have white spots all around the picture

### Reproduction
For example this gif (you can try to split it with https://ezgif.com to see white spots)
https://media.giphy.com/media/RHoRwhdlh6TBK/giphy.gif

`
        SimpleDraweeView myDraweeView
                = (SimpleDraweeView)findViewById(R.id.my_drawee_view);

        DraweeController controller =
                Fresco.newDraweeControllerBuilder()
                        .setUri("https://media.giphy.com/media/RHoRwhdlh6TBK/giphy.gif\n")
                        .setAutoPlayAnimations(true)
                        .build();

        myDraweeView.setController(controller);
`

### Solution
unknown

### Additional Information

* Fresco version: I tried 1.0.0-1.3.0
* Platform version: Android

![screenshot_2017-04-27-15-18-24](https://cloud.githubusercontent.com/assets/54374/25508641/5ce34b3e-2b68-11e7-8cf6-a4c59aa18322.png)

**Comment by foghina** [comment]
Assigning to @oprisnik as the resident gif master.

**Comment by oprisnik** [comment]
Thanks for the bug report @venik. We'll take a look!

**Comment by oprisnik** [comment]
I've fixed the issue in f7487d1153461e654695ef6d20c1295cfceaca69, will be included in the next release

**Comment by venik** [comment]
We need to ping ReactNative guys too, because now they use broken gif-animated in the release.
