### ISSUE TITLE
APNG support

### ISSUE THREAD

**Issue by zyallday** [facebook/fresco#1749]
Will fresco support apng in the future?

**Comment by oprisnik** [comment]
Fresco now supports custom image formats, decoders, and drawable factories, which allows to add support for APNG.

Example for SVG: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/svg/SvgDecoderExample.java

Pull requests are welcome :)

**Comment by zyallday** [comment]
@oprisnik Ok,I know.Thanks.I'll try my best.

**Comment by erikandre** [comment]
Closing as we are not planning to implement this feature. Pull requests are still welcome!
