### ISSUE TITLE
Unable to expand TAR when build

### ISSUE THREAD

**Issue by macroharder** [facebook/fresco#175]
FAILURE: Build failed with an exception.
              
* What went wrong:
Unable to expand TAR '/Users/xxxx/code/fresco/imagepipeline/nativedeps/downloads/v0.4.2.tar.gz'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file extension.
  If you need to specify the compression explicitly please refer to the DSL reference.
> Could not copy tar entry /Users/xxxx/code/fresco/imagepipeline/nativedeps/downloads/v0.4.2.tar.gz!libwebp-0.4.2/swig/libwebp_python_wrap.c to '/Users/xxxx/code/fresco/imagepipeline/build/tmp/expandedArchives/v0.4.2.tar.gz_efurske37c9d98oidjq3g8dsd/libwebp-0.4.2/swig/libwebp_python_wrap.c'.
              
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
BUILD FAILED

**Comment by tyronen** [comment]
./gradlew clean and try again

If that does not succeed, try `cleanAll` instead, and remove the `imagepipeline/nativedeps` directory.

**Comment by macroharder** [comment]
@tyronen Thank you.I build success after remove the /nativedeps directory.But could you please tell me why this problem arises？Thanks.

**Comment by tyronen** [comment]
It's hard to tell. Probably there was a problem with the original download, and trying it again is all it takes.
