### ISSUE TITLE
Fetching updated Image

### ISSUE THREAD

**Issue by Anmolk22** [facebook/fresco#1750]
Hey , I am using Fresco for downloading images from Server. 
I want to download image and set it to a linearlayout as background. So I am using Imagepipeline to download image using the URL directly.
Now I am facing two issues
1. How to scale an image which has been downloaded via pipeline 
2. When I update the image on the website and logout from the application and then login back then the application crashes. Once the application crashes and I restart the application, the application works fine it shows me a null pointer exception.

Following is the code snippet being used for downloading the image

        Uri uri= Uri.parse(GlobalVariables.IMAGE_PREFIX+coverPic);
        final LinearLayout linearLayout= (LinearLayout) findViewById(R.id.navHeader);

        ImageDecodeOptions decodeOptions = ImageDecodeOptions.newBuilder()
                .build();
        ImageRequest request = ImageRequestBuilder
                .newBuilderWithSource(uri)
                .setImageDecodeOptions(decodeOptions)
                .setLocalThumbnailPreviewsEnabled(true)
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                .setProgressiveRenderingEnabled(false)
                .setResizeOptions(new ResizeOptions(width, height))
                .build();

        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        final DataSource<CloseableReference<CloseableImage>>
                dataSource = imagePipeline.fetchDecodedImage(request, this);

        try{
            dataSource.subscribe(new BaseBitmapDataSubscriber() {
                @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN)
                @Override
                protected void onNewResultImpl(Bitmap bitmap) {
                    assert bitmap!= null;
                        Bitmap result= BlurBuilder.blur(HomeActivity.this, bitmap);
                        linearLayout.setBackground(new BitmapDrawable(getResources(), result));
                        dataSource.close();
                }

                @Override
                protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>>dataSource) {

                }
            }, UiThreadImmediateExecutorService.getInstance());

        } catch (Exception e){
            e.printStackTrace();
        }

**Comment by oprisnik** [comment]
Scaling: If you don't use a DraweeView, you have to perform the scaling yourself. For example, do something similar with Matrix operations like we do in DraweeView and ScaleType.

Crashes: You should not use `BaseBitmapDataSubscriber` to get the bitmap since the bitmap will be closed right after `onNewResultImpl`, which causes the crash. See also #1550.

You should use a DraweeView instead if possible. Also, for the blurring step you should use a `Postprocessor` and we also have blurring postprocessors in the `showcase` sample app.
