### ISSUE TITLE
Fresco Library Not Loading Any Images

### ISSUE THREAD

**Issue by buckydroid** [facebook/fresco#1753]
So due to memory issue I thought about using Facebook's Fresco library.

So this is what I did,

First I added the following dependencies,

```
compile 'com.facebook.fresco:fresco:1.3.0'
compile 'com.facebook.fresco:animated-gif:1.3.0'
```
Then I initialized it in application class,

`Fresco.initialize(getApplicationContext());
`Then I added SimpleDraweeView to layout file,

```
<com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/imageMessage"
    android:layout_width="180dp"
    android:layout_height="180dp"
    />
```
Then I added the code in my activity,

        SimpleDraweeView gif = (SimpleDraweeView) row.findViewById(R.id.imageMessage);

        ImageRequest request = ImageRequestBuilder.newBuilderWithSource (Uri.parse(url.get(position)))
                .setProgressiveRenderingEnabled (true)
                .build ();
        DraweeController controller = Fresco.newDraweeControllerBuilder ()
                .setImageRequest (request)
                .setAutoPlayAnimations (true)

                .build ();

        gif.setController (controller);
But it's not loading images, I also tried different urls but same result, Also I have added Internet permission. So what I'm missing...

**Comment by foghina** [comment]
That looks mostly correct, just a couple of things to check:

1. Have you correctly set your application classname in `AndroidManifest.xml`? To verify this, you can add a log message in `Application#onCreate()` and make sure it shows up.
2. Is there anything relevant in logcat?

**Comment by buckydroid** [comment]
My application is fine, And I don't see any fresco specific log..

I'm using it with glide for testing, I know I'll remove it, but can that be a problem for which this is not working?

**Comment by foghina** [comment]
Ok, two more things to check:

1. `setProgressiveRenderingEnabled` is only needed for progressive JPEG images. You shouldn't use it with gifs, but I doubt this is causing problems
2. Can you post some of the URLs you're trying, so I can check them on my end?

**Comment by erikandre** [comment]
Closing as we need more information to proceed. Please reopen if anything changed. Thanks!
