### ISSUE TITLE
Is there a way to know if an image has been downloaded from mem cache, disk cache, network...

### ISSUE THREAD

**Issue by eboudrant** [facebook/fresco#1757]
I cannot find anything in the doc and looks like the [`ControllerListener`](http://frescolib.org/docs/listening-download-events.html) do not have this information. We need to know from which datasource the image is coming (mem cache, disk cache, network...) Is it possible ?
Thanks

**Comment by foghina** [comment]
You can use `onUltimateProducerReached`, which was added by f16d725. This callback will let you know which producer ultimately returned the image, so you will have to check if it's the memory cache producer, disk cache producer etc. However, for some reason this doesn't show up in javadocs yet, but it should be present in 1.3.0.
