### ISSUE TITLE
use fresco load and display a network picture。but the display is green

### ISSUE THREAD

**Issue by hujianping** [facebook/fresco#1763]
### Description

use fresco load and display a network picture。but the display is green。i use bitmap config is RGB565.
(low  probability)

### Reproduction

**Comment by foghina** [comment]
Can you post a URL to the image you are trying to display? Maybe some code to help us understand what is happening?

**Comment by erikandre** [comment]
Closing this as we don't have enough information to investigate the problem.
Please comment on this ticket providing more information and we will reopen the task. 
Thanks!

**Comment by froxCZ** [comment]
+1
