### ISSUE TITLE
gif circle

### ISSUE THREAD

**Issue by qbaowei** [facebook/fresco#1769]
A url which i get from server may be a jpg or a gif(i set auto play false) is used to display a circle SimpleDraweeView.
But, fresco not support gif circle!

So, what shall i do?

**Comment by qbaowei** [comment]
Note that the gif url i get from server is a static gif, it only have one frame.I only what to display the one frame image as circle.

**Comment by kirwan** [comment]
The solution is given in #1695.

**Comment by qbaowei** [comment]
@kirwan it works,you saved my day,thank you very much.
