### ISSUE TITLE
Is there any listener where we can use TrafficStats to calculate network stats?

### ISSUE THREAD

**Issue by rockerhieu** [facebook/fresco#177]
I want to see how much data Fresco consume when fetching images from network. Is there any way I can set a listener to hook into the lifecycle of Fresco and use `TrafficStatsCompat.setThreadStatsTag()`? Or do we have to create our own `NetworkFetcher`?

**Comment by tyronen** [comment]
setThreadStatsTag would have to be called from the thread itself, so right now we don't have such a hook.

It wouldn't be hard to add it - the tag could simply be specified at image pipeline configuration, and HttpUrlConnectionNetworkFetcher could kick off its threads will a runnable setting the tag.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by erikandre** [comment]
Closing as a possible solution was suggested and nothing further has been updated for 2 years
