### ISSUE TITLE
lowImage not request

### ISSUE THREAD

**Issue by lushan1314** [facebook/fresco#1770]
`ImageRequest request = ImageRequestBuilder.newBuilderWithSource(FrescoUtils.getUri(""))
                .build();

        ImageRequest lowRequset = ImageRequestBuilder.newBuilderWithSource(FrescoUtils.getUri(lowUrl))
                    .build();
        
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setLowResImageRequest(lowRequset)
                .setRetainImageOnFailure(true)
                .setImageRequest(request)
                .setOldController(photoView.getController())
                .build();
        photoView.setController(controller);`

lowimage no request,and no show。

* Fresco version: 1.3.0
* Platform version: [FILL THIS OUT: specific to a particular Android version? Device?]

**Comment by kirwan** [comment]
The low-res image is only loaded from cache if the full image isn't already available. It won't be loaded from the network as that would mean two images being requested when only one is needed.

**Comment by lushan1314** [comment]
ok.I also found is like this。but I have a question，two images display almost at the same time。This is concurrent execution of two request, is it possible to give them a sort？

**Comment by lambdapioneer** [comment]
@lushan1314 If you have two different image requests you can give them priorities. See the corresponding method in the image request builder.

For multiple images for the same entity see also http://frescolib.org/docs/requesting-multiple-images.html

**Comment by lushan1314** [comment]
@lambdapioneer  I saw it. Actually, in My case. low image changes to large image is always too fast.so i try to find a way make this transition have animation effect...Is there any way to do it？

**Comment by kirwan** [comment]
@lushan1314 There's no way to set a transition. The idea is that the two images should represent the same image just at different resolutions, so that you shouldn't notice the switch other than the image getting clearer.
