### ISSUE TITLE
In Android N Gif Animatable stop is not effect

### ISSUE THREAD

**Issue by WTree** [facebook/fresco#1772]
first Gif Animatable is stop,
when press home then back the activty,In Android N the gif will auto play

**Comment by lambdapioneer** [comment]
Hey @WTree, can you please provide some more information for this? In general it would be helpful to see the related code or have a minimal repro. Does this show in the sample apps that we provide?

**Comment by WTree** [comment]
@lambdapioneer  I use reflact Solve this problem, get the field  "mControllerListener",
and then removeControllerListener
