### ISSUE TITLE
JNI crash when accessing Bitmap from C++ code

### ISSUE THREAD

**Issue by sohayb** [facebook/fresco#1774]
### Description
My situation is the following: I have a `ViewPager` with Fragments, each `Fragment` has an `ImageView` that displays a high res image, this image might be from network or from disk. I'm using Fresco to load and cache these images. Everything was going well till I wanted to modify the image using JNI code, below is a snippet.

```cpp
JNIEXPORT jobject JNICALL Java_my_package_jni_OperationBridge_getModifiedBitmap(JNIEnv *jenv, jclass, jlong jobj, jobject jbitmap,
						jint jx, jint jy, jobject jrect, jint jimageWidth, jint jimageHeight)
{
	LOGD("JNICALL Java_my_package_jni_OperationBridge_getModifiedBitmap enter");
	try {
		Detector *detector = (Detector*) jobj;
		if (detector == NULL) {
			LOGD("invalid handle.");
			return NULL;
		}

		AndroidBitmapInfo bitmapInfo;
        int ret = AndroidBitmap_getInfo(jenv, jbitmap, &bitmapInfo);
        if (ret < 0) {
            LOGE("AndroidBitmap_getInfo() failed ! error=%d", ret);
            return 0L;
        }
        if (bitmapInfo.format != ANDROID_BITMAP_FORMAT_RGBA_8888) {
            LOGE("Bitmap format is not RGBA_8888!");
            return 0L;
        }

        //read pixels of bitmap into native memory
        void *bitmapPixels;
        ret = AndroidBitmap_lockPixels(jenv, jbitmap, &bitmapPixels);
       //...
}
```
Since there are 3 Fragments being created (center, right and left), all the images' operations for these 3 Fragments are being executed, whether on screen or not. I can defer these operations to when the `Fragment` is actually visible, but that would make me lose the smooth scrolling. Every time I load the `Activity`, the app crashes with this message:
```
A/libc: Invalid address 0xc6172988 passed to free: value not allocated
**or**
Bitmap: Failed to acquire strong reference to pixels
```
These are two different error messages, but after checking, they both are related to bitmaps not existing in memory. Then I checked that it's by design that you actually release the images from memory if they're not displayed: 

> **It also makes sure that images are automatically released from memory when they’re no longer shown on screen. This lets your application run faster - and suffer fewer crashes.**
I'm loading the image then I'm holding a strong reference to it a mentioned in docs:
```java
      CloseableReference<Bitmap> imageRef;
      .....
      jniFunctionCall(imageRef.get());
```
### Reproduction

Having a pager and calling a JNI function that uses a bitmap retrieved by `CloseableReference<Bitmap> imageRef.get()` should do make the app crash.

### Solution

This is not really a solution, but deferring these operations to when a `Fragment` is visible fixed the crash, but that's not the behavior I want.

### Additional Information
My question is, is there a way to not release images when they're off screen? because I'm explicitly releasing them when fragment is stopped like this:
```java
		if (rightImageRef != null && rightImageRef.isValid()) {
			CloseableReference.closeSafely(rightImageRef);
			rightImageRef = null;
		}
```

* Fresco version: 1.3.0
* Platform version: Android 7.1.2

**Comment by lambdapioneer** [comment]
Hi @sohayb, you want your call into JNI look something like this in order to make sure they are not closed while your code is executing:

```
CloseableReference myJniRef = CloseableReference.cloneOrNull(rightImageRef);
try {
    jniFunctionCall(myJniRef.get());
} finally {
    CloseableReference.closeSafely(myJniRef);
}
```

Your life probably would be easier though if you are using a post-processor and let the pipeline do the lifecycle handling for you (and you also get caching of the final result).

Docs: http://frescolib.org/docs/modifying-image.html
Example: https://github.com/facebook/fresco/blob/6ed61d352548f2462337a4af9841c3d050d9cabb/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/postprocessor/ScalingBlurPostprocessor.java

**Comment by sohayb** [comment]
This actually fixed the issue, thanks a lot!
I didn't use a post processor because changes are actually done based on user interaction and not when loading the actual image. I'm gonna close this now.
