### ISSUE TITLE
image display black and crash

### ISSUE THREAD

**Issue by qbaowei** [facebook/fresco#1778]
fresco 1.3
On some devices the image [http://images.9zhiad.com/87bb3872-37db-440e-9cb5-75b2ebc8a3c9.JPG](url) display black and crash.

Anybody tell me what should i do .

**Comment by kirwan** [comment]
Can you provide a stacktrace and your image pipeline config? From the URL alone we won't be able to help.

**Comment by qbaowei** [comment]
@kirwan The device not show a stacktrace,but it displays good after i set a small size option

**Comment by kirwan** [comment]
@qbaowei You said in the original issue that the app crashed. If so, I would expect you to see a crash in Logcat.

**Comment by qbaowei** [comment]
@kirwan In the page I load more than 20 images at the same time.Some images have a large size and I forgot to reset size option which may lead to  outof memory exception.

The bad thing is that my phone not show log in Logcat.It only crash.
