### ISSUE TITLE
Gif image within SimpleDraweeView showing white corner. 

### ISSUE THREAD

**Issue by PalDhv** [facebook/fresco#1783]
Both profile and chat buuble (gif image) are SimpleDraweeView.
please check this link:
https://yogeshd.tinytake.com/sf/MTYzOTIzNV81NTMwMDUx

**Code for chat bubble in xml.**
<com.facebook.drawee.view.SimpleDraweeView
                            android:id="@+id/gif_priview_img"
                            android:layout_width="@dimen/chat_image_max_width"
                            android:layout_alignParentTop="true"
                            android:layout_alignParentLeft="true"
                            android:layout_alignParentStart="true"
                            fresco:actualImageScaleType="fitXY"
                            android:visibility="visible"
                            fresco:roundedCornerRadius="9.5dp"
                            android:layout_height="@dimen/chat_image_max_width"
                            fresco:roundingBorderColor="#aa000000"
                            fresco:roundingBorderWidth="0.8dp"
                            fresco:roundWithOverlayColor="@color/about_screen_bg_color"
                            fresco:roundAsCircle="false">

**Code for profile image**
    <com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/profile_image"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_alignParentLeft="true"
                android:layout_marginLeft="2dp"
                fresco:placeholderImage="@drawable/blank_profile"
                fresco:roundAsCircle="true"
                fresco:placeholderImageScaleType="fitCenter"
                fresco:roundedCornerRadius="5dp"
                fresco:roundingBorderColor="@color/grey"
                fresco:roundingBorderWidth="0dp" />

**Comment by lambdapioneer** [comment]
@PalDhv, thanks for the issue. The white border seems to be just outside the `SimpleDraweeView, id=profile_image`. Is there any other container wrapping around it and/or is it just happening for (that) GIF images?

Would be great if you can the part of the layout file that contains both views. Then I can try to reproduce it locally. If it also just happens for certain images, those would be helpful as well.

**Comment by PalDhv** [comment]
This happens with gif image only and when that item of listview is focusable. For rest of items it do not show white border.  

SimpleDraweeView id=profile_image is warped inside Relative layout
   <RelativeLayout
            android:id="@+id/profile_image_layout"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginRight="-10dp"
            android:clipChildren="false"
            android:clipToPadding="false"
            android:visibility="visible" >

            <com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/profile_image"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_alignParentLeft="true"
                android:layout_marginLeft="2dp"
                fresco:placeholderImage="@drawable/blank_profile"
                fresco:roundAsCircle="true"
                fresco:roundedCornerRadius="5dp"
                fresco:roundingBorderColor="@color/grey"
                fresco:roundingBorderWidth="0dp" />
        </RelativeLayout>

SimpleDraweeView id=gif_priview_img is warped inside Relative layout

  <RelativeLayout
                        android:id="@+id/ack_message_layout"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:gravity="center_horizontal"
                        android:visibility="visible">

                        <com.ms.engage.widget.CustomImageView
                            android:id="@+id/attachment_preview"
                            android:layout_width="@dimen/chat_image_max_width"
                            android:layout_height="@dimen/chat_image_max_width"
                            android:adjustViewBounds="true"
                            android:scaleType="centerCrop"
                            android:src="@drawable/place_holder_blank_bg"
                            android:visibility="gone"
                            app:cornerRadius="12dp"
                            android:layout_alignParentTop="true"
                            android:layout_alignParentLeft="true"
                            android:layout_alignParentStart="true"/>

                        <com.facebook.drawee.view.SimpleDraweeView
                            android:id="@+id/gif_priview_img"
                            android:layout_width="@dimen/chat_image_max_width"
                            android:layout_alignParentTop="true"
                            android:layout_alignParentLeft="true"
                            android:layout_alignParentStart="true"
                            fresco:actualImageScaleType="fitXY"
                            android:visibility="visible"
                            fresco:roundedCornerRadius="9.5dp"
                            android:layout_height="@dimen/chat_image_max_width"
                            fresco:roundingBorderColor="#aa000000"
                            fresco:roundingBorderWidth="0.8dp"
                            fresco:roundWithOverlayColor="@color/about_screen_bg_color"
                            fresco:roundAsCircle="false"
                        />
id=attachment_preview will be gone when id=gif_priview_img is visible.

I hope this would help you to rectify this issue.
Let me know, if you want more information.

**Comment by PalDhv** [comment]
@lambdapioneer  Any update?

**Comment by oprisnik** [comment]
Can you post a working minimal example so that we can reproduce this? For example, by modifying [`DraweeSimpleFragment`](https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeSimpleFragment.java)?

**Comment by oprisnik** [comment]
I suppose this issue has been resolved. Let us know if you're still experiencing problems.
