### ISSUE TITLE
fresco:1.3.0   java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

### ISSUE THREAD

**Issue by RocLiuYC** [facebook/fresco#1784]
the app use fresco:1.3.0:

    compile 'com.facebook.fresco:fresco:1.3.0'
    compile "com.facebook.fresco:imagepipeline-okhttp3:1.3.0"
    compile 'com.facebook.fresco:animated-webp:1.3.0'
    compile 'com.facebook.fresco:webpsupport:1.3.0'

CRASH: In 4.x.x android version

**Comment by oprisnik** [comment]
There are many similar issues, see https://github.com/facebook/fresco/search?q=NativeMemoryChunk&type=Issues&utf8=%E2%9C%93

**Comment by RocLiuYC** [comment]
@oprisnik I have seen many similar issues that you have linked, but there is no solution for this issue!.

Please give a solution for this issues.

**Comment by oprisnik** [comment]
Using SoLoader or ReLinker should fix this issue. More info for example in #1724, #1738, #1723, #933.

**Comment by LIHAIYI** [comment]
dear RocLiuYC , I had the same issue, can you tell me how to solution?
