### ISSUE TITLE
ImageRequest setImageType method not exist

### ISSUE THREAD

**Issue by tsongski** [facebook/fresco#1785]
### Description

I try to config the disk cache in my app. A disk cache for default image, and a small disk cache for small image. But after I do that, I try to setImageType(ImageType.SMALL) in ImageRequest, and I find there is no method called setImageType, and I don't know to how to tell Fresco which image is small or not.

* Fresco version: 1.0.0
* Platform version: android 5.1

**Comment by oprisnik** [comment]
`ImageRequest.setCacheChoice(CacheChoice.SMALL)` should work. See for example https://github.com/facebook/fresco/blob/3d1e9ea532336975a5b39c2f8b5945a8d533640f/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/MediaVariationsFragment.java#L212
