### ISSUE TITLE
OOM Exception with Activity

### ISSUE THREAD

**Issue by KaleXia** [facebook/fresco#1787]
In my project,has an Activity---is a NewsDetail with a WebView(to show web content) and ListView(to show about News and comment)
    and when I open this Activity ,click aboutNews to open an new this Activity, when i repeat this opration;it must a issue an OOM exception.
    there is an Question that when the activity onPause(),the bitmap will be release? 
    Fresco and Lifecycle has any connection?

**Comment by oprisnik** [comment]
We are doing manual memory management for Bitmaps. If you're using DraweeView, the memory will be released when the drawee is detached from the current window and if nothing else holds on to the bitmap. If something holds on to the views, this might not work correctly. If you're using the pipeline directly, you have to do this manually.
