### ISSUE TITLE
try ZoomableDraweeView demo, but sometimes can not swipe smooth in view pager

### ISSUE THREAD

**Issue by ChocolateTan** [facebook/fresco#1788]
as title, thx.
i try fresco ZoomableDraweeView app, always can not swipe, plz help!

**Comment by oprisnik** [comment]
Hi! Please fill in the template for new issues. We need more information.

**Comment by jaimeagudo** [comment]
I'll try to help as I am experiencing the same for months so far. Btw I have tried it in a dozen of real devices, from Moto G5 to Samsung Sx, Huawei, Bq etc. with Android 6.0 and Android 7.0, it makes no difference

Just debug https://github.com/facebook/fresco/tree/master/samples/zoomableapp on a real device, try to swipe as you'd normally do and sometimes the swipe is not smooth but the worst is that **most of the times it simply doesn't swipe at all.** I have tried to narrow the source of errors commenting the Zoomable Feature (these 3 lines https://github.com/facebook/fresco/blob/master/samples/zoomableapp/src/main/java/com/facebook/samples/zoomableapp/MyPagerAdapter.java#L62-L65) and it made a very little difference 

It seems like you need to use just the tip of your finger and be very quick on your movements, if I use a bigger footprint and I swipe slowly it doesn't swipe or move at all 🤔

**Comment by Jorikua** [comment]
Faced the same problem today. You can just try to swipe it by your thumb, like every user always does. I think zoomable view just intercepts touches from viewpager, that's why you cannot swipe properly.

**Comment by oprisnik** [comment]
I've recently updated touch handling for [ZoomableDraweeView](https://github.com/facebook/fresco/blob/master/samples/zoomable/src/main/java/com/facebook/samples/zoomable/ZoomableDraweeView.java). Do you still see the issue?

**Comment by Jorikua** [comment]
Yes, I haven't updated samples for some time. Now everything works like a charm. Thank you for quick response and great work you do.

**Comment by Fauzdar1** [comment]
I'm currently using the `ZoomableDraweeView` but it still doesn't scroll smoothly inside `RecyclerView`. With `AllowTouchInterceptionWhileZoomed` as true, pinch zooming the image takes multiple attempts as it zooms in/out only a little bit by each pinch, also swiping the zoomed image also slides the image only a bit. And setting it as false makes the `RecyclerView` unscrollable when swiped from image, no matter the image is zoomed or not. Strange behavior, not smooth. Any fix for this? Implementation is exactly how it's done in the official repo of `ZoomableDraweeView` application.
