### ISSUE TITLE
Documentation mislead(?) - EncodedImage dimensions (getWidth & getHeight)

### ISSUE THREAD

**Issue by orenklein** [facebook/fresco#1791]
"Only valid if the image format is JPEG."
https://github.com/facebook/fresco/blob/c36e13ebb22078c19751e7d6389c94413aeb738a/imagepipeline-base/src/main/java/com/facebook/imagepipeline/image/EncodedImage.java#L242

I manually checked it with the following formats (remote urls): jpg, png, bmp;  and it worked. (calling parseMetaData() and then getWidth/getHeight)
It might have been fixed since that line had been written. If so, those lines should be removed.

**Comment by erikandre** [comment]
Hi @orenklein!

Thanks for submitting the bug report. Please feel free to submit a Pull request with updated docs :)

**Comment by orenklein** [comment]
Submitted :)

**Comment by erikandre** [comment]
Awesome! Thank you very much @orenklein  :) 👍
