### ISSUE TITLE
java.io.IOException:unexpected end of stream on Connection

### ISSUE THREAD

**Issue by li504799868** [facebook/fresco#1795]
These days, the server has migrated, but suddenly out of picture loading problems, java.io.IOException:unexpected, end, of, stream, on, Connection, how can I solve this problem?

**Comment by kirwan** [comment]
Sorry, you would need to provide a lot more details for us to help at all.

If things were working before, I suggest looking at how your old and new servers behave differently.

**Comment by foghina** [comment]
Closing this as we don't have enough information to investigate the problem.
Please comment on this ticket providing more information and we will reopen the task.
Thanks!
