### ISSUE TITLE
Display placeholder figure

### ISSUE THREAD

**Issue by Troll4it** [facebook/fresco#1797]
Used in recycleVIew Fresco "load network image, some pictures have been shown to take diagram, but after dragging recycleVIew, display placeholder figure place and normal network images, is this why?Is my some for Fresco "setting is not set??For answer, thank you

**Comment by Troll4it** [comment]
help!!!!!!!!

**Comment by lambdapioneer** [comment]
Hi @Troll4it, I'm sorry but I don't understand the exact issue here. A code sample and a video of the issue will help us a lot.

**Comment by Troll4it** [comment]
![img_20170620_154939](https://user-images.githubusercontent.com/27883219/27322403-a04f6bf4-55d0-11e7-9d7b-58b5bce2284b.jpg)
![img_20170620_155020](https://user-images.githubusercontent.com/27883219/27322410-a6f97422-55d0-11e7-9464-60e847964b16.jpg)


please,Look two image;   One Image  has  a  tag which is image 1,   This picture with the help of Internet, the place for a long time didn't figure transformation from a placeholder.But, after I drag the whole recycleView, until it disappeared in the interface, again to return to field of vision, the image is loaded out again .That is Others.

**Comment by lambdapioneer** [comment]
Hi @Troll4it, I think that the translation software that you are using fails to translate your issue into something that I can work on.

I get that it has something to do with RecyclerView and some loading (not) happening when elements return onto screen. I'd suggest you double check your code and also compare it to our sample implementation here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeRecyclerViewFragment.java

**Comment by Troll4it** [comment]
Hi! @lambdapioneer  
I'm sorry to have caused you to read. Read your website carefully, not the problem. My question is not only in the recycleView, in the other interface is also; first to the SimpleDraweeView set up a PlaceholderImage, when loading the network picture, some pictures can only display the placemark, and this interface in the network Smooth and placed for a long time, but the sliding interface until the picture from the interface and then pull back and found that the display bitmap SimpleDraweeView can display the network picture

**Comment by oprisnik** [comment]
As @lambdapioneer mentioned, I guess the issue is related to your RecyclerView usage. He linked to an example which shows how to use it correctly. If you modify the visibility of the view (e.g. by calling `setVisible(...)`), it could be that the image is not updated correctly since Fresco considers that when fetching images. It could also be that your implementation does not invalidate the correct view once the image is loaded. If you have a custom view, you'd have to correctly implement your custom view (see http://frescolib.org/docs/writing-custom-views.html) for this to work.
