### ISSUE TITLE
Resizing doesnt seem to be happening

### ISSUE THREAD

**Issue by Anmolk22** [facebook/fresco#1798]
Hey, I am trying to use resizing options in Fresco with the code snippet below 
but the resizing is not happening I also tried passing 10,10 for width and height but still it doesn't work
and should we use scale type and resizing together would this effect applications performance

```
resizingImage(){
int width = (int) (.50 * (new GlobalMethodClass().getScreenWidth(mContext)));
            int height = 50;
            Uri uriImage = Uri.parse(paintingPath);
            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uriImage)
                    .setResizeOptions(new ResizeOptions(width, height))
                    .build();
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setOldController(holder.getActionsPaintingImage().getController())
                    .setImageRequest(request)
                    .build();
            holder.getActionsPaintingImage().setController(controller);

            holder.getActionsPaintingImage().setImageURI(uriImage)
;}
```

**Comment by oprisnik** [comment]
What's the image format? Resizing is currently only supported for JPEG, see http://frescolib.org/docs/resizing-rotating.html

**Comment by Anmolk22** [comment]
Its a jpg image on the server

**Comment by Anmolk22** [comment]
I found the reason actually I shouldn't have added because of this line the holder is setting up the image again

holder.getActionsPaintingImage().setImageURI(uriImage)
