### ISSUE TITLE
Using OkHttp -- Docs clarification...

### ISSUE THREAD

**Issue by philipbjorge** [facebook/fresco#18]
So I'm reading the docs on using OkHttp and it indicates that my gradle file should not have ```compile 'com.facebook.fresco:fresco:0.1.0+'``` if I'm trying to use Fresco with OkHttp. However, unless I add that dependency, I have no Fresco to initialize.

Should I be including three dependencies as follows? If so, I think the docs could be clearer...
```
    compile 'com.facebook.fresco:fresco:0.1.0+'
    compile "com.facebook.fresco:drawee:0.1.0+"
    compile "com.facebook.fresco:imagepipeline-okhttp:0.1.0+"
```

http://frescolib.org/docs/using-other-network-layers.html#_

**Comment by plamenko** [comment]
Thank you, there was a typo in the documentation. The following should be enough:

    compile 'com.facebook.fresco:fresco:0.1.0+'
    compile "com.facebook.fresco:imagepipeline-okhttp:0.1.0+"

**Comment by philipbjorge** [comment]
Awesome -- Thanks for the prompt response.

**Comment by qq157755587** [comment]
It looks there is still a type.
```
compile: "com.facebook.fresco:fresco:0.1.0+"
compile: "com.facebook.fresco:imagepipeline-okhttp:0.1.0+"
```
should be
```
compile 'com.facebook.fresco:fresco:0.1.0+'
compile 'com.facebook.fresco:imagepipeline-okhttp:0.1.0+'
```

**Comment by xbroak** [comment]
the imagepipeline-okhttp also seems to have missing classes namely:

java.lang.NoSuchMethodError: com.squareup.okhttp.OkHttpClient.open
at com.squareup.okhttp.OkUrlFactory.open(OkUrlFactory.java:44)

**Comment by michalgr** [comment]
@xbroak : would you mind creating separate issue for the missing class ?
