### ISSUE TITLE
be default, it can only zoom in 2 levels by double click on the image, how can we zoom in event more just like how we can zoom in the image on photo viewer?

### ISSUE THREAD

**Issue by Binxie** [facebook/fresco#1800]
be default, it can only zoom in 2 levels by double click on the image, how can we zoom in event more just like how we can zoom in the image on photo viewer?

**Comment by lambdapioneer** [comment]
Hey @Binxie, have a look at our sample apps that you find in this repository. I can imagine that `samples/zoomable*` is what you are looking for.
