### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.wanda.app.wanhui-1/libimagepipeline.so" is too small to be an ELF executable

### ISSUE THREAD

**Issue by zhiyuchao** [facebook/fresco#1802]
Hi，everybody

Recently, I have encountered one issue like this,who can help me,thanks!

    1Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.wanda.app.wanhui-1/libimagepipeline.so" is too small to be an ELF executable
    2    at java.lang.Runtime.loadLibrary(Runtime.java:364)
    3    at java.lang.System.loadLibrary(System.java:526)
    4    at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(Feifan_O2O:32)
    5    at com.facebook.common.soloader.SoLoaderShim.loadLibrary(Feifan_O2O:56)
    6    at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(Feifan_O2O:43)
    7    at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(Feifan_O2O:36)
    8    at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(Feifan_O2O:60)
    9    at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.free(Feifan_O2O:22)
    10 alloc
    11    at com.facebook.imagepipeline.memory.BasePool.get(Feifan_O2O:259)
    12    at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(Feifan_O2O:53)
    13    at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(Feifan_O2O:98)
    14    at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(Feifan_O2O:26)
    15 newOutputStream
    16 newByteBuffer
    17 newByteBuffer
    18 newByteBuffer
    19    at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(Feifan_O2O:338)
    20    at com.facebook.imagepipeline.cache.BufferedDiskCache.access$100(Feifan_O2O:38)
    21 access$400
    22 access$500
    23    at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(Feifan_O2O:184)
    24    at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(Feifan_O2O:168)
    25    at bolts.Task$4.run(Feifan_O2O:357)
    26    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    27    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    28    at java.lang.Thread.run(Thread.java:841)

**Comment by lambdapioneer** [comment]
Hi @zhiyuchao, try using an alternative to the system's loader for native code. For instance, https://github.com/facebook/SoLoader should get you around this issue. Feel free to re-open if this continues to happen.
