### ISSUE TITLE
DraweeController CPU usage problem

### ISSUE THREAD

**Issue by spapapan** [facebook/fresco#1806]
I am trying to show a loading icon when the image hasn't loaded yet and hide the loading icon when the image is ready. I used the code below successfully to implement what I want.
My problem is that when I close the Fragment, I can see from the Android Monitor that the DraweeController continue using CPU. When I open consecutively 20-30 Fragment that contain one image, my phone freezes because of heavy CPU load. 
 
    private void loadImage(ImageView imageview,final ImageView videoicon, final GifTextView progressbar, Uri uri,final boolean video,final boolean child,boolean isConnectivity)
    { 
        if (child)
        {
            if (isConnectivity)
            progressbar.setBackgroundResource(Theme.Icons.LoadingChild);
        }
        else
        {
            progressbar.setBackgroundResource(Theme.Icons.LoadingMain);
        }
        SimpleDraweeView imageDrawee = (SimpleDraweeView) imageview;

        ControllerListener controllerListener = new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, @Nullable ImageInfo imageInfo, @Nullable Animatable anim) {
                if (imageInfo == null) {
                    return;
                }
                progressbar.setVisibility(View.GONE);
                if (video)
                {
                    if (child)
                    {
                        videoicon.setImageResource(Theme.Icons.MediaGalleryVideoIcon);
                    }
                    else
                    {
                        linearlayout_mediagalleryvideoicon.setVisibility(View.VISIBLE);
                        videoicon.setImageResource(Theme.Icons.MediaGalleryVideoIcon);
                    }
                }
            }

            @Override
            public void onIntermediateImageSet(String id, @Nullable ImageInfo imageInfo) {
                //FLog.d("Intermediate image received");
            }

            @Override
            public void onFailure(String id, Throwable throwable) {
                //FLog.e(getClass(), throwable, "Error loading %s", id)
            }
        };

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setControllerListener(controllerListener)
                .setOldController(imageDrawee.getController())
                .setUri(uri)
                .build();
        imageDrawee.setController(controller); 
    }
 
I tried to set imageDrawee.setController(null) inside onDestroy method, but the problem continues. 

* Fresco version: 1.3.0
* Platform version: Android 6

**Comment by lambdapioneer** [comment]
Hi @spapapan, thanks for the issue. The `DraweeController` shouldn't cause any CPU cycles after the DraweeView has been detached. I've some details that I'd need to help here :)

Do you know which method in `DraweeController` is causing the suspicious CPU usage? Or did you just see that the overall CPU usage is large?

Have you verified that the fragment is getting properly disposed when it's no longer on screen? Also, does the `GifTextView` get properly detached/closed? In general GIFs are very heavy on CPU.

**Comment by spapapan** [comment]
You are right, the problem wasn't from Fresco library but from a library that handles the gif. Thanks for the input.
