### ISSUE TITLE
I upgraded my fresco to 1.3.0，PooledByteBuffer and PooledByteBufferInputStream disappeared,What should I do

### ISSUE THREAD

**Issue by YuZhiLiang** [facebook/fresco#1810]
### Description
I upgraded my fresco to 1.3.0，PooledByteBuffer and PooledByteBufferInputStream disappeared, but i have used them, How can I deal with?
![oppo 20170626162250](https://user-images.githubusercontent.com/21107142/27531566-a10d6686-5a8f-11e7-9313-fba8fd491ee9.png)

* Fresco version: [1.3.0]
* Platform version: [Android6.0.1 OPPO R9s]

**Comment by ericleong** [comment]
Change 

```java
import com.facebook.imagepipeline.memory.PooledByteBuffer;
import com.facebook.imagepipeline.memory.PooledByteBufferInputStream;
```

to 

```java
import com.facebook.common.memory.PooledByteBuffer;
import com.facebook.common.memory.PooledByteBufferInputStream;
```

**Comment by kirwan** [comment]
This should have been documented in our release notes for 1.3.0. Sorry it's missing, I'll amend them.
