### ISSUE TITLE
fresco load gif

### ISSUE THREAD

**Issue by DukeLee1989** [facebook/fresco#1813]
The application in the background to cut back，GIF can reload lead to start there will be a blank
https://www.youtube.com/watch?v=wizs8TEzwU8&feature=youtu.be

**Comment by DukeLee1989** [comment]
[](https://youtu.be/wizs8TEzwU8 )

**Comment by DukeLee1989** [comment]
[https://www.youtube.com/watch?v=wizs8TEzwU8&feature=youtu.be](url)

**Comment by DukeLee1989** [comment]
https://www.youtube.com/watch?v=mjrDYBsarKI

**Comment by DukeLee1989** [comment]
https://www.youtube.com/watch?v=wizs8TEzwU8&feature=youtu.be

**Comment by kirwan** [comment]
Our next release will bring new animated GIF code which may help but memory limitations and time to decode animated images tends to result in this kind of delay.

**Comment by erikandre** [comment]
@DukeLee1989 Using a placeholder drawable might also help to make the issue less noticeable.

**Comment by DukeLee1989** [comment]
Thank you for the two

**Comment by oprisnik** [comment]
We've released [Fresco v1.4.0](https://github.com/facebook/fresco/releases/tag/v1.4.0), which includes a new implementation for animated GIFs that is way more performant. Please let us know if this fixed your issue.
