### ISSUE TITLE
Image from cache is not setting "centerCrop" correctly

### ISSUE THREAD

**Issue by santanaluiz** [facebook/fresco#1816]
### Description

I have an `ImageView` inside a `RecyclerView`.
Once the user tap on the image, the app starts an animation to my next `activity`. Which contains a bigger `ImageView`.
For this new `Activity` I first load the low-resolution URL (same used in my `RecyclerView`) and later load the full resolution.
**The problem is**: When I load this low res image from the cache, the `actualAspectRatio` is not working. It keeps as `fitCenter` and it should be `centerCrop`. (it's set in the XML but I also tried programmatically)

### Reproduction

1. Load image on a small `ImageView`
2. Load same image URL on a bigger `ImageView`
3. Fresco is not respecting the `actualScaleType`

### Additional Information

* Fresco version:1.3.0
* Platform version: Android SDK 26

**Comment by erikandre** [comment]
Hi @santanaluiz, are you using a shared element activity transition for animating between the two activities?

**Comment by santanaluiz** [comment]
Hi @erikandre,

Yes. I'm using with the following Transition:
```java
getWindow().setSharedElementEnterTransition(DraweeTransition.createTransitionSet(ScalingUtils.ScaleType.CENTER_CROP,ScalingUtils.ScaleType.FIT_CENTER));
```

**Comment by santanaluiz** [comment]
I just find the problem while writing you a comment. 
It was the transition set

Thank you :)
