### ISSUE TITLE
how to change load picture sequence

### ISSUE THREAD

**Issue by liujigang** [facebook/fresco#182]
like in GridView , I load a lot of picture,when i scroll to bottom, it's  take long time to display the bottom picture. How to let fresco load the visible DraweeView  primary.

**Comment by tyronen** [comment]
Hm, it looks like cancellation is not being implemented correctly.

As a workaround you can use [OkHttp](http://frescolib.org/docs/using-other-network-layers.html#using-okhttp)

**Comment by Ncit** [comment]
Okhttp does not help

**Comment by tyronen** [comment]
Stepping back - what kind of pictures are these? Network images, local files, resources, content provider?

**Comment by Ncit** [comment]
First time you load images from network,then from disk cache. When user scrolling items(Even if they are in disk cache) to the end of recyclerview visible items not shown immediately, they will be shown at the end. So user will wait for quit a long time to see those pictures. I can make video to show you more clear such situation.

**Comment by tyronen** [comment]
Yes, a video would be helpful.

Are these images JPEGs? Are you resizing or scaling them?

**Comment by tyronen** [comment]
Also please try again with today's release (0.4.0). It's possible that will fix this issue.

**Comment by liujigang** [comment]
good  ! ! !   给你三十二个赞。
