### ISSUE TITLE
Use of Android support libraries

### ISSUE THREAD

**Issue by mac-pro** [facebook/fresco#1826]
### Description

Fresco is using Android support libraries.

In my experiences, every new version of Android support library probably introduces new bugs. That happens no matter what its version name is (like only minor number changes). So for my own libraries which use Android support libraries, I always increase major version number if I change support library version -- which means my library's new version might break code. Also, I never user `+` for Android support libraries (even for patch version number).

### Reproduction

Not available.

### Solution

I've searched Fresco source in this commit 147c5e2f7e5a55ce99c223ace7c0826e553c0aa5 (July 14, 2017), and found only one use of Android support libraries in core code (not test/sample code): `android.support.v4.util.Pools`. I guess it's possible to make your own replacement.

Would you please consider accepting this suggestion?

### Additional Information

* Fresco version: 1.3.0

---

Thank you,

**Comment by foghina** [comment]
Hey @mac-pro, thanks for opening the issue. All of our dependencies should be declared as `provided`, in which case you can declare whatever version you want in your app, as long as the APIs that we use don't conflict (which they shouldn't). Are you finding that that is not the case?

**Comment by mac-pro** [comment]
Hi @foghina,

Thank you. I understand your point. However if I set your dependencies' versions, it obviously could break your code. I would propose these:

- If you want to use Android support libraries, it would help me a lot if you increase major version number when you change support libraries' versions (even for patch number, like `25.0.0` to `25.0.1`). For further cases, if you change any of your dependencies' versions, please increase your major number. I think it's a good practice.

- If you could consider removing support libraries, it would be really great. From my view, core code only uses one class `android.support.v4.util.Pools`, I think it could be replaced. Reducing unnecessary dependencies is always good, do you agree?  :-)

**Comment by kirwan** [comment]
As you say, we use very, very little of the support library.

We increase the version number we depend on because we use the same version for the annotations.

Looking at the support library repo shows that the [Pools](https://github.com/android/platform_frameworks_support/commits/master/compat/java/android/support/v4/util/Pools.java) class we depend on hasn't changed in a while and it's very unlikely that it will break anything whichever version you choose to use.

We could consider bringing that one class into the library (as could someone else via a pull request). It wouldn't affect the library size meaningfully.

I'm curious why this is a particular concern to you though, given I assume you use other libraries which also depend on the support library.

**Comment by foghina** [comment]
To add to what @kirwan said, increasing the major version of a library should be reserved for big breaking changes in the public API of said library. The support library is not part of our public API, so I wouldn't bump the major version when updating that.

**Comment by mac-pro** [comment]
Thanks @kirwan,

What I concern is, from my experiences, new version of support libraries almost introduces new bugs. So I tend to keep one old stable version. In case I update Fresco, what version (of support libraries) Fresco uses might be conflicted with mine.

For the major version and dependencies (not just support libraries), in my opinion, I would think that even the dependencies are not part of public API, but since they might break code, I tend to increase major number. Example:

- Fresco v1.0.0 uses dependency A v1.0.0. It works.

- Fresco v1.1.0 uses dependency A v1.1.0: Fresco code is tested and works perfectly, but dependency A might not. User's code (like mine) could break at this point.

Hopefully you could consider those concerns. And I have no further questions, I'm closing the issue  `:-)`

Thanks again for your hard work. Fresco helped me a lot.
