### ISSUE TITLE
Image loading with resize options

### ISSUE THREAD

**Issue by ankit02jindal** [facebook/fresco#1829]
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setProgressiveRenderingEnabled(true)
                    .setResizeOptions(new ResizeOptions(10,10))
                    .build();
use resize option 10 by 10 but still image  take time to load..

**Comment by foghina** [comment]
Hi @ankit02jindal! When you're loading an image with `ResizeOptions`, the whole image is still loaded from the server, it's just resized on the device so it takes up less memory (RAM) when displayed. If you want your images to load faster you should resize them on the server instead.
