### ISSUE TITLE
`SimpleDraweeView` doesn't set layout according to width and height when set to `wrap_content

### ISSUE THREAD

**Issue by omerasif57** [facebook/fresco#1831]
### Description
I follow the basic [tutorial](http://frescolib.org/docs/animations.html) on fresco website for animated images. 
Instead of setting `layout_width` and `layou_height` tags to fixed `130dp`, I set their value to `wrap_content`. (`match_parent` as well)
When I run it everything works fine except the `SimpleDraweeView` doesn't set layout according to width and height which is set to `wrap_content`. Gifs and View is loaded but View doesn't show up on screen. 

### Steps 
1: I followed the basic [tutorial](http://frescolib.org/docs/animations.html) of fresco.
2: I set SimpleDrawView layout width and height to `wrap_content`.  
        `android:layout_width="wrap_content"`
        `android:layout_height="wrap_content"`
3: SimpleDrawView and gif is loaded but didn't show up on screen
4: I was expecting to SimpleDrawView to detect Gif width and height automatically. (same case while loading images)

### Additional Information

* Fresco version: [1.4.0]
* Platform version: [Android, Moto X 2014, API Level 22]

**Comment by foghina** [comment]
See here: http://frescolib.org/docs/faq.html#why-cant-i-use-androids-wrap_content-attribute-on-a-draweeview
