### ISSUE TITLE
If bitmap not cached in bitmapMemoryCache,  Call the method to display the picture, the picture flash

### ISSUE THREAD

**Issue by duanyunfei** [facebook/fresco#1834]
If bitmap not cached in bitmapMemoryCache,  then call the method to display again, the picture will flash。I know it  caused by the Fresco display mechanism。Have a good way to avoid picture flashing? Because in some scenarios, can not be avoided to repeat the call.

I use fresco like this：

            ImageRequest imageRequest = createRequestByOption(uri, options, ImageRequest.RequestLevel.FULL_FETCH, simpleDraweeView);
            DraweeController draweeController = getDraweeController(imageRequest, simpleDraweeView, controllerListener);
            simpleDraweeView.setHierarchy(OptionToGenericDraweeHierarchy(uri, simpleDraweeView, options, needDefaultImage));
            simpleDraweeView.setController(draweeController);

thank you～

**Comment by foghina** [comment]
Are you setting the same image or a different image when it flashes? If it's the same image it **should** be in bitmap cache and there shouldn't be any flashing.

You can try using `RetainingDataSourceSupplier` from #1328 to keep the previous image while the new one is being loaded.

**Comment by duanyunfei** [comment]
@foghina  Thank you very much for your replay.   My application has a lot of pictures & activities & fragment，sometimes BitmapMemoryCache is full.   I have tried the method you provided and  encapsulation function like this and views not flash:

                ImageRequest imageRequest = createRequestByOption(uri, options, ImageRequest.RequestLevel.FULL_FETCH, simpleDraweeView);   //create a image request
                RetainingDataSourceSupplier<CloseableReference<CloseableImage>> retainingSupplier = (RetainingDataSourceSupplier<CloseableReference<CloseableImage>>) simpleDraweeView.getTag(R.id.jdImageLoader_supplier_tag);    //get the previous retainingSupplier
                if (retainingSupplier == null) {   //if null, create a new one
                    retainingSupplier = new RetainingDataSourceSupplier<>();
                    DraweeController draweeController = getDraweeControllerNotRest(imageRequest, simpleDraweeView, controllerListener, retainingSupplier);
                    simpleDraweeView.setHierarchy(OptionToGenericDraweeHierarchy(uri, simpleDraweeView, options, needDefaultImage));
                    simpleDraweeView.setController(draweeController);
                }
retainingSupplier.setSupplier(Fresco.getImagePipeline().getDataSourceSupplier(imageRequest, null, ImageRequest.RequestLevel.FULL_FETCH));   //send a request
                simpleDraweeView.setTag(R.id.imageLoader_supplier_tag, retainingSupplier);  //save the retainingSupplier to view tag

I want to encapsulate a method that everyone can use fresco quickly, i have to hold every SimpleDrawView repositorySupplier instance, so i used the view tag.  Does this way cause a memory leak?

**Comment by lambdapioneer** [comment]
@duanyunfei what kind of UI do you have where this issue appears? If it is a recycler view, you might want to have a look at the sample of the showcase app and check if it matches with your code: 

https://github.com/facebook/fresco/blob/1472a3e1b1655e9b52c74e0b06d5ba60d15a42f9/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeRecyclerViewFragment.java#L96-L132
