### ISSUE TITLE
addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by redpandatronicsuk** [facebook/fresco#1835]
### Description
When using webp images, I get an `addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).` error:
<img width="303" alt="screen shot 2017-07-21 at 13 36 45" src="https://user-images.githubusercontent.com/8609582/28463698-ae169026-6e19-11e7-8aef-4aedfdf7fe3d.png">

The code causing the error:
```
render() {
    const animals = this.animalShuffle.map(d=> {
        return <Image ref={d} key={d} source={imgs[d]}></Image>
    })
...
```

The component is created inside the render function (though in a nested map). The error only happens when I use .webp images.

### Reproduction
Initialise a react-native project, add
```
compile 'com.facebook.fresco:animated-webp:1.0.1'
compile 'com.facebook.fresco:webpsupport:1.0.1'
```
to `app/build.gradle` and use a webp image as a source for an image with a ref.

### Additional Information

* Fresco version: 1.0.1
* Platform version: Android Emulator Nexus_5X_API_25_x86
* React Native: 0.46.4

**Comment by foghina** [comment]
This looks very specific to React Native and not Fresco. My guess is any image format would give the same error. Can you confirm that this only happens for webps?

**Comment by redpandatronicsuk** [comment]
I just tried to recreate the error and you are right, it get the error regardless of image format. However, it used to work before I tried using webp. Must have changed something else too in the meanwhile I suppose.

**Comment by redpandatronicsuk** [comment]
**UPDATE**
I found a solution now. Using `ref={d => this.myRefs[d] = ref}` seems to work.
