### ISSUE TITLE
change the loading progressbar

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [facebook/fresco#1842]
hi
how to change the loading progressbar when the image is loading. i want to implement something like the below image.

and also is it possible to get the percent of progress when loading an image?

![untitled](https://user-images.githubusercontent.com/15226836/28610383-639252b4-71fd-11e7-9543-66c483d2ced4.png)

**Comment by lambdapioneer** [comment]
Hi @AlirezaGhanbarinia,

see http://frescolib.org/docs/progress-bars.html on how to create your own progress drawable. Feel free to re-open if there's something that remained unclear.
