### ISSUE TITLE
Animate the transition between fragments

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [facebook/fresco#1844]
hi
in the below sample i want to open a fragment instead of an activity and the transition be implemented inside the fragment and not the activity.
is it possible?
"showcase" sample > DraweeTransitionFragment > ImageDetailsActivity >startTransition

**Comment by lambdapioneer** [comment]
Hi @AlirezaGhanbarinia,

we use the GitHub issues for bug reports and questions particular to the Fresco library. You are likely to get a better answer when raising this on stackoverflow (or similar platforms). I'll close this for now.

If I've misunderstood your questions and it's related to a bug in Fresco, please re-open and comment with a repo and we'll have a look.
