### ISSUE TITLE
SVG support toggle not working

### ISSUE THREAD

**Issue by a-d-collins** [facebook/fresco#1850]
### Description

Case 1: (In showcase app) Turned on SVG support and expected SVG image to load. SVG image does not load.
Case 2: (In showcase app) Turned off SVG support and expected app to re-attempt loading of SVG. Instead, nothing changed.

If Showcase app is restarted and SVG support is already "on", SVG image loads.

### Reproduction

1. Run showcase app.
2. Turn on/off SVG support.

### Solution

(**ImageFormatSvgFragment.java**) Amend `switchCompat.setOnCheckedChangeListener()` so that image is re-loaded after the status of the toggle is changed.

### Additional Information

* Fresco version: 1.4.0
* Platform version: SDK 23

**Comment by kirwan** [comment]
As you've seen the app needs to be restarted because custom decoders can only be set during the initialisation of Fresco during app creation.

We should fix the Showcase so that this switch requests/triggers a restart.

**Comment by a-d-collins** [comment]
That makes sense. I was not aware of the necessity to restart Fresco. I'll look into that.

**Comment by a-d-collins** [comment]
@kirwan, is there any existing code that requests/triggers a restart like that? In SettingsFragment.onSharedPreferenceChanged() I found some switch-statement cases that run getShowRestartMessageDialog(), but I'm not sure if you're referring to that.

**Comment by kirwan** [comment]
Exactly @a-d-collins, a dialog like `ShowRestartMessageDialog` should be used to make it clear the restart is necessary.

**Comment by a-d-collins** [comment]
Roger that.

**Comment by oprisnik** [comment]
This has been implemented. A toggle will be shown to inform you that the app needs to be restarted.

**Comment by a-d-collins** [comment]
Awesome! Thanks for letting me know!
