### ISSUE TITLE
fresco1.4.0, when display gif ,there is always a space on the right.

### ISSUE THREAD

**Issue by liubao** [facebook/fresco#1851]
### Description

fresco1.4.0, when display gif ,there is always a space on the right.

### Reproduction

fresco1.4.0, when display gif ,there is always a space on the right.

### Solution

fresco1.4.0, when display gif ,there is always a space on the right.

### Additional Information

fresco1.2.0,1.3.0 displays OK

**Comment by kirwan** [comment]
Can you please provide an example URL for a GIF which is showing this issue?

**Comment by liubao** [comment]
https://b3-q.mafengwo.net/s10/M00/8B/19/wKgBZ1lDmPWABs9bAA6C1VXHu94895.gif?imageMogr2%2Fthumbnail%2F%21516x369r%2Fgravity%2FCenter%2Fcrop%2F%21516x369%2Fquality%2F90%7Cimageslim @kirwan

**Comment by oprisnik** [comment]
The image renders correctly for me both with fitCenter and centerCrop, see:

![screen shot 2017-11-07 at 11 59 20 am](https://user-images.githubusercontent.com/2699634/32492708-27d82d90-c3b3-11e7-9ab7-41973cb50b4f.png)

Please take a look at the sample app here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/gif/ImageFormatGifFragment.java
