### ISSUE TITLE
how to release bitmap cache when activity call  onStop()

### ISSUE THREAD

**Issue by lushan1314** [facebook/fresco#1853]
when actA jump to actB,how to release the bitmap caches from actA

**Comment by lushan1314** [comment]
actA - > actB - > actA - > actB...OOM will eventually occur,I wonder how to release the previous bigmap resources in the activity？

**Comment by kirwan** [comment]
You should not have to do this yourself. If the cached bitmaps aren't being held on by anything else they will clear themselves.

I suggest you use Stetho to debug how many images are being held as you make each activity jump. See #1719 for how to add Stetho and use it.
