### ISSUE TITLE
How to display byte[] image in database with Fresco?

### ISSUE THREAD

**Issue by zhufeng1222** [facebook/fresco#1856]
name | type
----|----
ID|	INTEGER
ORIGIN_IMAGE|	BLOB
CONVERT_IMAGE|	BLOB

I want to use the URI like this (content://authority/table_name/id/ORIGIN_IMAGE) to show the ORIGIN_IMAGE.</br>
Is this possible?</br>
Is there some way to do this?

**Comment by erikandre** [comment]
Hi @zhufeng1222, to make that work you would need to implement a ContentProvider that queries your database and returns the image data. After doing so, you can use a "content://" url with Fresco to load the image.

I'm going to close this issue, but if there is something else that is not clear, please leave another comment and we can reopen it. Thanks!

**Comment by zhufeng1222** [comment]
How can a “content://” returns the image data？

**Comment by zhufeng1222** [comment]
Is there a sample?

**Comment by erikandre** [comment]
You could do something similar to this answer on Stackoverflow: https://stackoverflow.com/a/30028763

Instead of storing the image in the database, it might be simpler to just store the URL, and then let Fresco load and cache the image on disk for you.
