### ISSUE TITLE
Local Image is not displayed on 1.4.0

### ISSUE THREAD

**Issue by stayf** [facebook/fresco#1858]
### Description

I use the library to display local images. This is my code:

```
Log.i("photo=" + photo);
ImageRequest request = (ImageRequestBuilder.newBuilderWithSource(Uri.parse(photo)).build());
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setOldController(getController())
                    .setImageRequest(request)
                    .build();
            setController(controller);
```

So photo=file://data/user/0/com.test.app/cache/thumb/profile/thumb0.png

It works great on the version 1.0.0.
I updated the dependence in the gradle on 1.4.0 and Image is not displayed

### Additional Information

* Fresco version: 1.4.0
* Platform version: Any

**Comment by erikandre** [comment]
Hi @stayf - Would it make any difference if you add another "/" to that URI, like this:

`file:///data/user/0/com.test.app/cache/thumb/profile/thumb0.png`

**Comment by stayf** [comment]
Thanks, it works
