### ISSUE TITLE
SimpleDraweeView RecyclerView

### ISSUE THREAD

**Issue by Anmolk22** [facebook/fresco#1860]
SimpleDraweeView in recycler view when fetched in RecyclerView adapter's onBindViewHolder() method sometime returns 0 for simpleDraweeView.getWidth() method

**Comment by erikandre** [comment]
Hi @Anmolk22 

Could you please share some of your code, showing how you:

1. How you request the image to be loaded into the SimpleDraweeView in onBindViewHolder
2. Where you call .getWidth()

Thanks!

**Comment by erikandre** [comment]
Also, for the SimpleDraweeView, what does the xlm layout look like for each item in the recyclerview?

**Comment by Anmolk22** [comment]
```
public void onBindViewHolder(RecyclerViewHolder holder, int position) {
            setUpImages(holder, position);
}

setUpImages(RecyclerViewHolder holder, int position){
           if(!imagePath.equalsIgnoreCase("null")){
            SimpleDraweeView simpleDraweeView = holder.getImage();
            simpleDraweeView.setVisibility(View.VISIBLE);
            Log.d("sdv", "simpleDraweeWidth Width"+simpleDraweeView.getWidth());
            setUpImages(simpleDraweeView, url);
      }
setUpImages(final SimpleDraweeView imageViewHolder, final String url){
        imageViewHolder.getViewTreeObserver()
                .addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
            @Override
            public boolean onPreDraw() {
                imageViewHolder.getViewTreeObserver().removeOnPreDrawListener(this);
                ImageRequest imageRequest;
                try{
                    imageRequest = ImageRequestBuilder
                            .newBuilderWithSource(Uri.parse(url))
                            .setResizeOptions(
                                    new ResizeOptions(imageViewHolder.getWidth(),
                                            imageViewHolder.getHeight()))
                            .build();

                    PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                            .setOldController(imageViewHolder.getController())
                            .setImageRequest(imageRequest)
                            .build();
                    imageViewHolder.setController(controller);
                } catch (Exception e){
                    Log.d("imageViewHolder", imageViewHolder.getWidth()+"width height"+imageViewHolder.getHeight()
                            +" urlPainting"+ urlPainting);
                    e.printStackTrace();

                }
                return true;
            }
        });}
}

/*XML CODE*/
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingBottom="10dp"
    android:paddingLeft="10dp"
    android:paddingRight="10dp"
    android:paddingTop="10dp">

<RelativeLayout
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:id="@+id/imageRelativeView">

                    <com.facebook.drawee.view.SimpleDraweeView
                        android:id="@+id/recyclerImageVIewHolder"
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        fresco:actualImageScaleType="none" />

</RelativeLayout>
</LinearLayout>

```

I have infinite scrolling when I scroll I monitor the log as well and I found out that sometimes it returns me with the value 0 for both width and height, The above code is the logic for fetching the SimpleDraweeView from ViewHolder through a getter method into the onBindViewHolder method of the recyclerView adapter

**Comment by erikandre** [comment]
Ok, I don't quite understand what is going on in `setUpImages`, why set the controller from inside he global layout listener?

**Comment by Anmolk22** [comment]
in the Setup image method I am actually taking up the dimensions of the simpledraweeview and resizing the image in order to optimize the memory usage as if I would have directly setup the URI to the SimpleDraweeView the ram usage for the recycler view will go up to 120mb while now the memory wont cross 25 mb

**Comment by UFreedom** [comment]
I also encountered this problem during use, but when I couldn't get the size of DraweeView, 
I did:

```
draweeView.post(new Runnable() {
                        @Override
                        public void run() {

                            printLog("ViewActualSize w: " + genericDraweeView.getMeasuredWidth() + " h: " + genericDraweeView.getMeasuredHeight());
                          ...
                        }
                    });
```

**Comment by Anmolk22** [comment]
@UFreedom  It seems to be an issue. What I think is while scrolling the view of the SimpleDraweeView or Drawee view is not getting created i.e it is returning 0

**Comment by erikandre** [comment]
@Anmolk22 , I would not recommend using this approach in a RecyclerView since the view could potentially be recycled before any draw occurs.

If possible, please use a fixed size for the SimpleDraweeView or use a fixed aspect ratio.

**Comment by Anmolk22** [comment]
@erikandre Sorry for the late reply.
Actually I have found the solution the issue was due to the recyclerview's recycling after I disabled the recycling in recyclerview in OnBind method. it's not happening

**Comment by erikandre** [comment]
Yes, the problem should be that using global layout listeners on views in a recycler view is not safe. I would still recommend that you either go with a fixed size or a fixed aspect ratio for the drawee views. You should then be able to already know the dimensions in onBind.

**Comment by v-b-r** [comment]
As observed earlier, draweeView.getWidth() does return zero sometimes in recyclerView. Incase if someone is trying to set view height based on actual image aspect ratio, instead of setting width and height layout params dynamically, you can simply use <b> setAspectRatio() </b> to get it done. (Note: I'm assuming <b>width is fixed</b>)
