### ISSUE TITLE
fresco  bitmap 

### ISSUE THREAD

**Issue by jhonween** [facebook/fresco#1861]
it can get a bitmap synchronize use ImageLoader
Bitmap bitmap = ImageLoader.getInstance().loadImageSync((medicalRecordImage.getPath());

so how to use Fresco to get a Bitmap synchronize?

**Comment by erikandre** [comment]
Hi @jhonween, please see documentation http://frescolib.org/docs/using-image-pipeline.html (section called "Synchronous image loading")
