### ISSUE TITLE
System app installing issue with .so files

### ISSUE THREAD

**Issue by pvkumar4125** [facebook/fresco#1864]
### Description
We built our app with fresco, then compiled our app with android os to load app as system app and then flashed to device. The app failed to install in device.
As of some sources, we got to know that failure may be with .so files contained in the apk. 
The only .so files in our app are belonging to fresco: libimagepipeline.so(x86, x86_64, arm64-v8a, armeabi, armeabi-v7a)
### Additional Information

* Fresco version: 1.0.1
* Platform version: 7.0
* min SDK version of app: 16
* max SDK version of app: 23

**Comment by erikandre** [comment]
Hi @pvkumar4125 , could you please attach some logcat logs showing the error that occurs during installation?
Some information about the device would also be useful.
Thanks!

**Comment by pvkumar4125** [comment]
In the logs we got only details that it is failed to parse and collect the certificates from my app with below details:

PackageManager: Failed to parse **/vendor/operator/app/_AppName_:** Failed to collect certificates from **/vendor/operator/app/_AppName_:/_AppName_.apk**

**Comment by kirwan** [comment]
If you're building a system app, I think you're supposed to put the .so files in `/system/lib/`. There are probably better places to get help with building and deploying system apps though.

**Comment by pvkumar4125** [comment]
Hi @kirwan, does the fresco itself takes care of loading .so files from /system/lib/ or do we need to do anything to load .so files manually?

**Comment by kirwan** [comment]
By default we include a lightweight, naive SoLoaderShim implementation which should work for you. You can make this more robust by using SoLoader or ReLinker, as per [this comment](https://github.com/facebook/fresco/issues/1817#issuecomment-313374035).

**Comment by erikandre** [comment]
Closing issue due to lack of updates
