### ISSUE TITLE
oom occurs when using 'roundedCornerRadius' option in xml

### ISSUE THREAD

**Issue by ys144756** [facebook/fresco#187]
hi.

now i'm trying to load local bitmap files into SimpleDraweeView
it looks like working well, but when i use 'roundedCornerRadius' option in xml file, oom occurs.

actually, local bitmap is too large. so i also use 'actualImageScaleType' for scaling.
but oom is still occurs..

how can i do?
thanks.

**Comment by ys144756** [comment]
or, if i must use resize options, is there any other ways to auto-resize to SimpleDraweeView?

**Comment by tyronen** [comment]
1) Can you attach a stack trace of the OOM?
2) Are you using `roundWithOverlayColor`? If you do, do you still get the OOM? 

But in general, very large images should indeed use ResizeOptions. You can try something like this:

```java
LayoutParams layoutParams = simpleDraweeView.getLayoutParams();
int width = layoutParams.getLayoutWidth();
int height = layoutParams.getLayoutHeight();
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
    .setResizeOptions(new ResizeOptions(width, height))
    .build();
PipelineDraweeController controller = Fresco.newDraweeControllerBuilder()
    .setOldController(mDraweeView.getController())
    .setImageRequest(request)
    .build();
mSimpleDraweeView.setController(controller);
```

**Comment by ys144756** [comment]
1) i'm sorry, i wasn't see OOM. just i guess it.
2) when i tried with 'roundWidthOverlayColor', OOM is not occurred.

**Comment by tyronen** [comment]
Okay, so what did you see? If your app crashed, please provide a dump of [logcat](http://developer.android.com/tools/debugging/debugging-log.html)

**Comment by ys144756** [comment]
i can't see anything about 'error' log.
so i attach 'verbose' level log.


04-23 19:06:43.704  12926-13377/x.x.x.x D/dalvikvm﹕ GC_FOR_ALLOC freed 373K, 13% free 22621K/25892K, paused 28ms, total 28ms
04-23 19:06:43.704  12926-13377/x.x.x.x I/dalvikvm-heap﹕ Grow heap (frag case) to 28.347MB for 4194320-byte allocation
04-23 19:06:43.994  12926-13379/x.x.x.x D/dalvikvm﹕ GC_FOR_ALLOC freed 528K, 13% free 26209K/29992K, paused 23ms, total 23ms
04-23 19:06:44.004  12926-13379/x.x.x.x I/dalvikvm-heap﹕ Grow heap (frag case) to 31.806MB for 4147216-byte allocation
04-23 19:06:44.394  12926-12926/x.x.x.x W/OpenGLRenderer﹕ Bitmap too large to be uploaded into a texture (4160x3120, max=4096x4096)
04-23 19:06:44.414  12926-12926/x.x.x.x W/OpenGLRenderer﹕ Bitmap too large to be uploaded into a texture (4160x3120, max=4096x4096)
04-23 19:06:44.424  12926-12926/x.x.x.x W/OpenGLRenderer﹕ Bitmap too large to be uploaded into a texture (4160x3120, max=4096x4096)
04-23 19:06:44.424  12926-12926/x.x.x.x A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x3f800010 (code=1), thread 12926 (.messenger.main)
04-23 19:06:44.454  12926-13377/x.x.x.x D/dalvikvm﹕ GC_FOR_ALLOC freed 4098K, 11% free 26785K/29856K, paused 20ms, total 20ms
04-23 19:06:44.504  12926-13377/x.x.x.x D/dalvikvm﹕ GC_FOR_ALLOC freed 6K, 11% free 27329K/30408K, paused 21ms, total 21ms
04-23 19:06:44.524  12926-13377/x.x.x.x D/dalvikvm﹕ GC_FOR_ALLOC freed <1K, 10% free 28004K/31084K, paused 20ms, total 20ms

**Comment by ys144756** [comment]
is there any way to enable fresco log?

**Comment by tyronen** [comment]
Yes, your bitmap is too large. You have to resize it.

**Comment by ys144756** [comment]
i have curiosity about OOM in fresco.
why OOM is occurred?

please give me a answer..

[seanario]
1. 16mb memory is available.
2. 6 each SimpleDraweeView is viewing. [1,2,3,4,5,6]
3. load 5mb image with no resizing. (encoded size)
4. maybe 1,2,3 SimpleDraweeView is success to load image.
5. now 15mb memory is allocated and then 4 is now loading
6 then..? crash or..?

if crashes occur, should i check available memory always?
i'm sorry about my pool english.

thanks.

**Comment by tyronen** [comment]
The crash isn't caused by running out of memory. It's caused by the OpenGL hardware that actually displays the image. This cannot render a resolution greater than 4096 x 4096, as your earlier log indicated.
