### ISSUE TITLE
How to render local image named end with ".mp4"?

### ISSUE THREAD

**Issue by HenryChao24** [facebook/fresco#1870]
for example: image path like this:  
/storage/emulated/0/test.mp4

yes, it's actual a jpg image with wrong suffix name.

**Comment by oprisnik** [comment]
Fresco doesn't check the file suffix. Just pass the file to a DraweeView and it should work. See also http://frescolib.org/docs/supported-uris.html

**Comment by imliujun** [comment]
[aaaa.mp4.zip](https://github.com/facebook/fresco/files/1937149/aaaa.mp4.zip)

This file is in jpg format, but changing the suffix name to mp4 fails to load
