### ISSUE TITLE
Update fresco from 1.3.0 to 1.4.0 cause bug TooManyBitmapsException

### ISSUE THREAD

**Issue by wangbin0802** [facebook/fresco#1873]
Before update we have not occured this problem.
Exception com.facebook.imagepipeline.common.TooManyBitmapsException:
com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.pinBitmap ()
com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.pinBitmap ()
com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage ()
com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGFromEncodedImage ()
com.facebook.imagepipeline.bitmaps.HoneycombBitmapFactory.createBitmapInternal ()
com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap ()
com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap ()
com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback ()
com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback ()
com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback ()
com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrame ()
com.facebook.fresco.animation.backend.AnimationBackendDelegate.drawFrame ()
com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck.drawFrame ()
com.facebook.fresco.animation.drawable.AnimatedDrawable2.draw ()
com.facebook.drawee.drawable.ForwardingDrawable.draw ()
com.facebook.drawee.drawable.ForwardingDrawable.draw ()
com.facebook.drawee.drawable.ScaleTypeDrawable.draw ()
com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha ()
com.facebook.drawee.drawable.FadeDrawable.draw ()
com.facebook.drawee.drawable.ForwardingDrawable.draw ()
com.facebook.drawee.generic.RootDrawable.draw ()
android.widget.ImageView.onDraw (ImageView.java:1040)
android.view.View.draw (View.java:15430)
android.view.View.getDisplayList (View.java:14324)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3296)
android.view.View.getDisplayList (View.java:14261)
android.view.View.getDisplayList (View.java:14366)
android.view.HardwareRenderer$GlRenderer.buildDisplayList (HardwareRenderer.java:1597)
android.view.HardwareRenderer$GlRenderer.draw (HardwareRenderer.java:1469)
android.view.ViewRootImpl.draw (ViewRootImpl.java:2785)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2651)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2219)

How can I solve this problem?

**Comment by Haoxiqiang** [comment]
same problem.Android 4.4 catch a lot exception in some device.

**Comment by dmitry-voronkevich** [comment]
Hi, @wangbin0802, please provide more details:
* How do you use Fresco?
* Do you have sample images?
* Is there sample app where this issue can be reproduced?
* Where and how do you show images (ListView, RecycleView, anything else)?
* How many images do you show at the same time? 
* Do you store DraweeView's anywhere in the memory, like caching them in HashMap for example? 
* Are DraweeView attached/detached correctly?

**Comment by wangbin0802** [comment]
@dmitry-voronkevich, I use fresco normally like sample in my production, it run good before.I can not reproduce it when testing, But I can collect the crash report from the third party instrument.
My production will show many images at home page, I use the default memory control and it has never been occured this situation.
Cache configure like:
```
configBuilder
                .setBitmapMemoryCacheParamsSupplier(new LollipopBitmapMemoryCacheParamsSupplier())
                .setMainDiskCacheConfig(
                        DiskCacheConfig.newBuilder(context)
                                .setBaseDirectoryPath(context.getApplicationContext().getCacheDir())
                                .setBaseDirectoryName(IMAGE_PIPELINE_CACHE_DIR)
                                .setMaxCacheSize(MAX_DISK_CACHE_SIZE)
                                .build());
```
```
public MemoryCacheParams get() {
        return new MemoryCacheParams(
                getMaxCacheSize(),
                Integer.MAX_VALUE,
                getMaxCacheSize(),
                Integer.MAX_VALUE,
                Integer.MAX_VALUE);
    }
```
Please be aware.Thanks a lot.

**Comment by dmitry-voronkevich** [comment]
Hi @wangbin0802,

This issue maybe related to change in 1.4.0. Fresco animated images stared to respect caching rules, in 1.3.0 they were ignoring such rules sometimes.
Currently number of images are limited via constant in Fresco code:  https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/BitmapCounterProvider.java#L24

Feel free to sent us a pull request with changes which will allow configuration of this constant when app is initialized.

**Comment by wangbin0802** [comment]
Hi @dmitry-voronkevich
I have pulled the newest code, you mean that I need limit the MAX_CACHE_ENTRIES from Integer.MAX_VALUE to 256(copy `DefaultBitmapMemoryCacheParamsSupplier`) can fix the issue?
```
 @Override
  public MemoryCacheParams get() {
    return new MemoryCacheParams(
        getMaxCacheSize(),
        MAX_CACHE_ENTRIES,
        MAX_EVICTION_QUEUE_SIZE,
        MAX_EVICTION_QUEUE_ENTRIES,
        MAX_CACHE_ENTRY_SIZE);
  }
```

**Comment by erikandre** [comment]
Duplicating to #1980
