### ISSUE TITLE
1.4.0 bug : "asCircle" invalid sometimes

### ISSUE THREAD

**Issue by Vixb1122** [facebook/fresco#1876]
if I add the following line to build.gradle file , that's no problem
```
compile 'com.facebook.fresco:fresco:1.4.0'
```

but if I add the following line to build.gradle file , displaying some pictures by using "asCircle" is invalid
```
compile 'com.facebook.fresco:fresco:1.4.0' 
compile 'com.facebook.fresco:animated-gif:1.4.0'
```

eg:
http://p1.music.126.net/n4ypQKBBkp4NMdMb2Bxr6Q==/2042892604407899.jpg

**Comment by dmitry-voronkevich** [comment]
This issue reproduces with this particular image. Other images work fine.

**Comment by dmitry-voronkevich** [comment]
@Vixb1122, your image is a gif (despite of jpeg extension), once you added support for animated-gif, library started to treat any gif as animated image. And library does not currently support rounding of animated images. I'd recommend to use png for such images, they will take less space and provide better quality.
Or if you don't have control of where images comes from, you can request image with image request and specify imageDecodeOptions.forceStaticImage = true.
```
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse("http://p1.music.126.net/n4ypQKBBkp4NMdMb2Bxr6Q==/2042892604407899.jpg"))
                .setImageDecodeOptions(new ImageDecodeOptionsBuilder()
                        .setForceStaticImage(true)
                        .build())
                .build();

        DraweeController controller = Fresco.getDraweeControllerBuilderSupplier().get()
                .setImageRequest(request)
                .build();
        draweeView.setController(controller);
```

**Comment by dmitry-voronkevich** [comment]
I hope, @Vixb1122, this answer is enough. If you still having issue, feel free to reopen this bug.

**Comment by Vixb1122** [comment]
thanks , that's helpful @dmitry-voronkevich
