### ISSUE TITLE
[React Native] Inline image not animated when wrapped in a Text component 

### ISSUE THREAD

**Issue by tikkichan4** [facebook/fresco#1878]
I am using Fresco v1.0.1 (Latest version with React native supported).
It just works fine in IOS and Android when rendering the gif only.
Once the image is wrapped in a text component, it just dont worked. (The image component always display the first frame of gif, but not animated)

Please note that this bug is reported by other user before. But that issue is closed without situation.

**Comment by kirwan** [comment]
I think you should raise this issue in the React Native project.

Fresco is only used by RN on Android but I'm not sure whether you're seeing this on both platforms.

I'd also suggest linking to the previous bug report.

**Comment by doublex** [comment]
Same issue (fresco 1.3)

**Comment by oprisnik** [comment]
Please raise this issue with React Native! Thanks!
