### ISSUE TITLE
fresco在Listview中的一个bug

### ISSUE THREAD

**Issue by nansong66** [facebook/fresco#1881]
您好，我是一个菜鸟，今天遇到了一个问题/滑稽，就是fresco如果关闭自动缓存，就会出现一个问题，在listview中，一个item被滚出屏幕视角后，在滚回来，这时就会重新请求图片，如果这时还没请求回图片就再次把这个item滚出屏幕视角，这个时候程序就会崩溃，也有个能是在这个之后滚回来发生的。。。。我比较菜。。

**Comment by kirwan** [comment]
Very sorry but we only can only help with issues in English.

很抱歉，我们只能帮助英文问题。
(Google Translate)
