### ISSUE TITLE
Add rounding support for RTL languages to GenericDraweeView

### ISSUE THREAD

**Issue by adamc01** [facebook/fresco#1898]
Can we add rounding support for RTL languages to GenericDraweeView?

Need to add:
```
fresco:roundTopStart
fresco:roundTopEnd
fresco:roundBottomStart
fresco:roundBottomEnd
```

Android Studio already recommends using start/end instead of left/right in support of RTL languages (e.g., android:paddingLeft -> android:paddingStart)

I would be happy to help contribute too.

thanks,
Adam

**Comment by erikandre** [comment]
Hi @adamc01 

Good idea! Please feel free to contribute an implementation of this.
A good place to start would be in:

- drawee/src/main/res/values/attrs.xml
- drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchyInflater.java
