### ISSUE TITLE
SimpleDraweeView set ScaleType not worked

### ISSUE THREAD

**Issue by yelonglt** [facebook/fresco#1906]
How to set ScaleType on SimpleDraweeView when load dynamic webp or gif.
I set ScaleType any type not worked.
`
GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(getContext().getResources()).build();
        hierarchy.setActualImageScaleType(ScalingUtils.ScaleType.FIT_XY);
        mSimpleDraweeView.setHierarchy(hierarchy);
`

**Comment by oprisnik** [comment]
Please take a look at our scale type example in the Showcase app.
You can set a URI override in the setting and everything works fine for me if I use a GIF.

See https://github.com/facebook/fresco/blob/4b54d54688565e57d7b290b214a7db38f74dec74/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeScaleTypeFragment.java
