### ISSUE TITLE
SIGSEGV crashed at libstatic-webp.so on x86 

### ISSUE THREAD

**Issue by newjorchen** [facebook/fresco#1907]
hi, I've introduced fresco which version is 1.3.0. However, I got the SIGSEGV crashed at libstatic-webp.so when run on x86 android phone.  The stack info is: 
libstatic-webp.so + 0x7ca97
    eip = 0x683d9a97   esp = 0x6befd61c   ebp = 0x6f33e280   ebx = 0x6840df10
    esi = 0xf3f00000   edi = 0x0000000a   eax = 0x6f33df30   ecx = 0x00000000
    edx = 0x683e78f0   efl = 0x00210246
and the corresponding assemble instruction(reassemble by IDA) is "movdqa  [esp+1Ch+var_1C], xmm6". I looked at the function of movdqa on web, and there exist an detailed description at [1]. It said that 'when the source or destination operand is a memory operand, the operand must be aligned on a 16-byte boundary or a general-protection exception (#GP) will be generated.'  However, the esp value printed on stack info are not aligned 16-byte. So, I wonder if the unaligned esp access leaded to this crash. If so,   Can we add '-falign-stack=maintain-16-byte' flag to request compiler to avoid unaligned access? [2]

ref: [1]. http://x86.renejeschke.de/html/file_module_x86_id_183.html
[2].https://software.intel.com/en-us/forums/intel-c-compiler/topic/277295

Brs
newjor

**Comment by foghina** [comment]
Hello, thank you for the report! What device / emulator and Android version does this happen on? Also, can you repro with the latest version of Fresco?

CC @lambdapioneer for native magic.

**Comment by newjorchen** [comment]
@foghina  the device crashed is ASUS T00J. Since the API of the Fresco are different between 1.3.0 and 1.5, and our project originally use 1.3.0, I do not try to upgrade to latest version.  I tried to rebuild the 1.3.0 by adding the flags '-mstackrealign -mincoming-stack-boundary=4', but the output library libstatic-webp.so has nothing different in the size and the function entry, and the app still crashed when using that library. I guess that may be not the esp disalignment leaded to crash.

**Comment by lambdapioneer** [comment]
Hi @newjorchen, thanks for raising the bug and thanks for having a detailed look already.

Does this bug only show on x86? Does it also crash on other x86 devices? Does that image also crash when you display it in the showcase app?

My guess is that it might be specific to a certain webp image. Can you share a crashing image with us?

**Comment by erikandre** [comment]
Closing due to lack of information to proceed with an investigation.
