### ISSUE TITLE
focusCrop doesn't work correctly with sharedTransitions

### ISSUE THREAD

**Issue by ryanzor** [facebook/fresco#1908]
### Description

When using scaleType "focusCrop" for a shared transition the image will change to be centerCropped then the shared Transition will take place.  On the exit transition, it will transition to be centerCropped and then after the transition finishes it will move to the focusCrop.

I am using setLegacyVisibilityHandlingEnabled, but don't think that matters.

### Reproduction

This is a video of the issue happening with transitions set to 5x slower than normal, so the issue is more visible.

![ezgif com-optimize](https://user-images.githubusercontent.com/1966657/30776810-2518a9a0-a062-11e7-9e74-355630ceced9.gif)

Testing on pixel with Android O, physical device.

### Solution

I'm guessing the transition magic just isn't aware that focus crop is a thing, so ideally when the transition image is displayed it can be aware of that, not sure if that is possible though.

### Additional Information

* Fresco version: 1.5.0
* Platform version: Pixel, O, physical device.  Seen it on on emulators as well.

**Comment by foghina** [comment]
CC @oprisnik

**Comment by oprisnik** [comment]
Thanks for the report, this has been fixed with e7993cc40fd3c0fc0becde2c11039e797813a813

All combinations, including focus crop should now work.
