### ISSUE TITLE
java.lang.RuntimeException: Failed to pin Bitmap

### ISSUE THREAD

**Issue by yline** [facebook/fresco#1909]
1) the way i used:

```
        ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(imageUri);
        imageRequestBuilder.setProgressiveRenderingEnabled(true);
        ImageRequest imageRequest = imageRequestBuilder.build();

        PipelineDraweeControllerBuilder controllerBuilder = Fresco.newDraweeControllerBuilder();
        // controllerBuilder.setOldController(frescoView.getController());
        controllerBuilder.setImageRequest(imageRequest);
        DraweeController controller = controllerBuilder.build();

        // GenericDraweeHierarchy genericDraweeHierarchy = frescoView.getHierarchy();

        frescoView.setController(controller);
```

2) So the question happend:
[issues.txt](https://github.com/facebook/fresco/files/1328230/issues.txt)

the issues.txt is my log for the problem;

3) last: the version that i use

```
    compile 'com.facebook.fresco:fresco:1.5.0'                // 主依赖
    compile 'com.facebook.fresco:animated-gif:1.5.0'  // 支持gif动图
    compile 'com.facebook.fresco:animated-webp:1.5.0'// 支持webp动态
    compile 'com.facebook.fresco:webpsupport:1.5.0'  // 支持webp静态
    compile 'com.facebook.fresco:imagepipeline-okhttp3:1.5.0'
```

**Comment by foghina** [comment]
Hi @yline, thanks for the bug report! Can you tell us what device & Android version this happens on specifically? Your usage of Fresco looks ok.

**Comment by yline** [comment]
I try again many times;  the Device is "魅族"；Android version : "6.0"

**Comment by foghina** [comment]
Pinning bitmaps only happens on Android 4.4 and below, so I don't understand why we would try to pin on a 6.0 device. What is the value of `Build.VERSION.SDK_INT` on your device?

**Comment by yline** [comment]
A blunder resulting from the avoidance of a machine. I tried a few more attempts.

Three Machine;
1）meizu，Android6.0
Fresco show the view failed, if the picture is "jpg" or other
Also it show the view well, if the pictre is "png"

2）the virtual device created by Android Studio in windows 
Corresponding information ： Nexus 5X API 23 &&  Android 6.0(Google APIs)  &&  CPU(X86) 
Fresco show the view failed, if the picture is "jpg" or other
Also it show the view well, if the pictre is "png"

3）the virtual device created by Android Studio in windows 
Corresponding information ： Nexus 5X API 26 &&  Android 8.0(Google APIs)  &&  CPU(X86) 
Fresco work well.

the code web size:
https://github.com/yline/as_x_jar/blob/master/Fresco/FrescoSample/src/main/java/com/yline/fresco/activity/sample/DebugActivity.java

I give you the apk.


[FrescoSample-debug.zip](https://github.com/facebook/fresco/files/1346038/FrescoSample-debug.zip)

The operate:
AppLauncher --> DebugActivity --> “click the onJpgClick” or "click the onFailedClick"

**Comment by yline** [comment]
So you should be able to repeat what I said.

Just Create the visual device by Android Studio. You will see the situation

**Comment by geetgobindsingh** [comment]
Hi what is the status of above issue, any solution? Cause we are also getting same kinda issue.

**Comment by erikandre** [comment]
Merging with issue #1862
