### ISSUE TITLE
Decoding images over HTTP that returns 204 status response

### ISSUE THREAD

**Issue by MiguelCa-MSFT** [facebook/fresco#1910]
### Description

Fresco throws an IllegalArgumentException (with "unknown image format" as message) when decoding an image over HTTP that returns a 204 status code. Here there is more information about 204 status code: https://httpstatuses.com/204

This is treated as a generic error, so when we are trying to handle it on our React Native app, we can't differentiate this from other kinds of error (i.e.: 404). When an image has no content we would want to just not render anything as supposed to fallback into a error situation (for example retry a couple of times).

### Reproduction

Just try to render an image on React Native which server request returns 204 status code. It probably has the same behavior when decoding an image that returns 200 status with no content.

### Solution

I am not sure what the right solution would be here, as I am not familiar with the fresco library implementation, but this is my proposal.

The status of the http request could be bubbled all the way up (maybe inside EncodedImage object?) so this information can be added to the exception being thrown by DefaultImageDecoder on line 65. Then the client can access the status code to decide how to handle the error.

### Additional Information

* Fresco version: 1.0.1
* Platform version: All

Thanks! 👍

**Comment by rigdern** [comment]
@foghina do you have any thoughts on this? We're interested in getting some advice on how to solve this problem from a fresco expert.

Adam Comella
Microsoft Corp.

**Comment by foghina** [comment]
The behavior you're seeing sounds correct to me. The server isn't returning any data, so it's impossible to determine the image format, so we throw an exception. IMO a 204 status code *is* an error condition when trying to load an image, so showing the failure / retry images is the correct behavior.

Bubbling up the http response code sounds potentially useful, but I'm not sure about putting it in `EncodedImage`. That type is often used to represent local images as well, e.g. from camera roll or resources.

However, I'm not sure you need the response code to differentiate between 204 and e.g. 404. In the case of 204, the network producer does emit a response, but then the decode fails. When the response is 404, the network producer emits a failure. Perhaps we can leverage that?

Also, your Fresco version is super old :)

CC @oprisnik who knows more about our API architecture.

**Comment by MiguelCa-MSFT** [comment]
Thanks @foghina for replying!

I agree that is the right behavior too. I guess what you are suggesting is to expand the general decode error in the case the decode failed because the content was empty. We can throw a more specific error, something like "Decoding failed due to empty content" or something like that. I think that would work for us. In order to make this useful on caller's end, we would need to throw  a more specific exception, we could create a exception class: ImageEmptyException (or something similar).

Please, @foghina and @oprisnik could you confirm you are ok with this approach?

Thanks again!

**Comment by MiguelCa-MSFT** [comment]
@foghina @oprisnik could you please confirm if this approach is reasonable to you? Thanks!

**Comment by foghina** [comment]
Adding an `ImageEmptyException` sounds too specific. I'd rather add something more generic like an `HttpException` that would also hold the response code (if available). Do you think that would work?

**Comment by oprisnik** [comment]
Yeah, I would also be inclined to keep this as generic as possible. Would it be an option to catch these in the network layer or somewhere else?

Also, is this something that quite a few people could run into or something that's specific to your setup? To me, it sounds like 204 should not be returned for images in general?

**Comment by MiguelCa-MSFT** [comment]
I can add the exception at the network level, my only concern is that a 204 response is not a network error, it is a success response. It is the decoder layer the one that really fails when there is no content to decode. However, you guys have way more experience with this code base and I will follow your guide lines. Thanks for the feedback!

About how often this error would happen, I am not sure but I can see how this is not a common scenario, specially because there hasn't been a request for this fix before this one. We certainly have a specific need on our end, that is why we are proposing this fix.

**Comment by oprisnik** [comment]
Without any Fresco changes, it is also possible to supply a custom `ImageDecoder` to Fresco (can be either a global or per-image override) that should be able to handle empty responses.

I'm not really sure where the best place for these checks would be. I'd have to dig into the current code a bit.

**Comment by oprisnik** [comment]
We've discussed this a bit with the team. Do you know what the default behavior in a browser / iOS is if you get a 204 image to have a consistent default behavior?

To solve your problem, can you add a custom image format for the 204 image (with a corresponding header checker) and have a custom decoder that creates an empty 1x1px bitmap for these images.
The custom header checker can expect a header length of 1 and check if the length is 0 (i.e. the image is empty), return the custom image format. It might just work if you return an existing image format instead (like JPEG or PNG), not sure what these decoders would do though, so you'd have to check. 
If you want to test this quickly, you can build our showcase sample app and add a custom decoder like this [example for keyframes](https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/keyframes/KeyframesDecoderExample.java). You can register them globally when Fresco is initialized. Not sure if that's exposed in React Native though.

**Comment by MiguelCa-MSFT** [comment]
Thanks for this information! We will consider this approach for sure. It seems we can use custom decoders to handle this situation and is up to us what to surface, either an error or, as you suggested, an empty image. Thank you very much for your help!

**Comment by oprisnik** [comment]
Awesome. Please let us know if this approach worked or if we still need to change Fresco.
