### ISSUE TITLE
dlopen failed: library "/system/lib/libimagepipeline.so" 

### ISSUE THREAD

**Issue by hcadoid** [facebook/fresco#1913]
From the user's statistical log，The test did not happen，Uncertainty，only in 7.1 devices。
The user's device is xiaomi mix2（7.1）,but I did not appear in google pixel。
I read the previous issuse, they are through the SoLoader or ReLinker library to fix?

```
"fresco" : "com.facebook.fresco:fresco:1.3.0",
 "fresco_gif" : "com.facebook.fresco:animated-gif:1.3.0",
 ndk {
            abiFilters "armeabi"
   }

```

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libimagepipeline.so" 
needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
	java.lang.Runtime.loadLibrary0(Runtime.java:989)
	java.lang.System.loadLibrary(System.java:1530)
	com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
	com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
	com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
	com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
	com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
	com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
	com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:100)
	com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:28)
	com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:341)
	com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:38)
	com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:185)
	com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:168)
	bolts.g$5.run(Task.java:357)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	java.lang.Thread.run(Thread.java:761)
```

```

java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.imagepipeline.memory.NativeMemoryChunk; see exception in other thread
	com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
	com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
	com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:100)
	com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:28)
	com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:341)
	com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:38)
	com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:185)
	com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:168)
	bolts.g$5.run(Task.java:357)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	java.lang.Thread.run(Thread.java:761)
	
```

**Comment by efrohnhoefer** [comment]
There are number of issues loading native libraries on older version of Android. There are a number of similar issues already reported. Give either [SoLoader](https://github.com/facebook/SoLoader) or [ReLinker](https://github.com/KeepSafe/ReLinker) a try.

**Comment by lambdapioneer** [comment]
@hcadoid, I'll close this task since the provided solution most likely fixed the issue and I haven't heard otherwise. Thanks @efrohnhoefer!

If your issue persists, just comment and I'll re-open.

**Comment by huanting** [comment]
The above error reproduces on my app.  It is uploaded by umeng sdk on user device. Below is log and device.

Fresco recommends to use SoLoader to solve the problem. I read the codes of SoLoader and can't find the fixed codes. I write a demo to reproduce this error.  The result is that SoLoader can't fix this bug. 
The demo codes: https://github.com/huanting/TestDlopenedError

**Error Log:** 
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libimagepipeline.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
Invalid SoFile=libBugly.so
should not run here. User deletes the so manually.needUnpack=false
installPath isSuc= true 
all native library exist!

	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
	at java.lang.System.loadLibrary(System.java:1562)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java)
	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java)
	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java)
	at bolts.Task$4.run(Task.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

**Device**: MI 5X, android 7.1.2

**Comment by lambdapioneer** [comment]
@huanting, the log provided suggests that the `DefaultHandler` is used and not the `SoLoader` library.

The newest 1.8.0 release of Fresco comes with SoLoader as default. Can you try if this helps?

**Comment by huanting** [comment]
I will update the version of fresco to 1.8.0 in the new app version.   If the problem is reported, I  will update in the issue. Thank you.

**Comment by oy2898601** [comment]
If your project only contains armeabi libs. You can find the freso path in your gradle caches path. (/Users/**/.gradle/caches/**/**/**.**.fresco)

Then go to imagepipeline dir. Move imagepipeline-*.*.*.aar to imagepipeline-*.*.*.zip. Unzip it and copy the imagepipeline.so in  armeabi-v7a to your project's libs/armeabi.

This works for me!
