### ISSUE TITLE
Cannot import project and run its sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [facebook/fresco#1915]
I get this error:
![image](https://user-images.githubusercontent.com/5357526/30971610-0d0046ee-a471-11e7-8e96-54e577e52c13.png)

**Comment by foghina** [comment]
Any chance you have a stable version of Android Studio as well? If yes does it repro there as well?

Also, what version of gradle are you using?

**Comment by foghina** [comment]
I can't repro in either AS 2.2.3 or 3.0 Beta 6. The problem might be that you have the "Unnamed" build config selected (what is that?), you should try selecting something like "showcase".

Let us know if this still doesn't work for you, and if so, give us more info on your env: do you use the gradle wrapper or local gradle? What target are you trying to run / build?

**Comment by AndroidDeveloperLB** [comment]
I don't have stable version of Android-Studio, but it's Beta 6 already, so should work fine.
All I did is Git-clone the repo, and open it on the IDE.
All gradle settings weren't changed from their default ones. 

Trying to do it again, I chose not to update gradle version, and now it got a different issue:

![image](https://user-images.githubusercontent.com/5357526/31053027-5761ea1c-a69c-11e7-8f88-ec7b5b0f4f04.png)

Then I chose to sync project again, and now it works fine...

However, I tried the "comparison" sample, and out of all items there, when I tried "fresco" (with "network", as I did for all), it took more and more memory, till the app crashed silently. Is it intended to be this way?
Almost all others just got the memory have a random number, but none really crashed. 

I also noticed that sometimes when I try to build a sample I get a warning/error :
![image](https://user-images.githubusercontent.com/5357526/31053493-2a91d4f6-a6a7-11e7-9a19-8eb07fdfaaaf.png)
Sometimes it warns something about architecture.
However, when I choose to run, it runs fine...

**Comment by AndroidDeveloperLB** [comment]
On another time I tried the "comparison" sample, Fresco doesn't take more and more memory, but now its UI is very very slow, till it reaches ANR...

All tested on Nexus 5x with Android O, BTW.

**Comment by oprisnik** [comment]
Looks like the original issue (importing project) has been resolved. If you think the ANR is a Fresco issue, we need more details. Feel free to open a separate GitHub issue.

**Comment by AndroidDeveloperLB** [comment]
@oprisnik It's not just ANR issue. It's also memory leak issue. Both in the "comparison" sample.
Both could be just sample issues, but I don't know.
Please just try the sample.

**Comment by AndroidDeveloperLB** [comment]
I've now tried to import the repo again, this time with Android Studio 3.1 canary 2, and again  it has an issue:
![image](https://user-images.githubusercontent.com/5357526/32573232-f3f11978-c4d5-11e7-83a0-cfef341cf919.png)
