### ISSUE TITLE
HttpUrlConnectionNetworkFetcher fetchSync() method,callback.onResponse(is, -1);

### ISSUE THREAD

**Issue by wolongalick** [facebook/fresco#1922]
Why is -1??????

**Comment by wolongalick** [comment]
NetworkFetchProducer calculateProgress() methode,total params Always be 1

**Comment by lambdapioneer** [comment]
Hi @wolongalick, 

see https://github.com/facebook/fresco/blob/f2268961dfd7d8be9ea3b3cf1a978c4d7d0aac9a/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/NetworkFetcher.java#L35-L43

It indicates that the implementation does not provide the total data length from the network stream.
