### ISSUE TITLE
placeholder image is weird.

### ISSUE THREAD

**Issue by jcsla** [facebook/fresco#1923]
hello

At first, my app screen shot is here.
![img_3076](https://user-images.githubusercontent.com/5294906/31315497-d5b4ae14-ac54-11e7-9772-3037573ba870.JPG)
my xml code is below.
<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/picture_message"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            fresco:placeholderImage="@drawable/ico_photo_placeholder"
            fresco:placeholderImageScaleType="centerInside"
            fresco:roundedCornerRadius="5dp" />

there is no line in my placeholder drawable image.
![ico_photo_placeholder](https://user-images.githubusercontent.com/5294906/31315511-09972a7c-ac55-11e7-9fd4-d91eefe9db0f.png)

how can I delete line around my placeholderImage? thank you

**Comment by kirwan** [comment]
That looks like a progress bar. I don't see anything in your XML that sets that. Do you have something in Java that does?

**Comment by lambdapioneer** [comment]
This looks like a known issue with rounded corners with overlay mode BITMAP_ONLY.

Try setting `fresco:roundWithOverlayColor="@color/you_background_color"` instead (it's also a bit more performant)

**Comment by jcsla** [comment]
@lambdapioneer thank you for your reply. I resolved this issue!!!!!!!! 👍 👍 👍 👍 👍
