### ISSUE TITLE
How to run the fresco demo in Android Studio

### ISSUE THREAD

**Issue by gongzelong0718** [facebook/fresco#1927]
### Description

How to run fresco demo

I imported the whole project in Android Studio

Information:Gradle tasks [:samples:demo:assembleInternalDebug]
Error:Execution failed for task ':imagepipeline:downloadLibjpeg'.
> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Information:BUILD FAILED
Information:Total time: 8.085 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

### Additional Information

* Fresco version: [The latest master branch]
* Platform version: [Xiao Mi 5 Android 6.0.1]

The attach file shows my sdk java ndk location, hope that it will help.

<img width="1437" alt="screen shot 2017-10-10 at 1 31 46 pm" src="https://user-images.githubusercontent.com/6286811/31370712-838f13c8-ad52-11e7-9a79-064eec9037a1.png">

**Comment by lambdapioneer** [comment]
Hi @gongzelong0718, this looks like a problem with the configuration of your system or network.

Can you try the following command from your command line and check if it does work?

```
wget https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.0.tar.gz
```

**Comment by oprisnik** [comment]
I assume that the problem has been resolved since this looks like a network issue.

**Comment by Saturdaycong** [comment]
have you solved this problem?
