### ISSUE TITLE
OOM on android5.1.1

### ISSUE THREAD

**Issue by SandyWangWei** [facebook/fresco#1934]
### OOM like this

java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 2097152 free bytes and 6MB until OOM
dalvik.system.VMRuntime.newNonMovableArray(Native Method)
android.graphics.Bitmap.nativeCreate(Native Method)
android.graphics.Bitmap.createBitmap(Bitmap.java:812)
android.graphics.Bitmap.createBitmap(Bitmap.java:789)
android.graphics.Bitmap.createBitmap(Bitmap.java:756)
com.facebook.imagepipeline.memory.BitmapPool.android.graphics.Bitmap alloc(int)(BitmapPool.java:55)
com.facebook.imagepipeline.memory.BitmapPool.java.lang.Object alloc(int)(BitmapPool.java:30)
com.facebook.imagepipeline.memory.BasePool.java.lang.Object get(int)(BasePool.java:259)
com.facebook.imagepipeline.platform.ArtDecoder.com.facebook.common.references.CloseableReference decodeStaticImageFromStream(java.io.InputStream,android.graphics.BitmapFactory$Options)(ArtDecoder.java:137)
com.facebook.imagepipeline.platform.ArtDecoder.com.facebook.common.references.CloseableReference decodeJPEGFromEncodedImage(com.facebook.imagepipeline.image.EncodedImage,android.graphics.Bitmap$Config,int)(ArtDecoder.java:120)
com.facebook.imagepipeline.decoder.DefaultImageDecoder.com.facebook.imagepipeline.image.CloseableStaticBitmap decodeJpeg(com.facebook.imagepipeline.image.EncodedImage,int,com.facebook.imagepipeline.image.QualityInfo,com.facebook.imagepipeline.common.ImageDecodeOptions)(DefaultImageDecoder.java:183)
com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.com.facebook.imagepipeline.image.CloseableImage decode(com.facebook.imagepipeline.image.EncodedImage,int,com.facebook.imagepipeline.image.QualityInfo,com.facebook.imagepipeline.common.ImageDecodeOptions)(DefaultImageDecoder.java:63)
com.facebook.imagepipeline.decoder.DefaultImageDecoder.com.facebook.imagepipeline.image.CloseableImage decode(com.facebook.imagepipeline.image.EncodedImage,int,com.facebook.imagepipeline.image.QualityInfo,com.facebook.imagepipeline.common.ImageDecodeOptions)(DefaultImageDecoder.java:123)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.void doDecode(com.facebook.imagepipeline.image.EncodedImage,boolean)(DecodeProducer.java:239)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.void run(com.facebook.imagepipeline.image.EncodedImage,boolean)(DecodeProducer.java:144)
com.facebook.imagepipeline.producers.JobScheduler.void doJob()(JobScheduler.java:207)
com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
com.facebook.imagepipeline.producers.JobScheduler$1.void run()(JobScheduler.java:78)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
com.facebook.imagepipeline.core.PriorityThreadFactory$1.void run()(PriorityThreadFactory.java:43)
java.lang.Thread.run(Thread.java:818)

we can not find our own source code which lead to the OOM , need some help.

**Comment by SandyWangWei** [comment]
The reason of OOM is that we need load big pic like 192*1080，sometimes load many large pics.Now we decide to clear memory cache when finish loading a big pic.Hope it works。

**Comment by oprisnik** [comment]
Sounds good. Let us know if you're still experiencing issues.
