### ISSUE TITLE
image not display

### ISSUE THREAD

**Issue by adityabudi** [facebook/fresco#194]
DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setLowResImageRequest(ImageRequest.fromUri(imageURL))
                    .setImageRequest(ImageRequest.fromUri(imageURL))
                    .setOldController(holder.imgProduct1.getController())
                    .build();
            holder.imgProduct1.setController(controller);

but image not display image

**Comment by tyronen** [comment]
Are you setting the low-res and image request to the same URL? Can you tell us one such URL that is failing?
What does holder.imageProduct1 look like?

**Comment by plamenko** [comment]
reaping
