### ISSUE TITLE
Feature Request: Control memory cache per request

### ISSUE THREAD

**Issue by krottv** [facebook/fresco#1942]
### Description

I would like to control memory cache per request. Sometimes I need it and sometimes I don't.
By analogy how it is done with disk cache:

`ImageRequest request = ImageRequestBuilder
                                .newBuilderWithSource(path)
                                .disableDiskCache()
                                .disableMemoryCache() //this is how it should be done.
                                .build();`

**Comment by erikandre** [comment]
Hi @krottv 

That sounds reasonable. You are more than welcome to implement it in a similar way to how it is handled for the disk cache, and then submit a pull request.
