### ISSUE TITLE
How to ResizeOptions for match_parent, match_parent dimensions?

### ISSUE THREAD

**Issue by ursusursus** [facebook/fresco#1943]
Hi, I have a fullscreen imageview, with both width and heigth set to match_parent, i.e. frescos requirments of known dimensions are met, and it works. 

However I do also need to resize the image with ResizeOptions as it might be bigger than needed.

Its there I trick how to get the actual dimensions without setting up a globalLayoutListener and waiting for it(if both dimensions are match_parent)?
If Fresco can figure it out given the requirments of known dimensions, there must be a way to pass something to ResizeOptions, right?

```
<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/coverImageView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="fitCenter"
            app:actualImageScaleType="fitCenter"/>
```

**Comment by erikandre** [comment]
Hi @ursusursus 

I'm afraid using a layout listener is the way to go for that case. Either that, or if possible making sure that you already know the dimensions of the image beforehand.
