### ISSUE TITLE
Cannot Run Showcase app In android Studio

### ISSUE THREAD

**Issue by moehan** [facebook/fresco#1945]
I have downloaded ndk as instructed. 
![screen shot 2017-10-20 at 3 52 32 pm](https://user-images.githubusercontent.com/13792433/31810536-be994880-b5ae-11e7-9080-a005f02eccc7.png)

I failed to Load Sample App and got this error ... please advice. Thanks !

/Users/toccostudios_macmini02/Library/Android/sdk/ndk-bundle/build/core/build-binary.mk
Warning:(580) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: overriding commands for target `.'
Warning:(528) warning: ignoring old commands for target `.'
Warning:(635) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: overriding commands for target `Test'
Warning:(528) warning: ignoring old commands for target `Test'
Warning:(778) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: overriding commands for target `Test'
Warning:(635) warning: ignoring old commands for target `Test'
Warning:(797) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: overriding commands for target `Test'
Warning:(778) warning: ignoring old commands for target `Test'
Error:(796) target `Test' given more than once in the same rule.
Warning:(803) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: overriding commands for target `.'
Warning:(580) warning: ignoring old commands for target `.'
Error:(803) target `.' given more than once in the same rule.
Error:(803) target `.' given more than once in the same rule.
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: overriding commands for target `.'
Warning:(803) warning: ignoring old commands for target `.'
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: overriding commands for target `Test'
Warning:(797) warning: ignoring old commands for target `Test'
Warning:(580) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: overriding commands for target `.'
Warning:(528) warning: ignoring old commands for target `.'
Warning:(635) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: overriding commands for target `Test'
Warning:(528) warning: ignoring old commands for target `Test'
Warning:(778) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: overriding commands for target `Test'
Warning:(635) warning: ignoring old commands for target `Test'
Warning:(797) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: overriding commands for target `Test'
Warning:(778) warning: ignoring old commands for target `Test'
Error:(796) target `Test' given more than once in the same rule.
Warning:(797) warning: overriding commands for target `libgnustl_shared.so'
Warning:(797) warning: ignoring old commands for target `libgnustl_shared.so'
Warning:(803) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: overriding commands for target `.'
Warning:(580) warning: ignoring old commands for target `.'
Error:(803) target `.' given more than once in the same rule.
Error:(803) target `.' given more than once in the same rule.
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: overriding commands for target `.'
Warning:(803) warning: ignoring old commands for target `.'
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: overriding commands for target `Test'
Warning:(797) warning: ignoring old commands for target `Test'
Warning:(580) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: overriding commands for target `.'
Warning:(528) warning: ignoring old commands for target `.'
Warning:(635) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: overriding commands for target `Test'
Warning:(528) warning: ignoring old commands for target `Test'
Warning:(778) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: overriding commands for target `Test'
Warning:(635) warning: ignoring old commands for target `Test'
Warning:(797) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: overriding commands for target `Test'
Warning:(778) warning: ignoring old commands for target `Test'
Error:(796) target `Test' given more than once in the same rule.
Warning:(797) warning: overriding commands for target `libgnustl_shared.so'
Warning:(797) warning: ignoring old commands for target `libgnustl_shared.so'
Warning:(803) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: overriding commands for target `.'
Warning:(580) warning: ignoring old commands for target `.'
Error:(803) target `.' given more than once in the same rule.
Error:(803) target `.' given more than once in the same rule.
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: overriding commands for target `.'
Warning:(803) warning: ignoring old commands for target `.'
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: overriding commands for target `Test'
Warning:(797) warning: ignoring old commands for target `Test'
Warning:(580) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: overriding commands for target `.'
Warning:(528) warning: ignoring old commands for target `.'
Warning:(635) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: overriding commands for target `Test'
Warning:(528) warning: ignoring old commands for target `Test'
Warning:(778) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: overriding commands for target `Test'
Warning:(635) warning: ignoring old commands for target `Test'
Warning:(797) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: overriding commands for target `Test'
Warning:(778) warning: ignoring old commands for target `Test'
Error:(796) target `Test' given more than once in the same rule.
Warning:(797) warning: overriding commands for target `libgnustl_shared.so'
Warning:(797) warning: ignoring old commands for target `libgnustl_shared.so'
Warning:(803) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: overriding commands for target `.'
Warning:(580) warning: ignoring old commands for target `.'
Error:(803) target `.' given more than once in the same rule.
Error:(803) target `.' given more than once in the same rule.
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: overriding commands for target `.'
Warning:(803) warning: ignoring old commands for target `.'
Warning:(528) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: overriding commands for target `Test'
Warning:(797) warning: ignoring old commands for target `Test'
Warning:(580) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: overriding commands for target `.'
Warning:(528) warning: ignoring old commands for target `.'
Warning:(635) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(528) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: overriding commands for target `Test'
Warning:(528) warning: ignoring old commands for target `Test'
Warning:(778) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(635) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: overriding commands for target `Test'
Warning:(635) warning: ignoring old commands for target `Test'
Warning:(797) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(778) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents/Android'
Warning:(797) warning: overriding commands for target `Test'
Warning:(778) warning: ignoring old commands for target `Test'
Error:(796) target `Test' given more than once in the same rule.
Warning:(797) warning: overriding commands for target `libgnustl_shared.so'
Warning:(797) warning: ignoring old commands for target `libgnustl_shared.so'
Warning:(803) warning: overriding commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(580) warning: ignoring old commands for target `/Users/toccostudios_macmini02/Documents'
Warning:(803) warning: overriding commands for target `.'
Warning:(580) warning: ignoring old commands for target `.'
Error:(803) target `.' given more than once in the same rule.
Error:(803) target `.' given more than once in the same rule.
Error:no such file or directory: 'Test'
Error:error: no such file or directory: 'Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/armeabi/objs/bitmaps/Bitmaps.o.d'
Error:error: no such file or directory: 'Test'clang
Error:error: no such file or directory: 'Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/armeabi/objs/bitmaps/Bitmaps.o'
/Users/toccostudios_macmini02/Documents/CIT_VISA/TravelSmart vNext (Android)/TravelSmart
Error:error: no such file or directory: 'Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/armeabi-v7a/objs/bitmaps/Bitmaps.o.d'
Error:error: no such file or directory: 'Test'clang: error: no such file or directory: 'Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/arm64-v8a/objs/bitmaps/Bitmaps.o.d'
Error:error: clang: error: no such file or directory: 'Test'
Error:error: no such file or directory: 'Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/arm64-v8a/objs/bitmaps/Bitmaps.o'
Error:error: no such file or directory: 'Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/x86/objs/bitmaps/Bitmaps.o.d'
Error:error: no such file or directory: 'Test'
Error:error: no such file or directory: 'Projects/fresco/imagepipeline/build/tmp/ndk_build_bitmaps/local/x86/objs/bitmaps/Bitmaps.o'
Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> Process 'command '/Users/toccostudios_macmini02/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

**Comment by erikandre** [comment]
Hi @moehan 

Which NDK version are you using?

**Comment by moehan** [comment]
android-ndk-r15c-darwin-x86_64
android-ndk-r13b-darwin-x86_64

I've tried to use those 2 versions. Both not working :(

**Comment by zmroczek** [comment]
@moehan have you tried setting the ndk in the `local.properties` file? See the instructions here: https://github.com/facebook/fresco/tree/master/samples.

**Comment by oprisnik** [comment]
I'm closing this issue since it should work when the NDK is set in `local.properties`. If this is still an issue, let us know!
