### ISSUE TITLE
PhotoView  

### ISSUE THREAD

**Issue by JerryYangLu** [facebook/fresco#195]
I used the PhotoView in my project, but now I want PhotoView to work with Fresco.
How can I solve this?

**Comment by tyronen** [comment]
See #178

**Comment by JerryYangLu** [comment]
Thanks.........

**Comment by ffelini** [comment]
If anyone still interested in PhotoView version that works with Fresco here is my fork https://github.com/namshi/PhotoView/tree/fresco_refactoring

**Comment by JerryYangLu** [comment]
Cool!
