### ISSUE TITLE
gif image download too slow

### ISSUE THREAD

**Issue by TickerBomb** [facebook/fresco#1951]
### Description
When I use HttpUrlConnectionNetworkFetcher to download gif image, it's download speed is too slow. but not OkHttpNetworkFetcher. Animated GIF file size is about 16MB.

### Solution
The problem is that HttpUrlConnectionNetworkFetcher always returns -1 as contentLength.

in HttpUrlConnectionNetworkFetcher
```
if (connection != null) {
        is = connection.getInputStream();
        callback.onResponse(is, -1);
}
```

in OkHttpNetworkFetcher
```
long contentLength = body.contentLength();
if (contentLength < 0) {
        contentLength = 0;
}
callback.onResponse(body.byteStream(), (int) contentLength);
```

### Additional Information

* Fresco version: [1.5.0]

**Comment by wangrunxiang** [comment]
The gif picture would have been big

**Comment by erikandre** [comment]
Hi @TickerBomb 

Thanks for submitting the bug report.
Could you please elaborate a bit more on why the content length affects the download speed in this case?

**Comment by erikandre** [comment]
In general we recommend that you use OkHttpNetworkFetcher.

Please feel free to submit a push request if you want to help us improve HttpUrlConnectionNetworkFetcher. Thanks!

**Comment by TickerBomb** [comment]
Hi @erikandre 

Because NativeMemoryChunk size is too smaller than contentLength, realloc occurs too frequently. 

NativePooledByteBufferOutputStream.java
```
void realloc(int newLength) {
    ensureValid();
    /* Can the buffer handle @i more bytes, if not expand it */
    if (newLength <= mBufRef.get().getSize()) {
      return;
    }

    long reallocTime = SystemClock.elapsedRealtime();
    NativeMemoryChunk newbuf = mPool.get(newLength);
    mBufRef.get().copy(0, newbuf, 0, mCount);
    mBufRef.close();
    long reallocTimeCompleted = SystemClock.elapsedRealtime();
    reallocTotalTime += (reallocTimeCompleted - reallocTime);
    mBufRef = CloseableReference.of(newbuf, mPool);
  }
```

**Comment by dmitry-voronkevich** [comment]
@TickerBomb, We use OkHttpNetworkFetcher and recommend it to others. If you need another fetcher, please send us pull request with fix for length issue.

**Comment by erikandre** [comment]
Closing as there is not much we can do about this at the moment.
In the future we might implement streaming for gifs but that is not prioritized and quite complex.
