### ISSUE TITLE
How can I get GIF total Frame count and duration?

### ISSUE THREAD

**Issue by ajaystha005** [facebook/fresco#1953]
I need to get the total Frame Count and the total duration of the gif

* Fresco version: 1.5.0

**Comment by oprisnik** [comment]
You can use a controller listener to get the `Animatable` when the final image is loaded, see http://frescolib.org/docs/listening-to-events.html

The animatable is an instance of `AnimatedDrawable2` and you can do:
`animatedDrawable2.getFrameCount()`, `animatedDrawable2.getLoopCount() * animatedDrawable2.getLoopDuration()`. Keep in mind that the loop count can be `AnimationInformation.LOOP_COUNT_INFINITE` for infinite animations.
