### ISSUE TITLE
AbstractDraweeControllerBuilder#setDataSourceSupplier should return BUILDER

### ISSUE THREAD

**Issue by efrohnhoefer** [facebook/fresco#1958]
### Description

`AbstractDraweeControllerBuilder#setDataSourceSupplier` should return `BUILDER`. 

```
Fresco.newDraweeControllerBuilder()
            .setDataSourceSupplier(supplier)
            .build()
```

### Solution

Change `AbstractDraweeControllerBuilder#setDataSourceSupplier` to return `BUILDER`

### Additional Information
* Fresco version: 1.5

**Comment by lambdapioneer** [comment]
Thanks for the suggestion @efrohnhoefer, we should fix that. Please feel invited to create a pull-request if you want to contribute to Fresco :)

**Comment by efrohnhoefer** [comment]
I will submit a PR shortly...
