### ISSUE TITLE
Gif will not load in Google Map infowindow

### ISSUE THREAD

**Issue by REWKyleB** [facebook/fresco#196]
Images of type gif will not load in Google Map info windows. I've tested other image types and they are working fine, but there seems to be an issue with gifs.

**Comment by REWKyleB** [comment]
On a side note, any tips on loading an image with Fresco into a custom map info window? I'm currently using the OnFinalImageSet event and then marker showInfoWindow() to reload the info window which will make the image display.

Additional details on this method here: http://stackoverflow.com/questions/18938187/add-an-image-from-url-into-custom-infowindow-google-maps-v2

This seems to be working, but I'm getting the following messages in my logcat

437c2ed8: Draw requested for a non-attached controller 436d9750. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, activityStarted=true, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER, ON_CLEAR_OLD_CONTROLLER, ON_SET_CONTROLLER]}
Finalized without closing: 445d67b8 44711ce0 (type = CloseableStaticBitmap)

**Comment by REWKyleB** [comment]
I've simplified the code, but this is basically what I'm working with.

```Java
// Custom Info Windows
map.setInfoWindowAdapter(new GoogleMap.InfoWindowAdapter() {

	@Override
	public View getInfoContents(final Marker marker) {

		// Create view
		// *** This could just an inflated view
		vi = viewBuilder.createViewWithConfig(config);
	
		// Get View
		SimpleDraweeView childImageView = vi.findViewById(r.id.test);
	
		// Build control listener for marker images
		ControllerListener controllerListener = new BaseControllerListener<ImageInfo>() {
			@Override
			public void onFinalImageSet(String id, @Nullable ImageInfo imageInfo,   @Nullable Animatable anim)     {
				if (marker != null && marker.isInfoWindowShown()) {
					marker.hideInfoWindow();
					marker.showInfoWindow();
				}
			}
		};
		
		DraweeController controller = Fresco.newDraweeControllerBuilder()
			.setControllerListener(controllerListener)
			.setUri(Uri.parse(http://www.peacethroughyoga.com/wp-content/uploads/2014/05/placeholder-image-850x500.gif))
			.build();

		// Set controller
		childImageView.setController(controller);
	}
});
```
As mentioned in the SO post above, the MapFragment renders the view into a Canvas and then draws that. This example will re-render the canvas once the image is set with Fresco.

**Comment by tyronen** [comment]
There was an issue with non-animated GIFs that was fixed in 0.5.1.

**Comment by githubdoramon** [comment]
I'm doing EXACTLY the same code above, but the controllerListener is never called.... What can be wrong?

**Comment by githubdoramon** [comment]
@REWKyleB I'm using my map inside a fragment... That is the only thing I can think could be different for what you are doing

**Comment by markfili** [comment]
any luck in figuring out how to implement this?

i've tried versions 0.11 and 0.12 but without success

**Comment by lambdapioneer** [comment]
@markfili, thanks for the info 👍
