### ISSUE TITLE
Thumbnail of video from Android document provider does not show 

### ISSUE THREAD

**Issue by w0yne** [facebook/fresco#1969]
### Description

Video thumbnail cannot be rendered via `SimpleDraweeView#setImageURI` if the content uri is like: 
`content://com.android.providers.media.documents/document/video%3A160`

### Reproduction

My app allows user to choose a file from Android document provider.  The Intent is constructed by this way:
```.java
    public static Intent getChooseMediaIntent(String type) {
        Intent intent = new Intent(Intent.ACTION_GET_CONTENT, MediaStore.Video.Media.EXTERNAL_CONTENT_URI);
        intent.setType(type); // type is "video/*" here
        return intent;
    }
```
The returned uri is `content://com.android.providers.media.documents/document/video%3A160`.
However, when I use `SimpleDraweeView#setImageURI` to render the video thumbnail, it should blank.

### Solution
The root cause as I found out is within `LocalVideoThumbnailProducer#getLocalFilePath`. For the uri `content://com.android.providers.media.documents/document/video%3A160` this method will return null.
I've sent a PR #1970 

### Additional Information

* Fresco version: 1.5.0
* Platform version: Android 7.1.1 on OnePlus 5 / Android 7.1.2 on Xiaomi 5C.

![device-2017-11-16-171253](https://user-images.githubusercontent.com/5569148/32885768-748310e0-caf9-11e7-9502-58ddb9164845.png)

**Comment by dmitry-voronkevich** [comment]
Thanks for reporting and PR. Will close this one once PR is imported.
