### ISSUE TITLE
issue loading image when imagepath contains special chars like %

### ISSUE THREAD

**Issue by Ujjwal-soft** [facebook/fresco#1972]
### Description 
 imagepath for my image is :
/storage/emulated/0/Pictures/OGQ/Richard Walker_Stairway To Heaven%3F_YkFgR2RZ.jpg

tried loading image with above Url but it failed because it contains % as special char in path, otherwise works fine.

### Additional Information

* Fresco version: [1.5.0]
* Platform version: [android all versions on all devices]

**Comment by dmitry-voronkevich** [comment]
Please look at this response on the similar issue: https://github.com/facebook/fresco/issues/1088#issuecomment-203730626

**Comment by Ujjwal-soft** [comment]
@dmitry-voronkevich looked into that before but none of the suggestions seems to be working...there is no method like parseFromFile() in Uri.parseFromFile(new File(path).. if you have some working solution, please suggest, thanks a lot!!

**Comment by Ujjwal-soft** [comment]
Found a solutions to this:

convert imagepath to Uri as :
    Uri picUri= Uri.fromFile(new File("/storage/emulated/0/Pictures/OGQ/Richard Walker_Stairway To Heaven%3F_YkFgR2RZ.jpg"
    
    ImageRequest request=ImageRequestBuilder.newBuilderWithSource(picUri).setResizeOptions(new ResizeOptions(width, height)).build();

This will load image contains special chars or symbols.
