### ISSUE TITLE
Image is not getting loaded in release apk by using Fresco

### ISSUE THREAD

**Issue by ershanky** [facebook/fresco#1973]
While building release APK getting following warning
 **"Warning:com.facebook.imagepipeline.memory.BitmapCounterProvider: can't find referenced class com.facebook.infer.annotation.ThreadSafe"**
 I supressed it by using progard-rules.
**-dontwarn com.facebook.infer.annotation.ThreadSafe**
Does this issue concerned with image loading in release apk?

**Comment by dmitry-voronkevich** [comment]
Thanks for letting us know. Currently we are suggesting to follow this guide: http://frescolib.org/docs/shipping.html#proguard, which require including fresco proguard configuration. 
We are thinking to automate this in future.

**Comment by luizguilhermefr** [comment]
I am having the same problem on 1.11.0

I am not loading large images, but images just like this:

https://focus-library.s3.sa-east-1.amazonaws.com/5333f320-a79d-11e7-be81-833fcc7d70fc/Categorias/carreiras-policiais.png

The image loads on debug build but not on release builds.

**Comment by anooshkhalid** [comment]
@luizguilhermefr did you find solution for this?
