### ISSUE TITLE
Apparently bogus asset log error (E/JHEAD﹕ can't open)

### ISSUE THREAD

**Issue by burnaz** [facebook/fresco#198]
I have tried to load an image from assets and I got this error log:
<code>E/JHEAD﹕ can't open '/asset/flags/CN.png'</code>

Although ImageView was loaded successfully, that log always appears.

URI in my code:
<code>asset:///flags/CN.png</code>

Update:
I have tested setImageURI and imagePipeline and both load the asset image, but with error log.

**Comment by tyronen** [comment]
So the image does load, but shows a bogus error message? Not sure that's worth worrying about, or do you mean that the image does not load? Can you upload the image?

**Comment by burnaz** [comment]
Yes, image loads but with that error log. I could ignore it, but I think isn't normal.

https://dl.dropboxusercontent.com/u/7372650/CZ.png

![cz](https://cloud.githubusercontent.com/assets/7516541/7346877/10e829a6-ecb9-11e4-87da-c84b42e2ad10.png)

**Comment by agoodcoolman** [comment]
i get the same problem, in the assert resource,use uri("asset://3.png")but it can't work, log is can't open

**Comment by agoodcoolman** [comment]
@burnaz try it, asset:///

**Comment by burnaz** [comment]
@agoodcoolman yes, it works with <code>asset:///</code> or <code>asset:/</code>
Image loads normally, but with error log.

**Comment by burnaz** [comment]
I have the same problem with URI <code>content</code>.
I tried to load photo from contacts using fresco, image loads normally but shows error log.

Example:
<code>E/JHEAD﹕ can't open '/contacts/241'</code>

Just to remember, fresco is loading images from <code>content</code> and <code>assets</code>, but it always shows error log.

**Comment by GuyHamawi** [comment]
same issue with contacts for me too!

**Comment by tonyley** [comment]
same issue with content provider for me too

**Comment by leofirespotter** [comment]
Hm for me I get the error log but also the image does not load...

**Comment by tsebire** [comment]
I'm also getting this bug, the image shows but it logs that it can't open the file. Any news ?

**Comment by chrisnewhouse** [comment]
I also get this bogus error log when loading some PNG resources.  The images display fine.  I've tried both "res:/<resid>" and "res://<package>/<resid>", both work fine but put these bogus errors in the log.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tyronen** [comment]
Fixed in v0.8.0.
