### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by WenshyDreamPenta** [facebook/fresco#1982]
### Description

I met a bug on Sumsung and ZTE phone, the descirptions: 
java.lang.NoClassDefFoundError
[com.facebook.imagepipeline.memory.NativeMemoryChunk]([url](url))

### Reproduction

[FILL THIS OUT: How can we reproduce the bug? Provide URLs to relevant images if possible, or a sample project.]

### Solution

[OPTIONAL: Do you know what needs to be done to address this issue? Ideally, provide a pull request which fixes this issue.]

### Additional Information

* Fresco version: [1.5.0]
* Platform version: [Sumsung and ZTE phone 4.0 66%  7.0 33%]

**Comment by foghina** [comment]
See here for solution: https://github.com/facebook/fresco/issues/933#issuecomment-186266187
