### ISSUE TITLE
OOM Problem

### ISSUE THREAD

**Issue by yline** [facebook/fresco#1987]
###1：
the log:
[Fresco_OOM_Log.txt](https://github.com/facebook/fresco/files/1550458/Fresco_OOM_Log.txt)

Our App has many users every day. it has happend for many many times. 

###2：
I came back to this question，Analyze the reason；This is my code.
1）FrescoConfig
[Fresco_OOM_Config.txt](https://github.com/facebook/fresco/files/1550466/Fresco_OOM_Config.txt)

2）Init in Application

    @Override
    public void onCreate() {
        super.onCreate();

        FrescoConfig.initConfig(this, true);
    }

3）The way I use it;  
RecyclerView + GridLayoutManager(3 line)

            SimpleDraweeView frescoView = holder.get(R.id.fresco_view_recycler);
            frescoView.setImageURI(url);

4）The APK View
![fresco_demo_show](https://user-images.githubusercontent.com/8294532/33870420-a86fe6f4-df48-11e7-8c72-8b9fa40190f6.jpg)

5）Analyze the reason With Android Studio
![fresco_oom_android_studio](https://user-images.githubusercontent.com/8294532/33870256-fd2c36b2-df47-11e7-85eb-c091feb3aafd.png)
![fresco_oom_android_studio_2](https://user-images.githubusercontent.com/8294532/33870466-e1d9b5a0-df48-11e7-8f00-daf5388ecce7.png)

###3：Analyze
In the Picture, the “Graphics Memery”  is corresponding to bitmap cache.
So, it is down when I exit the "Activity"。

But，the "java Memery" do not down. when I exit the "Activity"; unless I click the "Fore GC" Button. 

I guess，the "encoded cache" is Quote to too much "java Memery", and it will cause the "java Memery" cannot be release.

Therefore, it will cause OOM because of "java Memery" is still in the app. 

### Additional Information
1）Fresco Version
compile 'com.facebook.fresco:fresco:1.5.0'
    compile 'com.facebook.fresco:animated-gif:1.5.0'
    compile 'com.facebook.fresco:animated-webp:1.5.0'
    compile 'com.facebook.fresco:webpsupport:1.5.0'
    compile 'com.facebook.fresco:imagepipeline-okhttp3:1.5.0'
    compile 'com.squareup.okhttp3:okhttp:3.9.0'

2） Platform version: [FILL THIS OUT: specific to a particular Android version? Device?]
Android 6.0.1
Sunsum Galaxy 6 and so on； I think It has nothing to do with the equipment.

**Comment by erikandre** [comment]
Hi @yline 

Could you please try using ResizeOptions to make sure that the images are resizes to a size that is suitable for the view. More details here: http://frescolib.org/docs/resizing.html

You can also enable the debug overlay to check if the images you are loaded are the right size:

https://github.com/facebook/fresco/blob/38d13c0995fd93688b228abea717870775868975/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/ShowcaseApplication.java#L76

With the overlay enabled, images that are the correct size are shown in green while images with incorrect size are shown in red.

**Comment by erikandre** [comment]
Closing due to no response from the submitter.
