### ISSUE TITLE
How to cache resized local images?

### ISSUE THREAD

**Issue by pluzmedia** [facebook/fresco#1988]
Hi,

In our app we are listing local photos but the problem is Fresco doesn't cache the local files. When i scroll a recyclerview during every data bind, library is attempt to resize the raw photos. On this behavior there is a lag in scrolling also eating too much system resources. How to handle this?. Any help would be appreciated.

**Comment by erikandre** [comment]
Hi @pluzmedia 

I believe the resized image should at least be cached in memory. Are you seeing a different behaviour? or is the problem that the resized image is not cached to disk?
