### ISSUE TITLE
Fresco 1.7.0 Error:attribute 'com.listenergao.myapplication2:placeholderImage' not found.

### ISSUE THREAD

**Issue by ListenerGao** [facebook/fresco#1991]
When I updated Fresco to 1.7.0，compilation got an error。
this is my error log:
  Information:Gradle tasks [clean, :app:assembleDebug]
/Users/listenergao/AndroidStudio_Project/MyApplication2/app/src/main/res/layout/item_layout.xml
Error:error: attribute 'com.listenergao.myapplication2:placeholderImage' not found.
Error:attribute 'com.listenergao.myapplication2:placeholderImage' not found.
Error:failed linking file resources.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 1s
Information:7 errors
Information:0 warnings
Information:See complete output in console

Use the following configuration：
app/build.gradle:
 compile 'com.facebook.fresco:fresco:1.7.0'
Application:
 Fresco.initialize(this);
xml content:
```javascript
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="60dp"
    android:background="@android:color/darker_gray">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/my_image_view"
        android:layout_width="60dp"
        android:layout_height="match_parent"
        fresco:placeholderImage="@mipmap/ic_launcher" />

    <EditText
        android:id="@+id/editText"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@null" />

</LinearLayout>
```

**Comment by savvasdalkitsis** [comment]
To add to this, it seems that 1.7.0 deployed a bad artifact. Most classes are missing from it.

SimpleDraweeView etc are not packaged in.

I am only seeing these classes:

![screen shot 2017-12-16 at 17 18 18](https://user-images.githubusercontent.com/873077/34072795-c12bbafc-e285-11e7-8679-886a41dec50a.png)

Downgrading to 1.5.0 works

**Comment by codguru** [comment]
I guess 1.7.0 dependancy is broken by update to gradle ( compile -> implements ).
So, added below dependancy. and It's working!

implementation 'com.parse.bolts:bolts-tasks:1.4.0'
implementation "com.facebook.fresco:fbcore:1.7.0"
implementation "com.facebook.fresco:animated-base:1.7.0"
implementation "com.facebook.fresco:animated-drawable:1.7.0"
implementation "com.facebook.fresco:imagepipeline-base:1.7.0"
implementation "com.facebook.fresco:imagepipeline:1.7.0"
implementation "com.facebook.fresco:drawee:1.7.0"
implementation "com.facebook.fresco:fresco:1.7.0"

**Comment by dansaka** [comment]
折腾一上午,不靠谱啊 ，准备弃用了

**Comment by siralam** [comment]
@dansaka 別啊，這是1.7.0的問題，我用1.5.0用得很開心

**Comment by efrohnhoefer** [comment]
Looks like the POM file is being incorrectly generated. Looking at (fresco-1.7.0.pom)[http://central.maven.org/maven2/com/facebook/fresco/fresco/1.7.0/fresco-1.7.0.pom] all the dependencies are missing. As @codguru points out it is likely do to changing compile to implements/api.

**Comment by efrohnhoefer** [comment]
Looks like the [android-maven-gradle-plugin](https://github.com/dcendents/android-maven-gradle-plugin) needs to be updated to v2.0.

**Comment by foghina** [comment]
Whoops, this is my bad. I've updated the release details with a link to this issue. I'll have a look tomorrow and push another release.

@efrohnhoefer do you think the plugin update is enough to fix everything? I would've thought some `implementation` -> `api` dependency changes would be necessary as well.

**Comment by efrohnhoefer** [comment]
So I bumped the version to 1.7.1 and added a local repo to my test project.
```
        maven {
            url uri('file:///Users/foo/workspace/libs')
        }
```
I was able to successfully build my simple test project. I don't think any additional changes are required but my testing was limited.

**Comment by foghina** [comment]
[v1.7.1 is now out](https://github.com/facebook/fresco/releases/tag/v1.7.1).
