### ISSUE TITLE
Is There have any detail about 1.7.0?

### ISSUE THREAD

**Issue by UFreedom** [facebook/fresco#1993]
I'm glad to see Fresco updated to 1.7.0, but when I looked at the official website or GitHub release, I didn't find the details of this update.

Fresco is a powerful library, and we want to know what the main updates are.

**Comment by dmitry-voronkevich** [comment]
Release notes published now: https://github.com/facebook/fresco/releases
Sorry for delay.

**Comment by UFreedom** [comment]
@dmitry-voronkevich 
Nothing has been found
