### ISSUE TITLE
can't load fresco's library to android

### ISSUE THREAD

**Issue by MostafaElkhouly** [facebook/fresco#1994]
I put your all code as you said 
and I can make import  Fresco.initialize(this); to my Application's class
but I can't load widgets as you side in your side 
<com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/my_image_view"
    android:layout_width="130dp"
    android:layout_height="130dp"
    fresco:placeholderImage="@drawable/my_drawable"
    />

I don't know why ... ... ... ?

**Comment by dmitry-voronkevich** [comment]
Please ask such questions on stackoverflow
