### ISSUE TITLE
Unable to find the com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by nawanirakshit** [facebook/fresco#1998]
I started with the documentation http://frescolib.org/docs/index.html

I compiled my gradle file with   **compile 'com.facebook.fresco:fresco:1.7.0'**

Added  **Fresco.initialize(this);** in the class extenfing **Application** 

But I am unable to find the **com.facebook.drawee.view.SimpleDraweeView** as it is unable to find the view package.
Please find the attached image, any help is appreciable. 
Thanks 

![ms online - c__users_ushyka_documents_more code_ms online - app - _app_src_main_java_com_msonline_android_applicationclass java - android studio 3 0 1 12_19_2017 12_42_09 pm](https://user-images.githubusercontent.com/12641430/34144999-0ffb605c-e4ba-11e7-8946-960c01c9c2d5.png)

**Comment by UFreedom** [comment]
@ericnakagawa 

Please check the release page https://github.com/facebook/fresco/releases 

This release 1.7.0  is broken. see #1991 

Please give them a little time to fix it
