### ISSUE TITLE
com.facebook.drawee.view.SimpleDraweeView  error  in com.facebook.fresco:fresco:1.7.0

### ISSUE THREAD

**Issue by Rameshsam** [facebook/fresco#1999]
We use GitHub Issues for bugs.
com.facebook.fresco:fresco:1.7.0

![image](https://user-images.githubusercontent.com/10371244/34159084-e8945f30-e4ed-11e7-852e-b933092e2fef.png)
![image](https://user-images.githubusercontent.com/10371244/34159098-f456bf7a-e4ed-11e7-970a-a4368da7236c.png)

I am trying to import com.facebook.drawee.view.SimpleDraweeView in 1.7.0 is it removed? Its added in the documentation.But if I use 1.5.0 its working what will be the fix

**Comment by jyh149129** [comment]
1.7.1

**Comment by foghina** [comment]
Fixed in v1.7.1, see #1991.

**Comment by Rameshsam** [comment]
working
