### ISSUE TITLE
Choose storage location for images

### ISSUE THREAD

**Issue by liaibai** [facebook/fresco#200]
If I want to define their own storage location, and you do not want such a complex folder, only one folder, which stood picture on it, change how to modify it, or that it can be modified

**Comment by tyronen** [comment]
You can [configure the image pipeline](http://frescolib.org/docs/configure-image-pipeline.html#_). Use [DiskCacheConfig.setBaseDirectoryPath](http://frescolib.org/javadoc/reference/com/facebook/cache/disk/DiskCacheConfig.Builder.html#setBaseDirectoryPath\(java.io.File\)) and setBaseDirectoryName to determine where the cache goes.

**Comment by liaibai** [comment]
thank you
