### ISSUE TITLE
the wasImmediate is always false.

### ISSUE THREAD

**Issue by jungletian** [facebook/fresco#2006]
https://github.com/facebook/fresco/blob/fb0aa4fd16d37d340d83a6d4455a2ec533ed0cfa/drawee/src/main/java/com/facebook/drawee/controller/AbstractDraweeController.java#L453

**Comment by zmroczek** [comment]
In the current code `wasImmediate` is not always `false`. Please take a look on tests in `AbstractDraweeControllerTest` where you can find scenarios when it is `true`.

The PR you sent is breaking the tests for scenarios where `wasImmediate` should be `false`, it seems like after your change it always returns `true` which is not expected.
