### ISSUE TITLE
Why DalvikPurgeableDecoder not support region decode?

### ISSUE THREAD

**Issue by xjy2061** [facebook/fresco#2014]
In commit https://github.com/facebook/fresco/commit/bd249fa4792ab3102339b069b776ba010dcbbfd1 just add region decode to `ArtDecoder`, why not add to  `DalvikPurgeableDecoder`?

**Comment by oprisnik** [comment]
Region decoding is still work in progress (you can't currently use it out-of-the-box with Fresco). We might add support for it later on.
