### ISSUE TITLE
Animated WebP Rendering is Broken

### ISSUE THREAD

**Issue by ericleong** [facebook/fresco#2015]
### Description

The animated WebP in the showcase sample project is rendered incorrectly.

Original WebP ([Chrome-only](https://caniuse.com/#feat=webp)) | Fresco 1.7.1 on Google Pixel 1, 8.1
--- | ---
![sample animated webp](https://www.gstatic.com/webp/animated/1.webp) | ![rubix-fresco-crop-scaled](https://user-images.githubusercontent.com/1572011/34501228-f8ca231e-efdb-11e7-8fbe-2dc2f24ed020.gif)

Ignore the color differences, the latter is a gif so that the images are shown side by side.

Note that WebP files that have full-size intermediary frames do not seem to be affected, such as [this one](https://78.media.tumblr.com/a587fdc05866312443e46153e2da8b47/tumblr_olz8ax7awm1rhfekio1_640.gifv).

### Reproduction

1. Build and launch the sample project.
2. Navigate to the "WebP" sample under the "Image Format" section in the hamburger menu.
3. Scroll down to the animated WebP, and notice the corrupted image.

### Additional Information

* Fresco version: 1.7.1
* Platform version: 8.1

**Comment by oprisnik** [comment]
Thanks for reporting @ericleong, we'll take a look

**Comment by oprisnik** [comment]
It looks like 504401041cc783c231feb7fabc870a3acea3ee30 introduced this regression. We'll fix it.

**Comment by oprisnik** [comment]
Fixed with 086fd1dfc4ee6d772ea50cba7731461120dd95c5
