### ISSUE TITLE
Using Fresco together with a Notification

### ISSUE THREAD

**Issue by bottiger** [facebook/fresco#202]
Could you please help with some documentation of how to use Fresco together a Notification (or any other RemoteView). You have documented how to [fetch a CloseableImage from the cache](http://frescolib.org/docs/using-image-pipeline.html#_), but It is not clear to me when (in the context of a notification) when to close the image again in this case.

**Comment by burnaz** [comment]
I have the same question, especially when I need to use bigPicture on my notification style.

**Comment by tyronen** [comment]
The easiest way for a Notification is to [use BaseBitmapDataSubscriber](http://frescolib.org/docs/datasources-datasubscribers.html#i-just-want-a-bitmap). Inside the `onNewResultImpl` method, you can call [NotificationCompat.Builder.setLargeIcon][http://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setLargeIcon\(android.graphics.Bitmap\)). Then you don't have to worry about closing the bitmap.

**Comment by bottiger** [comment]
@tyronen Thank you for this. I have not tested it yet, and while I'm happy I'm also a bit confused. The documentation says

> You can not assign the bitmap to any variable not in the scope of the onNewResultImpl method. The reason is that, after the subscriber has finished executing, the image pipeline will recycle the bitmap and free its memory. If you try to draw the bitmap after that, your app will crash with an IllegalStateException.

I am not aware of the internal workings of the Android UI. However, I interpreted this as assigning a bitmap to a (remote) view means that the bitmap is kept alive and used beyond the scope of "onNewResultImpl".

**Comment by tyronen** [comment]
No. Internally, Android copies the Bitmap in order to send the data over to the notification or remote view process. So you don't need to keep a reference to it after you have copied it. I can add this to the docs.

**Comment by Kaushik1502** [comment]
@tyronen but I need to pass that bitmap in `web-service` how can I get that bitmap
