### ISSUE TITLE
SimpleDraweeView shows transparent padding on Left & Right

### ISSUE THREAD

**Issue by asadullahrao** [facebook/fresco#2024]
### Description

My SimpleDraweeView showing transparent padding on Left & Right side. 

![whatsapp-image-2018-01-18-at-5 29_01](https://user-images.githubusercontent.com/429518/35098463-110db408-fc76-11e7-8db3-c2b8cfdc5ee9.png)
### Additional Information
XML:
```
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/offer_img"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerVertical="true"
        android:focusable="true" fresco:actualImageScaleType="fitXY"
        android:focusableInTouchMode="true" />

```

**Comment by zmroczek** [comment]
Hi @asadullahrao 

This might be a bug for using the XML value, it should work when set in code using `setActualImageScaleType()` method (as in the scaling example in the showcase app).

We'll take a look on that, thanks for reporting!

**Comment by asadullahrao** [comment]
It;s also not working with your suggested change. Same behaviour:-(

**Comment by asadullahrao** [comment]
My image size is 640 x 1136, and screen size is 1080x1920. It is not scaling to fit all screen.

**Comment by zmroczek** [comment]
I cannot reproduce this in the showcase app, are you sure there is no padding set in the layout or parent?

**Comment by asadullahrao** [comment]
Basically it is reproducing when setting bitmap with "setImageBitmap" method. It is not happening with "setImageUri" method.

Method with issue:
 `imageView.setImageBitmap(imageBitmap);`
Method working fine:
` imageView.setImageURI(Uri.fromFile(file));`

**Comment by oprisnik** [comment]
If you look at the documentation for DraweeView, you'll find that `setImageBitmap` is deprecated: `Use this method only when using this class as an ordinary ImageView.`.
Basically, your image view will be "downgraded" to an ImageView and that's the default ImageView behavior.

**Comment by asadullahrao** [comment]
Thanks for Response.
