### ISSUE TITLE
About SimpleDraweeSpanTextView 

### ISSUE THREAD

**Issue by zhangzhen123** [facebook/fresco#2025]
I found a problem  if set enableResizing true and set fix width and height like this: 
 draweeSpanStringBuilder.setImageSpan(
        getContext(), 
        draweeHierarchy, 
        controller, 
        imagePosition, 
        60,
        60,
        true,
        DraweeSpan.ALIGN_CENTER);

if the placeholder picture the width is larger(140*60) When word breaks The text on the line may not be full  the acture text is "Text with an # inline image using a dd dd dd dd dd DraweeSpan. Also works with % animated images!"
![i2d l3qn t3 _apsp4 r](https://user-images.githubusercontent.com/8609480/35100420-b9a47c94-fc96-11e7-8d1e-060bbceb2c0f.png)

**Comment by erikandre** [comment]
Hi @zhangzhen123! Thanks for submitting the bug report.

Using the resize option currently only works OK for some use cases (like when the resized image is smaller, but not by much).

Could you try the following workaround:

```
draweeSpanStringBuilder.setDraweeSpanChangedListener(new DraweeSpanStringBuilder.DraweeSpanChangedListener() {
      public void onDraweeSpanChanged(DraweeSpanStringBuilder builder) {
        mDraweeSpanTextView.setDraweeSpanStringBuilder(builder);
      }
    });
```

**Comment by zhangzhen123** [comment]
Thanks very match. setDraweeSpanChangedListener is useful.
