### ISSUE TITLE
Draw requested for a non-attached controller

### ISSUE THREAD

**Issue by datnt1987** [facebook/fresco#2028]
Hi, I current have the same error with #254. I have an object list that remove or add object when check/uncheck from another list. So when I scroll the recycler view, the avatar image (using SimpleDraweeView) disappear and only appear when I touch/scroll again. Here's my logcat:

> W/DraweeEventTracker: ba4b6ca: Draw requested for a non-attached controller f0f903b. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER, ON_DRAWABLE_HIDE, ON_DRAWABLE_SHOW]}

In my code , I just initialized a SimpleDraweeView image named mImgAvatar and set: mImgAvatar.setImageURI(profile.avatar);

**Comment by zmroczek** [comment]
Hi @datnt1987 

Could you please post a code snippet that you're using? What is the image that is failing to load?

**Comment by datnt1987** [comment]
Dear @zmroczek ,
I handled my list like this:
Add:
```
private void add(Singer data) {
        if (mSelectedFavoriteList == null || containFavorite(data)) {
            return null;
        }
        
        Singer clone = new Singer(data);
        mSelectedFavoriteList.add(clone);

        renderList(mSelectedFavoriteList);
    }
```
Remove:
```
private void remove(Singer data) {
for (Iterator<Singer> list = mSelectedFavoriteList.iterator(); list.hasNext(); ) {
            Singer entry = list.next();
            if (entry.equals(data)) {
                list.remove();
            }
        }
renderList(mSelectedFavoriteList);
}
```
In my adapter, I just set the avatar like that:
```
@BindView(R.id.img_avatar)
SimpleDraweeView imgAvatar;
public void bindView(FavoriteData profile) {
      imgAvatar.setImageURI(profile.avatar);
}
```
The renderList(mSelectedFavoriteList) is a function that I want to update Adapter (NotifidatasetChanged).

P/S:
In my screen, I have two list: a ListView to display list of Singers and a recyclerView above to display Favorite Singer when touch a singer in ListView below.

Issue: Click the Singer ListView to add item to Favorite RecyclerView above. When scroll, the avatar in Favorite List do not display and show log "Draw requested for a non-attached controller" and the recyclerview (Favorite List) scroll laggy as well.

**Comment by oprisnik** [comment]
I don't see anything suspicious in these code snippets. Can you compare your code to our Showcase sample app  recycler view (https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeRecyclerViewFragment.java)?
There, everything works as expected, so if you make sure your code behaves similarly, everything should work.

You can also experiment with our sample app, see https://github.com/facebook/fresco/tree/master/samples/
