### ISSUE TITLE
Download error when using self-checked https

### ISSUE THREAD

**Issue by anymol** [facebook/fresco#2034]
### Description

There is an error loading the image in case when the xml certificate is invalid, or self-signed

### Reproduction

Try load image from server with self-signed certificate

### Additional Information

Fresco version: 1.8.0
Platform version: Android N

**Comment by dmitry-voronkevich** [comment]
@anymol, please take a look at conversation here: https://github.com/facebook/fresco/issues/1592#issue-196621209
