### ISSUE TITLE
App crashes when use Fresco in ListView in main fragment of Navigation Drawer

### ISSUE THREAD

**Issue by HardikMaru** [facebook/fresco#2036]
I have navigation drawer in my app with listview in main fragment. navigation drawer open and closes with jerky movement if I use Fresco to load images with SimpleDrawview.
After few time of open/close drawer, app crashes in Lenovo A6000, A7010, MotoE. MotoG5plus, OnePlus5 and my other testing devices.
So after spending few hours after this issue I've tried my luck with glide and its working fine with Glide. 

### Reproduction

I am attaching two APKs (with Fresco and with Glide), so that you can debug the issue. Just download the APK from the link: https://drive.google.com/drive/folders/1iEGFd3v1vzHk7RT-NJxwZkAtrTI-r7zM?usp=sharing and login with below test credentials:
email: admin@goexpress.com
pass: 123
and you will see the issue in main screen it self.

Can you please suggest me a solution for this issue as soon as possible as the app is in it's last stage and I don't want to use any other lib than Fresco.

Best,
 Harry.

**Comment by dmitry-voronkevich** [comment]
Sorry to hear about your problems, @HardikMaru. Can you provide more details?
We need:
* Code sample which reproduces this issue
* Url to image which causes problems

**Comment by HardikMaru** [comment]
[Code Details.zip](https://github.com/facebook/fresco/files/1680441/Code.Details.zip)

I have attached the code which is creating an issue. I have included all the things which are required to reproduce the issue, still if you need anything do let me know. OR else you can check the APK which I have shared in my issue description. and you will get an idea of it.

Best,
 Harry.

**Comment by HardikMaru** [comment]
Any updates??

**Comment by lambdapioneer** [comment]
Hi @HardikMaru, we would need a minimal code sample that reproduces the issue as we simply don't have the capacity to debug 3rd party apps. Also, the task of reducing it down to the most-simple Activity most likely will already show you what excatly causes the issue.

Maybe it can help you to compare your app with our showcase app which uses a drawer which works quite fine. Also the recycler view example might be interesting for you: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeRecyclerViewFragment.java

Feel free to open a new task with a compilable sample (or ideally a modification of the show case app) that demonstrates the issue.

**Comment by HardikMaru** [comment]
@lambdapioneer 

I am not newbee so I did tried all the possible ways and have check the demos available over repository and other sources. And when I haven't found any solutions working for me, I raise an issue over here.

But from your last comment, I can easily get an idea that you do not have time to solve the issue in Fresco Library. As I said I can't figure out the actual issue, as it don't give anything in Log and app load cause rendering issue of whole phone. But I know you don't have time to check it out and therefore you have closed the issue by ignoring it instead of solving it.
Its an issue of Fresco it self as Glide is working like a charm, so I would suggest you should stop providing the services of Fresco and close out the Fresco Library it self. :)

TOTALLY DISAPPOINTED FROM YOUR SUPPORT.

Best,
 Harry.

**Comment by BlackHC** [comment]
make ❤️ not 😠

**Comment by HardikMaru** [comment]
@BlackHC Sorry if it hurts. I totally believe in your words.

but I have posted this issue in hope of solution, not आश्वासन. :)
