### ISSUE TITLE
set scaletype for thumbnails

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [facebook/fresco#2037]
Hi 
i need to set scaletype to thumbnails in my  app but i can't find how to do that? 
please help me to do that.
thanks in advance.

**Comment by dmitry-voronkevich** [comment]
Hi, @AlirezaGhanbarinia, you can use placeholderImageScaleType and pass there scale type from http://frescolib.org/docs/scaletypes.html

**Comment by AlirezaGhanbarinia** [comment]
I have a used all of below methods together, but scale type is not set for "thumbnail".

setActualImageScaleType
setFailureImageScaleType
setPlaceholderImageScaleType
setProgressBarImageScaleType
setRetryImageScaleType


ScalingUtils.ScaleType.FIT_CENTER

**Comment by dmitry-voronkevich** [comment]
Can you please specify what is thumbnail in your case? Where do you use, what do you show there?
I thought thumbnail is the same as "placeholder".

**Comment by AlirezaGhanbarinia** [comment]
i want to load a low quality image at first and aftervthat a high quality one. i load the low quality image as a thumnail. the thumbnail has a scaletype itself but i want to change it.

**Comment by lambdapioneer** [comment]
Hi @AlirezaGhanbarinia, can you post some sample code that reproduces the issue? I'm not sure if thumbnail refers to what we call "placeholder" (see http://frescolib.org/docs/placeholder-failure-retry.html) or if you are doing a multi-uri request (see http://frescolib.org/docs/requesting-multiple-images.html).

**Comment by AlirezaGhanbarinia** [comment]
I`m using multi-uri request , Here is my sample code : PipelineDraweeControllerBuilder.setLowResImageRequest

**Comment by lambdapioneer** [comment]
Hey @AlirezaGhanbarinia, I've looked into this and tried to reproduce the issue. I took the `DraweeScaleTypeFragment` fragment from the Showcase sample app and changed the following method:

```
  private void changeMainDraweeUri(Uri uri) {
    final AbstractDraweeController controller =
        Fresco.getDraweeControllerBuilderSupplier().get()
            .setUri("http://frescolib.org/static/sample-images/animal_a_xxl.jpg")
            .setLowResImageRequest(ImageRequest
                .fromUri("http://frescolib.org/static/sample-images/animal_d_xxl.jpg")).build();
    mDraweeMain.setController(controller);
  }
```

By default the scale type in this example is `ScalingUtils.ScaleType.CENTER`. I observed the intended behavior: Both the low-res image request and the final image request are shown using the mentioned scale type (focus on the center, original size and rest of the image cropped).

Do you want to apply different scale types for the different image requests? Or is there another issue showing? It would be most helpful to have a code sample that I can run locally to reproduce the issue :)

**Comment by oprisnik** [comment]
I'm closing this issue for now due to inactivity. If this is still a problem, please let us know!
