### ISSUE TITLE
java.lang.VerifyError: com/facebook/i/k at SoLoader.initImpl$230dc011(SoLoader.java:203)

### ISSUE THREAD

**Issue by gajicm93** [facebook/fresco#2039]
### Description

Crash is happening on Android 4.x devices, when APK is built with ProGuard enabled and 'proguard-android-optimize.txt' configuration file.

### Reproduction

1. Get an Android 4.x device
2. Build an app with following build settings ("-optimize" is the important part):
```
debug {
    minifyEnabled true
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'proguard-fresco.pro'
}
```
3. BOOM!

You can find all the detailed information and system dumps here: http://crashes.to/s/c450feed2e9

### Additional Information

* Fresco version: 1.8.0
* Platform version: Android 4.x.

**Comment by lambdapioneer** [comment]
Hi @gajicm93, thank you very much for the bug report!

I can reproduce this with the showcase app by using the build settings that you've mentioned and a 4.4.2 emulator.

I'll have a look into how we can fix this (y)

**Comment by lambdapioneer** [comment]
Got it, proguard needs to know about the SoLoader `@DoNotOptimize` annotation. I'll add those rules for to the Fresco proguard file. If you want to unblock yourself in the meantime, you can add the following lines to your app's proguard file:

```
-keep,allowobfuscation @interface com.facebook.soloader.DoNotOptimize
-keep @com.facebook.soloader.DoNotOptimize class *
-keepclassmembers class * {
    @com.facebook.soloader.DoNotOptimize *;
}
```

**Comment by oprisnik** [comment]
Thanks for reporting this issue. @lambdapioneer has updated the ProGuard rules with 559082930126c05988f46de8f27fccad0dd88568, so please update your proguard files!
