### ISSUE TITLE
okhttp3 may not build after Fresco sources update

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#2041]
### Description

Build from sources complains and outputs errors (even after clean project) :  missing okhttp3 after this commit (switch from compile to implementation) : https://github.com/facebook/fresco/commit/b83a71b9d27cd3d95ef59cdaa291d89b6a09c27a#diff-68af0e80447eb282f6a40fa64a9b16f7 - https://github.com/facebook/fresco/blob/06fe3719a3a3c659438b6c25a8008945e67156a0/imagepipeline-backends/imagepipeline-okhttp3/build.gradle#L7

### Workaround
switch back to compile : 
`compile "com.squareup.okhttp3:okhttp:${OKHTTP3_VERSION}" `

Clean and build, then switch back to : 
 `implementation "com.squareup.okhttp3:okhttp:${OKHTTP3_VERSION}"`

### Additional Information
Not a bug - Workaround 
* Fresco version: up to https://github.com/facebook/fresco/commit/b83a71b9d27cd3d95ef59cdaa291d89b6a09c27a#diff-68af0e80447eb282f6a40fa64a9b16f7
* Gradle version : 4.1
* Android studio version : 3.0.1

**Comment by eldk** [comment]
Hello,

Just test again, when debug build with use of 'implementation', it always fails.

**Comment by oprisnik** [comment]
Thanks for the PR @eldk !
