### ISSUE TITLE
Render local image failed if the image path contains '#'

### ISSUE THREAD

**Issue by HenryChao24** [facebook/fresco#2045]
### Description

Render local image failed if the image path contains '#'

### Reproduction

`  String localThumb = "/storage/emulated/0/abc#abc/test.jpg";
    simpleImageDrawee.setImageURI(ResourceUtil.getFileURI(localThumb));`

**Comment by lambdapioneer** [comment]
Hi @HenryChao24, I think the issue might be with the `ResourceUtil` that you are using (is it the Apache one?).

Fresco comes with a `UriUtil` class that should correctly handle the `#` sign in file paths. I've tested that the following works in the Showcase sample app:

```
final Uri uri = UriUtil.getUriForFile(new File("/sdcard/Download/penguin#penguin.jpg"));
simpleDraweeView.setImageURI(uri);
```

**Comment by HenryChao24** [comment]
@lambdapioneer Great thanks, problem solved.

My `ResourceUtil` get Uri with `Uri.parse("file://" + path)` method creating a Uri which parses the given encoded URI string.  

Problem solved by using Fresco's `UriUtil` or `Uri.fromFile(file)`.
