### ISSUE TITLE
setResizeOptions Question

### ISSUE THREAD

**Issue by chongivan** [facebook/fresco#205]
The image pipeline "keeps a cache of compressed images on local storage, and a second cache of decompressed images in memory."

From the docs, "Resizing just resizes an encoded image in memory, prior to being decoded."

If i resize an image (via setResizeOptions), say 40x40 in one activity, and 200x200 in another activity, 

1) will there be 2 **resized** versions in memory? (assuming resized encoded image is cached)
2) will there be 2 **decompressed** versions in memory?
3) would it be **more memory efficient**, cache wise, if image is only resized once, say 200x200?

**Comment by tyronen** [comment]
1) Only the decompressed version. The resized encoded image is not yet cached.
2) Yes.
3) Yes, but for most apps this isn't going to make much difference.

**Comment by chongivan** [comment]
Thanks @tyronen =)
