### ISSUE TITLE
BMP support?

### ISSUE THREAD

**Issue by ened** [facebook/fresco#206]
During a first test, we found Fresco will not load .BMP images, like this one https://www.dropbox.com/s/dnye6rnxjftebq8/2girl-facebook-fresco.bmp?dl=0 > Is this a known / wanted limitation?

**Comment by tyronen** [comment]
This does count as a bug, but a low-priority one.

.BMP files are not compressed. They will take up excessive space on your users' disk, and if downloaded will eat their data usage and slow down their download. Are you sure you really need to use them?

**Comment by ened** [comment]
@tyronen I agree with everything you said. Our product is not just an app, but also a hardware media player for locally connected media sources like USB sticks, SD Cards and as such we try to aim to support as many formats as possible.

**Comment by ened** [comment]
@tyronen Just to be sure, you do plan on supporting all standard Android photo formats as outlined on https://developer.android.com/guide/appendix/media-formats.html, right? I think besides BMP it's already the case for most.

**Comment by tyronen** [comment]
Yes.

**Comment by tyronen** [comment]
Fixed in 0.5.1.

**Comment by ombres** [comment]
aha, this problem encountered in my project when using version 0.5.0, thanks for fixing this bug.
