### ISSUE TITLE
SoLoader breaks custom class loaders

### ISSUE THREAD

**Issue by ChengCheng-Hello** [facebook/fresco#2062]
java.lang.RuntimeException:Unable to create application com.baijiahulian.tianxiao.App: java.lang.IllegalStateException: ClassLoader com.taobao.sophix.core.dex.a.a should be of type BaseDexClassLoader
--
android.app.ActivityThread.handleBindApplication(ActivityThread.java:6500)
......
Caused by:
java.lang.IllegalStateException:ClassLoader com.taobao.sophix.core.dex.a.a should be of type BaseDexClassLoader
com.facebook.soloader.SoLoader$Api14Utils.getClassLoaderLdLoadLibrary(SourceFile:638)
com.facebook.soloader.SoLoader.initSoLoader(SourceFile:238)
com.facebook.soloader.SoLoader.initImpl(SourceFile:141)
com.facebook.soloader.SoLoader.init(SourceFile:120)
com.facebook.soloader.SoLoader.init(SourceFile:104)

* Fresco version: 1.8.0
* Platform version: Android >=7.0

**Comment by erikandre** [comment]
Hi @ChengCheng-Hello 

I think the problem might be that you are also using some other library in your app which modifies how classes and .so files are loaded. 

My guess is that com.taobao.sophix.core is connected to this.

@oprisnik  - is it still possible to use SoLoaderShim instead of SoLoader? That might help here.

**Comment by oprisnik** [comment]
No, SoLoader is the new default, but it should not interfere with this.

**Comment by erikandre** [comment]
@oprisnik , it seems like SoLoader assumes that the class loader extends BaseDexClassLoader though. So if you're injecting a different class loader (I guess this is the case here), it would break.

**Comment by oprisnik** [comment]
As @erikandre mentioned, the issue is likely your custom class loader. It should extend BaseDexClassLoader.

**Comment by xylitolhub** [comment]
Could fresco not break down when class loader is not instance of BaseDexClassLoader? 
And I think it should not force user's custom classloader to be an BaseDexClassLoader, I just want the picture loading function of fresco.
It could has **downgraded to use system default way** to load .so file in this case.

**Comment by parcool** [comment]
how to fix this bug? i got this error and i don't know how to do

**Comment by krottv** [comment]
My opinion that adding SoLoader as default wasn't a good choice. I use different so loader for my project and I don't need SoLoader. I use ReLinker

**Comment by parcool** [comment]
@krottv  SoLoader named sophix what is a hot-fix library and it must the base application,it use annotation to add my application.i want to add this two libs(fresco and sophix),is there any workground?

**Comment by oprisnik** [comment]
We're bringing back a new native loader interface (as part of SoLoader itself) so that you can use whatever you want in the future.

**Comment by oprisnik** [comment]
This has been introduced now with version 2.1.0

**Comment by oprisnik** [comment]
You can use `NativeLoader.init(....)` before Fresco is initialized to use any native loader and you can exclude SoLoader from your Gradle dependencies when Fresco is loaded.
