### ISSUE TITLE
Add the ability to check whether a SimpleDraweeView is displaying a placeholder/fail/retry image

### ISSUE THREAD

**Issue by DogParty** [facebook/fresco#2065]
### Description

Would it be possible to add a method to SimpleDraweeView that returns the state of the image download? This is necessary for my codebase because the user can long press on an image to share it but I don't want to allow this on images that haven't loaded yet. I have managed to implement it myself by grabbing the Drawable, finding the FadeDrawable, and then checking if the layer for each state is enabled. This works but relies on using hardcoded layer indexes that I fear might change in a future Fresco update. Here's the Kotlin code I wrote as extension functions:

```Kotlin
package com.app.util

import com.facebook.drawee.drawable.FadeDrawable
import com.facebook.drawee.generic.RootDrawable
import com.facebook.drawee.view.SimpleDraweeView

fun SimpleDraweeView.isPlaceholderVisible(): Boolean {
    val FRESCO_PLACEHOLDER_DRAWABLE_LAYER_INDEX = 1
    return this.isDrawableLayerVisible(FRESCO_PLACEHOLDER_DRAWABLE_LAYER_INDEX)
}

fun SimpleDraweeView.isTaptoRetryVisible(): Boolean {
    val FRESCO_TAP_TO_RETRY_DRAWABLE_LAYER_INDEX = 4
    return this.isDrawableLayerVisible(FRESCO_TAP_TO_RETRY_DRAWABLE_LAYER_INDEX)
}

private fun SimpleDraweeView.isDrawableLayerVisible(drawableLayer: Int): Boolean {
    return this.drawable is RootDrawable
            && (this.drawable.current as? FadeDrawable)?.isLayerOn(drawableLayer) ?: false
}
```

I apologize if this is the wrong location for feature requests. If you could point me to the proper avenue, I'll submit it there :) Also, if this is totally unnecessary and if there's an easy way to find out the state using the SimpleDraweeView, please let me know! Thanks!

### Additional Information

* Fresco version: 1.8.1
* Platform version: Any

**Comment by erikandre** [comment]
Hi @DogParty 

I believe you can achieve what you want using one of the listeners that we provide:
http://frescolib.org/docs/listening-to-events.html

**Comment by DogParty** [comment]
Thanks @erikandre!

**Comment by oprisnik** [comment]
That said, we're happy about pull requests that make this easier to check. Feel free to submit one!
