### ISSUE TITLE
placeholder roundCorner to do work

### ISSUE THREAD

**Issue by zhangxu1005** [facebook/fresco#2069]
` app:placeholderImage="@drawable/smart_video_default_cover"
                app:placeholderImageScaleType="fitXY"
                app:roundBottomLeft="false"
                app:roundBottomRight="false"
                app:roundTopLeft="true"
                app:roundTopRight="true"
                app:roundedCornerRadius="10dp"`

Here is my source code , the placeholderImage is a nine-patch drawable, then the roundedCorner to not work when show placeholder. If set a normal drawable to placeholderImage, the roundedCorner works well.

**Comment by oprisnik** [comment]
I think we might not properly handle 9patch images with rounded corners. You can manually create a rounded corner version in code and set it.

We'd appreciate help with implementing this if you or somebody else wants to add this feature.

**Comment by jnawaz** [comment]
@zhangxu1005 if you're able to share the nine-patch image you're using, I'll take a look at reproducing this and have a go at implementing a fix.

**Comment by zhangxu1005** [comment]
![oscar_default_image 9](https://user-images.githubusercontent.com/3357262/37823538-bd8fada0-2ec4-11e8-8497-cc0efad420ab.png)

**Comment by defHLT** [comment]
Fixed in e1aa81f797583c244817fc334395a13d0e33b3bc
