### ISSUE TITLE
why is EncodedImage#get/setEncodedCacheKey deprecated?  other method replace?

### ISSUE THREAD

**Issue by qhyuan1992** [facebook/fresco#2071]
how can i get uri from EncodedImage?

**Comment by qhyuan1992** [comment]
@oprisnik  can you help me

**Comment by oprisnik** [comment]
What would you like to achieve? 

The `EncodedImage` class represents an image. The fact that this image might have had a network URL at some point should be irrelevant. I guess that

**Comment by kirwan** [comment]
This was introduced to support a scenario where an alternative image may be provided which shouldn't be cached under the original URI.

However, we now have better ways of handling this and it was never intended that this API would be used outside of the pipeline itself.

@qhyuan1992: What's the use case? You must have the URI to begin with so why do you need it back from the EncodedImage?

**Comment by qhyuan1992** [comment]
I know, Thanks
We use Fresco from v1.1. we use a custom ImageDecoder to solve some OOM,where we add some
 protect Logic ,do not decode too big picture, and print the url which cause OOM. there are many old code using such as AnimatedDrawable... or deprecated Apis.
Now i have updated Fresco to v1.8.1 successfully

**Comment by oprisnik** [comment]
That's interesting. So you're catching the OOM exception and just display no image if it happens?

**Comment by qhyuan1992** [comment]
yes. I read the old code. we will display nothing for too big pic. there are too many various of  machines that has extremely low memory. so it may be a good idea? 

recently. i met a question I use fresco imagepipeline outside for weex. maybe i did not manage the CloseableReference correctly. so i receive many crash only above Android O?  i find Bitmap#recycle change on Android O? when Bitmap#recycle execute, the pixel data of Bitmap referenced by View can not free below Android O ? but can free above?   I am not very sure. can you help me ?

[https://android.googlesource.com/platform/frameworks/base/+/c69853c8b72540e5031d28e03cbce5a390c6959f%5E%21/#F0](https://android.googlesource.com/platform/frameworks/base/+/c69853c8b72540e5031d28e03cbce5a390c6959f%5E%21/#F0)
