### ISSUE TITLE
there are sawteeth when setting rounding border to display round pic

### ISSUE THREAD

**Issue by YuZhiLiang** [facebook/fresco#2072]
### Description

there are sawteeth when setting rounding border to display round pic, Only on versions above 8.0

### Reproduction

Here's the code:
``` xml
    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/active_img"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        fresco:actualImageScaleType="fitXY"
        fresco:layout_constraintBottom_toBottomOf="parent"
        fresco:layout_constraintLeft_toLeftOf="parent"
        fresco:layout_constraintRight_toRightOf="parent"
        fresco:layout_constraintTop_toTopOf="parent"
        fresco:placeholderImageScaleType="fitXY"
        fresco:roundedCornerRadius="3.33dp"
        fresco:roundingBorderColor="#FFEBEBEB"
        fresco:roundingBorderWidth="0.33dp"/>
```
``` java
SimpleDraweeView mTopicImg = Views.findViewById(this, R.id.active_img);
Uri urii = Uri.parse(mPicUrl);
mTopicImg.setImageURI(uri);
```

###ImageLink:
![the whole picture](https://s1.ax1x.com/2018/03/20/9TOOns.png)
![detail picture](https://s1.ax1x.com/2018/03/20/9TOXBn.png)
![detailMark](https://s1.ax1x.com/2018/03/20/9TOj7q.png)

### Additional Information
* Only on versions above 8.0
* Fresco version: [fresco:1.8.0]
* Platform version: [OPPO R11s Android 8.1.0]

**Comment by lambdapioneer** [comment]
Thanks @YuZhiLiang for the bug report. I feel that I cannot reproduce this on a Google Pixel with Android 8.1.0 in our showcase app.

When setting your border configuration, the edges look weird. However, when zooming in it seems that they are correct and it's just the thinness of the border that makes it look weird.

Setting an overlay color (opposed to bitmap rounding, http://frescolib.org/docs/rounded-corners-and-circles.html) does not seem to have any effect.

Does removing the border help in your case?
Is it just that OPPO device or also other Android 8.1.0 devies?

**img1: Just setting rounding looks great**

![a](https://user-images.githubusercontent.com/908387/37768809-d4b9d9a0-2dc6-11e8-8f97-8760478d3f7d.png)

**img2: Adding a 0.33dp border looks "ugly" around the corners**

![b](https://user-images.githubusercontent.com/908387/37768814-d846e7c0-2dc6-11e8-866d-dc28c563ecb8.png)

![bb](https://user-images.githubusercontent.com/908387/37769140-ee3159fc-2dc7-11e8-8461-05ea9d12385f.png)

**Comment by YuZhiLiang** [comment]
removing the border is ok, but not the best solution,UI made compromises.
I only test it on OPPO devices, because we are equipment manufacturers，hope this problem can be fixed.
thankssssssss  ╭(●｀∀´●)╯╰(●’◡’●)╮ (●’◡’●)ﾉ ヾ(*´▽‘*)ﾉ

**Comment by oprisnik** [comment]
I don't think that there's anything that we can do. You can always manually draw the border by adding a custom overlay / background to the image. Otherwise, as Daniel described, it's the 0.33dp that's causing issues.
