### ISSUE TITLE
webp have native memory leak

### ISSUE THREAD

**Issue by howardpang** [facebook/fresco#2073]
### Description

webp have native memory leak; please open the file : 
https://github.com/facebook/fresco/blob/master/static-webp/src/main/jni/static-webp/webp.cpp
and jump to the function:

`
jobject WebPImage_nativeGetFrame(JNIEnv* pEnv, jobject thiz, jint index) {
  auto spNativeContext = getWebPImageNativeContext(pEnv, thiz);
  if (!spNativeContext) {
    throwIllegalStateException(pEnv, "Already disposed");
    return nullptr;
  }

  auto spIter = std::unique_ptr<WebPIterator, decltype(&WebPDemuxReleaseIterator)> {
    new WebPIterator(),
    WebPDemuxReleaseIterator
  };
........
`

because "WebPDemuxReleaseIterator" do nothing, and "spIter" will never release, the "WebPDemuxReleaseIterator" implemention:

`void WebPDemuxReleaseIterator(WebPIterator* iter) {
  (void)iter;
}`

### Reproduction

play webp animated

### Solution

Don't use "std::unique_ptr", use local var to define "spIter" or don't specify deleter to "std::unique_ptr"

### Additional Information

* Fresco version: all version
* Platform version: [FILL THIS OUT: specific to a particular Android version? Device?]

**Comment by lambdapioneer** [comment]
Thanks for creating this issue @howardpang! This looks legit.

We'll have a look, but also feel invited to provide a PR with the suggested fix :)

**Comment by lambdapioneer** [comment]
Fixed in https://github.com/facebook/fresco/pull/2079
