### ISSUE TITLE
About the actualImageScaleType

### ISSUE THREAD

**Issue by sicmu** [facebook/fresco#208]
I don't know why the view display like this?

![1](https://cloud.githubusercontent.com/assets/11207241/7347688/9a009458-ed1d-11e4-890e-fb2a7057fba4.png)

The nomal picture is :
![20150214111048728](https://cloud.githubusercontent.com/assets/11207241/7347552/46d46314-ed1c-11e4-88b9-6537e2a1dc50.jpg)

The xml is :

 FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/lore_img"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        fresco:actualImageScaleType="fitCenter"
        fresco:placeholderImage="@color/white"
        fresco:roundedCornerRadius="3dp"/>

 FrameLayout>

And the java code is :

public class MakGroupFragment extends MainBaseFragment {
	private SimpleDraweeView img;

	@Override
	public void onAttach(Activity activity) {
		super.onAttach(activity);
	}

	@Override
	public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
		return inflater.inflate(R.layout.fragment_mak_group, container, false);
	}

	@Override
	public void onActivityCreated(@Nullable Bundle savedInstanceState) {
		super.onActivityCreated(savedInstanceState);
		img = (SimpleDraweeView) getView().findViewById(R.id.lore_img);
		img.setImageURI(Uri.parse("http://www.iyi8.com/uploadfile/2015/0214/20150214111048728.jpg"));
	}

}

**Comment by sicmu** [comment]
I find the similar issue.
https://github.com/facebook/fresco/issues/153

**Comment by show111** [comment]
how to solution this issue?i also encounter this.

**Comment by oprisnik** [comment]
It seems that the easiest solution right now is to use `OVERLAY_COLOR` instead of `BITMAP_ONLY` for  rounding the corners, see [the documentation for rounded corners](http://frescolib.org/docs/rounded-corners-and-circles.html).

You can take a look at the discussion in #153 for more details why this is happening @show111.
