### ISSUE TITLE
proguard-fresco.pro broken link

### ISSUE THREAD

**Issue by novotnyfra** [facebook/fresco#2080]
### Description
in file https://github.com/facebook/fresco/blob/cd416a3bcab402617ec95b69892f865568d49647/docs/_docs/proguard.md

broken link to download file _proguard-fresco.pro_ (https://raw.githubusercontent.com/facebook/fresco/master/proguard-fresco.pro)

### Reproduction

https://github.com/facebook/fresco/blob/cd416a3bcab402617ec95b69892f865568d49647/docs/_docs/proguard.md or http://frescolib.org/docs/shipping.html - follow instruction - "download Fresco’s ProGuard file, proguard-fresco.pro"

**Comment by lambdapioneer** [comment]
Thanks @novotnyfra for raising this issue :)

Seems like it got lost in here: https://github.com/facebook/fresco/pull/2075

I'll fix that right now

**Comment by lambdapioneer** [comment]
You can use `https://raw.githubusercontent.com/facebook/fresco/master/fbcore/proguard-fresco.pro` as a working link for now

**Comment by novotnyfra** [comment]
oh, fast fix, thanks a lot
