### ISSUE TITLE
How i can Blur the image ??

### ISSUE THREAD

**Issue by ahmadmiraj** [facebook/fresco#2084]
How i can BLUR my image like this ??
@sophiebits @zpao @ericnakagawa @killian @veenix 
<img width="532" alt="screen shot 2018-04-02 at 11 14 57 pm" src="https://user-images.githubusercontent.com/12697617/38208835-bcb44954-36cb-11e8-8705-47fe1f0e77fa.png">

**Comment by ahmadmiraj** [comment]
@oprisnik

**Comment by oprisnik** [comment]
You have to supply a postprocessor that does this, see http://frescolib.org/docs/modifying-image.html and https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/postprocessor/ScalingBlurPostprocessor.java
