### ISSUE TITLE
circuler image issue ??

### ISSUE THREAD

**Issue by ahmadmiraj** [facebook/fresco#2085]
i am getting this problem while i am using this library for creating circular image !

xml code
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/ivProfilePic"
                android:layout_gravity="center_horizontal"
                android:layout_marginTop="111dp"
                android:layout_width="100dp"
                android:layout_height="100dp"
                fresco:roundWithOverlayColor="@android:color/transparent"
                fresco:roundingBorderWidth="3dp"
                fresco:roundingBorderColor="@color/colorPrimaryDark"
                fresco:placeholderImageScaleType="centerCrop"
                fresco:roundAsCircle="true"
                />

Hierarchy call :
 GenericDraweeHierarchy hierarchy1 = profilePic.getHierarchy();
        try {
            profilePic.setController(Utils.returnController(URLDecoder.decode(imgURL, "UTF-8"), profilePic));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

 public static DraweeController returnController(String uri, SimpleDraweeView view){
        if(uri==null)
            uri = "";

        ImagePipeline imagePipeline = Fresco.getImagePipeline();

        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
                .setProgressiveRenderingEnabled(true)
                .build();
        ImageRequest mediumRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
                .setProgressiveRenderingEnabled(true)
                .setResizeOptions(new ResizeOptions(Utils.getDeviceHeight(view.getContext())/2,Utils.getDeviceHeight(view.getContext())/2))
                .build();
        ImageRequest lowResRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
                .setProgressiveRenderingEnabled(true)
                .setResizeOptions(new ResizeOptions(Utils.getDeviceHeight(view.getContext())/5,Utils.getDeviceHeight(view.getContext())/5))    .build();

        imagePipeline.clearCaches();

        return Fresco.newDraweeControllerBuilder()
                .setLowResImageRequest(mediumRequest)
                .setFirstAvailableImageRequests(new ImageRequest[]{request,mediumRequest,lowResRequest},false)
<img width="277" alt="screen shot 2018-04-02 at 11 27 27 pm" src="https://user-images.githubusercontent.com/12697617/38209333-7315ce1a-36cd-11e8-82fe-b98d7520a638.png">

                .setAutoPlayAnimations(true)
                .setOldController(view.getController())
                .build();
    }

Please help me with this 
@sophiebits @zpao @ericnakagawa @killian @veenix

**Comment by ahmadmiraj** [comment]
@oprisnik

**Comment by jcsla** [comment]
gif image ?

**Comment by ahmadmiraj** [comment]
@jcsla no it is a Simple iMage 
you can find that image here 
https://tattoodo-mobile-app.imgix.net/images/posts/nodes_AAleRQLAJg.jpg?w=600&auto=format,compress&fit=crop

**Comment by foghina** [comment]
See here about the different rounding methods that we have: http://frescolib.org/docs/rounded-corners-and-circles.html

You probably want to use `BITMAP_ONLY` in this case (i.e. don't specify an overlay color).

**Comment by oprisnik** [comment]
As to why this is happening: The overlay color is the color drawn on top of the underlying square image to make it appear as if it's rounded. In your case, you're drawing a transparent color on top, which means that you still see the original image.
