### ISSUE TITLE
play GIF once and manually in RN application

### ISSUE THREAD

**Issue by assafb81** [facebook/fresco#2086]
### Description
I add a GIF to my RN application as described here(https://facebook.github.io/react-native/docs/image.html#gif-and-webp-support-on-android)
I want to click on the GIF cover - the 1st image of the GIF - and than it should play only once.
once it complete the image should be the last image of the GIF.

Actual Behavior

- on Android & iOS once the screen is rendered the GIF plays, I can't control it.

- play once - on iOS the gif is played in a loop without stopping

### Reproduction

Add gif as describe in here(https://facebook.github.io/react-native/docs/image.html#gif-and-webp-support-on-android)

### Additional Information

* Fresco version: com.facebook.fresco:animated-base-support:1.3.0
* Fresco version: com.facebook.fresco:animated-gif:1.3.0
* OS 1: Windows 8.1
* OS 2: iOS - macOS High Sierra 10.13.3
* Node: 8.9.3
* npm: 5.6.0
* react: 16.2.0
* react-native: 0.52.0

the settings in my `build.gradle`:
```
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId XXXX
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    .....
    dependencies {
        // If your app supports Android versions before Ice Cream Sandwich (API level 14)
        compile 'com.facebook.fresco:animated-base-support:1.3.0'

        // For animated GIF support
        compile 'com.facebook.fresco:animated-gif:1.3.0'
        ....
```

**Comment by foghina** [comment]
This is something that needs to be fixed / implemented on the React Native side -- please report this issue there.
