### ISSUE TITLE
is:issue is:open java.lang.RuntimeException: Could not initialize SoLoader

### ISSUE THREAD

**Issue by li504799868** [facebook/fresco#2088]
first install app on my Phone，the app has crashed，the log is：

is:issue is:open java.lang.RuntimeException: Could not initialize SoLoader

**Comment by foghina** [comment]
Please fill out the issue template with more details. This isn't giving us much to go on.

Closing this issue for now, feel free to open a new one once you can provide more information such as logs, code, repro steps and so on.
