### ISSUE TITLE
Camera Image and Camera Folder Image not showing in SimpleDraweeView

### ISSUE THREAD

**Issue by saran2somu** [facebook/fresco#2089]
Hi Team, 

Compare to other image libraries, fresco has more option. 

I have an issue, when I was select the Camera image's into `SimpleDraweeView` it displays empty view, 
I have used image picker to pick images and take camera option too.

 `SimpleDraweeView` - fail in, taking an image using the camera and browse the image from a camera folder. Another image folder , images load correctly without resizing.
I tried all option to set Images like setImageURI ... 

Finally, I find when I resize the camera image to 50X50 as width and height it shows.

I try to fix the issue in last two days. I didn't find the solution. Please help me to fix the issue.

Mobile Configuration,
One Plus X - Android Oreo
Android Studio 3.1
library: 1.8.1 

```
public void setImageFileURI(String imageURI,int width,int height){
        try {
            Uri uri = new Uri.Builder()
                    .scheme(UriUtil.LOCAL_FILE_SCHEME)
                    .path(imageURI)
                    .build();
            ImageRequest request = ImageRequestBuilder
                    .newBuilderWithSource(uri)
                    .setResizeOptions(new ResizeOptions(width,height))
                    .setProgressiveRenderingEnabled(true)
                    .build();
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setImageRequest(request)
                    .setRetainImageOnFailure(true)
                    .setOldController(getController())
                    .build();
           simpleDraweeView.setController(controller);
        }catch (Exception e){
            e.printStackTrace();
        }

    }
```

**Comment by foghina** [comment]
We have sample in our showcase app that does this. You can have a look at the sample code here:

https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeMediaPickerFragment.java

If your app always works when you resize to 50x50 it might mean that your photos are too large and they don't fit in memory. Is there a reason why you wouldn't always resize, e.g. to the screen width/height?

Also, could you share logcat output when you're trying to load these images?

**Comment by oprisnik** [comment]
I'm closing this for now. Feel free to let us know if this is still an issue and we can re-open.
