### ISSUE TITLE
com.facebook.imagepipeline.memory.NativeMemoryChunk

### ISSUE THREAD

**Issue by Yinzeyu** [facebook/fresco#2090]
设备机型
魅族 M2 NOTE
系统版本
Android 5.1,level 22
com.facebook.imagepipeline.memory.NativeMemoryChunk

com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:58)
--
2 com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:20)
3 com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:257)
4 com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:51)
5 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
6 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
7 com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:90)
8 com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:70)
9 com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:122)
10 okhttp3.RealCall$AsyncCall.d(RealCall.java:153)
11 okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
12 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
13 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
14 java.lang.Thread.run(Thread.java:818)

**Comment by Yinzeyu** [comment]
com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:522)
--
2 com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:420)
3 com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:370)
4 com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:335)
5 com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:42)
6 com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:33)
7 com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:58)
8 com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:20)
9 com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:257)
10 com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:51)
11 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
12 com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
13 com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:90)
14 com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:70)
15 com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:122)
16 okhttp3.RealCall$AsyncCall.d(RealCall.java:153)
17 okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
18 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
19 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
20 java.lang.Thread.run(Thread.java:818)

**Comment by Yinzeyu** [comment]
# OkHttp Dispatcher(821)

java.lang.UnsatisfiedLinkError

com.facebook.imagepipeline.memory.NativeMemoryChunk

**Comment by Yinzeyu** [comment]
//图片请求框架
    compile 'com.facebook.fresco:fresco:1.8.1'
    compile 'com.facebook.fresco:animated-webp:1.8.1'
    //noinspection GradleDynamicVersion
    compile 'com.facebook.fresco:imagepipeline-okhttp3:0.12.0+'

**Comment by Yinzeyu** [comment]
compileSdkVersion 27
    minSdkVersion 19
        targetSdkVersion 21
 classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by oprisnik** [comment]
Can you try and use `compile 'com.facebook.fresco:imagepipeline-okhttp3:1.8.1' ` instead?

**Comment by Yinzeyu** [comment]
I'll try and give you a reply tomorrow.

**Comment by Yinzeyu** [comment]
abiFilters 'armeabi-v7a', 'arm64-v8a'    
 We can't solve this problem. We support two kinds of V8 and V7 by NDK. We can remove V8, but we can't get rid of one of two kinds of projects.

**Comment by oprisnik** [comment]
Are you using ABI splits? We've explained how to set up your application in that case, see http://frescolib.org/docs/shipping.html

**Comment by llong0807** [comment]
@Yinzeyu 问题解决了吗？  在魅蓝2也出现了
