### ISSUE TITLE
Fresco not loading images after uploading the images to playstore !

### ISSUE THREAD

**Issue by ahmadmiraj** [facebook/fresco#2092]
i am using fresco in my app and it is working fine but when i uploaded the app on playstore it is not loading the images. ant guess why it is not working ???

**Comment by ahmadmiraj** [comment]
@sophiebits @oprisnik

**Comment by oprisnik** [comment]
My best guess is that your release app uses ProGuard and you did not set up ProGuard correctly. Please take a look at http://frescolib.org/docs/shipping.html

If this doesn't help, we need a stack trace of the error. I'm closing this for now but can re-open if ProGuard wasn't the issue.

**Comment by ahmadmiraj** [comment]
i was facing warnings while generating apk.
so i put 
-dontwarn com.facebook.infer.annotation.ReturnsOwnership
-dontwarn com.facebook.infer.annotation.Functional
-dontwarn com.facebook.infer.annotation.PropagatesNullable
-dontwarn com.facebook.infer.annotation.ThreadSafe
these roles in prograd file.

@oprisnik

**Comment by heapsol** [comment]
@oprisnik can you please help me out ?

**Comment by oprisnik** [comment]
You can try and upgrade to version 1.9.0, which has inlined proguard rules, which should then work. https://github.com/facebook/fresco/releases/tag/v1.9.0

If you don't want to upgrade, please use the proper proguard rules according to the link I've posted above.
