### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Failed to decode frame

### ISSUE THREAD

**Issue by ShamsChu** [facebook/fresco#2093]
![image](https://user-images.githubusercontent.com/12422273/38484873-89ff4704-3c0a-11e8-9902-8b7b8aba4293.png)

This is my crash report. The version of fresco I use is V1.8.1. Is there any way I can avoid it? Many thanks...

**Comment by ShamsChu** [comment]
I hope we can catch this exception if it is because of a picture problem rather than let it crash.

**Comment by oprisnik** [comment]
Thanks for the report. Do you have a sample image where this happens?

**Comment by FrankChanCQF** [comment]
I still receive several same crashes every day after i did as @oprisnik  replied on 23 May，it seemed that wrapping the origin backend implementation in customed one doesn't work. Then I found the last comment in [https://github.com/facebook/fresco/issues/1954](url). Hope version-1.1.0.0 can help me

**Comment by EyreGe** [comment]
I have the same issue with 1.9.0. 
Edited gradle to use fresco dependencies v 1.3.0 and it is working.
