### ISSUE TITLE
Unable to resolve dependency for ':banner@debug/compileClasspath'

### ISSUE THREAD

**Issue by faith-hb** [facebook/fresco#2095]
Unable to resolve dependency for ':banner@debug/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':banner@debugAndroidTest/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':banner@debugUnitTest/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':banner@release/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':banner@releaseUnitTest/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.facebook.fresco:fresco:1.8.1.
Open File
Show Details

**Comment by oprisnik** [comment]
Did you properly configure JCenter / Maven Central in your Gradle setup?

I've just created a simple empty application using Android Studio, set it up according to http://frescolib.org/docs/index.html and the app compiles and the image loads without issues.

Please set up your app according to http://frescolib.org/docs/index.html
