### ISSUE TITLE
 draweeView.setImageURI(imageUri) throws an exception "unknown Image format" when the image is set from cache.

### ISSUE THREAD

**Issue by prathibhap-google** [facebook/fresco#2096]
draweeView.setImageURI(imageUri) throws an exception "unknown Image format" when the image is set from cache. 

This is the decoder that is used to decode the input stream after the image is downloaded from the server.

`private static class CustomImageDecoder implements ImageDecoder {
        @Override
        public CloseableImage decode(EncodedImage encodedImage, int length, QualityInfo qualityInfo, ImageDecodeOptions options) {
            try {
                InputStream inputStream = decrypt(encodedImage.getInputStream());
                Bitmap bitmap = BitmapFactory.decodeStream(inputStream);
                return new CloseableStaticBitmap(bitmap, SimpleBitmapReleaser.getInstance(), qualityInfo, encodedImage.getRotationAngle());
              } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }
    }

private void setImage(Uri imageUri) {
    if (Fresco.getImagePipeline().isInBitmapMemoryCache(imageUri)) {
         draweeView.setImageURI(imageUri);
    } else {
         ImageRequestBuilder imageRequestBuilder = 
         ImageRequestBuilder.newBuilderWithSource(imageUri)
                .setImageDecodeOptions(ImageDecodeOptions.newBuilder()
                        .setCustomImageDecoder(new CustomImageDecoder()).build());
        ImageRequest imageRequest =imageRequestBuilder.build();
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setUri(imageUri)
                    .setImageRequest(imageRequest)
                    .setOldController(draweeView.getController())
                    .build();
            draweeView.setController(controller);
      }
}`

**Comment by oprisnik** [comment]
Sorry for the late reply.

I think your controller setup is causing this issue.
You're setting both an image URI and an imageRequest, and the URI will override what's set via ImageRequest.

If you remove `setUri(imageUri)`, it should work:
```java
DraweeController controller = Fresco.newDraweeControllerBuilder()
.setImageRequest(imageRequest)
.setOldController(draweeView.getController())
.build();
draweeView.setController(controller);
```
