### ISSUE TITLE
How to use matrix?

### ISSUE THREAD

**Issue by EdgarX** [facebook/fresco#210]
I want to use matrix , like this
```
Matrix matrix = new Matrix();
Camera camera = new Camera();

camera.save();
camera.rotateY(10);
camera.getMatrix(matrix);
camera.restore();
matrix.preTranslate(0, -280);
```
I can use it on PlaceholderImage, like this
```
SimpleDraweeView simpleDraweeView;
Resources res;
        
Bitmap bm = BitmapFactory.decodeResource(res, R.drawable.placeholderimage);
bm = Bitmap.createBitmap(bm, 0, 0, bm.getWidth(), bm.getHeight(), mMatrix, true);
simpleDraweeView.getHierarchy().setPlaceholderImage(new BitmapDrawable(res, bm));
```
But I can not use it in ImageRequest, I should be how to use the matrix?

**Comment by tyronen** [comment]
When [constructing the hierarchy](http://frescolib.org/docs/using-drawees-code.html#customizing-the-hierarchy), use the [setActualImageMatrix](http://frescolib.org/javadoc/reference/com/facebook/drawee/generic/GenericDraweeHierarchyBuilder.html#setActualImageMatrix\(android.graphics.Matrix\)) method.

**Comment by sagartrehan** [comment]
Method setActualImageMatrix is deprecated, now how I can apply martix on image. :(
