### ISSUE TITLE
https://www.fresco-cn.org/ used an invalid security certificate

### ISSUE THREAD

**Issue by OCNYang** [facebook/fresco#2100]
I know Mark Elliot Zuckerberg was busy recently.
But still ask him to find some free time to update the site's security certificate.

**Comment by zmroczek** [comment]
Hi @OCNYang 

Thanks for reporting this issue. fresco-cn.org is a community-hosted translation of frescolib.org and we do not own it. We will try to get in touch with the person who owns it and ask to update the certificate.

Thank you!
