### ISSUE TITLE
fresco can not  show image 

### ISSUE THREAD

**Issue by fengruyi** [facebook/fresco#2105]
I use fresco as my app image loader lib,when I enter app in a weak wifi net ,I can get data from service but no image can show,I switch another good strong wifi and refresh,this page never show image ,even I shutdown app and open again,but I open another activity with image data,i can show image ,finally I remove fresco disk memory,it work for me. is a bug in fresco?how can I fix it at my code

**Comment by erikandre** [comment]
Closing due to lack of response. Please comment here with more details if you would like us to investigate further.

**Comment by lambdapioneer** [comment]
@cdiamon Please create a new issue for that. Also, that image is really large (>10000px side length, 8MB file). I wouldn't expect a mobile system to load such a file
