### ISSUE TITLE
Fresco site broken over HTTPS

### ISSUE THREAD

**Issue by Daniel15** [facebook/fresco#2106]
GitHub now support HTTPS for custom domains (see https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

Currently, the Fresco site is broken over HTTPS, as all the URLs in the HTML appear to be hard-coded to use "http://": https://frescolib.org

I'd suggest changing everything to use HTTPS, and then enable the "Enforce HTTPS" option in the GitHub settings.

**Comment by erikandre** [comment]
Thanks for the suggestion @Daniel15

**Comment by erikandre** [comment]
Closing as this has been fixed
