### ISSUE TITLE
Animated webp cost a lot of memory

### ISSUE THREAD

**Issue by stackJolin** [facebook/fresco#2109]
### Description

I have a animated webp,size is 90K。And per frame is 121K，but when I display the animated webp，the app's memory increase about 2M。But in iOS platform，it increase 200K，why and how to optimize memory

### Additional Information

* Fresco version: 1.9.0 and 0.14.1
* Platform version: 5.1

**Comment by erikandre** [comment]
Hi @stackJolin 

What is the size of each frame (width and height in pixels). Depending on what library you are using to decode the animations on iOS it might keep fewer frames in memory (which is good for memory usage but bad for performance).

**Comment by stackJolin** [comment]
@erikandre one frame is webp unzip to pngs，one png is 121K。In iOS，I use SDWebImage(It's contain libwebp)，performance and memory is good。So，I want to know what I can do to optimize memory

**Comment by stackJolin** [comment]
@erikandre  Webp unzip to pngs，one png(frame) is 121K。In iOS，I use SDWebImage(It's contain libwebp)，performance and memory is good。So，I want to know what I can do to optimize memory

**Comment by erikandre** [comment]
@oprisnik, can we specify the number of frames which should be kept in memory?

**Comment by oprisnik** [comment]
So basically what's happening is that Fresco's version prepares a couple of frames (default = 3) ahead of time and caches them in memory. This really helps to have a fluent animation to ensure that we are more likely to have a frame ready for rendering when needed.
If you want to customize that behavior, you can set a custom BitmapFramePreparationStrategy or use the default fixed one with a custom number of frames (https://github.com/facebook/fresco/blob/master/animated-drawable/src/main/java/com/facebook/fresco/animation/bitmap/preparation/FixedNumberBitmapFramePreparationStrategy.java)

You can get the `AnimatedDrawable2` by casting the `Animatable` object of the Controller listener and then just set your custom animation backend properties.
