### ISSUE TITLE
crash when using weibo API－closed

### ISSUE THREAD

**Issue by binqiangsun** [facebook/fresco#211]
IWeiboShareAPI mWeiboShareAPI = WeiboShareSDK.createWeiboAPI(getContext(), SocialConstants.SINA_APP_KEY);
       mWeiboShareAPI.registerApp();
        if (!mWeiboShareAPI.isWeiboAppSupportAPI()) {
...
}

When I using weibo API like this together with Fresco. The process will crash as following:

04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ BOARD : MSM8974
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ BOOTLOADER : unknown
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ BRAND : smartisan
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ CPU_ABI : armeabi-v7a
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ CPU_ABI2 : armeabi
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ DEVICE : msm8974sfo
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ DISPLAY : SANFRANCISCO dev-keys
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ FINGERPRINT : smartisan/msm8974sfo/msm8974sfo:4.4.2/SANFRANCISCO:user/dev-keys
04-28 14:34:36.443    3071-3843/com.lukouapp D/CrashHandler﹕ HARDWARE : qcom
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ HOST : hardcomp
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ ID : SANFRANCISCO
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ IS_DEBUGGABLE : false
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ MANUFACTURER : smartisan
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ MODEL : SM701
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ PRODUCT : msm8974sfo
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ RADIO : 2.0.1.c7-00022-M01046001
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ SERIAL : 1baad615
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ TAGS : dev-keys
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ TIME : 1409035961000
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ TYPE : user
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ UNKNOWN : unknown
04-28 14:34:36.453    3071-3843/com.lukouapp D/CrashHandler﹕ USER : jenkins

04-28 14:34:37.853    3071-3071/com.lukouapp I/ActivityManager﹕ Timeline: Activity_idle id: android.os.BinderProxy@423ebd40 time:357596010
04-28 14:34:39.453    3071-3843/com.lukouapp I/Process﹕ killProcess pid=3071
    java.lang.RuntimeException
            at android.os.Process.killProcess(Process.java:957)
            at com.lukouapp.crash.CrashHandler.uncaughtException(CrashHandler.java:90)
            at com.baidu.mobstat.r.uncaughtException(Unknown Source)
            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by DHuckaby** [comment]
Can you post more of the stacktrace?

**Comment by tyronen** [comment]
Are you doing anything combining Weibo with Fresco? eg using Fresco images to pass to Weibo? Can you also post a code snippet?

**Comment by binqiangsun** [comment]
ok， ignore this problem， the sdk need .so files。
