### ISSUE TITLE
setBitmapsConfig with Bitmap.Config.RGB_565 not working

### ISSUE THREAD

**Issue by JuHonggang** [facebook/fresco#2113]
I inited Fresco following code:

`
ImagePipelineConfig frescoConfig = ImagePipelineConfig.newBuilder(getApplicationContext())
                    .setBitmapsConfig(Bitmap.Config.RGB_565)
                    .setDownsampleEnabled(true)
                    .build();
            Fresco.initialize(getApplicationContext(), frescoConfig);
`

but memory not decreased, setBitmapsConfig seems not working.

Fresco version: v1.9

**Comment by erikandre** [comment]
Hi @JuHonggang,

Can you see any difference in image quality of the loaded images? In some cases it should be fairly easy to see the difference between RGB_565 and higher bit-depth images.

Are you using the Android studio memory profiler to measure memory usage?

**Comment by JuHonggang** [comment]
@erikandre The quality of images have not difference,  I loaded a image 748 * 561, use Android studio to measure memory usage, the memory size always is 1678591. Whether set RGB_565 or not.

my test phone screen resolution is 1920*1080.

**Comment by JuHonggang** [comment]
@erikandre 
You can close the issue, I found RGB_565 is invalid for png24. it is not fresco issue.

**Comment by oprisnik** [comment]
Thanks for letting us know!

**Comment by superlinxiao** [comment]
> @erikandre
> You can close the issue, I found RGB_565 is invalid for png24. it is not fresco issue.
I have the same problem as you，Could you share why RGB_565 is invalid for png24?

**Comment by superlinxiao** [comment]
> @erikandre
> You can close the issue, I found RGB_565 is invalid for png24. it is not fresco issue.

@Liberuman 
I have the same problem as you，Could you share why RGB_565 is invalid for png24? Thanks!
