### ISSUE TITLE
I found a problem where using pictures with RoundingParams and ScalingUtils.ScaleType.FIT_CENTER shows abnormalities

### ISSUE THREAD

**Issue by selfimprW** [facebook/fresco#2114]
I found a problem where using pictures with RoundingParams and ScalingUtils.ScaleType.FIT_END shows abnormalities。

**Comment by erikandre** [comment]
Hi @selfimprW ! 

Which rounding mode are you using (see here: http://frescolib.org/docs/rounded-corners-and-circles.html). The default rounding mode (BITMAP_ONLY) only works if the image covers the entire View. So if you are using FIT_END to position the image in one corner, then you can expect strange things to happen :)

**Comment by erikandre** [comment]
Closing due to lack of response. Please comment here with more details if you would like us to investigate further.
