### ISSUE TITLE
PooledByteBuffer.read() doesn't return int.

### ISSUE THREAD

**Issue by mariotaku** [facebook/fresco#2122]
### Description

According to its javadoc, `com.facebook.common.memory.PooledByteBuffer#read(int, byte[], int, int)` should return int for number of bytes copied. However this method returns void.

### Reproduction

Problem in source code.

### Solution

Change `com.facebook.common.memory.PooledByteBuffer#read(int, byte[], int, int)` to make it return int, and its implementation com.facebook.imagepipeline.memory.NativePooledByteBuffer.

### Additional Information

* Fresco version: 1.8.1
* Platform version: Not platform specific issue

**Comment by lambdapioneer** [comment]
That's right. Looks like a good starter-task as it is an easy to fix and test change (y)

Also feel free to send a PR yourself if this blocks you

**Comment by lambdapioneer** [comment]
Looks good :) importring
