### ISSUE TITLE
TooManyBitmapsException cause no display

### ISSUE THREAD

**Issue by lindow2009** [facebook/fresco#213]
how to clear memory cache or how to fix it?

**Comment by weilii** [comment]
Any follow up? It appears frequently.

**Comment by tyronen** [comment]
The general solution to this is to make use of a [MemoryTrimmableRegistry](http://frescolib.org/docs/caching.html#trimming-the-caches):

```java
class MemoryManager implements MemoryTrimmableRegistry {
  List<MemoryTrimmable> trimmables;
  void registerMemoryTrimmable(MemoryTrimmable trimmable) {
    trimmables.add(trimmable);
  }

 /// some code that gets called when memory is low, or when you get this exception
 for (MemoryTrimmable trimmable : trimmables) {
    trimmable.trim(/* choose appropriate type here; OnAppBackgrounded will clear the cache */);
}
```

**Comment by tyronen** [comment]
However, step back a bit. TooManyBitmapsException usually means you have too many bitmaps open. What is your application doing?

**Comment by plamenko** [comment]
What are the parent views/layouts of the DraweeViews?

**Comment by lindow2009** [comment]
just like pinterest,many images in one activity,so when activity jump,it may cause TooManyBitmapsException Especially in the mobile phone memory is too small.
parent views/layouts of the DraweeViews is normal LinearLayout and RelativeLayout

**Comment by lindow2009** [comment]
do you means trimmable clear the cache should app on background?but i think it's bad when user use it

**Comment by NNirvana** [comment]
I got this method in BitmapCunter:
public synchronized boolean increase(Bitmap bitmap) {
    final int bitmapSize = getBitmapSize(bitmap);
    if (mCount >= mMaxCount || mSize + bitmapSize > mMaxSize) {
      return false;
    }

    mCount++;
    mSize += bitmapSize;
    return true;
  }

if return false, you will  got a TooManyBitmapsExcetion.
value of mMaxCount is 384, value of mMaxSize is:
private static int getMaxSizeHardCap() {
    final int maxMemory = (int) Math.min(Runtime.getRuntime().maxMemory(), Integer.MAX_VALUE);
    if (maxMemory > 16 * MB) {
      return maxMemory / 4 * 3;
    } else {
      return maxMemory / 2;
    }
  }
so, maybe your bitmap is too big,

**Comment by weilii** [comment]
Actually, single image storage size is no more than 200k(#214), the bitmap is not big. It seems the cache size is overload when too many images between app's activity changing and device memory is low. So is there any method to clear the cache used by not showing views?

**Comment by IanChilds** [comment]
Are you using Drawee, or are you just using the image pipeline directly?

**Comment by lindow2009** [comment]
use SimpleDraweeView

**Comment by tyronen** [comment]
http://frescolib.org/docs/caching.html#clearing-the-cache

**Comment by narychen** [comment]
@tyronen  I tried to use imagePipeline.clearCaches(),  it doesn't work. Still got TooManyBitmapsException failure.
I checked the code and didn't see any code decrease the mCount and mSize in com.facebook.imagepipeline.memory.BitmapCounter.
Is there anything missed?

**Comment by tgithubc** [comment]
you've created 384 bitmaps
@see com.facebook.imagepipeline.memory.BitmapCounterProvider.MAX_BITMAP_COUNT
so in less than LOLLIPOP of the phone, the limited number of bitmaps in the Ashmem can not be more than 384
`@Override
    public MemoryCacheParams get() {
        int maxSize = (int) getMaxCacheSize();
        /**
         * fix fresco TooManyBitmapsException
         * @see com.facebook.imagepipeline.memory.BitmapCounterProvider.MAX_BITMAP_COUNT
         */
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            return new MemoryCacheParams(maxSize, 380, maxSize, Integer.MAX_VALUE, Integer.MAX_VALUE);
        } else {
            return new MemoryCacheParams(maxSize, Integer.MAX_VALUE, maxSize, Integer.MAX_VALUE, Integer.MAX_VALUE);
        }
    }`

**Comment by hovterteryan** [comment]
tgithubc you saved my day
