### ISSUE TITLE
Use of method blacklisted in Android P

### ISSUE THREAD

**Issue by legarspol** [facebook/fresco#2130]
### Description

Android P enforces that the developers don't use any internal/hidden apis of the Android SDK. This is to make sure that Android can change its internals without worrying about anyone using APIs they didn't intend to share.
Using such method make the app crash. (Didn't reproduced myself but this is definitly the intent in Android P)
See more on the [Android Documentation on Android P and app compatibility change](https://developer.android.com/preview/restrictions-non-sdk-interfaces)

Using the Veridex tool to check the use of blacklisted APIs in our app it raised that Fresco uses such internal API:
com.facebook.imagepipeline.cache.CountingLruMap#removeAll use the method apply() on the Predicate implementation located in com.android.internal.util.Predicate

### Solution

This class is deprecated (At least in Android-27) they recommend using java.util.function.Predicate instead which is available only from API 24 onward.

A solution would be to embed a copy of that interface in Fresco. 
Does it raise the concern of copying some code we didn't write into Fresco? I guess no-one can claim the monopoly of using Predicates.

### Additional Information
A quick search on that internal package seems to hint that this is the only class used in the internal package. 

* Fresco version: Personally using 1.8.1 but this is on master too.

**Comment by oprisnik** [comment]
Thanks for your report @legarspol. We are aware of this issue and looking into this.

**Comment by legarspol** [comment]
Do you have any idea of ETA?

**Comment by dementia2029** [comment]
@oprisnik Hi. When will be update for Android P? We really need to it to support new API in production.

**Comment by oprisnik** [comment]
@defHLT is looking into this.

**Comment by dementia2029** [comment]
@oprisnik Can you please make quick fix? We really need support of P.

**Comment by defHLT** [comment]
@dementia2029 fixed in 0a93ffc58585a1f7104ea7a5e0b93b6c1b16cdcc

**Comment by legarspol** [comment]
I see that commit on master mentioning the release of 1.10. What is the release process and when will it be published on maven?

**Comment by oprisnik** [comment]
We're preparing the release right now. Should be available soon.

**Comment by defHLT** [comment]
@legarspol @dementia2029 Unfortunately we are delaying the release for a week. If you need to

**Comment by defHLT** [comment]
@legarspol @dementia2029 Unfortunately, the release will be delayed for a week. If it's urgent I suggest adding source-code directly to your app. I'm also will look into ways of making releases more often or getting artifacts on demand.
