### ISSUE TITLE
Image url changed for api level 19

### ISSUE THREAD

**Issue by mayankkussh** [facebook/fresco#2133]
-- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

Image loading working fine on api version > 21, but the url changes to something like this on API Level 19
final_failed @ onFailure: failure: java.net.ConnectException: failed to connect to image.wedmegood.com/2600:9000:2046:d400:14:f6d7:4bc0:93a1 (port 443):

original url
https://image.wedmegood.com/resized/800X/uploads/real_wedding_banner_left/699/1527598117_minchu_42.jpg 

* Fresco version: 1.9.0
* Platform version: Api Level 19

**Comment by oprisnik** [comment]
I tried overriding to your URL in the Showcase app and get a `javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=...: Failure in SSL library, usually a protocol error`.

You need to properly set up OkHttp / whatever networking library you are using. A quick Stackoverflow search should help, like for example: https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han
