### ISSUE TITLE
Artifacts in the image after rounding

### ISSUE THREAD

**Issue by jaksab** [facebook/fresco#2137]
### Description

I get line (artifact) on foreground when I use app:roundWithOverlayColor.

![Bug image](http://stirka.dp.ua/images/photo_2018_bug.jpg)

![Bug image2](http://stirka.dp.ua/images/photo_2018_2.jpg)

### Reproduction

```
app:roundAsCircle="true"
app:roundWithOverlayColor="@color/color_white"
```

SimpleDraweeView is under ImageView in RelativeLayout (declared first), but line happens on top of ImageView. I use SimpleDraweeView in many cases of my project, I saw this bugs in other screens before rarely, but I didn't impose view on drawee.

I can't use other rounding method, because I have many lists with SimpleDraweeView including drawer fragment in project and on many devices I get OOM and not only in this project.

### Solution

After tap to screen all lines will hide, but why they are first?

### Additional Information

* Fresco version: 1.9.0
* Platform version: Android 8, Samsung S8+ and other newest Samsung devices I tested, don't happent on Nexus 4.

**Comment by oprisnik** [comment]
Can you reproduce this in the Showcase sample app, for example by modifying the simple example (https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeSimpleFragment.java)?

You can simply checkout the Git repo, open it with Android Studio and then run the Showcase sample.

**Comment by AlexCJW** [comment]
Can this be reproduced after you set android:hardwareAccelerated="false" ?

**Comment by jaksab** [comment]
@AlexCJW No, when I set android:hardwareAccelerated="false" in manifest, this problem is not present.

**Comment by jaksab** [comment]
@oprisnik Yes, I get this bug in different projects during the imposition views and only with rounding color method.

**Comment by jaksab** [comment]
@AlexCJW Elevation and translationZ didn't work

**Comment by jaksab** [comment]
I don't find solution yet. I hope this issue will resolved in future.

**Comment by jaksab** [comment]
In new Fresco version 1.10.0 this bug was disappeared, Thank you! @AlexCJW @oprisnik
