### ISSUE TITLE
How to deal with the "com.facebook.imagepipeline.bitmaps.TooManyBitmapsException"?

### ISSUE THREAD

**Issue by weilii** [facebook/fresco#214]
If the device mem is low,  the "TooManyBitmapsException" will come out and new images will not be displayed any more, especially on android 2.3.x devices.
Since the imageViews holding the bitmaps are not dealloced in this case, is there any solution to handle that exception? Many thanks!

**Comment by tyronen** [comment]
Follow in #213.
