### ISSUE TITLE
ArrayStoreException in ExtraFormZipSoSource.java

### ISSUE THREAD

**Issue by voiddog** [facebook/fresco#2141]
### Description

My online app found this problem and it happened 30 times per day

### Reproduction

I am sorry I can not reproduction this bug

### Additional Information

* Fresco version: 1.9.0
* Platform version: 8.0.0 or 8.1.0

### Crash Information
Stack details:

* java.lang.ArrayStoreException:com.facebook.soloader.ExtractFromZipSoSource$ZipDso cannot be stored in an array of type com.facebook.soloader.ExtractFromZipSoSource$ZipDso[]
* java.util.AbstractCollection.toArray(AbstractCollection.java:196)
* com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker.ensureDsos
* com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker.getDsoManifest
* ...

**Comment by erikandre** [comment]
Hi @voiddog 

Thanks for submitting the bug report. I checked the line where the exception occurs:

`ZipDso[] dsos = providedLibraries.values().toArray(new ZipDso[providedLibraries.size()]);`

and it looks like the exception should never be thrown here.

Do you have information about which devices this is happening on? (like specific modules names, manufacturer)

**Comment by voiddog** [comment]
I am very sorry, we can not reproduce this problem here, crash is online log. The reported operating system is `8.0` or `8.1.0`. The device contains *Xiaomi*, *Huawei*, and *OnePlus*.

I also read the source code and thought it was no problem, so I felt very surprised.

**Comment by voiddog** [comment]
I think it's a problem caused by our app plugin. I fix it by try catch and called system load

**Comment by oprisnik** [comment]
Thanks for letting us know.
