### ISSUE TITLE
Prefetching images in drawable folder

### ISSUE THREAD

**Issue by HenrySaba** [facebook/fresco#2144]
### Description

Hello,

I am trying to improve my app speed by prefetching PNG images that are in the drawable folder and keeping them in the cache for fast access whenever they're needed.

I tried using the prefetchToDiskCache method for ImagePipeline, but that method requires an ImageRequest for the first parameter, and ImageRequest requires either a Uri or a File.

I'm thinking of saving all my drawables as Files, and running code as such:

ImageRequest imageRequest = ImageRequest.fromFile(---file name here---);
Fresco.getImagePipeline().prefetchToDiskCache(imageRequest, null);

However, I feel that there is a more elegant way to do this without creating a File for every image in the drawable folder.

Please let me know if there is anything that could be done to do prefetch drawables more efficiently.

### Additional Information

* Fresco version: 1.9.0
* Platform version: 26

**Comment by HenrySaba** [comment]
Hi @erikandre 

My tests have actually shown Fresco to be approximately 3x faster than ImageViews when displaying images that have been loaded into cache already.

Here are my test results on just a few samples:
Loading an image from memory into ImageView: 370 ms
Loading an image from memory into SimpleDraweeView: 160 ms
Loading an image from cache into ImageView: 250 ms
Loading an image from cache into SimpleDraweeView: 80 ms

I might need to run some more tests on the ImageView (each recording had a huge variance), but I'm quite impressed with the consistent and fast results I've seen from using Fresco.

So what I'm trying to do now is get the 80 ms load time for images every time (including the first time the image is displayed). Please correct me if I'm wrong, but I believe that prefetching all images is the right way to this.

Is prefetching a drawable using Fresco not possible in a manner that is similar to prefetching an image from the Internet?

**Comment by oprisnik** [comment]
You actually want to prefetch the local assets to memory I suppose. Prefetching to disk will do nothing since local assets are already on the disk. Prefetching to bitmap cache using `imagePipeline.prefetchToBitmapCache(...)` should work.

**Comment by oprisnik** [comment]
Let us know if `prefetchToBitmapCache` doesn't work. It should solve your issues though I suppose.
