### ISSUE TITLE
what changed between v1.8 and v1.1 result in the method `Bitmap#isMutable` return false? 

### ISSUE THREAD

**Issue by qhyuan1992** [facebook/fresco#2146]
Following code:when downloading image with imagepipeline
```
CloseableBitmap closeableBitmap = (CloseableBitmap) imageReference.get();
Bitmap bitmap = closeableBitmap.getUnderlyingBitmap();
GLog.d(TAG, "isMutable:" + bitmap.isMutable());
```
why return false? in previous version here return true? what changed?

**Comment by qhyuan1992** [comment]
@oprisnik

**Comment by zmroczek** [comment]
Hi @qhyuan1992 

Thanks for your question. We don't really see anything that changed between versions 1.7.1 and 1.8 that could have caused that. Why do you need bitmap to be mutable at that point?

**Comment by qhyuan1992** [comment]
sorry, i means v1.8 and v1.1, last week, I update from v1.1 to 1.8
then there are some crash 
```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@321ad47
```

here are some code  like this when loading image finish
```
Bitmap newBitmap = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, false);
```
because we need a scale bitmap, here matrix may not be `null` or `Identity`, which may cause  same Bitmap returned from following code, WHERE  if is true!
```
public static Bitmap createBitmap(Bitmap source, int x, int y, int width, int height,
            Matrix m, boolean filter) {
        // check if we can just return our argument unchanged
        if (!source.isMutable() && x == 0 && y == 0 && width == source.getWidth() &&
                height == source.getHeight() && (m == null || m.isIdentity())) {
            return source;
        }
...
```
we did not hold the CloseableReference of origin bitmap, so it may be recycle after the method, so,  we think we are using a "new " bitmap but Actually the same with the origin ONE, which was recycled! CRASH happend!

**Comment by qhyuan1992** [comment]
I have found the reason
in ArtDecoder, there are following codes
```
protected CloseableReference<Bitmap> decodeStaticImageFromStream(
      InputStream inputStream, BitmapFactory.Options options, @Nullable Rect regionToDecode) {
    Preconditions.checkNotNull(inputStream);
    //...
    try {
      //...
      
      if (decodedBitmap == null) {
        decodedBitmap = BitmapFactory.decodeStream(inputStream, null, options);
      }
    } catch (IllegalArgumentException e) {
      mBitmapPool.release(bitmapToReuse);
      // This is thrown if the Bitmap options are invalid, so let's just try to decode the bitmap
      // as-is, which might be inefficient - but it works.
      try {
        // here may cause ..
       // at this point. it will throw IllegalArgumentException("Problem decoding into existing bitmap")
        Bitmap naiveDecodedBitmap = BitmapFactory.decodeStream(inputStream);
       //...
      } catch (IOException re) {
       //...
      }
    } catch (RuntimeException re) {
      // ...
    } finally {
      mDecodeBuffers.release(byteBuffer);
    }

    if (bitmapToReuse != decodedBitmap) {
      mBitmapPool.release(bitmapToReuse);
      decodedBitmap.recycle();
      throw new IllegalStateException();
    }
    return CloseableReference.of(decodedBitmap, mBitmapPool);
  }
```
here we try to use `RGB_565` to decode png(may be ARGB_8888), `Bitmap#decodeStream(InputStream is, Rect outPadding, Options opts)` may throws IllegalArgumentException("Problem decoding into existing bitmap")

then, in v1.8.1, the exception is caught, decode with this method `Bitmap decodeStream(InputStream is)`, so options is default value.  we got a bitmap which is ismutable and also ARGB_8888

in v1.1.0, the exception is not caught. so `retryOnFail` work, where uses  Bitmap.Config.ARGB_8888, and options is not null, when decoding
```
public CloseableReference<Bitmap> decodeFromEncodedImage(
      EncodedImage encodedImage,
      Bitmap.Config bitmapConfig) {
    final BitmapFactory.Options options = getDecodeOptionsForStream(encodedImage, bitmapConfig);
    boolean retryOnFail=options.inPreferredConfig != Bitmap.Config.ARGB_8888;
    try {
      return decodeStaticImageFromStream(encodedImage.getInputStream(), options);
    } catch (RuntimeException re) {
      if (retryOnFail) {
        return decodeFromEncodedImage(encodedImage, Bitmap.Config.ARGB_8888);
      }
      throw re;
    }
  }
```

i would  try to see why `Bitmap#decodeStream(InputStream is, Rect outPadding, Options opts)` may be null in this cases.

**Comment by qhyuan1992** [comment]
source :
EncodedImage: png/ARGB_8888
It will throw `IllegalArgumentException("Problem decoding into existing bitmap")`  when decode with `decodeFromEncodedImage` using the following option
options.inPreferredConfig = RGB_565
options.inBitmap = bitmapToReuse
options.inJustDecodeBounds = false
options.inDither = true
options.inPreferredConfig = bitmapConfig
options.inMutable = true

**Comment by oprisnik** [comment]
Thanks for investigating @qhyuan1992. That's good to know. We used to just throw the exception if that happens but decided that it's better to show something if possible instead of just crashing.

**Comment by qhyuan1992** [comment]
oh, i understand. the question also means what if i decode a png image with alhpa using RGB_565?
it could reuse bitmap in Fresco, so we allocate a size of `width * height * (size of RGB_565, also 2)`.
 in native , it really change to ARGB_8888 because of alpha, although we use a colortype of RGB_565. it need `width * height * (size of ARGB_8888, also 4)`. so the crash happend
```
BitmapFactory: bitmap marked for reuse (524288 bytes) can't fit new bitmap (1048576 bytes)
```

**Comment by qhyuan1992** [comment]
@oprisnik  The issue caused by different size of reused bitmap is similar to the issue [Android Oreo - can't load some PNG - BitmapFactory: bitmap marked for reuse (3944728 bytes) can't fit new bitmap (7889456 bytes)](url). A immutable bitmap returned  also result from the change for issue #2021. so I close the issue
