### ISSUE TITLE
Import eclipse, compile time problems

### ISSUE THREAD

**Issue by androidbyxj** [facebook/fresco#215]
04-28 11:28:55.120: E/AndroidRuntime(15167): FATAL EXCEPTION: OkHttp Dispatcher
04-28 11:28:55.120: E/AndroidRuntime(15167): Process: com.example.frescosample, PID: 15167
04-28 11:28:55.120: E/AndroidRuntime(15167): java.lang.NoClassDefFoundError: okio.Okio
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.internal.http.HttpConnection.<init>(HttpConnection.java:89)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.Connection.connect(Connection.java:161)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.Call.getResponse(Call.java:271)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.Call.access$100(Call.java:34)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-28 11:28:55.120: E/AndroidRuntime(15167):         at java.lang.Thread.run(Thread.java:841)

use the fresco+okhhtp

**Comment by tyronen** [comment]
Download the [okio jar](https://search.maven.org/remote_content?g=com.squareup.okio&a=okio&v=LATEST) and put it in the frescolib/imagepipeline-okhttp/libs directory. I'll fix future zip files to include these automatically.

**Comment by haogg** [comment]
@tyronen  Hey,bro. I think it will be a better way to provide a eclipse project with src  or  jars with src. How would you think?

**Comment by tyronen** [comment]
That wouldn't help this problem - you have to have the okio jars.

**Comment by tyronen** [comment]
Were you building with Eclipse or Gradle? If with Eclipse, there was a problem with the [zip file](http://frescolib.org/docs/index.html#eclipse-adt) which is now fixed.

**Comment by androidbyxj** [comment]
Thank you for your help
