### ISSUE TITLE
in samples ZoomableDraweeView I can't disable zoom via ZoomableController.setEnabled()

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#2150]
In samples ZoomableDraweeView I can't disable zoom via ZoomableController.setEnabled(false). This flag(`mZoomableController.isEnabled()`) only works when setting final image. Can I disable zoom afterwards of setting final image?

```
private void onFinalImageSet() {
        FLog.v(getLogTag(), "onFinalImageSet: view %x", this.hashCode());
        if (!mZoomableController.isEnabled()) {
            mZoomableController.setEnabled(true);
            updateZoomableControllerBounds();
        }
    }
```

**Comment by zmroczek** [comment]
Hi @rafaelekol 
Thanks for pointing that out, I added a flag for enabling/disabling the zooming in https://github.com/facebook/fresco/commit/fcbb2443486ab6b78e41cd1cc0c4513959f63291, this should solve your problem.
