### ISSUE TITLE
update website documentation about inlined ProGurad rules 

### ISSUE THREAD

**Issue by pju-intive** [facebook/fresco#2151]
### Description

In new version, 1.9.0 ProGurad rules are inlined and you don't need to use Gradle files.
On documentation website there is still info about gradle files
(http://frescolib.org/docs/shipping.html)

### Solution

update website about new version

**Comment by erikandre** [comment]
Thanks for submitting the bug @pju-intive, we'll update in the next version of the docs

**Comment by oprisnik** [comment]
@erikandre added this in 7f8f906b6dde77a5666e25eeed8b46ecf7fa5aeb
