### ISSUE TITLE
roundWithOverlayColor doesn't work on android api 21?

### ISSUE THREAD

**Issue by TongWeiLe** [facebook/fresco#2153]
only roundingBorderColor work on api 21, but roundWithOverlayColor doesn't work?

fresco version:1.2.102-5

**Comment by TongWeiLe** [comment]
It seems that less than 21 has failed.

**Comment by oprisnik** [comment]
Rounding with the overlay color works as expected in our Showcase app (https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeRoundedCornersFragment.java).

API 21:

![screenshot_1531737158](https://user-images.githubusercontent.com/2699634/42754372-27a21152-88ec-11e8-9b55-847afddd28bd.png)

Please fill out the issue template with steps how to reproduce in DraweeRoundedCornersFragment if you think this is a Fresco issue.

**Comment by TongWeiLe** [comment]
@oprisnik In Fragment this attributes work,In xml it's doesn't work 

<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/feed_template_big_image_id"
        android:layout_width="@dimen/template_p2_w"
        android:layout_height="@dimen/template_p2_h"
        fresco:roundWithOverlayColor="@color/feed_image_border_color"
        fresco:roundingBorderWidth="@dimen/image_border_width"/>

**Comment by oprisnik** [comment]
You need to supply a radius: `fresco:roundAsCircle="true"` or `fresco:roundedCornerRadius="5dp"`

**Comment by TongWeiLe** [comment]
why in higher than 21 ,I don't need to set radius and can see the roundingBorder,it 's strange

**Comment by TongWeiLe** [comment]
![qq20180717-0](https://user-images.githubusercontent.com/18482342/42794530-e4344efa-89b1-11e8-9ea1-c282598893a1.png)
I want the effect like this in lower than API 21,when add the radius 
<com.facebook.drawee.view.SimpleDraweeView
      android:layout_below="@id/button"
      android:id="@+id/simple"
      android:layout_centerHorizontal="true"
      fresco:roundedCornerRadius="5dp"
      android:layout_width="300px"
      android:layout_height="300px"
      fresco:roundingBorderWidth="1px"
      fresco:roundWithOverlayColor="@color/colorAccent"
      />

it's show like this
API 21:
![qq20180717-0](https://user-images.githubusercontent.com/18482342/42794652-92cbabf2-89b2-11e8-9a6b-683066ffe0d9.jpeg)

still can't see the borderline

**Comment by TongWeiLe** [comment]
when I just use the attributes fresco:roundingBorderColor
<com.facebook.drawee.view.SimpleDraweeView
      android:layout_below="@id/button"
      android:id="@+id/simple"
      android:layout_centerHorizontal="true"
      android:layout_width="match_parent"
      android:layout_height="600px"
      fresco:roundingBorderWidth="1px"
      fresco:roundingBorderColor="@color/colorPrimaryDark"
  />

For some reason,I Package the ForwardingDrawable and put our drawable(for placeholder image) in it's 
Construction method

```
Drawable drawable = new MyDrawable(placeholderImage);
simpleDraweeView.getHierarchy().setPlaceholderImage(drawable, ScalingUtils.ScaleType.FIT_XY);
```
part of MyDrawable code

```
public class MyDrawable extends ForwardingDrawable {
    private Paint mPaint;
    /** Matrix that is actually being used for drawing. */
    private Matrix mDrawMatrix;
    /** Temporary objects preallocated in advance to save future allocations. */
    private Matrix mTempMatrix = new Matrix();

    public BdPlaceHolderDrawable(Drawable drawable) {
        super(drawable);
        mPaint = new Paint();
        mPaint.setAntiAlias(true);
    }

    @Override
    public void draw(Canvas canvas) {
    if (mDrawMatrix != null) {
            int saveCount = canvas.save();
            canvas.clipRect(getBounds());
            canvas.concat(mDrawMatrix);
            super.draw(canvas);
            canvas.restoreToCount(saveCount);
        } else {
            // mDrawMatrix == null means our bounds match and we can take fast path.
            super.draw(canvas);
        }     
    }
}
```
because use ScalingUtils.ScaleType.FIT_XY(for some reason not use ScalingUtils.ScaleType.CENTER), move the image to the center  :canvas.concat(mDrawMatrix);

then the bug like this:
![bug](https://user-images.githubusercontent.com/18482342/42824598-bbb0eb62-8a12-11e8-831d-ff4557e5d16f.png)

add the border line in place holder image.


then I try the attributes fresco:roundWithOverlayColor in xml it's work 

```
<com.facebook.drawee.view.SimpleDraweeView
      android:layout_below="@id/button"
      android:id="@+id/simple"
      android:layout_centerHorizontal="true"
      android:layout_width="match_parent"
      android:layout_height="600px"
      fresco:roundingBorderWidth="1px"
      fresco:roundWithOverlayColor="@color/colorPrimaryDark"
      />
```
![qq20180717-4](https://user-images.githubusercontent.com/18482342/42825308-4d3c3c16-8a14-11e8-98a2-75e1212f725e.png)

and the border line on the simpleDraweeView

but in under api 21, this attributes not work, I don't know why, and don't search anything about limits in android api about this attributes


In api 21,I only set the attributes fresco:roundingBorderWidth="1px"

```
<com.facebook.drawee.view.SimpleDraweeView
      android:layout_below="@id/button"
      android:id="@+id/simple"
      android:layout_centerHorizontal="true"
      android:layout_width="match_parent"
      android:layout_height="600px"
      fresco:roundingBorderWidth="1px"
      fresco:roundWithOverlayColor="@color/colorPrimaryDark"/>
```
![qq20180717-3](https://user-images.githubusercontent.com/18482342/42823622-972f2bde-8a10-11e8-8426-03280911172d.png)

but when i set roundingBorderColor="1px" & fresco:roundWithOverlayColor

both these attributes

in api 21:
```
<com.facebook.drawee.view.SimpleDraweeView
      android:layout_below="@id/button"
      android:id="@+id/simple"
      android:layout_centerHorizontal="true"
      android:layout_width="match_parent"
      android:layout_height="600px"
      fresco:roundingBorderWidth="1px"
      fresco:roundingBorderColor="@color/colorPrimaryDark"
      fresco:roundWithOverlayColor="@color/colorPrimaryDark"/>
```
![qq20180717-4](https://user-images.githubusercontent.com/18482342/42823555-6883855a-8a10-11e8-9703-99c338a08ad7.png)

the border line show again,and on the simpleDraweeView
so where can i find these source code or doc about these attributes effect ,thanks @oprisnik
