### ISSUE TITLE
Make rounding for placeholder image optional

### ISSUE THREAD

**Issue by TongWeiLe** [facebook/fresco#2154]
I set the roundingBorderColor in xml file,and set simpleDraweeView.getHierarchy().setPlaceholderImage(drawable), I mean when the simpleDraweeView setImage failed, why the borderline still on the placeholderImage?

Code:
```
<com.facebook.drawee.view.SimpleDraweeView
      android:layout_below="@id/button"
      android:id="@+id/simple"

      android:layout_centerHorizontal="true"
      android:layout_width="300px"
      android:layout_height="300px"
      fresco:roundingBorderWidth="1px"
      fresco:roundingBorderColor="@color/colorAccent"
      />


ImageRequestBuilder dynamicImageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(
                    Uri.parse("http://xxx"));
                PipelineDraweeControllerBuilder
                    pipelineDraweeControllerBuilder = Fresco.newDraweeControllerBuilder().setAutoPlayAnimations(false)
                    .setImageRequest(dynamicImageRequestBuilder.build());

 simpleDraweeView.setController(pipelineDraweeControllerBuilder.build());
simpleDraweeView.getHierarchy().setPlaceholderImage(drawable);
```

when the url is right:
![qq20180717-1](https://user-images.githubusercontent.com/18482342/42814456-ddfded76-89f6-11e8-878a-a74abd33fb29.png)

but when the url is false:
![qq20180717-0](https://user-images.githubusercontent.com/18482342/42814500-0525ce6e-89f7-11e8-9f10-9aeb6c6d7e51.png)

the border line still in there, I mean the border line set on the SimpleDraweeView, when it's failed ,fresco:roundingBorderColor will no work

**Comment by oprisnik** [comment]
Our new Fresco Vito image components will support that, see ImageOptions.
