### ISSUE TITLE
What does the "wait if scrolling" mean?

### ISSUE THREAD

**Issue by xyc112233** [facebook/fresco#216]
There are comments similar to "Bitmap cache get -> wait if scrolling -> thread hand off -> multiplex -> bitmap cache" in the ProducerSequenceFactory.java.
But in the code, there is no waitIfScrollingProducer or some logic else.
So what do you mean by this?

If there is no where to listen scrolling events by now,
Is it possible to add that support?
I think the ideal strategy is:
1. load image from memory cache only when scrolling.
2. if scrolling stops and the image is not loaded, then load image from other producers.

**Comment by tyronen** [comment]
The comments are a leftover from earlier implementations. We originally didn't load images while scrolling, but discovered that Fresco is fast enough that users vastly prefer it when we do.
