### ISSUE TITLE
Get load image callback when parent is GONE in android 7.0

### ISSUE THREAD

**Issue by jave1987** [facebook/fresco#2161]
### Description

I write code like this.
![image](https://user-images.githubusercontent.com/4319006/42984959-d9ede7f4-8c21-11e8-8d91-154a382707f3.png)
when i call  parent.setVisibility(GONE).
In android 7.1.1 callback log is not print.
but in android 7.0, call back log is print.

* Fresco version: 1.10.0
* Platform version:android 7.0

**Comment by zmroczek** [comment]
Hi @jave1987 

Thanks for reporting the issue. I guess this might be connected to the bug in Android with restoring the visibility mentioned in https://github.com/facebook/fresco/issues/1445 but will need to double check.

**Comment by oprisnik** [comment]
I think we actually don't trigger the fetch when the image is not visible (to avoid doing unnecessary work). You can trigger a prefetch call to load the image.

**Comment by oprisnik** [comment]
As mentioned above, you have to prefetch the image since we don't load when it's set to gone. See https://frescolib.org/docs/prefetching.html for more information.
