### ISSUE TITLE
[feature request] Add image's origin info to DebugControllerOverlayDrawable

### ISSUE THREAD

**Issue by s1rius** [facebook/fresco#2162]
Why I need this:
I want debug some image(avatar/picture/...) show in ListView/RecyclerView, the LogCat info is to much. If the DebugControllerOverlayDrawable show this info will be helpful.
like this:
![aaaa](https://user-images.githubusercontent.com/3580391/43043553-9d1887e6-8dc8-11e8-8f39-727eeb8cea3b.png)

already done in this [commit](https://github.com/s1rius/fresco/commit/31a07d763396ae0cb14f3e32a94a503a0433b5eb)
Could we add this feature to Fresco?

**Comment by zmroczek** [comment]
Hi @s1rius 

Thanks for this suggestion! Please submit this as a pull request and we will take a closer look before adding it.

**Comment by s1rius** [comment]
@zmroczek please see #2163
