### ISSUE TITLE
PooledByteBuffer class could not be found

### ISSUE THREAD

**Issue by Iamrookie** [facebook/fresco#2167]
PooledByteBuffer、PooledByteBufferInputStream class could not be found 

import com.facebook.imagepipeline.memory.PooledByteBuffer;
import com.facebook.imagepipeline.memory.PooledByteBufferInputStream;

ext{
    buildToolsVersion = "27.0.3"
    compileSdkVersion = 26

    minSdkVersion = 16
    targetSdkVersion = 21

    supportVersion = "26.1.0"
}

How to solve  ?  online waiting

**Comment by erikandre** [comment]
Hi @Iamrookie 

What does your gradle config for the app look like? (where you include Fresco)
