### ISSUE TITLE
download a bitmap and translate to circle bitmap

### ISSUE THREAD

**Issue by DymanZy** [facebook/fresco#2168]
I just want to download a bitmap and translate to circle bitmap，how can i do it？

**Comment by erikandre** [comment]
Hi @DymanZy 

Please read the documentation for rounding: http://frescolib.org/docs/rounded-corners-and-circles.html

If you just want the bitmap without using a SimpleDraweeView then you can access the Fresco pipeline directly: http://frescolib.org/docs/using-image-pipeline.html

**Comment by DymanZy** [comment]
Thanks for your answer @erikandre 
Yes, you are right. I use ImagePipeline get the bitmap by BaseBitmapDataSubscriber success, but i still want to know how to translate a bitmap to circle bitmap by Fresco.

**Comment by erikandre** [comment]
Internally Fresco uses a couple of different approaches for rounding Bitmaps depending on what type of image it is, and what parameters were specified in the ImageRequest.

Here are two relevant classes:
https://github.com/facebook/fresco/blob/e5b19f5cebc547c140dfee6c25f62fb27e6f4443/imagepipeline/src/main/java/com/facebook/imagepipeline/nativecode/NativeRoundingFilter.java
https://github.com/facebook/fresco/blob/e5b19f5cebc547c140dfee6c25f62fb27e6f4443/imagepipeline/src/main/java/com/facebook/imagepipeline/postprocessors/RoundAsCirclePostprocessor.java
