### ISSUE TITLE
 # FrescoDecodeExecutor-8(1190)  java.lang.IllegalStateException  Failed to decode frame  

### ISSUE THREAD

**Issue by xiaoyao27610** [facebook/fresco#2170]
com.facebook.animated.webp.WebPFrame.void nativeRenderFrame(int,int,android.graphics.Bitmap)(Native Method)
--
2 com.facebook.animated.webp.WebPFrame.void renderFrame(int,int,android.graphics.Bitmap)(WebPFrame.java:48)
3 com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.void renderImageSupportsScaling(android.graphics.Canvas,com.facebook.imagepipeline.animated.base.AnimatedImageFrame)(AnimatedDrawableBackendImpl.java:214)
4 com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.void renderFrame(int,android.graphics.Canvas)(AnimatedDrawableBackendImpl.java:178)
5 com.facebook.imagepipeline.animated.impl.AnimatedImageCompositor.void renderFrame(int,android.graphics.Bitmap)(AnimatedImageCompositor.java:118)
6 com.facebook.fresco.animation.bitmap.wrapper.AnimatedDrawableBackendFrameRenderer.boolean renderFrame(int,android.graphics.Bitmap)(AnimatedDrawableBackendFrameRenderer.java:72)
7 com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.boolean renderFrameAndCache(int,com.facebook.common.references.CloseableReference,int)(DefaultBitmapFramePreparer.java:180)
8 com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.boolean prepareFrameAndCache(int,int)(DefaultBitmapFramePreparer.java:159)
9 com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.boolean prepareFrameAndCache(int,int)(DefaultBitmapFramePreparer.java:167)
10 com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.void run()(DefaultBitmapFramePreparer.java:110)
11 com.facebook.common.executors.ConstrainedExecutorService$Worker.void run()(ConstrainedExecutorService.java:175)
12 java.util.concurrent.Thr

**Comment by erikandre** [comment]
Hi @xiaoyao27610 

Please use the bug report template when reporting bugs, and include as much of the information listed there as possible. Thanks!
