### ISSUE TITLE
Program type already present: bolts.AndroidExecutors$1

### ISSUE THREAD

**Issue by NitinSharma639** [facebook/fresco#2175]
Hello Fresco Team

I am getting this error. How to fix this. I am not able to compile fresco library. 

Please check details
Program type already present: bolts.AndroidExecutors$1
Message{kind=ERROR, text=Program type already present: bolts.AndroidExecutors$1, sources=[Unknown source file], tool name=Optional.of(D8)}

Please help me.

**Comment by oprisnik** [comment]
Yeah, please exclude the bolts dependencies. That should fix the issue.
