### ISSUE TITLE
How the circular border is anti-aliased

### ISSUE THREAD

**Issue by Iamrookie** [facebook/fresco#2183]

**Comment by oprisnik** [comment]
Please fill out the issue template so that we can actually reproduce the issue.

**Comment by Iamrookie** [comment]
//边角形状和边框
        int shapeMode = config.getShapeMode();
        RoundingParams roundingParams = null;

        switch (shapeMode) {
            case ShapeMode.RECT:
                roundingParams = RoundingParams.fromCornersRadius(0);
                if (config.getBorderWidth() > 0) {
                    roundingParams.setBorder(config.getBorderColor(), config.getBorderWidth());
                }
                break;
            case ShapeMode.RECT_ROUND:
                roundingParams = RoundingParams.fromCornersRadius(config.getRectRoundRadius());
                if (config.getBorderWidth() > 0) {
                    roundingParams.setBorder(config.getBorderColor(), config.getBorderWidth());
                }
                if (config.isGif() && config.getRoundOverlayColor() > 0) {
                    roundingParams.setOverlayColor(config.getRoundOverlayColor());
                }
                break;
            case ShapeMode.OVAL:
                roundingParams = RoundingParams.asCircle();
                if (config.getBorderWidth() > 0) {
                    roundingParams.setBorder(config.getBorderColor(), config.getBorderWidth());
                }
                if (config.isGif() && config.getRoundOverlayColor() > 0) {
                    roundingParams.setOverlayColor(config.getRoundOverlayColor());
                }
                break;
        }

How to solve the sawtooth after setting the roundingParams.setBorder method ？
