### ISSUE TITLE
Android P dark greylist 

### ISSUE THREAD

**Issue by GlimmerYang** [facebook/fresco#2187]
Description
I have tested the compatibility of Android P and found that fresco has some methods appearing in the dark gray list. 

Reproduction
dark greylist Lcom/android/internal/util/Predicate;->apply(Ljava/lang/Object;)Z use(s):
       Lcom/facebook/imagepipeline/cache/CountingLruMap;->getMatchingEntries(Lcom/android/internal/util/Predicate;)Ljava/util/ArrayList;
       Lcom/facebook/imagepipeline/cache/CountingLruMap;->removeAll(Lcom/android/internal/util/Predicate;)Ljava/util/ArrayList;

Additional Information
Fresco version: 1.10.0

**Comment by GlimmerYang** [comment]
I have tested the compatibility of Android P and found that fresco has some methods appearing in the dark gray list. I hope it can be solved as soon as possible. Thank you so much.

**Comment by defHLT** [comment]
Hi! Thanks for reporting! However we already removed this. I think your check is triggered by com.facebook.common.internal.Predicate or you are testing against an old version.
