### ISSUE TITLE
DebugControllerOverlayDrawable, setOrigin

### ISSUE THREAD

**Issue by FoundMe** [facebook/fresco#2188]
I use okhttp:3.11.0 and fresco:1.10.0,
when i run an application with it, it does not compile due to en error in the file "PipelineDraweeController.java" (package com.facebook.drawee.backends.pipeline;)
the error is about an object type "DebugControllerOverlayDrawable" which ask to play the procedure setOrigin which it doesn't has. 

line 322 DebugControllerOverlayDrawable debugOverlay =
          (DebugControllerOverlayDrawable) getControllerOverlay();

line 334  debugOverlay.setOrigin(mDebugOverlayImageOriginListener.getImageOrigin());

**Comment by oprisnik** [comment]
I guess you are mixing different versions of Fresco for your Gradle dependencies? You always have to specify the same version for all Fresco imports.

I just created a new sample app and this works:
Gradle:
```
    implementation 'com.facebook.fresco:fresco:1.10.0'
    implementation 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0'
    implementation 'com.squareup.okhttp3:okhttp:3.11.0'
```

Kotlin:
```
val okHttpClient = OkHttpClient()
val config = OkHttpImagePipelineConfigFactory
    .newBuilder(applicationContext, okHttpClient)
    .build()
Fresco.initialize(applicationContext, config)
```

**Comment by FoundMe** [comment]
You are right involved more than one JAR file and yes i saw that i forgot to put part of the code from github.
but still not working cause i have other issues on the code.

thank you any way
