### ISSUE TITLE
Could not find class 'com.facebook.imagepipeline.producers.DiskCacheProducer$1', referenced from method 

### ISSUE THREAD

**Issue by agoodcoolman** [facebook/fresco#219]
04-29 11:19:02.129: E/dalvikvm(776): Could not find class 'com.facebook.imagepipeline.producers.DiskCacheProducer$1', referenced from method com.facebook.imagepipeline.producers.DiskCacheProducer.produceResults
04-29 11:19:02.129: W/dalvikvm(776): VFY: unable to resolve new-instance 1909 (Lcom/facebook/imagepipeline/producers/DiskCacheProducer$1;) in Lcom/facebook/imagepipeline/producers/DiskCacheProducer;
04-29 11:19:02.129: D/dalvikvm(776): VFY: replacing opcode 0x22 at 0x002b
04-29 11:19:02.139: I/dalvikvm(776): Failed resolving Lcom/facebook/imagepipeline/producers/DiskCacheProducer$1; interface 1463 'Lbolts/Continuation;'
04-29 11:19:02.139: W/dalvikvm(776): Link of class 'Lcom/facebook/imagepipeline/producers/DiskCacheProducer$1;' failed
04-29 11:19:02.139: D/dalvikvm(776): DexOpt: unable to opt direct call 0x3af4 at 0x30 in Lcom/facebook/imagepipeline/producers/DiskCacheProducer;.produceResults
04-29 11:19:02.229: W/dalvikvm(776): threadid=11: thread exiting with uncaught exception (group=0x40a13300)
04-29 11:19:02.259: D/gralloc_goldfish(776): Emulator without GPU emulation detected.
04-29 11:19:02.269: D/dalvikvm(776): GC_CONCURRENT freed 263K, 4% free 8205K/8519K, paused 16ms+4ms, total 133ms
04-29 11:19:02.269: D/dalvikvm(776): WAIT_FOR_CONCURRENT_GC blocked 18ms
04-29 11:19:02.279: E/AndroidRuntime(776): FATAL EXCEPTION: pool-2-thread-1
04-29 11:19:02.279: E/AndroidRuntime(776): java.lang.NoClassDefFoundError: com.facebook.imagepipeline.producers.DiskCacheProducer$1
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.DiskCacheProducer.produceResults(DiskCacheProducer.java:76)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MemoryCacheProducer.produceResults(MemoryCacheProducer.java:114)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:362)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:121)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:85)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:41)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.ImageTransformProducer.produceResults(ImageTransformProducer.java:53)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.RemoveImageTransformMetaDataProducer.produceResults(RemoveImageTransformMetaDataProducer.java:37)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.java:88)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MemoryCacheProducer.produceResults(MemoryCacheProducer.java:114)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:362)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:121)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:85)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(ThreadHandoffProducer.java:45)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
04-29 11:19:02.279: E/AndroidRuntime(776): 	at java.lang.Thread.run(Thread.java:856)

import the project in eclipse, according to the document 
https://github.com/facebook/fresco/tree/gh-pages/docs/00-getting-started.md

just four steps,run it, i get the problem.i check it again,but i can't find any questions.

**Comment by tyronen** [comment]
There was an error in the uploaded Eclipse zip file. This has been fixed.

Can you try again using the [instructions here](http://frescolib.org/docs/index.html#eclipse-adt)?

**Comment by agoodcoolman** [comment]
@tyronen thank you,it's working,
