### ISSUE TITLE
heic header contains msf1

### ISSUE THREAD

**Issue by RICEYRQ** [facebook/fresco#2191]
I have found a problem.
There are some pictures of heic that have headers with "msf1".
But now this case is not supported.
Also, I can use java reflection to change the static array of heif headers.
However, I still hope you can solve it in your project.
Finally, thank's for your project to help us and hope this project better and better.

**Comment by lambdapioneer** [comment]
The `msf1` would indicate a sequence image of no specified type (http://nokiatech.github.io/heif/technical.html). I'm not sure if Android can consume this easily - but if it does then we're happy to accept a pull-request with the changes and appropriate testing (should include at least an example of such a file).

**Comment by lambdapioneer** [comment]
Solved with PR #2198 :)
