### ISSUE TITLE
Placeholder image scale type not working

### ISSUE THREAD

**Issue by SethFeng** [facebook/fresco#2193]
### Description

In layout xml file, set SimpleDraweeView's placeholder scale type but not set placeholder image. The scale type not working when set placeholder image in Java code.

### Reproduction
Layout xml:
```xml
<com.facebook.drawee.view.SimpleDraweeView
      android:id="@+id/drawee_view"
      android:layout_width="@dimen/drawee_width_medium"
      android:layout_height="300dp"
      fresco:placeholderImageScaleType="centerCrop"
      android:layout_marginTop="@dimen/margin_large"
      />
```
Java code:
```Java
draweeView.getHierarchy().setPlaceholderImage(R.drawable.logo);
```

### Additional Information

* Fresco version: 1.10.0
* Platform version: Android 7.1.1, Nexus 6

**Comment by erikandre** [comment]
Hi @SethFeng 

Instead of calling `setPlaceholderImage(int resourceId)` please use `setPlaceholderImage(int resourceId, ScalingUtils.ScaleType scaleType)` and specify the required placeholder scale type.

**Comment by SethFeng** [comment]
It does work, but that situation is out of my expect. Android's original attributes always works.
Layout xml:
```xml
<ImageView
      android:id="@+id/image_view"
      android:layout_width="@dimen/drawee_width_medium"
      android:layout_height="300dp"
      scaleType="centerCrop"
      android:layout_marginTop="@dimen/margin_large"
      />
```
Java code:
```java
imageView.setImageResource(R.drawable.logo);
```

**Comment by DuanYafei** [comment]
> Hi @SethFeng
> 
> Instead of calling `setPlaceholderImage(int resourceId)` please use `setPlaceholderImage(int resourceId, ScalingUtils.ScaleType scaleType)` and specify the required placeholder scale type.

I used this and met the crash below
https://github.com/facebook/fresco/issues/2241

**Comment by lynn-chen-3000** [comment]
I use fresco of version 2.2.0.

Source code
> 
        imageView.hierarchy.apply {
            setPlaceholderImage(R.drawable.default, ScalingUtils.ScaleType.FIT_XY)
            setFailureImage(R.drawable.default, ScalingUtils.ScaleType.FIT_XY)
        }

and Xml
> 
        fresco:failureImage="@drawable/default"
        fresco:failureImageScaleType="fitXY"
        fresco:placeholderImage="@drawable/default"
        fresco:placeholderImageScaleType="fitXY"

Both do work.
