### ISSUE TITLE
Later API methods being called

### ISSUE THREAD

**Issue by qianlvable** [facebook/fresco#220]
I just try the simplest usage:

      <com.facebook.drawee.view.SimpleDraweeView
         android:id="@+id/cover_img"
         android:layout_width="match_parent"
         android:layout_height="wrap_content"
         fresco:placeholderImage="@drawable/cover"/>

    SimpleDraweeView draweeView = (SimpleDraweeView)findViewById(R.id.cover_img);
    draweeView.setImageURI(Uri.parse("http://fresco-cn.org/static/fresco-logo.png"));

And logcat show this info below and image not show:

    04-29 13:01:06.907  21688-21688/com.lvable.zhihudigest I/dalvikvm﹕ Could not find method android.graphics.Bitmap.getAllocationByteCount, referenced from method com.facebook.imagepipeline.animated.util.AnimatedDrawableUtil.getSizeOfBitmap
    04-29 13:01:06.907  21688-21688/com.lvable.zhihudigest I/dalvikvm﹕ Could not find method android.graphics.Bitmap.getAllocationByteCount, referenced from method com.facebook.imagepipeline.memory.BitmapPool.getBucketedSizeForValue
    04-29 13:01:07.035  21688-21701/com.lvable.zhihudigest I/dalvikvm﹕ Could not find method android.graphics.Bitmap.getAllocationByteCount, referenced from method com.facebook.imagepipeline.nativecode.Bitmaps.reconfigureBitmap

**Comment by tyronen** [comment]
What version of Android are you running? What versions of Android do you support in your manifest file?

**Comment by qianlvable** [comment]
Test on api 16.And my build file as follow:
   compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.lvable.zhihudigest"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }

**Comment by tyronen** [comment]
What do you have for minSdk and targetSdk in your `AndroidManifest.xml` file?

**Comment by qianlvable** [comment]
Do the minSdk and targetSdk not support in build.gradle?If then the minSDK will be 14,targetSDK will be 21

**Comment by tyronen** [comment]
Ok I now think your logcat messages have nothing to do with it. Actually the problem is that you are using layout_height wrap_content. [Fresco does not support this type](http://frescolib.org/docs/using-drawees-xml.html#wrap-content).
