### ISSUE TITLE
libgifimage crashed on Android 5.x ~ 6.x

### ISSUE THREAD

**Issue by wangjing53406** [facebook/fresco#2202]
get crash from fabric

* Fresco version: [1.10.0]
* Platform version: [os version: 5.0 ~ 6.0, brand: oppo、huawei、vivo、xiaomi and so on]

Crashed: Thread
0  libart.so                      0x41f95f08 (Missing)
1  libgifimage.so                 0x8d694032 (Missing)
2  system@framework@boot.oat      0x739ab211 (Missing)
3  libunwind.so                   0x412ccbb7 (Missing)
4  libc.so                        0x40158d83 (Missing)
5  system@framework@boot.oat      0x739ab211 (Missing)
6  system@framework@boot.oat      0x739ab211 (Missing)
7  libunwind.so                   0x412cbc25 (Missing)
8  libbacktrace_libc++.so         0x4203d621 (Missing)
9  system@framework@boot.oat      0x739ab211 (Missing)
10 libc.so                        0x40167f3b (Missing)
11 (Missing)                      0x8008000f (Missing)
12 (Missing)                      0x737de74e (Missing)
13 (Missing)                      0x737de755 (Missing)
14 (Missing)                      0x7118edf6 (Missing)
15 libc.so                        0x40169a60 (Missing)
16 (Missing)                      0x7ffffffd (Missing)
17 libc.so                        0x4014175b (Missing)
18 libutils.so                    0x401d1121 (Missing)
19 (Missing)                      0x7173ffce (Missing)
20 libart.so                      0x41df09bf (Missing)
21 libart.so                      0x41fbfa31 (Missing)
22 (Missing)                      0x7173ffce (Missing)
23 (Missing)                      0x136c511e (Missing)
24 (Missing)                      0x131a83be (Missing)
25 (Missing)                      0x7173ffce (Missing)
26 libart.so                      0x41fc0255 (Missing)
27 (Missing)                      0x141b575e (Missing)
28 (Missing)                      0x70fe4136 (Missing)
29 (Missing)                      0x141b575e (Missing)
30 (Missing)                      0x7119c626 (Missing)
31 (Missing)                      0x141b575e (Missing)
32 libart.so                      0x41ffa74e (Missing)
33 libart.so                      0x41ffa74e (Missing)
34 libart.so                      0x41ffa74e (Missing)
35 libart.so                      0x41ff9dba (Missing)
36 libart.so                      0x41ff9d92 (Missing)
37 libart.so                      0x41ffa74e (Missing)
38 libart.so                      0x41ff9ca2 (Missing)
39 libart.so                      0x41ff9cb6 (Missing)
40 (Missing)                      0x12c02bde (Missing)
41 (Missing)                      0x12c9254e (Missing)
42 libutils.so                    0x401d134b (Missing)
43 (Missing)                      0x12c9f73e (Missing)
44 (Missing)                      0x7118edf6 (Missing)
45 libandroid_runtime.so          0x4009cf4f (Missing)
46 (Missing)                      0x12c9254e (Missing)
47 system@framework@boot.oat      0x739ab213 (Missing)
48 system@framework@boot.oat      0x738fdc87 (Missing)
49 (Missing)                      0x718e77ee (Missing)
50 (Missing)                      0x71866066 (Missing)
51 (Missing)                      0x12c9254e (Missing)
52 (Missing)                      0x12c9f73e (Missing)
53 (Missing)                      0x7118edf6 (Missing)
54 (Missing)                      0x12c02bde (Missing)
55 (Missing)                      0x12c9254e (Missing)
56 system@framework@boot.oat      0x745b9a57 (Missing)
57 (Missing)                      0x7118edf6 (Missing)
58 (Missing)                      0x141b577e (Missing)
59 (Missing)                      0x12c02bde (Missing)
60 libart.so                      0x41db722b (Missing)
61 (Missing)                      0x7ffffffd (Missing)
62 (Missing)                      0x710cfe16 (Missing)
63 (Missing)                      0x141b577e (Missing)
64 (Missing)                      0x12c02bde (Missing)

**Comment by lambdapioneer** [comment]
Hey @wangjing53406 is there a chance that you can reproduce this issue locally and provide us with any information about the image and the logcat?

**Comment by wangjing53406** [comment]
[com.culiu.chuchutui_issue_1663_crash_5b9653c00385000133d9184475ed91f4_DNE_0_v2.txt](https://github.com/facebook/fresco/files/2366425/com.culiu.chuchutui_issue_1663_crash_5b9653c00385000133d9184475ed91f4_DNE_0_v2.txt)

**Comment by oprisnik** [comment]
As @lambdapioneer we would need more information on how to reproduce the issue. Your crash log doesn't give any more details.

**Comment by wangjing53406** [comment]
@oprisnik @lambdapioneer Thanks a lot. I can't reproduce this issue locally. I just see it on fabric.
