### ISSUE TITLE
how should use fresco with bytes

### ISSUE THREAD

**Issue by rRemix** [facebook/fresco#2204]
```
        MediaMetadataRetriever retriever = null;
        try {
            retriever = new MediaMetadataRetriever();
            retriever.setDataSource(songPath);
            byte[] bytes = retriever.getEmbeddedPicture();
            //xxxxx
        } catch (Exception e){
            e.printStackTrace();
        }
```
Maybe this is a strange problem,but i have some code like this,and how should i use fresco next?

**Comment by zmroczek** [comment]
Hi @rRemix 

If I understand correctly, are you trying to retrieve the embedded cover art from an audio file? If so, currently we don't support it but you can take a look on how @pablode did this in his fork: https://github.com/pablode/fresco/commit/655f5ab8b83971ba048df19c1c176d1c76a435bf#diff-66198584a78198d71a1ea48bf1ec542c

**Comment by rRemix** [comment]
@zmroczek Thanks,that is useful
