### ISSUE TITLE
AnimatedDrawable2 onAnimationStop not work

### ISSUE THREAD

**Issue by alonedmer** [facebook/fresco#2205]
I just use DraweeController to play gif files in my project of drawable resources like this

![image](https://user-images.githubusercontent.com/14309813/45289906-dad87580-b520-11e8-8d86-0ffa317783b7.png)

but only onAnimationStart method callback, onAnimationStop is never, I am not sure if this is a bug or 
something wrong in my code

* Fresco version: fresco v1.10.0  animated-gif v1.10.0
* Platform version: Android 6.0.1
* Device: xiaomi 4

**Comment by zmroczek** [comment]
Hi @alonedmer 

It seems to be a duplicate of https://github.com/facebook/fresco/issues/2081

Since we were not able to reproduce it properly before, could you please provide the file and a sample app or exact steps to reproduce it in the showcase app?

**Comment by alonedmer** [comment]
Hi @zmroczek 
I am sorry, I write a demo, it seems to be the problem of gif file, but I do not know why, in the demo project, demo1.gif is normal, but demo2.gif can not callback, I have upload my demo project

[GifDemo.zip](https://github.com/facebook/fresco/files/2369236/GifDemo.zip)

**Comment by oprisnik** [comment]
I just tested with your sample app on an API23 (Marshmallow) emulator:
demo2:
```
09-20 14:29:30.762 3999-3999/com.xiaw.gifdemo E/MainActivity: onAnimationStart
09-20 14:29:31.846 3999-3999/com.xiaw.gifdemo E/MainActivity: onAnimationStop
```

demo1:
```
09-20 14:30:26.138 4244-4244/com.xiaw.gifdemo E/MainActivity: onAnimationStart
09-20 14:30:29.039 4244-4244/com.xiaw.gifdemo E/MainActivity: onAnimationStop
```

Seems that everything works fine for me.

The callback is triggered in `draw()` for AnimatedDrawable2, so I don't see how this could be a device-specific issue. https://github.com/facebook/fresco/blob/master/animated-drawable/src/main/java/com/facebook/fresco/animation/drawable/AnimatedDrawable2.java#L197

Does this also reproduce on an emulator for you or only on that specific device?
