### ISSUE TITLE
BitmapFactory: bitmap marked for reuse (1408000 bytes) can't fit new bitmap (2816000 bytes)

### ISSUE THREAD

**Issue by WangZongBao** [facebook/fresco#2209]
In my android 8.1.0, I had the following error:

BitmapFactory: bitmap marked for reuse (1408000 bytes) can't fit new bitmap (2816000 bytes)

This problem seems to have existed before. I introduced the latest com. facebook. fresco: fresco: 1.7. Ask for help.

**Comment by defHLT** [comment]
Does it happen randomly or every time with the same image? If it's the latter, a sample image would be helpful.

**Comment by WangZongBao** [comment]
> 是随机发生还是每次使用相同的图像？如果是后者，则样本图像会有所帮助。

It happens every time.

**Comment by WangZongBao** [comment]
I found a description of the problem.
https://blog.csdn.net/qq_16624353/article/details/79124195

After I update the SDK problem, this is sometimes good and sometimes bad.
