### ISSUE TITLE
individual dependencies to add

### ISSUE THREAD

**Issue by pavn34** [facebook/fresco#221]
Hi Team,
              Presently i am using only "<com.facebook.drawee.view.SimpleDraweeView" in my project.
Do i need to add "com.facebook.fresco:fresco:0.4.0" ? in build.gradle
or "com.facebook.fresco:drawee:0.4.0" is enough ? Please help me...because after adding this fresco lib(for image loading) and volley lib(for network request), my apk size jumped from 6.7MB to 9.3MB ;(

**Comment by tyronen** [comment]
You need to add either fresco or drawee-volley. We recommend fresco - drawee-volley doesn't use the image pipeline but Volley image loader instead to power drawees.

We are aware of the apk size issue and are working on it.
