### ISSUE TITLE
how to listen fresco decode failed

### ISSUE THREAD

**Issue by jokermonn** [facebook/fresco#2211]
### Description
How do I know if fresco is successful in decoding images？I have a need to monitor the state of image decoding, but fresco doesn't provide a listener for developer. My practice is to use `setRequestListeners()` to register a global listener to know whether a picture shows success, and analyze throwable in `onRequestFailure()` to judge whether is a decode exception：

1. throwable instanceof DecodeException
2. analyze exception message by `Throwable#getStackTrace()`, and if it's caused by `ArtDecoder#decodeStaticImageFromStream`

The second judgment looks a bit silly...

### Solution
could fresco provide a listener? or there is a better way to solve my problem?

**Comment by oprisnik** [comment]
Yes, monitoring and checking if the throwable is a DecodeException is the way to go, see https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/DecodeProducer.java#L279
