### ISSUE TITLE
Can not save cache in SDcard

### ISSUE THREAD

**Issue by Christain** [facebook/fresco#222]
DiskCacheConfig mainDiskCacheConfig = DiskCacheConfig.newBuilder()
                .setBaseDirectoryPath(new File(Constant.IMAGE_CACHE_DIR_PATH))
                .setBaseDirectoryName("cache")
                .setMaxCacheSize(20 * 1024)
                .setMaxCacheSizeOnLowDiskSpace(10 * 1024)
                .setMaxCacheSizeOnVeryLowDiskSpace(5 * 1024)
                .setVersion(1)
                .build();
I am write this in my Application,when I use listview has SimpleDraweeView, but when I move the listview  will download the picture everytime. I see my SDcard have no cache file, every file is null.

**Comment by GuyHamawi** [comment]
Hi Christain,

I think i can use your help... please contact me at guy.hamawi@gmail.com

Thanks
