### ISSUE TITLE
java.io.IOException  Resource deadlock would occur

### ISSUE THREAD

**Issue by fcscr126608** [facebook/fresco#2223]
I used fresco 1.10.0  Android 7.0,level 24   armeabi-v7a   samsung SM C5000

![image](https://user-images.githubusercontent.com/35981460/46850585-0b187a00-ce27-11e8-8472-78bf03fbab81.png)

How fix this bug? Thank you!!!

**Comment by zmroczek** [comment]
Seems to be a duplicate of #2111 - are you also using Replugin mentioned there? Are you able to reproduce this issue in the showcase app?
