### ISSUE TITLE
Question: is it possible to get frames of animated GIF/WEBP, one after another?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [facebook/fresco#2229]
Not always we have a View to show content of animated GIF/WEBP (example: live wallpaper). For this, it's best to have a bit more manual control of the decoding pipeline.

Is there a way to get one frame after another (into a Bitmap instance), while knowing how much time to wait between them?

I've looked at the documentation and I couldn't find it:
https://frescolib.org/docs/animations.html

**Comment by oprisnik** [comment]
Hi! Yes, you can manually request the image, which gives you a `CloseableImage`. You can then create a bitmap animation backend according to what we do internally: https://github.com/facebook/fresco/blob/5d419bcc450bd0e4fbc27546e94ac55ad20a3e60/animated-base/src/main/java/com/facebook/fresco/animation/factory/ExperimentalBitmapAnimationDrawableFactory.java#L90

You can modify this to do whatever you need. If you need to render into an existing bitmap, you can for example use this helper class: https://github.com/facebook/fresco/blob/5d419bcc450bd0e4fbc27546e94ac55ad20a3e60/animated-base/src/main/java/com/facebook/fresco/animation/bitmap/wrapper/AnimatedDrawableBackendFrameRenderer.java

**Comment by AndroidDeveloperLB** [comment]
@oprisnik I'm actually a newb with this library. I wanted to try out the samples, but it failed to import and run them. Wrote about this [here](https://github.com/facebook/fresco/issues/2230) . 

I don't understand what you mean by those instructions. To me it seems that the API doesn't exist for this question, and that you tell me to copy code of Fresco and then modify it. Is it true? Do you have a working sample for this? Just the bare minimal of it? Or even a snippet?

**Comment by oprisnik** [comment]
Yes, this functionality doesn't exist out of the box. However, we do internally glue classes together that you can use to emulate that behavior. Manually request the `CloseableImage` (see https://frescolib.org/docs/using-image-pipeline.html) (which is the decoded GIF) and then use the raw GIF data in `CloseableAnimatedImage` however you like. I've listed some helper classes that make things easier and that we use internally to render GIFs.

**Comment by AndroidDeveloperLB** [comment]
Can you please demonstrate how to do it?
I think it could actually be useful for all and not just me, no?

**Comment by oprisnik** [comment]
A really naive solution for this (that's not too efficient) would be something like this:

```kotlin
    fun loadImage(uri: String, frameNumber: Int) {
        val result = Fresco.getImagePipeline().fetchDecodedImage(ImageRequest.fromUri(uri), "animatedImage")
        result.subscribe(object : BaseDataSubscriber<CloseableReference<CloseableImage>>() {
            override fun onNewResultImpl(dataSource: DataSource<CloseableReference<CloseableImage>>) {
                if (dataSource.hasResult()) {
                    val ref = dataSource.result
                    if (ref != null) {
                        try {
                            // do something with the result
                            val gif = ref.get()
                            when (gif) {
                                is CloseableAnimatedImage -> handleAnimatedImage(gif, frameNumber)
                            }
                        } finally {
                            CloseableReference.closeSafely(ref)
                        }
                    }
                }
            }

            override fun onFailureImpl(dataSource: DataSource<CloseableReference<CloseableImage>>) {
                TODO("not implemented")
            }
        }, UiThreadImmediateExecutorService.getInstance())
    }

    fun handleAnimatedImage(animatedImage: CloseableAnimatedImage, frameNumber: Int) {
        val frameCache = NoOpCache()
        val backend = AnimatedDrawableBackendImpl(
            AnimatedDrawableUtil(),
            animatedImage.imageResult,
            Rect(0, 0, animatedImage.width, animatedImage.height)
        )
        val renderer = AnimatedDrawableBackendFrameRenderer(frameCache, backend)

        val bitmap = Bitmap.createBitmap(animatedImage.width, animatedImage.height, Bitmap.Config.ARGB_8888)
        renderer.renderFrame(frameNumber, bitmap)

        yourImageView.setImageBitmap(bitmap)
    }
```

**Comment by AndroidDeveloperLB** [comment]
Where is the part of "not too efficient" ? Because you keep creating more and more bitmaps, instead of using the previous one (or 2 : one for UI and one for decoding) ?

And what do you mean "hold on to the image"?

**Comment by oprisnik** [comment]
Yes, no caching, no frame preparation ahead of time on background threads, not using PlatformBitmapFactory.
"Hold on to the image" means keep the CloseableReference<CloseableImage> around until you don't need it any more as described in my 2 links.

**Comment by AndroidDeveloperLB** [comment]
@oprisnik Is there a better way, then?

**Comment by oprisnik** [comment]
Yes, use AnimatedDrawable2 / a DraweeView or manually do what that one does, see my comment above.

**Comment by AndroidDeveloperLB** [comment]
So I should copy what's in the AnimatedDrawable2 into a new class that provides Bitmap instances ?
