### ISSUE TITLE
Bug: Unable to import project and run samples

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [facebook/fresco#2230]
I tried to clone the project. Without updating anything, I got this error:

![image](https://user-images.githubusercontent.com/5357526/47620611-a6327480-daf4-11e8-9063-ed7ac9323c72.png)

It writes the same error for each of the samples.

So I tried to update all that's needed (because it complained otherwise), but it failed to be built. It keeps showing me this error now:

`Duplicate key BuildableArtifactImpl (file collection)`

![image](https://user-images.githubusercontent.com/5357526/47620487-45ef0300-daf3-11e8-9165-27a92ae340f2.png)

**Comment by oprisnik** [comment]
Your second screenshot shows local changes. Can you revert those and try again? What NDK version are you using? android-ndk-r15c works for me.

**Comment by AndroidDeveloperLB** [comment]
@oprisnik As I wrote "I tried to update all that's needed". This means I modified the project to have the latest of a lot of things I know about. I changed of sdk version ,build tools, support library, gradle plugin version ...

Attached here the global gradle file.

[gradle.zip](https://github.com/facebook/fresco/files/2530658/gradle.zip)

About NDK version, I have what the IDE offers: 18.1.5063045 .

I did it again, and still got the same error. Since I can't upload here the whole project, here's an alternative :

https://ufile.io/v6zub

**Comment by oprisnik** [comment]
I guess that one of your changes causes Fresco not to build properly. Feel free to submit a pull request to update dependencies once you figured out what's going wrong. Otherwise, please use the build setup that we currently use.

**Comment by AndroidDeveloperLB** [comment]
@oprisnik As I wrote, both options didn't work for me.
Not changing anything (it was my first attempt, shown on the first screenshot), and changing a lot.
Both failed to build. 
Why make yet another issue, if it's the exact same one?
The issue: I can't clone and build the project, no matter if I leave it unchanged or not.

**Comment by oprisnik** [comment]
Yeah, the issue is that you're using NDK 18. Please use an older one (e.g. android-ndk-r15c). You can just set that up in your local.properties file. See https://frescolib.org/docs/building-from-source.html

For 18, you'd need to change Fresco's native code, for example as described here:
https://stackoverflow.com/questions/52475177/android-ndk-app-stl-gnustl-shared-is-no-longer-supported
