### ISSUE TITLE
Question: Does fresco intend to support monitor in the future

### ISSUE THREAD

**Issue by jokermonn** [facebook/fresco#2231]
### Description

Does fresco intend to support monitor in the future？It seems that monitoring image decoding time, network request time (etc..) is a very broad demand，and now we could custom NetworkFetcher(like [OkHttpNetworkFetcher](https://github.com/facebook/fresco/blob/695b161427d1cbee124e60a4219a5aa208f0b5f9/imagepipeline-backends/imagepipeline-okhttp/src/main/java/com/facebook/imagepipeline/backends/okhttp/OkHttpNetworkFetcher.java)) to listen network request time，but we could not listen image decoding time, or cache hit time...

so is there any way to address these issues now or will fresco support monitoring in the future?

**Comment by oprisnik** [comment]
You can already get this data using an ImagePerfDataListener: https://github.com/facebook/fresco/blob/master/drawee-backends/drawee-pipeline/src/main/java/com/facebook/drawee/backends/pipeline/info/ImagePerfDataListener.java

Simple example how to use it here: https://github.com/facebook/fresco/blob/master/samples/kotlin/src/main/kotlin/com/facebook/samples/kotlin/ImageAdapter.kt#L45

**Comment by jokermonn** [comment]
thx
