### ISSUE TITLE
[Feature Request] Drop Shadow/Colored Drop Shadow in Simpledraweeview

### ISSUE THREAD

**Issue by AagitoEx** [facebook/fresco#2233]
It would nice to have drop shadow (material drop shadow) and colored drop shadow (even translucent drop shadow).

**Comment by oprisnik** [comment]
I don't think this should be part of the core image loading library. Shadows heavily depend on the product / feature and it's quite easy to do nowadays. Google has a nice training guide here: https://developer.android.com/training/material/shadows-clipping

**Comment by oprisnik** [comment]
I'm re-opening this, since having a sample in the Showcase app would be useful. Feel free to submit a pull request.

**Comment by droidluv** [comment]
So how exactly do we add a shadow for a circular image?

**Comment by daviddebre** [comment]
By using elevation, and an oval shape as a background?!

**Comment by droidluv** [comment]
I used elevation and got a square shadow, maybe set a circle background and
set an outline?

**Comment by daviddebre** [comment]
<img width="435" alt="Screenshot 2019-11-11 at 12 42 52" src="https://user-images.githubusercontent.com/49857946/68581300-d428f380-0480-11ea-86b2-d512e5e43c02.png">
<img width="530" alt="Screenshot 2019-11-11 at 12 41 42" src="https://user-images.githubusercontent.com/49857946/68581317-dbe89800-0480-11ea-9dcf-d125fa0b3aca.png">

**Comment by oprisnik** [comment]
I think we don't need a sample for this. @daviddebre explained how this can be implemented. Thanks!
