### ISSUE TITLE
Provide support for the latest API level

### ISSUE THREAD

**Issue by ebghrimtech** [facebook/fresco#2234]
Hello,
We are currently using your library in one of our application. Actually we need a favour from your side. According to the Google Play Policy, all apps have to provide support for at least API level 26 which is satisfied in your case. We are targeting API level 28. So do we need to make any changes for supporting the latest API level i.e. 28?

**Comment by erikandre** [comment]
Hi @ebghrimtech ,

Fresco supports API level 28 without any changes (at least as long as you are on one of our more recent releases). If you do come across any issue, please file a bug report with details about what did not work.

Thanks!

**Comment by ebghrimtech** [comment]
Thank you @erikandre for the update.
