### ISSUE TITLE
Download a gif to Local Storage

### ISSUE THREAD

**Issue by sohailniazai** [facebook/fresco#2239]
Hi,
    I am using fresco version 1.10.0 . I have successfully got CloseableAnimatedDrawable from dataSource. I just need help in how can I save this animated Image to my localStorage. I tried but no succeeded.

Regards

**Comment by erikandre** [comment]
Hi @sohailniazai 

If you just want to use Fresco to download the gif (and then write the data to disk?) you could use the instructions from here: https://frescolib.org/docs/using-image-pipeline.html (section called "Skipping the decode")

**Comment by oprisnik** [comment]
I'm closing this issue since @erikandre explained how to manually get the encoded image.
