### ISSUE TITLE
Rounded corner in fresco

### ISSUE THREAD

**Issue by stefanlam88** [facebook/fresco#224]
Hi developers,
       I feel very impressive in fresco library but I face some issues like rounder corner?I tried your setasround as true but not working?any guidance?

**Comment by tyronen** [comment]
Please provide screenshots and code snippets.

**Comment by stefanlam88** [comment]
Hi tyronen, 

my code snippet as below

<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/rounded_img"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_gravity="center"
            fresco:roundAsCircle="true"
            fresco:roundingBorderWidth="5dp"
            fresco:roundingBorderColor="@android:color/white"
            />

anything wrong with mycode?I wan circle rounded image

**Comment by stefanlam88** [comment]
tyronen u can close this issue. I managed to solve. it was due to xml

**Comment by amankumarjain** [comment]
Hi, can we split the round corner like whatsapp usage in status.
