### ISSUE TITLE
Partial Image from Local Storage

### ISSUE THREAD

**Issue by sohailniazai** [facebook/fresco#2240]
Hi, I am using fresco version 1.10.0 for image loading. I am prefetching images and saving to app's internal Storage and loading that downloaded image in my view. But someTimes only partial image in loaded in the view. I cannot understand problem and need some help...

![b802b59e-2a59-4810-8f71-72006d076089](https://user-images.githubusercontent.com/34642164/48395822-44038180-e73a-11e8-85e0-5c6895efd3f2.jpeg)

**Comment by erikandre** [comment]
Hi @sohailniazai 

Could you please provide some code showing how you are prefetching as well as how you are then loading the image?
