### ISSUE TITLE
Question about PATENTS file in dependencies

### ISSUE THREAD

**Issue by iyegoroff** [facebook/fresco#2242]
### Description

One of fresco [dependencies](https://github.com/facebook/fresco/search?q=bolts-tasks&unscoped_q=bolts-tasks) - [Bolts-Android](https://github.com/BoltsFramework/Bolts-Android) has a BSD + PATENTS style license. So it looks like legally nothing changed since removal of PATENTS file from fresco. Can you give some clarification on this issue? Thanks.

### Reproduction

This is not technical issue

### Additional Information

* Fresco version: any
* Platform version: any

Original issue: https://github.com/facebook/react-native/issues/22260

**Comment by erikandre** [comment]
Hi @iyegoroff 

Bolts-Android is now relicensed under MIT license :)
