### ISSUE TITLE
 Fresco load circle image scaleType is wrong

### ISSUE THREAD

**Issue by keep2iron** [facebook/fresco#2243]
### Description
when I set application activity resource.displayMetrics.density,resource.densityDpi,resource.scaledDensity and use Fresco load circle image scaleType is wrong

### Reproduction

this is my repo:
https://github.com/keep2iron/pineapple
when I changed application activity resource.displayMetrics.density,resource.densityDpi
```
//change density code
....
applicationDisplayMetrics.density = targetDensity
applicationDisplayMetrics.densityDpi = targetDpi
applicationDisplayMetrics.scaledDensity = targetScaledDensity

val activityDisplayMetrics = activity.resources.displayMetrics
activityDisplayMetrics.density = targetDensity
activityDisplayMetrics.scaledDensity = targetScaledDensity
activityDisplayMetrics.densityDpi = targetDpi
....

//and use fresco load a circle image
RoundingParams.asCircle()
```
this is not use **change density code**，the image scaleType is right
![](https://i.imgur.com/vA05qAM.jpg)

but when I use **change density code** and with **RoundingParams.asCircle()**,the image scaleType is wrong
![](https://i.imgur.com/bPxqzqS.jpg)

### Solution

[OPTIONAL: Do you know what needs to be done to address this issue? Ideally, provide a pull request which fixes this issue.]

### Additional Information

* Fresco version: 1.11.0
* Platform version: Radmi Note 5A Android 7.1.2

**Comment by erikandre** [comment]
Hi @keep2iron 

Thanks for finding the workaround. We don't officially support this particular use case for Fresco (overriding density settings) so I'm glad it worked out :)
