### ISSUE TITLE
java.lang.NullPointerException at com.facebook.drawee.view.SimpleDraweeView.<init>

### ISSUE THREAD

**Issue by GabrielBB** [facebook/fresco#2244]
### Description

I cloned this repository: [WhatsApp Stickers](https://github.com/WhatsApp/stickers), did some modifications and deployed to Google Play. Today i found this error on the Google Play Console:

```
Caused by: android.view.InflateException: 
  at android.view.LayoutInflater.createView (LayoutInflater.java:645)
  at android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:764)
  at android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:704)
  at android.view.LayoutInflater.rInflate (LayoutInflater.java:835)
  at android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:798)
  at android.view.LayoutInflater.inflate (LayoutInflater.java:515)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Constructor.newInstance (Native Method)
  at android.view.LayoutInflater.createView (LayoutInflater.java:619)
Caused by: java.lang.NullPointerException: 
  at com.facebook.common.d.i.a (Unknown Source)
  at com.facebook.drawee.view.SimpleDraweeView.b (Unknown Source)
  at com.facebook.drawee.view.SimpleDraweeView.<init> (Unknown Source)
```

The error was at the line 3 of this method:

```
    @NonNull
    @Override
    public StickerPackListItemViewHolder onCreateViewHolder(@NonNull final ViewGroup viewGroup, final int i) {
        final Context context = viewGroup.getContext();
        final LayoutInflater layoutInflater = LayoutInflater.from(context);
        final View stickerPackRow = layoutInflater.inflate(R.layout.sticker_packs_list_item, viewGroup, false);
        return new StickerPackListItemViewHolder(stickerPackRow);
    }
```

What can possibly return NullPointerException at `com.facebook.drawee.view.SimpleDraweeView.<init>` ? Fresco is being initialized properly, as you can see, that repo seems to be from Facebook people too, so i guess they know what they were doing. I can't reproduce it since the app is working fine in every device i have tested. I can't test on the device the error ocurred since i can't find that phone: **TCT (Alcatel) alcatel U5 (BUZZ6T4G)**. I see that it was on Android 6.0, i have tested my app on that Android version too and it works fine.

* Fresco version: 

```
    implementation 'com.facebook.fresco:fresco:1.10.0'
    implementation 'com.facebook.fresco:webpsupport:1.10.0'
    implementation 'com.facebook.fresco:animated-webp:1.10.0'
    implementation 'com.facebook.fresco:webpsupport:1.10.0'
```

* Platform version: **TCT (Alcatel) alcatel U5 (BUZZ6T4G), Android 6.0**

**Comment by erikandre** [comment]
Hi @GabrielBB 

I also don't see anything that should be going wrong in those lines. If you're only seeing this from a single device then perhaps this is due to a dodgy ROM on that particular phone.

You might want to disable Proguard obfuscation on the classes involved in the crash to see if you can get the line numbers.

**Comment by oprisnik** [comment]
This looks suspiciously similar to #2246 where Fresco was not initialized properly. You have to do it before the layout is inflated, that's one of the reasons why we recommend doing it in your custom `Application` to make sure that is always the case.

**Comment by GabrielBB** [comment]
Just noticed the repo owners move Fresco Initialization from the EntryActivity to a class that extends Application as you can see in this commit: [Moved Fresco initialization to application](https://github.com/WhatsApp/stickers/commit/c63a35db4d7f59caa91ab39d5b834ee6f8838004)

I will update my fork with that change and will publish to store. If i don't see the error in 5 days i'm closing this issue
