### ISSUE TITLE
After setting the roundAsCircle property, the picture is not displayed properly.

### ISSUE THREAD

**Issue by q876625596** [facebook/fresco#2248]
![screenshot_2018-11-29-17-55-15-032](https://user-images.githubusercontent.com/20555239/49213777-ff493d00-f3ff-11e8-9db7-472558fe28d6.png)

That's what happened to the right and the bottom.

**Comment by oprisnik** [comment]
Unfortunately, this is a known issue and just how bitmap shaders work on Android. See #153 for solutions (using overlay color as a rounding mode).

If you always have fully circular images, you can use this postprocessor instead: https://github.com/facebook/fresco/blob/d19a009c5cfe6657201ac1614fbafe9f76e00395/native-filters/src/main/java/com/facebook/imagepipeline/postprocessors/RoundAsCirclePostprocessor.java
