### ISSUE TITLE
Load GIF error java.lang.IllegalStateException: Wrong color format

### ISSUE THREAD

**Issue by lx5288** [facebook/fresco#2252]
Android 4.2.2 load gif java.lang.IllegalStateException: Wrong color format
fresco version:
implementation 'com.facebook.fresco:fresco:1.10.0'
implementation 'com.facebook.fresco:animated-gif:1.10.0'
load GIF:
public void loadResGif(MyImageView imageView, int resId) {
        try {
            Uri uri = new Uri.Builder()
                    .scheme(UriUtil.LOCAL_RESOURCE_SCHEME)
                    .path(String.valueOf(resId))
                    .build();
            DraweeController draweeController =
                    Fresco.newDraweeControllerBuilder()
                            .setUri(uri)
                            .setAutoPlayAnimations(true)
                            .build();
            imageView.setController(draweeController);
        } catch (Exception e) {
        }
    }
ERROR:
I/dalvikvm( 7319): java.lang.IllegalStateException: Wrong color format

I/dalvikvm( 7319): 	at com.facebook.animated.gif.GifFrame.nativeRenderFrame(Native Method)

I/dalvikvm( 7319): 	at com.facebook.animated.gif.GifFrame.renderFrame(GifFrame.java:48)

I/dalvikvm( 7319): 	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderImageDoesNotSupportScaling(AnimatedDrawableBackendImpl.java:230)

I/dalvikvm( 7319): 	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderFrame(AnimatedDrawableBackendImpl.java:180)

I/dalvikvm( 7319): 	at com.facebook.imagepipeline.animated.impl.AnimatedImageCompositor.renderFrame(AnimatedImageCompositor.java:118)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.bitmap.wrapper.AnimatedDrawableBackendFrameRenderer.renderFrame(AnimatedDrawableBackendFrameRenderer.java:76)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.renderFrameInBitmap(BitmapAnimationBackend.java:313)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:217)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:237)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:237)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrame(BitmapAnimationBackend.java:165)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.backend.AnimationBackendDelegate.drawFrame(AnimationBackendDelegate.java:59)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck.drawFrame(AnimationBackendDelegateWithInactivityCheck.java:109)

I/dalvikvm( 7319): 	at com.facebook.fresco.animation.drawable.AnimatedDrawable2.draw(AnimatedDrawable2.java:206)

I/dalvikvm( 7319): 	at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)

I/dalvikvm( 7319): 	at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)

I/dalvikvm( 7319): 	at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:123)

I/dalvikvm( 7319): 	at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:302)

I/dalvikvm( 7319): 	at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:289)

I/dalvikvm( 7319): 	at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)

I/dalvikvm( 7319): 	at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:81)

I/amffmpeg( 7129): ff_network_wait_fd,retry=1

I/dalvikvm( 7319): 	at android.widget.ImageView.onDraw(ImageView.java:967)

I/dalvikvm( 7319): 	at android.view.View.draw(View.java:13712)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12650)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12694)

I/dalvikvm( 7319): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12588)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12694)

I/dalvikvm( 7319): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12588)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12694)

I/dalvikvm( 7319): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12588)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12694)

I/dalvikvm( 7319): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12588)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12694)

I/dalvikvm( 7319): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12588)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12694)

I/dalvikvm( 7319): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12588)

I/dalvikvm( 7319): 	at android.view.View.getDisplayList(View.java:12694)

I/dalvikvm( 7319): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)

I/dalvikvm( 7319): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2173)

I/dalvikvm( 7319): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2045)

I/dalvikvm( 7319): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)

I/dalvikvm( 7319): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)

I/dalvikvm( 7319): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)

I/dalvikvm( 7319): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:760)

I/dalvikvm( 7319): 	at android.view.Choreographer.doCallbacks(Choreographer.java:573)

I/dalvikvm( 7319): 	at android.view.Choreographer.doFrame(Choreographer.java:543)

I/dalvikvm( 7319): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:746)

I/dalvikvm( 7319): 	at android.os.Handler.handleCallback(Handler.java:725)

I/dalvikvm( 7319): 	at android.os.Handler.dispatchMessage(Handler.java:92)

I/dalvikvm( 7319): 	at android.os.Looper.loop(Looper.java:137)

I/dalvikvm( 7319): 	at android.app.ActivityThread.main(ActivityThread.java:5041)

I/dalvikvm( 7319): 	at java.lang.reflect.Method.invokeNative(Native Method)

I/dalvikvm( 7319): 	at java.lang.reflect.Method.invoke(Method.java:511)

I/dalvikvm( 7319): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)

I/dalvikvm( 7319): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)

I/dalvikvm( 7319): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by oprisnik** [comment]
Thanks for the report! Can you give us the GIF that causes this?

**Comment by lambdapioneer** [comment]
Cannot reproduce with `1.11.0` in the sample app. Can you verify if it still does not work if you upgrade to 1.11.0 and requesting the GIF via URI?
