### ISSUE TITLE
Gravity for overlayImage attribute

### ISSUE THREAD

**Issue by eboudrant** [facebook/fresco#2258]
### Description

I am trying to add an overlay image using the dimension from the drawable and with a `top|end` gravity. By default the `fresco:overlayImage` attribute zoom the overlay to the image view. Would it be possible to specify a gravity for the `fresco:overlayImage` (similar to what Android did `android:foreground` / `android:foregroundGravity`). 

In my use case I cannot use `android:foreground`.
### Additional Information

* Fresco version: 1.11.0

**Comment by lambdapioneer** [comment]
Hi @eboudrant, this is not possible at the moment. However, you can provide your own drawable using the `.setOverlayImage()` method on the `Drawee`'s ``GenericDraweeHierachy`. 

Similar to this line in the sample app: https://github.com/facebook/fresco/blob/e1145cfce57bb1b31dbd88d59a353a484a91cc80/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/drawee/DraweeHierarchyFragment.java#L76

Alternatively, writing a custom view that uses `DraweeHolder` under the hood might be interesting to you: https://frescolib.org/docs/writing-custom-views.html
