### ISSUE TITLE
Placehoder image not centered on Android P

### ISSUE THREAD

**Issue by raymondctc** [facebook/fresco#2260]
### Description

The placeholder image is not centred on Android P (OK on other versions of Android):
![screenshot_20181217-183117](https://user-images.githubusercontent.com/13764117/50081845-6ea99400-022a-11e9-929b-f3a1b2083d5c.png)

### Reproduction

When using the image below as placeholder image in SimpleDraweeView, placing it to `drawable-xhdpi` folder and with param `roundAsCircle=true` 
![edit_profile_default_avatar](https://user-images.githubusercontent.com/13764117/50081386-4c634680-0229-11e9-9f72-19942c6fdd6b.png)

Example XML
```xml
        <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/profile_avatar"
            android:layout_width="@dimen/profile_me_avatar"
            android:layout_height="@dimen/profile_me_avatar"
            android:layout_centerHorizontal="true"
            android:padding="@dimen/16dp"
            app:failureImage="@drawable/edit_profile_default_avatar"
            app:placeholderImage="@drawable/edit_profile_default_avatar"
            app:failureImageScaleType="fitCenter"
            app:actualImageScaleType="fitCenter"
            app:placeholderImageScaleType="fitCenter"
            app:roundAsCircle="true"
            />
```

### Additional Information

* Fresco version: 1.11.0
* Platform version: Android Pie, Nokia 7 Plus

**Comment by wkingluoye** [comment]
I have the same problem as you. Do you have a solution?

**Comment by raymondctc** [comment]
@wkingluoye I found it can be solved by supplying all types of dimensions for this drawable, we used to have `drawable-xhdpi` only for this image in the past.

**Comment by oprisnik** [comment]
I verified that this works properly for P if you put the placeholder in `res/drawable/`. I guess Android P changed the way that drawables are loaded if variants are missing.

![screenshot_1546955353](https://user-images.githubusercontent.com/2699634/50834603-5a9a1380-134c-11e9-8168-3242801c4af3.png)

**Comment by thirtyyuan** [comment]
Did you verify on Google Pixel 2 XL？I just find this problem on Google Pixel 2 XL.

**Comment by frapeti** [comment]
I'm still having this issue even after putting the file to /res/drawable

**Comment by TangoHanks** [comment]
I fixed this issue after putting image to drawable-nodpi folder (Test on Pixel 3 Android P)

**Comment by TouhidApps** [comment]
I have the same problem and asked in StackOverflow:
[Question Link](https://stackoverflow.com/q/62209758/5646794)
![x6mbo](https://user-images.githubusercontent.com/11577788/84472841-cb63fe80-aca9-11ea-8269-c251cc3c4bcd.png)

**Comment by amankumarjain** [comment]
i also had this same issue,
how i resolved it:
create a drawable-nodpi and mv a copy of those images to this folder, it will resolve this issue

**Comment by alen252** [comment]
> I'm still having this issue even after putting the file to /res/drawable
> 
> EDIT: Fixed it after moving the resource to /res/drawable-nodpi (tested on Pixel 2 XL - Android Q)
But this will make probblem when the picture also used in low density phone.

**Comment by amazingvoice** [comment]
I just fixed the same issue on my Pixel 3 (Android 12) by creating a drawable-nodpi folder and moving the PNG to that folder.
