### ISSUE TITLE
Images not displaying in RecyclerView

### ISSUE THREAD

**Issue by knjk04** [facebook/fresco#2262]
### Description
I am trying to load in an image from a URL in a RecyclerView in onBindViewHolder() in my adapter class. Only the placeholder images are being shown.

I'm initialising Fresco in my Application class. I also declare and assign my SimpleDraweeView in my ViewHolder inner class, similar to the sample you have for RecyclerViews.

### Reproduction

``` java
   @Override
    public void onBindViewHolder(@NonNull ViewHolder viewHolder, int i) {
        Book book = bookList.get(i);
        viewHolder.singleListRowBinding.setBook(book);

        if (book.getStrImageURL() != null) {
            String sampleUrl = "https://i.imgur.com/tGbaZCY.jpg%22";

            Log.d(TAG, "image url: " + book.getStrImageURL());
            viewHolder.draweeView.setImageURI(bookList.get(i).getStrImageURL());
    }
```

I've also tried using a sample URL. The URLs are from some JSON data that I am reading. I think they should work fine given that I'm using them elsewhere on my app (when I click on one of the items in the recyclerview, it takes me to a new activity where the images are being displayed fine). I've tried using an ImageRequest and then set the draweeView to the image request, but the recyclerview still only displays the placeholders.

The file: https://github.com/knjk04/Bookshelf/blob/feature/app/src/main/java/com/presentedbykaran/bookshelf/BookListAdapter.java 

### Additional Information

* Fresco version: 1.10.0
* Platform version: Pixel 2 XL emulator, API 28

Please let me know if more information is required

**Comment by knjk04** [comment]
Sorry, I did remove the initialisation from the adapter and into an Application class, but forgot to push (but have since pushed: https://github.com/knjk04/Bookshelf/blob/feature/app/src/main/java/com/presentedbykaran/bookshelf/BookListAdapter.java)

I couldn't get it working with picasso or glide. Do you think it could be something to do with my SimpleDraweeView being too small? (https://github.com/knjk04/Bookshelf/blob/feature/app/src/main/res/layout/single_list_row.xml)

**Comment by erikandre** [comment]
If you can see the placeholder image, then the layout is probably fine.
In the xml file I see some stuff that looks to be related to data bindings.
Are you using that? Maybe the issue could be related to that?
It might be worth a try to create a simple list item layout with just the image, text and nothing else just to see if the image loads.
