### ISSUE TITLE
reset gif to first frame

### ISSUE THREAD

**Issue by Lizz0y** [facebook/fresco#2265]
i use AnimatedDrawable2 to play gif and loop once , when loop end, imageview stop at the last frame, how to reset it to the first frame?

**Comment by zmroczek** [comment]
Hi @Lizz0y 

I think you could achieve this by creating an [`AnimationListener`](https://github.com/facebook/fresco/blob/5d419bcc450bd0e4fbc27546e94ac55ad20a3e60/animated-drawable/src/main/java/com/facebook/fresco/animation/drawable/AnimationListener.java) that will do that for you in the `onStop()` method (please take a look on `jumpToFrame()` method in the AntimatedDrawable2 if it helps).
