### ISSUE TITLE
jfif can't be displayed properly

### ISSUE THREAD

**Issue by folk113** [facebook/fresco#2272]
### Description
Only this [picture](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537975679433&di=c3c7d04f40c28adbf8476ae31fdcaa96&imgtype=0&src=http%3A%2F%2Fnpic7.edushi.com%2Fcn%2Fzixun%2Fzh-chs%2F2018-03%2F13%2F47fa381799f742118e6a2725a15e024b.jpg) can't be displayed properly，the others I used at present can。

### Reproduction
<pre>
In layout: 
   &lt;com.facebook.drawee.view.SimpleDraweeView 
         android:layout_width="42dp"
         android:layout_height="42dp"/&gt;
in Java:  <code>
   String url = "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537975679433&di=c3c7d04f40c28adbf8476ae31fdcaa96&imgtype=0&src=http%3A%2F%2Fnpic7.edushi.com%2Fcn%2Fzixun%2Fzh-chs%2F2018-03%2F13%2F47fa381799f742118e6a2725a15e024b.jpg";
   sdv.setImageURI(url );</code>
</pre>

**Comment by erikandre** [comment]
Hi @folk113 

The image that you linked to is a `.gif` file. Have you added the optional gif dependency to your gradle file? See here: https://frescolib.org/docs/index.html

It's also a very small image (only a few pixels big), it might hardly be visible? Try setting the scaletype to fitXY to stretch the image (https://frescolib.org/docs/scaletypes.html)

**Comment by folk113** [comment]
> Hi @folk113
> 
> The image that you linked to is a `.gif` file. Have you added the optional gif dependency to your gradle file? See here: https://frescolib.org/docs/index.html
> 
> It's also a very small image (only a few pixels big), it might hardly be visible? Try setting the scaletype to fitXY to stretch the image (https://frescolib.org/docs/scaletypes.html)

The link you provide I can't open successfully, but the picture I opened in windows platform, I can get the information of it like this, width:450,height:335, and the extend name is jpg, so it's not a very small image but really 18,781 bytes.

**Comment by folk113** [comment]
Maybe you can't download the image file from internet of yours, so I upload this file to my git repository, and provide the [link](https://github.com/folk113/Spi-Test/blob/master/timg.jfif), so you can download the file again.

**Comment by erikandre** [comment]
Thanks for uploading the file. For some reason when I tried to download it before I got a different file (maybe an error response?).

Do you see any error message in logcat when the image is loaded?

**Comment by folk113** [comment]
The logcat list as followed
<pre>
618 01-19 11:36:57.977 29892 30108 V unknown:BufferedDiskCache: Did not find image for https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537975679433&di=c3c7d04f40c28adbf8476ae31fdcaa96&imgtype=0&src=http%3A%2F%2Fnpic7.edushi.com%2Fcn%2Fzixun%2Fzh-chs%2F2018-03%2F13%2F47fa381799f742118e6a2725a15e024b.jpg in staging area
620 01-19 11:36:57.977 29892 30108 V unknown:BufferedDiskCache: Disk cache read for https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537975679433&di=c3c7d04f40c28adbf8476ae31fdcaa96&imgtype=0&src=http%3A%2F%2Fnpic7.edushi.com%2Fcn%2Fzixun%2Fzh-chs%2F2018-03%2F13%2F47fa381799f742118e6a2725a15e024b.jpg
621 01-19 11:36:57.979 29892 30108 V unknown:BufferedDiskCache: Found entry in disk cache for https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537975679433&di=c3c7d04f40c28adbf8476ae31fdcaa96&imgtype=0&src=http%3A%2F%2Fnpic7.edushi.com%2Fcn%2Fzixun%2Fzh-chs%2F2018-03%2F13%2F47fa381799f742118e6a2725a15e024b.jpg
622 01-19 11:36:57.980 29892 30108 V unknown:NativeMemoryChunkPool: Used = (4, 394240); Free = (0, 0)
623 01-19 11:36:57.982 29892 29892 V unknown:AbstractDraweeController: controller d1b7cb7 null -> null: initialize
624 01-19 11:36:57.982 29892 29982 D AsyncHttpClient: Headers were overwritten! (Accept | application/json) overwrites (Accept | application/json)
625 01-19 11:36:57.982 29892 29892 V unknown:AbstractDraweeController: controller d1b7cb7 null -> 19: initialize
626 01-19 11:36:57.982 29892 29892 V unknown:AbstractDraweeController: controller d1b7cb7 19: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@13e0c24
628 01-19 11:36:57.985 29892 30108 V unknown:NativeMemoryChunkPool: get (alloc) (object, size) = (60ad7b6, 1024)
629 01-19 11:36:57.986 29892 30108 V unknown:GenericByteArrayPool: Used = (1, 16384); Free = (0, 0)
630 01-19 11:36:57.986 29892 30108 V unknown:GenericByteArrayPool: get (reuse) (object, size) = (8154c21, 16384)
631 01-19 11:36:57.989 29892 30108 V unknown:GenericByteArrayPool: release (reuse) (object, size) = (8154c21, 16384)
632 01-19 11:36:57.990 29892 29892 V unknown:AbstractDraweeController: controller d1b7cb7 19 -> 20: initialize
633 01-19 11:36:57.990 29892 29892 V unknown:AbstractDraweeController: controller d1b7cb7 20: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@13e0c24
634 01-19 11:36:57.991 29892 30108 V unknown:GenericByteArrayPool: Used = (0, 0); Free = (1, 16384)
635 01-19 11:36:57.991 29892 29892 V unknown:AbstractDraweeController: controller d1b7cb7 20: onAttach: request needs submit
636 01-19 11:36:57.992 29892 29892 V unknown:PipelineDraweeController: controller d1b7cb7: getDataSource
637 01-19 11:36:57.992 29892 29892 V unknown:AbstractDraweeController: controller d1b7cb7 20: submitRequest: dataSource: 6f6538d
638 01-19 11:36:57.993 29892 30108 V unknown:BufferedDiskCache: Successful read from disk cache for https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537975679433&di=c3c7d04f40c28adbf8476ae31fdcaa96&imgtype=0&src=http%3A%2F%2Fnpic7.edushi.com%2Fcn%2Fzixun%2Fzh-chs%2F2018-03%2F13%2F47fa381799f742118e6a2725a15e024b.jpg
639 01-19 11:36:57.996 29892 29988 D AsyncHttpClient: Headers were overwritten! (Accept | application/json) overwrites (Accept | application/json)
</pre>

**Comment by folk113** [comment]
could anyone help me?

**Comment by oprisnik** [comment]
The image loads properly in the Showcase app if I set the URI override to https://github.com/folk113/Spi-Test/blob/master/timg.jfif?raw=true

Looks like everything is is working on the Fresco side?

![screenshot_1549541928](https://user-images.githubusercontent.com/2699634/52411142-9a325780-2ad2-11e9-9341-ebc86e906e34.png)

**Comment by folk113** [comment]
> The image loads properly in the Showcase app if I set the URI override to https://github.com/folk113/Spi-Test/blob/master/timg.jfif?raw=true
> 
> Looks like everything is is working on the Fresco side?
> 
> ![screenshot_1549541928](https://user-images.githubusercontent.com/2699634/52411142-9a325780-2ad2-11e9-9341-ebc86e906e34.png)

How can I define when to add this Suffix "?raw=true", or can I add it to the end of all image url address?

**Comment by lambdapioneer** [comment]
@folk113, just add it to your URI string when setting the image URI :) (or host it outside GitHub where you don't need to specify it).

As this is not related to Fresco, I'll close this issue now :)
