### ISSUE TITLE
How to save images to local storage

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [facebook/fresco#2275]
My app needs to load images from local storage, apply some transformation and then save the transformed image back to local storage.

I am using Fresco to load images from storage. Everything works well, except that I'm not able to save images back to local storage.

This is what I'm doing to save images:

```kotlin
val imagePipeline = Fresco.getImagePipeline()
val dataSource = imagePipeline.fetchEncodedImage(imageRequest, context)
dataSource.subscribe(SaveBitmapSubscriber(), DefaultExecutorSupplier(1).forLocalStorageWrite())

class SaveBitmapSubscriber: BaseDataSubscriber<CloseableReference<PooledByteBuffer>>() {
  override fun onFailureImpl(dataSource: DataSource<CloseableReference<PooledByteBuffer>>) {
    Log.d(javaClass.simpleName, "onFailureImpl")
  }

  override fun onNewResultImpl(dataSource: DataSource<CloseableReference<PooledByteBuffer>>) {
    Log.d(javaClass.simpleName, "onNewResultImpl")
  }
}
```
`onFailureImpl` is called every time. What am I doing wrong? Is this even the right way to do it? the documentation on the topic is scarce.

**Comment by lambdapioneer** [comment]
Hi @PierfrancescoSoffritti, Fresco isn't designed to save images locally. It's focus is on downloading remote and local images. Directly interacting with the file cache that it uses will be brittle at best.

We have recently open-sourced a library that takes care of image transcoding on Android. It might be a good solution for "encoding" an image (i.e. saving a Bitmap as an encoded image). You can checkout: https://libspectrum.io/docs/getting_started_android for more information.
