### ISSUE TITLE
When using roundAsCircle , placeholder image is no longer displaying as expected

### ISSUE THREAD

**Issue by nbortolussi** [facebook/fresco#2277]
### Description

When setting fresco:roundAsCircle="true", fresco:placeholderImageScaleType="centerCrop" is ignored. I should see the placeholder image with it's X and Y filling the space. However, it instead displays a small version in the upper left corner.

### Reproduction

<com.facebook.drawee.view.SimpleDraweeView
Set fresco:placeholderImage="whatever image"
Set fresco:placeholderImageScaleType="centerCrop"
Set fresco:roundAsCircle="true"
 </com.facebook.drawee.view.SimpleDraweeView>

### Additional Information

* Fresco version: 1.11.0
* Platform version: Android 9 Google Pixel 3 XL

**Comment by nbortolussi** [comment]
The image width and height are bigger than view width and height. Camera icon is directly in the center.

`<com.facebook.drawee.view.SimpleDraweeView
                        android:id="@+id/add_image_button"
                        android:layout_width="150dp"
                        fresco:placeholderImage="@drawable/bg_camera"
                        android:layout_height="150dp"
                        fresco:actualImageScaleType="centerCrop"
                        fresco:roundAsCircle="true"
                        fresco:placeholderImageScaleType="centerCrop"
                        android:layout_centerInParent="true"/>`


![ss](https://user-images.githubusercontent.com/19995679/51612358-4844db80-1eef-11e9-90df-3d8e35879d6c.png)

![bg_camera](https://user-images.githubusercontent.com/19995679/51612444-77f3e380-1eef-11e9-932e-a5afef7421df.png)

**Comment by erikandre** [comment]
Is the placeholder a PNG file?

**Comment by oprisnik** [comment]
This is likely a duplicate of #2260. Looks like Android changed the way that resources are handled if a density bucket is missing. Do you supply all densities or put the resource in /drawable/ instead of drawable-xhdpi or similar?

**Comment by nbortolussi** [comment]
confirmed that when placing the PNG in a non density specific folder like drawable or drawable-nodpi the problem is resolved. thank you for the help.

**Comment by alen252** [comment]
> confirmed that when placing the PNG in a non density specific folder like drawable or drawable-nodpi the problem is resolved. thank you for the help.

I can only put one png in drawable-nodpi.But how to select the png size that display normal in different screen density mobile phone.
