### ISSUE TITLE
Is there a way to do url rewriting ?

### ISSUE THREAD

**Issue by aclassen** [facebook/fresco#228]
I'm looking for a way to do some url rewriting according to the view size. 
I want to provide a url like : http://xx.yy/img.png
Now when the view should be shown in a 64dp x 64dp view the request should look like : http://xx.yy/img.png?width=64&height=64
Something like Glide's BaseGlideUrlLoader getUrl(ImageRequest model, int width, int height) function.
Can you point me in the right direction ?

**Comment by tyronen** [comment]
The server has to support these URLs though. We can't built a general-purpose solution.

Glide does provide an API for this, but the only two implementations I could find are specific to Giphy and Flickr.

**Comment by aclassen** [comment]
Of course the server must support the urls.
Sorry if my questing was misleading.

We are hosting our images at google and requesting them with a size parameter.
The only thing i was looking for, was a callback, with the drawee size, which get called to get the final url before requesting it.
