### ISSUE TITLE
Malformed Gif causes OOM

### ISSUE THREAD

**Issue by jkcailteux** [facebook/fresco#2283]
A malformed GIF is being sent around our app and is being used to DOS users.  The offending GIF is here: https://cdn.discordapp.com/attachments/480860143924412438/539632514839347241/death.gif

I have prepared a sample app that simply loads this GIF via Fresco, it crashes with an OOM at the end of the GIF.

[MyApplication.zip](https://github.com/facebook/fresco/files/2809387/MyApplication.zip)

I noticed the GIF is 128x128 until the last frame where it is roughly 65000x65000. 

Curious if you guys had any ideas on how to workaround this until a proper fix is in place.

* Fresco version: Latest as of 1/29/19, 1.11.0
* Platform version: Android 9.0 Pie

**Comment by defHLT** [comment]
@jkcailteux The fix is in 7479a6fe103101fdf1bada5d2ed3f28a27e5e2f0. You need to set `.experiment().setShouldDownscaleFrameToDrawableDimensions(true)` on image pipeline options. I tested on showcase sample app. Closing the issue but please let me know if it works for you.

**Comment by defHLT** [comment]
This change should be in 1.12.1 release
