### ISSUE TITLE
Fresco 1.12 does not have new commits

### ISSUE THREAD

**Issue by jkcailteux** [facebook/fresco#2285]
### Description

Fresco 1.12 does not contain the features mentioned in the release notes. Decompiling it reveals the new code is not there.

### Reproduction

Start a sample project with Fresco 1.12. Notice that features that are supposed to be in 1.12 are not. Decompiling the code reveals the code from the mentioned commits is not there.

### Solution

Re-roll the release? Not sure how you guys do releases/CI.

### Additional Information

* Fresco version: 1.12.0
* Platform version: All

**Comment by oprisnik** [comment]
Thanks for letting us know. cc @zmroczek who did the release.

**Comment by zmroczek** [comment]
Hey @jkcailteux,

Thanks for letting us know. I verified some of the maven packages and seems they include correct changes. Could you provide more details on which modules you're using?

**Comment by defHLT** [comment]
Thanks for reporting, however I can't repro.
With:
```
    implementation 'com.facebook.fresco:fresco:1.12.0'
```

The following code which uses two new futures compiles for me:

```
        ImageRequestBuilder.newBuilderWithSource(null)
                .setShouldDecodePrefetches(true)
                .setResizingAllowedOverride(true)
                .build();
```

Could you please specify which particular feature does is not available for you?

**Comment by jkcailteux** [comment]
I'm referencing this comment from my previous issue: https://github.com/facebook/fresco/issues/2283#issuecomment-460009253

I didn't see the recommended fix in the latest Fresco (1.12)

**Comment by jkcailteux** [comment]
Upon further inspection, looks like commit https://github.com/facebook/fresco/commit/7479a6fe103101fdf1bada5d2ed3f28a27e5e2f0
didn't make it into Fresco 1.12. Explains why I thought features were missing.

**Comment by AndyG** [comment]
@defHLT thanks for the quick response! Is there any way we could get another release that includes https://github.com/facebook/fresco/commit/7479a6fe103101fdf1bada5d2ed3f28a27e5e2f0 ? We have been unfortunately unsuccessful trying to build Fresco ourselves, but certain GIFs continue to be used as an attack vector in our product (referencing [this issue](https://github.com/facebook/fresco/issues/2283).)

Again, thanks for being so responsive and getting the fix made so quickly :)

**Comment by oprisnik** [comment]
We'll do a hotfix release tomorrow morning London time.

**Comment by AndyG** [comment]
![dot](https://user-images.githubusercontent.com/8857134/52293653-3ec66500-292c-11e9-9298-35abc93477fe.gif)

Fresco continues to be one of my favorite OSS projects to contribute to and interact with!

**Comment by zmroczek** [comment]
Version 1.12.1 has just been released https://github.com/facebook/fresco/releases
