### ISSUE TITLE
Why does the so Library of imagepipeline not support armeabi since V1.10.0

### ISSUE THREAD

**Issue by TextX666888** [facebook/fresco#2288]
Why does the so Library of imagepipeline not support armeabi since V1.10.0

V1.9.0
![image](https://user-images.githubusercontent.com/35981460/52829289-206c2080-3107-11e9-84ad-4821d2592a3d.png)
V1.10.0
![image](https://user-images.githubusercontent.com/35981460/52829311-3da0ef00-3107-11e9-9d24-586a262028dd.png)
Thank you!

**Comment by lambdapioneer** [comment]
Hi @TextX666888, this is due to the deprecation of armeabi with NDK r16 and the removal in NDK r17.

See https://developer.android.com/ndk/guides/abis for background on this :)
