### ISSUE TITLE
Rounded corners for animations

### ISSUE THREAD

**Issue by ChadCSong** [facebook/fresco#229]
Gif animation on round shape is invalid, when I try to load a square Gif animation on SimpleDraweeView.

How to solve this problem?

**Comment by tyronen** [comment]
Can you provide a sample URL and screenshot?

**Comment by ChadCSong** [comment]
Thanks for your attention.

The url of gif :
(GIF sample)[http://q.qlogo.cn/qqapp/100537558/BE743B7457A973C4A79819B2FB3F6BEF/100]

I use the SimpleDraweeView as follow code:

 DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                    .setAutoPlayAnimations(true)
                    .setUri(Uri.parse(photo))//设置uri
                    .build();
            RoundingParams roundingParams = RoundingParams.asCircle();
            simpleDraweeView.getHierarchy().setRoundingParams(roundingParams);
            simpleDraweeView.setController(draweeController);

screenshot has add to the attach. Check it.

**Comment by ChadCSong** [comment]
I have tried many gif pictures, just animation couldn't be cut as circle.

**Comment by ChadCSong** [comment]
I have tried many gif pictures, just animation couldn't be cut as circle.

**Comment by tyronen** [comment]
Yes, this is a limitation. We don't support rounded corners for animated images.

**Comment by IanChilds** [comment]
Hi Chad. You will be able to round an animated image if you use the `OVERLAY_COLOR` rounding method, rather than `BITMAP_ONLY` rounding method (which is the default). Try using: `RoundingParams.asCircle().setRoundingMethod(OVERLAY_COLOR).setOverlayColor(your_color)` instead.
