### ISSUE TITLE
Fresco failed to load libimagepipeline.so 

### ISSUE THREAD

**Issue by dinuscxj** [facebook/fresco#2290]
### Description

java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/mnt/expand/73b20745-928d-44e1-bed7-1093ff4eba84/user/0/com.kwai.global.video.social.kwaigo/lib-main/libimagepipeline.so" is 32-bit instead of 64-bit

1 com.facebook.soloader.SoLoader.b(SoLoader.java:703)
2 com.facebook.soloader.SoLoader.a(SoLoader.java:564)
3 com.facebook.soloader.SoLoader.b(SoLoader.java:500)
4 com.facebook.soloader.SoLoader.a(SoLoader.java:455)
5 com.facebook.imagepipeline.nativecode.a.a(ImagePipelineNativeLoader.java:40)
6 com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:31)
7 com.facebook.imagepipeline.memory.i.b(NativeMemoryChunkPool.java:5056)
8 com.facebook.imagepipeline.memory.BasePool.a(BasePool.java:259)
9 com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:49)
10 com.facebook.imagepipeline.memory.k.a(NativePooledByteBufferFactory.java:1139)
11 com.facebook.imagepipeline.producers.aa$1.a(NetworkFetchProducer.java:1088)
12 com.facebook.imagepipeline.a.a.b$2.a(OkHttpNetworkFetcher.java:136)
13 okhttp3.v$a.b(RealCall.java:153)
14 okhttp3.internal.b.run(NamedRunnable.java:32)
15 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
16 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
17 java.lang.Thread.run(Thread.java:818)

**Comment by oprisnik** [comment]
Hey! The same issue has been reported for SoLoader (the library that fails to load the .so) here: https://github.com/facebook/SoLoader/issues/29
