### ISSUE TITLE
Fresco support Cronet ?

### ISSUE THREAD

**Issue by santiagoseek** [facebook/fresco#2291]
Fresco have any plan on Cronet network layers ?

**Comment by lambdapioneer** [comment]
There's no support in Fresco at the moment. However, this is something that could be provided from another developer as a plugin. We are also open to pull-requests that add these kind of support :)

**Comment by defHLT** [comment]
It's not planned for now. But contributions welcome :)

**Comment by limuyang2** [comment]
https://github.com/limuyang2/Fresco-Cronet
