### ISSUE TITLE
Version 1.8.0, the picture failed to load, what is the cause

### ISSUE THREAD

**Issue by droidan** [facebook/fresco#2292]
02-25 13:48:12.149 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.platform.DalvikPurgeableDecoder,FileName:DalvikPurgeableDecoder.java,MethodName:pinBitmap,LineNumber:178 02-25 13:48:12.150 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.platform.KitKatPurgeableDecoder,FileName:KitKatPurgeableDecoder.java,MethodName:pinBitmap,LineNumber:30 02-25 13:48:12.150 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.platform.DalvikPurgeableDecoder,FileName:DalvikPurgeableDecoder.java,MethodName:decodeJPEGFromEncodedImage,LineNumber:95 02-25 13:48:12.150 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.platform.KitKatPurgeableDecoder,FileName:KitKatPurgeableDecoder.java,MethodName:decodeJPEGFromEncodedImage,LineNumber:30 02-25 13:48:12.150 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.decoder.DefaultImageDecoder,FileName:DefaultImageDecoder.java,MethodName:decodeJpeg,LineNumber:175 02-25 13:48:12.151 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.decoder.DefaultImageDecoder$1,FileName:DefaultImageDecoder.java,MethodName:decode,LineNumber:58 02-25 13:48:12.151 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.decoder.DefaultImageDecoder,FileName:DefaultImageDecoder.java,MethodName:decode,LineNumber:121 02-25 13:48:12.151 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder,FileName:DecodeProducer.java,MethodName:doDecode,LineNumber:251 02-25 13:48:12.152 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder,FileName:DecodeProducer.java,MethodName:access$300,LineNumber:115 02-25 13:48:12.152 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1,FileName:DecodeProducer.java,MethodName:run,LineNumber:154 02-25 13:48:12.152 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.producers.JobScheduler,FileName:JobScheduler.java,MethodName:doJob,LineNumber:204 02-25 13:48:12.153 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.producers.JobScheduler,FileName:JobScheduler.java,MethodName:access$000,LineNumber:24 02-25 13:48:12.153 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.producers.JobScheduler$1,FileName:JobScheduler.java,MethodName:run,LineNumber:75 02-25 13:48:12.153 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:java.util.concurrent.ThreadPoolExecutor,FileName:ThreadPoolExecutor.java,MethodName:runWorker,LineNumber:1112 02-25 13:48:12.153 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:java.util.concurrent.ThreadPoolExecutor$Worker,FileName:ThreadPoolExecutor.java,MethodName:run,LineNumber:587 02-25 13:48:12.154 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:com.facebook.imagepipeline.core.PriorityThreadFactory$1,FileName:PriorityThreadFactory.java,MethodName:run,LineNumber:53 02-25 13:48:12.154 27194-27194/com.ilike.cartoon E/ManHuaRenLog: [main(1): VerticalRecyclerViewAdapter.java:390] - ClassName:java.lang.Thread,FileName:Thread.java,MethodName:run,LineNumber:848

**Comment by erikandre** [comment]
Hi @droidan 

Based on the log I cannot see a cause for the failure. Could you please provide some more information:

- What is the URL of the image you are trying to load?
- Code snippet showing how you are using Fresco to load the image

**Comment by droidan** [comment]
Load the local Uri, I think is the source thread scheduling problem, frequent loading of local pictures failed

    public static PipelineDraweeController getReadDraweeController(Uri uri,int width,int height,ControllerListener controllerListener,Postprocessor postprocessor){
        ImageRequestBuilder requestBuilder = ImageRequestBuilder.newBuilderWithSource(uri).setPostprocessor(postprocessor);
        if(width > 0 && height > 0){
            requestBuilder.setResizeOptions(new ResizeOptions(width,height,Integer.MAX_VALUE));
        }
        ImageRequest request = requestBuilder.build();
        PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
                .setControllerListener(controllerListener)
                .build();
        return controller;
    }
