### ISSUE TITLE
The image clarity with adjusting the screen resolution manually

### ISSUE THREAD

**Issue by tgithubc** [facebook/fresco#2297]
### Description

Hello, I've found a problem. When i adjusting the screen resolution manually, the image clarity looks blurry at low screen resolution(hd 1520_720),looks normal at high screen resolution(fhd 2280_1080). Moreover, if I use Fresco.getImagePipeline().fetchDecodedImage get a Bitmap and setImageBitmap to SimpleDraweeView, this case display is normal. So please tell me what causes the blurred picture.

### Reproduction
![image](https://s2.ax1x.com/2019/02/28/k78bpd.png)

the (hd 1520_720)
![image](https://s2.ax1x.com/2019/03/05/kXjUq1.png)
the (fhd 2280_1080)
![image](https://s2.ax1x.com/2019/03/05/kXjdVx.png)

It's more obvious on mobile phones.

* Fresco version: [1.7.0]
* Platform version: HuaWei Honor10 / Android 9.0

**Comment by zmroczek** [comment]
Hi @tgithubc 

Thanks for reporting it. Could you provide a clearer repro scenario for the case where the image gets blurry? Did you restart the app after changing the screen resolution?

**Comment by tgithubc** [comment]
> Hi @tgithubc
> 
> Thanks for reporting it. Could you provide a clearer repro scenario for the case where the image gets blurry? Did you restart the app after changing the screen resolution?

Hi， @zmroczek 
Thank you for your reply!
After changing the screen resolution the app will be killed auto.
Can see the obvious graininess on the phone at low screen resolution, which is not obvious on the computer

**Comment by zmroczek** [comment]
Could you please provide more details, e.g. code samples on when this reproduces and when not?

**Comment by ZumaLuma** [comment]
Hello to reproduce this problem need set rounding corners to image with flag BITMAP_ONLY, this problem may reproduce only on devices with Android Pie. If set rounding with overlay color, this problem doesnt reproduce on Android Pie. Devices with system below Android Pie dont have this problem. I hope we find how to resolve this problem. Thank you for your answer.

**Comment by tgithubc** [comment]
@zmroczek 
Thank you again for your reply.
I think I found the reason, but I don't know how to solve it.
Reproduce this problem need set rounding corners to SimpleDraweeView view with flag BITMAP_ONLY on Android P. If set rounding with OVERLAY_COLOR or remove rounding corners, this problem doesn't reproduce. But I can't do that because of business needs. 
I wonder if there are other solutions？

**Comment by tgithubc** [comment]
Hi @oprisnik 
The implementation of Fresco‘s RoundedBitmapDrawable may cause blurred picture display on android p. I have tryed to replace it with android.support.v4.graphics.drawable.RoundedBitmapDrawable can solve it. Hope to fix this bug.
Thank you for your attention to this problem.

**Comment by oprisnik** [comment]
Does https://github.com/facebook/fresco/pull/2294 fix your problem? Looks like it's the same issue where the rounded image is not upscaled.

**Comment by tgithubc** [comment]
> Does #2294 fix your problem? Looks like it's the same issue where the rounded image is not upscaled.

Thanks for the links!
But it didn't work for me,the situation looks even worse.
The hd screen solution became like this:
![image](https://s2.ax1x.com/2019/03/06/kvwYB6.png)

**Comment by oprisnik** [comment]
What's the resolution of your images vs the Drawable dimensions? Can you enable the Fresco debug overlay for both versions? See https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/ShowcaseApplication.java#L66 where we enable the overlay for the sample app.

**Comment by tgithubc** [comment]
RoundedBitmapDrawable  Paint setFilterBitmap can fix it
