### ISSUE TITLE
Problem with shared element

### ISSUE THREAD

**Issue by leandro1995** [facebook/fresco#2299]
The library has problems using the shared element, when I pass the image to a new activity it disappears and the animation that should be shown does not show the same thing happens in reverse.

Why does this happen?

**Comment by zmroczek** [comment]
Hi @leandro1995 

Thanks for reporting. Could you please provide a clear repro steps with code samples so that we can reproduce this issue?

**Comment by oprisnik** [comment]
Hey! Please take a look at #1445. Unfortunately, Android changed the behavior for handling visibility events which causes this issue. There are some workarounds in the discussion.
