### ISSUE TITLE
Does Fresco support Android Q?

### ISSUE THREAD

**Issue by Zhuinden** [facebook/fresco#2307]
> Apps targeting Q can no longer directly use ashmem (/dev/ashmem) and must instead access shared memory via the NDK’s ASharedMemory class. 

*(from https://developer.android.com/preview/behavior-changes-q#shared-memory)*

I remember reading that Fresco relies on access to `ashmem` in order to be more reliable, does this change affect Fresco?

**Comment by oprisnik** [comment]
Hey! Thanks for letting us know! Fresco should still work with Android Q. We have been using ashmem for Bitmaps, but that API doesn't exist in newer versions anyway (ART), so we're not putting bitmaps in ashmem. We do use native memory for some internal buffers & caches and could experiment with using ashmem again on newer versions.

Did you experience issues with Fresco and Q?
