### ISSUE TITLE
edges repeating  when use fresco:roundedCornerRadius on v1.10.0 and higher version on HTC M10u

### ISSUE THREAD

**Issue by sangchengjiang** [facebook/fresco#2308]
### Description

When I use fresco:roundedCornerRadius on HTC M10u on v1.10.0 and higher version, I got a edges repeating image. 
The picture I use is bigger than view, and use default scale type (centerCrop) . 

This is my layout:
<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/iv_gif"
            android:layout_width="300dp"
            android:layout_height="200dp"
            android:layout_centerVertical="true"
            fresco:placeholderImage="@mipmap/ic_launcher"
            fresco:roundedCornerRadius="2dp"
            />

And the picture I use :
http://img.ivsky.com/img/tupian/pre/201606/27/yarlung_zangbo_grand_canyon-004.jpg

![Screenshot_20190319-111502](https://user-images.githubusercontent.com/27657335/54577916-8fa3a000-4a38-11e9-87f1-6afd5dd5dc38.png)

**When I back to v1.9.0, every thing is ok ：**

![Screenshot_20190319-111917](https://user-images.githubusercontent.com/27657335/54578006-e9a46580-4a38-11e9-94df-f2037c4e69c3.png)

**This issue reproduce only on HTC M10u**

### Additional Information

* Fresco version: [v1.10.0-1.13.0]
* Platform version: [HTC M10u Android 6.0.1]

**Comment by oprisnik** [comment]
This is a limitation of Bitmap Shaders on Android. See https://frescolib.org/docs/rounded-corners-and-circles.html for more information.

**Comment by sangchengjiang** [comment]
Why it's OK on fresco v1.9.0 and lower version?

**Comment by sangchengjiang** [comment]
> This is a limitation of Bitmap Shaders on Android. See https://frescolib.org/docs/rounded-corners-and-circles.html for more information.

Why it's OK on fresco v1.9.0 and lower version?
