### ISSUE TITLE
Some public APIs' add request.

### ISSUE THREAD

**Issue by whataa** [facebook/fresco#2309]
### Description

I use dataBinding library to bind data for SimpleDraweeView and want to know if  some attributes of DraweeView are specified in the XML such as `app:backgroundImage`, `app:progressBarImage`, so that I can decide if need set default values for them in `@BindingAdapter`. And now I only know the state of `PlaceholderImage` by call `getHierarchy().hasPlaceholderImage()`, how can I know the others ?

```
@BindingAdapter(value = {"image"})
public static void loadImage(SimpleDraweeView image, final String path) {
    ...
    if (!image.getHierarchy().hasPlaceholderImage()) {
        image.getHierarchy().setPlaceholderImage(/* the default image */, ScalingUtils.ScaleType.CENTER_INSIDE);
    }
    // How to do for BackgroundImage
    ...
}
```

### Solution

Hope for adding some apis in `GenericDraweeHierarchy` class like `hasPlaceholderImage()` for `backgroundImage`、`ProgressBarImage` and others.

### Additional Information

* Fresco version: v1.12.1

**Comment by lambdapioneer** [comment]
Hi @whataa, you can find all supported XML attributes in the `attrs.xml` file: https://github.com/facebook/fresco/blob/master/drawee/src/main/res/values/attrs.xml#L143-L233

If you want to understand the link between the XML attributes and the Java objects, you should have a look at the corresponding inflater: https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchyInflater.java

**Comment by whataa** [comment]
Thanks @lambdapioneer . 

Maybe I didn't make myself clear enough, in other words, I just want the `GenericDraweeHierarchy` class to provide some public methods such as `hasBackgroundImage()`, `hasProgressBarImage()`, so that I can call them in the Java not XML.  

In some cases, these methods are necessary.

**Comment by defHLT** [comment]
GenericDraweeHierarchy was not written with having such usecase in mind. But if you need to do it:
- You should be able to get drawable by index: `((ArrayDrawable)simpleDraweeView.getHierarchy().getTopLevelDrawable().getCurrent()).getDrawable(INDEX)`
- You can get layer indexes from here: https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchy.java#L85-L91
