### ISSUE TITLE
How can I load non-resource Drawable?

### ISSUE THREAD

**Issue by dengyuhan** [facebook/fresco#2310]
### Description
Such as  `GradientDrawable`, `ColorDrawable`, It is not a URI, I use `drawee.setImageDrawable` but can't work like ImageView.

### Additional Information
* Fresco version: 1.13.0
* Platform version: Android 7.0

**Comment by erikandre** [comment]
Hi @dengyuhan 

You say that it doesn't work like ImageView, what feature from ImageView are you missing in Fresco?
If it's not very clear, a code example always helps :)

**Comment by dengyuhan** [comment]
I wanted to set 'GradientDrawable',  or 'ColorDrawable', but I couldn't find a way to set Drawable.
Because the examples are all uris that are used.

**Comment by dengyuhan** [comment]
My image is a custom Drawable, how do I get it to show in SimpleDraweeView.

**Comment by defHLT** [comment]
You can set a drawable as placeholder.
If you think you need to, you can also set it like this:
```
    ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithResourceId(R.drawable.ic_settings).build();

    SimpleDraweeView simpleDraweeView = (SimpleDraweeView) view.findViewById(R.id.drawee_view);
    simpleDraweeView.setImageRequest(imageRequest);
```

**Comment by dengyuhan** [comment]
I found a solution in [ColorImageExample](https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/color/ColorImageExample.java)
