### ISSUE TITLE
No image request was specified!

### ISSUE THREAD

**Issue by fflin** [facebook/fresco#2311]
Hello there,
When I used Fresco to load a web image, I encountered the following problem:
On the Meizu phone of the Android 5.1 system, I listened to the image loading onFailure through the ControllerListener, and the throwable display information is: No image request was specified!
But I don't have this problem on other phones like Nokia 7Plus for Android 9.0, I will call back onFinalImageSet every time.
I would like to ask if there is any solution for this?

**Comment by fflin** [comment]
com.facebook.fresco:fresco:1.7.1

**Comment by erikandre** [comment]
Hi @fflin 

Could you please show me the code where you are using Fresco to load the image in question? Thanks!

**Comment by fflin** [comment]
Hello @erikandre 
    This is the code,Thanks!
SimpleDraweeView sdv = new SimpleDraweeView(getContext());
sdv.getHierarchy().setPlaceholderImage(R.drawable.placeholder_square);
 sdv.getHierarchy().setActualImageScaleType(ScalingUtils.ScaleType.FIT_START);
sdv.setImageURI(item.pic);

**Comment by fflin** [comment]
@erikandre 
Hello there,
This is my code,The two phones use the same wifi network, only the Meizu 5.1 version can not be successfully loaded, I can load these pictures with the older Android 4.4 phone 
```javascript
                SimpleDraweeView sdv = new SimpleDraweeView(getContext());
                sdv.getHierarchy().setPlaceholderImage(R.drawable.placeholder_square);
                sdv.getHierarchy().setActualImageScaleType(ScalingUtils.ScaleType.FIT_START);
                sdv.setImageURI(item.pic);//the url for image
                
                ControllerListener listener = new BaseControllerListener(){
                    @Override
                    public void onFinalImageSet(String id, Object imageInfo, Animatable animatable) {
                        super.onFinalImageSet(id, imageInfo, animatable);
                        Log.i("dialChild","-------onFinalImageSet");
                    }

                    @Override
                    public void onFailure(String id, Throwable throwable) {
                        super.onFailure(id, throwable);
                        Log.i("dialChild","-------onFailure:"+throwable.getMessage());
                    }

                    @Override
                    public void onIntermediateImageFailed(String id, Throwable throwable) {
                        super.onIntermediateImageFailed(id, throwable);
                        Log.i("dialChild","-------onIntermediateImageFailed:"+throwable.getMessage());
                    }
                };
                DraweeController controller = Fresco.newDraweeControllerBuilder()
                        .setUri(item.pic)
                        .setControllerListener(listener)
                        .build();
                sdv.setController(controller);
```

**Comment by erikandre** [comment]
I see that you are setting the Uri twice (both on the view and the controller). Try removing the 2nd call and only set it on the sdv.

**Comment by fflin** [comment]
Setting Uri twice is for testing convenience, but you reminded me that I actually submitted the test code to the master. I updated the latest version of the filyme system on the weekend. After rebooting, this problem can't be reproduced again. The domestic customized system will always encounter many unexpected problems. Thank you.

**Comment by erikandre** [comment]
Thanks for letting us know @fflin !

**Comment by sagar091** [comment]
I have searched a lot about it. Then I switch to Glide. It's not working in that too.

Then I digg into its listener. It shows me error "Cleartext HTTP traffic to maps.google.com not permitted" because of I was fetching the image from **maps.google.com** and this is the error after API Level 27 for network security config.

So do one thing:
Create a XML file under res->xml directory: 
`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">**google.com**</domain>
    </domain-config>
</network-security-config>`

> It works for me.
