### ISSUE TITLE
create pipe(2) failed: too many open files loading

### ISSUE THREAD

**Issue by venkypokala** [facebook/fresco#2314]
We use GitHub Issues for bugs.

appdata::create pipe(2) failed: too many open files. we are using in recycle view and size around 1500 items

**Comment by erikandre** [comment]
Hi @venkypokala 

is the issue reproducible? If so could you share some code samples of how you are using Fresco?

**Comment by venkypokala** [comment]
i am using in recyclerview


XML
-----------------------

 <com.facebook.drawee.view.SimpleDraweeView
            xmlns:fresco="http://schemas.android.com/apk/res-auto"
            android:id="@+id/image"
            android:layout_width="53dp"
            android:layout_height="53dp"
            fresco:actualImageScaleType="fitCenter"
            fresco:placeholderImage="@drawable/nopic"
            fresco:placeholderImageScaleType="fitCenter"
            fresco:roundAsCircle="true" />

Adapter code :
----------------------


        holder.image.setImageResource(R.drawable.nopic);
        try {
            Uri imageUri = Uri.parse(URLUtilites.getInstance().urlProfilePic + singleton.getOwnerId() + "_" + empId + ".png");
            holder.image.setImageURI(imageUri);

        } catch (Exception e) {
            e.printStackTrace();

**Comment by venkypokala** [comment]
How to list item size around 2000

**Comment by defHLT** [comment]
If you are still experiencing the issue, could you share your adapter code and your Freco initialization code? Ideally a small sample that reproduces it.
