### ISSUE TITLE
app:preDebugBuild

### ISSUE THREAD

**Issue by satheeshkumar608** [facebook/fresco#2315]
What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.facebook.fresco:imagepipeline' has different version for the compile (1.10.0) and runtime (0.8.1) classpath. You should manually set the same version via DependencyResolution

**Comment by erikandre** [comment]
Hi @satheeshkumar608 

Try searching your project for any reference to "0.8.1" to see if there's more than one version of Fresco configured.
