### ISSUE TITLE
Dynamically Fressco Image preview  i try to close that preview but not closing that image

### ISSUE THREAD

**Issue by balakrishnaneprm** [facebook/fresco#2316]
Dynamically Fressco Image preview  i try to close that preview but not closing that image. How to close current preview image.

 new ImageViewer.Builder(context, ImageUrl)
                                .setStartPosition(0)
                                .hideStatusBar(true)
                                .allowZooming(true)
                                .allowSwipeToDismiss(true)
                                .setOnDismissListener(getDismissListener())
                                .setOverlayView(overlayView)
                                .setCustomDraweeHierarchyBuilder(hierarchyBuilder) //set Imageloader
                                .setImageChangeListener(getImageChangeListener())
                                .show();

**Comment by balakrishnaneprm** [comment]
Dynamically Fressco Image preview i try to close that preview but not closing that image. How to close current preview image. I tried not close that imageview. Please Give me any idea.

**Comment by balakrishnaneprm** [comment]
> Dynamically Fressco Image preview i try to close that preview but not closing that image. How to close current preview image.
> 
> new ImageViewer.Builder(context, ImageUrl)
> .setStartPosition(0)
> .hideStatusBar(true)
> .allowZooming(true)
> .allowSwipeToDismiss(true)
> .setOnDismissListener(getDismissListener())
> .setOverlayView(overlayView)
> .setCustomDraweeHierarchyBuilder(hierarchyBuilder) //set Imageloader
> .setImageChangeListener(getImageChangeListener())
> .show();

**Comment by balakrishnaneprm** [comment]
Hi
    implementation 'com.facebook.fresco:fresco:1.11.0'
    implementation 'com.github.stfalcon:frescoimageviewer:0.5.0'
Use above libray not close current imageview when onclick. How to solve this one

Dynamically Fressco Image preview i try to close that preview but not closing that image. How to close current preview image.

new ImageViewer.Builder(context, ImageUrl)
.setStartPosition(0)
.hideStatusBar(true)
.allowZooming(true)
.allowSwipeToDismiss(true)
.setOnDismissListener(getDismissListener())
.setOverlayView(overlayView)
.setCustomDraweeHierarchyBuilder(hierarchyBuilder) //set Imageloader
.setImageChangeListener(getImageChangeListener())
.show();

**Comment by defHLT** [comment]
I'm not sure about your question, but it seems to be related more to https://github.com/stfalcon-studio/FrescoImageViewer library than to Fresco itself.
