### ISSUE TITLE
setDecodeMemoryFileEnabled

### ISSUE THREAD

**Issue by Iamrookie** [facebook/fresco#2317]
I upgraded to 1.10.0 in fresco 0.12.0 and could not find the method setDecodeMemoryFileEnabled

**Comment by defHLT** [comment]
It was removed quite some time ago: https://our.intern.facebook.com/intern/diff/D3995313/
You could say it's enabled by default now.

Just try removing the call to it. Please comment if you have any issues with that.

**Comment by Iamrookie** [comment]
Page cannot be displayed
The link may be corrupted or the page has been removed

> It was removed quite some time ago: https://our.intern.facebook.com/intern/diff/D3995313/
> You could say it's enabled by default now.
> 
> Just try removing the call to it. Please comment if you have any issues with that.

Page cannot be displayed
The link may be corrupted or the page has been removed.

**Comment by defHLT** [comment]
Hi lambrookie! I think you should be fine just removing this call. This options was removed long time ago.

**Comment by Iamrookie** [comment]
> Hi lamrookie! I think you should be fine just removing this call. This options was removed long time ago.

Ok, but the new version is now calling this method, not found.
