### ISSUE TITLE
Feature request; compliance to "R.Drawable"

### ISSUE THREAD

**Issue by chjan** [facebook/fresco#2319]
The current  API introduces an extra layer of complexity compared against default Android API. The suggestion is to replace this:

```
Uri uri = Uri.parse("res:///" + R.drawable.xxx);
draweeView.setImageURI(uri);
```

with this:

`draweeView.setImage(R.drawable.xxx);`

And similar, enable the same API as granted by Android, e.g. like this:

`draweeView.setColorFilter(…,...);` 

IOW, hide away the complex hierarchy builder for elementary features, while keeping it of course for advanced configurations.

Your  comment?

**Comment by defHLT** [comment]
Thanks for your suggestions!

> draweeView.setImage(R.drawable.xxx);
There's a method with the same functionality in `SimpleDraweeView`: `setActualImageResource`. Arguably the naming could be better :)

As for your second suggestion, I think the following should work as expected?
```
    PorterDuffColorFilter colorfilter = new PorterDuffColorFilter(Color.RED, PorterDuff.Mode.ADD);
    simpleDraweeView.setColorFilter(colorfilter);
```

**Comment by AikoKiko** [comment]
In documentation : SimpleDraweeView#setImageURI(Uri uri, @Nullable Object callerContext) 
caller : null or metadata String TAG type
Additionally you can use: 
val uriPath = arrayList!![position].getUrl()
draweeView.setImageURI(uriPath)
