### ISSUE TITLE
After I finished the gif animation, I didn’t display the image.

### ISSUE THREAD

**Issue by Iamrookie** [facebook/fresco#2327]
After loading the gif animation, setting the local resource image does not display！
Listening has execution

public void setResImg(Context context, SimpleDraweeView ivCar) {
        Uri uri = Uri.parse("res://" + context.getPackageName() + "/" + R.drawable.shopping_status_img);
        ImageLoader.loadImages(uri, ivCar);
    }

BaseControllerListener<ImageInfo> mControllerListener = new BaseControllerListener<ImageInfo>() {

        @Override
        public void onFinalImageSet(String id, @Nullable ImageInfo imageInfo, @Nullable Animatable animatable) {
//                super.onFinalImageSet(id, imageInfo, animatable);
            if (animatable != null) {
                if (!animatable.isRunning()) {
                    animatable.start();
                }
                AnimatedDrawable2 animatedDrawable2 = (AnimatedDrawable2) animatable;
//                mAnimation = animatedDrawable2;
                animatedDrawable2.setAnimationListener(new AnimationListener() {
                    @Override
                    public void onAnimationStart(AnimatedDrawable2 drawable) {
                        Log.e(TAG, "onAnimationStart()");
                    }

                    @Override
                    public void onAnimationStop(AnimatedDrawable2 drawable) {
                        Log.e(TAG, "onAnimationStop()");
//                        ImageLoader.loadImageRes(mContext, R.drawable.shopping_status_img, mEndView);
                        setResImg(mContext, mEndView);
                    }

                    @Override
                    public void onAnimationReset(AnimatedDrawable2 drawable) {
                        Log.e(TAG, "onAnimationReset()");
                    }

                    @Override
                    public void onAnimationRepeat(AnimatedDrawable2 drawable) {
                        Log.e(TAG, "onAnimationRepeat()");
//                        ImageLoader.loadImageRes(mContext, R.drawable.shopping_status_img, mEndView);
                        setResImg(mContext, mEndView);

                    }

                    @Override
                    public void onAnimationFrame(AnimatedDrawable2 drawable, int frameNumber) {
                        Log.e(TAG, "onAnimationFrame()");
                    }
                });

            }

        }
    };

**Comment by oprisnik** [comment]
What are you trying to achieve and what's not working? From your question it is not clear. How can we reproduce the issue in our Showcase sample application?

**Comment by Iamrookie** [comment]
> What are you trying to achieve and what's not working? From your question it is not clear. How can we reproduce the issue in our Showcase sample application?

@oprisnik  How to play gif animation in fresco1.10.0 and play it once ？
