### ISSUE TITLE
Gif animation only plays once on fresco 1.10.0

### ISSUE THREAD

**Issue by Iamrookie** [facebook/fresco#2328]
Gif animation only plays once on fresco 1.10.0

**Comment by Crysis21** [comment]
why don't you use the latest version?!

**Comment by Iamrookie** [comment]
> why don't you use the latest version?!

Have problems, don’t use them early

**Comment by Iamrookie** [comment]
> why don't you use the latest version?!

@Crysis21   How to achieve animation only once ?

**Comment by oprisnik** [comment]
Do you have the GIF? How are you loading images? There are GIFs that have a loop count of 1, which would result in this behavior.

**Comment by Iamrookie** [comment]
1.10.0 How to set the number of loops  ？
