### ISSUE TITLE
Recyclerview scrolls slowly

### ISSUE THREAD

**Issue by Scorpiolol** [facebook/fresco#2329]
Hi  I'm Android TV devloper.
When I was using Fresco, when I didn't load the picture, RecyclerView scrolled very fast. But at after I loaded the picture, the scrolling speed decreased obviously. What is the reason? How to solve it? 

Thank

**Comment by songsong0218** [comment]
I think it should be that your picture is too big, or there are too many pictures displayed on the interface, which consumes a lot of memory on the phone. If this is the case, you can let your server compress the image or control the size of the uploaded image.




------------------ 原始邮件 ------------------
发件人: "Scorpiolol"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 下午2:44
收件人: "facebook/fresco"<fresco@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [facebook/fresco] Recyclerview scrolls slowly (#2329)




Hi  I'm Android TV devloper.
 When I was using Fresco, when I didn't load the picture, RecyclerView scrolled very fast. But at after I loaded the picture, the scrolling speed decreased obviously. What is the reason? How to solve it?
 
Thank

**Comment by Scorpiolol** [comment]
I do have many pictures, but the quality is not very good. Each picture is between 30KB and 200KB.
In addition, does Fresco loading pictures really affect the sliding speed of RecyclerView? I did not find this situation with glide. But Fresco's loading speed makes me fondle admiringly.

**Comment by songsong0218** [comment]
The picture I can see on one page here is about ten. The picture quality is similar to yours. It is still smoother to slide.How about your mobile phone, if it will affect performance a long time ago, my mobile phone is android 7.0.




------------------ 原始邮件 ------------------
发件人: "Scorpiolol"<notifications@github.com>; 
发送时间: 2019年4月18日(星期四) 下午3:17
收件人: "facebook/fresco"<fresco@noreply.github.com>; 
抄送: "松"<593941160@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [facebook/fresco] Recyclerview scrolls slowly (#2329)




I do have many pictures, but the quality is not very good. Each picture is between 30KB and 200KB.
 In addition, does Fresco loading pictures really affect the sliding speed of RecyclerView? I did not find this situation with glide. But Fresco's loading speed makes me fondle admiringly.

**Comment by Scorpiolol** [comment]
I am Android TV, so the device performance is not very good, but Android version is 6.0. The memory is 2G and the chip is MStart848.

I have 10-20 pictures per page. After loading the picture, due to the memory cache, when sliding up and down, you can see that the picture has been loaded and displayed. However, I can feel that the speed of sliding up and down is slower than before, which makes me confused.

**Comment by oprisnik** [comment]
My guess is that your images are quite big. Even if the encoded size is only 30-200KB, the bitmap can be huge depending on the image (e.g. a single 1000x1000px bitmap has 4MB). Ideally, you would supply small images that fit the viewport (you can enable the Fresco debug overlay for that or add logging) and if that's not possible, you can try resizing the image.

**Comment by Scorpiolol** [comment]
Why does glide not have this kind of situation? Is it because Fresco has any special mechanism and I don't have it?
Can I solve the problem of slow sliding speed after loading pictures by means other than picture size?
thanks~
