### ISSUE TITLE
Create animated webP using fresco

### ISSUE THREAD

**Issue by didi789** [facebook/fresco#2331]
There is any way to create animated webP/gif using fresco?

**Comment by oprisnik** [comment]
Hey @didi789. Fresco is used to *display* images, so we don't offer the option to create animated WebPs and GIFs. However, under the hood, we use a native GIF / WebP library on versions that don't natively support these formats, so you could make use of these libraries.

In general, we open sourced Spectrum for client-side image transcoding (https://github.com/facebookincubator/spectrum) that might be better suited for this task.

**Comment by didi789** [comment]
Unfortunately, I can't see an option to create using Spectrum animated webp.
