### ISSUE TITLE
Can Fresco support gif of the round corner?

### ISSUE THREAD

**Issue by Ternence** [facebook/fresco#2333]
### Description

I found Fresco can't support the circle gif animation. It'll turn automatically around the corner. 

### Reproduction

Code: 
`    implementation 'com.facebook.fresco:fresco:1.13.0'
    implementation 'com.facebook.fresco:animated-gif:1.13.0'
    implementation 'com.squareup.okhttp3:okhttp:3.14.1'
    implementation 'com.facebook.fresco:animated-base-support:1.2.0'
`

`
 String img = "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1556189728318&di=ca8aed726c896aab73737bfac2f5dc0a&imgtype=0&src=http%3A%2F%2Fb3-q.mafengwo.net%2Fs12%2FM00%2F82%2FCA%2FwKgED1vEWRWAJLESAA7orkxbTts940.gif%3FimageMogr2%2Fthumbnail%2F%2521440x260r%2Fgravity%2FCenter%2Fcrop%2F%2521440x260%2Fquality%2F100";

        navView.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
        SimpleDraweeView simpleDraweeView = (SimpleDraweeView) findViewById(R.id.aiapps_guide_image);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(img)
                .setAutoPlayAnimations(true)
                .build();
        simpleDraweeView.setController(controller);
`

 <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/aiapps_guide_image"
        android:layout_width="345dp"
        android:layout_height="496dp"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:scaleType="centerCrop"
        fresco:roundBottomRight="false" 
        fresco:roundTopEnd="true"
        fresco:roundTopLeft="true" 
        fresco:roundTopRight="true"
        fresco:roundTopStart="true"
        fresco:roundedCornerRadius="12dp"/>

![image](https://user-images.githubusercontent.com/2890392/56720540-a8108400-6775-11e9-93b5-36412b0fcd45.png)

### Solution

How can I fix this?  Which class may relate to this module? Maybe I can solve it.

### Additional Information

* Fresco version: 1.13.0
* Platform version: Android 8.1

**Comment by lambdapioneer** [comment]
Hi @Ternence,

this is a known limitation for animated images. @oprisnik, can you chime in if this will be addressed with v2, or if there's a preferred location to make changes?

Best, Daniel

**Comment by oprisnik** [comment]
Yeah, this is quite tricky to implement. One way would be to extend RoundedBitmapDrawable / RoundedDrawable to support AnimatedDrawable2 - or to just draw a colored outline outside the circle, which you can achieve by just using RoundedCornersDrawable and a custom DrawableFactory (or changing ExperimentalBitmapAnimationDrawableFactory)

**Comment by oprisnik** [comment]
I'm going to close this issue since we already have #2087 for this feature.
