### ISSUE TITLE
Android gradle plugin 3.4.0 and 5.1.1 gradle caused fresco package or class not found

### ISSUE THREAD

**Issue by hbzhzw** [facebook/fresco#2334]
### Description
When updated android gradle plugin to 3.4.0 and gradle version to 5.1.1, 
android build tools to 28.0.3, then found the following error:

error: package com.facebook.imagepipeline.animated.base does not exist
import com.facebook.imagepipeline.animated.base.AnimatedImage;
                                                                                         

### Additional Information

* Fresco version: 1.13.0

**Comment by lambdapioneer** [comment]
Hi @hbzhzw , can you provide the exact dependencies in your gradle file?

Does it work after adding `com.facebook.fresco:animated-base:1.13.0`?

**Comment by hbzhzw** [comment]
after add com.facebook.fresco:animated-base:1.13.0,  it works now.... thanks

**Comment by illwiz** [comment]
I add fresco animated webp in gradle but i can't access AnimatedDrawable2 class, looking in external library dependency there's no animated-base dependency, fixed by manually add `com.facebook.fresco:animated-base` dependency in gradle
