### ISSUE TITLE
FRESCO Issue with Android 9

### ISSUE THREAD

**Issue by tiltsan** [facebook/fresco#2336]
All the fresco code was working fine till arrival of Android 9.
With android 9, the placeholder and error images are pixelated
--- 

### Description
The placeholder image and error images are pixelated. I have defined the width and height of the layout in xml. The actual image size larger than the defined bounds. I have tried all scale types. The image displayed in small size at top left corner and rest of the layout is filled with pixelated colors. 

Similar types of problems are being reported with Android 9 but suggested solution do not work for me.

### Reproduction
this is my layout
`<com.facebook.drawee.view.SimpleDraweeView
                android:layout_width="250dp"
                android:layout_height="320dp"
                android:id="@+id/cal_month"
                app:roundingBorderColor="@color/homeGradTwo"
                app:roundingBorderWidth="2dp"
                android:layout_gravity="center"/>`

and this is my java code
`final SimpleDraweeView draweeView = (SimpleDraweeView)findViewById(R.id.cal_month);
        draweeView.getHierarchy().setPlaceholderImage(R.drawable.back1, ScalingUtils.ScaleType.FIT_XY);
        draweeView.getHierarchy().setFailureImage(R.drawable.err, ScalingUtils.ScaleType.FIT_XY);`

### Solution
Not yet known

### Additional Information

* Fresco version: 1.13.0
* Platform version: android P

**Comment by ZumaLuma** [comment]
Same issue, Version 1.13.0 doesn't have changes between 1.12.1. File RoundingParams doesn't have mPaintFilterBitmap 
![android  ~:Projects:android  - ~: gradle:caches:modules-2:files-2 1:com facebook fresco:drawee:1 13 0:1299ee4b44abe47a0d5c0829c… 2019-05-07 10-52-59](https://user-images.githubusercontent.com/45362279/57275043-aa000e80-70b6-11e9-9ef6-67d73dcf039a.png)
![fresco:RoundingParams java at 6d3a538525d2eab10bd59400ee1fcaf9569bdf79 · facebook:fresco 2019-05-07 10-54-25](https://user-images.githubusercontent.com/45362279/57275047-ad939580-70b6-11e9-81de-36c8e956708a.png)

**Comment by erikandre** [comment]
Hi @tiltsan 

This looks like the same issue reported here: https://github.com/facebook/fresco/issues/2293
It was fixed in this pull-request but you need to change one options in rounding params:
https://github.com/facebook/fresco/pull/2294/files by calling setPaintFilterBitmap(true)

**Comment by RupBarad** [comment]
@oprisnik @erikandre @loe @tiltsan @dreiss 
The placeholder image and error images are pixelated. The image displayed in small size at top left corner and rest of the layout is filled with pixelated colors.

Similar types of problems are being reported with Android 9 but suggested solution do not work for me.

Additional Information
Fresco version: 2.4.0
Android version: 9

My java code:


private void setImage(Context mContext, SimpleDraweeView imageView, String path, int color, int imageSize, boolean isTeam)
{

        try {
            if(!path.isEmpty()) {
                int drawable = R.drawable.ic_android_user_profile;
                if(isTeam){
                    drawable = R.mipmap.ic_team_profile;
                }

                //path = path+"abc";
                //Resize image
                resizeOptions = new ResizeOptions(imageSize, imageSize);
                request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(path))
                        .setResizeOptions(resizeOptions)
                        .build();

                //Round shape
                roundingParams = RoundingParams.fromCornersRadius(1f);
                roundingParams.setRoundAsCircle(true);
                if(color != -1) {
                    roundingParams.setOverlayColor(color);
                }
                roundingParams.setCornersRadius(1f);
                roundingParams.setBorder(mContext.getResources().getColor(R.color.rounded_border), 1f);
                roundingParams.setPaintFilterBitmap(true);

                GenericDraweeHierarchyBuilder genericDraweeHierarchyBuilder = GenericDraweeHierarchyBuilder.newInstance(mContext.getResources());
                genericDraweeHierarchyBuilder.setActualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP);
                genericDraweeHierarchyBuilder.setFadeDuration(500);
                genericDraweeHierarchyBuilder.setFailureImage(drawable);
                genericDraweeHierarchyBuilder.setFailureImageScaleType(ScalingUtils.ScaleType.CENTER_CROP);
                genericDraweeHierarchyBuilder.setPlaceholderImage(drawable);
                genericDraweeHierarchyBuilder.setPlaceholderImageScaleType(ScalingUtils.ScaleType.CENTER_CROP);
                genericDraweeHierarchyBuilder.setRoundingParams(roundingParams);
                GenericDraweeHierarchy hierarchy = genericDraweeHierarchyBuilder.build();
                imageView.setHierarchy(hierarchy);

                //Drawer controller
                draweeController = Fresco.newDraweeControllerBuilder()
                        .setImageRequest(request)
                        .setOldController(imageView.getController())
                        .build();
                imageView.setController(draweeController);
            }
            else {
                if(isTeam){
                    imageView.setImageResource(R.mipmap.ic_team_profile);
                }else {
                    imageView.setImageResource(R.mipmap.cir_img_profile);
                }
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }

- This problem come when image url wrong. 

screenshot:

<img width="316" alt="Screenshot 2021-04-05 at 3 24 57 PM" src="https://user-images.githubusercontent.com/63725999/113562345-90a9c900-9623-11eb-83f2-ccd9e386c712.png">


please guide me. It would be great help for me.

**Comment by RupBarad** [comment]
I found that the error images are pixelated in android 9 PI for **image file**. This problem come when url wrong. I Resolved it by **vector drawable image**. User vector drawable image instead of image file. 

like 
 drawable = R.drawable.ic_android_team_profile;   //vector drawable file

(you can see above commented code for more information)

**Comment by evening424** [comment]
@RupBarad Change the placeholderImage to 9-patch file and set the scale as you want. Can temporarily solve this problem
