### ISSUE TITLE
fresco doesn't support to play APNG dynamic

### ISSUE THREAD

**Issue by hply** [facebook/fresco#2337]
fresco doesn't support to play APNG dynamic；
for example : https://d17qpog9ccnbkb.cloudfront.net/v5res/vova/2018-12-20/images/banners/0yuangou/0yuangou.png

**Comment by erikandre** [comment]
Hi @hply 

Please see the response in #1749 
We are not planning to add support for APNG. If we possible I would recommend using other formats for animations (like GIF or animated WEBP)

**Comment by oprisnik** [comment]
In addition to that, Fresco does support custom decoders, so you could just plug in a library that's able to handle APNG, see https://frescolib.org/docs/customizing-image-formats.html. Pull requests that add this to our sample app (probably should not be part of the main library) are welcome.
