### ISSUE TITLE
NullPointException 

### ISSUE THREAD

**Issue by weiweiForAndroid** [facebook/fresco#2347]
in my project, I got the exception:Attempt to read from field 'java.lang.Object.com.facebook.stetho.inpector.elements.ElementInfo.parentElement' on a null object reference
 at com.facebook.stetho.inpector.elements.ShadowDocument$Update.removeGarbageSubTree(ShadowDocument.java:378)

**Comment by oprisnik** [comment]
Hi! Please fill out the issue template. Are you using Fresco's Stetho plugin? When does this happen etc.

**Comment by weiweiForAndroid** [comment]
@oprisnik thanks, I will provide the details of stack message.
