### ISSUE TITLE
Use current image as placeholder for next

### ISSUE THREAD

**Issue by csechuan** [facebook/fresco#236]
Is there anyway to set current actual image as placeholder for the next image request?
I want to achieve something like photo gallery / carousel in the website, slide through images seamlessly. The only difference is that they are using preset images while my app needs to load images from network. I know this hack isn't a perfect solution as the animation will play in between switches of images, which completely defeat the meaning of seamless. My next question is any other approach for achieving this?

**Comment by tyronen** [comment]
You can use the [low-res/high-res scheme](http://frescolib.org/docs/requesting-multiple-images.html#going-from-low-to-high-resolution) for this purpose. Despite the name, the low-res request can be for any image; it will be the placeholder for the 'main' request.
