### ISSUE TITLE
Using disableMemoryCache causes crash: Error, cannot access an invalid/free'd bitmap here!

### ISSUE THREAD

**Issue by snepalnetflix** [facebook/fresco#2361]
### Description

Using disableMemoryCache() causes a crash.

It's not clear how to use the returned bitmap from BaseBitmapDataSubscriber.onNewResultImpl if disableMemoryCache is specified.

If the bitmap is used after a delay, it results in a crash. See attached log.

### Reproduction

A simple way to reproduce this bug is to patch ImagePipelineNotificationFragment and add disableMemoryCache(). If a delay is added to before calling displayNotification() then it results in a crash.

### Solution

If the solution is to not use BaseBitmapDataSubscriber and instead hold onto the reference then maybe the documentation should be updated?

Patch to sample app: https://pastebin.com/raw/SvdGvSa5
Logcat: https://pastebin.com/raw/8sHVK3TB

**Comment by snepalnetflix** [comment]
> You may also label this issue as "bug" or "enhancement" and I will leave it open
I don't seem to have rights to do that.

It would be great if this issue wasn't closed. I'm still struggling to find the right way to keep a reference to the bitmap

**Comment by oprisnik** [comment]
As to the documentation, the bitmap in BaseBitmapDataSubscriber is only guaranteed to be around for the lifespan of the callback method: https://github.com/facebook/fresco/blob/5d419bcc450bd0e4fbc27546e94ac55ad20a3e60/imagepipeline/src/main/java/com/facebook/imagepipeline/datasource/BaseBitmapDataSubscriber.java#L67

You should use a BaseBItmapReferenceDataSubscriber to hold on to the reference until it's no longer needed: https://frescolib.org/docs/closeable-references.html
