### ISSUE TITLE
SimpleDraweeView fadeDuration set to 0,fade animation still exist

### ISSUE THREAD

**Issue by Aeiric** [facebook/fresco#2366]
### Description

I have set fadeDuration to 0 in xml of SimpleDraweeView,but fade animation still exists when when image chages

**Comment by oprisnik** [comment]
I cannot reproduce this with our sample app. I add `app:fadeDuration="0"` for our simple Drawee sample: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/res/layout/fragment_drawee_simple.xml#L13

It doesn't fade.

**Comment by Aeiric** [comment]
@oprisnik when show just one bitmap ,fade not very obviously. When show many bitmaps one after one with same SimpleDraweeView ,fade obviously~

**Comment by oprisnik** [comment]
Can you give a code example? Everything works fine for me.

**Comment by shaohui10086** [comment]
@Aeiric  Maybe I understand your problem, because I  also have this problem just now. But I find it not the Fresco bug. But my default recyclerView.ItemAnimator cause this problem.

**Comment by buptmaster** [comment]
> @Aeiric Maybe I understand your problem, because I also have this problem just now. But I find it not the Fresco bug. But my default recyclerView.ItemAnimator cause this problem.

counter similar problem here. I use view.draw(canvas) to generate pictures of current view and have to call setItemAnimator(null) to prevent simpleDraweeView not loading pictures.
