### ISSUE TITLE
How should I use ResizeOptions on a network image

### ISSUE THREAD

**Issue by FreeTotoro** [facebook/fresco#2368]
### Description
The question is ,I want to rewrite the maxBitmapSize to load big images. But width and height are needed.While I use SimpleDraweeView.setImageUri to load image. So what should do to make it?

public void setImageURI(String uri) {
        this.uri = uri;
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
                .setResizeOptions(new ResizeOptions(?,?,4096))
                .build();
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setImageRequest(request)
                .setOldController(getController())
                .setControllerListener(new ImageControllerListener())
                .build();
        setController(controller);

**Comment by oprisnik** [comment]
What exactly are you trying to achieve? Resize all images that are bigger than a given dimension?

**Comment by defHLT** [comment]
@FreeTotoro For now you could just specify sufficiently large value for width and height. `maxBitmapSize` would take precedence then. For instance: `.setResizeOptions(new ResizeOptions(Integer.MAX_VALUE, Integer.MAX_VALUE, 4096))` or `.setResizeOptions(new ResizeOptions(4096, 4096, 4096))`

**Comment by FreeTotoro** [comment]
> @FreeTotoro For now you could just specify sufficiently large value for width and height. `maxBitmapSize` would take precedence then. For instance: `.setResizeOptions(new ResizeOptions(Integer.MAX_VALUE, Integer.MAX_VALUE, 4096))` or `.setResizeOptions(new ResizeOptions(4096, 4096, 4096))`

You got me.And it works.Thank you very much!
