### ISSUE TITLE
Fast Thumbnails

### ISSUE THREAD

**Issue by wordlessly** [facebook/fresco#2370]
To get a thumbnail you need to decode the full picture and then scale it to thumbnail size. To overcome this obstacle the jpeg-format allows you to get a picture 1/2, 1/4, 1/8 or even 1/16 in size of the original picture. E.g. for a factor 1/8, a 5000x5000 picture will be returned as a 625x625 picture. Java does NOT offer this functionality (C++ libs like ijg do).

For jpeg thumbnails you just need the DC components and skip all the AC components. This means you only have to decrypt the DC component. You still have to do the full Huffman decompression, but still it saves a hell lot of time, disk I/O, memory and exceptions.

Pure (but clever) Java, especially multi-threaded Java often beats native performance-wise. This lack of fast thumbnail support shaped the type of apps you could write with Java over the last 20 years. Fast thumbnails are ESSENTIAL!

Please implement!

**Comment by oprisnik** [comment]
Fresco does downsampling when you set it up and load an image with given resize options, see https://frescolib.org/docs/resizing.html.

**Comment by wordlessly** [comment]
Thanks! Very interesting. What I was describing is resizing or downsampling or both?

There is (1) scaling, (2) resizing and (3) downsampling. 

Are you using turobjpeg for (1) or is this just GPU scaling?

Let's assume you load images from local storage (i.e. pictures taked with the camera). For (2) and (3) you read the entire image file - or are you already doing some clever I/O to read only part of the bytes?

What exactly do you still need "native calls" for? Would it be too slow in pure Java? Do you have a pure Java fallback in case you want to execute it for platforms where the "native backend" does not exist? This would be really nice!

Can one use this library (or at least the resize/downsampling functionality) outside of Android? This would be really helpful if you could also use it just with the Java JRE. Or is it too much integrated with Android core elements?

**Comment by oprisnik** [comment]
For scaling, we use the Android system APIs.

For downsampling, we use inSampleSize: https://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inSampleSize

Re native code: We have it in multiple places: Backporting functionality (support for other image formats), transcoding to different formats etc. (you can just search for C / header files in the codebase). For some of them we have Java alternatives, for others we do not.

Fresco has lots of Android dependencies, so I don't think it's easy to reuse for non-Android environments.

I'm going to close this issue for now, but let me know if you have more questions.
