### ISSUE TITLE
null point at RotationOptions.disableRotation()

### ISSUE THREAD

**Issue by liujinchaoDS** [facebook/fresco#2371]
### Description

I get the NullPointException when disable rotation in loading a jpg file with rotation exif info.
The error is below:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.imageformat.ImageFormat com.facebook.imagepipeline.image.EncodedImage.getImageFormat()' on a null object reference
        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:119)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:764)
```

### Reproduction

The code is below:
```
val defaultImageRequest =
            ImageRequestBuilder.newBuilderWithResourceId(R.drawable.image_ic_exif)
                .setRotationOptions(RotationOptions.disableRotation())
                .build()
image_fresco_rotation_default.controller =
            Fresco.newDraweeControllerBuilder()
                .setImageRequest(defaultImageRequest)
                .build()
```
image_ic_exif is a jpg file with rotation info.

### Additional Information

* Fresco version: v2.0.0
* Platform version: Android 9

**Comment by liujinchaoDS** [comment]
Please test with this pic
![image_ic_exif](https://user-images.githubusercontent.com/8395162/60763973-3ed0b980-a0b2-11e9-8825-1d6f34e2a4cb.jpg)

**Comment by defHLT** [comment]
@liujinchaoDS I couldn't reproduce with provided image on Android 9 device. Are you using default image pipeline configuration or something more specific?

**Comment by liujinchaoDS** [comment]
Please refer this project: https://github.com/liujinchaoDS/FrescoRotation

**Comment by liujinchaoDS** [comment]
Please refer to this project: https://github.com/liujinchaoDS/FrescoRotation.
In this code, I load the same drawable into two drawee, and the first with RotationOptions.disableRotation(), and the last with RotationOptions.autoRotate(). 
This will cause a NullPointException.But I change the call order, that is the first is autoRotate, the last is disableRotation. This will load success and without exception. Why?

**Comment by defHLT** [comment]
@liujinchaoDS That was super helpful! Thanks. I can repro now. The fix is on the way.

**Comment by defHLT** [comment]
@liujinchaoDS Should be fixed now. Can you confirm please?

**Comment by liujinchaoDS** [comment]
@defHLT Yes, It works.

**Comment by defHLT** [comment]
Thanks for reporting and providing a sample app!
