### ISSUE TITLE
更改了屏幕密度值后，fresco加载图片显示不正确。

### ISSUE THREAD

**Issue by bingdiao** [facebook/fresco#2375]
调整了设备页面的displayMetrics.density属性值，比如设备原先该值为2，项目有需要我统一调为了3，却发现Fresco框架的SimpleDraweeView控件原先加载正常的图片此时会加载变形，有什么方法/配置可以让SimpleDraweeView控件适应页面新的displayMetrics.density值么？

**Comment by defHLT** [comment]
Looks like it's a duplicate of #2376

**Comment by nodzhang** [comment]
解决了嘛？
