### ISSUE TITLE
Android Q open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by Rogero0o** [facebook/fresco#2378]
### Description

Run in Android Q beta 5 and use the URI from MediaStore but the image will not show.

### Reproduction

Load image path from MediaStore and use the path to generate URI, then put it into the ImageRequest.

### Solution

"resolver.openFileDescriptor(item, mode)" Maybe use this will help?

### Additional Information

* Fresco version: last
* Platform version: Android Q beta 5

**Comment by beatrizz** [comment]
I am also experiencing this problem

**Comment by oprisnik** [comment]
This should be fixed with ffab15c80a2c91a2618dbfd40e05f560f58ea8c9

Thanks @Rogero0o !

**Comment by beatrizz** [comment]
The fix for this issue is merged into master and it's needed for Fresco (and apps that use Fresco) to work well in Android 10, which has just been released. Is there going to be a Fresco release with this fix soon? Thank you!

**Comment by oprisnik** [comment]
We're working on making SoLoader optional, which is almost ready. Once that's merged, we'll do a release.

**Comment by beatrizz** [comment]
Thanks! Looking forward to it

**Comment by hassankalhoro** [comment]
add this in your application tag 
android:requestLegacyExternalStorage="true"
by default it is false

**Comment by oprisnik** [comment]
You should also be able to use jitpack.io to include a newer Fresco version I suppose.

**Comment by kesha-antonov** [comment]
> add this in your application tag
> android:requestLegacyExternalStorage="true"
> by default it is false

Finally!
Thanks
I spent a day trying to figure out why images not showing after getting them with https://github.com/react-native-community/react-native-cameraroll
