### ISSUE TITLE
Can you tell me config disk cache directory? I use fresco on viewPager, but only cache last image to disk every time.

### ISSUE THREAD

**Issue by ancode-cn** [facebook/fresco#238]
Context context = getApplicationContext();
        DiskCacheConfig diskCacheConfig =  DiskCacheConfig.newBuilder()//
                .setBaseDirectoryPath(new File(Environment.getExternalStorageDirectory().getAbsoluteFile(),getPackageName()))
                .setBaseDirectoryName("image")
                .build();
        ImagePipelineConfig imagePipelineConfig = ImagePipelineConfig.newBuilder(context)//
                .setMainDiskCacheConfig(diskCacheConfig)
                .build();
        Fresco.initialize(context,imagePipelineConfig);

**Comment by IanChilds** [comment]
Please also set a size for your cache using `setMaxCacheSize`
