### ISSUE TITLE
How to region decode a huge image ?

### ISSUE THREAD

**Issue by youshuang** [facebook/fresco#2386]
### Description

In my app , it sometimes happens an OOM crash when decode a huge image , I want to region decode the image just when the image is big enough and the format is PNG /JPEG
, and reponsed to touch events to change the  region, after reading the source, I did not find a way to achieve this, what should I do ?

OOM stack :
'java.lang.OutOfMemoryError: Failed to allocate a 529212 byte allocation with 175512 free bytes and 171KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
at com.facebook.imagepipeline.memory.BitmapPool.alloc
at com.facebook.imagepipeline.memory.BitmapPool.alloc
at com.facebook.imagepipeline.memory.BasePool.retryOnce
at com.facebook.imagepipeline.memory.BasePool.retryOnce
at com.facebook.imagepipeline.memory.BasePool.get
at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream
at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage
at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg
at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode
at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200
access$400
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run
at com.facebook.imagepipeline.producers.JobScheduler.doJob
at com.facebook.imagepipeline.producers.JobScheduler.access$000
at com.facebook.imagepipeline.producers.JobScheduler$1.run
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SearchBox:51)
at java.lang.Thread.run(Thread.java:818)

**Comment by youshuang** [comment]
the stack is to allocate a 529212 byte memory, it may be a more larger number when decode a hug image, may be 9529212, maybe the main reason is the app use too much memory in other scenes , but allocate 10m memory one time is not reasonable, so I need region decode the image

**Comment by oprisnik** [comment]
You can find an example for region decoding with the Fresco image pipeline here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/ImagePipelineRegionDecodingFragment.java

**Comment by youshuang** [comment]
I know that from the showcase, but that can't meet my requirement.If I define myself decoder, I have to also decode webp, animated webp , gif and so on.
 In the method ImagePipelineRegionDecodingFragment.decode, I just hope to decode huge image and png/jpeg format. Now I can get a PlatformDecoder by Fresco.getImagePipelineFactory().getPlatformDecoder() which can help me to region decode. 
But when the encode image's format is webp or gif, I need to use fresco inner ImageDecoder to decode. In current situation is that  I can't get a  ImageDecoder because the Fresco.getImagePipelineFactory().getImageDecoder is a private method.   Can be public ? Maybe my implementation is trick, I also fresco can provide a mechanism for this needs.

**Comment by youshuang** [comment]
> You can find an example for region decoding with the Fresco image pipeline here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/ImagePipelineRegionDecodingFragment.java



> You can find an example for region decoding with the Fresco image pipeline here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/ImagePipelineRegionDecodingFragment.java



> You can find an example for region decoding with the Fresco image pipeline here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/ImagePipelineRegionDecodingFragment.java

I know that from the showcase, but that can't meet my requirement.If I define myself decoder, I have to also decode webp, animated webp , gif and so on.
In the method ImagePipelineRegionDecodingFragment.decode, I just hope to decode huge image and png/jpeg format. Now I can get a PlatformDecoder by Fresco.getImagePipelineFactory().getPlatformDecoder() which can help me to region decode.
But when the encode image's format is webp or gif, I need to use fresco inner ImageDecoder to decode. In current situation is that I can't get a ImageDecoder because the Fresco.getImagePipelineFactory().getImageDecoder is a private method.
Two ways to solve this in my opinion:
1、Fresco.getImagePipelineFactory().getImageDecoder can by public ?
2、When use a custom decoder, the custom decoder has privilege decide decoding or not , if not , don't return in DefaultImageDecoder#decode#
if (options.customImageDecoder != null) {
return options.customImageDecoder.decode(encodedImage, length, qualityInfo, options);
}
go on decoding work .

I will be pleasure that fresco can provide a mechanism for this needs.
