### ISSUE TITLE
Problems when using Maven

### ISSUE THREAD

**Issue by luccascorrea** [facebook/fresco#239]
I am using maven for dependency management and I added the library to my pom like so:

```
<dependency>
    <groupId>com.facebook.fresco</groupId>
    <artifactId>fresco</artifactId>
    <version>0.4.0</version>
</dependency>
```

However, I can't import com.facebook.drawee.view.SimpleDraweeView. I see that the only thing I can import is com.facebook.drawee.backends.pipeline.*

If I add <type>aar</type> it doesn't change anything. 

I also tried importing the aar files independently (fresco, fbcore, drawee and imagepipeline) but then I get an error like this when I run the app:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/imagepipeline/core/ImagePipelineFactory
```

I also get errors like this:

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/br.com.estudio89.rhmais-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmemchunk.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
at java.lang.System.loadLibrary(System.java:988)
at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:198)
at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
at bolts.Task$2.run(Task.java:195)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

Am I doing anything wrong? I am using Intellij IDEA by the way.

Thanks for the help

**Comment by tyronen** [comment]
You could add the individual artifacts to your .pom file, does that work?

**Comment by luccascorrea** [comment]
I tried it, like this:

	<dependency>
		<groupId>com.facebook.fresco</groupId>
		<artifactId>imagepipeline</artifactId>
		<version>0.4.0</version>
		<type>aar</type>
	</dependency>

	<dependency>
		<groupId>com.facebook.fresco</groupId>
		<artifactId>fbcore</artifactId>
		<version>0.4.0</version>
		<type>aar</type>
	</dependency>

	<dependency>
		<groupId>com.facebook.fresco</groupId>
		<artifactId>drawee</artifactId>
		<version>0.4.0</version>
		<type>aar</type>
	</dependency>


	<dependency>
		<groupId>com.facebook.fresco</groupId>
		<artifactId>fresco</artifactId>
		<version>0.4.0</version>
		<type>aar</type>
	</dependency>

But then I get the errors I mentioned in the first comment.

I found out that when I add only the com.facebook.fresco:fresco:0.4.0 library to my pom file, if I run **mvn clean compile** on the command line, I get this message:

    Failed to execute goal on project rhmais-android: Could not resolve dependencies for project br.com.estudio89:rhmais-android:apk:1.0-SNAPSHOT: The following artifacts could not be resolved: com.facebook.fresco:fbcore:jar:0.4.0, com.facebook.fresco:imagepipeline:jar:0.4.0, com.facebook.fresco:drawee:jar:0.4.0: 

What I can see is that, because the fresco library has fbcore, imagepipeline and drawee as dependencies, maven tries to load them but it tries to load them as jars, even though I specified `<type>aar</type>` in the pom file.

If then I add the individual artifacts separately, I still can't compile it from the command line (the same message is shown) but I can do it from Intellij, however the app crashes whenever the first drawee is shown, as I mentioned.

**Comment by liaohuqiu** [comment]
### The problem

The type in missing in all dependencies, for example:

fresco-0.4.0.pom

```
  <dependencies>
    <dependency>
      <groupId>com.facebook.fresco</groupId>
      <artifactId>imagepipeline</artifactId>
      <version>0.4.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.facebook.fresco</groupId>
      <artifactId>fbcore</artifactId>
      <version>0.4.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.facebook.fresco</groupId>
      <artifactId>drawee</artifactId>
      <version>0.4.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

Maven can not solve the dependency transitively. 

### The solution

And I can add the individual artifacts in my pom.xml and exclude them from **fresco**, like this way:

```
<dependency>
    <groupId>com.android.support</groupId>
    <artifactId>support-v4</artifactId>
    <version>21.0.3</version>
    <type>aar</type>
</dependency>

<!-- begin of fresco -->
<dependency>
    <groupId>com.facebook.fresco</groupId>
    <artifactId>fresco</artifactId>
    <version>0.4.0</version>
    <type>aar</type>
    <exclusions>
        <exclusion>
            <groupId>com.android.support</groupId>
            <artifactId>support-v4</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.facebook.fresco</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.facebook.fresco</groupId>
    <artifactId>fbcore</artifactId>
    <type>aar</type>
    <version>0.4.0</version>
</dependency>
<dependency>
    <groupId>com.facebook.fresco</groupId>
    <artifactId>drawee</artifactId>
    <type>aar</type>
    <version>0.4.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.android.support</groupId>
            <artifactId>support-v4</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.facebook.fresco</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.facebook.fresco</groupId>
    <artifactId>imagepipeline</artifactId>
    <type>aar</type>
    <version>0.4.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.android.support</groupId>
            <artifactId>support-v4</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.facebook.fresco</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<!-- end of fresco -->
```

### Conclusion

It works. But, looks ugly.

It seems that the libraries from android repository also have the same problem.

For example, the `appcompat-v7-21.0.3.pom`

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.android.support</groupId>
  <artifactId>appcompat-v7</artifactId>
  <version>21.0.3</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>support-v4</artifactId>
      <version>21.0.3</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by tyronen** [comment]
It looks like this is a bug in Gradle. The fix is to add '@aar' to the compile dependencies in the build.gradle files.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
