### ISSUE TITLE
When trying to upgrade gradle to 3.5.0, aminated-base.aar and aminated-drawable.aar not import.

### ISSUE THREAD

**Issue by fireantzhang** [facebook/fresco#2396]
1. build file import fresco like this:
![image](https://user-images.githubusercontent.com/5302051/63484917-f2abce00-c4d3-11e9-9427-df211ad56dd7.png)

2. if gradle version <= 3.2.1
![image](https://user-images.githubusercontent.com/5302051/63484969-271f8a00-c4d4-11e9-976a-c9e558fdace5.png)

3. but when gradle version = 3.5.0(Don't have animated-base-2.0.0.aar and animated-drawable-2.0.0.aar)
![image](https://user-images.githubusercontent.com/5302051/63484993-43232b80-c4d4-11e9-9b92-2340574a7059.png)

How to solve this problem, Waiting for your reply, thx.

**Comment by vlasquez** [comment]
Did you find any solution for this bug? its happening for me

**Comment by fireantzhang** [comment]
@vlasquez  Yes, already has a solution to this issue:
```
implementation 'com.facebook.fresco:fresco:2.0.0'
implementation 'com.facebook.fresco:imagepipeline-okhttp3:2.0.0'
implementation 'com.facebook.fresco:animated-gif:2.0.0'
implementation 'com.facebook.fresco:animated-webp:2.0.0'
implementation 'com.facebook.fresco:webpsupport:2.0.0'

// If the gradle version >= 3.5，should be add these two entries
implementation 'com.facebook.fresco:animated-base:2.0.0'
implementation 'com.facebook.fresco:animated-drawable:2.0.0'
```

I wish you good luck, enjoy coding.

**Comment by fireantzhang** [comment]
> Did you find any solution for this bug? its happening for me

@vlasquez Yes, already has a solution to this issue:
```
implementation 'com.facebook.fresco:fresco:2.0.0'
implementation 'com.facebook.fresco:imagepipeline-okhttp3:2.0.0'
implementation 'com.facebook.fresco:animated-gif:2.0.0'
implementation 'com.facebook.fresco:animated-webp:2.0.0'
implementation 'com.facebook.fresco:webpsupport:2.0.0'

// If the gradle version >= 3.5，should be add these two entries
implementation 'com.facebook.fresco:animated-base:2.0.0'
implementation 'com.facebook.fresco:animated-drawable:2.0.0'
```

I wish you good luck, enjoy coding.
