### ISSUE TITLE
androidx.appcompat.widget.AppCompatImageView cannot be cast to com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by Gintron** [facebook/fresco#2399]
### Description

I have a chat application and I want to show my images with fresco. I tried to initialize fresco in my chat activity but I`m getting still this error. I think the problem is that I have one layout for the chat activity but I also have 2 other layouts that are displaying the chat messages one is for the left(chat_item_right.xml, and chat_item_left.xml) messages and one is for the right messages. The SimpleDraweeView is in the chat_item_left. 

My chat_item_left.xml
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:layout_marginTop="0dp"
    android:padding="5dp"
    android:weightSum="10">

    <RelativeLayout
        android:layout_width="270dp"
        android:layout_height="wrap_content"
        android:layout_alignParentStart="true">

        <de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/profile_image"
            android:layout_width="36dp"
            android:layout_height="36dp"
            android:layout_alignParentStart="true"
            android:src="@mipmap/ic_launcher" />

        <TextView
            android:id="@+id/show_message"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="8dp"
            android:layout_toEndOf="@+id/profile_image"
            android:background="@drawable/background_left"
            android:padding="8dp"
            android:text="Message Text"
            android:textColor="#444444"
            android:textSize="18sp" />
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignStart="@+id/show_message"
            android:adjustViewBounds="true"
            android:layout_marginTop="5dp"
            >
        <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/chat_image"
        android:layout_width="200dp"
        android:layout_height="200dp"
        fresco:placeholderImage="@drawable/placeholder"
            android:layout_toRightOf="@id/chat_image"
            android:visibility="gone"
        />
        </LinearLayout>

        <TextView
            android:id="@+id/txt_seen"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@id/show_message"
            android:layout_alignParentStart="true" />
    </RelativeLayout>

</RelativeLayout>

`
This is the onCreate for the MessageActivity
This is calling the activityMessage layout but there I am not using fresco this is why I believe initializing i here did not worked 

`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_message);`

This is my MessageAdapter
`

public class MessageAdapter extends RecyclerView.Adapter<MessageAdapter.ViewHolder> {

    public static  final int MSG_TYPE_LEFT = 0;
    public static  final int MSG_TYPE_RIGHT = 1;

    private Context mContext;
    private List<Chat> mChat;
    private String imageurl;

    FirebaseUser fuser;

    public MessageAdapter(Context mContext, List<Chat> mChat, String imageurl){
        this.mChat = mChat;
        this.mContext = mContext;
        this.imageurl = imageurl;
    }

    @NonNull
    @Override
    public MessageAdapter.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {

        if (viewType == MSG_TYPE_RIGHT) {
            View view = LayoutInflater.from(mContext).inflate(R.layout.chat_item_right, parent, false);
            return new MessageAdapter.ViewHolder(view);

        } else  {
             //THIS IS WHERE FRESCO IS CALLED I JUST TRIED TO PUT IT ALSO HERE 
            Fresco.initialize(mContext);
            View view = LayoutInflater.from(mContext).inflate(R.layout.chat_item_left, parent, false);
            return new MessageAdapter.ViewHolder(view);
        }
    }

    @Override
    public void onBindViewHolder(@NonNull MessageAdapter.ViewHolder holder, int position) {
        Chat chat = mChat.get(position);
        String message_type = chat.getType();
        try{
            if(message_type.equals("image")){
                holder.show_message.setVisibility(View.GONE);
                holder.draweeView.setVisibility(View.VISIBLE);
                //Glide.with(mContext).load(chat.getMessage()).into(holder.sendImage);
                Uri uri = Uri.parse(chat.getMessage());
                holder.draweeView.setImageURI(uri);
            }
            else{
                holder.show_message.setText(chat.getMessage());
                holder.draweeView.setVisibility(View.GONE);
            }
        }catch (Exception e){

        }

        if (imageurl.equals("default")){
            holder.profile_image.setImageResource(R.mipmap.ic_launcher);
        } else {
            Glide.with(mContext).load(imageurl).into(holder.profile_image);
        }

        if (position == mChat.size()-1){
            if (chat.isIsseen()){
                holder.txt_seen.setText("Seen");
            } else {
                holder.txt_seen.setText("Delivered");
            }
        } else {
            holder.txt_seen.setVisibility(View.GONE);
        }

    }

    @Override
    public int getItemCount() {
        return mChat.size();
    }

    public  class ViewHolder extends RecyclerView.ViewHolder{

        public TextView show_message;
        public ImageView profile_image;
        public TextView txt_seen;
        public SimpleDraweeView draweeView;

        public ViewHolder(View itemView) {
            super(itemView);
            show_message = itemView.findViewById(R.id.show_message);
            profile_image = itemView.findViewById(R.id.profile_image);
            txt_seen = itemView.findViewById(R.id.txt_seen);
            //sendImage = itemView.findViewById(R.id.chat_image);
            draweeView =  itemView.findViewById(R.id.chat_image);
        }
    }

    @Override
    public int getItemViewType(int position) {
        fuser = FirebaseAuth.getInstance().getCurrentUser();
        if (mChat.get(position).getSender().equals(fuser.getUid())){
            return MSG_TYPE_RIGHT;
        } else {
            return MSG_TYPE_LEFT;
        }
    }

}
`
### Additional Information

'com.facebook.fresco:fresco:2.0.0'
enableJetifier=true

**Comment by oprisnik** [comment]
You must initialize Fresco before any layout is inflated, as for example in your `Application`, see https://frescolib.org/docs/
