### ISSUE TITLE
Multiple OkHttp support?

### ISSUE THREAD

**Issue by georgewhiz** [facebook/fresco#240]
My app requires the ability to download images with basic authentication.  Creating a new okhttpclient with proper headers isn't a problem, but how do I download from two different resources with different authentication?  Is there a way for me to get a reference to the okhttp client so i can modify the headers?  Or do I have to create two separate imagepipelineconfigs and call Fresco.initialize every time to switch between the clients?  Or is there a more elegant way?

Thanks for the help!

-George

**Comment by xu6148152** [comment]
volley + okhttp

**Comment by georgewhiz** [comment]
Sorry, I don't understand.  If I use volley, i call initialize on the draweeview itself; but if the view is in a recycler, wouldn't it get very expensive to initialize quickly?  And don't i lose okhttp support since I'm not supposed to call fresco.initialize with volley per http://frescolib.org/docs/using-other-image-loaders.html#

Slightly lost at the suggestion.  Thanks

**Comment by tyronen** [comment]
When configuring the image pipeline [to use OkHttp](http://frescolib.org/docs/using-other-network-layers.html#using-okhttp) you pass it the OkHttpClient. You can hold onto that reference and call any of its methods whenever you need to.

**Comment by jeprojects** [comment]
@georgewhiz Did you manage to solve this? We are looking at doing the exact same thing..

**Comment by loctran106** [comment]
@jeprojects

Not really.  That project didn't get very far.  With OkHTTP 3 out, hoping
fresco gets updated and then I'll revisit the issue.
