### ISSUE TITLE
[Bug] Android app doesn't display ANY image after adding Fresco in React Native 0.59.9

### ISSUE THREAD

**Issue by canpoyrazoglu** [facebook/fresco#2401]
### Description

My React Native app was working perfectly until I needed GIF support in Android. I've added Fresco and no images are (even existing JPEGs and PNGs that used to display before adding Fresco) are displayed (they're just blank) and I'm getting many errors about `com.facebook.imagepipeline.nativecode.NativeJpegTranscoderFactory` not found.

### Reproduction

 - Have a React Native project. (0.59.9)
 - Add the following to `build.gradle`:

`implementation 'com.facebook.fresco:animated-gif:1.12.0'`

 - Sync the project.

### Additional Information

* Fresco version: 1.12
* Platform version: Android 8.1

I've also seen https://github.com/facebook/fresco/issues/2238 but I don't understand the solution or what to do.

**Comment by oprisnik** [comment]
Does it work if you add a dependency to `com.facebook.fresco:nativeimagetranscoder`?

**Comment by canpoyrazoglu** [comment]
@oprisnik I can't add such dependency. I've triedn now:

` implementation 'com.facebook.fresco:nativeimagetranscoder:*'`

Though it cannot be resolved.

**Comment by oprisnik** [comment]
It is on bintray though, so it should work: https://bintray.com/facebook/maven/com.facebook.fresco%3Anativeimagetranscoder

**Comment by vijay-dadhich09** [comment]
I am facing the same issue with RN 0.59.8 below is the code but still not showing images. 
implementation 'com.facebook.fresco:nativeimagetranscoder:1.12.0' 

    // For animated GIF support
    compile 'com.facebook.fresco:animated-gif:1.10.0'

    // For WebP support, including animated WebP
    compile 'com.facebook.fresco:animated-webp:1.10.0'
    compile 'com.facebook.fresco:webpsupport:1.10.0'

    // For WebP support, without animations
    compile 'com.facebook.fresco:webpsupport:1.10.0'
