### ISSUE TITLE
Doesn't Load Any image with excluded nativeimagetranscoder

### ISSUE THREAD

**Issue by zetbrush** [facebook/fresco#2402]
[https://cdn1.imggmi.com/uploads/2019/9/5/dd8b729a2a160140f0f2849020b2d62b-full.png](url)
to eliminate issues described in https://github.com/facebook/fresco/issues/2049#issuecomment-473866204 and using configurations using steps mentioned in above comment, we are getting `getNativeImageTranscoder` thrown an exception  (as nativeImageTranscoder have been excluded) and the fallback to `SimpleImageTranscoder` never reaches, so no image can be loaded

### Reproduction
use excluding nativeimagetranscoder module solution described and approved in https://github.com/facebook/fresco/issues/2049#issuecomment-473866204

### Solution

[thrown exception should be handled in order to continue execution to `SimpleImageTranscoder` fallback ]

### Additional Information

* Fresco version: 2.0.0
* Platform version: [Pixel 3, Android 10]

**Comment by zetbrush** [comment]
@tyronen @oprisnik  hey, can you check this out pls?

**Comment by zetbrush** [comment]
Solution: add 
`ImagePipelineConfig.Builder:: setImageTranscoderType(ImageTranscoderType.JAVA_TRANSCODER);` https://github.com/facebook/fresco/issues/2049#issuecomment-462880309

**Comment by oprisnik** [comment]
Cool, I'll close this then. We're also working on a Java-only Fresco version, so this should be much easier soon.
