### ISSUE TITLE
@Nullable annotations from non-androidx sources

### ISSUE THREAD

**Issue by heyarny** [facebook/fresco#2404]
You seem to be using annotations which are not part of androidx.

See class BaseBitmapDataSubscriber for example, which I was about to use but can't right now as those are causing new conflicts.

As of version 2.0.0 I expect @Nullable to be used from androidx.annotation.
You're using javax.annotation which is not available in androidx.

**Comment by oprisnik** [comment]
Yes, our convention is to use `javax.annotation.Nullable`, which is part of Google's FindBugs / JSR 305 (https://github.com/findbugsproject/findbugs). You should use that annotation.

`compileOnly "com.google.code.findbugs:jsr305:${JSR_305_VERSION}"`
