### ISSUE TITLE
Images not loading in custom layout inside android library

### ISSUE THREAD

**Issue by RajuSE** [facebook/fresco#2407]
### Description

Fresco seems to be not working in android library.

I have created a library and I'm using Fresco SimleDraweeView inside custom layout in library view. Now when I pass url, Image is not loading. It's only showing placeholder image. Also It's not showing failure image. I don't know if http call to download image is happening or not.

### Reproduction

Repro is simple, just checkout develop branch of https://github.com/RajuSE/InstaPopSave-Android and run.
Check this file MainActivity.kt
: https://github.com/RajuSE/InstaPopSave-Android/blob/develop/app/src/main/java/dev/testapp/MainActivity.kt 

I'm passing url in loadImage method inside library.
https://github.com/RajuSE/InstaPopSave-Android/blob/develop/InstaPopSave-Android-Lib/src/main/java/devx/insta/popsave/ViewExtension.kt

```
fun SimpleDraweeView?.loadImage(imageUrl: String, width: Int = 100, height: Int = 100, tapToRetry: Boolean = false, hasPlaceHolder: Boolean = false) {
    val imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(imageUrl))
        .setResizeOptions(ResizeOptions(width, height))
        .build()
    val controller = Fresco.newDraweeControllerBuilder()
        .setImageRequest(imageRequest)
        .setOldController(this@loadImage?.controller)
        .setTapToRetryEnabled(tapToRetry)
        .build()
    if (hasPlaceHolder) {
        this@loadImage?.hierarchy?.setPlaceholderImage(ContextCompat.getColor(context, R.color.c2_light2_grey))
    }
    this@loadImage?.controller = controller
}
```

### Things I tried:
1. I tried creating application class and inititializing fresco there
2. setting 100dp width and height instead of wrap_content of SimpleDraweeView

### Additional Information

    implementation 'com.facebook.fresco:fresco:2.0.0'

**Comment by defHLT** [comment]
Do you see any errors in logcat?

**Comment by RajuSE** [comment]
@defHLT No there was no error in logcat.

**Comment by RajuSE** [comment]
Reproduction of this issue is simple, just checkout develop branch of https://github.com/RajuSE/InstaPopSave-Android and run

**Comment by RajuSE** [comment]
how to check if http call to download image is happening or not?

**Comment by RajuSE** [comment]
Any update?
