### ISSUE TITLE
Decoding a huge images will fail

### ISSUE THREAD

**Issue by ened** [facebook/fresco#242]
Given I want to load a PNG image of size 5616x3744
Or I want to load a JPG image of size 4499×4499 (https://www.flickr.com/photos/sevenx/16659995426/sizes/l)
Then Fresco will not load or display the picture.

This is the code used:

``` java
final long photoId = ...
final float origWidth = ...
final float origHeight = ...

log.log(Level.FINEST, "origWidth: {0}, origHeight: {1}", new Object[]{origWidth, origHeight});

final Uri uri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI.buildUpon().appendPath(Long.toString(photoId)).build();
final DraweeController controller = Fresco.newDraweeControllerBuilder().setUri(uri).setAutoPlayAnimations(true).build();

viewHolder.imageView.setController(controller);

final GridLayoutManager.LayoutParams lp = (GridLayoutManager.LayoutParams) viewHolder.itemView.getLayoutParams();
lp.width = (int) ((origWidth / origHeight) * targetHeight) - 5;
viewHolder.itemView.setLayoutParams(lp);
```

**Comment by ened** [comment]
For the JPG file, after research this might be a hardware limitation. However, the PNG image will be successfully shown by Picasso.

**Comment by xu6148152** [comment]
may be a bug

**Comment by tyronen** [comment]
An image of this size is much too large for a mobile screen, and the device's OpenGL subsystem won't be able to handle it. You have to [resize](http://frescolib.org/docs/resizing-rotating.html#resizing) it first.
