### ISSUE TITLE
animated-gif package breaks downloadable gifs with rounding

### ISSUE THREAD

**Issue by ilyamuromets** [facebook/fresco#2422]
### Description

I'm using **com.facebook.fresco:fresco** and **com.facebook.fresco:animated-gif** for show animated gif.
I load a gif image (non animated) from the Internet and apply **RoundingParams**.  
I expect to see round image, but I get square.
Gifs from app resources work fine.
I need **animated-gif** package for animation, but how to disable it for non animated gifs?

### Reproduction

If enable **animated-gif** package then **RoundingParams** will broken but animation will worked fine.

### Solution

Disabling **animated-gif** package resolve problem, but all animated gifs break.

### Additional Information

* Fresco version: 2.0.0
* animated-gif: 2.0.0
* Platform version: any device

**Comment by ilyamuromets** [comment]
The problem still exist!

**Comment by oprisnik** [comment]
Hey! How can we reproduce the issue? Can you give us some sample code? Rounding for GIFs is currently not supported.

**Comment by ilyamuromets** [comment]
@oprisnik The problem is in use **fresco**'s and **animated-gif**'s dependencies at the same time.
I use fresco for show user photo which is one-frame gif without animation and round it in user list. And I use fresco for show animated gifs. Both (user photo and funny gifs) are loading from the Internet. But with **animated-gif** fresco doesn't round user photo gif.
I can create demo project for you during several days.

**Comment by oprisnik** [comment]
Oh, that explains the issue.
When you include animated-gif, we'll use the animated GIF decoder for the image, which does not support rounding. For a single frame GIF, the system can decode a static image (which is happening when you don't have animated-gif).

The solution to this problem is to supply this method:

```java
ImageDecodeOptions options = ImageDecodeOptions.newBuilder().setForceStaticImage(true).build();
// Pass the options to the Drawee view via a DraweeController
draweeControllerBuilder.setImageRequest(
          ImageRequestBuilder.newBuilderWithSource(uri)
              .setImageDecodeOptions(options)
              .build());
```

**Comment by ilyamuromets** [comment]
@oprisnik thanks, it's working.
