### ISSUE TITLE
Images used for notifications sometimes recycled.

### ISSUE THREAD

**Issue by EverydayPineapple** [facebook/fresco#2423]
### Description

I'm using Fresco to obtain `Bitmap`s to form part of notifications. This mostly works fine, however I see maybe 20-30 "crashes" a day in Crashlytics with `Fatal Exception: java.lang.IllegalStateException: Cannot parcel a recycled bitmap`.

As far as I can tell I am following the docs and using `BaseBitmapDataSubscriber` to obtain the image and calling on to `NotificationManagerCompat#notify`. 

The notifications are in a messaging context, so sometimes I'll update the group with more messages.

I've also added an if statement into the line where I add the bitmap to the notification builder but still seeing issues. Something like below.

`.setLargeIcon(bitmap?.isRecycled == false) bitmap else null)`

### Reproduction

I've tried reproducing this issue but I don't seem to get anywhere with finding what is recycling the bitmap before I use it.

### Additional Information

* Fresco version: '2.0.0'
* Platform version: Seeing this issue across OS and Device versions. 59% Android 9, however I don't think this is of significance.

**Comment by EverydayPineapple** [comment]
I'd still like some input on this if possible.

**Comment by oprisnik** [comment]
You have to hold on to the image reference until it's no longer required and only close the reference once the notification is sent.

**Comment by oprisnik** [comment]
As a workaround, you can try using a `BaseBitmapReeefereenceDataSubscriber` instead of `BaseBitmapDataSubscriber` and then close the reference once notify has been called.

**Comment by EverydayPineapple** [comment]
Thanks! I'll give this a shot, plus some prod logging in case I still see the edge case crashes. At least I'll have a better idea of what's happening then.

I'll close this issue now, will re-open if it's still occurring after using `BaseBitmapReferenceDataSubscriber` and closing the reference myself after notify.

**Comment by oprisnik** [comment]
Yeah, this is one of the usages where manual memory management like Fresco is doing right now can cause problems unfortunately. Let us know if this still happens. It could be that Android 9.0 changes something related to notifications when they set the bitmap, which could cause this issue. 

We also have a Showcase example for notifications, if it's easy to repro there, would be great to have that so that we can investigate:

https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/ImagePipelineNotificationFragment.java

**Comment by EverydayPineapple** [comment]
Hi @oprisnik,

I've been using the `BaseBitmapReferenceDataSubscriber` interface and manually closing the reference to the bitmap after sending the notification to the system. Still however seeing crashes. It's a small percentage of users, however it's still a cause for concern and I'd like to be able to get to the bottom of the issue. 

I'll explain my current setup, and flow. And hopefully you'll be able to point me in the right direction to troubleshoot this issue. 

As the notification comes into the app, I check if I have the matching image in cache using `Fresco.getImagePipeline().isInDiskCacheSync(Uri.parse(url))`. 
If not in cache, I send the notification without the image, then start requesting the image from network and on response I'll update that notification with the image response.
If in cache, I will fetch the image from Fresco straight away, and send the notification.

The image is always fetched using `BaseBitmapReferenceDataSubsriber` and sent back to my notification classes using a standard interface callback (so no thread jumping going on here). once the bitmap has been consumed via this callback (i.e. `notificationManagerCompat.notify(id notification.build())` has been called), I call `CloseableReference.closeSafely(bitmapReference)` to close that bitmap. 

With this approach I still see over 100 crashes a day. This is small compared to the number of successful runs through this code, so there's obviously some edge case sometimes being hit. 

As a last ditch effort to catch the crash I also added `.setLargeIcon(if (bitmap?.isRecycled == false) bitmap else null)` when building the notifications but still see the issue.

Is there any advice you might be able to give me? Perhaps some idea on where I should be logging to find out more. I would try to reproduce in the showcase app but I fear that'll be a lost cause since this is appearing as an edge case for me in prod. 

Thanks

**Comment by EverydayPineapple** [comment]
Yes I'd still like some thoughts on this.

**Comment by oprisnik** [comment]
It looks like the icon is sometimes parceled later on after `notify` has been called. You can create a normal bitmap with `Bitmap.createBitmap(bitmap)`.

**Comment by EverydayPineapple** [comment]
I'll give it a shot. Was a little concerned about memory issues with me putting in that sort of code. Worth a shot I suppose. 

Thanks
