### ISSUE TITLE
fresco not able to load image if used in android library 

### ISSUE THREAD

**Issue by RajuSE** [facebook/fresco#2424]
**Description**

Fresco seems to be not working in android library.

I have created a library and I'm using Fresco SimleDraweeView inside custom layout in library view. Now when I pass url, Image is not loading. It's only showing placeholder image. Also It's not showing failure image. I don't know if http call to download image is happening or not.

**Reproduction**

Repro is simple, just checkout develop branch of [Github repo](https://github.com/RajuSE/InstaPopSave-Android) and run.
Check this file MainActivity.kt
: [MainActivity](https://github.com/RajuSE/InstaPopSave-Android/blob/develop/app/src/main/java/dev/testapp/MainActivity.kt)

I'm passing url in loadImage method inside library.
[](https://github.com/RajuSE/InstaPopSave-Android/blob/develop/InstaPopSave-Android-Lib/src/main/java/devx/insta/popsave/ViewExtension.kt)

> fun SimpleDraweeView?.loadImage(imageUrl: String, width: Int = 100, height: Int = 100, tapToRetry: Boolean = false, hasPlaceHolder: Boolean = false) {
>     val imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(imageUrl))
>         .setResizeOptions(ResizeOptions(width, height))
>         .build()
>     val controller = Fresco.newDraweeControllerBuilder()
>         .setImageRequest(imageRequest)
>         .setOldController(this@loadImage?.controller)
>         .setTapToRetryEnabled(tapToRetry)
>         .build()
>     if (hasPlaceHolder) {
>         this@loadImage?.hierarchy?.setPlaceholderImage(ContextCompat.getColor(context, R.color.c2_light2_grey))
>     }
>     this@loadImage?.controller = controller
> }

**Things I tried:**

I tried creating application class and inititializing fresco there
setting 100dp width and height instead of wrap_content of SimpleDraweeView
**Additional Information**

> implementation 'com.facebook.fresco:fresco:2.0.0'

**Comment by oprisnik** [comment]
What's the error log? See https://frescolib.org/docs/troubleshooting.html for debug information

**Comment by RajuSE** [comment]
@oprisnik I'm adding log of code:

```
var imageUrl="http://www.winterquilts.com/wp-content/uploads/2016/11/packing.png"
val imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(imageUrl))
                .build()
popSaveDrawee?.frescoImageView?.setImageRequest(imageRequest)
```



> 
> 11-12 19:09:46.945  7867  7867 V unknown:AbstractDraweeController: controller 19feff0c 53 -> 54: initialize
> 11-12 19:09:46.946  7867  7867 V unknown:AbstractDraweeController: controller 19feff0c 54: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@12907055
> 11-12 19:09:46.946  7867  7867 V unknown:AbstractDraweeController: controller 19feff0c 54: onAttach: request needs submit
> 11-12 19:09:46.946  7867  7867 V unknown:RequestLoggingListener: time 13859657: onRequestSubmit: {requestId: 27, callerContext: null, isPrefetch: false}
> 11-12 19:09:46.946  7867  7867 V unknown:RequestLoggingListener: time 13859657: onProducerStart: {requestId: 27, producer: BitmapMemoryCacheGetProducer}
> 11-12 19:09:46.946  7867  7867 V unknown:RequestLoggingListener: time 13859657: onProducerFinishWithSuccess: {requestId: 27, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
> 11-12 19:09:46.946  7867  7867 V unknown:RequestLoggingListener: time 13859657: onProducerStart: {requestId: 27, producer: BackgroundThreadHandoffProducer}
> 11-12 19:09:46.946  7867  7867 V unknown:AbstractDraweeController: controller 19feff0c 54: submitRequest: dataSource: 1388a9cd
> 11-12 19:09:46.946  7867  7867 V unknown:RequestLoggingListener: time 13859657: onRequestCancellation: {requestId: 27, elapsedTime: 0 ms}
> 11-12 19:09:46.946  7867  7867 V unknown:RequestLoggingListener: time 13859657: onProducerFinishWithCancellation: {requestId: 27, stage: BackgroundThreadHandoffProducer, elapsedTime: 0 ms, extraMap: null}
> 11-12 19:09:46.946  7867  7867 V unknown:AbstractDraweeController: controller 19feff0c 54 -> 55: initialize

**Comment by oprisnik** [comment]
Looks like you're not properly attaching / detaching the view, see: https://frescolib.org/docs/writing-custom-views.html

**Comment by RajuSE** [comment]
@oprisnik I checked the code however I'm not clear where to initialize `DraweeHolder` 

Can u check the code below:

In my case, its custom layout where I'm using `SimpleDraweeView`. 
Please check the code:
[Custom RelativeLayout ](https://github.com/RajuSE/InstaPopSave-Android/blob/develop/InstaPopSave-Android-Lib/src/main/java/devx/insta/popsave/PopSaveDrawee.kt)

**Comment by oprisnik** [comment]
You must only initialize Fresco once, not for every view as in your example. If you properly initialize Fresco in your application, it shoudl work, see https://frescolib.org/docs/

**Comment by RajuSE** [comment]
Hi @oprisnik,  I removed that line and initialized fresco in Application. Still it isn't working. Logs are same as shared previously.
```

var requestListeners =  HashSet<RequestListener>();
        requestListeners.add( RequestLoggingListener());
        var config = ImagePipelineConfig.newBuilder(applicationContext)
            .setRequestListeners(requestListeners)
            .build();

        Fresco.initialize(applicationContext, config)
        FLog.setMinimumLoggingLevel(FLog.VERBOSE);
```
