### ISSUE TITLE
Showcase crash for API <21

### ISSUE THREAD

**Issue by Yithis** [facebook/fresco#2426]
### Description

Showcase is crashing for API <21.

### Reproduction
Open "Placeholder, Progress, Failure" tab.
https://imgur.com/a/eyfzeOv

### Solution

https://stackoverflow.com/a/41629944
https://imgur.com/a/yWTwNrl

### Additional Information
* Platform version: [API <21]

**Comment by oprisnik** [comment]
Thanks! The PR has been merged.
