### ISSUE TITLE
Best quality from multiple cached images

### ISSUE THREAD

**Issue by aleksey-boldinov** [facebook/fresco#2430]
### Description
I have several requests with different sizes for one image
https://example.com/30/30/image.jpeg
https://example.com/50/50/image.jpeg
https://example.com/1000/1000/image.jpeg
Each image request contains a DraweeView pixel size in url.

**I don’t want to download the image again if there is already a good quality one on the local disk**
If there is a bad quality image on the local disk, then I want to install it as setLowResImageRequest.

Example:
DraweeView size: 50x50
This url is cached on the local disk: https://example.com/1000/1000/image.jpeg

```
const val URL = "https://example.com/50/50/image.jpeg"
if (CacheUtils.containsCurrentAndHighQuality(URL)) {
val targetUrl = CacheUtils.convertUriToHightQuality(URL)
val request = ImageRequestBuilder.newBuilderWithSource(targetUrl)
                .setResizeOptions(ResizeOptions(getDraweeWidth(), getDraweeHeight()))
                .build()
} else if (CacheUtils.containsLowQuality(URL)) {
val targetUrl = CacheUtils.convertUriToLowQuality(URL)
Fresco.newDraweeControllerBuilder()
.setLowResImageRequest(ImageRequest.fromUri(targetUrl))
.setImageRequest(ImageRequest.fromUri(URL))
.build()
} else {
.setImageRequest(ImageRequest.fromUri(URL))
}
```

**This task will help save user traffic.**
### Solution
1) Provide access to modifications fileName (resourceId) in local disk cache. 
For example: "50_50_" + SecureHashUtil.makeSHA1HashBase64(key.getUriString().getBytes("UTF-8"))
To do this, add to the CacheKey interface method **getUriSize(): IntArray(width, height)**
And provide a utility for finding the best cached quality by uri and my custom size
2) Implement automatic determination of the best cached quality
For example:
ImageRequest.newBuilderWithSource(URL).setMinimumImageSize(50, 50).setCachedQualityRenderingEnabled(true)
3) Revert MediaVariations
https://github.com/facebook/fresco/blob/d14cbec7f559a5575702416fa4cb45e53a3af806/imagepipeline/src/main/java/com/facebook/imagepipeline/request/ImageRequest.java#L52
or create analog

**Comment by oprisnik** [comment]
Hey! This is already possible with Fresco.

You can just use `AbstractDraweeControllerBuilder.setFirstAvailableImageRequests(...)` where you pass a list of image requests and it will return the first one that's available.

It will try loading the first one, then the second one etc.
There's also `setFirstAvailableImageRequests(requests, boolean tryCacheOnlyFirst)`. If the second parameter is true, it will check if any of them is already in bitmap memory cache and if not go to the network until one of them returns a result. You can also manually specify ImageRequest objects that only go up to the disk cache (and not network) by specifying ImageRequest.RequestLevel.DISK_CACHE when it's created.
