### ISSUE TITLE
RGB_565 is not working

### ISSUE THREAD

**Issue by superlinxiao** [facebook/fresco#2439]
### Description

By looking at the Bitmap memory size in the Profiler of android studio, I found a setBitmapsConfig problem.
I went to load a 24-bit PNG image. In fresco1.0 and below, RGB_565 was half as much as ARGB_8888, but above 1.0 (including 1.0 and the latest version), RGB_565 and ARGB_8888 used the same amount of memory.
I don't know if this is a bug, please help to have a look

**Comment by defHLT** [comment]
Hi,

I was not able to verify using Android Studio profiler.

Requesting image like this:
```
                Uri uri = sampleUris().createSampleUri();
                  ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                          .setImageDecodeOptions(ImageDecodeOptions.newBuilder()
                                  .setBitmapConfig(Bitmap.Config.RGB_565)
                                  .build())
                          .build();
                simpleDraweeView.setImageRequest(request);

```

Puts bitmap into memory whose size is consistent with RGB_565: 522 (w) * 788 (h) * 2 (bytes) = 822672 ~= 822747

![Screenshot 2019-11-28 13 33 32](https://user-images.githubusercontent.com/1539296/69810396-b29b6c00-11e3-11ea-982e-b26ceff04bcf.png)

**Comment by defHLT** [comment]
Please feel free to open a new issue if the problem persists. Thanks

**Comment by superlinxiao** [comment]
> Please feel free to open a new issue if the problem persists. Thanks
`ImagePipelineConfig  config =
          ImagePipelineConfig.newBuilder(context)
              .setBitmapsConfig(Bitmap.Config.RGB_565) 
..
              .build();
Fresco.initialize(application,config);
`
I tried your code, RGB_565 is in effect.
I configured the RGB_565 parameter at initialization, like the code above, but it didn't work for the PNG image.
Ask why the configuration RBG_565 does not take effect during initialization.
