### ISSUE TITLE
Permission to translate into Korean

### ISSUE THREAD

**Issue by recrack** [facebook/fresco#244]
This issue is related to #34 

Fresco is really cool project.
@plamenko, @tyronen. May i translate the document into Korean?

translate: http://fresco.recrack.com/docs/index.html#_
git repo: https://github.com/recrack/fresco-docs-kr

I think many Korean developers will love this project.

**Comment by tyronen** [comment]
Why, this is splendid! 대단히 감사합니다! Yes, we welcome more translations.

Please be sure to keep the documents up to date when the English ones are updated. I believe GitHub lets you subscribe to notifications of changes.

**Comment by recrack** [comment]
cc @larsien
2015. 5. 8. 오후 11:58에 "Tyrone Nicholas" <notifications@github.com>님이 작성:
