### ISSUE TITLE
 Could not initialize SoLoader

### ISSUE THREAD

**Issue by xingyao1015** [facebook/fresco#2440]
java.lang.RuntimeException:Unable to create application com.stub.StubApp: java.lang.RuntimeException: Could not initialize SoLoader
--
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4998)
3 ......
4 Caused by:
5 android.system.ErrnoException:fcntl failed: EDEADLK (Resource deadlock would occur)
6 libcore.io.Posix.fcntlFlock(Native Method)
7 libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
8 java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
9 java.nio.FileChannelImpl.lock(FileChannelImpl.java:166)
10 java.nio.channels.FileChannel.lock(FileChannel.java:185)
11 com.facebook.soloader.FileLocker.<init>(FileLocker.java:38)
12 com.facebook.soloader.FileLocker.lock(FileLocker.java:31)
13 com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:417)
14 com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:304)
15 com.facebook.soloader.SoLoader.init(SoLoader.java:181)
16 com.facebook.soloader.SoLoader.init(SoLoader.java:164)
17 com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:68)
18 com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
19 com.online.xthk.OnlineApp.onCreate(OnlineApp.kt:135)
20 com.stub.StubApp.onCreate(SourceFile:116)
21 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
22 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
23 android.app.ActivityThread.access$1800(ActivityThread.java:170)
24 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
25 android.os.Handler.dispatchMessage(Handler.java:102)
26 android.os.Looper.loop(Looper.java:179)
27 android.app.ActivityThread.main(ActivityThread.java:5769)
28 java.lang.reflect.Method.invoke(Native Method)
29 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
30 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

this error is in us new version and start time 2019.11.4, fresco version is 2.0.0, it happened most phone  is oppo r9s r8sk,  can you help me ?

**Comment by oprisnik** [comment]
Can you try with Fresco 2.1.0, which includes an updated SoLoader version? The problem might be fixed already.
