### ISSUE TITLE
when version more than 1.9.0, SimpleDraweeView use roundAsCircle, placeholderImage display small

### ISSUE THREAD

**Issue by yongshengdev** [facebook/fresco#2441]
in xml
`
<com.facebook.drawee.view.SimpleDraweeView
    android:layout_width="34dp"
    android:layout_height="34dp"
    fresco:actualImageScaleType="fitCenter"
    fresco:layout_constraintLeft_toLeftOf="parent"
    fresco:layout_constraintTop_toTopOf="parent"
    fresco:placeholderImage="@drawable/ic_bill"
    fresco:roundAsCircle="true"/>
`
when use fresco version 1.9.0, display right
![291575360267_ pic](https://user-images.githubusercontent.com/23274870/70032106-be25d300-15e7-11ea-9be3-92c466e1e3f0.jpg)
but when use version more than 1.9.0, like 1.10.0 or 2.0.0
![271575360148_ pic](https://user-images.githubusercontent.com/23274870/70032179-dc8bce80-15e7-11ea-8ebd-f8a4d7a2ce50.jpg)
file is in drawable directory

![ic_boleto_detail_icon](https://user-images.githubusercontent.com/23274870/70032269-12c94e00-15e8-11ea-970a-490846213410.png)

I try the method of https://github.com/facebook/fresco/issues/2260, but feel it's not a good solution, because the 1.9.0 is display right, 1.9.0 & 2.0.0 display different in one mobile phone. because 1.9.0 find some crash in google play(https://github.com/facebook/fresco/issues/2405), I want to update library version, but has display problem, may you solve my question? thx for your help

**Comment by SilenceBurst** [comment]
> bug

**Comment by idaima** [comment]
i have same issue ...

**Comment by TouhidApps** [comment]
I have the same problem and asked in StackOverflow:
[Question Link](https://stackoverflow.com/q/62209758/5646794)
![x6mbo](https://user-images.githubusercontent.com/11577788/84472841-cb63fe80-aca9-11ea-8269-c251cc3c4bcd.png)

**Comment by lvfxiang** [comment]
> I have the same problem and asked in StackOverflow:
> [Question Link](https://stackoverflow.com/q/62209758/5646794)
> ![x6mbo](https://user-images.githubusercontent.com/11577788/84472841-cb63fe80-aca9-11ea-8269-c251cc3c4bcd.png)

I solved, leave same space round image, even if 1px

**Comment by oprisnik** [comment]
This is a known issue with bitmap shaders on Android, see https://frescolib.org/docs/rounded-corners-and-circles.html

**Comment by yongshengdev** [comment]
> > I have the same problem and asked in StackOverflow:
> > [Question Link](https://stackoverflow.com/q/62209758/5646794)
> > ![x6mbo](https://user-images.githubusercontent.com/11577788/84472841-cb63fe80-aca9-11ea-8269-c251cc3c4bcd.png)
> 
> I solved, leave same space round image, even if 1px

@lvfxiang leave same space round image ? I try add ` roundingBorderPadding = 1px`  ` roundingBorderWidth = 1px` , also cannot solve

**Comment by shuifengYu** [comment]
I have the same problem, and it seems only occurs when the targetSdkVersion >= 29?
