### ISSUE TITLE
[Enhancement] Lack of debug information for Vito

### ISSUE THREAD

**Issue by Yithis** [facebook/fresco#2442]
### Description

Vito images almost don't have any information for debug. 
Example is [here.](https://pasteboard.co/IKr0g65.png)

I would like to add more information to display, similar to those for normal images like [here.](https://pasteboard.co/IKr1m9L.png) 

Can I try to take care of it or is someone already working to add such feature?

**Comment by defHLT** [comment]
We are already working on it and debug overlay for Vito should be working soon. But please feel free to introduce any improvements :)
