### ISSUE TITLE
Not able to load hands-Ons in fresco play for the node.js Essentials course.

### ISSUE THREAD

**Issue by cauvia** [facebook/fresco#2443]
When tried to load Hands-Ons for Node.js using fresco play I'm getting the below error.
"Sorry, we are unable to connect to hacker rank".
Can anyone please let me the reason and solution for this.....

**Comment by cauvia** [comment]
Error

**Comment by cauvia** [comment]
![Uploading 15760498848962939569605117631888.jpg…]()

**Comment by oprisnik** [comment]
Please fill out the issue template. I don't have any context what's going on here.

**Comment by tamilselvangnp** [comment]
Hi guys, I need your help to complete FRESCO's js Qualis final Hands-on.Could you pl help me!

**Comment by Randhawa2204** [comment]
> 

did you get help?? Please help if you found anything
