### ISSUE TITLE
fresco hands-on error while executing a command for the course Ansible - Automation choral, 

### ISSUE THREAD

**Issue by cauvia** [facebook/fresco#2444]
While the below command was executed i this error saying " the API server (galaxy.ansible.com) is not responding, please try again later.

Command: ansible-galaxy init sample_role

Tried many times getting same error.
![Uploading 15760506024185755030778970390441.jpg…]()

**Comment by oprisnik** [comment]
Hey! Same as #2443 - please fill out the template
