### ISSUE TITLE
v2.1.0 needs release notes or a changelog

### ISSUE THREAD

**Issue by erikhuizinga** [facebook/fresco#2449]
### Description

The latest release found [here](https://github.com/facebook/fresco/releases) has no changelog. However, there are [a lot of changes](https://github.com/facebook/fresco/compare/v2.0.0...v2.1.0) since the previous release, too many for Fresco users to go through to get a grasp about what has changed, what's new and what's now deprecated or obsoleted.

### Reproduction

Check the releases page, see no changelog / release notes for v2.1.0.

### Solution

Add a changelog.

I prefer to [keep a changelog](https://keepachangelog.com/) in a CHANGELOG.md file in the root of the project, which may be easier to find. Or, if this project contains many subprojects, keep a changelog at the root of each subproject.

### Additional Information

* Fresco version: v2.1.0
* Platform version: N/A

**Comment by erikhuizinga** [comment]
This is still an issue, so this is not stale.

Side note:
IMHO stale bot is useless if it tags issues as stale before any contributor / maintainer interacts with an issue. What it should do is label this as 'needs triage', not 'stale'. Only the fresco maintainers are stale in this case. If they had responded and I, the issuer, would not respond, only then this would truly be stale. Suggestion: don't use stale bot, configure it better or use a bot that marks issues as 'needs triage' before stale bot can mark them as stale.

**Comment by erikhuizinga** [comment]
Ping 👍

**Comment by oprisnik** [comment]
The changelog is availablee here: https://github.com/facebook/fresco/releases/tag/v2.1.0

**Comment by erikhuizinga** [comment]
Thank you!
