### ISSUE TITLE
How to cancel progressive animation

### ISSUE THREAD

**Issue by CronZhu** [facebook/fresco#2451]
I have a local jpeg picture,and I want to display it on my device immediately withou any animation , but when it firts display ,it always have a progressive animation.How can I cancel the progressive animation?

**Comment by oprisnik** [comment]
You can disable progressive JPEG rendering, see https://frescolib.org/docs/progressive-jpegs.html#main_wrap

You can also globally disable this via ImagePipelineConfig.
