### ISSUE TITLE
Fresco make my app crash on initialize

### ISSUE THREAD

**Issue by SugarDwarf** [facebook/fresco#2454]
### Description
I'm new to android and i just want to put a GIF in my layout without getting lag.
I added the most recent version of Fresco in my dependencies but when i try to do 
Fresco.initialize(this);
it make my app crash.

### Here's my dependencies 
    implementation 'com.facebook.fresco:fresco:2.0.0'
    // For animated GIF support
    implementation 'com.facebook.fresco:animated-gif:2.0.0'

### I initialize Fresco in my MainActivity this way:
   protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fresco.initialize(this);
       ....
   }

### And my layout look like this:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".Activities.MainActivity"
    android:background="@drawable/main">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/my_image_view"
        android:layout_width="130dp"
        android:layout_height="130dp"
        fresco:placeholderImage="@drawable/something" />
</RelativeLayout>

**Comment by oprisnik** [comment]
What's the crash?
