### ISSUE TITLE
Rounded not worked for placeholder image

### ISSUE THREAD

**Issue by flzyup** [facebook/fresco#246]
After i use SimpleDraweeView with roundAsCircle configuration with true.

I notice that the round not worked for place holder image but i read doc it said it default support the actual image and place holder. Please fixed it. I used the 0.4.0 fresco

    `<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/header"
            android:layout_width="97dp"
            android:layout_height="97dp"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="79dp"
            fit:placeholderImage="@drawable/place_holder"
            fit:roundAsCircle="true" />`

**Comment by IanChilds** [comment]
Please note the caveats section of the docs (http://frescolib.org/docs/rounded-corners-and-circles.html#_) - only `BitmapDrawable`s and `ColorDrawable`s can be rounded. If you're using a different type of drawable, perhaps consider using the `OVERLAY_COLOR` rounding method instead.
