### ISSUE TITLE
download image by image pipline

### ISSUE THREAD

**Issue by saed220** [facebook/fresco#2462]
could not download image by images pipline,
in [fresco web](https://frescolib.org/docs/using-image-pipeline.html) site and stack over flow ,there 
are many sugesiton for using image pipline for download images diresctly and I use this code base on 
doc:
`
try {
                   ImagePipeline imagePipeline = Fresco.getImagePipeline();
                   dataSource = imagePipeline.fetchDecodedImage(ImageRequest.fromUri(uri), getContext());

                   try { dataSource.subscribe(new BaseBitmapDataSubscriber() {
                      @Override
                      public void onNewResultImpl(@Nullable Bitmap bitmap) {
                       // You can use the bitmap here, but in limited ways.
                        // No need to do any cleanup.
                         Drawable d=new BitmapDrawable(getResources(),bitmap);
                         switch (id) {
                         case R.id.down: util.saveImageToSDCard(d, false);break;
                         case R.id.sharebutton: util.shareImage(d, null);break;
                         case R.id.zoom:
                         case R.id.blur:
                         case R.id.crop_walp:cropAction(d,id);break;

                                                      }
                         

                                                  }
                              @Override
                               public void onFailureImpl(DataSource dataSource) { }

                               },
                           CallerThreadExecutor.getInstance());}finally {
                     dataSource.close();

               }

               }catch (Exception e){e.printStackTrace();} }}`
but its work just when I load same uri befor this code simple drawee,
if i want downlad image directly image pipe lines deos not work .
aldos 
`dataSource.getProgress()` 
always return zero.

**Comment by oprisnik** [comment]
You can't hold on to the bitmap you get in onNewResultImpl, it will be recycled after the method finishes, see https://frescolib.org/docs/datasources-datasubscribers.html

**Comment by saed220** [comment]
Thank your for your comment .
I want dowmload image without showing in draweeView .but onNewResultImpl never called  and dataSource.getProgress() always return zero
 .how do I use image pipline for direct download.

**Comment by oprisnik** [comment]
Please see https://frescolib.org/docs/using-image-pipeline.html for documentation.

**Comment by saed220** [comment]
I get my code snipet from that link but it does not work
