### ISSUE TITLE
[Report from Firebase ] BucketsBitmapPool.java line 54. 

### ISSUE THREAD

**Issue by chihung93** [facebook/fresco#2466]
I can't reproduce this crash, but this is a report from Firebase.

Devices: 
1. Galaxy J3(2016) (20% )
2. Vivo Y21 -  (Vivo 40%)
3. Vivo Y55s
4. Huawei LISZT - (Huawei 40%)

OS: Android 5.1.1 (60%), Android 5.1 (40%)

Fresco Version:
'com.facebook.fresco:fresco:2.0.0'
'com.facebook.fresco:animated-gif:2.0.0'
'com.facebook.fresco:imagepipeline-okhttp3:1.12.1'
```

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 3467676 byte allocation with 2657936 free bytes and 2MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:842)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:779)
       at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:54)
       at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:29)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:266)
       at com.facebook.imagepipeline.platform.DefaultDecoder.decodeFromStream(DefaultDecoder.java:217)
       at com.facebook.imagepipeline.platform.DefaultDecoder.decodeJPEGFromEncodedImageWithColorSpace(DefaultDecoder.java:155)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:181)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:121)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:281)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:128)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:170)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
       at java.lang.Thread.run(Thread.java:831)
```

**Comment by oprisnik** [comment]
Looks like your application is displaying too many images. You only have 2MB left and are trying to display a larger image.

**Comment by kmrinmoy07** [comment]
Is there any fix to this. I am also getting this crash

**Comment by chihung93** [comment]
> Is there any fix to this. I am also getting this crash

I have to migrate to Glide to resolve these crashes on Firebase.  Or you can resize your image base on config.

**Comment by kmrinmoy07** [comment]
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
                .setDownsampleEnabled(true)
                .setResizeAndRotateEnabledForNetwork(true)
                .setBitmapsConfig(Bitmap.Config.RGB_565)
                .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
                .build();
        Fresco.initialize(this, config);

Will this help?

**Comment by oprisnik** [comment]
That should help yes

**Comment by jocoders** [comment]
> ```
>     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
>             .setDownsampleEnabled(true)
>             .setResizeAndRotateEnabledForNetwork(true)
>             .setBitmapsConfig(Bitmap.Config.RGB_565)
>             .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
>             .build();
>     Fresco.initialize(this, config);
> ```
> 
> Will this help?

Guys I have the same error. Can you tell me please where should I put this config? Which file? Will it help me?

**Comment by kmrinmoy07** [comment]
> 
> 
> > ```
> >     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
> >             .setDownsampleEnabled(true)
> >             .setResizeAndRotateEnabledForNetwork(true)
> >             .setBitmapsConfig(Bitmap.Config.RGB_565)
> >             .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
> >             .build();
> >     Fresco.initialize(this, config);
> > ```
> > 
> > 
> > Will this help?
> 
> Guys I have the same error. Can you tell me please where should I put this config? Which file? Will it help me?

You need to place this in your Application class, also you need to create a new class for the TrimmableRegistry. For example create a new class as - 

         public class FrescoMemoryTrimmableRegistry implements MemoryTrimmableRegistry {

              private final List<MemoryTrimmable> trimmables = new LinkedList<>();

              @Override
               public void registerMemoryTrimmable(final MemoryTrimmable trimmable) {
                  trimmables.add(trimmable);
               }

             @Override
              public void unregisterMemoryTrimmable(final MemoryTrimmable trimmable) {
                 trimmables.remove(trimmable);
              }

             public synchronized void trim(final MemoryTrimType trimType) {
                for (MemoryTrimmable trimmable : trimmables) {
                  trimmable.trim(trimType);
             }
         }

Then inside your Application class use it as 

        private final FrescoMemoryTrimmableRegistry frescoMemoryTrimmableRegistry = new FrescoMemoryTrimmableRegistry();


After that use

        ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
            .setDownsampleEnabled(true)
            .setResizeAndRotateEnabledForNetwork(true)
            .setBitmapsConfig(Bitmap.Config.RGB_565)
            .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
            .build();
       Fresco.initialize(this, config);

**Comment by jocoders** [comment]
> > > ```
> > >     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
> > >             .setDownsampleEnabled(true)
> > >             .setResizeAndRotateEnabledForNetwork(true)
> > >             .setBitmapsConfig(Bitmap.Config.RGB_565)
> > >             .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
> > >             .build();
> > >     Fresco.initialize(this, config);
> > > ```
> > > 
> > > 
> > > Will this help?
> > 
> > 
> > Guys I have the same error. Can you tell me please where should I put this config? Which file? Will it help me?
> 
> You need to place this in your Application class, also you need to create a new class for the TrimmableRegistry. For example create a new class as -
> 
> ```
>      public class FrescoMemoryTrimmableRegistry implements MemoryTrimmableRegistry {
> 
>           private final List<MemoryTrimmable> trimmables = new LinkedList<>();
> 
>           @Override
>            public void registerMemoryTrimmable(final MemoryTrimmable trimmable) {
>               trimmables.add(trimmable);
>            }
> 
>          @Override
>           public void unregisterMemoryTrimmable(final MemoryTrimmable trimmable) {
>              trimmables.remove(trimmable);
>           }
> 
>          public synchronized void trim(final MemoryTrimType trimType) {
>             for (MemoryTrimmable trimmable : trimmables) {
>               trimmable.trim(trimType);
>          }
>      }
> ```
> 
> Then inside your Application class use it as
> 
> ```
>     private final FrescoMemoryTrimmableRegistry frescoMemoryTrimmableRegistry = new FrescoMemoryTrimmableRegistry();
> ```
> 
> After that use
> 
> ```
>     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
>         .setDownsampleEnabled(true)
>         .setResizeAndRotateEnabledForNetwork(true)
>         .setBitmapsConfig(Bitmap.Config.RGB_565)
>         .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
>         .build();
>    Fresco.initialize(this, config);
> ```

Thank you so much for the answer 🙏🙏🙏 Can you tell me please did you have this error on Android in React Native?

**Comment by jocoders** [comment]
> > > ```
> > >     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
> > >             .setDownsampleEnabled(true)
> > >             .setResizeAndRotateEnabledForNetwork(true)
> > >             .setBitmapsConfig(Bitmap.Config.RGB_565)
> > >             .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
> > >             .build();
> > >     Fresco.initialize(this, config);
> > > ```
> > > 
> > > 
> > > Will this help?
> > 
> > 
> > Guys I have the same error. Can you tell me please where should I put this config? Which file? Will it help me?
> 
> You need to place this in your Application class, also you need to create a new class for the TrimmableRegistry. For example create a new class as -
> 
> ```
>      public class FrescoMemoryTrimmableRegistry implements MemoryTrimmableRegistry {
> 
>           private final List<MemoryTrimmable> trimmables = new LinkedList<>();
> 
>           @Override
>            public void registerMemoryTrimmable(final MemoryTrimmable trimmable) {
>               trimmables.add(trimmable);
>            }
> 
>          @Override
>           public void unregisterMemoryTrimmable(final MemoryTrimmable trimmable) {
>              trimmables.remove(trimmable);
>           }
> 
>          public synchronized void trim(final MemoryTrimType trimType) {
>             for (MemoryTrimmable trimmable : trimmables) {
>               trimmable.trim(trimType);
>          }
>      }
> ```
> 
> Then inside your Application class use it as
> 
> ```
>     private final FrescoMemoryTrimmableRegistry frescoMemoryTrimmableRegistry = new FrescoMemoryTrimmableRegistry();
> ```
> 
> After that use
> 
> ```
>     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
>         .setDownsampleEnabled(true)
>         .setResizeAndRotateEnabledForNetwork(true)
>         .setBitmapsConfig(Bitmap.Config.RGB_565)
>         .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
>         .build();
>    Fresco.initialize(this, config);
> ```

Can you tell me please, did you mean to write like this:
```
package ru.vtb.broker;

import android.app.ActivityManager;
import android.app.Application;
import android.content.Context;
import android.os.Build;
import android.os.Bundle;
import android.util.Log;
import android.webkit.WebView;

import com.datatheorem.android.trustkit.TrustKit;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.github.wuxudong.rncharts.MPAndroidChartPackage;
import com.facebook.react.bridge.ReadableNativeArray;
import com.facebook.react.bridge.ReadableNativeMap;
import com.facebook.react.modules.network.OkHttpClientProvider;
import com.facebook.soloader.SoLoader;
import com.livefront.bridge.Bridge;
import com.livefront.bridge.SavedStateHandler;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import com.wix.interactable.Interactable;

import icepick.Icepick;

public class FrescoMemoryTrimmableRegistry implements MemoryTrimmableRegistry {

  private final List<MemoryTrimmable> trimmables = new LinkedList<>();

  @Override
  public void registerMemoryTrimmable(final MemoryTrimmable trimmable) {
    trimmables.add(trimmable);
  }

  @Override
  public void unregisterMemoryTrimmable(final MemoryTrimmable trimmable) {
    trimmables.remove(trimmable);
  }

  public synchronized void trim(final MemoryTrimType trimType) {
    for (MemoryTrimmable trimmable : trimmables) {
     trimmable.trim(trimType);
    }
  }
}

public class MainApplication extends Application implements ReactApplication {
  private final FrescoMemoryTrimmableRegistry frescoMemoryTrimmableRegistry = new FrescoMemoryTrimmableRegistry();

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
              .setDownsampleEnabled(true)
              .setResizeAndRotateEnabledForNetwork(true)
              .setBitmapsConfig(Bitmap.Config.RGB_565)
              .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
              .build();
         Fresco.initialize(this, config);

      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new MPAndroidChartPackage());
      packages.add(new Interactable());

      return packages;

/*
      List<ReactPackage> rv = Arrays.<ReactPackage>asList(
	      new MainReactPackage(),
            new NetInfoPackage(),
            new RNFetchBlobPackage(),
            new AppMetricaPackage(),
            new RNCWebViewPackage(),
            new LinearGradientPackage(),
            new OrientationPackage(),
            new RNScreensPackage(),
            new RNGestureHandlerPackage(),
            new ReactNativeWheelPickerPackage(),
            new ReactNativeRestartPackage(),
            new RNAppsFlyerPackage(),
            new ReactNativePushNotificationPackage(),
        new RNExitAppPackage(),
        new IMEI(),
        new RNDeviceInfo(),
	      new RNDefaultPreferencePackage(),
	      new SvgPackage(),
	      new ru.vtb.broker.security.FingerprintAuthPackage(),
	      new ru.vtb.broker.security.SecurityV2Package(),
	      new ReactNativeConfigPackage(),
	      new SplashScreenReactPackage(),
	      new VectorIconsPackage(),
	      new Interactable(),
	      new LinearGradientPackage(),
        new FabricPackage(),
        new ReactVideoPackage(),
        new MPAndroidChartPackage(),
        new TransformSwiperPackage(),
        new PDFViewPackage()
      );

      return rv;
      */
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();

    Bridge.initialize(getApplicationContext(), new SavedStateHandler() {
        @Override
        public void restoreInstanceState(Object target, Bundle state) {
            Icepick.restoreInstanceState(target, state);
        }
        @Override
        public void saveInstanceState(Object target, Bundle state) {
            Icepick.saveInstanceState(target, state);
        }
    });

    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this); // Remove this line if you don't want Flipper enabled


    if (BuildConfig.SSL_PINNING_ENFORCE_POLICY == "true") {
      this.initTrustKit();
    }

        // ******
        // Смотри https://github.com/wuxudong/react-native-charts-wrapper
        // call for react native >= 0.54.0
        // ReadableNativeArray.setUseNativeAccessor(true);
        // ReadableNativeMap.setUseNativeAccessor(true);
        // otherwise
        try {
          Method arrayUseNativeAccessor = ReadableNativeArray.class.getDeclaredMethod("setUseNativeAccessor", boolean.class);
          if (arrayUseNativeAccessor != null) {
              arrayUseNativeAccessor.invoke(null, true);
          }

          Method mapUseNativeAccessor = ReadableNativeMap.class.getDeclaredMethod("setUseNativeAccessor", boolean.class);
          if (mapUseNativeAccessor != null) {
              mapUseNativeAccessor.invoke(null, true);
          }
        } catch (Exception e) {
            Log.e("Ошибка вызова метода setUseNativeAccessor(true) для ReadableNativeArray/ReadableNativeMap", e.getMessage());
        }
        // ******

        // https://github.com/react-native-community/react-native-webview/issues/968
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            String processName = getProcessName(this);
            String packageName = this.getPackageName();
            if (!packageName.equals(processName)) {
                WebView.setDataDirectorySuffix(processName);
            }
        }
  }

  private void initTrustKit() {
    TrustKit.initializeWithNetworkSecurityConfiguration(this);
    OkHttpClientProvider.setOkHttpClientFactory(new HttpClientFactory(TrustKit.getInstance()));
  }

  /**
     * Loads Flipper in React Native templates.
     *
     * @param context
     */
    private static void initializeFlipper(Context context) {
      if (BuildConfig.DEBUG) {
        try {
          /*
           We use reflection here to pick up the class that initializes Flipper,
          since Flipper library is not available in release mode
          */
          Class<?> aClass = Class.forName("com.facebook.flipper.ReactNativeFlipper");
          aClass.getMethod("initializeFlipper", Context.class).invoke(null, context);
        } catch (ClassNotFoundException e) {
          e.printStackTrace();
        } catch (NoSuchMethodException e) {
          e.printStackTrace();
        } catch (IllegalAccessException e) {
          e.printStackTrace();
        } catch (InvocationTargetException e) {
          e.printStackTrace();
        }
      }
    }

    private String getProcessName(Context context) {
        if (context == null) return null;
        ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        for (ActivityManager.RunningAppProcessInfo processInfo : manager.getRunningAppProcesses()) {
            if (processInfo.pid == android.os.Process.myPid()) {
                return processInfo.processName;
            }
        }
        return null;
    }
}

```

**Comment by mhashim6** [comment]
> > > ```
> > >     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
> > >             .setDownsampleEnabled(true)
> > >             .setResizeAndRotateEnabledForNetwork(true)
> > >             .setBitmapsConfig(Bitmap.Config.RGB_565)
> > >             .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
> > >             .build();
> > >     Fresco.initialize(this, config);
> > > ```
> > > 
> > > 
> > > Will this help?
> > 
> > 
> > Guys I have the same error. Can you tell me please where should I put this config? Which file? Will it help me?
> 
> 
> You need to place this in your Application class, also you need to create a new class for the TrimmableRegistry. For example create a new class as -
> 
> 
> ```
>      public class FrescoMemoryTrimmableRegistry implements MemoryTrimmableRegistry {
> 
>           private final List<MemoryTrimmable> trimmables = new LinkedList<>();
> 
>           @Override
>            public void registerMemoryTrimmable(final MemoryTrimmable trimmable) {
>               trimmables.add(trimmable);
>            }
> 
>          @Override
>           public void unregisterMemoryTrimmable(final MemoryTrimmable trimmable) {
>              trimmables.remove(trimmable);
>           }
> 
>          public synchronized void trim(final MemoryTrimType trimType) {
>             for (MemoryTrimmable trimmable : trimmables) {
>               trimmable.trim(trimType);
>          }
>      }
> ```
> 
> 
> Then inside your Application class use it as
> 
> 
> ```
>     private final FrescoMemoryTrimmableRegistry frescoMemoryTrimmableRegistry = new FrescoMemoryTrimmableRegistry();
> ```
> 
> 
> After that use
> 
> 
> ```
>     ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
>         .setDownsampleEnabled(true)
>         .setResizeAndRotateEnabledForNetwork(true)
>         .setBitmapsConfig(Bitmap.Config.RGB_565)
>         .setMemoryTrimmableRegistry(frescoMemoryTrimmableRegistry)
>         .build();
>    Fresco.initialize(this, config);
> ```

Could you please describe what does this do?

**Comment by seecaoxing** [comment]
why don't use setRegisterLruBitmapPoolAsMemoryTrimmable method set lrubitmappool

**Comment by BennyTian** [comment]
MainApplication#onCreate

`NoOpMemoryTrimmableRegistry.getInstance().registerMemoryTrimmable(new MemoryTrimmable() {
                @Override
                public void trim(MemoryTrimType trimType) {
                    final double suggestedTrimRatio = trimType.getSuggestedTrimRatio();
                    if (MemoryTrimType.OnCloseToDalvikHeapLimit.getSuggestedTrimRatio() == suggestedTrimRatio
                            || MemoryTrimType.OnSystemLowMemoryWhileAppInBackground.getSuggestedTrimRatio() == suggestedTrimRatio
                            || MemoryTrimType.OnSystemLowMemoryWhileAppInForeground.getSuggestedTrimRatio() == suggestedTrimRatio){
                        ImagePipelineFactory.getInstance().getImagePipeline().clearMemoryCaches();
                        Log.e(TAG,"clearMemoryCaches");
                    }
                }
            });

            ImagePipelineConfig config = ImagePipelineConfig.newBuilder(application)
                    .setDownsampleEnabled(true)
                    .setResizeAndRotateEnabledForNetwork(true)
                    .setBitmapsConfig(Bitmap.Config.RGB_565)
                    .setMemoryTrimmableRegistry(NoOpMemoryTrimmableRegistry.getInstance())
                    .build();

            Fresco.initialize(application,config);`
