### ISSUE TITLE
How to fix “No Suggestion" xml file android studio? 

### ISSUE THREAD

**Issue by Alkahirah** [facebook/fresco#2469]
In my XML files in the android studio, there is no suggestion I tried many different ways but no one worked with me.
I changed the name of files in path c/users/AndroidStudio3.5/sys
I checked the save power it was disabled
I made the Inv...cash also it didn't work.

can anyone help me???

**Comment by Adnanbashirmanak** [comment]
In my XML files in the android studio, there is no suggestion I tried many different ways but no one worked with me.
I checked the save power it was disabled
I made the Inv...cash also it didn't work.

can anyone help me???
