### ISSUE TITLE
Doc updates needed

### ISSUE THREAD

**Issue by mrsasha** [facebook/fresco#247]
Hi, 
just found some inaccuracies in the docs:
**Modifying image page** (http://frescolib.org/docs/modifying-image.html), section *Example*, example *L22*
is: `PipelineDraweeController controller = Fresco.newDraweeControllerBuilder()`
should be: `PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()`

**Modifying image page** (http://frescolib.org/docs/modifying-image.html), section *Example*, example *L24*
is: `.setOldController(mSimpleDraweeView.getOldController())`
should be: `.setOldController(mSimpleDraweeView.getController())`

**Modifying image page** (http://frescolib.org/docs/modifying-image.html), section *Copying into a different size*, example *L12*
is: `destBitmap.setPixel(sourceBitmap.getPixel(x, y));`
should be: `destBitmap.setPixel(x == 0 ? 0 : x/2, y == 0 ? 0 : y / 2, sourceBitmap.getPixel(x, y));`

Thanks!

**Comment by IanChilds** [comment]
Thanks for pointing these out - should now be fixed!
