### ISSUE TITLE
Can I change Bitmap.Config?

### ISSUE THREAD

**Issue by thirtyyuan** [facebook/fresco#2479]
### Description
I have a situation, using `Bitmap.Config.RGB_565` to "avatar", but using `Bitmap.Config.RGB_8888` to "background". Can I change the bitmap config for single DraweeView? I read the source code, I know I can't.

Do you have another solution?  it's not a good idea that load a large size image more than I really need, isn't it?

**Comment by oprisnik** [comment]
Hey! You can do something like:

```
    ImageDecodeOptions imageDecodeOptions =
        new ImageDecodeOptionsBuilder()
            .setBitmapConfig(Bitmap.Config.RGB_565)
            .setCustomImageDecoder(customImageDecoder)
            .build();
```
and then pass them to Fresco.

**Comment by victory316** [comment]
> Hey! You can do something like:
> 
> ```
>     ImageDecodeOptions imageDecodeOptions =
>         new ImageDecodeOptionsBuilder()
>             .setBitmapConfig(Bitmap.Config.RGB_565)
>             .setCustomImageDecoder(customImageDecoder)
>             .build();
> ```
> 
> and then pass them to Fresco.

I've landed here so far to set those options, it seems it can solve my problem. Thank you.

By the way, those codes can make some Sonarqube warnings about using generic types like that.

So I'm making approach like below. I'm using fresco version  2.6.0 now. 

>     ImageDecodeOptions imageDecodeOptions =
>         ImageDecodeOptions.newBuilder()
>             .setBitmapConfig(Bitmap.Config.RGB_565)
>             .setCustomImageDecoder(customImageDecoder)
>             .build();
