### ISSUE TITLE
Android工程师进阶教程，点击获取☞

### ISSUE THREAD

**Issue by gnehsuy** [facebook/fresco#2489]
![223108bf0de7853590b769fab34f591](https://user-images.githubusercontent.com/13401581/79435208-f3b0e300-8001-11ea-808d-23e409c8777e.png)

**Comment by zjw-swun** [comment]
if you want qia fan ,please get out

**Comment by misakuo** [comment]
advance your 🐎

**Comment by al0ne** [comment]
advance your 🐎
