### ISSUE TITLE
Support for overriding the default press behavior

### ISSUE THREAD

**Issue by raylee4204** [facebook/fresco#249]
Other than using `pressedStateOverlayImage`, there's no easy way to support touch feedback on the default DraweeView such as tinting the loaded image when touched.

One thing I tried,which took a little amount of work was to extend SimpleDraweeView and override `drawableStateChanged()` method of ImageView doing the following:

```java
ColorStateList tint = getResources().getColorStateList(R.color.default_icon_selector);
@Override
protected void drawableStateChanged() {
     super.drawableStateChanged();
     updateTintColor();
}

private void updateTintColor() {
     int color = tint.getColorForState(getDrawableState(), 0);
     setColorFilter(color);
}
```

**Comment by NNirvana** [comment]
you'd better not use drawableStateChanged() from ImageView, "Any ImageView attrribute or method will be removed in the upcoming release, so please don't use those."

**Comment by IanChilds** [comment]
Can you just use standard Android click events to achieve what you need?

**Comment by raylee4204** [comment]
How would you use standard android click events in DraweeView?
If the DraweeView has a custom shape of an image, overlaying a ColorDrawable on top of it would cover the entire size of the View instead of the custom shaped area.

**Comment by IanChilds** [comment]
Can you use GenericDraweeHierarchy.getActualImageBounds for your use case perhaps?
