### ISSUE TITLE
Abort message: 'GL errors! frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126'

### ISSUE THREAD

**Issue by yaoguangdong** [facebook/fresco#2494]
### Description

[when I load several large pictures（example：10000 x 11180）in my custom pohoto album, often encounter no responseing or app is restarted. and Logcat output this:

04-28 08:50:16.973 10946 20310 20430 F libc : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 20430 (RenderThread), pid 20310 com.xxx.yyy
04-28 08:50:17.256 10946 31455 31455 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-28 08:50:17.257 10946 31455 31455 F DEBUG : Build fingerprint: 'google/walleye/walleye:10/QP1A.190711.020/5800535:user/release-keys'
04-28 08:50:17.257 10946 31455 31455 F DEBUG : Revision: 'MP1'
04-28 08:50:17.257 10946 31455 31455 F DEBUG : ABI: 'arm'
04-28 08:50:17.257 10946 31455 31455 F DEBUG : Timestamp: 2020-04-28 08:50:17+0800
04-28 08:50:17.257 10946 31455 31455 F DEBUG : pid: 20310, tid: 20430, name: RenderThread >>> com.xxx.yyy <<<
04-28 08:50:17.257 10946 31455 31455 F DEBUG : uid: 10946
04-28 08:50:17.257 10946 31455 31455 F DEBUG : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-28 08:50:17.257 10946 31455 31455 F DEBUG : Abort message: 'GL errors! frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126'
04-28 08:50:17.257 10946 31455 31455 F DEBUG : r0 00000000 r1 00004fce r2 00000006 r3 c5e60b30
04-28 08:50:17.257 10946 31455 31455 F DEBUG : r4 c5e60b44 r5 c5e60b28 r6 00004f56 r7 0000016b
04-28 08:50:17.257 10946 31455 31455 F DEBUG : r8 c5e60b40 r9 c5e60b30 r10 c5e60b60 r11 c5e60b50
]

load small picture is ok，and I use ResizeOption and DownSample=true normally.

about the native memory used:
Fresco 1G-1.5G
Glide 0.6G-1G

### Reproduction

[you can find some large image, for example 20M size and reproduce the bug]

### Solution

[]

### Additional Information

* Fresco version: [any]
* Platform version: [any

]

**Comment by yaoguangdong** [comment]
I have solved this problem，the reason is Fresco be initialized again by React Native framework，so the native memory is leaked!
I change the Fresco's initialize method, and if sIsInitialized== true,then return!

**Comment by eugenioamato** [comment]
Today I had same error while testing a Flutter app on Emulator 'Android TV 1080 Api Q.
'GL errors! frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126'.

Steps to reproduce:

Create the base flutter app with 
flutter create x
in Android Studio :
Create an Emulator : Android Tv 1080 api Q (Google ATV x86)
Run on that device:

> Syncing files to device sdk google atv x86...
D/OpenGLRenderer(30120): Skia GL Pipeline
D/OpenGLRenderer(30120): Swap behavior 1
D/        (30120): HostConnection::get() New Host Connection established 0xd233f9c0, tid 30200
D/        (30120): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer(30120): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer(30120): Swap behavior 0
D/EGL_emulation(30120): eglCreateContext: 0xe54127e0: maj 3 min 0 rcv 3
D/EGL_emulation(30120): eglMakeCurrent: 0xe54127e0: ver 3 0 (tinfo 0xe54b8eb0)
D/        (30120): HostConnection::get() New Host Connection established 0xe09118c0, tid 30181
D/        (30120): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(30120): eglCreateContext: 0xec3713c0: maj 3 min 0 rcv 3
W/Gralloc3(30120): mapper 3.x is not supported
D/EGL_emulation(30120): eglMakeCurrent: 0xec3713c0: ver 3 0 (tinfo 0xec464200)
D/EGL_emulation(30120): eglMakeCurrent: 0xe54127e0: ver 3 0 (tinfo 0xe54b8eb0)
D/EGL_emulation(30120): eglMakeCurrent: 0xec3713c0: ver 3 0 (tinfo 0xec464200)
F/OpenGLRenderer(30209): GL errors! frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126
...

(more 54 repeated lines)
frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126



my flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre, on Mac OS X 10.15.4 19E287, locale en-NL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)

**Comment by hasanm08** [comment]
> Today I had same error while testing a Flutter app on Emulator 'Android TV 1080 Api Q. 'GL errors! frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126'.
> 
> Steps to reproduce:
> 
> Create the base flutter app with flutter create x in Android Studio : Create an Emulator : Android Tv 1080 api Q (Google ATV x86) Run on that device:
> 
> > Syncing files to device sdk google atv x86...
> > D/OpenGLRenderer(30120): Skia GL Pipeline
> > D/OpenGLRenderer(30120): Swap behavior 1
> > D/        (30120): HostConnection::get() New Host Connection established 0xd233f9c0, tid 30200
> > D/        (30120): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
> > W/OpenGLRenderer(30120): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
> > D/OpenGLRenderer(30120): Swap behavior 0
> > D/EGL_emulation(30120): eglCreateContext: 0xe54127e0: maj 3 min 0 rcv 3
> > D/EGL_emulation(30120): eglMakeCurrent: 0xe54127e0: ver 3 0 (tinfo 0xe54b8eb0)
> > D/        (30120): HostConnection::get() New Host Connection established 0xe09118c0, tid 30181
> > D/        (30120): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
> > D/EGL_emulation(30120): eglCreateContext: 0xec3713c0: maj 3 min 0 rcv 3
> > W/Gralloc3(30120): mapper 3.x is not supported
> > D/EGL_emulation(30120): eglMakeCurrent: 0xec3713c0: ver 3 0 (tinfo 0xec464200)
> > D/EGL_emulation(30120): eglMakeCurrent: 0xe54127e0: ver 3 0 (tinfo 0xe54b8eb0)
> > D/EGL_emulation(30120): eglMakeCurrent: 0xec3713c0: ver 3 0 (tinfo 0xec464200)
> > F/OpenGLRenderer(30209): GL errors! frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126
> > ...
> 
> (more 54 repeated lines) frameworks/base/libs/hwui/pipeline/skia/SkiaOpenGLPipeline.cpp:126
> 
> my flutter doctor
> 
> Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel master, 1.19.0-2.0.pre, on Mac OS X 10.15.4 19E287, locale en-NL)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2) [✓] Xcode - develop for iOS and macOS (Xcode 11.5) [✓] Chrome - develop for the web [✓] Android Studio (version 3.6) [✓] VS Code (version 1.45.1)

this problem still exists in flutter ```2.10.5```
