### ISSUE TITLE
OOM exceptions - BucketsBitmapPool.java line 54  & ForwardingDrawable.java line 185

### ISSUE THREAD

**Issue by BianconeroIle** [facebook/fresco#2498]
Our team is struggling with Fresco OOM exceptions for a long time. Our top crashes are coming from this library. Any recommendation how we can handle this? 

BucketsBitmapPool.java line 54
com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 4314636 byte allocation with 2105952 free bytes and 2MB until OOM
com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
android.graphics.Bitmap.createBitmap (Bitmap.java:796)
com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc (BucketsBitmapPool.java:54)
com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc (BucketsBitmapPool.java:27)
com.facebook.imagepipeline.memory.BasePool.get (BasePool.java:243)
com.facebook.imagepipeline.platform.DefaultDecoder.decodeFromStream (DefaultDecoder.java:217)
com.facebook.imagepipeline.platform.DefaultDecoder.decodeJPEGFromEncodedImageWithColorSpace (DefaultDecoder.java:155)
com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg (DefaultImageDecoder.java:179)
com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode (DefaultImageDecoder.java:58)
com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode (DefaultImageDecoder.java:120)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode (DecodeProducer.java:316)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$300 (DecodeProducer.java:136)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run (DecodeProducer.java:186)
com.facebook.imagepipeline.producers.JobScheduler.doJob (JobScheduler.java:220)
com.facebook.imagepipeline.producers.JobScheduler.access$000 (JobScheduler.java:23)
com.facebook.imagepipeline.producers.JobScheduler$1.run (JobScheduler.java:89)

& 

ForwardingDrawable.java line 185
com.facebook.drawee.drawable.ForwardingDrawable.draw
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 4665612 byte allocation with 2639848 free bytes and 2MB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
android.graphics.Bitmap.nativeCreate (Bitmap.java)
android.graphics.Bitmap.createBitmap (Bitmap.java:831)
android.graphics.Bitmap.createBitmap (Bitmap.java:808)
android.graphics.Bitmap.createBitmap (Bitmap.java:775)
android.graphics.drawable.VectorDrawable$VectorDrawableState.createCachedBitmapIfNeeded (VectorDrawable.java:834)
android.graphics.drawable.VectorDrawable.draw (VectorDrawable.java:318)
com.facebook.drawee.drawable.ForwardingDrawable.draw (ForwardingDrawable.java:185)
com.facebook.drawee.drawable.ScaleTypeDrawable.draw (ScaleTypeDrawable.java:143)
com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha (FadeDrawable.java:315)
com.facebook.drawee.drawable.FadeDrawable.draw (FadeDrawable.java:302)
com.facebook.drawee.drawable.ForwardingDrawable.draw (ForwardingDrawable.java:185)
com.facebook.drawee.generic.RootDrawable.draw (RootDrawable.java:81)

* Fresco version: 
 implementation 'com.facebook.fresco:fresco:2.1.0'
 implementation "com.facebook.fresco:imagepipeline-okhttp3:2.1.0"
 implementation 'com.facebook.soloader:soloader:0.8.2'

* Platform version: 
- ForwardingDrawable.java line 185 - 83% of the crashes happens on Android 5
- BucketsBitmapPool.java line 54 - 50% on Android 5, 41% on Android 6.

**Comment by kmrinmoy07** [comment]
Hi, I am also getting a similar issue BucketsBitmapPool.java line 55 only on Android 5.1.1 Vivo devices

**Comment by kmrinmoy07** [comment]
Hi, I am also getting a similar issue BucketsBitmapPool.java line 55 only on Android 5.1.1 Vivo devices and I have already opened a issue.

Do you use drawable in placeholders?

**Comment by oprisnik** [comment]
Hey! Looks like you're displaying lots of images. What's your setup and what are the dimensions of your images?

**Comment by BianconeroIle** [comment]
- square pictures in a 3 column recyclerview grid
- max image size is dependent on display width and a max size of 848

**Comment by stevenwsg** [comment]
Hi, I am also metting the same issue BucketsBitmapPool.java in line 54 on Android 6.0.1,VIVO Y66.Yesterday happend first time..

This is my stack information.

![avatar](https://upload.cc/i1/2020/05/13/CTZIik.png)


Fresco version:


            //fresco
            "fresco-sdk"                        : "com.facebook.fresco:fresco:${version["frescoSdkVersion"]}",
            "fresco-gif"                     : "com.facebook.fresco:animated-gif:${version["frescoSdkVersion"]}",
            "fresco-imagepipeline-okhttp3"      : "com.facebook.fresco:imagepipeline-okhttp3:${version["frescoSdkVersion"]}",
            "fresco-animated-gif"               : "com.facebook.fresco:animated-gif:${version["frescoSdkVersion"]}",
            "fresco-animated-webp"              : "com.facebook.fresco:animated-webp:${version["frescoSdkVersion"]}",
            "fresco-webpsupport"                : "com.facebook.fresco:webpsupport:${version["frescoSdkVersion"]}",

  
frescoSdkVersion            : "1.13.0.0.5"

**Comment by oprisnik** [comment]
You can also use the Flipper images plugin (https://fbflipper.com/) to figure out what images are currently marked as "on screen", i.e. we have a hard reference to the bitmap and cannot free memory / re-use. That might help you to debug what's going on.

**Comment by kmrinmoy07** [comment]
Is there any fix to this, I am facing huge amount of the above crash

**Comment by stevenwsg** [comment]
> Is there any fix to this, I am facing huge amount of the above crash

Emmmm, I an facing huge amount of the above crash too!

**Comment by BianconeroIle** [comment]
Nothing from my side, we will implement the Flipper plugin to try to get more informations... and the crash is inconsistent

**Comment by kongxiaoan** [comment]
Several models based on Vivo mobile phone in my side are experiencing serious collapse. Is there any specific solution? Thank you
![image](https://user-images.githubusercontent.com/29633044/105807989-ee95b100-5fe1-11eb-88f8-fa93d0626b21.png)

**Comment by eeKend** [comment]
<img width="1970" alt="WeChat227af6e1d5f02de998f23f13053d0c39" src="https://user-images.githubusercontent.com/27043598/121623909-2427cc00-caa3-11eb-8dd0-d7a9981a6f3f.png">

**Comment by kopihao** [comment]
<img width="1119" alt="Screenshot 2022-03-14 at 12 10 07 PM" src="https://user-images.githubusercontent.com/8252002/158103536-e87bf2f5-1b5e-4036-b661-e337c772934c.png">
<img width="1146" alt="Screenshot 2022-03-14 at 12 09 44 PM" src="https://user-images.githubusercontent.com/8252002/158103518-e45bd0d9-1198-46f1-a58a-264b662fdb1f.png">
<img width="441" alt="Screenshot 2022-03-14 at 12 15 44 PM" src="https://user-images.githubusercontent.com/8252002/158104178-e6b345f1-e9ef-4465-b924-22b8522b482b.png">
<img width="453" alt="Screenshot 2022-03-14 at 12 15 57 PM" src="https://user-images.githubusercontent.com/8252002/158104184-75b937bf-da61-4fb1-9ec2-ec79efd3abc2.png">
<img width="1156" alt="Screenshot 2022-03-14 at 12 18 43 PM" src="https://user-images.githubusercontent.com/8252002/158104211-6f587a6a-3295-4da3-9278-2c1a01069514.png">

Does this really caused by large image? This issue is the top regression issue captured in Crashlytics at my side. 

https://github.com/facebook/fresco/issues/2136#issuecomment-397608264
