### ISSUE TITLE
fbcore's proguard limit is too broad

### ISSUE THREAD

**Issue by NormanOu** [facebook/fresco#2499]
### Description

the proguard configuration in 'fbcore-2.1.0.aar' includes a line that keeps all classes with a native method, which is not good. As we can't choose to shrink other classes with native method any more.

` # Keep native methods
 -keepclassmembers class * {
     native <methods>;
 }`

### Reproduction

any demo app implements fresco should be able to reproduce

### Solution

change the proguard rule to be something like the following
` # Keep native methods
 -keepclassmembers class com.facebook.** {
     native <methods>;
 }`

### Additional Information

* Fresco version: 2.1.0
* Platform version: android

**Comment by oprisnik** [comment]
Thanks, this should be fixed. Pull requests are welcome! :)
