### ISSUE TITLE
Fresco load image without drawee

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#250]
Can committers give a demo to us? how to load image without drawee?I am a little confused about directly using imagepiple.

**Comment by NNirvana** [comment]
call method of ImagePipeLine: fetchDecodedImage or fetchEncodedImage,then subscribe returned DataSource, by the way , you need to give a thread pool executor to  fetchDecodedImage or fetchEncodedImage
Fresco.getImagePipeline()
                .fetchDecodedImage(ImageRequestBuilder.newBuilderWithSource(Uri.parse(url)).build(), null)
                .subscribe(new BaseBitmapDataSubscriber() {
                    @Override
                    protected void onNewResultImpl(Bitmap bitmap) {
                    }

                    @Override
                    protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                    }
                }, ThreadUtil.getGlobalThreadPoolExecutor());

**Comment by KrystalJake1989** [comment]
ok，thank you! I have another question, when I read the fresco document,it warns that onNewResultImpl's argument bitmap can't be hold to exceed the method scope,but I really need reference that bitmap in other place, how to solve it?

**Comment by NNirvana** [comment]
you can copy the source code of process method in BasePostprocessor

**Comment by KrystalJake1989** [comment]
ok!I got it.But sometimes I need use bitmap to share to social app such as weibo,facebook,twitter.Their sdk api needs a bitmap as argument, or some of my custom widgets such as gesture zoom-in-out image view, it needs a bitmap to be operated by users.In those cases, do you have any good ideas or suggestion?

**Comment by IanChilds** [comment]
You just need to make sure that you close the bitmap you have once you've finished with it. In the case of sharing to a social app, I expect that the app will make its own copy of the bitmap, so you can use BaseBitmapDataSubscriber just fine. 

If you need the bitmap to stay around longer than the life of `onNewResultImpl(Bitmap bitmap)` then you should instead subclass `BaseDataSubscriber` and extract the bitmap yourself - then you can close it when you want to (just make sure you do!).

**Comment by KrystalJake1989** [comment]
Ok,thanks!one more question,I use fresco to load bitmaps from MediaStore.Images.Media.EXTERNAL_CONTENT_URI，but when I use girdview to display them.Some of them can't be displayed，I find fresco can only loads 10-11 bitmaps.Does fresco set limit on loaded bitmaps?

**Comment by IanChilds** [comment]
Depending upon your pipeline configuration, you may run out of memory if you have too many bitmaps at once - are you resizing them? If not then it's quite likely that you will run out of memory.

**Comment by KrystalJake1989** [comment]
Yes,I resizing them and there are 24 simpleDraweeimageviews on screen,how can I detect whether I am run out of memory?

**Comment by IanChilds** [comment]
you should see some errors logged if that is the case

**Comment by KrystalJake1989** [comment]
I have turn log level to INFO，but I don't observe any log about running out of memory.I also use ddms to observe memory alloc, it also under normal status.

**Comment by IanChilds** [comment]
What format is the image that isn't loading?

**Comment by KrystalJake1989** [comment]
Most of them are png format
