### ISSUE TITLE
com.facebook.drawee.view.SimpleDraweeView  decodeBitmap

### ISSUE THREAD

**Issue by T-chuangxin** [facebook/fresco#2503]
Huawei 6.1.1  && Huawei 10
I used systrace tool to analyze my application and found that there are many com.facebook.drawee.view.SimpleDraweeView in Huawei 6.1.1 system
The problem with decodeBitmap is not found in the Android10 system, is this normal?
? What should I do to eliminate these time-consuming operations？

**Comment by oprisnik** [comment]
What images are you decoding? Decoding bitmaps takes time, and if you have huge images there might not be much that you can do.

What do you mean with decodeBitmap is not found in Android10? Do you use proguard and properly set up Fresco's ProGuard rules?
