### ISSUE TITLE
Why BitmapMemoryCacheKey.containsUri() use String.contains()?

### ISSUE THREAD

**Issue by thirtyyuan** [facebook/fresco#2505]
### Situation
The small image url is "https://xxx.jpg?w/100", and the original image url is "https://xxx.jpg". I always load small image at first time. Sometimes, I need to load original image after that.

### Problem
In `MemoryCache.contains(Predicate<K>)`, the small image url is always contains the original image url "https://xxx.jpg", so it's won't be load the original url correctly.

### Question
Can I custom `mCacheKeyFactory`, and override `BitmapMemoryCacheKey.containsUri()` by using `String.equals()`? Should I have to notice any problem?

**Comment by jokermonn** [comment]
+1

**Comment by oprisnik** [comment]
Yes, you can have a custom cache key factory, see my response here:
https://stackoverflow.com/a/62137295/2300128

**Comment by thirtyyuan** [comment]
> Yes, you can have a custom cache key factory, see my response here:
> https://stackoverflow.com/a/62137295/2300128

OK, I custom my cache key factory yet.  May I ask you more questions about cache key? Such as, I implement `BitmapMemoryCacheKey.containsUri()` by using `String.equals()`, it's only depends on my needs? Should I notice any problem?
