### ISSUE TITLE
return value of PostProcessor.process()

### ISSUE THREAD

**Issue by NNirvana** [facebook/fresco#251]
I want to do someting with decoded Bitmap, but I don't need to change the source bitmap, BaseProcessor create a new bitmap everytime, this is not necessary for me, so I want to use PostProcessor to get the origin bitmap, but I don't know what to return for process method.

**Comment by IanChilds** [comment]
If you don't need to do anything at all with the bitmap, then why have a postprocessor at all? Can't you just use `ImagePipeline.fetchDecodedImage(..)` and subscribe to that `DataSource`, which will give you a bitmap?

**Comment by NNirvana** [comment]
Thank you!
Sometimes I need show the bitmap in SimpleDraweeView and also want to get the source bitmap to generate a Gaussian Blur bitmap, as you say, I can send two request with the same uri, like this:

1: simpleDraweeView.setUri(uri);
2:Fresco.getImagePipeline()
                .fetchDecodedImage(imageRequest)
                .subscribe(mySubscriber, myExecutor);

if the uri is a url, this two request will download only one image actually, because they use the same uri. 
Am I right? Sorry for my poor English!

**Comment by IanChilds** [comment]
Yes, you are right that the requests will only download one image because they use the same uri. 

Can you explain what you want to do with the Gaussian Blur bitmap? Are you putting it into the same SimpleDraweeView as (1), or somewhere else? It seems like for (2) you should be using a postprocessor, but not for (1).

**Comment by NNirvana** [comment]
the Gaussian Blur bitmap will be set to another ImageView, not this SimpleDraweeView

**Comment by NNirvana** [comment]
or saved to local disk

**Comment by IanChilds** [comment]
In that case you should use a Postprocessor to do the Gaussian Blur.

**Comment by NNirvana** [comment]
Got it, Thank you!

**Comment by NNirvana** [comment]
Further more, if I want to implement my own Postprocessor, what to return for process()  method?
I have tried to find answer from Fresco's source code, but I still can't get the point.

**Comment by IanChilds** [comment]
Subclass BasePostprocessor, and then if you are able to do Gaussian Blur in-place, you should override `process(Bitmap bitmap)` (the pipeline will then return this bitmap) or otherwise override `process(Bitmap destBitmap, Bitmap sourceBitmap)` (the pipeline will return `destBitmap`)

**Comment by NNirvana** [comment]
yes, I have read the code of BasePostprocessor, it create a copy of source bitmap, then pass this copy to process(Bitmap bitmap). But I don't want to create a copy because I  won't make changes on source bitmap,Can I do this?

**Comment by IanChilds** [comment]
You always need to copy the source bitmap if you are going to do a Gaussian Blur on it, since that source bitmap might be used in other places (e.g. for you, it will be used in request (1) that you mentioned above). 

Therefore you should use one of the methods I suggested - which one you use depends upon whether your blur is done in-place or not, but either way you should not touch the source bitmap.

**Comment by NNirvana** [comment]
In fact, I will create a new Bitmap during Gaussian Blur , It won't make any change on the source Bitmap

**Comment by waterone** [comment]
@Gerald09 
Hi,
Could you please share the blur code? I am trying to achieve the same effect on image but as fresco do not provide and call back like Picaso I am unable to do this. I am using bluring view and invalidating teh view for blur effect.

PS: Pardon me for english and also I am new to android.
