### ISSUE TITLE
ImageView + DraweeHolder: Image is cleared during fragment transition

### ISSUE THREAD

**Issue by snepalnetflix** [facebook/fresco#2512]
### Description

I'm using a ImageView with DraweeHolder<GenericDraweeHierarchy>. When I transition to a different fragment, the image in my image view is cleared. My non-Fresco backed images don't get cleared.

It seems like this is triggered from AbstractDraweeController.onDetach.

Is there any way to avoid this?

### Additional Information

* Fresco version: 2.2.0
* Platform version: Android Q

**Comment by oprisnik** [comment]
Hey! Are you using animations? If so, this is probably the same issue as #1445.

**Comment by oprisnik** [comment]
Thanks, so you're saying that with the patch and your patch everything is fixed?

**Comment by snepalnetflix** [comment]
> Thanks, so you're saying that with the patch and your patch everything is fixed?

Correct. We no longer see flashes during fragment transitions.
