### ISSUE TITLE
java.io.FileNotFoundException by some special uri 

### ISSUE THREAD

**Issue by liujianying** [facebook/fresco#252]
java.io.FileNotFoundException: http://img.v89.com/group1/M07/05/48/rBAA11RgD1CAJPPdAAGPO1KuZzs243_640*640.jpg 

Occasionally appear in the list. The url contains special characters？

**Comment by IanChilds** [comment]
Can you post a code snippet please? 

Also, what do you mean by "occasionally appear in the list"? Does this also happen for some other urls?

**Comment by liujianying** [comment]
Trouble side of # 254 under his problem as much as I do 
https://github.com/facebook/fresco/issues/254
thank you
