### ISSUE TITLE
Loss the ninePatchChunk info in bitmap

### ISSUE THREAD

**Issue by Richard0403** [facebook/fresco#2523]
I download a picture that contains nine patch info by ImagePipeline, but  i get a bitmap without nine path info

the code is
```
 val url = "https://childsong.oss-cn-beijing.aliyuncs.com/jpg/icon_test_nine_patch.png"
        val imagePipeline = Fresco.getImagePipeline()
        val imageRequest: ImageRequest? = ImageRequest.fromUri(url)
        val dataSource = imagePipeline.fetchDecodedImage(imageRequest, context)
        dataSource.subscribe(object : BaseBitmapDataSubscriber() {
            override fun onFailureImpl(dataSource: DataSource<CloseableReference<CloseableImage>>) {

            }

            override fun onNewResultImpl(bmpTemp: Bitmap?) {
                var chunk = bmpTemp?.ninePatchChunk
                // this chunk == null
            }
        }, UiThreadImmediateExecutorService.getInstance())
``` 

I download this picture by a normal thread, Bitmap.ninePatchChunk is not null

**Comment by oprisnik** [comment]
Hi! It looks like nine patch decoding is not supported right now. Fresco just decodes the 9patch as a normal png (since that is what it is, just with the 1px border that indicates what to stretch.

This could be solved either with a custom decoder that properly handles that border or by getting the encoded image and using Android's 9patch decoding manually.

**Comment by oshamahue** [comment]
Hi, We have added a sample for how to use 9patch with fresco.  Feel free to check this [commit](https://github.com/facebook/fresco/commit/4c364a0db0d8daba5e244614f8ecd49704a2429e )

**Comment by oshamahue** [comment]
I want to note that for 9 patch to work chunk info needs to be added to the file. For Android res images it happen at compile for external images they need to be chunk info needs to be added at runtime or at server side. There are various libraries available to do that at runtime and server side.
