### ISSUE TITLE
target 30   android X

### ISSUE THREAD

**Issue by FireLightYoung** [facebook/fresco#2528]
AndroidX is not supported in my project, but I would like target to be updated to 30. Currently, it cannot be completed. Will the older version do target support?

**Comment by Zsl19871212** [comment]
I have the same question

**Comment by jisuanji1ban09** [comment]
support is also used in my project. I need support new version

**Comment by yuesetaimei** [comment]
I have also encountered this kind of adaptation problem. Is there a better way to solve it

**Comment by yuesetaimei** [comment]
I have also encountered this kind of adaptation problem. Is there a better way to solve it? Please give me some advice. thanks

**Comment by tager988** [comment]
Is there a good solution?
