### ISSUE TITLE
How to get current disk cache size

### ISSUE THREAD

**Issue by NNirvana** [facebook/fresco#253]
I wanna show disk cache size in my app

**Comment by IanChilds** [comment]
You can do the following: 

`Fresco.getImagePipelineFactory().getMainDiskStorageCache().getSize();`

**Comment by NNirvana** [comment]
Thank you

**Comment by MurtadhaS** [comment]
This doesn't work anymore.

**Comment by lambdapioneer** [comment]
Hi @MurtadhaS, that observation is correct. The name changed and the correct one is:

```java
final long diskCacheSizeInBytes = 
    Fresco.getImagePipelineFactory().getMainFileCache().getSize();
```

**Comment by MurtadhaS** [comment]
still returns -1 all the time for me.

**Comment by jackqack** [comment]
It doesn't work me either, always returns `-1`.
