### ISSUE TITLE
 java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by snowf07** [facebook/fresco#2533]
1 android.graphics.Bitmap.nativeCreate(Native Method)
2 android.graphics.Bitmap.createBitmap(Bitmap.java:1266)
3 android.graphics.Bitmap.createBitmap(Bitmap.java:1224)
4 android.graphics.Bitmap.createBitmap(Bitmap.java:1174)
5 android.graphics.Bitmap.createBitmap(Bitmap.java:1135)
6 com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:4)
7 com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:1)
8 com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:24)
9 com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.createBitmapInternal(ArtBitmapFactory.java:2)
10 com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:3)
11 com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:1)
12 com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:7)
13 com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:16)
14 com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.run(DefaultBitmapFramePreparer.java:6)
15 com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:2)
16 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
17 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
18 com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:2)
19 java.lang.Thread.run(Thread.java:929)

**Comment by defHLT** [comment]
Hi,

This can happen when decoding too many images with large dimensions. If this happens consistently for you, could please provide more details?

**Comment by snowf07** [comment]
thanks,I replaced it with a Glide framework.

**Comment by snowf07** [comment]
https://github.com/facebook/fresco/issues/2533#issuecomment-680792944

**Comment by snowf07** [comment]
I am playing webp animation caused by an error
