### ISSUE TITLE
Image occasionally load not to come out, throw an exception: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by 1908561871** [facebook/fresco#254]
The following two different exception occurs

The first initialization:

    Fresco.initialize(context);
    onFailure(String id, Throwable throwable) {
    /***   java.io.FileNotFoundException  *****/
    }

 In case:Occasional pictures showed not to come out, can show the pictures to request.

========================================================================

The second initialization:
    ImagePipelineConfig config = OkHttpImagePipelineConfigFactory.newBuilder(this, new OkHttpClient())
                .setMainDiskCacheConfig(diskCacheConfig)
                .build();

    Fresco.initialize(weiLeCtx, config);
    onFailure(String id, Throwable throwable) {
     /*********java.lang.IllegalArgumentException: unknown image format **********/
    }

 In case:Occasional pictures showed not to come out, to request or show not to come out, doubt is Okhttp cache problem

![snap](https://cloud.githubusercontent.com/assets/7844583/7583857/ad5cfe7e-f8cb-11e4-860f-94604059680b.jpg)

**Comment by IanChilds** [comment]
What is the image that is failing to load?

**Comment by plamenko** [comment]
reaping
