### ISSUE TITLE
Rounded Corners Distort Images

### ISSUE THREAD

**Issue by Peter0014** [facebook/fresco#2541]
### Description

Inside my Android application I have a RecyclerView that includes several SimpleDraweeView fed with urls from an API.
 
The actualImageScaleType is set to "centerInside" and there is a background color set. 

To fit the design I use rounded corners, too. Unfortunately this breaks all images in places where the background would be visible (also happens if roundedCornerRadius is set to 1dp). 

See following images:
![image](https://user-images.githubusercontent.com/15862181/94291647-2d482b80-ff5c-11ea-8390-885be2e89c2e.png)
![image](https://user-images.githubusercontent.com/15862181/94291783-55378f00-ff5c-11ea-8cfb-b412c93a01fe.png)

I hope that is not the intended behavior in this case.

### Reproduction

A sample project can be found here - [https://github.com/Peter0014/Fresco_Rounded_Corners_Bug](https://github.com/Peter0014/Fresco_Rounded_Corners_Bug)

### Additional Information

* Fresco version: 2.3.0
* Platform version: tested on Pixel 2 API 30 (Emulator) and Xiaomi Mi 10 API 30 (Device)

**Comment by EMIN3M1986** [comment]
I have the same issue.
It happens when I just set corner radius. 
new RoundingParams().setCornersRadii(cornerRadius, cornerRadius, 0, 0));

**Comment by eslamfaisal** [comment]
I have the same issue.
It happens when I just set corner radius.
new RoundingParams().setCornersRadii(cornerRadius, cornerRadius, 0, 0));

**Comment by Peter0014** [comment]
Problem still persists. If a developer could add a label to this bug.

**Comment by oprisnik** [comment]
Hey! Unfortunately this is a limitation for bitmap shaders, they repeat edges. In your case, you can use the overlay rounding mode, see https://frescolib.org/docs/rounded-corners-and-circles.html#caveats for more information.

Another alternative is to either use Android's Outline API or round the bitmap using a BitmapTransformation and https://github.com/facebook/fresco/blob/master/native-filters/src/main/java/com/facebook/imagepipeline/nativecode/NativeRoundingFilter.java

**Comment by TaeHyungK** [comment]
I have same issue in fresco version 2.3.0. 
Please see rounding area.
How to fix this bug?

sample image:
![image](https://user-images.githubusercontent.com/27183572/147072030-9c489ffe-6087-468e-84b5-3aad6277633d.png)

**Comment by oprisnik** [comment]
This was fixed with a592ca5e3e9d8ffd523c5161d39bd479d48aefd1 and the next Fresco version should properly handle this

**Comment by JamesGZM** [comment]
> 这已通过[a592ca5](https://github.com/facebook/fresco/commit/a592ca5e3e9d8ffd523c5161d39bd479d48aefd1)修复，下一个 Fresco 版本应该可以正确处理这个问题

Hope to update as soon as possible

**Comment by BeeMargarida** [comment]
Hi, any update regarding the next Fresco version?
