### ISSUE TITLE
Kindly help

### ISSUE THREAD

**Issue by Namai20** [facebook/fresco#2544]
This is the error code and i am unable to fond the bitmap and softwareserial liberary 

Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Nano, ATmega328P 
RetroWatchArduino_u8glib:32:10: fatal error: bitmap.h: No such file or directory

 #include "bitmap.h"

Multiple libraries were found for "SoftwareSerial.h"

          ^~~~~~~~~~

 Used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.42.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\SoftwareSerial

compilation terminated.

 Not used: C:\Users\ABC\Documents\Arduino\libraries\SoftwareSerial-master

exit status 1

bitmap.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Namai20** [comment]
enhancement

**Comment by oprisnik** [comment]
Hey! Can you please fill out the template for the issue? Fresco is an Android image loading library an it seems that you are trying to use it on an Arduino?
