### ISSUE TITLE
SimpleDraweeView  circle display occurs some problem

### ISSUE THREAD

**Issue by ffyliu** [facebook/fresco#2546]
test device:huawei mate 9

version:
'com.facebook.fresco:fresco:2.3.0'
'com.facebook.fresco:imagepipeline-okhttp3:2.3.0'
'com.facebook.fresco:animated-base:2.3.0'
'com.facebook.fresco:animated-gif:2.3.0'
'com.facebook.fresco:animated-webp:2.3.0'
'com.facebook.fresco:webpsupport:2.3.0'

the xm is below:

<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/itemImg"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="10dp"
        fresco:actualImageScaleType="fitXY"
        fresco:placeholderImage="@drawable/head_xiaop_default"
        fresco:placeholderImageScaleType="fitXY"
        fresco:roundAsCircle="true" />

when i use the normal Activity Configuration,the normal display image is:
![normal_display](https://user-images.githubusercontent.com/43327380/95953713-cc11ca80-0e2c-11eb-8623-c120b844f22b.png)

when i change the Activity Configuraton，and zoom the densityDpi to 1.3 times，the error display image is:
![error_display](https://user-images.githubusercontent.com/43327380/95954093-5fe39680-0e2d-11eb-832a-24c454459194.png)

the code is:
protected Context getAttachBaseContext(Context newBase) {
        return isDefaultDisplay() ? newBase : DisplayUtils.attachBaseContext(newBase);
    }

public static Context attachBaseContext(Context context) {
        Configuration config = context.getResources().getConfiguration();
        initFontScale(config);
        if (usedDpi > 0) {
            config.fontScale = 1f;
            config.densityDpi = usedDpi;
        } else {
            config.fontScale = usedScale;
        }
        return context.createConfigurationContext(config);
 }

**Comment by oprisnik** [comment]
Hey! Unfortunately this is a limitation for bitmap shaders, they repeat edges. In your case, you can use the overlay rounding mode, see https://frescolib.org/docs/rounded-corners-and-circles.html#caveats for more information.

**Comment by ffyliu** [comment]
> Hey! Unfortunately this is a limitation for bitmap shaders, they repeat edges. In your case, you can use the overlay rounding mode, see https://frescolib.org/docs/rounded-corners-and-circles.html#caveats for more information.

Thank you very much for your reply, because this problem occurred only when I upgraded from version 1.9.0 to version 2.3.0. I want to know why, under the same conditions, the bitmap boundary was not drawn repeatedly in version 1.9.0.
