### ISSUE TITLE
:imagepipeline:downloadGiflib

### ISSUE THREAD

**Issue by xingxiang1989** [facebook/fresco#255]
Error:Execution failed for task ':imagepipeline:downloadGiflib'.
> java.net.SocketException: Unexpected end of file from server

**Comment by IanChilds** [comment]
Can you try again? Seems like it's probably a transient issue.

**Comment by xingxiang1989** [comment]
[x86] SharedLibrary  : libbitmaps.so
[armeabi-v7a] Install        : libbitmaps.so => /Users/xiangxing/StudioProject/fresco/imagepipeline/build/bitmaps/armeabi-v7a/libbitmaps.so
[armeabi] Install        : libbitmaps.so => /Users/xiangxing/StudioProject/fresco/imagepipeline/build/bitmaps/armeabi/libbitmaps.so
[x86] Install        : libbitmaps.so => /Users/xiangxing/StudioProject/fresco/imagepipeline/build/bitmaps/x86/libbitmaps.so
make: Leaving directory `/Users/xiangxing/StudioProject/fresco/imagepipeline/src/main/jni/bitmaps'
:imagepipeline:createNativeDepsDirectories UP-TO-DATE
:imagepipeline:downloadGiflib FAILED
Error:Execution failed for task ':imagepipeline:downloadGiflib'.
> java.net.SocketException: Unexpected end of file from server

**Comment by IanChilds** [comment]
Looks like you're having trouble connecting to sourceforge. There are two options for you: 

1, Do you have to build from source, or can you just use the instructions on this page: http://frescolib.org/docs/index.html#_

2, Try downloading the sources you need directly from sourceforge and put them into nativedeps/downloads. The sources you need are all specified here: https://github.com/facebook/fresco/blob/master/imagepipeline/build.gradle#L70-L96
