### ISSUE TITLE
version change in handle bitmap shaders

### ISSUE THREAD

**Issue by ffyliu** [facebook/fresco#2557]
Hey! Unfortunately this is a limitation for bitmap shaders, they repeat edges. In your case, you can use the overlay rounding mode, see https://frescolib.org/docs/rounded-corners-and-circles.html#caveats for more information.

_Originally posted by @oprisnik in https://github.com/facebook/fresco/issues/2546#issuecomment-710000373_

Thank you very much for your reply, because this problem occurred when I upgraded from version 1.9.0 to version 2.3.0. I want to know why, under the same conditions, the bitmap boundary was not drawn repeatedly in version 1.9.0.

**Comment by oprisnik** [comment]
Hey! I don't believe we changed anything in version 1.9.0. This caveat has always been documented, even before we had Fresco version 1.0.0.
Did your image change or maybe aspect ratio etc?

**Comment by ffyliu** [comment]
Thank you very much for your reply. I'll write a demo and try again。
After the reappearance, I sent out the demo

**Comment by ffyliu** [comment]
> Hey! I don't believe we changed anything in version 1.9.0. This caveat has always been documented, even before we had Fresco version 1.0.0.
> Did your image change or maybe aspect ratio etc?

The attachment is the corresponding test demo。

modify the config.gradle file with 1.9.0 to compile apk
1.install and run,the display is normal
2.click the top-right set menu and adjust the fontSize too max and return back(dialog choose  sure)
3.the display is still normal

modify the version to 2.3.0 and do the above steps again，step1 is normal，step3 is error。

 // facebook,fresco\stetho
            'facebook-fresco'                          : 'com.facebook.fresco:fresco:2.3.0',
            'facebook-fresco-imagepipeline-okhttp3'    : 'com.facebook.fresco:imagepipeline-okhttp3:2.3.0',
            'facebook-fresco-animated-base'            : 'com.facebook.fresco:animated-base:2.3.0',
            'facebook-fresco-animated-gif'             : 'com.facebook.fresco:animated-gif:2.3.0',
            'facebook-fresco-animated-webp'            : 'com.facebook.fresco:animated-webp:2.3.0',
            'facebook-fresco-webpsupport'              : 'com.facebook.fresco:webpsupport:2.3.0',
//            'facebook-fresco'                          : 'com.facebook.fresco:fresco:1.9.0',
//            'facebook-fresco-imagepipeline-okhttp3'    : 'com.facebook.fresco:imagepipeline-okhttp3:1.3.0',
//            'facebook-fresco-animated-base'            : 'com.facebook.fresco:animated-base:1.9.0',
//            'facebook-fresco-animated-gif'             : 'com.facebook.fresco:animated-gif:1.9.0',
//            'facebook-fresco-animated-webp'            : 'com.facebook.fresco:animated-webp:1.9.0',
//            'facebook-fresco-webpsupport'              : 'com.facebook.fresco:webpsupport:1.9.0',

[TestAll.zip](https://github.com/facebook/fresco/files/5514805/TestAll.zip)

**Comment by ffyliu** [comment]
The http address of the picture in demo above cannot be accessed, and the http address in this attachment should be OK

Special note: the placeholderImage has the same problem，so both demo can be used for testing。

[TestAll.zip](https://github.com/facebook/fresco/files/5514889/TestAll.zip)

**Comment by ffyliu** [comment]
Is there any progress? 
looking forward to your reply. 😊

**Comment by ffyliu** [comment]
The question still exists. Do you need any other details？

**Comment by hilo-feng** [comment]
> Thank you very much for your reply. I'll write a demo and try again。
> After the reappearance, I sent out the demo

问题解决了?
