### ISSUE TITLE
Loading large resolution pictures

### ISSUE THREAD

**Issue by lidexin-aldelo** [facebook/fresco#2561]
Hello! We use this library in our development as an image loading dependency. But in use, if the image resolution is particularly high. For example, 5990 * 4180. At this time, there are multiple imageviews, and the system refresh rate drops sharply. It will be very stuck. Is there any solution?

* Fresco version: [2.3.0]
* Platform version: [SUMMI M2 Android Version:7.1.2]

**Comment by oprisnik** [comment]
Hey! There are multiple ways how you can resize the image so that it does not require as much memory:

https://frescolib.org/docs/resizing.html
