### ISSUE TITLE
setImageBitmap alternative

### ISSUE THREAD

**Issue by farfromrefug** [facebook/fresco#2565]
I know we cant use `setImageBitmap` directly. Now how i  can set `android.graphics.Bitmap` inside a `DraweeView` while keeping the hierarchy?
I need to be able to apply a `Bitmap` which came from somewhere else (like camera) inside a `DraweeView`.

Thanks

**Comment by oprisnik** [comment]
If you don't want to use Fresco to load the image but supply your own Bitmap, you can do something like this:

draweeView.getHierarchy().setImage(new BitmapDrawable(bitmap), 1, true);
The last param specifies if it should be shown immediately or via a fade in animation if false (if a fade duration is set).
