### ISSUE TITLE
gif play once? how can i config?

### ISSUE THREAD

**Issue by ZINK-FU** [facebook/fresco#2575]
i want to play gif once, and stop at last frame, how can i do?

**Comment by oprisnik** [comment]
You could use an AnimationListener where you manually stop the animation in onAnimationRepeat if there are multiple loops.
You'd have to set this listener via a ControllerListener where you get the Animatable in onFinalImageSet, which you can cast t AnimatedDrawable2.

**Comment by SEUCalvin** [comment]
onAnimationRepeat is unreliable, sometimes the gif will be played several times before calling onAnimationRepeat. If you know the frameNumber of the gif, onAnimationFrame maybe a good time to stop the animation.
