### ISSUE TITLE
Inherit from ShapeableImageView

### ISSUE THREAD

**Issue by katajona** [facebook/fresco#2576]
### Description

Currently, it is not possible to custom shape our SimpleDraweeView. com.google.android.material.imageview.ShapeableImageView would offer a solution for this. It would also fix all the issues with roundAsCircle and would offer even more customization.

**Comment by wizh** [comment]
Hi, thanks for your question. In the future when we release Vito this would be supported automatically by VitoView. For now you could write a custom view which does that or make SimpleDraweeView inherit ShapeableImageView yourself.

**Comment by katajona** [comment]
That sounds really good. Is there a timeline for when will it be released?

**Comment by wizh** [comment]
No, we don't have a specific timeline in mind yet. I'm closing the issue since the original question was answered, but feel free to open a new issue if you need further support.
