### ISSUE TITLE
CloseableAnimatedImage  class can not be found

### ISSUE THREAD

**Issue by cjztool** [facebook/fresco#2577]
After upgraded Fresco  from 1.9.0 to 2.3.0, add additional Fresco feature modules as follow:

    api 'com.facebook.fresco:fresco:2.3.0'
    api 'com.facebook.fresco:animated-gif:2.3.0'
    api 'com.facebook.fresco:animated-webp:2.3.0'
    api 'com.facebook.fresco:webpsupport:2.3.0'
    api 'com.facebook.fresco:imagepipeline-okhttp3:2.3.0'

CloseableAnimatedImage  class can not be found.

Did i miss something?

**Comment by wizh** [comment]
Hi! Thanks for your question. Can you please try adding a dependency to 'com.facebook.fresco:animated-base:2.3.0'?

**Comment by cjztool** [comment]
> Hi! Thanks for your question. Can you please try adding a dependency to 'com.facebook.fresco:animated-base:2.3.0'?

worked, Thank you!

Where can I find the full list of Fresco feature modules or/and some docs about upgrading?

**Comment by wizh** [comment]
You can find all of our documentation here: https://frescolib.org/docs/. I'm closing this since the issue is resolved, but feel free to open a new issue if you need further support!
