### ISSUE TITLE
when committers can solve the problem that fresco can't lots of bitmaps from sdcard or contentprovider

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#258]
I use girdview to load around 30 bitmaps from sdcard on screen each time.But it only display 11 bitmaps on screen.details on question#256

**Comment by NNirvana** [comment]
I think you can try to find the reason by yourself, but not keep asking here

**Comment by IanChilds** [comment]
As NNirvana says, please don't keep filing issues for the same problem. If you are able to investigate yourself, that would be great. We have many things on our to-do list at the moment.
