### ISSUE TITLE
Change width and height of  simpleDraweeView's  LayoutParams cause strange result

### ISSUE THREAD

**Issue by NNirvana** [facebook/fresco#259]
![1](https://cloud.githubusercontent.com/assets/6387593/7603017/f74db0b2-f95e-11e4-83b5-2888d6383f16.png)
![2](https://cloud.githubusercontent.com/assets/6387593/7603023/01d49b04-f95f-11e4-8c1e-680b00c2a28c.png)

first  is the source image.
After get the bitmap's size, I change simpleDraweeView's width and height by ratio. Then I get the strange result as second image.
The SimpleDraweeView was set ScalingUtils.ScaleType.FIT_XY, and  setAspectRatio 1.5f

**Comment by NNirvana** [comment]
I find it may be cause by scale type. 
If I set scale type to CENTER_INSIDE, the image was show in the center of SimplwDraweeView, but with that strange affect around the image(left top right bottom).
If I set scale type to CENTER_CROP, result is OK.
Is this a bug?

**Comment by IanChilds** [comment]
Could you give a code snippet please?

**Comment by NNirvana** [comment]
My SimpleDraweeViews are created dynamically based on a list of url.Each created SimpleDraweeView is added into a LinearLayout and display image with a url in the list. Then I will get a bitmap thought a callback. With this bitmap's width and height, I change SimpleDraweeView's size to fit the LinearLayout's width, and SimpleDraweeView's height is also changed by ratio.
![1](https://cloud.githubusercontent.com/assets/6387593/7608802/a694a568-f99f-11e4-910a-8a4fa6e6b026.png)
![2](https://cloud.githubusercontent.com/assets/6387593/7608810/b12a30ba-f99f-11e4-95c9-f10271b759be.png)
![3](https://cloud.githubusercontent.com/assets/6387593/7608814/b69ce48e-f99f-11e4-930e-d88415f5f437.png)
![4](https://cloud.githubusercontent.com/assets/6387593/7608818/bd03edcc-f99f-11e4-92bb-5a57bc9ab5bd.png)

Is this enough?

**Comment by IanChilds** [comment]
The problem here is actually related to your use of rounded corners - please see the caveats section in the docs: http://frescolib.org/docs/rounded-corners-and-circles.html#caveats. If you want to use CENTER_INSIDE then you are advised to use the OVERLAY_COLOR rounding method rather than the default BITMAP_ONLY rounding method.

**Comment by NNirvana** [comment]
When I call createDraweeHierarchy method,I set second and third params to false. So there are no corners

**Comment by IanChilds** [comment]
There is a fix coming for this, but it still breaks if you set RoundingParams with each corner having radius 0. Can you remove the `.setRoundingParams` line and see if it works after that?

**Comment by NNirvana** [comment]
OK, I will try

**Comment by NNirvana** [comment]
You are right! I remove .setRoundingParams line, and use FIX_XY like before.It's OK now
