### ISSUE TITLE
Get multiple images from postProcess

### ISSUE THREAD

**Issue by mohammedhammouri** [facebook/fresco#26]
I have an image I want it to be processed ,but on the other hand I need both images the processed image and the original one to be passed to the ControllerListener (I need an array of imageInfo insted of only the processed imageInfo), can I do it now or should I wait ?

**Comment by plamenko** [comment]
Can you give us more context on what are you trying to achieve? I'm pretty sure we already support what you need, but I need some clarifications in order to be able to help.

**Comment by mohammedhammouri** [comment]
1- I get images from server.
2- then I blur the image.
  I want to display both images the original one and the blurred one together in one imageView (DraweeView) 
Example : 

![screenshot_1](https://cloud.githubusercontent.com/assets/6051190/6887237/b9d7a5e6-d661-11e4-9430-761863836953.jpg)

**Comment by plamenko** [comment]
If I am interpreting your example correctly, you want only a part of the image to be blurred?
Or do you want to display those two side-by-side (but this seems not to be the case based on your example)?
Or do you want to display first the original and then the blurred image?

**Comment by mohammedhammouri** [comment]
I want to display them side-by-side , I do that by taking the original image cut it then blur it after that put both the original and the blurred image togather.
So I blur and cut the image in on PostExecute but I want both the original and the blurred get returned to DraweeView

**Comment by plamenko** [comment]
The easiest solution would be to use the post-processor that blurs the part of the image only.
Post-processor provides you a bitmap to modify, so why not just blurring the part of it?

Can you give us more context on why do you "want both the original and the blurred image get returned to DraweeView"? To solve the problem you described, this is not necessary and by providing a more context, we may be able to devise a better solution.

**Comment by mohammedhammouri** [comment]
This is an example why I need two images , or if you have any other ideas you are welcome :D
![_____15_v_1920_1080](https://cloud.githubusercontent.com/assets/6051190/6902896/6334abda-d71f-11e4-86e5-b9943749afcd.gif)

**Comment by plamenko** [comment]
Okay, if you are not actually changing the blurred area, but rather just sliding in the blurred image, than you can have two SimpleDraweeViews: the original one below, and the blurred one on top that slides in.

**Comment by mohammedhammouri** [comment]
Thank you alot you have fixed my problem :D , I will try it.
