### ISSUE TITLE
Library is too big

### ISSUE THREAD

**Issue by walksin** [facebook/fresco#260]
Will fresco reduce it's lib size? We once use UIL and it's 193KB, however since we use fresco, it makes our apk much more larger then using UIL, would you help to show how to minimize frescolib? TKS.

**Comment by gajicm93** [comment]
If you haven't, take a look at http://frescolib.org/docs/proguard.html#_ and http://frescolib.org/docs/multiple-apks.html#_

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by prateek1190** [comment]
any updates on this ?

**Comment by ppamorim** [comment]
+1

**Comment by beartung** [comment]
any updates on this ?

**Comment by aashrairavooru** [comment]
Around 5k methods and the image pipeline takes too much memory, I love fresco but this is just way too much

**Comment by massimocarli** [comment]
We're working on reducing size library making all modules optionals. Stay on tune!

**Comment by hellosure** [comment]
any updates on this?

**Comment by artemik** [comment]
+1

**Comment by ashish29agre** [comment]
+1

**Comment by ndurell** [comment]
+1

**Comment by yangkai3** [comment]
+1

**Comment by NammariMarkavip** [comment]
+1

**Comment by MycroftWong** [comment]
+1

**Comment by dudhatparesh** [comment]
+1

**Comment by sirius60111** [comment]
+1

**Comment by tomzhaowang** [comment]
+1

**Comment by oprisnik** [comment]
With v0.10.0 we split Fresco up in more AARs to make the core library smaller, see http://frescolib.org/docs/index.html

**Comment by alexodus** [comment]
what does png and jpeg code inside  static-webp /src/main/jni/static-webp folder?
