### ISSUE TITLE
How to use schema res://

### ISSUE THREAD

**Issue by hiphonezhu** [facebook/fresco#261]
Like the title

**Comment by NNirvana** [comment]
ImageRequestBuild has a static method newBuilderWithResourceId(int resId):

public static ImageRequestBuilder newBuilderWithResourceId(int resId) {
    Uri uri = new Uri.Builder()
        .scheme(UriUtil.LOCAL_RESOURCE_SCHEME)
        .path(String.valueOf(resId))
        .build();

    return newBuilderWithSource(uri);
  }

there you go

**Comment by hiphonezhu** [comment]
Thank you
