### ISSUE TITLE
Upload 2.4.0 version to maven central repo

### ISSUE THREAD

**Issue by zetbrush** [facebook/fresco#2613]
### Description

2.4.0 is on jcenter only, which will be shut down, so pls upload 2.4.0 version to maven central repo

* Fresco version: 2.4.0

**Comment by dulmandakh** [comment]
@oprisnik please publish 2.4.0 to Maven Central, thanks

**Comment by oprisnik** [comment]
Hi! @passy helped us with setting up a release pipeline to publish to Maven Central. I plan to release a new version that's going to be on Maven Central in the next days.

**Comment by oprisnik** [comment]
Version 2.5.0 should now be available on Maven Central.

**Comment by zetbrush** [comment]
@oprisnik can you pls upload 2.4.0 version exactly?

**Comment by JulianKingman** [comment]
I ran into this after upgrading to react native 66 from 63. I updated my build.gradle to use 2.6.0, but I bet more people will run into this problem.
