### ISSUE TITLE
Fresco deletes other native libraries in apk

### ISSUE THREAD

**Issue by BHsueh** [facebook/fresco#264]
Hi,
We have one app which includes two native libraries and works well. We put these two native libraries under app/src/main/jniLibs/armeabi/ and build the app with Gradle.

But after we integrated Fresco, there is always one error on Nexus(Android 5.0.1) which said these two libraries couldn't be found. Then we checked the path on device, /data/app/our_app_package_name/lib/arm, where these two libraries are supposed to be. Both of theme are gone and only some new libraries are there,  like libbitmaps.so, libgifimage.so and etc.

Would you please help to have a check on this issue?

Thank you

**Comment by michalgr** [comment]
Hi,
At first it does not sound like an issue with fresco but rather gradle or gralde build script. I expect that the libraries are not included when packaging the final apk. You can unzip your apk and check if files are there. If no, can you provide more details on how do you tell gradle to include 2 missing libraries in the final apk ?

**Comment by BHsueh** [comment]
Hi,
Thanks a lot for your reminder.
We unzipped our apk and found that there were our libraries + fresco libraries under armeabi folder, but only fresco libraries under armeabi-v7 folder. This should be because we only create one folder to put our libraries, armeabi. Then on arm v7 device, this issue happens. After we created armeabi-v7 folder, the issue is fixed. 

Thank you! Have a good day.
