### ISSUE TITLE
Bug When Set "failureImage" and "roundedCornerRadius"(not zero value) at the same time

### ISSUE THREAD

**Issue by evangerlions** [facebook/fresco#2643]
### Description

When set "failureImage" and "roundedCornerRadius"(not zero value) at the same time, the failure Image display abnormal, see image below.

### Reproduction
* Device: XIAOMI 11
* Resolution: 3200*1400, **but 2400\*1400 is OK**
* Fresco version: 2.3.0 && 2.6.0, **but 0.13.0 is OK**
* Platform version: Android 11(MIUI 12.5)

Just copy simple code below to your Application, and with such conditions, you can see the bug stable recurrence.
moreover, set or change "failureImageScaleType" is totally useless.
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

        <com.facebook.drawee.view.SimpleDraweeView
            android:layout_width="94dp"
            android:layout_height="94dp"
            android:layout_gravity="center"
            fresco:actualImageUri="https//JustAInvalidUrl"
            fresco:failureImage="@drawable/my_failure_image"
            fresco:failureImageScaleType="centerInside"
            fresco:roundedCornerRadius="10dp" />

</FrameLayout>
```
(fresco: 2.6.0 && 2.3.0 ↓)
![image](https://user-images.githubusercontent.com/32103614/144705319-81602659-9ae6-436d-9019-d68f407f7f8a.png)
(fresco: 0.13.0 ↓)
![image](https://user-images.githubusercontent.com/32103614/144705340-7a4b522e-74be-451e-ae11-d4f82fbe86cf.png)

my_failure_image:
![my_failure_image](https://user-images.githubusercontent.com/32103614/144705380-d04f843c-c59b-4a1d-9285-eec451c7d49f.png)

**Comment by oprisnik** [comment]
Hi! This is an issue with resource loading, see https://github.com/facebook/fresco/issues/2260 for more info
