### ISSUE TITLE
Change Border Color not work in code

### ISSUE THREAD

**Issue by zhangtengchao** [facebook/fresco#267]
`<addr>` RoundingParams roundingParams = 
`<addr>`    mSimpleDraweeView.getHierarchy().getRoundingParams();
`<addr>` roundingParams.setBorder(R.color.red, 1.0);
`<addr>` roundingParams.setRoundAsCircle(true);
`<addr>` mSimpleDraweeView.getHierarchy().setRoundingParams(roundingParams);

These code not work in code.WHY?

**Comment by IanChilds** [comment]
You should do `getResources().getColor(R.color.red)`
