### ISSUE TITLE
Playing animations

### ISSUE THREAD

**Issue by adnan-SM** [facebook/fresco#27]
The docs say : 

```java
Uri uri;
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
    .setAutoPlayAnimation(true)
    . // other setters
    .build();
    
```
But ImageRequestBuilder class has no method named setAutoPlayAnimation()

**Comment by plamenko** [comment]
This is a typo in the docs. one "s" is missing, it should be `setAutoPlayAnimations`. I wonder if it would be easier to just try autocomplete instead of opening issue.

**Comment by plamenko** [comment]
Ah sorry, this is a controller builder setter, not image request builder setter
