### ISSUE TITLE
Document about how to use Fresco in Intellij IDEA

### ISSUE THREAD

**Issue by liaohuqiu** [facebook/fresco#270]
We need a section in http://frescolib.org/docs/index.html to introduce how to use Fresco in Intellij IDEA or Maven .

**Comment by IanChilds** [comment]
The maven docs will be done in due course. What is it that you would like the Intellij docs to contain? I.e. what is your use case?

**Comment by liaohuqiu** [comment]
As discussed in this issue: https://github.com/facebook/fresco/issues/239, there are some problems while using Fresco as a maven dependency:

1.  The dependencies can not be resolved.
2.  Must copy the native libs to /libs manually.

I've finished the Chinese version. I do not know why we did not have the part. I remembered it existed in the early version and was removed the version.

**Comment by IanChilds** [comment]
Yeah it was removed as there were problems - it will be added back in by @tyronen once it is fixed.

**Comment by liaohuqiu** [comment]
@tyronen  If the problems were the two I mentioned above. I can finish this section.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
