### ISSUE TITLE
META-INF/services/javax.annotation.processing.Processor error 

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#271]
use library butterknife realm-android
android {
	  packagingOptions {
	    exclude 'META-INF/services/javax.annotation.processing.Processor'
	  }
	}

fresco error 
 at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
            at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:36)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:59)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)

**Comment by IanChilds** [comment]
I'm not totally clear on the relation between the error, and the code you have given that presumably is part of your build.gradle. Do you think that part of your build.gradle is causing the problem, or what?

**Comment by chonamdoo** [comment]
my build gradle setting

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url "http://dl.bintray.com/countly/maven" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'me.tatarka:gradle-retrolambda:2.5.0'
    }
}
repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
}
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

def timestamp() {
    def date = new Date()
    def formattedDate = date.format('yyyyMMddHHmmss')
    return formattedDate.substring(2, 8)
}

apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'io.fabric'
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"
    project.archivesBaseName = "Couchgram_dev"
    project.ext.set("buildTimestamp", timestamp());
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "com.couchgram.privacycall"
        versionCode 40
        versionName "1.5.0-devel"
        minSdkVersion 14
        targetSdkVersion 22
        multiDexEnabled true
    }
    signingConfigs {
        releaseWith {
            storeFile file(keystore);
            storePassword keystore_pass
            keyAlias key_alias
            keyPassword key_pass

        }
    }
    buildTypes {
        debug {
            minifyEnabled true
            signingConfig signingConfigs.releaseWith
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.releaseWith
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'AndroidManifest.xml'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    dexOptions {
        jumboMode true
        incremental true
        javaMaxHeapSize "4g"
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def apkFile = output.outputFile
            if (apkFile != null && apkFile.name.endsWith('.apk')) {
                def newApkName = apkFile.name.replace("-" + variant.buildType.name, "")
                newApkName = newApkName.replace(".apk",
                        "-v" + defaultConfig.versionName + "-" + defaultConfig.versionCode +
                                "-" + variant.buildType.name.toUpperCase() + ".apk")
                output.outputFile = new File(apkFile.parent, newApkName)
            }
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.android.support:support-annotations:22.1.1'
    compile 'com.android.support:recyclerview-v7:22.1.1'
    compile 'com.google.android.gms:play-services:7.3.0'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.googlecode.libphonenumber:libphonenumber:7.0.1'
    compile 'com.jakewharton:butterknife:6.1.0'
    compile 'com.facebook.fresco:fresco:0.4.0+'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.3.0'
    compile 'com.shehabic.droppy:Droppy:0.2.5.1@aar'
    compile 'com.timehop.stickyheadersrecyclerview:library:0.4.0@aar'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.facebook.stetho:stetho:1.1.0'
    compile 'com.facebook.stetho:stetho-okhttp:1.1.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'io.reactivex:rxandroid:0.24.0'
    compile 'com.github.lzyzsd:circleprogress:1.1.0@aar'
    compile 'commons-cli:commons-cli:1.2'
    compile 'commons-io:commons-io:2.4'
    compile group: project.KAKAO_SDK_GROUP, name: 'kakaolink', version: project.KAKAO_SDK_VERSION
    compile 'ly.count.android:sdk:15.03'
    compile 'com.rabbitmq:amqp-client:3.5.1'
    compile 'com.balysv.materialmenu:material-menu-toolbar:1.5.1'
    compile 'com.github.pwittchen:networkevents:1.0.4'
    compile 'jp.wasabeef:recyclerview-animators:1.2.0@aar'
    compile 'io.realm:realm-android:0.80.3-SNAPSHOT'
    compile('com.crashlytics.sdk.android:crashlytics:2.+@aar') {
        transitive = true;
    }
}

**Comment by chonamdoo** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/multiwindow.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.couchgram.privacycall-1/base.apk"],nativeLibraryDirectories=[/data/app/com.couchgram.privacycall-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libmemchunk.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
            at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
            at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
            at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:36)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:59)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:58)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:49)
            at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(Threa


buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url "http://dl.bintray.com/countly/maven" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'me.tatarka:gradle-retrolambda:2.5.0'
    }
}
repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    maven {
        url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
    }
}
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

def timestamp() {
    def date = new Date()
    def formattedDate = date.format('yyyyMMddHHmmss')
    return formattedDate.substring(2, 8)
}

apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'io.fabric'
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"
    project.archivesBaseName = "Couchgram_dev"
    project.ext.set("buildTimestamp", timestamp());
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "com.couchgram.privacycall"
        versionCode 40
        versionName "1.5.0-devel"
        minSdkVersion 14
        targetSdkVersion 22
        multiDexEnabled true
    }
    signingConfigs {
        releaseWith {
            storeFile file(keystore);
            storePassword keystore_pass
            keyAlias key_alias
            keyPassword key_pass

        }
    }
    buildTypes {
        debug {
            minifyEnabled true
            signingConfig signingConfigs.releaseWith
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.releaseWith
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'AndroidManifest.xml'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    dexOptions {
        jumboMode true
        incremental true
        javaMaxHeapSize "4g"
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def apkFile = output.outputFile
            if (apkFile != null && apkFile.name.endsWith('.apk')) {
                def newApkName = apkFile.name.replace("-" + variant.buildType.name, "")
                newApkName = newApkName.replace(".apk",
                        "-v" + defaultConfig.versionName + "-" + defaultConfig.versionCode +
                                "-" + variant.buildType.name.toUpperCase() + ".apk")
                output.outputFile = new File(apkFile.parent, newApkName)
            }
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.android.support:support-annotations:22.1.1'
    compile 'com.android.support:recyclerview-v7:22.1.1'
    compile 'com.google.android.gms:play-services:7.3.0'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.googlecode.libphonenumber:libphonenumber:7.0.1'
    compile 'com.jakewharton:butterknife:6.1.0'
    compile 'com.facebook.fresco:fresco:0.5.0+'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.3.0'
    compile 'com.shehabic.droppy:Droppy:0.2.5.1@aar'
    compile 'com.timehop.stickyheadersrecyclerview:library:0.4.0@aar'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.facebook.stetho:stetho:1.1.0'
    compile 'com.facebook.stetho:stetho-okhttp:1.1.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'io.reactivex:rxandroid:0.24.0'
    compile 'com.github.lzyzsd:circleprogress:1.1.0@aar'
    compile 'commons-cli:commons-cli:1.2'
    compile 'commons-io:commons-io:2.4'
    compile group: project.KAKAO_SDK_GROUP, name: 'kakaolink', version: project.KAKAO_SDK_VERSION
    compile 'ly.count.android:sdk:15.03'
    compile 'com.rabbitmq:amqp-client:3.5.1'
    compile 'com.balysv.materialmenu:material-menu-toolbar:1.5.1'
    compile 'com.github.pwittchen:networkevents:1.0.4'
    compile 'jp.wasabeef:recyclerview-animators:1.2.0@aar'
    compile 'io.realm:realm-android:0.80.3-SNAPSHOT'
    compile('com.crashlytics.sdk.android:crashlytics:2.+@aar') {
        transitive = true;
    }
}

**Comment by michalgr** [comment]
Do you get this behavior on 64bit device ? Can you unzip the apk and tell us what is there inside "lib" directory ?

**Comment by plamenko** [comment]
reaping
