### ISSUE TITLE
Delayed Rendering of Images with Custom Decoders

### ISSUE THREAD

**Issue by vignesh-em** [facebook/fresco#2729]
### Description

When using custom decoders, the decode method is called after a longer-than-usual delay resulting in delayed rendering of images.

Observations:
- The image is downloaded from the internet.
- The `determineFormat` method of the custom `ImageFormat.FormatChecker` is called and a correct `ImageFormat` is returned.
- The `decode` method of the custom `ImageDecoder` is called after 20-30 seconds (and in some cases even more than a minute)

### Reproduction

This is reproducible on OnePlus devices running Android 10 and 11 but works as expected on other devices.
The sample project can be found [here](https://github.com/vignesh-em-swiggy/fresco-custom-decoder).

### Additional Information

* Fresco version: 3.0.0
* Device: One Plus 9 (Android 11), One Plus 8 (Android 10)

**Comment by vignesh-em** [comment]
@oprisnik, do you think some other thread is holding up the resources required by this thread and the decode method is called after the resource is released? This however is specifically happening on OnePlus devices running Android 10 and 11.

**Comment by vignesh-em** [comment]
I was using a custom decoder for the [AV1 Image Format](https://aomediacodec.github.io/av1-avif/v1.1.0.html). When Fresco tries to decode the dimensions and colorspace to read the image metadata (`EncodedImage#readImageMetaData`), on certain devices, spends more than 5 seconds in `BitmapFactory.decodeStream()`. This is android version-specific and device-specific behaviour. Closing this as this is not an issue with Fresco.

**Comment by AS0820075980** [comment]
Chaiwat oppo A16

ในวันที่ ส. 3 มิ.ย. 2023 08:35 น. Vignesh ***@***.***>
เขียนว่า:

**Comment by vignesh-em** [comment]
As a step forward, for Custom Decoders, Fresco could allow clients to decode the dimensions and color space of the image and send it back.
