### ISSUE TITLE
While updating app from playstore the images not displaying properly 

### ISSUE THREAD

**Issue by KanagasathishP** [facebook/fresco#2735]
Build gradle added
implementation 'com.facebook.fresco:fresco:3.0.0
after that also still facing the issue  While updating app from playstore the images not displaying properly

**Comment by GoldenSoju** [comment]
Was this actually solved in the latest 3.1.0 or 3.1.1 release?

**Comment by steelrooter** [comment]
This issue was fixed in Fresco v3.1.3 released on Oct 25, 2023.
