### ISSUE TITLE
 some questions about fresco

### ISSUE THREAD

**Issue by JoneWeng** [facebook/fresco#274]
I have some questions about fresco. I'm working on an app which is similar to facebook-- sharing words, images, etc.  
1. How can we load the big pictures that must be load and bigger than 4096*4096? I have try to set at ResizeOption, but it's useless.  

2.When definite the view in fresco, some photos are transparent (getTopDraweeale). After setting the holderImage, some pictures are holderimage, and the others are target image. Really a bad experience.

![qq 20150515150644](https://cloud.githubusercontent.com/assets/12455694/7648347/895d50f0-fb14-11e4-8f00-99ccf2f0a6c2.png)

![3tql7 09 6j_y_nn6_6g ub](https://cloud.githubusercontent.com/assets/12455694/7648349/8c6d263a-fb14-11e4-9c73-d24f010684ce.png)

  3.when the listview sliding, it frequently appears gc and obvious memory thrashing that lead to sliding stuck ( don't exclude the problem of GPU drawing slowly).  Is this problem caused by fresco memory cache or second memory cache? If yes, how can I configure the cache.
Hope can get your reply soon. Thanks.

**Comment by JoneWeng** [comment]
3. when the listview sliding, it frequently appears gc and obvious memory thrashing that lead to sliding stuck ( don't exclude the problem of GPU drawing slowly).  Is this problem caused by fresco memory cache or second memory cache? If yes, how can I configure the cache.

**Comment by JoneWeng** [comment]
problem 2 is  customer view ,we want that can show single or many picture。

**Comment by IanChilds** [comment]
So if I understand correctly, you want to load a picture that is *bigger* than 4096 * 4096? What size are you trying to resize it to? 

for 2, can you give a code snippet and also the urls that are failing to load? I wouldn't expect to see these transparent images.

**Comment by JoneWeng** [comment]
Problem 1: picture height (4096+), width of uncertain (1000-), I want to 400*1000 about, there is no similar BitmapOption.inSampleSize API

**Comment by lushan1314** [comment]
same question 
```
ImageRequestBuilder.newBuilderWithSource(uri).setResizeOptions(new ResizeOptions(100, 100)).build() 
```
the param __ResizeOptions__ is not useful.

**Comment by lushan1314** [comment]
version : 0.4.0

**Comment by IanChilds** [comment]
What is the image format? Currently only JPEGs get resized

**Comment by lushan1314** [comment]
ok,i see. 
Here have JPEGS ,png, gif ...  look like only use __Postprocessor__ can solve it.

**Comment by JoneWeng** [comment]
it is jpegs. what is Postprocessor ? don't see it in fresco doc .

**Comment by JoneWeng** [comment]
Is there any way that I can get this picture(big),sorry i'm chinese, english is so bad.Help me to explain the problem 2, 3. Under the upload customer view  code .

**Comment by JoneWeng** [comment]
![qq 20150515225903](https://cloud.githubusercontent.com/assets/12455694/7655482/48a06614-fb56-11e4-8afa-785091991e5d.jpg)

![qq 20150515225922](https://cloud.githubusercontent.com/assets/12455694/7655484/4ac57290-fb56-11e4-9724-f10e18fa6ac5.jpg)

**Comment by JoneWeng** [comment]
![qq 20150515225952](https://cloud.githubusercontent.com/assets/12455694/7655518/8678431c-fb56-11e4-8339-bad8dc0fea9c.png)

**Comment by lushan1314** [comment]
我不知道你遇到什么问题了，显示大图会有问题吗？他这个自定义holder我没用，我建议如果不行就别用。你只用加载那块就好了

**Comment by JoneWeng** [comment]
不是，理论上 图片不可能加载4096*4096以上的，但是有这样的需求，不知道怎么解决。

**Comment by lushan1314** [comment]
他文档里有个后处理器，也就是图片加载完之后可以对图片做处理。[Postprocessor ](http://fresco-cn.org/docs/modifying-image.html)

**Comment by lushan1314** [comment]
哥们，我也遇到这个问题了。确实加载大图会有问题，加载不出来。
我有的sd卡的图片有的一张有4m的大小，一个页面多次加载会出现加载不出来。
由于这里图片格式是jpeg，所以加上ResizeOptions暂时解决了。其他格式肯定有问题。

你这边后来有找到什么方法没？

我想应该是这样的：
用ResizeOptions他就直接缓存处理后大小的图片，如果不用，直接缓存原图，但是原图太大，所以频繁的清除cache。

**Comment by Freedom000** [comment]
You two guys are really funny,aren't you?  So you are from the same place —— the Middle Kingdom!

**Comment by JoneWeng** [comment]
so what

**Comment by mheras** [comment]
English dude... English.

**Comment by tyronen** [comment]
Ok the issue with 4096x4096 has since been fixed. Latest Fresco will always resize the image to be less than 2048x2048 which is guaranteed to load across all devices.

For the transparency issue, can you show:
- what is the placeholder drawable? It looks like it is transparent
- what is the actual image? same issue
- how are you setting the controllers to the MultiDraweeHolder?

**Comment by JoneWeng** [comment]
Latest Fresco ? what version ?

**Comment by JoneWeng** [comment]
Of course, controller be setted to MultiDraweeHolder, Otherwise actual image not be showed.
ok, I have a problem. I don't understand it. 
how redraw work in  SimpleDraweeView ( what notify?), when image be load? 
i have to design can show multi image view, but this can't work . so i want put question to you ? 
i think the question is  multi image,because each image is loaded, it needs to be invalidate view?  
so i want know how redraw work in SimpleDraweeView ?

**Comment by tyronen** [comment]
The latest version of Fresco is 0.5.2.

Your StatusPicView should override the methods as described here: http://frescolib.org/docs/writing-custom-views.html#handling-attach-detach-events. I think the Chinese translation may not be quite up to date.

**Comment by JoneWeng** [comment]
ok，I did that too. setting drawable callback , and invalidate some rect .feel refreshed frequently, will cause the carton?

In the new version to solve the problem about big image ? Other types(not jpeg)

**Comment by tyronen** [comment]
I don't know what you mean - 'carton' is probably not the right word.

Non-JPEG images must be less than 2048 x 2048 or they will not be displayed. Resize options do not apply for non-jpegs, even in the latest version.

I am going to close this issue for now; open a new one if you need it. Please only ask one question per issue. If you have more than one question, open more than one issue.
