### ISSUE TITLE
Image invaidate

### ISSUE THREAD

**Issue by avibhamare** [facebook/fresco#275]
I am migrating from picasso to fresco. I want to know if there is any way to invalidate a image already catched as I am adding feature to replace existing image there is way to do so in picasso like

Picasso.with(context).invalidate(URI);

**Comment by IanChilds** [comment]
You can do `ImagePipeline.evictFromMemoryCache(uri)`. However, that will not remove the image from the disk cache that is #124 (there is a workaround you can use for that specified there too).

**Comment by avibhamare** [comment]
Yes, I did same it is removing image but replacing view with same old image and not getting a new one. I am using OKHTTP here

**Comment by IanChilds** [comment]
Is the new image coming from the memory cache or the disk cache? (you might have to add a `RequestListener` to determine this).

**Comment by avibhamare** [comment]
Thanks, This worked, hope it will not create any further issue.

Fresco.getImagePipelineFactory().getMainDiskStorageCache().remove(new SimpleCacheKey(uri.toString()));
		Fresco.getImagePipelineFactory().getSmallImageDiskStorageCache().remove(new SimpleCacheKey(uri.toString()));
