### ISSUE TITLE
error initializing Fresco

### ISSUE THREAD

**Issue by uwescheunemann** [facebook/fresco#2759]
Hello,

with the current version 3.1.3 I have problem to initialize Fresco.
As described in Fresco getting started (https://frescolib.org/docs/index.html) I initialize Fresco with the following code:
```
Fresco.initialize(
    applicationContext,
    ImagePipelineConfig.newBuilder(applicationContext)
        .setMemoryChunkType(MemoryChunkType.BUFFER_MEMORY)
        .setImageTranscoderType(ImageTranscoderType.JAVA_TRANSCODER)
        .experiment().setNativeCodeDisabled(true)
        .build())
```
I get the following compiler error message: 
'initialize(android.content.Context, com.facebook.imagepipeline.core.ImagePipelineConfig)' in 'com.facebook.drawee.backends.pipeline.Fresco' cannot be applied to '(android.content.Context, com.facebook.imagepipeline.core.ImagePipelineExperiments)'

As you can see I create a ImagePipelineConfig object and not a ImagePipelineExperiments object.
So this error message is missleading!

And with then older version 3.0.0 everything is fine.

Is this a mistake on my side or can you check i and correct the problem in your library?

Thanks for help
U. Scheunenann

**Comment by steelrooter** [comment]
Experiments now have a dedicated builder, and it is accessed via the `.experiment()` method in the `ImagePipelineConfig.Builder`.

You can try modifying the code like this and it should compile again:
```
Fresco.initialize(
        applicationContext,
        ImagePipelineConfig.newBuilder(applicationContext)
            .setMemoryChunkType(MemoryChunkType.BUFFER_MEMORY)
            .setImageTranscoderType(ImageTranscoderType.JAVA_TRANSCODER)
            .also { it.experiment().setNativeCodeDisabled(true) }
            .build())
```
