### ISSUE TITLE
Not able to build Fresco in Eclipse

### ISSUE THREAD

**Issue by swatigoel** [facebook/fresco#276]
I have downloaded fresco zip https://github.com/facebook/fresco/releases/download/v0.4.0/frescolib-v0.4.0.zip
After that I imported 4 projects in eclipse drawee, fbcore, fresco, and imagepipeline.

Used fresco as library in My project but it didn't work. So I added these 4 projects in My Project build path. Then I could access Fresco.initialize(context) in activity.

But when I run my app and open that activity which initializing Fresco gives below error:
E/AndroidRuntime(4563): java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco

I have used "com.facebook.drawee.view.SimpleDraweeView" in layout but this line fresco:placeholderImage="@drawable/contact" always giving compiling error for "placeholderImage" attribute. I have used xmlns:fresco="http://schemas.android.com/apk/res-auto" also. Still no luck.

Can anybody help me please!!!

**Comment by tyronen** [comment]
Please try again with the latest release: https://github.com/facebook/fresco/releases/download/v0.5.0/frescolib-v0.5.0.zip

**Comment by tyronen** [comment]
File a new issue if this persists.
