### ISSUE TITLE
hierarchy.setRoundingParams and hierarchy.setActualImageColorFilter conflict

### ISSUE THREAD

**Issue by xingxp** [facebook/fresco#277]
i want to set colorFilter to some round corner image,
but after i use hierarchy.setRoundingParams, the corner shows.

**Comment by IanChilds** [comment]
are you sure it's caused by having the color filter? Can you show me the code that rounds the corners, I suspect it is actually that which is wrong? Also can you give the Uri of the image that you are trying to round the corners of?

**Comment by xingxp** [comment]
my code is below
whithout  setting colorfilter,it works fine.
after the colorfilter applied, the corner show with color.

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fresco.initialize(this);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        SimpleDraweeView mDrawee = (SimpleDraweeView) findViewById(R.id.my_image_view);
        RoundingParams roundingParams = RoundingParams.fromCornersRadius(80f);
        GenericDraweeHierarchyBuilder genericDraweeHierarchyBuilder = new GenericDraweeHierarchyBuilder(getResources());
        GenericDraweeHierarchy hierarchy = genericDraweeHierarchyBuilder.setRoundingParams(roundingParams).build();

        int color=Color.parseColor("#3c7d09");
        hierarchy.setActualImageColorFilter(makeScrimColorFilter(color));
        Uri uri = Uri.parse("res://" + getPackageName() + "/" + R.mipmap.graph_n);

        mDrawee.setHierarchy(hierarchy);
        mDrawee.setImageURI(uri);
    }

    private ColorFilter makeScrimColorFilter(int sessionColor) {
        float a = 0.3f;
        float sat = 0.3f; // saturation (0=gray, 1=color)
        return new ColorMatrixColorFilter(new float[]{
                ((1 - 0.213f) * sat + 0.213f) * a, ((0 - 0.715f) * sat + 0.715f) * a, ((0 - 0.072f) * sat + 0.072f) * a, 0, Color.red(sessionColor) * (1 - a),
                ((0 - 0.213f) * sat + 0.213f) * a, ((1 - 0.715f) * sat + 0.715f) * a, ((0 - 0.072f) * sat + 0.072f) * a, 0, Color.green(sessionColor) * (1 - a),
                ((0 - 0.213f) * sat + 0.213f) * a, ((0 - 0.715f) * sat + 0.715f) * a, ((1 - 0.072f) * sat + 0.072f) * a, 0, Color.blue(sessionColor) * (1 - a),
                0, 0, 0, 0, 255
        });
    }

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by erikandre** [comment]
Since the color filter is applied after the image is rounded, it means that the cropping is not applied to it. A potential workaround would be to use a post processor to apply a color filter + round the image.
