### ISSUE TITLE
Cached images extension

### ISSUE THREAD

**Issue by mohammedhammouri** [facebook/fresco#278]
Why cached images extension is ( .cnt ) not jpg or png or anything else ? 
Can I change the extension to something else ? so I can access them directly without the need for imagePipline.

**Comment by IanChilds** [comment]
Why do you not want to use the pipeline? I can't think of a disadvantage of accessing it using the pipeline

**Comment by michalgr** [comment]
You do not need to use extension to detect type of the image, see https://github.com/facebook/fresco/blob/847851a8de6d223c0a6634447bddee1252e01c64/imagepipeline/src/main/java/com/facebook/imageformat/ImageFormatChecker.java. Checking file name to determine image type is not reliable, images often do not have extension and sometimes they have extensions indicating wrong format.

File names and even the fact that there are multiple files used by the cache are its internal details and you should not depend on that.

What is the problem you are trying to solve that ImagePipeline does not allow you to solve through its API ?

**Comment by mohammedhammouri** [comment]
Because I have images that I want to share , and every time the user press the share button I have to get the image from the pipline and save to his sdcard or internal card I don't want this delay , also it's not a big problem. THANKS
