### ISSUE TITLE
[Question] Supporting inBitmap in Android 4.4

### ISSUE THREAD

**Issue by huyduongtu** [facebook/fresco#281]
"Android 3.0 (API level 11) introduces the BitmapFactory.Options.inBitmap field. If this option is set, decode methods that take the Options object will attempt to reuse an existing bitmap when loading content. This means that the bitmap's memory is reused, resulting in improved performance, and removing both memory allocation and de-allocation. However, there are certain restrictions with how inBitmap can be used. In particular, before Android 4.4 (API level 19), only equal sized bitmaps are supported."

I wonder Why don't fresco use inBitmap in Android 4.4, but Android 5.0?
Is managing bitmap on ashmem with the options inPurgeable more efficient than  reusing bitmap with option inBitmap on Davilk heap?
Thanks.

**Comment by tyronen** [comment]
Yes, the ashmem is more efficient. This places bitmaps off the Java heap entirely. We would have preferred to use this solution even on Android 5.0, but unfortunately Google dropped support for it in that release.

**Comment by huyduongtu** [comment]
Thanks
