### ISSUE TITLE
[Question] Supporting inPurgeable from Android 3.0 -> 4.4

### ISSUE THREAD

**Issue by huyduongtu** [facebook/fresco#282]
"While inPurgeable can help avoid big Dalvik heap allocations (from API level 11 onward), it sacrifices performance predictability since any image that the view system tries to draw may incur a decode delay which can lead to dropped frames. Therefore, most apps should avoid using inPurgeable to allow for a fast and fluid UI. To minimize Dalvik heap allocations use the inBitmap flag instead."

Google says that It decreases performance. Why do you still use inPurgeable?
Do you trade off Dalvik heap allocations for performance predictability?

**Comment by IanChilds** [comment]
Please see this blog post: https://code.facebook.com/posts/366199913563917. We are able to do both as explained in the section "Having our cake and eating it too"

**Comment by huyduongtu** [comment]
Thanks
