### ISSUE TITLE
Memory?

### ISSUE THREAD

**Issue by LinkOut** [facebook/fresco#284]
On Android 4.x and lower, Fresco puts images in a special region of Android memory.

Only for android 4.x and lower, infact it seems not to do that on newer version... Why this?

**Comment by michalgr** [comment]
BitmapFactory.decode does not allow us to create purgeable bitmaps on 5.0 anymore: http://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inPurgeable

**Comment by LinkOut** [comment]
Ok i got that, but actually is for api 21.
Why 4.x and lower and not 5.x and lower?

I mean from 4.0 to 5.0 library uses heap memory?

**Comment by tyronen** [comment]
5.0 IS api 21.
