### ISSUE TITLE
When Change Border Color, the image not display

### ISSUE THREAD

**Issue by zhangtengchao** [facebook/fresco#285]
```java
GenericDraweeHierarchy hierarchy = viewHolder.mIvAvatar.getHierarchy();
RoundingParams roundingParams = hierarchy.getRoundingParams();
roundingParams.setBorder(getResources().getColor(R.color.orange), width);
hierarchy.setRoundingParams(roundingParams);
viewHolder.mIvAvatar.setHierarchy(hierarchy);`
```

![qq 20150519142602](https://cloud.githubusercontent.com/assets/9455805/7696796/67481bf4-fe33-11e4-950e-9c81183a0bd1.png)

How should i do?

**Comment by plamenko** [comment]
Can you paste the XML as well?

**Comment by zhangtengchao** [comment]
` <com.facebook.drawee.view.SimpleDraweeView
            fresco:roundingBorderColor="@color/white"
            fresco:roundingBorderWidth="@dimen/main_item_comment_avatar_rounding_border_width"
            fresco:roundAsCircle="true"
            fresco:fadeDuration="300"
            fresco:failureImage="@mipmap/default_avatar_stroke_white"
            android:id="@+id/iv_comment_avatar"
            android:layout_width="@dimen/main_item_gallery_avatar_width"
            android:layout_height="@dimen/main_item_gallery_avatar_width" />`

**Comment by plamenko** [comment]
I don't understand the attached image. Where is the background image coming from? or is this the actual image? What are those red circles?

**Comment by tyronen** [comment]
Reaping.
