### ISSUE TITLE
Broken link and wrong word in "Building from Source"

### ISSUE THREAD

**Issue by larsien** [facebook/fresco#287]
Hi. I'm a member of Fresco Korean translation. 
Translation is almost done. But I found wrong word and broken link here. 

1. below "include" link has broken
2. inde might be index or anything else? 

Please check it and Thanks in advance.

Fresco does not support source builds with Eclipse, Ant, or Maven. We do not plan to ever add such support. Eclipse users can already include inde

https://github.com/facebook/fresco/blob/gh-pages/docs/05-building-from-source.md

**Comment by tyronen** [comment]
Fixed docs.
