### ISSUE TITLE
Building with Fresco in Eclipse

### ISSUE THREAD

**Issue by swatigoel** [facebook/fresco#289]
I have raised one issue earlier "https://github.com/facebook/fresco/issues/276" and received positive response.
Now I am able to build my App with Fresco successfully in Eclipse with lib version (https://github.com/facebook/fresco/releases/download/v0.5.0/frescolib-v0.5.0.zip)

But I have a query while building app.
I have imported all four projects (drawee, fbcore, fresco, and imagepipeline) and used fresco as library in my App. But at compile time it gives error for fresco attributes in XML layout. It asks to fix project build path and adds all four jar in build path (drawee-v0.5.0, fbcore-v0.5.0, fresco-v0.5.0, & imagepipeline-v0.5.0).

While adding jar in build path means we should not require project as library. But It doesn't build.

It requires all fours jars in build path as well as fresco project should be added as library and other 3 projects should be available in Eclipse.

It's so confusing for me. Because I want to share my code base with other persons, I thought that I could share only jar but only jar doesn't work.

Can you please let me know If I am missing something to build my App with Fresco?

**Comment by tyronen** [comment]
Can you paste here the actual error message you are receiving? 

Did it work when you added all four projects as dependencies?

**Comment by swatigoel** [comment]
Yes it works only when four projects are added in Eclipse, and fresco is added as library as well as four jars added in build path.

**Comment by swatigoel** [comment]
I just removed all four jars from build path and tried to build code.
It gives below error:
Fresco cannot be resolved at line 
Fresco.initialize(context);
And basically for all classes which I have used in Java files/
SimpleDraweeView, RoundingParams etc.

**Comment by swatigoel** [comment]
If I add all four jars and remove "fresco" library and build the code.
It gives below error for all layouts:
res/layout/test_layout.xml:52: error: No resource identifier found for attribute 'placeholderImage' in package 'com.example.test'
/res/layout/test_layout.xml:52: error: No resource identifier found for attribute 'roundAsCircle' in package 'com.example.text'
etc..

**Comment by swatigoel** [comment]
Is there any update on this plz?

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tyronen** [comment]
Because the Drawee library provides XML attributes, you have to include it as an Android project. It will not work if you add it as a jar.

**Comment by vimaljaingoyal** [comment]
It works with xml & jar also. :) Tyronen
