### ISSUE TITLE
Bitmap too large to loaded to a texture

### ISSUE THREAD

**Issue by hike2008** [facebook/fresco#290]
when the bitmap yi large like 2238 * 3328  , setImageUri() error with Bitmap too large to loaded to a texture

**Comment by michalgr** [comment]
Can you try resize the image ? http://frescolib.org/docs/resizing-rotating.html#resizing

**Comment by ICECHN** [comment]
In Fresco sample code,  i add a large image url to mCurrentAdapter, the result :Bitmap too large to be uploaded into a texture (7648x375, max=4096x4096)
![qq 20150521172633](https://cloud.githubusercontent.com/assets/11832023/7745571/cc6d2dc4-ffde-11e4-9192-0a449f40eb61.jpg)
