### ISSUE TITLE
Dalvik heap memory alway increase

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#292]
I config my bitmap cache like follow,but I find the dalvik memory increase more and more, when I scroll the listview and jump between activities

public class MemoryCacheSupplier implements Supplier<MemoryCacheParams> {

    private static final int NORMAL_SIZE = 8 * ByteConstants.MB; //byte
    private static final int LARGE_SIZE = 16 * ByteConstants.MB; //byte
    private static final int SUPER_SIZE = 32 * ByteConstants.MB; //byte
    private static final int EXTRA_SUPER_SIZE = 64 * ByteConstants.MB; //byte

    @Override
    public MemoryCacheParams get() {
        ActivityManager am = (ActivityManager) AppUtil.getAppContext().getSystemService(Context.ACTIVITY_SERVICE);
        int totalMemorySize = am.getMemoryClass() * ByteConstants.MB;

        int memorySize = 0;

        if(totalMemorySize <= NORMAL_SIZE){
            memorySize = totalMemorySize >> 5;
        }else if(NORMAL_SIZE < totalMemorySize && totalMemorySize <= LARGE_SIZE){
            memorySize = totalMemorySize >> 5;
        }else if(totalMemorySize < SUPER_SIZE && totalMemorySize <= EXTRA_SUPER_SIZE){
            memorySize = Math.round(totalMemorySize * 0.15f);
        }else if(totalMemorySize > EXTRA_SUPER_SIZE){
            memorySize = totalMemorySize >> 5;
        }

        if(memorySize <= 0){
            memorySize = ByteConstants.MB;
        }

        MemoryCacheParams params = new MemoryCacheParams(
                memorySize,Integer.MAX_VALUE,memorySize,Integer.MAX_VALUE,Integer.MAX_VALUE);

        return params;
    }
}

**Comment by michalgr** [comment]
Interesting. Cache is one of the places that can keep big bitmaps around. Another place is a view. Do you use Drawee to display images ? Is it SimpleDraweeView or something else ?

**Comment by KrystalJake1989** [comment]
Yes,I just use SimpleDraweeView,like follow:

<com.facebook.drawee.view.SimpleDraweeView
                xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:fresco="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                fresco:failureImage="@drawable/wdb_default_place_holder"
                fresco:failureImageScaleType="centerCrop"
                fresco:actualImageScaleType="centerCrop"
                fresco:placeholderImageScaleType="centerCrop"
                fresco:placeholderImage="@drawable/wdb_default_place_holder"/>

ImageRequest imageRequest =
                ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
                        .setResizeOptions(
                                new ResizeOptions(width, height))
                        .setAutoRotateEnabled(false)
                        .build();
        DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequest)
                .setOldController(view.getController())
                .build();
        view.setController(draweeController);

**Comment by KrystalJake1989** [comment]
I find if I use a normal png image as placeholder,then the dalvik heap will be increase while I jump between activities.But If I don't set placeholder or use drawable xml,then the dalvik heap as expected increase and go down.Dose fresco support to use png image as placeholder?

**Comment by plamenko** [comment]
Placeholders are loaded by using the Android's built-in facility `resources.getDrawable`. Fresco doesn't do anything special there.
