### ISSUE TITLE
java.lang.NullPointerException: SimpleDraweeView was not initialized!

### ISSUE THREAD

**Issue by bottiger** [facebook/fresco#293]
I am getting a few crash reports with this exception using Fresco version 0.4:

    Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!

Fresco is initialized very early in my applications onCreate() and I only have this problem with a few selected uses whom I cannot get in touch with.

I'm sorry I can not give you any more information than this. Please close the issue if you can't do anything about this, I just wanted to let you know the problem is out there. I will update this issue if I learn more about it.

**Comment by tyronen** [comment]
Fresco.initialize needs to be called before setContentView in your app.

**Comment by SuhairZain** [comment]
Hi, I have the same issue. I call Fresco.initialize(context) in my MainActivity. And this error was reported in an Activity which was called later(where I did not call initialize). Do I have to call initialize() and shutdown() in every Activity or do I have to do it only once for the whole application (before setContentView() ofcourse)?

**Comment by tyronen** [comment]
You only need to call initialize once per application. You shouldn't be calling shutdown at all, ordinarily.

**Comment by SuhairZain** [comment]
I was getting some leaks, probably not from fresco library itself. So I thought of using shutdown(). Are you sure there is no need to call shutdown()?

**Comment by feichngr** [comment]
You should probably sub-class `Application` if you haven't already, and initialize Fresco in `onCreate()` of that class.

**Comment by SuhairZain** [comment]
Yes. I did that now but still there is no way to verify if it solves the issue. AFAIK, the crash only appears on some user's devices. Can anyone explain to me what shutdown() does?

**Comment by hubcin** [comment]
@tyronen what should I do when my app crash and get SimpleDraweeView not initialized error ?  Because when my app crash for some reason, the android system recovers the last activity only to find that simpleDraweeView not initialized.

**Comment by Cococ** [comment]
I got the same issue.I have call Fresco.initialize(context) in  my Appliaction onCreate.
I have not idea on it.

 ` Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!
                                                                       at     com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:226)
                                                                       at com.facebook.drawee.view.SimpleDraweeView.init(SimpleDraweeView.java:79)
                                                                       at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:61)
`

**Comment by iballan** [comment]
I got the same error message, 
I Fresco.initialize(context) in my Application onCreate
So the problem does not look like initializing Fresco problem

**Comment by tzveeJ** [comment]
I was having this issue. I was initializing Fresco after my application called super.onCreate(). Moving it before super.onCreate() seems to have solved the problem for me.

**Comment by tzveeJ** [comment]
First of all, thanks for making a great library. It is a pleasure to use. I happen to be having this crash and I can reproduce it on my device, HTC One M8. It takes a little playing around to do so. I initialize Fresco as the first thing in my application's onCreate.

    public void onCreate() {
        ImagePipelineConfig config = ImagePipelineConfig.newBuilder(getApplicationContext())
                .setDownsampleEnabled(true)
                .build();
        Fresco.initialize(getApplicationContext(), config);

The above suggestions have not fixed it. I'd be happy to provide additional information.

**Comment by tzveeJ** [comment]
I was having this issue. As it turns out, I had used some of Facebook's sample code in my project, and in their sample code they had Fresco initialize and shutdown for each activity. Removing that stopped my crashes!

**Comment by iballan** [comment]
@tzveeJ  so do the activities open and close smoothly?

**Comment by tzveeJ** [comment]
@iballan Yes, they do. To clarify, the Facebook sample code contained Fresco.initialize(context) which I have now removed because I had already initialized it in my application class per their instructions.

**Comment by xavieryang2011** [comment]
try {
            ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
                    .setDownsampleEnabled(true)
                    .build();
            Fresco.initialize(this, config);
        } catch (Exception e) {
            e.printStackTrace();
        }
the answer like above solved the problem.

**Comment by shantanukhond** [comment]
Just add Fresco.initialize(this); in your class!

**Comment by kojofosu** [comment]
just call `Fresco.initialize(this)` before `setContentView()` or yout before your `binding` if you're using viewBinding
