### ISSUE TITLE
Viewpager rendering issue

### ISSUE THREAD

**Issue by Ncit** [facebook/fresco#296]
When you have viewpager with 2 fragments, where you using recyclerview + fresco, you will get black items, rather then images.

**Comment by Ncit** [comment]
video https://www.dropbox.com/s/cytpy1162ar5kr0/occamLRX22Cnikitafeshchun05202015172248.mp4?dl=0

**Comment by michalgr** [comment]
Quick player refuses to play the video, should I use something else to view it ?

**Comment by Ncit** [comment]
I will create a new one video

**Comment by Ncit** [comment]
https://www.dropbox.com/s/5p6hq1wbsr1berz/occamLRX22Cnikitafeshchun05292015173555.mp4?dl=0 here you go. On the video you can see 2 recyclerview,images is Simpledrawerview

**Comment by tyronen** [comment]
Normally your placeholder should be specified? What is your placeholder?

**Comment by tyronen** [comment]
Closing as no response made.
