### ISSUE TITLE
DraweeHierarchy cause memory leak!

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#297]
I find that if l set placeholder and failureImage  through xml layout(fresco:placeholderImage="@drawable/placeholder", fresco:failureImage="@drawable/failure"),then I analyze memory status by mat,I observe the memory contains a lots of BitmapDrawableState instance and a bit of bitmaps.They are never be released.My placeholder and failure image are png formate picture.Does fresco support to use png as placeholder?

**Comment by michalgr** [comment]
Do you mean BitmapDrawable$BitmapState ? You should have separate instances of them per every view, but all of them should point to the same placeholder or failure bitmaps. Is that not the case ?

**Comment by KrystalJake1989** [comment]
I specify  placeholder in xml layout and I read the source code, it will call Resource class getDrawable method,when creating draweeview,so I think there are a lot of placeholder drawable,but they should point same bitmap

**Comment by plamenko** [comment]
We should investigate that.
The reference chain should be something like this: View -> Hierarchy -> Drawable -> Bitmap. If the bitmap drawables are piling up, there may be a memory leak somewhere.

**Comment by takecare** [comment]
I have to say I'm facing the same issue when using placeholder images. The memory gets consumed really fast. If I remove them (the placeholders) everything goes back to normal.

**Comment by turgutsaricam** [comment]
I have the same problem. Orientation change causes a huge memory leak when I use placeholder drawables.

**Comment by CrystalJake** [comment]
I have solved this problem.First,you'd better make you placeholder drawable as .9 png.Second,you'd keep every adapter or interface a same placeholder drawable.

**Comment by takecare** [comment]
You mean sharing the same (placeholder) drawable throughout the different drawee views? Isn't that a bad practice? I mean, it's even listed in the [gotchas section](http://frescolib.org/docs/gotchas.html#_).

**Comment by CrystalJake** [comment]
Even though,it's not a good idea that sharing same drawable between DraweeHierarchy,but I think if one of your app interface has same image size,it would be not a big problem.If one of your app interface has different image size,you share same placeholder drawable will cause a problem which all placeholder has same size that different from you actual image size.

**Comment by CrystalJake** [comment]
But As google said, the drawable come from same resource will share a bitmap,so I am a little confused of why placeholder occupied so many memory.As this page explain:http://android-developers.blogspot.com/2009/05/drawable-mutations.html

**Comment by plamenko** [comment]
Do **NOT** share the same drawable instance across multiple hierarchies/views. Here is an example of what can go wrong:
Let's say that there are two profile pictures on the screen that are not loaded just yet. Both are displaying a placeholder. Now one of the images load and we fade out its placeholder and fade in the actual image. If you are using the same placeholder instance, both of them will be faded out which is incorrect thing to do.

Perhaps the leak is higher in the stack, rather than in the hierarchy itself. If so, what you really need to do is to find out why do you have that many DraweeHierarchy instances alive. What keeps them alive?

**Comment by plamenko** [comment]
Also, unless there is a bug in Android framework, there should only be a single Bitmap object on the heap per resource image. There might be many drawable referencing that same bitmap, but it should really be only one Bitmap out there. Is that not so?
However, BitmapState in BitmapDrawable does not consist only of Bitmap. Other additional information take up some space and if your app is leaking DraweeViews or DraweeHierarchies and therefore Drawables, there will be a memory leak. How many instances of DraweeHierarchy do you see on the heap?
