### ISSUE TITLE
GIF Bitmap null on ImagePipeline

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#299]
Context context = PrivacyCall.getContext();
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(Uri.parse(imgUrl))
                .setAutoRotateEnabled(false)
                .setImageType(ImageRequest.ImageType.SMALL)
                .setLocalThumbnailPreviewsEnabled(true)
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                .setProgressiveRenderingEnabled(false)
                .setResizeOptions(new ResizeOptions((int)     

         context.getResources().getDimension(R.dimen.notice_dial_call_sticker_layer_call_sticker_size), (int) context.getResources().getDimension(R.dimen.notice_dial_call_sticker_layer_call_sticker_size)))
                .build();

        DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest, null);
        dataSource.subscribe(new BaseBitmapDataSubscriber() {

            @Override
            protected void onNewResultImpl(@Nullable Bitmap bitmap) {
                LogUtils.v("DEBUG95", "onNewResultImpl : " + bitmap);

            }

            @Override
            protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                LogUtils.v("DEBUG95", "onFailureImpl");
            }
        }, CallerThreadExecutor.getInstance());

**Comment by michalgr** [comment]
At the moment static gifs go through the same path as animated gifs. They are not represented as Bitmpas but instances of CloseableAnimatedImage. To get that image please use BaseDataSubscriber<CloseableReference<CloseableImage>> instead of BaseBitmapDataSubscriber
