### ISSUE TITLE
Custom Uri handlers / accepting arbitrary InputStreams

### ISSUE THREAD

**Issue by mcginty** [facebook/fresco#3]
The current Uri handlers are great for many cases, but in our app (and many others) we store our media encrypted on disk. Because of this, vanilla ContentProviders are unavailable as an option as we'd have to write a temporary unencrypted version to disk (ewww). The other option in Fresco would be to setup a localhost HTTP server that streams the unencrypted version (ewwwwww), which is a lot of unnecessary overhead.

If, however, Fresco allowed additional custom Uri handlers that provide InputStreams, we'd be golden. Alternatively, having a setImageInputStream alongside setImageUri would also suffice.

**Comment by plamenko** [comment]
We are thinking of supporting something very similar (basically either a custom uri handler or specifying Supplier<InputStream> while building image request).

**Comment by kenyee** [comment]
I was going to say exactly the same thing...our app has data stored on disk in encrypted form as well.  It's only unencrypted when in the in-memory cache.
Thanks for supporting this soon @plamenko :-)

**Comment by plamenko** [comment]
I'll have to refactor some of the fetching logic to make this plugin-like, but hopefully I'll get to this some time soon.

**Comment by ashughes** [comment]
I'm running into this same issue. I'd like to use this in conjunction with [Conceal](https://github.com/facebook/conceal) or another file encryption mechanism which provides an `InputStream`.

**Comment by agirardello** [comment]
@plamenko is there a timeline on this or any way I can "help" or use an InputStream with the current API? We would like to use in this app https://play.google.com/store/apps/details?id=fm.clean for its internal Gallery.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by caojianfeng** [comment]
I`m running into this issue too.
I think we can use content provider.
See http://frescolib.org/docs/supported-uris.html#_
Fresco support "content:" like url.
so we can make a content provider and do decrypt in it at first.
and then set uri "content:xxx?id=xxx&key=xxx"  to drawee.

**Comment by anotherdev** [comment]
@caojianfeng do you have an example code for that content provider?

**Comment by sohayb** [comment]
@plamenko any update regarding a custom Uri handler?

**Comment by kirwan** [comment]
I don't think we're likely to get to this any time soon. If someone would like to offer a pull request, I'd be willing to offer support.

We're currently cleaning up old issues which aren't progressing but I'll leave this a little longer in case anyone is interested in pursuing this.

**Comment by erikandre** [comment]
Closing this as part of our cleanup of old issues.

If anyone requires this feature, please consider implementing it and submitting a pull request.

**Comment by AntDev95** [comment]
> Я не думаю, что мы до этого дойдем в ближайшее время. Если кто-то захочет предложить пулл-реквест, я буду готов предложить поддержку.

As I understand it, nothing was implemented in the end?
