### ISSUE TITLE
window os build failed

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#30]
![12312](https://cloud.githubusercontent.com/assets/6761814/6883670/e8e32646-d5fb-11e4-9adc-be3dbb7d727b.png)

![123213](https://cloud.githubusercontent.com/assets/6761814/6883637/fbd79f9a-d5f9-11e4-8f50-e402dce68d92.png)

**Comment by tyronen** [comment]
You also need to add the NDK to your system PATH variable. See http://www.computerhope.com/issues/ch000549.htm
