### ISSUE TITLE
Bitmap too large to be uploaded into a texture 

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#301]
In Fresco sample code, i add a large image url to mCurrentAdapter, the result :Bitmap too large to be uploaded into a texture (7648x375, max=4096x4096)
![cc6d2dc4-ffde-11e4-9192-0a449f40eb61](https://cloud.githubusercontent.com/assets/11832023/7772040/23ceabc0-00ce-11e5-98aa-697ed2213332.jpg)

@michalgr

**Comment by michalgr** [comment]
We don't resize images if any of the dimensions is already smaller than what we asked for. We plan to have more resizing options, but for now the workaround would be to specify smaller dimensions: https://github.com/facebook/fresco/blob/master/samples/comparison/src/main/java/com/facebook/samples/comparison/adapters/FrescoAdapter.java#L63

**Comment by tyronen** [comment]
Fixed in 0.5.2.
