### ISSUE TITLE
The failure image can't be rounded.

### ISSUE THREAD

**Issue by johnzheng00** [facebook/fresco#305]
set the drawee view is round conner is 5dp . the image will be rounded,  placeholder is the same . But the failure image can t changed.

**Comment by IanChilds** [comment]
This is a known limitation, which we may fix in the future. If you wish to do it yourself, let me know and I can provide some pointers (it is a pretty easy change).

**Comment by johnzheng00** [comment]
Thanks ! But can you please see another issue ?  #304

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by balazsbalazs** [comment]
@johnzheng00 I believe this is implemented now with the new 0.9.0 release. Can you check please?

**Comment by johnzheng00** [comment]
Thanks a lot
