### ISSUE TITLE
URLs with asterisks don't load

### ISSUE THREAD

**Issue by liujianying** [facebook/fresco#306]
This is my project address:https://github.com/liujianying/FrescoDemo 
Use Fresco "version 0.5.0
compile 'com.facebook.fresco:fresco:0.5.0'
compile 'com.facebook.fresco:imagepipeline-okhttp:0.5.0'
This is the sample project in the URL:
http://img.v89.com/group1/M08/04/22/rBAA11OtUeqAILyjAAC2I8VNHUU462_640*640.jpg
http://img.v89.com/group1/M01/05/CF/rBAA11SJGj6ANUmYAAHYXsbUhAM483_640*640.jpg
http://img.v89.com/group1/M07/05/CF/rBAA11SJGjuAYGYwAAHthrrvYrQ279_640*640.jpg
http://img.v89.com/group1/M05/05/CE/rBAA11SIRc2AR95TAAFos2CSxNk102_640*640.jpg
http://img.v89.com/group1/M05/05/CE/rBAA11SIRcaAC81hAAHeRIw0YkE550_640*640.jpg
http://img.v89.com/group1/M05/05/CF/rBAA11SJCT2AaVvHAAFPnJV76ic597_640*640.jpg
http://img.v89.com/group1/M01/05/CF/rBAA11SJCTiAPJeLAAFPo48Ykuk249_640*640.jpg
http://img.v89.com/group1/M05/06/C9/rBAA11UhWACAcl-pAAG5ICOGh7I506_640*640.jpg
http://img.v89.com/group1/M08/05/CF/rBAA11SJCTaAXAPXAAHyIyeKNgo933_640*640.jpg

Engineering sample code here to view：https://github.com/liujianying/FrescoDemo

**Comment by liujianying** [comment]
![0a04b8e4-ffaa-11e4-8404-c757473b3a34](https://cloud.githubusercontent.com/assets/6265414/7790909/ee1ad26e-02c7-11e5-88bc-887c792d2f4c.png)
![5df839d4-005a-11e5-9484-a7e82789bfee](https://cloud.githubusercontent.com/assets/6265414/7790908/ee0e2cbc-02c7-11e5-8f25-bf58c39819a1.png)

**Comment by tyronen** [comment]
One of my colleagues took a look at your sample code.

You load the URI in MainActivity line 101 by parsing a string directly:

    Uri.parse(arrayList.get(arg0))

Because it contains special characters, it should be escaped properly, like:

```java
String escapeUrl(String url) throws UnsupportingEncodingException {
  return URLEncoder.encode(uri, "UTF-8").replace("*", "%2A");
}
... 
Uri.parse(escapeUrl(arrayList.get(arg0)))
```
