### ISSUE TITLE
Where can I find the changelog per version?

### ISSUE THREAD

**Issue by mheras** [facebook/fresco#309]
I need the changelog in order to be sure I want to upgrade the version of the library. Could you please tell us where to find it?

**Comment by IanChilds** [comment]
See here: https://github.com/facebook/fresco/releases 

If you look at the previous releases you can see the number of commits that have been made since that release, and if you click on the link it will show you which commits those are.

**Comment by SimonSchubert** [comment]
For the latest 2 version 1.14.0 and 2.0.0 the changelog doesn't exist anymore https://github.com/facebook/fresco/releases Did you move them somewhere else?

**Comment by oprisnik** [comment]
We didn't have time to compile the changelog yet. We'll update these soon.
