### ISSUE TITLE
How do you import&run the sample?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [facebook/fresco#31]
I keep getting:

"Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
A problem occurred starting process 'command 'ndk-build''
"

**Comment by tyronen** [comment]
You have to download the Android NDK and add its location to your system PATH variable. If using Android Studio, do the first build from the command line.

**Comment by AndroidDeveloperLB** [comment]
I do use Android-Studio.  Can you please put a tutorial for this operation?

**Comment by plamenko** [comment]
We are sending a fix for gradle file so that native stuff can be built with AS. Stay tuned :)

**Comment by AndroidDeveloperLB** [comment]
Thank you.
