### ISSUE TITLE
how to use custome way to down pics  ?

### ISSUE THREAD

**Issue by tqzym** [facebook/fresco#310]
currently, I use code below download pic .

import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.transfer.Download;
import com.amazonaws.services.s3.transfer.TransferManager;
   s3tx = new TransferManager(new BasicAWSCredentials(mS3Uid, mS3Pwd));
   myOutfile = outputFilepath != null
                    ? (new java.io.File(outputFilepath))
                            :File.createTempFile("prefix", "extension", mContext.getCacheDir());
    myDownload=s3tx.download(mS3Bucket, filePath, myOutfile);

how i use fresco OKHTTP to do it ?  or  compatibility old code ?
how to do it ?

**Comment by TarangS** [comment]
You could use the imagepipeline to download the pic and then write it to a file. http://frescolib.org/docs/using-image-pipeline.html#_
