### ISSUE TITLE
how can i  loading large bitmap which display in screen can be sliding 

### ISSUE THREAD

**Issue by mio4kon** [facebook/fresco#313]
i use:
```     java

draweeImage = (SimpleDraweeView) findViewById (R.id.drawee_image);
GenericDraweeHierarchy hierarchy = draweeImage.getHierarchy ();
hierarchy.setActualImageScaleType (ScalingUtils.ScaleType.CENTER);
draweeImage.setImageURI (pic_uri);

```

how can i slide my finger to show the bitmap everywhere.
In other words,how can i use subsampling-scale-image-view with fresco?

and 
[why i use dataSource to get bitmap is empty][1]
  [1]: http://stackoverflow.com/questions/30477827/why-use-fresco-datasource-to-get-bitmap-is-empty

**Comment by tyronen** [comment]
Hang on. Hopefully soon we will release a sample library that demonstrates how to create zoomable DraweeViews.

**Comment by tyronen** [comment]
Sorry for the delay. The long-promised sample library is out: https://github.com/facebook/fresco/tree/master/samples/zoomable/src/main/java/com/facebook/samples/zoomable
