### ISSUE TITLE
Can't find class "com.facebook.imagepipeline.backends.okhttp.OkHttpImagePipelineConfigFactory";

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#317]
Can't find class "com.facebook.imagepipeline.backends.okhttp.OkHttpImagePipelineConfigFactory";

**Comment by ICECHN** [comment]
dependencies {
  compile 'com.facebook.fresco:fresco:0.5.0+'
}

**Comment by tyronen** [comment]
You also need to depend on the okhttp libs. See http://frescolib.org/docs/using-other-network-layers.html#using-okhttp
