### ISSUE TITLE
Can't load multiple images in ListView when using ResizeOptions on 0.5.0

### ISSUE THREAD

**Issue by mrlongtt** [facebook/fresco#325]
Hi Fresco,
This library is so cool for loading image. But I have an issue when upgrading to 0.5.0 (It's not happen on 0.4.0).
I have a ListView which contains items that using Fresco to load Image (like the sample code),the issue is some images can't be loaded on the list. If I removed `ResizeOptions`, it works fine. It also work fine on 0.4.0. 
Here's my code:
```
ImageRequestBuilder builder = ImageRequestBuilder.newBuilderWithSource(uri)
        .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
        .setAutoRotateEnabled(true);
    if (width != 0 && height != 0) {
      builder.setResizeOptions(new ResizeOptions(width, height));
    }
    DraweeController controller = Fresco.newDraweeControllerBuilder().setImageRequest(builder.build())
        .setAutoPlayAnimations(true)
        .setOldController(draweeView.getController()).build();
    draweeView.setController(controller);
```
Please help me to troubleshoot the issue. Thanks

**Comment by TarangS** [comment]
@mrlongtt does this happen for local images or images downloaded over the network or both?

**Comment by mrlongtt** [comment]
It only happens for images downloaded over the network

**Comment by tyronen** [comment]
Are these animated images? We don't support resizing them. Only JPEGs can be resized.

**Comment by mrlongtt** [comment]
All of them are Jpegs files.

**Comment by tyronen** [comment]
How large are the images? There is an issue for images where either dimension is longer than the OpenGL texture limit (usually either 2048 or 4096).

**Comment by mrlongtt** [comment]
They are small images (100x100 and 200x200)

**Comment by rockerhieu** [comment]
I got this issue at well.

**Comment by tyronen** [comment]
The improvements made in 0.6.1 should help with this. Also try the new experimental [downsampling](http://frescolib.org/docs/resizing-rotating.html#downsampling) facility.
