### ISSUE TITLE
[Question] Reuse Bitmap with option inBitmap for different config

### ISSUE THREAD

**Issue by huyduongtu** [facebook/fresco#327]
I see fresco lib doesn't care about the config. If the decoding bitmap size is smaller than reused bitmap size, it will reuse the bitmap to decode.
Is it true for all the bitmap (png, jpg, gif)? 
Because I see that Glide lib considers both config and size.

**Comment by tyronen** [comment]
Fresco only supports ARGB_888 config right now. The format of the encoded image (png/jpg) does not matter when reusing the bitmap.
