### ISSUE TITLE
should support svg and vector  xml function.

### ISSUE THREAD

**Issue by johnzheng00** [facebook/fresco#329]
the fresco should support svg and vector xml function!?

**Comment by TarangS** [comment]
@johnzheng00 it would be useful if you could tell us the use case which fresco falls short on.

**Comment by tyronen** [comment]
Fundamentally Fresco is a raster graphics library, not a vector images library. It's not likely we'd ever support this.

**Comment by johnzheng00** [comment]
If use svg or vector, I just one vector xml or svg file for my project. But now we use png for my project. Support so many devices and screen size, mdpi to xxxdpi, over 4 size at least. So the png need 4 at least. My apk will be large.  Is it right ?
