### ISSUE TITLE
import com.facebook.drawee.backends.pipeline.Fresco; can't be recognized.

### ISSUE THREAD

**Issue by yorkwang** [facebook/fresco#331]
compile('com.facebook.fresco:drawee:0.5.0+') {
        exclude group: 'com.nineoldandroids', module: 'library'
    }
    compile ('com.facebook.fresco:imagepipeline-okhttp:0.5.0+'){
        exclude group: 'com.nineoldandroids', module: 'library'
    }
Everything is fine, but  backends can't be recognized. 
![2015-05-31 8 59 32](https://cloud.githubusercontent.com/assets/2316433/7902005/0f93bbe4-07d8-11e5-89d0-adfb6ab22d4c.png)

**Comment by yorkwang** [comment]
Please help, I did follow the guid, still meet the problem.

**Comment by yorkwang** [comment]
Figure it out. It should be:
compile('com.facebook.fresco:fresco:0.5.0+') {
        exclude group: 'com.nineoldandroids', module: 'library'
    }
Your chinese guide write it wrongly.

**Comment by yorkwang** [comment]
Yes, 
The english document said:

In order to use it, the dependencies section of your build.gradle file needs to be changed. Do not use the Gradle dependencies given on the download page. Use these instead:
dependencies {
  // your project's other dependencies
  compile "com.facebook.fresco:fresco:0.5.0+"
  compile "com.facebook.fresco:imagepipeline-okhttp:0.5.0+"
}

But in chinese document, it said:
dependencies {
  // your project's other dependencies
  compile 'com.facebook.fresco:drawee:0.5.0+'
  compile 'com.facebook.fresco:imagepipeline-okhttp:0.5.0+'
}

**Comment by liaohuqiu** [comment]
@yorkwang  Thank you for your feedback :+1:
