### ISSUE TITLE
about dev question 

### ISSUE THREAD

**Issue by JoneWeng** [facebook/fresco#333]
i have  customer view,  it must reuse in listview. So I need to create it(MultiDraweeHolder,ImageRequest etc) every time?

**Comment by JoneWeng** [comment]
In the fresco sample, it seems to be.

**Comment by plamenko** [comment]
No, you do not have to create drawee holder each time. You only need to set a new uri / controller whenever the image changes.
Please read [Writing custom views] (http://frescolib.org/docs/writing-custom-views.html#_)

**Comment by ShawnDuan** [comment]
@plamenko what if there are different amount of DraweeHolders in the MultiDraweeHolders of each custom view? Can I still reuse the contained DraweeHolder?
