### ISSUE TITLE
[Question] Sample on github doesn't use option inBitmap in Android 5.0

### ISSUE THREAD

**Issue by huyduongtu** [facebook/fresco#334]
I made some research in Fresco lib's open source.I see that Fresco lib doesn't use option inBitmap like you tell it.
In the class DefaultBitmapPoolParams, MAX_SIZE_SOFT_CAP = 0. So there's no bucket in BitmapPool. Geting bitmap from BitmapPool always return null, then has to allocate bitmap manually.
Are there any differences between official vesion and opensource?

**Comment by kirwan** [comment]
We're looking at this issue of bitmap pooling again now but have found some issues internally when enabling it.

In the meantime, this is a very old issue so I'm going to close it.
