### ISSUE TITLE
custome view -- multiple bitmap

### ISSUE THREAD

**Issue by JoneWeng** [facebook/fresco#336]
what  callback  method is bitmap be loaded ? What should I do in it (invalidate view)?  method onDraw like this：

onDraw (canvas){
   mHolders.draw(canvas);
}

i think the callback method is invalidateDrawable or ControllerListener, so code like this

invalidateDrawable(drawable who){
    // check drawable
    invalidate(who.getBounds());
}

new ControllerListener(){
     onFinalSet(){
           invalidate(xxx.getBounds());
       }
}

please help me.. Troubled me for a long time.  i hope fresco provider multiple bitmap views .

**Comment by plamenko** [comment]
Please read [Writing Custom Views] (http://frescolib.org/docs/writing-custom-views.html#_).

**Comment by JoneWeng** [comment]
I've read it.  what callback method is bitmap be loaded ? invalidateDrawable or ControllerListener

**Comment by tyronen** [comment]
ControllerListener will tell you when the image is loaded.

You don't need to invalidate the view for that reason, though. Fresco takes care of that for you.
