### ISSUE TITLE
Q:MemoryCacheParams

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#339]
I changed ConfigConstants.MAX_MEMORY_CACHE_SIZE = 20 * ByteConstants.MB, but the native heap size and java heap size increased to more than 20MB。

**Comment by plamenko** [comment]
It is possible that you are looking at the total memory usage of your app and Fresco is not the only part of the app that uses memory.
How did you get the amount of the native/java heap size?

**Comment by ICECHN** [comment]
I got it from the sample app, i think you are right.
