### ISSUE TITLE
The license of the document

### ISSUE THREAD

**Issue by liaohuqiu** [facebook/fresco#34]
Fresco is really really great. 
What it's the license of the document? Also BSD?
May I translate the document into Chinese and publish to github pages?

**Comment by plamenko** [comment]
I'll double check that, but can you clarify what "document" are you referring to? Do you mean the documentation on frescolib.org/docs/ ?

**Comment by liaohuqiu** [comment]
I mean the content in `gh-pages`: https://github.com/facebook/fresco/tree/gh-pages

**Comment by liaohuqiu** [comment]
Yes, also include the documentation on frescolib.org/docs/ .

**Comment by liaohuqiu** [comment]
Hi, @pallotron, If there is any progress about this issue, please let me know.

Thank you in advance.

**Comment by tyronen** [comment]
We have placed the documentation under the CC BY license, except for sample code which is under a separate sample license. See links on the footers in frescolib.org.

You may certainly translate the documents. We will be updating them frequently, though, so it may take a lot of effort to keep them up to date.

We're still looking into a proper i18n solution that might let you send us the translations as a pull request.

**Comment by liaohuqiu** [comment]
Thank you. 

The translate work has been done here: https://github.com/liaohuqiu/fresco-docs-cn.  And I will keep the documentation update up to date.

I posted a feed about Fresco with the Chinese documentation  in weibo.com (a chinese-twitter-liked website). That feed has been viewed over 230,000 times. The Chinese developers like this library very much.

Thank you for your great work and your great effort. You guys really bring this world something wonderful.

And here is a jekyll plugin for i18n.  https://github.com/liaohuqiu/jekyll-multiple-languages. I use this plugin for my own website and it works well. http://www.liaohuqiu.net/. 

Hope this would be helpful.

**Comment by plamenko** [comment]
Thanks @liaohuqiu , that's awesome!
