### ISSUE TITLE
custom header for every image request

### ISSUE THREAD

**Issue by yorkwang** [facebook/fresco#340]
Our app has a gridview which contains a lot of images from different sources. Some images have its custom "Referer", we have to request them with different custom headers. Is there any chance to change the headers dynamically by using fresco+OKhttpclient?

**Comment by oprisnik** [comment]
A a OkHttp interceptor is the preferred way to do this. There is also a discussion going on in #1459 with alternative solutions, so just monitor the discussion in the PR.
