### ISSUE TITLE
Show old image until new image downloads

### ISSUE THREAD

**Issue by murugaprabum** [facebook/fresco#343]
I have a list of user profile pictures shown in a list. The profile pictures are downloaded from a http endpoint. When a user updates the profile picture, it is broadcasted to all his friends. Is it possible to show the old profile picture of an user till the new profile picture is downloaded ?

**Comment by plamenko** [comment]
Yes, set the old image as a low-res and the new image as a high-res while building a drawee controller. 
See [Requesting Multiple Images] (http://frescolib.org/docs/requesting-multiple-images.html#_)
