### ISSUE TITLE
Recycled bitmaps aren't removed from Ashmem

### ISSUE THREAD

**Issue by huyduongtu** [facebook/fresco#346]
I'm implementing my own library but using your rule about caching bitmap in ashmem.
After decoding bitmap, I call pin bitmap to keep this memory from unpinning.
When the bitmap is no longer displayed and is removed from memory cache, I recycle this bitmap.
I used Memory Analyzer (MAT) and see just a few Bitmap object that are cached in memory cache (in dominator_tree).
But in the Histogram, I see a lot of pixel data for bitmap objects is stored in byte arrays.
It seems the objects themselves are removed by Garbage Collector, but the pixel data of them are not.

If I scroll  the listview normally, the ashmem works well (its size also increases and decreases by GC).
But if I scroll the listview fast, the pixel data for bitmap object aren't removed by GC.
Because I download and decode bitmap based on the request's order. Don't cancel the request if the imageview is recycled by the listview. So that the bitmaps are cached in the ashmem continuously, but the GC doesn't responds to remove bitmap.

Does Fresco library do something else to remove the pixel data in the ashem? Thanks.

EDIT:
I see that Fresco doesn't use options.inInputShareable in conjunction with options.inPurgeable.
If I set options.inInputShareable = false, my java heap size increases obviously.
Why is that? Could you tell what NativeMemoryChunk is for?

**Comment by tyronen** [comment]
Bitmap.recycle is all we do.

Purgeable bitmaps hold a memory reference to the original encoded memory area. We don't use inInputShareable so we can safely delete the image pipeline's copy of the encoded data.

NativeMemoryChunk stores the encoded data on the native heap.

**Comment by huyduongtu** [comment]
Do you mean that when decoding image, it'll make a deep copy of the bitmap on Native Heap by using NativeMemoryChunk? I see that you create NativeMemoryChunk whenever getting data from Network or DiskCache. But when decoding bitmap, you also create an byte array on Java Heap.
"final CloseableReference<byte[]> encodedBytesArrayRef = mSharedByteArray.get(length + 2);" in method "decodeJPEGFromPooledByteBuffer".
So the deep copy of a bitmap is stored on Native Heap or Memory Heap?
What do you use 'NativePooledByteBufferOutputStream" and "SharedByteArray" for?
When do you delete NativeMemoryChunk?
I really appreciate all your help.

**Comment by tyronen** [comment]
Stepping back - may I ask why you are implementing another library? What do you need that Fresco does not provide?

**Comment by huyduongtu** [comment]
This is a existing library I developed based on AQuery lib. If I use Fresco lib, I must modify a lot in my application. So that I decided to improve my existing library. After researching Fresco, I have some questions
- Is the native memory (NativeMemoryChunk) just used for storing encoded data (encoded memory cache) because native memory is fast and doesn't causes GC?
- If inInputShareable isn't used, a deep copy of the input (InputStream, byte array,...) is created when decoding. Where  is the deep copy? (native memory, ashmem or java heap). Is is controlled by system or yourself?
- Why did you choose decodeByteArray not method decodeFileDescriptor? Using decodeByteArray, you have to alloc byte array on java heap and copy data from native memory to it. It is not good.

**Comment by tyronen** [comment]
Native memory is indeed fast and does not GC.

The deep copy is made into ashmem, and is controlled by the system.

decodeFileDescriptor I believe reads only from disk. We may revisit this later.

**Comment by huyduongtu** [comment]
Thanks for your help.

**Comment by huyduongtu** [comment]
The error is my wrong logic - in some cases, bitmaps aren't recycled. I fixed my problem. My Ashmem and native memory work well, doesn't increase in size much.. But it comes to another problem when drawing round bitmap. I did 2 ways but both of them don't work. 
I customized the ImageView and drawed round bitmap in onDraw() method.

Option 1:
```
private void init() {
        mRoundPaint = new Paint();
        mRoundPaint.setColor(Color.RED);
        mRoundPaint.setStyle(Paint.Style.FILL);
        mRoundPaint.setAntiAlias(true);

        mBmPaint = new Paint();
        mBmPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_IN));
    }

protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);

        mWidth = Math.min(w, h);
        rectDes = new Rect(0, 0, mWidth, mWidth);
    }

protected void onDraw(Canvas canvas) {
        if(getDrawable() == null)
            return;

        Drawable drawable = getDrawable();
        canvas.drawCircle(mWidth / 2, mWidth / 2, mWidth / 2, mRoundPaint);
        Bitmap bitmap = ((BitmapDrawable) drawable).getBitmap();
        canvas.drawBitmap(bitmap, null, rectDes, mBmPaint);
  }
```
It doesn't draw round bitmap instead of the original bitmap. If I `setLayerType(View.LAYER_TYPE_SOFTWARE, null)`, It works. But It doesn't works prior to Android 3.0

Options 2:
```
protected void onDraw(Canvas canvas) {
         Bitmap bitmap = ((BitmapDrawable) drawable).getBitmap();
         BitmapShader shader;
         shader = new BitmapShader(bitmap, Shader.TileMode.CLAMP, Shader.TileMode.CLAMP);

         Paint paint = new Paint();
         paint.setAntiAlias(true);
         paint.setShader(shader);
         paint.setStyle(Paint.Style.FILL);
         canvas.drawCircle(mWidth / 2, mWidth/ 2, mWidth /2, paint);
  }
```
It drawed round bitmap. But the ashmem size increases much. Seems BitmapShader keep the bitmap aren't removed from Ashmem. 
Currently, I'm using `decodeByteArray` method. If I use `decodeFileDescriptor` method, I get the error same like the issue [FileNotFoundException - too many open files #358](https://github.com/facebook/fresco/issues/358).

Fresco uses BitmapShader to draw round bitmap. But It works well.
Do you know what is my error?
Thanks in advance.

**Comment by tyronen** [comment]
I'm afraid this isn't really an issue with Fresco itself, and is beyond the scope of what we can support.
