### ISSUE TITLE
Why Native Memory grows up all the time?

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#350]
I print the native memory size through Debug class's getNativeHeapSize，but I find the native memory size become larger when I switch between several activities，then I think it would decrease a little after a while when I open more activities,but unfortunately it always increase and never decrease.Does fresco trim  native memory? I think it exceeds the size of native memory params I config.

**Comment by tyronen** [comment]
Native memory is used by Fresco to store encoded data. This is not trimmed by Fresco, but normally it doesn't need to; native memory use is bounded by the encoded memory cache and the number of active decodes in the pipeline. What is your application doing?

**Comment by KrystalJake1989** [comment]
I just use native memory for fresco,none for others.I mean that I observe native memory  increase more and more when I open many activities,if it reaches the total memory,will it make app crash? I dump native memory through  Debug class's getNativeHeapSize

**Comment by IanChilds** [comment]
No, there should be an upper limit on the amount of memory used so that the app never crashes.
