### ISSUE TITLE
Is there a better way to load a fixed URL image without clearing cache everytime

### ISSUE THREAD

**Issue by Harlber** [facebook/fresco#352]
As the question title,my project has a loading page that load images from the same URL.Is there a better way to load a fixed URL image without clearing cache . Is there any APIs like other library that attach the HTTP head and automatically determine whether you need to load. If so, please tell me as soon as possible. Thanks a lot.

**Comment by tyronen** [comment]
OkHttp supports this behavior, and we support using it with Fresco. See http://frescolib.org/docs/using-other-network-layers.html#using-okhttp
