### ISSUE TITLE
As long as I push my app to /system/app, Fresco does't work.

### ISSUE THREAD

**Issue by hycmanson** [facebook/fresco#353]
As long as I push my app to /system/app, Fresco does't work.
Maybe it cause by this issue:
https://groups.google.com/forum/#!topic/android-porting/xq9l193V7_M

**Comment by mariotaku** [comment]
try copy native .so library into /system/lib ?

**Comment by tyronen** [comment]
Can you clarify what you are trying to do? Are you trying to install your app on an external SD card?

**Comment by tyronen** [comment]
Probably not supported.
