### ISSUE TITLE
[Question] Ashmem and Encoded Memory Cache

### ISSUE THREAD

**Issue by nguyentando** [facebook/fresco#354]
I'm implementing my own library for loading and caching images using the Fresco's rules. I also tried both decoding methods (decodeByteArray and decodeFileDescriptor) and ignore the options inInputShareable like Fresco did. The bitmap is actually already recycled but isn't removed from Ashmem. The Ashmem size is increasing gradually until I call explicitly GC (System.gc()). 
I checked that there is no memory leak in bitmap management. 
Can you tell me why?

In Fresco, there is an encoded memory cache that stores encoded data in native memory. I wonder whether there are any purpose relating to removing bitmap pixel data in Ashmem? I see that you create a byte array on Java Heap and copy encoded data from native memory to that byte array. So the deep copy of encoded data is stored on native heap or java heap?

**Comment by tyronen** [comment]
The deep copy is carried out by Android itself - I believe the source code is in [BitmapFactory.cpp](https://github.com/android/platform_frameworks_base/blob/kitkat-release/core/jni/android/graphics/BitmapFactory.cpp#L212).
