### ISSUE TITLE
[Question] Ashmem size doesn't update instantly!

### ISSUE THREAD

**Issue by nguyentando** [facebook/fresco#355]
I see that when I scroll list images in Fresco sample, the ashmem size increase to a limit which is about 100MB (I use Samsung Galaxy Note 3 - 3 GB of RAM), and then it fluctuate around that limit when I keep scrolling.

https://github.com/facebook/fresco/issues/346
In the above link , you said that you just call Bitmap.recycle() for releasing the bitmap pixel data. But calling recycle() do not free the pixel data synchronously. 
So why your sample can keep the ashmem size at that limit? Did you do anything else to update the ashmem size instantly so it can not increase incessantly until the System call GC.

I followed your rules to try to write my own images loading library:
- I copy the encoded data from file to byte array, and then use that byte array to decode images by calling BitmapFactory.decodeByteArray, and ignore the options.inInputShareable, so that the bitmap will make a deep copy of that data to a byte array of its own.
- I pinned the images right after decoding.
- I call bitmap.recycle() whenever I don't use that bitmap anymore.
Is that right? 

Please help me! Thank you!

**Comment by IanChilds** [comment]
No, we didn't do anything special. I would think that it just so happens that as you release and assign more memory, the memory used stays at about 100MB, since the pixel data gets freed pretty quickly even if it is not synchronous.
