### ISSUE TITLE
How to stop loading when i scrolling listview very fast!

### ISSUE THREAD

**Issue by longmh** [facebook/fresco#356]
just like the imageloader:
mListview.setOnScrollListener(new PauseOnScrollListener(
				ImageLoader.getInstance(), false, true));
if fresco can do this ,it will be wonderful！

**Comment by tyronen** [comment]
Why would it be wonderful? Your users would just see grey boxes as they scroll. 

Are you suffering performance issues?

**Comment by vsahu1986** [comment]
@tyronen 
1 it might be necessary multiple network and then upon view detached , the request are cancel . so again CPU computation and wastage of Bandwidth .

2 Question :- When Target view is detached from Any Scrolling Widget , the Request is canceled or Completed , Or Fresco check the percentage of Image is downloaded then take decision to cancel or continue

**Comment by vsahu1986** [comment]
Thanks @tyronen , 
For adding this as enhancement also please have a look at 

http://stackoverflow.com/questions/27146850/cancelling-the-image-request-android-on-the-basis-of-progress-image-loader-vol

**Comment by tyronen** [comment]
Duplicate of #512. Closing this one as the other has more discussion.

**Comment by TyrionCN** [comment]
Fresco.getImagePipeline().resume() and Fresco.getImagePipeline().pause()
