### ISSUE TITLE
SipleDraweeView setImageURI is not working for native resource

### ISSUE THREAD

**Issue by xu6148152** [facebook/fresco#357]
my code:

    final SimpleDraweeView imageView = (SimpleDraweeView) findViewById(R.id.backdrop);
		Resources resources = getResources();
		final int resId = Cheeses.getRandomCheeseDrawable();
		final Uri uri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" +
				resources.getResourcePackageName(resId) + '/' +
				resources.getResourceTypeName(resId) + '/' +
				resources.getResourceEntryName(resId));
		imageView.setImageURI(uri);

if I use ImageView, it can work, but when i used SimpleDraweeView, it does not work.

Why? Can someone help me?

**Comment by Numan1617** [comment]
I believe the scheme needs to be set using UriUtil (com.facebook.common.util.UriUtil). Try the following:

```java
Uri uri = new Uri.Builder()
        .scheme(UriUtil.LOCAL_RESOURCE_SCHEME)
        .path(String.valueOf(resId))
        .build();
imageView.setImageURI(uri);
```
