### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by appledong** [facebook/fresco#36]
大家好：
   我下载一份代码，在android studio中编译不通过，报的是下面错误，麻烦帮忙看一下，解决一下，谢谢！错误代码：
     Execution failed for task ‘：imagepipeline：ndk_build_gifimage',
     >A problem occurred starting process ' command' ndk-build''

**Comment by kongnanlive** [comment]
建议你发问题先看看是否已经有类似问题了！去 issue #5找答案。

**Comment by appledong** [comment]
@kongnanlive .我看了那个问题按照上面说的配置了path甚至修改了命令行，但是仍然不能编译通过，阁下已经编译通过了么？谢谢

**Comment by liaohuqiu** [comment]
没有安装ndk或者ndk路径不在`$PATH`变量之中。

**Comment by liaohuqiu** [comment]
I think this issue can be closed now.

**Comment by appledong** [comment]
你好，打扰一下：
       fb的框架fresco你能够编译通过么？我按照上面说的方法配置了ndk的path路径，甚至修改了组建文件，但是还是报哪个错误，麻烦帮忙看一下，谢谢！



yijianpiaoxue2011@163.com
 
发件人： 孔楠
发送时间： 2015-03-30 17:25
收件人： facebook/fresco
抄送： appledong
主题： Re: [fresco] 编译不通过 (#36)
建议你发问题先看看是否已经有类似问题了！去 issue #5找答案。

**Comment by kongnanlive** [comment]
@appledong 还没解决吗？

**Comment by appledong** [comment]
@kongnanlive 还没有，我配置了NDK_ROOT和path路径，还是运行不起来

**Comment by liaohuqiu** [comment]
echo $PATH ?

**Comment by liaohuqiu** [comment]
`./gradlew :imagepipeline:ndk_build_gifimage --stacktrace`

**Comment by kongnanlive** [comment]
@appledong @liaohuqiu 加了也没用，必须修改imagepipeline/build.gradle文件，把commandline 'ndk-build' 替换成commandLine '你的ndk路径/ndk-build'才行。

**Comment by appledong** [comment]
@kongnanlive @liaohuqiu commandLine 'E/android-ndk-r10d/ndk-build',
                'NDK_APPLICATION_MK=../Application.mk',
                'NDK_OUT=' + temporaryDir,
                "NDK_LIBS_OUT=$buildDir/$name",
                '-C', file("src/main/jni/$name").absolutePath,
                'clean' 我这样修改了但是还是报错

**Comment by kongnanlive** [comment]
你确定windows的路径是这样？试试E:\android-ndk-r10d\ndk-build.cmd 记得带上cmd

**Comment by appledong** [comment]
Error:(148) *** Android NDK: Aborting    .  Stop.
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
make.exe: Entering directory `F:/fresco-master/fresco-master/imagepipeline/src/main/jni/gifimage'
make.exe: Leaving directory `F:/fresco-master/fresco-master/imagepipeline/src/main/jni/gifimage'

**Comment by BaronZ** [comment]
+1
Error:(148) *** Android NDK: Aborting . Stop.
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.

make.exe: Entering directory F:/fresco-master/fresco-master/imagepipeline/src/main/jni/gifimage' make.exe: Leaving directoryF:/fresco-master/fresco-master/imagepipeline/src/main/jni/gifimage'

**Comment by mrljdx** [comment]
@appledong I had the same problem , my solution is edit the /imagepipeline/gradle.properties as below 
      
        ##解决问题：https://github.com/facebook/fresco/issues/36
        ndk.path=/Users/Mrljdx/Library/Android/sdk/ndk-bundle

Change the **ndk.path** to your's local path~，and then compile the project ,it will be compiled success ~
