### ISSUE TITLE
Question about using a touch image view

### ISSUE THREAD

**Issue by anshu56** [facebook/fresco#364]
Hello,

We working on incorporating Fresco into our code base, and are having a hard time incorporating it with our TouchImageView.  We use a custom touch image view to support zooming/panning an image, the code that we're using is similar to that found here : https://github.com/MikeOrtiz/TouchImageView/blob/master/src/com/ortiz/touch/TouchImageView.java.  

The problem is that these are all matrix based operations on the imageview and all of these operations involve using the drawable intrinsic width/height.  This doesn't work for us out of the box with Fresco, because GenericDraweeHierarchy forces it's root drawable to return intrinsic width/height of -1.  To get around this problem we've made our own implementation of DraweeHierarchy that is the exact same as GenericDraweeHierarchy with the only difference being that it doesn't over ride intrinsic width/height in the RootFadeDrawable.  We then leave it to the logic in our view to make sure that the final image is set on our view before applying any matrix operations, so that the height/width doesn't change upon image load.  

Does this seem like a reasonable solution to you or are there problems that we may not be considering?  I'm assuming that the reason you chose to overwrite the intrinsic width/height properties is because these values will change until the final image is loaded.  Is that correct, or are there other reasons as well?

Thanks for your help!

**Comment by tyronen** [comment]
We hope to soon release a sample library showing how to use Fresco with touch gestures.

**Comment by gajicm93** [comment]
For now, you can use this code to load any image with Fresco into normal ImageView:

        DataSource <CloseableReference<CloseableImage>> dataSource = Fresco.getImagePipeline().fetchDecodedImage(ImageRequest.fromUri(Uri.parse(IMAGE_URL)),getApplicationContext());

        dataSource.subscribe(new BaseBitmapDataSubscriber() {
                                 @Override
                                 public void onNewResultImpl(@Nullable final Bitmap bitmap) {
                                     IMAGEVIEW.post(new Runnable() {
                                         public void run() {
                                             IMAGEVIEW.setImageBitmap(bitmap);
                                         }
                                     });
                                 }

                                 @Override
                                 public void onFailureImpl(DataSource dataSource) {
                                     // No cleanup required here.
                                 }
                             },
                CallerThreadExecutor.getInstance());

**Comment by tyronen** [comment]
See the sample at https://github.com/facebook/fresco/tree/master/samples/zoomable/src/main/java/com/facebook/samples/zoomable
