### ISSUE TITLE
Animated-GIF loading slower than 0.4.0

### ISSUE THREAD

**Issue by b22n** [facebook/fresco#365]
In 0.5.1
Animated GIF's animation begining is delayed noticeably than before(compare with 0.4.0)

**Comment by tyronen** [comment]
Can you give an example of such a gif?

**Comment by b22n** [comment]
I think it's not a specific image problem. 
All GIFs begins starting animation lately than before

**Comment by skptl** [comment]
I am still facing the same issue in 0.7.0.
Animated GIFs are delayed 4-5 seconds before they animate smoothly.

**Comment by oprisnik** [comment]
This should be fixed, see #1275
