### ISSUE TITLE
How I use  clear memory  ?    configBuilder.setMemoryTrimmableRegistry(new MemoryTrimmableRegistry()

### ISSUE THREAD

**Issue by dongliang0108** [facebook/fresco#369]
How I use  clear memory  ?

        configBuilder.setMemoryTrimmableRegistry(new MemoryTrimmableRegistry(){
            @Override
            public void registerMemoryTrimmable(MemoryTrimmable trimmable) {
            }

            @Override
            public void unregisterMemoryTrimmable(MemoryTrimmable trimmable) {
            }
        } );

**Comment by tyronen** [comment]
http://frescolib.org/docs/configure-image-pipeline.html#using-a-memorytrimmableregistry
