### ISSUE TITLE
Can fresco be used in Html.ImageGetter 

### ISSUE THREAD

**Issue by skipness** [facebook/fresco#370]
Hello, I am trying to make fresco work in html.imagegetter. Is it possible to make it works?

**Comment by tyronen** [comment]
It would be a bit of a challenge, since ImageGetter returns a Drawable, not a Bitmap.

You could conceivably build your app such that DraweeHolders or SimpleDraweeViews are created for each HTML img tag. Even then, it would be awkward to use a Drawable-returning method like this.
