### ISSUE TITLE
java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco

### ISSUE THREAD

**Issue by YaPengLi** [facebook/fresco#372]
I am using Fresco.initialize(this);. Log the error :java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco.I follow http://fresco-cn.org/support.html on my eclipse.

**Comment by IanChilds** [comment]
I'm afraid I can't read the Chinese docs, but did you add all the projects?

Or are you using Proguard perhaps?

**Comment by YaPengLi** [comment]
Thank you for answering my question！
I've added all the projects. and now I am not using Proguard perhaps.
See on the Internet，add libs to Java build path-Soure`Folder,But other exceptions.Repeat jar

At 2015-06-17 05:49:09, "IanChilds" <notifications@github.com> wrote:


I'm afraid I can't read the Chinese docs, but did you add all the projects?

Or are you using Proguard perhaps?

**Comment by tyronen** [comment]
The call to `Fresco.initialize` must take place **after** your application has called `setContentView`. Are you doing this? It looks as though the Chinese docs don't state this.

**Comment by agoodcoolman** [comment]
Before it's work well before，
now it's logout java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco
I call Fresco.initialize( ) in MyApplication class.it's right?

**Comment by IanChilds** [comment]
What changed? Could you have exceeded the 64k method limit recently?

**Comment by agoodcoolman** [comment]
Could you have exceeded the 64k method limit recently?

**Comment by agoodcoolman** [comment]
in my pc， it's work. when copy it another pc, i get the problem

**Comment by IanChilds** [comment]
Are you building from source? Or are you using Eclipse or Android Studio?

**Comment by agoodcoolman** [comment]
use eclipse,

**Comment by IanChilds** [comment]
This seems to be a problem with the environment on your other pc. Have you set up eclipse per the instructions here: http://frescolib.org/docs/index.html#_?

**Comment by agoodcoolman** [comment]
i have set up ecplise http://frescolib.org/docs/index.html#
but it not work

**Comment by agoodcoolman** [comment]
in console it show

Could not find drawee.apk
Could not find drawee.apk
Could not find drawee.apk
Could not find drawee.apk
Could not find drawee.apk

**Comment by agoodcoolman** [comment]
ok,i solve it
change project.properties target to android-21

**Comment by IanChilds** [comment]
Great!
