### ISSUE TITLE
Need User-Agent added to HTTP header

### ISSUE THREAD

**Issue by dev-chrisk** [facebook/fresco#373]
Hi,
Like subject, fresco can not recognize the url is valid without image extension. This is a example Url here (https://lh3.googleusercontent.com//JOu5Dhqyc-glytUjUOnqQb6UKfiHL1D_Ywqi_49Z-kbn3atTYRI6DZiWiPdixN31ndQ=h310)
Does Fresco not support this kind of url? or Anybody knows to solve this problem?

[ logcat ] 
Unable to decode stream: java.io.FileNotFoundException: https:/lh3.googleusercontent.com/JOu5Dhqyc-glytUjUOnqQb6UKfiHL1D_Ywqi_49Z-kbn3atTYRI6DZiWiPdixN31ndQ=h310: open failed: ENOENT (No such file or directory)
06-15 13:48:27.456  22524-22524/? I/System.out﹕ resolveUri failed on bad bitmap uri: https://lh3.googleusercontent.com/JOu5Dhqyc-glytUjUOnqQb6UKfiHL1D_Ywqi_49Z-kbn3atTYRI6DZiWiPdixN31ndQ=h310

**Comment by tyronen** [comment]
Can you access the same URI from a browser on the device?

Google URIs are blocked in some countries.

**Comment by dev-chrisk** [comment]
@tyronen Yes, I can access the above URI from chrome on Nexus5.

**Comment by kunny** [comment]
@dev-chrisk  I am using the CDN for image request, and it also does not have an extension in the uri itself, works well with Fresco.
It seems to be caused by google's server setting, i.e., blocking the request that does not have a valid User-Agent.

**Comment by tyronen** [comment]
Same issue as #321.

**Comment by shahrukhqasim** [comment]
I had an exact same problem just now. The problem was that the view was not SimpleDraweeView but rather an ImageView. If that doesn't resolve the problem, make sure you send valid HTTP headers from the web.

**Comment by freshFoot** [comment]
good
