### ISSUE TITLE
App Crash: Does it related to Fresco?

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#376]
1、
F/libc    ( 8000): invalid address or address of corrupt block 0x77a4a4a8 passed to dlfree
F/libc    ( 8000): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 9808 (pool-19-thread-)

2、
A/libc﹕ Fatal signal 6 (SIGABRT) at 0x000023ab (code=-6), thread 9216 (pool-24-thread-)
I/DEBUG﹕ *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-16 10:45:32.115    2135-2135/? I/DEBUG﹕ Build fingerprint: 'Meizu/meizu_mx3/mx3:4.4.4/KTU84P/m35x.Flyme_OS_4.2.8.2.20150422040832:user/release-keys'
06-16 10:45:32.115    2135-2135/? I/DEBUG﹕ Revision: '21520'
06-16 10:45:32.115    2135-2135/? I/DEBUG﹕ pid: 9131, tid: 9216, name: pool-24-thread-  >>> com.evideo.MobileKTV <<<
06-16 10:45:32.115    2135-2135/? I/DEBUG﹕ signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
06-16 10:45:32.455   9403-15984/? E/Hcdn_DeTask1601914235﹕ HCDN_LOG: 2015/06/16-10:45:32:461: OnRecvDownloadInfoRequest,2225     hcdn download info speed(0 KB/s) flie_size(2963089)
06-16 10:45:32.475    3604-3604/? D/StatusBar.NetworkController﹕ refreshing SignalClusterView.
06-16 10:45:32.475    3604-3604/? D/SignalClusterView﹕ mMobileVisible[0] = true mIsAirplaneMode = false
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ r0 00000000  r1 00002400  r2 00000006  r3 00000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ r4 00000006  r5 00000000  r6 00002400  r7 0000010c
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ r8 7caf5b10  r9 7c3bede0  sl 7c59b3e0  fp 7caf5b24
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ ip 7c3bedf0  sp 7caf5a60  lr 400c80a1  pc 400d71d0  cpsr 00070010
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d0  455a49535f444d5f  d1  58414d5f50564520
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d2  6e6f697472657364  d3  3a64656c69616669
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d4  412e848000000000  d5  3ff0000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d6  003d0900ffffffff  d7  3ff0000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d8  0000000000000000  d9  0000000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d10 0000000000000000  d11 0000000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d12 0000000000000000  d13 0000000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d14 0000000000000000  d15 0000000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d16 0000000000000000  d17 0000000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d18 0000000000000004  d19 4024000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d20 4018000000000000  d21 412e848000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d22 4156e36000000000  d23 4018000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d24 4000000000000000  d25 412e848c00000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d26 412e848000000000  d27 3ff0000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d28 412e848000000000  d29 0000000000000001
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ d30 4024000000000000  d31 4000000000000000
06-16 10:45:32.475    2135-2135/? I/DEBUG﹕ scr 68000012
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ backtrace:
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #00  pc 000221d0  /system/lib/libc.so (tgkill+12)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #01  pc 0001309d  /system/lib/libc.so (pthread_kill+48)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #02  pc 000132b1  /system/lib/libc.so (raise+10)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #03  pc 00011fe7  /system/lib/libc.so
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #04  pc 00021a84  /system/lib/libc.so (abort+4)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #05  pc 0005dd31  /system/lib/libcrypto.so (OpenSSLDie+24)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #06  pc 000798e5  /system/lib/libcrypto.so (EVP_DigestFinal_ex+32)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #07  pc 000798b3  /system/lib/libcrypto.so (EVP_DigestFinal+6)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #08  pc 00008f8b  /system/lib/libjavacrypto.so
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #09  pc 0001db8c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #10  pc 0004e65b  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #11  pc 00026fa0  /system/lib/libdvm.so
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #12  pc 0002e4a0  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #13  pc 0002bb04  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #14  pc 00060a7d  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #15  pc 00060aa1  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #16  pc 0005579b  /system/lib/libdvm.so
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #17  pc 0000d240  /system/lib/libc.so (__thread_entry+72)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ #18  pc 0000d3d8  /system/lib/libc.so (pthread_create+240)
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ stack:
06-16 10:45:32.490    2135-2135/? I/DEBUG﹕ 7caf5a20  00000000
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a24  415dfe09  /system/lib/libdvm.so (dvmAddTrackedAlloc+24)
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a28  42dc6b28  /dev/ashmem/dalvik-heap (deleted)
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a2c  00000000
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a30  42dc6b28  /dev/ashmem/dalvik-heap (deleted)
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a34  4163a1f0  /system/lib/libdvm.so
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a38  0000006e
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a3c  415b4308  /system/lib/libdvm.so (dvmMalloc(unsigned int, int)+96)
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a40  00000000
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a44  415dfe09  /system/lib/libdvm.so (dvmAddTrackedAlloc+24)
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a48  7a50fb10
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a4c  88366a1a
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a50  37643753
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a54  00000000
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a58  401001d8  /system/lib/libc.so
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a5c  71c44008
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ #00  7caf5a60  00000006
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a64  00000000
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a68  00002400
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a6c  7c3bedf0
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a70  7c3bedf0
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a74  400c80a1  /system/lib/libc.so (pthread_kill+52)
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ #01  7caf5a78  00000006
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a7c  00000000
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a80  7caf5ae8  [stack:9216]
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a84  400c82b5  /system/lib/libc.so (raise+14)
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ #02  7caf5a88  7caf5a94  [stack:9216]
06-16 10:45:32.495    2135-2135/? I/DEBUG﹕ 7caf5a8c  400c6feb  /system/lib/libc.so
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ memory near r1:
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000023e0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000023f0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002400 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002410 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002420 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002430 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002440 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002450 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002460 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002470 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002480 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002490 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000024a0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000024b0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000024c0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000024d0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ memory near r6:
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000023e0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 000023f0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002400 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002410 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002420 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.500    2135-2135/? I/DEBUG﹕ 00002430 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 00002440 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 00002450 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 00002460 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 00002470 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 00002480 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 00002490 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 000024a0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 000024b0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 000024c0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 000024d0 ffffffff ffffffff ffffffff ffffffff
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ memory near r8:
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5af0 daf00005 43131938 43131928 6d7fdfa0
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b00 7c59b3d0 415a7b90 daf00005 00000000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b10 7c3bede0 00000001 6e8a125d 41800c18
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b20 00000061 415d865f 7c3bede0 6e8a1259
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b30 7396af4d 7c59b3e0 00000000 7caf5bb8
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b40 fc800001 00000000 4478cbd0 40104384
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b50 7c59b73c 415dbe97 7c59b3d0 415dfe5b
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b60 4478ddd0 7caf5bc8 7ab33588 4478dca8
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b70 4478ddb0 4478cbd0 402ce3ec 402ce3fc
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b80 7a4fac78 00000002 00000000 00000020
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5b90 00000000 00000020 00000001 00000020
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5ba0 4163a1f0 7c3bedf0 00000061 43131928
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5bb0 4163a1f0 43131928 41589408 415fd73d
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5bc0 41635c78 41635c78 000819a0 00000020
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5bd0 43131928 4163a1f0 00000020 415b42ec
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7caf5be0 4163a1f0 42c148c8 41589408 41635c78
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ memory near r9:
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bedc0 6e889248 6d7fe0b8 7c3bee04 7c3bee04
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bedd0 6e8891c6 6d7fdfa0 00000000 00000000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bede0 7b5c36d0 00000000 daf00005 00000000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bedf0 7c3bee2c 6e5f16a8 6d816150 6e8891c6
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee00 00000000 43131928 7b5c36d0 00000000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee10 00000000 44c41dd0 7c3bee48 75afc106
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee20 6d8164d8 6e5f16a8 00000000 44c41dd0
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee30 44c41dd0 7c3bee6c 75afc0d8 6da33a10
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee40 75afc106 00000000 42dc6b28 44c41dd0
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee50 42dc6b28 42dc6b28 7c3bee8c 75ae38a2
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee60 6da339d8 75afc0d8 00000000 42c148c8
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee70 42dc6b28 42c148c8 7c3beed0 75ae6d9c
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee80 6da335b0 75ae38a2 00000000 428046b0
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3bee90 430a6fd0 43394540 42c14610 7c3beed0
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3beea0 42c148c8 43394540 75ae6d56 42c14610
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c3beeb0 428046b0 430a6fd0 43394540 7c3bef00
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ memory near sl:
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b3c0 482d687a 2d736e61 00004e43 0000045b
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b3d0 75c76e94 7c3bede0 6d816150 6e4fe000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b3e0 7b5c36d0 00000000 7caf5c40 00000000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b3f0 7caf5c94 0000001b 00000000 415a7d00
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b400 00000000 00000000 6c8bd870 7c3bb300
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b410 00000000 00000000 00000001 00004000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b420 00000000 7c59b858 415a7d00 415acbc0
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b430 00000000 415b0cbc 415b0d30 415b0be0
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b440 415b0c00 415b0c5c 00000000 00000000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b450 76a22008 00000028 00000000 00000000
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b460 00000000 00000006 00001ee2 4163a91c
06-16 10:45:32.505    2135-2135/? I/DEBUG﹕ 7c59b470 4165c138 6d53eaf8 00000002 7c59bd18
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c59b480 00000001 00000040 00000200 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c59b490 00000002 6eb06e54 6eb06e54 00000004
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c59b4a0 6eb06e60 6d865ac8 6f70cbb1 39a2620b
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c59b4b0 a4ca60dc 563a21ea 989a4224 6850e274
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ memory near fp:
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b04 415a7b90 daf00005 00000000 7c3bede0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b14 00000001 6e8a125d 41800c18 00000061
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b24 415d865f 7c3bede0 6e8a1259 7396af4d
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b34 7c59b3e0 00000000 7caf5bb8 fc800001
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b44 00000000 4478cbd0 40104384 7c59b73c
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b54 415dbe97 7c59b3d0 415dfe5b 4478ddd0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b64 7caf5bc8 7ab33588 4478dca8 4478ddb0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b74 4478cbd0 402ce3ec 402ce3fc 7a4fac78
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b84 00000002 00000000 00000020 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b94 00000020 00000001 00000020 4163a1f0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5ba4 7c3bedf0 00000061 43131928 4163a1f0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5bb4 43131928 41589408 415fd73d 41635c78
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5bc4 41635c78 000819a0 00000020 43131928
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5bd4 4163a1f0 00000020 415b42ec 4163a1f0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5be4 42c148c8 41589408 41635c78 41640800
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5bf4 00000010 00000020 415f365f 42c148c8
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ memory near ip:
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bedd0 6e8891c6 6d7fdfa0 00000000 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bede0 7b5c36d0 00000000 daf00005 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bedf0 7c3bee2c 6e5f16a8 6d816150 6e8891c6
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee00 00000000 43131928 7b5c36d0 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee10 00000000 44c41dd0 7c3bee48 75afc106
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee20 6d8164d8 6e5f16a8 00000000 44c41dd0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee30 44c41dd0 7c3bee6c 75afc0d8 6da33a10
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee40 75afc106 00000000 42dc6b28 44c41dd0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee50 42dc6b28 42dc6b28 7c3bee8c 75ae38a2
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee60 6da339d8 75afc0d8 00000000 42c148c8
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee70 42dc6b28 42c148c8 7c3beed0 75ae6d9c
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee80 6da335b0 75ae38a2 00000000 428046b0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3bee90 430a6fd0 43394540 42c14610 7c3beed0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3beea0 42c148c8 43394540 75ae6d56 42c14610
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3beeb0 428046b0 430a6fd0 43394540 7c3bef00
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7c3beec0 75ae7384 6d95c288 75ae6d9c 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ memory near sp:
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5a40 00000000 415dfe09 7a50fb10 88366a1a
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5a50 37643753 00000000 401001d8 71c44008
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5a60 00000006 00000000 00002400 7c3bedf0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5a70 7c3bedf0 400c80a1 00000006 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5a80 7caf5ae8 400c82b5 7caf5a94 400c6feb
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5a90 43131938 ffffffdf 7c3bedf0 40a74e31
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5aa0 43131928 7caf5ab4 7caf5b24 7b5c36d0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5ab0 43131938 400d6a88 40ad4f61 40a74d35
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5ac0 7caf5b24 40a908e9 7b5c36d0 7c00c580
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5ad0 00000004 40a908b7 7b5c36d0 7c00c580
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5ae0 7caf5b24 7396af8f ffffffff 7c00c580
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5af0 daf00005 43131938 43131928 6d7fdfa0
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b00 7c59b3d0 415a7b90 daf00005 00000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b10 7c3bede0 00000001 6e8a125d 41800c18
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b20 00000061 415d865f 7c3bede0 6e8a1259
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 7caf5b30 7396af4d 7c59b3e0 00000000 7caf5bb8
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ code around pc:
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 400d71b0 e8bd00f0 e3700a01 912fff1e e2600000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 400d71c0 ea006f78 e92d50f0 e3a07f43 ef000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 400d71d0 e8bd50f0 e3700a01 912fff1e e2600000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 400d71e0 ea006f70 e92d50f0 e3a070ee ef000000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 400d71f0 e8bd50f0 e3700a01 912fff1e e2600000
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 400d7200 ea006f68 e1520003 8a000102 f5d1f040
06-16 10:45:32.510    2135-2135/? I/DEBUG﹕ 400d7210 e92d4001 e3520010 3a00003f e3520d0d
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7220 aa00004c e2603000 e213300f 0a00000e
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7230 e0422003 e1b0cf83 44d1e001 44c0e001
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7240 24d1c001 24d1e001 24c0c001 24c0e001
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7250 e1b0ce83 aa000001 f4a1030d f480031d
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7260 3a000001 f421070d f400071d e2522080
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7270 3a000014 f4210acd f4000acd f4210acd
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7280 f4000acd f4210acd f4000acd f4210acd
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d7290 f4000acd f4210acd f4000acd f4210acd
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400d72a0 f4000acd f4210acd f4000acd f4210acd
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ code around lr:
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8080 447b4b13 42b3e010 4812d10e 44786a1e
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8090 ec90f7fb e9d8f00d 46224631 e892f00f
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c80a0 d00a3001 e00b2400 2b00681b 480ad1eb
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c80b0 44782403 ec7ef7fb f001e002 6804fa1b
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c80c0 fa18f001 46206005 bf00bd70 0003c322
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c80d0 0003c316 0003c30e 0003c2ea bf7ef7ff
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c80e0 4a3e4b3d 43f0e92d 4606b08b 447b460d
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c80f0 6823589c 930946a1 f9fcf001 8000f8d0
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8100 d0482d00 f0104628 280ff84f d8444604
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8110 ffe4f7ff d1064286 4629200f e8a2f00d
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8120 d03c2800 482ee02e f7fb4478 482debc2
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8130 e0154478 d11342b0 482b6a06 f7fb4478
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8140 4a2aec3a 46332120 447aa801 fd74f013
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8150 a8012101 f872f01b 46061c42 e011d104
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8160 28006800 e02cd1e6 46294630 f00d4622
06-16 10:45:32.515    2135-2135/? I/DEBUG﹕ 400c8170 1c43e8de d11e4607 f9bcf001 29046801

**Comment by michalgr** [comment]
I don't know whether it is related or not. Do you use any non-fresco native libraries ? What do you do to reproduce this ?

**Comment by ICECHN** [comment]
I don't know the specific time of the error occurred.The error didn't occur before. When i upgrade fresco to 0.5.1, the error occured many times. Most ot the other native libraries are created by my colleague, and the log shows the specific .so file when error occur. The log above doesn't show any .so file.

**Comment by ICECHN** [comment]
I found the wrong code in the code, it didn't relate to fresco.
