### ISSUE TITLE
[Question] Release the deep copy of bitmap's encoded data

### ISSUE THREAD

**Issue by nguyentando** [facebook/fresco#378]
You use decodeByteArray, and ignore inInputShareable, so when you decode bitmap, the system must make a deep copy of bitmap's encoded data.
Where is the deep copy? (java heap, native heap, ashmem).
Do you control it, and release it yourself, or you let the system do?

I use decodeFileDescriptor, and set inInputShareable = true, so the bitmap just keep the reference to its encoded data, which is probably the reference to the file I used to decode bitmap in this case. Everything works fine, but when I use BitmapShader to round images, it seems that after I call bitmap.recycle(), BitmapShader still keep reference to the file I used to decode bitmap. It causes Too Many Open Files Exception, after I scrolling list images for a while.

Did you do anything to solve this problem?

**Comment by tyronen** [comment]
We don't have this problem, as we're not using inInputShareable.

Android makes the deep copy, which I believe lives in ashmem and is controlled by the system. This will use more memory but as you have discovered, inInputShareable isn't really always safe to use.
