### ISSUE TITLE
performance hint

### ISSUE THREAD

**Issue by OleksandrKucherenko** [facebook/fresco#380]
Performance optimization hint:
- in addition to stored image type in "firstBits/firstBytes" also store image resolution width, height, bits

Benefits:
- allows to extract image meta information without image loading in memory
- allows to pre-allocate memory for image (or reuse one from available memory blocks)

Pointers:
- ~\fresco\imagepipeline\src\main\java\com\facebook\cache\disk\DefaultDiskStorage.java
- method typeOfBytes() give me an idea.

**Comment by IanChilds** [comment]
Unfortunately extracting image type is based on industry standards. We can't just assume that the image resolution width and height is stored at the very beginning of the image as it may be stored elsewhere in the header of the image. See https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imageutils/JfifUtil.java#L88-L118 for how we extract this information.

**Comment by OleksandrKucherenko** [comment]
```java
public static class DiskDumpInfoEntry {
    public final String path;
    public final String type;
    public final float size;
    public final String firstBits;
    protected DiskDumpInfoEntry(String path, String type, float size, String firstBits) {
      this.path = path;
      this.type = type;
      this.size = size;
      this.firstBits = firstBits;
    }
  }
```

Why not to store width and height ?
