### ISSUE TITLE
Add NDK Image Manipulation Methods

### ISSUE THREAD

**Issue by jcamp1** [facebook/fresco#381]
Greetings,

I would find it very useful if I could load a jpeg image in NDK memory, manipulate it in various ways, and then save it, all without pulling it into the java heap or displaying it.

Specifically I could really use the following functions:
* Rotate counter-clockwise
* Rotate clockwise
* Flip Horizontally
* Flip Vertically
* Resize

Thanks!

**Comment by IanChilds** [comment]
The purpose of Fresco is to load images, not to manipulate them natively, so this is not something that we will be adding, sorry.
