### ISSUE TITLE
Listening to download events documentation incorrect?

### ISSUE THREAD

**Issue by LarsLiden** [facebook/fresco#382]
The following docs page seems to be out of date:
http://frescolib.org/docs/listening-download-events.html

Fresco.newControllerBuilder() does not seem to exist in 0.5.2  

I can instead call Fresco.newDraweeControllerBuilder(), however that returns a PipelineDraweeControllerBuilder and the sample code showing 
 
mSimpleDraweeView.setController(controller);

will fail because setController only takes a DraweeController as an arguement.

**Comment by IanChilds** [comment]
Now fixed.

**Comment by LarsLiden** [comment]
Hmmm...   The page seems the same to me:
http://frescolib.org/docs/listening-download-events.html

**Comment by IanChilds** [comment]
No it is now `newDraweeControllerBuilder` instead of `newControllerBuilder`
