### ISSUE TITLE
How can i remove image file from disk cache when failed?

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#383]
For some reason, i need to remove image file from disk cache if onFailure is called in DraweeController.
How can i do that ?

In my app, i upload a image to server, then server return a redirect url, and server is handling the uploaded image.
I call fresco to show image with the redirect url, before server finishes the processing.
So the content downloaded is wrong. For a moment, i call fresco again, fresco doesn't download again.

**Comment by IanChilds** [comment]
There are a couple of similar issues - the solution in #124 and #275 should work for this case.
