### ISSUE TITLE
how to make fresco compatible with Samsung Galaxy S6 64-bit cpu 

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#386]
I notice that the latest fresco supports 64-bit so library,but my program has a strict limited size.So I hope that my program can also run on 64-bit cpu phone without importing 64-bit so library.Is it possible for me or how to modify fresco source code to support 64-bit cpu without building a 64-bit so library?

**Comment by michalgr** [comment]
Have you read this: frescolib.org/docs/multiple-apks.html ? You can build your apk per architecture and those build should be smaller. I would suggest this.

Another option is to play with productFlavors and abiFilter (example here: https://github.com/facebook/fresco/blob/v0.5.0/samples/comparison/build.gradle#L43). You should be able to specify a build flavor that includes native libs for multiple architectures you want. If you specify x86, armeabi and armeabi-v7a then you'll end up including the same libraries as previous versions of Fresco.
