### ISSUE TITLE
Crash Of the lib in the App (Log added)

### ISSUE THREAD

**Issue by EugineKKK** [facebook/fresco#389]
Build fingerprint: 'samsung/trlteusc/trlteusc:5.0.1/LRX22C/N910R4TYU1BOC4:user/release-keys'
Revision: '12'
ABI: 'arm'
pid: 27672, tid: 28452, name: Thread-63973 >>> com.kidoz <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:memory.cc(18)] Out of memory. size=4194304
'
r0 00000000 r1 00006f24 r2 00000006 r3 00000000
r4 8c3ffdb8 r5 00000006 r6 00000009 r7 0000010c
r8 b6fc2e04 r9 8c3fe5e8 sl 00000000 fp a178a200
ip 00006f24 sp 8c3fe100 lr b6f6cfd1 pc b6f90970 cpsr 680f0010

backtrace:
#00 pc 00037970 /system/lib/libc.so (tgkill+12)
#01 pc 00013fcd /system/lib/libc.so (pthread_kill+52)
#02 pc 00014beb /system/lib/libc.so (raise+10)
#03 pc 00011531 /system/lib/libc.so (__libc_android_abort+36)
#04 pc 0000fcbc /system/lib/libc.so (abort+4)
#05 pc 002b4775 /data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so

**Comment by michalgr** [comment]
This is not one of the Fresco's libs. The 'out of memory' suggests examining memory usage. What device do you use to reproduce this ? Do you use custom Fresco configuration ?

**Comment by EugineKKK** [comment]
Sorry. Yes you are right. It doesn't relates to Fresco.

**Comment by BaderThanBad** [comment]
Hey Eugine, I have the exact same issue (down to even the size=4194304 part). What was the issue and how did you solve it?

**Comment by EugineKKK** [comment]
Hey. 
I get different types of those errors only on Samsung devices. I think they have bug there. Currently i don't see any way to solve it , cause its related to some native components of the Samsung ROMs.
