### ISSUE TITLE
placeholders are too small

### ISSUE THREAD

**Issue by wzrd-clss** [facebook/fresco#390]
in the image below you can see some small dots at the top of the screen which I think are the placeholders. The images will load eventually from the network but I think the tiny size of the placeholders is preventing the app from retaining the scroll position on an orientation change. is this small size normal when using a controller?

a gist of the listview's adapter:
https://gist.github.com/d8b275b1fbf1972bfb35.git

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/iv_photo"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        fresco:placeholderImage="@drawable/empty_photo"
        fresco:actualImageScaleType="fitCenter"
        fresco:placeholderImageScaleType="fitCenter"
        />

![Screenshot](http://i.imgur.com/ENRKBoK.png)

**Comment by IanChilds** [comment]
Your problem is that you are using `wrap_content` - see http://frescolib.org/docs/using-drawees-xml.html#wrap-content

**Comment by wzrd-clss** [comment]
i actually got this working by overriding onsubmit() and then setting the aspect ratio to a fixed value

**Comment by IanChilds** [comment]
Yes, per the docs you can use `wrap_content` with an aspect ratio - you could do this in xml if you know the ratio in advance.
