### ISSUE TITLE
Why fresco can't load png on Android 5.0,if I modify the source code with Bitmap.Config.RGB565

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#392]
I notice that fresco use ARGB_8888 to load any type image,But I want to decrease the bitmap memory by modifying the source code with RGB565，but then I encounter a problem , when fresco decode png on android 5.0，it uses inbitmap argument while decoding bitmap,it throws a IllegalArgumentException (Problem decoding into existing bitmap)，I am a little confuse what cause this problem?

**Comment by tyronen** [comment]
How did you modify the source code? This argument will happen if Bitmaps.BITMAP_CONFIG was not changed.

**Comment by KrystalJake1989** [comment]
Yes,I change Bitmaps.BITMAP_CONFIG as RGB_565

**Comment by plamenko** [comment]
RGB_565 doesn't support transparency and this may be the reason why BitmapFactory fails to decode a PNG into it.
Anyways, we do not support RGB565 at the moment.
