### ISSUE TITLE
please make pressedStateOverlayImage support ripple effect

### ISSUE THREAD

**Issue by lizhiqiang-unnoo** [facebook/fresco#399]
In fresco 0.5.2, set fresco:pressedStateOverlayImage to a ripple drawable does not work. Currently I have to extend SimpleDraweeView like [ForegroundLinearLayout](https://gist.github.com/chrisbanes/9091754).

Wish fresco support it. Thanks!

**Comment by sagartrehan** [comment]
@lizhiqiang-unnoo I tried extending SimpleDraweeView and adding ripple selector to it by refering to ForegroundLinearLayout, but its no working for me. If possible can you please share the work around you did for adding ripple on SimpleDraweeView.

I am able to add ripple effect on top SimpleDraweeView by using its "overlayImage" attribute. But hotspot is showing from center which I want from the touch position.
I have created a issue #912 for it.

**Comment by boxcounter** [comment]
@sagartrehan 
Hope this helps :)

[ForegroundDraweeView.java](https://gist.github.com/boxcounter/89fe6c3de997ac6dd473)

**Comment by sagartrehan** [comment]
Thanks, I will test it and let you know.

**Comment by sagartrehan** [comment]
Thanks boxcounter. 
It is working fine. :)

**Comment by boxcounter** [comment]
Glad to hear that :P

**Comment by plamenko** [comment]
I think there is an easy fix to this. Let's track this in #912.
