### ISSUE TITLE
[Question] Using both of inBitmap and inPurgeable in Android 4.4

### ISSUE THREAD

**Issue by huyduongtu** [facebook/fresco#400]
I see that inBitmap supports well from Android 4.4 and still use option inPurgeable.
Why doesn't Fresco use both of two options in Android 4.4?

**Comment by tyronen** [comment]
inPurgeable, with Fresco's memory management, is better than inBitmap, since we can bypass the Java heap entirely. 

If inPurgeable had not been removed in Android 5.0, we would have kept using it.

**Comment by huyduongtu** [comment]
Using inPurgeable to store bitmap into Ashmem. Using inBitmap to reuse the previous bitmap when decoding bitmap. They are different. What I mean is Fresco can use BitmapPool in Android 4.4 when also using inPurgeable.

**Comment by tyronen** [comment]
No, it can't. The two options are not compatible. If you use inBitmap, inPurgeable will have no effect.
