### ISSUE TITLE
GIF how to play once?

### ISSUE THREAD

**Issue by ihgoo** [facebook/fresco#401]
I set the animation to run just ONCE,but it is not useful...what do I do next?

**Comment by tyronen** [comment]
Did this not work? http://frescolib.org/docs/animations.html#playing-animations-manually

What happened exactly? Is the image a GIF or a WebP?

**Comment by ihgoo** [comment]
It is GIF image.It's work,but i want to only make it play once.I use this code in my project:

![](http://7oxim7.com1.z0.glb.clouddn.com/ic_star_boom.gif)

```
Uri uri;
DraweeController controller = Fresco.newDraweeControllerBuilder()
    .setUri(uri)
    .setAutoPlayAnimations(true)
    .build();
mSimpleDraweeView.setController(controller);
```

I set the animation to run just once at PS,but in the project the GIF image play repeat..I only want it play once...What do I need to set up？

**Comment by tyronen** [comment]
Please follow the the instructions in the link I posted above.

**Comment by bkach** [comment]
I'm not sure the documentation answers the question. 

Is there a way to have the GIF animate only once, or for some custom  ```BaseControllerListener``` to understand where in the animation is in its own sequence?

Writing a custom ```BaseControllerListener``` allows one to start and stop an animation based on any outside event - but there doesn't seem to be a way for the controller to understand when the animated GIF has already run more than once.

This could be incredibly useful if trying to implement a callback at the end of a given animation.

**Comment by emanzanoaxa** [comment]
+1

**Comment by fahimsakri** [comment]
how to play the gif once? i could find the way to do it. please share the way to do it

**Comment by m0er** [comment]
for workaround..

```java
.setAutoPlayAnimations(false)
.setControllerListener(new BaseControllerListener<ImageInfo>() {
    @Override
    public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
        if (animatable != null) {
            try {
              Field field = AnimatedDrawable.class.getDeclaredField("mTotalLoops");
              field.setAccessible(true);
              field.set(animatable, 1);
            } catch (Exception e) {
                e.printStackTrace();
            }
            animatable.start();
        }
    }
})
```

**Comment by wswenyue** [comment]
.setAutoPlayAnimations(false)
.setControllerListener(new BaseControllerListener<ImageInfo>() {
    @Override
    public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
        if (animatable != null) {
            try {
              Field field = AnimatedDrawable.class.getDeclaredField("mTotalLoops");
              field.setAccessible(true);
              field.set(animatable, 1);
            } catch (Exception e) {
                e.printStackTrace();
            }
            animatable.start();
        }
    }
})

@m0er it didn't work

**Comment by m0er** [comment]
@wswenyue try AbstractAnimatedDrawable instead of AnimatedDrawable. There is change class hierarchy a bit.

**Comment by wswenyue** [comment]
It worked,Thank you very much @m0er

**Comment by Dev-Wiki** [comment]
AbstractAnimatedDrawable可以正常工作播放一次

**Comment by oprisnik** [comment]
@liyuehui is correct, you can supply value animators to modify the repeat count. Nice trick :)

**Comment by guoxiaoxing** [comment]
@oprisnik The method is not working in 1.3.0, it will cause ClassCastException Exception. 
`com.facebook.imagepipeline.animated.base.AnimatedDrawableSupport cannot be cast to com.facebook.imagepipeline.animated.base.AnimatedDrawable`

**Comment by oprisnik** [comment]
The problem here is not the version but that you are casting to `AnimatedDrawable`, which will be `AnimatedDrawableSupport` on older Android versions. It should work if you cast it to `AbstractAnimatedDrawable` instead.

**Comment by liyuehui** [comment]
@guoxiaoxing 
 
<pre>
if "animated-base-support" is added
	dependencies {
		compile 'com.facebook.fresco:animated-base-support:x.x.x' 
		//compile(name: 'animated-base-support', ext: 'aar')
  	}
        /////////////////////
	public void onFinalImageSet(
			String id,
			@Nullable  imageInfo,
			@Nullable Animatable anim) {
		if (anim != null) {
			// 其他控制逻辑
			<em>com.facebook.imagepipeline.animated.base.AnimatedDrawableSupport</em> an = (com.facebook.imagepipeline.animated.base.AnimatedDrawableSupport) anim;
			<em>com.nineoldandroids.animation.ValueAnimator</em> v = an
					.createValueAnimator();
			v.setRepeatCount(0);
			v.start();
		}
	}

</pre>
<pre>
else "animated-base-support" is not added

	public void onFinalImageSet(
			String id,
			@Nullable  imageInfo,
			@Nullable Animatable anim) {
		if (anim != null) {
			// 其他控制逻辑
			<em>com.facebook.imagepipeline.animated.base.AnimatedDrawable</em> an = (com.facebook.imagepipeline.animated.base.AnimatedDrawable) anim;
			<em>android.animation.ValueAnimator</em> v = an
					.createValueAnimator();
			v.setRepeatCount(0);
			v.start();
		}
	}



</pre>

**Comment by guoxiaoxing** [comment]
@liyuehui thank you, you save my time.

**Comment by oprisnik** [comment]
See https://github.com/facebook/fresco/issues/1863 for a solution.

**Comment by rickytee29** [comment]
@liyuehui thank you very much!
