### ISSUE TITLE
Big size for imagepipeline folder

### ISSUE THREAD

**Issue by alessandro-oliveira** [facebook/fresco#402]
The imagepipeline folder exceeds 4 MB of size, which is a huge drawback for using the library. It would be great if:
- [ ] The folder itself got lighter. I even tried using the library along with proguard / minifyEnabled (http://frescolib.org/docs/proguard.html#_), but the resulting APK was almost 4 MB bigger than the original size.
- [ ] We could opt-out for the features that uses this folder. For example, the DraweeView doesn't seem to need it.

**Comment by tyronen** [comment]
Tracking in #260.
