### ISSUE TITLE
CloseableAnimatedImage can return a bytes ?

### ISSUE THREAD

**Issue by 06peng** [facebook/fresco#405]
I want to use my custom gif view,so i need a bytes.

**Comment by tyronen** [comment]
The bytes of an individual frame, or of the entire animation? We only expose the individual frames.

What is your custom GIF view? Why do you need the bytes? Can you try using [manual playing](http://frescolib.org/docs/animations.html#playing-animations-manually)?

**Comment by 06peng** [comment]
Thanks for reply, I had  understand.but I have another problem, My network is very bad and my GIF image is more than 2M,when imageview is loading image,I want to get a progress value to show to user.But I  can not found anything about this on the docs.

**Comment by tyronen** [comment]
I would suggest not to make your users download a 2M image over a bad network! 

We do have support for showing a progress bar: http://frescolib.org/docs/progress-bars.html#_

**Comment by leeyikjiun** [comment]
Is there a way to know the size of an image just before downloading starts?

**Comment by tyronen** [comment]
No. Unless your server has another uri you can use to query it.
