### ISSUE TITLE
Increased storage data usage, but not cache

### ISSUE THREAD

**Issue by bhaskarmurthy** [facebook/fresco#407]
Hi, we switched from Picasso to Fresco recently and noticed that our app now shows an increasing amount of data usage in Storage, but not in Cache. 

We use SimpleDraweeView everywhere, mostly with some png placeholders. What is the default disk cache behaviour, and is there a way to purge disk cache periodically?

I haven't found a good way to purge the data storage programatically in Fresco, and was hoping there's something I missed that might help. Thanks.

**Comment by tyronen** [comment]
By default the disk cache goes in the application context's cache dir. You can change this by calling ImagePipelineConfig.setMainDiskCacheConfig when [configuring the image pipeline](http://frescolib.org/docs/configure-image-pipeline.html).

The recommended way to clear the disk cache is to implement a [DiskTrimmableRegistry](http://frescolib.org/docs/caching.html#trimming-the-caches) object. This must keep a list of DiskTrimmable (cache) objects, which it can trim whenever it wishes.
