### ISSUE TITLE
The fresco pipeline may be blocked

### ISSUE THREAD

**Issue by duguguiyu** [facebook/fresco#411]
If use fresco to load an png with some error, like: http://img.wdjimg.com/mms/icon/v1/9/f4/e2fed53a563d696d990484de34729f49_256_256.png , the whole fresco my be blocked, any image could be loaded any more.

**Comment by duguguiyu** [comment]
Log like this:

V/RippleFresco:BufferedDiskCache( 6689): Did not find image for http://img.wdjimg.com/mms/icon/v1/9/f4/e2fed53a563d696d990484de34729f49_256_256.png in staging area
V/RippleFresco:BufferedDiskCache( 6689): Disk cache read for http://img.wdjimg.com/mms/icon/v1/9/f4/e2fed53a563d696d990484de34729f49_256_256.png
V/RippleFresco:AbstractDraweeController( 6689): controller a735665 25: submitRequest: dataSource: 2d536948
V/RippleFresco:BufferedDiskCache( 6689): Found entry in disk cache for http://img.wdjimg.com/mms/icon/v1/9/f4/e2fed53a563d696d990484de34729f49_256_256.png
V/RippleFresco:NativeMemoryChunkPool( 6689): Used = (11, 954368); Free = (6, 97280)
V/RippleFresco:NativeMemoryChunkPool( 6689): get (reuse) (object, size) = (3db4425b, 32768)
V/RippleFresco:GenericByteArrayPool( 6689): Used = (1, 16384); Free = (1, 16384)
V/RippleFresco:GenericByteArrayPool( 6689): get (reuse) (object, size) = (2d3823e9, 16384)
V/RippleFresco:GenericByteArrayPool( 6689): release (reuse) (object, size) = (2d3823e9, 16384)
V/RippleFresco:GenericByteArrayPool( 6689): Used = (0, 0); Free = (2, 32768)
V/RippleFresco:BufferedDiskCache( 6689): Successful read from disk cache for http://img.wdjimg.com/mms/icon/v1/9/f4/e2fed53a563d696d990484de34729f49_256_256.png
V/RippleFresco:BitmapPool( 6689): Used = (11, 16141328); Free = (0, 0)
V/RippleFresco:BitmapPool( 6689): get (alloc) (object, size) = (25554bb6, 65536)
V/RippleFresco:AbstractDraweeController( 6689): controller 21389a90 null -> 26: initialize
V/RippleFresco:AbstractDraweeController( 6689): controller 21389a90 26: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@3f91df89
V/RippleFresco:AbstractDraweeController( 6689): controller 21389a90 26: onAttach: request needs submit
V/RippleFresco:PipelineDraweeController( 6689): controller 21389a90: getDataSource
V/RippleFresco:AbstractDraweeController( 6689): controller 21389a90 26: submitRequest: dataSource: 2ddb2faf
V/RippleFresco:AbstractDraweeController( 6689): controller 2f06ced8 null -> 27: initialize
V/RippleFresco:AbstractDraweeController( 6689): controller 2f06ced8 27: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@2bfc1231
V/RippleFresco:AbstractDraweeController( 6689): controller 2f06ced8 27: onAttach: request needs submit
V/RippleFresco:PipelineDraweeController( 6689): controller 2f06ced8: getDataSource
V/RippleFresco:AbstractDraweeController( 6689): controller 2f06ced8 27: submitRequest: dataSource: ac4dd16
V/RippleFresco:AbstractDraweeController( 6689): controller 609c7f null -> 28: initialize
V/RippleFresco:AbstractDraweeController( 6689): controller 609c7f 28: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@220b844c
V/RippleFresco:AbstractDraweeController( 6689): controller 609c7f 28: onAttach: request needs submit
V/RippleFresco:PipelineDraweeController( 6689): controller 609c7f: getDataSource
V/RippleFresco:AbstractDraweeController( 6689): controller 609c7f 28: submitRequest: dataSource: 84311aa
V/RippleFresco:AbstractDraweeController( 6689): controller 2d53cc81 null -> 29: initialize
V/RippleFresco:AbstractDraweeController( 6689): controller 2d53cc81 29: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@1c39126
V/RippleFresco:AbstractDraweeController( 6689): controller 2d53cc81 29: onAttach: request needs submit
V/RippleFresco:PipelineDraweeController( 6689): controller 2d53cc81: getDataSource
V/RippleFresco:AbstractDraweeController( 6689): controller 2d53cc81 29: submitRequest: dataSource: 3fe29167
V/RippleFresco:AbstractDraweeController( 6689): controller 5e4ad0a null -> 30: initialize
V/RippleFresco:AbstractDraweeController( 6689): controller 5e4ad0a 30: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@ed2e97b
V/RippleFresco:AbstractDraweeController( 6689): controller 5e4ad0a 30: onAttach: request needs submit
V/RippleFresco:PipelineDraweeController( 6689): controller 5e4ad0a: getDataSource
V/RippleFresco:AbstractDraweeController( 6689): controller 5e4ad0a 30: submitRequest: dataSource: 23131398
V/RippleFresco:AbstractDraweeController( 6689): controller 238e1374 null -> 31: initialize
V/RippleFresco:AbstractDraweeController( 6689): controller 238e1374 31: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@2d23d09d
V/RippleFresco:AbstractDraweeController( 6689): controller 238e1374 31: onAttach: request needs submit
V/RippleFresco:PipelineDraweeController( 6689): controller 238e1374: getDataSource
V/RippleFresco:AbstractDraweeController( 6689): controller 238e1374 31: submitRequest: dataSource: 206518e3

**Comment by duguguiyu** [comment]
@TarangS Do you know how to avoid this bug? I try it, but can not find the solution. thanks...

**Comment by michalgr** [comment]
Which Fresco version do you use ? Does this happen for any png image or just that one ?

**Comment by michalgr** [comment]
And what do you mean by "png with some error" ? Is that png corrupted or something ?

**Comment by duguguiyu** [comment]
@michalgr The newest version (0.5.3, and all versions are same). The png some bytes was not correct, I can not avoid all png images which app loaded are right format.

If any image was corrupted, all images followed can not be loaded. Following log, non callback was done.

**Comment by duguguiyu** [comment]
My phone is Nexus6, android 5.0+

**Comment by duguguiyu** [comment]
This issue just in android 5.0+, maybe the bitmap pool (for 5.0) has bug?

**Comment by bluef** [comment]
is there any plan to fix this bug? we have the same issue on Android 5.0+, even with 0.6.0

**Comment by duguguiyu** [comment]
@bluef This a bug of android 5.0, the BitmapFactory decode a image which some bytes are not correct, the method would be block, no response...

I don't know how to avoid that...

**Comment by michalgr** [comment]
Is this still happening ? There are a few things worth trying here: we can supply 0 bytes if BitmapFactory repeatedly asks for more data even though there is none left, we can throw something or decode pngs from byte array.

@duguguiyu : Did youinvestigate why BitmapFactory blocks ? Can you point us to the offending line if so ?

**Comment by duguguiyu** [comment]
@michalgr I just know the JNI API was block, I don't known what happen in native code above android 5.0.

**Comment by erikandre** [comment]
Closing as there are no updates or further reports for almost 2 years
