### ISSUE TITLE
Exif thumbnail displayed instead of original image

### ISSUE THREAD

**Issue by mingqlin** [facebook/fresco#415]
when try to display following image CACHED in local using Fresco with "file://....., only thumbnail from Exif is display, full image is not displayed. 

http://blog.kasal.info/images/20150627224228_img_8702_blog.jpg

Image metadata can be view using this link: (http://regex.info/exif.cgi?dummy=on&imgurl=http%3A%2F%2Fblog.kasal.info%2Fimages%2F20150627224228_img_8702_blog.jpg)

How to reproduce:
1. Download image from http://blog.kasal.info/images/20150627224228_img_8702_blog.jpg
2. Save image to SDcard as file name: file:///storage/emulated/0/cache/Image/0384d438b268f93f2ab1ded6b765ff33
3. Code below:

ImageRequest request1 = ImageRequestBuilder.newBuilderWithSource(Uri.parse("file:///storage/emulated/0/cache/Image/0384d438b268f93f2ab1ded6b765ff33"))
		.build();
ImageRequest[] requests = {request1};

DraweeController controller = Fresco.newDraweeControllerBuilder()
		.setFirstAvailableImageRequests(requests)
		.setAutoPlayAnimations(true)
		.build();
simpleDraweeView.setController(controller);

**Comment by mingqlin** [comment]
One note to add, where the jpg don't contain thumbnail in Exif, image will be display fine with Fresco. Problem is only with jpg with exif thumbnail. let me know in case you can't reproduce this issue.

**Comment by plamenko** [comment]
Thanks for the detailed report, we'll investigate ASAP.

**Comment by gchudnov** [comment]
Any updates on this issue?
Just bumped into the same problem...

**Comment by tyronen** [comment]
Fixed in v0.8.0
