### ISSUE TITLE
How to get cacheSize and clearCache by code?

### ISSUE THREAD

**Issue by nimengbo** [facebook/fresco#416]
How to get cacheSize and clearCache by code?

**Comment by plamenko** [comment]
If by `cacheSize` you mean the size in bytes currently occupied by our caches, I don't think we expose that. We do however have the limits in place and you can control the maximum allowed size for our image caches.
Also, I don't think we expose `clearCache` at the moment, but it is on our TODO list.

**Comment by massimocarli** [comment]
The methods to evict and clear memory and disk caches are now available for the ImagePipeline starting from here:

http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/core/ImagePipeline.html#clearCaches()
