### ISSUE TITLE
can't load image use imageRequest

### ISSUE THREAD

**Issue by agoodcoolman** [facebook/fresco#419]
![qq 20150702155846](https://cloud.githubusercontent.com/assets/11003275/8472412/b201d8b6-20d3-11e5-9d80-6160201e15f3.png)

the log

ImageRequest imageRequest = ImageRequestBuilder
					.newBuilderWithSource(uri)
					.setLocalThumbnailPreviewsEnabled(true).build();
			DraweeController draweeController = Fresco
					.newDraweeControllerBuilder().setImageRequest(imageRequest)
					.build();
			draweeView.setController(draweeController);
			draweeView.setId(picCounter);

after Call system taking pictures in fourth time, can't load the image.... use the method

**Comment by agoodcoolman** [comment]
resolve

ImageRequest imageRequest =
        ImageRequestBuilder.newBuilderWithSource(Uri.parse("content://...")
                .setResizeOptions(
                        new ResizeOptions(150, 150))
                .build();
DraweeController draweeController = Fresco.newDraweeControllerBuilder()
        .setImageRequest(imageRequest)
        .setOldController(view.getController())
        .setAutoPlayAnimations(true)
        .build();
view.setController(draweeController);

**Comment by agoodcoolman** [comment]
have a method to clean the image  and show default?

**Comment by plamenko** [comment]
I am not sure I understand the issue. Can you please clarify?

**Comment by IanChilds** [comment]
You can just submit a new image request in order to show the "default image".
