### ISSUE TITLE
Support for animated GIF's

### ISSUE THREAD

**Issue by MohamadAtieh** [facebook/fresco#42]
Does this support GIF type images? There is this [gist](https://gist.github.com/devunwired/4479231) that [Glide](https://github.com/bumptech/glide) is using. 

[Picasso doesn't support it](https://github.com/square/picasso/issues/700) but Glide does and since Fresco is supported by Facebook I would like to know if there will be support for this if not already. 

It is also nice to have a comparison list between different image management libraries.

Thanks.

**Comment by liaohuqiu** [comment]
The answer is YES.

**Comment by MohamadAtieh** [comment]
Supported = Gold. 
http://frescolib.org/docs/animations.html#_
