### ISSUE TITLE
SimpleDraweeView not initialized

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#421]
Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!
            at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:226)

I have extended SimpleDraweeView to use a custom view.I am doing this only to separate my logic from that of Fresco.
This happens only when I fling on a recyclerview or switch swiftly between 2 long lists(~20 items each).
all my constructors in the custom view are chained to the three param constructor where the first call is super.
Any idea if the volume of data and images is causing an issue?

*EDIT*

facing this issue when I use 0.5.3 ,0.5.2 works fine.

**Comment by plamenko** [comment]
Are you properly calling `Fresco.initialize(context)` and where?

**Comment by droidekas** [comment]
I have extended the Application class and I call the `Fresco.initialize(context)` there.
I am sorry I am not able to give more details.
But it could also be a gradle build issue.
I am unable to replicate it.
You can close the issue or change it to need more details.I shall update the same if I face the same issue again.

**Comment by plamenko** [comment]
Sounds good. Please reopen or create a new issue if you encounter this again.
