### ISSUE TITLE
Add param placeholderBackground

### ISSUE THREAD

**Issue by ppamorim** [facebook/fresco#424]
We need to implement a background color for translucid placeholder. I need this because my placeholder can't be cropped and this makes everything more simple to change (like a color). This needs to be affected by borders too.

Can be:

    fresco:placeholderBackground="resource|color|drawable"

**Comment by plamenko** [comment]
You can achieve that by setting the placeholder programmatically. See [Using Drawees in Code] (http://frescolib.org/docs/using-drawees-code.html#_).

    Drawable[] layers = new Drawable[] {placeholderBackground, placeholder};
    hierarchy.setPlaceholderImage(new ArrayDrawable(layers));
