### ISSUE TITLE
When I add fresco to my app, it fails to run

### ISSUE THREAD

**Issue by hishamBakr** [facebook/fresco#425]
Dear,
 when I add fresco to my app using
compile 'com.facebook.fresco:fresco:0.5.3'
and run app, it gives me this error

Error:Execution failed for task ':mobile:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

Please advise

**Comment by plamenko** [comment]
Have you updated the Fresco from some older version to 0.5.3, or you just freshly added it?

**Comment by hishamBakr** [comment]
Thank you for reply. issue is fixed when I added
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
apply plugin: 'com.neenbedankt.android-apt'

I don't know if this is the root cause of issue but when I added this, issue fixed while this was not mentioned in installation guide.

**Comment by hishamBakr** [comment]
I am sorry. issue still exist. I thought it is fixed. it compiles without issues. but when I run app, it give me mentioned error.

I am not upgrading from older app. I am just trying fresco as I used to use Glide and I am interested to see if fresco is better than Glide or not. Please help

**Comment by sguillen** [comment]
If you are getting something like "Unable to execute dex: method ID not in [0, 0xffff]: 65536"
It could be this: https://github.com/facebook/fresco/issues/368

**Comment by hishamBakr** [comment]
I managed to fix the issue by adding:

 multiDexEnabled true
   compile 'com.android.support:multidex:1.0.0'
