### ISSUE TITLE
You should use provided rather than compile for javax.annotation:javax.annotation-api

### ISSUE THREAD

**Issue by mbrubin56** [facebook/fresco#43]
You need the annotations at compile time, not at run time, so "provided" is preferred. There is no need to distribute the source for the annotations. This is actually an issue for me because another library I depend on also packages the annotations (in a jar), and I'm getting an dex error because of the multiple definitions. I'm checking with my company to see whether I can sign your agreements to file a pull request.

**Comment by tyronen** [comment]
Looks like this is handled by your pull request #54.
