### ISSUE TITLE
RecyclerView scrolling is choppy when there are 10 identical gif images loaded from disk

### ISSUE THREAD

**Issue by wuqia** [facebook/fresco#431]
I'm using RecyclerView, each row has a SimpleDraweeView, and 10 rows. They are all loading an identical gif image from the phone's flash disk:
![dfqqm](https://cloud.githubusercontent.com/assets/5226466/8525500/325e0cca-23cf-11e5-8daa-096d32fa77dc.gif)

Scrolling is really choppy.

**Comment by plamenko** [comment]
What device and OS are we talking about? How many images / rows are visible at the same time? Scrolling issues might be due to a several animations being visible and running at the same time.

**Comment by wuqia** [comment]
Thanks for the reply.

Device: Moto G (2nd Generation)
OS: 5.0.2
Visible rows at the same time: 3
There is one image in each row.

Is it expected when there are several gifs visible on screen? Is it a hardware constraint? When I scroll I first observe the row that comes in being blank for briefly 1 or 2 seconds, then I see the image being loaded into its container and starts animating. 

It feels to me though it is the loading part that causes the delay. Although it is the same identical image that is already loaded for another row.(caching issue?)

**Comment by wuqia** [comment]
Sorry, I ran method profiler from DDMS and found that it is one of my methods in UI thread that caused the choppy behavior. After fixing that, scrolling is good at close to 60 fps. Please close this issue.

**Comment by plamenko** [comment]
Awesome!
