### ISSUE TITLE
Have Fresco generate thumbnails

### ISSUE THREAD

**Issue by CaiHuan** [facebook/fresco#439]
hi guys,
  i'm android developer who use fresco,but i have some problem when i use fresco~
  i'm make a photo app, but the original image is too large and throw too many image exception,
  so i wanna control the imagePipeline to generate thumbnail(use MediaStore.Images.Media.insertImage) 
  and load the thumbnail bitmap，but i didn't know how to do

**Comment by plamenko** [comment]
Have you tried [Resizing] (http://frescolib.org/docs/resizing-rotating.html#_)?

**Comment by CaiHuan** [comment]
the Resizing just resize the image,  but the list_view load image slowly if i load too many large photo(have not thumbnail)

**Comment by CaiHuan** [comment]
for example:
  the photo which take by Samsung Camera hasn't thumbnail, the fresco run slowly if i load the original photo(it isn't thumbnail in mobile), so i wanna imagePipeline generate thumbnail and load it

**Comment by plamenko** [comment]
We are working on improving the thumbnail support, but regardless of that, you should still specify the resize options. If you don't specify the resize options, Fresco doesn't know how big image you need and will return the original size which is probably not what you want for camera images.

**Comment by ikkyu0319** [comment]
@plamenko @CaiHuan I have same problem~

 String url= thumbnails://328914

name = "Screenshot_2016-03-08-16-54-45.png"
path = "/storage/emulated/0/Pictures/Screenshots/Screenshot_2016-03-08-16-54-45.png"
photoID = 328914

**Comment by s1rius** [comment]
`setDownsampleEnabled(true)` in ImagePipelineConfig
