### ISSUE TITLE
SimpleDraweeView.setImageURI(String) should be SimpleDraweeView.setImageURI(Uri)

### ISSUE THREAD

**Issue by bradleybossard** [facebook/fresco#44]
In the example on this page

https://github.com/facebook/fresco/blob/gh-pages/docs/00-index.md

it reads

    SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
    draweeView.setImageURI("http://frescolib.org/static/fresco-logo.png");

but when I try to compile, I get the following

Error:(80, 19) error: no suitable method found for setImageURI(String)
method SimpleDraweeView.setImageURI(Uri,Object) is not applicable
(actual and formal argument lists differ in length)
method SimpleDraweeView.setImageURI(Uri) is not applicable
(actual argument String cannot be converted to Uri by method invocation conversion)

Shouldn't it read something like this instead?

        Uri uri = Uri.parse("http://frescolib.org/static/fresco-logo.png");
        SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
        draweeView.setImageURI(uri);

**Comment by tyronen** [comment]
The docs have been corrected. Thanks for reporting this!
