### ISSUE TITLE
MediaTek Chipset device crashes when App uses Fresco + SqlCipher + Camera permisson

### ISSUE THREAD

**Issue by wuqia** [facebook/fresco#442]
The issue is that MediaTek has a native bug that when Bitmap decode configuration is set to ARGB_8888, and app requests for camera permisson, and app uses database encryption with sqlCipher, app crashes on the native layer when bitmap is being decoded.

We use a work around to detect MediaTek chipset and use ARGB_4444 instead of 8888.

Reference:
http://ask.csdn.net/questions/169972

Could Fresco provide a way to customize the bitmap decode configuration to something else, like ARGB_4444.

**Comment by erikandre** [comment]
Closing as this is most likely not as relevant any more due to the obsolescence of these devices.
