### ISSUE TITLE
android:tint is not taking affect

### ISSUE THREAD

**Issue by imraansarwar** [facebook/fresco#443]
Hi,
I am simply using the following declaration. I need the tint on the image, but its not appearing at all.
        <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/imgItemPrimary"
            android:layout_width="match_parent"
            android:layout_height="200dp"
            android:scaleType="centerCrop"
            android:tint="@color/tint_background"
            fresco:placeholderImage="@drawable/img_placeholder"
            fresco:roundedCornerRadius="5dp"
            fresco:roundBottomLeft="false"
            fresco:roundBottomRight="false"
            fresco:roundingBorderWidth="1dp"
            />

Kindly advice what am I missing here.

Thanks,
Imran

**Comment by imraansarwar** [comment]
I tried using overlayImage attribute such that: 
app:overlayImage="@color/tint_background"

but it is shadowing the rounded corner effect. I need the round affect... its a must... any solution please.

Thanks
Imran

**Comment by aagnes** [comment]
The fix is in 0.7.0 already.
