### ISSUE TITLE
crash in Nexus5 

### ISSUE THREAD

**Issue by guomin0999** [facebook/fresco#45]
F/libc    ( 7134): heap corruption detected by dlmalloc
F/libc    ( 7134): Fatal signal 6 (SIGABRT) at 0x00001bde (code=-6), thread 7134 (esco.frescotest)

F/libc    ( 7267): Fatal signal 6 (SIGABRT) at 0x00001c63 (code=-6), thread 7276 (FinalizerDaemon)

F/libc    ( 7433): Fatal signal 7 (SIGBUS) at 0x0000000d (code=1), thread 7442 (FinalizerDaemon)

**Comment by plamenko** [comment]
Hi, we'll look into it ASAP. Can you please provide more information on how you use Fresco? This will help us in isolating the issue.

**Comment by guomin0999** [comment]
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fresco.initialize(this);
        setContentView(R.layout.activity_main);

        SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
        draweeView.setImageURI(Uri.parse("url"));
    }

Step:
1.open app > ok > close
2.open app> ok > close
3.open app>crash
4.open app> ok > close
5.open app > ok > close
6.open app>crash

**Comment by michalgr** [comment]
Thanks, for the scenario, I am able to reproduce - fix is coming soon.

**Comment by michalgr** [comment]
The crash is happening when calling recycle on already finalized Bitmap. It is fixed in master now.
