### ISSUE TITLE
How Can I remove x86 support

### ISSUE THREAD

**Issue by huclengyue** [facebook/fresco#454]
my app is just 2M, after useing  the fresco,it  increases 4M ,I just want support ARM platform.How can I remove X86 and x86_64 platform ?

**Comment by lizhiqiang-unnoo** [comment]
This may help: http://frescolib.org/docs/multiple-apks.html#_

**Comment by michalgr** [comment]
use abiFilter in your gradle file, find more information here: http://tools.android.com/tech-docs/new-build-system/tips
