### ISSUE TITLE
FailureImage does not fade in if coming from cache

### ISSUE THREAD

**Issue by jkane001** [facebook/fresco#455]
I know there was a similar issue (Issue #147) that was closed, but I still think there's a potential improvement to be had.  If the failure image is in cache, it doesn't fade when loads the failure image, after attempting to load the actual image. Since this (by definition) happens after the load has tried & failed, it happens sometimes several seconds after the image started loading, making the snap-in of the failure image more jarring. So my request is that when switching to the failure image (or retry image) that it would fade in, even if it is in cache.

**Comment by IanChilds** [comment]
Sorry for the extremely slow reply. 

The failure image is a drawable that you set on the hierarchy, so I'm not sure what you mean by "even if it is in the cache". I think it will always be present in the drawee hierarchy. If you do it this way, then the failure image will be faded in as you wish. 

Are you loading a new image on failure that is found in cache and then shown immediately? Can you give a code snippet?
