### ISSUE TITLE
How can I exclude arm64-v8a

### ISSUE THREAD

**Issue by goodboywt** [facebook/fresco#458]
I found the arm64-v8a dir in 0.5.3,but another lib dependent by my app has not the arm64-v8a,so my app will crash on arm64 platform,as you know ,the other lib hasn't "so" file math arm64-v8a so that my app can't find the "so" file on arm64 platform.

How can I exclude arm64-v8a dir in build.gradle

**Comment by lizhiqiang-unnoo** [comment]
this may help: http://frescolib.org/docs/multiple-apks.html#_

**Comment by goodboywt** [comment]
@lizhiqiang-unnoo this doesn't help,I just want to exclude the arm64-v8a,but this create each platform a apk file

**Comment by huclengyue** [comment]
@goodboywt you can use include 'arm64-v8a' . will just create arm_64 apk

**Comment by goodboywt** [comment]
@huclengyue I don't want the arm64 dir

**Comment by michalgr** [comment]
Try playing with abiFilters. You might find this link useful: http://tools.android.com/tech-docs/new-build-system/tips. abiFilter should allow you to select single architecture to include in your app, abiFilters should let you do the same with multiple archs.

**Comment by liuchonghui** [comment]
try

packagingOptions {
        exclude 'lib/arm64-v8a/libbitmaps.so'
        exclude 'lib/arm64-v8a/libgifimage.so'
        exclude 'lib/arm64-v8a/libimagepipeline.so'
        exclude 'lib/arm64-v8a/libmemchunk.so'
        exclude 'lib/arm64-v8a/libwebp.so'
        exclude 'lib/arm64-v8a/libwebpimage.so'
        exclude 'lib/x86_64/libbitmaps.so'
        exclude 'lib/x86_64/libgifimage.so'
        exclude 'lib/x86_64/libimagepipeline.so'
        exclude 'lib/x86_64/libmemchunk.so'
        exclude 'lib/x86_64/libwebp.so'
        exclude 'lib/x86_64/libwebpimage.so'
    }
