### ISSUE TITLE
Split common package into a standalone lib

### ISSUE THREAD

**Issue by villadora** [facebook/fresco#46]
Great Library! and I saw lots of commons classes for android. How about to split those classes in `common` package into a new lib. so people can use it like guava in java.

That would be very very helpful!  THX

**Comment by tyronen** [comment]
This has already been done.

There is an alternate Gradle target you can use called fbcore.

This isn't yet documented, as that library isn't comprehensive but merely support utilities used by Fresco.

```groovy
compile 'com.facebook.fresco:fbcore:0.1.0+'
```

**Comment by villadora** [comment]
Cool!
