### ISSUE TITLE
Unnecessary permissions used by Fresco.

### ISSUE THREAD

**Issue by EugineKidoz** [facebook/fresco#461]
Hello.

Why does Image Library use following permissions ? 

 android:name="android.permission.ACCESS_COARSE_LOCATION"
 android:name="android.permission.USE_CREDENTIALS"

**Comment by tyronen** [comment]
Fresco does not require these permissions. You can see that our sample apps do not have these permissions in their manifests.

Why do you think this is required?

**Comment by EugineKKK** [comment]
After adding fresco and compiling Final apk, When installing this permissions are added to the pre install info view of the application (Application ask them) ... when fresco removed i don't see those permission.. so i had to add  remove node (Manifest Tools)  to exclude those permission from merging to final manifest on compilation..

**Comment by AcidicSkittles** [comment]
I have fresco in my project and I don't have those permissions added to my final apk. To see exactly what is adding those permissions you can check the contents of app/build/outputs/logs/manifest-merger-debug-report.txt in your project folder and do a search for those permissions to see which external library is adding them

See https://commonsware.com/blog/2015/06/25/hey-where-did-these-permissions-come-from.html for more help on doing so

**Comment by EugineKKK** [comment]
Have checked the report.
Seems like com.android.support:support-v4:22.2 is adding those permissions.

Thanks.

**Comment by AcidicSkittles** [comment]
That's strange. If need be you can remove those permissions by adding something like
```xml
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" tools:node="remove" />
<uses-permission android:name="android.permission.USE_CREDENTIALS" tools:node="remove" />
```
to your manifest. I'm not sure what damage that would cause, so it's best to try and figure out why it's importing them.
