### ISSUE TITLE
Animations with PNG sequences

### ISSUE THREAD

**Issue by haseebrabbani** [facebook/fresco#462]
Hi, 
I am trying to determine the viability of Fresco for the animations in my app. I have PNG sequences for each animation which are included as drawable resources in my project (one PNG per frame named as frame_1.png, frame_2.png, etc...). My question is: how can I get Fresco to animate these frames for me in a SimpleDraweeView? Does it currently support this functionality?

**Comment by michalgr** [comment]
Is transforming sequence of pngs into single animated webp image an option here ? Note that you would probably save a lot of bytes this way. There is no support for assembing animations from multiple frames right now.

**Comment by haseebrabbani** [comment]
Is there a recommended tool for converting PNG sequences into animated WebP files?

**Comment by AcidicSkittles** [comment]
The only tool that comes to mind is ImageMagick. You'll have to convert the frames to an animation (gif or webp) before sending it to your app. I don't know if it's possible to use ImageMagick to convert the png frames to an animation in android

**Comment by haseebrabbani** [comment]
So I've got the GIF animation. How can I tell Fresco to only play it once? I see the anim.start()/stop() methods, but is there a way to tell Fresco to just play an animation once and then stop?

**Comment by AcidicSkittles** [comment]
I don't think there's an api call in frasco for that. If you're using ImageMagick to build the gif, I do know that it has a [-loop](http://www.imagemagick.org/Usage/anim_basics/#loop) flag. You can try that to set it to play only once using -loop 1

**Comment by solohsu** [comment]
It seems like  `GifImage#getLoopCount` is never used to limit the loop times...

**Comment by plamenko** [comment]
The loop count specified in the GIF image should be respected. If that's not the case then it is a bug.

**Comment by tyronen** [comment]
The bug is tracked separately in #180

**Comment by erikandre** [comment]
Cleaning up old issues
