### ISSUE TITLE
BaseRepeatedPostProcessor sourceBitmap scaleType question

### ISSUE THREAD

**Issue by lichangadd** [facebook/fresco#465]
My SimpleDraweeView's size is 640*180(scaleType="centerCrop") and the picture's size is 640*640.
But in my PostProcessor, sourceBitmap's size is 640*640.How can I get the centerCroped sourceBitmap?

**Comment by lichangadd** [comment]
Got It, use destBitmap's size

**Comment by tyronen** [comment]
You can't get it. The Bitmap itself is not modified to do the crop. The Drawable that renders it calculates a matrix to do the cropping, and passes it to a Canvas object. This will (Android 4.0+) do the cropping in the GPU hardware.
