### ISSUE TITLE
Can't deploy samples on devices

### ISSUE THREAD

**Issue by LittlePanpc** [facebook/fresco#466]
I download this project and import into my Android Studio. Updated sdk information and building tools version and run samples on my emulator.

But error happened.

`Error:Execution failed for task ':imagepipeline:ndk_clean_bitmaps'.`
`> A problem occurred starting process 'command 'ndk-build''`

No matter whether I set the ndk location, the result is the same. 

What happened? How could I solve this?

**Comment by michalgr** [comment]
how do you set ndk location ? Did you follow instructions here: http://frescolib.org/docs/building-from-source.html ? What ndk version do you use ?

**Comment by LittlePanpc** [comment]
Right-click  --> Open Module Settings -->  SDK Location -->  Android NDK Location, then I selected ".../android-ndk-r10e", and OK, but this error happened once and over again.

My NDK is up to date and downloaded from official website, which is a bin file and uncompressed by terminator.

**Comment by michalgr** [comment]
Please follow instructions here instead: http://frescolib.org/docs/building-from-source.html. Our gradle script does not use the location set in android studio.
