### ISSUE TITLE
Images aren't loading on certain devices 

### ISSUE THREAD

**Issue by Adam-Fresko** [facebook/fresco#469]
Certain images aren't loading on certain devices. We are having grid recycler with about  60 small images. Devices are in the same WIFI network, factory settings. Images are working perfectly on sgs 3, xperia z1c, nexus 4, and fails on htc desire 816. Tested with 0.5.1, 0.5.2, 0.5.3 exactly same result. I have debugged code and proper url is provided, also tested with browser, webview, picasso.

Working images:
https://online.kreckm.pl/data/achievements/gra-na-czas.png
https://online.kreckm.pl/data/achievements/niezla-forma.png
https://online.kreckm.pl/data/achievements/rowery_rozpedzony.png

Not loading:
 https://online.kreckm.pl/data/achievements/miejska-jazda.png
 https://online.kreckm.pl/data/achievements/na-start.png
 https://online.kreckm.pl/data/achievements/gaz-do-dechy.png

**Comment by michalgr** [comment]
Can you turn on verbose logging and check whether there are any error messages in the logcat ?

**Comment by Adam-Fresko** [comment]
I look for that tomorrow.

**Comment by tyronen** [comment]
Never heard back.
