### ISSUE TITLE
Bitmap too large to be uploaded into a texture

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#470]
This occurs only when i fling on the recycler view. each item in the recyclerview contains ~ 4 images.All the images are displayed:however the logcat shows this issue.

 W/OpenGLRenderer﹕ Bitmap too large to be uploaded into a texture (1440x4500, max=4096x4096)

**Comment by michalgr** [comment]
Do you control size of displayed images ? If images you display are arbitrary big, you should resize them: http://frescolib.org/docs/resizing-rotating.html#resizing

**Comment by droidekas** [comment]
based on the doc,resizing is limited only to jpeg.Anyway that I can handle other formats?

**Comment by IanChilds** [comment]
Not yet. But it should be coming in a future release.

**Comment by tyronen** [comment]
You can now use [downsampling](http://frescolib.org/docs/resizing-rotating.html#downsampling)

**Comment by zhangmaoyong34** [comment]
I also meet this problem.who have good idea

**Comment by sbmaggarwal** [comment]
As said by @tyronen ,

`ImagePipelineConfig config = ImagePipelineConfig.newBuilder(getApplicationContext())
                .setDownsampleEnabled(true)
                .build();

        Fresco.initialize(getApplicationContext(), config);`

This solved the problem for me.
