### ISSUE TITLE
CountingMemoryCache not cache current images in memory

### ISSUE THREAD

**Issue by wxcchdStar** [facebook/fresco#471]
I cat the CountingMemoryCache source code, and i found that CountingMemoryCache do not cache new image when the memory cache is already full. So when notifyDataSetChanged called, the image in ListView will be flash. Because the images don't be cached.

I think this is a bug.

**Comment by michalgr** [comment]
This is intentional. If the cache is full of images that cannot be evicted it won't accept any more images. Image cannot be evicted if there is a reference from outside of the cache pointing to that image. Try to release more images if you hit this problem

**Comment by wxcchdStar** [comment]
Thank you! I get it. But how i use Fresco to release more images? Clear the memory cache?

**Comment by IanChilds** [comment]
If images cannot be evicted it is because there is still another reference to them somewhere, and that is usually because they are on the screen (or you are not releasing your references correctly). Your best bet is probably to use a larger cache, if you are able to.

**Comment by wxcchdStar** [comment]
@IanChilds, i use SimpleDraweeView.setImageURI() in BaseAdapter.getView(). When convertView is used to load another image, do SimpleDraweeView release its old image reference? Or how i release the old reference?

**Comment by IanChilds** [comment]
Yeah, if you're using SimpleDraweeView it will do all the work for you.

**Comment by wxcchdStar** [comment]
@IanChilds, I think the SimpleDraweeView don't release the old image reference. At least, when the SimpeDraweeView load a new image(the memory cache is full), the old image don't be evicted in the CountingMemoryCache and the new image don't be added in memory cache.So when notifyDataSetChanged call, the images will be flash.

**Comment by qichuan** [comment]
Having the same problem here, I called `imagePipeline.evictFromMemoryCache(uri)` to try to release the memory but yet the newly loaded images are still flashing.
