### ISSUE TITLE
Leak on NavigationDrawer and RecyclerView

### ISSUE THREAD

**Issue by leonardo2204** [facebook/fresco#472]
I'm using LeakCanary in my app and I got this leak trace from the app:

Device: samsung samsung SM-G900M klteub
* Android Version: 5.0 API: 21 LeakCanary: 1.3.1
* Durations: watch=5017ms, gc=172ms, heap dump=6541ms, analysis=56068ms

 com.maddogs.mymoney.activities.MainActivity has leaked:
* GC ROOT static com.facebook.drawee.view.SimpleDraweeView.sDraweeControllerBuilderSupplier
* references com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.mContext
* leaks com.maddogs.mymoney.activities.MainActivity instance

* Details:
* Class com.facebook.drawee.view.SimpleDraweeView
|   static $staticOverhead = byte[] [id=0x76fce1d1;length=8;size=24]
|   static sDraweeControllerBuilderSupplier = com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier [id=0x12fc6600]
* Instance of com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier
|   mBoundControllerListeners = null
|   mContext = com.maddogs.mymoney.activities.MainActivity [id=0x12f19490]
|   mImagePipeline = com.facebook.imagepipeline.core.ImagePipeline [id=0x12f74dc0]
|   mPipelineDraweeControllerFactory = com.facebook.drawee.backends.pipeline.PipelineDraweeControllerFactory [id=0x12fc69a0]
* Instance of com.maddogs.mymoney.activities.MainActivity
|   avatar = com.facebook.drawee.view.SimpleDraweeView [id=0x12c14c00]
|   drawer = android.support.design.widget.NavigationView [id=0x12c1e000]
|   drawer_layout = android.support.v4.widget.DrawerLayout [id=0x12c1d400]
|   emailTextView = android.support.v7.widget.AppCompatTextView [id=0x12c15800]
|   fragmentSelected = java.lang.String [id=0x12c0c4c0]
|   nameTextView = android.support.v7.widget.AppCompatTextView [id=0x12c15400]
|   searchView = null
|   toolbar = android.support.v7.widget.Toolbar [id=0x12c1dc00]
|   selectedMenuItem = 2131623942
|   mDelegate = android.support.v7.app.AppCompatDelegateImplV14 [id=0x12c2e760]
|   mAllLoaderManagers = android.support.v4.util.SimpleArrayMap [id=0x12cb3a60]
|   mContainer = android.support.v4.app.FragmentActivity$2 [id=0x12f4d540]
|   mFragments = android.support.v4.app.FragmentManagerImpl [id=0x12d1ed60]
|   mHandler = android.support.v4.app.FragmentActivity$1 [id=0x12f59dc0]

My code snippet: 

```
SimpleDraweeView avatar;
...
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
...
avatar = (SimpleDraweeView) findViewById(R.id.avatar);
avatar.setImageURI(Uri.parse(user.getProfileImg().getUrl()));
```
}

The image comes from the internet and are JPEG;
Any ideas ?

Thanks

**Comment by IanChilds** [comment]
Where are you initializing Fresco? It looks like it is complaining because you initialize Fresco using MainActivity, and then Fresco keeps the reference to MainActivity after the activity has been destroyed, causing the leak. Is that possible? 

If so, consider passing Fresco the application context, or initialize Fresco in a subclass of android.app.Application.

**Comment by leonardo2204** [comment]
Thanks for the reply, but actually I'm initializing Fresco in my Application subclass, and only there.
In my MainActivity I don't have any Fresco initialization (and nowhere else).

**Comment by IanChilds** [comment]
In that case I'm not sure how SimpleDraweeView could have a DraweeControllerBuilderSupplier that references MainActivity. Perhaps you can do some logging to see where it gets set to that value? I'm afraid I can't really help any more than that without the code in front of me.
