### ISSUE TITLE
onLevelChange gif issue

### ISSUE THREAD

**Issue by ReginFell** [facebook/fresco#475]
Hi! I think you can help me.
We are using your awesome library to show jpg/png/gif images with the progress bar. With the jpeg and the png images everything work fine, but when we load gif, onLevelChange callback we get 10000, but the gif is shown after 10-25 seconds.
How we can solve this issue?

![cdae7426-2f96-11e5-8a50-01f95f54bc9f](https://cloud.githubusercontent.com/assets/3144106/8821091/a88c11a8-3063-11e5-808e-0759a28f9636.png)
![cdccd024-2f96-11e5-9efd-134532a199e2](https://cloud.githubusercontent.com/assets/3144106/8821090/a887c04e-3063-11e5-907d-794ea8b5c84e.png)

**Comment by IanChilds** [comment]
Is this an animated or static image? Can you give me the url so that we can test it our end? It sounds like it's taking a long time for the image to load after it is downloaded/retrieved from cache, but I'm not sure why that would be the case.

**Comment by ReginFell** [comment]
Animated image.

We are facing this problem with any big GIF, for example http://ta-ty-sho.com/wp-content/uploads/2015/04/gifki-gif-animatsia-multfilm-kot-v-sapogakh-i-t.gif

If GIF cached, then it take 1-2 seconds to appear, but if loaded first time, we have that problem.
Actually, we try to use onFinalImageSet to handle animation loaded event, it triggered after 10-25 seconds after onLevelChange got level == 10000

**Comment by xufan** [comment]
Same issue,after progressBarImage disappear fresco need a short time to show the gif.
But after first loaded when gif show again ,it has no delay at all.

**Comment by IanChilds** [comment]
It looks like this is a bug in Fresco - when we fetch an image from disk cache successfully, we say that the request is 100% completed, when we fact we still need to do the decode. For an animated GIF like the above one, the decode can take a long time, leading to the gap that you notice above.

**Comment by rf3Studios** [comment]
@IanChilds Do you have a recommendation for how to work around this issue for now?

**Comment by IanChilds** [comment]
Can you use it in conjunction with the `onFinalImageSet` callback?

**Comment by ReginFell** [comment]
@IanChilds yeah, we try to use it, but have no idea how we can connect onFinalImageSet  with ProgressBarDrawable

**Comment by IanChilds** [comment]
Don't you have access to the ProgressBarDrawable when you construct your listener for the DraweeController?

**Comment by ReginFell** [comment]
Yeah, that is my code which override setUri: 

 @Override
    public void setImageURI(Uri uri) {
        CircularProgressDrawable.Builder progressBuilder = new CircularProgressDrawable.Builder(mContext).
                setBackgroundColorResource(mBackgroundColor)
                .setRadiusDimenResource(mRadius)
                .setRingSizeDimenResource(mRingSize)
                .setEmptyRingColorResource(mEmptyRingColor)
                .setRingColorResource(mRingColor);
        GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(mContext.getResources()).setFadeDuration(0)
                .setProgressBarImage(progressBuilder.create()).setActualImageScaleType(ScalingUtils.ScaleType.FOCUS_CROP)
                .build();

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setAutoPlayAnimations(mPlayAnimation)
                .build();

        if (mFitStart) {
            hierarchy.setActualImageFocusPoint(new PointF(0f, 0f));
        }
        if (mIsRounded) {
            RoundingParams roundingParams = RoundingParams.fromCornersRadius(5f);
            roundingParams.setRoundAsCircle(true);
            hierarchy.setRoundingParams(roundingParams);
        }
        this.setHierarchy(hierarchy);
        this.setController(controller);
    }

**Comment by IanChilds** [comment]
You need to add a ControllerListener to the DraweeControllerBuilder that overrides onFinalImageSet

**Comment by ReginFell** [comment]
I tried this code http://pastebin.com/TAem1tta
still ProgressBar pass very fast, but animation appeared after 10-25 seconds

**Comment by IanChilds** [comment]
Yeah the problem is that the progress bar gets faded out when the progress is set to 100. 

I wonder if it's possible to make this work by setting the progress bar to be the placeholder image too? Can you try that?

**Comment by ReginFell** [comment]
Please, take a look how it works with ProgressDrawable in placeholder: 
https://www.youtube.com/watch?v=vOg4KwPi3pE&feature=youtu.be

**Comment by plamenko** [comment]
We should handle this on the pipeline level. It is hard to estimate the decoding time, but my hunch is that there are two main components here: the size in bytes of the image and the decode queue length (in bytes).

We could make decode producer do some heuristics like:
`out_progress = f(in_progress, estimated_decode_wait_time)`
`out_progress` is the progress that decode producer reports to its parent
`in_progress` is the progress of the child producer (e.g. network fetch progress)
`f(in_progress, wait_time)` could be something like `in_progress * 0.9 + exp(-C1 * wait_time) * 0.1`.
`estimated_decode_wait_time` could be something like C2 * (total_bytes_in_the_decode_queue_including_the_current_image)
There is no optimal solution to this problem, all we can do is to provide an estimate. This is just one idea.

**Comment by JiaoShuai** [comment]
Have you solved the delay problem? How ?

**Comment by kirwan** [comment]
I believe this should be solved by da9b7f162bb31f538bda2f34e83ac505f0e67a39.
