### ISSUE TITLE
Is it possible to turn off the fade-in animation when the image is loaded ?

### ISSUE THREAD

**Issue by cooperkong** [facebook/fresco#476]
Thanks for the awesome library.
Just wondering Is there such mechanism to turn off the fade-in animation of Drawee?
Thanks guys!

**Comment by IanChilds** [comment]
Yeah, you can - either via XML (http://frescolib.org/docs/using-drawees-xml.html#_) or via code (http://frescolib.org/docs/using-drawees-code.html#_). Just set the fade duration to 0.
