### ISSUE TITLE
is there a way to retry download the url ?

### ISSUE THREAD

**Issue by wiliemusLin** [facebook/fresco#478]
is there a way to retry download the url when the downloading is faliure because of timeout? like setting 2 times or 3 times?
i am very worried, who can help me, i need help,come on!
i am a beautiful girl, i have no boyfriend, who can help me?

**Comment by IanChilds** [comment]
You could use a network stack that automatically retries, or you can use tap-to-retry on Drawee if you're okay with the user having to manually retry.
