### ISSUE TITLE
When I load a picture of 600 * 22177， the app run crash!

### ISSUE THREAD

**Issue by pphdsny** [facebook/fresco#479]
I want to know that fresco has a size limit for loading pictures?

**Comment by IanChilds** [comment]
It shouldn't. But this is a pretty big image so could cause problems, what Android version are you running? What is the stack trace from the crash?

**Comment by pphdsny** [comment]
Nothing.No detailed log.Only 
07-23 09:38:46.428 W/OpenGLRenderer﹕ Bitmap too large to be uploaded into a texture (200x7382, max=4096x4096)
07-23 09:38:46.429  A/libc﹕ Fatal signal 7 (SIGBUS) at 0x0000000f (code=1), thread 17160 (eam.app.android)
I saw that there was a maximum limit on the log is 4096*4096, is not I load the picture can not exceed this limit?
My app is running version is 4.0+.fresco version is 0.5.3.

**Comment by IanChilds** [comment]
Is this a JPEG or a PNG?

**Comment by pphdsny** [comment]
JPEG

**Comment by pphdsny** [comment]
JPEG

**Comment by aiuuyoyo** [comment]
I am doubt that, too! But I didn't find any method to rule the decoding size of images

**Comment by aiuuyoyo** [comment]
It seems fresco has no a size limit for loading pictures. I didn't find any in the guidline.http://fresco-cn.org/docs/using-image-pipeline.html#_

**Comment by IanChilds** [comment]
The limit is device-specific, and is imposed by OpenGL. See http://stackoverflow.com/questions/10271020/bitmap-too-large-to-be-uploaded-into-a-texture for example. In this case it is 4096x4096, which should be plenty. You might need to use an image that doesn't have such a huge aspect ratio.
