### ISSUE TITLE
First frame of animated GIF as placeholder image?

### ISSUE THREAD

**Issue by ewills** [facebook/fresco#480]
Is there a way to use the first frame of an animated GIF as the placeholder image for a view?  This would ease the visual transition when loading (and reloading) animated GIFs.

If not, I would love to see this added as a feature!

**Comment by IanChilds** [comment]
I'm afraid this isn't possible at the moment - we'll see if there's a lot of demand for this feature.

**Comment by ewills** [comment]
Great, thanks!

**Comment by Eagles2F** [comment]
It would be very nice to have this feature

**Comment by PaulProject** [comment]
+1

**Comment by jhwing** [comment]
+1

**Comment by dmitrychistyakov** [comment]
As a temporary workaround you can save first gif frame and then use it as lowresImage while hige gif is loading
```
@Override
        public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
            if (imageInfo instanceof CloseableAnimatedImage) {
                GifImage gif = (GifImage) imageInfo.getImageResult().getImage();
                if (gif != null) {
                    Bitmap bitmap = Bitmap.createBitmap(attach.getPhoto().getWidth(), attach.getPhoto().getHeight(), Bitmap.Config.ARGB_8888);
            gif.getFrame(0).renderFrame(attach.getPhoto().getWidth(), attach.getPhoto().getHeight(), bitmap);
//save bitmap in your own cache
bitmap.recycle();
                }
            }
}
```

**Comment by ramilushev** [comment]
+1

**Comment by kimthangatm** [comment]
+1

**Comment by odaeagle** [comment]
+ 1

**Comment by biwoodfengs** [comment]
+1

**Comment by Tamarabyte** [comment]
+1

**Comment by kimthangatm** [comment]
+1

**Comment by lazybios** [comment]
+1

**Comment by yshubin** [comment]
+1

**Comment by rafaelekol** [comment]
+1

**Comment by namchuai** [comment]
Still waiting for this feature!
+1

**Comment by storix** [comment]
+1

**Comment by lambdapioneer** [comment]
I'm afraid that I have no update on this. However, we are always welcoming pull-requests that add support for this in a maintainable way :) @oprisnik is working on a new architecture for animations that hopefully make support for this easier

**Comment by jjding1986** [comment]
+1

**Comment by qinhehu** [comment]
+1

**Comment by dbof10** [comment]
+1

**Comment by foghina** [comment]
We don't have a use case for this so we're probably not going to work on it internally. However, I think the use case is valid and it would be a good feature to have, so we would still appreciate a PR for this, even though I'm closing the issue now.

**Comment by daixiansen** [comment]
+1

**Comment by daixiansen** [comment]
Is this problem solved now?

**Comment by maidou0215** [comment]
+1

**Comment by Lizz0y** [comment]
+1
