### ISSUE TITLE
gif show slow

### ISSUE THREAD

**Issue by danhantao** [facebook/fresco#481]
I show gif in gridview, every row 4, slide it quickly, gif image loading is too slow, you can see the background.

**Comment by IanChilds** [comment]
What kind of GIF is this? Where are the images coming from - are they network images, or local images?

**Comment by danhantao** [comment]
network images,downloaded,but show slowly when scroll~~~

**Comment by danhantao** [comment]
gif all like this:http://media4.giphy.com/media/zfCCnYiOyihos/200w.gif       not large,

**Comment by IanChilds** [comment]
Unfortunately you will see the background since they need to be decoded and that takes a non-trivial amount of time, even for relatively small GIFs. 

You'll have to prefetch (carefully) if you want to avoid seeing the background briefly.

**Comment by AllenVork** [comment]
I got the same problem,when i loading the gif from sdcard, it's much more slow than a jpeg.I don't know how to promote it.And i just wanna load the gif, no matter whether it animates or not.
