### ISSUE TITLE
Avoid OutOfMemoryError crashes when loading PNGs

### ISSUE THREAD

**Issue by sguillen** [facebook/fresco#483]
Apart from the fact that catching an ```OutOfMemoryError``` is not a solution, nor an advisable approach.

In cases where there is no control on the size of a PNG, let's say because of external URL's, [resizing with Fresco] (http://frescolib.org/docs/resizing-rotating.html) can't be done, since at the moment only JPEG resizing is supported. So I can't find a way of reducing the image's size in memory.

The only way I see to avoid a crash is to catch the OutOfMemoryError. The problem is the crash happens on a thread created by Fresco and I have no way of building a try/catch block on it.

Is there any way to avoid an OutOfMemoryError crash when loading an image with Fresco? If not, this is a feature request to support PNG resizing.

Related issues: https://github.com/facebook/fresco/issues/159, https://github.com/facebook/fresco/issues/477

**Comment by IanChilds** [comment]
We will have a solution for PNG resizing soon - watch this space!
