### ISSUE TITLE
SimpleDraweeView wrong scale when using rounded corners

### ISSUE THREAD

**Issue by elikohen** [facebook/fresco#486]
When setting both:

```
android:layout_width="60dp"
android:layout_height="80dp"
...
fresco:roundedCornerRadius="4dp"
fresco:actualImageScaleType="fitXY"
...
```
The image gets rounded corners but the image drawn is not fitting the space. I can just see the top left corner of the image loaded (the image is bigger than the space).

**Comment by IanChilds** [comment]
Are you able to use an overlay color to do your rounding for you? http://frescolib.org/docs/rounded-corners-and-circles.html#_

**Comment by elikohen** [comment]
Not in this case as there is part of an image below and also i'm using the elevation attribute to draw a shadow. Is not THAT important, as we can live without the rounded corners on that case but i wanted to let you know that rounded corners + fitXY doesn't work properly.

**Comment by hendrawd** [comment]
yea sure we can use color overlay for this bug, but it will be hard if we have custom background for the drawee view, not just a plain color
![as](https://cloud.githubusercontent.com/assets/9481791/10184612/0af638c8-6769-11e5-9a6c-0cf3858bd4fb.png)

**Comment by hendrawd** [comment]
ok, i am able to resolve this by passing resize options to the drawee view by the exact value i declare on the XML
ImageRequestBuilder requestBuilder = ImageRequestBuilder.newBuilderWithSource(uri)
                .setAutoRotateEnabled(true)
                .setResizeOptions(new ResizeOptions((int) util.convertDpToPixel(100, this), (int) util.convertDpToPixel(100, this)));
and the XML use
app:roundAsCircle="true"
![screen shot 2015-09-30 at 3 42 11 pm](https://cloud.githubusercontent.com/assets/9481791/10188486/e46d2b78-6789-11e5-8480-acfb043f58f1.png)

**Comment by tyronen** [comment]
Modified the documentation. FItXY is not supported with BitmapOnly rounding, except in the case of @hendrawd's workaround.
