### ISSUE TITLE
fresco:placeholderImageScaleType does not seem to have any effect (in GridView)

### ISSUE THREAD

**Issue by ewills** [facebook/fresco#487]
I've got a SimpleDraweeView in a GridView with XML:

```
<com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/redacted"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    fresco:viewAspectRatio="0.75"
    fresco:placeholderImageScaleType="centerCrop" />
```

I'm setting the placeholder using:

hierarchy.setPlaceholderImage(new BitmapDrawable(context.getResources(), iconPlaceholder));

Regardless of the value of fresco:placeholderImageScaleType, the placeholder scaling appears to be fitXY (i.e., image aspect ratio not preserved).  Scaling of the actual image is working great.

**Comment by luca992** [comment]
make a gridview with a RecyclerView. Then use something like this for your grid item layout:
    
    <?xml version="1.0" encoding="utf-8"?>
    <com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/networkImageView"
    android:layout_width="130dp"
    android:layout_height="130dp"
    app:actualImageScaleType="fitCenter"
    app:placeholderImage="@mipmap/ic_launcher"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto" />

**Comment by kirwan** [comment]
I'm cleaning up very old issues. If this still causes problems please comment and we can re-open.
