### ISSUE TITLE
The app crashed when sliding grideview ,version 0.6.0 

### ISSUE THREAD

**Issue by somatezyc** [facebook/fresco#490]
1.Display local camera images;
2.The image's count is 100+;

Environment:
1.samsung note4;

Log:
07-24 16:18:52.535    1345-1345/? E/StatusBar.NetworkController_dual﹕ updateTelephonySignalStrength: slot2 iconLevel = 2
07-24 16:18:53.415     338-1866/? E/BufferQueue﹕ [com.guangquaner/com.guangquaner.activitys.SelectImgActivity] queueBuffer: fence is NULL
07-24 16:18:53.415  28053-28053/com.guangquaner E/Surface﹕ queueBuffer: error queuing buffer to SurfaceTexture, -22
07-24 16:18:53.415  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1344>: failed to queueBuffer
07-24 16:18:53.415  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.435     338-1635/? E/BufferQueue﹕ [com.guangquaner/com.guangquaner.activitys.SelectImgActivity] queueBuffer: fence is NULL
07-24 16:18:53.435  28053-28053/com.guangquaner E/Surface﹕ queueBuffer: error queuing buffer to SurfaceTexture, -22
07-24 16:18:53.435  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1344>: failed to queueBuffer
07-24 16:18:53.435  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.455  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.455  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.455  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.455    1023-1023/? E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
07-24 16:18:53.475  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.475  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.475  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.485  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.485  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.485  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.495  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.495  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.495  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.515  28053-28213/com.guangquaner E/JHEAD﹕ can't open '/storage/emulated/0/dcim/camera/20150724_160951.jpg'
07-24 16:18:53.515  28053-28212/com.guangquaner E/JHEAD﹕ can't open '/storage/emulated/0/dcim/camera/20150724_160951(0).jpg'
07-24 16:18:53.515  28053-28213/com.guangquaner E/JHEAD﹕ can't open '/storage/emulated/0/dcim/camera/20150724_160952.jpg'
07-24 16:18:53.515  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.515  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.515  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.535  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.535  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.535  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.545  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.545  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.545  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.565  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.565  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.565  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.585  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.585  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.585  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.595  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.595  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.595  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE
07-24 16:18:53.615  28053-28053/com.guangquaner W/Adreno-GSL﹕ <gsl_ldd_control:414>: ioctl fd 63 code 0xc0140933 (IOCTL_KGSL_TIMESTAMP_EVENT) failed: errno 22 Invalid argument
07-24 16:18:53.615  28053-28053/com.guangquaner W/Adreno-EGLSUB﹕ <SwapBuffers:1338>: gsl_device_3d_add_fence_event failed
07-24 16:18:53.615  28053-28053/com.guangquaner W/Adreno-EGL﹕ <qeglDrvAPI_eglSwapBuffers:3796>: EGL_BAD_SURFACE

**Comment by somatezyc** [comment]
Like this #320;

**Comment by IanChilds** [comment]
Your logcat isn't very useful. What is the crash? Are you resizing your images correctly?

**Comment by somatezyc** [comment]
My code #320.  It does not worked in v5.0 ,and It  is resumed in v5.3.
Log:
07-28 10:29:40.286  18231-18231/com.guangquaner E/Surface﹕ dequeueBuffer failed (Invalid argument)
07-28 10:29:40.286  18231-18231/com.guangquaner E/ViewRootImpl﹕ Could not lock surface
    java.lang.IllegalArgumentException
            at android.view.Surface.nativeLockCanvas(Native Method)
            at android.view.Surface.lockCanvas(Surface.java:264)
            at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2882)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2856)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2694)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2267)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6678)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
            at android.view.Choreographer.doCallbacks(Choreographer.java:613)
            at android.view.Choreographer.doFrame(Choreographer.java:583)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5748)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by michalgr** [comment]
TransactionTooLargeException is a bucket for a lot of different issues: http://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception.

Does it happen if you display less than 100+ images ? Can you check number of opened file descriptors in your app ?

**Comment by somatezyc** [comment]
@michalgr .My code worked in v0.5.3,when i changed the verison to 0.6.0,this bug happend.
The bug reappeared when i sliding grideview, so i think it's fresco's bug;

**Comment by michalgr** [comment]
I am not saying it is not related to Fresco, Fresco uses file descriptors. Could you answer my questions from previous comment ?

**Comment by somatezyc** [comment]
#490 fixed in 0.6.1,thanks!
