### ISSUE TITLE
I want to show gif image files to preview the last frame

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#495]
public void onBindViewHolder(ViewHolder viewHolder, int position) {
        StickerData data = mArrayList.get(position);
        String call_stikcerText = "";
        if (data != null) {
            ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(new Uri.Builder()
                    .scheme(UriUtil.LOCAL_FILE_SCHEME)
                    .path(String.valueOf(data.imgUrl))
                    .build()).setImageType(ImageRequest.ImageType.SMALL)
                    .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                    .setResizeOptions(new ResizeOptions(viewHolder.call_sticker.getLayoutParams().width, viewHolder.call_sticker.getLayoutParams().height))
                    .build();
            ImagePipeline imagePipeline = Fresco.getImagePipeline();
            DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest, null);
            dataSource.subscribe(new BaseDataSubscriber<CloseableReference<CloseableImage>>() {
                @Override
                protected void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                    if (dataSource.isFinished()) {
                        CloseableReference closeableImageRef = (CloseableReference) dataSource.getResult();
                        if (closeableImageRef != null && closeableImageRef.get() instanceof CloseableAnimatedImage) {
                            CloseableAnimatedImage closeableAnimatedImage = (CloseableAnimatedImage) closeableImageRef.get();
                            AnimatedImage animatedImage = closeableAnimatedImage.getImage();
                            AnimatedImageFrame animatedImageFrame = animatedImage.getFrame(animatedImage.getFrameCount());
                            Bitmap bitmap = Bitmap.createBitmap(
                                    animatedImage.getWidth(),
                                    animatedImage.getHeight(),
                                    Bitmap.Config.ARGB_8888);
                            bitmap.eraseColor(Color.TRANSPARENT);
                            animatedImageFrame.renderFrame(animatedImage.getWidth(), animatedImage.getHeight(), bitmap);
                            if(bitmap != null){
                                viewHolder.call_sticker.setImageBitmap(bitmap);
                            }
                        }

                    }
                }
            }
        }
    }

**Comment by IanChilds** [comment]
What is going wrong? This is only going to get the last frame once the whole image is decoded, at which point you might as well show the image I guess?

**Comment by plamenko** [comment]
Take a look at:
`ImageRequestBuilder.setImageDecodeOptions`
`ImageDecodeOptionsBuilder.setDecodePreviewFrame`
`ImageDecodeOptionsBuilder.setUseLastFrameForPreview`

**Comment by plamenko** [comment]
You should not be doing any of those things you are doing in the subscriber.

**Comment by tyronen** [comment]
Reaping.
