### ISSUE TITLE
Now image loading speed really fast, but not particularly smooth slide

### ISSUE THREAD

**Issue by duanyuGit** [facebook/fresco#497]
I have a GridView,Sensory integration 0.6.0 version, when I scroll quickly to the head or tail, image loading speed really fast a lot, but found quickly scroll process, some slow is not smooth

**Comment by mingqlin** [comment]
Same issue here. in 0.5.*, gridview with 12 images, scrolling fast and very smooth. after upgrade to 0.6.0, when scroll fast, scroll is not smooth. please let me know if you need sample apps with both Fresco version for comparison

**Comment by michalgr** [comment]
We are aware of the problem, fix is on its way.

**Comment by tyronen** [comment]
Fixed in 0.6.1
