### ISSUE TITLE
ImageRequest setPostProcessor will cause the screen jump when recyclerview load more content

### ISSUE THREAD

**Issue by marsyu** [facebook/fresco#498]
ImageRequest setPostProcessor will cause the screen jump when recyclerview load more content

**Comment by michalgr** [comment]
What does screen jump mean ? Do images disappear for a moment ?

**Comment by marsyu** [comment]
the RecyclerViewAdapter add more items and invoke notifyDataSetChanged when the RecyclerView scroll to the bottom

**Comment by marsyu** [comment]
modify the demo https://github.com/06peng/FrescoDemo, the important part of code as below:
        public void onBindViewHolder(final ViewHolder holder, final int position) {
            FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) holder.mImageView.getLayoutParams();
            if (mRecyclerView.getLayoutManager() instanceof GridLayoutManager) {
                layoutParams.height = 200;
            } else if (mRecyclerView.getLayoutManager() instanceof StaggeredGridLayoutManager) {
                layoutParams.height = 600;
            } else {
                layoutParams.height = 800;
            }
            Uri uri = Uri.parse(mValues.get(position));
            Postprocessor redMeshPostprocessor = new BasePostprocessor() {
                @Override
                public String getName() {
                    return "redMeshPostprocessor";
                }

                @Override
                public void process(Bitmap bitmap) {
                 // do nothing
                    Log.d("ImageListFragment","process");
                }
            };

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setPostprocessor(redMeshPostprocessor)
                    .build();

            PipelineDraweeController controller = (PipelineDraweeController)
                    Fresco.newDraweeControllerBuilder()
                            .setImageRequest(request)
                            .setOldController(holder.mImageView.getController())
                                    // other setters as you need
                            .build();
            holder.mImageView.setController(controller);
//            holder.mImageView.setImageURI(uri);
            holder.mImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(mActivity, ViewPagerActivity.class);
                    intent.putExtra("position", position);
                    mActivity.startActivity(intent);

                }
            });
        }

        @Override
        public int getItemCount() {
            return mValues.size();
        }
        public void addItem(String[] items){
            mValues.addAll(Arrays.asList(items)) ;
            notifyDataSetChanged();
        }

        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if(linearLayoutManager != null){
                    boolean scrollToBottom =  linearLayoutManager.findLastVisibleItemPosition() >= adapter.getItemCount() - 2;
                    if(scrollToBottom){
                        adapter.addItem(ImageUrlUtils.getImageUrls());
                        Log.d("ImageListFragment",String.valueOf(scrollToBottom));
                    }
                }

            }
        });

**Comment by marsyu** [comment]
modify the demo https://github.com/06peng/FrescoDemo, the important part of code as below:
        public void onBindViewHolder(final ViewHolder holder, final int position) {
            FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) holder.mImageView.getLayoutParams();
            if (mRecyclerView.getLayoutManager() instanceof GridLayoutManager) {
                layoutParams.height = 200;
            } else if (mRecyclerView.getLayoutManager() instanceof StaggeredGridLayoutManager) {
                layoutParams.height = 600;
            } else {
                layoutParams.height = 800;
            }
            Uri uri = Uri.parse(mValues.get(position));
            Postprocessor redMeshPostprocessor = new BasePostprocessor() {
                @Override
                public String getName() {
                    return "redMeshPostprocessor";
                }

                @Override
                public void process(Bitmap bitmap) {
                 // do nothing
                    Log.d("ImageListFragment","process");
                }
            };

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setPostprocessor(redMeshPostprocessor)
                    .build();

            PipelineDraweeController controller = (PipelineDraweeController)
                    Fresco.newDraweeControllerBuilder()
                            .setImageRequest(request)
                            .setOldController(holder.mImageView.getController())
                                    // other setters as you need
                            .build();
            holder.mImageView.setController(controller);
//            holder.mImageView.setImageURI(uri);
            holder.mImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(mActivity, ViewPagerActivity.class);
                    intent.putExtra("position", position);
                    mActivity.startActivity(intent);

                }
            });
        }

        @Override
        public int getItemCount() {
            return mValues.size();
        }
        public void addItem(String[] items){
            mValues.addAll(Arrays.asList(items)) ;
            notifyDataSetChanged();
        }

        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if(linearLayoutManager != null){
                    boolean scrollToBottom =  linearLayoutManager.findLastVisibleItemPosition() >= adapter.getItemCount() - 2;
                    if(scrollToBottom){
                        adapter.addItem(ImageUrlUtils.getImageUrls());
                        Log.d("ImageListFragment",String.valueOf(scrollToBottom));
                    }
                }

            }
        });

**Comment by marsyu** [comment]
modify the demo https://github.com/06peng/FrescoDemo, the important part of code as below:
        public void onBindViewHolder(final ViewHolder holder, final int position) {
            FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) holder.mImageView.getLayoutParams();
            if (mRecyclerView.getLayoutManager() instanceof GridLayoutManager) {
                layoutParams.height = 200;
            } else if (mRecyclerView.getLayoutManager() instanceof StaggeredGridLayoutManager) {
                layoutParams.height = 600;
            } else {
                layoutParams.height = 800;
            }
            Uri uri = Uri.parse(mValues.get(position));
            Postprocessor redMeshPostprocessor = new BasePostprocessor() {
                @Override
                public String getName() {
                    return "redMeshPostprocessor";
                }

                @Override
                public void process(Bitmap bitmap) {
                 // do nothing
                    Log.d("ImageListFragment","process");
                }
            };

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setPostprocessor(redMeshPostprocessor)
                    .build();

            PipelineDraweeController controller = (PipelineDraweeController)
                    Fresco.newDraweeControllerBuilder()
                            .setImageRequest(request)
                            .setOldController(holder.mImageView.getController())
                                    // other setters as you need
                            .build();
            holder.mImageView.setController(controller);
//            holder.mImageView.setImageURI(uri);
            holder.mImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(mActivity, ViewPagerActivity.class);
                    intent.putExtra("position", position);
                    mActivity.startActivity(intent);

                }
            });
        }

        @Override
        public int getItemCount() {
            return mValues.size();
        }
        public void addItem(String[] items){
            mValues.addAll(Arrays.asList(items)) ;
            notifyDataSetChanged();
        }

        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if(linearLayoutManager != null){
                    boolean scrollToBottom =  linearLayoutManager.findLastVisibleItemPosition() >= adapter.getItemCount() - 2;
                    if(scrollToBottom){
                        adapter.addItem(ImageUrlUtils.getImageUrls());
                        Log.d("ImageListFragment",String.valueOf(scrollToBottom));
                    }
                }

            }
        });

**Comment by marsyu** [comment]
modify the demo https://github.com/06peng/FrescoDemo, the important part of code as below:
        public void onBindViewHolder(final ViewHolder holder, final int position) {
            FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) holder.mImageView.getLayoutParams();
            if (mRecyclerView.getLayoutManager() instanceof GridLayoutManager) {
                layoutParams.height = 200;
            } else if (mRecyclerView.getLayoutManager() instanceof StaggeredGridLayoutManager) {
                layoutParams.height = 600;
            } else {
                layoutParams.height = 800;
            }
            Uri uri = Uri.parse(mValues.get(position));
            Postprocessor redMeshPostprocessor = new BasePostprocessor() {
                @Override
                public String getName() {
                    return "redMeshPostprocessor";
                }

                @Override
                public void process(Bitmap bitmap) {
                 // do nothing
                    Log.d("ImageListFragment","process");
                }
            };

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setPostprocessor(redMeshPostprocessor)
                    .build();

            PipelineDraweeController controller = (PipelineDraweeController)
                    Fresco.newDraweeControllerBuilder()
                            .setImageRequest(request)
                            .setOldController(holder.mImageView.getController())
                                    // other setters as you need
                            .build();
            holder.mImageView.setController(controller);
//            holder.mImageView.setImageURI(uri);
            holder.mImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(mActivity, ViewPagerActivity.class);
                    intent.putExtra("position", position);
                    mActivity.startActivity(intent);

                }
            });
        }

        @Override
        public int getItemCount() {
            return mValues.size();
        }
        public void addItem(String[] items){
            mValues.addAll(Arrays.asList(items)) ;
            notifyDataSetChanged();
        }

        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if(linearLayoutManager != null){
                    boolean scrollToBottom =  linearLayoutManager.findLastVisibleItemPosition() >= adapter.getItemCount() - 2;
                    if(scrollToBottom){
                        adapter.addItem(ImageUrlUtils.getImageUrls());
                        Log.d("ImageListFragment",String.valueOf(scrollToBottom));
                    }
                }

            }
        });

**Comment by marsyu** [comment]
modify the demo https://github.com/06peng/FrescoDemo, the important part of code as below:
        public void onBindViewHolder(final ViewHolder holder, final int position) {
            FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) holder.mImageView.getLayoutParams();
            if (mRecyclerView.getLayoutManager() instanceof GridLayoutManager) {
                layoutParams.height = 200;
            } else if (mRecyclerView.getLayoutManager() instanceof StaggeredGridLayoutManager) {
                layoutParams.height = 600;
            } else {
                layoutParams.height = 800;
            }
            Uri uri = Uri.parse(mValues.get(position));
            Postprocessor redMeshPostprocessor = new BasePostprocessor() {
                @Override
                public String getName() {
                    return "redMeshPostprocessor";
                }

                @Override
                public void process(Bitmap bitmap) {
                 // do nothing
                    Log.d("ImageListFragment","process");
                }
            };

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setPostprocessor(redMeshPostprocessor)
                    .build();

            PipelineDraweeController controller = (PipelineDraweeController)
                    Fresco.newDraweeControllerBuilder()
                            .setImageRequest(request)
                            .setOldController(holder.mImageView.getController())
                                    // other setters as you need
                            .build();
            holder.mImageView.setController(controller);
//            holder.mImageView.setImageURI(uri);
            holder.mImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(mActivity, ViewPagerActivity.class);
                    intent.putExtra("position", position);
                    mActivity.startActivity(intent);

                }
            });
        }

        @Override
        public int getItemCount() {
            return mValues.size();
        }
        public void addItem(String[] items){
            mValues.addAll(Arrays.asList(items)) ;
            notifyDataSetChanged();
        }

        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if(linearLayoutManager != null){
                    boolean scrollToBottom =  linearLayoutManager.findLastVisibleItemPosition() >= adapter.getItemCount() - 2;
                    if(scrollToBottom){
                        adapter.addItem(ImageUrlUtils.getImageUrls());
                        Log.d("ImageListFragment",String.valueOf(scrollToBottom));
                    }
                }

            }
        });

**Comment by marsyu** [comment]
modify the demo https://github.com/06peng/FrescoDemo, the important part of code as below:
        public void onBindViewHolder(final ViewHolder holder, final int position) {
            FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) holder.mImageView.getLayoutParams();
            if (mRecyclerView.getLayoutManager() instanceof GridLayoutManager) {
                layoutParams.height = 200;
            } else if (mRecyclerView.getLayoutManager() instanceof StaggeredGridLayoutManager) {
                layoutParams.height = 600;
            } else {
                layoutParams.height = 800;
            }
            Uri uri = Uri.parse(mValues.get(position));
            Postprocessor redMeshPostprocessor = new BasePostprocessor() {
                @Override
                public String getName() {
                    return "redMeshPostprocessor";
                }

                @Override
                public void process(Bitmap bitmap) {
                 // do nothing
                    Log.d("ImageListFragment","process");
                }
            };

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setPostprocessor(redMeshPostprocessor)
                    .build();

            PipelineDraweeController controller = (PipelineDraweeController)
                    Fresco.newDraweeControllerBuilder()
                            .setImageRequest(request)
                            .setOldController(holder.mImageView.getController())
                                    // other setters as you need
                            .build();
            holder.mImageView.setController(controller);
//            holder.mImageView.setImageURI(uri);
            holder.mImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(mActivity, ViewPagerActivity.class);
                    intent.putExtra("position", position);
                    mActivity.startActivity(intent);

                }
            });
        }

        @Override
        public int getItemCount() {
            return mValues.size();
        }
        public void addItem(String[] items){
            mValues.addAll(Arrays.asList(items)) ;
            notifyDataSetChanged();
        }

        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if(linearLayoutManager != null){
                    boolean scrollToBottom =  linearLayoutManager.findLastVisibleItemPosition() >= adapter.getItemCount() - 2;
                    if(scrollToBottom){
                        adapter.addItem(ImageUrlUtils.getImageUrls());
                        Log.d("ImageListFragment",String.valueOf(scrollToBottom));
                    }
                }

            }
        });

**Comment by kirwan** [comment]
I'm cleaning up very old issues. If this still causes problems please comment and we can re-open.
