### ISSUE TITLE
SimpleDraweeView rounded inside scrollview overlaps ActionBar

### ISSUE THREAD

**Issue by SirKuryaki** [facebook/fresco#499]
When I put a rounded image inside an ScrollView or a ListView I get a weird behaviour: While scrolling to the bottom, the image overlaps the action bar and it keeps there when I go up.

![hrqgv](https://cloud.githubusercontent.com/assets/6807077/8912076/ab877e5e-3466-11e5-9de7-89bf52ba23bd.png)

This issue happens on a Samsung S5, but when I run it on a Nexus 4 it works perfectly.

**Comment by erikandre** [comment]
Closing as it's been 2 years without further reported cases of this. Most likely this was a device specific issue.
