### ISSUE TITLE
Error: duplicate files during packaging of APK ('lib/armeabi/libgif.so')

### ISSUE THREAD

**Issue by dominicthomas** [facebook/fresco#50]
Fresco has a dependency that clashes with another library that my project is heavily dependent on. 

Origin 1: <Project Path>/build/intermediates/exploded-aar/pl.droidsonroids.gif/android-gif-drawable/1.0.11/jni/armeabi/libgif.so

Origin 2: <Project Path>/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline/0.1.0/jni/armeabi/libgif.so

The "duplicate filed during packaging" error instructs to add this to the build.gradle file:

android {
    packagingOptions {
        exclude 'lib/armeabi/libgif.so'
    }
}

but this does not solve the issue...

Has anyone else had this issue yet? 
If so is there a way of properly excluding this as a dependency from one or the other?

**Comment by IanChilds** [comment]
It looks like you've provided the wrong path in the `exclude` line - does fixing that up do the trick?

**Comment by tyronen** [comment]
Reopen if this is still happening.

**Comment by dominicthomas** [comment]
What would be the correct path to the libgif.so file inside the fresco library?

**Comment by michalgr** [comment]
https://code.google.com/p/android/issues/detail?id=158630&q=Error%3A+duplicate+files+during+packaging+of+APK&colspec=ID+Type+Status+Owner+Summary+Stars

I am afraid gradle does not handle conflicts in so files. What we can do is hide libgif under different name or link it into something fresco-specific.

**Comment by michalgr** [comment]
Let's keep this open until fix lands in master.

**Comment by YlorD** [comment]
I've got in trouble with the same error. Hope someone could find a solution.

**Comment by tyronen** [comment]
This is now in master.
