### ISSUE TITLE
About 64bit problem.

### ISSUE THREAD

**Issue by binqiangsun** [facebook/fresco#504]
As I upgraded fresco from 0.4.0 to 0.6.0, a problem with "nativeLibraryDirectories=[/data/app/com.lukouapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libweibosdkcore.so" encounted, when I used 64bit phones. The libweibosdkcore.so is another module library. I checked the lib directory:
0.4.0: 
![image](https://cloud.githubusercontent.com/assets/8416392/8979327/7ec5798a-36db-11e5-8bae-b4015cb1b1c9.png)

0.6.0: 
![image](https://cloud.githubusercontent.com/assets/8416392/8979342/9680a70c-36db-11e5-8594-d632d2f729a9.png)

I doubt that my problem is caused by 0.6.0 added some 64bit files, as I rolled back to 0.4.0 version is ok. why did fresco add some 64 bit library?

**Comment by michalgr** [comment]
There is no libweibosdkcore.so in arm64-v8a directory. When your app is installed Android unpacks libs from the most appropriate directory and those libs can be loaded at run time. In case of 64bit devices it selects arm64-v8a (or x86_64) and if some of the libraries is not there then you won't be able to load it.

64bit devices, however, should be able to run 32bit libs. Just make sure that arm64-v8a and x86_64 are not included in your apk. See here: https://github.com/facebook/fresco/issues/458
