### ISSUE TITLE
SimpleDraweeView  bad url  reload

### ISSUE THREAD

**Issue by ytqandrew** [facebook/fresco#505]
hi，i use SimpleDraweeView  in xml  ,if load bad img url for server , later fix the  img url  ,SimpleDraweeView  alaways load local cache ,it doesnt  reload new  url     (new url and  old  the same)

**Comment by michalgr** [comment]
Call `Fresco.getImagePipeline().evictFromCache(uri_to_your_image)` before you reload the image.
