### ISSUE TITLE
Clear Image Cache

### ISSUE THREAD

**Issue by LinkOut** [facebook/fresco#507]
http://frescolib.org/docs/caching.html
Clearing the cache

ImagePipeline imagePipeline = Fresco.getImagePipeline();
imagePipeline.clearMemoryCaches();
imagePipeline.clearDiskCaches();

// combines above two lines
imagePipeline.clearCaches();

But clearMemoryCaches && clearDiskCaches are not methods of ImagePipeline 

So, how to do that? Thanks!

**Comment by michalgr** [comment]
https://github.com/facebook/fresco/blob/v0.6.0/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipeline.java

Please use newest version of Fresco: 0.6.0
