### ISSUE TITLE
Fresco support OSS?

### ISSUE THREAD

**Issue by substarry** [facebook/fresco#508]
My pictures are save in OSS, I want to use Fresco to show the pictures, and i know the OSS uri , does fresco support OSS uri ?

**Comment by plamenko** [comment]
What's OSS?

**Comment by substarry** [comment]
It's like Amazon S3，a cloud storage service. It give me a url like "s3://xxxx.xxx.jpg" or "oss://xxxx.xxx.jpg" to download picture. So , I need to modify the network layer  in fresco to download my picture. I have read fresco document, I need subclass NetworkFetcher. It's right?

**Comment by CaiHuan** [comment]
support~

**Comment by substarry** [comment]
I've got it. Thank you.
