### ISSUE TITLE
Use one builder to build multiple Hierarchys....

### ISSUE THREAD

**Issue by sirvon** [facebook/fresco#51]
is this code doable or encouraged or is there a better way....
I'm attempting to put iconFontDrawables in the placeholder of multiple drawees Views.

So, I'm using one builder to set multiple hierarchy is this cool? or nah....

```java
GenericDraweeHierarchyBuilder builder =
                new GenericDraweeHierarchyBuilder(getResources());

        GenericDraweeHierarchy radioPauseButtonHierarchy = builder
                .setFadeDuration(300)
                .setPlaceholderImage(iconicFontDrawablePause)
                .build();

        GenericDraweeHierarchy radioPlayButtonHierarchy = builder
                .setFadeDuration(300)
                .setPlaceholderImage(iconicFontDrawablePlay)
                .build();

        GenericDraweeHierarchy radioBuyNowButtonHierarchy = builder
                .setFadeDuration(300)
                .setPlaceholderImage(iconicFontDrawableBuyNow)
                .build();

 buyNowButton.setHierarchy(radioBuyNowButtonHierarchy);
 playButton.setHierarchy(radioPlayButtonHierarchy);
 pauseButton.setHierarchy(radioPauseButtonHierarchy);
```

**Comment by plamenko** [comment]
Yeah, using the same builder is fine, but you need to be careful. The builder is not reset after build, so all previously set options remain.

You can either do:

    GenericDraweeHierarchy hierarchy = builder
      .reset()    // <=======
      .setXxx()
      ...
      .build()

OR, you need to make sure that you don't use the same drawable instances for multiple hierarchies. If 

In short, if you are reusing builder, doing `reset()` at before setting options is the safest option.
