### ISSUE TITLE
Write to disk cache conditions ?

### ISSUE THREAD

**Issue by chunyong1991** [facebook/fresco#510]
It seems like Fresco only write files with image extension (eg: .png, .jpg, .bmp) to disk cache.
Is there any option to modify this to allow image caching for other extensions ?

**Comment by plamenko** [comment]
Can you be more specific? I.e. what extensions would you like to support?
We only deal with the image formats we recognize. We are aware that the extension is not an ideal indicator of the file format, but it serves well in vast majority of cases.

**Comment by chunyong1991** [comment]
Because currently our system pass in parameters to resize the image on our server-side, which will make the link of the image looks something like this : 

www.someweb.com/image/pic01.jpg&width=100&height=200

As what I observed, all other images with extensions like .jpg and .png able to be cached well in disk cache, but these images with links above will not cache, so is there any option to modify this to allow image caching for other extensions ?

**Comment by michalgr** [comment]
Fresco should write all remote images to disk cache. Can you provide example of a valid url that is not cached ? I'll try to reproduce and debug.

**Comment by plamenko** [comment]
http://www.keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg?width=100&height=200

**Comment by michalgr** [comment]
@plamenko your image loads successfully

> 08-12 09:11:14.791  6690  6690 V unknown:AbstractDraweeController: controller 28ebe0eb 0 -> 1: initialize
08-12 09:11:14.791  6690  6690 V unknown:AbstractDraweeController: controller 28ebe0eb 1: onDetach
08-12 09:11:14.791  6690  6690 V unknown:AbstractDraweeController: controller 28ebe0eb 1: setHierarchy: null
08-12 09:11:14.791  6690  6690 V unknown:AbstractDraweeController: controller 28ebe0eb 1: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@2bb88e48
08-12 09:11:14.791  6690  6690 V unknown:AbstractDraweeController: controller 28ebe0eb 1: onAttach: request needs submit
08-12 09:11:14.791  6690  6690 V unknown:PipelineDraweeController: controller 28ebe0eb: getDataSource
08-12 09:11:14.791  6690  6690 V unknown:RequestLoggingListener: time 11201791: onRequestSubmit: {requestId: 1, callerContext: null, isPrefetch: false}
08-12 09:11:14.792  6690  6690 V unknown:RequestLoggingListener: time 11201791: onProducerStart: {requestId: 1, producer: BitmapMemoryCacheGetProducer}
08-12 09:11:14.792  6690  6690 V unknown:RequestLoggingListener: time 11201792: onProducerFinishWithSuccess: {requestId: 1, producer: BitmapMemoryCacheGetProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
08-12 09:11:14.792  6690  6690 V unknown:RequestLoggingListener: time 11201792: onProducerStart: {requestId: 1, producer: BackgroundThreadHandoffProducer}
08-12 09:11:14.792  6690  6690 V unknown:AbstractDraweeController: controller 28ebe0eb 1: submitRequest: dataSource: 36e95857
08-12 09:11:14.792  6690  6734 V unknown:RequestLoggingListener: time 11201792: onProducerFinishWithSuccess: {requestId: 1, producer: BackgroundThreadHandoffProducer, elapsedTime: 0 ms, extraMap: null}
08-12 09:11:14.792  6690  6734 V unknown:RequestLoggingListener: time 11201792: onProducerStart: {requestId: 1, producer: BitmapMemoryCacheProducer}
08-12 09:11:14.792  6690  6734 V unknown:RequestLoggingListener: time 11201792: onProducerFinishWithSuccess: {requestId: 1, producer: BitmapMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
08-12 09:11:14.792  6690  6734 V unknown:RequestLoggingListener: time 11201792: onProducerStart: {requestId: 1, producer: EncodedMemoryCacheProducer}
08-12 09:11:14.792  6690  6734 V unknown:RequestLoggingListener: time 11201792: onProducerFinishWithSuccess: {requestId: 1, producer: EncodedMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
08-12 09:11:14.792  6690  6734 V unknown:RequestLoggingListener: time 11201792: onProducerStart: {requestId: 1, producer: DiskCacheProducer}
08-12 09:11:14.792  6690  6735 V unknown:BufferedDiskCache: Did not find image for http://www.keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg?width=100&height=100 in staging area
08-12 09:11:14.793  6690  6735 V unknown:BufferedDiskCache: Disk cache read for http://www.keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg?width=100&height=100
08-12 09:11:14.793  6690  6735 V unknown:BufferedDiskCache: Disk cache miss for http://www.keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg?width=100&height=100
08-12 09:11:14.793  6690  6735 V unknown:RequestLoggingListener: time 11201793: onProducerFinishWithSuccess: {requestId: 1, producer: DiskCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
08-12 09:11:14.793  6690  6735 V unknown:RequestLoggingListener: time 11201793: onProducerStart: {requestId: 1, producer: NetworkFetchProducer}
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 1024); Free = (10, 2095104)
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (22601f19, 1024)
08-12 09:11:15.144  6690  7358 V unknown:GenericByteArrayPool: Used = (1, 16384); Free = (0, 0)
08-12 09:11:15.144  6690  7358 V unknown:GenericByteArrayPool: get (reuse) (object, size) = (12bd0bde, 16384)
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 3072); Free = (9, 2093056)
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (1fcfe1bf, 2048)
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (22601f19, 1024)
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 2048); Free = (10, 2094080)
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 6144); Free = (9, 2089984)
08-12 09:11:15.144  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (3b05808c, 4096)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (1fcfe1bf, 2048)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 4096); Free = (10, 2092032)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 12288); Free = (9, 2083840)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (6ca93d5, 8192)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (3b05808c, 4096)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 8192); Free = (10, 2087936)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 24576); Free = (9, 2071552)
08-12 09:11:15.145  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (90a07ea, 16384)
08-12 09:11:15.146  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (6ca93d5, 8192)
08-12 09:11:15.146  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 16384); Free = (10, 2079744)
08-12 09:11:15.149  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 49152); Free = (9, 2046976)
08-12 09:11:15.149  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (30aadadb, 32768)
08-12 09:11:15.149  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (90a07ea, 16384)
08-12 09:11:15.149  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 32768); Free = (10, 2063360)
08-12 09:11:15.153  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 98304); Free = (9, 1997824)
08-12 09:11:15.154  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (27d01978, 65536)
08-12 09:11:15.154  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (30aadadb, 32768)
08-12 09:11:15.154  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 65536); Free = (10, 2030592)
08-12 09:11:15.155  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 196608); Free = (9, 1899520)
08-12 09:11:15.155  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (62d9851, 131072)
08-12 09:11:15.155  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (27d01978, 65536)
08-12 09:11:15.155  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 131072); Free = (10, 1965056)
08-12 09:11:15.160  6690  7358 V unknown:NativeMemoryChunkPool: Used = (2, 393216); Free = (9, 1702912)
08-12 09:11:15.160  6690  7358 V unknown:NativeMemoryChunkPool: get (reuse) (object, size) = (2578b8b6, 262144)
08-12 09:11:15.160  6690  7358 V unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (62d9851, 131072)
08-12 09:11:15.160  6690  7358 V unknown:NativeMemoryChunkPool: Used = (1, 262144); Free = (10, 1833984)
08-12 09:11:15.161  6690  7358 V unknown:RequestLoggingListener: time 11202161: onProducerFinishWithSuccess: {requestId: 1, producer: NetworkFetchProducer, elapsedTime: 368 ms, extraMap: null}
08-12 09:11:15.162  6690  7358 I unknown:TiffUtil: Unsupported orientation
08-12 09:11:15.162  6690  7358 V unknown:StagingArea: Count = 1
08-12 09:11:15.162  6690  6742 V unknown:BufferedDiskCache: About to write to disk-cache for key http://www.keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg?width=100&height=100
08-12 09:11:15.162  6690  6734 V unknown:RequestLoggingListener: time 11202162: onProducerStart: {requestId: 1, producer: DecodeProducer}
08-12 09:11:15.162  6690  7358 V unknown:GenericByteArrayPool: release (reuse) (object, size) = (12bd0bde, 16384)
08-12 09:11:15.162  6690  7358 V unknown:GenericByteArrayPool: Used = (0, 0); Free = (1, 16384)
08-12 09:11:15.163  6690  6734 V unknown:BitmapPool: Used = (1, 960000); Free = (0, 0)
08-12 09:11:15.163  6690  6734 V unknown:BitmapPool: get (alloc) (object, size) = (32c122f3, 240000)
08-12 09:11:15.163  6690  6742 V unknown:GenericByteArrayPool: Used = (1, 16384); Free = (0, 0)
08-12 09:11:15.163  6690  6742 V unknown:GenericByteArrayPool: get (reuse) (object, size) = (12bd0bde, 16384)
08-12 09:11:15.163  6690  6742 V unknown:GenericByteArrayPool: release (reuse) (object, size) = (12bd0bde, 16384)
08-12 09:11:15.163  6690  6742 V unknown:GenericByteArrayPool: Used = (0, 0); Free = (1, 16384)
08-12 09:11:15.163  6690  6742 V unknown:BufferedDiskCache: Successful disk-cache write for key http://www.keenthemes.com/preview/metronic/theme/assets/global/plugins/jcrop/demos/demo_files/image1.jpg?width=100&height=100
08-12 09:11:15.163  6690  6742 V unknown:StagingArea: Count = 0
08-12 09:11:15.169  6690  6734 V unknown:RequestLoggingListener: time 11202169: onProducerFinishWithSuccess: {requestId: 1, producer: DecodeProducer, elapsedTime: 7 ms, extraMap: {hasGoodQuality=true, queueTime=0, bitmapSize=600x400, isFinal=true}}
08-12 09:11:15.169  6690  6734 V unknown:RequestLoggingListener: time 11202169: onRequestSuccess: {requestId: 1, elapsedTime: 378 ms}
08-12 09:11:15.184  6690  6690 V unknown:AbstractDraweeController: controller 28ebe0eb 1: set_final_result @ onNewResult: image: CloseableReference 2fd41bb0

**Comment by chunyong1991** [comment]
@michalgr Is your image able to load from disk cache after restart the application ? Or is there any cache -clearing mechanism in fresco upon exit ?

**Comment by michalgr** [comment]
It is able to load from disk. Can you have a look at #530 and verify whether this is the same issue ?

**Comment by tyronen** [comment]
Closing as no repro. File a new issue if you have a definitely reproducible URL.
