### ISSUE TITLE
Allow image loading to be paused on scroll

### ISSUE THREAD

**Issue by JiangDaYa0** [facebook/fresco#512]
I want to pause loading on scoll

**Comment by plamenko** [comment]
Can you give us more context on why would you want to do that?

**Comment by JiangDaYa0** [comment]
save 4G flow.

**Comment by plamenko** [comment]
By "flow" do you mean "data usage"?

**Comment by JiangDaYa0** [comment]
yup！

**Comment by droidekas** [comment]
I would be interested in this feature too.Something like how [UIL does it] (https://github.com/nostra13/Android-Universal-Image-Loader/blob/master/library/src/main/java/com/nostra13/universalimageloader/core/ImageLoader.java#L751).

**Comment by michalgr** [comment]
I think the easiest way to achieve this at the moment would be to add request queueing in ThreadHandoffProducer.

Right now Fresco first looks up if the image is available immediately in Bitmap cache. If it misses then execution gets to ThreadHandoffProducer which moves execution of the image request from UI thread to background thread. We could have additional check there to see if image loading is paused or not and depending on that resume request immediately or queue it for execution later.

I am happy to provide more directions.

https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/ThreadHandoffProducer.java

**Comment by droidekas** [comment]
Sorry for the late reply.But I think Fresco also determines if a view is visible in order to download an image. Can you point me to that piece of the source code?

**Comment by IanChilds** [comment]
This is the code that ends up kicking off the downloads (and cancelling them): https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/view/DraweeView.java#L101:L124

**Comment by droidekas** [comment]
Hi,
I finally got to this task now and would need some help if you could provide me a bit of detail.

The required behaviour is:

When a Recycler/List View is being flung you want to pause the image loading
  The image-requests obtained in this duration should be queued with a lesser priority

When a RecyclerView is Settling/Idle ,the image loading would be resumed:
   The image-requests obtained now would have to be given priority in the request queue.

Current behaviour is:the requests get queued unconditionally,which  leads to a bad UX.

Any thoughts on how this behaviour could be achieved?

**Comment by droidekas** [comment]
bump

**Comment by droidekas** [comment]
Just realized that this feature has been implemented in c3253ba2367fd3c956e2877a9aa528e66092836c

**Comment by oprisnik** [comment]
I'm closing this since this should be possible with `resume()` and `pause()` as stated above.
