### ISSUE TITLE
about fresco memory

### ISSUE THREAD

**Issue by dongliang0108** [facebook/fresco#514]
I use fresco loaded  network image by ListView, the network image is not compressed, so when I slide when large memory footprint, if what this page to slide the memory will take to around 200M, to how to solve this problem, thank you.

**Comment by plamenko** [comment]
What are the dimensions of the image? What do you mean by "the network image is not compressed"? Are you loading animated images?

**Comment by nimengbo** [comment]
I meet same problem，in my listview I load images ，one pic size is 1080*1080，I scroll and load many picture，the memory will around 200m ，the htc802 in Android4.2，memory will over 350m and oom！

**Comment by nimengbo** [comment]
and A startActivity B ,B use fresco load image about 1080*1080 ,then finish B , do not in liferecyle ondestory , then startActivity B again and load image again , recycle this options , memory only add but not relase memory in Android 4.x

**Comment by plamenko** [comment]
Are you sure that you don't have multiple instances of activity B in memory?

**Comment by nimengbo** [comment]
@plamenko My activityB launch mode is 'singleTask'

**Comment by nimengbo** [comment]
@plamenko My activityB launch mode is 'singleTask'

**Comment by nimengbo** [comment]
@plamenko My activityB launch mode is 'singleTask'

**Comment by nimengbo** [comment]
@plamenko My activityB launch mode is 'singleTask'

**Comment by plamenko** [comment]
@nimengbo, perhaps the best way of telling what happens is to take a heap dump when your memory usage gets suspiciously big and then analyze that. There are various ways to cause a memory leak, `singleTask` being used or not.

Please see: https://developer.android.com/tools/debugging/debugging-memory.html

**Comment by tyronen** [comment]
We strongly recommend against using uncompressed network images. Very large images can OOM; you should [resize](http://frescolib.org/docs/resizing-rotating.html#_) instead.
