### ISSUE TITLE
Cant open image which name contains“%”

### ISSUE THREAD

**Issue by somatezyc** [facebook/fresco#515]
2XVS{40M0@T%(55Q)GX1SQT.jpg
49b2c0ad05f042%736e5dcad6e233ff76.jpg

Log:
 E/JHEAD﹕ can't open '/storage/emulated/0/2XVS{40M0@T�5Q)GX1SQT.jpg'
E/JHEAD﹕ can't open '/storage/emulated/0/49b2c0ad05f042s6e5dcad6e233ff76.jpg'

**Comment by plamenko** [comment]
I think this is due to Uri.parse. Perhaps you should escape the string before passing it to Uri.parse.
How do you create an uri from such a string? Can you paste the code snippet?

**Comment by somatezyc** [comment]
Thank you very much!
