### ISSUE TITLE
About DiskCacheConfig

### ISSUE THREAD

**Issue by nimengbo** [facebook/fresco#518]
The question is i do used the DiskCacheConfig,can the Fresco clear the cache in disk automaticlly or should i do this ? if so( i do this job)  when?

**Comment by nimengbo** [comment]
DiskCacheConfig diskCacheConfig = DiskCacheConfig.newBuilder()
                .setMaxCacheSizeOnLowDiskSpace(50 * 1024 * 1024)
                .setMaxCacheSize(500 * 1024 * 1024)
                .build();

Caused by: java.lang.NullPointerException

**Comment by michalgr** [comment]
Fresco will evict old entries from disk cache to free space for new images automatically before creating new file, you don't have to do anything.

Your NullPointerException comes from these lines: https://github.com/facebook/fresco/blob/96d74f385b297f364db1f719dd6ee61fc380d0d4/imagepipeline/src/main/java/com/facebook/cache/disk/DiskCacheConfig.java#L42-L43 - you have to set base directory name (prefix of cache directory name) and base directory path suplier (supplier of File object represetning directory where cache directory should be created). Use this as a reference: https://github.com/facebook/fresco/blob/e58561de5b3ca613d2647d4d8cc55c344d5cc579/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipelineConfig.java#L159-L166
