### ISSUE TITLE
Error:Execution failed for task ':imagepipeline:cloneWebp'. > org.eclipse.jgit.api.errors.TransportException: https://chromium.googlesource.com/webm/libwebp: User Is Over Quota

### ISSUE THREAD

**Issue by junjie0324** [facebook/fresco#52]
when i run sample , i got message:

Error:Execution failed for task ':imagepipeline:cloneWebp'.
> org.eclipse.jgit.api.errors.TransportException: https://chromium.googlesource.com/webm/libwebp: User Is Over Quota

so,what can i do

**Comment by MarkMjw** [comment]
maybe you unable to access to https://chromium.googlesource.com/webm/libwebp, try vpn?

**Comment by tyronen** [comment]
Unfortunately Google imposes a per-IP quota on accessing its servers. Here is a possible workaround: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/ITllccBdd5I

**Comment by junjie0324** [comment]
@MarkMjw i can access https://chromium.googlesource.com/webm/libwebp  ,thanks

**Comment by junjie0324** [comment]
@tyronen thanks for your help , now it's ok. i just try again and again ,at last it runs normal.thanks guys.
