### ISSUE TITLE
Deciding rotation direction of loading animation ?

### ISSUE THREAD

**Issue by deibid** [facebook/fresco#523]
I think it would be great to be able to decide if you want clock wise or counter clock wise rotation of the loading drawable

**Comment by plamenko** [comment]
Just a note: we do welcome external contributions :)

**Comment by IanChilds** [comment]
AutoRotateDrawable already has this as an option: https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/drawable/AutoRotateDrawable.java#L30
