### ISSUE TITLE
Export fresco aar in my library aar to be used in third party apps.

### ISSUE THREAD

**Issue by NabilNoaman** [facebook/fresco#525]
Hi All ,

Thanks for great library .

I am using fresco inside my own library module then export library as aar which used by third party apps.

My problems are : 

- No resource identifier found for attribute ' **placeholderImage** '  in package 'com.example.test'

- No resource identifier found for attribute ' **failureImage** '  in package 'com.example.test'

Layout : 

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"    --------------------------------------------
    android:layout_width="match_parent"
    android:layout_height="44dp"
    android:orientation="horizontal"
    android:padding="5dip" >

    <!--  ListRow Left side POI Category Thumbnail image -->
    <LinearLayout android:id="@+id/category_thumbnail"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:padding="10dip"
        android:layout_alignParentLeft="true"
        android:background="@drawable/image_bg"
        android:layout_marginRight="5dip">

        <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/poi_category_image"
            android:layout_width="23dip"
            android:layout_height="23dip"
            fresco:placeholderImage="@drawable/default_category_placeholder"  ---------------------------
            fresco:failureImage="@drawable/default_category"  -------------------------------------------
         />

    </LinearLayout>

</RelativeLayout>
```

- The way i am using fresco in my library : 
```
compile 'com.facebook.fresco:fresco:0.6.0+'
```
- The way I am using mylibrary.aar in third party app (inside libs).
```
compile 'com.mylibrary:mylibrary:1.0@aar'
```

**Comment by michalgr** [comment]
Does it work if you add `compile 'com.facebook.fresco:fresco:0.6.0+'` to third party app gradle file ?

**Comment by NabilNoaman** [comment]
Thanks Michal for your help , yes the error disappear when I add  
``` compile 'com.facebook.fresco:fresco:0.6.0+'  ``` to third party app gradle file.

But , I want to let developers who will use my library to depend only on the local mylibrary.aar  without adding its dependencies to their apps.

So How can i solve this issue ?

**Comment by michalgr** [comment]
Do you use your lib as a prebuilt aar ? If so, you'll also have to check in fresco prebuilt aars, as well as aars/jars for all of fresco's dependencies.

When you build a library gradle does not put dependencies inside your's library aar. Instead it will try to recursively bundle all dependencies together with your app. This is achieved either by analyzing associated pom.xml (1) or available projects (2).

Fresco is a good example here. Fresco is not a single aar, as you can see here: http://search.maven.org/#search%7Cga%7C1%7Cfresco.

(1) When you depend on fresco you depend on fresco.aar, but also on all aars and jars listed in this pom file: https://repo1.maven.org/maven2/com/facebook/fresco/fresco/0.6.1/fresco-0.6.1.pom. If you fetch your dependency from maven then gradle will recursively traverse pom files of all dependencies and fetch all aars/jars for you. In the end, when compiling project depending on Fresco, gradle will also bundle fbcore, drawee, imagepipeline, nineoldandroids, bolts and support library (and possibly more).

(2) Gradle can also automatically detect dependencies across your own projects. This is a `build.gradle` file for one of fresco sample apps: https://github.com/facebook/fresco/blob/master/samples/demo/build.gradle. When gradle sees
> compile project(':drawee-backends:drawee-pipeline')

it knows you depend on other project and it will make sure that all dependencies of `:drawee-backends:drawee-pipeline` end up in the app's apk.

Now, back to prebuilt aars/jars. With prebuilt jars you don't give gradle any clue what the dependencies are and you have to deal with them on your own. I do not know if it is possible to force gradle to put all library dependencies in the library's aar. Maybe it is, but this is not the standard way of dealing with deps. It seems that most reasonable thing to do is to use maven to distribute your library. Another option is to tell gradle it should depend on fresco.

**Comment by NabilNoaman** [comment]
Thanks Michal so much , I solved my issue by creating pom file for my library with all it dependencies and deployed arr with pom.xml

One of nice commands which helped me is ```./gradlew app:dependencies```

**Comment by Fishoo0** [comment]
> Thanks Michal so much , I solved my issue by creating pom file for my library with all it dependencies and deployed arr with pom.xml
> 
> One of nice commands which helped me is `./gradlew app:dependencies`

Hi, can you share your configuration files? I've run into the same mess, thx
