### ISSUE TITLE
Is there a way to set place holder image scale type in code?

### ISSUE THREAD

**Issue by KashanDanish** [facebook/fresco#527]

**Comment by chunyong1991** [comment]
GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(getResources())
                .setActualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP)
                .setPlaceholderImage(getResources().getDrawable(R.color.transparent))
                .build();
mySimpleDraweeView.setHierarchy(hierarchy);
mySimpleDraweeView.setImageUri(yourImageUri);

Voila!

**Comment by KashanDanish** [comment]
@chunyong1991 Where did you set place holder image's scale type?

**Comment by michalgr** [comment]
Use this: https://github.com/facebook/fresco/blob/920539d9443bc3979fbd838ecd64d3356b735ee0/drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchyBuilder.java#L156-L158

**Comment by KashanDanish** [comment]
Right, thanks just one issue:
GenericHierarchyBuilder.setPlaceholderImage can take second attribute but hierarchy.setPlaceholderImage does not take scaleType as second attribute. I need to change scale type of images on the run.

**Comment by plamenko** [comment]
@KashanDanish , you could make a pull request :)

**Comment by IanChilds** [comment]
This will be available in the next version of Fresco.
