### ISSUE TITLE
How to get  the fresco local  diskcache file 

### ISSUE THREAD

**Issue by chenhf1990** [facebook/fresco#531]
I just call the Fresco.initialize() ,the other is the default setting,I'd like to get the cache file, and let the user can choose whether to remove it, how to acquire the local cache file?

**Comment by michalgr** [comment]
Have a look at `evictFromDiskCache` and `clearDiskCaches` methods in `ImagePipeline` (https://github.com/facebook/fresco/blob/e58561de5b3ca613d2647d4d8cc55c344d5cc579/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipeline.java)
