### ISSUE TITLE
Options to disable auto-cancel image loading when user leave the view

### ISSUE THREAD

**Issue by chunyong1991** [facebook/fresco#532]
Good day, 

I have a long list view that display a lot of images, I've found out that my images which are not loaded will stop loading as users scrolling down the list view, users will have to wait for them to load again when he/she scroll back to that position, this could causing some issues for those users who do not own high speed internet / using mobile data.

So I would like to ask is there anywhere to toggle the auto-cancel image loading feature when SimpleDraweeView is out of the active view ? 

Any kind of help is much appreciated, thank you.

**Comment by michalgr** [comment]
Currently there is no way in which you can prevent DraweeView from canceling the request once image is off the screen. You can work around it by submitting prefetch request at the same time when you set image uri to drawee view: (https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipeline.java#L241): this will prevent image pipeline from canceling network fetch, but also will increase number of requests queueing for network fetch.

Appropriate thing to do here would be to prevent network fetch cancellation if a http request was already passed to the network stack. In the case of default network fetch implementation (not OkHttp based) it should be as easy as adding additional atomic boolean somewhere in `HttpUrlConnectionNetworkFetcher.fetch` method.

**Comment by chunyong1991** [comment]
@michalgr Very helpful suggestion, thank you.

**Comment by chunyong1991** [comment]
@michalgr Hi Gregorczyk, I've implemented the workaround as you suggested, it works fine, but one thing, is there any chances that I can modify the sequence of the network queue from FIFO to LIFO ?

**Comment by chunyong1991** [comment]
@michalgr  Sorry for keep tagging you but much thanks if you could give me an answer to my question above :)

**Comment by IanChilds** [comment]
You can write your own implementation of `NetworkFetcher` that uses a LIFO executor rather than a FIFO executor. 

If you are using OkHttpNetworkFetcher, then I think you can just pass in an OkHttpClient that does what you want.
