### ISSUE TITLE
Broken gif can't load

### ISSUE THREAD

**Issue by s1rius** [facebook/fresco#533]
fresco 0.6.1
android 5.1
image url  http://7vzseb.com1.z0.glb.clouddn.com/12nuDeDV4xU3yE.gif
The gif image can't show animation or display static image. it is broken, I open it on Photoshop CS6 and get an error, maybe ```fatal error C1004``` or ```EOFException```, I don't know. 
It displays well with [android-gif-drawable](https://github.com/koral--/android-gif-drawable/).

**Comment by YuhuihuiYang** [comment]
hello ,My program also encountered the same problem,Will you solve it？

**Comment by s1rius** [comment]
Not yet.
