### ISSUE TITLE
Need round bitmap for imageview

### ISSUE THREAD

**Issue by saurabh0802chd** [facebook/fresco#534]
I need round bitmap to be set to imageview as I cannot use custom view(SimpleDraweeView) in appwidget. Using below code for getting bitmap

// To get bitmap using Fresco
ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri)).setProgressiveRenderingEnabled(true).build();
ImagePipeline imagePipeline = Fresco.getImagePipeline();
DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest,mContext);
dataSource.subscribe(new BaseBitmapDataSubscriber() {
	@Override
	public void onNewResultImpl(@Nullable Bitmap bitmap) {
		//getting square bitmap here but need round bitmap
		remoteViews.setImageViewBitmap(R.id.imageView,bitmap);
	}
	@Override
	public void onFailureImpl(DataSource dataSource) {
		
	}
}, CallerThreadExecutor.getInstance());

Thanks in advance.

**Comment by michalgr** [comment]
Fresco does not round bitmaps. Instead it uses RoundedButmapDrawable to draw it as rounded one to Canvas. If you need a rounded bitmap you have to create one on your own. You can use Canvas and code similar to this one: https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/drawable/RoundedBitmapDrawable.java#L157-L175
