### ISSUE TITLE
Listview scrolling is not smooth

### ISSUE THREAD

**Issue by saurabh0802chd** [facebook/fresco#535]
My app has a listview which displays all images from phone. 
If user scrolls the view fast  it seems to have jerks in between. As scrolling pause for a while to load images on the screen.

Please let me know if there is any API for pause and resume scrolling or any other suggestion to make scroll smooth.

**Comment by kexuejin** [comment]
me too,if diaplays images from local ,the listview is block when scroll.

**Comment by michalgr** [comment]
@kexuejin : do I understand correctly that the issue happens only for local images, not for the ones that are downloaded ?

Also: does it happen on all versions of Android or is it Lollipop-only issue ?

**Comment by yychai** [comment]
me too, even my local image`s size is very small, it`s also block when scroll.

**Comment by michalgr** [comment]
Do you use LeakCanary? Let me know if this might be related to #536

@saurabh0802chd @kexuejin @yychai : I would love to help here but I need more details. For start I need to know:
- sizes of decoded images and sizes of drawee views used to display them
- do you use resizing or downsampling (http://frescolib.org/docs/resizing-rotating.html)
- android version you use to reproduce this
- number of images on screen

**Comment by kexuejin** [comment]
1.I load photo from sdcard ,it's clude camera photo,so maybe 3m-5m per image.
2.no
3.Android 5.1
4.load more then 10+ on screen,total image 100+
5.i change to glide has no problem.

**Comment by michalgr** [comment]
I see. Without resizing or downsampling Fresco will decode huge bitmap and that will cause gc issues. Specifying resize options will most likely solve the issue.

**Comment by kexuejin** [comment]
I set the view width and height ，fresco can not auto resize view size?

**Comment by michalgr** [comment]
No, at least not yet.

**Comment by tyronen** [comment]
Resizing should work. Use downsampling if PNGs.
