### ISSUE TITLE
Extreamly slow gc leads to no reponse of UI on Android 5.+, Fresco 0.6.1

### ISSUE THREAD

**Issue by bluef** [facebook/fresco#536]
We have experienced such problem for long time, here's some logs:

08-12 15:21:46.041  16379-16524/com.nice.main I/art﹕ Explicit concurrent mark sweep GC freed 463650(24MB) AllocSpace objects, 186(22MB) LOS objects, 17% free, 77MB/93MB, paused 1.466ms total 299.088ms
08-12 15:22:07.001  16379-16524/com.nice.main I/art﹕ Explicit concurrent mark sweep GC freed 223894(15MB) AllocSpace objects, 66(8MB) LOS objects, 10% free, 69MB/77MB, paused 970us total 98.934ms
08-12 15:23:34.991  30142-30257/com.nice.main I/art﹕ Explicit concurrent mark sweep GC freed 640847(43MB) AllocSpace objects, 323(23MB) LOS objects, 19% free, 67MB/83MB, paused 1.336ms total 321.995ms
08-12 15:23:43.891  30142-30257/com.nice.main I/art﹕ Explicit concurrent mark sweep GC freed 47899(2MB) AllocSpace objects, 17(1912KB) LOS objects, 20% free, 63MB/79MB, paused 1.323ms total 123.515ms

We're an image sharing and social app called nice, and we display a lot of images in our app. Fresco works perfect on Android 4.+, but as the market share of Android 5.+ growing, we're looking for the solution of the issue descrbed above. Just let us know if you guys need more detail for investigating problem.

Thanks!

**Comment by michalgr** [comment]
How many different sizes of Bitmaps do your app use ? If there are not many we can use bitmap pool to trade allocations for memory consumption. I'll tell you how to configure it if pooling is applicable.

**Comment by bluef** [comment]
@michalgr there're no more than 8 different sizes, from screen wide to 100x100

**Comment by michalgr** [comment]
Ok, let's tray this then:

1. Create PoolParams for bitmap pool (https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/PoolParams.java). Default PoolParams for bitmap pool is created here: https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/DefaultBitmapPoolParams.java#L48-L54 - you can use this code for reference. Soft cap is number of bytes that pool will try not to exceed (after hitting this limit bitmap pool will start dropping pooled bitmaps when a new one has to be allocated), hard cap is number of bytes that will not be exceeded ever (after hitting that limit bitmap allocations will fail). You can set soft = hard = max number of MB you want to use for bitmaps. Make this bigger than 1/4 of your heap size, because 1/4 is what bitmap cache keeps alive.
<p> Now the important part - you need to specify bucket sizes (the 3rd param). For each bitmap size you need to specify how many additional bitmaps you want to keep alive for the purpose of future reusing. This is done by providing SparseIntArray that maps bitmap size (number of pixels) to number of extra instances. This is app specific and you should experiment with few configurations.
2. Create PoolFactory and pass PoolParams from 1) to its constructor
3. Use PoolFactory from 2) to create ImagePipelineConfig http://frescolib.org/docs/configure-image-pipeline.html
4. Initialize Fresco

I hope this helps reduce gcs. Let me know how it goes, I am happy to explain things in more details.

**Comment by bluef** [comment]
it looks like pooling is not helping. Still, everytime explicit gc starts, UI freezes for around 1 sec... Background gc works like a charm.

I made the buckets to a SparseIntArray initiated like new SparseIntArray(2250000) .

And I setup the bitmap pool stat tracker and only setBasePool, onAlloc and onFree actions were logged. Is it normal or I just didn't make the bitmap pooling parameter right?

**Comment by michalgr** [comment]
You need to populate SparseIntArray with appropriate entries. The argument passed to constructor does not do that. This is example of code that configures another pool: https://github.com/facebook/fresco/blob/96d74f385b297f364db1f719dd6ee61fc380d0d4/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/DefaultByteArrayPoolParams.java#L41-L42 - if you used the same SparseIntArray then bitmap pool would store up to `DEFAULT_BUCKET_SIZE` bitmaps, each one having `DEFAULT_IO_BUFFER_SIZE` pixels. I hope this example helps.

**Comment by michalgr** [comment]
By the way, do you observe scroll perf issues when using Fresco to load local or network photos ? And what device do you use to reproduce ?

**Comment by bluef** [comment]
We load local photo with ImageRequest with resize option which helps improving memory and scrolling performance. Fresco will perform badly if load those giant photo with millions of pixels directly without resizing, consuming more memory and triggering gc much more often.

**Comment by bluef** [comment]
```Java
    public static PoolParams get() {
        SparseIntArray defaultBuckets = new SparseIntArray();
        defaultBuckets.put(2250000, 3);
        defaultBuckets.put(1638400, 1);
        defaultBuckets.put(679680, 5);
        defaultBuckets.put(19600, 5);
        defaultBuckets.put(409600, 1);

        return new PoolParams(
                getMaxSizeHardCap(),
                getMaxSizeHardCap(),
                defaultBuckets
        );
    }
```
Did I make it right? Still I couldn't find onValueReuse or any other action except onAlloc and onFree.

Here're the log
```
08-13 14:12:18.911  10417-11076/com.nice.main E/PoolStatsTracker﹕ onAlloc 409600
08-13 14:12:18.921  10417-11076/com.nice.main E/PoolStatsTracker﹕ onFree 2250000
08-13 14:12:19.201  10417-11074/com.nice.main E/PoolStatsTracker﹕ onAlloc 19600
08-13 14:12:19.781  10417-11077/com.nice.main E/PoolStatsTracker﹕ onAlloc 19600
08-13 14:12:19.791  10417-11028/com.nice.main E/PoolStatsTracker﹕ onAlloc 19600
08-13 14:12:23.561  10417-11073/com.nice.main E/PoolStatsTracker﹕ onAlloc 19600
08-13 14:12:23.841  10417-11025/com.nice.main E/PoolStatsTracker﹕ onAlloc 409600
08-13 14:12:23.891  10417-11069/com.nice.main E/PoolStatsTracker﹕ onAlloc 409600
08-13 14:12:24.281  10417-11068/com.nice.main E/PoolStatsTracker﹕ onAlloc 409600
08-13 14:12:24.321  10417-11076/com.nice.main E/PoolStatsTracker﹕ onAlloc 409600
08-13 14:12:24.341  10417-11076/com.nice.main E/PoolStatsTracker﹕ onFree 19600
08-13 14:12:24.391  10417-11074/com.nice.main E/PoolStatsTracker﹕ onAlloc 19600
08-13 14:12:24.401  10417-11074/com.nice.main E/PoolStatsTracker﹕ onFree 2250000
08-13 14:12:24.431  10417-11077/com.nice.main E/PoolStatsTracker﹕ onAlloc 409600
08-13 14:12:24.441  10417-11077/com.nice.main E/PoolStatsTracker﹕ onFree 2250000
08-13 14:12:24.481  10417-11028/com.nice.main E/PoolStatsTracker﹕ onAlloc 409600
08-13 14:12:24.491  10417-11028/com.nice.main E/PoolStatsTracker﹕ onFree 19600
```

And explicit gc still happens...

Thank you so much for your patience.

**Comment by bluef** [comment]
Could we just avoid triggering explict gc on Android 5+?

**Comment by michalgr** [comment]
You mean `System.gc()` cals ? Fresco does not use it apart from the sample app: https://github.com/facebook/fresco/search?utf8=%E2%9C%93&q=%22System.gc%28%29%22&type=Code

PoolParams setup looks fine. I'll try to set it up for our sample app, verify it works and share the code.

I also tried to scroll through a long grid of camera photos (on Nexus 5 running Lollipop). I could not see jitter and glitches. Any advices how to reproduce this ? I used our sample app (https://github.com/facebook/fresco/tree/master/samples/comparison) which displays 3 images in a row (on Nexus 5 each one is 371x371 px)

**Comment by michalgr** [comment]
Ok, I am able to reproduce significant gc pauses if I resize to 1500x1500 instead of 371x371 (1500x1500 corresponds to size=2250000).

**Comment by bluef** [comment]
wow you reminded me about the ```System.gc()``` call and I did found a plugin call LeakCanary triggers explict gc randomly... I should recognize this at the very beginning. : (

Thank you so much for your help.

By the way, we have over 10m Android users in China, and we started using Fresco from 0.1.0. It would be our pleasure to help Fresco improve. Let me know when you need us. : )

**Comment by michalgr** [comment]
@bluef thanks, it is great to hear that ! Would you mind adding your app to the list on our main page ? (https://github.com/facebook/fresco/edit/gh-pages/index.md - look for "Who Uses Fresco?" and ). It is great to see that more and more production apps use Fresco :)

**Comment by sahibprashant** [comment]
I am also getting some similar problem in my application. Will you suggest me what i have to do.
i m posting the same question that i post on stackoverflow. I know i am posting my ques in comments but i really need the solution of this that is why

 I am developing an android game and it is working properly in my  galaxy j5 prime but when it tested it in other devices then in some of  them the application stops on its own showing the error given below.  Information about the game: it has several layout in it, inside a  frame layout and i am using setvisiblity to hide and show the layouts  and one of the layout has the surfaceview added dynamically to it. It  also has Media Player object in it for game sound. App stops when the layout having surface view inside in it is visible.  I am not getting what kind of error this is and why this error is generating in some devices. 
 Logcat :  

12-21 10:34:11.058 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
12-21 10:34:11.058 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
12-21 10:34:11.068 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
12-21 10:34:11.068 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
12-21 10:34:11.068 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
12-21 10:34:11.078 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
12-21 10:34:11.078 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:11.078 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:11.088 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:11.098 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:11.098 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:11.098 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:12.008 9332-9344/com.example.prashant.dodgeballfinal W/MediaPlayer-JNI: MediaPlayer finalized without being released
 12-21 10:34:12.008 9332-9344/com.example.prashant.dodgeballfinal W/MediaPlayer-JNI: MediaPlayer finalized without being released
 12-21 10:34:12.008 9332-9344/com.example.prashant.dodgeballfinal W/MediaPlayer-JNI: MediaPlayer finalized without being released
 12-21 10:34:23.838 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:23.848 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:23.858 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:23.858 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:23.858 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:23.878 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:23.878 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:23.878 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
 12-21 10:34:23.888 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:23.928 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:23.928 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:23.928 9332-9332/com.example.prashant.dodgeballfinal E/MediaPlayer: Should have subtitle controller already set
 12-21 10:34:24.418 9332-9344/com.example.prashant.dodgeballfinal W/MediaPlayer-JNI: MediaPlayer finalized without being released
 12-21 10:34:24.418 9332-9344/com.example.prashant.dodgeballfinal W/MediaPlayer-JNI: MediaPlayer finalized without being released
 12-21 10:34:24.418 9332-9344/com.example.prashant.dodgeballfinal W/MediaPlayer-JNI: MediaPlayer finalized without being released
 12-21 10:34:31.398 9332-9347/com.example.prashant.dodgeballfinal I/art: Background sticky concurrent mark sweep GC freed 46738(3MB) AllocSpace objects, 0(0B) LOS objects, 18% free, 14MB/18MB, paused 951us total 101.562ms
 12-21 10:34:50.498 9332-9332/com.example.prashant.dodgeballfinal A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 9332 (.dodgeballfinal)

                                                                     [ 12-21 10:34:50.498   321:  321 W/         ]
                                                                     handle_request(11) debug_value = false;


                                                                     [ 12-21 10:34:50.498   321:  321 W/         ]
                                                                     wait_for_sigstope = 19

                                                                     [ 12-21 10:34:50.548   321:  321 W/         ]
                                                                     wait_for_sigstope = 11

**Comment by arkilis** [comment]
@sahibprashant Did you solve this non response issue? thx
