### ISSUE TITLE
Fresco won't recycle the memory on Lollipop .

### ISSUE THREAD

**Issue by leeyc09** [facebook/fresco#537]
I show some picture using viewpager. Viewpager item is Fragment. 
 Even though Fregment is detroy. GC is not occur.
Keep add Image to memory. 

![11](https://cloud.githubusercontent.com/assets/6457985/9247708/69a155a4-41f0-11e5-8af0-5033929813af.png)

![222](https://cloud.githubusercontent.com/assets/6457985/9247792/1acb1540-41f1-11e5-95e7-01d21d49a062.png)

init Fresco

```
  ImagePipelineConfig config = OkHttpImagePipelineConfigFactory
                .newBuilder(this, DCB_RestfulAdapter.getClient())
                .build();
        Fresco.initialize(this, config);
```

showing image

```
 GenericDraweeHierarchyBuilder builder = new GenericDraweeHierarchyBuilder(getResources());
            GenericDraweeHierarchy hierarchy = builder.setFadeDuration(300)
            .setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER)
            .setProgressBarImage(new CustomProgressbarDrawable(this))
            .build();

            hierarchy.setPlaceholderImage(R.drawable.ic_placeholder);


            ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url))
                .setResizeOptions(new ResizeOptions(Utils.getScreenWidth(getActivity()), Utils.getScreenHeight(getActivity())))
//                .setResizeOptions(new ResizeOptions(300, 300))
                .setAutoRotateEnabled(true)
                .build();


            DraweeController draweeController = Fresco.newDraweeControllerBuilder()

                    .setImageRequest(imageRequest)
                    .setAutoPlayAnimations(true)
                    .setOldController(view.getController())

                    .build();
            view.setController(draweeController);
            view.setHierarchy(hierarchy);
            view.setAspectRatio(1.33f);
```

**Comment by michalgr** [comment]
Fresco maintains bitmap cache and it's default size limit is equal to 1/4 of the heap size. Can you confirm that Bitmaps take more space than that ?

**Comment by leeyc09** [comment]
occur OOM.

**Comment by DASAR** [comment]
A also saw strange behaviour on Lollipop (Nexus 5). Images inside RecyclerView became black, scrolling became slow after some usage. And then app crashes if I continue to scroll this collection of images. Looks like after close/open this Fragment with images Fresco do not free memory.

**Comment by ChenSiLiang** [comment]
@DASAR yes, that situation also happened in all my Lolliopop version cellphones.

**Comment by parane** [comment]
+1

**Comment by erikandre** [comment]
Closing due to lack of updates.
