### ISSUE TITLE
Does fresco checks if a similar request is also in queue before sending out a new request?

### ISSUE THREAD

**Issue by KashanDanish** [facebook/fresco#538]
By similar I mean same Uri.

**Comment by michalgr** [comment]
Yes. If you start another request for the same uri it will wait for the first one to be decoded (or downloaded if you specify different decode options) and after that both requests will share the result. Component that takes care of this is called MultiplexProducer (https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/MultiplexProducer.java)
