### ISSUE TITLE
load local image issue

### ISSUE THREAD

**Issue by willchyis** [facebook/fresco#539]
1.when I load local images use LOCAL_FILE_SCHEME, not LOCAL_CONTENT_SCHEME, it works lag when I scroll it.
2.load local image fail, here is log:
01-06 08:32:40.796  27803-27923/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412284: onProducerFinishWithFailure: {requestId: 896, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
01-06 08:32:40.796  27803-27923/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412290: onRequestFailure: {requestId: 896, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
01-06 08:32:40.796  27803-27925/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412291: onProducerFinishWithFailure: {requestId: 897, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
01-06 08:32:40.804  27803-27925/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412292: onRequestFailure: {requestId: 897, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
01-06 08:32:40.835  27803-27924/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412324: onProducerFinishWithFailure: {requestId: 898, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
01-06 08:32:40.835  27803-27924/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412325: onRequestFailure: {requestId: 898, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
01-06 08:32:40.867  27803-27926/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412357: onProducerFinishWithFailure: {requestId: 899, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
01-06 08:32:40.867  27803-27926/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 18412358: onRequestFailure: {requestId: 899, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}

**Comment by michalgr** [comment]
Hi !

do you resize or downsample local images ? If not, can you check if that solves the issue ?
http://frescolib.org/docs/resizing-rotating.html

**Comment by willchyis** [comment]
when i call setResizeOptions(new ResizeOptions(100, 100)), it also loads image fail, here is log:
08-17 10:39:52.242  30190-30731/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600061: onProducerFinishWithFailure: {requestId: 568, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
08-17 10:39:52.242  30190-30731/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600063: onRequestFailure: {requestId: 568, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
08-17 10:39:52.242  30190-30733/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600063: onProducerFinishWithFailure: {requestId: 570, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
08-17 10:39:52.242  30190-30734/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600064: onProducerFinishWithFailure: {requestId: 571, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
08-17 10:39:52.242  30190-30732/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600065: onProducerFinishWithFailure: {requestId: 569, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
08-17 10:39:52.242  30190-30732/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600065: onRequestFailure: {requestId: 569, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
08-17 10:39:52.242  30190-30733/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600065: onRequestFailure: {requestId: 570, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}
08-17 10:39:52.242  30190-30734/com.facebook.samples.comparison W/unknown:RequestLoggingListener﹕ time 6600065: onRequestFailure: {requestId: 571, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.bitmaps.TooManyBitmapsException}

**Comment by plamenko** [comment]
Are you using DraweeView or are you submitting those image requests in some other way?

**Comment by tyronen** [comment]
Are these PNG images? If so, use downsampling instead of resizing: http://frescolib.org/docs/resizing-rotating.html#downsampling

**Comment by IanChilds** [comment]
No reply to multiple comments, reaping
