### ISSUE TITLE
Toggling visibility of the SimpleDraweeViews 

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#541]
I have extended the `SimpleDraweeView` to create a simple wrapper in order to use in my code.
My current logic works as follow.

I request the image from a webservice and once the image is loaded, I use the `BaseControllerListener.onFinalImageSet()` to make the DraweeView visible. Although the entire callback occurs,the image visiblity does not change
Inface

PS : the draweeview is initally invisible. Can that prevent the image from loading?

**EDIT** 
It seems if the view is invisible intially,the callback does not occur.However if i toggle the visiblity of the parent container, instead the image gets loaded.

**Comment by plamenko** [comment]
It's hard to tell without looking at the code. Can you please provide the implementation of your view?

**Comment by droidekas** [comment]
I've solved the issue by making the container invisible and then populating it.
