### ISSUE TITLE
The image loaded from local file is small

### ISSUE THREAD

**Issue by YuanJialiang** [facebook/fresco#543]
When I trying to use SimpleDraweeView.setImageURI(Uri.parse("file:///storage/emulated/0/Pictures/JPEG_20150814_223226_-1110502600.jpg"));
The image loaded from the photo that I took from the camera is very small, but the image loaded from the other photo(ex. screenshots) is normal.

**Comment by plamenko** [comment]
@tyronen could that be related to the media thumbnails?

**Comment by tyronen** [comment]
Unlikely. What are the layout width and height of your view?

**Comment by YuanJialiang** [comment]
I set the layout width and height to match parent and scale type is center. But the photo take from the phone camera is very small.Actually, it is a big one.

**Comment by TigerHix** [comment]
This is likely the same issue as mentioned at:

https://github.com/facebook/fresco/issues/559

**Comment by tyronen** [comment]
Fixed in v0.8.0
