### ISSUE TITLE
How can I save an image to sd card?

### ISSUE THREAD

**Issue by y11t** [facebook/fresco#549]
How can I save an image to sd card? What to do with cacheFile?
```java
public void DownloadClicked(String url){
        Uri uri = Uri.parse(url);
        ImageRequest downloadRequest = ImageRequest.fromUri(uri);
        CacheKey cacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(downloadRequest);
        if (ImagePipelineFactory.getInstance().getMainDiskStorageCache().hasKey(cacheKey)) {
            BinaryResource resource = ImagePipelineFactory.getInstance().getMainDiskStorageCache().getResource(cacheKey);
            File cacheFile = ((FileBinaryResource) resource).getFile();
            try{
                FileInputStream fis = new FileInputStream(cacheFile);
                ImageFormat imageFormat = ImageFormatChecker.getImageFormat(fis);
                switch (imageFormat) {
                    case GIF:
                        //copy cacheFile to sdcard
                        break;
                }
            }catch (Exception e){
                e.printStackTrace();
            }

        }
    } 
```

**Comment by plamenko** [comment]
Please read our documentation [Using the Image Pipeline Directly] (http://frescolib.org/docs/using-image-pipeline.html#_) and [DataSources and DataSubscribers] (http://frescolib.org/docs/datasources-datasubscribers.html#_).

Do not access the disk cache directly, but submit the image request and subscribe your data subscriber as explained in the "get encoded image" example in the documentation.

**Comment by Aravind-Rajendran** [comment]
what is executor does there?

**Comment by Kroderia** [comment]
I found they mention it in https://github.com/facebook/fresco/issues/265. However, the doc has not get updated.
I found it is runnable with this:
new Executor() {
            @Override
            public void execute(Runnable command) {
                command.run();
            }
        }

**Comment by leeyikjiun** [comment]
How do you retrieve the GIF file from the subscriber?
