### ISSUE TITLE
Can not show the local Image (JPG) taking by Meizu phone

### ISSUE THREAD

**Issue by fdublue** [facebook/fresco#550]
I use the simpledraweeview to load the local images. Most of time it works except the images taking by Meizu phone
Please download this 4.8m JPG file and have a try.
https://www.dropbox.com/s/haeo0hoj993dn88/2.pic_hd.jpg?dl=0

code:
drawee.setImageURI(Uri.fromFile(file));

**Comment by tyronen** [comment]
What happens exactly? Can you turn on verbose logging and call FLog.setMinimumLoggingLevel(FLog.VERBOSE) so we can look at what is going on?

**Comment by TigerHix** [comment]
This issue may be connected to:

https://github.com/facebook/fresco/issues/550

**Comment by tyronen** [comment]
Oh wait - the image is 4.8MB? You must [resize](http://frescolib.org/docs/resizing-rotating.html#resizing) it, unless you are running on Android 5.0 or later.
