### ISSUE TITLE
ZoomableDrawee with Zoom maintaing Aspect ratio

### ISSUE THREAD

**Issue by vipulasri** [facebook/fresco#551]
How to implement the ZoomableDrawee having maintained the Aspect Ratio of the picture inflated.
And double tap zoom feature does work but it is not smooth.

**Comment by plamenko** [comment]
What do you mean by maintaining aspect ratio? If you set the `FIT_CENTER` scale type, the aspect ratio should be preserved. Is that not the case?
What do you mean by not smooth? If you mean not animated, yeah, that's not implemented. The zoomable code provided here is only an example of how such functionality can be achieved with Fresco. You'd have to implement any zoomable functionality you desire yourself.

**Comment by vipulasri** [comment]
I have already applied <code>FIT_CENTER</code> in <code>GenericDraweeHierarchy</code> : 
This is my code : 
<code>GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(getResources())
                .setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER)
                .setProgressBarImage(drawable)
                .build();</code>
By aspect ratio means I should not be able to zoom enough (destroying aspect ratio of image and making it pixelated).

and yeah I mean Animated in case of smooth, now i got it.

**Comment by plamenko** [comment]
Ah, this is not what aspect ratio means. Aspect ratio is the ratio between the width and the height. What you are looking for is scale factor that you can set with [setMaxScaleFactor] (https://github.com/facebook/fresco/blob/c5e1d4cf2c081bf871f59f70cd02e4a68950ac41/samples/zoomable/src/main/java/com/facebook/samples/zoomable/DefaultZoomableController.java#L162).

**Comment by binqiangsun** [comment]
@vipulasri  where is  "double tap zoom feature"

**Comment by vipulasri** [comment]
@binqiangsun see @kyungin-park answer on this https://github.com/facebook/fresco/issues/86

**Comment by levianye** [comment]
@vipulasri Did you resolved the double tap not smooth problem? I still don't know how to eliminate shake problem when double tap zoom image? it seems must rewrite onTouch to  handle the touch event

**Comment by arlindiDev** [comment]
Here is the code for smooth double tap zoom and pinch to zoom
https://github.com/arlindiDev/FrescoDoubleTapZoom
