### ISSUE TITLE
should have option for selecting ABIs while importing library or AAR

### ISSUE THREAD

**Issue by vipulasri** [facebook/fresco#554]
Fresco should provide us with an option to select the ABIs while importing library as importing whole library cost's developer an extra 3-4mb with Apk. I understand the concept of multiple apk's but thats a work around. Fresco should provide us with compatibility.

**Comment by michalgr** [comment]
Use `abiFilter` or `abiFilters`. More info here: #458 and here: http://tools.android.com/tech-docs/new-build-system/tips.

**Comment by vipulasri** [comment]
@michalgr I know about making multiple apk's for different devices but I don't want to make multiple Apk's there should be one Universal Apk. While Fresco should provide me the option to import only selected ABIs or Fresco should also focus on library size.

**Comment by michalgr** [comment]
I am not suggesting using multiple apks. I am telling you that you can use `abiFilters` to select abis for your universal apk :) Example for universal x86_64 and x86 abis:
```
apply plugin: 'com.android.application'

dependencies {
    compile project(':drawee-backends:drawee-pipeline')
}

android {
    compileSdkVersion 21
    buildToolsVersion '21.1.2'
    defaultConfig {
        applicationId "com.facebook.samples.demo"
        minSdkVersion 9
        targetSdkVersion 21
        versionCode 1
        versionName "${VERSION_NAME}"

        testApplicationId "com.facebook.samples.demo.test"
        testInstrumentationRunner "android.test.InstrumentationTestRunner"

        ndk {
            abiFilters 'x86', 'x86_64'
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), '../../proguard-fresco.pro'
        }
    }

    lintOptions {
        warning 'InvalidPackage'
    }
}
```

I used this `build.gradle` file to build our demo app (https://github.com/facebook/fresco/tree/master/samples/demo):
```
./gradlew samples:demo:assembleRelease
```

After that I run following command to verify content of the apk:
```
unzip -l samples/demo/build/outputs/apk/demo-release-unsigned.apk
```
>Archive:  samples/demo/build/outputs/apk/demo-release-unsigned.apk
>  Length     Date   Time    Name
> --------    ----   ----    ----
>     1992    08-19-15 20:06   AndroidManifest.xml
>     2388    08-19-15 20:06   res/layout/activity_main.xml
>     3122    08-19-15 20:05   res/mipmap-hdpi-v4/ic_launcher.png
>     1956    08-19-15 20:05   res/mipmap-mdpi-v4/ic_launcher.png
>     4366    08-19-15 20:05   res/mipmap-xhdpi-v4/ic_launcher.png
>     7007    08-19-15 20:05   res/mipmap-xxhdpi-v4/ic_launcher.png
>     3488    08-19-15 20:05   resources.arsc
>     403912  08-19-15 20:06   classes.dex
>     5288    08-19-15 20:05   lib/x86/libbitmaps.so
>     157356  08-19-15 20:05   lib/x86/libgifimage.so
>     562556  08-19-15 20:05   lib/x86/libimagepipeline.so
>     5364    08-19-15 20:05   lib/x86/libmemchunk.so
>     234752  08-19-15 20:05   lib/x86/libwebp.so
>     140972  08-19-15 20:05   lib/x86/libwebpimage.so
>     5856    08-19-15 20:05   lib/x86_64/libbitmaps.so
>     498576  08-19-15 20:05   lib/x86_64/libgifimage.so
>     985424  08-19-15 20:05   lib/x86_64/libimagepipeline.so
>     5984    08-19-15 20:05   lib/x86_64/libmemchunk.so
>     259920  08-19-15 20:05   lib/x86_64/libwebp.so
>     482192  08-19-15 20:05   lib/x86_64/libwebpimage.so
> --------                   -------
>  3772471                   20 files

**Comment by vipulasri** [comment]
@michalgr Thank you so much for this solution. I would suggest you to add this solution to your Fresco documentation too, that would be a great help to everyone.
