### ISSUE TITLE
Use fresco:actualImageScaleType="fitCenter" will 

### ISSUE THREAD

**Issue by nimengbo** [facebook/fresco#555]
I create a class extends SimpleDraweeView as SquareSimpleDraweeView and override this method:

 @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, widthMeasureSpec);
    }
use it in listview.
and use it in xml :
 android:id="@+id/iv_pic"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        fresco:actualImageScaleType="fitCenter"
        fresco:placeholderImage="@drawable/icon_default_pic"
        fresco:roundBottomLeft="true"
        fresco:roundBottomRight="true"
        fresco:roundTopLeft="true"
        fresco:roundTopRight="true"
        fresco:roundedCornerRadius="1px"
        fresco:roundingBorderColor="@color/grey_cccccc"
        fresco:roundingBorderWidth="1px"

display as :

![image](https://cloud.githubusercontent.com/assets/6950107/9347610/95d87518-465e-11e5-9fd4-5382fe774728.png)

It is a bug?

original picture is 

![image](https://cloud.githubusercontent.com/assets/6950107/9347694/af2e417c-465f-11e5-8302-86e677ae15f9.png)

**Comment by plamenko** [comment]
No need to extend `SimpleDraweeView` to make it square, simply add the following XML property: `fresco:viewAspectRatio="1"`.
As for the repeated edges, this is a known limitation of Android. Please see the Caveats section of [Rounded Corners and Circles] (http://frescolib.org/docs/rounded-corners-and-circles.html#_).
