### ISSUE TITLE
Add support for RGB_565 bitmaps to use less memory

### ISSUE THREAD

**Issue by nbarraille** [facebook/fresco#56]
Hey,
I'd like to be able to force decoding bitmap in RGB_565 to use less memory but didn't find anything in the doc, is there any way I can do this?
Thanks!

**Comment by blackiedm** [comment]
you can see [Modifying The Image](http://frescolib.org/docs/modifying-image.html#_)

**Comment by tyronen** [comment]
We don't currently support this. We are considering adding RGB_565 for images that don't use alpha.

**Comment by nbarraille** [comment]
@blackiedm Using a Postprocessor wouldn't provide much, because the version of the image stored in the memory cache is the one before post processing from what I understand, so you will end up having to transform it back every time, and keep both versions in memory.
Plus I don't even know if changing the config of a bitmap instance is possible at all, as it changes the size of the underlying byte array
@tyronen I really hope this gets in soon, this would be super helpful for apps using a lot of images. The library looks pretty good so far, keep up the good work!

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by nikslushkin** [comment]
We really need this feature for images without alpha. It will free 50% of its memory usage.

**Comment by tyronen** [comment]
This was added in v0.8.0.
