### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jyh149129** [facebook/fresco#560]
XT320
Android 4.3,level 18

java.lang.UnsatisfiedLinkError
Couldn't load memchunk from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xx.xx.xx-1.apk"],nativeLibraryDirectories=[/data/app-lib/xx.xx.xx-1, /vendor/lib, /system/lib]]]: findLibrary returned null
java.lang.Runtime.loadLibrary(Runtime.java:355)
java.lang.System.loadLibrary(System.java:525)
com.facebook.common.soloader.SoLoaderShim$DefaultHandler.a(SoLoaderShim.java:32)
com.facebook.common.soloader.SoLoaderShim.a(SoLoaderShim.java:56)
com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:35)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.i(NativeMemoryChunkPool.java:59)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.b(NativeMemoryChunkPool.java:21)
com.facebook.imagepipeline.memory.BasePool.a(BasePool.java:253)
com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:52)
com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.a(NativePooledByteBufferFactory.java:97)
com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.b(NativePooledByteBufferFactory.java:25)
com.facebook.imagepipeline.producers.LocalFetchProducer.a(LocalFetchProducer.java:89)
com.facebook.imagepipeline.producers.LocalFetchProducer.a(LocalFetchProducer.java:102)
com.facebook.imagepipeline.producers.LocalFileFetchProducer.a(LocalFileFetchProducer.java:34)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.d(LocalFetchProducer.java:56)
com.facebook.imagepipeline.producers.LocalFetchProducer$1.c(LocalFetchProducer.java:52)
com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
java.lang.Thread.run(Thread.java:841)

**Comment by tyronen** [comment]
This looks identical to #429. Make sure the libmemchunk.so file is in the armeabi-v7a folder, not armeabi, when installing on an ARM v7 device. All phones and most tablets running Android 4.0 or later are ARM v7.
