### ISSUE TITLE
fresco:roundedCornerRadius Not working with Gif images 

### ISSUE THREAD

**Issue by jehad-suliman** [facebook/fresco#561]
its not working if the image is a GIF 

     fresco:roundedCornerRadius="4dp"
     fresco:roundTopLeft="true"
     fresco:roundTopRight="true"

**Comment by plamenko** [comment]
Is the image animated?

**Comment by jehad-suliman** [comment]
yes it is

**Comment by plamenko** [comment]
Yeah, this is a known limitation. Please see our documentation for [Rounding] (http://frescolib.org/docs/rounded-corners-and-circles.html#_), there are more explanations and alternatives.
