### ISSUE TITLE
Load images failed.

### ISSUE THREAD

**Issue by starFelix** [facebook/fresco#564]
There are about 100 images whose size is 2048*1536 will show in my project.I had used resizing.But I found that fresco can only load several images,and then all below images would load fail.    
By the way, I use viewPage with FragmentStatePagerAdapter.
    
The code I used to load image is below   
```
SimpleDraweeView imageView=new SimpleDraweeView(getContext());
imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
imageView.setLayoutParams(new LayoutParams(LayoutParams.MATCH_PARENT, this.deviceSize.y));
Uri uri = Uri.parse(this.imageUrls.get(i));
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
         .setResizeOptions(new ResizeOptions(deviceSize.x, deviceSize.y))
         .build();
PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
          .setOldController(imageView.getController())
          .setControllerListener(controllerListener)
          .setImageRequest(request)
          .build();
imageView.setController(controller);   
```    
and the error   
```
E/unknown:﹕ Error loading 8
    com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 50331648Used size = 48168960Free size = 0Request size = 9633792
            at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:241)
            at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.doDecodeStaticImage(ArtBitmapFactory.java:131)
            at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeJPEGFromPooledByteBuffer(ArtBitmapFactory.java:119)
            at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromPooledByteBuffer(PlatformBitmapFactory.java:106)
            at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:135)
            at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:83)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:166)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$000(DecodeProducer.java:88)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:112)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:109)
            at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:214)
            at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:30)
            at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:68)
            at com.facebook.common.executors.SerialDelegatingExecutor.executeSingleCommand(SerialDelegatingExecutor.java:76)
            at com.facebook.common.executors.SerialDelegatingExecutor.access$000(SerialDelegatingExecutor.java:24)
            at com.facebook.common.executors.SerialDelegatingExecutor$1.run(SerialDelegatingExecutor.java:47)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

P.S. the example for the imageUrl
http://www.yccy.cc/xueermian/source/03-1.jpg

**Comment by plamenko** [comment]
What resize options do you specify? How many images at once can be displayed?

**Comment by starFelix** [comment]
@plamenko deviceSize is the size of device's screen. There may be three or four images display at once. If the simpleDraweeView is not in screen,what is the best way to clear it's content and recycle the image cache?

**Comment by starFelix** [comment]
@plamenko And when I use Fresco,I found the warning as below.
```
CloseableReference﹕ Finalized without closing: 2e7d7658 258a63b1
```

**Comment by plamenko** [comment]
SimpleDraweeView should clear the resources automatically once it gets off the screen. However if the container is misbehaving and is not detaching the invisible children (or calling setVisible(false) on them) Drawee won't be able to tell that is not visible and will not release the resources. What is the container of DraweeView? Is it ViewPager? How many pages are there?

**Comment by starFelix** [comment]
@plamenko the container of DraweeView is scrollview,and the container of the scroll is FragmentStatePagerAdapter in ViewPager.

**Comment by starFelix** [comment]
I found that if i move the scroll,the image cache can be rightly recycled.But if I scroll the ViewPager,the image cache won't be recycled.

**Comment by tyronen** [comment]
Do not use ScrollViews with Fresco.

**Comment by Parthacus** [comment]
Sorry for reopening an old issue, but I seem to be having a similar problem, my app currently has a main page with ~60 images with a small text that are displayed using a recycler view and I would expect Fresco to handle fine since it **should** only be loading a few at a time, however I frequently get a "Pool Size Violation".  I'm not entirely sure if this is a fault on my side or on Fresco's so just in case it isn't I'll post the related code

**Note: It's mostly in Kotlin, however I'm fairly sure this isn't the problem since most of the interactions with Fresco are done through Java**

`    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerViewAdapter.ViewHolder {
        val v = LayoutInflater.from(parent.context).inflate(R.layout.list, parent, false)
        return ViewHolder(v)
    }

    //this method is binding the data on the list
    override fun onBindViewHolder(holder: RecyclerViewAdapter.ViewHolder, position: Int) {
        holder.bindItems(list[position])
    }

    //this method is giving the size of the list
    override fun getItemCount(): Int {
        return list.size
    }

    class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
        fun bindItems(data: MyData) {
            val _textView: TextView = itemView.textview
            val _titleView: TextView = itemView.titleView
            _titleView.text = data.title
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                _textView.text = Html.fromHtml(ReplaceEscapes(data.text), Html.FROM_HTML_MODE_LEGACY)
            } else {
                _textView.text = Html.fromHtml(ReplaceEscapes(data.text))
            }

            val _card: CardView = itemView.findViewById(R.id.cardView)

            val _imageView: SimpleDraweeView = itemView.findViewById(R.id.imageview)
            _imageView.setOnClickListener {
                Log.e("Click: ", data.imageURL)
            }
            Required_Functions.setPicture(_imageView, data.imageURL, _card.width)


            //set the onclick listener for the singlt list item
            itemView.setOnClickListener({
                Log.e("ItemClicked", data.text)
            })
        }

    }
}`

And here's my referenced "Requested Functions" function

 
```public static void setPicture(SimpleDraweeView img, String img_location, int cardwidth){
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(img_location))
                .setResizeOptions(new ResizeOptions(100, 100))
                .build();
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(img.getController())
                .setImageRequest(request)
                .build();

        img.setController(controller);

        img.setImageURI(Uri.parse(img_location));
    }```

Extra Information: I'm on fresco 1.5.0 and I've tried this out on my Nexus 6 and an S4. On the Nexus 6, the images load but upon scrolling I get the error above and the S4 crashes upon boot-up.

Thanks for helping!

**Comment by vinhnguyenitvn** [comment]
This issue just happens when I try to display image as viewPager item, and the viewPager is in an item of recyclerView. Hope it helps to reproduce the issue
And it just happen with a gif image, not for png

**Comment by Gnzlt** [comment]
I have the same issue and it still happens on version `2.6.0` with `ViewPager` + `FragmentStatePagerAdapter` when calling `setOffscreenPageLimit()` with a value higher than **1**. In the meanwhile I found the following workaround:

**ViewPager child Fragment:**
```
binding.image.controller = Fresco.newDraweeControllerBuilder()
    .setOldController(binding.image.controller)
    .setControllerListener(object : BaseControllerListener<ImageInfo>() {
        override fun onFailure(id: String, throwable: Throwable) {
            if (throwable is BasePool.PoolSizeViolationException) {
                activity?.onLowMemory()
            }
        }
    })
    .setAutoPlayAnimations(true)
    .setImageRequest(mainImageRequest)
    .build()
```

**ViewPager parent Activity:**
```
override fun onLowMemory() {
    binding.viewPager.offscreenPageLimit = OFFSCREEN_PAGE_LIMIT_DEFAULT
}
```
