### ISSUE TITLE
Can't open file if path contains "#"

### ISSUE THREAD

**Issue by MichaelArchangel** [facebook/fresco#565]
failed to load local file.
file uri:
file:///storage/emulated/0/Android/data/com.org.app/org#app/a83ee0da519d19d2db58ee966e6535a5/image/f0111720-47b6-11e5-87d8-a3b5efcd5fab

log:
08-21 15:23:02.425  16424-16486/com.org.appE/JHEAD﹕ can't open '/storage/emulated/0/Android/data/com.org.app/org'

**Comment by desmond1121** [comment]
try replace '%23' to '#'

**Comment by MichaelArchangel** [comment]
can't open '/storage/emulated/0/Android/data/com.org.app/org#app/a83ee0da519d19d2db58ee966e6535a5/image/f0111720-47b6-11e5-87d8-a3b5efcd5fab'
I checked, that file really exists and can be opened in gallery.

**Comment by plamenko** [comment]
I was thinking the same as @desmond1121 . I wonder whether this is a misspelled path issue, or something else, such as permission issue.

**Comment by plamenko** [comment]
Just for a test, can you try to open a plain old Java FileInputStream with that path?

**Comment by MichaelArchangel** [comment]
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.org.app/org#app/5cf124023bb26e021a91c2654363737c/image/9f0f5950-47c9-11e5-9f76-e51d328d690d: open failed: ENOENT (No such file or directory)
the file is gone when I check it in that folder!so weird...so I decide to use an alternate path, the remote one...since Fresco has cache  itself.
Anyway, thanks~

**Comment by plamenko** [comment]
Alright, this doesn't seem to be related to Fresco, hence closing it.
