### ISSUE TITLE
PNG issue

### ISSUE THREAD

**Issue by s1rius** [facebook/fresco#567]
I get a TooManyBitmapsException when I load several  PNG format images by use GridView on screen. After that, I can't display one of these images on a SimpleDraweeView full screen.
Use a Sumsung device make many screenshots and run the comparison sample, The exception can reproduce every time.
I upload a [video](https://youtu.be/5cFpkJPIWNM) about this on youtube.
I searched and saw all issues about this, but I have no idea to resolve it.
#213
#214 
#256
#307 
#308 
#469
#483
#539
#556

**Comment by s1rius** [comment]
Now, The only way is rolling back to UIL before application release :(

**Comment by plamenko** [comment]
Do you specify ResizeOptions? If not, each of these images requires a bitmap of the screen size, even though they are 9 times smaller (I.e. your app is using 9x more memory on images than it should).

Without some more context it is hard to tell.

**Comment by tyronen** [comment]
For PNGs you need to [enable downsampling](http://frescolib.org/docs/resizing-rotating.html#downsampling) when specifying ResizeOptions.

**Comment by s1rius** [comment]
Awesome, thank you.

**Comment by xyczero** [comment]
That's Right,thank you @tyronen

**Comment by AllenVork** [comment]
i wanna load gifs in my gallery.But when i get the first frame of the gif as a bitmap, i don't know how to load it with fresco
