### ISSUE TITLE
Cant import to android studio

### ISSUE THREAD

**Issue by sach200** [facebook/fresco#568]
I have added 
compile 'com.facebook.fresco:fresco:0.6.1+' to dependency and 
mavenCentral() to repositories.
I rebuild the project and it is now taking forever to rebuild. 

Anyone with the same issue?

--UPDATE--

I was wrong, it didnt took forever. Building finally finished after 1 hour with error : 

Error:A problem occurred configuring project ':app'.
> Could not download artifact 'imagepipeline.aar (com.facebook.fresco:imagepipeline:0.6.1)'
   > Failed to download resource 'https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/0.6.1/imagepipeline-0.6.1.aar'.
      > Connection reset

**Comment by tyronen** [comment]
Are you located in mainland China? There are occasional issues connecting to jcenter and Maven Central. See http://fresco-cn.org/docs/compile-in-android-studio.html#_ (in Chinese).

Please file a new issue if you are experiencing this problem outside China.

**Comment by MummyDing** [comment]
I got the same issue http://stackoverflow.com/questions/32524166/can-not-resolve-com-facebook-frescofresco0-7-0 (I don't think it's because of GFW .. )
