### ISSUE TITLE
Make nineoldandroids optional

### ISSUE THREAD

**Issue by goodev** [facebook/fresco#570]
How to avoid using NineOldAndroids lib. My app min target is api level 15.

**Comment by balazsbalazs** [comment]
This is coming soon.

**Comment by IlyaEremin** [comment]
Any changes?

**Comment by oprisnik** [comment]
We are actively working on this, should be available soon.

**Comment by oprisnik** [comment]
Newer versions now support this, just add your dependency as needed, see http://frescolib.org/docs/
