### ISSUE TITLE
Space in URL, image unable to load

### ISSUE THREAD

**Issue by jenshen312** [facebook/fresco#572]
Image unable to appear when using URL that content spaces , URL without any space is working ok.

Not Working URL
http://www.thestar.com.my/~/media/Images/TSOL/Photos-Gallery/Nation/2015/08/26/Bersih 4.ashx?crop=1&w=460&h=345&

Working URL
http://www.thestar.com.my/~/media/Images/TSOL/Photos-Gallery/Nation/2015/08/26/011040853.ashx?crop=1&w=460&h=345&

It does not work even I replace the space "Bersih 4" to "Bersih%204"

Thanks

**Comment by tyronen** [comment]
The one with the space shouldn't work, but the one with %20 should.

We will probably have to do something like this: http://stackoverflow.com/questions/26818553/filenotfoundexception-for-site-with-tilde-when-using-httpurlconnection.

**Comment by jenshen312** [comment]
I already said It DOES NOT work even I replace the space "Bersih 4" to "Bersih%204"

**Comment by andreidiaconu** [comment]
I want to reproduce the bug but http://www.thestar.com.my/~/media/Images/TSOL/Photos-Gallery/Nation/2015/08/26/Bersih%204.ashx/?crop=1&w=460&h=345& worked for me. This is with %20

The one with space doesn't work, as described, but I'm not sure it should.
Should this be closed or should we make URLs with invalid characters work?

**Comment by IanChilds** [comment]
Thanks @andreidiaconu
