### ISSUE TITLE
how to load local application or apk file icon

### ISSUE THREAD

**Issue by wangduheng** [facebook/fresco#576]
Excuse me
: i am want to load local application or apk file icon to show. how to do? Thanks

**Comment by tyronen** [comment]
You can construct a resource ImageRequest with the [ImageRequestBuilder.newBuilderWithResourceId](http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/request/ImageRequestBuilder.html#newBuilderWithResourceId\(int\)) method.

**Comment by wangduheng** [comment]
Hello. 
This answer doesn't work!.

for example with:universal-image-loader
 class MImageDownloader extends BaseImageDownloader {

    public static final String INSTALLED_APP_SCHEME = "installedApp://";

    public static final String UNINSTALLED_APP_SCHEME = "unInstalledApp://";

    public MImageDownloader(Context context) {
        super(context);
    }

    public MImageDownloader(Context context, int connectTimeout, int readTimeout) {
        super(context, connectTimeout, readTimeout);
    }

    @Override
    protected InputStream getStreamFromOtherSource(String imageUri, Object extra) throws IOException {
        boolean install;
        if ((install = imageUri.startsWith(INSTALLED_APP_SCHEME)) || imageUri.startsWith(UNINSTALLED_APP_SCHEME)) {
            PackageManager packageManager = MarketApplication.getInstance().getPackageManager();
            try {
                PackageInfo packageInfo;
                if (install) {
                    packageInfo = packageManager.getPackageInfo(imageUri.substring(INSTALLED_APP_SCHEME.length()), PackageManager.GET_ACTIVITIES);
                    if (packageInfo != null) {
                        Drawable icon = packageInfo.applicationInfo.loadIcon(packageManager);
                        return drawable2InputStream(icon);
                    }

                } else {
                    String apkPath = imageUri.substring(UNINSTALLED_APP_SCHEME.length());
                    packageInfo = packageManager.getPackageArchiveInfo(apkPath, PackageManager.GET_ACTIVITIES);
                    if (packageInfo != null) {
                        ApplicationInfo appInfo = packageInfo.applicationInfo;
                        appInfo.sourceDir = apkPath;
                        appInfo.publicSourceDir = apkPath;

                        Drawable icon = packageInfo.applicationInfo.loadIcon(packageManager);
                        return drawable2InputStream(icon);
                    }
                }
            } catch (PackageManager.NameNotFoundException e) {
                e.printStackTrace();
            }
        }
        return super.getStreamFromOtherSource(imageUri, extra);
    }
 ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(getApplicationContext())
                .imageDownloader(new MImageDownloader(this))//load icon from packName or apk file path
                .build();
        ImageLoader.getInstance().init(config);
