### ISSUE TITLE
High failure rate when Circle image with border--SimpleDraweeView

### ISSUE THREAD

**Issue by champion32** [facebook/fresco#577]
here's my code in xml
<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/iv_userportrait_header_mine"
            android:layout_width="71dp"
            android:layout_height="71dp"
            fresco:placeholderImage="@mipmap/mine_not_logged_head"
            fresco:failureImage="@mipmap/mine_not_logged_head"
            fresco:roundAsCircle="true"
            fresco:roundingBorderColor="@color/white"
            fresco:roundingBorderWidth="2dp"
            android:layout_centerHorizontal="true"/>

without roundingBorder it's pretty,but with roundingBorder the failure rate are so high,just like follow:
the result i want
![image](https://cloud.githubusercontent.com/assets/6419308/9538841/84e2490e-4d7b-11e5-8e32-8a1e07508e4a.png)
but after refresh it sometimes looks like this:
![image](https://cloud.githubusercontent.com/assets/6419308/9538879/124bfba0-4d7c-11e5-9259-cdb642261c32.png)
![image](https://cloud.githubusercontent.com/assets/6419308/9538884/21158926-4d7c-11e5-9177-6de5282417f8.png)
how to resolve this problem?thanks for your answer

**Comment by champion32** [comment]
any progress?thanks

**Comment by kirwan** [comment]
I'm cleaning up very old issues. If this still causes problems please comment and we can re-open.
