### ISSUE TITLE
Reuse DraweeHierarchy

### ISSUE THREAD

**Issue by sourabhv** [facebook/fresco#578]
Is using same `DraweeHierarchy` (or `GenericDraweeHierarchy`) object on all `SimpleDraweeView` views a good idea? All my hierarchies are same, should I reuse the same object or make new one for each view?

**Comment by nikslushkin** [comment]
Do not reuse hierarchies
http://frescolib.org/docs/gotchas.html#don-t-re-use-draweehierarchies

**Comment by tyronen** [comment]
Correct. Separate hierarchy per view.
