### ISSUE TITLE
Downloading png - unknown image format 

### ISSUE THREAD

**Issue by koptus** [facebook/fresco#579]
I'm downloading with fresco images from my server. Links are without extension, but some of them are loaded correctly but others throws exception java.lang.IllegalArgumentException: unknown image format. Of course images are accessible from Postman (server authentication needs additional request headers so this is why I'm testing this in postman). How can i fix that? 
Here are response headers:
Cache-Control → public, max-age=2678400
Content-Length → 33160
Content-Type → image/png
Date → Fri, 28 Aug 2015 05:44:22 GMT
Server → Microsoft-IIS/8.5
X-AspNet-Version → 4.0.30319
X-Powered-By → ASP.NET 

EDIT: I've tried it on GenyMotion emulator and one more photo is downloaded in compare to device - Samsung S3, which is weird. My ImagePipelineConfig setting:

        sOkHttpClient = new OkHttpClient();
        ImagePipelineConfig config = OkHttpImagePipelineConfigFactory.newBuilder(sContext, sOkHttpClient).setDownsampleEnabled(true)
                .build();

**Comment by plamenko** [comment]
I wonder if the actual file downloaded is some HTML response instead of the actual image file. What do you get if you curl or wget your uri?
