### ISSUE TITLE
Image flashes if it is not loaded from memory cache

### ISSUE THREAD

**Issue by qichuan** [facebook/fresco#583]
Is there a way to force remove the fade animation? The animation is always playing if the image is not loaded from memory cache. if the fade duration is set to zero, the image flashes from the placeholder image to the actual image. 

Many thanks.

**Comment by plamenko** [comment]
Can you give us some more information?
* Do you see the image, and then it flashes to placeholder and then back to image again?
* Do you know what triggers this flash?
* How many images do you have visible on the screen?

**Comment by tyronen** [comment]
You can [setFadeDuration](http://frescolib.org/javadoc/reference/com/facebook/drawee/generic/GenericDraweeHierarchyBuilder.html#setFadeDuration(int)) to 0 to turn off the animation. Reaping.
