### ISSUE TITLE
Is it possible to load images stored as blob in external database?

### ISSUE THREAD

**Issue by DmitriyZaitsev** [facebook/fresco#584]
I ran into a problem when I have to load images that stored in SQLite database as BLOB.
With Glide it was easy just call ```load(byte[])```. How can I do the same with Fresco? Is there any support for ```byte[]``` or ```InputStream```?

**Comment by tyronen** [comment]
Can you use a content provider URI to access them?

**Comment by DmitriyZaitsev** [comment]
As soon as I implemented my ContentProvider, Fresco began to work as expected.

**Comment by zhufeng1222** [comment]
I am doing a camera project. Camera returns a byte[] data,and I saved it into a database.How can i use Fresco to show this byte[] image?

**Comment by zhufeng1222** [comment]
My database table has three column,(long,byte[],byte[]).I used a URI like this:"content://***/table/id" to match the Fresco,but it dose not worked.
