### ISSUE TITLE
ZoomableDrawee not exactly in the project

### ISSUE THREAD

**Issue by coralinejones1985** [facebook/fresco#585]
Hello, I would like to use your library in my project, but what stops me is that ZoommableDrawee is not exactly included, so I can can't just import it. Can you, please, tell me, will it be included in the new version on not? :)

**Comment by tyronen** [comment]
ZoomableDraweeView uses a sample license rather than the BSD license used by the core library, so unfortunately we cannot include it in the same library. You are free to compile it yourself, as long as  you abide by the terms of the license.
