### ISSUE TITLE
download image in cache without displaying it.

### ISSUE THREAD

**Issue by vipulasri** [facebook/fresco#588]
I want to know a way to download the image directly into the cache rather than setting Uri to imageview and displaying it after it is downloaded. Basically I dont want to display image but download image and store it into the cache.

**Comment by tbruceyu** [comment]
I think we use the imagepipe directly to download the image. This may help you http://frescolib.org/docs/using-image-pipeline.html#_ .

**Comment by plamenko** [comment]
This is what prefetching means. You can find more info on the link @tbruceyu provided.
