### ISSUE TITLE
A problem occurred starting process 'command 'ndk-build.cmd''

### ISSUE THREAD

**Issue by MrThiago** [facebook/fresco#591]
When I try to build the project I get this error:

Error:Execution failed for task ':imagepipeline:ndk_clean_bitmaps'.
> A problem occurred starting process 'command 'ndk-build.cmd''

please advice. thank you

**Comment by archersmind** [comment]
@MrThiago have you seen this issue #286

**Comment by anvesh523** [comment]
I am also getting the same problem.... 

Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> A problem occurred starting process 'command 'ndk-build.cmd''

Help me out,

**Comment by tyronen** [comment]
Please run Gradle with the --debug option and see what the output of ndk-build is.

Have you installed the Android NDK? and set it in your $HOME/.gradle/gradle.properties file?

**Comment by impasoftware** [comment]
Error:Execution failed for task ':scanlibrary:ndkBuild'.
> A problem occurred starting process 'command 'ndk-build.cmd'' help me to resolve this
