### ISSUE TITLE
Fresco V0.7.0 may fail to load local images 

### ISSUE THREAD

**Issue by tbruceyu** [facebook/fresco#593]
I'm trying the fresco comparison app with the latest V0.7. But it seems that some bad changed make it  wrong. It's OK in fresco V0.6. Reproduce process:
1. Select Fresco--> Local
2. Scroll down the local images and stop randomly. 
3. Check if some images is failed to load(a pink block).

![20150906213114](https://cloud.githubusercontent.com/assets/1342575/9704562/a3756a62-54de-11e5-941d-8d04c1065825.png)

**Comment by tbruceyu** [comment]
It seems that something wrong with downsample option. After removing that configuration, comparison works well.

**Comment by tyronen** [comment]
How large are the images? We have had problems if they are very large.

**Comment by tbruceyu** [comment]
@tyronen These image are token by camera with a large size(average about 5M). I think the reason is that we  turn on the downsample option. This would disable resize option.

**Comment by tyronen** [comment]
Yes this is a confirmed issue - downsampling cannot yet be used for large images.
