### ISSUE TITLE
how to load unknown size images in a listview? 

### ISSUE THREAD

**Issue by heyanyanchina123** [facebook/fresco#594]
because all my images are fetched from Internet, I only know the images' url, but I don't know the images' size

**Comment by springhi2013** [comment]
I would also like to know

**Comment by eldk** [comment]
Hello,

You should look here and use : "Fixing the aspect ratio" with the width set (or MATCH_PARENT) and the height to WRAP_CONTENT.

->http://frescolib.org/docs/using-drawees-xml.html#_

Greatings,

Eric

**Comment by tyronen** [comment]
What Eric said.

Also, you don't always need to know the size of the image. If it's not too large, you can simply set it into your ListView using standard Android layout parameters. Except `wrap_content,` which isn't supported except as Eric described above.

If you really need the size, you can set a [controller listener](http://frescolib.org/docs/listening-download-events.html#_) and examine the `ImageInfo` object passed in; it will tell you the size.
