### ISSUE TITLE
load large png images not smooth

### ISSUE THREAD

**Issue by limingwei234** [facebook/fresco#601]
i load the image list of sdcard and scroll fast . the listview scroll not smooth.

**Comment by IanChilds** [comment]
What version are you using?

**Comment by limingwei234** [comment]
both 0.6.0 and 0.7.0 exist the condition.



limingwei234@163.com
 
From: IanChilds
Date: 2015-09-10 17:52
To: facebook/fresco
CC: limingwei234
Subject: Re: [fresco] load sdcard images not smooth (#601)
What version are you using?

**Comment by tyronen** [comment]
What images is your app loading? How large are they? Are you resizing?

**Comment by limingwei234** [comment]
@tyronen I load all images of SDCard, include screenshots, there are about 1500 image.  The large of screenshot image is about 100KB.  I resize the image size to 100*100 px.

**Comment by tyronen** [comment]
How are you attaching each image to a view. Are you using SimpleDraweeViews with the URI set to the file path on sdcard? This would be the recommended approach.

Or are you using ImagePipeline to load everything at once and then placing them in your child views?

**Comment by starkingwx** [comment]
How to resize large png image with fresco?
When I load large png images from sdcard page will be quite slow

**Comment by lushan1314** [comment]
same questions...version 0.8.1 ,load png image ,size is 1440x2560 , and resized it,still slow

**Comment by lushan1314** [comment]
sorry,chinese document is a little delay.

i was find a way solve it,__ImagePipelineConfig.newBuilder(...).setDownsampleEnabled(true)...__

**Comment by AllenVork** [comment]
//downsample image       
 val config = ImagePipelineConfig.newBuilder(this)
                .setDownsampleEnabled(true)
                .build();
        Fresco.initialize(this, config);

//resize image
        val request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(ResizeOptions(width, height)).build()

        val controller = Fresco.newDraweeControllerBuilder()
                .setOldController(view.controller)
                .setImageRequest(request)
                .build()
        view.controller = controller

i have done both the things above .but when i scroll the recyclerview, it's not smooth at all.
by the way,what i load is the local image through "file://imagePath"

anyone who can help?
