### ISSUE TITLE
Only download images in wifi

### ISSUE THREAD

**Issue by WoookLiu** [facebook/fresco#602]
When the phone has no wifi connection, I want to disable the image downloading. How can I do that?

**Comment by IanChilds** [comment]
Fresco does not support this out of the box. You could write a NetworkFetcher that enabled this functionality though. Just check what kind of connection the phone has before sending the download request for the image.

**Comment by WoookLiu** [comment]
Ok, I did that by OkHttpNetworkIntercepter.
