### ISSUE TITLE
com.facebook.imagepipeline.bitmaps.TooManyBitmapsException

### ISSUE THREAD

**Issue by hzq19920817** [facebook/fresco#604]
com.facebook.imagepipeline.bitmaps.TooManyBitmapsException

**Comment by massimocarli** [comment]
This is an Exception we throw when the number/memory of Bitmap allocated exceed the values configured. Could you please add more information to the possible question?

**Comment by hzq19920817** [comment]
there is a lisview ,and Each item has a GridView,well,In this GridView it will load 9 pic.Each pic is not more than 50kb

ImageRequest request = ImageRequestBuilder
				    .newBuilderWithSource(Uri.parse(imageurl))
				    .setAutoRotateEnabled(true)
				    .setLocalThumbnailPreviewsEnabled(true)
				    .setLowestPermittedRequestLevel(RequestLevel.FULL_FETCH)
				    .setProgressiveRenderingEnabled(false)
				    .build();
			PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
				    .setImageRequest(request)
				    .setOldController(mImageView.getController()).setControllerListener(controllerListener)
				    .build();
			mImageView.setController(controller);

**Comment by massimocarli** [comment]
The use case is similar to our demo apps. Please use those apps as reference for your application.
