### ISSUE TITLE
How can i use libjpeg-turbo to save image on SDCard?

### ISSUE THREAD

**Issue by zhangtengchao** [facebook/fresco#608]
I find fresco contain libjpeg-turbo. How can i use libjpeg-turbo to save image on SDCard? Is There a method which can save image on SDCard in Fresco?

**Comment by IanChilds** [comment]
Fresco doesn't have such a method I'm afraid. 

You can probably use the code provided by @mkrcpp in #603 to get the file you want, and then just save that to the SD card.
