### ISSUE TITLE
incorrect documentation for image prefetching. 

### ISSUE THREAD

**Issue by yrizk** [facebook/fresco#609]
In order to implement image pre-fetching, we get the `ImagePipeline` and call `prefetchToBitmapCache` on it. however, both the API Javadoc (http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/core/ImagePipeline.html#prefetchToBitmapCache(com.facebook.imagepipeline.request.ImageRequest, java.lang.Object) and the plain doc (http://frescolib.org/docs/using-image-pipeline.html#) are incorrect. specifically , they leave out the description and example for what the second method parameter is. I am talking about the `Object callerContext` . which since its an object isn't an android `Context`. I'm guessing that because the type is an object, not a Context. Could the documentation be updated and/or someone explain what the caller context is supposed to be? 
Thank you!

**Comment by massimocarli** [comment]
Thanks for the note. We're working to integrate the callerContext into the documentation.

**Comment by aphexcx** [comment]
Hi, sorry to reopen, but there's nothing online anywhere about what the correct object to pass in for callerContext should be. [This SO post says to pass in null](http://stackoverflow.com/questions/32830745/what-should-callercontext-param-be-for-frescos-prefetchtobitmapcache), but that's really unsettling. Can we get an unequivocal response? Should I use an Android Context (e.g. getActivity() or getContext()?

**Comment by lambdapioneer** [comment]
Hi @aphexcx, the caller context can be anything that you like. It's meant to allow you to pass information down the chain to your `RequestListener` or `ControllerListener`.

Applications might store metadata about the object that is helpful for their logging or error triage. E.g. the name of the current fragment.
