### ISSUE TITLE
Cannot load urls with redirect

### ISSUE THREAD

**Issue by kssilvoza** [facebook/fresco#61]
I am currently migrating our app to fresco but I encountered a problem. Whenever I try loading a url that redirects to another url to the SimpleDraweeView, the image does not load at all. How can I fix this?

**Comment by plamenko** [comment]
I think the OkHttp stack handles this correctly and we do provide OkHttp backend for our pipeline.
See: http://frescolib.org/docs/using-other-network-layers.html#_

**Comment by jagspage2013** [comment]
Excelent, this solves the problem.

I was trying to download a Facebook Profile Image via graph api url, but it has redirect, so I used @plamenko  solution and it worked.
