### ISSUE TITLE
still OOM ??

### ISSUE THREAD

**Issue by springhi2013** [facebook/fresco#611]
I am using fresco framework, fresco in listView, due to a number of Activity in a Tab, each Tab has a listView, so the program starts, the memory is full, the program will appear in the OOM, the use of a single picture in my program is relatively large, can not be set in the SimpleDraweeView image compression ratio, the image of a small number of small?

**Comment by massimocarli** [comment]
Please use our demo apps as a reference and be sure to resize the images before using them.

**Comment by tyronen** [comment]
http://frescolib.org/docs/resizing-rotating.html#_ provides instructions on doing this.
