### ISSUE TITLE
find interface

### ISSUE THREAD

**Issue by springhi2013** [facebook/fresco#612]
I can give a picture of the URL, directly back to the Bitmap, there is such an interface? SimpleDraweeView class, what happens if you call the setImageURI method frequently?

**Comment by tyronen** [comment]
If you just want a Bitmap, we can get it, but it is not recommended: http://frescolib.org/docs/datasources-datasubscribers.html#i-just-want-a-bitmap

You can call setImageURI as often as you want - Fresco will display the image in the last call.
