### ISSUE TITLE
Some gif images can not be loaded

### ISSUE THREAD

**Issue by YuhuihuiYang** [facebook/fresco#615]
hello , Some gif images can not be loaded,the problem has troubled me a long time

**Comment by massimocarli** [comment]
A simple test is to use the images that are not working with our demo applications. Can you please do that and tell us if it happens again? Better if tested with different version of the Android platform.

**Comment by YuhuihuiYang** [comment]
Thank you for your reply.
My test environment:
Fresco:0.7.0
android version: 5.0 and 4.4.2
The gif can be normal operation In the system photo album.

**Comment by tyronen** [comment]
Please show us the specific images that do not load.
