### ISSUE TITLE
JIT code cache full

### ISSUE THREAD

**Issue by sayah-y** [facebook/fresco#617]
Hello everyone,

I explain my problem. I have a mapView (canvas) with a lot of bitmaps. Everything is ok during my navigation. But, after a long time, images no longer appear.
When I see my log, I get : 
E/dalvikvm﹕ JIT code cache full

Do you have any idea ?

Thank you for your help.

**Comment by massimocarli** [comment]
Could you provide us some more information please? Are you using Drawee? If yes how are you instantiating them? From layout or from code?

**Comment by sayah-y** [comment]
Thank you for your help. I don't use Drawee, I am in a canvas, so I use your factory to download bitmaps and I draw them in my canvas:

        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(builder.mUri)
                .setLocalThumbnailPreviewsEnabled(true)
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                .setProgressiveRenderingEnabled(false)
                .build();
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest, builder.mContext);

        dataSource.subscribe(new BaseBitmapDataSubscriber() {
            @Override
            public void onNewResultImpl(@Nullable final Bitmap bitmap) {
                builder.mListener.mDataSource = null;
                handler.post(new Runnable() {
                    @Override
                    public void run() {
                        builder.mListener.onBitmapLoaded(bitmap);
                    }
                });
            }

            @Override
            public void onFailureImpl(DataSource dataSource) {
                builder.mListener.mDataSource = null;
                handler.post(new Runnable() {
                    @Override
                    public void run() {
                        builder.mListener.onBitmapFailed();
                    }
                });
            }
        }, CallerThreadExecutor.getInstance());

After, I draw the bitmap like that:

    canvas.drawBitmap(tile.mBitmap, null, mDest, TILE_PAINT);

**Comment by massimocarli** [comment]
The JIT code cache full problem seems to be completely unrelated to the image loading. Anyway I remind you that the Bitmap provided by the BaseBitmapDataSubscriber  to this method is only guaranteed to be around for the lifespan of the callback method. As JavaDoc says the framework will free the bitmap's memory after this method has completed. I suggest to use the BaseDataSubscriber instead and manage the returned CloseableImage as needed.

**Comment by sayah-y** [comment]
Now, I use BaseDataSubscriber and I manage the CloseableImage as needed.
When I want to recycle my bitmap, I execute : 

     CloseableReference.closeSafely(imageReference);

Everything is ok, I don't have any issue with the Memory.
But after a long time, I always have JIT code cache full problem.

**Comment by tyronen** [comment]
As @massimocarli said, this is not likely to be an issue with Fresco. But you can verify this. Can you comment Fresco out of your app and try it again? Do you then get the same problem?
