### ISSUE TITLE
AnimatedDrawable Example

### ISSUE THREAD

**Issue by sourabhv** [facebook/fresco#619]
Can you guys share an example of using `AnimatedDrawable` say to draw a bar below every SimpleDraweeView to show its progress? I couldn't find it in docs

**Comment by massimocarli** [comment]
The Comparison app uses that feature. It's as easy as what described here.

http://frescolib.org/docs/progress-bars.html#_

**Comment by sourabhv** [comment]
But that Progress bar is not animated smoothly, it changes with sudden steps whenever `onLevelChange` is called. I want smooth animation between those parts when `onLevelChange` is called. I tried the following code but  it didn't work  

	public class BorderProgressDrawable extends Drawable {

	    public static final String TAG = BorderProgressDrawable.class.getSimpleName();

	    private static final int MAX_LEVEL = 10000;
	    private static final int DURATION = 1000; // milliseconds

	    private int mLevel = 0;
	    private int mCurrentLevel = 0;
	    private Paint mPaint;
	    private ValueAnimator mAnimator;

	    public BorderProgressDrawable(Context context) {
	        mPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
	        mPaint.setColor(context.getResources().getColor(R.color.accent));
	        mPaint.setStrokeWidth((float) CommonMethods.dpToPx(context.getResources().getDisplayMetrics(), 4));
	    }

	    @Override
	    public void draw(final Canvas canvas) {
	        final int width = canvas.getWidth();
	        final int height = canvas.getHeight();

	        if (mAnimator != null) mAnimator.cancel();
	        mAnimator = ValueAnimator.ofInt(mCurrentLevel, mLevel);
	        mAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
	            @Override
	            public void onAnimationUpdate(ValueAnimator animation) {
	                mCurrentLevel = (int) animation.getAnimatedValue();
	                float visibleWidth = (((float) mCurrentLevel) / MAX_LEVEL) * width;
	                canvas.drawLine(0, height, visibleWidth, height, mPaint);
	            }
	        });

	        mAnimator.setDuration(DURATION);
	        mAnimator.start();
	    }

	    @Override
	    public void setAlpha(int i) {
	        mPaint.setAlpha(i);
	    }

	    @Override
	    public void setColorFilter(ColorFilter colorFilter) {
	        if (colorFilter != null) mPaint.setColorFilter(colorFilter);
	    }

	    @Override
	    public int getOpacity() {
	        return mPaint.getAlpha();
	    }

	    @Override
	    protected boolean onLevelChange(int level) {
	        if (mLevel != level) {
	            mLevel = level;
	            return true;
	        }
	        return false;
	    }

	}

**Comment by massimocarli** [comment]
I wouldn't create anything into the draw() method that should just "draw" what related to the current position of the ProgressBar. The easiest way, but not the best in terms of performance, is to manage the current position into the onLevelChange() triggering the invalidation of the View accordingly.
