### ISSUE TITLE
Rounding method cannot be changed and it has to be set during construction time.

### ISSUE THREAD

**Issue by msilemsile** [facebook/fresco#62]
RoundingParams roudParam = holder.image.getHierarchy().getRoundingParams();
                roudParam.setRoundAsCircle(true);
                holder.image.getHierarchy().setRoundingParams(roudParam);

**Comment by plamenko** [comment]
If you are specifying SimpleDraweeView in XML, then do `roundAsCircle="true"` there. If you are creating the hierarchy programmatically, then specify rounding params while building the hierarchy.
Basically, you need to tell the hierarchy at its construction time that you are going to use roudned corners, in order for hierarchy to preallocate some stuff.
