### ISSUE TITLE
Samples license 

### ISSUE THREAD

**Issue by arkty** [facebook/fresco#622]
Hello, 
i have some misunderstanding about license is samples? Is it OSS-like license? Is it possible to use code from samples in closed source projects(without modifying code)?
e.x: https://github.com/facebook/fresco/blob/master/samples/gestures/src/main/java/com/facebook/samples/gestures/MultiPointerGestureDetector.java (license header)

**Comment by tyronen** [comment]
Code licensed under our sample license may be used in closed source applications if it’s only for testing and evaluation purposes. It should not be shipped in a commercial application.
