### ISSUE TITLE
can not set image width and height,no example

### ISSUE THREAD

**Issue by yufan2014** [facebook/fresco#626]
can not set image width and height,no example

**Comment by yamateh** [comment]
you can see http://fresco-cn.org/docs/resizing-rotating.html#_

**Comment by tyronen** [comment]
You don't have to directly set the height and width of your image. You set them for your View, usually in XML as for any Android view. Fresco scales your image to match.

If the image is much larger than the view, and you can't get a smaller image, then you should use resizing as @yamateh says.
