### ISSUE TITLE
How do I add Zoomable library via gradle

### ISSUE THREAD

**Issue by riinav** [facebook/fresco#628]
Since I do not want to manually copy and paste those files into my project, Is there a way to add them via gradle, without which I need to keep tap on weather there is any code change or not.

**Comment by tyronen** [comment]
The zoomable library is not under the same BSD license as the rest of Fresco and therefore can't be included in the same download. Right now, I'm afraid that does mean downloading the source.

**Comment by jhass** [comment]
What about providing a separate artifact with its own license?

**Comment by Gnzlt** [comment]
It would still be really useful
