### ISSUE TITLE
i can't running the project 

### ISSUE THREAD

**Issue by chenjy2015** [facebook/fresco#63]
i get the projcet from github. and i  think  has a android library no found . the android library name is  com.facebook.drawee or com.facebook.imagepipeline.can you tell me why ?

**Comment by tyronen** [comment]
Can you paste the exact command you ran, and the output?

**Comment by chenjy2015** [comment]
i am a android developer man
i just want to running the project for android By fackbook fresco  
But the Android open source framework seems to configure a lot of trouble there are a lot of web on the development of things and JNI. This one I do not know
Can you tell me the specific configuration of GitHub above the Facebook fresco how to configure to separate running Android apps?
Thank you again for your answer！！！

**Comment by tyronen** [comment]
I admit I don't understand what you are writing.

Can you see if the answer to your question is found in our documentation? It is available in [English](http://frescolib.org/docs/index.html) and [Chinese](http://fresco-cn.org/docs/index.html).

If your native language is not English, it may be clearer to repeat your question in that language, and we may be able to find someone to help you.
