### ISSUE TITLE
document is not clear for saving bitmaps

### ISSUE THREAD

**Issue by Aravind-Rajendran** [facebook/fresco#632]
I was trying to save image using onclick listen.but its not working..in executor i am getting result as 1.0...

 

       ImagePipeline imagePipeline=Fresco.getImagePipeline();
             final DataSource<CloseableReference<PooledByteBuffer>> dataSource =
                     imagePipeline.fetchEncodedImage(request, context);

             final DataSubscriber<CloseableReference<PooledByteBuffer>> dataSubscriber =
                     new BaseDataSubscriber<CloseableReference<PooledByteBuffer>>() {
                         @Override
                         protected void onNewResultImpl(
                                 DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                             if (!dataSource.isFinished()) {
                                 Log.e(TAG,"Datasource is not finished");
                                 return;
                             }
                             CloseableReference<PooledByteBuffer> buffRef = dataSource.getResult();
                             if (buffRef != null) {
                                 PooledByteBufferInputStream is = new PooledByteBufferInputStream(buffRef.get());
                                 try {
                                     ImageFormat imageFormat = ImageFormatChecker.getImageFormat(is);
                                     Bitmap bitmap= BitmapFactory.decodeStream(is);
                                     Log.e(TAG,"bitmap widht and height"+bitmap.getWidth()+bitmap.getHeight());

                                     // TODO: write input stream to file
                                 } catch (Exception e) {

                                 } finally {
                                     Closeables.closeQuietly(is);
                                     CloseableReference.closeSafely(buffRef);
                                 }
                             }
                         }

                         @Override
                         public void onProgressUpdate(DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                             super.onProgressUpdate(dataSource);
                             Log.e(TAG,"onprogressupdate");
                         }

                         @Override
                         protected void onFailureImpl(
                                 DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                             Log.e(TAG,"failure");

                         }
                     };

             dataSource.subscribe(dataSubscriber, new Executor() {
                 @Override
                 public void execute(Runnable command) {
                     Log.e(TAG, "executeing commadnds" + dataSource.getProgress());

                 }
             });

**Comment by IanChilds** [comment]
The problem is that your Executor doesn't do anything except make a log. Apart from that you just want to follow the instructions on http://frescolib.org/docs/datasources-datasubscribers.html#i-just-want-a-bitmap, which you mostly seem to have done

**Comment by Aravind-Rajendran** [comment]
@IanChilds  if i write the code in  the executor its works fine and i can get bitmaps..
but the call back method which you mentioned there,never gets called

**Comment by IanChilds** [comment]
Which callback method is that?

**Comment by Aravind-Rajendran** [comment]
ImagePipeline imagePipeline = Fresco.getImagePipeline();
                final DataSource<CloseableReference<PooledByteBuffer>> dataSource =
                        imagePipeline.fetchEncodedImage(request, context);

                final DataSubscriber<CloseableReference<PooledByteBuffer>> dataSubscriber =
                        new BaseDataSubscriber<CloseableReference<PooledByteBuffer>>() {
                            @Override
                            protected void onNewResultImpl(
                                    DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                                if (!dataSource.isFinished()) {
                                    Log.e(TAG, "Datasource is not finished");
                                    return;
                                }
                                CloseableReference<PooledByteBuffer> buffRef = dataSource.getResult();
                                if (buffRef != null) {
                                    PooledByteBufferInputStream is = new PooledByteBufferInputStream(buffRef.get());
                                    try {
                                        ImageFormat imageFormat = ImageFormatChecker.getImageFormat(is);

                                        Bitmap bitmap = BitmapFactory.decodeStream(is);
                                        Log.e(TAG, "bitmap widht and height" + bitmap.getWidth() + bitmap.getHeight());

                                        // TODO: write input stream to file
                                    } catch (Exception e) {

                                    } finally {
                                        Closeables.closeQuietly(is);
                                        CloseableReference.closeSafely(buffRef);
                                    }
                                }
                            }

                            @Override
                            public void onProgressUpdate(DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                                super.onProgressUpdate(dataSource);
                                Log.e(TAG, "onprogressupdate");
                            }

                            @Override
                            protected void onFailureImpl(
                                    DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                                Log.e(TAG, "failure");

                            }
                        };

                dataSource.subscribe(dataSubscriber, new Executor() {
                    @Override
                    public void execute(Runnable command) {
                        CloseableReference<PooledByteBuffer> dataBuffer;
                        dataBuffer = dataSource.getResult();
                        PooledByteBufferInputStream is = new PooledByteBufferInputStream(dataBuffer.get());
                        Bitmap bitmap = BitmapFactory.decodeStream(is);
                        Log.e(TAG, "bitmap widht and height" + bitmap.getWidth() + bitmap.getHeight());                    

                        OutputStream outstream;
                        try {
                            outstream = context.getContentResolver().openOutputStream(uri);
                            bitmap.compress(Bitmap.CompressFormat.JPEG, 100, outstream);
                            outstream.close();
                        } catch (Exception e) {
                            System.err.println(e.toString());
                        }                      


                    
                    }
                });


onnewresultimpl never get called

**Comment by IanChilds** [comment]
Yeah, that is because you executor ignores the Runnable that is passed to it.

**Comment by Aravind-Rajendran** [comment]
@IanChilds  how to do it properly?

**Comment by IanChilds** [comment]
You need to call `command.run()`. I also suggest not creating a new executor for every request.

**Comment by Aravind-Rajendran** [comment]
thank u so much..i will try it out...
