### ISSUE TITLE
How to use Fresco to read any package's  gif image in the assets directory

### ISSUE THREAD

**Issue by shewenbiao** [facebook/fresco#633]
I know how to read the gif image in local package assets directory. The code is as follows:
```javascript
Uri uri = Uri.parse("asset:///" + image.gif);
DraweeController controller = Fresco.newDraweeControllerBuilder().setUri(uri).setAutoPlayAnimations(true).build(); imageView.setController(controller);
```
But now I need read gif image from other package assets, what should I do? Can you give me a suggestion?

**Comment by IanChilds** [comment]
what do you mean? There is a single assets folder per apk.

**Comment by shewenbiao** [comment]
@IanChilds I have two applications, such as A and B. Now, in A application, I want to get a gif image from B asset's folder. Using fresco can be achieved? Can you have a good suggestion? Thanks.

**Comment by IanChilds** [comment]
Fresco doesn't have the ability to do this for you, sorry.

**Comment by shewenbiao** [comment]
@IanChilds Anyway, I thank you very much.
