### ISSUE TITLE
some image loading is not complete

### ISSUE THREAD

**Issue by hahagod** [facebook/fresco#635]
I use ListViewForScrollView in the project. Lead to some pictures showed.
thanks.
![image](https://cloud.githubusercontent.com/assets/11895727/10158762/b3bb566c-66c6-11e5-981e-7f0ca8e28cb9.png)

**Comment by IanChilds** [comment]
What happens to the other pictures? Nothing is ever shown? Do they fail? 

Generally using a scrollview is a bad idea as you will retain all the images in memory. Why can't you just use a pure listview for your needs?
