### ISSUE TITLE
wrap_conent for very thin images

### ISSUE THREAD

**Issue by ffelini** [facebook/fresco#636]
Hello. I have an issue with "wrap_conent" height for remote thin images
onFinalImageSet i'm doint this
```
mSimpleDraweeView.setAspectRatio((float) imageInfo.getWidth() / imageInfo.getHeight());
```
This code code works fine for images were aspect ration is about 1 - 2

I have one special case.
I'm laoding a very thin image that should autofil his height, but for some reason it doesn't.
```
imageInfo.getWidth() = 641
imageInfo.getHeight() = 37
```
so aspectRatio is about 17

Image is resized about 3 times bigger than should be by height.

Here is the layout
```
 <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/thumbnail_image_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            fresco:actualImageScaleType="fitCenter" >
```
I think it happens only for very thin images because others with ( ex: 640x290) are resized properly.

Did anyone encountered this before?

**Comment by IanChilds** [comment]
Could you give the image url and a screenshot of the problem please? 

What do you mean by "it should autofill its height"?

**Comment by ffelini** [comment]
@IanChilds 
Here is the url of the image 
http://a.namshicdn.com/cms/vogue/men/2015/20042015/module_10_en.jpg

imageInfo.getWidth() = 640
imageInfo.getHeight() = 37
aspectRatio = 17

![device-2015-09-30-174520](https://cloud.githubusercontent.com/assets/1655758/10196473/b6e1172a-679b-11e5-8b29-fe9d987c226b.png)

The image has extra white space at bottom, the result of aspectRation equals to 17

Other images are properly resized 
http://a.namshicdn.com/cms/vogue/kids/2015/12082015/module_06_en.jpg
http://a.namshicdn.com/cms/vogue/kids/2015/04052015/module_05.jpg

imageInfo.getWidth() = 640
imageInfo.getHeight() = 290
aspectRatio = 2.2

**Comment by ffelini** [comment]
Guys any updates on this issue?
@IanChilds is it reproducible on your side?

**Comment by ffelini** [comment]
Gonna close this, after some long time finally found that issue was in my code :)
