### ISSUE TITLE
WebM support

### ISSUE THREAD

**Issue by pabloogc** [facebook/fresco#639]
Since WebP is already supported and Android also supports WebM is there any plan to get this feature into Fresco?

The current solution using a MediaPlayer / TextureView / other has a lot of drawbacks, it's really hard to get "right" and does not benefit from Fresco memory handling.

If there is no support for WebM expected: What is the best way to let Fresco handle WebM memory natively and hook the result to a MediaPlayer (if possible)?

Thank you for your time.

**Comment by aagnes** [comment]
Fresco is mainly target in handling images. We don't have a plan to support WebM right now.

**Comment by tyronen** [comment]
Encoded images are simply bytes. You could use Fresco's [encoded image ability](http://frescolib.org/docs/using-image-pipeline.html#skipping-the-decode) and then pass the bytes to a video decoder instead of an image decoder.
