### ISSUE TITLE
Minor API Change: expose getId() on DraweeController interface

### ISSUE THREAD

**Issue by j-houston** [facebook/fresco#641]
Both ControllerListener and BaseControllerList provide callbacks that include the controller ID as a parameter, but DraweeController does not include getId() as an interface method. The only way to find out the ID of the controller (for shared ControllerListener instances) is to downcast to AbstractDraweeController.

**Comment by kirwan** [comment]
I'm cleaning up very old issues. If this is still something you think is needed please comment and we can re-open.
