### ISSUE TITLE
Images are not loading in Jellybean Genymotion

### ISSUE THREAD

**Issue by himgupta** [facebook/fresco#643]
Hi,

When I am trying to load image from server the images are not getting loaded.I am attaching the logs for your reference.Same code is working fine for Nexus 5 emulator.Can someone help me in this regard.
<com.facebook.drawee.view.SimpleDraweeView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:id="@+id/imageview"
    android:layout_width="250dp"
    android:layout_height="match_parent"
    fresco:actualImageScaleType="fitCenter"
/>

10-01 12:01:14.014      736-736/  E/﹕ [ 10-01 12:01:14.058   736:  736 V/unknown:AbstractDraweeController ]
    controller 5362c6e8 null -> 0: initialize
10-01 12:01:14.058      736-736/  V/unknown:AbstractDraweeController﹕ controller 5362c6e8 0: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@53836bc4
10-01 12:01:14.062      736-736/  V/unknown:AbstractDraweeController﹕ controller 5362c6e8 0: onAttach: request needs submit
10-01 12:01:14.062      736-736/  V/unknown:PipelineDraweeController﹕ controller 5362c6e8: getDataSource
10-01 12:01:14.070      736-736/  V/unknown:RequestLoggingListener﹕ time 4729369: onRequestSubmit: {requestId: 0, callerContext: null, isPrefetch: false}
10-01 12:01:14.070      736-736/  V/unknown:RequestLoggingListener﹕ time 4729370: onProducerStart: {requestId: 0, producer: BitmapMemoryCacheGetProducer}
10-01 12:01:14.078      736-736/  V/unknown:RequestLoggingListener﹕ time 4729376: onProducerFinishWithSuccess: {requestId: 0, producer: BitmapMemoryCacheGetProducer, elapsedTime: 6 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.078      736-736/  V/unknown:RequestLoggingListener﹕ time 4729377: onProducerStart: {requestId: 0, producer: BackgroundThreadHandoffProducer}
10-01 12:01:14.078      736-736/  V/unknown:AbstractDraweeController﹕ controller 5362c6e8 0: submitRequest: dataSource: 53ca5f84
10-01 12:01:14.082      736-736/  V/unknown:AbstractDraweeController﹕ controller 5379f294 null -> 1: initialize
10-01 12:01:14.082      736-736/  V/unknown:AbstractDraweeController﹕ controller 5379f294 1: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@53655bb8
10-01 12:01:14.082      736-736/  V/unknown:AbstractDraweeController﹕ controller 5379f294 1 -> 2: initialize
10-01 12:01:14.086      736-736/  V/unknown:AbstractDraweeController﹕ controller 5379f294 2: setHierarchy: null
10-01 12:01:14.086      736-736/  V/unknown:AbstractDraweeController﹕ controller 5379f294 2: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@53655bb8
10-01 12:01:14.090     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729389: onProducerFinishWithSuccess: {requestId: 0, producer: BackgroundThreadHandoffProducer, elapsedTime: 12 ms, extraMap: null}
10-01 12:01:14.098     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729398: onProducerStart: {requestId: 0, producer: BitmapMemoryCacheProducer}
10-01 12:01:14.102      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 null -> 3: initialize
10-01 12:01:14.102      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 3: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@537b63a4
10-01 12:01:14.106      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 3 -> 4: initialize
10-01 12:01:14.106      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 4: setHierarchy: null
10-01 12:01:14.106      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 4: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@537b63a4
10-01 12:01:14.106      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 4: onAttach: request needs submit
10-01 12:01:14.106      736-736/  V/unknown:PipelineDraweeController﹕ controller 53c7db38: getDataSource
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729409: onRequestSubmit: {requestId: 1, callerContext: null, isPrefetch: false}
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729409: onProducerStart: {requestId: 1, producer: BitmapMemoryCacheGetProducer}
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729409: onProducerFinishWithSuccess: {requestId: 1, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729409: onProducerStart: {requestId: 1, producer: BackgroundThreadHandoffProducer}
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 4: submitRequest: dataSource: 537c2a2c
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 null -> 5: initialize
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 5: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@537ec918
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 5 -> 6: initialize
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 6: setHierarchy: null
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 6: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@537ec918
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 6: onAttach: request needs submit
10-01 12:01:14.110      736-736/  V/unknown:PipelineDraweeController﹕ controller 53cae570: getDataSource
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729411: onRequestSubmit: {requestId: 2, callerContext: null, isPrefetch: false}
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729411: onProducerStart: {requestId: 2, producer: BitmapMemoryCacheGetProducer}
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729411: onProducerFinishWithSuccess: {requestId: 2, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.110      736-736/  V/unknown:RequestLoggingListener﹕ time 4729411: onProducerStart: {requestId: 2, producer: BackgroundThreadHandoffProducer}
10-01 12:01:14.110      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 6: submitRequest: dataSource: 537e53cc
10-01 12:01:14.122      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc null -> 7: initialize
10-01 12:01:14.122      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc 7: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@535c8d1c
10-01 12:01:14.122      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc 7 -> 8: initialize
10-01 12:01:14.122      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc 8: setHierarchy: null
10-01 12:01:14.122      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc 8: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@535c8d1c
10-01 12:01:14.122      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc 8: onAttach: request needs submit
10-01 12:01:14.126      736-736/  V/unknown:PipelineDraweeController﹕ controller 537ed9cc: getDataSource
10-01 12:01:14.126      736-736/  V/unknown:RequestLoggingListener﹕ time 4729427: onRequestSubmit: {requestId: 3, callerContext: null, isPrefetch: false}
10-01 12:01:14.134      736-736/  V/unknown:RequestLoggingListener﹕ time 4729433: onProducerStart: {requestId: 3, producer: BitmapMemoryCacheGetProducer}
10-01 12:01:14.134      736-736/  V/unknown:RequestLoggingListener﹕ time 4729433: onProducerFinishWithSuccess: {requestId: 3, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.134      736-736/  V/unknown:RequestLoggingListener﹕ time 4729433: onProducerStart: {requestId: 3, producer: BackgroundThreadHandoffProducer}
10-01 12:01:14.134      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc 8: submitRequest: dataSource: 537f4958
10-01 12:01:14.138     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729440: onProducerFinishWithSuccess: {requestId: 0, producer: BitmapMemoryCacheProducer, elapsedTime: 42 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.174     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729472: onProducerStart: {requestId: 0, producer: EncodedMemoryCacheProducer}
10-01 12:01:14.182     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729473: onProducerFinishWithSuccess: {requestId: 0, producer: EncodedMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.182     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729481: onProducerStart: {requestId: 0, producer: DiskCacheProducer}
10-01 12:01:14.182      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb93226e8): name, size, mSize = 516, 3552, 4879016
10-01 12:01:14.186      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb9357e88): name, size, mSize = 517, 94080, 4973096
10-01 12:01:14.198      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb9174520): name, size, mSize = 520, 36208, 5009304
10-01 12:01:14.202     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729503: onProducerFinishWithSuccess: {requestId: 1, producer: BackgroundThreadHandoffProducer, elapsedTime: 94 ms, extraMap: null}
10-01 12:01:14.202     736-1108/  V/unknown:BufferedDiskCache﹕ Did not find image for http://url/images/dealercallbacklogo/hyundai_logo.jpg in staging area
10-01 12:01:14.202     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729503: onProducerStart: {requestId: 1, producer: BitmapMemoryCacheProducer}
10-01 12:01:14.202     736-1108/  V/unknown:BufferedDiskCache﹕ Disk cache read for http://url/images/dealercallbacklogo/hyundai_logo.jpg
10-01 12:01:14.202     736-1108/  D/unknown:DefaultDiskStorageSupplier﹕ Created cache directory /data/data/ /cache/image_cache
10-01 12:01:14.206     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729504: onProducerFinishWithSuccess: {requestId: 1, producer: BitmapMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.206     736-1108/  V/unknown:BufferedDiskCache﹕ Found entry in disk cache for http://url/images/dealercallbacklogo/hyundai_logo.jpg
10-01 12:01:14.206     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729505: onProducerStart: {requestId: 1, producer: EncodedMemoryCacheProducer}
10-01 12:01:14.206     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729506: onProducerFinishWithSuccess: {requestId: 1, producer: EncodedMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.206     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729506: onProducerStart: {requestId: 1, producer: DiskCacheProducer}
10-01 12:01:14.210     736-1108/  D/dalvikvm﹕ Trying to load lib /data/data/ /lib/libmemchunk.so 0xa6aeff10
10-01 12:01:14.214     736-1108/  D/dalvikvm﹕ Added shared lib /data/data/ /lib/libmemchunk.so 0xa6aeff10
10-01 12:01:14.214     736-1108/  V/unknown:NativeMemoryChunkPool﹕ Used = (1, 4096); Free = (0, 0)
10-01 12:01:14.214     736-1108/  V/unknown:NativeMemoryChunkPool﹕ get (alloc) (object, size) = (537daf20, 4096)
10-01 12:01:14.222     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729519: onProducerFinishWithSuccess: {requestId: 2, producer: BackgroundThreadHandoffProducer, elapsedTime: 108 ms, extraMap: null}
10-01 12:01:14.238     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729536: onProducerStart: {requestId: 2, producer: BitmapMemoryCacheProducer}
10-01 12:01:14.238     736-1109/  V/unknown:BufferedDiskCache﹕ Did not find image for http://url/images/car-images/320x224/Hyundai/Hyundai-i10/pure-white.jpg in staging area
10-01 12:01:14.238     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729537: onProducerFinishWithSuccess: {requestId: 2, producer: BitmapMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.238     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729538: onProducerStart: {requestId: 2, producer: EncodedMemoryCacheProducer}
10-01 12:01:14.238     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729539: onProducerFinishWithSuccess: {requestId: 2, producer: EncodedMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.242     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729540: onProducerStart: {requestId: 2, producer: DiskCacheProducer}
10-01 12:01:14.246     736-1109/  V/unknown:BufferedDiskCache﹕ Disk cache read for http://url/images/car-images/320x224/Hyundai/Hyundai-i10/pure-white.jpg
10-01 12:01:14.246     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729545: onProducerFinishWithSuccess: {requestId: 3, producer: BackgroundThreadHandoffProducer, elapsedTime: 112 ms, extraMap: null}
10-01 12:01:14.246     736-1109/  V/unknown:BufferedDiskCache﹕ Found entry in disk cache for http://url/images/car-images/320x224/Hyundai/Hyundai-i10/pure-white.jpg
10-01 12:01:14.246     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729547: onProducerStart: {requestId: 3, producer: BitmapMemoryCacheProducer}
10-01 12:01:14.246     736-1109/  V/unknown:NativeMemoryChunkPool﹕ Used = (2, 20480); Free = (0, 0)
10-01 12:01:14.250     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729548: onProducerFinishWithSuccess: {requestId: 3, producer: BitmapMemoryCacheProducer, elapsedTime: 1 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.258     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729550: onProducerStart: {requestId: 3, producer: EncodedMemoryCacheProducer}
10-01 12:01:14.258     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729556: onProducerFinishWithSuccess: {requestId: 3, producer: EncodedMemoryCacheProducer, elapsedTime: 6 ms, extraMap: {cached_value_found=false}}
10-01 12:01:14.258     736-1107/  V/unknown:RequestLoggingListener﹕ time 4729556: onProducerStart: {requestId: 3, producer: DiskCacheProducer}
10-01 12:01:14.258     736-1109/  V/unknown:NativeMemoryChunkPool﹕ get (alloc) (object, size) = (53c84970, 16384)
10-01 12:01:14.270     736-1108/  V/unknown:GenericByteArrayPool﹕ Used = (1, 16384); Free = (0, 0)
10-01 12:01:14.274     736-1108/  V/unknown:GenericByteArrayPool﹕ get (alloc) (object, size) = (537cef88, 16384)
10-01 12:01:14.294     736-1108/  V/unknown:GenericByteArrayPool﹕ release (reuse) (object, size) = (537cef88, 16384)
10-01 12:01:14.294     736-1108/  V/unknown:GenericByteArrayPool﹕ Used = (0, 0); Free = (1, 16384)
10-01 12:01:14.298     736-1108/  V/unknown:BufferedDiskCache﹕ Successful read from disk cache for http://url/images/dealercallbacklogo/hyundai_logo.jpg
10-01 12:01:14.298     736-1108/  V/unknown:RequestLoggingListener﹕ time 4729598: onProducerFinishWithSuccess: {requestId: 0, producer: DiskCacheProducer, elapsedTime: 117 ms, extraMap: {cached_value_found=true}}
10-01 12:01:14.318     736-1109/  V/unknown:GenericByteArrayPool﹕ Used = (1, 16384); Free = (0, 0)
10-01 12:01:14.318     736-1109/  V/unknown:GenericByteArrayPool﹕ get (reuse) (object, size) = (537cef88, 16384)
10-01 12:01:14.318     736-1109/  V/unknown:GenericByteArrayPool﹕ release (reuse) (object, size) = (537cef88, 16384)
10-01 12:01:14.318     736-1109/  V/unknown:GenericByteArrayPool﹕ Used = (0, 0); Free = (1, 16384)
10-01 12:01:14.318     736-1109/  V/unknown:BufferedDiskCache﹕ Successful read from disk cache for http://url/images/car-images/320x224/Hyundai/Hyundai-i10/pure-white.jpg
10-01 12:01:14.326     736-1109/  V/unknown:RequestLoggingListener﹕ time 4729624: onProducerFinishWithSuccess: {requestId: 1, producer: DiskCacheProducer, elapsedTime: 118 ms, extraMap: {cached_value_found=true}}
10-01 12:01:14.326      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb9176a30): name, size, mSize = 527, 27556, 5036860
10-01 12:01:14.350     736-1108/  I/dalvikvm﹕ Could not find method android.graphics.Bitmap.getAllocationByteCount, referenced from method com.facebook.imageutils.BitmapUtil.getSizeInBytes
10-01 12:01:14.350     736-1108/  W/dalvikvm﹕ VFY: unable to resolve virtual method 806: Landroid/graphics/Bitmap;.getAllocationByteCount ()I
10-01 12:01:14.350     736-1108/  D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x000a
10-01 12:01:14.362     736-1108/  I/unknown:TiffUtil﹕ Unsupported orientation
10-01 12:01:14.362     736-1109/  I/unknown:TiffUtil﹕ Unsupported orientation
10-01 12:01:14.362     736-1109/  V/unknown:BufferedDiskCache﹕ Did not find image for http://url/images/car-images/320x224/Hyundai/Hyundai-i20-Active/Phantom-Black.jpg in staging area
10-01 12:01:14.362     736-1109/  V/unknown:BufferedDiskCache﹕ Disk cache read for http://url/images/car-images/320x224/Hyundai/Hyundai-i20-Active/Phantom-Black.jpg
10-01 12:01:14.366     736-1109/  V/unknown:BufferedDiskCache﹕ Found entry in disk cache for http://url/images/car-images/320x224/Hyundai/Hyundai-i20-Active/Phantom-Black.jpg
10-01 12:01:14.366     736-1109/  V/unknown:NativeMemoryChunkPool﹕ Used = (3, 36864); Free = (0, 0)
10-01 12:01:14.366     736-1109/  V/unknown:NativeMemoryChunkPool﹕ get (alloc) (object, size) = (54010740, 16384)
10-01 12:01:14.366     736-1109/  V/unknown:GenericByteArrayPool﹕ Used = (1, 16384); Free = (0, 0)
10-01 12:01:14.366     736-1109/  V/unknown:GenericByteArrayPool﹕ get (reuse) (object, size) = (537cef88, 16384)
10-01 12:01:14.366     736-1109/  V/unknown:GenericByteArrayPool﹕ release (reuse) (object, size) = (537cef88, 16384)
10-01 12:01:14.394     736-1108/  V/unknown:BufferedDiskCache﹕ Did not find image for http://url/images/car-images/320x224/Hyundai/Hyundai-Santa-Fe/Red-Wine.jpg in staging area
10-01 12:01:14.394     736-1108/  V/unknown:BufferedDiskCache﹕ Disk cache read for http://url/images/car-images/320x224/Hyundai/Hyundai-Santa-Fe/Red-Wine.jpg
10-01 12:01:14.398     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729699: onProducerStart: {requestId: 0, producer: DecodeProducer}
10-01 12:01:14.398     736-1109/  V/unknown:GenericByteArrayPool﹕ Used = (0, 0); Free = (1, 16384)
10-01 12:01:14.398     736-1109/  V/unknown:BufferedDiskCache﹕ Successful read from disk cache for http://url/images/car-images/320x224/Hyundai/Hyundai-i20-Active/Phantom-Black.jpg
10-01 12:01:14.414     736-1110/  I/dalvikvm﹕ Could not find method android.graphics.Bitmap.getAllocationByteCount, referenced from method com.facebook.imagepipeline.nativecode.Bitmaps.reconfigureBitmap
10-01 12:01:14.414     736-1109/  V/unknown:RequestLoggingListener﹕ time 4729712: onProducerFinishWithSuccess: {requestId: 2, producer: DiskCacheProducer, elapsedTime: 172 ms, extraMap: {cached_value_found=true}}
10-01 12:01:14.414     736-1110/  W/dalvikvm﹕ VFY: unable to resolve virtual method 409: Landroid/graphics/Bitmap;.getAllocationByteCount ()I
10-01 12:01:14.414     736-1110/  D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0000
10-01 12:01:14.430     736-1110/  D/dalvikvm﹕ Trying to load lib /data/data/ /lib/libbitmaps.so 0xa6aeff10
10-01 12:01:14.446     736-1110/  D/dalvikvm﹕ Added shared lib /data/data/ /lib/libbitmaps.so 0xa6aeff10
10-01 12:01:14.490     736-1110/  D/dalvikvm﹕ GC_FOR_ALLOC freed 9506K, 34% free 20194K/30215K, paused 43ms, total 44ms
10-01 12:01:14.494     736-1109/  I/unknown:TiffUtil﹕ Unsupported orientation
10-01 12:01:14.494     736-1108/  V/unknown:BufferedDiskCache﹕ Found entry in disk cache for http://url/images/car-images/320x224/Hyundai/Hyundai-Santa-Fe/Red-Wine.jpg
10-01 12:01:14.494     736-1108/  V/unknown:NativeMemoryChunkPool﹕ Used = (4, 53248); Free = (0, 0)
10-01 12:01:14.494     736-1108/  V/unknown:NativeMemoryChunkPool﹕ get (alloc) (object, size) = (53c9b614, 16384)
10-01 12:01:14.494     736-1108/  V/unknown:GenericByteArrayPool﹕ Used = (1, 16384); Free = (0, 0)
10-01 12:01:14.494     736-1108/  V/unknown:GenericByteArrayPool﹕ get (reuse) (object, size) = (537cef88, 16384)
10-01 12:01:14.494     736-1108/  V/unknown:GenericByteArrayPool﹕ release (reuse) (object, size) = (537cef88, 16384)
10-01 12:01:14.494     736-1108/  V/unknown:GenericByteArrayPool﹕ Used = (0, 0); Free = (1, 16384)
10-01 12:01:14.494     736-1108/  V/unknown:BufferedDiskCache﹕ Successful read from disk cache for <url>
10-01 12:01:14.498     736-1108/  V/unknown:RequestLoggingListener﹕ time 4729794: onProducerFinishWithSuccess: {requestId: 3, producer: DiskCacheProducer, elapsedTime: 238 ms, extraMap: {cached_value_found=true}}
10-01 12:01:14.498     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (1, 131072); Free = (0, 0)
10-01 12:01:14.498     736-1110/  V/unknown:SoftRefByteArrayPool﹕ get (alloc) (object, size) = (53837490, 131072)
10-01 12:01:14.498     736-1108/  I/unknown:TiffUtil﹕ Unsupported orientation
10-01 12:01:14.506     736-1110/  V/unknown:SoftRefByteArrayPool﹕ release (reuse) (object, size) = (53837490, 131072)
10-01 12:01:14.506     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (0, 0); Free = (1, 131072)
10-01 12:01:14.506     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729806: onProducerFinishWithSuccess: {requestId: 0, producer: DecodeProducer, elapsedTime: 107 ms, extraMap: {queueTime=35, bitmapSize=89x50, isFinal=true, hasGoodQuality=true}}
10-01 12:01:14.522     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729823: onRequestSuccess: {requestId: 0, elapsedTime: 454 ms}
10-01 12:01:14.522     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729823: onProducerStart: {requestId: 1, producer: DecodeProducer}
10-01 12:01:14.526     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (1, 131072); Free = (0, 0)
10-01 12:01:14.538     736-1110/  V/unknown:SoftRefByteArrayPool﹕ get (reuse) (object, size) = (53837490, 131072)
10-01 12:01:14.546      736-736/  V/unknown:AbstractDraweeController﹕ controller 5362c6e8 0: set_final_result @ onNewResult: image: CloseableReference 535fdc9c
10-01 12:01:14.566     736-1110/  V/unknown:SoftRefByteArrayPool﹕ release (reuse) (object, size) = (53837490, 131072)
10-01 12:01:14.566     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (0, 0); Free = (1, 131072)
10-01 12:01:14.578     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729874: onProducerFinishWithSuccess: {requestId: 1, producer: DecodeProducer, elapsedTime: 51 ms, extraMap: {queueTime=159, bitmapSize=320x224, isFinal=true, hasGoodQuality=true}}
10-01 12:01:14.582     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729880: onRequestSuccess: {requestId: 1, elapsedTime: 471 ms}
10-01 12:01:14.594     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729895: onProducerStart: {requestId: 2, producer: DecodeProducer}
10-01 12:01:14.594     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (1, 131072); Free = (0, 0)
10-01 12:01:14.598     736-1110/  V/unknown:SoftRefByteArrayPool﹕ get (reuse) (object, size) = (53837490, 131072)
10-01 12:01:14.622     736-1110/  V/unknown:SoftRefByteArrayPool﹕ release (reuse) (object, size) = (53837490, 131072)
10-01 12:01:14.622     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (0, 0); Free = (1, 131072)
10-01 12:01:14.622     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729923: onProducerFinishWithSuccess: {requestId: 2, producer: DecodeProducer, elapsedTime: 28 ms, extraMap: {queueTime=99, bitmapSize=320x224, isFinal=true, hasGoodQuality=true}}
10-01 12:01:14.622     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729923: onRequestSuccess: {requestId: 2, elapsedTime: 512 ms}
10-01 12:01:14.626     736-1110/  V/unknown:RequestLoggingListener﹕ time 4729924: onProducerStart: {requestId: 3, producer: DecodeProducer}
10-01 12:01:14.626     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (1, 131072); Free = (0, 0)
10-01 12:01:14.634     736-1110/  V/unknown:SoftRefByteArrayPool﹕ get (reuse) (object, size) = (53837490, 131072)
10-01 12:01:14.642      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb9173900): name, size, mSize = 540, 17800, 5054660
10-01 12:01:14.690      736-736/  V/unknown:AbstractDraweeController﹕ controller 53c7db38 4: set_final_result @ onNewResult: image: CloseableReference 535a8054
10-01 12:01:14.698      736-736/  V/unknown:AbstractDraweeController﹕ controller 53cae570 6: set_final_result @ onNewResult: image: CloseableReference 535a4bd8
10-01 12:01:14.730     736-1110/  V/unknown:SoftRefByteArrayPool﹕ release (reuse) (object, size) = (53837490, 131072)
10-01 12:01:14.730     736-1110/  V/unknown:SoftRefByteArrayPool﹕ Used = (0, 0); Free = (1, 131072)
10-01 12:01:14.734      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb9356fb8): name, size, mSize = 545, 286720, 5341380
10-01 12:01:14.742     736-1110/  V/unknown:RequestLoggingListener﹕ time 4730043: onProducerFinishWithSuccess: {requestId: 3, producer: DecodeProducer, elapsedTime: 119 ms, extraMap: {queueTime=121, bitmapSize=320x224, isFinal=true, hasGoodQuality=true}}
10-01 12:01:14.746      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb937ac70): name, size, mSize = 547, 286720, 5628100
10-01 12:01:14.750     736-1110/  V/unknown:RequestLoggingListener﹕ time 4730049: onRequestSuccess: {requestId: 3, elapsedTime: 619 ms}
10-01 12:01:14.774      736-736/  V/unknown:AbstractDraweeController﹕ controller 537ed9cc 8: set_final_result @ onNewResult: image: CloseableReference 5356f440
10-01 12:01:14.814      736-736/  D/OpenGLRenderer﹕ TextureCache::get: create texture(0xb930e2c8): name, size, mSize = 552, 286720, 5914820
10-01 12:01:28.674      736-921/  W/DebugConnManager﹕ getNetworkInfo() on networkType 1

**Comment by aagnes** [comment]
which os version specific and device type of genymotion are you using?

**Comment by himgupta** [comment]
I am using genymotion Samsung Galaxy S2 ,OS-4.1.1

**Comment by himgupta** [comment]
@aagnes  Did you find the cause for the issue?

**Comment by aagnes** [comment]
I used your code in SimpleDraweeView to get a network image. It's working properly. Where is the image resource? And can you share more code for using the DraweeView?

**Comment by adityasaxena** [comment]
It's probably an issue with Jellybean devices with certain formats the images get saved with. Experiencing the same issue with lots of images in a mobile app
