### ISSUE TITLE
can't get bitmap from DataSource.scribe

### ISSUE THREAD

**Issue by Kaushik1502** [facebook/fresco#644]
can not get the bitmap in onActivityResult after selecting a picture from gallery or taking picture from camera though I am using  `ImagePipeline` . Here is the code snippet

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
   super.onActivityResult(requestCode, resultCode, data);
   if (resultCode == Activity.RESULT_OK) {
       switch (requestCode) {
          case ACTION_OPEN_GALLERY:
              mImageCaptureUri = data.getData();
          case ACTION_OPEN_CAMERA:
              if (mImageCaptureUri != null) {
                  //String path = MyApp.getInstance().getPath(this, mImageCaptureUri);

                  ImageRequest imageRequest = ImageRequestBuilder
                                .newBuilderWithSource(mImageCaptureUri)
                                .setRequestPriority(Priority.HIGH)
                                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                                .build();
                  ImagePipeline imagePipeline = Fresco.getImagePipeline();
                  DataSource<CloseableReference<CloseableImage>>
                          dataSource = imagePipeline.fetchDecodedImage(imageRequest, ProfileMainActivity.this);
                  if (isProfilePic) {
                      try {
                          isProfilePic = false;
                          dataSource.subscribe(new BaseBitmapDataSubscriber() {

                                 @Override
                                 public void onNewResultImpl(@Nullable Bitmap bitmap) {
                                    // You can use the bitmap in only limited ways
                                    // No need to do any cleanup.
                                    if (bitmap != null) {
                                        if (MyApp.getInstance().isConnectionPossible()) {
                                             restService.uploadProfilePic(MyApp.VALUE_OPTION, "uploadavatar", userId, MyApp.VALUE_APP_TYPE, bitmap, new RestCallback<ProfilePicUpload>() {
                                                 @Override
                                                 public void success(ProfilePicUpload o) {
                                                      String profileImg = o.getUploadProfilePicture().getImage();
                                                      String profileThumbImg = o.getUploadProfilePicture().getThumbnail();
                                                      MyPrefs.writeString(ProfileMainActivity.this, MyApp.KEY_PROFILE_IMAGE, profileImg);
                                                      MyPrefs.writeString(ProfileMainActivity.this, MyApp.KEY_PROFILE_THUMB_IMAGE, profileThumbImg);
                                                      ivUserThumb.setImageURI(Uri.parse(profileImg));
                                                                             //Glide.with(ProfileMainActivity.this).load(profileImg).placeholder(R.drawable.profile_pic_bg).into(ivPostPerson);
                                        }

                                                                         @Override
                                                                         public void invalid() {                                                                              
                                                                         }

                                                                         @Override
                                                                         public void failure() {
                                                                             isProfilePic = false;
                                                                         }
                                                                     });
                                                                 } else {
                                                                     MyApp.showDialog(ProfileMainActivity.this, getResources().getString(R.string.error_msg_internet));
                                                                 }
                                                             } else {
                                                                 MyApp.showDialog(ProfileMainActivity.this,"Bitmap is null");
                                                             }
                                                         }

                                                         @Override
                                                         public void onFailureImpl(DataSource dataSource) {
                                                             // No cleanup required here.
                                                             MyApp.showDialog(ProfileMainActivity.this,"Failure");
                                                         }
                                                     },
                                        CallerThreadExecutor.getInstance());
                            } finally {
                                if (dataSource != null) {
                                    dataSource.close();
                                }
                            }
                        }
                    }
                    break;
            }
        }
}

I debug the code after `dataSource.subscribe(new BaseBitmapDataSubscriber() {` this line it is executing the finally block not showing any exception. Not executing `protected void onNewResultImpl` or `protected void onFailureImpl`

**Comment by aagnes** [comment]
Do you have user-permission for getting access gallery and camera for your app?

**Comment by Kaushik1502** [comment]
Yes @aagnes I used Glide previously and I get the bitmap successfully

**Comment by aagnes** [comment]
http://frescolib.org/docs/datasources-datasubscribers.html#_
Check the caveat here

**Comment by Kaushik1502** [comment]
As I told it is not getting called onNewResultImpl or the failure how can I get and use that bitmap

**Comment by Kaushik1502** [comment]
After clean and rebuild project I debugged it and notice onFailureImpl is getting called

**Comment by aagnes** [comment]
Good, thanks.

**Comment by Kaushik1502** [comment]
@aagnes Please see the issue

**Comment by aagnes** [comment]
If you are using animated images, try use BaseDataSubscriber instead of BaseBitmapDataSubscriber

**Comment by Kaushik1502** [comment]
It is for pick an image from gallery and get the bitmap in onActivityResult
for some use. I am not loading any animated image such as gif

**Comment by aagnes** [comment]
When I tried with your code and selected one static jpeg image from the Gallery, I get onNewResultImpl called with a good Bitmap returned. I doubt if it's because the device specific you're using.

**Comment by aagnes** [comment]
Can you attach the error log and see what the stack trace is

**Comment by Kaushik1502** [comment]
No error log no exception is shown that really surprised me as I told when I debug the code then it is executing but when I run it is not executing `onNewResultImpl` or `onFailureImpl` put a toast and a log inside both methods. I also checked if uri which I am getting is incorrect but it is working I am checking it by setting that uri on that SimpleDraweeView.
