### ISSUE TITLE
Allow control over transition between controllers

### ISSUE THREAD

**Issue by damianw** [facebook/fresco#645]
Currently, setting a new `DraweeController` switches over immediately, even if the new image is not ready. This can be jarring, even if the fade effect is used, since it only fades in the second image. Ideally, the interface would allow a crossfade between the two images or other customizations.

**Comment by emanzanoaxa** [comment]
+1

**Comment by ealymbaev** [comment]
+1

**Comment by ShawnDuan** [comment]
+1

**Comment by oprisnik** [comment]
You can now use a `RetainingDataSourceSupplier` ff3bed97fb05e4d235e5e67009b1e26b7ad384b8 to control what happens.
