### ISSUE TITLE
9-patch placeholder image rendering

### ISSUE THREAD

**Issue by PavelSynek** [facebook/fresco#646]
I want to use [this](http://imgur.com/jXWiywA) 9-patch from resources as a placeholder while my image is loading. The problem is that since version 0.7.0, Fresco isn't rendering it properly.

```java
<FrameLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:fresco="http://schemas.android.com/apk/res-auto"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:background="@android:color/black">

	<com.facebook.drawee.view.SimpleDraweeView
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		fresco:placeholderImage="@drawable/ic_placeholder"
		fresco:placeholderImageScaleType="none"/>

</FrameLayout>
```
This layout looks differently in 0.6.1 and 0.7.0
![comparison](https://cloud.githubusercontent.com/assets/11048800/10353004/65981324-6d53-11e5-92af-4be04f29bf34.png)

I can provide sample project if needed.

**Comment by aagnes** [comment]
I think you need to use scaletype as fitXY for your placeholder image

**Comment by levianye** [comment]
I also meet such question,my problem  is layer-list drawable rendering  not sync, it seems fresco rendering the layer-list drawable by the item in the layer-list,here is my drawable xml code:

`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" >
    
    <item >
        <shape android:shape="rectangle">
            <solid android:color="#f4f4f4"/>
            <size
                android:width="200dp"
                android:height="200dp">
            </size>
        </shape>
    </item>
    
    <item >
        <bitmap android:src="@drawable/mt_default_normal" android:gravity="center"/>
    </item>

</layer-list>`

it display the shap item first then dispaly the bitmap item ,I don't know why!Can any one help me?
