### ISSUE TITLE
How to get a bitmap synchronously?

### ISSUE THREAD

**Issue by HomHomLin** [facebook/fresco#647]
Hello.
I'm using fresco in my project.But now I have a probleam.
I have a picture url, how to get bitmap from the url synchronously?
In ImageLoader, I can do like this:
Bitmap bmp = imageLoader.loadImageSync(url);
It could return a bitmap after Imageloader decode, and it's synchronously.How can I do in fresco?

**Comment by aagnes** [comment]
see #446
