### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by Tim1008** [facebook/fresco#65]
when run the sample, i got an error :
:imagepipeline:cloneWebp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:cloneWebp'.
> org.eclipse.jgit.api.errors.TransportException: https://chromium.googlesource.com/webm/libwebp: cannot open git-upload-pack

**Comment by michalgr** [comment]
Hi, can you try to build once again ? Fresco depends on libwebp and we do clone it directly from google's repo. You might be over their quota currently.

**Comment by tyronen** [comment]
Duplicate of #52

**Comment by Tim1008** [comment]
@michalgr @tyronen when i try vpn ,it's ok ! thanks for your help.
