### ISSUE TITLE
Allow config the default Bitmap.Config value.

### ISSUE THREAD

**Issue by rey5137** [facebook/fresco#652]
Is there any way to change the Bitmap.Config.ARGB_8888 currently used when create Bitmap? I want to use Bitmap.Config.RGB_565 for smaller memory on Lolipop device.

**Comment by aagnes** [comment]
You can build your own Bitmap.Config in ImagePipelineConfig.Builder

**Comment by rey5137** [comment]
I have read both the doc and source code. You can set a custom `PlatformBitmapFactory` object via `ImagePipelineConfig.Builder.setPlatformBitmapFactory()` method, but `ImagePipelineFactory` seem like not using the config value, and create a new one in `buildPlatformBitmapFactory(PoolFactory)` method.
