### ISSUE TITLE
build on mac os10.9.5 Fail 

### ISSUE THREAD

**Issue by xl736592857** [facebook/fresco#653]
my system is MAC OS 10.9.5 NDK is r10e
when I build fresco ,always fail. error log:

com.facebook.imagepipeline.bitmaps.DalvikBitmapFactoryTest > testDecodeJpeg_incomplete                                                                         FAILED
    java.lang.VerifyError at DalvikBitmapFactoryTest.java:134

com.facebook.imagepipeline.bitmaps.DalvikBitmapFactoryTest > testDecode_Jpeg_Detailed                                                                          FAILED
    java.lang.VerifyError at DalvikBitmapFactoryTest.java:194

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testPostprocess FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalContentUriFullFetch                                                                     FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testNetworkFetchToEncodedMemoryPrefetch                                                          FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalAssetFullFetch                                                                          FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testNetworkFullPrefetch                                                                          FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalContentUriFullPrefetch                                                                  FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalImageFileFullFetch                                                                      FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testEncodedBytesNotAllowedForLocalFiles                                                          FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testNetworkFetchToEncodedMemory                                                                  FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalAssetAndResourceFullPrefetch                                                            FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testNetworkFullFetch                                                                             FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalResourceFullFetch                                                                       FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalVideoFileFullFetch                                                                      FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalImageFileFullPrefetch                                                                   FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.core.ProducerSequenceFactoryTest > testLocalVideoFileFullPrefetch                                                                   FAILED
    java.lang.VerifyError at ProducerSequenceFactoryTest.java:74

com.facebook.imagepipeline.producers.JobSchedulerTest > testSchedule_Last_Running_And_Pending                                                                  FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testUpdate_Last_Null FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testFailure FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testUpdate_Last FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testClear FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testUpdate_IntermediateFAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testSchedule_Last_Queued                                                                               FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testSchedule_TooSoon FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testSchedule_Last_Idle FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testSchedule_Last_Null FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testUpdate_Intermediate_Invalid                                                                        FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testSchedule_Intermediate_Invalid                                                                      FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.JobSchedulerTest > testSchedule_Intermediate                                                                              FAILED
    java.lang.VerifyError at JobSchedulerTest.java:121

com.facebook.imagepipeline.producers.LocalExifThumbnailProducerTest > testNoExifThumbnail                                                                      FAILED
    java.lang.VerifyError at LocalExifThumbnailProducerTest.java:78

com.facebook.imagepipeline.producers.LocalExifThumbnailProducerTest > testFindExifThumbnail                                                                    FAILED
    java.lang.VerifyError at LocalExifThumbnailProducerTest.java:78

com.facebook.imagepipeline.producers.NetworkFetchProducerTest > testDownloadHandler                                                                            FAILED
    java.lang.VerifyError at NetworkFetchProducerTest.java:168

com.facebook.imagepipeline.producers.NetworkFetchProducerTest > testNoIntermediateResults                                                                      FAILED
    java.lang.VerifyError at NetworkFetchProducerTest.java:130

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesNotTransformIfNotRequested                                                          FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testResizeRatio                                                                             FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesRotateWhenNoResizeOptions                                                           FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesResizeIfJpeg                                                                        FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testUnknownDoesNotPassOnIntermediateResult                                                  FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesNotTransformIfNotJpeg                                                               FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesNotUpscaleWhenRotating                                                              FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesComputeRightNumeratorWhenRotating_180                                               FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesComputeRightNumeratorWhenRotating_270                                               FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesComputeRightNumeratorWhenRotating_90                                                FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesNothingWhenNotAskedToDoAnything                                                     FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesNotUpscale                                                                          FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testUnknownPassesOnResultIfIsLast                                                           FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesComputeRightNumeratorWhenRotating_0                                                 FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104

com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testDoesRotateIfJpeg                                                                        FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104
com.facebook.imagepipeline.producers.ResizeAndRotateProducerTest > testRoundNumerator                                                                          FAILED
    java.lang.VerifyError at ResizeAndRotateProducerTest.java:104
563 tests completed, 50 failed
:imagepipeline:testDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':imagepipeline:testDebug'.

**Comment by massimocarli** [comment]
The java.lang.VerifyError happens if you have compiled against a different library than you are using at runtime. Could you provide please more information about that please?

**Comment by xl736592857** [comment]
I try to change jdk version from 1.7.0_71 to 1.7.0_80,build success.
