### ISSUE TITLE
Images cannot be shown in some kinds of wifi conditions

### ISSUE THREAD

**Issue by binqiangsun** [facebook/fresco#656]
Some users said that the images cannot be shown sometimes with wifi conditions, while other apps worked well. When changed to the mobile network(2g, 3g, or 4g), images were shown again.

Has anyone had this problem?

**Comment by massimocarli** [comment]
Fresco doesn't listen to the network state and doesn't trigger a new request in that case. Is this what you mean? Could you provide us more information about this please?

**Comment by whokilledtheelectricmonk** [comment]
I have an issue like this with `react-native` using Fresco. Images whose source uri takes a long time to fetch (e.g. an image being resized on Cloudfront) just don't show up.

**Comment by binqiangsun** [comment]
maybe it is the problem of our own image server.  sorry.

**Comment by tyronen** [comment]
@whokilledtheelectricmonk please file a separate issue for that, and include an example of the source uri.
