### ISSUE TITLE
Fresco 100张1M GridView Caton , but do not have a little 1000 3M

### ISSUE THREAD

**Issue by Tijn1314** [facebook/fresco#657]
Fresco 100张1M GridView Caton , but do not have a little 1000 3M  why？

**Comment by Tijn1314** [comment]
Fresco 100张1M GridView Caton , but do not have a little 1000 3M

**Comment by massimocarli** [comment]
Could you provide more information please? Your question is not very clear.
Thanks

**Comment by aagnes** [comment]
请用中文. 我们看不懂你的问题.希望你可以用中文详细描述你的问题.
