### ISSUE TITLE
Need to know the size of the cache when cleanAll

### ISSUE THREAD

**Issue by hubcin** [facebook/fresco#658]
Can ImagePipeline return a value of the cache size after cleanAll called ? Need to know how much image cache have been cleaned or how much disk space or memory get freed.

**Comment by caojianfeng** [comment]
I think you can implment com.facebook.cache.common.CacheEventListener#onEviction
and set it by com.facebook.cache.disk.DiskCacheConfig.Builder#setCacheEventListener

need try.

**Comment by hubcin** [comment]
will try, thanks for the guide!

**Comment by nimdanoob** [comment]
you can user File.length to get  the cache file size。 the default disk cacheFile path is  context.getCacheFile +"image_cache"

**Comment by hubcin** [comment]
OK, I should give it a try, thank you so much for giving me a hint.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: ZousSent: Sunday, February 7, 2016 00:45To: facebook/frescoReply To: facebook/frescoCc: hubcinSubject: Re: [fresco] Need to know the size of the cache when cleanAll (#658)you can user File.length to get  the cache file size。 the default disk cacheFile path is  context.getCacheFile +"image_cache"

—Reply to this email directly or view it on GitHub.
