### ISSUE TITLE
How to add http header when downloading image?

### ISSUE THREAD

**Issue by KynoYang** [facebook/fresco#659]
I need to add some info to the http header, or it will be failed to download images. I can't find the way to do that. Anyone know how to solve it?

**Comment by massimocarli** [comment]
At the moment you should add the headers on the ```HttpUrlConnectionNetworkFetcher``` that is responsible to fetch the image. We're going to add this feature to the ```ImageRequestBuilder```.

**Comment by KynoYang** [comment]
@massimocarli  Thanks for replying.

**Comment by LiuDeng** [comment]
@massimocarli when will this feature be added? It is really necessary for our project.
Thank you all your great jobs.

**Comment by balazsbalazs** [comment]
@LiuDeng: unfortunately we don't have a timeline for this. This is not something we need internally so it's not high priority for us at the moment.
If you really need it feel free to submit a pull request - those are always welcome :)

**Comment by yjwfn** [comment]
What is a good way to solve this problem?

**Comment by contrudar** [comment]
with okhttp you can create an interceptor and after initialize Fresco with it

        final OkHttpClient okHttpClient = new OkHttpClient.Builder().addInterceptor(chain -> {
                return chain.proceed(chain.request().newBuilder().addHeader("YourHeader", "value").build());
            }
        }).build();

        Fresco.initialize(this, OkHttpImagePipelineConfigFactory.newBuilder(this, okHttpClient).build());

**Comment by oprisnik** [comment]
Yes, adding a OkHttp interceptor is the preferred way to do this. There is also a discussion going on in #1459 with alternative solutions, so just monitor the discussion in the PR.

**Comment by ShankyPatel** [comment]
Hi,
I am passing file key in headers which is different for every image to download. So my question is is it good to initialize fresco everytime to download image ? Or there is another way just like picasso provides to add okhttp request upon every api hit for image download ?

**Comment by oprisnik** [comment]
Re-initializing Fresco is not a good idea here. You can do what React Native is doing and have a custom ImageRequest that includes request headers and then pass the headers in the network fetcher, see https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/ReactAndroid/src/main/java/com/facebook/react/modules/fresco/ReactNetworkImageRequest.java

**Comment by ShankyPatel** [comment]
How do i use imagerequest ? from this code i am able to pass it to the the drawable controller but its an imageview,
[https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java ) would you please tell me how to use it with setImageUri() as i am new to this library.

**Comment by oprisnik** [comment]
See the code snippets here: https://github.com/facebook/react-native/search?q=ReactNetworkImageRequest&unscoped_q=ReactNetworkImageRequest

**Comment by ShankyPatel** [comment]
thanks

**Comment by sp00ne** [comment]
Honestly, there are plenty of image services out there that support adding image sizes as headers for the call and many projects utilise that in order to not request huge images. 

Not having the possibility to do this with Fresco is causing us to migrate away. A custom interceptor inside the network fetcher won't do it, I don't have view access there.

Glide has an option with an interceptor that exposes the url, width of the view and height of the view (http://bumptech.github.io/glide/javadocs/400/com/bumptech/glide/load/model/ModelLoader.html)

**Comment by oprisnik** [comment]
@sp00ne This is already quite easy to do. You can for example set the dimensions as Fresco's resize options and then access them in the OkHttpNetworkFetcher.  You'd just have to extend OkHttpNetworkFetcher and override the fetch method to set your custom header. We already do this here:
https://github.com/facebook/fresco/blob/master/imagepipeline-backends/imagepipeline-okhttp3/src/main/java/com/facebook/imagepipeline/backends/okhttp3/OkHttpNetworkFetcher.java#L107

You'd just have to add something like:

```
requestBuilder.addHeader("w", fetchState.getContext().getImageRequest().getResizeOptions().width);
```

If you want custom parameters,  just extend ImageRequest as described above.
This solution seems very simple to me.

**Comment by sp00ne** [comment]
Not every image/view needs this. The requests needs to be able to be handled per view basis and have values/variables set based on UI. 

1) To do a broad stroke decision like that for every request is not preferable
2) To do UI work/decisions on the network layer is a clear violation.
