### ISSUE TITLE
Fresco load local image for GridView does not scroll smoothly

### ISSUE THREAD

**Issue by simidaxu** [facebook/fresco#660]
I want to load pictures with fresco to gridview on devices, but it could not scroll very well.
in gridview item xml, both width and height are MATCH_PARENT, in adapter I use:
                image.setImageURI(Uri.parse("file://" + data.path));

OR
                Uri uri = Uri.parse("file://" + data.path);
                ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                        .build();
                DraweeController controller = Fresco.newDraweeControllerBuilder()
                        .setImageRequest(request)
                        .build();
                image.setController(controller);

when I scroll the gridView, I found UI not works very well. I found that use Picasso load local image does not has the same issue, here is the code:
                Picasso.with(mContext)
                        .load(imageFile)
                        .placeholder(R.drawable.default_error)
                        .error(R.drawable.default_error)
                        .resize(mItemSize, mItemSize)
                        .centerCrop()
                        .into(image);

Now, I wanted to use Fresco instead of Picasso beause I use Fresco in other parts, do not want to import Picasso with the same function.

Wanted to get help.

**Comment by massimocarli** [comment]
Have you tried our comparison app? It uses local images as well. Please try it with your local images and tell us if the same thing happens.
Thanks

**Comment by wenxueguo107room** [comment]
same problem, but when I use Universal Image Loader, it works fine

**Comment by michalgr** [comment]
Please, tell Fresco to resize (or even better, downsample) as well: http://frescolib.org/docs/resizing-rotating.html#resizing.

@wenxueguo107room: does it help ?

**Comment by wenxueguo107room** [comment]
Thanks, resize works well. All the images I load are local files. But I already set width and height in xml, why it didn't work?

**Comment by tyronen** [comment]
Setting the width and height in xml only sets the display size, it doesn't resize the image itself.

**Comment by AllenVork** [comment]
I got the same issue.
i use fresco to load local image.and i have resized the image to 270*270px, but it doesn't work

    fun loadResizeImage(uri: Uri, view: SimpleDraweeView, width: Int, height: Int) {
        val request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(ResizeOptions(width, height)).build()

        val controller = Fresco.newDraweeControllerBuilder()
                .setOldController(view.controller)
                .setImageRequest(request)
                .build()
        view.controller = controller
    }

i can't scroll smooth.

**Comment by simidaxu** [comment]
@massimocarli Thanks， it works well.

**Comment by chenwulue** [comment]
@specneeo 你是怎么解决的呢

**Comment by specneeo** [comment]
@chenwulue  clone一下fresco的源码，里面有个sample 目录，运行comparison，这里面有。
