### ISSUE TITLE
Detect Redirect Image

### ISSUE THREAD

**Issue by snoopgroggygrog** [facebook/fresco#661]
Hi, 

Using Fresco can I detect whether an image has come from a redirected URL? 

eg, I request www.example.com/images/a_cat.jpg and it returns (through redirect) www.example.com/images/no_such_image.jpg

One possible solution would be to compare the URL I sent and the one in the returned header. Is there a way to do this?

Thanks!

**Comment by michalgr** [comment]
There is not API for that. Can you share more details about your use case ? What do you want to do ? Prevent redirections ? Collect some stats ?

**Comment by snoopgroggygrog** [comment]
In my particular case, I want to know know when a redirection has taken place so I can replace the image (from the redirected URL) with a different one. 

A more general case might be that when images from URLs A, B, and C are all loaded from a redirected URL D, they are all cached separately, even though they came from the same source (D). 

At the very least, being able to grab the original URL and the actual URL (the one that the network connection was redirected to), when an image loads would be useful for a variety of cases.

**Comment by kirwan** [comment]
This is a useful idea but not something we are currently prioritising internally. If you'd like to send a pull request, that would be brilliant.

**Comment by erikandre** [comment]
Closing since this issue is not prioritized to be implemented in the foreseeable future.
If this is a feature that you need, please consider contributing a pull request to Fresco!
