### ISSUE TITLE
Scale Image to screen height and including aspect ratio to width

### ISSUE THREAD

**Issue by stasbar** [facebook/fresco#663]
Helo.
How to scale Image to screen height and width including aspect ratio.
I have this SimpleDraweeView in HorizontalScrollView
So i'm able to scroll this view If image is wider than screen width
````
        <HorizontalScrollView
                android:id="@+id/horizontal_scroll_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent">
                <com.facebook.drawee.view.SimpleDraweeView
                    android:id="@+id/my_image_view"
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    fresco:actualImageScaleType="fitCenter"
                    />
            </HorizontalScrollView>
````
Please help me

**Comment by michalgr** [comment]
I am not sure I understand the question. Do you want SimpleDraweeView to scale image to be as high as screen and its width to be scaled up to preserve aspect ratio even if it would be wider than screen ?

**Comment by stasbar** [comment]
Yes, exacly. It can be wider than screen because it  is in HorizontalScrollView. 
(This is wallpaper browser app)

**Comment by michalgr** [comment]
Do you know aspect ratio of images you want to display ? Setting the aspect ratio would help SimpleDraweeView position itself when layout happens and image is not decoded yet. If you don't know the aspect ratio upfront you might use ControllerListener (http://frescolib.org/docs/listening-download-events.html#usage) to wait for the final image and set the aspect ratio then.
