### ISSUE TITLE
High memory usage when image is mostly black

### ISSUE THREAD

**Issue by alvinthen** [facebook/fresco#664]
When loading an image which is mostly black using fresco, causes a spike in memory usage, and eventually causes OOM. Codes and images are supplied below.

Tested in Android API 17, 21, images that is not mostly black will not cause such issue

```java
    @Override
    protected void onResume() {
        super.onResume();
        if (mPhotoFile != null) {
            //delete cache
            ImagePipeline imagePipeline = Fresco.getImagePipeline();
            imagePipeline.clearMemoryCaches();
            imagePipeline.clearDiskCaches();
            imagePipeline.clearCaches();
            image.setImageURI(Uri.fromFile(mPhotoFile));
        }
    }
```

```xml
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/child_picture"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:contentDescription="@string/child_picture"
                android:fitsSystemWindows="true"
                app:layout_collapseMode="parallax"
                fresco:placeholderImage="@drawable/person_white_540dp"
                fresco:placeholderImageScaleType="centerCrop"
                fresco:viewAspectRatio="1" />
```

![black-image](https://cloud.githubusercontent.com/assets/771989/10568637/7bb6d700-764d-11e5-998a-82d1ea9c08eb.png)
![memory-usage](https://cloud.githubusercontent.com/assets/771989/10568653/ba39872a-764d-11e5-9cc7-e956adc0a7d2.png)
![error-msg](https://cloud.githubusercontent.com/assets/771989/10568659/dde2dd2a-764d-11e5-83de-bc9a82a4715a.png)

**Comment by michalgr** [comment]
I doubt it is about the color. Uploaded photo is just huge, tell Fresco to make it smaller before decoding: http://frescolib.org/docs/resizing-rotating.html
