### ISSUE TITLE
ImagePipelineFactory doesn't use the PlatformBitmapFactory that is set in ImagePipelineConfig.

### ISSUE THREAD

**Issue by rey5137** [facebook/fresco#665]
You can set a custom `PlatformBitmapFactory` object via `ImagePipelineConfig.Builder.setPlatformBitmapFactory()` method, but `ImagePipelineFactory` seem like not using the config value, and create a new ones in `buildPlatformBitmapFactory(PoolFactory)` method.

**Comment by aagnes** [comment]
If you want to use your own config, you'll need to pass it when you create your own ImagePipelineFactory. The sequence here really matters. Can you please share your code, or steps how you do?

We expect the usage is
 *   ImagePipelineConfig config = ImagePipelineConfig.newBuilder()
 *       .setPlatformBitmapFactory(platformBitmapFactory)
 *       .build();
 *   ImagePipelineFactory factory = new ImagePipelineFactory(config);
 *   ImagePipeline pipeline = factory.getImagePipeline();
