### ISSUE TITLE
How to save image to disk cache

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#667]
I am new to fresco, so i  want to know how to store and retrieve image from disk cache using fersco.

**Comment by michalgr** [comment]
This is the method you can use to prefetch image to disk cache: https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipeline.java#L271. After that Drawee will fetch the image from disk cache instead of downloading it from network.

**Comment by karun2189** [comment]
If i am using prefetchToDiskCache it will store bitmap to disk ?
