### ISSUE TITLE
How to set Shadow for SimpleDraweeView

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#668]
Hi, How to set shadow effect in SimpleDraweeView...Can anyone help me

**Comment by kaedea** [comment]
I think it is better to use CardView

**Comment by karun2189** [comment]
If i am use CardView how can i use fersco for that view?

**Comment by kaedea** [comment]
Of course, CardView is an ViewGroup, using it to wrap DraweeView.

**Comment by michalgr** [comment]
have you tried any of the ideas here: http://stackoverflow.com/questions/4406524/how-to-set-shadow-to-a-view-in-android ?

**Comment by karun2189** [comment]
Multiple views take large weight for Gridview. So i am not use that solution

**Comment by lendra85** [comment]
this is not help for circular shadow.
