### ISSUE TITLE
fresco can't be built by Gradle after imported into Android Studio

### ISSUE THREAD

**Issue by LittlePanpc** [facebook/fresco#67]
I have posted my question in [StackOverFlow](http://stackoverflow.com/questions/29386772/fresco-cant-be-built-by-gradle-after-imported-into-android-studio). Could anybody have a look and help me?

**Comment by tyronen** [comment]
This looks like another Windows issue - but we'll probably have to fix #24 first.

**Comment by Rockcafe3in1** [comment]
＋1， same problem i meet.

**Comment by plamenko** [comment]
Duplicate
