### ISSUE TITLE
SimpleDraweeView is Flickering

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#671]
SimpleDraweeView is flickering when i am updating image in that imageview in Grid. How can i avoid this flickering ?

**Comment by KynoYang** [comment]
Try to display image without duration. 
fresco:fadeDuration="0"

**Comment by michalgr** [comment]
Could you show us a video ? I don't see flickering in our comparison app (http://frescolib.org/docs/sample-code.html#the-comparison-app), unless you mean fade-in animation as suggested by @KynoYang or the bug is device specific. Could you try reproducing it using the comparison app ?

**Comment by karun2189** [comment]
Its working fine thanks for your reply
