### ISSUE TITLE
ART has trouble loading AnimatedDrawable

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#673]
I am trying to load a gif from a remote url,when does this error occur?And should this be of any impact.

`Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.animated.base.AnimatedDrawable$5>`

**Comment by michalgr** [comment]
Does this cause a crash ? Is there anything else in the logcat ? What phone and os version do you use to reproduce the issue ?

**Comment by droidekas** [comment]
It sometimes prevents my gif from loading(cellular data cases),
Nexus 5 - 5.1.1,
One Plus One - 5.1.1
Moto G(1st gen) -

no other fresco related logs in the LogCat

**Comment by tyronen** [comment]
This may be an issue loading libraries depended on by AnimatedDrawable - either Fresco's native libraries (libimagepipeline.so et al) or nineoldandroids. Are you excluding nineoldandroids in your build.gradle file anywhere? Can you show us the file?

**Comment by droidekas** [comment]
Yes I am excluding nineoldandroids.But since I am supporting only api 14 above.Do I still need that dependency?

**Comment by massimocarli** [comment]
@droidekas Do you still have the problem with version 0.10.0? Can you provide us the fresco dependencies you're using?
Thanks

**Comment by oprisnik** [comment]
Since there has been no response, I assume this is fixed.

**Comment by droidekas** [comment]
@oprisnik @massimocarli  This works now on updating. Thanks :)
