### ISSUE TITLE
Fresco guide page no update?

### ISSUE THREAD

**Issue by parkjaeiek** [facebook/fresco#674]
this guide 0.5.0+

now lib 0.8.0+

when update?

**Comment by michalgr** [comment]
English documentation should be already up to date: http://frescolib.org/docs/index.html.

**Comment by tyronen** [comment]
Filed a pull request with the Korean doc owners. Please report issues with the Korean docs to the [Korean repository](https://github.com/recrack/fresco-docs-kr).
