### ISSUE TITLE
Could I stop the ImageRequest job when the DraweeView is onDetach?

### ISSUE THREAD

**Issue by kaedea** [facebook/fresco#676]
I would like to stop ImageRequest when the DraweeView is detached from window in RecyclerView, thinking that this might save Network Traffic and make the DraweeView get its ImageRequest done earlier.

I have saw that DraweeHolder will do some business when the DraweeView is detached, but I don't know whether this will remove the ImageRequest.

Could I set DraweeController null? This may be dangerous as the doc has sugguested not to handler the DraweeHierarchy outside the DraweeView.

Please offer some info.
Thanks.

**Comment by michalgr** [comment]
This is taken care of. DraweeView will notify ImagePipeline whenever it is detached from window and it will cancel the request.
