### ISSUE TITLE
failed to resolve:com.facebook.fresco:fresco:0.8.0+

### ISSUE THREAD

**Issue by hukejia** [facebook/fresco#677]

**Comment by desmond1121** [comment]
@hukejia which repository you use in your project gradle script ?  In china, you can use [oschina maven center](http://maven.oschina.net/index.html#welcome).

**Comment by hukejia** [comment]
@desmond1121 

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by hukejia** [comment]
@desmond1121  不行

**Comment by KynoYang** [comment]
try jcenter

**Comment by hukejia** [comment]
I made it like this 
compile 'com.facebook.fresco:fresco:0.8.0'
The problem is solved.
