### ISSUE TITLE
Proguard issue with imagepipeline in 0.8.0

### ISSUE THREAD

**Issue by Deepscorn** [facebook/fresco#681]
Problem: 
Warning:com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory: can't find referenced field 'android.graphics.Bitmap$Config BITMAP_CONFIG' in program class com.facebook.imagepipeline.nativecode.Bitmaps

Environment:
Android Studio 1.4

Gradle:
```groovy
compile 'com.facebook.fresco:fresco:0.8.0'
compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.0'
```

Proguard configuration taken from official docs http://frescolib.org/docs/proguard.html.

I reverse-engineered apk and found out that there is no BITMAP_CONFIG field in a non-obfuscated Bitmaps class

**Comment by franciscofranco** [comment]
I can confirm this issue.

**Comment by michalgr** [comment]
Interesting - there is no DalvikBitmapFactory in version 0.8.0 anymore. I am able to reproduce though.

**Comment by michalgr** [comment]
we'll do new release

**Comment by Shailevy** [comment]
Same problem here

**Comment by alexndreazevedo** [comment]
Any suggestion to this issue?

**Comment by Deepscorn** [comment]
michalgr, thanks, waiting for new release. This one appears to be broken. We encountered another 2 problems and switched back to 0.7.0. One problem was that gradle was looking for fbcore.jar when there is aar (looks like wrong pom file). The solution was to add @aar everywhere, on all fresco inclusions in build.gradle files. But that was solution only for compiling project. Then we've encountered crashes with class not defined (don't remember exact name) exceptions at runtime without changing any code - it works well with 0.7.0

**Comment by kaitian521** [comment]
I also found this issue... will this issue be fixed sooner?

**Comment by tyronen** [comment]
Please try v0.8.1.

**Comment by alexndreazevedo** [comment]
I got the following error:
```
Error:A problem occurred configuring project ':app'.
> Could not find fbcore.aar (com.facebook.fresco:fbcore:0.8.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/facebook/fresco/fbcore/0.8.1/fbcore-0.8.1.aar
```

**Comment by pipipzz** [comment]
Having the same issue with 0.8.1 also

**Comment by zbobyuan** [comment]
0.8.1 works well.

    compile 'com.facebook.fresco:fresco:0.8.1'
    compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.1'

proguard rule:

#facebook fresco
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

# Keep native methods
-keepclassmembers class * {
    native <methods>;
}

-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn com.android.volley.toolbox.**
#facebook fresco end.

**Comment by mrljdx** [comment]
@Deepscorn  Hi ，i also had this problem and my solution is adding the below words to the **proguard-rules.pro** file
    
     -dontwarn com.facebook.imagepipeline.**

for more details see my answer in [stackoverflow](http://stackoverflow.com/questions/33867642/proguard-error-with-fresco/34351360#34351360)
