### ISSUE TITLE
Getting outofmemory

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#683]
I am getting out-of-fmemory when i am set a failure image to simpledrawee
view. Why this is occur?

**Comment by michalgr** [comment]
How big is your failure image ? Is it a Bitmap ?

**Comment by karun2189** [comment]
My failure image size is 5.10kb and its drawable

**Comment by tyronen** [comment]
Does it always happen exactly when you set a failure image? or randomly at different spots in your app?

If Fresco is causing OOMs, the most common cause of this is using very large images and not [resizing](http://frescolib.org/docs/resizing-rotating.html#resizing) them.
