### ISSUE TITLE
Eclipse: exception when inflating SimpleDraweeView

### ISSUE THREAD

**Issue by springhi2013** [facebook/fresco#684]
I use fresco 0.8, directly to the drawee-v0.8.0.jar, imagepipiline-v0.8.0.jar fbcore-v0.8.0.jar, etc. directly placed in my project directory libs/, 

the code is as follows:

   <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/user_head"
            android:layout_width="35dp"
            android:layout_height="35dp"
            android:layout_centerVertical="true"
            android:layout_marginLeft="10dp"
            />

10-22 18:08:26.614: E/AndroidRuntime(7840): android.view.InflateException: Binary XML file line #34: Error inflating class com.facebook.drawee.view.SimpleDraweeView
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.createView(LayoutInflater.java:623)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)

10-22 18:08:26.614: E/AndroidRuntime(7840):     at java.lang.reflect.Method.invokeNative(Native Method)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at java.lang.reflect.Method.invoke(Method.java:515)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at dalvik.system.NativeStart.main(Native Method)
10-22 18:08:26.614: E/AndroidRuntime(7840): Caused by: java.lang.reflect.InvocationTargetException
10-22 18:08:26.614: E/AndroidRuntime(7840):     at java.lang.reflect.Constructor.constructNative(Native Method)
10-22 18:08:26.614: E/AndroidRuntime(7840):     at java.lang.reflect.Constructor.newInstance(C

**Comment by michalgr** [comment]
Can you share full stack trace ?

**Comment by springhi2013** [comment]
10-22 20:14:44.894: W/dalvikvm(13607): threadid=1: thread exiting with uncaught exception (group=0x41725d58)
10-22 20:14:44.924: E/AndroidRuntime(13607): FATAL EXCEPTION: main
10-22 20:14:44.924: E/AndroidRuntime(13607): Process: cn.com.mobnote.golukmobile, PID: 13607
10-22 20:14:44.924: E/AndroidRuntime(13607): java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.com.mobnote.golukmobile/cn.com.mobnote.golukmobile.MainActivity}: android.view.InflateException: Binary XML file line #52: Error inflating class com.facebook.drawee.view.SimpleDraweeView
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.ActivityThread.access$800(ActivityThread.java:141)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.os.Looper.loop(Looper.java:136)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.ActivityThread.main(ActivityThread.java:5047)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at dalvik.system.NativeStart.main(Native Method)
10-22 20:14:44.924: E/AndroidRuntime(13607): Caused by: android.view.InflateException: Binary XML file line #52: Error inflating class com.facebook.drawee.view.SimpleDraweeView
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.createView(LayoutInflater.java:623)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:842)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at cn.com.mobnote.golukmobile.MainActivity.onCreate(MainActivity.java:149)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.Activity.performCreate(Activity.java:5249)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	... 11 more
10-22 20:14:44.924: E/AndroidRuntime(13607): Caused by: java.lang.reflect.InvocationTargetException
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at java.lang.reflect.Constructor.constructNative(Native Method)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at android.view.LayoutInflater.createView(LayoutInflater.java:597)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	... 25 more
10-22 20:14:44.924: E/AndroidRuntime(13607): Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:128)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:77)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:60)
10-22 20:14:44.924: E/AndroidRuntime(13607): 	... 28 more
10-22 20:14:44.934: I/KLO_Stability(1759): [am_crash][1445516084]:[13607,0,cn.com.mobnote.golukmobile,11058758,java.lang.NoClassDefFoundError,com.facebook.drawee.R$styleable,GenericDraweeView.java,128]
10-22 20:14:44.934: I/WhetstoneService(1461): Receive am_crash event for pid: 13607
10-22 20:14:44.934: W/KloServer(1461): Aborted broadcast does not supprt for: cn.com.mobnote.golukmobile
10-22 20:14:44.934: W/ActivityManager(1201):   Force finishing activity cn.com.mobnote.golukmobile/.MainActivity
10-22 20:14:44.954: I/libmc(1759): received event[index:0,mask:0x80,name:data_app_crash@1445516084954.txt]
10-22 20:14:44.954: I/KLO_Stability(1759): get wanted event[mask:128, name:data_app_crash@1445516084954.txt] from the watchset

**Comment by springhi2013** [comment]
on eclipse 

XXX/libs/bolts-android-1.1.4.jar
XXX/libs/android-support-v4.jar
XXX/libs/drawee-v0.8.0.jar
XXX/libs/fbcore-v0.8.0.jar
XXX/libs/fresco-v0.8.0.jar
XXX/libs/imagepipeline-okhttp-v0.8.0.jar
XXX/libs/imagepipeline-v0.8.0.jar
XXX/libs/library-2.4.0.jar
XXX/libs/okhttp-2.3.0.jar
XXX/libs/okio-1.3.0.jar

XXX/libs/armeabi/libbitmaps.so
XXX/libs/armeabi/libgifimage.so
XXX/libs/armeabi/libimagepipeline.so
XXX/libs/armeabi/libmemchunk.so
XXX/libs/armeabi/libwebp.so
XXX/libs/armeabi/libwebpimage.so

**Comment by michalgr** [comment]
This is the cause:
10-22 20:14:44.924: E/AndroidRuntime(13607): Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable

You did not list any resource files. How did you add Fresco to your project ? Did you follow http://frescolib.org/docs/index.html#eclipse-adt ?

**Comment by hejie** [comment]
Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable
                                                                   at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:128)
                                                                   at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:77)
                                                                   at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:60)
                                                                   at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:354)

**Comment by michalgr** [comment]
@hejie: are you an eclipse user as well ? Did you add res files to your eclipse project as well ?

**Comment by HildaChen** [comment]
I have the same problem. Eclipse project and have added the res/values/attrs.xml

**Comment by oprisnik** [comment]
Do you still experience these issues with newer versions of Fresco?

**Comment by oprisnik** [comment]
I assume that the problem has been resolved. Please let us know if you're still experiencing this issue.
