### ISSUE TITLE
Images removed on calling notifyDataSetChanged()

### ISSUE THREAD

**Issue by sourabhv** [facebook/fresco#687]
I am using EventBus in my code and when it fires an event from an activity I make some changes to a textview and call `notifyDataSetChanged` (I also tried `notifyItemChanged`) but that gave me similar issue and all images disappear, and their placeholder image is visible

Here's my code snippet from `onBindViewHolder`

    if (mHierarchies.get(position) == null) {
        GenericDraweeHierarchyBuilder builder = new GenericDraweeHierarchyBuilder(mContext.getResources())
                .setFadeDuration(300)
                .setPlaceholderImage(ContextCompat.getDrawable(mContext, R.color.secondary), ScalingUtils.ScaleType.CENTER_CROP)
                .setProgressBarImage(new BorderProgressDrawable(mContext), ScalingUtils.ScaleType.CENTER_INSIDE)
                .setRetryImage(ContextCompat.getDrawable(mContext, R.drawable.ic_retry), ScalingUtils.ScaleType.CENTER_INSIDE)
                .setFailureImage(ContextCompat.getDrawable(mContext, R.drawable.ic_error), ScalingUtils.ScaleType.CENTER_INSIDE)
                .setPressedStateOverlay(ContextCompat.getDrawable(mContext, R.drawable.overlay));
        mHierarchies.put(position, builder.build());
    }

    ImageRequestBuilder requestBuilder = ImageRequestBuilder
            .newBuilderWithSource(Uri.parse(url))
            .setImageType(ImageRequest.ImageType.SMALL);
    holder.mImage.setController(Fresco.newDraweeControllerBuilder()
            .setImageRequest(requestBuilder.build())
            .setTapToRetryEnabled(true)
            .setOldController(holer.mImage.getController())
            .build());

And here is the part which calls `notifyDataSetChanged` when an event from EventBus is received

    public void updateLikeOnItem(String id, boolean liked, int likeCount) {
        for (int i = 0; i < mPhotos.size(); i++) {
            if (mPhotos.get(i) != null && mPhotos.get(i).getId().equals(id)) {
                mPhotos.get(i).setLiked(loved);
                mPhotos.get(i).setLikeCount(likeCount);
                notifyDataSetChanged(); // and bam! images are gone
                break;
            }
        }
    }

Also, I remember reading something about not recreating `DraweeHierarchy` objects in the docs so I am keeping them in an `ArrayList` as well, is that alright?

**Comment by michalgr** [comment]
You don't have to cache instances of `DraweeHierarchy` on your own. Create hierarchies in `onCreateViewHolder` as in our sample app: https://github.com/facebook/fresco/blob/v0.8.0/samples/comparison/src/main/java/com/facebook/samples/comparison/adapters/FrescoAdapter.java#L44 and rely on views to cache them for you.

**Comment by michalgr** [comment]
When placeholders appear, do actual images show up after a while ?

**Comment by sourabhv** [comment]
No, they show up if I move the views out of screen by scrolling down and then scrolling back up, so I guess when `onBindViewHolder` is called again?

**Comment by tyronen** [comment]
This sounds like onAttach/onDetach is not called correctly.

What is your holder.mImage? Is it a SimpleDraweeView or something else?

**Comment by kevinzetterstrom** [comment]
I faced a similar issue - my solution was to set a tag (```setTag```) on the drawee view with the uri that I also set on the drawee view. This way, when onBindViewHolder is called again, you can check the tag of the drawee view, and only set the image uri if the tag is different that the uri.

In this example, ```imageUrl``` is a String representing the url of my image:
    
    String lastImageUri = (String) viewHolder.simpleDraweeView.getTag();
    if ((imageUrl != null) && (lastImageUri == null || !lastImageUri.equals(imageUrl) ||
      viewHolder.simpleDraweeView.getDrawable() == null)) {
        Uri uri = Uri.parse(imageUrl);
        viewHolder.simpleDraweeView.setTag(imageUrl);
        viewHolder.simpleDraweeView.setImageURI(uri);
    }

**Comment by sourabhv** [comment]
@tyronen I guess it was the ArrayList of GenericDraweeHierarchy I was using causing this. I switched to caching it in View holder and it fixed the issue, I'll reopen this issue if it occurs again. @kevinzetterstrom Thanks, I'll try your solution if it occurs again
