### ISSUE TITLE
Where does freso unpin image?

### ISSUE THREAD

**Issue by caihanyuan** [facebook/fresco#688]
I find <b>pin</b> image in  
```javascript
DalvikBitmapFactory.createBitmap(short width, short height),
```
but i can't find anywhere to upin image.
I look for unpin in <b>CloseableBitmap</b>, but they just do like this:
```javascript
 public void close() {
    CloseableReference<Bitmap> reference;
    synchronized (this) {
      if (mBitmapReference == null) {
        return;
      }
      reference = mBitmapReference;
      mBitmapReference = null;
      mBitmap = null;
    }
    reference.close();
  }
```
this cose just release refrence to image,  Can someone help me please？

**Comment by michalgr** [comment]
Bitmaps are never unpinned. They are recycled when they are not needed anymore.

**Comment by caihanyuan** [comment]
@michalgr thanks!
