### ISSUE TITLE
Tiling a Bitmap in SimpleDraweeView?

### ISSUE THREAD

**Issue by skptl** [facebook/fresco#691]
How do I tile a bitmap before displaying it in SimpleDraweeView?

http://frescolib.org/docs/scaling.html#none doesn't make it clear, so for now I have to use native ImageView and use Fresco pipeline to fetch just the Bitmap, repeat it with a BitmapDrawable and display which I guess is not a very good way.

I tried doing it in a PostProcessor but the Bitmap received in process(Bitmap destBitmap, Bitmap sourceBitmap) is already streched.

**Comment by massimocarli** [comment]
Thanks for your comment. We'll add some more specific documentation about that.

**Comment by skptl** [comment]
Thanks @massimocarli for the response, but for now what I am doing is a correct way?

**Comment by kirwan** [comment]
I'm cleaning up very old issues. If this is still something you think is needed please comment and we can re-open.
