### ISSUE TITLE
SimpleDraweeView use in the RecyclerView which with the GridLayoutManager loading bitmap perform so bad. I even can't stand

### ISSUE THREAD

**Issue by caixuejian** [facebook/fresco#692]
// Java Code 
GridLayoutManager mLayoutManager = new GridLayoutManager(getActivity(), 3);
mRecyclerView.setLayoutManager(mLayoutManager);
...
protected class AbbrevFeedViewHolder extends RecyclerListAdapter.ViewHolder<Feed> implements View.OnClickListener {

        private final SimpleDraweeView mImageView;

        public AbbrevFeedViewHolder(ViewGroup parent) {
            this(LayoutInflater.from(getActivity()).inflate(R.layout.item_abbrev_feed, parent, false));
        }

        public AbbrevFeedViewHolder(@NonNull View view) {
            super(view);
            mImageView = (SimpleDraweeView) view.findViewById(R.id.image);
        }

        @Override
        public void bind(Feed feed, int position) {
            itemView.setOnClickListener(this);

            mImageView.setImageURI(Uri.parse(cdn(feed.primaryImage().id())));
        }

        @Override
        public void onClick(View view) {
            startActivity(FeedDetailActivity.createIntent(getActivity(), (Feed) getAdapter().getItem(getAdapterPosition())));
        }
    }
// xml 
FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/card_view"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content">
    <com.facebook.drawee.view.SimpleDraweeView  
        android:id="@+id/image"
        android:layout_width="120dp"
        android:layout_height="120dp"
        android:layout_margin="0.5dp"
        app:fadeDuration="0"
        app:actualImageScaleType="centerCrop" />
</FrameLayout

**Comment by massimocarli** [comment]
Please use our comparison app as a reference for `Drawee` into a `RecyclerView`.
