### ISSUE TITLE
when I add "compile 'com.facebook.fresco:fresco:0.8.0+'" to the dependencies section of my build.gradle file and build

### ISSUE THREAD

**Issue by huangtaoAppple** [facebook/fresco#693]
Error:A problem occurred configuring project ':app'.
> Could not download imagepipeline.aar (com.facebook.fresco:imagepipeline:0.8.0)
   > Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/0.8.0/imagepipeline-0.8.0.aar'.
      > Could not GET 'https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/0.8.0/imagepipeline-0.8.0.aar'.
         > peer not authenticated

**Comment by UmeshAawte** [comment]
Please read this thread https://github.com/facebook/fresco/issues/672#issuecomment-151138283

**Comment by tyronen** [comment]
And also try again with 0.8.1.

**Comment by siahewei** [comment]
I have changed "compile 'com.facebook.fresco:fresco:0.8.1+'" to "compile 'com.facebook.fresco:fresco:0.8.1'", and it works well
