### ISSUE TITLE
lag when display scrennshots of PNG format

### ISSUE THREAD

**Issue by MichaelArchangel** [facebook/fresco#694]
Init in application class:
ImagePipelineConfig config = OkHttpImagePipelineConfigFactory
                .newBuilder(this, BMNet2.getInstance().getClient())
                .setDownsampleEnabled(true)
        .build();
        Fresco.initialize(this,config);

In image adapter:
SimpleDraweeView iv = (SimpleDraweeView) context.getView(R.id.item_gallery_folder_image);
                    int width = iv.getWidth(), height = iv.getHeight();//463x463 px
                    ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(file_path))
                            .setResizeOptions(new ResizeOptions(width, height))
                            .build();
                    PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                            .setOldController(iv.getController())
                            .setImageRequest(request)
                            .build();
                    iv.setController(controller);

Still lag when display device's screenshots of PNG format...

**Comment by massimocarli** [comment]
Please use our demo apps as references for the usage of Fresco with a ListView o RecyclerView.
