### ISSUE TITLE
roundAsCircle not working

### ISSUE THREAD

**Issue by ihash** [facebook/fresco#695]
Hi
I'm using Fresco everything is Ok but roundAsCircle attribute seem not having any effects...
I dont get any error to post here what should i do?

**Comment by massimocarli** [comment]
Hi,
can you provide us more information about that please? Have you applied what's here? http://frescolib.org/docs/rounded-corners-and-circles.html 

Thanks

**Comment by ihash** [comment]
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/vendor_image"
                android:layout_width="100dp"
                android:layout_height="100dp"
                android:layout_gravity="center"
                fresco:placeholderImage="@drawable/design1"
                fresco:roundedCornerRadius="5dp"
                fresco:viewAspectRatio="1"/>

**Comment by ihash** [comment]
Hellloooo....

**Comment by tyronen** [comment]
Your `viewAspectRatio` won't make any difference here. Can you post:

- the original image you are using
- a screenshot of what it looks like with this code?
