### ISSUE TITLE
How to customize ImageDecoder? the file might be base64 or encrypted

### ISSUE THREAD

**Issue by Stay** [facebook/fresco#696]
here is the scenario: 
the image from server is encrypted, so it should be decrypted when decode as a image.
i read the sourcecode, Postprocessor can't do the decryption, maybe i could use ImageDecoder to decrypt before decode as a image. but i found it is hard to customize ImageDecoder.
do you have any advise about this?

**Comment by massimocarli** [comment]
With the `ImagePipelineConfig` class you have the opportunity to inject an `ImageDecoder`. At the moment it's a class but not final so you could extend it and override the methods you need. At the moment we don't have immediate plan to abstract this step.
