### ISSUE TITLE
Get a bitmap from SimpleDraweeView

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#699]
Is it possible to get the bitmap which is being displayed by the SimpleDraweeView ?

**Comment by massimocarli** [comment]
From the `SimpleDraweeView` you can get the `DraweeHierarchy` and the current `Drawable`. If it's a `BitmapDrawable`, or any other Drawable implementation that publish the related image, you can get the related `Bitmap`.

**Comment by droidekas** [comment]
Sounds good,thanks!

**Comment by LOG-TAG** [comment]
Any coding example available for getting DraweeHierarchy from SimpleDraweeView ? After clicking on share button of recycler view item I can't be redownload the image and share it (example like this https://guides.codepath.com/android/Displaying-Images-with-the-Fresco-Library), so thinking of sharing the already downloaded image in the recyclerview item!

**Comment by LOG-TAG** [comment]
https://github.com/codepath/android_guides/wiki/Displaying-Images-with-the-Fresco-Library
