### ISSUE TITLE
Leaks.

### ISSUE THREAD

**Issue by HomHomLin** [facebook/fresco#702]
Look the pic as follows, do I use the fresco in a wrong way?
![pic](http://f2.topitme.com/2/a4/ee/1145936993dd3eea42o.jpg)

**Comment by HomHomLin** [comment]
I just do like this, no leak happened when you are normal use, leaks in sometime ,I don't know why :
            mRequest = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setLocalThumbnailPreviewsEnabled(true)
                    .build();
        }

        mController = Fresco.newDraweeControllerBuilder()
                .setImageRequest(mRequest)
                .setAutoPlayAnimations(mAnim)
                .setOldController(this.getController())
                .build();

        this.setController(mController);

**Comment by kaedea** [comment]
Which instance has leak?

**Comment by tyronen** [comment]
Your link does not work.

**Comment by HomHomLin** [comment]
Ok,I have re-commit the pic:
![pic](http://ww2.sinaimg.cn/bmiddle/6e4e0c91gw1exft2il5n0j20o30jkdrm.jpg)

**Comment by michalgr** [comment]
How do you determine that given byte array is a leak ?

**Comment by oprisnik** [comment]
The picture doesn't work any more.
We also need more sample code how Fresco is used.
I'm closing this for now, but feel free to update with more details and we can re-open this issue.
