### ISSUE TITLE
Image Color is modified

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#703]
If i am loading image to simpledraweeview then the image color is modified like some mask is apply for top of the image.

**Comment by massimocarli** [comment]
Can you provide the layout resource and a snippet of code you're using please? Also a link to the image you're loading could be very useful.
Thanks

**Comment by karun2189** [comment]
Here is my layout resource 
 <com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/fake_image"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:layout_gravity="center|center_horizontal|center_vertical"
                android:adjustViewBounds="true"
                android:contentDescription="@string/app_name"
                android:scaleType="centerInside" />

**Comment by tyronen** [comment]
You should use fresco:actualImageScaleType if this is a SimpleDraweeView.

What is the image itself? Can you upload a screenshot of how it is rendered?
