### ISSUE TITLE
Change Network Request parameters for image

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#704]
Can i set a custom retry policy and network timeout for network image request?

**Comment by massimocarli** [comment]
In our implementation we keep the network layer decoupled from the ImagePipeline; not all images are loaded from network. We'll probably add the chance to set some header to the HTTP request and we're evaluating the same for other features.

**Comment by droidekas** [comment]
For the time being,I am using a counter for retrying.But it would be helpful to have such a  functionality.

**Comment by zhuAria** [comment]
Can you give me an example, for this problem @droidekas

**Comment by droidekas** [comment]
Some image requests timeout/any other error,and the request will not be triggerred again till the view is removed from the viewport and then brought back.So I just set a new Controller to the DraweeView when  the image request fails.Using a counter ,i make sure that this does not flood the RequestQueue

**Comment by zhuAria** [comment]
Thanks for you reply @droidekas

**Comment by erikandre** [comment]
The solution to get more control over how requests are performed would be to write a custom Network fetcher. See NetworkFetcher and OkHttpNetworkFetcher.
