### ISSUE TITLE
Is it possible to add a bitmap into BitmapMemoryCache manually?

### ISSUE THREAD

**Issue by chethann** [facebook/fresco#705]
I need to manually add a bitmap to the cache specifying the URI (as key). If the request URI to download the image matches with the key, I need the pipeline to load the bitmap from the cache instead of making the network call.

I found this method `Fresco.getImagePipelineFactory().getBitmapMemoryCache().cache( cacheKey, closeableReference)`. But how to get a closableReference to an arbitrary bitmap. Please help. Thank you.

**Comment by massimocarli** [comment]
Here you can find the information you need.
http://frescolib.org/docs/closeable-references.html#_
