### ISSUE TITLE
Pause and restart processing queue

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#706]
How can i stop processing queue during scroll in listview making smooth scroll ? How can i achieve this?  Thanks

**Comment by massimocarli** [comment]
`ImagePipeline` is already design in order to optimize the load of the images. The `Drawee` framework is then optimize to interact with the `ImagePipeline`. Do you have any specific use case? What do you mean with 'stop processing queue'?
Thanks

**Comment by karun2189** [comment]
My use case is  : If the image is not available in memory i will create the snapshot based on my views.If i am scrolling at that time may be scroll is stuck....

**Comment by tyronen** [comment]
Duplicate of #512
