### ISSUE TITLE
How to load big picture which size is bigger than 4M?

### ISSUE THREAD

**Issue by sidneywang** [facebook/fresco#710]
When I load a jpeg picture which size is bigger than 4M, fresco throw a exception named PoolSizeViolationException. 
The problem is how can I load a big picture?

I noticed Fresco read all encoded image bytes to memory, why do it?

**Comment by xialixue007** [comment]
+ 1

**Comment by xialixue007** [comment]
i have the same issue

**Comment by tyronen** [comment]
[Resize](http://frescolib.org/docs/resizing-rotating.html#resizing) your image before decoding it.  Be sure not to enable downsampling.

**Comment by sidneywang** [comment]
If the origin jpeg file is bigger than 4M. Resize options is no effert.
