### ISSUE TITLE
BPG Support

### ISSUE THREAD

**Issue by sourabhv** [facebook/fresco#711]
BPG (Better Portable Graphics) is a new image format. Its purpose is to replace the JPEG image format when quality or file size is an issue. Its main advantages are:

High compression ratio. Files are much smaller than JPEG for similar quality.
Supported by most Web browsers with a small Javascript decoder (gzipped size: 56 KB).
Based on a subset of the HEVC open video compression standard.
Supports the same chroma formats as JPEG (grayscale, YCbCr 4:2:0, 4:2:2, 4:4:4) to reduce the losses during the conversion. An alpha channel is supported. The RGB, YCgCo and CMYK color spaces are also supported.
Native support of 8 to 14 bits per channel for a higher dynamic range.
Lossless compression is supported.
Various metadata (such as EXIF, ICC profile, XMP) can be included.
Animation support.
Source: http://bellard.org/bpg/

Some people have added it to Android apps already.
https://github.com/alexandruc/android-bpg

Note: Shamelessly copied from [here](https://github.com/owncloud/android/issues/1026)

**Comment by massimocarli** [comment]
Thank you for this proposal. We're evaluating the support for other types of images but not in the short term.
