### ISSUE TITLE
Performance Consideration: Return HTTP Status Code or Header

### ISSUE THREAD

**Issue by mingqlin** [facebook/fresco#712]
It would be helpful if Fresco can return HTTP Status Code (and it is also nice to return HTTP Header as well) for every ImageRequest excuted. The HTTP Status Code Fresco returns could be use to tweak the future Image requests. 

For example, in following Sample Code, It requests to remote server to see if avatar exist, if not, it will next request to local storage to get the avatar. If application could read HTTP Status Code or Header, it can understand the Image doesn't exist on Server, as result, it can add login to exclude future request to the server.
## Sample Code

ImageRequest requestServer = ImageRequestBuilder.newBuilderWithSource(avatarServerUri).build();
ImageRequest requestPlaceholder = ImageRequestBuilder.newBuilderWithSource(avatarPlaceholderUri).build();

List<ImageRequest> imageRequests = new ArrayList<>();

imageRequests.add(requestServer);
imageRequests.add(requestPlaceholder);

DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setFirstAvailableImageRequests(imageRequests.toArray(new ImageRequest[imageRequests.size()]))
                .setOldController(draweeView.getController())
                .build();
        draweeView.setController(controller);

**Comment by massimocarli** [comment]
The ImagePipeline should be decoupled form the source of the image that is not always the web. In any case we're working on providing some more information about the HTTP stack when we make a request and when we get a response.
Thanks

**Comment by erikandre** [comment]
Closing. This would be useful but it also break the abstractions we have to decouple image fetching.
