### ISSUE TITLE
setPlaceholderImage, setFailureImage and setOverlay support Uri and load Image from Cache

### ISSUE THREAD

**Issue by mingqlin** [facebook/fresco#713]
At this moment, we have to construct Drawable everytime we call setPlaceholderImage, setFailureImage and setOverlay. It would be ideal if we could call using Uri, and it could load image from Pipeline memory and disk cache for better performance.

**Comment by massimocarli** [comment]
Most of the time the placeholder and failure images are already into the application and not loaded from a different sources. Anyway, we'll consider other way to se those images.
Thanks

**Comment by mingqlin** [comment]
Thanks for the response. These days it is popular for Android app (like Gmail) to have cycle text avatar (similar to this library https://github.com/amulyakhare/TextDrawable), Since we use Fresco, we pre-generate all round text as pngs, and load them as placeholder. there could be many different pngs as round text, which is reason we think it is more memory efficient and better performance, if we could load Fresco placeholder through Fresco pipeline.

**Comment by massimocarli** [comment]
Sure, we'll definitely improve that. 
Thanks
