### ISSUE TITLE
FetchDecodedImage return recycled bitmap

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#717]
I am getting "Canvas: trying to use a recycled bitmap" error. If i am get bitmap from cache by using below code 

```java
ImagePipeline imagePipeline = Fresco.getImagePipeline();
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(Uri.fromFile(new File(url)))
                .build();

        DataSource<CloseableReference<CloseableImage>>
                dataSource = imagePipeline.fetchDecodedImage(imageRequest, mContext);
        dataSource.subscribe(new BaseBitmapDataSubscriber() {

                                 @Override
                                 public void onNewResultImpl(@Nullable Bitmap bitmap) {
                                     if (cacheListener != null) {
                                         cacheListener.onAvailableBitmap(bitmap);
                                     }
                                 }

                                 @Override
                                 public void onFailureImpl(DataSource dataSource) {
                                     if (cacheListener != null) {
                                         cacheListener.onAvailableBitmap(null);
                                     }
                                 }
                             },
                CallerThreadExecutor.getInstance());
```

Why i am getting this error ?  I am getting frequently.. 
Thanks

**Comment by massimocarli** [comment]
As documentation says the Bitmap into the `onNewResultImpl()` method  is only guaranteed to be around for the lifespan of the method. This means you have to consume the image into that method. Probably you're keeping the image around. Try to use a `BaseDataSubscriber` instead. 

https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/imagepipeline/src/main/java/com/facebook/imagepipeline/datasource/BaseBitmapDataSubscriber.java#L71

**Comment by karun2189** [comment]
I am getting same exception if i am using below code
ImagePipeline imagePipeline = Fresco.getImagePipeline();
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(Uri.fromFile(new File(url)))
                .build();

        DataSource<CloseableReference<CloseableImage>>
                dataSource = imagePipeline.fetchDecodedImage(imageRequest, mContext);
        dataSource.subscribe(new BaseDataSubscriber<CloseableReference<CloseableImage>>() {
            @Override
            protected void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                if (!dataSource.isFinished()) {
                    return;
                }

                CloseableReference<CloseableImage> closeableImageRef = dataSource.getResult();
                Bitmap bitmap = null;
                if (closeableImageRef != null &&
                        closeableImageRef.get() instanceof CloseableBitmap) {
                    bitmap = ((CloseableBitmap) closeableImageRef.get()).getUnderlyingBitmap();
                }

                if(cacheListener != null){
                    cacheListener.onAvailableBitmap(bitmap);
                }
            }

            @Override
            protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                if(cacheListener != null){
                    cacheListener.onAvailableBitmap(null);
                }
            }
        }, CallerThreadExecutor.getInstance());

**Comment by massimocarli** [comment]
How are you using the image into the Canvas? Can you provide a snippet please?
Thanks

**Comment by karun2189** [comment]
Bitmap = "this bitmap i am getting from cache."
Drawable d = new BitmapDrawable(getResources(), bitmap);
CustomImageSpan imageSpan = new CustomImageSpan(d,ImageSpan.ALIGN_BASELINE);
editable.setSpan(imageSpan, (start), (end), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);

Here set span will automatically call invalidate at that time i am getting the exception.

**Comment by massimocarli** [comment]
At some stage there's a call to Bitmap `recycle()` probably in `CustomImageSpan`. Could you check if the Bitmap in the onNewResultImpl() has isRecycled() returning false?

Thanks

**Comment by karun2189** [comment]
We are not calling the recycle method. If we are get directly bitmap from path it will work fine without using cache if we are use cache the it will show the exception

**Comment by massimocarli** [comment]
Do you mean ImagePipeline caches or another cache implementation?

**Comment by karun2189** [comment]
ImagePipeline caches

**Comment by karun2189** [comment]
What details you need ? The exception is occur frequently.....If you give solution its great helpful for me

**Comment by tyronen** [comment]
Your code above is wrong. You are taking the Bitmap out of the `CloseableReference` and passing it to the rest of your app. When the reference count goes to zero, your Bitmap will be recycled without warning.

You should instead pass the `CloseableReference<Bitmap>` to the rest of your app, and hold a reference to it. When you are done with the Bitmap, then call `close()`.

**Comment by karun2189** [comment]
@tyronen If i close the CloseableReference after setting the bitmap again i am getting same exception ? Can you explain me why this occur what i want to do

**Comment by tyronen** [comment]
That sounds like you are closing the reference too early. Once you have called close, you should never again pass that bitmap to any draw method.

**Comment by happyjosh** [comment]
@massimocarli @tyronen @karun2189  I am also having same issues when I use CustomImageSpan。So,When should I close the reference?

**Comment by oprisnik** [comment]
You should close the reference when nothing holds on to the bitmap and when the bitmap will never be rendered again.

**Comment by happyjosh** [comment]
Now I create a new bitmap by old from fresco to resolve the problem.Because I can not exactly judge whether be rendered.

**Comment by ThugKd** [comment]
I am getting same exception if i am using below code

public static void setImageUrl(final ImageView view, String url) {
        final ImageRequest request = ImageRequestBuilder
                .newBuilderWithSource(Uri.parse(url))
                .build();
        Fresco.getImagePipeline()
                .fetchDecodedImage(request, view.getContext().getApplicationContext())
                .subscribe(new BaseBitmapDataSubscriber() {
                    @Override
                    protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {

                    }

                    @Override
                    protected void onNewResultImpl(Bitmap bitmap) {
                        if (bitmap != null) {
                            view.setImageBitmap(bitmap);
                        }
                    }
                }, UiExecutor);
    }

**Comment by oprisnik** [comment]
See the first comment. The bitmap will be recycled once `onNewResultImpl` is done. You have to use a `BaseBitmapReferenceDataSubscriber` instead and properly manage the lifecycle of the reference.
