### ISSUE TITLE
Is it possible to know when the image is finished loading?

### ISSUE THREAD

**Issue by silverAndroid** [facebook/fresco#719]
I want to put a ProgressBar animation on top of the image and when it's done loading, make it disappear. However, I want to use the ProgressBar View provided by Android.

**Comment by tyronen** [comment]
We don't directly support Android's ProgressBar, because it's not a Drawable. You could define your own that looks similar. See the [progress bar docs](http://frescolib.org/docs/progress-bars.html#_).

**Comment by silverAndroid** [comment]
I understand it's not supported directly but I was going to put it above the DraweeView, so I just wanted to know if there was a method to know if the Image was done loading.

**Comment by tyronen** [comment]
Use a [controller listener](http://frescolib.org/docs/listening-download-events.html#_)
