### ISSUE TITLE
How can I obtain the image from disk cache?

### ISSUE THREAD

**Issue by MohamadAtieh** [facebook/fresco#720]
I am trying to use [this library](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/X.-Using-with-Picasso) with Fresco. How can I know whether the image I click on is in the disk cache and is there a way to create custom decoders? 

Thanks

**Comment by tyronen** [comment]
Follow [these instructions](http://frescolib.org/docs/caching.html#checking-to-see-if-an-item-is-in-cache) to see if an item is in cache.

You can specify a custom decoder when [configuring the image pipeline](http://frescolib.org/docs/configure-image-pipeline.html#_). Use the `setImageDecoder` method.

**Comment by MohamadAtieh** [comment]
I used the suggested method on that page, but when you have a list of images loaded and you invoke the method once, and it works, but not the second time on another image. Is there a way to *always* have the image in disk cache, or is it the default behavior?

If I every have to wait for an image request to finish (be in disk cache), how can I listen to those events and execute? Is `fetchEncodedImage` with the Data Source be sufficient?

**Comment by tyronen** [comment]
No. Images are not in cache until they've been downloaded, and they will be evicted from cache if the cache fills up. Eviction goes by least-recently-used; so if you want to prevent an image from being evicted, fetch it again.

You can also make use of two caches by using the [small cache](http://frescolib.org/docs/caching.html#using-one-disk-cache-or-two).

If you call `fetchEncodedImage`, you get a DataSource. Add a DataSubscriber to that DataSource, and it will get called when the image is downloaded. After that it will remain in cache until evicted.

**Comment by MohamadAtieh** [comment]
And the small cache is applied to any image request. even the low resolution one? I am loading thumbnails before the actual image and I think the default disk cache behavior applies to the actual image request. 

https://github.com/Redgram/redgram-for-reddit/blob/dev/Redgram/app/src/main/java/com/matie/redgram/ui/common/views/widgets/postlist/dynamic/PostItemImageView.java#L127 

What I am currently doing in my app is that *only* if the image is in disk cache, preview the image in a new fragment. Which is not ideal since some images take time to load.

I am trying to click on the drawee view however it is and **continue** listen to it in the new fragment, and then load the downloaded image from cache. 

That's why I was asking about `fetchEncodedImage`
