### ISSUE TITLE
The way for the image is there?

### ISSUE THREAD

**Issue by yljjiava** [facebook/fresco#721]
I have a custom imageview, for example, you want to display images in through the fresco "to the imageview when  simpleDraweeView. setImageUrl ()  not make, fresco" whether there is a similar to Glide.load(url).into(imageview)  loading pictures that way?

**Comment by tyronen** [comment]
I don't understand your question.

If you mean you cannot use SimpleDraweeView, you can use our [custom view](http://frescolib.org/docs/writing-custom-views.html#_) support.

Please open a new issue if that was not your question.
