### ISSUE TITLE
Why not show the modified pictures in SimpleDraweeView

### ISSUE THREAD

**Issue by MuFe** [facebook/fresco#724]
public static void GeneriRotePhotoDraweeHierarchy(SimpleDraweeView view,
			PhotoInfo info, RoteListener listener) {
               GenericDraweeHierarchyBuilder builder = new GenericDraweeHierarchyBuilder(
				view.getResources());
		GenericDraweeHierarchy hierarchy = builder.setFadeDuration(50).build();
		hierarchy.setPlaceholderImage(R.drawable.water_bg);
		hierarchy.setActualImageScaleType(ScaleType.CENTER_CROP);
		view.setHierarchy(hierarchy);
		Uri uri = Uri.parse(info.getUrl());
		ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
				.setProgressiveRenderingEnabled(true)
				.setPostprocessor(new FrescoUtil().new MeshPostprocessor(info,listener))
				.setAutoRotateEnabled(true).build();

             DraweeController controller = Fresco.newDraweeControllerBuilder()
				.setImageRequest(request).setTapToRetryEnabled(true)
				.setOldController(view.getController())
				.build();
		view.setController(controller);
      }

      public class MeshPostprocessor extends BasePostprocessor {
		private PhotoInfo info;
		private RoteListener listener;
		public MeshPostprocessor(PhotoInfo info, RoteListener listener) {
			this.info = info;
			this.listener = listener;
		}

		public MeshPostprocessor(PhotoInfo info) {
			this.info = info;
		}

		@Override
		public String getName() {
			return "meshPostprocessor";
		}

		@Override
		public void process(Bitmap destBitmap, Bitmap sourceBitmap) {
			// TODO Auto-generated method stub
			super.process(destBitmap, sourceBitmap);
		}
		@Override
		public void process(Bitmap bitmap) {
			// TODO Auto-generated method stub
			Matrix matrix = new Matrix();
			if (info.getRotion() != 0) {
				matrix.setRotate(info.getRotion());
				// 重新绘制Bitmap
			}
			if (!info.getUrl().startsWith("http")) {
				info.setInfo(new int[] { bitmap.getWidth(),
						bitmap.getHeight() });
			}
			
			bitmap = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(),
					bitmap.getHeight(), matrix, true);
			if(listener!=null){
				listener.returenBitmap(bitmap);
			}
		}
	}

**Comment by tyronen** [comment]
See the [API docs](http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/request/BasePostprocessor.html#process(android.graphics.Bitmap)) for the method you called. You have to make your changes to the passed-in bitmap for them to appear. You're creating a whole new Bitmap, which is not returned anywhere and will simply get garbage-collected.

You should override this method instead:
```public CloseableReference<Bitmap> process (Bitmap sourceBitmap, PlatformBitmapFactory bitmapFactory)```

Instead of calling `Bitmap.createBitmap`, you can then call `bitmapFactory.createBitmap`.
