### ISSUE TITLE
Image is not storing in Disk Cache

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#725]
Hi, 

When the image is store to disk cache. if i am checking below code it always return false

```java
DataSource<Boolean> inDiskCacheSource = imagePipeline.isInDiskCache(uri);
DataSubscriber<Boolean> subscriber = new BaseDataSubscriber<Boolean>() {
    @Override
    protected void onNewResultImpl(DataSource<Boolean> dataSource) {
      if (!dataSource.isFinished()) {
        return;
      }
      boolean isInCache = dataSource.getResult();
      // your code here
    }
  };
inDiskCacheSource.subscribe(subscriber, executor);
```

**Comment by karun2189** [comment]
My disk cache config is 

private static void configureCaches(
      ImagePipelineConfig.Builder configBuilder,
      Context context) {
    final MemoryCacheParams bitmapCacheParams = new MemoryCacheParams(
        MAX_MEMORY_CACHE_SIZE, // Max total size of elements in the cache
        Integer.MAX_VALUE,                     // Max entries in the cache
        MAX_MEMORY_CACHE_SIZE, // Max total size of elements in eviction queue
        Integer.MAX_VALUE,                     // Max length of eviction queue
        Integer.MAX_VALUE);                    // Max cache entry size
    configBuilder
        .setBitmapMemoryCacheParamsSupplier(
            new Supplier<MemoryCacheParams>() {
              public MemoryCacheParams get() {
                return bitmapCacheParams;
              }
            })
        .setMainDiskCacheConfig(
            DiskCacheConfig.newBuilder()
                .setBaseDirectoryPath(context.getApplicationContext().getCacheDir())
                .setBaseDirectoryName(IMAGE_PIPELINE_CACHE_DIR)
                .setMaxCacheSize(MAX_DISK_CACHE_SIZE)
                .build());
  }

**Comment by karun2189** [comment]
What details you need ?

**Comment by tyronen** [comment]
Try this: 

```java
ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(uri)
    .setLowestPermittedRequestLevel(RequestLevel.DISK_CACHE)
    .build(();

DataSource dataSource = imagePipeline.fetchDecodedImage(imageRequest, callerContext);
dataSource.subscribe(new BaseBitmapDataSubscriber() {
    @Override
    public void onNewResultImpl(@Nullable Bitmap bitmap) {
        if (bitmap != null) {
            Log.w("Debug", "The bitmap is in cache!!!");
        }
    }
  },
  executor);
```

This will determine if the image is, in fact, in cache.

**Comment by karun2189** [comment]
I am using that function but the bitmap is not null. Is it bitmap is came from disk cache ? How can i identifiy whether it came from disk or memory cache ?

**Comment by plamenko** [comment]
Can you give us some context on what are you actually trying to do?
`imagePipeline.isInDiskCache` will return whether the image is in the disk cache. But this won't download the image and put it in the disk cache. This merely checks whether the image is there or not.

Doing the following will prefetch the image in the disk cache:

```java
imagePipeline.prefetchToDiskCache(ImageRequest.fromUri(uri), callerContext);
```

If the above succeeds, your `isInDiskCache` code should yield true.

**Comment by yy1300326388** [comment]
@plamenko  I create``` ImageRequest setRequestListener onRequestSuccess ```method ```Fresco.getImagePipeline().isInDiskCacheSync(request)``` return false

but I wait a minute  return true.

How do create cache finish listener?
