### ISSUE TITLE
JNI errors on Baba MX-4 Pro with WebP

### ISSUE THREAD

**Issue by goodboywt** [facebook/fresco#726]
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: java_class == null
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]     in call to GetStaticMethodID
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]     from android.graphics.Bitmap android.graphics.BitmapFactory.nativeDecodeStream(java.io.InputStream, byte[], android.graphics.Rect, android.graphics.BitmapFactory$Options)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65] "Thread-933" prio=5 tid=68 Runnable
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12fe60e0 self=0xb405ac00
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   | sysTid=23996 nice=10 cgrp=apps/bg_non_interactive sched=0/0 handle=0xb406e300
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=1 stm=0 core=2 HZ=100
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   | stack=0x9399c000-0x9399e000 stackSize=1036KB
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at android.graphics.BitmapFactory.nativeDecodeStream(Native method)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.bitmaps.a.b(SourceFile:163)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.bitmaps.a.a(SourceFile:89)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.bitmaps.g.a(SourceFile:87)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.decoder.a.a(SourceFile:124)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.decoder.a.a(SourceFile:91)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.t.c(SourceFile:188)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.t.a(SourceFile:96)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.u.a(SourceFile:128)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.JobScheduler.e(SourceFile:207)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.JobScheduler.a(SourceFile:27)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.aj.run(SourceFile:78)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-04 11:15:03.226 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.b.m.run(SourceFile:43)
11-04 11:15:03.231 23814-23996/? A/art: art/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:818)

Occurred in android 5.0 with some devices

**Comment by goodboywt** [comment]
Our app has 50 million users in China，this error is very serious。Can you help us?

**Comment by tyronen** [comment]
This seems to be a build problem - at run time, it's apparently unable to get a system class from JNI code. 

Are you using v0.8.0? We have had issues with that - please upgrade to v0.8.1.

You can also make sure you are doing a completely clean build for your production releases:

```
rm $HOME/.gradle/caches
rm .gradle
./gradlew clean
./gradlew build
```

Do you get the issue in debug builds?

**Comment by goodboywt** [comment]
We tried 0.6.1;0.7;0.8.1,unfortunately ,our app occurred this error again. Now we doubt the device's OS,it may change some JNI class . we have not encounter this error before the device upgrade OS.But this device's factory has sale 20 millions devices in china,so we must adjust it.But it may not be your fault.THX

**Comment by tyronen** [comment]
Please tell us the manufacturer and model name of this device. Is it available outside China?

**Comment by goodboywt** [comment]
The device's name is mx4,you can't directly buy it outside China. Do you know BABA，it is a E- business company from china，you can search the device at this site https://www.taobao.com/     or http://www.tmall.com.Maybe you can buy it.If you want to test this bug,you must upgrade the OS to the latest one

**Comment by goodboywt** [comment]
By the way, I found fresco decode image failed sometimes ,then there is no image but the background color,is it possible?

**Comment by goodboywt** [comment]
We found more details：
 
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception 'java.lang.NoClassDefFoundError' thrown in unknown throw location
11-06 18:56:30.306 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]     in call to NewGlobalRef
11-06 18:56:30.306 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]     from android.graphics.Bitmap android.graphics.BitmapFactory.nativeDecodeStream(java.io.InputStream, byte[], android.graphics.Rect, android.graphics.BitmapFactory$Options)
11-06 18:56:30.306 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65] "Thread-50900" prio=5 tid=76 Runnable
11-06 18:56:30.306 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x131b36e0 self=0x94602000
11-06 18:56:30.306 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   | sysTid=19959 nice=10 cgrp=apps/bg_non_interactive sched=0/0 handle=0x94611800
11-06 18:56:30.306 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=1 stm=0 core=2 HZ=100
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   | stack=0x93fea000-0x93fec000 stackSize=1036KB
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at android.graphics.BitmapFactory.nativeDecodeStream(Native method)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.platform.ArtDecoder.getDecodeOptionsForStream(ArtDecoder.java:178)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(ArtDecoder.java:78)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.decoder.ImageDecoder.decodeStaticImage(ImageDecoder.java:127)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:94)
11-06 18:56:30.311 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
11-06 18:56:30.326 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
11-06 18:56:30.326 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
11-06 18:56:30.326 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
11-06 18:56:30.326 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
11-06 18:56:30.326 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
11-06 18:56:30.326 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-06 18:56:30.331 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-06 18:56:30.331 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
11-06 18:56:30.331 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:818)
11-06 18:56:30.331 19657-19959/com.coohuaclient A/art: art/runtime/check_jni.cc:65]

**Comment by goodboywt** [comment]
New detail,we used webp format image in our app. Today we replace webp  with jpg ,then it worked well.

**Comment by aagnes** [comment]
Thanks for the updates. We'll investigate later.

**Comment by kirwan** [comment]
I'm cleaning up very old issues. If this still causes problems please comment and we can re-open.
