### ISSUE TITLE
use android:src error

### ISSUE THREAD

**Issue by caopeng000** [facebook/fresco#727]
I try to use andorid:src property lead to this application error!
Although i found use  fresco:placeholderImage property not lead to error 
so i want to know if i use android:src how to avert application error!Tanks!

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.drawee.view.DraweeHolder.setController(com.facebook.drawee.interfaces.DraweeController)' on a null object reference
11-04 01:10:22.822 6400-6400/? E/AndroidRuntime:     at com.facebook.drawee.view.DraweeView.setImageDrawable(DraweeView.java:140)
11-04 01:10:22.822 6400-6400/? E/AndroidRuntime:     at android.widget.ImageView.<init>(ImageView.java:148)
11-04 01:10:22.822 6400-6400/? E/AndroidRuntime:     at android.widget.ImageView.<init>(ImageView.java:135)
11-04 01:10:22.822 6400-6400/? E/AndroidRuntime:     at android.widget.ImageView.<init>(ImageView.java:131)
11-04 01:10:22.822 6400-6400/? E/AndroidRuntime:     at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:51)

**Comment by tyronen** [comment]
`android:src` is [not supported by Fresco](http://frescolib.org/docs/gotchas.html#don-t-use-imageview-attributes-or-methods-with-draweeview).
