### ISSUE TITLE
加载大图片

### ISSUE THREAD

**Issue by GCZeng** [facebook/fresco#729]
我使用Fresco框架加载网络图片，当图片太大(1M)的时候，图片没有显示，这个可以优化吗？

**Comment by terryyhl** [comment]
这个明显是你图片oom了。加下硬件加速，还不行的话试一下subsampling或者国人写的一个加载大图的框架

**Comment by GCZeng** [comment]
Fresco没有处理大图的？

**Comment by aagnes** [comment]
当使用大图的时候，请你按照你的需求使用resize或者downsampling。

**Comment by GCZeng** [comment]
好的，谢谢，用resize就可以了。
