### ISSUE TITLE
How to get GIF byte array from cache?

### ISSUE THREAD

**Issue by javaee2012** [facebook/fresco#731]
How to get GIF byte array from cache?
My app has a future download gif from network and save to sdcard.How to get GIF byte array from cache(memory or disk) through url.
Thanks

**Comment by tyronen** [comment]
Just fetch it as you normally would. Fresco always checks cache first.

If you don't want to go to network again, use `ImageRequestBuilder.setLowestPermittedRequestLevel`.

**Comment by javaee2012** [comment]
When I fetch, is there is no data in cache, It will be get data from the network?

**Comment by tyronen** [comment]
Yes. If the data is not in cache, it is fetched from network.
