### ISSUE TITLE
error：trying to use a recycled bitmap

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#735]
I am getting this error frequently my scenario is

I am creating Custom EditTextView i am adding image in that View. If i am adding a single image is working fine, if i am adding more than one image for first time its working fine if i am close and again open that activity it will through this error. if one image it will open without error.

If more than one image it get crashed . I am setting bitmap for imageSpan. What i exactly want is i want to store that image to cache and getback it from cache this is my scenario . Thanks

**Comment by tyronen** [comment]
If you are using an ImageSpan inside a view, then the images in the span should all belong to a MultiDraweeHolder. See the instructions for [custom views](http://frescolib.org/docs/writing-custom-views.html#_).

**Comment by karun2189** [comment]
Can you provide sample MultiDraweeHolder. How can i achieve this if you give some sample its helpful for me..
