### ISSUE TITLE
怎样设置加载最大缓存

### ISSUE THREAD

**Issue by GCZeng** [facebook/fresco#738]
我现在用fresco加载一个列表，列表每一个item都是一张图片，加载到大概10页面左右，就使用了200M左右的内存，这个内存可以通过回收控制吗，怎样优化？

**Comment by tianlang** [comment]
你是5.0以上系统吧，5.0以上系统 需要配置一下，不能无限制使用内存缓存

我是这样配置的：
public class LollipopBitmapMemoryCacheParamsSupplier implements Supplier<MemoryCacheParams> {

    private ActivityManager activityManager;

    public LollipopBitmapMemoryCacheParamsSupplier(ActivityManager activityManager) {
        this.activityManager = activityManager;
    }

    @Override
    public MemoryCacheParams get() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return new MemoryCacheParams(getMaxCacheSize(), 56, Integer.MAX_VALUE,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE);
        } else {
            return new MemoryCacheParams(
                    getMaxCacheSize(),
                    256,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE);
        }
    }

    private int getMaxCacheSize() {
        final int maxMemory = Math.min(activityManager.getMemoryClass() * ByteConstants.MB, Integer.MAX_VALUE);

        if (maxMemory < 32 * ByteConstants.MB) {
            return 4 * ByteConstants.MB;
        } else if (maxMemory < 64 * ByteConstants.MB) {
            return 6 * ByteConstants.MB;
        } else {
            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.GINGERBREAD) {
                return 8 * ByteConstants.MB;
            } else {
                return maxMemory / 4;
            }
        }
    }

}

**Comment by anAngryAnt** [comment]
@tianlang 可以问一下你为什么要这样配置么？ MemoryCacheParams的cacheEntries为什么要设置56和256？
