### ISSUE TITLE
How to get actual view size before onBindViewHolder() in Recyclerview

### ISSUE THREAD

**Issue by hhuimie** [facebook/fresco#740]
i'm loading some big image in a recyclerview.
i wanna resize it before it set to a SimpleDraweeView.
Question is i can not get the actual view size before that.
My item view layout is:
```xml
<***.SquaredFrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <com.facebook.drawee.view.SimpleDraweeView
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
    </***.SquaredFrameLayout>
```
the `SquaredFrameLayout` is a squared layout base on it's width

My adapter is like:
```java
@Override
public void onBindViewHolder(@NonNull List<Object> items, int position,
    @NonNull ViewHolder holder) {
    FeedViewHolder viewHolder = (FeedViewHolder) holder;
    ImageRequest request = ImageRequestBuilder.newBuilderWithSource(URI1)
        .setResizeOptions(new ResizeOptions(*, *))
        .build();
    DraweeController controller = Fresco.newDraweeControllerBuilder()
        .setImageRequest(request)
        .setOldController(viewHolder.mSimpleDraweeView.getController())
        .build();
    viewHolder.mSimpleDraweeView.setController(controller);
}
```

I cannot get size just like `view.getWidth()`or`view.getLayoutParams().width`.
it will return 0

How can I get actual view size before `onBindViewHolder()`??
Thanks for your help!!!

**Comment by gokhanbarisaker** [comment]
If the view is not go through layout phase (which is common with onBindViewHolder), you need to add a listener for layout on ViewTreeObserver.

There is a faster and efficient alternative, where you can pass the recyclerview width to the adapter and apply simple math to access the view width

**Comment by hhuimie** [comment]
NONONONO!
I tried to add a listener like `addOnPreDrawListener()` or `addOnGlobalLayoutListener()` for my itemView in my ViewHolder's constructor.
it actual give me the size.
but before the listener respond, the method `onBindViewHolder()` already called.
I still get no size in `onBindViewHolder()`
do I did something wrong?

**Comment by hhuimie** [comment]
can anybody helps?

**Comment by IanChilds** [comment]
I suggest you do as @gokhanbarisaker suggested and pass the width into the adapter. 

Also, when someone tries to help you I don't think responding "NONONONO!" is really going to encourage them to help you again in the future.

**Comment by hhuimie** [comment]
I'm so sorry about that!
I did not mean that.
thanks again

**Comment by IanChilds** [comment]
No worries :)

**Comment by hhuimie** [comment]
@IanChilds sorry to bother you again.
I donot mean to offend fresco or other.
But I wanna do a simple comparison between fresco and glide.

`Glide`
Anytime we want to show a image, just do some stuff like:
```java
Glide.with(this)
    .load(stringUri)
    .diskCacheStrategy(DiskCacheStrategy.ALL)
    .into(imageView);
```
Then, glide will caches the imageView-size one and full-size one.
we do not need to warry about how to resize to actual view size.

`Fresco`
First,resizing is needed in this case.
In some case, we already set the imageview like this:
```xml
android:layout_width="20dp"
android:layout_height="20dp"
```
then it is easy to resize.
just:
```java
int size = ScreenUtils.dpToPx(20);
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
    .setResizeOptions(new ResizeOptions(size, size))
    .build();
DraweeController controller = Fresco.newDraweeControllerBuilder()   
    .setImageRequest(request)
    .setOldController(imageView.getController())
    .build();
imageView.setController(controller);
```
or sometime we don't know the size of this view.
we can:
```java
imageView.getViewTreeObserver()
    .addOnPreDrawListener(new OnPreDrawListener() {
        @Override
        public boolean onPreDraw() {
            imageView.getViewTreeObserver()
                .removeOnPreDrawListener(this);
            int width = imageView.getWidth();
            int height = imageView.getHeight();
            /**
             * do the same as above
             */                 
            return true;
        }
    });
```
is it right?

Finally, in my case, what if I'm using recyclerView with a complicate item layout, not just simply match_parent to the root or the whole screen.
I can not get size like `ScreenUtils.dpToPx(20)`.
I can not add a listener as above.
Then, I must calculate the view size carefully according to my item layout.
And do it everytime for all different imageview.
Is it boring?

sorry about my pool english and my pool android. :)

**Comment by majidsa70** [comment]
itemView.measure(View.MeasureSpec.UNSPECIFIED, View.MeasureSpec.UNSPECIFIED);
int width = itemView.getMeasuredWidth();
int height = itemView.getMeasuredHeight();
