### ISSUE TITLE
java.lang.NoClassDefFoundError with Google Play Services

### ISSUE THREAD

**Issue by petersf7** [facebook/fresco#741]
Hei,

When i try to implement the newest Google Analytics:
(app level gradle)
apply plugin: 'com.google.gms.google-services'
compile 'com.google.android.gms:play-services-analytics:8.3.0'
(project level gradle) 
classpath 'com.google.gms:google-services:1.5.0-beta2'

I get this error: 
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

Looked into the issue, and proguard is instructed not to remove anything annotated with @DoNotStrip.

Compiling fresco with "compile 'com.facebook.fresco:fresco:0.7.0+'". 

When I remove Analytics, the error is gone, and Fresco loads images again. 
Any ideas what could be the cause of the error?

Thanks!

**Comment by raylee4204** [comment]
I'm getting 

Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.memory.NativeMemoryChunk>

for the latest version as well.

No images are loaded at the moment.

It doesn't seem to be related to any libraries I use for me.

**Comment by ongakuer** [comment]
I build with ```com.android.tools.build:gradle:1.5.0-beta1```, 
```
splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a'
            universalApk false
        }
    }
```

and crash.

```
Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/facebook/imagepipeline/memory/NativeMemoryChunk;
```
But ```1.4.0-beta6``` can work well.

**Comment by bluesoulx** [comment]
Same here
use com.google.gms:google-services:1.5.0-beta2 with com.google.android.gms:play-services-gcm:8.3.0 cause UnsatisfiedLinkError
But with com.google.gms:google-services:1.4.0-beta6 with com.google.android.gms:play-services-gcm:8.1.0 work well

**Comment by yilzer** [comment]
Thanks this will solved the issue, but with 

    compile 'com.google.android.gms:play-services-analytics:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'

and 

   classpath 'com.google.gms:google-services:1.5.0-beta2'

compiled, the app size is 5mb smaller than with the solution that works right now.

**Comment by githubdoramon** [comment]
Same here.... i managed to use play services 8.3 with com.google.gms:google-services:1.3.1 on the project build.gradle!

**Comment by botondbutuza** [comment]
@tyronen Any progress on this issue?

**Comment by massimocarli** [comment]
I cannot reproduce the problem. I've just created a simple application using Google Play Services and loading an image with Fresco. Are these dependencies the same you are using?
```
    compile 'com.facebook.fresco:fresco:0.8.1+'
    compile 'com.google.android.gms:play-services:8.3.0'
```
When do you see the problem?
Thanks

**Comment by githubdoramon** [comment]
@massimocarli have you tried to change the com.google.gms:google-services:1.3.1 on the project build.gradle to 1.5?

**Comment by botondbutuza** [comment]
@massimocarli The dependency that is causing me issues is `classpath 'com.google.gms:google-services:1.5.0-beta2'` in the project level build.gradle file.

**Comment by petersf7** [comment]
I have not tried with the said dependencies in a while, changed it to com.google.gms:google-services:1.4.0-beta6 with com.google.android.gms:play-services-gcm:8.1.0 , and that worked.

**Comment by githubdoramon** [comment]
@petersf7 with this configurations it works.... algo with play services 8.3 and 1.3.0 .... the problem is when you try to use the latest ones (8.3 and 1.5.0).... actually I think the problem is only with 1.5.0-beta2, no matter what play services you use on app level gradle

**Comment by githubdoramon** [comment]
I just updated to google-services:2.0.0-alpha6 and Fresco 0.9 and things seems to be working :) !

**Comment by oprisnik** [comment]
I assume that the problem has been resolved. Please let us know if you're still experiencing this issue.
