### ISSUE TITLE
the images in listview are Flickering on lollipop

### ISSUE THREAD

**Issue by tianlang** [facebook/fresco#742]
public class LollipopBitmapMemoryCacheParamsSupplier implements Supplier<MemoryCacheParams> {

    private ActivityManager activityManager;

    public LollipopBitmapMemoryCacheParamsSupplier(ActivityManager activityManager) {
        this.activityManager = activityManager;
    }

    @Override
    public MemoryCacheParams get() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return new MemoryCacheParams(getMaxCacheSize(), 1, 1,1,1);
        } else {
            return new MemoryCacheParams(
                    getMaxCacheSize(),
                    256,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE);
        }
    }

    private int getMaxCacheSize() {
        final int maxMemory = Math.min(activityManager.getMemoryClass() * ByteConstants.MB, Integer.MAX_VALUE);

        if (maxMemory < 32 * ByteConstants.MB) {
            return 4 * ByteConstants.MB;
        } else if (maxMemory < 64 * ByteConstants.MB) {
            return 6 * ByteConstants.MB;
        } else {
            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.GINGERBREAD) {
                return 8 * ByteConstants.MB;
            } else {
                return maxMemory / 4;
            }
        }
    }

}

When I configure fresco like this，the images in listview are Flickering on lollipop，
if I change the configuration to this:
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return new MemoryCacheParams(getMaxCacheSize(), 56, Integer.MAX_VALUE,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE);
        }

it will be fine,but the memory cache is too much bigger,it's easier to oom.
how to fix that,no flickering and the memory cache is fine?

**Comment by tianlang** [comment]
是不是大家都在关注双十一啊

**Comment by IanChilds** [comment]
With your Lollipop config, you are only allowing 1 entry in the cache at once. I suggest you change the value returned by the `getMaxCacheSize` method for Lollipop builds, and leave all the other params as is.

**Comment by tianlang** [comment]
This did not help,thank you anyway

**Comment by IanChilds** [comment]
Why didn't it help? What happened? Can I see your new code?

**Comment by tianlang** [comment]
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        return new MemoryCacheParams(getMaxCacheSize() / 2 , 256,
                Integer.MAX_VALUE,
                Integer.MAX_VALUE,
                Integer.MAX_VALUE);
    } else {
        return new MemoryCacheParams(
                getMaxCacheSize(),
                256,
                Integer.MAX_VALUE,
                Integer.MAX_VALUE,
                Integer.MAX_VALUE);
    }




This is my new code, did you mean that?

**Comment by IanChilds** [comment]
Yeah, what goes wrong now?

**Comment by tianlang** [comment]
Oh, it works, I had to use another phone before, which something goes wrong,now I think the reason is that the phone itself.
Thanks again.
