### ISSUE TITLE
Downsampling webp doesn't work

### ISSUE THREAD

**Issue by gelitenight** [facebook/fresco#743]
I'm using fresco 0.8.0 and find it can't downsample webp.
As in `DownsampleUtil.determineSampleSize`

```
    if (!EncodedImage.isMetaDataAvailable(encodedImage)) {
      return DEFAULT_SAMPLE_SIZE;
    }
```

and in `EncodedImage.parseMetaData`

```
// Dimensions decoding is not yet supported for WebP since BitmapUtil.decodeDimensions has a
// bug where it will return 100x100 for some WebPs even though those are not its actual
// dimensions
if (!ImageFormat.isWebpFormat(imageFormat)) {
    ...
```

I really need this feature. May I ask when will it be fixed?

**Comment by IanChilds** [comment]
This isn't a hi-pri bug for us so we don't have a timeline for fixing this I'm afraid.

**Comment by caojianfeng** [comment]
still in 0.9.0 waitting

**Comment by caojianfeng** [comment]
It is very hard to resolve? For the webp decoder has not downsample function?

**Comment by eldk** [comment]
Hello,

>Bitmap too large to be uploaded into a texture (720x4353, max=Bitmap too large to be uploaded into a texture (720x4353, max=4096x4096)4096x4096)

Should you set a resize option in your picture request :

`ImageRequest request = ImageRequestBuilder .newBuilderWithSource(urlImage) .setResizeOptions(new ResizeOptions(2048, 2048)) .build();`

So downsampling on ImagePipeline config, then resize picture on ImageRequest.

I think It will work with these, even with (4096,4096).

**Comment by caojianfeng** [comment]
```
 private static final int MAX_IMAGE_SIZE = 2048;
  private void testDrawee(ImageItem testItem) {
        Uri uri = Uri.parse(testItem.url);

        ImageRequest imgReq = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(new ResizeOptions(MAX_IMAGE_SIZE, MAX_IMAGE_SIZE)).build();

        AbstractDraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imgReq)
                .build();

        dvPic.setController(controller);
        textView.setText(testItem.name);
    }

```
I had set this but not work .
And I also try to .setDownsampleEnabled(false) or .setDownsampleEnabled(true)
both not work.

**Comment by caojianfeng** [comment]
It look like this:
in the doDecode in src/main/jni/static-webp/webp_bitmapfactory.cpp line 124
```
if ((bitmapOptions != nullptr) &&
      (setOutDimensions(env, bitmapOptions, image_width, image_height))) {
    return {};
  }
```
As soon as you use bitmapOptions ,setOutDimensions and  return {}; for decodeBounds.
Even when you what decode a real downsample image.

The coding of 'downsample  webp' not finish yet.

**Comment by zmroczek** [comment]
There is a more general task for WebP downsampling support #1975
