### ISSUE TITLE
Fresco binaries not appearing in JCenter

### ISSUE THREAD

**Issue by luca992** [facebook/fresco#744]
Trying to sync gradle with the latest version v0.8.1 and keep getting
> Failed to resolve: com.facebook.fresco:fresco:0.8.1+ 

com.facebook.fresco:fresco:0.8.0+
and lower are syncing just fine in android studio

**Comment by luca992** [comment]
I found out that v0.8.1 is not in the jcenter Repo. Had to add mavenCentral() to my dependencies in gradel

**Comment by IanChilds** [comment]
Hmm, strange. ImagePipeline and Drawee have been correctly mirrored to jcenter from mavenCentral(), but Fresco has not.

**Comment by ongakuer** [comment]
Try to update grade to v2.8

gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-2.8-all.zip
```

**Comment by luca992** [comment]
@ongakuer doesn't help. As you can see it is just not there when you search for it on the JCenter website https://bintray.com/tyronen/maven/com.facebook.fresco%3Afresco/view

**Comment by hellorachid** [comment]
Try this 
       ` compile 'com.facebook.fresco:fresco:0.8.1'`
it works for me

**Comment by balazsbalazs** [comment]
We're working on it. You can use it from Maven Central for now. JCenter doesn't have 0.8.1 yet.

**Comment by kirwan** [comment]
jCenter is now up to date with Fresco releases. Either 0.8.1 or 0.9.0 can now be used without needing Maven Central.
