### ISSUE TITLE
Incorrect image drawing (local image with orientation and rounded corners)

### ISSUE THREAD

**Issue by burzumrus** [facebook/fresco#751]
In case of loading a local image (from sd card) with 90 or 270 deegrees orientation, with rounded corners, Fresco draws such images with artifacts (edges are repeated). Bounds of RoundedBitmapDrawable are incorrect, looks like RoundedBitmapDrawable dones't respect image orientation
Fresco version: 0.8.0+

**Comment by IanChilds** [comment]
Is the problem that the image doesn't fully cover the view? See the last bullet point here: http://frescolib.org/docs/rounded-corners-and-circles.html#caveats

can you use `OVERLAY_COLOR` instead?

**Comment by burzumrus** [comment]
Hello, yes, this issue relates to problem that the image doesn't fully cover the view. But image doesn' cover view fully not because it has size, smaller than view, but beacuse of RoundedBitmapDrawable render it with incorrect width and height (for 90 deegrees orientation width and height are swapped);

Let me show you concrete example
![pic](https://cloud.githubusercontent.com/assets/3293271/11113975/011fb064-8932-11e5-8a9e-d18ce147faa0.jpg)
here is image, it has width 747 and height 1328, exif rotation - 90 (so physical bitmap sizes w - 1328, h - 747) (captured from device camera). Please open image in new tab or in good image editor, because github draws it wrong too :)

![app](https://cloud.githubusercontent.com/assets/3293271/11114024/6cd3be4a-8932-11e5-96d9-0e5397774f59.png)
here is how fresco render it. View has size: w-670, h-1192, so image should full cover it. But fresco render it, starts from left and top - 290, with repeating edges to up and left. RoundedBitmapDrawable bounds in draw() method are top:290, left:-291, rigth:1037, bottom:1037, so its height = 747 (matches image width with respect orientation).

I have found temporary workaround, if i rotate bitmap to 90 degress and set exif orientation of file to 0 - it rendered perfectly.

Without round cornders, image rendered perfrectly

**Comment by balazsbalazs** [comment]
Oh, great find, thx a lot! I'm looking into it now.

**Comment by balazsbalazs** [comment]
Thx again @burzumrus for the amazing details, this issue is fixed now, will be available with the next release.
