### ISSUE TITLE
Fresco doesn't display image with both width and height - match_parent / see loading images

### ISSUE THREAD

**Issue by iDaniel19** [facebook/fresco#753]
I have an app which loads an image using the fresco library. I have 2 problems. 
1. If I use the fresco image like this 

   ` <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/feedImage"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />`

it won't display anything but a thin line of colors where the image should be. 

However if I do something like 

    `<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/feedImage"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            fresco:viewAspectRatio="1.33"
            android:scaleType="fitXY"
            />`

everything is working fine(but I don't see the full image). 

I want to achieve the same view as facebook(images full width and height). 

2. I load the images in a list in a recycler. The images are loaded into cache(I verified that) but if I go all the way down and then back up I can see the images being loaded(facebook doesn't have this problem and they use the same library). If I scroll really slow there is no problem. I recently changed from volley and I did not have this problem before(so it's not the recycler). How can I solve this ? 

Edit: And something else that I noticed is that if I disable the disk cache and kill the app the cache is not deleted as the documentation says. I know that if I call  `ImagePipeline imagePipeline = Fresco.getImagePipeline();
Uri uri;
imagePipeline.evictFromMemoryCache(uri);` the cache will be deleted, but shouldn't this be automatically ?

**Comment by IanChilds** [comment]
If you are using a recycler view, then match_parent is undefined, so you can't use that. You have to use wrap_content, and then you can rely on the aspect ratio of the image, rather than specifying one yourself. 

Where in the documentation does it say that the disk cache will be deleted if you kill the app? I don't think that is the case (that is the point of the disk cache, after all).

**Comment by iDaniel19** [comment]
So how can I get the full image to be displayed ? A little code could help :+1: 

Not the disk cache(As I said in the post the disc cache is disabled.). I delete that myself. I'm talking about the other cache.  Even after I kill the app the cache is still present. And another question: How can I save in the disc cache only the first 10 images let's say.

**Comment by IanChilds** [comment]
You can get the full image to be displayed using match_parent for width, and then whatever aspect ratio will show you the full image. 

You can use DiskCacheConfig to specify that you only want 10 images to be saved.

**Comment by DeepakDroid** [comment]
Hello I am new for Fresco Library implementation. so please guide me where i wrong in code.

in my view of phone image height not coming properly its always coming in single line.

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fresco="http://schemas.android.com/tools"
    android:id="@+id/scrollview_linear"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="#ffffff"
    android:orientation="vertical">

    <include
        layout="@layout/remint_it_layout_include"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <RelativeLayout
            android:id="@+id/inside_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">


            <ImageView
                android:id="@+id/thumbnailVideo"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_alignBottom="@id/videoView"
                android:layout_alignEnd="@id/videoView"
                android:layout_alignLeft="@id/videoView"
                android:layout_alignRight="@id/videoView"
                android:layout_alignStart="@id/videoView"
                android:layout_alignTop="@id/videoView"
                android:layout_centerInParent="true"
                android:scaleType="fitXY"
                android:visibility="gone"
                android:background="#FFF"/>

            
            
            
            <com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/image_mint"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:adjustViewBounds="true"
                android:layout_alignBottom="@id/videoView"
                android:layout_alignEnd="@id/videoView"
                android:layout_alignLeft="@id/videoView"
                android:layout_alignRight="@id/videoView"
                android:layout_alignStart="@id/videoView"
                android:layout_alignTop="@id/videoView"
                android:layout_centerInParent="true"
                android:layout_marginBottom="25dp"
                android:scaleType="fitXY"
                fresco:progressBarImage="@drawable/progress"
                fresco:progressBarImageScaleType="centerInside"
                fresco:progressBarAutoRotateInterval="1000"
                android:visibility="gone" />

          

            <im.ene.lab.toro.widget.ToroVideoView
                android:id="@+id/videoView"
                android:layout_width="match_parent"
                android:layout_height="350dp"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                app:videoScaleMode="fitWidth"
                android:layout_alignParentLeft="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentTop="true"
                android:visibility="gone"/>


            <ImageView
                android:id="@+id/imageviewYoutuneLogo"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:src="@drawable/youtube_logo"
                android:visibility="gone"
                />

            <ImageView
                android:id="@+id/imagePlayPauseCenter"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:padding="10dp"
                android:src="@drawable/new_video_play_icon"
                android:visibility="gone" />

            <LinearLayout
                android:id="@+id/layoutSeekbar"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:layout_below="@+id/videoView"
                android:background="@color/default_line_indicator_unselected_color"
                android:gravity="center"
                android:orientation="horizontal"
                android:visibility="gone">

                <TextView
                    android:id="@+id/textStartTime"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="0"
                    android:text="00.00"
                    android:textColor="#FFFFFF" />

                <SeekBar
                    android:id="@+id/seekbarVideoTime"
                    style="@android:style/Widget.Holo.SeekBar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:layout_weight="1"
                    android:paddingLeft="0dp"
                    android:paddingRight="0dp"
                    android:thumb="@drawable/thumb_drawable"
                    android:thumbOffset="0dp" />

                <TextView
                    android:id="@+id/textEndTime"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_weight="0"
                    android:text="00.00"
                    android:textColor="#FFFFFF" />
            </LinearLayout>

            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="horizontal">

                <ImageView
                    android:id="@+id/imagePlayPause"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:padding="10dp"
                    android:src="@drawable/playback_pause"
                    android:visibility="gone" />

                <ImageView
                    android:id="@+id/imageMuteUnmute"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:padding="8dp"
                    android:src="@drawable/unmute_audio"
                    android:visibility="gone" />
            </LinearLayout>


            <ImageView
                android:id="@+id/nomination_badge"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_alignParentRight="true"
                android:layout_alignParentTop="true"
                android:src="@drawable/achievement_badge"
                android:visibility="gone" />
        </RelativeLayout>

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/inside_layout">

            <com.mintshow.utils.emoji_lib.EmojiExplorerView
                android:id="@+id/mint_text"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_margin="9dp"
                android:background="#FFFFFF"
                android:gravity="center"
                android:padding="3dp"
                android:text="30 days of Water is the best hsdfhsdf ghfg jafjhgj hsdgghdghsf hfhhfh ggfgthing 30 days of Water is the best thing "
                android:textColor="#4A4A4A"
                android:textColorLink="#F35E1B"
                android:textSize="17sp" />

            <TextView
                android:id="@+id/edited_text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_below="@+id/mint_text"
                android:layout_marginRight="7dp"
                android:text="Edited"
                android:textSize="15sp"
                android:visibility="gone" />
        </RelativeLayout>
    </RelativeLayout>

    <include
        layout="@layout/remint_headerview_show_mint"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp" />
    <include
        layout="@layout/location_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
    <include
        layout="@layout/relative_icons_include_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <View
        android:layout_width="fill_parent"
        android:layout_height="1dp"
        android:layout_marginTop="3dp"
        android:background="#EFEFEF" />


    <include
        layout="@layout/compliments_root_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />


    <TextView
        android:id="@+id/bottom_line_divider"
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:layout_marginBottom="0dp"
        android:layout_marginTop="5dp"
        android:background="@drawable/thin_line" />

</LinearLayout>

**Comment by oprisnik** [comment]
Your parent container has a height of `wrap_content`, which we do not support. You can either explicitly set a height or set an aspect ratio for the Drawee view.

See http://frescolib.org/docs/wrap-content.html and http://frescolib.org/docs/using-drawees-xml.html

**Comment by DeepakDroid** [comment]
thanks @oprisnik for replying , even if I set an aspect ratio for the Drawee view . its not working
