### ISSUE TITLE
I download a picture from Tumblr,but the Fresco can not display it correctly

### ISSUE THREAD

**Issue by wang00850023** [facebook/fresco#754]
I use the Fresco's version is 0.8.1.
I download a picture from Tumblr, and the save path is /storage/emulated/0/Tumblr/https:/33.media.tumblr.com/acca7cf3d29f90dc4426727cf695f4c5/tumblr_nxn5novmR11te1g66o1_500.jpg,The path is default saved when I download.And I can see it in System photo album,but when I used Fresco to diplay it ,it throws the exception:
/storage/emulated/0/Tumblr/https:/33.media.tumblr.com/acca7cf3d29f90dc4426727cf695f4c5/tumblr_nxn5novmR11te1g66o1_500.gif: open failed: ENOENT (No such file or directory)
Is it a bug?
Thanks!

**Comment by IanChilds** [comment]
What URL are you passing to Fresco? It looks like you are passing *.gif, when it should be *.jpg?

**Comment by wang00850023** [comment]
It is gif,
/storage/emulated/0/Tumblr/https:/33.media.tumblr.com/acca7cf3d29f90dc4426727cf695f4c5/tumblr_nxn5novmR11te1g66o1_500.gif
and also can not display it

**Comment by IanChilds** [comment]
In your first comment, it says that it is a jpg, no?

**Comment by wang00850023** [comment]
No matter gif or jpg,all pictures in Tumblr folder can not be displayed.

**Comment by s1rius** [comment]
Just use a custom ImageRequest, like this:
```
public class EncodedPathImageRequest extends ImageRequest {

    public EncodedPathImageRequest(ImageRequestBuilder builder) {
        super(builder);
    }

    @Override
    public synchronized File getSourceFile() {
        File file = super.getSourceFile();
        if (file == null || !file.exists()) {
            file = new File(getSourceUri().getEncodedPath());
        }
        return file;
    }
}
```

**Comment by wang00850023** [comment]
Just like this?
ImageRequest request = EncodedPathImageRequest.fromUri(Uri.parse(loaderFilePath));
            
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setControllerListener(controllerListener)
                    .setImageRequest(request)
                    .setAutoPlayAnimations(true)
                    .setOldController(imageView.getController())
                    .build();
            
            imageView.setController(controller);

**Comment by s1rius** [comment]
Yep

**Comment by wang00850023** [comment]
But it can not work either.It also throws the exception.

**Comment by IanChilds** [comment]
What happens if you move it to a different directory?

**Comment by s1rius** [comment]
Sorry, It's my fault.
Write like this:
```
ImageRequest imageRequest = new EncodedPathImageRequest(ImageRequestBuilder.newBuilderWithSource(uri);
```
Don't use ```EncodedPathImageRequest.FromUri()```

The reason why Fresco throws no such file exception is the path is not correct.
fake path
```/storage/emulated/0/Tumblr/https:/33.media.tumblr.com/acca7cf3d29f90dc4426727cf695f4c5/tumblr_nxn5novmR11te1g66o1_500.gif ```
real path
```/storage/emulated/0/Tumblr/https%3A%2F33.media.tumblr.com%2Facca7cf3d29f90dc4426727cf695f4c5%2Ftumblr_nxn5novmR11te1g66o1_500.gif ```

So, use ```new File(getSourceUri().getEncodedPath())``` will get the real file.

**Comment by wang00850023** [comment]
@s1rius Thanks a lot, It works correctly.
