### ISSUE TITLE
Load huge image failure

### ISSUE THREAD

**Issue by epolar** [facebook/fresco#755]
I can't load a big image. the image url is : 
http://static.oneplus.cn/data/attachment/forum/201410/18/111437v9ll9869qqmq76n7.jpg

Image size: 5210 x 2880
Image usage memory on disk: 2.72MB
Device:Genymotion - Sony Xperia S - 4.1.1
I Use with Recycler,View  three image on a screen.
And other image not show.

**Comment by wang00850023** [comment]
The image max width and height is 4096 in Fresco,so you must scale your image when you display it.

**Comment by epolar** [comment]
@wang00850023 image from network, i can scale it from fresco?

**Comment by IanChilds** [comment]
Yeah, you can specify resize params. See http://frescolib.org/docs/resizing-rotating.html#_

As that article says, really you should try to load a smaller image from the network, as that is using a lot of unnecessary data.
