### ISSUE TITLE
Why UiThreadExecutorService is removed?

### ISSUE THREAD

**Issue by anotherdev** [facebook/fresco#756]
From commit: Removed UiThreadExecutorService
https://github.com/facebook/fresco/commit/635f0bf6028f5f658c156bab09d3c59763263fd3

Why is that class removed? It was not in the internal package.

**Comment by IanChilds** [comment]
It was no longer required.

**Comment by tyronen** [comment]
It was also a duplicate of `UiThreadImmediateExecutorService`. You can use that class instead.
