### ISSUE TITLE
Image encryption in DiskCache

### ISSUE THREAD

**Issue by anotherdev** [facebook/fresco#757]
I want to encrypt image files that are stored in Fresco DiskCache using Facebook Conceal library. What would be the best approach?

I tried using ContentProvider approach, but the scrolling is really slow and OOMEs for large images.

**Comment by IanChilds** [comment]
Yeah, unfortunately it will be slow as encryption is fairly slow. I suspect the OOMs are unrelated. Unfortunately there is no good way to do this right now.
