### ISSUE TITLE
reload image in listview

### ISSUE THREAD

**Issue by wowsershan** [facebook/fresco#758]
I want to get some info about fresco to get images.So i write this code.  

       @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            .............
            MgUtils.log("getView:"+position);
            setImg(holderview.iv,getItem(position).getAbsolutePath());
            ..............
            return convertView;
        }

	private void setImg(SimpleDraweeView img, final String path) {
	        final Uri uri = Uri.parse("file://"+path);
	        final long start = System.currentTimeMillis();
	        ControllerListener controllerListener = new BaseControllerListener<ImageInfo>() {
	            @Override
	            public void onFinalImageSet(
	                    String id,
	                    @Nullable ImageInfo imageInfo,
	                    @Nullable Animatable anim) {
	                totalTimes += System.currentTimeMillis()-start;
	                count++;
	                MgUtils.log("num:"+count+" time:" + (System.currentTimeMillis()-start) + " totalTime:"+totalTimes+
	                " avg:"+(totalTimes/count));
	                MgUtils.log("path:"+path+" size:"+((CloseableStaticBitmap)imageInfo).getSize());
	            }

            @Override
            public void onIntermediateImageSet(String id, @Nullable ImageInfo imageInfo) {
                //FLog.d("Intermediate image received");
            }

            @Override
            public void onFailure(String id, Throwable throwable) {
                FLog.e(getClass(), throwable, "Error loading %s", id);
            }
        };

        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setControllerListener(controllerListener)
                .setUri(uri)
                .build();
        img.setController(controller);
    }
here is log:
<img width="521" alt="2015-11-13 11 54 36" src="https://cloud.githubusercontent.com/assets/15625685/11138477/ad2dacc8-89fd-11e5-99a7-9a5d84a7b5b3.png">

so the image load more then onece

**Comment by IanChilds** [comment]
I don't understand. It makes a request each time getView is called, which is what you've written your code to do.
