### ISSUE TITLE
No fade transition when switching from Low Res image to High Res image

### ISSUE THREAD

**Issue by ealymbaev** [facebook/fresco#760]
When using the following controller from docs:

http://frescolib.org/docs/requesting-multiple-images.html#going-from-low-to-high-resolution

there is no fade animation when switching from low res to high res.

Maybe this issue is related to #645

**Comment by IanChilds** [comment]
Yeah this is not supported - the images should be the same, just at a different resolution, so you shouldn't require fading at this point.
