### ISSUE TITLE
SDcard have no cache file

### ISSUE THREAD

**Issue by cndotfish** [facebook/fresco#762]
DiskCacheConfig mainDiskCacheConfig = DiskCacheConfig.newBuilder()
            .setBaseDirectoryPath(new File(Constant.IMAGE_CACHE_DIR_PATH))
            .setBaseDirectoryName("cache")
            .setMaxCacheSize(100 * 1024)
            .setVersion(1)
            .build();
I am write this in my Application,when I use listview has SimpleDraweeView, but when I move the listview will download the picture everytime. I see my SDcard have only one cache file, other file is null.

**Comment by IanChilds** [comment]
Your cache size is 100KB so that's probably why you can only fit one image in it at a time.

**Comment by cndotfish** [comment]
thanks for your answer,but when i setMaxCacheSize(500*ByteConstants.MB),only one cache file still.is it a bug?

**Comment by cndotfish** [comment]
i have solved this problem by using setMaxCacheSizeOnLowDiskSpace(100 * ByteConstants.MB).thank you all the same
