### ISSUE TITLE
Save only 10 images using DiskCacheConfig

### ISSUE THREAD

**Issue by iDaniel19** [facebook/fresco#764]
I was told that  `You can use DiskCacheConfig to specify that you only want 10 images to be saved`
but I couldn't find any option to set that. This is how my disk cache config looks like 

`DiskCacheConfig diskCacheConfig = DiskCacheConfig.newBuilder()
                .setBaseDirectoryPath(new File(Environment.getExternalStorageDirectory().getAbsoluteFile(), getPackageName()))
                .setBaseDirectoryName("imageFresco")
                .setMaxCacheSize(50 * ByteConstants.MB)
                .setMaxCacheSizeOnLowDiskSpace(10 * ByteConstants.MB)
                .setMaxCacheSizeOnVeryLowDiskSpace(5 * ByteConstants.MB)
                .setVersion(1).build();`

        ProgressiveJpegConfig progressiveJpegConfig=new ProgressiveJpegConfig() {
            @Override
            public int getNextScanNumberToDecode(int scanNumber) {
                return scanNumber + 2;
            }

            @Override
            public QualityInfo getQualityInfo(int scanNumber) {
                boolean isGoodEnough = (scanNumber >= 5);
                return ImmutableQualityInfo.of(scanNumber, isGoodEnough, false);
            }
        };

        ImagePipelineConfig imagePipelineConfig = ImagePipelineConfig.newBuilder(this)
                .setMainDiskCacheConfig(diskCacheConfig)
                .setProgressiveJpegConfig(progressiveJpegConfig)
                .build();

        Fresco.initialize(this, imagePipelineConfig);
`

How can I add the 10 images part ? Is that a proper progressiveJpeg config ?

**Comment by IanChilds** [comment]
My mistake, you can't actually do that for the disk cache - I was thinking of the bitmap cache, where this is an option.
