### ISSUE TITLE
Fresco won't load images android with Google cloud messaging service inside build.gradle

### ISSUE THREAD

**Issue by yilzer** [facebook/fresco#767]
Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.memory.NativeMemoryChunk>

I get this error when i put this: 

       dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'com.google.gms:google-services:1.5.0-beta2'
    }

In build.gradle the problem is solved when i put old version inside this:

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'com.google.gms:google-services:1.3.0-beta1'
    }

More info:

in the other build.gradlle with dependencies i have this bundles compiled:

    compile 'com.google.android.gms:play-services-analytics:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.facebook.fresco:fresco:0.8.1+'

Is there a solution for this problem, or is this a bug?

Thanks in advance!

**Comment by IanChilds** [comment]
Same as #741
