### ISSUE TITLE
roundAsCircle does not apply to placeholder images

### ISSUE THREAD

**Issue by REWKyleB** [facebook/fresco#77]
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/agent_image"
        android:layout_width="80dp"
        android:layout_height="80dp"
        fresco:roundAsCircle="true"
        fresco:placeholderImage="@drawable/ic_image_placeholder"
        fresco:placeholderImageScaleType="fitCenter"/>

roundAsCircle is being applied to the replacement images, but not the placeholder.

Thanks!

**Comment by plamenko** [comment]
What is `ic_image_placeholder`?

**Comment by REWKyleB** [comment]
It's just a normal bitmap (.png).

**Comment by plamenko** [comment]
Hmm, that's weird. If the placeholder gets resolved to `ColorDrawable` or `BitmapDrawable`, then it should get rounded. Can you give us more information? 
Btw, are you able to debug? This is the place where rounding should be applied:
https://github.com/facebook/fresco/blob/53e1317d47e0e33d9927740ad4974cc479d8cc2a/drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchy.java#L165

**Comment by REWKyleB** [comment]
Android studio add a bit of padding to the image when I initially import it and I didn't notice. It was correctly rounding the image, but the extra space would make it seem like it was rounding. All working fine :)
