### ISSUE TITLE
Need the way to prefetch image with progress and listener

### ISSUE THREAD

**Issue by ealymbaev** [facebook/fresco#770]
I was trying to use ImagePipeline's "prefetch" feature. But it accepts ImageRequest only, but ImageRequest does not have any progress or complete listeners.

I have also tried to use temp SimpleDraweeView in order to set hierarchy with ProgressDrawable and Controller with listener - but it does not download image on "setController()". I guess it start downloading only when it is rendered on the screen.

Could you please let me know how can I listen to the progress on "prefetch" OR how can I force downloading image into SimpleDraweeView created in code (without showing it on the screen).

**Comment by IanChilds** [comment]
You can listen to all requests (including prefetches) by setting a listener here: https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipelineConfig.java#L402:L405

**Comment by KashanDanish** [comment]
@IanChilds I am not able to understand how to use `ImagePipelineConfig` to listen to downloads. A small piece of code would be appreciated. Thanks.

**Comment by xiadeye** [comment]
same question.
Ps, @IanChilds L402-L405 is the setting code?Maybe the code has changed,could you post the function name,Tks.

**Comment by korniltsev** [comment]
@xiadeye its com.facebook.imagepipeline.core.ImagePipelineConfig.Builder#setRequestListeners

**Comment by lambdapioneer** [comment]
Hi @xiadeye, besides the global listener that @korniltsev suggested, you can now also register listener for single image requests: `ImageRequestBuilder#setRequestListener`.

Usually, you want to use the former for implementing general logging and the later if you want to instrument special requests.

**Comment by eldk** [comment]
Hello,

If you prefetchDataSource - ImagePipeline.prefetchToDiskCache(), you may (also) use onProgressUpdate() - http://frescolib.org/javadoc/reference/com/facebook/datasource/BaseDataSubscriber.html - that's including : download + eventually transcode to jpeg if you download webp pictures with one Android that can't handle them natively.

On single image request/display, you may (also) use BaseControllerListener<ImageInfo>() - http://frescolib.org/javadoc/reference/com/facebook/drawee/controller/BaseControllerListener.html - http://frescolib.org/docs/listening-download-events.html.
So you may check quality, or time to download/transcode  ... until displayed ...

And finally the @lambdapioneer solution.


@xiadeye 
> how to use ImagePipelineConfig to listen to downloads. When setting requestListeners when initialising fresco,

This will enable listener on all ImagePipeline request and will be some logs only if FLog.setMinimumLoggingLevel(FLog.VERBOSE);

`Set<RequestListener> requestListeners = new HashSet<>();
RequestLoggingListener requestLoggingListener = new RequestLoggingListener();
requestListeners.add(requestLoggingListener);`

This include download, write to cache, get in cache ... transcode, , display ... events ... all events from get picture to display it with each step. http://frescolib.org/docs/troubleshooting.html.

Thanks,

Eric
