### ISSUE TITLE
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.

### ISSUE THREAD

**Issue by cxmmxc** [facebook/fresco#773]
### 3. Run project, crashInfo:Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/nineoldandroids/animation/Animator$AnimatorListener.class

## PhoneInfo
device:Mx3
Android version:5.0.1

**Comment by aagnes** [comment]
nineOldslibrary is shipped with 0.8.1, you don't need to add it yourself.
