### ISSUE TITLE
If Fresco will store local image to Disk Cache

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#774]
I have some doubts,
1. When the image is store to disk cache?
2. And local image also store to disk cache?
3. If i want to store some local image to cache how can i store ?

I am asking only about disk cache... If anyone give suggestion its great helpful for me.
Thanks in advance

**Comment by aagnes** [comment]
http://frescolib.org/docs/caching.html#_
It's stated in doc. Hold true for local images as well.
