### ISSUE TITLE
Why fresco don't open downsample feature by default, is there any disadvantage?

### ISSUE THREAD

**Issue by sidneywang** [facebook/fresco#776]
I think downsmaple feature cost less than resize, and android support it in skia, why Fresco didn't support before and  closed by default now?

**Comment by aagnes** [comment]
http://frescolib.org/docs/resizing-rotating.html#_
We're still in the stage of experimenting downsampling.

Depending on your need, downsample may be better to use in you case.

**Comment by sidneywang** [comment]
My doubt is why fresco didn't support it at first.  After all downsample is supported in android natively.

**Comment by aagnes** [comment]
There's limited for downsampling which you can find online as well. Downsampling might not cover what the use cases.

**Comment by sidneywang** [comment]
It will be appreciated if you give me a url. ;)

**Comment by sidneywang** [comment]
I tested resize in fresco and inSampleSize in android, the picture effort is totally same. Actually they both call libjpeg function in a same way.
I am full of doubt why Freco do that.
