### ISSUE TITLE
Image takes a while to render

### ISSUE THREAD

**Issue by schan93** [facebook/fresco#778]
Hi, I am new to using the fresco library and I want to display images very quickly. In my navigation header, I have a simple call where I do the following: 

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Profile profile = Profile.getCurrentProfile();
        Uri uri = Uri.parse("http://graph.facebook.com/" + profile.getId() + "/picture?type=normal");
        SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.avatarImageView);
        draweeView.setImageURI(uri);
    }

This basically calls the Facebook API, gets my user id, and calls the URI so that the image can be displayed correctly. This works but the very first time the user loads the app, it takes a while for the image to actually appear. Every other time I run the app, the picture seems to appear just fine. I know there is no way to reduce the amount of time it takes to perform the HTTP request because of network latency, but is there any way to not display the activity to the user (i.e. have a loading screen of some sort) before this image has finished loading? I have a loading screen implementation but I just don't know where to put the code. Any help would be appreciated. Thanks!

It would look something like this:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Profile profile = Profile.getCurrentProfile();
        Uri uri = Uri.parse("http://graph.facebook.com/" + profile.getId() + "/picture?type=normal");
        SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.avatarImageView);
        if(imageIsDoneLoading){
            //Make loading screen disappear and show entire activity with the image set
           stopLoadingScreen();
            draweeView.setImageURI(uri);
        }
        else {
           //For the time being, set the layout view to be loader screen.
           showLoadingScreen();
        }
    }

**Comment by aagnes** [comment]
You're doing the right thing!

**Comment by schan93** [comment]
@aagnes can help point me in the right direction for the loading screen portion? I just don't really know when the image "is done loading."

**Comment by aagnes** [comment]
You need have a listener.
http://frescolib.org/docs/listening-download-events.html#_ surely helps you.
