### ISSUE TITLE
Issue - Zoom, Drag and Drop

### ISSUE THREAD

**Issue by hanhmh1203** [facebook/fresco#779]
I have question, 
how to custom for zoom in, zoom out image or drag and drop image in drawee ???

**Comment by aagnes** [comment]
We have ZoomableDraweeView do this thing.

**Comment by hanhmh1203** [comment]
yes, I'm got it, thanks :)

**Comment by wang00850023** [comment]
@aagnes 
Where is the ZoomableDraweeView? I can not find it in the packages.

**Comment by aagnes** [comment]
It should be in com.facebook.samples.zoomable. Do you have the lastest version of Fresco library?

**Comment by hanhmh1203** [comment]
I can not implement setonclickListener , it not run in my code :|
 ZoomableDraweeView view = new ZoomableDraweeView(container.getContext());
        view.setController(
                Fresco.newDraweeControllerBuilder()
                        .setUri(Uri.parse(mArrayImage.get(position)))
                        .build());

        GenericDraweeHierarchy hierarchy =
                new GenericDraweeHierarchyBuilder(container.getResources())
                        .setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER)
                        .setProgressBarImage(new ProgressBarDrawable())
                        .build();

        view.setHierarchy(hierarchy);
        view.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.i("setOnClickListener","----------");
            }
        });
