### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by crabfang** [facebook/fresco#78]
Error:Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> A problem occurred starting process 'command 'ndk-build''

**Comment by hounychang** [comment]
I got this error too, how to fix it

**Comment by wewe89** [comment]
I got this error too, how to fix it

**Comment by xlrei** [comment]
I got this error too, how to fix it

**Comment by tyronen** [comment]
This is a known issue on Windows; please see issue #24. 

On other platforms, you can eliminate this error by downloading the Android NDK and adding its location to your system PATH variable.

**Comment by jokerpp** [comment]
i am  sorry ,i want to know if you fix it on windows OS，i still have this problem  : A problem occurred starting process 'command 'ndk-build''

**Comment by tyronen** [comment]
First of all, be sure you need to build from source. We have install instructions for both [Gradle and Eclipse](http://frescolib.org/docs/index.html#_).

Please follow the most recent [instructions](http://frescolib.org/docs/building-from-source.html#_) to build from source.
