### ISSUE TITLE
wrap_content for view

### ISSUE THREAD

**Issue by hanhmh1203** [facebook/fresco#781]
Hi friend,
I have problem, In my app, with more case I need use wrap_content for view,
How can set wrap_content for view ??
Thanks for support :)
Hanh
gmail: hanhmh1203@gmail.com

**Comment by ffelini** [comment]
Here it was answered https://github.com/facebook/fresco/issues/173
But there are some issues with it https://github.com/facebook/fresco/issues/636

**Comment by hanhmh1203** [comment]
Ok, I see.
Thanks Ffelini

**Comment by hanhmh1203** [comment]
hi @ffelini , I understand this issue, but i don't know how to get imageInfo in adapter listview, and set it for imageview in my adapter view.
Plz help me, Thanks
