### ISSUE TITLE
Force image to remain in cache

### ISSUE THREAD

**Issue by hanhmh1203** [facebook/fresco#782]
Hello
In my app, it has function bookmark, with bookmark I need use offline (for long time).
when I offline I want image alway show (Image cached on local ).
it's mean, I can control image, set no clear cache with this image.
Thanks

**Comment by aagnes** [comment]
This is something we'll plan to do in future. Thanks.

**Comment by hanhmh1203** [comment]
thanks, I will follow this project, thanks :)

**Comment by tyronen** [comment]
You can actually do this now, sort of:

```java
DiskStorageCache diskCache = Fresco.getImagePipelineFactory().getMainDiskStorageCache();
SimpleCacheKey cacheKey = new SimpleCacheKey(uri.toString());
diskCache.probe(cacheKey);
```

This updates the timestamp so that the image is once again the 'least recently used'. Do this regularly and the image won't ever get evicted.

**Comment by kirwan** [comment]
Another way to tackle a problem like this is to request the encoded image data and write it to a local file. You can then attempt to display it based on a local URI.

We're cleaning up long-untouched issues so I'm closing this one.
