### ISSUE TITLE
java.lang.OutOfMemoryError Failed to allocate a 2073612 byte allocation with 1645896 free bytes and 1607KB until OOM

### ISSUE THREAD

**Issue by luohong** [facebook/fresco#783]
fresco 0.8.1

dalvik.system.VMRuntime.newNonMovableArray(Native Method)
android.graphics.Bitmap.nativeCreate(Native Method)
android.graphics.Bitmap.createBitmap(Bitmap.java:939)
android.graphics.Bitmap.createBitmap(Bitmap.java:912)
android.graphics.Bitmap.createBitmap(Bitmap.java:879)
com.facebook.imagepipeline.memory.BitmapPool.android.graphics.Bitmap alloc(int)(Unknown Source)
                                             java.lang.Object alloc(int)
com.facebook.imagepipeline.memory.BitmapPool.android.graphics.Bitmap alloc(int)(Unknown Source)
                                             java.lang.Object alloc(int)
com.facebook.imagepipeline.memory.BasePool.java.lang.Object get(int)(Unknown Source)
com.facebook.imagepipeline.platform.ArtDecoder.com.facebook.common.references.CloseableReference decodeStaticImageFromStream(java.io.InputStream,android.graphics.BitmapFactory$Options)(Unknown Source)
com.facebook.imagepipeline.platform.ArtDecoder.com.facebook.common.references.CloseableReference decodeJPEGFromEncodedImage(com.facebook.imagepipeline.image.EncodedImage,android.graphics.Bitmap$Config,int)(Unknown Source)
com.facebook.imagepipeline.decoder.ImageDecoder.com.facebook.imagepipeline.image.CloseableStaticBitmap decodeJpeg(com.facebook.imagepipeline.image.EncodedImage,int,com.facebook.imagepipeline.image.QualityInfo)(Unknown Source)
com.facebook.imagepipeline.decoder.ImageDecoder.com.facebook.imagepipeline.image.CloseableImage decodeImage(com.facebook.imagepipeline.image.EncodedImage,int,com.facebook.imagepipeline.image.QualityInfo,com.facebook.imagepipeline.common.ImageDecodeOptions)(Unknown Source)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.void doDecode(com.facebook.imagepipeline.image.EncodedImage,boolean)(Unknown Source)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(Unknown Source)
com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.void run(com.facebook.imagepipeline.image.EncodedImage,boolean)(Unknown Source)
com.facebook.imagepipeline.producers.JobScheduler.void doJob()(Unknown Source)
com.facebook.imagepipeline.producers.JobScheduler.access$000(Unknown Source)
com.facebook.imagepipeline.producers.JobScheduler$1.void run()(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
com.facebook.imagepipeline.core.PriorityThreadFactory$1.void run()(Unknown Source)
java.lang.Thread.run(Thread.java:818)

**Comment by aagnes** [comment]
please do a resize or downsample to your images. THe last image you're decoding before oom is more than 2mb. You don't need an entire original image load in.

**Comment by UmeshAawte** [comment]
Is this issue with specific image having size more than 2mb?

**Comment by balazsbalazs** [comment]
You are simply running out of memory. Loading huge images in a collection view will cause that.
