### ISSUE TITLE
Making disk cache check synchronous

### ISSUE THREAD

**Issue by chethann** [facebook/fresco#784]
As per the documentation the disk cache check in fresco is asynchronous. I was wondering if it is possible to make it a synchronous call. 

The below code says if the cache key corresponding to imageUrl exists in the disk cache.

```CacheKey cacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(ImageRequest.fromUri(imageUrl));
        Boolean temp = ImagePipelineFactory.getInstance().getMainDiskStorageCache().hasKey(cacheKey) || ImagePipelineFactory.getInstance().getSmallImageDiskStorageCache().hasKey(cacheKey);```

Isn't it enough to check if the cache key exists to know something is in the cache. 
Is there a case where the cache key exists and it points to null.

If the above code doesn't work for all cases, is it recommended to modify the library to make the call synchronous. Will this change block the UI thread for a long time?  

Please help!

**Comment by aagnes** [comment]
Making a synchronous call to disk cache would surely block main thread for some time. It's highly unrecommended to do so, and also unnecessary. You can isInDiskCache in imagepipeline class to see if image lives on disk.
