### ISSUE TITLE
ProGuard error with ImagePipeline fresco

### ISSUE THREAD

**Issue by pipipzz** [facebook/fresco#785]
Fresco dependency :
```
compile 'com.facebook.fresco:fresco:0.8.1+'
compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.1+'
```

When I am enabling ProGuard, I am getting following:
```
Warning:com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory: can't find referenced field 'android.graphics.Bitmap$Config BITMAP_CONFIG' in program class com.facebook.imagepipeline.nativecode.Bitmaps
```

I am using [ProGuard Rules](https://raw.githubusercontent.com/facebook/fresco/master/proguard-fresco.pro) as written in the docs.

How do I resolve it?

**Comment by balazsbalazs** [comment]
Hey @pipipzz !

`DalvikBitmapFactory` was removed in 0.8.1. so this message is strange. Do you have any specific rule in your proguard config related to `DalvikBitmapFactory`?
Can you also try a gradle clean?

**Comment by pipipzz** [comment]
@balazsbalazs  Hey, cleaning the project and then rebuilding it did actually work. I was so focused on the errors that I totally forgot to try it. Thanks.
