### ISSUE TITLE
Build failed when using gradle plugin 1.5.0

### ISSUE THREAD

**Issue by xjy2061** [facebook/fresco#789]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:mergeReleaseJniLibFolders'.
> [armeabi/libwebp.so] E:\...\imagepipeline\build\imagepipeline\armeabi\libwebp.so	[armeabi/libwebp.so] E:\...\imagepipeline\build\webpimage\armeabi\libwebp.so: Error: Duplicate resources

If downgrade to 1.3.1, it will build success.

**Comment by LouisCAD** [comment]
Did you try a clean/rebuild?

**Comment by xjy2061** [comment]
Yes, I have tried.

**Comment by LouisCAD** [comment]
You try to replace version 1.5.0 with 2.0.0beta1. I'm working on a project using fresco 0.8.1, and it builds and runs flawlessly with the newest beta version of gradle plugin.

**Comment by LouisCAD** [comment]
I just pushed updates to my [PopularMovies repo](https://github.com/LouisCAD/PopularMovies), which use these libraries, in the versions I specified above
