### ISSUE TITLE
ResizeOptions does not resize the image in given bounds

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#791]
I use `new ResizeOptions(1200,1200)`. However the output image has dimensions of 1170x2080 . Is that possible?

**Comment by lushan1314** [comment]
This way if only applies to JPEG format...  I have a 1440x2560 PNG images, loading is very slow.

need help...

**Comment by lushan1314** [comment]
sorry,chinese document is a little delay.

i was find a way solve it,__ImagePipelineConfig.newBuilder(...).setDownsampleEnabled(true)...__

**Comment by droidekas** [comment]
My question is with regard to the size.I want to know if the resize options makes sure that the image is within the given bounds?

**Comment by plamenko** [comment]
Please see the [resize] (http://frescolib.org/docs/resizing-rotating.html#_) documentation.
