### ISSUE TITLE
0.8.1 is not on JCenter

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#792]
Could not find any version that matches com.facebook.fresco:fresco:0.8.1+.
           Versions that do not match:
               0.8.0
               0.7.0
               0.6.1
               0.6.0
               0.5.3
               + 7 more
           Searched in the following locations:
               https://jcenter.bintray.com/com/facebook/fresco/fresco/maven-metadata.xml

**Comment by Doctoror** [comment]
I had the same problem and removed the plus char.

**Comment by manishkungwani** [comment]
I can confirm that removing the + works.

**Comment by akashandroid90** [comment]
I am not able to get it i have even try without '+'

**Comment by balazsbalazs** [comment]
We're working on it. You can use it from Maven Central for now, it's not on Jenter doesn't have 0.8.1 yet.

**Comment by balazsbalazs** [comment]
See issue #744 . Closing this.
