### ISSUE TITLE
dataSource.getResult() returns null for successful request when fetching from Resources in UI thread using ImagePipeline directly

### ISSUE THREAD

**Issue by Doctoror** [facebook/fresco#793]
Fresco version: 0.8.1
Download the full reproducable project from my [Google Drive (link)](https://drive.google.com/file/d/0Bw4z78Q7Eys6aFR6NE81c05YU2c/view?usp=sharing)

I need to load an animated GIF from raw Resource in UI thread and set the image into an ImageView.

The snippet below compares two methods for a Resource with the same Uri.
The "Normal method", using DraweeController works fine and sets the working Drawable into a DraweeView.
The "Direct ImagePipeline method" loads it from ImagePipeline directly and gets a null Drawable.
The demo shows an Activity with a DraweeView and ImageView that should display the same Drawable.

RequestListener prints 
```
FrescoRequestListener: onRequestSuccess(), requestId = 0, Uri = res:/2131099648, isPrefetch = false
FrescoRequestListener: onRequestSuccess(), requestId = 1, Uri = res:/2131099648, isPrefetch = false
```

But the CloseableReference<CloseableImage> in the last line of the snippet below is null.

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    FrescoIniter.initialize(getApplicationContext());

    setContentView(R.layout.activity_main);

    final Uri uri = new Uri.Builder()
        .scheme(UriUtil.LOCAL_RESOURCE_SCHEME)
        .path(String.valueOf(R.raw.florian))
        .build();

    // Normal method

    final DraweeController controller = Fresco.newDraweeControllerBuilder()
        .setUri(uri)
        .setAutoPlayAnimations(true)
        .build();

    final SimpleDraweeView normal = (SimpleDraweeView) findViewById(R.id.draweeView);
    normal.setController(controller);

    // Direct ImagePipeline method

    final ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri).build();
    final DataSource<CloseableReference<CloseableImage>> dataSource = Fresco.getImagePipeline()
        .fetchDecodedImage(request, null);
    Log.d(TAG, "DataSource is: " + toStringOrNull(dataSource));

    final CloseableReference<CloseableImage> result = dataSource.getResult();
    Log.d(TAG, "Result is: " + toStringOrNull(result)); // Is null

    if (result != null) {
        final Drawable drawable;
        try {
            drawable = CloseableImageHelper
                    .createDrawable(getResources(), result);
        } finally {
            result.close();
        }
        Log.d(TAG, "Drawable is: " + toStringOrNull(drawable));
        final ImageView direct = (ImageView) findViewById(R.id.imageView);
        direct.setImageDrawable(drawable);
    }
}
```

Download the full reproducable project from my [Google Drive (link)](https://drive.google.com/file/d/0Bw4z78Q7Eys6aFR6NE81c05YU2c/view?usp=sharing)

**Comment by balazsbalazs** [comment]
DataSource.getResult() will return null if the image is not downloaded yet.
The DataSource is basically a Future. You need to use a DataSubscriber, see documentation here:
http://frescolib.org/docs/datasources-datasubscribers.html#_

**Comment by Doctoror** [comment]
I see, thanks. I thought this way the request will be ran in UI thread, which is wrong.
Here comes another question. Can I somehow load gif from Resources in UI thread?

**Comment by balazsbalazs** [comment]
I don't think so. Why do you want to load it on the UI thread?

**Comment by Doctoror** [comment]
Normally you would load images from resources or assets in UI thread. So that when the Activity, Fragment, or Dialog finishes creating it's UI and is shown to user, all images are already loaded.

Using Fresco's method I see Activity opened and the image is set into DraweeView after 600ms or so.

**Comment by balazsbalazs** [comment]
You're loading local resources normally in UI thread because they are relatively fast. Decoding an animated GIF is much slower.
Blocking the UI thread is never a good idea, if you don't want to show any UI until this is loaded you can set a listener and make your UI invisible/visible. Blocking the UI thread will make the whole app unresponsible (not just the UI), back key won't work, etc.

**Comment by Doctoror** [comment]
You have a point there. Thanks.
