### ISSUE TITLE
ProgressBar disappear before decode is done

### ISSUE THREAD

**Issue by Kroderia** [facebook/fresco#797]
In some cases, when fresco loading the internet images, the progress bar disappear before it is decoded.

I use progressive rendering for debug, it shows rendering action after progress bar is disappeared. Also, in ProgressBarDrawable, setLevelChange(10000) is already called before this.

**Comment by balazsbalazs** [comment]
What's the reason you closed this? Is this not happening anymore?

**Comment by Kroderia** [comment]
I found that the progress bar is only progress of network download only in the doc, which not related to the decoding progress.
Still, I want some way to keep it until it is decoded.

By the way, there is an another issue about the "progressive rendering" above. I found it is able to make jpeg decode line by line(like in browser), which is great to me. However, this feature disappear for no reason, and I can't make it happen anymore, any idea?

**Comment by tonyjs** [comment]
I'm too. I want to showing progress bar until decoding.
Can I take the hint?
