### ISSUE TITLE
Is it any method to set progressive rendering background?

### ISSUE THREAD

**Issue by Kroderia** [facebook/fresco#798]
Is it any method to set progressive rendering background?
It always show the grey background. I tried ImageDecodeOptions and it doesn't work.

**Comment by balazsbalazs** [comment]
Can you provide more detail please? What are you trying to do exactly?

**Comment by Kroderia** [comment]
When setProgressiveRenderingEnabled(true) is called, it always shows a grey background in the DraweeView. Is it possible to change it into white?
