### ISSUE TITLE
Multi thread problem while using Fresco

### ISSUE THREAD

**Issue by liqiuye** [facebook/fresco#799]
Hi Fresco,
	I met a problem when I tried to use Fresco 0.6.0 and 0.7.0 in a multi thread concurrency. The phenomenon is, when the concurrent number less than 2, it works properly, but once the concurrent number more than 3(including 3),  only 2 Drawees can be displayed.
	I tried to use ExecutorSupplier to increase the number of threads, but there is no effect. The image file is compressed, each of them is less than 1MB, and the size is less than 1920*1080, The Android version is 4.2.2, here is my testing code:

```Java
// handle the non-UIThread message
final Handler handler = new Handler(){
        @Override
        public void handleMessage(Message msg) {
            final int fileIndex = msg.what;
            final RelativeLayout layout = (RelativeLayout) msg.obj;
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    displayDrawee(layout, images[fileIndex].getAbsolutePath());
                }
            });
            super.handleMessage(msg);
        }
    };

// display the image file with drawee
private void displayDrawee(RelativeLayout layout, String path) {
        layout.removeAllViews();

        SimpleDraweeView view = new SimpleDraweeView(this.getApplicationContext());
        view.setImageURI(Uri.parse("file://" + path));

        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(960, 540);
        params.setMargins(0, 0, 0, 0);
        view.setLayoutParams(params);

        view.getHierarchy().setActualImageScaleType(ScalingUtils.ScaleType.FIT_XY);

        layout.addView(view);
}
```

**Comment by balazsbalazs** [comment]
Can you attach or link a sample app where this is reproducible?
I'm not sure what you want to do here. I guess the runOnUiThread() will just schedule the runnables in the UI looper, in which case there is no concurrency, everything is running on the UI thread synchronously, one after another.

Not sure what the relative layout is in this case.
