### ISSUE TITLE
One Picture with many url, how to cache it?

### ISSUE THREAD

**Issue by kareluo** [facebook/fresco#803]
My app's picture may have many different url, such as need a signature to append after the url of the picture, so the same picture have different url.

**Comment by plamenko** [comment]
Extend [DefaultCacheKeyFactory] (https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/imagepipeline/src/main/java/com/facebook/imagepipeline/cache/DefaultCacheKeyFactory.java), override `getCacheKeySourceUri` and return a new normalized Uri. If I understand correctly, in your case normalization would be something like removing a signature from the end of the Uri. 
Then build `ImagePipelineConfig` with your cache key factory (just set it with `setCacheKeyFactory`) and pass that config to Fresco initialization as explained in the documentation.
