### ISSUE TITLE
Can't load all images correctly to display in  RecyclerView

### ISSUE THREAD

**Issue by Fedhaier** [facebook/fresco#804]
![102](https://cloud.githubusercontent.com/assets/9740458/11495229/7534009c-9844-11e5-82f0-9a920d885451.png)
I use setImageUri to read all the images in my mobile phone XiaoMi, then list them all in RecyclerView.
As you can see above, the images can't be ALL displayed.When I scoll up and down, it's the same case. When I back to Fresco 0.7.0, the images can be displayed correctly. But some ‘BIG’ images with high pixels become  blur.
Waiting for your advice!

**Comment by michalgr** [comment]
Can you try enabling resizing or downsampling ? http://frescolib.org/docs/resizing-rotating.html#resizing

**Comment by Anilugale** [comment]
facing same issue

**Comment by tyronen** [comment]
Can you follow the instructions for [debug logcat dumps](http://frescolib.org/docs/troubleshooting.html#investigating-issues-with-logcat) and paste the results here?
