### ISSUE TITLE
Attempt to decode failed or corrupted images

### ISSUE THREAD

**Issue by atomd** [facebook/fresco#805]
Fresco can not get the correct format of some images that I can open in my laptop.
Here is the error log:

```
12-01 16:35:11.535 29714-29887/io.egg.now.alpha V/unknown:BufferedDiskCache: Successful read from disk cache for http://xxx.xxx.xxx/d/8d653663fc7d4406980a16bae1409132/151130?_upp=2&_upt=8b58d32f1449062748
12-01 16:35:11.535 29714-29887/io.egg.now.alpha V/unknown:RequestLoggingListener: time 95579973: onProducerFinishWithSuccess: {requestId: 52, producer: DiskCacheProducer, elapsedTime: 5 ms, extraMap: {cached_value_found=true}}
12-01 16:35:11.536 29714-29887/io.egg.now.alpha D/skia: --- SkImageDecoder::Factory returned null
12-01 16:35:11.536 29714-29889/io.egg.now.alpha V/unknown:RequestLoggingListener: time 95579974: onProducerStart: {requestId: 52, producer: DecodeProducer}
12-01 16:35:11.536 29714-29889/io.egg.now.alpha W/unknown:RequestLoggingListener: time 95579974: onProducerFinishWithFailure: {requestId: 52, stage: DecodeProducer, elapsedTime: 0 ms, extraMap: {hasGoodQuality=true, queueTime=0, isFinal=true}, throwable: java.lang.IllegalArgumentException: unknown image format}
12-01 16:35:11.536 29714-29889/io.egg.now.alpha W/unknown:RequestLoggingListener: time 95579974: onRequestFailure: {requestId: 52, elapsedTime: 11 ms, throwable: java.lang.IllegalArgumentException: unknown image format}
12-01 16:35:11.777 29714-29714/io.egg.now.alpha V/unknown:AbstractDraweeController: controller 24cccc28 38: final_failed @ onFailure: failure: java.lang.IllegalArgumentException: unknown image format
```

**Comment by plamenko** [comment]
Can you give us more information about those images? If you can upload one of them that would be very useful. If you can't upload it, if you could extract first couple (say 100) of bytes of the file, with some Hex editor, that would be also be helpful.

**Comment by atomd** [comment]
I try to delete the cache directory,  and those images can be displayed correctly without errors. I guess Fresco caches the dirty data in the disk for unknown reason. It is better to clear the cached data if an error has occurred.

**Comment by balazsbalazs** [comment]
Yeah, this is similar to #321 
Would it make sense to clear the cache if the image if we fail to decode it?
Disadvantage might be more data usage (we're going to re-download something that is not recoverable). Maybe we can have a retry limit.

**Comment by plamenko** [comment]
That's weird. I don't think we should do any code changes until we understand what exactly happened here. If the image gets corrupted during the download, network fetch should fail. I would expect HTTP library to be able to detect corruptions. That means that there is no reason to expect different outcome if we fetch the image again. So, caching the image is not a problem here, even if it cannot be decoded.

The problem we need to investigate is how we first got a corrupted and then a correct image for the same uri.

**Comment by droidwolf** [comment]
I have the same problem.

Because HttpUrlConnectionNetworkFetcher [HttpUrlConnectionNetworkFetcher](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/HttpUrlConnectionNetworkFetcher.java "HttpUrlConnectionNetworkFetcher")
did not determine whether the ResponseCode is HTTP_OK

**Comment by kirwan** [comment]
We're cleaning up long-untouched issues so I'm closing this one.

If you think this is still an issue, feel free to comment and we can re-open.

The last comment however mentioned the lack of a check for HTTP_OK which is now present.
