### ISSUE TITLE
After Proguard, the setImageURI(Uri.parse("res:///" + R.drawable.jl_kc_qun)) doesn't work

### ISSUE THREAD

**Issue by doubliekill** [facebook/fresco#806]
it was showed in placeholderImage

**Comment by plamenko** [comment]
What exactly "doesn't work" mean? Do you get an exception, do you just get a blank image, something else?

**Comment by doubliekill** [comment]
yeah it got a blank image.

when i use "clearn up" , the problem has resolved

**Comment by plamenko** [comment]
So, is this still an issue for you, or "clean up" resolved it and we can close this task?

**Comment by MARGI3** [comment]
@doubliekill  you problem resolved? i got the same problem too, the view show placeholderImage after proguard
