### ISSUE TITLE
Error:Unable to expand TAR 'C:\code\sample\fresco\fresco\imagepipeline\build\downloads\giflib-5.1.1.tar.gz'

### ISSUE THREAD

**Issue by guqun** [facebook/fresco#81]
hi 
 i met this problem ，how to solve？ windows version is 8.1.
Error:Unable to expand TAR 'C:\code\sample\fresco\fresco\imagepipeline\build\downloads\giflib-5.1.1.tar.gz'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file extension.
  If you need to specify the compression explicitly please refer to the DSL reference.
> Could not copy tar entry C:\code\sample\fresco\fresco\imagepipeline\build\downloads\giflib-5.1.1.tar.gz!giflib-5.1.1/lib/egif_lib.c to 'C:\code\sample\fresco\fresco\imagepipeline\build\tmp\expandedArchives\giflib-5.1.1.tar.gz_8s8zccijvdeiwfvw9mai009yv\giflib-5.1.1\lib\egif_lib.c'.

**Comment by tyronen** [comment]
Hmm...possibly another Windows issue, there sure are a lot of these. Can you try gradlew.bat clean and then build again?

**Comment by michalgr** [comment]
If `gradlew.bat clean` fails then removing `C:\code\sample\fresco\fresco\imagepipeline\build` directory manually should help.

**Comment by ljnalex** [comment]
I have the same issue:
Unable to expand TAR 'D:\facebook\fresco-master\imagepipeline\build\downloads\libjpeg-turbo-1.3.1.tar.gz'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file extension.
  If you need to specify the compression explicitly please refer to the DSL reference.
> Could not copy tar entry D:\facebook\fresco-master\imagepipeline\build\downloads\libjpeg-turbo-1.3.1.tar.gz!libjpeg-turbo-1.3.1/testimages/testorig.pp
m to 'D:\facebook\fresco-master\imagepipeline\build\tmp\expandedArchives\libjpeg-turbo-1.3.1.tar.gz_aa2m28byia46ll6k0hfesm18v\libjpeg-turbo-1.3.1\testim
ages\testorig.ppm'.

**Comment by guqun** [comment]
@tyronen 
i run gradlew.bat clean but failed. 
C:\code\thirdparty-code\fresco\fresco>gradlew clean
:drawee:clean
:fbcore:clean
:imagepipeline:ndk_clean_gifimage
Android NDK: Could not find application project directory !
C:\android-dev\android-ndk-r10d\build/core/build-local.mk:148: *** Android NDK:
Aborting    .  Stop.
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
make.exe: Entering directory `C:/code/thirdparty-code/fresco/fresco/imagepipelin
e/src/main/jni/gifimage'
make.exe: Leaving directory `C:/code/thirdparty-code/fresco/fresco/imagepipeline
/src/main/jni/gifimage'
:imagepipeline:ndk_clean_gifimage FAILED

**Comment by guqun** [comment]
@tyronen 
i run gradlew.bat build and met a problem.
Android NDK: WARNING: Ignoring unknown import directory: ../:../../../../build/n
ativemerge
Android NDK: Android.mk: Cannot find module with tag 'giflib' in import path

Android.mk:25: *** Android NDK: Aborting.    .  Stop.
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?

Android NDK: The following directories were searched:
Android NDK:
make.exe: Entering directory `C:/code/thirdparty-code/fresco/fresco/imagepipelin
e/src/main/jni/gifimage'
make.exe: Leaving directory `C:/code/thirdparty-code/fresco/fresco/imagepipeline
/src/main/jni/gifimage'
:imagepipeline:ndk_build_gifimage FAILED

**Comment by guqun** [comment]
@michalgr 
i try to  remove \imagepipeline\build directory .but the common of clean still fail。
C:\code\thirdparty-code\fresco\fresco>gradlew clean
:drawee:clean
:fbcore:clean
:imagepipeline:ndk_clean_gifimage
Android NDK: Could not find application project directory !
C:\android-dev\android-ndk-r10d\build/core/build-local.mk:148: *** Android NDK:
Aborting . Stop.
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
make.exe: Entering directory C:/code/thirdparty-code/fresco/fresco/imagepipelin e/src/main/jni/gifimage' make.exe: Leaving directoryC:/code/thirdparty-code/fresco/fresco/imagepipeline
/src/main/jni/gifimage'
:imagepipeline:ndk_clean_gifimage FAILED

**Comment by guqun** [comment]
i has sloved. please look #102
