### ISSUE TITLE
Decode BPG images

### ISSUE THREAD

**Issue by ioana-bacila** [facebook/fresco#810]
Hello,

I am a developer in search of an open source project trying to add some contributions in order to grow her own coding skills. I am interested in mainly Java and Android tools. After searching the Internet I found your library which is quite nice. I studied during my master degree about image encoding and formats. I realized that fresco doesn't add support for BPG, but it does add support for WebP. I consider that it would be quite a nice feature to be added to fresco, even though BPG (later edit - typo) is a fresh format. I have seen the comparisons between other graphics encoding and it seems that is does make a difference. Fresco would be up to date with the latest cutting edge technologies. If you think it is okay to include such support to fresco, I would gladly like to implement it.

Best regards,
Ioana

**Comment by plamenko** [comment]
Hi!

Thank you for your interest in Fresco. I think your idea is pretty cool and I see no reason not to do it. We just need to check some technicalities such as the license of those image formats, because some of them might be proprietary.
On a related note, right now we are in the process of making WebP support optional so that we don't impose additional size overhead to those apps that do not need it. Once we add ability to make WebP optional, I think it would be pretty straightforward to optionally support any other image format at no cost to those that are not using it. So we should be fine on that front too.
Btw, I am slightly confused because you mentioned BPG at first and then BNP. Are those two the same image format or? Also, I am curious what you have in mind when you say adding support for it. Do you mean adding an open source C library that handles those formats and the corresponding Java glue-logic, or are you thinking of actually implementing the codec itself?

**Comment by ioana-bacila** [comment]
Hi again!

First of all: sorry for that typo, it is about BPG image format. About the developemnt: yes, I was thiking about implementing the codec itself. If I will find some open source C library it might be a good option, I haven't made the complete research on the topic. Also, if I would add support for encoding the image, I believe that even if it is a lot of work, I can do it as I have written codecs before for both images and sounds. 
About WebP: can I help you with that or it is already in progress?

Cheers,
Ioana

**Comment by plamenko** [comment]
Exactly my thoughts, we should not reimplement this logic, but use the existing implementation. WebP refactoring is already in progress and we should be able to reuse that infrastructure to other formats as well.
But waiting until this is done that doesn't have to block you. You can still check out Fresco repo and start playing with it.

**Comment by ioana-bacila** [comment]
I will not wait for that, I just thought that it is okay to offer my help. I am already working on the task.

**Comment by ioana-bacila** [comment]
Hello, me again! 

I started wondering about the license for the BPG image format. I found out that it is subordinated to HAVC patents. Here is the list of those who are allowed to use HAVC:

Apple Inc.
Electronics and Telecommunications Research Institute (ETRI)
Fujitsu Limited
Hitachi Maxell, Ltd.
HUMAX Holdings Co., Ltd.
Intellectual Discovery Co., LTD.
JVC KENWOOD Corporation
Korea Advanced Institute of Science and Technology (KAIST)
Korean Broadcasting System (KBS)
KT Corp.
M&K Holdings Inc.
NEC Corporation
Newratek, Inc.
Nippon Hoso Kyokai (NHK)
Nippon Telegraph and Telephone Corporation (NTT)
NTT DOCOMO, INC.
Orange SA
Samsung Electronics Co., Ltd.
Siemens Corp.
SK Telecom
Tagivan II, LLC
The Trustees of Columbia University in the City of New York
Vidyo, Inc.

So, I see that not all Andorid users might be allowed to use such image format. This will limit fresco, isn't it?

Best regards,
Ioana

**Comment by plamenko** [comment]
Let me check that and we will respond here.

**Comment by ioana-bacila** [comment]
I checked the HAVEC info and BPG licence. There are some restrictions in using the code, but not all is restricted to be included in other projects. They state on their official site that:
1. "The BPG decoding library excluding the FFmpeg code is released under the BSD license."
2. "The BPG encoder sources excluding x265 are released under the BSD license."
3. "Some of the HEVC algorithms may be protected by patents in some countries (read the FFmpeg Patent Mini-FAQ for more information). Most devices already include or will include hardware HEVC support, so we suggest to use it if patents are an issue."

So, I can implement the Java logic referring to encode from JPEG/PNG to BPG and vice-versa.

**Comment by ioana-bacila** [comment]
Hello and Happy new year,

I have an issue with my contribution: I try to build my code with ndk-build but somehow, I do not know why, I get compile errors. My make file compiles properly with no issues. Can you advise me please about where I should place mu libbpg decoder so it could find my functions and compile properly?

Have a nice day and thank you in advance,
Ioana

**Comment by tyronen** [comment]
Use as a model the native code that does transcoding and resizing in the imagepipeline package.

**Comment by kirwan** [comment]
We're cleaning up long-untouched issues so I'm closing this one.

If you think this is still worth pursuing, feel free to comment and we can re-open. It looks to me as though the licensing issues which have been raised might make this impossible to pursue though.
