### ISSUE TITLE
in listview cell  has two images,but has some problem

### ISSUE THREAD

**Issue by zhiyou007** [facebook/fresco#813]
this is my item_xml

      <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:layout_marginLeft="10dp"
    android:layout_marginRight="8dp"
    android:layout_marginBottom="10dp">
    
	
    <com.facebook.drawee.view.SimpleDraweeView
        fresco:placeholderImage="@mipmap/bpic"
        fresco:placeholderImageScaleType="focusCrop"
        fresco:actualImageScaleType="focusCrop"
        android:layout_width="match_parent"
        android:layout_marginRight="2dp"
        android:layout_height="wrap_content"
        android:id="@+id/pianchang_pic"/>

        <com.facebook.drawee.view.SimpleDraweeView
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            fresco:roundWithOverlayColor="@color/translucent"
            android:layout_centerInParent="true"
            android:id="@+id/iv_graph"
            android:layout_width="38dp"
            android:layout_height="38dp"
            fresco:fadeDuration="300"
            fresco:actualImageScaleType="focusCrop"
            fresco:placeholderImage="@mipmap/avatar_default"
            fresco:placeholderImageScaleType="focusCrop"
            fresco:roundAsCircle="true"
            fresco:roundingBorderWidth="1dp"
            fresco:roundingBorderColor="@color/white"/>    
               </RelativeLayout>

but it show like this:

![device153913](https://cloud.githubusercontent.com/assets/1121168/11584720/2d8528b6-9aa1-11e5-96fd-9ffc641f7062.jpg)

avater image is not as circle

**Comment by zhiyou007** [comment]
imge type is jpeg,GIF OR png

**Comment by plamenko** [comment]
You need to specify `fresco:roundAsCircle="true"` on each view that you need to be rounded.

**Comment by zhiyou007** [comment]
@plamenko you not look my xml file carefully, the param is setted in my xml 
fresco:roundAsCircle="true"

**Comment by zhiyou007** [comment]
hello,has anybody?

**Comment by michalgr** [comment]
Can you check if removing `fresco:roundWithOverlayColor` helps ?

**Comment by zhiyou007** [comment]
@michalgr     i tried it,it's not work,you can try it,  in listview,  use my item_xml

**Comment by plamenko** [comment]
The XML you provided is confusing. There are two `SimpleDraweeView`, one with
`android:id="@+id/pianchang_pic"` and the other with `android:id="@+id/iv_graph"`. Only the later has the rounding params set. The screenshot you provided shows one image rounded and the other not. It is not clear what view in XML corresponds to what view on the screenshot.

Can you set the following two on BOTH SimpleDraweeViews and post the screenshot here:

  fresco:roundAsCircle="true"
  fresco:roundWithOverlayColor="@android:color/red"

**Comment by zhiyou007** [comment]
i chaged it as this:
    xml:

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:layout_marginLeft="10dp"
    android:layout_marginRight="8dp"
    android:layout_marginBottom="10dp">
    
	
    <com.facebook.drawee.view.SimpleDraweeView
        fresco:placeholderImage="@mipmap/bpic"
        fresco:placeholderImageScaleType="focusCrop"
        fresco:actualImageScaleType="focusCrop"
        android:layout_width="match_parent"
        android:layout_marginRight="2dp"
        fresco:roundAsCircle="true"
        fresco:roundWithOverlayColor="@android:color/red"
        android:layout_height="wrap_content"
        android:id="@+id/pianchang_pic"/>


    <com.facebook.drawee.view.SimpleDraweeView
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            android:layout_centerInParent="true"
            android:id="@+id/iv_graph"
            android:layout_width="38dp"
            android:layout_height="38dp"
            fresco:fadeDuration="300"
            fresco:actualImageScaleType="focusCrop"
            fresco:placeholderImage="@mipmap/avatar_default"
            fresco:placeholderImageScaleType="focusCrop"
            fresco:roundAsCircle="true"
            fresco:roundWithOverlayColor="@android:color/red"
            fresco:roundingBorderWidth="1dp"
            fresco:roundingBorderColor="@color/white"/>
      </RelativeLayout>

       it seems also not work.
![Uploading device-2015-12-10-114838.jpg…]()

**Comment by zhiyou007** [comment]
![Uploading device-2015-12-10-114838.jpg…]()

**Comment by tyronen** [comment]
I don't see your second screenshot. I also see that you are using `wrap_content` as the layout_height of the pianchang_pic view. Fresco does not support this.
