### ISSUE TITLE
Fresco can not load local xxx.gif resource

### ISSUE THREAD

**Issue by sfsheng0322** [facebook/fresco#815]
Hi:
    My name is SunFusheng.
    I want to load local xxx.gif, but fresco can not.
    Can it support?

**Comment by plamenko** [comment]
Yes, Fresco does support GIF images. In order to determine why your GIF fails to load we are going to need more information. If you can share the GIF image that would be the easiest way.

**Comment by sfsheng0322** [comment]
The following code:
Uri uri = Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.drawable.mygif);
DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setAutoPlayAnimations(true)
                .build();
sdvGif.setController(controller);
I put mygif in drawable dir. it does not work.

**Comment by plamenko** [comment]
Any chance you can upload that GIF file so we can try it ourselves? Have you followed the [troubleshooting] (http://frescolib.org/docs/troubleshooting.html#_) steps?

**Comment by sfsheng0322** [comment]
![gif_robot_walk](https://cloud.githubusercontent.com/assets/8130553/11673757/4f209236-9e56-11e5-8868-2c81fbd12a32.gif)
I try it again! Thank you!

**Comment by sfsheng0322** [comment]
I solved the problem by modifing following code:
Uri uri = Uri.parse("res://" + getActivity().getPackageName() + "/" + R.drawable.mygif);
Thanks very much!
