### ISSUE TITLE
GIF size limit

### ISSUE THREAD

**Issue by MojRoid** [facebook/fresco#816]
Whenever I try to load a large GIF in a SimpleDraweeView, it fails. Is there a hard size limit for GIFs, if so what is it and how do I change it? Sorry if question is a little noob, couldn't find anything in the documentation (or missed it).

**Comment by plamenko** [comment]
We do have a limit on cache items size, so it is quite possible that that's the reason. Any chance you can share the GIF file? Also, are you seeing any logcat messages output by Fresco?

**Comment by MojRoid** [comment]
For example http://media1.giphy.com/media/qzquneepSjFhm/giphy.gif wont load as I'm guessing the file size is too large (didn't record any logcat messages). In chance in knowing the hard limit so I can put a condition in my app?

**Comment by michalgr** [comment]
How do you determine that loading fails ? I am able to display the image you pointed to using our [uriapp](https://github.com/facebook/fresco/tree/master/samples/uriapp) sample app, it takes a few seconds to decode though.

**Comment by MojRoid** [comment]
Ah right, I tested it again and it actually worked, just took a good minute to load 😄 perhaps limited by my internet connection. I have my views in a RecyclerView with around a 100 or so items, maybe half with GIFs so perhaps it could be have been a memory issue. This is the app it's used in for reference:- https://play.google.com/store/apps/details?id=dev.moj.pad

Not too big of a deal, just thought there was a hard limit, if that was the case I would have checked the GIF size to determine whether to skip it or not. The issue I face tends to occur with large GIFs only, hence my thinking that it was a memory issue.

ps. On a second look, I think the long wait is attributed to the decode stage (as the loading placeholder disappears after a couple of seconds i.e. download, then the view appears to do nothing for about a minute as it decodes).

**Comment by skpnchl** [comment]
Fresco need. gif file decodes on the fly. I shaw their code they are passing the whole byte[] to native memory this is the main issue.
