### ISSUE TITLE
How much is the LowDiskSpace and the  VeryLowDiskSpace exactly is？

### ISSUE THREAD

**Issue by LiuDeng** [facebook/fresco#817]
How much is the LowDiskSpace and the  VeryLowDiskSpace exactly is？

**Comment by plamenko** [comment]
How is this Fresco related question?

**Comment by michalgr** [comment]
In case this is related to fresco, here is the disk cache configuration: https://github.com/facebook/fresco/blob/c08495a312ceffe15a815304b42db8fe24f6fde0/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipelineConfig.java#L177-L178

**Comment by LiuDeng** [comment]
@michalgr You do not get what i mean ,i mean how much is the border of the low and verylow disk space size. For example the if the space under 10M is very low , under 50M is low  so what exactly the border is ?

**Comment by plamenko** [comment]
@LiuDeng where do you get `LowDiskSpace` and ` VeryLowDiskSpace` from? Is this something that **Fresco** reports, or is this something that your **Android device** reports? If it is the later than this has nothing to do with the Fresco library. Even if the Fresco disk cache contributes to the disk usage the actual limits have likely nothing to do with Fresco.
