### ISSUE TITLE
Does Fresco respect Header caching?

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#818]
Is the max age in network requests respected? and ETAG?

**Comment by michalgr** [comment]
No, the default http stack and disk cache do not exchange any information apart from image bytes. But you can use ok-http as the http stack and disk cache: http://frescolib.org/docs/using-other-network-layers.html.

**Comment by droidekas** [comment]
So what is the max age for the images?

**Comment by michalgr** [comment]
By default Fresco never removes old entires unless you hit the size limit. If you want to clear old entries on your own, there is `FileCache. clearOldEntries` method which you can use.

**Comment by droidekas** [comment]
Ok that sounds good.
