### ISSUE TITLE
Glitches on some images on Nexus 4

### ISSUE THREAD

**Issue by defHLT** [facebook/fresco#819]
![zshlo2hpx](https://cloud.githubusercontent.com/assets/1539296/11662136/e8e6befa-9ddd-11e5-910c-bbfd0323bf10.png)
Some images have those distinctive stripes on them. I can provide original photo if needed

**Comment by michalgr** [comment]
Please share the original photo, I'll check whether I can reproduce this in our sample app.

**Comment by mlatu** [comment]
![img_20151114_151627](https://cloud.githubusercontent.com/assets/1539296/11671270/be2a5cda-9e0f-11e5-9c08-f033827cc4a2.jpg) here you go

**Comment by michalgr** [comment]
I am able to display the picture in our [uriapp](https://github.com/facebook/fresco/tree/master/samples/uriapp) without any artifacts. What version of fresco do you use ? Can you show us the code (java/xml) that configures SimpleDraweeView ?

**Comment by root1991** [comment]
We use latest version. Also we are making resize feature

ImageRequest request = ImageRequestBuilder.newBuilderWithSource(imageItem.getUri())
                    .setResizeOptions(new ResizeOptions(mImageSize, mImageSize))
                    .build();
            PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                    .setImageRequest(request)
                    .build();
            imageViewFolder.setAspectRatio(1.0f);
            imageViewFolder.setController(controller);

Image size is 50dp.

**Comment by tyronen** [comment]
Hm. What devices is this behaviour occurring on?

**Comment by root1991** [comment]
Only Nexus 4. Android Version 5.1.1

**Comment by kirwan** [comment]
We're cleaning up long-untouched issues so I'm closing this one.

If you think this is still an issue, feel free to comment and we can re-open.
