### ISSUE TITLE
java.lang.NoClassDefFoundError: com.facebook.imagepipeline.producers.DiskCacheProducer$1

### ISSUE THREAD

**Issue by pengpeng** [facebook/fresco#82]
Android 5.0.1
Java sdk 1.7

Load Image From Web

W/System.err(24508): java.lang.NoClassDefFoundError: com.facebook.imagepipeline.producers.DiskCacheProducer$1
W/System.err(24508):    at com.facebook.imagepipeline.producers.DiskCacheProducer.produceResults(DiskCacheProducer.java:71)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MemoryCacheProducer.produceResults(MemoryCacheProducer.java:108)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:354)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:121)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:85)
W/System.err(24508):    at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:40)
W/System.err(24508):    at com.facebook.imagepipeline.producers.ImageTransformProducer.produceResults(ImageTransformProducer.java:55)
I/BufferQueue(16715):     [NEW] gb=0x64e0f070, handle=0x65840148, w=492, h=874, s=496, fmt=1
W/System.err(24508):    at com.facebook.imagepipeline.producers.RemoveImageTransformMetaDataProducer.produceResults(RemoveImageTransformMetaDataProducer.java:37)
W/System.err(24508):    at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.java:87)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MemoryCacheProducer.produceResults(MemoryCacheProducer.java:108)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:354)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:121)
W/System.err(24508):    at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:85)
W/MALI    (16507): MTK_AUX_isMTKFormat:168: int MTK_AUX_isMTKFormat(ANativeWindowBuffer_t*): format=1
W/System.err(24508):    at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(ThreadHandoffProducer.java:45)
W/System.err(24508):    at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
W/System.err(24508):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(24508):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(24508):    at java.lang.Thread.run(Thread.java:841)

got this error too

**Comment by pengpeng** [comment]
Already add imagepipeline-release.jar in the libs

**Comment by mbrubin56** [comment]
I had this error when I was trying to run compiling in the individual aars I built locally. It was solved by also including bolts-android. Perhaps you need to include that, too?

**Comment by michalgr** [comment]
If you compile aars separately and copy them into your project then you have to make sure that all dependencies are copied as well. It is much more convenient to use maven or gradle and let them handle this stuff.
