### ISSUE TITLE
Fresco fails to load an image again after its reference is closed.

### ISSUE THREAD

**Issue by ch4ndu** [facebook/fresco#821]
This is reproduced in a 3 step process.
1. Load the image from a url into a simpledrawee by calling setImageUri()
2.Use the same url to get the underlying bitmap through the new        
        BaseDataSubscriber<CloseableReference<CloseableBitmap>>() call. 
[Fresco log.txt](https://github.com/facebook/fresco/files/56120/Fresco.log.txt)

 After step 2, I try to load the image at same URL into another SimpleDrawee through the setImageUri(). I get a "Canvas: trying to use a recycled bitmap" error.

Here, I think Fresco didn't keep track of the image reference being closed(basically recycled the bitmap). In this case, when I make another request to the same url, it should go and do a Full Fetch.

**Comment by michalgr** [comment]
1. Is the view that draws to Canvas a SimpleDraweeView ?
2. What do you do with the bitmap in the `//work on the bitmap` if branch ? Do you store it somewhere (this is not allowed) ? Is there any chance that the code that manipulates the bitmap recycles it on its own ?
3. There is a leak in your code where you call `imageReference.clone().get()`. Clone method returns new instance of ClosaebleReference that you are responsible for closing. If you don't do that then garbage collector will have to.

**Comment by ch4ndu** [comment]
1. It is the SimpleDraweeView that draws to canvas
2.  I put the bitmap into a mediasessionCompat object for its use. This is the code snippet
mMediaSessionCompat.setMetadata(newMediaMetadataBuilder()
                                    .putBitmap(MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bitmap) 
                                    .putBitmap(MediaMetadataCompat.METADATA_KEY_ART, bitmap)
                                    .putBitmap(MediaMetadataCompat.METADATA_KEY_ALBUM_ART, bitmap)
                                    .build());

3.I didn't realize I had to close that too. Will not closing that cause this bug?

In my testing, I saw this crash happen only on ICS. Lollipop and Marshmallow seems to be fine though.

**Comment by michalgr** [comment]
Can you show us the full stack trace ? 3 can cause the bitmap to be recycled while it is used, however I still don't know how can this cause exception in SimpleDraweeView.
