### ISSUE TITLE
Have a package?

### ISSUE THREAD

**Issue by guoyoujin** [facebook/fresco#83]
Hello, is there any plane fresco ", I was directly in the eclipse development, at present the android studio is not very well, can you send me a plane? Or download on my own

**Comment by tyronen** [comment]
It sounds like you are looking for a binary download of Fresco? You can use Gradle or Maven for that; see the instructions in [English](http://frescolib.org/docs/download-fresco.html#_) or [Chinese](http://fresco-cn.org/docs/download-fresco.html#_)
