### ISSUE TITLE
Can I get bitmap synchronously?

### ISSUE THREAD

**Issue by tonyjs** [facebook/fresco#830]
I want to display image on Notification.

I searched the previous similar Issue, Check your reply, Check the Document and finally I I got the result that I can get Bitmap synchronously.

But I think to get Bitmap synchronously is really necessary when build Notification in IntentService.
Many android developers are using IntentService for handling the push message.

I added code what you guided in document into my PushIntentService, Image is not showing when first try.
```
private Notification getNotification() {
    final NotificationCompat.Builder builder = new NotificationCompat.Builder(context);
    builder.setContentTitle(notificationTitle);
    ...
    DataSource<CloseableReference<CloseableImage>> dataSource =
                    imagePipeline.fetchDecodedImage(imageRequest, context);
    dataSource.subscribe(subscriber, CallerThreadExecutor.getInstance());
    ...
    @Override
    public void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
            Bitmap bitmap = getBitmap(~);
            builder.setLargetIcon(bitmap);
    ...
    return builder.build();
}
```

Should I rethink the handle push message with image?

**Comment by michalgr** [comment]
There is no synchronous API for getting images. If you want you can make the operation synchronous by employing one of the synchronization primitives (CountDownLatch should be good). 

Please have in mind that Fresco deterministically manages lifetime of images via CloseableReferences. I have a strong suspicion that your `getBitmap` might violate the contract. Please read http://frescolib.org/docs/using-image-pipeline.html carefully to find out how to work with CloseableReferences.

That being said, to avoid issues you probably want not only to build the notification in `onNewResultImpl` but also send it there. Alternatively you can make copy of the bitmap managed by Fresco or make caller of getNotification responsible for closing CloseableReferences when it does not need the image anymore.

**Comment by michalgr** [comment]
Actually `builder.build()` makes a copy of the bitmap, so you don't need to send notification in `onNewResultImpl`. Here you can find some more info: http://frescolib.org/docs/datasources-datasubscribers.html#i-just-want-a-bitmap

**Comment by tonyjs** [comment]
Thanks for your answer eventhough insufficient and strange question. I'm gonna check a point that you gave me and documents more deeply.
