### ISSUE TITLE
How to make it not flash when constantly switching Load picture?

### ISSUE THREAD

**Issue by h1091129209** [facebook/fresco#833]

**Comment by michalgr** [comment]
Can you provide more information ? Can you show us how you use Fresco in your xml or java code ?

**Comment by h1091129209** [comment]
如何不让图片闪
How not to let the picture flash
![Uploading jdfw.gif…]()

**Comment by oprisnik** [comment]
I guess you have the same issue as #1468. If not, please let us know and we can re-open this issue.
