### ISSUE TITLE
Bitmap downloaded percentage

### ISSUE THREAD

**Issue by mustafasevgi** [facebook/fresco#835]
Hi,
I used to UIL for image downloading and i decide to use fresco. But i dont find get percentage downloaded.

Can you help me,
Thanks,

**Comment by massimocarli** [comment]
Hi,
Do you mean the percentage of the image while downloading?

**Comment by mustafasevgi** [comment]
Yes, @massimocarli

**Comment by massimocarli** [comment]
To do that you should use the ```getProgress()``` callback method of the ```DataSource```. This is a float from 0.0f and 1.0f which can be used to calculate percentage. https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/fbcore/src/main/java/com/facebook/datasource/DataSource.java#L73

**Comment by mustafasevgi** [comment]
Thanks @massimocarli.
