### ISSUE TITLE
gif image cound 't work fine with attr  fresco:roundAsCircle in SimpleDraweeView

### ISSUE THREAD

**Issue by cjztool** [facebook/fresco#836]
the layout is :
<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/xxxx_avatar"
            android:layout_width="58dp"
            android:layout_height="58dp"
            android:layout_centerVertical="true" 
            fresco:actualImageScaleType="fitCenter"
            fresco:placeholderImage="@drawable/avatar"
            fresco:placeholderImageScaleType="fitCenter"
            fresco:roundAsCircle="true" />

in java code :

Uri uri = Uri.parse(avatarUrl);
xxxxAvatar.setImageURI(uri); 

the url is

http://q.qlogo.cn/qqapp/1104755926/00D2048535A0170ABED755FD207845DD/100

i expact it shows as circle border (even if gif image does not animate), 
but it shows in square border still

fresco:roundAsCircle didn't work...

how can i fix it ?

**Comment by massimocarli** [comment]
At the moment we don't support rounded gif animations.  
http://frescolib.org/docs/rounded-corners-and-circles.html

**Comment by cjztool** [comment]
@massimocarli   Sorry, my mistakes , I didn't read docs carefully...Thanks for ur tips.

**Comment by marcosalis** [comment]
Hi @massimocarli, are there any plans to support `BITMAP_ONLY` for animated gifs in the future? Using the overlay color works but it poses way too many limitations: static background, impossible to use the view as shared element (the gif glitches and becomes squared as soon as the transition starts). Not to mention that even the ripple effect on the background looks horrible since it goes beyond the overlay color rectangle.

**Comment by erikandre** [comment]
@marcosalis There would be a quite a high performance penalty of performing the crop using a bitmap shader for each frame.

On newer versions of Android using an outline provider on the View itself could be an option. We got a pull request where this is implemented: https://github.com/facebook/fresco/pull/1736
As a workaround you could try using an View outline on API level 21+ and using the less nice overlay color option for older devices.

To work around the issue with shared element transitions you could then for older devices replace the animated image with a still frame where the crop is done using a bitmap shader right before you trigger the transition (yes, It's a bit hacky)

**Comment by marcosalis** [comment]
@erikandre thank you, you're class as usual ;)
I've successfully managed to improve the look on API 21+ with the view outline and using the overlay color for lower versions. That means quite a lot of changes programmatically and conditional code which is not ideal, it would be great if Fresco supported this out of the box in the future. But it works!

Regarding the flicker on the animated gif, I think it has to do with `setDecodePreviewFrame(true)` not working as it should. I'll create a separate ticket with a demo app for that though.

**Comment by erikandre** [comment]
@marcosalis About the flicker issue, the next release of Fresco will contain a rewritten GIF pipeline which is much improved over the old one (specially for performance, frame rate consistency, caching and lots more) so fingers crossed that it might be fixed then :)
