### ISSUE TITLE
Duplicate files copied in APK lib/armeabi-v7a/libwebp.so

### ISSUE THREAD

**Issue by 0kai** [facebook/fresco#837]
our app want to using "libwebp.so", so we compile a new share "libwebp.so", but it was duplicate with freso.

1. I try to using the "libwebp.so" in freso, but it cannot locate symbol like "WebPMemoryWriterInit".
2. I compile the lib as other name, it will woke.

How can I using the libwebp.so in freso, or exclude the "libwebp.so" from freso
can somebody give me an idea?

**Comment by massimocarli** [comment]
We're working on making webp optional and it will be released very soon. Anyway if you use Fresco just change the name of your own library and you should not have any problem. If you want the same libwebp.so of Fresco you just skip the build phase for yours.

**Comment by 0kai** [comment]
Thank you~
