### ISSUE TITLE
Error when rotating the view with animated image

### ISSUE THREAD

**Issue by 0kai** [facebook/fresco#838]
![jp479 tj0j _q vu3 s](https://cloud.githubusercontent.com/assets/1498653/11803725/75442126-a338-11e5-929a-72e2efd72373.png)

some android telephone will has this issue.
1. the view was set as "Crop" and loading animated image(like gif).
2. when rotate the view, it will happen to see the image out of view rect

**Comment by massimocarli** [comment]
Hi,
can you provide more information please? Is it possible to get the URL of the animated webp/gif. What kind of rotation animation did you implement?
Thanks

**Comment by 0kai** [comment]
Hello,
For example: 
1、an animated gif file（320x320）
2、the fresco view width=320, height=200, set as crop
3、the gif is playing, view.setRotation(45)
some telephone will see this issue. (the image will showing out of the view rect)

**Comment by oprisnik** [comment]
We've released [Fresco v1.4.0](https://github.com/facebook/fresco/releases/tag/v1.4.0), which includes a new implementation for animated GIFs and animated WebPs. Please let us know if you're still experiencing this issue with the new version.
