### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by luozhiran** [facebook/fresco#842]
have a error "Failed to allocate a 28 byte allocation with 0 free bytes and 0B until OOM""

at java.util.concurrent.CopyOnWriteArrayList.iterator(CopyOnWriteArrayList.java:184)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at java.util.concurrent.CopyOnWriteArraySet.iterator(CopyOnWriteArraySet.java:305)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onProgressUpdate(MultiplexProducer.java:472)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onProgressUpdateImpl(MultiplexProducer.java:514)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.BaseConsumer.onProgressUpdate(BaseConsumer.java:92)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.DelegatingConsumer.onProgressUpdateImpl(DelegatingConsumer.java:38)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.BaseConsumer.onProgressUpdate(BaseConsumer.java:92)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.DelegatingConsumer.onProgressUpdateImpl(DelegatingConsumer.java:38)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.BaseConsumer.onProgressUpdate(BaseConsumer.java:92)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:106)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:65)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 18:42:45.694 12287-13208/utan.renyuxian E/art:     at java.lang.Thread.run(Thread.java:818)

**Comment by massimocarli** [comment]
Hi,
please provide more context and code in order to understand the problem.
