### ISSUE TITLE
Dynamic url support.

### ISSUE THREAD

**Issue by LPFinch** [facebook/fresco#847]
Hi folks! 

Logic.
I have 2 objects with image id. I can get dynamic url from server by api, example 
```java
String url = api.getImageUrl(object1.getId(), object2.getId());
}
```
I need put image to cache(both, internal and external) by custom id. 
Like this
```java
String customId = object1.getId() + "_" + object2.getId();
```
1. Objects have unique id's
2. Images on server the same but urls is dynamic
3. Check image by custom id in cache and download by dynamic url if not stored in cache

Thanks.

**Comment by aashrairavooru** [comment]
So basically you are saying that because of the server and client logic you have different urls may be generated for the same image?

**Comment by tyronen** [comment]
You can use a custom cache key factory. Override [CacheKeyFactory](http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/cache/CacheKeyFactory.html) and use it to configure the image pipeline.
