### ISSUE TITLE
Placeholder is not scaled properly when image rounding enabled

### ISSUE THREAD

**Issue by daviswalker** [facebook/fresco#848]
I am inserting a placeholder bitmap image into a SimpleDraweeView. When rounding is enabled, this image is not scaled to fit in the view. The actual image (not the placeholder) works fine - this is restricted to the placeholder.

I'm inserting the placeholder as so:

                GenericDraweeHierarchy hierarchy = getHierarchy();
                hierarchy.setPlaceholderImage(new BitmapDrawable(_context.getResources(), placeholder));

Thanks.

**Comment by massimocarli** [comment]
Please refer to this documentation for rounding and let us know if the problem persists. 
http://frescolib.org/docs/rounded-corners-and-circles.html#_
