### ISSUE TITLE
Massive memory use

### ISSUE THREAD

**Issue by mohammedhammouri** [facebook/fresco#849]
Did you this video :
https://www.youtube.com/watch?v=JEdcPenx8p8

Fresco uses too much memory hope you can fix it.

**Comment by plamenko** [comment]
Author of the video didn't use Fresco as intended. Local camera photos are huge and the best practice is to resize them before displaying.
Please see the documentation: [resizing] (http://frescolib.org/docs/resizing-rotating.html#_).
