### ISSUE TITLE
Issue in the doc for custom views

### ISSUE THREAD

**Issue by nbarraille** [facebook/fresco#85]
In http://frescolib.org/docs/writing-custom-views.html#_

The snippet of code for overriding the view lifecycle methods is off:
@Override
public void onDetachedFromWindow() {
  super.onDetachedToWindow();
  mDraweeHolder.onDetach();
}

instead of

@Override
public void onDetachedFromWindow() {
  super.onDetachedFromWindow();
  mDraweeHolder.onDetach();
}

**Comment by tyronen** [comment]
Thanks for finding this. Docs are corrected now.
