### ISSUE TITLE
How can I retain the progress image until decoding has finished?

### ISSUE THREAD

**Issue by tonyjs** [facebook/fresco#851]
My application should be show the large size image, so I add the progress drawable into hierarchy.
But It has fade out before image showing up.

I find the issue https://github.com/facebook/fresco/issues/797 but can't find any hint.

At least I only want to know whether the decoding image started.

**Comment by massimocarli** [comment]
Yes, this is related to https://github.com/facebook/fresco/issues/797 so please refer to that.
