### ISSUE TITLE
Request to support VectorDrawable

### ISSUE THREAD

**Issue by FragShawn** [facebook/fresco#855]
Android API 21 and above supports Vector Drawables I would like to use Fresco for switching between regular PNG and a VectorDrawable without having to use another class.
This will allow android apks to be smaller. It also allows build tools to to generate PNGs automatically if an android app is on a device older than API 21.

**Comment by IanChilds** [comment]
If you want to use VectorDrawable then I think you're best just creating it yourself and then setting it to be the placeholder image, and do not set an actual image.

**Comment by FragShawn** [comment]
So the issue is that I've made a VectorDrawable as a place holder image, and it doesn't show up on any device.

**Comment by oprisnik** [comment]
See also #1176
