### ISSUE TITLE
Ripple PressedStateOverlay works just once.

### ISSUE THREAD

**Issue by tonyjs** [facebook/fresco#858]
I make the drawable resource.
```
<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="?attr/colorControlHighlight"/>
```

and set into DraweeHierarchy.
```
Drawable drawable = getResources().getDrawable(R.drawable.ripple);
GenericDraweeHierarchy hierarchy = GenericDraweeHierarchyBuilder.newInstance(getResources())
                .setPressedStateOverlay(drawable)
                .setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER)
                .build();
draweeView.setHierarchy(hierarchy);
```
and then touch the draweeview, It works just once with no ripple effect(just showing colored rect).

Can I solve this problem ?

**Comment by sagartrehan** [comment]
@tonyjs I have added ripple effect on SimpleDraweeView by setting "app:overlayImage" attribute of SimpleDraweeView in layout xml. Doing this ripple effect working for me. But hot spot is always coming from center. I found that we need to set hotSpot of drawable programmatically but I didn't get any method of SimpleDraweeView that return "overlayImage" that I set in xml file.

Please let me know if we can programmatically get overlayImage drawable and set hot spot to it. Also let me know if there is another work around for this.

**Comment by plamenko** [comment]
Let's track this in #912.
