### ISSUE TITLE
Erasing cache from android app manager make  prefetchToDiskCache() have a strange behavior

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#862]
Hello,

Erasing cache from android app manager make  prefetchToDiskCache() have a strange behavior : some uris are not fetched thus dataSource is called and return isFinished().

Goal : prefetchToDiskCache() for a list of Uris

1 - On first install and first run of app : all uris are well prefetched.

2 - Go to Android app manager and erase cache (not app data)

3 - relaunch prefetchToDiskCache() : some uris return isFinished() threw BaseDataSubscriber and onNewResultImpl() thus nothing has been downloaded. Always 16 uris from a list of 52 uris.

for (int i = 0; i < finalListNotInCache_2.length(); i++) {
            JSONObject json_obj = null;
            try {
                json_obj = finalListNotInCache_2.getJSONObject(i);
            } catch (JSONException e) {
                e.printStackTrace();
            }
           Uri urlImage = null;
            try {
                urlImage = Uri.parse(json_obj.getString("IMAGE"));
            } catch (JSONException e) {
                e.printStackTrace();
            }
            ImagePipeline imagePipeline = Fresco.getImagePipeline();
            ImageRequest request = ImageRequestBuilder
                    .newBuilderWithSource(urlImage)
                    .setResizeOptions(new ResizeOptions(4096, 4096)
                    .build();
            //initiate prefetch
            `DataSource<Void> prefetchDataSource = imagePipeline.prefetchToDiskCache(request, this);`
	    Log.d("TEST PREFETCH_1", String.valueOf(prefetchDataSource) + " url: " + String.valueOf(urlImage));

            final Uri finalUrlImage = urlImage;

            DataSubscriber<Void> subscriber = new BaseDataSubscriber<Void>() {
                @Override
                protected void onNewResultImpl(DataSource<Void> prefetchDataSource) {
                    if (!prefetchDataSource.isFinished()) {
                        Log.d("TEST PROGRESS_1 : ", String.valueOf(prefetchDataSource) + "progress :" + String.valueOf(prefetchDataSource.getProgress()) + " url: " + String.valueOf(countImages) + " - " + finalUrlImage);
                        return;
                    }
                    addOneMoreImage(); // ajoute 1 au compteur d'images countImages
                    Log.d("TEST PROGRESS_2 : ", String.valueOf(prefetchDataS`ource) + " url: " + String.valueOf(countImages) + " - " + finalUrlImage);
                    tvNombreImagesInCache.setText(String.valueOf(nombreImagesInCache + countImages));
                    tvNombreImagesNotInCache.setText(String.valueOf(nombreImagesNotInCache - countImages));
                    prefetchDataSource.close();
                    if (prefetchDataSource.isClosed()) {

                        Log.d("TEST_IS_CLOSED_2 : ", String.valueOf(prefetchDataSource) + " url: " + String.valueOf(countImages) + " - " + finalUrlImage);

                    }

                }

                @Override
                protected void onFailureImpl(DataSource<Void> dataSource) {
                    Throwable t = dataSource.getFailureCause();
                    Log.d("TEST FAILURE : ", " url: " + finalUrlImage + "T :" + t);
                    // handle failure
                    
                }

            };
            prefetchDataSource.subscribe(subscriber, UiThreadImmediateExecutorService.getInstance());  //CallerThreadExecutor.getInstance() utilise UI pour update compteurs - UiThreadImmediateExecutorService.getInstance()

           }

Is there something I missed ?

Greatings,
Eric

**Comment by eldk** [comment]
Hello,

A check with this : 


`    public static boolean isImageDownloaded(Uri loadUri) {
        if (loadUri == null) {
            return false;
        }
        CacheKey cacheKey = DefaultCacheKeyFactory.getInstance().getEncodedCacheKey(ImageRequest.fromUri(loadUri));
        return ImagePipelineFactory.getInstance().getMainDiskStorageCache().hasKey(cacheKey) || ImagePipelineFactory.getInstance().getSmallImageDiskStorageCache().hasKey(cacheKey);
    }
`

on each image after erasing cache from Android App Manager show that some of them hasn't been writed to cache.

**Comment by IanChilds** [comment]
Can you try resizing to something much smaller? 4096 is huge, and may mean that there isn't space for all of the images that you are trying to prefetch.

**Comment by eldk** [comment]
Hello,

I'm logging all request now, with okHttp interceptors and log, tcpflow to webserver side.
Some urls aren't fetched and no request are send from Fresco. But, com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter onNewResultImpl() return isFinished() and datasource is closed.

For example, for a well fetched file : 
adb logs :
>01-05 15:24:24.189 1073-1073/tld.domain.appname D/TEST PREFETCH_1: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@408d7170 url: http://www.domain.tld/LAMAILLE/alose.jpg
>01-05 15:24:24.259 1073-2390/tld.domain.appname V/unknown:BufferedDiskCache: Did not find image for http://www.domain.tld/LAMAILLE/alose.jpg in staging area
01-05 15:24:24.259 1073-2390/tld.domain.appname V/unknown:BufferedDiskCache: Disk cache read for http://www.domain.tld/LAMAILLE/alose.jpg
01-05 15:24:24.259 1073-2390/tld.domain.appname V/unknown:BufferedDiskCache: Disk cache miss for http://www.domain.tld/LAMAILLE/alose.jpg
01-05 15:24:24.269 1073-14875/tld.domain.appname D/unknown:TEST_OKHTTP_1: Sending request http://www.domain.tld/LAMAILLE/alose.jpg on null
                                                                                     Cache-Control: no-store
01-05 15:24:24.329 1073-14875/tld.domain.appname D/unknown:TEST_OKHTTP_2: Received response for http://www.domain.tld/LAMAILLE/alose.jpg in 55.0ms
                                                                                     Date: Tue, 05 Jan 2016 14:15:14 GMT
                                                                                     Server: Apache/2.2.22
                                                                                     Content-Length: 238724
                                                                                     Etag: W/"PSA-aj-vgvDVpQ3zG"
                                                                                     Expires: Sun, 03 Jul 2016 13:31:21 GMT
                                                                                     Cache-Control: max-age=15549367
                                                                                     Vary: Accept
                                                                                     X-Content-Type-Options: nosniff
                                                                                     Keep-Alive: timeout=2
                                                                                     Connection: Keep-Alive
                                                                                     Content-Type: image/webp
                                                                                     OkHttp-Selected-Protocol: http/1.1
                                                                                     OkHttp-Sent-Millis: 1452003864296
                                                                                     OkHttp-Received-Millis: 1452003864338
01-05 15:24:50.439 1073-2390/tld.domain.appname V/unknown:BufferedDiskCache: About to write to disk-cache for key http://www.domain.tld/LAMAILLE/alose.jpg
01-05 15:24:50.449 1073-1073/tld.domain.appname D/TEST PROGRESS_2 :: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@408d7170 url: 20 - http://www.domain.tld/LAMAILLE/alose.jpg
01-05 15:24:50.449 1073-1073/tld.domain.appname D/TEST_IS_CLOSED_2 :: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@408d7170 url: 20 - http://www.domain.tld/LAMAILLE/alose.jpg
01-05 15:24:50.519 1073-2390/tld.domain.appname V/unknown:BufferedDiskCache: Successful disk-cache write for key http://www.domain.tld/LAMAILLE/alose.jpg`

tcpflow logs :
>192.168.001.001.56737-192.168.001.002.00080: GET /LAMAILLE/alose.jpg HTTP/1.1
>192.168.001.001.33459-192.168.001.002.00080: GET /LAMAILLE/alose.jpg HTTP/1.1
>192.168.001.002.00080-192.168.001.001.33459: HTTP/1.1 200 OK
(...)

and a non well fetched file :
adb logs :
>01-05 15:24:24.249 1073-1073/tld.domain.appname D/TEST PREFETCH_1: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@4082bda8 url: http://www.domain.tld/LAMAILLE/seiche_sepia_officinalis-2.jpg
01-05 15:24:39.039 1073-1073/tld.domain.appname D/TEST PROGRESS_2 :: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@4082bda8 url: 17 - http://www.domain.tld/LAMAILLE/seiche_sepia_officinalis-2.jpg
01-05 15:24:39.039 1073-1073/tld.domain.appname D/TEST_IS_CLOSED_2 :: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@4082bda8 url: 17 - http://www.domain.tld/LAMAILLE/seiche_sepia_officinalis-2.jpg

tcpflow logs : nothing

Thanks,

Eric

**Comment by eldk** [comment]
Hello,
@IanChilds 
>Can you try resizing to something much smaller? 4096 is huge, and may mean that there isn't space for all of the images that you are trying to prefetch. 

I have set down ResizeOptions() to 2048,2048 and 1024,1024 with same result.

Thanks,

Eric

**Comment by IanChilds** [comment]
I wonder if some of the images are not being fetched because they are already in the memory cache. Could you please run with logcat http://frescolib.org/docs/troubleshooting.html#setting-up-logcat and see if that is the case (or just post the logcat here)? Thanks!

**Comment by eldk** [comment]
Hello,

I have disabled all okHttp and get back to Fresco ImagePipelineConfig.

Fresco is initialized with this : 

`Context context = getApplicationContext();
        Set<RequestListener> requestListeners = new HashSet<>();
        requestListeners.add(new RequestLoggingListener());`
`ImagePipelineConfig config = ImagePipelineConfig
                .newBuilder(context)
                .setDownsampleEnabled(true)
                .setRequestListeners(requestListeners)
                .build();
        Fresco.initialize(context, config);
        FLog.setMinimumLoggingLevel(FLog.VERBOSE);`

I can reproduce it. (request is started but no request send to webserver for some files)
I will try to produce clear logs tomorrow (I have stopped them  a little too early for adb logs).

Thanks,

**Comment by eldk** [comment]
@IanChilds 
Hello,
Should I send you logs by mail ?
Four files : 2 tcpflow logs, 2 adb logs
1 tcpflow + 1 adb logs with all url requested, writed to disk/cached
1 tcpflow + 1 adb logs with all url requested, from the app, but not on webserver (no GET), and not writed to disk/cached.

Trace from one file succeded : 
adb logs :
>01-07 15:59:33.999  6773  6773 D TEST PREFETCH_1: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@407db9b8 url: http://www.domain.tld/LAMAILLE/alose.jpg
01-07 15:59:34.009  6773  6773 V unknown:RequestLoggingListener: time 1025264270: onRequestSubmit: {requestId: 219, callerContext: java.lang.Object@40763f68, isPrefetch: true}
01-07 15:59:34.009  6773  6773 V unknown:RequestLoggingListener: time 1025264270: onProducerStart: {requestId: 219, producer: BackgroundThreadHandoffProducer}
01-07 15:59:34.109  6773  6786 V unknown:BufferedDiskCache: Did not find image for http://www.domain.tld/LAMAILLE/alose.jpg in staging area
01-07 15:59:34.109  6773  6786 V unknown:BufferedDiskCache: Disk cache read for http://www.domain.tld/LAMAILLE/alose.jpg
01-07 15:59:34.109  6773  6786 V unknown:BufferedDiskCache: Disk cache miss for http://www.domain.tld/LAMAILLE/alose.jpg
01-07 15:59:34.189  6773  6783 V unknown:RequestLoggingListener: time 1025264449: onProducerFinishWithSuccess: {requestId: 219, producer: BackgroundThreadHandoffProducer, elapsedTime: 179 ms, extraMap: null}
01-07 15:59:34.209  6773  6783 V unknown:RequestLoggingListener: time 1025264464: onProducerStart: {requestId: 219, producer: EncodedMemoryCacheProducer}
01-07 15:59:34.209  6773  6783 V unknown:RequestLoggingListener: time 1025264464: onProducerFinishWithSuccess: {requestId: 219, producer: EncodedMemoryCacheProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=false}}
01-07 15:59:34.209  6773  6783 V unknown:RequestLoggingListener: time 1025264465: onProducerStart: {requestId: 219, producer: DiskCacheProducer}
01-07 15:59:34.209  6773  6783 V unknown:RequestLoggingListener: time 1025264471: onProducerFinishWithSuccess: {requestId: 219, producer: DiskCacheProducer, elapsedTime: 6 ms, extraMap: {cached_value_found=false}}
01-07 15:59:34.309  6773  6783 V unknown:RequestLoggingListener: time 1025264499: onProducerStart: {requestId: 219, producer: NetworkFetchProducer}
01-07 15:59:34.379  6773  6786 V unknown:BufferedDiskCache: About to write to disk-cache for key http://www.domain.tld/LAMAILLE/alose.jpg
01-07 15:59:34.389  6773  6773 D TEST PROGRESS_2 : : com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@407db9b8 url: 1 - http://www.domain.tld/LAMAILLE/alose.jpg
01-07 15:59:34.389  6773  6773 D TEST_IS_CLOSED_2 : : com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@407db9b8 url: 1 - http://www.domain.tld/LAMAILLE/alose.jpg
01-07 15:59:34.609  6773  6786 V unknown:BufferedDiskCache: Successful disk-cache write for key http://www.domain.tld/LAMAILLE/alose.jpg
01-07 15:59:35.799  6773  6787 V unknown:RequestLoggingListener: time 1025266061: onProducerFinishWithSuccess: {requestId: 219, producer: NetworkFetchProducer, elapsedTime: 1562 ms, extraMap: null}
01-07 15:59:35.849  6773  6787 V unknown:RequestLoggingListener: time 1025266111: onRequestSuccess: {requestId: 219, elapsedTime: 1841 ms}

tcpflow logs : 
>192.168.001.001.55885-192.168.001.002.00080: GET /LAMAILLE/alose.jpg HTTP/1.1
User-Agent: Dalvik/1.4.0 (Linux; U; Android 2.3.6; XT320 Build/GRK39F)
Host: www.domain.tld
Connection: Keep-Alive
Accept-Encoding: gzip

>192.168.001.002.00080-192.168.001.001.55885: HTTP/1.1 200 OK
Date: Thu, 07 Jan 2016 14:50:24 GMT
Server: Apache/2.2.22
Content-Length: 353836
Etag: W/"PSA-aj-4HObs4nmYS"
Expires: Tue, 05 Jul 2016 14:06:31 GMT
Cache-Control: max-age=15549367
Vary: Accept
X-Content-Type-Options: nosniff
Keep-Alive: timeout=2
Connection: Keep-Alive
Content-Type: image/jpeg

Trace from one file not writed/cached to disk nor fetched : 
adb logs : 
>01-07 15:59:34.159  6773  6773 V unknown:RequestLoggingListener: time 1025264421: onRequestSubmit: {requestId: 269, callerContext: java.lang.Object@40809400, isPrefetch: true}
01-07 15:59:34.159  6773  6773 V unknown:RequestLoggingListener: time 1025264422: onProducerStart: {requestId: 269, producer: BackgroundThreadHandoffProducer}
01-07 15:59:34.159  6773  6773 D TEST PREFETCH_1: com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@407b8fe8 url: http://www.domain.tld/LAMAILLE/seiche_sepia_officinalis-2.jpg
01-07 15:59:39.559  6773  6783 V unknown:RequestLoggingListener: time 1025269814: onProducerFinishWithSuccess: {requestId: 269, producer: BackgroundThreadHandoffProducer, elapsedTime: 5392 ms, extraMap: null}
01-07 15:59:39.559  6773  6783 V unknown:RequestLoggingListener: time 1025269816: onProducerStart: {requestId: 269, producer: EncodedMemoryCacheProducer}
01-07 15:59:39.559  6773  6783 V unknown:RequestLoggingListener: time 1025269818: onProducerFinishWithSuccess: {requestId: 269, producer: EncodedMemoryCacheProducer, elapsedTime: 2 ms, extraMap: {cached_value_found=true}}
01-07 15:59:39.569  6773  6773 D TEST PROGRESS_2 : : com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@407b8fe8 url: 19 - http://www.domain.tld/LAMAILLE/seiche_sepia_officinalis-2.jpg
01-07 15:59:39.569  6773  6773 D TEST_IS_CLOSED_2 : : com.facebook.imagepipeline.datasource.ProducerToDataSourceAdapter@407b8fe8 url: 19 - http://www.domain.tld/LAMAILLE/seiche_sepia_officinalis-2.jpg
01-07 15:59:39.599  6773  6783 V unknown:RequestLoggingListener: time 1025269845: onRequestSuccess: {requestId: 269, elapsedTime: 5423 ms}

No trace from tcpflow, no GET for this file.

Thanks,
Eric

PS : I may mail you complete traces if needed

**Comment by IanChilds** [comment]
This is good thanks. You can see what is happening from the trace. After you clear the cache, the disk cache is emptied but the memory cache is not. This particular image is found in the memory cache and is therefore not fetched from the network (and not put back into the disk cache). 

If you want to clear the memory cache too, then you need to kill the app from the settings menu.

**Comment by eldk** [comment]
Ok, thanks.
So, I should use `imagePipeline.clearMemoryCaches();`  http://frescolib.org/docs/caching.html before launching prefetch ?
I try it.

**Comment by IanChilds** [comment]
Yep! Try that.

**Comment by eldk** [comment]
>So, I should use imagePipeline.clearMemoryCaches(); http://frescolib.org/docs/caching.html before launching prefetch ?
I try it.

Ok, thanks @IanChilds that solve the unprefetched files
