### ISSUE TITLE
Round progressbar 

### ISSUE THREAD

**Issue by hanhmh1203** [facebook/fresco#866]
Hi friends, 
I has a question, in my app I using SimpleDraweeView and I want use round progressbar  override when SimpleDraweeView load image.
plz help me.
my code:
   <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/adapter_detail_iv"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                android:visibility="gone"
                fresco:placeholderImage="@drawable/bg_default_loading_image" />

            <LinearLayout
                android:id="@+id/layout_progressbar"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="center"
                android:background="#33000000"
                android:gravity="center"
                android:orientation="vertical"
                android:visibility="gone">

                <ProgressBar
                    android:id="@+id/indeterminate_progress_large_library"
                    style="@style/Widget.MaterialProgressBar.ProgressBar.Small"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:indeterminate="true"
                    android:visibility="gone" />
            </LinearLayout>
        </FrameLayout>

**Comment by cazador4** [comment]
Maybe this will help you.
https://github.com/facebook/fresco/pull/775

**Comment by aagnes** [comment]
alternatively, fresco has an indeterminate progress indicator already. U can use AutoRotateDrawable for ProgressBarDrawable.

**Comment by rafaelekol** [comment]
@cazador4  I tried to implement your [CircleProgressBarDrawable](https://github.com/facebook/fresco/blob/2ed3a9dd56e14d7211f328c9952d114118b6598f/samples/contrib/com/facebook/drawee/drawable/CircleProgressBarDrawable.java), but instead of circle shape I get Oval. What could be the problem? Maybe because my DraweeView is not square?

**Comment by arpanbag001** [comment]
> 
> 
> @cazador4 I tried to implement your [CircleProgressBarDrawable](https://github.com/facebook/fresco/blob/2ed3a9dd56e14d7211f328c9952d114118b6598f/samples/contrib/com/facebook/drawee/drawable/CircleProgressBarDrawable.java), but instead of circle shape I get Oval. What could be the problem? Maybe because my DraweeView is not square?

That might be the problem.
Anyway, use 
`setPlaceholderImage(
                        AutoRotateDrawable(
                            ContextCompat.getDrawable(
                                postMediaHolder.context,
                                R.drawable.ic_refresh
                            ), 1000
                        ), ScalingUtils.ScaleType.CENTER
                    )`
And it should center, fix aspect ratio and scaling of the drawable.
