### ISSUE TITLE
Cant display image on HUAWEI H60-L02

### ISSUE THREAD

**Issue by DankeLuo** [facebook/fresco#867]
the device run Android4.4.2. i am not sure what the problem cause. But it was done well on other devices.
here is the log I found when open the app,and the screenshot:
![20151229115503](https://cloud.githubusercontent.com/assets/6705440/12029331/4fe26168-ae23-11e5-80de-4b8ff433b6bf.png)
![20151229115552](https://cloud.githubusercontent.com/assets/6705440/12029332/55c5acf2-ae23-11e5-9296-7402af5ce197.png)

**Comment by oprisnik** [comment]
I assume that the problem has been fixed with newer Fresco versions. Please let us know if you're still experiencing this issue.

**Comment by DankeLuo** [comment]
yeah, it works well now
