### ISSUE TITLE
Why fresco doesn't inlcude webp encoding functions?

### ISSUE THREAD

**Issue by beartung** [facebook/fresco#870]
Hi, fresco is awosome!  I have use freso to my projects for a while but I need webp encoding support too as downloadind and showing webp images. 

I check fresco codes and I found the webp lib didn't compile the encoder sources. Could you guys consider to support encode bitmap to webp inside freso? If so, I will not have to make a webp encoder jni lib and it will make the application more smaller.

Thanks.

**Comment by aagnes** [comment]
We currently don't have a plan for encoding webp since there's few needs.

**Comment by balazsbalazs** [comment]
Hey @beartung 
Can you explain in more details why do you need encoding for displaying images?

**Comment by eldk** [comment]
Hello,

You can request webp pictures with okhttp by using for example a webp request in header Accept:image/webp,*/*;q=0.8  if they are stored as webp on webserver, I use it with pagespeed_module (Apache or Nginx - https://developers.google.com/speed/pagespeed/module/) on pictures webserver side.

Your pictures will be stored as it, webp, by Fresco, then you need to use  .setDownsampleEnabled(true) in your request to display it - http://frescolib.org/docs/resizing-rotating.html.

The picture storage is downsized for about 30 to 40%, if pictures metadata are erased too.

This is used there : https://play.google.com/apps/testing/net.opalesurfcasting.lamaille (alpha release).

Greatings,

Eric

**Comment by balazsbalazs** [comment]
I don't understand where you need encoding webps.
As far as I can understand your webserver will send Fresco already encoded webp images (the jpeg -> webp encoding will happen on the server in the pagespeed_module), right?
On the client side we only need to decode the webp images to display them.

Am I missing something?

**Comment by erikandre** [comment]
Closing as fresco already supports decoding of webp images. There is at the moment no need to including the encoding support.
