### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by huangshengsen** [facebook/fresco#871]
When loading a few pictures, I rotate the phone screen, after a while LeakCanary told me that there was a memory leak

This is the code in the adapter.

ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(TngouApi.IMG_BASE_URL + data.getImg()))
                .setPostprocessor(redMeshPostprocessor)
                .build();
        PipelineDraweeController controller = (PipelineDraweeController)
                Fresco.newDraweeControllerBuilder()
                        .setImageRequest(request)
                        .setOldController(imageView.getController())
                        .build();

        imageView.setController(controller);

![2015-12-29-23-15-51](https://cloud.githubusercontent.com/assets/12515992/12047325/981d5e24-af04-11e5-9c18-258595bfab15.png)

**Comment by jonyChina162** [comment]
I think this is not the Fresco's problem. When you rotate the screen, the activity needs to be destroyed and recreated, but the drawee prevent the destroy process of the activity as it holds the instance of the activity. So you just add  android:configChanges="orientation" into your manifest file where you define the activity like this:
<activity
            android:name=".MainActivity"
            android:configChanges="orientation" />

**Comment by huangshengsen** [comment]
Yes, I can limit the screen does not rotate, but I still hope to be able to rotate the screen

I tried to use the Glide and rotated the screen, LeakCanary did not tell me the memory leak

But I don't want to use Glide in my project.

**Comment by aagnes** [comment]
I assume you're using GenericDraweeView right? Fresco provides ActivityListener, which allows you to disconnect drawee from the destroyed activity.

**Comment by aagnes** [comment]
Can you try to debug and see if detachController in draweeholder is getting called when the activity gets destroyed?

**Comment by huangshengsen** [comment]
I define a MyDraweeView. When it onDetachedFromWindow let mDraweeHolder onDetach, log also printed out, but the problem is still the same, I do wrong?

/**
 * Created by tom on 15/12/29.
 */
public class MyDraweeView extends ImageView {

    private DraweeHolder<GenericDraweeHierarchy> mDraweeHolder;

    public MyDraweeView(Context context) {
        this(context, null);
    }

    public MyDraweeView(Context context, AttributeSet attr) {
        this(context, attr, 0);
    }

    public MyDraweeView(Context context, AttributeSet attr, int defStyle) {
        super(context, attr, defStyle);
        init();
    }
    private void init() {
        if (mDraweeHolder == null) {
            final GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(getResources())
                   .build();

            mDraweeHolder = DraweeHolder.create(hierarchy, getContext());
        }
    }

    @Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        mDraweeHolder.onDetach();
        System.out.println("&&onDetachedFromWindow");
    }

    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        mDraweeHolder.onAttach();
    }

    @Override
    protected boolean verifyDrawable(Drawable dr) {
        super.verifyDrawable(dr);
        return dr == mDraweeHolder.getHierarchy().getTopLevelDrawable();
    }

    @Override
    public void onStartTemporaryDetach() {
        super.onStartTemporaryDetach();
        mDraweeHolder.onDetach();
    }

    @Override
    public void onFinishTemporaryDetach() {
        super.onFinishTemporaryDetach();
        mDraweeHolder.onAttach();
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        return mDraweeHolder.onTouchEvent(event) || super.onTouchEvent(event);
    }
    public void setImageUri(String uri, ResizeOptions options) {
        final ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(uri))
                .setResizeOptions(options)
                .setAutoRotateEnabled(true)
                .build();
        final ImagePipeline imagePipeline = Fresco.getImagePipeline();
        final DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchDecodedImage(imageRequest, this);
        final AbstractDraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(mDraweeHolder.getController())
                .setImageRequest(imageRequest)
                .setControllerListener(new BaseControllerListener<ImageInfo>() {
                    @Override
                    public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                        super.onFinalImageSet(id, imageInfo, animatable);

                        CloseableReference<CloseableImage> imageCloseableReference = null;
                        try {
                            imageCloseableReference = dataSource.getResult();
                            if (imageCloseableReference != null) {
                                final CloseableImage image = imageCloseableReference.get();
                                if (image != null && image instanceof CloseableStaticBitmap) {
                                    CloseableStaticBitmap closeableStaticBitmap = (CloseableStaticBitmap) image;
                                    final Bitmap bitmap = closeableStaticBitmap.getUnderlyingBitmap();
                                    if (bitmap != null) {
                                        setImageBitmap(bitmap);
                                        setScaleType(ScaleType.CENTER_CROP);
                                    }
                                }
                            }
                        } finally {
                            dataSource.close();
                            CloseableReference.closeSafely(imageCloseableReference);
                        }
                    }
                })
                .build();
        controller.onDetach();
        mDraweeHolder.setController(controller);
        setImageDrawable(mDraweeHolder.getTopLevelDrawable());
    }
}
![screenshot_2015-12-31-10-51-25](https://cloud.githubusercontent.com/assets/12515992/12060897/e9cd579c-afb3-11e5-945c-755aa7e91a1a.png)

**Comment by aagnes** [comment]
you should really use drawee, then you won't have the leak problem. do you subclass from ImageView.
