### ISSUE TITLE
How to expand Fresco to support more types?

### ISSUE THREAD

**Issue by SongZiming19** [facebook/fresco#872]
Fresco cannot load bitmap from every video file. I want to use ffmpeg to retriever a bitmap from videofile when if failed , but the decoded Bitmap cannot put in memory cache, and will cause a continue loading if I setBitmap to the Drawee in a listview.
So I do not want just do this after it failed , but  want to do this on a callback where I can return a Bitmap, then Fresco helps to cache it in memory.

**Comment by aagnes** [comment]
How do you ask fresco to load the video file?
It works with mSimpleDraweeView.setImageURI(Uri.fromFile(new File(videoPath)));

**Comment by SongZiming19** [comment]
Yes, I am using mSimpleDraweeView.setImageURI(Uri.fromFile(new File(videoPath)));
But in some case, it cannot load success.
So I want to use ffmpeg.so to load bitmap when Fresco failed, how  to do this?
Thank you!

**Comment by SongZiming19** [comment]
I tried to save a jpg file from video, then use Fresco load from jpg file...
