### ISSUE TITLE
Square image in Horizontal Listview

### ISSUE THREAD

**Issue by Mithrandir21** [facebook/fresco#873]
**I am attempting to create a XML code for a SimpleDraweeView to display a square image in different RecyclerViews**.

``` java
<com.facebook.drawee.view.SimpleDraweeView
   android:id="@+id/card_item_image"
   android:layout_width="match_parent"
   android:layout_height="wrap_content"
   fresco:actualImageScaleType="centerCrop"
   fresco:viewAspectRatio="1"/>
```

I can achieve square images in any type of **vertical** list.
My issue is that if I attempt to use this layout for any **horizontal** lists, the SimpleDraweeView is not present.

(The image below shows 3 lists. The first is a horizontal list, while the two lists below are vertical.)
![screenshot](https://cloud.githubusercontent.com/assets/7038451/12050325/9eb9b174-aeeb-11e5-9134-f07fde9b0065.png)

I understand that Fresco has issues when it comes to not setting width and/or height.
If I set the Width to wrap, nothing is show, so _viewAspectRatio_ only works when it has a width.

Is there a workaround for this and can this be altered to accommodate square image based on available height instead of width?

**Comment by aagnes** [comment]
there's a way of doing so,
you need to have different params for different orientations
vertical:
<com.facebook.drawee.view.SimpleDraweeView
   android:id="@+id/card_item_image"
   android:layout_width="match_parent"
   android:layout_height="wrap_content"
   fresco:actualImageScaleType="centerCrop"
   fresco:viewAspectRatio="1"/>
horizontal:
<com.facebook.drawee.view.SimpleDraweeView
   android:id="@+id/card_item_image"
   android:layout_width="wrap_content"
   android:layout_height="match_parent"
   fresco:actualImageScaleType="centerCrop"
   fresco:viewAspectRatio="1"/>
then you should be good

**Comment by Mithrandir21** [comment]
My friend, I wrote specifically that this setup did not work.
(See the attach image to see what happens when I use your XML for horizontal.)

![screenshot1](https://cloud.githubusercontent.com/assets/7038451/12064215/15cf103c-afb5-11e5-9550-4d56f8224130.png)

So maybe not close this issue just yet?

**Comment by Mithrandir21** [comment]
Hi
Can this issue be re-opened since it is not resolved?

**Comment by hasMobi** [comment]
We are also experiencing this. Unfortunately, setting a fixed dp size to either the width or the height of the  `SimpleDraweeView` is not an option. Instead, we need a way of telling the view to recalculate the image width and height after downloading and setting it and then re-scale (I understand the performance hit needed implied from the recalculation of layout).

**Comment by hablema** [comment]
I'm also facing the same issue. Has anyone solved it ?


`         <com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/imagethumb"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                fresco:actualImageScaleType="centerCrop"
                fresco:viewAspectRatio="1"
                fresco:placeholderImage="@drawable/tile_default_square"
                fresco:placeholderImageScaleType="centerCrop"/>`


`  //Fresco init
        ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)
                .setDownsampleEnabled(true)
                .build();
        Fresco.initialize(context,config);`

**Comment by erikandre** [comment]
Closing as there has been no updates since 2016 and this is no prioritized to be implemented.
If this is a feature that you need, please consider submitting a pull request. Thanks!

**Comment by k2evil** [comment]
Guys it's so annoying. Please consider to fix this bug

**Comment by KevinPan** [comment]
> Guys it's so annoying. Please consider to fix this bug

UP
