### ISSUE TITLE
0.8.1 Load Gif Fial : Failed to slurp image 0, waiting online to fix ^_^...

### ISSUE THREAD

**Issue by LiuDeng** [facebook/fresco#874]
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err: java.lang.IllegalStateException: Failed to slurp image 0
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.gif.GifImage.nativeCreateFromNativeMemory(Native Method)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.gif.GifImage.create(GifImage.java:64)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(AnimatedImageFactory.java:67)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeGif(ImageDecoder.java:113)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:88)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke W/System.err:     at java.lang.Thread.run(Thread.java:818)
01-02 11:29:08.851 22170-22170/com.qiuduanribao.joke E/**onFailure:: Failed to slurp image 0

gif url is http://ww4.sinaimg.cn/bmiddle/6d87e02fjw1ezjzc314x2g20ao0607uw.gif

hope this will be fix in next version

thank you very much for this great lib

Happy new year with my best wishes

**Comment by aagnes** [comment]
#167

**Comment by anpingxiong** [comment]
Can you tell me .why is closed????@aagens
