### ISSUE TITLE
Incorrect cache hit when uri parameters change

### ISSUE THREAD

**Issue by devzhan** [facebook/fresco#878]
as fresco developer often use setImage to show image.but the uri is chaged sometimes when uri contains session .and then the cacheKey is new .there will be a new request.but the image dose not change. 
just like 
https://www.XXX.com/download/5805189589510567654
and
https://www.XXX.com/download/5805189589510567654?jsession=58adasfadse589510567654
the same image

**Comment by kirwan** [comment]
This can be resolved by the use of a `CacheKeyFactory` which strips your changeable query parameters.

We're cleaning up long-untouched issues so I'm closing this one.
