### ISSUE TITLE
Can not resolve symbol Fresco! 

### ISSUE THREAD

**Issue by Wood-Water-Peng** [facebook/fresco#879]
I am trying to import Fresco in my project,and i encounter the problem ,"Can't resolve symbol Fresco"!
And,this really make me crazy.
![fresco_pro_02](https://cloud.githubusercontent.com/assets/12949541/12112279/99b87ce2-b3d6-11e5-9d30-a4011731c550.png)
As you seee,"Fresco is red",when i enter the shortCut "Alt+Enter",it does not work.
![fresco_pro_03](https://cloud.githubusercontent.com/assets/12949541/12112333/e57177a6-b3d6-11e5-86bf-9520a7bea842.png)
I am sure i have import the module
![fresco_pro_04](https://cloud.githubusercontent.com/assets/12949541/12112478/c26e3374-b3d7-11e5-9720-4a80dc4c0e92.png)
But,when i import the modules,i changed their build.gradle file
![fresco_pro_01](https://cloud.githubusercontent.com/assets/12949541/12112506/e928ed10-b3d7-11e5-8b86-016ec81edb73.png)
I know little about  maven and JCenter,but i still do not know how to use them.
i hope you guys can give me a suitable solution!
And,I am Chinese,I live in Chinese mainland!

**Comment by tyronen** [comment]
It looks like you are trying to build directly from source inside Android Studio? In which case you shouldn't use the Maven compile.

```groovy
// don't use 
// compile 'com.facebook.fresco:0.7.0+'

// do this instead
compile project(':drawee-backends:drawee-pipeline')
```

**Comment by Wood-Water-Peng** [comment]
Inspired by your "Maven" world,i literally add Maven in my build.gradle.
![fresco_pro_05](https://cloud.githubusercontent.com/assets/12949541/12132972/f5745f3a-b45b-11e5-958f-6465c9f9bda5.png)
And It works! Thank you so much!
