### ISSUE TITLE
Nesting SimpleDraweeView in ScrollView

### ISSUE THREAD

**Issue by Wood-Water-Peng** [facebook/fresco#881]
when i try to nest SimpleDraweeView in ScrollView
i can not get the desired height of the image.
i mean, the image is scrollable,but the actual height is 1dp or 0
this is the url of the image http://www.qmtjr.com/images/ypic_03.jpg
i hope i can scroll the image vertically.
![fresco_nest_01](https://cloud.githubusercontent.com/assets/12949541/12133167/94e3532c-b45d-11e5-865e-1574399da3a2.png)
![fresco_nest_02](https://cloud.githubusercontent.com/assets/12949541/12133169/96b74686-b45d-11e5-84a5-b946ead065bc.png)
i really hope the suggestion!

**Comment by tyronen** [comment]
[Do not nest SimpleDraweeView in ScrollViews.](http://frescolib.org/docs/gotchas.html#don-t-use-scrollviews)
