### ISSUE TITLE
D/skia: --- SkImageDecoder::Factory returned null

### ISSUE THREAD

**Issue by z124055429y** [facebook/fresco#882]
i load many image url from network , but there is 4 image show incorrectly , and 4 log display on the logcat
D/skia: --- SkImageDecoder::Factory returned null
D/skia: --- SkImageDecoder::Factory returned null
D/skia: --- SkImageDecoder::Factory returned null
D/skia: --- SkImageDecoder::Factory returned null

**Comment by tyronen** [comment]
The most common reason for this is the images being in an unsupported format. What are the URls of these imags?

**Comment by z124055429y** [comment]
thank you very much , you are right ,i really get 2 empty string and 2 wrong unsupported format URIs
