### ISSUE TITLE
faild to resolve:com.facebook.fresco:fresco:0.8.1+

### ISSUE THREAD

**Issue by aileelucky** [facebook/fresco#886]
faild to resolve:com.facebook.fresco:fresco:0.8.1+

**Comment by aileelucky** [comment]
i can use 0.7.0+,but when i use 0.8.1+,android studio show this error

**Comment by tyronen** [comment]
By default, Fresco is served from Maven Central, not yet jCenter. Make sure your `build.gradle` file reflects this:

```groovy
repositories {
  mavenCentral()
}
```

**Comment by aileelucky** [comment]
@tyronen thank you very much

**Comment by kirwan** [comment]
jCenter is now up to date with Fresco releases. Either 0.8.1 or 0.9.0 can now be used without needing Maven Central.
