### ISSUE TITLE
Postprocessed image disappears when scrolling and back

### ISSUE THREAD

**Issue by Wood-Water-Peng** [facebook/fresco#887]
I prepare to use Fresco in my new app,so i meet a problem again!
This time i try to use Fresco in ListView.
In the item of the listView,i try get to image from server.
util now,i got two ways of loading image,so i made a comparison.
The sample one works well(set uri directly)
But i must post-process the downloaded bitmap,so i choose the set-controller one.
![qq 20160107190602](https://cloud.githubusercontent.com/assets/12949541/12169143/ba69d598-b571-11e5-95f2-b4fe1d876bed.png)
please see my problem
![qq 20160107185328](https://cloud.githubusercontent.com/assets/12949541/12169162/d3633238-b571-11e5-8146-3d10e16247d9.png)
first,i scroll down to make sure that the item is out of the screen,then i scroll back
![qq 20160107185428](https://cloud.githubusercontent.com/assets/12949541/12169200/1b651e84-b572-11e5-950d-85369afd7d7a.png)
so,buddy,what is wrong with my code?

**Comment by tyronen** [comment]
Can you attach a dump of logcat? Follow these instructions: http://frescolib.org/docs/troubleshooting.html#investigating-issues-with-logcat

**Comment by Wood-Water-Peng** [comment]
i try to do according to the doc!
first,i initialize the configuration
![qq 20160107193217](https://cloud.githubusercontent.com/assets/12949541/12169728/9d12da0e-b575-11e5-896c-2e55dbc0d10c.png)
then,i enter adb shell,and execute the command
![qq 20160107193301](https://cloud.githubusercontent.com/assets/12949541/12169729/9e05f892-b575-11e5-8027-520c19413138.png)
am i doing wrong or something else i was ignored?

**Comment by tyronen** [comment]
You have to turn on verbose logging in your app.

**Comment by massimocarli** [comment]
@Wood-Water-Peng 
is this problem fixed? It should be after a fix on PostProcessor. 
Thanks

**Comment by erikandre** [comment]
Cleaning up old issues. No additional information was provided.
