### ISSUE TITLE
Error:(25, 13) Failed to resolve: com.facebook.fresco:fresco:0.1.0+

### ISSUE THREAD

**Issue by Xuzhiwei** [facebook/fresco#89]
I'm use android studio to compile fresco.but it failed.

Error:(25, 13) Failed to resolve: com.facebook.fresco:fresco:0.1.0+
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by tyronen** [comment]
Your build.gradle file should point to Maven Central.

**Comment by jsflax** [comment]
Can confirm: I have mavenCentral() and it is still not working.

**Comment by FragShawn** [comment]
I'm also having this issue on both a mac and a windows pc. It looks like it couldn't get a file from the server. The details are pasted below:
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve javax.annotation:javax.annotation-api:[1.2,).
     Required by:
         PoppinSpot:app:unspecified > com.facebook.fresco:fresco:0.1.0 > com.facebook.fresco:imagepipeline:0.1.0
         PoppinSpot:app:unspecified > com.facebook.fresco:fresco:0.1.0 > com.facebook.fresco:drawee:0.1.0
         PoppinSpot:app:unspecified > com.facebook.fresco:fresco:0.1.0 > com.facebook.fresco:fbcore:0.1.0
      > Failed to list versions for javax.annotation:javax.annotation-api.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/javax/annotation/javax.annotation-api/maven-metadata.xml.
            > Could not GET 'https://jcenter.bintray.com/javax/annotation/javax.annotation-api/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

**Comment by mikeknoop** [comment]
Had the same error. It worked when I unchecked this:

![screen shot 2015-04-05 at 5 49 34 pm](https://cloud.githubusercontent.com/assets/800430/6999017/4000e0ec-dbbc-11e4-97cd-a46b45ed6a82.png)

**Comment by FragShawn** [comment]
Thanks for the reply. It got fixed without me doing anything on my end. I think it was a jcenter server issue.

**Comment by j-mateo** [comment]
I encountered the same issue when I first added Fresco and then again when I added the OkHttp lib for Fresco. In both instances, I fixed it by rebuilding the project: Build> Rebuild Project. Hope this helps someone else.

**Comment by Xuzhiwei** [comment]
Today I build the project,this issue was fixed.I didn't modify anything

**Comment by jsflax** [comment]
Agreed, seems to be fixed now.

On Mon, Apr 6, 2015 at 9:40 PM, Xuzhiwei <notifications@github.com> wrote:

> Today I build the project,this issue was fixed.I didn't modify anything
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/fresco/issues/89#issuecomment-90307910>.
>



-- 
*Jason Flax*
Lead Android Engineer
TodayTix

379 W. Broadway
New York, NY 10012
+1 (908) 839-2649

www.todaytix.com

Download TodayTix <http://www.todaytix.com/redirect-download.php>
Facebook <http://on.fb.me/1wktmJ9> | Twitter <http://bit.ly/1smvXyl> |
LinkedIn <http://linkd.in/1GqiVq6> | Blog <http://bit.ly/1wktvMJ>

**Comment by mkraitman** [comment]
> Thanks for the reply. It got fixed without me doing anything on my end. I think it was a jcenter server issue.

      > No cached version listing for com.facebook.fresco:fresco:1.+ available for offline mode.
      > No cached version listing for com.facebook.fresco:fresco:1.+ available for offline mode.
      > No cached version listing for com.facebook.fresco:fresco:1.+ available for offline mode.

**Comment by bjm88** [comment]
jcenter seems to be going away, does Maven Central have this>
https://stackoverflow.com/questions/69205724/unable-to-load-maven-meta-data-from-https-jcenter-bintray-com-org-webkit-andro

I got issue recently and not going away, only when removing jcenter as a repo in gradle build file.
