### ISSUE TITLE
Post processed images aren't properly cached

### ISSUE THREAD

**Issue by manuelbl** [facebook/fresco#895]
Our Android app has a dialog with a list. Each list item has the same icon in either green or gray. When the dialog is opened, we're seeing a fade-in animation for all but one icon even though the dialog has been opened before and all icons should already be in the cache.

It seems that the cache for post processed images isn't working properly. Therefore, the images are not taken from the postprocessor cache. Instead, a background process takes them from the cache with the original images, reruns the postprocessing and displays them with an animation.

We use the post processor to color the icons in either green or gray. The initial icon is downloaded as a PNG file from our remote server.

Our suspicion is that the code in PostprocessedBitmapMemoryCacheProducer.java at line 134 could be the cause. This code is called when an image has been successfully postprocessed. Instead of removing an existing image with the given key and reinserting it, it removes all images of the given post processor. Does that make sense? 

The relevant code in the dialog is:

    protected SimpleDraweeView iconView;
    protected ColorIconPostProcessor inactiveColorProcessor;
    protected ColorIconPostProcessor activeColorProcessor;
 
    ...

    iconView = (SimpleDraweeView) view.findViewById(R.id.icon)
    activeColorProcessor = new ColorIconPostProcessor(this.activeColor);
    inactiveColorProcessor = new ColorIconPostProcessor(this.inactiveColor);
 
    ...

    ImageRequestBuilder builder = ImageRequestBuilder.newBuilderWithSource(uri)
        builder.setPostprocessor(isActive ? this.activeColorProcessor : this.inactiveColorProcessor);
    ImageRequest request = builder.build();
    PipelineDraweeController controller = (PipelineDraweeController)
        Fresco.newDraweeControllerBuilder()
            .setImageRequest(request)
            .setOldController(iconView.getController())
            .build();
    iconView.setController(controller);

----

    public class ColorIconPostProcessor extends BasePostprocessor {

        private int color;

        public ColorIconPostProcessor(int color) {
            this.color = color;
        }

        @Override
        public String getName() {
            return "colorPostProcessor";
        }

        @Override
        public void process(Bitmap destBitmap, Bitmap sourceBitmap) {
            destBitmap.setHasAlpha(true);
            Canvas canvas = new Canvas(destBitmap);
            Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
            PorterDuffColorFilter pdf = new PorterDuffColorFilter(color, PorterDuff.Mode.SRC_ATOP);
            p.setColorFilter(pdf);
            canvas.drawBitmap(sourceBitmap, 0, 0, p);
        }

        @Override
        public CacheKey getPostprocessorCacheKey() {
            return new SimpleCacheKey(String.format("iconcolor-%d", color));
        }
    }

**Comment by VAdaihiep** [comment]
I have same issue with you @manuelbl 
And it seem to be fixed in v0.9.0, update your build.gradle and rebuild project.

**Comment by manuelbl** [comment]
Thanks for letting me know.

Yes, I've seen that the relevant code has been rewritten and can confirm it's working now. This issue has been fixed with v0.9 and can be closed.
