### ISSUE TITLE
Any way to use the sample classes via gradle dependency?

### ISSUE THREAD

**Issue by peterneubauer** [facebook/fresco#896]
Hi there, I'm trying to use the `ZoomableDraweeView` but it seems it's not included in the gradle dependency.

Is there a good way to package it and use it that you recommend?

Thanks a lot!

**Comment by tyronen** [comment]
We have build.gradle files for it in the repo. You can use that to include them in your app, as long as you are abiding by the sample license terms.

**Comment by peterneubauer** [comment]
Thanks!
