### ISSUE TITLE
In Qihoo Phone,Fresco can't loading section image

### ISSUE THREAD

**Issue by lzy26fate** [facebook/fresco#901]
those can't loading image is black
![bug image](https://cloud.githubusercontent.com/assets/7358871/12229500/5fe6d476-b883-11e5-9ad9-c768e85d3f05.png)

**Comment by michalgr** [comment]
Does this happen only on this particular phone ? Is there anything special about the image that cannot be opened ? What is the size/format of the images that can't be displayed ? Can you share them ? Also, does it always happen for the same images or random images cannot be displayed ?

**Comment by caojianfeng** [comment]
@lzy26fate 你是360的么，你这上面哪个是马赛克，哪个是没加载的啊？建议你做个demo截个图。

**Comment by lzy26fate** [comment]
The image is too large, making it impossible to load
