### ISSUE TITLE
When I use roundAsCircle="true" or roundedCornerRadius , url fails to load, display square

### ISSUE THREAD

**Issue by xiang-jian** [facebook/fresco#903]

**Comment by michalgr** [comment]
If I understood correctly, you want fresco: xml attributes to apply to failure images, right ? At the moment this is not supported, but you can provide any drawable as fresco:failureImage, you should be able to add rounding based on that.

**Comment by tcking** [comment]
that not work in xml,but worked in java code `            simpleDraweeView.getHierarchy().setFailureImage(getResources().getDrawable(R.drawable.img_defaul),ScalingUtils.ScaleType.FOCUS_CROP);`
