### ISSUE TITLE
about SimpleDraweeView$setImageURI

### ISSUE THREAD

**Issue by helengray** [facebook/fresco#905]
the uri is a network string url,every time,I must new a instance URI and had to judge the url is not empty.Can I just pass the string url parameter?

**Comment by michalgr** [comment]
For now there is no such option, feel free to drop a diff adding a utility method though !

**Comment by froxCZ** [comment]
@michalgr Hi, I would like to implement this. Could you let me know what is the desired behaviour? Would simple checking for not null in [https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/view/SimpleDraweeView.java#L96](SimpleDraweeView.java:96) and returning if Uri == null be enough?

**Comment by michalgr** [comment]
I think we need a new method on SimpleDraweeView that accepts String argument and calls [setImageURI](https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/view/SimpleDraweeView.java#L96) with null or new Uri depending on whether the string was null or not.

**Comment by froxCZ** [comment]
@michalgr I have submitted [pull request](https://github.com/facebook/fresco/pull/1038)
