### ISSUE TITLE
How to get a file which is the uri cache on the disk?

### ISSUE THREAD

**Issue by a631855639** [facebook/fresco#907]
How to get a file which is the uri cache on the disk?I want to save the image which is show by fresco,but I don't know to get the file from the cache disk

**Comment by michalgr** [comment]
There is no API exposing exact file location at the moment, we do not commit to preserving original format of cached images (we may want to add headers for example or encrypt images if cached on external storage).

Would accessing encoded bytes be enough for your use-case ? If so, have a look here: http://frescolib.org/docs/using-image-pipeline.html#skipping-the-decode
