### ISSUE TITLE
Use current image as placeholder for the next image, part 2

### ISSUE THREAD

**Issue by ealymbaev** [facebook/fresco#908]
I have the same issue as in the #236.

But the solution provided did not work - i have a FLICKER when replacing the image.

First, I load the thumbnail. After that (on user action) I start loading the original image with low res image request set to thumbnail (that is already loaded). But I have the flicker anyway.

Is there any way to just keep the existing image and set the new one when it is ready?

P.S. Please note that I am also resizing the original image (replacing datasource could be tricky)

**Comment by michalgr** [comment]
Can you make sure that all the options specified in the thumbnail request and the low res request are exactly the same ? Here is the list of things that needs to match in order for bitmap cache hit (bitmap cache hit = no flicker): https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/imagepipeline/src/main/java/com/facebook/imagepipeline/cache/BitmapMemoryCacheKey.java#L39

Also, you do you use post-processors by any chance ?

**Comment by ealymbaev** [comment]
The two requests are exactly the same. And I also use the postprocessor for blurring. Here are the codes:

Thumbnail Request: (initially thumbnail is displayed)

        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(thumbUrl))
                .setResizeOptions(new ResizeOptions(thumbnailSize, thumbnailSize))
                .setPostprocessor(new BlurPostprocessor(App.getContext()))
                .build();

After that I load the original image (from disk) and set the following low image request:

        if (thumbUrl != null) {
            ImageRequest thumbRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(thumbUrl))
                    .setResizeOptions(new ResizeOptions(thumbnailSize, thumbnailSize))
                    .setPostprocessor(new BlurPostprocessor(App.getContext()))
                    .build();
            controllerBuilder.setLowResImageRequest(thumbRequest);
        }

Thumbnail size:

        int thumbnailSize = LayoutHelper.dpToPx(100);

And the cache related methods of the BlurPostprocessor:

    @Override
    public String getName() {
        return getClass().getSimpleName();
    }

    @Override
    public CacheKey getPostprocessorCacheKey() {
        return new SimpleCacheKey("radius=" + radius + ",sampling=" + sampling);
    }

I am also using listeners for requests, but I don't think this can make any difference.

**Comment by ealymbaev** [comment]
I have found out that the issue is not with the low image request. My thumbnail images are not cached at all!

The issue is exactly with the BlurPostprocessor. If I remove blur - everything works as expected.

What is the issue with the postprocessor?

    public class BlurPostprocessor extends BasePostprocessor {
    
        private static int MAX_RADIUS = 20;
    
        private Context context;
        private int radius;
    
        public BlurPostprocessor(Context context) {
            this(context, MAX_RADIUS);
        }
    
        public BlurPostprocessor(Context context, int radius) {
            this.context = context.getApplicationContext();
            this.radius = radius;
        }
    
        @Override
        public void process(Bitmap dest, Bitmap source) {
            if (Build.VERSION.SDK_INT >= 17) {
                super.process(dest, getBlurredBitmap(dest, source));
            } else {
                super.process(dest, source);
            }
        }
    
        @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
        private Bitmap getBlurredBitmap(Bitmap dest, Bitmap source) {
            Bitmap blurredBitmap = Bitmap.createBitmap(source.getWidth(), source.getHeight(), Bitmap.Config.ARGB_8888);
    
            RenderScript rs = RenderScript.create(context);
            Allocation input = Allocation.createFromBitmap(rs, source, Allocation.MipmapControl.MIPMAP_NONE, Allocation.USAGE_SCRIPT);
            Allocation output = Allocation.createTyped(rs, input.getType());
    
            ScriptIntrinsicBlur blur = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));
    
            blur.setInput(input);
            blur.setRadius(radius);
            blur.forEach(output);
            output.copyTo(blurredBitmap);
    
            Bitmap scaledBitmap = Bitmap.createScaledBitmap(blurredBitmap, dest.getWidth(), dest.getHeight(), true);
            blurredBitmap.recycle();
    
            rs.destroy();
    
            return scaledBitmap;
        }
    
        @Override
        public String getName() {
            return getClass().getSimpleName();
        }
    
        @Override
        public CacheKey getPostprocessorCacheKey() {
            return new SimpleCacheKey("radius=" + radius);
        }
    
    }

**Comment by ealymbaev** [comment]
I have investigated the issue even deeper.

Caching stops working even if I set the simplest postprocessor without any real processing:

    public class BlurPostprocessor extends BasePostprocessor {
    
        @Override
        public String getName() {
            return getClass().getSimpleName();
        }
    
        @Override
        public CacheKey getPostprocessorCacheKey() {
            return new SimpleCacheKey(getName());
        }
    
    }

**Comment by michalgr** [comment]
Looks like a bug, which version of Fresco are you using ?

**Comment by ealymbaev** [comment]
compile 'com.facebook.fresco:fresco:0.8.1'

**Comment by ealymbaev** [comment]
Any updates on this issue?

**Comment by ealymbaev** [comment]
This issue is blocking me from releasing my application. Could you please let me know when it will be fixed?

**Comment by plamenko** [comment]
I made some changes to postprocessor caching a few weeks ago. This may have fixed the caching issue. Can you please check with the latest Fresco version?

**Comment by ealymbaev** [comment]
Great work! Now it works as expected. All postprocessed images are now cached. Thanks!

**Comment by plamenko** [comment]
Glad to heart that!
