### ISSUE TITLE
Does not load image from network

### ISSUE THREAD

**Issue by rajatdeshpande** [facebook/fresco#91]
I tried the code as mentioned on the getting started page of the fresco website. It loads the placeholder image but never loads the image from the network. Is there a way to check where is it stuck?

Activity's OnCreate Method looks like so

  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    Fresco.initialize(getBaseContext());
    setContentView(R.layout.activity_main);
    Uri uri = Uri.parse("http://frescolib.org/static/fresco-logo.png");
    SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
    draweeView.setImageURI(uri);
    
  }

**Comment by migueljimeno96** [comment]
You only need to add network connection permissions. Here you've a simple guide: http://developer.android.com/training/basics/network-ops/connecting.html

**Comment by Kester4android** [comment]
I solved it by add the Internet permission. Thanks for @tuhin10 's tip~
