### ISSUE TITLE
Not able to set hotspot on "overlayImage" drawable set in xml 

### ISSUE THREAD

**Issue by sagartrehan** [facebook/fresco#912]
I have set "app:overlayImage" drawable on SimpleDraweeView in xml layout for adding selector ripple effect on top of SimpleDraweeView. Setting "overlayImage" attribute correctly showing ripple effect on image but hot spot is always showing from center. To solve this I need the overlayImage drawable that I had set in xml resource but I didn't find any method to get overlayImage drawable programmatically.

If I prepare GenericDraweeHierarchy programmatically then I can prepare overlayImage drawable and can set touch listener hot spot to it. Code snippet:

SimpleDraweeView image = (SimpleDraweeView) findViewById(R.id.image);
GenericDraweeHierarchyBuilder builder = new GenericDraweeHierarchyBuilder(mContext.getResources());
Drawable overlayImage = getDrawable(R.drawable.image_selector);
builder.setOverlay(overlayImage);

image.setHierarchy(builder.build());

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
view.setOnTouchListener(new View.OnTouchListener() {
@TargetApi(Build.VERSION_CODES.LOLLIPOP)
@Override
public boolean onTouch(View v, MotionEvent event) {
if (overlayImage != null) {
overlayImage.setHotspot(event.getX(), event.getY());
}
return false;
}
});
}

But I do not want to create GenericDraweeHierarchy programmatically as I had already set different attributes in xml and do not want to change it and set programmatically. Please suggest any method to get "overlayImage" drawable that I had set in xml layout resource.

Please let me know if I can add hot spot in any other way

**Comment by sagartrehan** [comment]
Let me know if more details needed

**Comment by plamenko** [comment]
I think there is an easy fix to that. As of API 21 Drawable got a new method: ` void setHotspot (float x, float y)`. We just need to override this method in our `ForwardingDrawable` and `ArrayDrawable` and forward the call to the children.
We might want to make this feature optional though, because I am concerned by performance implications of passing each touchevent to the whole hierarchy of drawables. Anyhow, this should be easy to fix on Fresco side.

**Comment by plamenko** [comment]
@sagartrehan pull requests are always welcome :) If you would like to give it a shot, here are the two drawables that need to be modified: [ForwardingDrawable] (https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/drawable/ForwardingDrawable.java) and [ArrayDrawable] (https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/drawable/ArrayDrawable.java).

We just need to add something along these lines:

```Java
  @Override
  @TargetApi(Build.VERSION_CODES.LOLLIPOP)
  public void setHotspot(float x, float y) {
    mCurrentDelegate.setHotspot(x, y);
  }
```

**Comment by sagartrehan** [comment]
@plamenko : Sure I will prepare a pull for this change. Thanks

**Comment by sagartrehan** [comment]
@plamenko I have created PR to fix this issue. 

As per your comments "We might want to make this feature optional" let me know if I should add a configurable attribute for SimpleDraweeView styleable for enabling disabling ripple effect to prevent performance related issue involved due to passing each touch event to all drawee layers.

**Comment by erikandre** [comment]
Closing since this issue is not prioritized to be implemented in the foreseeable future.
If this is a feature that you need, please consider contributing a pull request to Fresco!
