### ISSUE TITLE
How to monitor the image loading  process

### ISSUE THREAD

**Issue by a631855639** [facebook/fresco#915]
Can I set the listener to monitor the image loading  process?How to do?

**Comment by desmond1121** [comment]
@a631855639 你是想要网络请求的进度还是？

**Comment by a631855639** [comment]
@desmond1121 图片加载的进度，包括从网络下载到显示这段时间的一个进度监听

**Comment by michalgr** [comment]
If you want to display progress bar, you can follow this: http://frescolib.org/docs/progress-bars.html. If you want to do something else you probably need to use image pipeline directly and provide your own DataSubscriber. You can find out more here:
http://frescolib.org/docs/using-image-pipeline.html
http://frescolib.org/docs/datasources-datasubscribers.html
https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/fbcore/src/main/java/com/facebook/datasource/BaseDataSubscriber.java#L70
