### ISSUE TITLE
Change BitmapUtil.MAX_BITMAP_SIZE dynamically based on the device

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [facebook/fresco#916]
when i load a long image，enlarge this Image，Can't read the words on the picture，Very low quality

**Comment by sillydong** [comment]
When we zoom in image which has large height toward width, it is displayed in very low quality.

ps. we are using v0.8.1

![longimage](https://cloud.githubusercontent.com/assets/1894696/12353765/68a27a2e-bbcc-11e5-910a-4d40740ad2a4.jpg)
![displaying](https://cloud.githubusercontent.com/assets/1894696/12353774/7f2c7f88-bbcc-11e5-952f-f7dc136dba9a.png)

**Comment by michalgr** [comment]
Could you help us debugging this by capturing debug logs ? Here is the description how to do this: http://frescolib.org/docs/troubleshooting.html#setting-up-logcat

**Comment by kunny** [comment]
There are several causes related to this issue:

- Source image's aspect ratio
- Fresco's max supported width/height in resizing

#### Source image's aspect ratio
The image's dimension that you have uploaded is 440x4200px, which is too long. I recommend making it smaller to fit into at least 1:2 (width:height), for example, 440*700 per each image, sliced in six.

#### Fresco's max supported width/height in resizing
If you `ResizeOptions`, the converted one has a max size of 2048px, which makes wide or long image's quality low. If you can cut the source into smaller one, its quality will be better.

@michalgr Is there any plan to make BitmapUtil.MAX_BITMAP_SIZE user-configurable?

**Comment by michalgr** [comment]
@kunny not at the moment. What is the desired limit you want to use ?

**Comment by kunny** [comment]
@michalgr It depends on each device, so it can't be defined as a constant. 

I'm using the modified version of fresco, which can support larger image after resizing the source image.
(https://github.com/kunny/fresco/commit/4bc9387c517522bb47d851486915a07627adf50f)

It accepts `ResizeOptions` with a max bitmap size supported by the device, and then do a resize within the limit. It can make output image have a better quality than before. 

However, before using this method, developer *must* sure that given `maxSupportedSize` does not exceeds the device's actual limit.

**Comment by balazsbalazs** [comment]
Not sure to be honest. I'm a bit afraid exposing this. I'm afraid that a lot of people will not be familiar with the memory consequences and just change it to a very large limit.

**Comment by balazsbalazs** [comment]
So according to @tyronen :
"We picked a default of 2048x2048.The thing is, many devices actually do support 4096x4096. But the only way to tell that is to use a nonstatic Canvas method. You need 1) a real, hw-accelerated Canvas, and 2) an API 14+ device.
At most we could expose a method that takes a Canvas argument and adjusts the limit, but the user must call it from within a draw method somewhere. Or we could hit it from the first Drawee to get drawn."

I wouldn't make the BitmapUtil.MAX_BITMAP_SIZE user-configurable, but option two could be doable: adjusting the size automatically on the first draw call.

To be fair, this would be very low on our priority list but we're always happy to see a pull request :) @kunny : would you like to create one?

**Comment by kirwan** [comment]
A change has been made to enable larger bitmap sizes if requested.

We're cleaning up long-untouched issues so I'm closing this one.

If you think this is still an issue, feel free to comment and we can re-open.
