### ISSUE TITLE
multidex on fresco(windows)

### ISSUE THREAD

**Issue by dotingcode** [facebook/fresco#919]
1.I have a error when I run the project.
Error:Execution failed for task ':packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/nineoldandroids/animation/Animator$AnimatorListener.class

2.This is my build config.
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}
allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
apply plugin: 'android'

dependencies {
    compile fileTree(include: '*.jar', dir: 'libs')
    //    compile 'com.android.support:support-v4:18.0.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.facebook.fresco:fresco:0.8.1+'
}

android {
    compileSdkVersion 18
    buildToolsVersion '23.0.0'
    defaultConfig {
        // Enabling multidex support.
        multiDexEnabled true
        minSdkVersion 9
        targetSdkVersion 23
    }
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }

        // Move the tests to tests/java, tests/res, etc...
        instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
    dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
    }
    packagingOptions {
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE.txt'
    }
    afterEvaluate {
        tasks.matching {
            it.name.startsWith('dex')
        }.each { dx ->

            if (dx.additionalParameters == null) {
                dx.additionalParameters = []
            }
            dx.additionalParameters += '--multi-dex' // enable multidex

            dx.additionalParameters += '--set-max-idx-number=50000'
            //  dx.additionalParameters += "--main-dex-list=$projectDir/multidex.txt"
            println "dex name = " + dx.name
        }
    }
    productFlavors {
    }
}

**Comment by massimocarli** [comment]
Hi @dotingcode, We're making some tests on Windows. In the meanwhile, could you please try to upgrade the gradle plugin from 
`classpath 'com.android.tools.build:gradle:1.3.0'`

to 

`classpath 'com.android.tools.build:gradle:1.5.0'`

and see if the problem persists. 
Thanks

**Comment by balazsbalazs** [comment]
@dotingcode 
Are you including any library that includes `nineoldandroids`?
Could you try the same config with the Fresco sample apps?

**Comment by dotingcode** [comment]
I have found the reason .Thank you for your answer.

2016-01-23 5:48 GMT+08:00 Balazs Balazs <notifications@github.com>:
