### ISSUE TITLE
add onProgress to ControllerListener ?

### ISSUE THREAD

**Issue by starfalling** [facebook/fresco#92]
How to show the progress of downloading when request image from server?

**Comment by plamenko** [comment]
I only added this functionality recently. The changes has been pushed to github, but I'm not sure that they made it to Maven yet. Until then, you can use this functionality if you are building Fresco from source.

So, to display the progress, you need to set a progressbar drawable that knows how to interpret drawable level. You can implement your own drawable, but we also provide one:
https://github.com/facebook/fresco/blob/53e1317d47e0e33d9927740ad4974cc479d8cc2a/drawee/src/main/java/com/facebook/drawee/drawable/ProgressBarDrawable.java

For usage example see:
https://github.com/facebook/fresco/blob/53e1317d47e0e33d9927740ad4974cc479d8cc2a/sample/src/main/java/com/facebook/fresco/sample/adapters/FrescoAdapter.java#L54
