### ISSUE TITLE
How to store image to disk cache with your own CacheKey?

### ISSUE THREAD

**Issue by outofdate** [facebook/fresco#920]
Is it possible to store image with your own cache key?
We have our own type of link which redirect us to image on AWS. This image URL contains different query parameters, so storing an image into cache is not working, because these parameters always different, but base URL, before "?" always same, so i want to use it as CacheKey for image.

**Comment by michalgr** [comment]
You can configure ImagePipeline with your own CacheKeyFactory: http://frescolib.org/docs/configure-image-pipeline.html. Here is the default implementation: https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/imagepipeline/src/main/java/com/facebook/imagepipeline/cache/DefaultCacheKeyFactory.java. The default one uses full url, your implementation can cut everything after '?'
