### ISSUE TITLE
Add "Tap to download" support

### ISSUE THREAD

**Issue by leeyikjiun** [facebook/fresco#921]
Is there a "tap to download" feature that is similar to the "tap to retry"?

Use case: some users might not want to download all images automatically and want to select which images to download. Also, some users might be on data and do not wish to download large images automatically, say 5MB and above.

**Comment by balazsbalazs** [comment]
We're currently not supporting this functionality but you can easily do this on top of Fresco.

I think it's a good idea so we're going to add it to our things to do/consider.

**Comment by oprisnik** [comment]
This can easily be achieved on top of Fresco. Feel free to send a pull request!
