### ISSUE TITLE
Out of memory when loading many animated image

### ISSUE THREAD

**Issue by 0kai** [facebook/fresco#922]
When we load a lot of animated image(gif) in a screen, the memory was very large.
setAutoPlayAnimations(false) also can't reduce the memory.

**Comment by balazsbalazs** [comment]
Hey, thanks for reporting this issue!

Fresco is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

If you don't know **how to do something** or **something is not working as you expect but not sure it's a bug**, please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

We welcome clear issues and PRs that are ready for in-depth discussion. Please provide screenshots where appropriate and always mention the version of Fresco you're using. Thank you for your contributions!

**Comment by oprisnik** [comment]
The next version of Fresco will include an improved animation implementation that should fix this issue.
