### ISSUE TITLE
java.lang.NoClassDefFoundError: com.facebook.cache.disk.DiskCacheConfig

### ISSUE THREAD

**Issue by vladut-lp** [facebook/fresco#923]
This is the log for my error : 
01-17 15:36:56.634: E/CrashReporting(1023): ParseCrashReporting caught a NoClassDefFoundError exception for com.package.name. Building report.
01-17 15:36:56.714: E/CrashReporting(1023): Handling exception for crash
01-17 15:36:56.714: E/CrashReporting(1023): java.lang.NoClassDefFoundError: com.facebook.cache.disk.DiskCacheConfig
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.facebook.imagepipeline.core.ImagePipelineConfig.getDefaultMainDiskCacheConfig(ImagePipelineConfig.java:172)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.facebook.imagepipeline.core.ImagePipelineConfig.<init>(ImagePipelineConfig.java:133)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.facebook.imagepipeline.core.ImagePipelineConfig.<init>(ImagePipelineConfig.java:64)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.facebook.imagepipeline.core.ImagePipelineConfig$Builder.build(ImagePipelineConfig.java:420)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.facebook.imagepipeline.core.ImagePipelineFactory.initialize(ImagePipelineFactory.java:86)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:32)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.package.name.MainMenuActivity.onCreate(MainMenuActivity.java:142)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.app.Activity.performCreate(Activity.java:5047)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.app.ActivityThread.access$700(ActivityThread.java:134)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.os.Looper.loop(Looper.java:137)
01-17 15:36:56.714: E/CrashReporting(1023): 	at android.app.ActivityThread.main(ActivityThread.java:4867)
01-17 15:36:56.714: E/CrashReporting(1023): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-17 15:36:56.714: E/CrashReporting(1023): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
01-17 15:36:56.714: E/CrashReporting(1023): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
01-17 15:36:56.714: E/CrashReporting(1023): 	at dalvik.system.NativeStart.main(Native Method)

I have imported the library to Eclipse IDE. Could anyone help me ? This error, as you can see, appears when I call 
Fresco.initialize(context);

**Comment by plamenko** [comment]
Does your app have multiple dex files ? If yes, do you follow all steps listed here: https://developer.android.com/tools/building/multidex.html ?
