### ISSUE TITLE
does fresco support offline viewing of an image?

### ISSUE THREAD

**Issue by mikekaraa** [facebook/fresco#924]
greetings, I would like to know if fresco supports offline capabilites if for example there is a network problem, the image can still be seen in the app?

**Comment by outofdate** [comment]
Yes. You should configure a disk cache and make sure that you have an URI for your image.

**Comment by balazsbalazs** [comment]
Hey, thanks for reporting this issue!

Fresco is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

If you don't know **how to do something** or **something is not working as you expect but not sure it's a bug**, please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

We welcome clear issues and PRs that are ready for in-depth discussion. Please provide screenshots where appropriate and always mention the version of Fresco you're using. Thank you for your contributions!
