### ISSUE TITLE
where is the fresco:0.9.0+?

### ISSUE THREAD

**Issue by szpnygo** [facebook/fresco#926]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_appDebugCompile'.
   > Could not find any version that matches com.facebook.fresco:fresco:0.9.0+.
     Versions that do not match:
         0.8.0
         0.7.0
         0.6.1
         0.6.0
         0.5.3
         + 7 more
     Searched in the following locations:
         https://jcenter.bintray.com/com/facebook/fresco/fresco/maven-metadata.xml
         file:/Users/ztadmin/android-sdk-macosx/extras/android/m2repository/com/facebook/fresco/fresco/maven-metadata.xml
         file:/Users/ztadmin/android-sdk-macosx/extras/android/m2repository/com/facebook/fresco/fresco/
         file:/Users/ztadmin/android-sdk-macosx/extras/google/m2repository/com/facebook/fresco/fresco/maven-metadata.xml
         file:/Users/ztadmin/android-sdk-macosx/extras/google/m2repository/com/facebook/fresco/fresco/

**Comment by HomHomLin** [comment]
Use this:
    compile 'com.facebook.fresco:fresco:0.9.0'
    compile 'com.facebook.fresco:imagepipeline-okhttp:0.9.0'

**Comment by balazsbalazs** [comment]
Fresco 0.9.0 is not on jCenter yet. We're working on the issue but you can use mavenCentral until that.

**Comment by szpnygo** [comment]
thanks

**Comment by kirwan** [comment]
jCenter is now up to date with Fresco releases. Either 0.8.1 or 0.9.0 can now be used without needing Maven Central.

**Comment by vinod1988** [comment]
Thanks Its help me
