### ISSUE TITLE
How to I determine the image in downloading process or writing process to make disk cache?

### ISSUE THREAD

**Issue by tonyjs** [facebook/fresco#928]
I want to find the stage of the image request.
so I added code 

```
DataSource<Boolean> dataSource = Fresco.getImagePipeline().isInDiskCache(originalUri);
dataSource.subscribe(new DataSubscriber<Boolean>() {
    @Override
    public void onNewResult(DataSource<Boolean> dataSource) {
        boolean isInDiskCache = dataSource.isFinished()
                && (dataSource.getResult() != null && dataSource.getResult());
        Log.d("tony", "isInDiskCache " + isInDiskCache);
    }

    @Override
    public void onFailure(DataSource<Boolean> dataSource) {
        Log.e("tony", "onFailure");
    }

    @Override
    public void onCancellation(DataSource<Boolean> dataSource) {
        Log.e("tony", "onCancellation");
    }

    @Override
    public void onProgressUpdate(DataSource<Boolean> dataSource) {
        Log.i("tony", "onProgressUpdate");
    }
}, UiThreadExecutorService.getInstance());
```

but I always get false value at the method 'onNewResult' even though the stage on download, encode or decode.

**Comment by eldk** [comment]
Hello,

You're only checking if file is in cache.
For this you should have a look here : http://frescolib.org/docs/caching.html#_ (onNewResultImpl)
and here : http://frescolib.org/docs/using-image-pipeline.html#_

Eric

**Comment by balazsbalazs** [comment]
Hey, thanks for reporting this issue!

Fresco is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

If you don't know **how to do something** or **something is not working as you expect but not sure it's a bug**, please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

We welcome clear issues and PRs that are ready for in-depth discussion. Please provide screenshots where appropriate and always mention the version of Fresco you're using. Thank you for your contributions!

**Comment by tonyjs** [comment]
@eldk @balazsbalazs Ok, Thanks guys.

**Comment by erikandre** [comment]
Closing
