### ISSUE TITLE
Gif image can't be resized or cached with setAutoPlayAnimations(false)

### ISSUE THREAD

**Issue by CharlesLin99** [facebook/fresco#930]
I try to load photo images in recycler view and found that gif image is loaded slowly even through i set
setAutoPlayAnimations(false). When i scroll the view, the views with gif image will flash.  How can i resize and cache gif image?

**Comment by balazsbalazs** [comment]
Can you provide more info, a sample app or a vide and logs please?

**Comment by balazsbalazs** [comment]
Hey, thanks for reporting this issue!

Fresco is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

If you don't know **how to do something** or **something is not working as you expect but not sure it's a bug**, please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

We welcome clear issues and PRs that are ready for in-depth discussion. Please provide screenshots where appropriate and always mention the version of Fresco you're using. Thank you for your contributions!

**Comment by CharlesLin99** [comment]
Sorry for not providing detail info.
**Fresco**: 0.9.0
**Issue**: Gif image show high quality and flashes when scrolling RecyclerView as video shows.  Seems Gif images doesn't resize and cache.


**Log**:
D/Charles.Lin: file:///storage/emulated/0/Download/test_image_a.jpg inMemoryCache:true
D/Charles.Lin: file:///storage/emulated/0/DCIM/Gif/tumblr_n8d80y1BDV1rk9vano1_500.gif inMemoryCache:**false**
![anglermmb29mtaishanlin01212016190153](https://cloud.githubusercontent.com/assets/14235815/12478724/83268f26-c071-11e5-9432-ec9ddaa30b4e.gif)

D/Charles.Lin: file:///storage/emulated/0/DCIM/Gif/tumblr_n2nj3tO0Oh1qjk2rvo1_500.gif inMemoryCache:**false**
D/Charles.Lin: file:///storage/emulated/0/DCIM/Gif/florian-1.gif inMemoryCache:**false**
D/Charles.Lin: file:///storage/emulated/0/DCIM/Gif/DfQqM.gif inMemoryCache:**false**
D/Charles.Lin: file:///storage/emulated/0/DCIM/Tango/IMG_20160105_165156_0_.jpg inMemoryCache:true
D/Charles.Lin: file:///storage/emulated/0/DCIM/Tango/IMG_20160105_163839_0_.jpg inMemoryCache:true
D/Charles.Lin: file:///storage/emulated/0/DCIM/Tango/IMG_20160105_112223_0_.jpg inMemoryCache:true

**Code in bindView**:
```java
    Uri imageUri = Uri.fromFile(new File(galleryImage.getPath()));
    boolean inMemoryCache = Fresco.getImagePipeline().isInBitmapMemoryCache(imageUri);
    Log.d("Charles.Lin", imageUri + " inMemoryCache:" + inMemoryCache);

    ImageRequest request = ImageRequestBuilder.newBuilderWithSource(imageUri)
      .setResizeOptions(new ResizeOptions(100, 100))
      .build();
    DraweeController controller = Fresco.newDraweeControllerBuilder()
      .setOldController(mSimpleDraweeView.getController())
      .setImageRequest(request)
      .setAutoPlayAnimations(false)
      .build();
    mSimpleDraweeView.setController(controller);
```

**Comment by AllenVork** [comment]
I got the same issue, do you resolve it ?

**Comment by ParkGiTae** [comment]
I got the same issue, do you resolve it ? help me

**Comment by parane** [comment]
Same issue here , plz help me !!!

**Comment by gaoxuxu** [comment]
I got the same issue, do you resolve it ?

**Comment by storix** [comment]
I think, fresco should convert the first GIF frame to jpg and then resize and cache it the same way it does with all other images. The resizing is critical here because there are so large GIFs that even the first frame can cause memory exhaustion.
