### ISSUE TITLE
imageInfo.getQualityInfo().isOfGoodEnoughQuality() and isOfFullQuality() always return true

### ISSUE THREAD

**Issue by LiuDeng** [facebook/fresco#931]
no matter what image i set to simpledrawee imageInfo.getQualityInfo().isOfGoodEnoughQuality() and 
iimageInfo.getQualityInfo().isOfFullQuality() always return true
this is the large image i use http://ww2.sinaimg.cn/large/006ajtzXjw1f00hnszdkgj30ku4rvwya.jpg .
how can i know the image onFinalImageSet is resized? and how much is width and height is of the orginal image?
Thank you for any help

**Comment by LiuDeng** [comment]
i find the QualityInfo is just for fetching image progressively, and then how can i now how much is width and height is of the orginal image?

**Comment by LiuDeng** [comment]
http://ww2.sinaimg.cn/large/006ajtzXjw1f00hnszdkgj30ku4rvwya.jpg the image orginal width and height is 750*6187 and i get the ImageInfo in onFinalImageSet imageInfo.getWidth() == 188 and  imageInfo.getHeight() is 1547 how can i get the 750*6187 
@michalgr

**Comment by balazsbalazs** [comment]
Hey, thanks for reporting this issue!

Fresco is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

If you don't know **how to do something** or **something is not working as you expect but not sure it's a bug**, please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

We welcome clear issues and PRs that are ready for in-depth discussion. Please provide screenshots where appropriate and always mention the version of Fresco you're using. Thank you for your contributions!
