### ISSUE TITLE
Sometimes bitmap is not available in MemoryCache

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#935]
My problem is if i am fetching bitmap from memory cache sometimes its not available. What i am doing is 
1. Load image from local path to SimpleDraweeView via setController.
2. Then i am using below code to fetch bitmap from cache

ImagePipeline imagePipeline = Fresco.getImagePipeline();
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(Uri.fromFile(new File(url)))
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                .build();

```
    DataSource<CloseableReference<CloseableImage>> dataSource = imagePipeline.fetchImageFromBitmapCache(imageRequest, mContext);
```
1. dataSource.getResult() is some times null sometime i am getting the image 

Why bitmap is not available in memory cache ? How can is resolve this problem ?
Thanks for advance.

**Comment by balazsbalazs** [comment]
Hey, thanks for reporting this issue!

Fresco is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

If you don't know **how to do something** or **something is not working as you expect but not sure it's a bug**, please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

We welcome clear issues and PRs that are ready for in-depth discussion. Please provide screenshots where appropriate and always mention the version of Fresco you're using. Thank you for your contributions!

**Comment by oprisnik** [comment]
I assume that the problem has been resolved. Please let us know if you're still experiencing this issue.
