### ISSUE TITLE
Fresco Library set up - Cannot Expand TAR

### ISSUE THREAD

**Issue by JoysonF** [facebook/fresco#94]
I imported fresco project into Android Studio. However i am not able to run the sample . It gives the following error:
Error:Cannot expand TAR '/home/Documents/fresco-master/imagepipeline/build/downloads/giflib-5.1.1.tar.gz'.
> Unable to create gzip input stream for resource /home/Documents/fresco-master/imagepipeline/build/downloads/giflib-5.1.1.tar.gz.

**Comment by ljnalex** [comment]
@JoysonF ,How solve?

**Comment by JoysonF** [comment]
@ljnalex , I Imported the project in a new Workspace. Dont know how weird that was. But i havent got this issue again.
