### ISSUE TITLE
SimpleDraweeView doesn't resize to match scaled image dimensions 

### ISSUE THREAD

**Issue by gikarasojo** [facebook/fresco#940]
I like fresco but i have an issue with simpledraweeview  which doesn't resize to match the size of scaled image. i have tried CENTER_CROP and even FIT_CENTER scale types but  whenever the scaled image height is smaller than my simple drawee view's height, a large space is left.

am using it to show images in a list view where am using a view holder to avoid inflating my layout views all the time thus enabling smooth scrolling.

here is the link to my code at stalk overflow  
http://stackoverflow.com/questions/34874463/forcing-simpledraweeview-to-resize-after-scaling-image-in-fresco
here is my simple drawee view. the red color is my view's background thus symbolizing  the empty spaces in the view
![img_20160121_105853](https://cloud.githubusercontent.com/assets/14346659/12474739/7a2baff2-c02e-11e5-98ce-92b59f5792e5.jpg)

**Comment by plamenko** [comment]
Answered on StackOverflow
