### ISSUE TITLE
UnsatisfiedLinkErrors in other libraries

### ISSUE THREAD

**Issue by dotingcode** [facebook/fresco#944]
Why after adding fresco, local libraries can not be scored so apk out?

**Comment by balazsbalazs** [comment]
Can you explain what is your problem exactly?

**Comment by dotingcode** [comment]
<http://fanyi.baidu.com/?aldtype=16047###>

Local already has a armebi library, the use of studio fresco to add
Android, will generate a lot of adapter CPU library files, the local
library files did not score apk

2016-01-22 22:24 GMT+08:00 Balazs Balazs <notifications@github.com>:

**Comment by plamenko** [comment]
I'm afraid I don't understand the issue.

**Comment by Ly-cc** [comment]
I have this issue too.

**Comment by Ly-cc** [comment]
Why after adding fresco. the code will go UnsatisfiedLinkError 
    static {
        try {
			System.loadLibrary("xxx");
		} catch (UnsatisfiedLinkError e) {
			// TODO: handle exception
			System.out.println(ValueUtil.getString(R.string.string_get_jni_error));
		}
    }

**Comment by tyronen** [comment]
Please tell us what 'xxx' is.

Please also post your `build.gradle` file.

**Comment by nesterov-n** [comment]
@Ly-cc  We faced with same problem. The answer is that other libraries have not 64-bit version of `.so`file, but fresco has. You can see more detaills [here](http://stackoverflow.com/a/30799825/2893307)

**Comment by erikandre** [comment]
Problem seems unrelated to fresco.
