### ISSUE TITLE
Failed to import in gradle

### ISSUE THREAD

**Issue by npola** [facebook/fresco#949]
The instructions in the repository says to use the following line in gradle to import the library

compile 'com.facebook.fresco:fresco:0.9.0+'

but that line fails. It seems like only version 0.8.0+ is available on maven central.

**Comment by QiuSean** [comment]
me too

**Comment by Graham-Bryan** [comment]
Me three

**Comment by edarn** [comment]
compile 'com.facebook.fresco:fresco:0.9.0' works fine. Remove the "+" sign and it will work.

**Comment by my519820363** [comment]
me four

**Comment by my519820363** [comment]
Look : https://github.com/facebook/fresco/issues/955

**Comment by balazsbalazs** [comment]
The 0.9.0 version is available on Maven Central, look [here](http://search.maven.org/#artifactdetails%7Ccom.facebook.fresco%7Cfresco%7C0.9.0%7Caar).

How does your gradle file look and what is the exact compilation error you get?
