### ISSUE TITLE
Some of the images are not loading

### ISSUE THREAD

**Issue by UmeshAawte** [facebook/fresco#957]
I have configuration something like this,

File fl = Environment.getExternalStorageDirectory();
			DiskCacheConfig diskCacheConfig = DiskCacheConfig.newBuilder().setBaseDirectoryPath(fl)
		            .setBaseDirectoryName("AppLocal")
		            .setMaxCacheSize(100 * ByteConstants.MB)
		            .setMaxCacheSizeOnLowDiskSpace(30 * ByteConstants.MB)
		            .setMaxCacheSizeOnVeryLowDiskSpace(15 * ByteConstants.MB)
		            .setBaseDirectoryPath(android.os.Environment.getExternalStorageDirectory())
		            .setVersion(1)
					.build();

With this it creates catche folder and works fine. But some images do not load. The images that do not load in first attempt loads again if I delete cache folder from the device.

Is this issue with disk cache or something else

**Comment by plamenko** [comment]
Please follow the [Troubleshooting] (http://frescolib.org/docs/troubleshooting.html#_) steps and provide the logcat output that will show where the issue is.
