### ISSUE TITLE
Gradle InflateException

### ISSUE THREAD

**Issue by agoodcoolman** [facebook/fresco#958]
the problem is java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable ，how solve it

have search issues,but I can't get the solution；

01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err: Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err:     at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:128)
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err:     at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:77)
01-27 17:38:11.039 2370-2370/com.deao.jmt W/System.err:     at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:60)

01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.createView(LayoutInflater.java:606)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.parseInclude(LayoutInflater.java:823)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.rInflate(LayoutInflater.java:729)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.inflate(LayoutInflater.java:489)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.LayoutInflater.inflate(LayoutInflater.java:396)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: com.deao.jmt.fragment.BuyGoodsFragment1.onCreateView(BuyGoodsFragment1.java:122)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:486)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.view.ViewPager.populate(ViewPager.java:919)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.View.measure(View.java:12723)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.View.measure(View.java:12723)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.View.measure(View.java:12723)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.View.measure(View.java:12723)
01-27 17:38:10.979 2370-2370/com.deao.jmt E/frame: android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2092)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: android.view.View.measure(View.java:12723)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1070)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2448)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: android.os.Handler.dispatchMessage(Handler.java:99)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: android.os.Looper.loop(Looper.java:137)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: android.app.ActivityThread.main(ActivityThread.java:4482)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: java.lang.reflect.Method.invokeNative(Native Method)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: java.lang.reflect.Method.invoke(Method.java:511)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
01-27 17:38:10.989 2370-2370/com.deao.jmt E/frame: dalvik.system.NativeStart.main(Native Method)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err: android.view.InflateException: Binary XML file line #16: Error inflating class com.facebook.drawee.view.SimpleDraweeView
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:606)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:823)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:729)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at com.deao.jmt.fragment.BuyGoodsFragment1.onCreateView(BuyGoodsFragment1.java:122)
01-27 17:38:10.989 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:486)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.view.View.measure(View.java:12723)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
01-27 17:38:10.999 2370-2370/com.deao.jmt W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.view.View.measure(View.java:12723)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.view.View.measure(View.java:12723)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.view.View.measure(View.java:12723)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2092)
01-27 17:38:11.009 2370-2370/com.deao.jmt W/System.err:     at android.view.View.measure(View.java:12723)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1070)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2448)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at android.os.Looper.loop(Looper.java:137)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4482)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err:     at dalvik.system.NativeStart.main(Native Method)
01-27 17:38:11.019 2370-2370/com.deao.jmt W/System.err: Caused by: java.lang.reflect.InvocationTargetException
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:586)
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err: 	... 47 more
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err: Caused by: java.lang.NoClassDefFoundError: com.facebook.drawee.R$styleable
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err:     at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:128)
01-27 17:38:11.029 2370-2370/com.deao.jmt W/System.err:     at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:77)
01-27 17:38:11.039 2370-2370/com.deao.jmt W/System.err:     at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:60)
01-27 17:38:11.039 2370-2370/com.deao.jmt W/System.err: 	... 50 more

**Comment by plamenko** [comment]
Duplicate #945
