### ISSUE TITLE
Support for Eclipse

### ISSUE THREAD

**Issue by tuhin10** [facebook/fresco#96]
Is there any official support for Eclipse IDE?? Can I use any jar version ??

**Comment by kymjs** [comment]
And me, hope to provide official support.

**Comment by tyronen** [comment]
We don't yet officially support it, and it looks like you can't yet import Gradle files into Eclipse. However, you might be able to make use of Eclipse's Maven plugin, called m2eclipse. See if the following helps:

http://books.sonatype.com/m2eclipse-book/reference/repository-sect-repo-view.html

**Comment by 79144876** [comment]
And me, hope to provide official support.
My project is old stand project ,not use Gradle.

**Comment by huanyi0723** [comment]
and me, hope to provide official support

**Comment by yy1300326388** [comment]
And me, hope to provide official support.
Eclipse trial Maven is also very trouble and speed in special slow loading for the first time.
@tyronen  Thank you, but I don't have used on android studio Gradle added successfully.

**Comment by andforce** [comment]
there is a way to get fresco support jar.

1:create a simple Gradle project.
2:run gradle build script.
then, you will find the jar at : YoueProject/app/build/intermediates/exploded-aar/com.facebook.fresco/
3:copy it to your Eclipse's libs folder.

**Comment by tyronen** [comment]
Ok my earlier comment about m2eclipse was incorrect. Instead, we've uploaded a zip file. If you expand it, it creates the following directory structure:
frescolib/
  drawee/
  fbcore/
  fresco/
  imagepipeline/

In your Eclipse workspace, import all **four** of these subdirectories as Eclipse projects. Use File, Import, Android, "Existing Android Code into Workspace".

Then in your app's own project, add a dependency on 'fresco'. Right-click on your project, choose Properties, then Android. Click Add and select Fresco.

Please let me know if this works, or doesn't work, for you, and I will add it to the official documentation.

**Comment by adenisonafifi** [comment]
I am attempting your Eclipse project import workaround, but I am unable to locate the zip file you mention uploading to the git repo. Am I missing it or was it not uploaded?

**Comment by tyronen** [comment]
Ha, I forgot to specify the URI: https://github.com/facebook/fresco/releases/download/v0.3.0/fresco-v0.3.0.zip. You can get to it from the Releases page.

**Comment by adenisonafifi** [comment]
Thank you for the quick response! I am able to successfully compile with fresco using ANT / Eclipse now.

**Comment by tuhin10** [comment]
@tyronen thanks a lot for your help.

**Comment by 79144876** [comment]
Is there any official support for Eclipse IDE?? Can I use any jar version ??

**Comment by adenisonafifi** [comment]
Import the Android libraries into Eclipse. The libraries are provided in the fresco zip https://github.com/facebook/fresco/releases/download/v0.4.0/frescolib-v0.4.0.zip

Instructions are provided by tyronen above.

**Comment by swatigoel** [comment]
I have downloaded fresco zip https://github.com/facebook/fresco/releases/download/v0.4.0/frescolib-v0.4.0.zip
After that I imported 4 projects in eclipse  drawee, fbcore, fresco, and imagepipeline.

Used fresco as library in My project but it didn't work. So I added these 4 projects in My Project build path. Then I could access Fresco.initialize(context) in activity.

But when I run my app and open that activity which initializing Fresco gives below error:
E/AndroidRuntime(4563): java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco

I have used "com.facebook.drawee.view.SimpleDraweeView" in layout but this line fresco:placeholderImage="@drawable/contact" always giving compiling error for "placeholderImage" attribute. I have used xmlns:fresco="http://schemas.android.com/apk/res-auto" also. Still no luck. 

Can anybody help me please

**Comment by kymjs** [comment]
just for fresco, I will be used Android Studio. In fact, also good.
