### ISSUE TITLE
Determine if a GIF is animated?

### ISSUE THREAD

**Issue by jabarihunt** [facebook/fresco#961]
Is there a way to determine if a particular GIF is animated or not using Fresco?  I didn't see anything in the docs.

If not, this would be a nice enhancement.  Something like `isGifAnimated(Uri gifUri)` would be outstanding!

**Comment by plamenko** [comment]
Yeah, [GifFormatChecker.isAnimated] (https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/imagepipeline-base/src/main/java/com/facebook/imageformat/GifFormatChecker.java#L47).

It accepts an input stream instead of just Uri though.
