### ISSUE TITLE
Contributing a substantial size feature

### ISSUE THREAD

**Issue by rahulrj** [facebook/fresco#963]
Hi.

Is there anything planned for the next release of Fresco,a big module like "Tap to Download", "Support for WebP encoding functions", "Support for .ico format" that i can work upon and raise a PR. 
I wanted to work upon of something substantial size in Fresco, but dont have the idea of which one to pick. (So that its not discarded)
May be the authors can guide towards one of the features that they have planned in next release. @tyronen 

Github doesn't provide a platform for these discussions, so asking here.

**Comment by plamenko** [comment]
Thank you for your interest. Let us see if there is something that would be suitable and we'll respond here.

**Comment by rahulrj** [comment]
Thanks @plamenko . I will be waiting.

**Comment by balazsbalazs** [comment]
Hey @rahulrj, I'm very happy that you want to contribute to Fresco!

Here are a few things that are popular feature requests and would be a good match:
#480 , #807, #655, #941, #480, #868, #921

Starting with something simpler would be an easier way to get familiar with the codebase.

Let us know if you need any help with any of these.

**Comment by tyronen** [comment]
Closing this issue, but please get in touch with us if you need help.
