### ISSUE TITLE
Animating the progressBarImage

### ISSUE THREAD

**Issue by jshvarts** [facebook/fresco#969]
Hi all,

Not sure if this is possible (I have not found any examples). I have fresco drawee view defined in XML. It includes progressBarImage. 

What I am trying to do is automate that progress bar image (make it spin). Would I create a custom progress bar as shown here? http://frescolib.org/docs/progress-bars.html#_  and override onLevelChange(int) and do the animation there? 

Thanks for any help!
James

**Comment by massimocarli** [comment]
Yes. Please follow that guide.
