### ISSUE TITLE
setImageURI(Uri.parse("content://com.android.contacts/contacts/42/photo")); not open

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#97]
uses-permission android:name="android.permission.READ_CONTACTS"

why not open TT gilde library runs very well

**Comment by raymoondtang** [comment]
Seems to be an issue with how LocalContentUriFetchProducer get the input stream from Uri.
A workaround is to remove '/photo'  at the end of URI, it will load.

**Comment by chonamdoo** [comment]
thank you TT running

2015-04-08 1:19 GMT+09:00 raymoondtang <notifications@github.com>:
