### ISSUE TITLE
Memory leak in  Fresco.initialize(this)

### ISSUE THREAD

**Issue by hiai** [facebook/fresco#977]
In Fresco.initialize(this) will Initializes SimpleDraweeView,In SimpleDraweeView,there has a  static variable sDraweeControllerBuilderSupplier，and sDraweeControllerBuilderSupplier hold a variable mContext,finally leaks my activity instance.

**Comment by massimocarli** [comment]
We'll investigate more but you could also initialize Fresco on an ApplicationContext.

Thanks

**Comment by votagus** [comment]
Initialize Fresco with the application context does not resolve the problem, according to LeakCanary.
In com.artico.delivery.pedidos:2.0:25.
* com.cibersons.monchis.fragments.FranchisesFragment has leaked:
* GC ROOT static com.facebook.drawee.backends.pipeline.Fresco.sDraweeControllerBuilderSupplier
* references com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.mContext
* references com.cibersons.monchis.activities.MainActivity.adapter
* references com.cibersons.monchis.adapter.TabAdapter.mCurrentPrimaryItem
* references com.cibersons.monchis.fragments.MainFragment.mChildFragmentManager
* references android.support.v4.app.FragmentManagerImpl.mCreatedMenus
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references com.cibersons.monchis.fragments.CategoriaFragment.tabAdapter
* references com.cibersons.monchis.adapter.TabAdapter.mFragments
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* leaks com.cibersons.monchis.fragments.FranchisesFragment instance

* Reference Key: 369d383f-503a-40d4-9a95-26b8379fe4f0
* Device: samsung samsung SM-G355M kanas3gub
* Android Version: 4.4.2 API: 19 LeakCanary: 1.3.1
* Durations: watch=5062ms, gc=211ms, heap dump=1588ms, analysis=43497ms

* Details:
* Class com.facebook.drawee.backends.pipeline.Fresco
|   static $staticOverhead = byte[] [id=0x41c79681;length=24;size=40]
|   static sDraweeControllerBuilderSupplier = com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier [id=0x4210b3e0]
* Instance of com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier
|   mBoundControllerListeners = null
|   mContext = com.cibersons.monchis.activities.MainActivity [id=0x41ade3a0]
|   mImagePipeline = com.facebook.imagepipeline.core.ImagePipeline [id=0x4210b400]
|   mPipelineDraweeControllerFactory = com.facebook.drawee.backends.pipeline.PipelineDraweeControllerFactory [id=0x4210c9c8]
* Instance of com.cibersons.monchis.activities.MainActivity
|   static $staticOverhead = byte[] [id=0x41aa9401;length=216;size=232]
|   static CASH = 1
|   static DELIVERY = 1
|   static INVOICE_NOT_REQUIRED = 0
|   static INVOICE_REQUIRED = 1
|   static NOT_PRESSED = java.lang.String [id=0x4167ffd0]
|   static PICKUP = 2
|   static POS = 2
|   static PRESSED = java.lang.String [id=0x417719a0]
|   static TAG = java.lang.String [id=0x41c94a50]
|   accountType = java.lang.String [id=0x41ef8178]
|   adapter = com.cibersons.monchis.adapter.TabAdapter [id=0x41b193d0]
|   addresses = com.cibersons.monchis.beans.Address[] [id=0x42203c80;length=3]
|   addressesAdapter = com.cibersons.monchis.activities.MainActivity$AddressesAdapter [id=0x42203ca0]
|   btnPedir = android.support.v7.widget.AppCompatButton [id=0x41db6ab0]
|   buttonAddAddress = android.support.v7.widget.AppCompatButton [id=0x41f15628]
|   cart = com.cibersons.monchis.beans.Cart [id=0x4229aaa0]
|   viewPager = android.support.v4.view.ViewPager [id=0x41d5b448]
|   density = java.lang.Float [id=0x41b32f00]
|   gestureDestector = android.support.v4.view.GestureDetectorCompat [id=0x41bfe458]
|   imageResId = int[] [id=0x41c8d710;length=5;size=32]
|   ivImageProfile = com.facebook.drawee.view.SimpleDraweeView [id=0x41aa27a0]
|   llCartItems = android.widget.LinearLayout [id=0x41d542b8]
|   llTotal = android.widget.LinearLayout [id=0x41f861f0]
|   user = null
|   mDrawerLayout = android.support.v4.widget.DrawerLayout [id=0x41af0980]
|   mLayoutManager = android.support.v7.widget.LinearLayoutManager [id=0x41d36588]
|   mainFragment = null
|   menu = android.support.v7.view.menu.MenuBuilder [id=0x4217de80]
|   navigationViewLeft = android.support.design.widget.NavigationView [id=0x41c04768]
|   orderList = java.util.ArrayList [id=0x41d36570]
|   orders = java.util.ArrayList [id=0x4229b258]
|   tv_account_type = android.support.v7.widget.AppCompatTextView [id=0x41beb440]
|   progressBar = android.widget.ProgressBar [id=0x41c968f8]
|   recyclerViewAddresses = android.support.v7.widget.RecyclerView [id=0x41d7a988]
|   relativeLayoutAbout = android.widget.RelativeLayout [id=0x41b21008]
|   relativeLayoutAddresses = android.widget.RelativeLayout [id=0x41f50ed0]
|   relativeLayoutAddressesContainer = android.widget.RelativeLayout [id=0x41ee6ec8]
|   relativeLayoutExit = android.widget.RelativeLayout [id=0x41c67620]
|   relativeLayoutHelp = android.widget.RelativeLayout [id=0x41f68020]
|   relativeLayoutProfile = android.widget.RelativeLayout [id=0x41ba1e88]
|   result = com.cibersons.monchis.beans.Orders [id=0x421f5270]
|   rvHistorial = android.support.v7.widget.RecyclerView [id=0x41f000b0]
|   tabLayout = android.support.design.widget.TabLayout [id=0x41d40398]
|   toolbar = android.support.v7.widget.Toolbar [id=0x41acb9f0]
|   tvUsername = android.support.v7.widget.AppCompatTextView [id=0x41b82298]
|   tvCarritoCount = android.support.v7.widget.AppCompatTextView [id=0x41cca5e0]
|   tvCount = android.support.v7.widget.AppCompatTextView [id=0x41d1a640]
|   tvHistorialCompleto = android.support.v7.widget.AppCompatTextView [id=0x41ab7d98]
|   tvTotalCartCost = android.support.v7.widget.AppCompatTextView [id=0x41bb0f40]
|   tvTuhistorialCount = android.support.v7.widget.AppCompatTextView [id=0x41bdcc30]
|   totalItemCount = 0
|   pastVisiblesItems = 0
|   loading = false
|   countOrders = 3
|   visibleItemCount = 0
|   mDelegate = android.support.v7.app.AppCompatDelegateImplV14 [id=0x41f54618]
|   mMediaController = null
|   mFragments = android.support.v4.app.FragmentController [id=0x41c9ffb0]
|   mHandler = android.support.v4.app.FragmentActivity$1 [id=0x41c8d8f0]
|   mCreated = true
|   mOptionsMenuInvalidated = false
|   mReallyStopped = false
|   mRequestedPermissionsFromFragment = false
|   mResumed = true
|   mRetaining = false
|   mStopped = false
|   mActionBar = null
|   mActivityInfo = android.content.pm.ActivityInfo [id=0x41f3b2f0]
|   mAllLoaderManagers = android.util.ArrayMap [id=0x4209d450]
|   mApplication = com.cibersons.monchis.MonchisApp [id=0x41a9f1a0]
|   mWindowManager = android.view.WindowManagerImpl [id=0x41c88e50]
|   mWindow = com.android.internal.policy.impl.PhoneWindow [id=0x41aa64e8]
|   mUiThread = java.lang.Thread [id=0x41679d08]
|   mTranslucentCallback = null
|   mComponent = android.content.ComponentName [id=0x41c4e810]
|   mToken = android.os.BinderProxy [id=0x41c4e908]
|   mContainer = android.app.Activity$1 [id=0x41c9f830]
|   mCurrentConfig = android.content.res.Configuration [id=0x41e75498]
|   mDecor = com.android.internal.policy.impl.PhoneWindow$DecorView [id=0x41b92810]
|   mTitle = java.lang.String [id=0x41aee518]
|   mDefaultKeySsb = null
|   mSearchManager = android.app.SearchManager [id=0x421a7cf0]
|   mResultData = null
|   mEmbeddedID = null
|   mParent = null
|   mMenuInflater = null
|   mManagedDialogs = null
|   mFragments = android.app.FragmentManagerImpl [id=0x41effe28]
|   mHandler = android.os.Handler [id=0x41c8f130]
|   mManagedCursors = java.util.ArrayList [id=0x41c91168]
|   mInstanceTracker = android.os.StrictMode$InstanceTracker [id=0x41c949c8]
|   mInstrumentation = android.app.Instrumentation [id=0x41a9dee8]
|   mIntent = android.content.Intent [id=0x41b4e1d8]
|   mLastNonConfigurationInstances = null
|   mLoaderManager = null
|   mMainThread = android.app.ActivityThread [id=0x41a98748]
|   mLoadersStarted = true
|   mIdent = 1122750208
|   mFlipfont = 0
|   mFinished = false
|   mEnableDefaultActionBarUp = false
|   mResultCode = 0
|   mDoReportFullyDrawn = false
|   mResumed = true
|   mDestroyed = false
|   mStartedActivity = false
|   mStopped = false
|   mTemporaryPause = false
|   mDefaultKeyMode = 0
|   mTitleColor = 0
|   mTitleReady = true
|   mConfigChangeFlags = 0
|   mCheckedForLoaderManager = true
|   mChangingConfigurations = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mChangeCanvasToTranslucent = false
|   mWindowAdded = true
|   mCalled = true
|   mBase = android.app.ContextImpl [id=0x41f36320]
|   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater [id=0x41c896e8]
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources [id=0x41a9ceb8]
|   mTheme = android.content.res.Resources$Theme [id=0x41c88e68]
|   mThemeResource = 2131493021
|   mBase = android.app.ContextImpl [id=0x41f36320]
* Instance of com.cibersons.monchis.adapter.TabAdapter
|   mFragmentTitles = java.util.ArrayList [id=0x41b194e0]
|   mFragments = java.util.ArrayList [id=0x41b194c8]
|   registeredFragments = android.util.SparseArray [id=0x41b194f8]
|   resources = android.content.res.Resources [id=0x41a9ceb8]
|   mCurTransaction = null
|   mCurrentPrimaryItem = com.cibersons.monchis.fragments.MainFragment [id=0x41b1a6b8]
|   mFragmentManager = android.support.v4.app.FragmentManagerImpl [id=0x41d96870]
|   mFragments = java.util.ArrayList [id=0x41b194b0]
|   mSavedState = java.util.ArrayList [id=0x41b19498]
|   mObservable = android.database.DataSetObservable [id=0x41ca9a48]
* Instance of com.cibersons.monchis.fragments.MainFragment
|   static $staticOverhead = byte[] [id=0x41b197d1;length=48;size=64]
|   static $assertionsDisabled = true
|   static backStackChangedListener = null
|   density = java.lang.Float [id=0x41d82d58]
|   displaymetrics = android.util.DisplayMetrics [id=0x41a9d310]
|   mDemoSlider = com.daimajia.slider.library.SliderLayout [id=0x420dd490]
|   responseBean = java.lang.String [id=0x426e0768]
|   rvRecomendados = android.support.v7.widget.RecyclerView [id=0x42104c50]
|   progressBar = android.widget.ProgressBar [id=0x41c968f8]
|   mWho = java.lang.String [id=0x420d1ac0]
|   mAllowEnterTransitionOverlap = null
|   mAllowReturnTransitionOverlap = null
|   mAnimatingAway = null
|   mArguments = android.os.Bundle [id=0x41b1a7a8]
|   mView = android.widget.RelativeLayout [id=0x420d5cc8]
|   mTarget = null
|   mTag = null
|   mChildFragmentManager = android.support.v4.app.FragmentManagerImpl [id=0x420d0e40]
|   mContainer = android.support.v4.view.ViewPager [id=0x41d5b448]
|   mSharedElementReturnTransition = java.lang.Object [id=0x41cae4d0]
|   mSharedElementEnterTransition = null
|   mSavedViewState = null
|   mEnterTransition = null
|   mEnterTransitionCallback = null
|   mExitTransition = null
|   mExitTransitionCallback = null
|   mSavedFragmentState = null
|   mFragmentManager = android.support.v4.app.FragmentManagerImpl [id=0x41d96870]
|   mReturnTransition = java.lang.Object [id=0x41cae4d0]
|   mReenterTransition = java.lang.Object [id=0x41cae4d0]
|   mParentFragment = null
|   mHost = android.support.v4.app.FragmentActivity$HostCallbacks [id=0x41c8d878]
|   mLoaderManager = null
|   mInnerView = android.widget.RelativeLayout [id=0x420d5cc8]
|   mIndex = 0
|   mInLayout = false
|   mLoadersStarted = true
|   mMenuVisible = true
|   mNextAnim = 0
|   mHidden = false
|   mHasMenu = true
|   mRemoving = false
|   mRestored = false
|   mResumed = true
|   mRetainInstance = false
|   mRetaining = false
|   mFromLayout = false
|   mFragmentId = 2131755522
|   mDetached = false
|   mDeferStart = false
|   mContainerId = 2131755522
|   mState = 5
|   mStateAfterAnimating = 0
|   mCheckedForLoaderManager = true
|   mCalled = true
|   mTargetIndex = -1
|   mTargetRequestCode = 0
|   mUserVisibleHint = true
|   mBackStackNesting = 0
|   mAdded = true
* Instance of android.support.v4.app.FragmentManagerImpl
|   static $staticOverhead = byte[] [id=0x41d0d9d9;length=456;size=472]
|   static ACCELERATE_CUBIC = android.view.animation.AccelerateInterpolator [id=0x41d10ed8]
|   static ACCELERATE_QUINT = android.view.animation.AccelerateInterpolator [id=0x41d10e70]
|   static ANIM_DUR = 220
|   static ANIM_STYLE_CLOSE_ENTER = 3
|   static ANIM_STYLE_CLOSE_EXIT = 4
|   static ANIM_STYLE_FADE_ENTER = 5
|   static ANIM_STYLE_FADE_EXIT = 6
|   static ANIM_STYLE_OPEN_ENTER = 1
|   static ANIM_STYLE_OPEN_EXIT = 2
|   static DEBUG = false
|   static DECELERATE_CUBIC = android.view.animation.DecelerateInterpolator [id=0x41d10db0]
|   static DECELERATE_QUINT = android.view.animation.DecelerateInterpolator [id=0x41d10d40]
|   static HONEYCOMB = true
|   static TAG = java.lang.String [id=0x4174de78]
|   static TARGET_REQUEST_CODE_STATE_TAG = java.lang.String [id=0x417f69e8]
|   static TARGET_STATE_TAG = java.lang.String [id=0x417f6a50]
|   static USER_VISIBLE_HINT_TAG = java.lang.String [id=0x417f6ab0]
|   static VIEW_STATE_TAG = java.lang.String [id=0x417f6b18]
|   static sAnimationListenerField = java.lang.reflect.Field [id=0x42160770]
|   mActive = java.util.ArrayList [id=0x42219e08]
|   mAdded = java.util.ArrayList [id=0x4221c538]
|   mAvailBackStackIndices = null
|   mAvailIndices = null
|   mBackStack = java.util.ArrayList [id=0x41cdd8f8]
|   mBackStackChangeListeners = java.util.ArrayList [id=0x420d16f0]
|   mBackStackIndices = java.util.ArrayList [id=0x42229148]
|   mContainer = android.support.v4.app.Fragment$1 [id=0x41d879e0]
|   mController = null
|   mCreatedMenus = java.util.ArrayList [id=0x41c52b50]
|   mTmpActions = java.lang.Runnable[] [id=0x422272b0;length=1]
|   mStateBundle = null
|   mExecCommit = android.support.v4.app.FragmentManagerImpl$1 [id=0x41d96848]
|   mStateArray = null
|   mPendingActions = java.util.ArrayList [id=0x42228340]
|   mHost = android.support.v4.app.FragmentActivity$HostCallbacks [id=0x41c8d878]
|   mParent = com.cibersons.monchis.fragments.MainFragment [id=0x41b1a6b8]
|   mNoTransactionsBecause = null
|   mNeedMenuInvalidate = false
|   mHavePendingDeferredStart = false
|   mExecutingActions = false
|   mDestroyed = false
|   mStateSaved = false
|   mCurState = 5
* Instance of java.util.ArrayList
|   static $staticOverhead = byte[] [id=0x41678911;length=48;size=64]
|   static MIN_CAPACITY_INCREMENT = 12
|   static serialVersionUID = 8683452581122892189
|   array = java.lang.Object[] [id=0x41f4acd8;length=12]
|   size = 1
|   modCount = 1
* Array of java.lang.Object[]
|   [0] = com.cibersons.monchis.fragments.CategoriaFragment [id=0x41ab5c30]
|   [1] = null
|   [2] = null
|   [3] = null
|   [4] = null
|   [5] = null
|   [6] = null
|   [7] = null
|   [8] = null
|   [9] = null
|   [10] = null
|   [11] = null
* Instance of com.cibersons.monchis.fragments.CategoriaFragment
|   static $staticOverhead = byte[] [id=0x4284b989;length=72;size=88]
|   static CATEGORY = java.lang.String [id=0x421a0718]
|   static CATEGORY_ID = java.lang.String [id=0x421a15e0]
|   static CATEGORY_NAME = java.lang.String [id=0x421a2fd8]
|   categories = java.util.ArrayList [id=0x41f01ac8]
|   category = java.lang.String [id=0x426e0768]
|   categoryId = java.lang.String [id=0x4180ace0]
|   categoryName = java.lang.String [id=0x42700160]
|   tabLayout = android.support.design.widget.TabLayout [id=0x41b79a70]
|   pager = android.support.v4.view.ViewPager [id=0x41d7da88]
|   tabAdapter = com.cibersons.monchis.adapter.TabAdapter [id=0x41d87640]
|   currentItem = 0
|   progressBar = android.widget.ProgressBar [id=0x41c968f8]
|   mWho = java.lang.String [id=0x42196408]
|   mAllowEnterTransitionOverlap = null
|   mAllowReturnTransitionOverlap = null
|   mAnimatingAway = null
|   mArguments = android.os.Bundle [id=0x4217e080]
|   mView = android.widget.FrameLayout [id=0x41b00998]
|   mTarget = null
|   mTag = java.lang.String [id=0x421ab2f0]
|   mChildFragmentManager = android.support.v4.app.FragmentManagerImpl [id=0x4284fa38]
|   mContainer = android.widget.RelativeLayout [id=0x420d5cc8]
|   mSharedElementReturnTransition = java.lang.Object [id=0x41cae4d0]
|   mSharedElementEnterTransition = null
|   mSavedViewState = null
|   mEnterTransition = null
|   mEnterTransitionCallback = null
|   mExitTransition = null
|   mExitTransitionCallback = null
|   mSavedFragmentState = null
|   mFragmentManager = android.support.v4.app.FragmentManagerImpl [id=0x420d0e40]
|   mReturnTransition = java.lang.Object [id=0x41cae4d0]
|   mReenterTransition = java.lang.Object [id=0x41cae4d0]
|   mParentFragment = com.cibersons.monchis.fragments.MainFragment [id=0x41b1a6b8]
|   mHost = android.support.v4.app.FragmentActivity$HostCallbacks [id=0x41c8d878]
|   mLoaderManager = null
|   mInnerView = android.widget.FrameLayout [id=0x41b00998]
|   mIndex = 0
|   mInLayout = false
|   mLoadersStarted = true
|   mMenuVisible = true
|   mNextAnim = 0
|   mHidden = false
|   mHasMenu = true
|   mRemoving = false
|   mRestored = false
|   mResumed = true
|   mRetainInstance = false
|   mRetaining = false
|   mFromLayout = false
|   mFragmentId = 2131755432
|   mDetached = false
|   mDeferStart = false
|   mContainerId = 2131755432
|   mState = 5
|   mStateAfterAnimating = 0
|   mCheckedForLoaderManager = true
|   mCalled = true
|   mTargetIndex = -1
|   mTargetRequestCode = 0
|   mUserVisibleHint = true
|   mBackStackNesting = 1
|   mAdded = true
* Instance of com.cibersons.monchis.adapter.TabAdapter
|   mFragmentTitles = java.util.ArrayList [id=0x41d48b00]
|   mFragments = java.util.ArrayList [id=0x41d48bd0]
|   registeredFragments = android.util.SparseArray [id=0x41d875b8]
|   resources = android.content.res.Resources [id=0x41a9ceb8]
|   mCurTransaction = null
|   mCurrentPrimaryItem = com.cibersons.monchis.fragments.FranchisesFragment [id=0x427fe2c0]
|   mFragmentManager = android.support.v4.app.FragmentManagerImpl [id=0x4284fa38]
|   mFragments = java.util.ArrayList [id=0x41d4e720]
|   mSavedState = java.util.ArrayList [id=0x41d4f1a0]
|   mObservable = android.database.DataSetObservable [id=0x41f4e4a8]
* Instance of java.util.ArrayList
|   static $staticOverhead = byte[] [id=0x41678911;length=48;size=64]
|   static MIN_CAPACITY_INCREMENT = 12
|   static serialVersionUID = 8683452581122892189
|   array = java.lang.Object[] [id=0x420fc1f0;length=12]
|   size = 10
|   modCount = 10
* Array of java.lang.Object[]
|   [0] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x42849f00]
|   [1] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x428061c0]
|   [2] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x42802868]
|   [3] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x427fe2c0]
|   [4] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x426fb618]
|   [5] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x426fb3e8]
|   [6] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x426faae8]
|   [7] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x426f9a28]
|   [8] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x426f97f8]
|   [9] = com.cibersons.monchis.fragments.FranchisesFragment [id=0x426f8ea0]
|   [10] = null
|   [11] = null
* Instance of com.cibersons.monchis.fragments.FranchisesFragment
|   static $staticOverhead = byte[] [id=0x4283d061;length=48;size=64]
|   static CATEGORY_ID = java.lang.String [id=0x421a15e0]
|   static CATEGORY_NAME = java.lang.String [id=0x421a2fd8]
|   categoryId = java.lang.Integer [id=0x4167eaa0]
|   categoryName = java.lang.String [id=0x41f2b550]
|   swipeRefresh = android.support.v4.widget.SwipeRefreshLayout [id=0x422c6330]
|   placeHolderContainer = android.widget.LinearLayout [id=0x41c75cf0]
|   progressBar = android.widget.ProgressBar [id=0x41c968f8]
|   recyclerViewFranchises = android.support.v7.widget.RecyclerView [id=0x41c24d78]
|   dayOfTheWeek = 4
|   progressBar = android.widget.ProgressBar [id=0x41c968f8]
|   mWho = null
|   mAllowEnterTransitionOverlap = null
|   mAllowReturnTransitionOverlap = null
|   mAnimatingAway = null
|   mArguments = android.os.Bundle [id=0x41e5e4f8]
|   mView = null
|   mTarget = null
|   mTag = null
|   mChildFragmentManager = null
|   mContainer = null
|   mSharedElementReturnTransition = java.lang.Object [id=0x41cae4d0]
|   mSharedElementEnterTransition = null
|   mSavedViewState = android.util.SparseArray [id=0x420a02c8]
|   mEnterTransition = null
|   mEnterTransitionCallback = null
|   mExitTransition = null
|   mExitTransitionCallback = null
|   mSavedFragmentState = null
|   mFragmentManager = null
|   mReturnTransition = java.lang.Object [id=0x41cae4d0]
|   mReenterTransition = java.lang.Object [id=0x41cae4d0]
|   mParentFragment = com.cibersons.monchis.fragments.CategoriaFragment [id=0x41ab5c30]
|   mHost = null
|   mLoaderManager = null
|   mInnerView = null
|   mIndex = -1
|   mInLayout = false
|   mLoadersStarted = false
|   mMenuVisible = false
|   mNextAnim = 0
|   mHidden = false
|   mHasMenu = false
|   mRemoving = false
|   mRestored = false
|   mResumed = false
|   mRetainInstance = false
|   mRetaining = false
|   mFromLayout = false
|   mFragmentId = 0
|   mDetached = false
|   mDeferStart = false
|   mContainerId = 0
|   mState = 0
|   mStateAfterAnimating = 0
|   mCheckedForLoaderManager = false
|   mCalled = true
|   mTargetIndex = -1
|   mTargetRequestCode = 0
|   mUserVisibleHint = false
|   mBackStackNesting = 0
|   mAdded = false

**Comment by plamenko** [comment]
Can you provide the code snippet that initializes the Fresco? In what class exactly are you calling `Fresco.initialize` ?

**Comment by votagus** [comment]
Hi  @plamenko, here is the issue. #1101

**Comment by massimocarli** [comment]
Hi @votagus 
we're now explicitly calling Context.getApplicationContext() [here](https://github.com/facebook/fresco/blob/c83333404edfd9e7d87183e4bedafbd6f34a99c6/drawee-backends/drawee-pipeline/src/main/java/com/facebook/drawee/backends/pipeline/Fresco.java#L63).

This should be ok now.
Thanks

**Comment by votagus** [comment]
Great! Thanks!
