### ISSUE TITLE
Constant increasing amount of threads during unit test execution

### ISSUE THREAD

**Issue by budnyjj** [facebook/fresco#978]
Hello all,
I've spotted a big amount of waiting threads (about NumTests*3), created by Fresco library during unit test execution (with Robolectric 3.0):
![fresco_wait](https://cloud.githubusercontent.com/assets/1331682/12853064/10d4c09a-cc43-11e5-8dbc-e32265b9165b.png)

Here is related thread dump:
[fresco_wait_dump.txt](https://github.com/facebook/fresco/files/119530/fresco_wait_dump.txt)

I've added basic unit test to samples/demo to show this issue:
https://github.com/budnyjj/fresco

**Comment by massimocarli** [comment]
Hi @budnyjj, 
thanks for the interesting note. We're executing our test using RobolectricTestRunner. If you want to provide an optimized way we'll be happy to receive your pull request.
Thanks

**Comment by budnyjj** [comment]
Do you mean that this issue can be caused by using non-default test runner? I had to implement it,  because the default test runner wasn't able to locate Manifest.xml while using splits..

**Comment by budnyjj** [comment]
@massimocarli, unfortunatelly, RobolectricTestRunner doesn't pick resources while using Android Studio:
https://github.com/robolectric/robolectric/issues/1592

**Comment by erikandre** [comment]
Closing since this issue is not prioritized to be implemented in the foreseeable future.
If this is a feature that you need, please consider contributing a pull request to Fresco!
