### ISSUE TITLE
Deadlock during unit test execution

### ISSUE THREAD

**Issue by budnyjj** [facebook/fresco#979]
HI all, 
I've spotted deadlock during execution of unit tests (with Robolectric 3):
![fresco_deadlock](https://cloud.githubusercontent.com/assets/1331682/12853280/550a67d2-cc44-11e5-89e3-9ddc18c793fc.png)

It happens when at least two views download images at the same time.

Here is associated thread dump:
[fresco_deadlock_dump.txt](https://github.com/facebook/fresco/files/119540/fresco_deadlock_dump.txt)

To reproduce this issue, please uncomment any additional setImageUri invocation in  https://github.com/budnyjj/fresco/blob/master/samples/demo/src/main/java/com/facebook/samples/demo/MainActivity.java and run unit tests.

**Comment by massimocarli** [comment]
Hi @budnyjj, 
as in the previous issue, thanks for the interesting note. We'll be happy to receive your pull request in order to fix this. 
Thanks

**Comment by erikandre** [comment]
Closing due to lack of updates or further reports of the issue
