### ISSUE TITLE
Error:Execution failed for task ':imagepipeline:cloneWebp'

### ISSUE THREAD

**Issue by treeseedm** [facebook/fresco#98]
Error:Execution failed for task ':imagepipeline:cloneWebp'.
> org.eclipse.jgit.api.errors.TransportException: https://chromium.googlesource.com/webm/libwebp: cannot open git-upload-pack

**Comment by arlong** [comment]
I have a same problem!

**Comment by honghuiqing326** [comment]
I also have the same problem

**Comment by michalgr** [comment]
Can you try once again ? We depend on libwebp and we clone source from google's repo. The issue you describe could be caused by some temporary factors (quota ? temporary outage ?). I'll provide workaround if the issue does not disappear.

**Comment by treeseedm** [comment]
好了

**Comment by arlong** [comment]
@treeseedm How to solved?

**Comment by treeseedm** [comment]
@arlong 
fix it like this:
task cloneWebp(type: GitCloneTask) {
    dir = file("${downloads}/libwebp-0.4.2")
    uri = 'https://github.com/webmproject/libwebp/'
    treeish = 'v0.4.2'
    outputs.dir dir
}
change uri

**Comment by ljnalex** [comment]
@treeseedm It works,thanks!
