### ISSUE TITLE
SimpleDraweeView flickers if set to the same uri multiple times

### ISSUE THREAD

**Issue by nallwhy** [facebook/fresco#981]
I want to get the uri which a SimpleDraweeView has to determine to call setImageURI or not again.
When I call setImageURI with the same uri multiple times, SimpleDraweeView flickers each time.
So, I want to call setImageURI when the uri is changed.
Can I get the uri already been set to the SimpleDraweeView? or is there an other way to solve this problem?
and Can I remove uri from the SimpleDraweeView?

Thanks.

**Comment by tyronen** [comment]
SDV doesn't itself do this, but you should be able to maintain a Map in your app to achieve the same effect.

To remove a URI, simply call 

 ``sdv.setController(null);``

**Comment by nallwhy** [comment]
Thanks! It works.
