### ISSUE TITLE
Native webp library not been removed when i using fresco 0.9.0

### ISSUE THREAD

**Issue by wstczlt** [facebook/fresco#987]
My project dependencies:
dependencies {
    compile project(':utility')
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.facebook.fresco:fresco:0.9.0'
    compile 'com.facebook.fresco:imagepipeline-okhttp:0.9.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'

}

The result apk file also contains native webp library:
Jesse$ unzip -v 0.9.0.apk |grep "lib/armeabi/"
   34648  Defl:N    19785  43%  02-14-16 15:28  e4e7705e  lib/armeabi/liblocSDK5.so
   13536  Defl:N     5682  58%  02-14-16 15:28  7f823f49  lib/armeabi/libbitmaps.so
   91744  Defl:N    46546  49%  02-14-16 15:28  961d4107  lib/armeabi/libgifimage.so
  210252  Defl:N   118758  44%  02-14-16 15:28  09191f51  lib/armeabi/libimagepipeline.so
   13584  Defl:N     5575  59%  02-14-16 15:28  ac98b3ad  lib/armeabi/libmemchunk.so
  177456  Defl:N    96488  46%  02-14-16 15:28  27b9997e  lib/armeabi/libwebp.so
   83552  Defl:N    41805  50%  02-14-16 15:28  2803046d  lib/armeabi/libwebpimage.so
   25840  Defl:N    12474  52%  02-14-16 15:28  bd43d793  lib/armeabi/libweibosdkcore.so
   25816  Defl:N    14213  45%  02-14-16 15:28  e2eb3984  lib/armeabi/libcocklogic.so
   17756  Defl:N     9141  49%  02-14-16 15:28  09e230cc  lib/armeabi/libsupervisor.so
  161360  Defl:N    77623  52%  02-14-16 15:28  fabaacc1  lib/armeabi/libtnet-2.0.17.2-agoo.so
   29816  Defl:N    15883  47%  02-14-16 15:28  24afd67f  lib/armeabi/libgif.so

I want to remove the webp dependence, is there any problems in my configuration?

**Comment by massimocarli** [comment]
Hi @wstczlt,
this is true. This is because the libwebp are still used by animated-webp. We're making the animated-webp and animated-gif also optional and so the libwebp will disappear from the main aar. Stay tuned!

Thanks
