### ISSUE TITLE
SimpleDraweeView not visible when used in a ViewPager

### ISSUE THREAD

**Issue by cybergen78** [facebook/fresco#988]
If used within view items in a ViewPager, sometimes the loaded image isn't shown. This behavior is allways reproducable with at least four items in the pager: Swipe left three times just to swipe right three times. Then swipe one time to the left - é voilà - the SimpleDraweeView stays empty.

The ViewPager Items are as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:app="http://schemas.android.com/apk/res-auto"
             android:layout_width="match_parent"
             android:layout_height="wrap_content">

    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/cellDesireImage_image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:viewAspectRatio="1.33333"
        app:placeholderImage="@drawable/empty_image"
        app:failureImage="@drawable/failure_image"
        app:placeholderImageScaleType="fitCenter"
        app:actualImageScaleType="fitCenter"
        app:progressBarImage="@drawable/image_progress"
        app:progressBarAutoRotateInterval="1000"
        app:progressBarImageScaleType="center"/>

</FrameLayout>
```

Leave a comment if you want to see my simple ImagePagerAdapter code.

**Comment by IanChilds** [comment]
Are you correctly reloading the image? Check the logcat (http://frescolib.org/docs/troubleshooting.html#setting-up-logcat) to see whether the image is being reloaded when it's required?

**Comment by cybergen78** [comment]
Everything seems fine from the logs perspective. This is the output for the three Views in the ViewPager (1 onscreen and 2 offscreen pages) after a reload. As you can see the previous three views are detached and three new views get attached and the images loaded. The first view that should be visible is not. I can see the image if I swipe the invisible image out of the offscreen page limit and back again.

`02-19 01:37:31.260 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 726f538 47: onDetach
02-19 01:37:31.261 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 722c54d 48: onDetach
02-19 01:37:31.261 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 2173350 49: onDetach
02-19 01:37:31.314 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 23015b2 null -> 50: initialize
02-19 01:37:31.314 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 23015b2 50: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@ec1a903
02-19 01:37:31.315 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 23015b2 50: onAttach: request needs submit
02-19 01:37:31.315 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709220: onRequestSubmit: {requestId: 48, callerContext: null, isPrefetch: false}
02-19 01:37:31.315 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709220: onProducerStart: {requestId: 48, producer: BitmapMemoryCacheGetProducer}
02-19 01:37:31.315 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709220: onProducerFinishWithSuccess: {requestId: 48, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=true}}
02-19 01:37:31.315 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709220: onRequestSuccess: {requestId: 48, elapsedTime: 0 ms}
02-19 01:37:31.316 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 23015b2 50: submitRequest: dataSource: 5461080
02-19 01:37:31.316 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 23015b2 50: set_final_result @ onNewResult: image: CloseableReference 3e55b56
02-19 01:37:31.318 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller adc36b9 null -> 51: initialize
02-19 01:37:31.318 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller adc36b9 51: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@485dafe
02-19 01:37:31.318 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller adc36b9 51: onAttach: request needs submit
02-19 01:37:31.319 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709223: onRequestSubmit: {requestId: 49, callerContext: null, isPrefetch: false}
02-19 01:37:31.319 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709223: onProducerStart: {requestId: 49, producer: BitmapMemoryCacheGetProducer}
02-19 01:37:31.319 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709223: onProducerFinishWithSuccess: {requestId: 49, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=true}}
02-19 01:37:31.319 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709224: onRequestSuccess: {requestId: 49, elapsedTime: 1 ms}
02-19 01:37:31.319 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller adc36b9 51: submitRequest: dataSource: 42bd25f
02-19 01:37:31.320 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller adc36b9 51: set_final_result @ onNewResult: image: CloseableReference 178a73
02-19 01:37:31.321 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 53bb4ac null -> 52: initialize
02-19 01:37:31.321 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 53bb4ac 52: setHierarchy: com.facebook.drawee.generic.GenericDraweeHierarchy@4808575
02-19 01:37:31.321 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 53bb4ac 52: onAttach: request needs submit
02-19 01:37:31.322 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709226: onRequestSubmit: {requestId: 50, callerContext: null, isPrefetch: false}
02-19 01:37:31.322 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709227: onProducerStart: {requestId: 50, producer: BitmapMemoryCacheGetProducer}
02-19 01:37:31.322 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709227: onProducerFinishWithSuccess: {requestId: 50, producer: BitmapMemoryCacheGetProducer, elapsedTime: 0 ms, extraMap: {cached_value_found=true}}
02-19 01:37:31.322 26695-26695/de.jarosz.desires V/unknown:RequestLoggingListener: time 278709227: onRequestSuccess: {requestId: 50, elapsedTime: 1 ms}
02-19 01:37:31.322 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 53bb4ac 52: submitRequest: dataSource: e0a90a
02-19 01:37:31.323 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 53bb4ac 52: set_final_result @ onNewResult: image: CloseableReference 261e2fd
02-19 01:37:31.329 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 2173350 49: release: image: CloseableReference 261e2fd
02-19 01:37:31.330 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 722c54d 48: release: image: CloseableReference 178a73
02-19 01:37:31.330 26695-26695/de.jarosz.desires V/unknown:AbstractDraweeController: controller 726f538 47: release: image: CloseableReference 3e55b56`

**Comment by cybergen78** [comment]
It was my implementation of the ViewPager itself. Sorry for bothering.

**Comment by IanChilds** [comment]
No problem.

**Comment by guodaping** [comment]
@cybergen78  I have the same issue,  I just used ViewPager in a fragment. could you share the solution.
