### ISSUE TITLE
galaxy note3 5.0 oom error

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#994]
02-16 19:38:27.819 17832-21258/com.couchgram.privacycall W/unknown:RequestLoggingListener: time 5581173: onProducerFinishWithFailure: {requestId: 23, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 100663296 Used size = 99532800 Free size = 0 Request size = 8294400}
02-16 19:38:27.819 17832-21258/com.couchgram.privacycall W/unknown:RequestLoggingListener: time 5581173: onRequestFailure: {requestId: 23, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 100663296 Used size = 99532800 Free size = 0 Request size = 8294400}
02-16 19:38:27.819 17832-21272/com.couchgram.privacycall W/unknown:RequestLoggingListener: time 5581175: onProducerFinishWithFailure: {requestId: 24, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 100663296 Used size = 99532800 Free size = 0 Request size = 8294400}
02-16 19:38:27.819 17832-21272/com.couchgram.privacycall W/unknown:RequestLoggingListener: time 5581175: onRequestFailure: {requestId: 24, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 100663296 Used size = 99532800 Free size = 0 Request size = 8294400}
02-16 19:38:27.819 17832-21274/com.couchgram.privacycall W/unknown:RequestLoggingListener: time 5581176: onProducerFinishWithFailure: {requestId: 25, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 100663296 Used size = 99532800 Free size = 0 Request size = 8294400}
02-16 19:38:27.819 17832-21274/com.couchgram.privacycall W/unknown:RequestLoggingListener: time 5581176: onRequestFailure: {requestId: 25, elapsedTime: -1 ms, throwable: com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 100663296 Used size = 99532800 Free size = 0 Request size = 8294400

**Comment by IanChilds** [comment]
You have to be careful with memory on Lollipop, as it is allocated on the java heap. Please see: http://frescolib.org/docs/troubleshooting.html#ooms-and-failing-to-allocate-a-bitmap
