### ISSUE TITLE
CacheStats return - 1 on app update

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#995]
Hello,

I don't know if it's the same as https://github.com/facebook/fresco/issues/984 .

When app is update (or suppressed and reinstalled): 
`mDiskCacheUsedSize = Fresco.getImagePipelineFactory().getMainDiskStorageCache().getSize();`
return -1 thus all files are in cache.

This has been tested using : 
`.setBaseDirectoryPath(getExternalCacheDir())`
or
`.setBaseDirectoryPath(context.getApplicationContext().getCacheDir())`
as diskCacheConfig

Thanks,

Eric

**Comment by IanChilds** [comment]
Looks like a duplicate.

**Comment by eldk** [comment]
Hello,

On app update or reinstallation, even if the cache folder is there, Fresco recreate it and seems to reset (or loose) CacheStats : 
>DefaultDiskStorageSupplier: Created cache directory /mnt/sdcard/Android/data/tld.domain.appname/cache/images

So I'm not sure it's the same as #984

**Comment by e-hai** [comment]
@eldk hello,Do you solved the problem yet,Thanks!

**Comment by eldk** [comment]
Hello,

Yes it's solved with this commit https://github.com/facebook/fresco/pull/1013 .

But hasn't been released since 2 month.

Another "big" bug on controlling diskcache size when using external cache  is waiting too :  https://github.com/facebook/fresco/issues/898

Is a check and released on Fresco's team plan ?

Thanks,

Eric

**Comment by e-hai** [comment]
@eldk thank you ！

**Comment by eldk** [comment]
@e-hai :`

Maybe this change in Fresco 0.10.0  (https://github.com/facebook/fresco/blob/v0.10.0/imagepipeline-base/src/main/java/com/facebook/cache/disk/DiskStorageCache.java):

` public synchronized long getSize() {
      return mSize;
    }`

` public synchronized long getCount() {
      return mCount;
    }`

Solve it.
I haven't tested yet.
