### ISSUE TITLE
Cannot load images were obtained through the photos when i using fresco 0.9.0  

### ISSUE THREAD

**Issue by pxfile** [facebook/fresco#997]
BUG cause: Xiaomi Phone application crashes, after a short while will automatically exit.
nubia Phone Picture is black.
Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
but can load images were obtained through the photos when i using fresco 0.6.1

**Comment by IanChilds** [comment]
Are you sure this is caused by Fresco? Can you give more details?
