### ISSUE TITLE
draweeview Rendering layer-list drawable problem

### ISSUE THREAD

**Issue by levianye** [facebook/fresco#998]
I meet such a question,I need use a layer-list drawable as PlaceholderImage or RetryImagebut I found the drawable is not rendering in one time ,It seems fresco rendering it one layer by one layer ，and I can see the rendering process，it is werid,so is any body meet this question?
## my drawable xml is below

<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" 

  <item 
        <shape android:shape="rectangle"
            <solid android:color="#f4f4f4"
            <size
                android:width="200dp"
                android:height="200dp"
            </size
        </shape
    </item
    <item 
        <bitmap android:src="@drawable/mt_default_normal" android:gravity="center"/
    </item

</layer-list

**Comment by levianye** [comment]
OK，let me explain it more clearly ,I found that the drawable fadeout or fadein not in the same step,the shape layer update Alpha value correctly，but the bitmap layer update alpha value not correctly,when I tap to retry it seems the placeholder drawable bitmap layer fadein right now while the shape layer fadein as the duration . It seems very werid.so I think the problem is int the FadeDrawable.java, maybe update alpha problem,can anyone help me to findout the problem?

**Comment by IanChilds** [comment]
Can you explain your hierarchy a bit more clearly please. In particular, which layer are you using the drawable you mentioned above for? I'm not clear what you mean by "shape layer"? 

If you could explain what you see, and what is in your hierarchy at each stage, that would be great.

**Comment by levianye** [comment]
@IanChilds the shape layer as the XML code show 
<item >
    <shape android:shape="rectangle">
        <solid android:color="#f4f4f4"/>
        <size
            android:width="200dp"
            android:height="200dp">
        </size>
    </shape>
</item>


it seems if a drawable is a layer-list drawable each layer fade in or fade out not sync

the hierarchy is below
 Drawable placeHolder = getResources().getDrawable(R.drawable.mt_default_kill_bg);//the drawable is a layer-list drawable ,there are two layer a shape layer and a bitmap layer in the center of layer

 Drawable retryImg = getResources().getDrawable(R.drawable.mt_default_kill_bg);
 Drawable failureImg = getResources().getDrawable(R.drawable.mt_icon_car_error);
GenericDraweeHierarchy dh = GenericDraweeHierarchyBuilder.newInstance(res)
                .setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER)
                .setPlaceholderImage(placeHolder , ScalingUtils.ScaleType.FIT_CENTER)
                .setRetryImage(retryImg, ScalingUtils.ScaleType.FIT_CENTER)
                .setFailureImage(failureImg, ScalingUtils.ScaleType.FIT_CENTER)
                .setFadeDuration(400)
                .build();

**Comment by IanChilds** [comment]
Sounds like a bug I would guess, though can't see how it would be happening.

**Comment by levianye** [comment]
yes it looks like a bug ,I wrote a custom drawable draw a rectangle and a bitmap like the layer-list drawable define in the XML ,It works fine ! so I think the Fadedrawable.java maybe there exists animation bug.

**Comment by erikandre** [comment]
Closing due to lack of updates and no further reported instances of this issue.
